### ISSUE TITLE
speed/memory opt: sqr(W.dimshuffle('x',0,1) * G.dimshuffle(0,'x',1)).sum(axis=(1,2)) -> T.dot(...)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1022]
The pylearn-dev mailing list email 

https://groups.google.com/d/msg/pylearn-dev/iY7swxgn-xI/N9ynRaZMFSIJ

tell that they manually added this optimization:

we want is an optimization that replaces
T.sqr( W.dimshuffle('x',0,1) * G.dimshuffle(0,'x',1) ).sum(axis=(1,2))
with
T.dot(T.sqr(G), T.sqr(W).sum(axis=0))

We should do an optimization that do it automatically. W and G are matrices. We can probably do a more general optimization that replace more cases.

**Comment by hantek** [comment]
Hi 

Is there any progresses on this issue? I come across this problem again, and I am wandering how hard the optimization would be, to see if I am able to make it.

Zhouhan

**Comment by nouiz** [comment]
It isn't hard to do this opt.

If you didn't do an opt, there is a tutorial in this git repo:

https://github.com/abergeron/ccw_tutorial_theano

The pdf: https://github.com/abergeron/ccw_tutorial_theano/blob/master/advanced.pdf have a section on optimization. I think this is the best doc we have for this. There is exercices for opt with the answer. Try them first, it should help you.

Having this done would be great. If you have questions, do not hesitate.

**Comment by hantek** [comment]
Hi Fred,

I'd appreciate it a lot if I can do that in the next CCW ticket.

Zhouhan

**Comment by nouiz** [comment]
done
