### ISSUE TITLE
Inserting DeepCopyOp for an output X even if its borrow is True if X is destroyed

### ISSUE THREAD

**Issue by pascanur** [Theano/Theano#1029]
Right now a ViewOp is inserted for any output that has borrow=True. This can cause problems if one output is destroyed by other. One should check if an output is destroyed by another or not.
Note that we should insert a view op if it is just a view (and not destroyed) of another output or input. 

The current code mixes together the view map and destroy map which makes hard to distinguish between the two cases. 

This should be done inside the call to theano.function()

When done, Scan can revert to use borrow=True as a speed up.

**Comment by abergeron** [comment]
Was done in a different way by @carriepl
