### ISSUE TITLE
Add remaining tutorial code snippets as unit tests

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#1050]
All code snippets used in doc/tutorial used to have a corresponding unit test in theano/tests/test_tutorial.py, with comments pointing to each other, so that if a change in Theano made an example break, or if the example got changed, both could be updated.

Some of the example code snippets in doc/tutorial/ do not have the corresponding test in theano/tests/test_tutorial.py, thus they silently broke (see https://groups.google.com/d/topic/theano-users/nC2l8e-WL3c/discussion).

All missing unit tests should be added, and the corresponding snippets updated if needed.

**Comment by mgermain** [comment]
Task updated in #5007
