### ISSUE TITLE
Gradients of logical operators fail

### ISSUE THREAD

**Issue by jsalvatier** [Theano/Theano#1055]
If you take the gradient of a logical operator it generates an error because of something involving a logical operator, it will fail because logical operators have a gradient of None. And the gradient property checks to see if the gradient is none (introduced here https://github.com/Theano/Theano/commit/e4d03049609fbe73b6ca5ceca5d537feeea88e22), though this still fails if the assertion check (last line of the commit) is removed. 

@goodfeli

Is the correct solution to make scalar.basic.BinaryBitOp.grad return zeros? That doesn't seem right to me. 

example program:
```

from theano.tensor import * 
from theano import * 

x = dvector('x')

lt0 = and_(lt(0, x), 1)
c = sum(x * lt0)
g = grad(c, x)
fn = function([x], g)

fn([13., 17., 1, 5])
```

**Comment by nouiz** [comment]
done
