### ISSUE TITLE
Implement missing linalg ops

### ISSUE THREAD

**Issue by abalkin** [Theano/Theano#1057]
The following operations from numpy.linalg are not implemented:
   
###   Linear algebra basics:
    
 - [x] norm            Vector or matrix norm. (Not done: 3d tensor and more.)
 - [x] lstsq           Solve linear least-squares problem
 - [x] pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition [implemented in ops, but not exposed in linalg]
 - [x] matrix_power    Integer power of a square matrix
    
###    Eigenvalues and decompositions:
    
 - [x] eig             Eigenvalues and vectors of a square matrix (DONE except grad)
 - [x] eigh            Eigenvalues and eigenvectors of a Hermitian matrix
 - [x] eigvals         Eigenvalues of a square matrix
 - [x] eigvalsh        Eigenvalues of a Hermitian matrix
 - [x] qr              QR decomposition of a matrix
 - [x] svd             Singular value decomposition of a matrix
    
###    Tensor operations:
    
 - [x] tensorsolve     Solve a linear tensor equation
 - [x] tensorinv       Calculate an inverse of a tensor

NumPy development version update:
- [x] norm now support keepdims parameter: https://github.com/numpy/numpy/pull/5196/files

**Comment by Azrael1** [comment]
@nouiz I want to work on this problem. Where should I start?

**Comment by nouiz** [comment]
start by finding the op you want to add. Then grep in theano and google about it to know if it was added in Theano or if done by someone else but done outside of Theano.

As a first contribution, the last one would be a good start:

norm now support keepdims parameter: https://github.com/numpy/numpy/pull/5196/files

mostly, add the keepdims param to theano norm method.

**Comment by Sentient07** [comment]
@nouiz , I would like to work on "tensorinv Calculate an inverse of a tensor". Is anyone else working on that ?

**Comment by nouiz** [comment]
It have been started at:

https://github.com/Theano/Theano/pull/1973/files

Do you want to finish it? It is probably close to be done, but we don't
have too much time to review this this week and next week. But if you feel
confortable with that part of theano, you can try it.

**Comment by Sentient07** [comment]
Sure. I'll fork that work and see what is yet to be done and would comment there if I have any questions. I'll try to finish this up by this weekend and will remind you 2 at the end of next week for reviewing. 
Thanks

**Comment by yobibyte** [comment]
I will take **tensorsolve**.

**Comment by iikulikov** [comment]
@Sentient07 , are you working on the **tensorinv** or not?

**Comment by yobibyte** [comment]
Added **tensorsolve** and created [PR](https://github.com/Theano/Theano/pull/4529).

**Comment by Sentient07** [comment]
@iikulikov , I'm not currently working on that. I've started my GSoC project and wasn't able to finish this before. You can take go ahead with this if you want.

**Comment by iikulikov** [comment]
@Sentient07 ,okay, thanks for the info, then I will work on **tensorinv**

**Comment by iikulikov** [comment]
Added tensorinv op with this [PR](https://github.com/Theano/Theano/pull/4546)

**Comment by nouiz** [comment]
tensorinv is now merged.

**Comment by abergeron** [comment]
Done
