### ISSUE TITLE
CudaNdarray_dealloc should not modify the Exception state

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#1062]
CudaNdarray_dealloc is currently used as the the tp_dealloc function in the C API, which is akin to the Python __del__ method.
The __del__ method should not raise exceptions (actually, if you declare an Exception in the __del__ method of a class, there is a compile-time warning saying it will be ignored). In the same way, the tp_dealloc function should not modify the Exception state, even undirectly.  When an Exception is raised during the execution of tp_dealloc during garbage collection, the interpreter crashes.
However, that's what CudaNdarray_dealloc is doing if the CudaNdarray_uninit method fails.

We could use PyErr_Fetch at the beginning, and PyErr_Restore at the end of the CudaNdarray_dealloc method. That would prevent those crashes during garbage collection, and preserve the error-raising mechanism if CudaNdarray_uninit is called outside of the garbage collection phase.

**Comment by nouiz** [comment]
IRL, @abergeron affirm the new back-end don't have this problem.
