### ISSUE TITLE
Theano detect max GPU used by subprocess

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1064]
It would be good that Theano could detect when a process import it, then call a subprocess that also import it. In most cast, this would make the 2 process lock a GPU if the GPU are in exclusive mode like on clusters.

The user could set the env variable THEANO_MAX_GPU=1, when we init the GPU, we lower it to 0. Then the sub process would inherit the 0 value and would raise an error.

This would prevent problem on Cluster

**Comment by gokul-uf** [comment]
@nouiz, this can be done by using the `os.environ` dictionary. The following code snippet should do the job
```
import os
if os.environ['THEANO_MAX_GPU'] == 0:
    raise MaxGPUError
else:
    os.environ['THEANO_MAX_GPU'] = 0
```

Where should I add these lines?
Also, now that we are working towards supporting multiple GPUS, doesn't having THEANO_MAX_GPU = no_of_GPUs make more sense than setting it to 1?

**Comment by gokul-uf** [comment]
@nouiz , I shall add it at the end of `__init__.py`

**Comment by nouiz** [comment]
I suppose that subprocess shouldn't use the GPU by default. So if the user don't set it, the default, then subprocess shouldn't make an error.

In fact, I think we should only raise an error if we init the GPU in the sub process. This is done in the method use() in the file theano/sandbox/cuda/__init__.py and init_dev() in theano/sandbox/gpuarray/__init__.py.

**Comment by abergeron** [comment]
This is a poor solution.  If you fork before importing Theano, then we can't setup the environment to notice that a gpu is already in use and if you fork after importing Theano, then you fork with a cuda context active which is most likely to lead to strange crashes and/or lockups.

So basically you would still have to be aware of your GPU use and be very careful about it.  So I don't think this is worth doing.
