### ISSUE TITLE
CreateArrayObj triggering infinite loop in cuda

### ISSUE THREAD

**Issue by jaberg** [Theano/Theano#1065]
The CudaNdarray_CreateArrayObj call in cuda_ndarray.so calls cublasGetVector to copy data from the device to the host, so that it can return a numpy ndarray.

Sometimes the memcpy in libcuda does not return, as can be verified by attaching gdb to the running process (using 100% CPU)

OS: debian-unstable
DRIVER: nvidia-vdpau-driver:am 304.60-1
CUDA: nvidia-cuda-toolkit    4.2.9-1

**Comment by nouiz** [comment]
No problems anymore related to that. So closing.
