### ISSUE TITLE
importing Theano fails due to scipy import error

### ISSUE THREAD

**Issue by fonnesbeck** [Theano/Theano#1144]
Importing the current master branch of Theano fails due to a Scipy import error. It looks like the location of `fblas` may have changed in Scipy? I can import `scipy.linalg.fblas` but not `scipy.linalg.blas.fblas`.

```
In [1]: import theano
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-3397704bd624> in <module>()
----> 1 import theano

/Users/fonnescj/Code/Theano/theano/__init__.pyc in <module>()
     74 from misc.safe_asarray import _asarray
     75 
---> 76 import theano.tests
     77 if hasattr(theano.tests, "TheanoNoseTester"):
     78     test = theano.tests.TheanoNoseTester().test

/Users/fonnescj/Code/Theano/theano/tests/__init__.py in <module>()
      4 except ImportError:
      5     pass
----> 6 import unittest_tools

/Users/fonnescj/Code/Theano/theano/tests/unittest_tools.py in <module>()
      6 
      7 import theano
----> 8 import theano.tensor as T
      9 from theano.configparser import config, AddConfigVar, StrParam
     10 from theano.gof.python25 import any

/Users/fonnescj/Code/Theano/theano/tensor/__init__.py in <module>()
      8 import opt
      9 import opt_uncanonicalize
---> 10 import blas
     11 import blas_scipy
     12 import blas_c

/Users/fonnescj/Code/Theano/theano/tensor/blas.py in <module>()
    153     _have_fblas = True
    154     _blas_gemv_fns = {
--> 155             numpy.dtype('float32'): scipy.linalg.blas.fblas.sgemv,
    156             numpy.dtype('float64'): scipy.linalg.blas.fblas.dgemv,
    157             numpy.dtype('complex64'): scipy.linalg.blas.fblas.cgemv,

AttributeError: 'module' object has no attribute 'fblas'
```

**Comment by ibrahim-amer** [comment]
Do anyone tried this solution and worked with him ?

**Comment by nouiz** [comment]
This was due to newer version of scipy that removed something we used. Can
you update Theano? We made it support newer scipy version.

**Comment by ibrahim-amer** [comment]
Thank you sir for your response !. I had already updated Theano but with no hope here is the detailed error message:

AttributeError                            Traceback (most recent call last)
G:\ProgramFiles\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\theano\tensor\blas.py in <module>()
    162     try:
--> 163         fblas = scipy.linalg.blas.fblas
    164     except AttributeError:

AttributeError: 'module' object has no attribute 'linalg'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-1-7e2c1d176df1> in <module>()
      1 import numpy
----> 2 import theano

G:\ProgramFiles\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\theano\__init__.py in <module>()
     81 from theano.printing import pprint, pp
     82 
---> 83 from theano.scan_module import scan, map, reduce, foldl, foldr, clone
     84 
     85 from theano.updates import OrderedUpdates

G:\ProgramFiles\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\theano\scan_module\__init__.py in <module>()
     39 __contact__ = "Razvan Pascanu <r.pascanu@gmail>"
     40 
---> 41 from theano.scan_module import scan_opt
     42 from theano.scan_module.scan import scan
     43 from theano.scan_module.scan_views import map, reduce, foldl, foldr

G:\ProgramFiles\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\theano\scan_module\scan_opt.py in <module>()
     57 
     58 import theano
---> 59 from theano import tensor, scalar
     60 from theano.tensor import opt, get_scalar_constant_value, Alloc, AllocEmpty
     61 from theano import gof

G:\ProgramFiles\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\theano\tensor\__init__.py in <module>()
     15 from theano.tensor import opt
     16 from theano.tensor import opt_uncanonicalize
---> 17 from theano.tensor import blas
     18 from theano.tensor import blas_scipy
     19 from theano.tensor import blas_c

G:\ProgramFiles\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\theano\tensor\blas.py in <module>()
    166         # `scipy.linalg.blas.fblas` with `scipy.linalg.blas`.
    167         # See http://github.com/scipy/scipy/pull/358
--> 168         fblas = scipy.linalg.blas
    169     _blas_gemv_fns = {numpy.dtype('float32'): fblas.sgemv,
    170                       numpy.dtype('float64'): fblas.dgemv,

AttributeError: 'module' object has no attribute 'linalg'

**Comment by nouiz** [comment]
What is your version of scipy?

**Comment by ibrahim-amer** [comment]
I used this command to get my scipy version and here is what I got:
In[1]: import scipy
         scipy.__version__

Out[2]:'0.17.0'

**Comment by nouiz** [comment]
You have an old Theano version. Make sure to remove it. You probably need to do this command multiple time to make sure there isn't multiple version installed:

pip uninstall theano

Then reinstall Theano.

Newer Theano version would have catch this error and took a fall back (I just checked the code to confirm this)

**Comment by ibrahim-amer** [comment]
Thanks sir again for your reply. I did what you suggested but the problem is still occurring, I uninstalled theano using the command you provided, then I installed theano using this command:
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

Note: I'm using Winpython on windows 10 ... it was working fine from 2 months ago and it remained untouched until I used it recently then I found this error

**Comment by nouiz** [comment]
Can you give the new error message? Also what gice:

import theano; print theano.__version__

**Comment by arisbw** [comment]
Hello, I also have the same error while import scipy:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-6fec33cc1f15> in <module>()
----> 1 from theano import function, config, shared, sandbox
      2 import theano.tensor as T
      3 import numpy
      4 import time
      5 

/home/arisbw/anaconda3/envs/python2/lib/python2.7/site-packages/theano/__init__.pyc in <module>()
     85 from printing import \
     86     pprint, pp
---> 87 import scan_module
     88 from scan_module import scan, map, reduce, foldl, foldr, clone
     89 

/home/arisbw/anaconda3/envs/python2/lib/python2.7/site-packages/theano/scan_module/__init__.py in <module>()
     39 __contact__ = "Razvan Pascanu <r.pascanu@gmail>"
     40 
---> 41 import scan_opt
     42 from scan import scan
     43 from scan_views import map, reduce, foldl, foldr

/home/arisbw/anaconda3/envs/python2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py in <module>()
     18 
     19 import theano
---> 20 from theano import tensor
     21 from theano.tensor import opt, get_constant_value
     22 from theano import gof

/home/arisbw/anaconda3/envs/python2/lib/python2.7/site-packages/theano/tensor/__init__.py in <module>()
      9 import opt
     10 import opt_uncanonicalize
---> 11 import blas
     12 import blas_scipy
     13 import blas_c

/home/arisbw/anaconda3/envs/python2/lib/python2.7/site-packages/theano/tensor/blas.py in <module>()
    147     _have_fblas = True
    148     _blas_gemv_fns = {
--> 149             numpy.dtype('float32'):scipy.linalg.blas.fblas.sgemv,
    150             numpy.dtype('float64'):scipy.linalg.blas.fblas.dgemv,
    151             numpy.dtype('complex64'):scipy.linalg.blas.fblas.cgemv,

AttributeError: 'module' object has no attribute 'fblas'

I am now using scipy 0.18.1, theano 0.5.0 and conda environment. Can someone tell me what's wrong?

**Comment by nouiz** [comment]
Don't use Theano 0.5. it is war too old. Use 0.8.2 or the dev version.

Le 11 oct. 2016 16:33, "Aris Budi Wibowo" <notifications@github.com> a
écrit :

**Comment by leonardodutra** [comment]
Traceback (most recent call last):
  File "./veh.py", line 4, in <module>
    from printing import *
ImportError: No module named printing

**Comment by nouiz** [comment]
This is a user error, so you should check for help on theano-user mailing list. We try to keep issue for feature request and bug report.

If you want Theano printing module, you should do: "from theano import printing" and use "printing.debugprint(...)" in your code. It is bad habit to do "from a_module import *"
