### ISSUE TITLE
Remove no_recycle change to c code

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1174]
In gh-1169, @lamblin told that currently when an op is in the no_recycle list (i.e. when it is the output of an graph without the borrow=True flag), the c code for the apply node is changed.

This cause 2 problems:
- [ ] We generate different code an op depending where it is in the graph
- [x] gh-1187 DebugMode.check_preallocated_output won't do any check on ops that are the output of a graph. As many of our tests have the tested op as the only op or the last op of the graph, we don't test many ops.

I think we already clear the storage map of the no_recycle at other point. I forgot where. I think we should clear this list after the updates, but before the theano function return. This way, we are sure we won't have other reference when it will get called later and this won't make a memory leak.

Yes, the c_code of ops could store by themself a ptr to memory. This issue do not address this. I forgot how the no_recycle pass this info the ops c_code, but this proposal shouldn't affect this.

I set this at the 0.6 milestones, as I think it is easy change in the code and I want the check_preallocated_output to work.

Update: Since gh-1187 fix the most important problem, I removed the milestone. I think we should fix the double compilation at some time. But this can be when we try to do smarter memory management, like reusing intermediate output memory region when they aren't needed anymore by other apply node.

**Comment by lamblin** [comment]
Maybe we should restart the discussion about this now that we have Params for operations.
I don't know if it would be possible to have (some of) the `get_c_...` methods have their behaviour depend on the value of a Param.
If that is possible, then maybe we can move the logic of "what to extract / copy when" towards runtime (C code), rather than compile time (C code generation).

**Comment by nouiz** [comment]
fixed in https://github.com/Theano/Theano/pull/6107

Now if a node is an output or not of the graph, we generate the same c code.
