### ISSUE TITLE
Duplicate class/function tensor.Diag?

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1221]
In PR https://github.com/Theano/Theano/pull/1088 and https://github.com/Theano/Theano/pull/1119 @abalkin added  tensor_var.diagonal and theano.tensor.{diag,diagonal,Diag,Diagonal}. I think without too much investigation that there is too much Op(4) for that as there also exist theano.sandbox.linalg.heano.sandbox.linalg.ops.{diag,ExtractDiag,AllocDiag}.
- [ ] Check exactly what each op/function do and document why we need all of them
- [ ] If some of them are not needed refactor/remove them. In particular, it is possible that the class theano.tensor.Diag is a duplicate of theano.sandbox.linalg.ops.AllocDiag

**Comment by abergeron** [comment]
After discussion, we should keep Diagonal (with support for arbitrary axis and offset) and remove all the others.  Diag can be implemented with set_subtensor with no loss of functionality.

**Comment by abergeron** [comment]
Diagonal and ExtractDiag have been merged into a single ExtractDiag class that has all the features.

Diag and AllocDiag still left to merge.

**Comment by abergeron** [comment]
Diag and AllocDiag merged in https://github.com/Theano/Theano/pull/5524
