### ISSUE TITLE
Theano default RNG very slow in scan

### ISSUE THREAD

**Issue by hunse** [Theano/Theano#1233]
Using Theano's default random number generator (theano.tensor.shared_randomstreams.RandomStream) inside a scan loop is very slow. For the basic example below, the simulation takes me about 0.15 seconds using a Python loop and Numpy (case 1), 0.35 seconds using a Python loop and Theano (case 2), and over 10 seconds using a scan loop in Theano (case 3). Clearly the difference between the last case and the first two is ridiculous. (The difference between the first two cases is also a problem, and I'll open another bug report for it).

A little examination shows that the offending line is "r = copy(r)" in theano.tensor.RandomFunction.perform. It seems that in case 2, Theano first creates a RandomFunction with inplace=False, and then later optimizes this node to be replaced with one where inplace=True (using tensor/raw_random.py:random_make_inplace). The scan function also tries to make this optimization, but for some reason this optimization doesn't stick, and Theano ends up calling the function with inplace==False (which is horribly slow since it has to copy the RNG every time).

Using another Theano RNG (i.e., theano.sandbox.rng_mrg.MRG_RandomStreams) instead of the default RNG foxes this problem, because this alternate generator is set up differently and doesn't have to worry about the "inplace" optimization. This is a viable workaround for the time being.

``` python
"""Basic example to illustrate bug with scan and default RNG

Run some Brownian motion simulations to test out the Theano RNG
"""

import theano
import theano.tensor as T
# import theano.sandbox.rng_mrg

import numpy as np
import numpy.random as npr

import time

seed = 9

N = 10
dt = 1e-3
t_final = 10
nt = int(np.round(t_final/dt))
t = dt*np.arange(1,nt+1)

x0 = np.zeros(N)
b = 0.1
etaStd = 1

def get_next_x(eta, x):
    return x + dt*b + np.sqrt(dt)*eta

################################################################################
### with numpy
nrng = np.random.RandomState(seed)

x = x0.copy()
y = np.zeros((nt,N))
timer = time.time()
for i in xrange(nt):
    eta = nrng.normal(size=N)
    x = get_next_x(eta, x)
    y[i] = x
print "Numpy (multi-gen):", time.time() - timer

################################################################################
### loop with default RNG
srng = T.shared_randomstreams.RandomStreams(seed)

x = theano.shared(x0, name='x')
eta = srng.normal(size=(N,), std=etaStd)
x_new = get_next_x(eta, x)
f_step = theano.function([], x_new, updates=[(x, x_new)])

y = np.zeros((nt,N))
timer = time.time()
for i in xrange(nt):
    y[i] = f_step()
print "Theano loop:", time.time() - timer
print type(srng)

################################################################################
### scan with default RNG
srng = T.shared_randomstreams.RandomStreams(seed)
# srng = theano.sandbox.rng_mrg.MRG_RandomStreams(seed)

eta = srng.normal(size=(N,), std=etaStd)
y, updates = theano.scan(fn=lambda x: get_next_x(eta, x),
                         outputs_info=[x0],
                         n_steps=nt)
f_scan = theano.function([], y, updates=updates)

timer = time.time()
y = f_scan()
print "Theano scan:", time.time() - timer
print type(srng)

print '----------------------------------------------------------------------'
print "Debugprint for f_step:"
theano.printing.debugprint(f_step)
print '----------------------------------------------------------------------'
print "Debugprint for f_scan:"
theano.printing.debugprint(f_scan)
```

**Comment by nouiz** [comment]
We now use MRG in the deep learning tutorial by default, so closing.
