### ISSUE TITLE
Don't downcast shape dimensions to int32 in random.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#129]
I found that we always cast to int32 the shape in code related to ramdom. This prevent one dimensions to be higher then 2e32. This will also be silent error. Below is the email that discuss this finding, but I saw more case like that. We should find a way to cast to ~PySizet or cast to int32 only on 32 bits python.

> There is one question I have about this graph: why there is a cast to
> int32 on the shape before doing to the RandomFunction? James do you
> know the answer? That could cause problem if the shape don't fix in
> int32 in one of the dimensions.
>
> From the file raw_random.py around line 450, this was added by you
> James. I think we should modify this to do the fix only on 32 bits
> python installation. What do you think? On 32 bits computer
> Py_SizeT(or similar) is 32 bits I think, so the fix is safe, but I
> think that on python 64 bits, this Py_SizeT is 64 bits.
>
Sure, 64 bit sizes on 64 bit computers would be better.

**Comment by nouiz** [comment]
Use int64 in that case. This is what we use for the infer_shape.

For safety, we should use run Theano tests on windows for that PR.

**Comment by lamblin** [comment]
For safety, test on windows and with a 32-bit python

**Comment by abergeron** [comment]
This issue should be closed as we don't do this anymore.

**Comment by nouiz** [comment]
Why did you close this? We still do this. Just grep the file tensor/raw_random.py for int32.

**Comment by lamblin** [comment]
@nouiz is right, we are still doing that for the provided `shape` argument (not for the `infer_shape` mechanism).

**Comment by abergeron** [comment]
The cast there https://github.com/Theano/Theano/blob/master/theano/tensor/raw_random.py#L187 is only done when shape == ().

Unless you mean something else.

**Comment by lamblin** [comment]
- https://github.com/Theano/Theano/blob/575c7a97c305b09783218a8827f1bd7f2eb0ab0a/theano/tensor/raw_random.py#L397
- https://github.com/Theano/Theano/blob/575c7a97c305b09783218a8827f1bd7f2eb0ab0a/theano/tensor/raw_random.py#L521

**Comment by abergeron** [comment]
Oh, ok.

**Comment by lamblin** [comment]
Actually, we also do that in `theano/sandbox/rng_mrg.py` ([l. 334](https://github.com/Theano/Theano/blob/6e25ecf9b1a6677d9f9eba5dbfb6502b8a3e9add/theano/sandbox/rng_mrg.py#L334), [l. 542](https://github.com/Theano/Theano/blob/6e25ecf9b1a6677d9f9eba5dbfb6502b8a3e9add/theano/sandbox/rng_mrg.py#L542), [l. 784](https://github.com/Theano/Theano/blob/6e25ecf9b1a6677d9f9eba5dbfb6502b8a3e9add/theano/sandbox/rng_mrg.py#L784)), and we assert that the dtype is int32 in the C code ([l. 425](https://github.com/Theano/Theano/blob/6e25ecf9b1a6677d9f9eba5dbfb6502b8a3e9add/theano/sandbox/rng_mrg.py#L425-L428), [l. 674](https://github.com/Theano/Theano/blob/6e25ecf9b1a6677d9f9eba5dbfb6502b8a3e9add/theano/sandbox/rng_mrg.py#L674-L678), [l. 932](https://github.com/Theano/Theano/blob/6e25ecf9b1a6677d9f9eba5dbfb6502b8a3e9add/theano/sandbox/rng_mrg.py#L932-L936)).
I'm not sure what we should do for that case.

**Comment by lamblin** [comment]
So, for `rng_mrg.py`, here is what we should do, at all 3 places:
- In the graph, make sure shapes are `int64`.
- In the C code, expect int64, and check the values when setting `odims[i]` to make sure it fits in int32, raise a `ValueError` if it does not.

@yaoli this is your ticket.

**Comment by yaoli** [comment]
I'd appreciate if someone has a chat with me of this problem as I'm not sure if I understand it correctly.

**Comment by bouthilx** [comment]
@yaoli We can chat on google hangout
