### ISSUE TITLE
Make softmax on GPU work with bigger vectors

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#1302]
Right now, the code in GpuSoftmax (and GpuSoftmaxWithBias) is limiting the total dimension of the input matrix to some characteristics of the GPU.
We should add the appropriate loops to make it work with arbitrary shapes.

Example of failing code on the GTX Titan:

``` Python
import theano
import numpy
x = theano.shared(numpy.zeros((2,10000), dtype='float32'))
y = theano.shared(numpy.ones((2,10000), dtype='float32'))
s = theano.tensor.nnet.softmax(x + y)
f = theano.function([], s)
f()
RuntimeError: Cuda error: kSoftmax_node_3c4acb89aba08a5237cd1d1814011c3d_0: invalid argument.
Used 1 blocks, 512 threads 65536 bytes of shared memory
```

**Comment by ogurets** [comment]
It's weird... now it errors on _certain_ sizes, rather than just large ones:
```
def fixme():
    # x = theano.shared(numpy.random.rand(10, 10000).astype('float32'))  # Not crashing
    x = theano.shared(numpy.random.rand(10, 2592).astype('float32'))  # Crashing
    s = theano.tensor.nnet.softmax(x)
    f = theano.function([], s)
    print(f())
```

```
RuntimeError: Cuda error: kSoftmax[_fixed_shared]node_f50a21af25e5b321f04cd97022e3ddae_0: invalid argument.
 Used 10 blocks, 512 threads 20736 bytes of shared memory
```

Using Theano 0.9.0 + sandbox.cuda (got an old GPU).
Note that the crashing tensor is _smaller_ in size and varying the first number (10) doesn't seem to change anything, so it's second number which causes the problem.
I don't know why does this magic number 2592 "work", trying to debug and figure out.

**Comment by nouiz** [comment]
Use a more recent Theano version. It should fix your problem. We do not support 0.9 anymore.

**Comment by ogurets** [comment]
Can't do - it seems only sandbox.cuda supports shader model 1.3 and Theano 0.9.0 is the last one supporting sandbox.cuda. I would have to upgrade my hardware to use updated Theano, which is not an option.
Anyway, I've found the fix and shared it at the end of my previous post.
