### ISSUE TITLE
logistic regression example raises ordered dictionary warning

### ISSUE THREAD

**Issue by lzamparo** [Theano/Theano#1306]
Using python 2.7.2, I encounter a warning when trying out the [logistic regression example](http://deeplearning.net/software/theano/tutorial/examples.html#a-real-example-logistic-regression)

The line which constructs the function graph

``` python
train = function(inputs=[x,y], 
outputs = [prediction, xent], 
updates = {w: w - 0.1 * gw, b: b - 0.1 * gb})
```

Returns this warning:

> /scinet/gpc/tools/Python/Python272-shared/bin/ipython:1: UserWarning: The parameter 'updates' of theano.function() expects an OrderedDict, got <type 'dict'>. Using a standard dictionary here results in non-deterministic behavior. You should use an OrderedDict if you are using Python 2.7, or use a list of (shared, update) pairs. Do not just convert your dictionary to this type before the call as the conversion will still be non-deterministic.

Which is fixed by changing the dictionary parameter assigned to updates to an OrderedDict:

``` python
from collections import OrderedDict  # this can be moved to the top with the other imports
train = function(inputs=[x,y], 
outputs = [prediction, xent], 
updates = OrderedDict([(w, w - 0.1 * gw), (b, b - 0.1 * gb)]))
```

A minor issue, but worth cataloguing anyhow.

**Comment by Reddine** [comment]
for older versions of python, there is helper functions to make theano backwards compatible with python 2.6 - 2.7, as @goodfeli suggest in the 1st session of this [tutorial](https://github.com/goodfeli/theano_exercises) the use of : 
```python
from theano.compat.python2x import OrderedDict
```
instead of:
```python
from collections import OrderedDict
```
