### ISSUE TITLE
The solution to the "Using the GPU" exercise is confusing

### ISSUE THREAD

**Issue by delallea** [Theano/Theano#1356]
As pointed out by Karthik Narayan in thread https://groups.google.com/forum/?hl=en&fromgroups=#!topic/theano-users/ETXvE_cYbCI the solution to the "Using the GPU" exercise found at http://deeplearning.net/software/theano/tutorial/using_gpu.html#changing-the-value-of-shared-variables is sub-optimal since there is a lot of transfer between CPU & GPU when calling train().
See code of the solution here: http://deeplearning.net/software/theano/_downloads/using_gpu_solution_1.py

It might be intended (see at the very bottom of the solution file), but the explanation is not very clear, and it's easy to miss it if you only look at the code (there should at least be a comment in the code about where it's sub-optimal, and where the explanation can be found).

**Comment by nouiz** [comment]
was done by https://github.com/Theano/Theano/pull/2137/
