### ISSUE TITLE
'Failed to compile cuda_ndarray.cu' when importing theano, wrong Python path in nvcc flags

### ISSUE THREAD

**Issue by samvher** [Theano/Theano#1367]
Since the issue I posted in the comments here: https://github.com/Theano/Theano/issues/1319 is actually different from that of the original poster, I thought it would be better to open a new issue.

When importing theano, I get an error:

```
[4000+ lines of C code from mod.cu/cuda_ndarray.cu]
===============================
nvcc fatal   : Don't know what to do with 'Python.framework/Versions/111.222.33344/Python'

['/Developer/NVIDIA/CUDA-5.0/bin/nvcc', '-shared', '-g', '-O3', '-m64', '-Xcompiler',
'-L/Applications/Canopy.app/Contents/lib/python2.7/config,-DCUDA_NDARRAY_CUH=
90c42b258281d604500ad1a5624b6654,-D NPY_ARRAY_ENSURECOPY=NPY_ENSURECOPY,-D
NPY_ARRAY_ALIGNED=NPY_ALIGNED,-D NPY_ARRAY_WRITEABLE=NPY_WRITEABLE,-D
NPY_ARRAY_UPDATE_ALL=NPY_UPDATE_ALL,-D NPY_ARRAY_C_CONTIGUOUS=NPY_C_CONTIGUOUS,-D
NPY_ARRAY_F_CONTIGUOUS=NPY_F_CONTIGUOUS,-fPIC', '-Xlinker',
'-rpath,/Users/sam/.theano/compiledir_Darwin-12.3.0-x86_64-i386-64bit-i386-2.7.3/cuda_ndarray
', '-Xlinker', '-rpath,/Developer/NVIDIA/CUDA-5.0/lib',
'-I/Users/sam/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/Theano-0.6.0rc3
-py2.7.egg/theano/sandbox/cuda',
'-I/Applications/Canopy.app/appdata/canopy-1.0.0.1160.macosx-x86_64/Canopy.app/Contents/lib/
python2.7/site-packages/numpy/core/include',
'-I/Applications/Canopy.app/appdata/canopy-1.0.0.1160.macosx-x86_64/Canopy.app/Contents/
include/python2.7', '-o',
'/Users/sam/.theano/compiledir_Darwin-12.3.0-x86_64-i386-64bit-i386-2.7.3/cuda_ndarray/
cuda_ndarray.so', 'mod.cu', '-L/Developer/NVIDIA/CUDA-5.0/lib', '-lpython2.7', '-lcublas',
'-lcudart',
'-L/Library/Frameworks/Python.framework/Versions/111.222.33344/lib/python2.7/config', '-ldl',
'-lpython2.7', 'Python.framework/Versions/111.222.33344/Python', '-Xcompiler',
'-framework,CoreFoundation', '-Xlinker', '-pie']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 255,
'for cmd', '/Developer/NVIDIA/CUDA-5.0/bin/nvcc -shared -g -O3 -m64 -Xcompiler
-L/Applications/Canopy.app/Contents/lib/python2.7/config,-DCUDA_NDARRAY_CUH=
90c42b258281d604500ad1a5624b6654,-D NPY_ARRAY_ENSURECOPY=NPY_ENSURECOPY,-D
NPY_ARRAY_ALIGNED=NPY_ALIGNED,-D NPY_ARRAY_WRITEABLE=NPY_WRITEABLE,-D
NPY_ARRAY_UPDATE_ALL=NPY_UPDATE_ALL,-D NPY_ARRAY_C_CONTIGUOUS=NPY_C_CONTIGUOUS,-D
NPY_ARRAY_F_CONTIGUOUS=NPY_F_CONTIGUOUS,-fPIC -Xlinker
-rpath,/Users/sam/.theano/compiledir_Darwin-12.3.0-x86_64-i386-64bit-i386-2.7.3/cuda_ndarray
-Xlinker -rpath,/Developer/NVIDIA/CUDA-5.0/lib
-I/Users/sam/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/Theano-0.6.0rc3-
py2.7.egg/theano/sandbox/cuda
-I/Applications/Canopy.app/appdata/canopy-1.0.0.1160.macosx-x86_64/Canopy.app/Contents/lib/
python2.7/site-packages/numpy/core/include
-I/Applications/Canopy.app/appdata/canopy-1.0.0.1160.macosx-x86_64/Canopy.app/Contents/
include/python2.7 -o
/Users/sam/.theano/compiledir_Darwin-12.3.0-x86_64-i386-64bit-i386-2.7.3/cuda_ndarray/
cuda_ndarray.so mod.cu -L/Developer/NVIDIA/CUDA-5.0/lib -lpython2.7 -lcublas -lcudart
-L/Library/Frameworks/Python.framework/Versions/111.222.33344/lib/python2.7/config -ldl
-lpython2.7 Python.framework/Versions/111.222.33344/Python -Xcompiler
-framework,CoreFoundation -Xlinker -pie')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available
```

There are several references to the path /Library/Frameworks/Python.framework/Versions/111.222.33344 or some variation, which seem out of place. I am trying to install Theano in EPD on Mac OS X 10.8.3, so the relevant Python files which seem to be needed here are actually in /Applications/Canopy.app/Contents/. I tried to install Theano from the tarball and using pip, results are the same.

I tried adding the correct flag in my .theanorc like so:

```
[nvcc]
flags=-L/Applications/Canopy.app/Contents/lib/python2.7/config
```

but this obviously does not remove the other bad flags that are passed to nvcc, I can't seem to figure out where they come from, although the path is similar to what I see here: https://support.enthought.com/entries/23707811-TKinter-broken-on-Canopy-OS-X- .

Am I doing something wrong? Is there other information I should post?

Thank you in advance,
Kind regards

**Comment by angy50** [comment]
@nouiz 
I am also getting same error. But I am not able to solve it by clearing theano cache: 
theano-cache clear
Help to resolve it.

**Comment by nouiz** [comment]
Email theano-user with your exact and full error message. It isn't relatd to this closed issue.

**Comment by Autogazer** [comment]
I am getting that error when I import theano in python.  When I clear theano cache or purge theano cache, the same error is printed.

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: dlopen(/Users/danielyeager/.theano/compiledir_Darwin-15.6.0-x86_64-i386-32bit-i386-2.7.12-32/cuda_ndarray/cuda_ndarray.so, 2): Symbol not found: ___cudaRegisterFatBinary
  Referenced from: /Users/danielyeager/.theano/compiledir_Darwin-15.6.0-x86_64-i386-32bit-i386-2.7.12-32/cuda_ndarray/cuda_ndarray.so
  Expected in: flat namespace
 in /Users/danielyeager/.theano/compiledir_Darwin-15.6.0-x86_64-i386-32bit-i386-2.7.12-32/cuda_ndarray/cuda_ndarray.so
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
