### ISSUE TITLE
Make test_value do validation

### ISSUE THREAD

**Issue by goodfeli** [Theano/Theano#1372]
When you set
my_variable.tag.test_value = my_value
we should have test_value be a property that validates my_value before assigning it.
Currently you can assign invalid values to variables, and then later ops fail due to these invalid values. The error message will say something like that * isn't implemented for TensorVariable and TensorVariable, i.e., it gives an incorrect and confusing error message on a valid line, instead of giving the correct error message at the line that is actually invalid.

**Comment by lamblin** [comment]
Now, the `filter` method of the variable's type is called on the test value before it is used, so the error message makes sense now.
However, adding the stack trace for the variable creation in the error message would be helpful.

**Comment by nouiz** [comment]
I'm add a stack trace to when the variable with the bad test_value was created. we think this will do the work and would prevent an interface change.
