### ISSUE TITLE
MaxAndArgmax -> GpuMaxAndArgmax and just GpuArgmax

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1399]
A user spent 40% of his time in gpu transfer (20%) and 20% in MaxAndArgmax. He only use the argmax.
-  (see gh-5147) Make and Argmax only op, or do only 1 pass over the input in MaxAndArgmax.
- Make a Gpu version of argmax or maxandargmax.
  
  For the GPU version, we will do it only in the new back-end. The GPU implementation was merged in libgpuarray: https://github.com/Theano/libgpuarray/pull/185 and https://github.com/Theano/libgpuarray/pull/276. We need to make an op in Theano that will call this implementation. Check the CPU op MaxAndArgmax in tensor/basic.py. The make_node should be similar. No need for all the other implementation. Add perform/c_code and inherit from COp to have a working implementation.

**Comment by lamblin** [comment]
This popped up a couple of times for different users in the last weeks.
Currently, the only way of having something close to argmax on the GPU is something like:
`(T.eq(x, x.argmax(axis=..., keepdims=True)) * T.arange(x.shape[...]).dimshuffle(...).sum(axis=...)`
and it only works when there are no ties for the max.

**Comment by nouiz** [comment]
What is the number of dimensions of the inputs and what was the axis they where reducing on?

**Comment by lamblin** [comment]
I don't remember the different cases, but I think we should do it properly and support all reduction patterns for at least 4 dimensions, and not try to only do the strict minimum that would break as soon as someone works on examples instead of minibatches, or vice-versa.

**Comment by nouiz** [comment]
What was the number of input dimensions? What was the axis?

**Comment by danielvarga** [comment]
@nouiz @lamblin I have this exact use case, see https://groups.google.com/forum/#!topic/theano-users/E7ProqnGUMk

In my case, the following artificial example is roughly representative, that is, I'd like to reduce a 1000x5000 2d variable to 1000 indices.

https://gist.github.com/danielvarga/d0eeacea92e65b19188c

**Comment by danielvarga** [comment]
@lamblin I implemented and benchmarked your clever hack at https://gist.github.com/danielvarga/d0eeacea92e65b19188c, but it does not bring significant improvements on my task/machine:

```
bestIndices = T.argmin(s, axis=0)
  Time in Function.fn.__call__: 3.870916e-02s (99.867%)
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  77.7%    77.7%       0.029s       2.93e-02s     C        1       1   theano.tensor.basic.MaxAndArgmax
   7.0%    84.7%       0.003s       2.64e-03s     C        1       1   theano.sandbox.cuda.basic_ops.HostFromGpu
   6.9%    91.6%       0.003s       1.30e-03s     C        2       2   theano.sandbox.cuda.basic_ops.GpuFromHost
   6.2%    97.8%       0.002s       2.35e-03s     C        1       1   theano.sandbox.cuda.blas.GpuDot22Scalar

bestIndices = ( T.arange(n).dimshuffle(0, 'x') * T.eq(s, s.min(axis=0, keepdims=True)) ).sum(axis=0, acc_dtype='int32')
  Time in Function.fn.__call__: 3.252101e-02s (99.859%)
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  41.7%    41.7%       0.013s       1.33e-02s     C        1       1   theano.tensor.elemwise.Sum
  24.6%    66.3%       0.008s       7.87e-03s     C        1       1   theano.tensor.elemwise.Elemwise
  11.1%    77.4%       0.004s       1.18e-03s     C        3       3   theano.sandbox.cuda.basic_ops.GpuCAReduce
   7.0%    84.4%       0.002s       2.24e-03s     C        1       1   theano.sandbox.cuda.blas.GpuDot22Scalar
   6.8%    91.2%       0.002s       1.09e-03s     C        2       2   theano.sandbox.cuda.basic_ops.GpuFromHost
   6.0%    97.2%       0.002s       9.51e-04s     C        2       2   theano.sandbox.cuda.basic_ops.HostFromGpu
```

**Comment by lamblin** [comment]
The `sum` and `T.eq` operations do not seem to have been transferred to GPU, maybe due to the data type. Maybe calling `T.arange(n, dtype='float32')` or casting the result of `T.eq` to `float32` could help.

**Comment by danielvarga** [comment]
That helped, thanks a lot! You can tell that I haven't done much Theano profiling before. I've updated the gist.

```
bestIndices = T.cast( ( T.arange(n).dimshuffle(0, 'x') * T.cast(T.eq(s, s.min(axis=0, keepdims=True)), 'float32') ).sum(axis=0), 'int32')
  Time in 1 calls to Function.__call__: 1.155996e-02s
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  39.9%    39.9%       0.004s       1.06e-03s     C        4       4   theano.sandbox.cuda.basic_ops.GpuCAReduce
  23.3%    63.2%       0.002s       1.24e-03s     C        2       2   theano.sandbox.cuda.basic_ops.GpuFromHost
  21.8%    85.0%       0.002s       2.32e-03s     C        1       1   theano.sandbox.cuda.blas.GpuDot22Scalar
  14.6%    99.6%       0.002s       3.88e-04s     C        4       4   theano.sandbox.cuda.basic_ops.GpuElemwise
```

**Comment by nouiz** [comment]
I split the new CPU argmax op to its own issue: https://github.com/Theano/Theano/issues/5147

**Comment by lamblin** [comment]
Currently done in cuDNN.
We'll open a new ticket if needed when all reductions are in libgpuarray.
