### ISSUE TITLE
ZeroDivisionError while running ProfileMode

### ISSUE THREAD

**Issue by shackenberg** [Theano/Theano#1418]
If there is a Theano function call to a function with no `mode=profmode` before `print profmode.print_summary()` a `ZeroDivisionError: float division by zero` is thrown.
Could that be catched with a better error message like "No profile information found, did you set `mode=profmode` in the definition of function xyz?" ?

**Example code**

``` python
import theano
profmode = theano.ProfileMode(optimizer='fast_run', linker=theano.gof.OpWiseCLinker())
x = theano.tensor.matrix('x')
y = theano.tensor.matrix('y')
z = x+y
xv = [[2, 2], [1, 1]]
yv = [[2, 2], [1, 1]]

f = theano.function([x, y], z) 
f2 = theano.function([x, y], z, mode=profmode) 
print f(xv, yv)
print profmode.print_summary()
print f2(xv, yv)
```

**Output**

``` bash
[[ 4.  4.]
 [ 2.  2.]]
0 Elemwise{add,no_inplace}(x, y)

ProfileMode.print_summary()
---------------------------

Time since import 0.354s
Theano compile time: 0.000s (0.0% since import)
    Optimization time: 0.000s
    Linker time: 0.000s
Theano fct call 0.000s (0.0% since import)
   Theano Op time 0.000s 0.0%(since import) 0.0%(of fct call)
   Theano function overhead in ProfileMode 0.000s 0.0%(since import) 0.0%(of fct call)
0 Theano fct call, 0.000s per call
Rest of the time since import 0.354s 100.0%

Theano fct summary:
<% total fct time> <total time> <time per call> <nb call> <fct name>
   NOT CALLED None

Single Op-wise summary:
<% of local_time spent on this kind of Op> <cumulative %> <self seconds> <cumulative seconds> <time per call> [*] <nb_call> <nb_op> <nb_apply> <Op name>
Traceback (most recent call last):
  File "/home/ludwig/temp/theano1.py", line 12, in <module>
    print profmode.print_summary()
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/profilemode.py", line 270, in print_summary
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/profilemode.py", line 417, in print_summary_
    sotimes = [(t*100/local_time, t, a, sop_cimpl[a], sop_call[a], sop_op[a], sop_apply[a]) for a, t in sop_time.items()]
ZeroDivisionError: float division by zero
[Finished in 0.6s with exit code 1]
```

**Comment by Sandy4321** [comment]
pls make clear if I may use it
for example
for code above
import theano
profmode = theano.ProfileMode(optimizer='fast_run', linker=theano.gof.OpWiseCLinker())
x = theano.tensor.matrix('x')
y = theano.tensor.matrix('y')
z = x+y
xv = [[2, 2], [1, 1]]
yv = [[2, 2], [1, 1]]

f = theano.function([x, y], z) 
f2 = theano.function([x, y], z, mode=profmode) 
print f(xv, yv)
print profmode.print_summary()
print f2(xv, yv)

error is
File "C:\Sander\my_code\Feb12_Theano_Tutorial\S_Theano_Tutorial_from_Theano_Spec_FEb29.py", line 696, in <module>
  print profmode.print_summary()
File "C:\Anaconda\Lib\site-packages\theano\compile\profilemode.py", line 292, in print_summary
  **kwargs)
File "C:\Anaconda\Lib\site-packages\theano\compile\profilemode.py", line 482, in print_summary_
  sop_op[a], sop_apply[a]) for a, t in iteritems(sop_time)]

ZeroDivisionError: float division by zero

**Comment by nouiz** [comment]
Update Theano to the dev version of 0.8rc1. It should be fixed.
