### ISSUE TITLE
import theano.sandbox.cuda fails (windows 7 x64)

### ISSUE THREAD

**Issue by TheFausap** [Theano/Theano#1473]
Hello all,

I'm using Windows 7 64bit and Anaconda 1.6.2:

Python 2.7.5 |Anaconda 1.6.2 (64-bit)| (default, Jul  1 2013, 12:37:52) [MSC v.1
500 64 bit (AMD64)] on win32

I tried successfully several CUDA examples with Visual Studio 2010, but I have a nvcc error when try to run "import theano.sandbox.cuda".

nvcc : fatal error : nvcc cannot find a supported version of Microsoft Visual St
udio. Only the versions 2008, 2010, and 2012 are supported

['nvcc', '-shared', '-g', '-O3', '--compiler-bindir', 'C:\\Program Files (x86)\\
Microsoft Visual Studio 10.0\\VC\\bin', '-Xlinker', '/DEBUG', '-m64', '-Xcompile
r', '-LC:\\Anaconda\\lib,-DCUDA_NDARRAY_CUH=90c42b258281d604500ad1a5624b6654,/Zi
', '-IC:\\Anaconda\\lib\\site-packages\\theano\\sandbox\\cuda', '-IC:\\Anaconda\
\lib\\site-packages\\numpy\\core\\include', '-IC:\\Anaconda\\include', '-o', 'C:
\\temp\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_G
enuineIntel-2.7.5\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-LC:\\Anaconda\\l
ibs', '-LAUTO\\lib', '-LAUTO\\lib64', '-LC:\\Anaconda', '-lpython27', '-lcublas'
, '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return st
atus', -1, 'for cmd', 'nvcc -shared -g -O3 --compiler-bindir C:\\Program Files (
x86)\\Microsoft Visual Studio 10.0\\VC\\bin -Xlinker /DEBUG -m64 -Xcompiler -LC:
\\Anaconda\\lib,-DCUDA_NDARRAY_CUH=90c42b258281d604500ad1a5624b6654,/Zi -IC:\\An
aconda\\lib\\site-packages\\theano\\sandbox\\cuda -IC:\\Anaconda\\lib\\site-pack
ages\\numpy\\core\\include -IC:\\Anaconda\\include -o C:\\temp\\compiledir_Windo
ws-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.5\\cuda_
ndarray\\cuda_ndarray.pyd mod.cu -LC:\\Anaconda\\libs -LAUTO\\lib -LAUTO\\lib64
-LC:\\Anaconda -lpython27 -lcublas -lcudart')

Do you know if there's any chance to have theano working with CUDA under Windows ?

thanks in advance,
Fausto

**Comment by lamblin** [comment]
This should be fixed by gh-2451
