### ISSUE TITLE
Run Theano tests with NPY_RELAXED_STRIDES_CHECKING=1 python setup.py install

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1586]
NumPy will consider more array are C or F contiguous in the future.

It can be tested that Theano work correctly in that setup with reinstalling Theano like this:

NPY_RELAXED_STRIDES_CHECKING=1 python setup.py install

Do this and test Theano in that setup

**Comment by lamblin** [comment]
Fixed now that this is the default for numpy 1.12 and issues have been solved.
