### ISSUE TITLE
"import theano " fails

### ISSUE THREAD

**Issue by FiReTiTi** [Theano/Theano#1622]
Hi,

I am working on MacBook Pro with Mac OS X Mavericks.
I successfully installed Theano using Macport for the dependencies.
But when I want to do "import theano", I have the following error:

> > > import theano
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Theano-0.6.0rc3-py2.7.egg/theano/**init**.py", line 76, in <module>
> > >     import theano.tests
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Theano-0.6.0rc3-py2.7.egg/theano/tests/**init**.py", line 6, in <module>
> > >     import unittest_tools
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Theano-0.6.0rc3-py2.7.egg/theano/tests/unittest_tools.py", line 8, in <module>
> > >     import theano.tensor as T
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Theano-0.6.0rc3-py2.7.egg/theano/tensor/**init**.py", line 10, in <module>
> > >     import blas
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Theano-0.6.0rc3-py2.7.egg/theano/tensor/blas.py", line 393, in <module>
> > >     StrParam(default_blas_ldflags()))
> > >   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Theano-0.6.0rc3-py2.7.egg/theano/tensor/blas.py", line 332, in default_blas_ldflags
> > >     blas_info = numpy.distutils.**config**.blas_opt_info
> > > AttributeError: 'module' object has no attribute '**config**'

Is someone know why?
Thanks for your help.

**Comment by FiringBird** [comment]
Hi,I have just install the theano 0.8.2 on my linux machine which the os is "Linux test-60-11 2.6.32-220.23.2.ali878.el6.x86_64 #1 SMP Mon Jan 28 17:12:52 CST 2013 x86_64 x86_64 x86_64 GNU/Linux",  however, when I try to import theano, it ouccurs the error "illegal instructuion", I also have tried reinstall with the version 0.6, it can been imported successfully. So how can I import theano of 0.8.2 successfully on my machine? Who can help me , please!

**Comment by nouiz** [comment]
Don't revive old issue that are closed. Your problem is probably not the
same.

Use Theano dev version. It have update to it that help on that. But
otherwise, if the home directory is on NFS, delete Theano cache.
