### ISSUE TITLE
IndexError in Scan gradient

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#1647]
See https://groups.google.com/d/msg/theano-users/DN-OGIyQDms/dZEZ04JrXvoJ : the main example is now working, but not the variant:
```Python
import numpy
import theano
from theano import tensor

w = theano.shared(numpy.array(0, dtype='float32'), name='w')
out, _ = theano.scan(
        fn=lambda: w,
        n_steps=2)
theano.grad(out[-1], w)
```
The forward pass works well:
```Python
>>> out[-1].eval()
array(0.0, dtype=float32)
```

**Comment by nouiz** [comment]
It now work. So I support it was one of the crash fix for scan done recently. I close this ticket.
