### ISSUE TITLE
Theano returns thousands of lines of C code as warning message

### ISSUE THREAD

**Issue by fonnesbeck** [Theano/Theano#1680]
When running some code that uses Theano (from inside PyMC), I get conditions where Theano appears to write hundreds of thousands of lines of C code as a warning message. Sorry, but these are just screen shots because it actually locked up my browser writing warning messages:

![warn1](http://f.cl.ly/items/0y272v433t2I3N341S1Y/Screen%20Shot%202013-12-19%20at%202.14.20%20PM.png)

There is no exception thrown; the line runs without error, but throws out all this warning output (I assume it is warning, due to the pink background color that IPython notebook uses for warnings). 

![warn2](http://f.cl.ly/items/3j0d303e1a013007192p/Screen%20Shot%202013-12-19%20at%2012.19.38%20PM.png)

I know this may be impossible to diagnose based on what I have provided, but I am hoping someone knows what this may be from? I am at a loss as to how to debug it.

**Comment by lamblin** [comment]
For now, let's not worry too much about the temporary files. Let's just:
- put the source code (which should correspond to the content of mod.cpp / mod.cu) in a temporary file, created by the `tempfile` module
- print the path to that file in the error message, rather than the code itself.
