### ISSUE TITLE
Make Constant-folding a generic greedy Optimizer

### ISSUE THREAD

**Issue by jaberg** [Theano/Theano#169]
It's nice to have constant folding as a local optimizer so that it can be done during stabilization and specialization.

For better performance - and to permit lowering the max_use_ratio back to a sane level, it would also be good to do Constant folding "passes" similar to what the MergeOptimizer does.  Since constant folding is a kind of bottom-up transformation, a single pass could fold entire subgraphs all at once. This would be faster, because it would avoid running all of the equilibrium optimizers between every constant-folding substitution!

I would suggest making a single pass of the ConstantFoldingOptimizer, after stabilization, but before specialization. We don't do any constant folding before specialization right?

**Comment by lamblin** [comment]
We now have `topo_constant_folding` running at a couple of places, which is simply defined as `in2out(constant_folding)`.

**Comment by nouiz** [comment]
Note, we also include it inside some equilibrium.
