### ISSUE TITLE
Warning messages and crashes regarding 'Mingw 4.5.2', Numpy and nvcc

### ISSUE THREAD

**Issue by nomader** [Theano/Theano#1791]
Hi,

I am using theano (and pylearn2) on Windows 8.1 using the Enthought Canopy distribution. I am using the GPU. The first few times I run my code, i get the following error repeatedly: 

DEBUG: nvcc STDOUT
Your Python version is from Canopy. You need to install the package 'mingw 4.5.2' from Canopy package manager.
Your Python version is from Canopy. You need to install the package 'mingw 4.5.2' from Canopy package manager. c:\users\amogh\appdata\local\enthought\canopy\user\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
   Creating library C:/Users/amogh/AppData/Local/Theano/compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.6-64/tmpqjqmxe/94f272bc27573f140eef308b12f8617d.lib and object C:/Users/amogh/AppData/Local/Theano/compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.6-64/tmpqjqmxe/94f272bc27573f140eef308b12f8617d.exp

These messages keep repeating. My code also seems to be running but very very slow, and these messages completely clutter my console. I need to restart my python kernel a couple of times before I am able to execute the code relatively cleanly (I still get these messages, but only a few times in the beginning of the execution.

Note that by default Canopy includes the package 'mingw 4.8.1-2' and 'mingw 4.5.2' is no longer available.

Please let me know how I can fix this.

Regards
Amogh

**Comment by ZiqianXie** [comment]
Simply change mingw 4.5.2 in the code
>for f, lib in [('libpython27.a', 'libpython 1.2'),
>                           ('libmsvcr90.a', 'mingw 4.5.2')]:
to mingw 4.8.1 solves the problem

**Comment by nouiz** [comment]
@ZiqianXie 

Can one of you confirm that if you have mingw 4.8.1 installed, that it work?

If so, I'll update the error message to ask for "mingw 4.5.2+". That way it will make clear newer version are good.

**Comment by ZiqianXie** [comment]
@nouiz I have mingw 4.8.1 installed by still got that error message, I have to search for libsvcr90.a and copy it to the python libs folder.

**Comment by nouiz** [comment]
Are you sure the name is exactly libsvcr90.a and not libmsvcr90.a (we
search for the second one).

If we do not copy it, do Theano work, except that you have this useless
message?

Maybe we could just remove the check for now. Another option is to look for
the new place of this lib. Can you find again where you found it?

**Comment by amit-sethi** [comment]
Problem solved even with mingw 4.8.1-2 !!!

I downloaded the file from https://github.com/enthought/vendor-mingw/blob/master/msvcrt/libmsvcr90.a as it was missing on my computer. I copied it to both 
C:\Users\<USER>\AppData\Local\Enthought\Canopy\User\libs and
C:\Users\<USER>\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.5.1.2730.win-x86_64\libs

**Comment by nouiz** [comment]
To be sure, if they install 4.8.1-2, you do not need to download and
install the missing file? This was only needed for 4.8.1?

So I could juste update the error message to tell "mingw 4.5.2 or 4.8.1-2"?

**Comment by ZiqianXie** [comment]
Without copying that libmsvcr file theano works fine despite its annoying warning. My libmsvcr90.a is located at C:\Users\Administrator\AppData\Local\Enthought\Canopy\User\EGG-INFO\mingw\usr\x86_64-w64-mingw32\lib.

**Comment by nouiz** [comment]
You can give me the output of:

import sys
print sys.prefix
print sys.base_prefix

**Comment by ZiqianXie** [comment]
C:\Users\Administrator\AppData\Local\Enthought\Canopy\User
C:\Program Files\Enthought\Canopy\App\appdata\canopy-1.5.0.2717.win-x86_64

**Comment by nouiz** [comment]
I have a temptative fix in gh-2518. Can you remove your local fix. Try again to make sure the message come back, then update Theano to that pull request version and check again if the message is still there?

This PR could also speed up a little compilation on windows, as it is currently slower then on linux. Maybe this changee will lower the compilation speed difference vs linux at the same time.

thanks

**Comment by nouiz** [comment]
I'll close this issue as I think my PR fixed it. If you still see this, re-open this ticket.
