### ISSUE TITLE
theano.scalar.basic.py InRange.grad() return None.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1824]
Fix this to use the new interface and check if other op in that file do this too.

This also mean their is no test for that grad, so add a dummy tests to make sure the right thing is done.

**Comment by yobibyte** [comment]
I will have a look on this.

**Comment by nouiz** [comment]
I just checked and it don't return None anymore and it look good. So I'm closing this.

Did you had a problem with this PR or you where looking for something to help us?

**Comment by yobibyte** [comment]
No problems there, just willing to help. Do you have any suggestions?

**Comment by nouiz** [comment]
There is a label for issue that are easy to help you get started with Theano:

https://github.com/Theano/Theano/issues?q=is%3Aopen+is%3Aissue+label%3A%22Easy+fix%22

**Comment by yobibyte** [comment]
Ok, thanks.

Sincerely yours,
Vitaly Kurin

On Mon, Apr 11, 2016 at 10:06 PM, Frédéric Bastien <notifications@github.com
