### ISSUE TITLE
python setup.py develop does not recognized satisfied scipy dependency

### ISSUE THREAD

**Issue by fonnesbeck** [Theano/Theano#1852]
I'm installing Theano from master, using `python setup.py develop`, but the setup does not recognize that the scipy dependency has been satisfied. Here is my SciPy version:

    In [2]: scipy.__version__
    Out[2]: '0.14.0.dev-7cefb25'

But I get the following upon trying to install:

    Searching for scipy>=0.7.2
    Reading https://pypi.python.org/simple/scipy/
    Best match: scipy 0.14.0
    Downloading https://pypi.python.org/packages/source/s/scipy/scipy-     0.14.0.zip#md5=7ee4fa9e756bab6b46b79f77c821cb68

Running on Python 2.7.5, OS X 10.9.2.

**Comment by nouiz** [comment]
I think it is solved.
