### ISSUE TITLE
Error when compiling node using MKL on OS X

### ISSUE THREAD

**Issue by jfsantos** [Theano/Theano#1871]
I wrote the following function to reconstruct an input from the Deep Learning Tutorial [denoising autoencoder example](http://deeplearning.net/tutorial/dA.html) (mdl is an instance of the class dA):

    x = T.vector()
    c = T.scalar()
    xp = mdl.get_corrupted_input(x, c)
    h = mdl.get_hidden_values(xp)
    y = mdl.get_reconstructed_input(h)
    f = theano.function([x, c], y)

It works ok under Linux using Numpy linked to MKL (from Anaconda). However, on OS X and Theano 2993e6f7a I get the following error instead:

    ImportError: ('The following error happened while compiling the node', 
    CGemv{no_inplace}(b, TensorConstant{1.0}, W.T, Elemwise{Mul}[(0,
    0)].0,TensorConstant{1.0}), '\n', 'dlopen(/Users/jfsantos/.theano/compiledir_Darwin-
    13.2.0-x86_64-i386-64bit-i386-2.7.6-64/tmp2s3Irh
    /ca289642230ae8704509f2632485425e.so, 2): Library not loaded: 
    libmkl_intel_lp64.dylib\n  Referenced from: /Users/jfsantos/.theano/compiledir_Darwin-
    13.2.0-x86_64-i386-64bit-i386-2.7.6-64/tmp2s3Irh
    /ca289642230ae8704509f2632485425e.so\n  Reason: image not found', 
    '[CGemv{no_inplace}(b, TensorConstant{1.0}, W.T, <TensorType(float64, vector)>, 
    TensorConstant{1.0})]')

According to the traceback, the error happens in line 1993 of cmodule.py, where there is an dlimport call. It does not happen with simpler Theano functions (such as adding scalars, probably because you don't need to call BLAS for that), and also does not happen if I use another BLAS implementation.

**Comment by tylerpayne** [comment]
I am having the same issue, but setting DYLD_FALLBACK_LIBRARY_PATH is not fixing the issue.

**Comment by andozone** [comment]
same issue here, setting DYLD_FALLBACK_LIBRARY_PATH doesn't help either.

**Comment by abergeron** [comment]
The are no updates since it is not really possible to fix this problem from inside theano.  One possible fix is to repackage the libraries with a new install_name (using install_name_tool) but that will only work if there is sufficient space to write the new name (space has to be reserved at build time).

Exporting this variable in the theano startup will not fix anything since it has to be defined during program startup (when the OS loads python).

For those that have an error with setting DYLD_FALLBACK_LIBRARY_PATH, what do you set it to?

**Comment by andozone** [comment]
I set DYLD_FALLBACK_LIBRARY_PATH to '/Users/.../anaconda/lib' where the libmkl_intel_lp64.dylib file is. Is there anywhere else to set it to?
Right now the only way I can run theano is by turning off blas by setting THEANO_FLAGS to 'blas.ldflags='

**Comment by lamblin** [comment]
Are you sure you are exporting it, not simply setting it?

**Comment by gwulfs** [comment]
getting the same issue, curious what else you managed to try. everything was working fine until I got my student license for anaconda accelerate

**Comment by abergeron** [comment]
You don't set the path to the library file, but rather to the directory it's in.

**Comment by gwulfs** [comment]
thanks, fixed

**Comment by yanglinfang** [comment]
Same here, 
got following error

ImportError: ('The following error happened while compiling the node', Dot22(<TensorType(float64, matrix)>, <TensorType(float64, matrix)>), '\n', 'dlopen(/Users/linfangyang/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.10-64/tmp3PTov9/eb163660e6e45b373cd7909e14efd44a.so, 2): Library not loaded: libmkl_intel_lp64.dylib\n  Referenced from: /Users/linfangyang/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.10-64/tmp3PTov9/eb163660e6e45b373cd7909e14efd44a.so\n  Reason: image not found', '[Dot22(<TensorType(float64, matrix)>, <TensorType(float64, matrix)>)]')

tried this but not helpful. still seeing same error 
export DYLD_FALLBACK_LIBRARY_PATH='/anaconda/lib'

does this has anything to do the mkl accelerator thing?

**Comment by yanglinfang** [comment]
I did 
conda uninstall mkl 
then error disappeared

**Comment by jjm0022** [comment]
<conda uninstall mkl> worked for me too

**Comment by devang1994** [comment]
Thanks for the workaround, added this to the bash_profile
```export DYLD_FALLBACK_LIBRARY_PATH='/Users/.../anaconda/lib'```
and everything works

**Comment by mikeloukides** [comment]
That solution doesn't work on OS X 10.11:  see this article http://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1
Apple has apparently decided that you can't set any of the DYLD variables.

Any other ideas about how to make this work?  'conda uninstall mkl' broke a bunch of other things, so I had to reinstall it.

**Comment by nouiz** [comment]
A temp workaround is to do "blas.ldflags=". So mostly, we won't link
directly to it. But at least, it will work.

Hopefully, someone else can help more.

**Comment by cranmer** [comment]
having this problem too. Why is the issue closed?

**Comment by cranmer** [comment]
@nouiz can you be a bit more explicit. Where does one set `blas.ldflags=` ?

**Comment by lamblin** [comment]
It is closed because it is a bug or something we can fix in Theano.
@cranmer Can you check what the value of `theano.config.blas.ldflags` is from inside the notebook?
Also, clearing your theano cache may help making the workaround work.

**Comment by abergeron** [comment]
The current release candidate (0.8.0rc1) should help in that respect.  It won't link to mkl since it's not really possible without a lot of hacks, but it shouldn't crash either.

It should link with the default blas which is Accelerate on OS X.

**Comment by mikeloukides** [comment]
I just installed 0.8.0, and now I'm running into a different error:

ImportError                               Traceback (most recent call
last)<ipython-input-3-59b094c68549> in <module>()      8 from
sklearn.linear_model import LogisticRegressionCV      9 ---> 10 from
keras.models import Sequential     11 from keras.layers.core import
Dense, Activation

     12 from keras.utils import np_utils


....


/Users/mikel/anaconda/lib/python3.4/site-packages/theano/compile/function_module.py
in <module>()     16      17 import theano---> 18 from theano import
config, gof     19 from functools import partial     20 from
theano.compat import izip
ImportError: cannot import name 'gof'


Did gof disappear in the transition from 0.7.0 to 0.8.0?  (I've seen some
similar error reports on github, but nothing explicitly about gof...

Since this is ultimately coming from keras, I tried uninstalling and
reinstalling keras.  But no luck.


Mike Loukides
VP, Content Strategy
O'Reilly Media, Inc.

**Comment by lamblin** [comment]
`theano.gov` is still there. Can you try uninstalling completely Theano, making sure there is no other version of Theano on your system, and resinstalling version 0.8?

**Comment by mikeloukides** [comment]
Yeah, though now I'm getting different errors... this may have to do with
upgrading to OS X 10.11.4:

/Users/mikel/anaconda/lib/python3.4/site-packages/IPython/html.py:14:
ShimWarning: The `IPython.html` package has been deprecated. You
should import from `notebook` instead. `IPython.html.widgets` has
moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Using Theano backend.

===============================
===============================
clang: error: unsupported option '-b mi2'
clang: error: unsupported option '-b mi'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sse4a'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-tbm'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-fma4'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-prfchw'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-rtm'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-fma'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-rdseed'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-movbe'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-hle'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sha'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: no such file or directory: '+cx16'
clang: error: no such file or directory: '+xsave'
clang: error: language not recognized: 'savec'
clang: error: no such file or directory: '+fsgsbase'
clang: error: no such file or directory: '+avx'
clang: error: no such file or directory: '+popcnt'
clang: error: no such file or directory: '+aes'
clang: error: no such file or directory: '+rdrnd'
clang: error: language not recognized: 'saves'
clang: error: no such file or directory: '+sse4.1'
clang: error: no such file or directory: '+sse4.2'
clang: error: no such file or directory: '+sse'
clang: error: no such file or directory: '+pclmul'
clang: error: no such file or directory: '+f16c'
clang: error: no such file or directory: '+ssse3'
clang: error: no such file or directory: '+mmx'
clang: error: no such file or directory: '+cmov'
clang: error: language not recognized: 'op'
clang: error: no such file or directory: '+xsaveopt'
clang: error: no such file or directory: '+sse2'
clang: error: no such file or directory: '+sse3'


00001	#include <Python.h>
00002	#include "theano_mod_helper.h"
00003	#include "structmember.h"
00004	#include <sys/time.h>

... for many, many more lines.



This is getting frustrating.  Might be just one of those silly "license
acceptance" things for command line tools (though I don't think so; I can
run gcc, clang, git).

Anyway...

Mike Loukides
VP, Content Strategy
O'Reilly Media, Inc.

**Comment by nouiz** [comment]
This is caused by new version of Apple software. We have a work around in
this PR:

https://github.com/Theano/Theano/pull/4281

**Comment by mikeloukides** [comment]
Thanks.  Thought it was probably an OS X problem.  OS X is getting more and
more problematic...

Mike Loukides
VP, Content Strategy
O'Reilly Media, Inc.

**Comment by Sandy4321** [comment]
Thanks

**Comment by bbud148** [comment]
Any new workarounds discovered?  I installed using the Theano-master.zip.  My specific error message:

ImportError: ('The following error happened while compiling the node', Dot22(X, Y), '\n', 'DLL load failed: The specified module could not be found.', '[Dot22(X, Y)]')

**Comment by nilavghosh** [comment]
Same Error as bbud.

**Comment by nouiz** [comment]
We would need the full error message.
