### ISSUE TITLE
Slow GemmOptimizer

### ISSUE THREAD

**Issue by JonathanRaiman** [Theano/Theano#1895]
![screen shot 2014-06-02 at 6 35 57 pm](https://cloud.githubusercontent.com/assets/1411079/3150287/481da7f4-ea74-11e3-9a88-cbef6332c0cd.png)
For a big enough graph (1000+ nodes) GemmOptimizer has an infinite loop in the:

for node in nodelist:
   ...
   if new_outputs:
     ... (will add 1-60 more nodes to novelist, thereby making this loop quasi infinite)

The version available through pip doesn't have this issue, but has conflicts with Python3 with regards to "'str' does not support the buffer interface".

Not sure if a potential diff between the two versions is possible, but hopefully using the working GemmOptimizer and the corrected Python3 str usage (that encodes to utf-8 before writing) would be great!

**Comment by nouiz** [comment]
I think it is solved and I don't see anymore optimization trace where this take times. So I'm closing this.
