### ISSUE TITLE
Opt: Alloc(Alloc(...),...) -> Alloc(...)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#1902]
We saw this in a graph, where the first alloc had only 1 client, the second alloc:

Alloc(Alloc(m, x, 1), x, y) -> Alloc(m, x, y)

Here m was broadcastable on both dimensions, but the optimization can cover more cases.

We need to prove that the shape x is the same for both Alloc, otherwise, we could hide a shape mismatch.

**Comment by lamblin** [comment]
If the shapes cannot be proven to be equal, we should add an Assert node, not simply give up.
This could be a follow-up ticket if you prefer.

**Comment by nouiz** [comment]
done by gh-3132.
