### ISSUE TITLE
Elemwise perform: AttributeError: 'int' object has no attribute 'shape'

### ISSUE THREAD

**Issue by sisp** [Theano/Theano#1935]
I've stumbled upon a situation where, during graph optimization, a pure Python 'int' is passed to Elemwise.perform, but the current implementation expects a NumPy array because it assumes the 'shape' attribute (theano/tensor/elemwise.py:778). I'm not sure about the correct fix. Should numpy.asarray be applied to all inputs first? That might lead to incorrect floatX types though if an input is a Python float type and floatX=float32. Any suggestions?

**Comment by lamblin** [comment]
The test case is now working even without any of these fixes.
If you have another test case fixed by this, please reopen and submit that case.
