### ISSUE TITLE
Segmentation fault: 11 in theano.sandbox.cuda.tests.test_conv_cuda_ndarray.test_valid_0_2

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#1950]
Using the latest Theano, CUDA 6 and Mac OSX 10.9.3, when running tests I get:
`theano.sandbox.cuda.tests.test_conv_cuda_ndarray.test_valid_0_2 ... Segmentation fault: 11`

**Comment by nouiz** [comment]
I think this is fixed. As it is old, I'll just close, if someone see this again, tell us.
