### ISSUE TITLE
Continue gemm convolution

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2015]
- [ ] Remove The need of gpu_contiguous.
- [x] Remove restriction that filter need to be square.
- [x] Add support for strides (probably only square strides).
- [x] Doc how to use it directly GpuCorrMM, that way it remove the gpu_contiguous.
- [x] Modify GpuConv to select GpuCorrMM when possible automatically.
- [ ] Make the selection of the forward or gradInput case at run time and not as an opt.
- [x] Add a cpu version gh-3026.
- [ ] Make an inplace version for the GpuCorrMM_gradWeight.

This is the possible follow up of PR gh-2002

**Comment by f0k** [comment]
Now that the cuDNN convolution has support for inplace and alpha (#2559), should we do the same for the gemm-based convolution? Is it worth it?
I can easily adapt the C code to support `alpha` and `beta`, I can probably also extend the Theano ops to support `alpha` and `beta`, but I don't know much about `inplace` and the optimizers. Is there sufficient interest in having this, and would anybody be willing to help?

**Comment by nouiz** [comment]
Hi,

I'm not sure how much useful this is some other benchmark I saw only show
1% speed up. Also, the memory saving isn't big as what take the more space
is the output of the convolution, not the weight.

I'll be pretty busy this week and next week. But if you do it, I can help
after. The optimization isn't the hard part. Just do not expect big
difference.

**Comment by f0k** [comment]
> I'm not sure how much useful this is some other benchmark I saw only show
1% speed up. Also, the memory saving isn't big as what take the more space
is the output of the convolution, not the weight.

OK, then I don't think it's worth the effort (and the increased code complexity). It would only affect users with older GPUs or without cuDNN anyway, and people requiring maximum performance will not fall into that group. Thanks!

**Comment by nouiz** [comment]
We probably won't finish this. If the need is there, it will pop up again in the new back-end.
