### ISSUE TITLE
Simplify Op making and their c code.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2019]
We don't have good doc and the example we have tell to use python string manipulation. It isn't natural for people to code c in python strings. This move away some potential Theano contibutor. Here is what we can do to make this simpler.

This list also include other stuff to help make new op.

- [x] Doc the decorator as_op gh-1881.
- [x] Generalize Op.props to generate automatically  `__hash__`, `__eq__` and `__str__`. This should raise an error if the op didn't provide the props attribute. gh-2018.
- [x] Document how to put the code in c files and include it in c_support_code() and handle the version correctly. Provide an class that do all that when you specify just the file name.
- [x] If the c function in that file have a specific signature, we can generate the c_code() automatically. The signature will be a ptr to each inputs, then a ptr to a ptr for each outputs in the order provided by the Apply node.
- [x] Make a tutorial for people that know python and C, but not the Python/NumPy C-API. Tell them about the important stuff, refcount, where to look for the NumPy C-API, small review of the important fields that they need, with a good example with code in C file and code in python string. Put this in a new file: doc/tutorial/extending_theano_c.txt, include that in the index.txt file. doc/extending/cop.txt. doc c_code(), c_support_code(), c_code_cache_version(), link to the others c_* functions definition.
- [x] Update tutorial after @abergeron's changes

**Comment by nouiz** [comment]
The only thing left is to update the tutorial that was done.

**Comment by abergeron** [comment]
If by tutorial, you mean what is in doc/tutorial/extending_theano_c.txt then that is done.

**Comment by nouiz** [comment]
There was a need for the documentation update. Or is that in another issue?

**Comment by abergeron** [comment]
I've looked through it and it seems it was done.  The tutorial could be reworked to flow better, but I'd consider that a separate issue.
