### ISSUE TITLE
Pool and uppool with switch

### ISSUE THREAD

**Issue by ChienliMa** [Theano/Theano#2022]
In Pro. Zeiler's paper  < Visualizing and Understanding Convolutional Networks >.
http://www.matthewzeiler.com/pubs/arxive2013/arxive2013.pdf

Operation: Switch_pool() and Switch_upppool() are needed to visualizing CNN. I did not found similar function in theano( Or maybe I missed it ). 

Currently I have an implementation using numpy. If there are other people need such an operation, I may try implementing it. Yet it seem a little difficult for me since there are a lot of c code in pooling function. 

Need help.

**Comment by f0k** [comment]
> They show (Sect. 4) that Zeiler's method is closely related to computing the gradient of the network output wrt. the input image, which is very easy to do in Theano: [...]

There's example code for Zeiler's method, Simonyan's method and Springenberg's method here: https://github.com/Lasagne/Recipes/blob/master/examples/Saliency%20Maps%20and%20Guided%20Backpropagation.ipynb
It uses Lasagne for defining the network, but should be easy to adapt to whatever you're using.

@nouiz, this can definitely be closed, Theano has everything that's needed.

**Comment by nouiz** [comment]
Should we add an unpool function in theano to help build that? It came up a
few times and it don't seem trivial for people to find how to do it.

This is in the same spirit as the function max_pool_2d_same_size

http://www.deeplearning.net/software/theano/library/tensor/signal/downsample.html#theano.tensor.signal.downsample.max_pool_2d_same_size

What do you think about adding such unpool method?

**Comment by f0k** [comment]
> Should we add an unpool function in theano to help build that?

To implement what we're discussing here (the DeconvNet of Zeiler), you actually have to use the gradient of an existing pooling Op, not just something that does unpooling (because you need to use the correct pooling switches). An `unpool()` function wouldn't help for that.

It might be nice to have an unpooling function for convolutional auto-encoders, though. In Lasagne, we've added an [Upscale2DLayer](http://lasagne.readthedocs.org/en/latest/modules/layers/pool.html#lasagne.layers.Upscale2DLayer), but so far it supports upscaling by repetition only, and it would be nice to have it support bed-of-nails -- that's something that could be moved to a Theano function as well.

**Comment by nouiz** [comment]
I see that it use repeat. But what do you mean by support "bed-of-nails"?
Google don't give me related explanation:)

**Comment by f0k** [comment]
> But what do you mean by support "bed-of-nails"?

When you uppool by copying the input value always into the top left corner of its corresponding output region, leaving everything else at zero. The resulting output will look like a bed of nails. Some papers do it like that when the pooling switches are unknown. (I wonder what happens for negative values, though, maybe that case is ruled out by using rectifiers.)

**Comment by ChienliMa** [comment]
@nouiz  you can close this issue is what I've asked about can be implemented using existing feature of Theano.  
Thanks @f0k for your tutorial. :)

**Comment by Sentient07** [comment]
Hi @f0k , I'm having a question regarding this. 

> When you uppool by copying the input value always into the top left corner of its corresponding output region, leaving everything else at zero. The resulting output will look like a bed of nails. Some papers do it like that when the pooling switches are unknown. (I wonder what happens for negative values, though, maybe that case is ruled out by using rectifiers.)

When you mean copying the input, we should have the original location(indices) of the max value stored somewhere, right ? Or, could we perform the unpooling operation by using gradient of maxpool ? (using DownsampleFactorMaxGrad ) But even in that case, I think we need to have the indices of pooled values stored somewhere, right ?

**Comment by f0k** [comment]
I think you're mixing up some things.

>>> But what do you mean by support "bed-of-nails"?

>> When you uppool by copying the input value always into the top left corner of its corresponding output region, leaving everything else at zero.

> When you mean copying the input, we should have the original location(indices) of the max value stored somewhere, right ?

No, in that message, I was replying to Frederic's question, which was about generic unpooling, not about the backward pass of max-pooling. For the backward pass of max-pooling, you need `theano.grad` of a max-pooling forward pass. This will take care of using the same pooling switches. (In Lasagne, you can use an `InverseLayer` to unpool a `MaxPool2DLayer`, this creates the correct `theano.grad` expression for you.)

**Comment by Sentient07** [comment]
> In Lasagne, you can use an InverseLayer to unpool a MaxPool2DLayer, this creates the correct theano.grad expression for you.

Yes! This was what I wanted to know. Sorry if my question is elementary, but from what I understand, switches store information of indices where the pooled activations come from, right ?  Is there a way to store/access these indices in theano?

**Comment by f0k** [comment]
> Sorry if my question is elementary, but from what I understand, switches store information of indices where the pooled activations come from, right ? Is there a way to store/access these indices in theano?

No, they're just a concept to understand what's going on. In practice, they're not explicitly computed and kept for the backward pass -- instead, the backward pass finds where to propagate output gradients to by comparing the forward pass inputs to the forward pass outputs.

**Comment by Sentient07** [comment]
Perfect! Thank you, Jan!

**Comment by fsalmasri** [comment]
@f0k I built a function to create switches and then give them to right place in the backward phase but the implementation was very slow. If I understood well from what you said that there is no need to implement these witches. Could you give me and example please ?

**Comment by f0k** [comment]
> If I understood well from what you said that there is no need to implement these witches.

Exactly. An efficient implementation already exists because it's needed for the max-pooling gradient.

> Could you give me and example please?

What are you trying to achieve?
