### ISSUE TITLE
AssertionError: ('max_abs_diff, max_rel_diff, n_in, n_hid', 0.66509819, 0.05018222, 1024, 1024)

### ISSUE THREAD

**Issue by ghost** [Theano/Theano#2047]
nosetests -s theano/sandbox/cuda/tests/test_mlp.py:test_run_nnet

Using gpu device 0: GeForce GTX 570
F
======================================================================
FAIL: theano.sandbox.cuda.tests.test_mlp.test_run_nnet
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_mlp.py", line 149, in test_run_nnet
    rel_diff.max(), n_in, n_hid)
AssertionError: ('max_abs_diff, max_rel_diff, n_in, n_hid', 0.66509819, 0.05018222, 1024, 1024)

----------------------------------------------------------------------
Ran 1 test in 7.333s

FAILED (failures=1)

Does this matter? How can I fix it?

**Comment by lamblin** [comment]
Further discussion in https://groups.google.com/d/topic/theano-users/2QNGmcFl9dI/discussion
The solution would be to try a different random seed in case of a failure, and only report a failure if a couple of them fail.
