### ISSUE TITLE
Do not insert the Softmax Op directly in the graph

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2050]
The `Softmax` Op has limitations (its gradient does not have a gradient implemented, only works on 2d tensors) which can be problematic when building the graph.
We have an equivalent expression using only elementary operations, and (I think) an optimization to replace that expression with `Softmax`.
We should:
- [x] check that the optimization correctly detects the softmax reformulation (e.g., that it is not disrupted by another optimization) (FB: I checked and we have them in the canonizer)
- [x] Make SoftmaxGrad.grad() return a graph that represent the gradient.
- [ ] make `theano.tensor.nnet.softmax` build that expression instead. (not sure it is good, this make the graph bigger and we are missing some opt for now).
- [ ] make test that the rop work for the graph.

See https://groups.google.com/d/topic/theano-dev/yV4QjxlPGiU/discussion

**Comment by nouiz** [comment]
```
_softmax = Softmax()
def softmax(c):
    return exp(c) / exp(c).sum(axis=1, keepdims=True)
```

need test that the 2n grad work and the R_op of the grad work on that graph.

**Comment by nouiz** [comment]
@lamblin I would close this. the softmax op have rop implemented. the softmaxgrad have grad implemented as a graph. So this cover all case we need.

I don't think we should replace the softmax call to build a graph instead of using the op.

**Comment by lamblin** [comment]
OK.
