### ISSUE TITLE
Add logaddexp as a binary elemwise, and logsumexp for its reduction

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2082]
NumPy implements it as:

```
@type@ npy_logaddexp@c@(@type@ x, @type@ y)
{
    const @type@ tmp = x - y;
    if (tmp > 0) {
        return x + npy_log1p@c@(npy_exp@c@(-tmp));
    }
    else if (tmp <= 0) {
        return y + npy_log1p@c@(npy_exp@c@(tmp));
    }
    else {
        /* NaNs, or infinities of the same sign involved */
        return x + y;
    }
}
```

We should also add the optimizations to automatically use it. Such an optimization already exists for the two-input case (inserting `log1p` directly), but not for the sum case (there is a `KnownFailureTest` already, but no implementation).

**Comment by abergeron** [comment]
The optimization should do automatically what is proposed in #1563.

We should also do something for adds with more than two inputs, possibly by reusing the above.

**Comment by nouiz** [comment]
done by gh-2430

**Comment by lamblin** [comment]
That PR actually closes a different ticket. Reopening.

**Comment by nouiz** [comment]
I think the solution in gh-1563 is better for logsumexp as @abergeron told. @lamblin if you can tell if you agree with that solution, it would be good. Or why this version would be better?

Pylearn2 have an implementation of gh-1563

**Comment by lamblin** [comment]
@nouiz I agree, this is a better solution.
However, as @abergeron wrote, we should also have a solution for multiple-inputs `Add` node, not only for the reduction (`Sum`).

**Comment by lamblin** [comment]
Done in #4736.
