### ISSUE TITLE
Profile slicing of CudaNdarrays in scan's Cython implementation

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2084]
It may do unnecessary transfers to the CPU.

**Comment by khaotik** [comment]
At least I can confirm there are no redundant host-device transfers for the new backend, however multiple small device-device transfer can also be an overhead. I've put details on #1168 thread.

**Comment by khaotik** [comment]
Is it okay to close this ticket?

**Comment by nouiz** [comment]
Good finding of this old issue. I would keep it open, even if for now we do
the discussion in the other issue.

**Comment by lamblin** [comment]
CudaNdarray has been removed and the discussion is going on at #1168, so I'm closing this one.
