### ISSUE TITLE
Scan allow_gc in the graph, but free after all the iteration

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2123]
This would remove much allocation without raising to much the max peak. Not enabled by default, but make it easy to use: a scan parameter and a Theano flag for the default value of this value. scan.allow_gc = {True,False,loop} where True, False are the normal behavior, loop is the behavior I describe.

**Comment by carriepl** [comment]
@nouiz according to your comment, this has been done. Can we close this issue?
