### ISSUE TITLE
Improve the Extending Theano tutorial

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#2133]
@vdumoulin went through the Extending Theano tutorial and raised the following points :

- There is a large conceptual gap between the examples given in the tutorial and the exercices
- The tutorial should a bit more to explain how to implement the required methods instead of always referring the user to the documentation, especially the make_node method which is very confusing for newcomers even with the documentation.

I personally agree with both points. For the second point, I understand this is probably meant to reduce the duplication of information to make the documentation easier to maintain. However, I still think it takes away from the tutorial if it can't be used as a stand-alone instruction tool.

@vdumoulin : did I miss anythin from your feedback?
@abergeron : just adding you to the conversation since it's likely we end up discussing stuff relevant to your CCW tutorial

**Comment by lamblin** [comment]
Fixed by #2191
