### ISSUE TITLE
Make the printing of Composite more readable.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2134]

**Comment by dwf** [comment]
@nouiz Can you be more specific about what the requirements are for this ticket?

CC @mohammadpz

**Comment by nouiz** [comment]
Here is an example of a composite op in the profile:

   0.0%   100.0%       0.018s       2.34e-05s     C      779        1
GpuElemwise{Composite{[Switch(i0, mul(true_div(i1, i2), i3),
true_div(mul(i4, i1), i2))]}}[(0, 1)]

The composite part is:

Composite{[Switch(i0, mul(true_div(i1, i2), i3), true_div(mul(i4, i1),
i2))]}

We need to change that section:

[Switch(i0, mul(true_div(i1, i2), i3), true_div(mul(i4, i1), i2))]

This is created by the method init_name in the file theano/scalar/basic.py,
in the class Composite.

I think I would reuse the pretty print (pprint) from theano/printing.py

This example would be more readable if it where:


[Switch(i0, (i1/ i2)* i3, (i4* i1)/ i2)]

**Comment by mohammadpz** [comment]
Okay.
This is what I got:
We can print a Composite using init_name method in basic.py which return a string.
But it prints is like : Composite{[Switch(i0, mul(true_div(i1, i2), i3), true_div(mul(i4, i1),
i2))]}
The objective is to print Switch like this:
[Switch(i0, (i1/ i2)* i3, (i4* i1)/ i2)]

Right?

My Questions:
1. How can I write a generic test case? I don't know how to print a Composite or how to create a Composite.
2. Do you mean PPrinter class? I could find something similar in that. What should I look for? Should print  "[Switch(i0, (i1/ i2)* i3, (i4* i1)/ i2)]" using the computational tree or just by processing this string "Switch(i0, mul(true_div(i1, i2), i3), true_div(mul(i4, i1),
i2))"?

Thanks 

@dwf @nouiz

**Comment by nouiz** [comment]
There is theano.printing.pprint() that could do what we want, if it return
a string. This is based on the PPrinter. You can call this on the internal
graph of the Composite.

**Comment by nouiz** [comment]
Done.
