### ISSUE TITLE
Tutorials : Add example of Op with custom __init__()

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#2144]
Add to the Theano tutorials an example of an Op where the behavior is influenced by arguments passed to its __init__().

**Comment by nouiz** [comment]
done with the props doc.

**Comment by Sentient07** [comment]
Have been wondering for a while, how you remember to come back to an issue immediately once its done, even if it is few years down the line :)

**Comment by nouiz** [comment]
We did a pass on some old issue to clean them up. That is how we found it. We will continue to do so once per week now to try to keep this more clean.
