### ISSUE TITLE
Optimization with elemwise comparison

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2160]
Started at:

https://github.com/nouiz/Theano/tree/elemwise_opt

need tests.

Old assembla case to also cover:

T.and(x,1) -> x
T.and(x,0) -> zeros_likes(x)
T.or(x,0) -> x
T.or(x,1) -> ones_likes(x)
T.xor(x,x) -> zeros_likes(x)
T.le(x,x) -> ones_likes(x)
T.ge(x,x) -> ones_likes(x)

**Comment by dwf** [comment]
@aalmah Am I right to understand that you're assigned to this ticket? How's it going?

**Comment by aalmah** [comment]
I have pushed some fixes last week and was waiting for Fred to review it.

**Comment by dwf** [comment]
Can you tell me where the pull request is? Fred's on vacation so I think I'm going to review it instead.

**Comment by aalmah** [comment]
https://github.com/Theano/Theano/pull/3173

**Comment by aalmah** [comment]
So do you think everything is OK?

**Comment by dwf** [comment]
Sorry, I will review it today.
