### ISSUE TITLE
Update Theano PyPi package

### ISSUE THREAD

**Issue by elliottjhill** [Theano/Theano#2163]
I noticed that the Theano package in PyPi was last updated on December 3th, 2013. Theres been a fair bit of development since then. Would it be possible to update the package in PyPi to a more recent stable release?

**Comment by lamblin** [comment]
Version 0.7rc2 is not on pypi, hopefully a released 0.7 will be there soon.

**Comment by nouiz** [comment]
Clarification, 0.7rc2 is on pypi, but pypi do not anymore download by
default the release candiate. So it still install by default 0.6 in some
version. To get the release candidate, add the --pre parameter to pip.

**Comment by cancan101** [comment]
Any way to get more regular releases of Theano to pypi? It has been ~10 months since the last release even though there has been a lot of work on the repos.
