### ISSUE TITLE
Make  Theano's max_pool_2d support strides and support padding with 0 (to support size preserving version)

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#2196]
Allow max_pool_2d (in theano.tensor.signal.downsample) to work with strides that differ from the size of the pooling region.

- [x] support stride
- [x] support pad

**Comment by nouiz** [comment]
Update, the support for stride on the CPU (with only python code) is merged.

**Comment by lamblin** [comment]
Padding was added in #2543.
