### ISSUE TITLE
On MemoryError report Theano's memory usage

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#2202]
When the execution of a Theano function aborts due to lack of memory, Theano should output the names, in-memory sizes and other attributes of the variables that are still allocated. This would help diagnose memory usage and where to put our efforts to make memory management smarter.

@nouiz Suggested to use printing.pydotprint() for this, to generate a png of the graph with color codes indicating variables that are still allocated.

**Comment by nouiz** [comment]
done. Follow up in gh-2606
