### ISSUE TITLE
Crash in a scan optimization 

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#2223]
Currently I don't have a small code sample to reproduce it. The traceback:

ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x4b2d2d0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 183, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 82, in optimize
    ret = self.apply(fgraph, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1558, in apply
    gopt.apply(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1558, in apply
    gopt.apply(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 1070, in apply
    self.process_node(fgraph, node)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 946, in process_node
    nw_input = scan_utils.expand(_nw_input, nw_steps)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_utils.py", line 364, in expand
    zeros_shape = [size + shapes[0]] + shapes[1:]
IndexError: list index out of range

**Comment by lamblin** [comment]
To summarize quickly the discussion I had with @bartvm today, it looks like the optimization may be assuming the input in question to come from some particular Op, which is not the case.
We could try to put a breakpoint in that optimization, and see what it is supposed to do in the intended case, provided that there is a test in the test suite.
However, this would not tell us why that optimization is mistaken (indexing error? new case producing a different kind of input?), or what the actual fix would be for sure.

**Comment by lamblin** [comment]
To summarize quickly the discussion I had with @bartvm today, it looks like the optimization may be assuming the input in question to come from some particular Op, which is not the case.
We could try to put a breakpoint in that optimization, and see what it is supposed to do in the intended case, provided that there is a test in the test suite.
However, this would not tell us why that optimization is mistaken (indexing error? new case producing a different kind of input?), or what the actual fix would be for sure.

**Comment by mjwillson** [comment]
Hi all -- I'm getting this error too from theano when using blocks to train a recurrent model. Or rather I see a bunch of error logging about it but then training seemingly proceeds regardless.

Is this something I should be worried baout / did you guys find a workaround?

**Comment by rizar** [comment]
You should not worry about it too much in a sense that training works perfectly despite this crash. Theoretically when it's fixed it might work faster though, I guess.

**Comment by nouiz** [comment]
Can you update Theano to the dev version? We fixed some type of error like
this recently. Maybe it is now fixed? Otherwise, @carriepl, is it the same
as the one you are already working on?

**Comment by carriepl** [comment]
Yes, this (optimizations errors with Theano when using Blocks) is exactly the issue @lamblin and I are working on in PR #2717.

**Comment by mjwillson** [comment]
I just tried installing theano from this PR branch and I'm no longer seeing the error, thanks!

**Comment by nouiz** [comment]
fixed year ago!
