### ISSUE TITLE
ImportError when importing Theano on Cygwin: No module named cutils_ext

### ISSUE THREAD

**Issue by Wainberg** [Theano/Theano#2253]
I just installed the trunk version of Theano (commit c416c5eb4e) on Cygwin and receive the error "ImportError: No module named cutils_ext" when importing Theano.  However, cutils_ext is correctly created and can be imported after the fact:

```
Python 2.7.8 (default, Jul 25 2014, 14:04:36)
[GCC 4.8.3] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "theano/__init__.py", line 72, in <module>
    from theano.scan_module import scan, map, reduce, foldl, foldr, clone
  File "theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "theano/scan_module/scan_opt.py", line 65, in <module>
    from theano import tensor
  File "theano/tensor/__init__.py", line 7, in <module>
    from theano.tensor.subtensor import *
  File "theano/tensor/subtensor.py", line 26, in <module>
    import theano.gof.cutils  # needed to import cutils_ext
  File "theano/gof/cutils.py", line 295, in <module>
    compile_cutils()
  File "theano/gof/cutils.py", line 260, in compile_cutils
    preargs=args)
  File "theano/gof/cmodule.py", line 2014, in compile_str
    return dlimport(lib_filename)
  File "theano/gof/cmodule.py", line 289, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: No module named cutils_ext
>>> import cutils_ext
>>> cutils_ext.__file__
'/home/User/.theano/compiledir_CYGWIN_NT-6.1-1.7.32-0.274-5-3-x86_64-64bit--2.7.8-64/cutils_ext/__init__.py'
>>> import os; os.listdir('/home/User/.theano/compiledir_CYGWIN_NT-6.1-1.7.32-0.274-5-3-x86_64-64bit--2.7.8-64/cutils_ext')
['cutils_ext.so', 'mod.cpp', '__init__.py', '__init__.pyc']
```

This may be related to [this StackOverflow post](http://stackoverflow.com/questions/11257284/cant-load-python-extension-module-that-exists) and [this earlier bug report](https://github.com/Theano/Theano/issues/728).

**Comment by nouiz** [comment]
I made a guess fix to theano in this PR:

https://github.com/Theano/Theano/pull/2413

Can you test it? To test it correctly, you need to delete Theano compiledir.

thanks

**Comment by Wainberg** [comment]
@nouiz It's still broken with the latest version of Theano.  I think that fix is incorrect because the extension should be dll for cygwin, not pyd.

**Comment by abergeron** [comment]
No, python uses .pyd for compiled modules on windows.  So the correct fix is to use that.

**Comment by Wainberg** [comment]
@abergeron Manually renaming the file to .dll worked for me, and .pyd didn't.

**Comment by nouiz** [comment]
Is it possible that the cygwin python doesn't work the same way as windows
python?

**Comment by abergeron** [comment]
Apparently, yes.  It's somewhat crippled in that only the fallback name (.dll) works for compiled modules.

**Comment by ih4cku** [comment]
@nouiz rename to `dll` also work with me. @Wainberg 's code is just fine.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/2990

@ih4cku, can you delete your theano cache and try this PR? Just to be sure I get it right. There is different case (like cuda_ndarray that is a python lib and a shared lib other python lib link again, a python lib that do not link to other dll, a python lib that link to cuda_ndarray, and finaly, like cuda_convnet, a dll lib, where python lib link again). I would like to be sure they are all fine with .dll.

thanks

**Comment by rilut** [comment]
Affects me as well, I'm on Windows 10 x64. It always fails whether I'm on Anaconda Python2 or Python3, installing from pip (0.7.0) or github (0.8.0-dev).

Btw, when I search `cutils*` in my Anaconda2 folder on Windows Explorer, I only found:
- cutils.pyc on C:\Anaconda2\Lib\site-packages\theano\gof
- cutils.py on C:\Anaconda2\Lib\site-packages\theano\gof
- cutils.pyd on C:\Anaconda2\Lib\site-packages\sqlalchemy

No other pyd/so/dll files

**Comment by darkaeon10** [comment]
I'm having the same problem as @rilut.

There is a 'cutils_ext.pyd' in 'C:\Users\user\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-3.5.2-64\cutils_ext'. 

Renaming that file to 'cutils_ext.dll' as suggested by @Wainberg  doesn't work for me. I also tried editing the get_lib_extension() function in cmodule.py accordingt o @Wainberg 's suggested fix, but still no luck. I'm on Windows 10 x64 by the way.

Any updates on this?

**Comment by nouiz** [comment]
The update would be to not use cygwin and use this PR with anaconda:

https://github.com/Theano/Theano/pull/5207

We didn't tested that with the GPU.

**Comment by rilut** [comment]
Hi, so it was 9 months after my comment and I couldn't remember if:
- I can solve that problem or not; or
- whether it's solved itself or by restarting; or
- it's the same problem with my current laptop. But I think it's the same `cutils_ext` problem


So, on my current laptop, I've failed to install Theano too.
Python said a `dll`/`pyd` missing, even though it exists when I opened it in Windows Explorer. When I copy-pasted and `cd`-ed the directory in the command prompt, it errors, because of... a space. Thus I realized, **the culprit was a space in the user path**.

So, Windows 10 sometimes use your full name as the name of your user folder. Instead the one word `rilut`, it used my full name.

I solved it with creating a new user account: without spaces and without logging in to my Windows ID.

**Comment by darkaeon10** [comment]
Whoa there, so spaces in the path are causing errors. Thanks for finding and sharing that @rilut ! I'll give it a try.

**Comment by rilut** [comment]
Ah, so it's a different problem with my current laptop then

**Comment by darkaeon10** [comment]
Yeah it seems so. Thanks for the help though @rilut !

**Comment by darkaeon10** [comment]
@nouiz , is it correct to simply replace the theano folder in the conda environment with the PR you referred me to?

**Comment by darkaeon10** [comment]
Just an update, I was able to fix my problem by setting-up theano using this tutorial: http://ankivil.com/installing-keras-theano-and-dependencies-on-windows-10/

I'm not too sure how this is different from installing through the conda command, but this time I created a .theanorc file with this line in the global setting: "base_compiledir=C:\theano_compiledir".

**Comment by nouiz** [comment]
We go to support mainly only Conda on Windows. Otherwise it is too much time consuming. We will accept PR to give better support for Cygwin, but we won't work on that.

**Comment by kwonmha** [comment]
well I got same kind of problem like this.
To me, If I open python and import theano on Anaconda prompt, it works well.
But it doens't on cmd of Windows.
>>> import theano
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cutils.py", line 305, in <module>
    from cutils_ext.cutils_ext import *  # noqa
ImportError: DLL load failed: 지정된 모듈을 찾을 수 업습니다.(The specified procedure could not be found.)

Isn't it able to import theano from cmd?

**Comment by lamblin** [comment]
I think the Anaconda prompt may add things to the PATH that make it possible to load the right dependencies for the DLL. Check the value of %PATH% in both consoles.
If you are not using cygwin, then your question is not related to that ticket.

**Comment by Gauproo** [comment]
hi, maybe it's not the  dll / pyd  missing , I got same kind of problem like this.
just copy the depending dll into the cutils_ext.pyd's path.
on my laptop is libgcc_s_seh-1.dll and libstdc++-6.dll.
this'is problem made me crazy.

**Comment by junyicai** [comment]
@Gauproo I met the same problem when compile with mingw. After copy  libstdc++-6.dll to cutils_ext.pyd's path, it works. Thanks for the solution. I wonder how to track the depending dll?

**Comment by Gauproo** [comment]
@junyicai ,Any PE file viewer would work. Just like Dependency Walker. Processhacker also has a module peview.
