### ISSUE TITLE
Remove equality checks between arrays and None

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2258]
There is a warning in NumPy 1.9 that the result of such comparisons will be an array instead of a Boolean in the future:
```
/Library/Python/2.7/site-packages/theano/tensor/opt.py:2165: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
```

**Comment by nouiz** [comment]
There is only a partial fix I think.

**Comment by carriepl** [comment]
As of now, Dmitriy ran all the Theano unit tests in every possible combination of {debugmode, defaultmode}x{cpu,gpu}. For every warning he encountered, he did a pull request and all 3 of his PR (#2308, #2392, #2409) were merged. Do you ( @nouiz , @lamblin and/or @abergeron  ) see something else that should be done before we consider this issue resolved?

**Comment by nouiz** [comment]
I think this is good.

**Comment by abergeron** [comment]
I have no objections.

**Comment by nouiz** [comment]
I so close this issue.
