### ISSUE TITLE
Implement GpuAdvancedSubtensor

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2267]
See: https://groups.google.com/d/msg/theano-users/2bcqrJr_-qQ/us8wV0RRLGkJ

Some possible work around if you need this:

if you need:

```
import numpy, theano, theano.tensor as T

a = theano.shared(numpy.asarray([1,3,4], dtype='int32'), borrow=True)
b = theano.shared(numpy.asarray([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]], dtype='int32'), borrow=True)

b[a,1:3].eval()
```

You can use:

```
b[:,1:3][a].eval()
```

We should also implement an optimization that will do the reverse when we implement GpuAdvancedSubtensor to have old code get the speed up.

**Comment by lamblin** [comment]
Done in the new back-end by #4763.
