### ISSUE TITLE
Unpickled function does not update shared variables

### ISSUE THREAD

**Issue by y0ast** [Theano/Theano#2288]
I have a function that computes a gradient and updates the parameters via the updates functionality of theano.function. The parameters updated are all shared variables.

When I load the saved pickle of this function to avoid rebuilding the graph, it does not update my shared variables. I figure this is because the new shared variables I created are not at the same place in memory as those stored in the pickle.

I have thought about this problem for a while, but cannot think of a smart way of solving it. Maybe add a parameter that passes a list to theano.function and theano.function tries to replace shared variables in the graph with the ones from the list when they have the same name (the parameter name from theano.shared).

I know this is a problem for a few others and wonder if there is a good way to resolve it.

**Comment by nouiz** [comment]
Who else have this problem? Maybe working in a different way could solve the problem.

Pickling all related theano function together and reloading them together should work. As the new shared variable will be shared between all the unpickled function that way.

Do this solve your problem?

Othewise, we could make a method to Theano function to "swap" the shared variable.

**Comment by y0ast** [comment]
How do I pickle the shared variables together with the theano function?

I can put all the variables and the gradientfunction in a tuple and pickle the tuple. Although that seems a bit odd to do.

**Comment by nouiz** [comment]
That would work. You can use a list or dict if you prefer. You can create a class and put  them as member too.

**Comment by locriti** [comment]
Hi @y0ast, would you mind sharing the code you used to resolve this?

**Comment by nouiz** [comment]
Just pickle a tuple or a list where you error so the functions and shared
variable you want at the same time. Then when you unpickle, this will give
you ready access to the new shared variables that are unpickled.

**Comment by y0ast** [comment]
I don't pickle theano functions anymore. Their compilation is cached which turned out to be fast enough in practice :)
