### ISSUE TITLE
Document python3 installation

### ISSUE THREAD

**Issue by goodfeli** [Theano/Theano#2317]
The installation instructions don't specify how to install on python3, which is confusing. The instructions make it sound like if you have python3 installed then pip will automatically be linked to python3 and you can run "sudo pip install Theano". That is not really accurate.

"sudo apt-get install python-pip" will install a version of pip linked to python2 regardless of whether you have python3 installed. You need to run "sudo apt-get install python3-pip". You also need to explicitly run "pip3". pip will continue to be pip2, or at least it is on my machine.

To install Theano I had to get the right command from Pylearn2's travis installation script and then explicit invoke pip3:
sudo pip3 install -q --no-deps git+git://github.com/Theano/Theano.git

**Comment by nouiz** [comment]
We now have single code base for python2 and 3. So nothing special todo now.

**Comment by Girmaw** [comment]
Thanks! That was very helpful.
