### ISSUE TITLE
MRG_RandomStreams memory leak

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#2335]
@craffel and me distilled out a memory leak in `MRG_RandomStreams`:

``` python
import theano
srng = theano.sandbox.rng_mrg.MRG_RandomStreams()
inp = theano.tensor.matrix()

for n in xrange(10):
    print 'Call %d, before: %f MiB free' % (n,
        theano.sandbox.cuda.cuda_ndarray.cuda_ndarray.mem_info()[0] / 1024.**2)
    outp = srng.binomial(inp.shape, p=0.5, dtype=theano.config.floatX)
    print 'Call %d, after:  %f MiB free' % (n,
        theano.sandbox.cuda.cuda_ndarray.cuda_ndarray.mem_info()[0] / 1024.**2)
```

I get:

```
$ THEANO_FLAGS=device=gpu,floatX=float32,allow_gc=1 python leak.py
Using gpu device 0: GeForce GT 640
Call 0, before: 1212.519531 MiB free
/raid/user/jan/install/Theano-git/theano/sandbox/rng_mrg.py:1195: UserWarning: MRG_RandomStreams Can't determine #streams from size (Shape.0), guessing 60*256
  nstreams = self.n_streams(size)
Call 0, after:  1211.519531 MiB free
Call 1, before: 1211.519531 MiB free
Call 1, after:  1211.519531 MiB free
Call 2, before: 1211.519531 MiB free
Call 2, after:  1210.519531 MiB free
Call 3, before: 1210.519531 MiB free
Call 3, after:  1210.519531 MiB free
Call 4, before: 1210.519531 MiB free
Call 4, after:  1209.519531 MiB free
Call 5, before: 1209.519531 MiB free
Call 5, after:  1209.519531 MiB free
Call 6, before: 1209.519531 MiB free
Call 6, after:  1208.519531 MiB free
Call 7, before: 1208.519531 MiB free
Call 7, after:  1208.519531 MiB free
Call 8, before: 1208.519531 MiB free
Call 8, after:  1207.519531 MiB free
Call 9, before: 1207.519531 MiB free
Call 9, after:  1207.519531 MiB free
```

That is, every second call, one megabyte of GPU memory is gone. (It's freed when the process exits.)

When I use a smallish fixed shape such as `(100, 100)` instead of `inp.shape`, the memory leak disappears. When I use a largish shape such as `(1000, 1000)`, the memory leak reappears.

**Comment by lamblin** [comment]
I think the following use cases existed when this was implemented:
- reset the value of the random states for each variables created by a certain RandomStreams,
- have a way of sampling more than once (in succession) from the same sample, in the same function, by sampling from the updated random state and chaining the updates.

The first case is encapsulated by the `seed` method, so making `state_updates` private could still be done.
The second case is uncommon at least, and can also be done by accessing the random state variable and its `default_update` or `out` members.

However, I just realized a potential case for surprising behaviour if the `seed` method is called after some variables are deleted:
```Python
r = RandomStreams(42)
f = theano.function([], r.uniform())
f()  # array(0.3765878540723824)
g = theano.function([], r.uniform())
g()  # array(0.1860074959478063)
r.seed()
f ()  # array(0.3765878540723824)
g()  # array(0.1860074959478063)
def f
g()
```
Currently, it gives the same result as before (`array(0.1860074959478063)`), but if `u` is removed from `r.default_updates`, then calling `g()` again will return the value that used to be sampled from `f()` (`array(0.3765878540723824)`).
It may even give different results depending on whether the garbage collector has been called or not yet, which may make things much harder to trace and debug.

We could simply record the initial random seed for each distribution, but then it would still be problematic when calling `r.seed(42)` or `r.seed(43)` explicitly.

**Comment by nouiz** [comment]
I think the numpy random numbers have the same problem.

**Comment by f0k** [comment]
@lamblin: Was this solved or just abandoned?

**Comment by nouiz** [comment]
I would keep that open. I think it isn't fixed and still need to be fixed, even if low priority. @lamblin is doing a clean up of the issue. Let's wait why he closed it.

**Comment by f0k** [comment]
An intermediate solution might be to document it -- either in a memory use / memory leak FAQ, or wherever symbolic random variables are explained (i.e., document that any call to `binomial`, `uniform` etc. will allocate a bit of memory that is only freed when the random streams instance is deleted).
