### ISSUE TITLE
Document addbroadcast, unbroadcast and patternbroadcast

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2337]

**Comment by senarvi** [comment]
Both addbroadcast() and unbroadcast() give the same example:

    For example, addbroadcast(x, 0) will make the first dimension
    of x broadcastable. When performing the function, if the length
    of x along that dimension is not 1, a ValueError will be raised.

patternbroadcast() describes broadcastable argument like this:

    an iterable object such as list or tuple of bool values
    A set of boolean values indicating whether a dimension should be
    broadcastable or not. If the length of x along these dimensions is
    not 1, a ValueError will be raised.

It's not clear which dimension of x should have length 1, broadcastable or not broadcastable.
