### ISSUE TITLE
Better scan debugprint (show link with the outer graph)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2347]

**Comment by abergeron** [comment]
This means noting what node id each scan corresponds to when its graph is printed.

**Comment by carriepl** [comment]
Included is the output of debugprint for the Theano function compiled in the first example of the Scan documentation (http://deeplearning.net/software/theano/library/scan.html). Based on Arnaud's description, it looks like the required feature is already implemented as both mentions of the scan node share the same ID : [@B]. Am I missing something?

Subtensor{int64} [@A] ''   13
 |forall_inplace,cpu,scan_fn} [@B] ''   12
 | |Elemwise{Composite{minimum(((i0 + i1) - i1), i2)}} [@C] ''   4
 | | |Elemwise{Composite{Switch(LT(i0, i1), (i0 + i2 + i3), i0)}} [@D] ''   2
 | | | |Elemwise{Composite{Switch(LT((i0 - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0))), i2), (i3 + (-(i1 + i0))), Switch(GE((i0 - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0))), ((i1 + i0) - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0)))), (i4 + i0), Switch(LE(((i1 + i0) - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0))), i2), (i4 + i0), Identity(i0))))}} [@E] ''   0
 | | | | |k [@F]
 | | | | |TensorConstant{1} [@G]
 | | | | |TensorConstant{0} [@H]
 | | | | |TensorConstant{-1} [@I]
 | | | | |TensorConstant{2} [@J]
 | | | |TensorConstant{0} [@H]
 | | | |TensorConstant{1} [@G]
 | | | |k [@F]
 | | |TensorConstant{1} [@G]
 | | |k [@F]
 | |IncSubtensor{InplaceSet;:int64:} [@K] ''   11
 | | |Alloc [@L] ''   10
 | | | |TensorConstant{0.0} [@M]
 | | | |Elemwise{Composite{(Switch(LT(i0, i1), (i0 + i2), (i0 - i3)) + i4)}}[(0, 0)] [@N] ''   8
 | | | | |Elemwise{Composite{maximum(((i0 - Switch(LT(i1, i2), (i1 + i3 + i4), i1)) + i5), i5)}}[(0, 1)] [@O] ''   6
 | | | | | |Elemwise{Composite{minimum(((i0 + i1) - i1), i2)}} [@C] ''   4
 | | | | | |Elemwise{Composite{Switch(LT((i0 - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0))), i2), (i3 + (-(i1 + i0))), Switch(GE((i0 - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0))), ((i1 + i0) - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0)))), (i4 + i0), Switch(LE(((i1 + i0) - Composite{Switch(LT(i0, i1), i0, i1)}(i1, (i1 + i0))), i2), (i4 + i0), Identity(i0))))}} [@E] ''   0
 | | | | | |TensorConstant{0} [@H]
 | | | | | |TensorConstant{1} [@G]
 | | | | | |k [@F]
 | | | | | |TensorConstant{1} [@G]
 | | | | |TensorConstant{1} [@G]
 | | | | |TensorConstant{1} [@G]
 | | | | |TensorConstant{1} [@G]
 | | | | |TensorConstant{1} [@G]
 | | | |Shape_i{0} [@P] ''   1
 | | |   |A [@Q]
 | | |Rebroadcast{0} [@R] ''   5
 | | | |Alloc [@S] ''   3
 | | |   |TensorConstant{(1, 1) of 1.0} [@T]
 | | |   |TensorConstant{1} [@G]
 | | |   |Shape_i{0} [@P] ''   1
 | | |Constant{1} [@U]
 | |A [@Q]
 |ScalarFromTensor [@V] ''   9
   |Elemwise{Composite{(((i0 - i1) - i2) + i3)}}[(0, 0)] [@W] ''   7
     |Elemwise{Composite{Switch(LT(i0, i1), (i0 + i2 + i3), i0)}} [@D] ''   2
     |Elemwise{Composite{minimum(((i0 + i1) - i1), i2)}} [@C] ''   4
     |TensorConstant{1} [@G]
     |Elemwise{Composite{maximum(((i0 - Switch(LT(i1, i2), (i1 + i3 + i4), i1)) + i5), i5)}}[(0, 1)] [@O] ''   6

Inner graphs of the scan ops:

forall_inplace,cpu,scan_fn} [@B] ''   
 >Elemwise{mul,no_inplace} [@X] ''   
 > |<TensorType(float64, vector)> [@Y]
 > |A_copy [@Z]

**Comment by abergeron** [comment]
Please post debugprint outputs (and other similar things) between triple quotes (\`\`\`) to avoid github-tagging everybody who has a letter-of-alphabet account. (and sometimes two-letters for big graphs)

You can use single quotes (\`) for small inline references in a paragraph like the `[@B]` above.

It also makes it more readable since it was designed for a fixed-size font.

**Comment by nouiz** [comment]
The problem is that the input to scan have no link to what they are taken
from in the outer graph. So this is those line that need change:

```

 > |<TensorType(float64, vector)> [@Y]
 > |A_copy [@Z]

```
