### ISSUE TITLE
auto var name based on user code.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2354]
This come up frequently and came again today.

We should investigate if we can reuse the variable name from the user.

Maybe we could try to parse the stack trace like when we print back-trace:

Backtrace when the node is created:
  File "test0.py", line 8, in <module>
    z = z + y

We could check if the line contain an =, and take the part on the left. This do not work for multi-line statement and could give some wrong name. But I think it is better then nothing. Maybe there is something better.

**Comment by lamblin** [comment]
What was reasonable was done in #2398 (give an ID to variables).
I don't think we should do more (even if we could, for instance by using introspection).
