### ISSUE TITLE
wrap fbcufft (fft convoluation that is much faster then our version

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2366]
fbcufft's source is here btw: https://github.com/facebook/fbcunn/tree/master/src/cuda/fft

Some not final benchmark: https://gist.github.com/soumith/e6297e93dd2fe3751562

More info in this threads: https://github.com/soumith/convnet-benchmarks/issues/35#issuecomment-67703097

**Comment by lamblin** [comment]
I think that cuDNN now is at least as fast, so I propose we close this ticket.

**Comment by nouiz** [comment]
agreed.
