### ISSUE TITLE
GpuReshape do not have c code

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2369]
I saw a profile where it was taking ~10% of the run time, mostly due to the overhead.

As we are in the transition to the new back-end, we could just implement it there. The current and the new back-end do not have c code for this op.

**Comment by carriepl** [comment]
After discussion at the CCW meeting today, we decided it should be done in both GPU backends. The C code of the CPU version can be used as inspiration.

**Comment by nouiz** [comment]
Just to clarify, there is already some c function that do it, so no need to
implement the logic itself. Just call the right function with the right
parameter.
