### ISSUE TITLE
Python 3 support is broken

### ISSUE THREAD

**Issue by jfsantos** [Theano/Theano#2370]
As far as I know, Theano uses `2to3` to convert syntax to Python 3 upon install. I have just installed it under Python 3.4.3, but when trying to import it I got an error related to Python 2 syntax: 

```
In [1]: import theano
  File "/Users/jfsantos/Projects/Theano/theano/__init__.py", line 153
    except Exception, e0:
                    ^
SyntaxError: invalid syntax
```

I fixed this by hand, but only to get a crash due to incompatible syntax somewhere else (for example, references to `basestring`). Maybe this is just `2to3` not working as it is supposed to?

**Comment by abergeron** [comment]
You have to run the setup.py file to install theano in order to use it in python 3.  This looks like you used it from the checkout or tarball.

**Comment by jfsantos** [comment]
It seems I made a mistake indeed. Even though I ran this after calling `python setup.py install`, I was inside the Theano folder and Python gave priority to the local folder over the install folder. Sorry for the noise.
