### ISSUE TITLE
deeplearning.net is down

### ISSUE THREAD

**Issue by bobpoekert** [Theano/Theano#2373]
At the moment it's not possible to read theano tutorials or documentation, or to download theano (except from github). http://isup.me/www.deeplearning.net that it's down, and by browser complains about not being able to open a connection.

**Comment by abergeron** [comment]
Thanks for the report. We are working on it.

Next time, please use the mailing lists instead of github tickets for website problems.

**Comment by nouiz** [comment]
For the record, it is fixed.

**Comment by Infiltra** [comment]
2 Questions
1. Is the project still under development?
2. Why is it down?
