### ISSUE TITLE
CudaNdarray_get_dev_data and CudaNdarray_set_dev_data are dealing with truncated pointer in windows 64bit.

### ISSUE THREAD

**Issue by bloodmage** [Theano/Theano#2374]
When interacting with other library (such as scikits.cuda), these function gives truncated lower-32bit value of device pointer, which gives wrong result.

Code to reproduce error:

    import os
    import theano
    import theano.tensor as T
    import theano.sandbox.cuda.fftconv
    import numpy as np
    if __name__=="__main__":
        obj = T.tensor3()
        cufftop = theano.sandbox.cuda.fftconv.cufft(obj)
        f = theano.function([obj],[cufftop])
        print "STAGE"
        inpd = np.array([
            [
                [1,2,3,4],
                [5,6,7,8]],
            [
                [9,10,11,12],
                [13,14,15,16]]],'f')
        print f(inpd)

A temporary fix:

    static PyObject *
    CudaNdarray_get_dev_data(CudaNdarray *self, void *closure)
    {
        float * p =  CudaNdarray_DEV_DATA(self);
        //printf("get_dev_data %p %li \n", p, (long int)p );
        return PyInt_FromSize_t((size_t) CudaNdarray_DEV_DATA(self));
    }
    
    static int
    CudaNdarray_set_dev_data(CudaNdarray *self, PyObject *value, void *closure)
    {
        Py_ssize_t newdevdata = PyInt_AsSsize_t(value);
        //printf("set_dev_data %p %li \n",(float*)newdevdata ,newdevdata);
        if (PyErr_Occurred())
        {
            return -1;
        }
        return  CudaNdarray_set_device_data(self, (float*)newdevdata, (CudaNdarray*)self->base);
    }

**Comment by abergeron** [comment]
Can you make a PR out of that?

**Comment by nouiz** [comment]
I made a PR with your fix. Thanks.
