### ISSUE TITLE
Finish/merge in Theano batched gemm on GPU 

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2378]
https://github.com/benanne/theano_wmf/blob/master/ops.py

which I found in this thread:
https://groups.google.com/forum/#!searchin/theano-users/batched$20dot/theano-users/NpO2uG0d9uo/GzFdaIdd7FIJ

- move to: theano/sandbox/cuda/blas.py
- make sure there is tests in test_blas.py for it
- remove make_thunk and make c code.
- later, remove gpu contiguous?

**Comment by briancheung** [comment]
Just wanted to check in to see if there needs to be anything done for this. Batched gemm seems like a much better solution for batched_dot rather than using a scan.

**Comment by benanne** [comment]
Afaik no work has been done for this so far (but the Theano devs should correct me if I'm wrong). A version of this op with C-code as part of Theano would be awesome! And it would speed up the FFT convolution a bit as well, probably :)

**Comment by bouthilx** [comment]
It should be done in the next two weeks.

**Comment by nouiz** [comment]
Module insertitute with NIPS deadline... But it is on our short term plan.
