### ISSUE TITLE
automatique theano variable id

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#2384]
Add a mechanism to automatically assign a sequentially generated name/id to a theano variable at creation. This should be done in the `__init__()` function so that invoking `copy()` will return a variable with the same id as the original but invoking Theano's `clone()` function will return a variable with a new id (because `clone()` creates a new variable).

**Comment by nouiz** [comment]
Verify that each subclass of Variable (and Constant) call __init__.

**Comment by carriepl** [comment]
This has been addressed by pull requests #2398 and  #2438. Closing the issue.
