### ISSUE TITLE
identifier "PyInt_FromLong" is undefined

### ISSUE THREAD

**Issue by ziyuang** [Theano/Theano#2387]
OS: Ubuntu 14.04
Theano: 5ec4c302
Python: 3.4.0

The error occurs when running `theano.test()`:

    mod.cu (57): error: identifier "PyInt_FromLong" is undefined

It may be necessary to change from `PyInt_FromLong` to `PyLong_FromLong` according to [this post](http://python3porting.com/cextensions.html).

**Comment by abergeron** [comment]
Normally we include "numpy/npy_3kcompat.h" which takes care of all this.  But it seems you have a module which does not.  Can you run `theano-nose -v --theano` and give us the name of the test that fails.

**Comment by nouiz** [comment]
I saw this with a grep in the cudnn stuff.

**Comment by abergeron** [comment]
Yep, but the "fix" is in cuda_ndarray.cuh so we should have it there.

**Comment by nouiz** [comment]
It is in the op DnnVersion. It do not include cuda_ndarray.cuh.

I did a PR to fix this. @ziyuang, can you try it to confirm that it work:

https://github.com/Theano/Theano/pull/2399

**Comment by ziyuang** [comment]
There is an error `mod.cu(2734): error: identifier "PyInt_FromSize_t" is undefined` which fails the `nvcc` compilation.

There are also a number of warnings on macro redefinitions:

    /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:17:0: warning: "PyString_Check" redefined [enabled by default]
     #define PyString_Check PyUnicode_Check
     ^
    In file included from /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                     from mod.cu:9:
    /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:63:0: note: this is the location of the previous definition
     #define PyString_Check PyBytes_Check
     ^
    In file included from mod.cu:9:0:
    /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:18:0: warning: "PyString_FromString" redefined [enabled by default]
     #define PyString_FromString PyUnicode_FromString
     ^
    In file included from /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                     from mod.cu:9:
    /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:65:0: note: this is the location of the previous definition
     #define PyString_FromString PyBytes_FromString
     ^
    In file included from mod.cu:9:0:
    /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:19:0: warning: "PyString_AsString" redefined [enabled by default]
     #define PyString_AsString PyUnicode_AsUTF8
     ^
    In file included from /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                     from mod.cu:9:
    /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:72:0: note: this is the location of the previous definition
     #define PyString_AsString PyBytes_AsString
     ^
    In file included from mod.cu:9:0:
    /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:20:0: warning: "PyString_FromStringAndSize" redefined [enabled by default]
     #define PyString_FromStringAndSize PyUnicode_FromStringAndSize
     ^
    In file included from /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                     from mod.cu:9:
    /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:66:0: note: this is the location of the previous definition
     #define PyString_FromStringAndSize PyBytes_FromStringAndSize
     ^
    In file included from mod.cu:9:0:
    /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:21:0: warning: "PyString_Size" redefined [enabled by default]
     #define PyString_Size PyUnicode_GET_SIZE
     ^
    In file included from /usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda/cuda_ndarray.cuh:11:0,
                     from mod.cu:9:
    /usr/local/lib/python3.4/dist-packages/numpy/core/include/numpy/npy_3kcompat.h:74:0: note: this is the location of the previous definition
     #define PyString_Size PyBytes_Size
     ^

**Comment by nouiz** [comment]
this is new macro defined in newer numpy version. We needed them in the
past, so we created them, but now numpy added them.

Which version of numpy do you use? My guess is that you can ignore those
warning. Do the rest seem to work?

**Comment by ziyuang** [comment]
> Which version of numpy do you use?

Numpy 1.9.1

> Do the rest seem to work?

No, the error `identifier "PyInt_FromSize_t" is undefined` makes `nvcc` fail (while the test is going normally under Python 2.7):

1 error detected in the compilation of "/tmp/tmpxft_00004fee_00000000-8_mod.cpp1.ii".

    ['nvcc', '-shared', '-O3', '-use_fast_math', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mf6d896860391dd5093b721c63a0b2b33,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC', '-Xlinker', '-rpath,/home/ubuntu/.theano/compiledir_Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.0-64/cuda_ndarray', '-I/usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda', '-I/usr/local/lib/python3.4/dist-packages/numpy/core/include', '-I/usr/include/python3.4m', '-o', '/home/ubuntu/.theano/compiledir_Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.0-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/usr/lib', '-lpython3.4m', '-lcublas', '-lcudart']
    ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -use_fast_math -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mf6d896860391dd5093b721c63a0b2b33,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC -Xlinker -rpath,/home/ubuntu/.theano/compiledir_Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.0-64/cuda_ndarray -I/usr/local/lib/python3.4/dist-packages/Theano-0.6.0-py3.4.egg/theano/sandbox/cuda -I/usr/local/lib/python3.4/dist-packages/numpy/core/include -I/usr/include/python3.4m -o /home/ubuntu/.theano/compiledir_Linux-3.13.0-44-generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-3.4.0-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/usr/lib -lpython3.4m -lcublas -lcudart')
    WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: cuda unavilable)

**Comment by ziyuang** [comment]
But it still reports `error: identifier "PyInt_FromSize_t" is undefined`.

**Comment by abergeron** [comment]
It closed automatically since I merged #2399, but I agree it is not completely fixed.

**Comment by HapeMask** [comment]
It looks like numpy/npy_3kcompat.h doesn't define PyInt_FromSize_t as PyLong_FromSize_t like it should (could?). Adding

    #define PyInt_FromSize_t PyLong_FromSize_t

in the compatibility section of cuda_ndarray.cuh is one way to fix it.

**Comment by abergeron** [comment]
Yes that would fix it.  Can you make a PR?

**Comment by ziyuang** [comment]
Oops I tried adding it in the function `c_support_code` of `dnn.py` but had no luck.

**Comment by ziyuang** [comment]
Oops I tried adding it in the function `c_support_code` of `dnn.py` but had no luck.
