### ISSUE TITLE
Possible in documentation "Extending Theano"

### ISSUE THREAD

**Issue by jfmackay** [Theano/Theano#2422]
I believe some sample code is broken on this page: 
    http://deeplearning.net/software/theano/tutorial/extending_theano.html

In the Op Example code the line below causes an error:
    assert hasattr(self, '_props')

Not sure if this was the original intention but changing it to:
    assert hasattr(self, '__props__')

seems to make it work.

**Comment by abergeron** [comment]
The code is not broken, the assert is there to ensure your theano version
is recent enough (and actually supports __props__).

If the assert fires, that means your theano version is too old (probably
the 0.6 release which didn't have __props__).

Try updating to the latest master:
http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

2015-01-20 3:21 GMT-05:00 jfmackay <notifications@github.com>:
