### ISSUE TITLE
`numpy.indices` equivalent not found

### ISSUE THREAD

**Issue by xiaohan2012** [Theano/Theano#2433]
Hi,

It would be great if `numpy.indices` equivalent is found in theano.

**Comment by nouiz** [comment]
It is not done. There is a ticket about this, so I'll close this one: gh-1916.


Do you need the grad for this op? Is not, you can do it rapidly via as_op: http://deeplearning.net/software/theano/tutorial/extending_theano.html#as-op

If you have questions, do not hesitate.

**Comment by lamblin** [comment]
There is no gradient that makes sense for `indices`, the complete implementation would return `disconnected_gradient`, so using `as_op` would make sense.
