### ISSUE TITLE
Theano conv2d crashes 

### ISSUE THREAD

**Issue by guillempalou** [Theano/Theano#2435]
Hi,

I am encountering a similar issue as: https://github.com/Theano/Theano/issues/1547
I am running Theano 0.6.0 on a Macbook pro retina with the following specs:

Yosemite 10.10.1
2.3GHz Intel Core i7
16GB ram
NVIDIA GeForce GT 750M 2048 MB

I'm trying to run the code of convolutional_mlp.py but keep getting crashes on the GPU. The same code on the CPU runs fine. And the Logistic regression and the MLP also run fine on the GPU. 
I modified the convolutional  example so it prints the input variables and output variabels for each apply node and run the example using cuda-memcheck. 

The first number is the apply node number, in this case the number 47.

(47, GpuConv{valid, (1, 1), None, (5, 5), True, (20, 12, 12), (5, 5)}(GpuElemwise{Composite{[tanh(add(i0, i1))]},no_inplace}.0, <CudaNdarrayType(float32, 4D)>))
('input(s) value(s):', [<CudaNdarray object at 0x11ecfd330>, <CudaNdarray object at 0x10cb12e30>])
========= Error: process didn't terminate successfully
=========        The application may have hit an error when dereferencing Unified Memory from the host. Please rerun the application under cuda-gdb or Nsight Eclipse Edition to catch host side errors.
========= ERROR SUMMARY: 0 errors

Theoretically, after the line 'input(s) value' there should be a line printing the output values.  I've done some experiments and the GpuConv call also fails for the 'full' mode.

Did anyone encounter the same issue?

**Comment by nouiz** [comment]
Hi

You probably use Theano 0.6 (the last release). The development version
(that is pretty stable) use new code that is much faster. So I would
recommand strongly that you update Theano:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

That should make the convolution on the GPU faster and fix this problem.
I'll close this ticket now as I'm pretty sure that this will fix it. If
not, tell us and reopen the ticket.

**Comment by guillempalou** [comment]
I installed the bleeding edge version and it seems fixed! Now the convolutional code from the examples runs without problems.

Thanks!
