### ISSUE TITLE
Check that size and stride information in error message is correct with MonitorMode

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2452]
Here is an example producing a strange error message: https://gist.github.com/lzamparo/8a92e1f57c3e89d1569e

Discussion thread: https://groups.google.com/d/topic/theano-users/7EH_URy5dk8/discussion

Relevant part:
```
Apply node that caused the error: RandomFunction{binomial}(<RandomStateType>, Elemwise{Cast{int32}}.0, TensorConstant{1}, TensorConstant{1.0})
Inputs shapes: [(911, 800), (1, 1), 'No shapes', 'No shapes']
Inputs strides: [(800, 1), (0, 0), 'No strides', 'No strides']
Inputs types: [<theano.tensor.raw_random.RandomStateType object at 0x5e23750>, TensorType(int32, vector), TensorType(int8, scalar), TensorType(float32, scalar)]
```
We would expect that the `RandomStateType` has no shape, the vector has a shape of length 1, and the scalars of length 0, but it is not what gets displayed.

**Comment by nouiz** [comment]
In the gist, there is 2 python file. When I run the one you link, nothing
happen as it only define class.

The second one ran, but crash as it miss import. If I comment them, it try
to open a file that do not exist.

**Comment by lamblin** [comment]
@nouiz I think you need to download both at the same place, and `ReLU_vs_GB_test.py` imports from `AutoEncoder.py`.
@lzamparo: Can you edit your code so that it does not need an external hd5 file, but works on random data of the appropriate shape?

**Comment by nouiz** [comment]
I made a PR with the fix I suggested:

https://github.com/Theano/Theano/pull/2477

This add a fct that always contan the suggested detect_nan methods.

**Comment by lamblin** [comment]
@nouiz That PR fixes the original issue reported, for NaN detection.
However, does it address the issue of the *inaccurate size and stride* reported in the error message?

**Comment by nouiz** [comment]
It do not fix the inaccurate error message. That is why I didn't closed
this issue.

I have a few other stuff todo. Hopefully I can do it this week.

**Comment by lamblin** [comment]
OK, thanks for the clarification.

**Comment by lzamparo** [comment]
Sorry for the delay, I've updated the gist to use random data, and removed the extraneous imports.  Let me know if you still can't run it.

**Comment by nouiz** [comment]
I'm able to reproduce it with this:

THEANO_FLAGS=device=gpu,floatX=float32 python ReLU_vs_GB_test.py --dir=. --corruption=.2

**Comment by nouiz** [comment]
I got the fix: https://github.com/Theano/Theano/pull/2486

thanks for the test case.
