### ISSUE TITLE
Inconsistency between consider_constant and consider_constant()

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#2454]
Currently, `tensor.grad()` has a `consider_constant` parameter which forces Theano to consider certain variables as if they were constant for the purposes of gradient back-propagation (meaning that no gradient will be back-propagated through those variables). There is also a `consider_constant()` function in theano.gradient. That function however, has a different behavior than the the `consider_constant` argument. Instead of making the gradient return an instance of DisconnectedType (which would prevent back-propagation of the gradient), it returns 0 which Theano which Theano will attempt to back propagate. The result is that both elements have the same name but very different behaviors.

I spoke with @nouiz and he suggested deprecating the `consider_constant()` function and implementing a `zero_grad()` and a `disconnected_grad()` functions which would respectively implement the current functionality of `consider_constant()` and implement a functionality equivalent to the argument `consider_constant()`. @lamblin , what's your opinion about this?

**Comment by benanne** [comment]
This difference was noticed when I initially implemented this, but it was decided that returning 0 was better ( https://github.com/Theano/Theano/pull/1755#issuecomment-36635978 ). But I suppose that isn't necessarily the case and providing both options is definitely the best solution.

**Comment by carriepl** [comment]
Thanks for the info. Tagging @abergeron to get his input.

**Comment by abergeron** [comment]
No objection to the rename (with a reasonable deprecation period).  We
shouldn't delete it before the 0.7 release though.

As for disconnected_grad() I think it might be useful in some cases to
ensure that gradient does not flow toward certain things.

2015-01-30 11:09 GMT-05:00 carriepl <notifications@github.com>:

**Comment by lamblin** [comment]
I'm OK with that plan.

**Comment by nouiz** [comment]
Done.
