### ISSUE TITLE
function of vector throws TypeError if evaluated at single number

### ISSUE THREAD

**Issue by MaxNoe** [Theano/Theano#2457]
Consider following code:

```{python}
from theano.tensor import vector, exp
from theano import function
x = vector("x")
f = function([x], exp(x))
f(1)
```

It throws an error because it expects an 1-dimensional input for the vector x. 
This is rather inconvinient and should be easily changeable, as a single number could easily interpreted as length-one-vector.

All numpy functions accept single numbers.

**Comment by nouiz** [comment]
To get the most speed up, we need to limit how much pythonic Theano is. Sadly we can't get both in this case. If we make it more python, it will be slower.
