### ISSUE TITLE
Implement Heaviside function

### ISSUE THREAD

**Issue by MaxNoe** [Theano/Theano#2459]
could you add a heaviside function?

**Comment by benanne** [comment]
Try this: `lambda x: (T.sgn(x) + 1) / 2`

**Comment by MaxNoe** [comment]
Works, as well as lambda x, x0: T.switch(T.gt(x, x0), 1, 0), that's how I do it in the moment

**Comment by nouiz** [comment]
As it is easy to implement and it is not in python, I'm not sure we should
add it.

What other people think?

**Comment by lamblin** [comment]
If you really care about the value at `x0`, then @benanne's formula would probably be the best.
If you do not, then @MaxNoe's formula could be reduced to `lambda x, x0: T.gt(x, x0)`, or even `T.gt`.
