### ISSUE TITLE
Element-wise Vectors Matrix Products are hard to implement

### ISSUE THREAD

**Issue by capybaralet** [Theano/Theano#2463]
I found the fact that neither of these (prod1, prod2) evaluate very confusing while debugging, especially since vec.eval().shape = (5,) and NOT (1,5).  

vec = T.shared(np.ones(5))
mat = T.shared(np.ones((5,7)))
prod1 = vec * mat
prod2 = vec.T * mat
prod1.eval()
prod2.eval()

Shouldn't the error at least have:
Inputs shapes: [(5,), (5, 7)]

instead of:
Inputs shapes: [(1, 5), (5, 7)]

??

# and then this doesn't work, either!
vec = T.shared(np.ones((5,1)))
mat = T.shared(np.ones((5,7)))
prod1 = vec * mat
prod2 = vec.T * mat
prod1.eval()
prod2.eval()

# only THIS works:
vec = T.shared(np.ones(5))
mat = T.shared(np.ones((5,7)))
prod1 = vec * mat
prod2 = vec * mat.T
prod1.eval()
prod2.eval() # works!

Maybe this is all covered in the docs, but it is very counter-intuitive, IMO!

**Comment by nouiz** [comment]
The * is the element wise multiplication, not the dot product. We use the same convention as numpy. If you want the doc product, use T.dot().

The error message it good. Next time, add it in your post/issue, it make the reply faster.

element-wise operation use the broadcasting rules as numpy, but we hardcode the broadcast in the graph and do not use the shape as numpy. The size (1, 5) just mean that we put in the graph the operation that add the missing dimensions to allow the broadcasting to happen. There is more doc in this in that Theano tutorial:

https://github.com/abergeron/ccw_tutorial_theano

**Comment by nouiz** [comment]
If you still have questions, you can ask here.

**Comment by capybaralet** [comment]
I was trying to implement elementwise products.  

I think at least the second option should work:
vec = T.shared(np.ones((5,1)))
mat = T.shared(np.ones((5,7)))
prod1 = vec * mat
prod1.eval()

It would work in numpy:

vec = np.ones((5,1))
mat = np.ones((5,7))
prod1 = vec * mat

**Comment by lamblin** [comment]
I think @capybaralet is aware that this is for an elementwise product, as this is in the ticket title.
Regarding your first example:
- `prod1` tries to multiply each _row_ of `mat` by `vec`, which obviously does not have the right shape
- in `prod2`, you have to remember that transposing a vector does not do anything (just as in NumPy), as it only have one dimension. To make it a column, you can use `vec[:, np.newaxis]` or `vec.dimshuffle(0, 'x')` instead.

Regarding your second example, shared variables can change shape when they are updated, so there is no guarantee that `vec` will always be a column, so Theano will treat it as a full matrix. The solution would be to explicitly specify the broadcastable pattern: `vec = T.shared(np.ones((5, 1)), broadcastable=(False, True))`.
