### ISSUE TITLE
 Identifier "CUDNN_POOLING_AVERAGE" is undefined

### ISSUE THREAD

**Issue by ziyuang** [Theano/Theano#2481]
Environment: Python 2.7, Ubuntu 14.04, CUDA 6.5, cuDNN 6.5.41

At some point of the `theano.test()`, it complains 

    mod.cu(92): error: identifier "CUDNN_POOLING_AVERAGE" is undefined
    1 error detected in the compilation of "/tmp/tmpxft_00001931_00000000-8_mod.cpp1.ii".

Is it due to some incompatibility with the new cudnn-6.5-linux-x64-v2-rc2?

**Comment by nouiz** [comment]
You are right. They changed the interface a little. I'm looking at it now.
Not sure how long it will take.

**Comment by nouiz** [comment]
I have a PR: https://github.com/Theano/Theano/pull/2483

On Fri, Feb 6, 2015 at 2:28 PM, Frédéric Bastien <frederic.bastien@gmail.com
> wrote:

> You are right. They changed the interface a little. I'm looking at it now.
> Not sure how long it will take.
>
