### ISSUE TITLE
Fix the gradient of the Assert Op

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2488]
Reported on https://groups.google.com/d/topic/theano-users/NI_HhjIkh0Y/discussion
From that thread:
> There is indeed a but in the implementation of Assert.grad: it forwards
> the gradient of its output to its first input, but does not provide
> any gradient for the conditions.
> Those gradients (wrt the conditions) should be disconnected, because
> there is not reason for gradient to flow through them.
> So, the implementation should be something like:
```
def grad(self, inputs, output_gradients):
    return output_gradients + [DisconnectedType()()] * (len(inputs) - 1)
```

**Comment by dwf** [comment]
@harmdevries89 This one's for you this week. Should be pretty simple with the code provided in @lamblin's comment above.

**Comment by abergeron** [comment]
Done with #2720
