### ISSUE TITLE
conv2d for multi channel

### ISSUE THREAD

**Issue by jeehye** [Theano/Theano#2493]
Hello
I tried to run conv2d for 2 channel speech input.
input=(batch size, stack size, nb row, nb col)=(128,2,33,40)
filters=(nb filters, stack size, nb row, nb col)=(128,1,33,9)
output=(batch size, nb filters, output row, output col)
I want to use same filter for 2 channel input.
Can I use different stack size for input and filter??

Also,  I don't want to add output according to stack size.
I want to get output tensor for each channel.
How can I undo addition for stack size??

**Comment by benanne** [comment]
Just reshape your input to (128*2, 1, 33, 40), apply the convolution, and then unfold it into (128, 2, 128, 33, 40) again with another reshape. Or possibly (128, 2*128, 33, 40), depending on what you want to do next :)

**Comment by jeehye** [comment]
@benanne 
Thank you for your reply.
I tried to use "conv2d" in "theano/tensor/nnet/conv.py".
Then How could I reshape my input??
I'm new in python and theano...

**Comment by benanne** [comment]
The reshape method is documented here: http://deeplearning.net/software/theano/library/tensor/basic.html

**Comment by jeehye** [comment]
I want to split tensor.
Original tensor shape is (batch size, stack size, nb row, nb col)=(128,2,33,40)
But I want to split it into two tensor shape (128,1,33,40) (128,1,33,40)
Then how can I split tensor for each stack???

**Comment by nouiz** [comment]
There is many way to split. You can just use indexing in this case:

a_tensor ... # of shape (128,2,33,40)
first_split = a_tensor[:,0]
second_split = a_tensor[:,1]

Here is documentation about the different type of indexing that we support:

http://deeplearning.net/software/theano/library/tensor/basic.html#indexing

Fred

**Comment by jeehye** [comment]
@nouiz I tried to follow your reply, but it didn't work well
self.input.ndim = 4
But when I run code      input_one = self.input[:,0]
Then I got 
input_one.ndim = 3
Why this problem happened??

**Comment by nouiz** [comment]
Hi,

Did you look at the indexing documentation? If so, it probably miss details.

This is normal numpy indexing, so if my explanation aren't clear enough
google for it.

if you do "var[:]", This is taking slice (if slice in unknow, search for
python slice). This do not lower the number of dimensions.

If you do var[N], for N an integer, this remove that corresponding
dimensions. This is the same as python list.

The different with numpy.ndarray object and Theano tensor variable vs
python list is that we generatlise it to n-dimensions.

So if you do var[:, 0], it mean on the outer most dimensions take a full
slice. But on the 2nd dimensions, take only the element at index 0 and
remove that dimensions from the results.

To keep the dimensions: "var[:, 0:1]" (use 2 slices, and the second slice
have only 1 elements)

**Comment by jeehye** [comment]
@nouiz  Thank you I missed something.

For last, I tried to concatenate two outputs. 
Output_one and Output_two  have (128,1,33,32) shape.
And I will concatenate them and make (128,2,33,32) shape.

tensor.concatenate([output_one, output_two], axis=1)
Is this right??

**Comment by nouiz** [comment]
I think so. I close this issue for now. If that do not answer your questions, comment again here.
