### ISSUE TITLE
 Optimization tag that enable all unsafe opt for speed up(remove assert, error detection)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2495]

**Comment by nouiz** [comment]
local_remove_all_assert opt is unsafe.
register this opt in sandbox/cuda/opt.py and sandbox/gpuarray/opt.py
Document it.

**Comment by orhanf** [comment]
`local_remove_all_assert` opt is registered in `sandbox/cuda/opt.py` and `sandbox/gpuarray/opt.py` with an `unsafe` tag in `EquilibriumDB`. Documentation is pending tho.

**Comment by nouiz** [comment]
done
