### ISSUE TITLE
Include pep8 autocheck test + while list (from blocks)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2503]
After that, make a new ticket to fix the files.

whitelist the file that currently fail.

**Comment by bartvm** [comment]
I would just create a file `pep8-whitelist.txt` with the filenames that you want to whitelist:
```
scalar/__init__.py
scalar/basic.py
...
```
and then just run:
```bash
sed 's/^/theano\//g' pep8-whitelist.txt | tr '\n' , | xargs -I {} pep8 theano --exclude={}
```
(or maybe use `flake8` instead of `pep8` if you want to run PyFlakes too)

**Comment by nouiz** [comment]
We also need a tests that will run it automatically. That way we won't
introduce new error in clean file without knowing it.

**Comment by bartvm** [comment]
You can just add that command to `.travis.yml`, right?

**Comment by nouiz** [comment]
I prefer a normal nosetests test. That way people running Theano tests will
have this checked too.

We can call os command with os.system(...), so that it isn't hard to put in
a test.

**Comment by bartvm** [comment]
pep8 is just a Python package, and it has an API, so you could use that
too. See
https://github.com/jcrocholl/pep8/blob/master/docs/advanced.rst#automated-tests
for an example and
http://pep8.readthedocs.org/en/latest/api.html#pep8.StyleGuide for the API
reference.

**Comment by abergeron** [comment]
I think the module approach is best.  It's easier to integrate a whitelist with that.

**Comment by Saizheng** [comment]
You can make the test in the file theano/tests/test_pep8.py

**Comment by nouiz** [comment]
We should use flake8 instead. It cover more stuff then just pep8.

So the test should be in the file theano/tests/test_flake8.py

**Comment by Saizheng** [comment]
During testing in travis-CI, it claims that there is no module named "flake8" or "flake8.engine" so some test did not pass. 
It's weird since this program ran successfully in lisa's system, and it did have module "flake8" or  "flake8.engine".

**Comment by bartvm** [comment]
You'll need to install it on Travis probably. Change `.travis.yml` and add `flake8` to the list of packages after `conda create`.

**Comment by nouiz** [comment]
The PR gh-2557 did it.
