### ISSUE TITLE
Serializability Issue with NoneConst

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#2516]
In a few places of Theano code the `NoneConst.equals` call is done:

```
./theano/tensor/subtensor.py:2002:        if NoneConst.equals(v):
./theano/tensor/type_other.py:15:    elif NoneConst.equals(x):
./theano/tensor/basic.py:1299:        if NoneConst.equals(node.inputs[1]):
./theano/tensor/basic.py:1417:        if NoneConst.equals(axis):
./theano/tensor/basic.py:1426:        if NoneConst.equals(axis):
```

But after serialization and deserialization this call returns `False`, although it would be highly desirable that it returns `True`:

```python
import cPickle
from theano.tensor.type_other import NoneConst
print NoneConst.equals(cPickle.loads(cPickle.dumps(NoneConst)))
```
prints `False`.

I can trace the reason for that in the code, but I am not sure what is the right way to fix it. 
This is quite a serious bug, because a deserialized function can start behaving completely differently (in my cases fortunately I just caught an `AttributeError`).

**Comment by nouiz** [comment]
Can you make a small code that reproduce it?

I think the problem is that the NoneConst.type for the unpickled do not
equals the original one. Can you confirm this?

**Comment by nouiz** [comment]
I have code that reproduce this:

>>> from theano.tensor.type_other import NoneTypeT, Constant
>>> Constant(NoneTypeT(), None, name='NoneConst') == Constant(NoneTypeT(),
None, name='NoneConst')
False

**Comment by rizar** [comment]
Exactly - I had the same code in the issue description. I can try to reproduce the `AttributeError` at unpickling that I had originally, if you need that.

**Comment by nouiz** [comment]
I think I have enough for now.

**Comment by rizar** [comment]
Anyway I got it:
```
import cPickle
import theano
from theano import tensor

x = tensor.vector('x')
y = tensor.argmax(x)
f = theano.function([x], [y])
cPickle.loads(cPickle.dumps(f))
```

**Comment by nouiz** [comment]
My code didn't caused the problem. I need your code.

NoneTypeT should be a singleton, but it seam the unpickle break this.

**Comment by rizar** [comment]
Sorry, I don't understand. There is a 8-line code I posted above that crashes because of this issue. Doesn't it crash for you?

**Comment by nouiz** [comment]
I mean, the code I wrote here didn't caused the problem I expected. It was
behaving correctly.

You code reproduce well the problem.

I have a PR with a fix in gh-2517

**Comment by rizar** [comment]
Thanks!
