### ISSUE TITLE
Using Theano but return collect2: ld returned 1 exit status.

### ISSUE THREAD

**Issue by juexinwang** [Theano/Theano#2522]
Hello,
I just installed Theano 0.6.0 on python 2.7.9 by pip install theano
However, when I just type 
import theano, I got error
Here is my console by Ipython:

00584         if (!self->var_computed[prereq_idx])
00585           {
00586             err = lazy_rec_eval(self, prereq_idx, one, zero);
00587             if (err) return err;
00588           }
00589         assert (self->var_computed[prereq_idx]);
00590       }
00591   
00592     // STEP 2: compute the node itself
00593     if (self->is_lazy[owner_idx])
00594       {
00595         // update the compute_map cells corresponding to the inputs of this thunk
00596         for (int i = 0; i < self->node_n_inputs[owner_idx]; ++i)
00597           {
00598             int in_idx = self->node_inputs[owner_idx][i];
00599             if (self->var_computed[in_idx])
00600               {
00601                 Py_INCREF(one);
00602                 err = PyList_SetItem(self->var_computed_cells[in_idx], 0, one);
00603               }
00604             else
00605               {
00606                 Py_INCREF(zero);
00607                 err = PyList_SetItem(self->var_computed_cells[in_idx], 0, zero);
00608               }
00609             if (err) goto fail;
00610           }
00611   
00612         rval = pycall(self, owner_idx, verbose);
00613         // refcounting - rval is new ref
00614         //TODO: to prevent infinite loops
00615         // - consider check that a thunk does not ask for an input that is already computed
00616         if (rval == NULL)
00617           {
00618             assert (PyErr_Occurred());
00619             err = 1;
00620             goto fail;
00621           }
00622   
00623         //update the computed-ness of any output cells
00624         for (int i = 0; i < self->node_n_outputs[owner_idx]; ++i)
00625           {
00626             int out_idx = self->node_outputs[owner_idx][i];
00627             PyObject * el_i = PyList_GetItem(self->var_computed_cells[out_idx], 0);
00628             Py_ssize_t N = PyNumber_AsSsize_t(el_i, PyExc_IndexError);
00629             if (PyErr_Occurred())
00630               {
00631                 err = -1;
00632                 goto pyfail;
00633               }
00634             assert (N==0 || N==1);
00635             self->var_computed[out_idx] = N;
00636           }
00637         if (!self->var_computed[var_idx])
00638           {
00639             /*
00640              * If self is not computed after the call, this means that some
00641              * inputs are needed.  Compute the ones on the returned list
00642              * and try to compute the current node again (with recursive call).
00643              * This allows a node to request more nodes more than once before
00644              * finally yielding a result.
00645              */
00646             if (!PyList_Check(rval))
00647               {
00648                 //TODO: More helpful error to help find *which node* made this
00649                 // bad thunk
00650                 PyErr_SetString(PyExc_TypeError,
00651                                 "lazy thunk should return a list");
00652                 err = 1;
00653                 goto pyfail;
00654               }
00655   
00656             if (!PyList_Size(rval))
00657               {
00658                 PyErr_SetString(PyExc_ValueError,
00659                                 "lazy thunk returned empty list without computing output");
00660                 err = 1;
00661                 goto pyfail;
00662               }
00663   
00664             for (int i = 0; i < PyList_Size(rval); ++i)
00665               {
00666                 PyObject * el_i = PyList_GetItem(rval, i);
00667                 Py_ssize_t N = PyNumber_AsSsize_t(el_i, PyExc_IndexError);
00668                 if (PyErr_Occurred())
00669                   {
00670                     err = 1;
00671                     goto pyfail;
00672                   }
00673                 assert (N <= self->node_n_inputs[owner_idx]);
00674                 Py_ssize_t input_idx = self->node_inputs[owner_idx][N];
00675                 err = lazy_rec_eval(self, input_idx, one, zero);
00676                 if (err) goto pyfail;
00677               }
00678   
00679             Py_DECREF(rval);
00680             /*
00681              * We intentionally skip all the end-of-function processing
00682              * (mark outputs, GC) as it will be performed by the call
00683              * that actually manages to compute the result.
00684              */
00685             return lazy_rec_eval(self, var_idx, one, zero);
00686           }
00687   
00688         Py_DECREF(rval);
00689       }
00690     else //owner is not a lazy op. Ensure all intputs are evaluated.
00691       {
00692         // loop over inputs to owner
00693         // call lazy_rec_eval on each one that is not computed.
00694         // if there's an error, pass it up the stack
00695         for (int i = 0; i < self->node_n_inputs[owner_idx]; ++i)
00696           {
00697             Py_ssize_t input_idx = self->node_inputs[owner_idx][i];
00698             if (!self->var_computed[input_idx])
00699               {
00700                 err = lazy_rec_eval(self, input_idx, one, zero);
00701                 if (err) return err;
00702               }
00703             assert (self->var_computed[input_idx]);
00704           }
00705   
00706         // call the thunk for this owner.
00707         if (self->thunk_cptr_fn[owner_idx])
00708           {
00709             err = c_call(self, owner_idx, verbose);
00710             if (err) goto fail;
00711           }
00712         else
00713           {
00714             rval = pycall(self, owner_idx, verbose);
00715             //rval is new ref
00716             if (rval) //pycall returned normally (no exception)
00717               {
00718                 if (rval == Py_None)
00719                   {
00720                     Py_DECREF(rval); //ignore a return of None
00721                   }
00722                 else if (PyList_Check(rval))
00723                   {
00724                     PyErr_SetString(PyExc_TypeError,
00725                                     "non-lazy thunk should return None, not list");
00726                     err = 1;
00727                     goto pyfail;
00728                   }
00729                 else // don't know what it returned, but it wasn't right.
00730                   {
00731                     PyErr_SetObject(PyExc_TypeError, rval);
00732                     err = 1;
00733                     // We don't release rval since we put it in the error above
00734                     goto fail;
00735                   }
00736               }
00737             else // pycall returned NULL (internal error)
00738               {
00739                 err = 1;
00740                 goto fail;
00741               }
00742           }
00743       }
00744   
00745     // loop over all outputs and mark them as computed
00746     for (int i = 0; i < self->node_n_outputs[owner_idx]; ++i)
00747       {
00748         self->var_computed[self->node_outputs[owner_idx][i]] = 1;
00749       }
00750   
00751     // Free vars that are not needed anymore
00752     if (self->allow_gc)
00753       {
00754         for (int i = 0; i < self->node_n_inputs[owner_idx]; ++i)
00755           {
00756             int cleanup = 1;
00757             Py_ssize_t i_idx = self->node_inputs[owner_idx][i];
00758             if (!self->var_has_owner[i_idx])
00759               continue;
00760   
00761             for (int j = 0; j < self->n_output_vars; ++j)
00762               {
00763                 if (i_idx == self->output_vars[j])
00764                   {
00765                     cleanup = 0;
00766                     break;
00767                   }
00768               }
00769             if (!cleanup) continue;
00770   
00771             for (int j = 0; j < self->n_dependencies[i_idx]; ++j)
00772               {
00773                 if (!self->var_computed[self->dependencies[i_idx][j]])
00774                   {
00775                     cleanup = 0;
00776                     break;
00777                   }
00778               }
00779             if (!cleanup) continue;
00780   
00781             Py_INCREF(Py_None);
00782             err = PyList_SetItem(self->var_value_cells[i_idx], 0, Py_None);
00783   //See the Stack gc implementation for why we change it to 2 and not 0.
00784             self->var_computed[i_idx] = 2;
00785             if (err) goto fail;
00786           }
00787       }
00788   
00789     return 0;
00790    pyfail:
00791     Py_DECREF(rval);
00792    fail:
00793     set_position_of_error(self, owner_idx);
00794     return err;
00795   }
00796   PyObject *
00797   CLazyLinker_call(PyObject *_self, PyObject *args, PyObject *kwds)
00798   {
00799     CLazyLinker * self = (CLazyLinker*)_self;
00800     static char *kwlist[] = {
00801       (char*)"time_thunks",
00802       (char *)"n_calls",
00803       NULL};
00804     int n_calls=1;
00805     if (! PyArg_ParseTupleAndKeywords(args, kwds, "|ii", kwlist,
00806                                       &self->do_timing,
00807                                       &n_calls))
00808       return NULL;
00809     int err = 0;
00810     self->position_of_error = -1;
00811     // create constants used to fill the var_compute_cells
00812     PyObject * one = PyInt_FromLong(1);
00813     PyObject * zero = PyInt_FromLong(0);
00814   
00815     // pre-allocate our return value
00816     Py_INCREF(Py_None);
00817     PyObject * rval = Py_None;
00818     //clear storage of pre_call_clear elements
00819     for (int call_i = 0; call_i < n_calls && (!err); ++call_i)
00820       {
00821         Py_ssize_t n_pre_call_clear = PyList_Size(self->pre_call_clear);
00822         assert(PyList_Check(self->pre_call_clear));
00823         for (int i = 0; i < n_pre_call_clear; ++i)
00824           {
00825             PyObject * el_i = PyList_GetItem(self->pre_call_clear, i);
00826             Py_INCREF(Py_None);
00827             PyList_SetItem(el_i, 0, Py_None);
00828           }
00829         //clear the computed flag out of all non-input vars
00830         for (int i = 0; i < self->n_vars; ++i)
00831           {
00832             self->var_computed[i] = !self->var_has_owner[i];
00833             if (self->var_computed[i])
00834               {
00835                 Py_INCREF(one);
00836                 PyList_SetItem(self->var_computed_cells[i], 0, one);
00837               }
00838             else
00839               {
00840                 Py_INCREF(zero);
00841                 PyList_SetItem(self->var_computed_cells[i], 0, zero);
00842               }
00843           }
00844   
00845         for (int i = 0; i < self->n_output_vars && (!err); ++i)
00846           {
00847             err = lazy_rec_eval(self, self->output_vars[i], one, zero);
00848           }
00849   
00850         if (!err)
00851           {
00852             // save references to outputs prior to updating storage containers
00853             assert (self->n_output_vars >= self->n_updates);
00854             Py_DECREF(rval);
00855             rval = PyList_New(self->n_output_vars);
00856             for (int i = 0; i < (self->n_output_vars); ++i)
00857               {
00858                 Py_ssize_t src = self->output_vars[i];
00859                 PyObject * item = PyList_GetItem(self->var_value_cells[src], 0);
00860                 if (self->var_computed[src] != 1)
00861                   {
00862                     err = 1;
00863                     PyErr_Format(PyExc_AssertionError,
00864                                  "The compute map of output %d should contain "
00865                                  "1 at the end of execution, not %d.",
00866                                  i, self->var_computed[src]);
00867                     break;
00868                   }
00869                 Py_INCREF(item);
00870                 PyList_SetItem(rval, i, item);
00871               }
00872           }
00873   
00874         if (!err)
00875           {
00876             // Update the inputs that have an update rule
00877             for (int i = 0; i < self->n_updates; ++i)
00878               {
00879                 PyObject* tmp = PyList_GetItem(rval, self->n_output_vars - self->n_updates + i);
00880                 Py_INCREF(tmp);
00881                 Py_ssize_t dst = self->update_storage[i];
00882                 PyList_SetItem(self->var_value_cells[dst], 0, tmp);
00883               }
00884           }
00885       }
00886   
00887     /*
00888       Clear everything that is left and not an output.  This is needed
00889       for lazy evaluation since the current GC algo is too conservative
00890       with lazy graphs.
00891     */
00892     if (self->allow_gc && !err)
00893       {
00894         for (Py_ssize_t i = 0; i < self->n_vars; ++i)
00895           {
00896             int do_cleanup = 1;
00897             if (!self->var_has_owner[i] || !self->var_computed[i])
00898               continue;
00899             for (int j = 0; j < self->n_output_vars; ++j)
00900               {
00901                 if (i == self->output_vars[j])
00902                   {
00903                     do_cleanup = 0;
00904                     break;
00905                   }
00906               }
00907             if (!do_cleanup)
00908               continue;
00909             Py_INCREF(Py_None);
00910             PyList_SetItem(self->var_value_cells[i], 0, Py_None);
00911           }
00912       }
00913     Py_DECREF(one);
00914     Py_DECREF(zero);
00915     if (err)
00916       {
00917         Py_DECREF(rval);
00918         return NULL;
00919       }
00920     return rval;
00921   }
00922   
00923   #if 0
00924   static PyMethodDef CLazyLinker_methods[] = {
00925       {
00926         //"name", (PyCFunction)CLazyLinker_accept, METH_VARARGS, "Return the name, combining the first and last name"
00927       },
00928       {NULL}  /* Sentinel */
00929   };
00930   #endif
00931   
00932   static PyMemberDef CLazyLinker_members[] = {
00933       {(char*)"nodes", T_OBJECT_EX, offsetof(CLazyLinker, nodes), 0,
00934        (char*)"list of nodes"},
00935       {(char*)"thunks", T_OBJECT_EX, offsetof(CLazyLinker, thunks), 0,
00936        (char*)"list of thunks in program"},
00937       {(char*)"call_counts", T_OBJECT_EX, offsetof(CLazyLinker, call_counts), 0,
00938        (char*)"number of calls of each thunk"},
00939       {(char*)"call_times", T_OBJECT_EX, offsetof(CLazyLinker, call_times), 0,
00940        (char*)"total runtime in each thunk"},
00941       {(char*)"position_of_error", T_INT, offsetof(CLazyLinker, position_of_error), 0,
00942        (char*)"position of failed thunk"},
00943       {(char*)"time_thunks", T_INT, offsetof(CLazyLinker, do_timing), 0,
00944        (char*)"bool: nonzero means call will time thunks"},
00945       {(char*)"need_update_inputs", T_INT, offsetof(CLazyLinker, need_update_inputs), 0,
00946        (char*)"bool: nonzero means Function.__call__ must implement update mechanism"},
00947       {NULL}  /* Sentinel */
00948   };
00949   
00950   static PyTypeObject lazylinker_ext_CLazyLinkerType = {
00951   #if defined(NPY_PY3K)
00952       PyVarObject_HEAD_INIT(NULL, 0)
00953   #else
00954       PyObject_HEAD_INIT(NULL)
00955       0,                         /*ob_size*/
00956   #endif
00957       "lazylinker_ext.CLazyLinker",             /*tp_name*/
00958       sizeof(CLazyLinker), /*tp_basicsize*/
00959       0,                         /*tp_itemsize*/
00960       CLazyLinker_dealloc,       /*tp_dealloc*/
00961       0,                         /*tp_print*/
00962       0,                         /*tp_getattr*/
00963       0,                         /*tp_setattr*/
00964       0,                         /*tp_compare*/
00965       0,                         /*tp_repr*/
00966       0,                         /*tp_as_number*/
00967       0,                         /*tp_as_sequence*/
00968       0,                         /*tp_as_mapping*/
00969       0,                         /*tp_hash */
00970       CLazyLinker_call,          /*tp_call*/
00971       0,                         /*tp_str*/
00972       0,                         /*tp_getattro*/
00973       0,                         /*tp_setattro*/
00974       0,                         /*tp_as_buffer*/
00975       Py_TPFLAGS_DEFAULT|Py_TPFLAGS_BASETYPE,        /*tp_flags*/
00976       "CLazyLinker object",      /* tp_doc */
00977       0,                         /* tp_traverse */
00978       0,                         /* tp_clear */
00979       0,                         /* tp_richcompare */
00980       0,                         /* tp_weaklistoffset */
00981       0,                         /* tp_iter */
00982       0,                         /* tp_iternext */
00983       0,//CLazyLinker_methods,       /* tp_methods */
00984       CLazyLinker_members,       /* tp_members */
00985       0,                         /* tp_getset */
00986       0,                         /* tp_base */
00987       0,                         /* tp_dict */
00988       0,                         /* tp_descr_get */
00989       0,                         /* tp_descr_set */
00990       0,                         /* tp_dictoffset */
00991       (initproc)CLazyLinker_init,/* tp_init */
00992       0,                         /* tp_alloc */
00993       CLazyLinker_new,           /* tp_new */
00994   };
00995   
00996   static PyObject * get_version(PyObject *dummy, PyObject *args)
00997   {
00998     PyObject *result = PyFloat_FromDouble(0.20);
00999     return result;
01000   }
01001   
01002   static PyMethodDef lazylinker_ext_methods[] = {
01003     {"get_version",  get_version, METH_VARARGS, "Get extension version."},
01004     {NULL, NULL, 0, NULL}        /* Sentinel */
01005   };
01006   
01007   #ifndef PyMODINIT_FUNC  /* declarations for DLL import/export */
01008   #define PyMODINIT_FUNC void
01009   #endif
01010   
01011   #if defined(NPY_PY3K)
01012   static struct PyModuleDef moduledef = {
01013           PyModuleDef_HEAD_INIT,
01014           "lazylinker_ext",
01015           NULL,
01016           -1,
01017           lazylinker_ext_methods,
01018           NULL,
01019           NULL,
01020           NULL,
01021           NULL
01022   };
01023   #endif
01024   #if defined(NPY_PY3K)
01025   #define RETVAL m
01026   PyMODINIT_FUNC
01027   PyInit_lazylinker_ext(void) {
01028   #else
01029   #define RETVAL
01030   PyMODINIT_FUNC
01031   initlazylinker_ext(void) 
01032   {
01033   #endif
01034       PyObject* m;
01035   
01036       lazylinker_ext_CLazyLinkerType.tp_new = PyType_GenericNew;
01037       if (PyType_Ready(&lazylinker_ext_CLazyLinkerType) < 0)
01038           return RETVAL;
01039   #if defined(NPY_PY3K)
01040       m = PyModule_Create(&moduledef);
01041   #else
01042       m = Py_InitModule3("lazylinker_ext", lazylinker_ext_methods,
01043                          "Example module that creates an extension type.");
01044   #endif
01045       Py_INCREF(&lazylinker_ext_CLazyLinkerType);
01046       PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01047   
01048       return RETVAL;
01049   }
01050   
01051   
Problem occurred during compilation with the command line below:
g++ -shared -g -march=corei7-avx -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-tbm -mavx -msse4.2 -msse4.1 --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=generic -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m32 -IC:\Python27\lib\site-packages\numpy\core\include -IC:\Python27\include -o C:\Users\wangjue\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-32\lazylinker_ext\lazylinker_ext.pyd C:\Users\wangjue\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.9-32\lazylinker_ext\mod.cpp -LC:\Python27\libs -LC:\Python27 -lpython27
Traceback (most recent call last):

  File "<ipython-input-1-3397704bd624>", line 1, in <module>
    import theano

  File "C:\Python27\lib\site-packages\theano\__init__.py", line 55, in <module>
    from theano.compile import 
  File "C:\Python27\lib\site-packages\theano\compile\__init__.py", line 6, in <module>
    from theano.compile.function_module import *

  File "C:\Python27\lib\site-packages\theano\compile\function_module.py", line 18, in <module>
    import theano.compile.mode

  File "C:\Python27\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm

  File "C:\Python27\lib\site-packages\theano\gof\vm.py", line 516, in <module>
    import lazylinker_c

  File "C:\Python27\lib\site-packages\theano\gof\lazylinker_c.py", line 86, in <module>
    preargs=args)

  File "C:\Python27\lib\site-packages\theano\gof\cmodule.py", line 1971, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

. collect2: ld returned 1 exit status./lib/gcc/x86_64-w64-mingw32/4.6.3/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrte c:/perl64/site/lib/auto/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.6.3/../../../../x86_64-w64-mingw32/lib/libmsvcrt.a when searching for -lmsvcrtexmefor -lstdc++

**Comment by lamblin** [comment]
Please use the theano-users mailing list for such help requests.
As for your problem, can you try the latest development ("bleeding-edge") version, not the released one? If that does not work, please post on the mailing list.
