### ISSUE TITLE
Error while running check_blas.py for gpu

### ISSUE THREAD

**Issue by jayendra13** [Theano/Theano#2523]
I have installed theano by following instruction from http://deeplearning.net/software/theano/install.html.
It is working with cpu but there is some trouble while executing on gpu.
CUDA is installed and working properly, as I had successfully built and executed some random samples.
My OS is windows-7 professional and gpu is "NVIDIA Quadro K600"

I created the .theanorc.txt in my home directory. here is a content of it.
```
[nvcc]
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
[global]
device=gpu
floatX=float32
```
The problem is that when I run check_blas.py(from theano\misc) . Actually this error comes whenever I tries to import theano while using the gpu. 
Here is is the log of error
```
c:\anaconda\include\pymath.h(22): warning: dllexport/dllimport conflict with
und"
c:\program files\nvidia gpu computing toolkit\cuda\v6.5\include\math_functio
(2455): here; dllimport/dllexport dropped









mod.cu(405): error: namespace "std" has no member "min"

mod.cu(447): error: namespace "std" has no member "min"




2 errors detected in the compilation of "C:/Users/Nisarg/AppData/Local/Temp/
ft_00001620_00000000-10_mod.cpp1.ii".
mod.cu

['nvcc', '-shared', '-g', '-O3', '-arch=sm_50', '--compiler-bindir', 'C:\\Pr
m Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin', '-Xlinker', '/DEBUG',
64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=d67f7c8a21306c67152a70a88a837011,/Zi,
, '-IC:\\Users\\Nisarg\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.760
1-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\\cuda_ndarray',
None\\include', '-IC:\\Anaconda\\lib\\site-packages\\numpy\\core\\include',
:\\Anaconda\\include', '-IC:\\Anaconda\\lib\\site-packages\\theano\\sandbox\
a', '-o', 'C:\\Users\\Nisarg\\AppData\\Local\\Theano\\compiledir_Windows-7-6
601-SP1-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\\tmpzlsyj
173b40d34b57da0645a57198c96dbcc.pyd', 'mod.cu', '-LC:\\Anaconda\\libs', '-LC
sers\\Nisarg\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Inte
Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\\cuda_ndarray', '-LNone\\
, '-LNone\\lib', '-LNone\\lib64', '-LC:\\Anaconda', '-lpython27', '-lcudart'
lcublas', '-lcuda_ndarray']
Traceback (most recent call last):
  File "check_blas.py", line 23, in <module>
    import theano
  File "C:\Anaconda\lib\site-packages\theano\__init__.py", line 92, in <modu
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "C:\Anaconda\lib\site-packages\theano\sandbox\cuda\tests\test_driver.
 line 28, in test_nvidia_driver1
    profile=False)
  File "C:\Anaconda\lib\site-packages\theano\compile\function.py", line 223,
function
    profile=profile)
  File "C:\Anaconda\lib\site-packages\theano\compile\pfunc.py", line 512, in
nc
    on_unused_input=on_unused_input)
  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", li
312, in orig_function
    defaults)
  File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", li
181, in create
    _fn, _i, _o = self.linker.make_thunk(input_storage=input_storage_lists)
  File "C:\Anaconda\lib\site-packages\theano\gof\link.py", line 434, in make
nk
    output_storage=output_storage)[:3]
  File "C:\Anaconda\lib\site-packages\theano\gof\vm.py", line 847, in make_a
    no_recycling))
  File "C:\Anaconda\lib\site-packages\theano\sandbox\cuda\__init__.py", line
, in make_thunk
    compute_map, no_recycling)
  File "C:\Anaconda\lib\site-packages\theano\gof\op.py", line 606, in make_t

    output_storage=node_output_storage)
  File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 948, in make_t

    keep_lock=keep_lock)
  File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 891, in __comp
_
    keep_lock=keep_lock)
  File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 1322, in cthun
ctory
    key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
  File "C:\Anaconda\lib\site-packages\theano\gof\cmodule.py", line 996, in m
e_from_key
    module = next(compile_steps)
  File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 1237, in compi
module_by_step
    preargs=preargs)
  File "C:\Anaconda\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py",
e 433, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuCARe
{add}{1}(<CudaNdarrayType(float32, vector)>), '\n', 'nvcc return status', 2,
r cmd', 'nvcc -shared -g -O3 -arch=sm_50 --compiler-bindir C:\\Program Files
6)\\Microsoft Visual Studio 12.0\\VC\\bin -Xlinker /DEBUG -m64 -Xcompiler -D
_NDARRAY_CUH=d67f7c8a21306c67152a70a88a837011,/Zi,/MD -IC:\\Users\\Nisarg\\A
ta\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_
tepping_4_GenuineIntel-2.7.8-64\\cuda_ndarray -INone\\include -IC:\\Anaconda
b\\site-packages\\numpy\\core\\include -IC:\\Anaconda\\include -IC:\\Anacond
ib\\site-packages\\theano\\sandbox\\cuda -o C:\\Users\\Nisarg\\AppData\\Loca
heano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_62_Stepping_
nuineIntel-2.7.8-64\\tmpzlsyjp\\7173b40d34b57da0645a57198c96dbcc.pyd mod.cu
\\Anaconda\\libs -LC:\\Users\\Nisarg\\AppData\\Local\\Theano\\compiledir_Win
-7-6.1.7601-SP1-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\\
_ndarray -LNone\\lib -LNone\\lib -LNone\\lib64 -LC:\\Anaconda -lpython27 -lc
t -lcublas -lcuda_ndarray', '[GpuCAReduce{add}{1}(<CudaNdarrayType(float32,
or)>)]')

```

**Comment by nouiz** [comment]
Do you use Theano development version? I suppose so. This is a must, last
release do not support well GPU on Windows.

Googling this error seem to tell that we miss a "#include <algorithm>" in a
file. The error you give point to a class that didn't changed recently. So
I'm pretty surprised that it do not work.

Did you also got a dump of the source file that caused the error? Can you
give us that?

The problem can be caused by newer VS version that behave differently then
the older one.

thanks

On Mon, Feb 23, 2015 at 7:23 AM, Jayendra <notifications@github.com> wrote:
>
> I have installed theano by following instruction from
http://deeplearning.net/software/theano/install.html.
> It is working with cpu but there is some trouble while executing on gpu.
> CUDA is installed and working properly, as I had successfully built and
executed some random samples.
> My OS is windows-7 professional and gpu is "NVIDIA Quadro K600"
>
> I created the .theanorc.txt in my home directory. here is a content of it.
>
> [nvcc]
> compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
> [global]
> device=gpu
> floatX=float32
>
> The problem is that when I run check_blas.py(from theano\misc) . Actually
this error comes whenever I tries to import theano while using the gpu.
> Here is is the log of error
>
> c:\anaconda\include\pymath.h(22): warning: dllexport/dllimport conflict
with
> und"
> c:\program files\nvidia gpu computing
toolkit\cuda\v6.5\include\math_functio
> (2455): here; dllimport/dllexport dropped
>
> mod.cu(405): error: namespace "std" has no member "min"
>
> mod.cu(447): error: namespace "std" has no member "min"
>
> 2 errors detected in the compilation of
"C:/Users/Nisarg/AppData/Local/Temp/
> ft_00001620_00000000-10_mod.cpp1.ii".
> mod.cu
>
> ['nvcc', '-shared', '-g', '-O3', '-arch=sm_50', '--compiler-bindir',
'C:\Pr
> m Files (x86)\Microsoft Visual Studio 12.0\VC\bin', '-Xlinker', '/DEBUG',
> 64', '-Xcompiler',
'-DCUDA_NDARRAY_CUH=d67f7c8a21306c67152a70a88a837011,/Zi,
> , '-IC:\Users\Nisarg\AppData\Local\Theano\compiledir_Windows-7-6.1.760
>
1-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\cuda_ndarray',
> None\include', '-IC:\Anaconda\lib\site-packages\numpy\core\include',
> :\Anaconda\include', '-IC:\Anaconda\lib\site-packages\theano\sandbox\
> a', '-o', 'C:\Users\Nisarg\AppData\Local\Theano\compiledir_Windows-7-6
>
601-SP1-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\tmpzlsyj
> 173b40d34b57da0645a57198c96dbcc.pyd', 'mod.cu', '-LC:\Anaconda\libs', '-LC
> sers\Nisarg\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Inte
> Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\cuda_ndarray', '-LNone\
> , '-LNone\lib', '-LNone\lib64', '-LC:\Anaconda', '-lpython27', '-lcudart'
> lcublas', '-lcuda_ndarray']
> Traceback (most recent call last):
> File "check_blas.py", line 23, in
> import theano
> File "C:\Anaconda\lib\site-packages\theano__init__.py", line 92, in <modu
> theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
> File "C:\Anaconda\lib\site-packages\theano\sandbox\cuda\tests\test_driver.
> line 28, in test_nvidia_driver1
> profile=False)
> File "C:\Anaconda\lib\site-packages\theano\compile\function.py", line 223,
> function
> profile=profile)
> File "C:\Anaconda\lib\site-packages\theano\compile\pfunc.py", line 512, in
> nc
> on_unused_input=on_unused_input)
> File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", li
> 312, in orig_function
> defaults)
> File "C:\Anaconda\lib\site-packages\theano\compile\function_module.py", li
> 181, in create
> fn, i, _o = self.linker.make_thunk(input_storage=input_storage_lists)
> File "C:\Anaconda\lib\site-packages\theano\gof\link.py", line 434, in make
> nk
> output_storage=output_storage)[:3]
> File "C:\Anaconda\lib\site-packages\theano\gof\vm.py", line 847, in make_a
> no_recycling))
> File "C:\Anaconda\lib\site-packages\theano\sandbox\cuda__init.py", line
> , in make_thunk
> compute_map, no_recycling)
> File "C:\Anaconda\lib\site-packages\theano\gof\op.py", line 606, in make_t
>
> output_storage=node_output_storage)
>
> File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 948, in make_t
>
> keep_lock=keep_lock)
>
> File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 891, in __comp
> _
> keep_lock=keep_lock)
> File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 1322, in cthun
> ctory
> key=key, fn=self.compile_cmodule_by_step, keep_lock=keep_lock)
> File "C:\Anaconda\lib\site-packages\theano\gof\cmodule.py", line 996, in m
> e_from_key
> module = next(compile_steps)
> File "C:\Anaconda\lib\site-packages\theano\gof\cc.py", line 1237, in compi
> module_by_step
> preargs=preargs)
> File "C:\Anaconda\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py",
> e 433, in compile_str
> 'for cmd', ' '.join(cmd))
> Exception: ('The following error happened while compiling the node',
GpuCARe
> {add}{1}(), '\n', 'nvcc return status', 2,
> r cmd', 'nvcc -shared -g -O3 -arch=sm_50 --compiler-bindir C:\Program
Files
> 6)\Microsoft Visual Studio 12.0\VC\bin -Xlinker /DEBUG -m64 -Xcompiler -D
> NDARRAY_CUH=d67f7c8a21306c67152a70a88a837011,/Zi,/MD -IC:\Users\Nisarg\A
> ta\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model
> tepping_4_GenuineIntel-2.7.8-64\cuda_ndarray -INone\include -IC:\Anaconda
> b\site-packages\numpy\core\include -IC:\Anaconda\include -IC:\Anacond
> ib\site-packages\theano\sandbox\cuda -o C:\Users\Nisarg\AppData\Loca
>
heano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_62_Stepping_
> nuineIntel-2.7.8-64\tmpzlsyjp\7173b40d34b57da0645a57198c96dbcc.pyd mod.cu
> \Anaconda\libs -LC:\Users\Nisarg\AppData\Local\Theano\compiledir_Win
>
-7-6.1.7601-SP1-Intel64_Family_6_Model_62_Stepping_4_GenuineIntel-2.7.8-64\

**Comment by jayendra13** [comment]
I am pretty sure about not using the development (or bleeding edge) version as, installation was done by pip (Anaconda-pip).
You are right about the "#include <algorithm>", I added it to theano\sandbox\cuda\cuda_ndarray.cu so it resolved the previous error about 
 mod.cu(405): error: namespace "std" has no member "min"
but there are still showing at two places. I tried to find mod.cu but couldn't.

Actually I also get the same error while importing theano with gpu either in IPython QT console or in "command prompt".  I tried to debug the 'import theano' statement which led to me error in function
theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1() in __init__.py of theano.

dump of which source file will be helpful?

Here is extra information, it may help.
os: Windows 7 Professional
gpu: NVIDIA Quadro K600
cuda-version: v6.5
driver-version: 347.52
theano-version:0.6.0-py2.7

**Comment by nouiz** [comment]
Hi,

Do you continue that direction. You will need to reimplement all fixed done
in Theano.

My recommandatation is that you use the developmenet branch. It is pretty
stable and I recommand it to everybody. We are triing to make a release
candidate for the next release.

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Fred

**Comment by jayendra13** [comment]
It's working Fred
Thanks
How can I get notified about the availability of next release

**Comment by nouiz** [comment]
Subscribe to the theano - announce mailing list.
