### ISSUE TITLE
Runtime error in Windows with CNN

### ISSUE THREAD

**Issue by jayendra13** [Theano/Theano#2531]
I am trying the convolution neural network from the deep-learning tutorial [here](http://deeplearning.net/tutorial/lenet.html) 
My version of code is [here] (https://gist.github.com/jayendra13/83456bfcaaa1dee5667d) which basically merges the first two code snippets.
With cpu it is working fine but with gpu command prompt  says 'python.exe' has stopped working.
All the samples from [this](http://deeplearning.net/software/theano/tutorial/using_gpu.html) page are working fine with gpu except the pycuda examples (which are irrelevant) and [__Returning a Handle to Device-Allocated Data__] (http://deeplearning.net/software/theano/tutorial/using_gpu.html#id2) which might be problem The error is 

Using gpu device 0: Quadro K600
Traceback (most recent call last):
  File "theano_test_5.py", line 10, in <module>
    f = function([], sandbox.gpuarray.basic_ops.gpu_from_host(tensor.exp(x)))
AttributeError: 'module' object has no attribute 'gpuarray'

I have no idea about how to provide the more information for run-time error.

**Comment by lamblin** [comment]
Hi,

On Wed, Feb 25, 2015, Jayendra wrote:
> I am trying the convolution neural network from the deep-learning tutorial [here](http://deeplearning.net/tutorial/lenet.html) 
> My version of code is [here] (https://gist.github.com/jayendra13/83456bfcaaa1dee5667d) which basically merges the first two code snippets.
> With cpu it is working fine but with gpu command prompt  says 'python.exe' has stopped working.

If you are using Windows, you should use the development version of
Theano [1], not the latest release, as we fixed a number of bugs and
crashes since then.


> All the samples from [this](http://deeplearning.net/software/theano/tutorial/using_gpu.html) page are working fine with gpu except the pycuda examples (which are irrelevant) and [__Returning a Handle to Device-Allocated Data__] (http://deeplearning.net/software/theano/tutorial/using_gpu.html#id2) which might be problem The error is 
> 
> Using gpu device 0: Quadro K600
> Traceback (most recent call last):
>   File "theano_test_5.py", line 10, in <module>
>     f = function([], sandbox.gpuarray.basic_ops.gpu_from_host(tensor.exp(x)))
> AttributeError: 'module' object has no attribute 'gpuarray'

This is a different problem. That snippet uses the gpuarray backend [2],
which is optional and needs an additional library [3] to work.

[1] http://deeplearning.net/software/theano/install.html#windows-bleeding-edge
[2] http://deeplearning.net/software/theano/tutorial/using_gpu.html#gpuarray-backend
[3] http://deeplearning.net/software/libgpuarray/installation.html


-- 
Pascal

**Comment by jayendra13** [comment]
I am using the development version cloned from github repo.

**Comment by nouiz** [comment]
For now, you are better not to use the gpuarray array back-end.

So instead of calling:

sandbox.gpuarray.basic_ops.gpu_from_host

call:

sandbox.cuda.basic_ops.gpu_from_host


sandbox.cuda is the current back-end,


the new back-end is under sandbox.gpuarray.


Fred
