### ISSUE TITLE
segmentation fault (core dumped) in theano.test()

### ISSUE THREAD

**Issue by ziyuang** [Theano/Theano#2568]
Head: 7dcc9b59
Environment: Ubuntu 14.04 + Python 2.7.6 + GRID K520 + CUDA 6.5 + cuDNN v2 rc3
Installed via `python setup.py develop`

.theanorc:

    [global]
    device = gpu0
    floatX = float32
    optimizer_including = cudnn
    [blas]
    ldflags = -lmkl_rt
    [nvcc]
    fastmath = True

The last outputs from `theano.test()`:

    ~/repositories/theano/theano/sandbox/cuda/type.py:541: UserWarning: config.experimental.unpickle_gpu_on_cpu is set to True. Unpickling CudaNdarray as numpy.ndarray
      warnings.warn("config.experimental.unpickle_gpu_on_cpu is set to True. Unpickling CudaNdarray as numpy.ndarray")
    .........SSSSSSSSSS....F..KK............................SS......[1]    31236 segmentation fault (core dumped)  ipython

**Comment by ziyuang** [comment]
I double check the `theano.__version__`. It seems the imported theano was not at the HEAD. I am running the test again.

**Comment by lamblin** [comment]
First, you should not use `device=gpu0` when running `theano.test()`. Later versions of theano should warn you against that.
Running `theano-nose` on the command line, rather than `theano.test()` from inside Python, would allow you to pass the `-v` option, which will print the name of each test before executing it, this can help you pinpoint which test is failing.

**Comment by ziyuang** [comment]
Do you mean `theano-test -v`? I run `theano-nose -v` but there is no test.

    $ theano-nose -v
    ----------------------------------------------------------------------
    Ran 0 tests in 0.001s

**Comment by lamblin** [comment]
You would have to either pass it the path to theano (`theano-nose -v /path/to/Theano/theano`), or pass it the `--theano` flag (`theano-nose --theano -v`).

**Comment by ziyuang** [comment]
Thanks. But the error is gone with 238d2a84 and `device=cpu`.
