### ISSUE TITLE
How to pass variable image lengths into Theano function

### ISSUE THREAD

**Issue by AlaRuba** [Theano/Theano#2571]
I have a bunch of images that I want to store into an numpy matrix that I want to pass into a numpy function.

The problem is that all my images are different sizes and I don't want to necessarily change their size, because some will be square and some aren't.

However, using image = misc.imread(filename) from the scipy library. The image is returned as a 3 dimensional array. How should I construct my numpy ndarray if I want to store all the images in it to pass into a Theano function?

Alternatively, is a list possible?

Thanks

**Comment by lamblin** [comment]
Please use the `theano-users` mailing list for support requests, not GitHub tickets.
There is no way to make an array of irregular size in NumPy.

**Comment by nouiz** [comment]
There is the typedlist: http://deeplearning.net/software/theano/library/typed_list.html

But this isn't well supported. You are better to pad to the same size, or a fixed size per mini-batch when possible. I'll close this issue as mailing are a better place for this.
