### ISSUE TITLE
C code for max_pool_2d: add padding and strides

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2582]
Follow-up to #2196.
- [x] C code for `DownsampleFactorMax`: done in #2696
- [x] C code for `DownsampleFactorMaxGrad`
- [ ] C code, and Python code for padding, for `DownsampleFactorMaxGradGrad`

**Comment by nouiz** [comment]
The grad of grad for max_pool_2d padding isn't implemented too. I do not
know for stride.

**Comment by lamblin** [comment]
Strides are implemented for the 2nd derivative, padding is not.

**Comment by yaoli** [comment]
I've started to take a look at the ticket.
The part with reference counting is still a mystery, I'm sure there are bells and whistles. Can anyone give me some guidelines?

**Comment by nouiz** [comment]
Go see new theano tutorial on cop. We talk about it.

**Comment by yaoli** [comment]
Where do I look for it exactly? Can you send me the link?
2015-3-20 下午2:06于 "Frédéric Bastien" <notifications@github.com>写道：

> Go see new theano tutorial on cop. We talk about it.

**Comment by lamblin** [comment]
http://deeplearning.net/software/theano/tutorial/extending_theano_c.html

**Comment by lamblin** [comment]
So, next step is the C code for `DownsampleFactorMaxGrad`.

**Comment by yaoli** [comment]
OK.

**Comment by nouiz** [comment]
This have been done. From memory, it was in the PR that make the Pool op parallel. So closing.
