### ISSUE TITLE
ShapeFeature.same_shape missing case?

### ISSUE THREAD

**Issue by sisp** [Theano/Theano#2585]
Is there a `return True` missing [here](https://github.com/Theano/Theano/blob/master/theano/tensor/opt.py#L1218)? If all shapes are identical, i.e.
```
if dx is dy:
    continue
```
`same_shape` should return `True`, I guess, but it returns `None` right now.

**Comment by nouiz** [comment]
I have a try to make it better here:

https://github.com/Theano/Theano/pull/2586

I didn't test it. There isn't an extensive test suite for that method. I
think we should make more tests for that. What do you think of this PR?

I have other stuff to work on today/tomorrow, so I won't work on that code
again shortly, but I can talk about it.

**Comment by sisp** [comment]
I think that looks good. Good catch about the `equal_computations` part. I hadn't seen that one. I just noticed the first case while working on https://github.com/Theano/Theano/pull/2521.

**Comment by sisp** [comment]
Oh, one more comment while touching that code: Wouldn't the import above `equal_computations` be better placed before the loop?

**Comment by nouiz** [comment]
We could move it, but it would force the import even when it isn't used. As
this import scan stuff, this isn't ideal. The real fix is to move that
function to theano/compile/* or theano/gof/* and import it at the top of
the file.

**Comment by sisp** [comment]
OK, no problem then.
