### ISSUE TITLE
Better storage_map printing in error message

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2606]
In the file gof/link.py, we print the content of the storage map.

We should order it from the biggest size to the smallest. We should print the total size too. If we can also print the shared variable size, the would be good.

**Comment by t13m** [comment]
Like this?
```
...
Storage map footprint:
WholeSize: 56 Byte(s)
 - <TensorType(float64, vector)>, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
 - <TensorType(float64, vector)>, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - Elemwise{add,no_inplace}.0, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
```

And I'm not sure about printing the shared variable size. In this code:
```
import theano
import theano.tensor as T
import numpy as np
sx = theano.shared(np.array([1.,2.,3.]))
y = T.vector()
f = theano.function([y], x + y, givens={x:sx})
f([5.,6.])
```
It outputs like following:
```
...
Storage map footprint:
 - <TensorType(float64, vector)>, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
 - <TensorType(float64, vector)>, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
```
`x` and `y` have been printed out. Do you mean that `sx` should also be printed out? Then I think the size of `sx` shouldn't be calculate in total size.

**Comment by nouiz** [comment]
On Tue, Mar 17, 2015 at 5:30 AM, t13m <notifications@github.com> wrote:

> Like this?
>
> ...
> Storage map footprint:
> WholeSize: 56 Byte(s)
>  - <TensorType(float64, vector)>, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
>  - <TensorType(float64, vector)>, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
>  - Elemwise{add,no_inplace}.0, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
>
> Yes


> And I'm not sure about printing the shared variable size. In this code:
>
> import theano
> import theano.tensor as T
> import numpy as np
> sx = theano.shared(np.array([1.,2.,3.]))
> y = T.vector()
> f = theano.function([y], x + y, givens={x:sx})
> f([5.,6.])
>
> It outputs like following:
>
> ...
> Storage map footprint:
>  - <TensorType(float64, vector)>, Shape: (2,), ElemSize: 8 Byte(s), TotalSize: 16 Byte(s)
>  - <TensorType(float64, vector)>, Shape: (3,), ElemSize: 8 Byte(s), TotalSize: 24 Byte(s)
>
> x and y have been printed out. Do you mean that sx should also be printed
> out? Then I think the size of sx shouldn't be calculate in total size.
>

You can add a new section that will print shared variable. The Theano
function have a field extended_input that include shared variable that it
use. This would allow you to find it.

**Comment by t13m** [comment]
I did the descending sort part and have sent a PR. But I can't find any argument named "extended_input" in function "function" and other functions.

**Comment by nouiz** [comment]
The PR is merged. This is done.
