### ISSUE TITLE
T.concatenate([A, B], axis=-1) doesn't work on GPU

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#2613]
`axis=-1` is not documented to work on CPU but does.  On GPU it gives a confusing error message.

We should clarify whether this is supported or not and regularize the situation on GPU.

**Comment by julianser** [comment]
I've been experimented with T.concatenate (where axis=-1) on CPU and GPU, and it seems to work fine. Arnaud or Xavier, do you have an example code where it doesn't work?

Here is the test that works fine for me:

import numpy as np

import theano
import theano.tensor as T
from theano import shared

rng = np.random.RandomState(22)
t1 = shared(np.asarray(rng.rand(5), theano.config.floatX))
t2 = shared(np.asarray(rng.rand(5), theano.config.floatX))
t = T.concatenate([t1, t2], axis=-1)

test = theano.function(
	inputs=[],
	outputs=t
)

print test()

**Comment by bouthilx** [comment]
@julianser Do you get a 1D tensor with 5 values? This is even worse, there is no error message, but the output is wrong.

Here's what I get:

```python
# Numpy
[ 0.20846054  0.48168105  0.42053804  0.859182    0.17116155  0.33886397
  0.27053285  0.69104135  0.22040452  0.81195092]
# Theano
[ 0.33886397  0.27053285  0.69104135  0.22040452  0.81195092]
```

**Comment by bouthilx** [comment]
@abergeron Was Theano supposed to raise an error or nobody reported such a behavior yet?

**Comment by nouiz** [comment]
I never heard of negative axis with concatenation. So probably nobody
taught of that case before.

If we could support it, that is better, otherwise, we should raise an error.

On Thu, Apr 2, 2015 at 5:11 PM, Xavier Bouthillier <notifications@github.com

**Comment by bouthilx** [comment]
@nouiz Should not be to complicated to support I guess. axis=-1 -> axis=ndims-1?

**Comment by lamblin** [comment]
Indeed, the usual thing to do is `axis < 0` -> `axis += ndim`.

**Comment by nouiz** [comment]
Exact. In fact, if axis <0 do axis+NDIM. That work for all negative axis.
Le 2 avr. 2015 17:38, "Xavier Bouthillier" <notifications@github.com> a
écrit :

**Comment by julianser** [comment]
@bouthilx That's strange! With the current version of Theano I get the exact same results for Theano NumPy:

NumPy [ 0.20846054  0.48168106  0.42053804  0.859182    0.17116155  0.33886396
  0.27053283  0.69104135  0.22040452  0.81195092]
Theano [ 0.20846054  0.48168106  0.42053804  0.859182    0.17116155  0.33886396
  0.27053283  0.69104135  0.22040452  0.81195092]

This works both with GPU and CPU. Am I doing something different from you, Xavier?

**Comment by bouthilx** [comment]
@julianser Are you using up-to-date theano version? I pulled last commits and I still get this result. It works for CPU though.

**Comment by nouiz** [comment]
I reopen this ticket, as this fix the problem for constant axis, but not for when the axis is a symbolic variable.

import numpy as np

import theano.sandbox.cuda
theano.sandbox.cuda.use('gpu')
theano.config.floatX='float32'
import theano.tensor as T
from theano import shared

rng = np.random.RandomState(22)
t1 = shared(np.asarray(rng.rand(5), theano.config.floatX))
t2 = shared(np.asarray(rng.rand(5), theano.config.floatX))
i = theano.tensor.iscalar()
t = T.concatenate([t1, t2], axis=i)

test = theano.function([i], t)
print test(0)
# [ 0.20846054  0.48168105  0.42053804  0.859182    0.17116155  0.33886397 0.27053285  0.69104135  0.22040452  0.81195092]
print test(-1)
# [ 0.33886397  0.27053285  0.69104135  0.22040452  0.81195092]
print test(-2)
# [ 0.33886397  0.27053285  0.69104135  0.22040452  0.81195092]
print test(2)
# [ 0.33886397  0.27053285  0.69104135  0.22040452  0.81195092]

at the same time, check that the axis is not too high.

**Comment by nouiz** [comment]
Also, Just to have everything at the same place, here is part of the comment I did on the merged PR:

But if the axis is symbolic, it will still crash. So you should add test for that case (small modif to the test T_Join_and_Split.test_join_matrixV in tensor/tests/test_basic.py, it is reused by the GPU in cuda/tests/test_basic_ops.py:T_Join_and_Split.test_join_matrixV). After the test is added, you need to modify the perform and the c_code of this op to handle that correctly.

**Comment by bouthilx** [comment]
Oh! Good catch!

**Comment by julianser** [comment]
Good spot Fred. Alright, I'll continue work on this ticket.

**Comment by bouthilx** [comment]
@julianser  My bad, I should have seen this. I'll make a PR at the end of the day. You can concentrate on your other CCW ticket.

**Comment by nouiz** [comment]
Done.
