### ISSUE TITLE
nnet.conv2d output shape different on CPU/GPU

### ISSUE THREAD

**Issue by ebenolson** [Theano/Theano#2620]
I'm encountering a problem when giving an `image_shape` to `nnet.conv2d`, and subsequently providing an input image with a different shape. On the GPU, the output is correct for the shape of the input image, while on the CPU it appears to use `image_shape`.

Example:

        import numpy as np
        import theano
        import theano.tensor as T

        k = theano.shared(np.ones((1,1,3,3), dtype='float32'))

        im = T.tensor4()
        out = theano.function([im], T.nnet.conv2d(im, k, image_shape=(1,1,10,10)))

        print out(np.ones((1,1,20,10), dtype='float32')).shape

`THEANO_FLAGS='device=cpu' python test.py` => `(1, 1, 8, 8)`
`THEANO_FLAGS='device=gpu0' python test.py` => `(1, 1, 18, 8)`

**Comment by nouiz** [comment]
If you provide an image shape and this isn't exact, this is an error on
your side. But Theano should give an error on the CPU if he can't compute
the right output.

I think I solved that in Theano which version do you use? Can you update to
the lastest development version:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

If that do not fix it, it mean we must update Theano to raise an error.

**Comment by ebenolson** [comment]
Yes, I'm running the development version 0.7.0rc2.dev-d2c39c4ebd21eeb066681db0c74fd9ab3b0798e8

**Comment by nouiz** [comment]
Thanks for the report. I'm able to reproduce it. The problem is that you
give a given image_shape, but pass as an input another one. The GPU do not
use the image_shape, so it compute the good output size.

But the CPU use it, and should have checked the input have the right
shapes. But it miss this check. It should raise an error. I'm working on a
fix.

**Comment by nouiz** [comment]
I did a PR: gh-2663
