### ISSUE TITLE
Theano scan pass lists as output_info

### ISSUE THREAD

**Issue by escopeta** [Theano/Theano#2650]
Does anyone know if it's possible to pass, for example, a list containing [layer_one_hidden_units, layer_two_hidden_units] as output_info to scan for a multilayer rnn? I find that when I pass this, it converts it into a Tensor so when I work on the new hidden unit computations for the next time step I get theano errors since I guess it expects a tensor given that it converted my initial input to a tensor. Any help would be appreciated thank you very much.

**Comment by nouiz** [comment]
To my knowledge, it should work. @carriepl, do you think the same?

**Comment by escopeta** [comment]
I figured out how to do it. I just used variable size of input to scan (*args). I'm sorry I forgot to mark this as resolved. Thanks for your response.
