### ISSUE TITLE
Add example of "strict=True" in documentation of scan

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2651]
The scan documentation (in https://github.com/Theano/Theano/blob/master/doc/library/scan.txt, online at http://deeplearning.net/software/theano/library/scan.html) should have an example of `strict=True` as well as an explanation.
Follow-up to #2622

**Comment by cangermueller** [comment]
What about an example with a shared variable not given in `non_sequences`, and which raises an exception if `strict=True`? For instance, computing A^k as in the first example, but without specifing `A` as `non_sequence`.

Or maybe another example that points out the performance improvement if `strict=True`?
