### ISSUE TITLE
Update required for tutorial on memory management

### ISSUE THREAD

**Issue by keyboard-naptime** [Theano/Theano#2652]
I believe [this section](http://deeplearning.net/software/theano/tutorial/python-memory-management.html#internal-memory-management) is no longer current. Apart from the minor change between Python 2 and 3 (`range()` is no longer a list, so it needs `list(range(1000000))`), it seems the newer Python versions somehow (partially?) solve the growth of small blocks problem.

Running this code:

    import copy
    from memory_profiler import profile

    @profile
    def function():
        x = list(range(1000000))  # allocate a big list
        y = copy.deepcopy(x)
        del x
        return y

    if __name__=="__main__":
        function()

results in this output:

> Line #   Mem usage    Increment   Line Contents
> ================================================
>     4     12.2 MiB      0.0 MiB   @profile
>     5                             def function():
>     6     50.8 MiB     38.6 MiB       x = list(range(1000000)) # allocate a big list
>     7     58.7 MiB      7.9 MiB       y = copy.deepcopy(x)
>     8     51.1 MiB     -7.6 MiB       del x
>     9     51.1 MiB      0.0 MiB       return y

This suggests that the numbers 1 through 1000000 are not copied at all, and reused once created.

Replacing numbers with mutable objects removes that confusion, but still it appears the entire memory is released back to the heap:

    import copy
    from memory_profiler import profile

    class A:
        pass

    @profile
    def function():
        x = [A() for i in range(1000000)]
        y = copy.deepcopy(x)
        del x
        return y

    if __name__=="__main__":
        function()

> Line #    Mem usage    Increment   Line Contents
> ================================================
>      7     12.3 MiB      0.0 MiB   @profile
>      8                             def function():
>      9     75.2 MiB     63.0 MiB       x = [A() for i in range(1000000)]
>     10    167.2 MiB     92.0 MiB       y = copy.deepcopy(x)
>     11    105.8 MiB    -61.4 MiB       del x
>     12    105.8 MiB      0.0 MiB       return y

BTW, all of this run under Python 3.4 on Windows.

**Comment by cangermueller** [comment]
I will take care of this issue!

**Comment by cangermueller** [comment]
`test.py` has the following content:
```python
import copy
import memory_profiler

@profile
def function():
    x = list(range(1000000))  # allocate a big list
    y = copy.deepcopy(x)
    del x
    return y

if __name__=="__main__":
    function()
```
On OSX with `python2.7 -m memory_profiler test.py`, I get:
```
Filename: test.py

Line #    Mem usage    Increment   Line Contents
================================================
     4    9.625 MiB    0.000 MiB   @profile
     5                             def function():
     6   48.336 MiB   38.711 MiB       x = list(range(1000000))  # allocate a big list
     7  137.172 MiB   88.836 MiB       y = copy.deepcopy(x)
     8  137.172 MiB    0.000 MiB       del x
     9  137.172 MiB    0.000 MiB       return y
```
On OSX with `python3.4 -m memory_profiler test.py`, I get:
```
Filename: test.py

Line #    Mem usage    Increment   Line Contents
================================================
     4    9.539 MiB    0.000 MiB   @profile
     5                             def function():
     6   48.180 MiB   38.641 MiB       x = list(range(1000000))  # allocate a big list
     7   55.875 MiB    7.695 MiB       y = copy.deepcopy(x)
     8   55.875 MiB    0.000 MiB       del x
     9   55.875 MiB    0.000 MiB       return y
```

That means, no memory is released at all, also not for the pointers.

Instead of using `range(n)`, I tried using `[1] * n`. `test2.py` has the following content:

```
import copy
import memory_profiler

@profile
def function():
    x = [1] * 1000000  # allocate a big list
    y = copy.deepcopy(x)
    del x
    return y

if __name__=="__main__":
    function()
```
On OSX with `python2.7 -m memory_profiler test2.py`, I get:
```
Filename: test2.py

Line #    Mem usage    Increment   Line Contents
================================================
     4    9.367 MiB    0.000 MiB   @profile
     5                             def function():
     6   17.004 MiB    7.637 MiB       x = [1] * 1000000  # allocate a big list
     7   24.676 MiB    7.672 MiB       y = copy.deepcopy(x)
     8   24.676 MiB    0.000 MiB       del x
     9   24.676 MiB    0.000 MiB       return y
```
On OSX with `python3.4 -m memory_profiler test2.py`, I get:
```
Filename: test2.py

Line #    Mem usage    Increment   Line Contents
================================================
     4    9.336 MiB    0.000 MiB   @profile
     5                             def function():
     6   16.969 MiB    7.633 MiB       x = [1] * 1000000  # allocate a big list
     7   24.664 MiB    7.695 MiB       y = copy.deepcopy(x)
     8   24.664 MiB    0.000 MiB       del x
     9   24.664 MiB    0.000 MiB       return y
```

Here, no memory is released again, but `python2.7` and `python3.4` give the same result. Does anybody know why a) no memory is released and b) `python2.7` and `python3.4` behave different for `test.py`?

**Comment by keyboard-naptime** [comment]
In python 2, range() creates a list. It is then copied when you call
list(), so there are two large list objects before you even call
copy.deepcopy.

In python 3, range() is a generator, it does not actually create a list
(same as xrange() was in python 2). So no extra list is created.

As far as memory release, it seems MacOS behaves different from Ubuntu
14.04. Here's what I see on Ubuntu, very strange:

Line #    Mem usage    Increment   Line Contents
================================================
    11      9.3 MiB      0.0 MiB   @profile
    12                             def main():
    13     47.8 MiB     38.5 MiB       x = list(range(1000000))  # allocate
a big list
    14     55.8 MiB      7.9 MiB       y = copy.deepcopy(x)
    15     48.3 MiB     -7.5 MiB       del x
    16     48.3 MiB      0.0 MiB       return y

**Comment by cangermueller** [comment]
Right, `list(..)` is not required for `python2`, but I added it to such that the results are similar for `python2` and `python3`. Of course, there are now two listed created (one by `range(...)`, one by `list(...)`) if the code is run with `python2`, but it does not increase the memory usage (`38.5 MiB`). 

Do you have an idea why `python2` allocates `88.836 MiB` in line 13, but `python3` only  `7.9 MiB`?

**Comment by cangermueller** [comment]
I seems that `copy.deepcopy` performs a shallow copy instead of a deep copy for `python3`. I replaced `deepcopy` by `copy`:

```python


import copy
import memory_profiler

@profile
def function():
    x = list(range(1000000))  # allocate a big list
    y = copy.deepcopy(x)
    del x
    return y

if __name__=="__main__":
    function()
```

No get the following result:
```
Filename: ./test.py

Line #    Mem usage    Increment   Line Contents
================================================
     6      8.6 MiB      0.0 MiB   @profile
     7                             def function():
     8     47.3 MiB     38.7 MiB       x = list(range(1000000))  # allocate a big list
     9     54.9 MiB      7.6 MiB       y = copy.copy(x)
    10     54.9 MiB      0.0 MiB       del x
    11     54.9 MiB      0.0 MiB       return y
```

`deepcopy` seems to only copy pointer (1000000 * 8 byte = 7.6 MiB), just as `copy`.

**Comment by nouiz** [comment]
@abergeron should this ticket be closed too?

**Comment by abergeron** [comment]
Yes.
