### ISSUE TITLE
Add a flag to disable pickling test values

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#2655]

**Comment by lamblin** [comment]
Also, a warning should probably be raised by default if there are test values at pickling time, and the flag was not explicitly set to pickle them.
The problem is that it can take tens of gigabytes when pickling, and it is not obvious where that comes from.

**Comment by abergeron** [comment]
Then maybe we should just not pickle them by default.

**Comment by nouiz** [comment]
Agreed

**Comment by abergeron** [comment]
Do we really need a config flag then?  Is there any use case where it would make sense to pickle test values?

**Comment by nouiz** [comment]
To show error that get triggered by test value? To give test value that can
be used with theano.function_dump?

If you want to just remove them without a flag, I do not have an objection

**Comment by lamblin** [comment]
Does deep_copy use the pickling mechanism?
Test values of intermediate node do not matter much, but it would be surprising to have the test values for leaf variable disappear without warning, and without a way of getting them back.

Another way would be to only save the test values of variables with no owner, and recompute them when unpickling.

**Comment by nouiz** [comment]
deep_copy use pickling

**Comment by lamblin** [comment]
Then I would definitely expect my deep_copied variable to still have their test values.

**Comment by abergeron** [comment]
We can always implement \__copy__ and \__deepcopy__ on Variables to not strip the test_value

**Comment by abhishekgarg16** [comment]
Hi @nouiz , can you please explain in little more detail what exactly needs to be done?

**Comment by nouiz** [comment]
In the file theano/configdefaults.py, add a new Theano flag. I would guess the name "pickle_test_value" that default to True, but can be set to False.

Then in the class Variable(), you can add a \__getstate__() method that will don't cause the pickle of tag.test_value(). There is some example elsewhere of \__getstate__(). grep for it in Theano.

thanks

**Comment by abhishekgarg16** [comment]
Ok, i will be working on it and submit a pull request soon.

**Comment by SadhanaSrinivasan** [comment]
Hi @nouiz 

Should I be modifying the __getstate__ function in class Variable(node) (the one in theano/gof/graph.py) to throw an exception instead of returning the dictionary when the flag is set to false? Or should I be writing a new __getstate__ for class Variable (the one in theano/gof/unify.py) ?

In the latter case, how does the __getstate__ stop the pickling?

**Comment by nouiz** [comment]
It is for the class Variable in the file gof/graph.py. not in unify.py. 

getstate should return a dict with the member to safe. It already have such method to do the same for another field. Read it and you should find how to do it. Check the file theano/configdefaults.py to add the new flag.

To know if we should raise or not will depend how a copy or deepcopy work on the object. We don't want to break them. You could implement \__copy__ and \__deepcopy__ and have them copy the test value. Or just not raise an error.

Can you try by raising an error and see how copy an deepcopy react?

**Comment by nouiz** [comment]
This was started in https://github.com/Theano/Theano/pull/5207
