### ISSUE TITLE
Identify random states of MRG generators

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2668]
For the moment, random states of MRG are regular matrices, either `TensorType(int32, matrix)` or `CudaNdarrayType(float32, matrix)`.
It would be useful to have a way of differenciating them from model parameters, for instance.
@bartvm proposed a tag like `.is_RNG`.
Something else that could be useful would be a weak reference to the `MRG_RandomStreams` instance that created them.

**Comment by dwf** [comment]
Why a weakref, specifically?

**Comment by lamblin** [comment]
The `MRG_RandomStreams` has a dictionary of all `shared state -> update expression` that it created, so I think it may make the work of the garbage collector easier not to have a cycle.
If this is not a concern, a full reference is fine by me as well.

**Comment by dwf** [comment]
![](https://i.imgur.com/1XR0bEF.png)

Sounds good to me.
