### ISSUE TITLE
conv2d subsample > 2 on CPU.

### ISSUE THREAD

**Issue by small-yellow-duck** [Theano/Theano#2678]
Hi folks, I would like to use conv2d with subsample values greater than 2, but I see this feature is still in the works:

NotImplementedError: ERROR: We disable ConvOp.grad now when dx or dy are different from 1 and 2, as there is a bug in it

Is this a priority for being fixed or have the priorities shifted to the other implementations of conv?

**Comment by nouiz** [comment]
If you use dnn_conv or the GpuCorrMM
<http://deeplearning.net/software/theano/library/sandbox/cuda/op.html#theano.sandbox.cuda.blas.GpuCorrMM>
convolution directly, they support it. It is only the CPU and the default
interface that do not support it. We are working on the interface to make
it work.

http://deeplearning.net/software/theano/library/tensor/nnet/conv.html

The PR that work on the interface:

https://github.com/Theano/Theano/pull/2665


I rename this PR to specify the operation on the CPU, there is no work
ongoing on it to support more the strides > 2.

On Wed, Mar 25, 2015 at 5:22 PM, small-yellow-duck <notifications@github.com

**Comment by lamblin** [comment]
See #3026.
