### ISSUE TITLE
calculating layer output dimensions

### ISSUE THREAD

**Issue by small-yellow-duck** [Theano/Theano#2679]
I would find it useful to have a function that calculates the size of the output of a layer for given padding, downsampling and subsampling (stride) options. I've been calculating the dimensions of the output of each layer, but doing this manually makes it annoying to make changes to the network architecture.

**Comment by lamblin** [comment]
You can use `Conv2D.getOutputShape` (https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/conv.py#L254) to get a value or an output expression for the output shape, but you also need to provide the size of the input and kernels.
If you want a more generic way of computing shape informations in a graph, you can also use `some_var.eval({inputs: ...})`.

**Comment by small-yellow-duck** [comment]
Ooooh, thank you!

**Comment by nouiz** [comment]
Just to complement the code:

some_var.shape.eval({inputs: ...}).

To query just the shape and possible not do the computation itself.

On Thu, Mar 26, 2015 at 2:37 PM, small-yellow-duck <notifications@github.com
