### ISSUE TITLE
Need scan memory and segfault test case

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2684]
gh-2683 revert some stuff. 

- [x] One reenable some optimization that was missed. We need to add a test for that case.
- [x] The second commit revert something that cause a segfault. We should add a test for the segfault to detect it ourself.

**Comment by carriepl** [comment]
@lamblin, @abergeron, @nouiz Does any of you remember anything about the cases in which a segfault occured? I went through my email, theano-users and theano-dev without finding anything related to this issue.

**Comment by nouiz** [comment]
This was the junyoung case where he unpickle a scan from a different Theano version

**Comment by carriepl** [comment]
Then a test case already exists in Theano : https://github.com/Theano/Theano/blob/master/theano/scan_module/tests/test_scan.py#L4477 which ensures that the validations inside of Scan will catch the inconsistency leading to the segfault.

This means that this issue can be closed.
