### ISSUE TITLE
In Scan.make_thunk extra check to give an error instead of segfault.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2685]
There was some segfault that happened when we reloaded some old pickled graph/Theano function with some version of scan that generated segfault.

This was caused by inconsistency in the outer variable and inner variable type not being right. Also for input and output types of corresponding recurrent variable.

In Scan.make_thunk, we should test that they are what they should and give a good user error message that he need to rebuild his graph.

**Comment by abergeron** [comment]
One case I have seen is where the input was on the GPU and the corresponding output was on the CPU.

This led scan to reuse the input as the output buffer and outputting a CudaNdarray for a TensorType output.

So to fix this ticket we should assert in the make_thunk that all corresponding inputs and outputs (inner and outer) have the same theano type.

**Comment by lamblin** [comment]
@carriepl I think you worked on that. Can we close the ticket?

**Comment by carriepl** [comment]
Yes.
