### ISSUE TITLE
Accept symbolic `reps` in `tensor.tile`

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2695]
Now that #2362 has been merged, there is no reason not to accept a symbolic vector as `reps`, or a list of symbolic scalars.
The checks need to be upgraded, and `ndim` will need to be used to access the individual elements of `reps` if it is a vector.
This would address #2434.

**Comment by lamblin** [comment]
Partially addressed by #2734, but we should still add support for a vector of integers.

**Comment by lamblin** [comment]
Also, support `uint` dtypes. The check should be done against `discrete_dtypes`, not an explicit list.

**Comment by Saizheng** [comment]
Hi,
I guess the current version does not support:
1. rep is a integer.
2. rep is a theano scalar.
3. rep is a list of theano scalar, something like [T.scalar(), T.scalar()].
4. rep is a theano vector.

It seems that I need to rewrite the whole function of tile? Or I only need to focus on 3. and 4.?

**Comment by lamblin** [comment]
3. should already be supported, since #2734 was merged.
There is no need to rewrite the whole function, you just have to build a new "reps" that is a list of scalar variables (or scalar constants or ints), and then the main part of the function (lines 4281 and following) does not have to change.
The more important point is 4., but it should not be hard to add 1 and 2 as well.

**Comment by lamblin** [comment]
Btw, points 1 and 2 are mentioned in #2719, which is now assigned to you as well.

**Comment by dwf** [comment]
@Saizheng let me know if you have any questions about this.

**Comment by dwf** [comment]
@Saizheng any update?

**Comment by Saizheng** [comment]
Hey David,

I finished the code for integer and T.scalar cases which are simple, but when reps is a T.vector whose length is not fixe , I have no idea about it yet.

Do you have time this afternoon? We can talk about it when you have time.

**Comment by lamblin** [comment]
@Saizheng If `reps` is a vector, you have to simply make sure that ndim is defined.
Then, you have to pad `reps` with ones to the left, in order for it to have length `ndim`.
And then you simply redefine `reps` as `[reps[i] for i in range(ndim)]`.

**Comment by Saizheng** [comment]
@lamblin you mean reps is a theano symbolic vector? I think in that case, because we don't know the length of a symbolic vector, it is hard to do any following operation like padding..

**Comment by lamblin** [comment]
Fixed by #2875
