### ISSUE TITLE
In nnet/conv.py, is it available to differenciate num_channel of filter and input??

### ISSUE THREAD

**Issue by jeehye** [Theano/Theano#2699]
In convolution and max pooling,
I want to use input image dimension=(256,2,33,40) and filter dimension=(128,1,33,9).
input[1] is different from filter[1].
In this case number of input channel is 2, but each channel use same filter.
However,in conv.py, I cannot use different dimension filter.
How can I use only 1 channel filter???

**Comment by f0k** [comment]
> In this case number of input channel is 2, but each channel use same filter.
 However,in conv.py, I cannot use different dimension filter.
 How can I use only 1 channel filter???

The number of channels needs to match. What you can do, however, is to reshape your input to twice the number of items with half the number of channels: (512, 1, 33, 40). Then convolve with your filter, and reshape the result from (512, 128, 1, 32) to half the number of items with twice the number of channels: (256, 256, 1, 32).

**Comment by jeehye** [comment]
Thank you.
Your reply helps a lot.
But after I reshape to (256, 256, 1, 32), I get another problem...
I should do channel-wise max pooling in axis 1.
For example I need to find maximum value between [0,0,0,0] and [0,128,0,0].
(between [0,1,0,0] and [0,129,0,0],  [0,2,0,0] and [0,130,0,0] )
Because 0~127 in axis 1 is from channel 1 and 128~256 is from channel 2.
Do you have any idea about this problem??

**Comment by f0k** [comment]
Well, when you reshaped your input to `(512, ...)`, the data points from the two channels are interleaved (the first is from the first channel, the second from the second channel, the third from the first channel and so forth). It's the same after the convolution. So you can just reshape the convolution result to `(256, 2, 128, 1, 32)` instead to separate the feature maps of the two channels again, then do your pooling over the third axis (axis=2).

**Comment by lamblin** [comment]
Also, please use the mailing list (`theano-users`) for such support requests, and keep the tickets for reporting bugs or missing features.
