### ISSUE TITLE
Need to lower GPU burden in theano

### ISSUE THREAD

**Issue by KHN190** [Theano/Theano#2701]
Is there a way to control the GPU burdon (such as hold batches when free space is running out) in theano? My program dies every time after a specific number of iterations "out of memory". 
Using smaller bathes and less batches did not help too much - memory usage didn't drop a lot. I searched in theano document but didn't find a good solution.
I'm using CUDA by the way.

**Comment by nouiz** [comment]
Can you try to call :

import gc;gc.collect();gc.collect();gc.collect()

Sometimes inyour code? This could be related to python gc not always doing
its work.

**Comment by KHN190** [comment]
Worked! I just need to optimize the garbage collection frequency as it now runs a bit slow.
So I'll just close this issue. Thank you.

**Comment by yunqiw** [comment]
Hi, I ran into the same problem, does the import gc worked well?
