### ISSUE TITLE
Install Page Correction

### ISSUE THREAD

**Issue by ClaytonTurner** [Theano/Theano#2704]
On the page for installing the bleeding-edge version of Theano (http://deeplearning.net/software/theano/install.html) there is an error (at least on Debian systems).

pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git 
should actually be
pip install --upgrade --no-deps git+https://github.com/Theano/Theano.git

Tested on x86_64 architecture, Debian GNU/Linux 7

**Comment by nouiz** [comment]
What error do you have? It was working in the past. Maybe github changed
its interface.

**Comment by ClaytonTurner** [comment]
The URL never returns any data in a clone for some reason - I don't know if this is a new change by Github or maybe just a debian-specific issue.

git clone https://... works
git clone git://... doesn't

**Comment by abergeron** [comment]
I think it only works if you have an ssh key registered with github, which
is obviously not the case for everyone.  I think we should make the
change.  Can you do a PR?

2015-03-30 14:55 GMT-04:00 Clayton Turner <notifications@github.com>:

**Comment by nouiz** [comment]
I think the old work well when there is no ssh key. Which version of pip do
you have? Maybe this is the difference?

"pip --version"

**Comment by ClaytonTurner** [comment]
pip --version returned:

pip 1.1 from /usr/lib/python2.7/dist-packes (python 2.7)

**Comment by abergeron** [comment]
That is an incredibly old version.  run "pip install --upgrade pip" to get
the latest one.

2015-03-31 15:21 GMT-04:00 Clayton Turner <notifications@github.com>:

**Comment by nouiz** [comment]
I'll close this issue, as I think the update of pip should fix this. If not, tell us.
