### ISSUE TITLE
Updates to online documentation

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2711]
- In http://deeplearning.net/software/theano/tutorial/symbolic_graphs.html#optimizations, indicate the graph was generated by pydotprint and provide a link
- Also regenerate that graph since the printing of `Composite` has been updated
- While we are at it, regenerate all the graphs/debugprints with Composite
- In fact, maybe use some kind of automatic generation for those?
- Update identifiers (`[@...]`) for debugprint, in particular:
  * http://deeplearning.net/software/theano/cifarSC2011/advanced_theano.html?highlight=debugprint#printing-drawing-theano-graphs
  * http://deeplearning.net/software/theano/crei2013/advanced_theano.html?highlight=debugprint#printing-drawing-theano-graphs
  * http://deeplearning.net/software/theano/tutorial/shape_info.html?highlight=debugprint
  * http://deeplearning.net/software/theano/tutorial/printing_drawing.html?highlight=debugprint

**Comment by cangermueller** [comment]
@lamblin, I will update the documentation!

**Comment by cangermueller** [comment]
@lamblin, I updated pydotprint graphs and debugprint output in `tutorial/symbolic_graphs.txt` and `cifarSC2011/advanced_theano.txt`. I generated the html files with `scripts/docgen.py`, and checked if the resulting html files look good.
If you agree on my pull-request, I will update the remaining tutorials in the same way. So what do think?

**Comment by lamblin** [comment]
Thanks a lot!
