### ISSUE TITLE
Accept scalar `reps` in `tensor.tile`

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2719]
See #2718 for a report.
If `reps` is a scalar, or scalar variable, it should be interpreted like in NumPy, i.e., as replication over the last dimension, that is as `[1, ..., 1, reps]`.
This should probably be fixed at the same time as #2695

**Comment by lamblin** [comment]
Also, if `reps` is shorter than the number of dimensions of the inputs, it should be left-padded with as many ones as needed.

**Comment by dwf** [comment]
@Saizheng You're also on this one (related to #2695).

**Comment by dwf** [comment]
@Saizheng any update?

**Comment by lamblin** [comment]
Fixed by #2875
