### ISSUE TITLE
The problem of 

### ISSUE THREAD

**Issue by jiangfeng1124** [Theano/Theano#2724]
Hi -

I came across a weird problem when installing Theano on a new machine. I have figured out a temporary solution, but I still want to share this to you, to see if you have a better solution.

[problem]
The installation is fine. The problem occurs while importing theano in python. Specifically I got the following errors:
```
Problem occurred during compilation with the command line below:

/usr/bin/g++ -shared -g -march=corei7-avx -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rdrnd -mno-f16c -mno-fsgsbase --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=10240 -mtune=corei7-avx -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/jguo29/.local/lib/python2.7/site-packages/numpy/core/include -I/home/jguo29/tools/Python-2.7.8/Include -I/home/jguo29/tools/Python-2.7.8 -o /home/jguo29/.theano/compiledir_Linux-3.2--amd64-x86_64-with-debian-7.7--2.7.8-64/lazylinker_ext/lazylinker_ext.so /home/jguo29/.theano/compiledir_Linux-3.2--amd64-x86_64-with-debian-7.7--2.7.8-64/lazylinker_ext/mod.cpp -L/usr/local/lib -lInclude

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "theano/__init__.py", line 55, in <module>
    from theano.compile import \
  File "theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "theano/compile/function_module.py", line 17, in <module>
    import theano.compile.mode
  File "theano/compile/mode.py", line 11, in <module>
    import theano.gof.vm
  File "theano/gof/vm.py", line 569, in <module>
    import lazylinker_c
  File "theano/gof/lazylinker_c.py", line 116, in <module>
    preargs=args) 
  File "theano/gof/cmodule.py", line 2009, in compile_str    
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): /usr/bin/ld: cannot find -lInclude. collect2: error: ld returned 1 exit status.
```

It is weird that there is such a dynamic library linking: -lInclude. I have no idea what it is. I googled it and found nothing.

[my solution]
I filter the "-lInclude" in the command by modifying the line-1975 of `theano/gof/cmodule.py` from
```
cmd.extend(['-l%s' % l for l in libs])
```
to
```
cmd.extend(['-l%s' % l for l in libs if l != "Include"])
```

I know this is not an elegant solution, but I simply don't know how does this happen. I didn't meet this problem when I used theano before...

**Comment by nouiz** [comment]
At the point where you did your work around, can you run this and give me
the output:

print libs
print std_libs()
print lib_dirs
print std_lib_dirs()

The goal is to find where "Include" get in the list libs. That will help
find the root of the problem.


Also, what is your OS?

**Comment by nouiz** [comment]
closing since no news and nobody else reported it. If someone have this problem, give us the answer to the question in the comment above to allow us to fix this.

**Comment by dudheit314** [comment]
I think I got the same issue, see #3556
