### ISSUE TITLE
Import error under Windows: lazylinker_c.c

### ISSUE THREAD

**Issue by gsmafra** [Theano/Theano#2732]
Hello

I've had the following error when trying to import theano over Windows 7 64 bits, Anaconda, Python 2.7, using Spyder. I installed the library using the pip pull with no problems

The C code seems to be the file lazylinker_c.c

I already installed and succesfully imported theano in another machine with similar configurations and had no problems at all

Obs: I am new to Python

>00607                 err = PyList_SetItem(self->var_computed_cells[in_idx], 0, zero);
(...)
01075       PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01076   
01077       return RETVAL;
01078   }
01079   
01080   
Problem occurred during compilation with the command line below:
g++ -shared -g -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Users\Gustavo\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Gustavo\Anaconda\include -o C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp -LC:\Users\Gustavo\Anaconda\libs -LC:\Users\Gustavo\Anaconda -lpython27
Traceback (most recent call last):

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_code
    self.showtraceback()

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 1848, in showtraceback
    value, tb, tb_offset=tb_offset)

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 1240, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 1157, in structured_traceback
    self, etype, value, elist, tb_offset, number_of_lines_of_context

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 511, in structured_traceback
    lines = ''.join(self._format_exception_only(etype, value))

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\IPython\core\ultratb.py", line 623, in _format_exception_only
    Colors.Normal, s))

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 45: ordinal not in range(128)

Update: g++ was not in my PATH variables, new error now

>===============================
===============================
C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp:1: sorry, unimplemented: 64-bit mode not compiled in
C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp: In function `double pytime(const timeval*)':
C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp:44: error: `gettimeofday' undeclared (first use this function)
C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp:44: error: (Each undeclared identifier is reported only once for each function it appears in.)

>Traceback (most recent call last):

>  File "<ipython-input-1-3397704bd624>", line 1, in <module>
    import theano

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\__init__.py", line 55, in <module>
    from theano.compile import 
 > File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\compile\__init__.py", line 9, in <module>
    from theano.compile.function_module import *

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\compile\function_module.py", line 17, in <module>
    import theano.compile.mode

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\gof\vm.py", line 569, in <module>
    import lazylinker_c

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\gof\lazylinker_c.py", line 124, in <module>
    preargs=args)

>  File "C:\Users\Gustavo\Anaconda\lib\site-packages\theano\gof\cmodule.py", line 2009, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

>. C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp:44: error: (Each undeclared identifier is reported only once for each function it appears in.)ed in

>00001   #include <Python.h>
00002   #include "structmember.h"
00003   #include <sys/time.h>
00004   
00005   // Old Python compatibility from here:
00006   // http://www.python.org/dev/peps/pep-0353/
(...)
01075       PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01076   
01077       return RETVAL;
01078   }
01079   
01080   
>Problem occurred during compilation with the command line below:
C:\Dev-Cpp\bin\g++.exe -shared -g -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Users\Gustavo\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Gustavo\Anaconda\include -o C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp -LC:\Users\Gustavo\Anaconda\libs -LC:\Users\Gustavo\Anaconda -lpython27

Update 2: I think my compiler was too old, replaced by 4.9.2

I have lots of text in the error but the important part seems to be this one:

>Problem occurred during compilation with the command line below:
C:\cygwin64\bin\g++.exe -shared -g -march=corei7 -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Users\Gustavo\Anaconda\lib\site-packages\numpy\core\include -IC:\Users\Gustavo\Anaconda\include -o C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp -LC:\Users\Gustavo\Anaconda\libs -LC:\Users\Gustavo\Anaconda -lpython27

I already tried to do the cxxflags march trick but it doesn't work

**Comment by ddofer** [comment]
Same issue/errors. 
After printing that out, the error message changes to one involving gof (when I try importing again in the same python session). 
Windows 7.1 , 64 Bit, Anaconda. Tried installing bleeding edge Theano as well as (seperately) the pip version. 

![tuntitled](https://cloud.githubusercontent.com/assets/5120387/6998653/6e03c956-dbf2-11e4-984e-a41024abfc40.png)

**Comment by abergeron** [comment]
The cmd screenshot you posted conviniently truncates all error messages after the first two characters, therefore I can't say anything.  My guess however is that you have the same error are the OP, which is that the gcc version you installed does not support 64-bits (like the very first error message seems to indicate:

```
C:\Users\Gustavo\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\lazylinker_ext\mod.cpp:1: sorry, unimplemented: 64-bit mode not compiled in
```

Get a build of gcc that supports 64-bit and try again.

**Comment by gsmafra** [comment]
Thank you, abergeron, but I had already realized that, see my "Update 2". New message doesn't present anything like that ("sorry, unimplemented: 64-bit mode not compiled")

**Comment by abergeron** [comment]
The Update 2 does not contain the full error output so I can't say anything about it.

**Comment by gsmafra** [comment]
Too big to paste directly here

http://m.uploadedit.com/ba3b/1428442797909.txt

**Comment by abergeron** [comment]
The very first error indicates that you have problems with your environnement.  Fix those, and if you still have problems with theano then, we'll look at it.
```
C:\Users\Gustavo\Anaconda\include/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
```

**Comment by gsmafra** [comment]
I replaced my compiler by the one recommended in the install section
(http://deeplearning.net/software/theano/install_windows.html)

Now I have this

http://m.uploadedit.com/ba3c/1428860353377.txt

I wasn't able to find the "openmp support option" though

Just to be sure, if I don't need CUDA right now then I don't need to follow the "Visual Studio and CUDA" steps in the same install section right?

**Comment by gsmafra** [comment]
Solved: installed libpython
http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by nouiz** [comment]
Thanks for the info, this was also needed for anaconda instruction that is
updated there:

https://github.com/Theano/Theano/pull/2764

One error you had was hiding something else. That PR fix that problem too.

**Comment by DMU-3dTuneIn** [comment]
For Anaconda user install theano from:  conda install theano pygpu

**Comment by deaspo** [comment]
Followed and installed for Anaconda and now am getting the error: "RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.". Followed the instruction from [here](https://github.com/Theano/Theano/issues/6568). Didn't solve my problem, so I downgraded to 2017 version, conda install mkl=2017.

Now I can run Theano without problems
