### ISSUE TITLE
Does theano support cuda7 ?

### ISSUE THREAD

**Issue by zarzen** [Theano/Theano#2736]
I want to buy a new video card , gtx 970 maybe. I find only cuda 7 support 900 series card, but online documents(installation part) not mentions cuda 7

**Comment by nouiz** [comment]
Do not ask the same questions on all our mailing list and here. You won't have an answer faster. I got all of them. This ask us more time to answer you when we have multiple time the same questions.

For support questions, the mailing list is better. More people see it. The answer is yes.

**Comment by zarzen** [comment]
Sorry, I just think that maybe some people prefer mail list and other
prefer git issues.
I will not do this again.
