### ISSUE TITLE
error: unknown type name 'int64_t'

### ISSUE THREAD

**Issue by friskit-china** [Theano/Theano#2737]
Hi,

I use theano on my Mac OS 10.10 (Mac Pro 2013).
When I used Intel Xeon(R) CPU E5-1650 v2 by OpenCl, I got an compile error like this:
```
<program source>:68:20: error: unknown type name 'int64_t'
  o0 = (GLOBAL_MEM ga_long *)tmp;
                   ^
<program source>:42:17: note: expanded from macro 'ga_long'
#define ga_long int64_t
```
I think the problem comes from the absence of `#include <stdint.h>`, but where should I put it?

**Comment by abergeron** [comment]
While the gpuarray backend is included with theano, it not ready for use, especially with OpenCL.  We can't really offer support with it for now, but if you do find out how to fix this and send us a patch, we will look at it.

**Comment by nouiz** [comment]
As no news and we don't have the time for this now, I'll close it. If someone make a PR to fix it in Theano, we will review it.

**Comment by nouiz** [comment]
Here is the PR with the status about OpenCL: https://github.com/Theano/Theano/issues/2936
