### ISSUE TITLE
Bug: debugprint(file='str') does not work for profile=1

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#2738]
To reproduce:
```bash
# works:
python -c 'import theano; x = theano.tensor.matrix("x"); theano.printing.debugprint(theano.function([x], x), file="str")'

# raises: AttributeError: 'str' object has no attribute 'write'
CUDA_LAUNCH_BLOCKING=1 THEANO_FLAGS=profile=1 python -c 'import theano; x = theano.tensor.matrix("x"); theano.printing.debugprint(theano.function([x], x), file="str")'
```
For the empty function (`theano.function([], [])`), no error is raised in either case, if this helps. Tested with the current `master`.

This is not exactly a deal breaker, I just stumbled upon it while debugging something and thought I could just as well report it.

**Comment by nouiz** [comment]
This PR fix it:

https://github.com/Theano/Theano/pull/2740
