### ISSUE TITLE
ifelse is not lazy for tag.test_value

### ISSUE THREAD

**Issue by noskill** [Theano/Theano#2739]
this code would fail with compute_test_value set to 'raise':

from theano import tensor as T
from theano.ifelse import ifelse
import theano
import numpy

theano.config.compute_test_value = 'off' #'raise'

ar = numpy.random.random((1, 2, 2, 2))
x = T.dtensor4('x')
x.tag.test_value = ar
cond = ifelse(T.eq(x.shape[0], 1), x[0], x[1])
f = theano.function([x], cond)
print(f(ar))

**Comment by nouiz** [comment]
You are right that we compute all inputs data for test_value.

Would this help you or this is just a corner case you found by change?

**Comment by lamblin** [comment]
`ifelse` is not even necessary in that case. The fact that you call `x[1]` with test values will try to evaluate that expression, that is the point of test values.
If you do not want to evaluate it, then you can do something like:
```python
idx = ifelse(T.eq(x.shape[0], 1), 0, 1)
cond = x[idx]
```

**Comment by noskill** [comment]
Ok, thanks. I found a  way to remove ifelse from my code.
