### ISSUE TITLE
Creating large shared arrays fails (cublas)

### ISSUE THREAD

**Issue by git-** [Theano/Theano#2743]
The following error happens when trying to create shared variables from large matrices:

```
File "/home/user/Theano/theano/compile/sharedvalue.py", line 208, in shared
    allow_downcast=allow_downcast, **kwargs)
File "/home/user/Theano/theano/sandbox/cuda/var.py", line 209, in float32_shared_constructor
    deviceval = type_support_filter(value, type.broadcastable, False, None)
RuntimeError: CUBLAS error 'an access to GPU memory space failed' while copying 2211840000 data element to device memory.
```

**Comment by abergeron** [comment]
Does your GPU have 8.8Gb of RAM or more?  Because if it doesn't then that is your problem.

**Comment by git-** [comment]
I tried with a Titan X and with a Tesla K6000 (both have 12 GB of vram) and it failed in the same way both times.

**Comment by abergeron** [comment]
The memory may get fragmented sometimes preventing you from using a very large allocation that should fit in the remaining memory.

Otherwise it's possible that you just hit an overflow case since we store sizes with ints and that doesn't play well with values above 2Gb (and even worse with values above 4Gb).

**Comment by git-** [comment]
As I said, I tried on two different GPUs and the outcome was the same. As such, I think it's safe to say that in all likelihood, it is an overflow-related problem.

**Comment by lamblin** [comment]
The new GPU back-end uses 64-bit shapes and strides, so it should not happen again.
