### ISSUE TITLE
Opt: Reshape(arange(x)) -> arange(x) when this do not change the shapes, number of dimensions.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2752]
```
>>> import theano
>>> i=theano.tensor.iscalar()
>>> m=theano.tensor.mgrid[0:i,]
>>> f=theano.function([i], m)
>>> theano.printing.debugprint(f, print_type=True)
Reshape{1} [@A] <TensorType(int32, vector)> ''   3
 |ARange [@B] <TensorType(int32, vector)> ''   1
 | |TensorConstant{0} [@C] <TensorType(int8, scalar)>
 | |<TensorType(int32, scalar)> [@D] <TensorType(int32, scalar)>
 | |TensorConstant{1} [@E] <TensorType(int8, scalar)>
 |MakeVector [@F] <TensorType(int64, vector)> ''   2
   |Elemwise{Cast{int64}} [@G] <TensorType(int64, scalar)> ''   0
     |<TensorType(int32, scalar)> [@D] <TensorType(int32, scalar)>
```

This happen in gh-2572

Make this more general, in the sense that if the input is 1d and the output is 1d, what ever created it, remove it (add AssertOp if we can't assert that the shape are the same)

**Comment by lamblin** [comment]
There should probably be an assertion by default if we cannot determine that the shapes are equal (or that the new shape is -1).

**Comment by nouiz** [comment]
In fact, there is no optimization local_useless_reshape, only local_reshape_chain. If the shape are the same, just remove it, otherwise, should we set an assert op? I think we could keep it.
