### ISSUE TITLE
Stochastic EOFError

### ISSUE THREAD

**Issue by diogo149** [Theano/Theano#2754]
This error occured while performing hyperparameter optimization running on the same process multiple times, and also running on multiple processes (thus the exact code has run several times before), and this only occurred on the 40+th run on a single process. It seems hard to reproduce, so feel free to not bother, but perhaps the stack trace would be enough to see what's wrong. (:

```
/home/diogo/repos/Theano/theano/compile/function.pyc in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_
unused_input)
    264                 allow_input_downcast=allow_input_downcast,
    265                 on_unused_input=on_unused_input,
--> 266                 profile=profile)
    267     # We need to add the flag check_aliased inputs if we have any mutable or
    268     # borrowed used defined inputs

/home/diogo/repos/Theano/theano/compile/pfunc.pyc in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused
_input)
    509     return orig_function(inputs, cloned_outputs, mode,
    510             accept_inplace=accept_inplace, name=name, profile=profile,
--> 511             on_unused_input=on_unused_input)
    512 
    513 

/home/diogo/repos/Theano/theano/compile/function_module.pyc in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input)
   1464                    profile=profile,
   1465                    on_unused_input=on_unused_input).create(
-> 1466                        defaults)
   1467 
   1468     t2 = time.time()

/home/diogo/repos/Theano/theano/compile/function_module.pyc in create(self, input_storage, trustme)
   1322             theano.config.traceback.limit = 0
   1323             _fn, _i, _o = self.linker.make_thunk(
-> 1324                 input_storage=input_storage_lists)
   1325         finally:
   1326             theano.config.traceback.limit = limit_orig

/home/diogo/repos/Theano/theano/gof/link.pyc in make_thunk(self, input_storage, output_storage)
    517     def make_thunk(self, input_storage=None, output_storage=None):
    518         return self.make_all(input_storage=input_storage,
--> 519                              output_storage=output_storage)[:3]
    520 
    521     def make_all(self, input_storage, output_storage):

/home/diogo/repos/Theano/theano/gof/vm.pyc in make_all(self, profiler, input_storage, output_storage)
    895                                                  storage_map,
    896                                                  compute_map,
--> 897                                                  no_recycling))
    898                 if not hasattr(thunks[-1], 'lazy'):
    899                     # We don't want all ops maker to think about lazy Ops.

/home/diogo/repos/Theano/theano/sandbox/cuda/__init__.pyc in make_thunk(self, node, storage_map, compute_map, no_recycling)
    257                                     enable_cuda=False)
    258         return super(GpuOp, self).make_thunk(node, storage_map,
--> 259                                              compute_map, no_recycling)
    260 
    261 theano.compile.debugmode.default_make_thunk.append(

/home/diogo/repos/Theano/theano/gof/op.pyc in make_thunk(self, node, storage_map, compute_map, no_recycling)
    737                 logger.debug('Trying CLinker.make_thunk')
    738                 outputs = cl.make_thunk(input_storage=node_input_storage,
--> 739                                         output_storage=node_output_storage)
    740                 fill_storage, node_input_filters, node_output_filters = outputs
    741 

/home/diogo/repos/Theano/theano/gof/cc.pyc in make_thunk(self, input_storage, output_storage, keep_lock)
   1071         cthunk, in_storage, out_storage, error_storage = self.__compile__(
   1072             input_storage, output_storage,
-> 1073             keep_lock=keep_lock)
   1074 
   1075         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

/home/diogo/repos/Theano/theano/gof/cc.pyc in __compile__(self, input_storage, output_storage, keep_lock)
   1013                                     input_storage,
   1014                                     output_storage,
-> 1015                                     keep_lock=keep_lock)
   1016         return (thunk,
   1017                 [link.Container(input, storage) for input, storage in

/home/diogo/repos/Theano/theano/gof/cc.pyc in cthunk_factory(self, error_storage, in_storage, out_storage, keep_lock)
   1440         else:
   1441             module = get_module_cache().module_from_key(
-> 1442                 key=key, lnk=self, keep_lock=keep_lock)
   1443 
   1444         vars = self.inputs + self.outputs + self.orphans

/home/diogo/repos/Theano/theano/gof/cmodule.pyc in module_from_key(self, key, lnk, keep_lock)
   1052         # Is the source code already in the cache?
   1053         module_hash = get_module_hash(src_code, key)
-> 1054         module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
   1055         if module is not None:
   1056             return module
/home/diogo/repos/Theano/theano/gof/cmodule.pyc in _get_from_hash(self, module_hash, key, keep_lock)
    962             if (key[0] and not key_broken and
    963                 self.check_for_broken_eq):
--> 964                 self.check_key(key, key_data.key_pkl)
    965             self._update_mappings(key, key_data, module.__file__, check_in_keys=not key_broken)
    966             return module

/home/diogo/repos/Theano/theano/gof/cmodule.pyc in check_key(self, key, key_pkl)
   1114         # other key.
   1115         with open(key_pkl, 'rb') as f:
-> 1116             key_data = cPickle.load(f)
   1117 
   1118         found = sum(key == other_key for other_key in key_data.keys)

EOFError: ('The following error happened while compiling the node', GpuElemwise{Composite{(i0 * (sqrt((i1 - (i2 ** i3))) / (i1 - (i4 ** i3))))},no_inplace}(CudaNdarrayConstant{4.63060678157e-05}, C
udaNdarrayConstant{1.0}, CudaNdarrayConstant{0.999000012875}, GpuElemwise{add,no_inplace}.0, CudaNdarrayConstant{0.899999976158}), '\n')
```

**Comment by lamblin** [comment]
I'm confirming that I've seen the same kind of thing happen (@aalmah reported it IRL).
I thought it was maybe one corrupted directory or drive on one machine, but apparently there is a real problem to address.

**Comment by nouiz** [comment]
Is the stack trace always the same?

If so, I would add extra information to the error message to help debug
this.

**Comment by lamblin** [comment]
The last frames of the stack were the same, I think, but I don't think the node was the same (it was not a GPU job).

**Comment by abergeron** [comment]
This seems like a race condition where one process is not finished writing
the pickle when another is trying to load it, since we don't take the lock
for loading.

The proper fix is probably to just ignore the error and not load the cache
entry when that happens, otherwise we would require the lock when reading
the cache also.

2015-04-10 13:17 GMT-04:00 Pascal Lamblin <notifications@github.com>:

**Comment by nouiz** [comment]
I think we can't just ignore this. So I implemented a quick retry mechanism
in this PR:

https://github.com/Theano/Theano/pull/2766

Can you try it and tell if this make the problem disapear?

**Comment by diogo149** [comment]
Sure thing, but it will take me a few days (traveling - sorry, if anyone is waiting on this!).

**Comment by nouiz** [comment]
This pr have been merged and a follow up with a better fix. When you have
the time, just update theano to the dev version and tell us if you continue
to have the problem. Thanks.

**Comment by diogo149** [comment]
I've been running similar jobs, and can't see the issue reoccuring, though it did occur stochastically before.

Should I close the issue?

**Comment by nouiz** [comment]
As it don't happen anymore, I'll close it. Thanks for the report.

**Comment by dhdaines** [comment]
Hi, I am still seeing this problem with Theano 0.8.0 - launching 3-5 jobs at the same time on the same machine, inevitably I get an EOFError at some point (but it is stochastic).

theano.version.full_version is 0.8.0.dev-4b76348319c0b752c7af5c564e3e28d3135194cf

(this is a checkout of the rel-0.8.0 tag)

**Comment by nouiz** [comment]
Can you give the stack trace that you have when this happen? Is the
compiledir/your home directory local to that computer or remote via NFS or
something else?

**Comment by dhdaines** [comment]
Sure, here is an example stack trace.  I have
THEANO_FLAGS=base_compiledir=/tmp/.theano-dhd,floatX=float32 so the
compiledir should be local to each machine (however several jobs do get
scheduled at once on the same machine, as it is a small SGE grid).

  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/compile/function.py",
line 266, in function
    profile=profile)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/compile/pfunc.py",
line 511, in pfunc
    on_unused_input=on_unused_input)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/compile/function_module.py",
line 1466, in orig_function
    defaults)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/compile/function_module.py",
line 1324, in create
    input_storage=input_storage_lists)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/link.py",
line 519, in make_thunk
    output_storage=output_storage)[:3]
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/vm.py",
line 897, in make_all
    no_recycling))
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/op.py",
line 1002, in make_thunk
    compute_map, no_recycling)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/op.py",
line 739, in make_thunk
    output_storage=node_output_storage)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/cc.py",
line 1073, in make_thunk
    keep_lock=keep_lock)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/cc.py",
line 1015, in __compile__
    keep_lock=keep_lock)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/cc.py",
line 1442, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/cmodule.py",
line 1054, in module_from_key
    module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/cmodule.py",
line 964, in _get_from_hash
    self.check_key(key, key_data.key_pkl)
  File
"/data/nas/tools/python/Python-2.7.8-install/lib/python2.7/site-packages/theano/gof/cmodule.py",
line 1116, in check_key
    key_data = cPickle.load(f)
EOFError: ('The following error happened while compiling the node',
Elemwise{Composite{Cast{float64}((i0 *
i1))}}(TensorConstant{8.69498835527e-05}, Sum{acc_dtype=float64}.0), '\n')

(incidentally I have no idea why it is using float64 here... but I doubt
that is related to this problem)

**Comment by nouiz** [comment]
This stack trace is for an old Theano version.

uninstall Theano multiple time to be sure it is not there, then reinstall
it. Install at least Theano 0.8.

I check the current code and there is special code to handle that. So it
should not happen anymore normally.
