### ISSUE TITLE
cannot import name gof error  after installation

### ISSUE THREAD

**Issue by pattysan** [Theano/Theano#2757]
Hello, after installing Theano (I downloaded the pack form the website, unzipped and run pip install from spyder console to run the installation file) I have this error:cannot import name gof.
 I tried to add also the PYTHONPATH from tools-> PYTHONPATHmanager but it still doesn't work.
 I have the feeling  that I have to continue to look at the PYTHONPATH path but I don't know how to fix it.
I looked around on internet but I could not find the same issue.
I don' t know if you need it but here there is the error displayed
import theano
Traceback (most recent call last):

  File "<ipython-input-5-3397704bd624>", line 1, in <module>
    import theano

  File "theano\__init__.py", line 68, in <module>
    from theano.scan_module import scan, map, reduce, foldl, foldr, clone

  File "theano\scan_module\__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt

  File "theano\scan_module\scan_opt.py", line 65, in <module>
    from theano import tensor

  File "theano\tensor\__init__.py", line 7, in <module>
    from theano.tensor.subtensor import *

  File "theano\tensor\subtensor.py", line 14, in <module>
    from theano import gof

ImportError: cannot import name gof

Thank you very much

**Comment by lamblin** [comment]
Please use the `theano-dev` mailing list for support requests, tickets are for bug reports.
In your case, can you try the following:
- make sure your PYTHONPATH contains something that looks like `path\to\theano`, not `path\to\theano\theano`
- make sure your current directory is not inside `theano`.
