### ISSUE TITLE
Setting parameter with default value while missing setting obligatory parameters changes the default value

### ISSUE THREAD

**Issue by jimmycallin** [Theano/Theano#2762]
I'm finding it hard to explain, so here's an example. Notice that in 77, the output is faulty. This is because I changed the default value in 76 without setting the compulsory parameters. This is returned to normal the next time you run the code (78).

```
In [72]: a, b = T.dscalars('a', 'b')
In [73]: c = a + b

In [74]: f = theano.function([Param(a, name='first'), Param(b, default=1, name='second')], c)

In [75]: f(first=1)
Out[75]: array(2.0)

In [76]: f(second=2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-76-091a89f42488> in <module>()
----> 1 f(second=2)

/Users/jimmy/dev/anaconda/envs/py2/lib/python2.7/site-packages/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    581                     raise TypeError("Missing required input: %s" %
    582                                     getattr(self.inv_finder[c], 'variable',
--> 583                                             self.inv_finder[c]))
    584                 if c.provided > 1:
    585                     raise TypeError("Multiple values for input: %s" %

TypeError: Missing required input: a

In [77]: f(first=1)
Out[77]: array(3.0)

In [78]: f(first=1)
Out[78]: array(2.0)
```

**Comment by nouiz** [comment]
thanks for the report.

Did you found it by change and do not get bottered by this? It is a very
unfrequent case. But we still need to fix it.

**Comment by jimmycallin** [comment]
It was purely out of luck (?), although it happened five minutes into me learning Theano (going through the tutorial), so it might cause confusion among newbies like me.

**Comment by nouiz** [comment]
Can you tell us which tutorial pages and which section?

**Comment by jimmycallin** [comment]
Here: 
http://deeplearning.net/software/theano/tutorial/examples.html#setting-a-default-value-for-an-argument

To be clear, there is nothing wrong with the tutorial. I was just trying out different things to see what would happen when removing non-default parameters etc., which is how I discovered the bug.

**Comment by affanv14** [comment]
@nouiz I'd like to take on this issue
