### ISSUE TITLE
Tutorial about nan

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2770]
I do not know a good nan handling tutorial. I think we should make one as this cause frequent questions. A quick draft of a plan:

- most frequent problem, learning rate too high
- run in debugmode with flag DebugMode.check_py=False to know the op that cause this
- MonitorMode pointeur
- small talk about numerical stability issue, (log(x) + 1 vs (log1p(x)), probability get to low that get rounded to 0 and cause nan.
- Others?

**Comment by lamblin** [comment]
We should probably wait for https://github.com/lisa-lab/pylearn2/issues/1172 to be finished.
See also https://github.com/lisa-lab/pylearn2/issues/1171

**Comment by nouiz** [comment]
good idea to wait.

**Comment by dwf** [comment]
@hantek Have you made any progress on this one?

**Comment by hantek** [comment]
Should we write the tutorial based on the implementation of NanGuardMode in pylearn2? But that one is not merged right now.

**Comment by dwf** [comment]
@hantek I don't think it should contain references to NanGuardMode yet. When we move that to Theano, then that is a good addition. For now, look at @nouiz's comments at the top.

**Comment by dwf** [comment]
Fixed by #2849.
