### ISSUE TITLE
Doc, profiling without the Theano flags.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2771]

**Comment by lamblin** [comment]
I'm not sure what you mean by that. Can you elaborate?

**Comment by nouiz** [comment]
In the Theano doc, we tell how to profile with a Theano flags.

I got question on how to do it for only 1 function in the code. This is
possible and it isn't documented.

Mostly, f=theano.function(..., profile=True)
then
f.profile.print_summary()

To compine the profile of many functions

profile=theano.compile.ProfileStats()
theano.function(profile=profile)
theano.function(profile=profile)
...

profile.print_summary()

The exact path of the profileStats much be checked.

**Comment by abergeron** [comment]
Closed with #3703
