### ISSUE TITLE
sequence is too big to load into memory at one time in scan

### ISSUE THREAD

**Issue by wps712** [Theano/Theano#2785]
I'm trying to use scan in my RNN layer. But the input sequence (T frames of images) is so big that it cannot be loaded into memory at a time.  My code is like this:

result, _ = theano.scan(fn=step,
                              sequences=[inputs.T],
                              outputs_info=outputs_info)

Is there a way to load one image at a time? How can I solve this problem?

**Comment by lamblin** [comment]
Please use the theano-users mailing lists for support or help requests, and keep the tickets for bug reports or new feature requests, thanks.
In your case, if the main RAM of your machine is not big enough to load your sequence, you could use a mem-mapped array from the disk to hold it, and use http://deeplearning.net/software/theano/library/tensor/io.html#module-theano.tensor.io to load only part of it at a time.
However, keep in mind that, if you are computing gradients using BPTT with scan, you will need large intermediate buffers as well, so it may not solve your problem completely. If you are truncating the gradient, then maybe you do not need scan, and you can simply compile the inner function and call it in a Python loop.
