### ISSUE TITLE
Follow up Average pooling

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2792]
gh-2783 added average pooling on the CPU. Here is what is left:
- [x] Refactor to have the grad average in a different op that do not that the input of the forward as input (lower memory usage) (The refactor, rename the ops, have a common PoolGrad op that contain the common code for AveragePoolGrad and MaxPoolGrad)
- [x] the grad need support for pooling
- [x] need c code on the CPU.
- [x] no grad of grad (it return grad not implemented)
- [x] on the GPU, this is only supported by cudnn.
- [ ] average grad python code don't support padding (but c code does).

**Comment by lamblin** [comment]
@nouiz I checked the box for "refactor" and "no grad of grad", but I'm not sure. Can you check when you are back?

**Comment by dwf** [comment]
So, there's no average pooling on GPU yet? Is there no optimization that replaces CPU average pooling (via `max_pool_2d`) with CuDNN average pooling?

**Comment by lamblin** [comment]
There is average pooling on GPU via CuDNN, in `theano.sandbox.cuda.dnn.dnn_pool(..., mode='average_inc_pad')` (or `exc_pad` if you prefer).
However, you are right, there is no optimization replacing the CPU op... I'm adding that to the list.

**Comment by dwf** [comment]
Okay, and it should probably warn or flat out error if the replacement fails and your GPU graph is executing partly on CPU, since I think, the majority of the time, this is going to make a model intolerably slow.

**Comment by lamblin** [comment]
Well, actually, I think I was mistaken because the CPU Op is confusingly named `DownsampleFactorMax`, even when performing average pooling... according to the unit tests, average pooling should be transfered to the GPU.
For your second point, you can use [`config.assert_no_cpu_op`](http://deeplearning.net/software/theano/library/config.html#config.assert_no_cpu_op) to detect at least some of these cases.

**Comment by dwf** [comment]
Yes, and you very bizarrely must call max_pool_2d with a particular mode
argument to get average pooling. That probably isn't winning any API design
awards...

**Comment by lamblin** [comment]
#3592

**Comment by dwf** [comment]
@lamblin here's my debugprint:

https://gist.github.com/dwf/054b1ff9ec915a43dd10

Seems like it's not getting transferred even when it's max pooling. WTF.

**Comment by fchollet** [comment]
Is it still the case that there is no Theano average pooling op for GPU?

**Comment by dwf** [comment]
In general, with CuDNN only. So `ignore_border=False` with stride less than the pool size will force you onto the CPU.

**Comment by nouiz** [comment]
Just to be clear.

On GPU, we support AveragePool only with cudnn.
On GPU, for MaxPool, with cudnn, we only support ignore_border=True. For
MaxPool without cudnn, we support only strides==pool size (but we support
both value for ignore_border)

**Comment by nouiz** [comment]
The new gpu back-end support it.
The last point was also done. So closing.
