### ISSUE TITLE
Problems at theano tutorial printing drawing

### ISSUE THREAD

**Issue by zarzen** [Theano/Theano#2793]
My system environment:Mac OS 10.10, python 2.7.9, pydot 1.0.2, theano 0.7.0

First problem:
this code 
```
# before compilation
theano.printing.pydotprint_variables(prediction,
                           outfile="pics/logreg_pydotprint_prediction.png",
                           var_with_name_simple=True)
```
seems wrong. It should be modified like this :
```
# before compilation
theano.printing.pydotprint(prediction,
                           outfile="pics/logreg_pydotprint_prediction.png",
                           var_with_name_simple=True)
```
as the warning code suggests me

Second,
```
if any([x.op.__class__.__name__ in ['Gemv', 'CGemv'] for x in
        train.maker.fgraph.toposort()]):
    print 'Used the cpu'
elif any([x.op.__class__.__name__ == 'GpuGemm' for x in
         train.maker.fgraph.toposort()]):
    print 'Used the gpu'
else:
    print 'ERROR, not able to tell if theano used the cpu or the gpu'
    print train.maker.fgraph.toposort()
```
These codes always print 'ERROR, not able to tell if theano used the cpu or the gpu', though I have already installed gpu support.

**Comment by nouiz** [comment]
For the pydotprint_variable, there is a PR about this, but it didn't fix all of the for now. Thanks for the report.

The if for the error isn't good. Thanks for the report. I have a fix in this PR: gh-2834
