### ISSUE TITLE
help to get a theano out-of-the-box in winpython

### ISSUE THREAD

**Issue by stonebig** [Theano/Theano#2796]
I'm trying to get a working minimal Theano in my default Winpython 3.4.3  beta.
If I succeed, I will incoporate that in the winpython build itself.

Step1:
- starting from https://sourceforge.net/projects/winpython/files/WinPython_3.4/3.4.3.3/betas/
- I have to manually create the theano-nose.bat (as Christoph Gohlke's Theano wheel, the wheel format itself, doesn't apparently do it)
- I have to create a `settings\.theanorc`.

Step2:
- I would like to use the mingwpy that is included by default (not OpenBLAS for the moment)
- I'm a bit lost in:
  - configuration options to put in \.theanorc,
  - modifications to pre-include in the PATH.
- I'm not sure if theano can work with mingwpy, as default procedure is with TDM_GCC.

==> Did anyone have succeeded in step2 ? if so, what did you put in your .theanorc ?

**Comment by lamblin** [comment]
Please use the theano-users mailing list for help requests. We only use tickets for bug reports and feature requests.

**Comment by stonebig** [comment]
ok, done.
