### ISSUE TITLE
opt: subtensor(incsubtensor)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2801]
Low prio as this is currently for graph clean up.

gh-2545 optimized one case, but for the grad, the graph is ugly. It probably don't make a big speed difference in that particular case. The graph:

> > > import theano, numpy
> > > x = theano.tensor.matrix('x')
> > > splits = theano.tensor.ivector('splits')
> > > y = theano.tensor.split(x, splits, n_splits=1).sum()
> > > f = theano.function([x, splits], theano.grad(y, x))  
> > > theano.printing.debugprint(f)

output

```
Alloc [@A] <TensorType(float64, matrix)> ''   7
 |TensorConstant{(1, 1) of 1.0} [@B] <TensorType(float64, (True, True))>
 |Subtensor{int64} [@C] <TensorType(int64, scalar)> ''   6
 | |IncSubtensor{InplaceSet;int8} [@D] <TensorType(int64, vector)> ''   4
 | | |MakeVector [@E] <TensorType(int64, vector)> ''   3
 | | | |Shape_i{0} [@F] <TensorType(int64, scalar)> ''   2
 | | | | |x [@G] <TensorType(float64, matrix)>
 | | | |Shape_i{1} [@H] <TensorType(int64, scalar)> ''   1
 | | |   |x [@G] <TensorType(float64, matrix)>
 | | |Subtensor{int64} [@I] <TensorType(int32, scalar)> ''   0
 | | | |splits [@J] <TensorType(int32, vector)>
 | | | |Constant{0} [@K] <int64>
 | | |Constant{0} [@L] <int8>
 | |Constant{0} [@K] <int64>
 |Subtensor{int64} [@M] <TensorType(int64, scalar)> ''   5
   |IncSubtensor{InplaceSet;int8} [@D] <TensorType(int64, vector)> ''   4
   |Constant{1} [@N] <int64>
```

The node @ D can be removed from the graph.

**Comment by lamblin** [comment]
The earlier test case does not produce that graph anymore. Here is another test:
```python
>>> x = theano.tensor.matrix('x')
>>> i = theano.tensor.iscalar('i')
>>> v = theano.tensor.vector('v')
>>> y = theano.tensor.set_subtensor(x[i], v)
>>> z = y[i]
>>> f = f = theano.function([x, i, v], z)
>>> theano.printing.debugprint(f)
Subtensor{int32} [id A] ''   2
 |IncSubtensor{Set;int32} [id B] ''   1
 | |x [id C]
 | |v [id D]
 | |ScalarFromTensor [id E] ''   0
 |   |i [id F]
 |ScalarFromTensor [id E] ''   0
```

**Comment by Saizheng** [comment]
I think here is some inconsistency about Subtensor and IncSubtensor:
When I check their 'idx_list' attribute, Subtensor returns a **list** pbj, while IncSubtensor returns a **tuple** obj.

**Comment by nouiz** [comment]
Tuple and list are frequently interchangeable as in this case. The
important is what is in them and there length.

**Comment by nouiz** [comment]
done by https://github.com/Theano/Theano/pull/4355
