### ISSUE TITLE
Make a meta op of SparseBlockDot and a cpu version

### ISSUE THREAD

**Issue by bouthilx** [Theano/Theano#2825]
We decided to break ticket #2501 in two tickets. We need a cpu version of SparseBlockDot to implement the hierarchical softmax for both CPU and GPU. 

```sparse_block_dot``` will stay the public interface and should now return a meta op node rather than the gpu implementation. 

CPU implementation doesn't have to be optimized yet. A simple implementation with python/numpy in ```perform()``` will be sufficient.

Also, SparseBlockDot is hard to understand only with textual description. A drawing should be added in the doc to help comprehension. @adbrebs has a nice sketch that he could use.

**Comment by bouthilx** [comment]
@nouiz @abergeron Do you agree with the proposal?

**Comment by nouiz** [comment]
Yes. The CPU op can be a graph. It don't need to be a new op.
Le 23 avr. 2015 17:48, "Xavier Bouthillier" <notifications@github.com> a
écrit :

**Comment by abergeron** [comment]
This was done in #3311
