### ISSUE TITLE
In NanGuardMode, ignore false NaN in GPU random state

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2826]
This should be done when https://github.com/lisa-lab/pylearn2/issues/1172 is finished and NanGuardMode is part of Theano.
A summary of the problem is here: https://github.com/lisa-lab/pylearn2/issues/1465

A solution could be to modify `GPU_mrg_uniform` to add a note in the variables' tag, for instance `state.tag.ignore_nan`, when it is built, and then have `NanGuardMode` check that tag.

**Comment by lamblin** [comment]
Also, we should propagate that tag through dimshuffle / incsubtensor and maybe a couple more, at least when building a state for `scan` from a random state.

**Comment by nouiz** [comment]
This isn't needed with the new back-end.

**Comment by nouiz** [comment]
This is done: https://github.com/Theano/Theano/pull/3768
