### ISSUE TITLE
6 channel conv2d available?? 

### ISSUE THREAD

**Issue by jeehye** [Theano/Theano#2827]
I have two channel speech data and each channel has delta and double-delta.
So I have total 6 channel data.
By using these 6 channel data, I want to run conv2d code.
It runs well in 2 channel and 3 channel case, but doesn't work in 6 channel case.
How can I run conv2d code for 6 channel data??

**Comment by nouiz** [comment]
I do not understand what you mean by 6 channel. I see possibility:

1) Your input to the conv2d is a 6d tensor. In that case, maybe you can
reshape it as 4d and use conv2d.
2) Your input to conv2d is 4d tensor, but one of the dimensions is of size
6. In that case, it should work directly.

**Comment by lamblin** [comment]
Closing since there has been no reply for 1 month. Please reopen if needed.
