### ISSUE TITLE
memory access violation when using non primary gpu inside python thread

### ISSUE THREAD

**Issue by karas84** [Theano/Theano#2837]
I encountered an issue on a dual-gpu machine (dual GTX 980 setup) when calling a function from inside a thread (python threading module).
I was getting an illegal access violation when invoking any theano function from inside a thread when running my script on gpu1; no problems on gpu0.

Here is a simple test to reproduce the issue:
### test.py

``` python
import theano, numpy, threading

x = theano.shared(numpy.random.randn(1).astype(theano.config.floatX), borrow=True, name="x")
f = theano.function([], theano.tensor.exp(x))

def test_function():
    f()

thread1 = threading.Thread(target=test_function)
thread1.start()
thread1.join()
```

You can run it with:

``` bash
$ THEANO_FLAGS=floatX=float32,device=gpu1 python test.py
```

Searching for a solution I stumbled upon [this](http://devblogs.nvidia.com/parallelforall/cuda-pro-tip-always-set-current-device-avoid-multithreading-bugs/) post and fiddling with theano source I checked that, when inside a thread, gpu0 was always the used device, despite the fact that gpu1 was initialized at the beginning of my script.
Following the advice on the blog I made a little and dirty ugly hack and modified cuda_ndarray.cu as follows:
### cuda_ndarray.cu.diff

``` diff
@@ -34,7 +34,7 @@
 #define RELEASE_GIL 1
 #endif
 #if RELEASE_GIL
-#define CNDA_BEGIN_ALLOW_THREADS Py_BEGIN_ALLOW_THREADS
+#define CNDA_BEGIN_ALLOW_THREADS Py_BEGIN_ALLOW_THREADS cudaSetDevice(g_gpu_current_device);
 #define CNDA_END_ALLOW_THREADS Py_END_ALLOW_THREADS
 #else
 #define CNDA_BEGIN_ALLOW_THREADS
@@ -48,6 +48,7 @@
 /////////////////////////

 static int g_gpu_context_active = 0;
+static int g_gpu_current_device = 0;


 PyObject *
@@ -82,6 +83,7 @@

 void * device_malloc(size_t size, int verbose)
 {
+    cudaSetDevice(g_gpu_current_device);
     #if PRECHECK_ERROR
         cudaThreadSynchronize();
         cudaError_t prevError = cudaGetLastError();
@@ -3168,6 +3170,7 @@
     // really necessary.
     int currentDevice;
     cudaGetDevice(&currentDevice);
+    g_gpu_current_device = currentDevice;
     return PyInt_FromLong(currentDevice);
 }
```

With this hack I (probably) ensured that in every thread the right device is set at least once before calling any cuda-related function.
Rerunning the test code yields no errors and my original script started working fine on gpu1 as it already was on gpu0.

**Comment by stergioc** [comment]
I just encountered the same issue on a multi GPU system. However the proposed solution does not apply in the HEAD version of theano. Any ideas?

**Comment by nouiz** [comment]
g_gpu_current_device = currentDevice;

would be better at the end of the function CudaNdarray_gpu_init. This would be sure that it get set at the right time.

I don't like this solution, I think we should make a function that would just call cudaSetDevice() with the right device number. Are you ready to make a PR for this? If not, with the current diff + my small comment?

Note, we are dropping support of the current GPU back-end in favor of the new GPU back-end. But I think having this fixed would be great.

**Comment by lamblin** [comment]
Closing as the old GPU back-end has been removed.
