### ISSUE TITLE
Bug with double reshape optimization

### ISSUE THREAD

**Issue by delallea** [Theano/Theano#285]
The problem is with local_reshape_chain, whose output's broadcastable pattern may not match that of the original output.

This bug can be seen with this code:
https://gist.github.com/1445800

A workaround was suggested in #284, but it may not be the best way to solve this problem. We should probably try to understand why the information about the fact that some input shape dimension was 1 has been lost at some point.

Or, maybe it's just a bad idea to try to guess broadcastability based on constant dimensions? Could we just let the user specify it if he really wants it?

**Comment by nouiz** [comment]
There is a ticket for the general fix: gh-288, so I close this one.
