### ISSUE TITLE
theano 0.7.0 not compatible with python 3(.4?)

### ISSUE THREAD

**Issue by bshabash** [Theano/Theano#2858]
Using python 3.4 and theano 0.7.0 on my computer, or trying to, in any event. Many functions signature are seen as syntax errors by python since they contain tuple arguments 

E.g. all c_code(...) function in basic.py

Also, many "print" around the entire framework still do not use brackets (i.e. written as print "something" instead of print("something))

Also, izip inclusion should be changed and cPickle inclusion should be changed

Unless I am missing something fairly major, this entire library that is supposed to be python 3 compatible is not. So what is the most recent library that won't give me all these syntax errors?

**Comment by dwf** [comment]
Are you installing via `python setup.py install`? That runs 2to3.

We would like to migrate the codebase to a 2/3 compatible subset. Feel free to send pull requests.

**Comment by abergeron** [comment]
As @dwf said, the current install instructions are to use `python3 setup.py install` on python 3.  If you don't do this, you get the errors you mentioned.
