### ISSUE TITLE
Write test for bug introduced by #2750

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#2863]
https://github.com/Theano/Theano/pull/2750/files#diff-3a81c280f7c4d50677c682af9ee70240L1158

Steps to fix (in this order):
* Write a test for the grad of this op.
* Verify that it fails.
* Fix the bug (add "self." in front of the "get_grad" on the above-mentioned line).
* Verify that this makes your test pass.

Ideally make a commit for each of these steps.

**Comment by dwf** [comment]
@thomasmesnard This is your next ticket. It is fairly straightforward, let me know if you have any questions.

**Comment by lamblin** [comment]
Should this be closed, or are there other steps remaining?

**Comment by dwf** [comment]
Arnaud fixed the bug. @thomasmesnard is still assigned to write the test.
