### ISSUE TITLE
MultiChannel Convolutional Neural Network

### ISSUE THREAD

**Issue by ranti-iitg** [Theano/Theano#2878]
I am new to theano, I am going to work on multichannel convolutional network, say 2 channel convoltutional networks, Does Theano contains support for MCCNN ? If does is there any sample code?.
Thanks,
RD

**Comment by nouiz** [comment]
I'm nor 100% sure what is mccnn, bit what I have on mind is supported by
theano. What I have in mind is that some layers are like having 2 conv
layer in parallel. I don't know am example of that, but there is an example
of lenet in the 'deep learning tutorial'.

Fred

**Comment by lamblin** [comment]
Closing since there has been no reply for 1 month.
Please reopen if there is something to add.
