### ISSUE TITLE
Documentation for config.assert_no_cpu_op

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#2881]
Now that #2791 has been merged, we should:
- document the config flag in https://github.com/Theano/Theano/blob/master/doc/library/config.txt
- explain how to use it when a GPU function seems to slow, either in https://github.com/Theano/Theano/blob/master/doc/tutorial/debug_faq.txt, in http://deeplearning.net/software/theano/tutorial/using_gpu.html#tips-for-improving-performance-on-gpu, or in a new "GPU FAQ" section
- Another important use case is when no operation are on the GPU, like when float64 was used by mistake (floatX not set to float32, but device=gpu). We could check if there is no GpuOp in the graph, then we do as the new flag tell.

This is a follow-up to #2471.

**Comment by nouiz** [comment]
Another important use case is when no operation are on the GPU, like when float64 was used by mistake (floatX not set to float32, but device=gpu). I added this to the description.

**Comment by nouiz** [comment]
For the third point, I think you need to make a global optimizer, that take the fgraph completly to test if no op are on the GPU. Should we make an exception if all op are deepcopy? I see from time to time this type of function in pylearn2. @lamblin what do you think?

**Comment by lamblin** [comment]
@nouiz I can see two cases, that may not need a global optimizer:
- all shared variables, inputs, and outputs are on CPU, which would be the case of floatX=float64. We can detect that in theano.function.
- There are shared variables on the GPU, but they are only used by HostFromGpu. That one could be a local_optimizer running HostFromGpu, with the possible exclusion of the case where the client for that transfer is an output.
One thing to consider is how to make it easy (or easier) for a user to specify that some functions are meant to run on CPU, and other on GPU. If it is easy, then a user could do that for the functions consisting only of deepcopy.

**Comment by lamblin** [comment]
The documentation is fixed in #3053.
I opened #3062 for the new case.
