### ISSUE TITLE
Problem with using GPU

### ISSUE THREAD

**Issue by AntreasAntoniou** [Theano/Theano#2890]
I got Theano to work on my CPU and now I am trying to get the GPU to work , all the Flags are set and the .theanorx file is as follows :
[global]
device = gpu
floatX = float32

[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0

[nvcc]
flags=-LC:\Anaconda\lib;
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64
 
I've slowly fixed all the errors I got until i reached this one which I don't really know how to fix.

mod.cu(735): warning: conversion from pointer to smaller integer

mod.cu(1019): warning: statement is unreachable

mod.cu(735): warning: conversion from pointer to smaller integer

mod.cu(1019): warning: statement is unreachable

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -LC:\\Anaconda\\lib; --compiler-bindir C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\amd64 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=1d03da3f6da6d82f277578b3cc55c58a,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\\Users\\Antoniou Antreas\\Anaconda\\lib\\site-packages\\theano-0.7.0-py2.7.egg\\theano\\sandbox\\cuda -IC:\\Users\\Antoniou Antreas\\Anaconda\\lib\\site-packages\\numpy\\core\\include -IC:\\Users\\Antoniou Antreas\\Anaconda\\include -o C:\\Users\\Antoniou Antreas\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -LC:\\Users\\Antoniou Antreas\\Anaconda\\libs -LC:\\Users\\Antoniou Antreas\\Anaconda -lpython27 -lcublas -lcudart')
mod.cu
   Creating library C:/Users/Antoniou Antreas/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64/cuda_ndarray/cuda_ndarray.lib and object C:/Users/Antoniou Antreas/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64/cuda_ndarray/cuda_ndarray.exp
MSVCRT.lib(atonexit.obj) : error LNK2019: unresolved external symbol __imp_EncodePointer referenced in function __atonexitinit
MSVCRT.lib(crtdll.obj) : error LNK2001: unresolved external symbol __imp_EncodePointer
MSVCRT.lib(atonexit.obj) : error LNK2019: unresolved external symbol __imp_DecodePointer referenced in function _onexit
MSVCRT.lib(crtdll.obj) : error LNK2001: unresolved external symbol __imp_DecodePointer
MSVCRT.lib(gs_report.obj) : error LNK2019: unresolved external symbol __imp_IsDebuggerPresent referenced in function __raise_securityfailure
MSVCRT.lib(gs_report.obj) : error LNK2019: unresolved external symbol IsProcessorFeaturePresent referenced in function __report_gsfailure
MSVCRT.lib(gs_support.obj) : error LNK2019: unresolved external symbol __imp_QueryPerformanceCounter referenced in function __security_init_cookie
MSVCRT.lib(gs_support.obj) : error LNK2019: unresolved external symbol __imp_GetCurrentProcessId referenced in function __security_init_cookie
MSVCRT.lib(gs_support.obj) : error LNK2019: unresolved external symbol __imp_GetCurrentThreadId referenced in function __security_init_cookie
MSVCRT.lib(gs_support.obj) : error LNK2019: unresolved external symbol __imp_GetSystemTimeAsFileTime referenced in function __security_init_cookie
MSVCRT.lib(dllmain.obj) : error LNK2019: unresolved external symbol __imp_DisableThreadLibraryCalls referenced in function DllMain
C:/Users/Antoniou Antreas/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64/cuda_ndarray/cuda_ndarray.pyd : fatal error LNK1120: 9 unresolved externals

['nvcc', '-shared', '-O3', '-LC:\\Anaconda\\lib;', '--compiler-bindir', 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\amd64', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=1d03da3f6da6d82f277578b3cc55c58a,-D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-IC:\\Users\\Antoniou Antreas\\Anaconda\\lib\\site-packages\\theano-0.7.0-py2.7.egg\\theano\\sandbox\\cuda', '-IC:\\Users\\Antoniou Antreas\\Anaconda\\lib\\site-packages\\numpy\\core\\include', '-IC:\\Users\\Antoniou Antreas\\Anaconda\\include', '-o', 'C:\\Users\\Antoniou Antreas\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.9-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-LC:\\Users\\Antoniou Antreas\\Anaconda\\libs', '-LC:\\Users\\Antoniou Antreas\\Anaconda', '-lpython27', '-lcublas', '-lcudart']
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavilable)
('The following error happened while compiling the node', Dot22(<TensorType(float32, matrix)>, <TensorType(float32, matrix)>), '\n', 'invalid token in config.blas.ldflags', 'Antreas\\Anaconda\\pkgs\\mkl-rt-11.1-p0\\DLLs')
[Elemwise{exp,no_inplace}(<TensorType(float32, vector)>)]
Looping 1000 times took 14.9609999657 seconds
Result is [ 1.23178029  1.61879337  1.52278066 ...,  2.20771813  2.29967761
  1.62323284]
Used the cpu

So the CPU is used again because of the crash

**Comment by abergeron** [comment]
You should use the theano-users mailing list for problems, not github issues.

From what I can gather from the internet, the problem is related to building 64-bit binaries with some 32-bit options, but I can't really healp much with that.  You would have better luck on the mailing list.

**Comment by nouiz** [comment]
Just a quick comment, never mix 32 and 64 software in the stack. They must
all match.
