### ISSUE TITLE
Theano easy install doesn't work

### ISSUE THREAD

**Issue by MR-T77** [Theano/Theano#2904]
Hi!

I've just installed theano with the 2 lines described in "Easy Installation of an Optimized Theano on Current Ubuntu". After the second step "sudo pip install Theano", I get the following error:
    Running setup.py (path:/tmp/pip_build_root/Theano/setup.py) egg_info for package Theano

   warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.2 in /usr/lib/python2.7/dist-packages (from Theano)
    Requirement already satisfied (use --upgrade to upgrade): scipy>=0.11 in /usr/lib/python2.7/dist-packages (from Theano)
    Installing collected packages: Theano
      Running setup.py install for Theano
        changing mode of build/scripts-2.7/theano-cache from 644 to 755
        changing mode of build/scripts-2.7/theano-nose from 644 to 755
        changing mode of build/scripts-2.7/theano-test from 644 to 755
    
        warning: manifest_maker: MANIFEST.in, line 8: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
        changing mode of /usr/local/bin/theano-nose to 755
        changing mode of /usr/local/bin/theano-cache to 755
        changing mode of /usr/local/bin/theano-test to 755
 
When I test it with   python -c "import numpy; numpy.test()", I get the following messages:
    
    OpenBLAS : Your OS does not support AVX instructions. OpenBLAS is using Nehalem kernels as a fallback, which may give poorer performance.
    Running unit tests for numpy
    NumPy version 1.8.2
    NumPy is installed in /usr/lib/python2.7/dist-packages/numpy
    Python version 2.7.6 (default, Mar 22 2014, 22:59:56) [GCC 4.8.2]
    nose version 1.3.1
        (...)
        Ran 2347 tests in 31.093s

        OK (KNOWNFAIL=1, SKIP=5)

Can anyone help me surpassing this issue?
Thanks in advance

**Comment by lamblin** [comment]
Everything is OK, you do not have any error.
The first warning can be ignored, the second one is only about performance.
Then, the tests says "OK".
Please, in the future, use the mailing list (theano-users@googlegroups.com) instead of tickets for support requests.

**Comment by MR-T77** [comment]
Thanks for the answer. Subsequently, there are other problems (this was the first), but I'll use the mailing list.
