### ISSUE TITLE
A bug in 'local_gpu_lazy_ifelse'

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#2913]
The bug is here: https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/opt.py#L490

When the condition variable (the first argument of `theano.ifelse.ifelse`) is an output of `HostFromGpu`, two other inputs are subjected to `GpuFromHost` (https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/opt.py#L503). But it might be that the condition variable is `float32` and others have different dtypes.

An example:

```python
import numpy
import theano
import theano.ifelse
from theano import tensor
from theano.printing import debugprint

c = theano.shared(numpy.float32(1.0))
x = theano.shared(numpy.zeros((3, 3)))
y = theano.ifelse.ifelse(c, x.mean(), x[0, 0])
theano.function([], [y])
```

This is quite a bad issue for Blocks, because we are using `ifelse` deep inside and the user should be utterly confused getting an optimization failure when they did nothing special.

**Comment by nouiz** [comment]
I'm owkring on it. I'll have a fix shortly.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/2914
