### ISSUE TITLE
nervana kernels

### ISSUE THREAD

**Issue by pranv** [Theano/Theano#2919]
Are there any plans to integrate it with Theano soon?

**Comment by nouiz** [comment]
There is work on this.

1) We work to integrate float16 in the new GPU back-end. This isn't ready
and for now only cover gemm16 (no convolution op)
2) There is a private branch (started when the nervana code wasn't public)
that add convolution to the current GPU back-end. But it do not speed
things up for now. The Python overhead is too big for now.

**Comment by nouiz** [comment]
I created an issue with the status of those kernel:

https://github.com/Theano/Theano/issues/2941
