### ISSUE TITLE
Best way to flatten parameters for later optimization.

### ISSUE THREAD

**Issue by warmspringwinds** [Theano/Theano#2920]
Hello, I am following your tutorials on MLP and I wanted to flatten all the parameters of the network to make it easier to use optimization libraries that usually take only an array of a single dimension.

The cornerstone of my problem is here:
My MLP class has the following line
`self.theta = T.concatenate([self.hidden_layer.theta, self.log_layer.theta], axis=0)`
Here I just collect the flattened parameters from the hidden layer and from the output logistic regression layer.

But then when I try to find derivatives I got an error:
`grad_theta = T.grad(cost_var, classifier.theta)`

Here it is:
`DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: Join.0`

Is it possible to find a  derivative for concatenated variables?

**Comment by nouiz** [comment]
This use case should work. Where did you defined self. Theta? In the
__init__ method?
Le 17 mai 2015 11:15 AM, "Daniil Pakhomov" <notifications@github.com> a
écrit :

**Comment by kyunghyuncho** [comment]
I don't think this will work unfortunately. ``self.theta`` was never used to compute ``cost_var``. The only way I can see is to initialize a large vector (1-D tensor) containing all the parameters, and use slicing to get easier-to-understand parameter variables.

**Comment by lamblin** [comment]
@kyunghyuncho is right, you would have to define one flat vector with all the parameters first, as one shared variable, and slice and reshape it for use in your model. That way, you can directly use the value produced by the optimization algorithm to update the flat theta.
Also, in the future, please use the `theano-users` mailing list for such requests, we try to keep the tickets for bugs and feature requests.
