### ISSUE TITLE
Extracting subtensor with theano variable

### ISSUE THREAD

**Issue by escopeta** [Theano/Theano#2921]
Hi,

I am trying to extract a subtensor in the following way:

x, y = (matrix >= T.max(matrix)).nonzero()

extracted_theano_matrix = theano_matrix[x-6:x+8,y-6,y+8]

I have not been able to do this and haven't found anything online. I would really appreciate it if someone can give me some suggestion on how to do this. Thanks!

**Comment by nouiz** [comment]
Can you give full numpy code that do what you want? I'm not sure what you
want. The code above do not make sence to me and I'm not getting what you
want to do.

**Comment by escopeta** [comment]
I am trying to match a template in an image to find its location (x,y) in the image, followed by  placing the template in a third image that has the same dimensions as the image where the template was matched.

x = T.matrix('x')
template = T.matrix('x')
canvas = T.zeros( x.shape )

conv_out = T.nnet.conv2d( x.dimshuffle('x','x',0,1),
                                            template.dimshuffle('x','x',0,1),
                                            border_mode='full' )
conv_out = reshape( conv_out.shape[2],
                                  conv_out.shape[3] )

x, y = (conv_out >= T.max(conv_out)).nonzero()

canvas = T.set_subtensor(canvas[x-6:x+8, y-6:y+8],
                   T.max(
                      T.concatenate(
                         ( cavas[x-6:x+8, y-6,y+8].dimshuffle('x',0,1),
                            template.dimshuffle('x',0,1) ), axis=0 ), axis=0 ) )

**Comment by escopeta** [comment]
I think I solved it with a probably not very elegant hack. I just made sure I call x1 and y1 as x1[0] and y1[0]. I guess since theano doesn't is not a mind reader (joke), it tries to generalize for multiple point output, but since I know I am only going to get one per template I just make sure I explicitly state that I want to grab the first output of nonzero. Thanks!!
