### ISSUE TITLE
theano.test() should throw an exception if config is not as required

### ISSUE THREAD

**Issue by danstowell** [Theano/Theano#2931]
Hi - I just encountered the same problem as [this user](https://github.com/Theano/Theano/issues/2064) and [this user](http://thread.gmane.org/gmane.comp.mathematics.theano.user/4585) - namely, theano.test() is not supposed to be run with `device=gpu`, but when you run the tests it doesn't give you any clue that this is what's causing all the errors.

This is particularly frustrating when the tests take hours to run, because I have run my machine all afternoon to collect the error report, only to find that it is an entirely unuseful error report.

Luckily I could find the answer online, thanks to those two previous users. But wouldn't it be better if theano.test() would immediately bail out with something like

        ERROR: theano.test() requires config.device='cpu'

**Comment by lamblin** [comment]
You're right, it would be better.

We are already doing that if you run "theano-nose" from the command
line, rather than "theano.test()" from a Python prompt.

I don't remember if there was a reason preventing us from doing that in
theano.test as well, but if there is none, then it is a good idea.

**Comment by nouiz** [comment]
Currently, they do not seem to share code to starts the tests. It would be good to have them do the same/equivalent things.

**Comment by nouiz** [comment]
Do you want to try to implement this? It do not request Theano knowledge.

**Comment by danstowell** [comment]
I think it's unlikely I will find the time to do this. I appreciate it's probably not a big job for someone who knows python, but I'm not set up with the git master etc and I'd rather stick on point releases to the extent that I can...

**Comment by lamblin** [comment]
Fixed by #3078.
