### ISSUE TITLE
Feature Request: Ability to Serialize Graph Models

### ISSUE THREAD

**Issue by jramapuram** [Theano/Theano#2938]
I have been using keras recently (https://github.com/fchollet/keras) & find that recompiling models like LSTM's takes a very look time. It would be nice if the nvcc/gcc/clang compiled binary be retained and offered as a serializable object. Easiest way I'd imagine is to just base64(binary_blob) and serialize.

**Comment by nouiz** [comment]
compiled c code is already cached. what take times is probably the optimization time. This is already on our todo list to optimize this.

You can pickle/unpickle the Theano function to save on the compile time. You must also use this Theano flags: http://deeplearning.net/software/theano/library/config.html#config.reoptimize_unpickled_function

to False.

If that don't do it for now while we continue to work on this, tell us.
