### ISSUE TITLE
Nervana kernel status

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2941]
**Some requirement**
- maxas repo
- nervanagpu repo
- cuda 7 (otherwise, some of nervana kernel compilation crash)
- Maxwell and future GPU architectures. (nervana do not support older generation. This means that it can only be used on GTX750, GTX750Ti, GTX960, GTX970, GTX980 and Titan X)

**Wrapper for the current gpu back-end**

https://github.com/benanne/nervana_theano

It do not have a c interface, so using them can slow down computation in many cases. But very big convolution should be faster

**Wrapper for the new gpu back-end libgpuarray**

There is a PR (should be merged shortly) that include in the new gpu backend, Gemm16:
Some notes on using the code in the new gpu back-end (only gemm16 for now)

**Installation instruction without root access**
Install maxas: https://github.com/NervanaSystems/maxas
- cd ~/repos
- git clone https://github.com/NervanaSystems/maxas.git

Install nervanagpu: https://github.com/NervanaSystems/nervanagpu
- cd ~/repos
- git clone https://github.com/NervanaSystems/nervanagpu.git
- cd nervanagpu
- $PERL5LIB=~/repos/maxas/lib/ PATH=$PATH:~/repos/maxas/bin/ make kernels 
- Put in your PYTHONPATH ~/repos/nervanagpu/

run Theano related Theano tests:
- PYTHONPATH=$PYTHONPATH:~/repos/nervanagpu/ theano-nose theano/sandbox/gpuarray/tests/test_nerv.py -s --pdb --pdb-failure

**Comment by stencilman** [comment]
Is there any update on this, has anyone taken @bennane's work forward? Thanks.

**Comment by nouiz** [comment]
The difficulty is that they don't have a C interface. @benanne used nervana Python interface and this cause big overhead that mostly kill the speed up. We would need someone to make a c interface as we don't have the time to work on this.

**Comment by lamblin** [comment]
Float16 is now part of Cuda and cuDNN, and we have stopped the efforts to integrate Nervana's kernels a while ago.
