### ISSUE TITLE
scan bug?

### ISSUE THREAD

**Issue by june-qijun** [Theano/Theano#2946]
def lp(x, x2):
        return x
    x = T.vector('x')
    res, upd = theano.scan(lp, sequences = dict(input = x, taps = [-2, -1]))
    f = theano.function([x], res, updates = upd)
    print f([1, 2, 3, 4, 5])

And the result is [ 2.  3.  4.]
Shouldn't it be [1, 2, 3] ?

**Comment by carriepl** [comment]
I can reproduce this with the master branch and I obtain the exact same results. I agree that I would expect the result to be [1,2,3] and I didn't find anything in the scan documentation to explain why it shouldn't be the case so I'll start to investigate in the code to better understand what's happening. 

Thanks a lot for reporting this issue.

**Comment by nouiz** [comment]
The fix is merged. Thanks for the report. You need to update Theano to get the fix.

**Comment by june-qijun** [comment]
Thanks for the reply and fix so effectively!
