### ISSUE TITLE
documentation indicates default Ubuntu openBLAS is limited to two threads

### ISSUE THREAD

**Issue by paciorek** [Theano/Theano#2950]
I don't think this is the case. We use Ubuntu's libopenblas-base 0.2.8-6ubuntu1  on 14.04 and can use more than 2 threads. Some BUGS reported a few years ago mention a two thread limit, so perhaps the documentation is based on there being an issue at that time point?

I noticed this in: http://deeplearning.net/software/theano/install_ubuntu.html

**Comment by nouiz** [comment]
Thanks for the info. I'll update the doc when some other stuff next week. I already updated it locally.
