### ISSUE TITLE
DebugMode assertion failure when check_c_code=False

### ISSUE THREAD

**Issue by danstowell** [Theano/Theano#2954]
If I use DebugMode with its default parameters it seems to work as intended, but if I use `theano.function(... , mode=DebugMode(check_c_code=False))` I get this assertion error, which looks to me like a bug:

	% python -c "import theano; import theano.tensor as T; var = T.scalar(); theano.function([var], T.sqrt(T.ones(5) * var), mode=theano.compile.debugmode.DebugMode())(4)"                  
	Using gpu device 0: GeForce GT 730M

	% python -c "import theano; import theano.tensor as T; var = T.scalar(); theano.function([var], T.sqrt(T.ones(5) * var), mode=theano.compile.debugmode.DebugMode(check_c_code=False))(4)"
	Using gpu device 0: GeForce GT 730M
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call__
	    outputs = self.fn()
	  File "/usr/local/lib/python2.7/dist-packages/theano/compile/debugmode.py", line 2151, in deco
	    return f()
	  File "/usr/local/lib/python2.7/dist-packages/theano/compile/debugmode.py", line 1859, in f
	    assert r in r_vals
	AssertionError

My system: theano 0.7.0; Linux 3.13.0-49-generic; Ubuntu 14.04; cuda tools V7.0.27; CUDNN_VERSION 2000; gpu is GeForce GT 730M; python 2.7; gcc Ubuntu 4.8.2-19ubuntu1

**Comment by lamblin** [comment]
I can reproduce that, but I'm not sure whether that bug was introduced recently, or if it has always been there.
DebugMode should fall back on the C/CUDA implementation if there is no `perform` method, but obviously it fails to do so here.

**Comment by nouiz** [comment]
thanks for the report. I have a fix in:
https://github.com/Theano/Theano/pull/2978
