### ISSUE TITLE
Wrong ifelse branch gets executed with FAST_COMPILE

### ISSUE THREAD

**Issue by bartvm** [Theano/Theano#2955]
Not sure if this is expected behaviour, but `ifelse` seems to be executing the wrong branch when `mode=FAST_COMPILE`. The following thing is used in Blocks:

```python
>>> import theano
>>> from theano.ifelse import ifelse
>>> from theano import tensor

>>> x = tensor.vector('x')
>>> y = theano.shared(numpy.zeros((0,)))
>>> is_set = theano.shared(0.)
>>> update_or_set = ifelse(is_set, x + y, x)
>>> f = theano.function([x], [], updates=[(y, update_or_set)])

>>> y.get_value()
array([], dtype=float64)
>>> f([1, 2, 3])
[]
>>> y.get_value()
array([ 1.,  2.,  3.])
>>> is_set.set_value(1.)
>>> f([1, 2, 3])
[]
>>> y.get_value()
array([ 2.,  4.,  6.])
```
That's expected behaviour. Here's where it goes wrong:
```python
>>> y = theano.shared(numpy.zeros((0,)))
>>> is_set = theano.shared(0.)
>>> update_or_set = ifelse(is_set, x + y, x)
>>> f = theano.function([x], [], updates=[(y, update_or_set)], mode='FAST_COMPILE')
>>> f([1, 2, 3])
```
```pytb
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-24-177ff4dc5cd6> in <module>()
----> 1 f([1, 2, 3])

/home/vanmerb/lisa/Theano/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    597         t0_fn = time.time()
    598         try:
--> 599             outputs = self.fn()
    600         except Exception:
    601             if hasattr(self.fn, 'position_of_error'):

/home/vanmerb/lisa/Theano/theano/gof/link.pyc in streamline_default_f()
    524                         old_s[0] = None
    525             except Exception:
--> 526                 raise_with_op(node, thunk)
    527         f = streamline_default_f
    528     elif nice_errors:

/home/vanmerb/lisa/Theano/theano/gof/link.pyc in streamline_default_f()
    520                 for thunk, node, old_storage in zip(thunks, order,
    521                                                     post_thunk_old_storage):
--> 522                     thunk()
    523                     for old_s in old_storage:
    524                         old_s[0] = None

/home/vanmerb/lisa/Theano/theano/gof/op.pyc in rval(p, i, o, n)
    780             # default arguments are stored in the closure of `rval`
    781             def rval(p=p, i=node_input_storage, o=node_output_storage, n=node):
--> 782                 r = p(n, [x[0] for x in i], o)
    783                 for o in node.outputs:
    784                     compute_map[o][0] = True

/home/vanmerb/lisa/Theano/theano/tensor/elemwise.pyc in perform(self, node, inputs, output_storage)
    814             if any(v == 0 for v in values):
    815                 # All non-broadcasted dimensions should be zero
--> 816                 assert max(values) <= 1
    817                 out_shape.append(0)
    818             else:

AssertionError:
Apply node that caused the error: Elemwise{add,no_inplace}(x, <TensorType(float64, vector)>)
Inputs types: [TensorType(float64, vector), TensorType(float64, vector)]
Inputs shapes: [(3,), (0,)]
Inputs strides: [(8,), (8,)]
Inputs values: [array([ 1.,  2.,  3.]), array([], dtype=float64)]

Backtrace when the node is created:
  File "<ipython-input-22-5502ec9ea590>", line 1, in <module>
    update_or_set = ifelse(is_set, x + y, x)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by bartvm** [comment]
Ping @nouiz @lamblin. Would just like to know whether this is indeed a bug, in which case I'll wait for a fix, or expected behaviour, in which case I need to work my way around it in Blocks.

**Comment by lamblin** [comment]
FAST_COMPILE does not have lazy execution (neither does DebugMode or MonitorMode), so both branches of `ifelse` have to be valid and executable.
You can use `optimizer=fast_compile` instead, which will use the standard Mode, with the CVM that supports lazy execution, but without most of the optimizations. The C code for Ops would still be compiled, unlike `mode=FAST_COMPILE`.
I think it would be a good idea to redefine `FAST_COMPILE` so it uses the VM or CVM.

However, if you have one branch that does not make sense or cannot be computed, you may have trouble when computing the gradient, even in the default mode, see #1318.

**Comment by bartvm** [comment]
M'kay. The thing is, `mode=FAST_COMPILE` gives me: `Ran 131 tests in 9.972s` while `optimizer=fast_compile` is still pretty slow: `Ran 131 tests in 51.717s`. That's on my desktop, on Travis `mode=FAST_COMPILE` brings the runtime down from 119 s to 26 s.

We're not using `ifelse` for any gradient computation, it's only use to accumulate averages during training.

**Comment by nouiz** [comment]
I also think we should change to VM without C code. @lamblin and
@abergeron, are you ok with that? If so, I'll update it.

**Comment by lamblin** [comment]
@nouiz Ideally, we would also have an option to use the python thunk if available, rather than computing the C code.
But let's first try with VM and fast_compile, see how it affects the compile time.

**Comment by nouiz** [comment]
I think we must keep the python code only. Yes, that request a new
parameter to VM_Linker.

Bart, if want FAST_COMPILE but with lazy, use "optimizer=fast_compile" and
"cxx=". The second will disable the c code as mode=FAST_COMPILE.

**Comment by nouiz** [comment]
This is fixed. Now FAST_COMPILE will do lazy evaluation without c code by default.
