### ISSUE TITLE
report bug of running cnn model on windows

### ISSUE THREAD

**Issue by CrazymageLee** [Theano/Theano#2956]
When I run the sample convolutional_mlp.py of cnn in DeepLearningTutorials or cnn_centence python.exe will stop working but it just happen on windows. What should I do?

**Comment by nouiz** [comment]
Did you found a fix? If it just stop, it could a be a crash. Do you have some outputs?

This could be linked to a bad installation on python/numpy. What this with the GPU?

Anyway, as you closed it, I suppose you fixed it.

**Comment by CrazymageLee** [comment]
@nouiz   Yes, I fixed it. If I use the x86 version of python and theano this kind of crash happens, so I followed your setup tutorial to setup python with Anaconda package and install mingw x64 version, then the function with cnn works fine. Thank you for your great math library theano!
