### ISSUE TITLE
Speed up inplace elemwise optimizer

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#2962]
Currently in the inplace_elemwise_optimizer opt in tensor/opt.py, we have a quick hack to try to make it faster. If the graph have move then 500 nodes, we only call validate for each group of 10 nodes replaced. If validate fail (a cycle was detected) we skip all those optimization.

We could call validate less frequently to make it faster, but we risk of loosing even more optimization. So here is another algo that would allow to call validate only log(n) when there is no cycle where n is the number of elemwise in the graph and won't skip optimization.

- elem_list = Make a list of all the elemwise node in the graph.
- then set the number of call to validate after log(len(elem_list))
- Then process as before, but if we fail a validate, set all the skipped nodes in a failed_list.
- After having passed on all node in elem_list, put all nodes from failed_list to elem_list and empty failed_list. and restart(set new threashold before calling validate, ...).
- When the threashold is 1, stop iterating. All the element in failed_list can't be applied.

I suppose the number of failed will be low, as we pre-select some of them to limit the number of failure. The only failure should be caused by cycle.

**Comment by t13m** [comment]
In current code, there is a for loop `for node in list(graph.io_toposort(fgraph.inputs, fgraph.outputs)):`,  failed node will be skipped when executing this for loop. If we try to optimize failed nodes iteratively as described, the time cost can be large. What do you think?

**Comment by nouiz** [comment]
There is 2 contradiction goal that we must reconsile.
1) We want optimization fast
2) We want the most optimized graph.

What is taking time in this optimization is the call to validate. So we want to call it the less frequently we can.

So to make the fastest, we could do all opt and call it only once at the end. But if this fail, then we loose all optimization, not just the last one.

So I describe an algo that I think would try to archive both goal most of the time. I think that the number of failure of validate will be low as we prevalidate many case manually before doing the optimization. This allow us to do few call to validate. But I still try to get all optimization when this fail. That is why there is an iteration on the failied node, but where we will do more frequently call to validate to allow part of the failed nodes to get optimized.

Your comment made me think of a small modificaiton to the algo, when validate fail, if there is only 1 node that we optimized, we should not try it again. There is no change that we can optimize it later.

Can you add a link here to your current code? I forget where it is and it isn't in a PR. Can you make a PR with your current code? That would be better.

**Comment by t13m** [comment]
Thanks for explanation. PR is made here https://github.com/Theano/Theano/pull/3033

**Comment by nouiz** [comment]
I think the only way to do this well is via the gh-4233 issue. So I'm closing this.
