### ISSUE TITLE
FunctionGraph.clone_get_equiv() doesn't work.

### ISSUE THREAD

**Issue by ChienliMa** [Theano/Theano#2966]
Hi, I tried to clone a graph using ```clone_get_equiv```. But an exception raise.
It seems that somethings went wrong while attaching features.

```python
In [139]: x = T.iscalar()

In [140]: func = theano.function([x],[x+11])

In [141]: func.maker.fgraph.clone_get_equiv()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-141-5b54943bd7fb> in <module>()
----> 1 func.maker.fgraph.clone_get_equiv()

/Users/ChienliMa/Code/Theano/theano/gof/fg.pyc in clone_get_equiv(self, check_integrity)
    731             e.check_integrity()
    732         for feature in self._features:
--> 733             e.attach_feature(feature)
    734         return e, equiv
    735 

/Users/ChienliMa/Code/Theano/theano/gof/fg.pyc in attach_feature(self, feature)
    528         if attach is not None:
    529             try:
--> 530                 attach(self)
    531             except toolbox.AlreadyThere:
    532                 return

/Users/ChienliMa/Code/Theano/theano/gof/destroyhandler.pyc in on_attach(self, fgraph)
    704         if self.fgraph is not None:
    705             raise Exception(
--> 706                 "A DestroyHandler instance can only serve one"
    707                 " FunctionGraph. (Matthew 6:24)")
    708         for attr in ('destroyers', 'destroy_handler'):

Exception: A DestroyHandler instance can only serve one FunctionGraph. (Matthew 6:24)

```

**Comment by ChienliMa** [comment]
I could not find any good document about ```feature```. 
Someone have any hints about this?

**Comment by nouiz** [comment]
Feature are class that can be added to a FunctionGraph. The function graph
will call the features he have with callback.

In the file theano/gof/toolbox.py, you have the parent class Feature that
document all the possible callback.

DestroyHandler is one particular Feature. It is used to detect cycle in the
graph. This can happen when there is inplace operation. Each DestroyHandler
can be connected to only one FunctionGraph instance. There is other Feature
that support that. This is the error your see.

As you won't change the graph, could you just remove the DestroyHandler
Feature from it before calling clone_get_equiv? You can use
fgraph.remove_feature(the_feature). To find the list of features attached
to an fgraph: fgraph._features.

Fred

**Comment by ChienliMa** [comment]
Thanks. All I want is only the ``equiv``, so I turned to ```graph.clone_get_equiv()```.
Besides, I don't know if it's ok to remove features from ```fgraph``` in ```FunctionMaker```.

**Comment by nouiz** [comment]
You can remove feature when you know what it cause. In this case, it is
safe as this feature is only needed when we modify the fgraph. As we won't
modify the fgraph again, it is not needed anymore.

**Comment by nouiz** [comment]
I think this is solved.
