### ISSUE TITLE
Grad of gpu_contiguous() not always gpu_contiguous?

### ISSUE THREAD

**Issue by 317070** [Theano/Theano#2973]
I noticed that the grad of gpu_contiguous is not always gpu_contiguous? Is there a reason for this? I think it is strange behavior (and had issues with it).

It can be fixed easily by changing
```
class GpuContiguous(GpuOp):
    def grad(self, inputs, dout):
        x, = inputs
        dout, = dout
        dout = as_cuda_ndarray_variable(dout)
        return [dout]
```
to
```
class GpuContiguous(GpuOp):
    def grad(self, inputs, dout):
        x, = inputs
        dout, = dout
        dout = gpu_contiguous(as_cuda_ndarray_variable(dout))
        return [dout]
```

**Comment by lamblin** [comment]
I don't think the grad of GpuContiguous should be GpuContiguous, as there is no reason for the previous Op to expect a contiguous gradient if the next one needs a contiguous input.
If the previous Op needs a contiguous gradient, it should call gpu_contiguous from its grad method.

**Comment by nouiz** [comment]
Agreed. But I think this should be documented. Jonas, do you want that?
That way, the next one won't loose as much time on this then you.
