### ISSUE TITLE
BUG IN FGRAPH.REPLACE OR A LISTENER (2)

### ISSUE THREAD

**Issue by memming** [Theano/Theano#2976]
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.AssertionError'>  local_shape_to_shape_i
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i
ERROR:theano.gof.opt:Optimization failure due to: local_shape_to_shape_i
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/theano/gof/opt.py", line 1527, in process_node

Full error message dump: http://pastebin.com/YTbueDUS

Theano 0.7.0, and also with bleeding edge

I dumped the [function with `function_dump`](http://www.memming.com/temp/bug_function_dropout.pkl).

**Comment by nouiz** [comment]
I'm able to reproduce it. thanks.

A quick workaround is to disable one optimization with this Theano flag:
"optimizer_excluding=local_shape_to_shape_i"

**Comment by nouiz** [comment]
You have a scan in your graph with random numbers. Did you pass both
outputs of the scan function to theano.function?

It happen that people forget to pass the second outputs.

**Comment by nouiz** [comment]
Can I add your pickle in Theano for a permanant test? Replicating this
manually is hard.

I have a fix in gh-3003.

thanks for the report.

**Comment by memming** [comment]
Sure. Feel free to add it to the test.

Thank you for fixing it.
