### ISSUE TITLE
to_cudandarray() method fails to perform the conversion from GPUArray

### ISSUE THREAD

**Issue by miguelalexanderdiaz** [Theano/Theano#2986]
From the [theano.misc.pycuda_utils.pycuda_utils.py](https://github.com/Theano/Theano/blob/master/theano/misc/pycuda_utils.py)
Theano Version: 0.7.0
When you try to perform the conversion from GPUArray to CudaNdarray using this method fails showing the following error. 

>  Exception: CudaNdarray_from_gpu_pointer: The gpu pointor is not an long

The offender line is the line 64

``` .python
ptr = int(x.gpudata) # in pycuda trunk, y.ptr also works, which is a little cleaner
```

The fix is simply change the **int** by **long** 

``` .python
ptr = long(x.gpudata) # in pycuda trunk, y.ptr also works, which is a little cleaner
```

**Comment by nouiz** [comment]
Which version of python do you use? Which version of pycuda do you use? It
was working before, I would like to make sure we don't break old
installation. So I would like to understand more about when this fix is
needed.

**Comment by miguelalexanderdiaz** [comment]
I'm using python 2.7.9 and pycuda 2014.1, probably the change it's in the last pycuda's version

**Comment by lamblin** [comment]
Also, which operating system are you using?

**Comment by miguelalexanderdiaz** [comment]
I can't understand why the OS matters, but... I'm using Ubutu 14.04

**Comment by lamblin** [comment]
OK, thanks. I thought the OS could matter because for instance on windows, a Python `int`, which is a C `long`, may not be large enough to hold a 64-bit pointer.

**Comment by miguelalexanderdiaz** [comment]
ohh I see, thanks for the clarification

**Comment by lamblin** [comment]
This file has been removed from Theano with the old GPU back-end.
