### ISSUE TITLE
Lack of varstr quoting in pydotprint

### ISSUE THREAD

**Issue by diogo149** [Theano/Theano#2988]
I found this error with trying to print a graph: `InvocationException: Program terminated with status: 1. stderr follows: Error: /tmp/diogo149/tmpifE4cr: syntax error in line 7 near '='`

With the resulting dot file looking like below:
```
digraph G {
"Subtensor{int64__}" [shape=ellipse, style=filled, fillcolor="#FFAAFF"];
"name=default TensorType(float32, matrix)" [shape=box, style=filled, fillcolor=green];
"name=default TensorType(float32, matrix)" -> "Subtensor{int64__}"  [color=blue, label="0 TensorType(float32, matrix)"];
"val=0 int64" [shape=box, style=filled, fillcolor=green];
"val=0 int64" -> "Subtensor{int64__}"  [label="1 int64"];
"Subtensor{int64__}" -> name=default[0:] TensorType(float32, matrix)  [label="TensorType(float32, matrix)"];
Alloc [shape=ellipse, style=filled, fillcolor="#FFAA22"];
...
```

It seems like the problem is the lack of quoting for `name=default[0:] TensorType(float32, matrix)`, and adding in a line (`varstr = '"%s"' % varstr`) to `theano.printing.py` to quote it does fix the issue (but causes other problems, hence me not submitting a fix).

**Comment by nouiz** [comment]
This work here. What is your OS, python version, dot version, pydot version?

**Comment by diogo149** [comment]
OS: archlinux
Python: 2.7.9
dot: dot - graphviz version 2.38.0 (20140413.2041)
pydot: 1.0.2

**Comment by nouiz** [comment]
You have a very old pydot version. Can you update it to 1.0.28? All work
with that version. There have been big change in it since then and I don't
think it is easy to support all the version.

2015-06-01 20:41 GMT-04:00 diogo149 <notifications@github.com>:

**Comment by diogo149** [comment]
You are very right, my apologies! If it would be helpful, I'd happily make a pull request that mentions upgrading pydot version to avoid this happening (such as in https://github.com/Theano/Theano/pull/1521/files). For now, I'll close this. Thank you very much (:

On that note, that previous pull request mentions that pydot 1.0.28 is known to be bugged. Would it still be recommended to use 1.0.25?

**Comment by diogo149** [comment]
Nevermind the question, turns out that code is now deprecated. (:

**Comment by nouiz** [comment]
pydotprint_variable is deprecated as pydotprint() do the same. Did you had
problems with pytdotprint? If so, added a check and give a better error
message is always useful.
