### ISSUE TITLE
Gradient of the power 0 monomial at zero is nan (in fast_compile mode)

### ISSUE THREAD

**Issue by ogrisel** [Theano/Theano#2995]
It seems that `theano.grad` yields an unpected `nan` for the following case:

``` python
>>> import theano
>>> theano.config.optimizer = 'fast_compile'
>>> x = theano.tensor.fscalar()
>>> theano.tensor.grad((x ** 0), x).eval({x: 0.})
array(nan, dtype=float32)
```

arguably 0^0 can be considered undefined. However Python defines it at 1.0, hence I would expect the gradient at 0 to be zero.

Furthermore, theano also define 0^0 to be 1.0:

``` python
>>> (x ** 0).eval({x: 0})
array(1.0, dtype=float32)
>>> (0 ** x).eval({x: 0})
array(1.0, dtype=float32)
```

which makes me think that `grad((x ** 0), x).eval({x: 0.})` should be 0. instead of `nan`.

**Comment by ogrisel** [comment]
Note: this problem only happens with `theano.config.optimizer = 'fast_compile'`.

**Comment by nouiz** [comment]
fast_compile do not enable all optimization. By default (0 * x) will always
be optimized to 0. This is sometimes what you want, but other times, it
isn't.

fast_compile disable that particular optimization. So the nan generate by
this part of the grad graph:

 |Elemwise{pow} [@C] ''   0
   |<TensorType(float32, scalar)> [@D]
   |TensorConstant{-1} [@E]

will be  be multiplied by 0 (so the nan stay).

Why do you want to use fast_compile with that case? I need to leave now,
but we can find the missing optimization for that case and you could enable
it with optimizer_including=...

To see the optimization executed, use the flag optimizer_verbose=True. You
can try to include them to find the one missing. Probably
add_canonizer_group or local_mul_canonizer would do it. If you don't find
(it could be difficult, it depend of each case), just tell us. If you think
we need to change the default, tell us too.

**Comment by ogrisel** [comment]
I had not originally understood that this behavior was caused by the lack of an optimization (I forgot that I had enabled the `fast_compile` mode). I think some users might consider the nan result as a bug rather than the lack of an optimization. Others might disagree. I have not strong opinion. If there is an easy / cheap way to ensure that the gradient of a polynomial is always defined I think it should be made so whatever the level of optimization to enforce correctness as much as possible and therefore [the principle of least astonishment](http://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by Huarong** [comment]
The is a trap indeed. I have some codes with theano.config.optimizer = 'None', and the T.grad produces `nan` results. When I delete the theano.config.optimizer = 'None', everything goes fine.

Hope the code gives us some warnings in this situation.

**Comment by nouiz** [comment]
What about including Theano stability optimization in fast compile? We
could make an fast_unstable mode that is current fast_compile. People
should guess what it does I think. What do you think?

**Comment by Huarong** [comment]
Sorry I'm new to Theano, and do not know much about Theano stability optimization.
I think when computing `T.grad` with `then.config.optimizer`, just simply give some warnings.
