### ISSUE TITLE
An update must have the same type as the original shared variable

### ISSUE THREAD

**Issue by jingruixiaozhuang** [Theano/Theano#2997]
```
 vels = []
 grads = T.grad(cost, params)
 for param_i in params:
        vels.append(theano.shared(np.asarray(param_i.get_value() * 0., dtype = theano.config.floatX)))
for param_i, grad_i, vel_i, weight_type in \
                zip(params, grads, vels, weight_types):

            if weight_type == 'W':
                real_grad = grad_i + eta * param_i
                real_lr = lr
            elif weight_type == 'b':
                real_grad = grad_i
                real_lr = lr
            elif weight_type == 'W_ful':           # default finetune the network
                real_grad = grad_i + eta * param_i
                real_lr = 2. * lr
            elif weight_type == 'b_ful':
                read_grad = grad_i
                read_lr = 2. * lr
            else:
                raise TypeError("Weight Type Error")

            if config['use_nesterov_momentum']:
                vel_i_next = mu ** 2 * vel_i - (1 + mu) * real_lr * real_grad
            else:
                vel_i_next = mu * vel_i - real_lr * real_grad  #correspond to the update role of the paper

            updates.append((vel_i, vel_i_next))
            updates.append((param_i, param_i + vel_i_next)) 
```
I debug the code but: 
```
TypeError: ('An update must have the same type as the original shared variable (shared_var=<CudaNdarrayType(float32, vector)>, shared_var.type=CudaNdarrayType(float32, vector), update_val=Elemwise{sub,no_inplace}.0, update_val.type=TensorType(float32, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
```
I don't really understand why! Hope for anyone can help me solve this problem.

**Comment by nouiz** [comment]
The shared var you try to update is a vector of float32. But the new value end up being a matrix of float32. So check that each pair of update have the same type and try to traceback to where the change in the number of dimensions happen. Doing element wise operation between a vector and a matrix give a matrix.

What is eta? Could it be a matrix?

**Comment by nouiz** [comment]
as there is no response and this is a user problem, I'll close this issue. If you still have questions, you can still reply here. But otherwise, using the theano-user mailing list is better for those type of questions.

**Comment by aimaaonline** [comment]
def adadelta(lr, tparams, grads, emb11, mask11, emb21, mask21, y, cost):
    zipped_grads = [theano.shared(p.get_value() * numpy_floatX(0.),
                                  name='%s_grad' % k)
                    for k, p in tparams.iteritems()]
    running_up2 = [theano.shared(p.get_value() * numpy_floatX(0.),
                                 name='%s_rup2' % k)
                   for k, p in tparams.iteritems()]
    running_grads2 = [theano.shared(p.get_value() * numpy_floatX(0.),
                                    name='%s_rgrad2' % k)
                      for k, p in tparams.iteritems()]

    zgup = [(zg, g) for zg, g in zip(zipped_grads, grads)]
    rg2up = [(rg2, (0.95 * rg2 + 0.05 * (g ** 2)))
             for rg2, g in zip(running_grads2, grads)]

    **f_grad_shared = theano.function([emb11, mask11, emb21, mask21, y], cost, updates=zgup + rg2up,
                                    name='adadelta_f_grad_shared')**

    updir = [-tensor.sqrt(ru2 + 1e-6) / tensor.sqrt(rg2 + 1e-6) * zg
             for zg, ru2, rg2 in zip(zipped_grads,
                                     running_up2,
                                     running_grads2)]
    ru2up = [(ru2, (0.95 * ru2 + 0.05 * (ud ** 2)))
             for ru2, ud in zip(running_up2, updir)]
    param_up = [(p, p + ud) for p, ud in zip(tparams.values(), updir)]

    f_update = theano.function([lr], [], updates=ru2up + param_up,
                               on_unused_input='ignore',
                               name='adadelta_f_update', allow_input_downcast=True)

    return f_grad_shared, f_update


-------------------------------------------------------------------------------------------------------
Getting this error



TypeError: ('An update must have the same type as the original shared variable (shared_var=1lstm1_U_rgrad2, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')TypeError: ('An update must have the same type as the original shared variable (shared_var=1lstm1_U_rgrad2, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
