### ISSUE TITLE
Program runs fine on cpu, when I run on GPU grad does not work.

### ISSUE THREAD

**Issue by dxyzab** [Theano/Theano#3007]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 529, in grad
    handle_disconnected(elem)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 516, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: HostFromGpu.0

Can't HostFromGpu be made differentiable by copying the grads from the GPU?

**Comment by nouiz** [comment]
This is very surprising. Can you uninstall all Theano version. Do it a few
times to make sure there wasn't multiple copy installed and install Theano
dev version. Then try again.

**Comment by dxyzab** [comment]
I will do this tonight and post the results (what I have is usable at the moment). In the meantime -
running Ubuntu 14.04

pip freeze

PAM==0.4.2
Pillow==2.3.0
Theano==0.7.0
Twisted-Core==13.2.0
Twisted-Web==13.2.0
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
dirspec==13.10
dnspython==1.11.1
duplicity==0.6.23
futures==3.0.2
html5lib==0.999
httplib2==0.8
ipython==1.2.1
lockfile==0.8
lxml==3.3.3
matplotlib==1.3.1
nose==1.3.1
numpy==1.8.2
oauthlib==0.6.1
oneconf==0.3.7
pexpect==3.1
piston-mini-client==0.7.5
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pydot==1.0.2
pydub==0.11.0
pygobject==3.12.0
pyparsing==1.5.7
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu1
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
pytz==2012c
pyxdg==0.25
reportlab==3.0
requests==2.2.1
scikits.audiolab==0.11.0
scipy==0.13.3
sessioninstaller==0.0.0
simplegeneric==0.8.1
six==1.5.2
software-center-aptd-plugins==0.0.0
ssh-import-id==3.21
system-service==0.1.6
unity-lens-photos==1.0
urllib3==1.7.1
wsgiref==0.1.2
xdiagnose==3.6.3build2
zope.interface==4.0.5

**Comment by dxyzab** [comment]
sudo pip uninstall theano
sudo pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git 

I get the same error. Dev seems much slower than 0.7.0

    gW = TT.grad(final_cost, wrt=grad_params)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 530, in grad
    handle_disconnected(elem)
  File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 517, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: HostFromGpu.0

**Comment by nouiz** [comment]
The dev version should be faster, but the first time, it can recompile some
c code. So the fist call to theano.function() can be slower.

Or do you mean the grad is slower? That would surprise me.

Do you use OpFromGraph? Otherwise I don't understand how this can happen
execpt if you do strange things in your code. But I suppose this isn't the
case.

Can you give us a way to reproduce this?

**Comment by dxyzab** [comment]
I don't use OpFromGraph. 
Unfortunately I can't share the code. If I get a minimal version which exhibits the
problem I will certainly post here. 

The cpu version is fine, which I am going to use for the moment.
