### ISSUE TITLE
Unnecessary warning message when using compute_test_value

### ISSUE THREAD

**Issue by udibr** [Theano/Theano#3010]
The code at
https://github.com/Theano/Theano/blob/master/theano/tensor/blas.py#L179
is missing a dummy value for test_value, e.g.:
    x.tag.test_value = 0
as a result I get a warning message each time I use compute_test_value:

UserWarning: Warning, Cannot compute test value: input 0 (<TensorType(float32, matrix)>) of Op Dot22(<TensorType(float32, matrix)>, <TensorType(float32, matrix)>) missing default value
  theano.function([x], theano.tensor.blas._dot22(x,x),

**Comment by nouiz** [comment]
Thanks, I have a pr in gh-3011 with a fix for this.
