### ISSUE TITLE
Buildbot script should rm -rf the compiledir it uses first.

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3012]

**Comment by lamblin** [comment]
I think the reason it currently does not is that it lets us know if there is currently a problem with dealing with older cached files. It can help detect when version numbers have not been updated when they should.
Also, it speeds up the nightly build process by a sizeable amount.
What do you think is the problem with keeping the cache?

**Comment by dwf** [comment]
Well, for one thing, if you are switching between Python 2 and Python 3
you've got problems. (Fixable problems, but still.)

Another is that it's just irritating trying to debug what's new and what
isn't, and not being sure whether the bugs are present in the trunk. I'm
seeing several failures in my misc_py3k branch that were also present when
I ran it with the trunk checked out, but since the cache directory wasn't
cleared I can't be certain that this wasn't just some bullshit caching
mistake, and I now irritatingly have to run it again.

**Comment by lamblin** [comment]
Then, maybe the version of Python should be part of the compile key, so that these problems do not occur.

**Comment by nouiz** [comment]
This is already the case.

You can compare again the errors in the daily buildbot. There is some tests
failure related to grad. I think you can ignore them.

**Comment by dwf** [comment]
I get a test failure related to malloc on GPU.

On Wed, Jun 10, 2015 at 11:58 AM, Frédéric Bastien <notifications@github.com

**Comment by nouiz** [comment]
the test_memory() test? Ignore it. It seem not working right for some times
and I don't understand why yet. Not enough time to investigate for now.

Otherwise, give the error information you have.

**Comment by nouiz** [comment]
@dwf, do you know what we should do? We need the daily buildbot to keep the
old behavior and as the python version is in the compiledir by default, I
don't understand the problems you could have. Do you understand the problem
you had?

**Comment by dwf** [comment]
I suspect it's because the script is setting compiledir in the flags rather
than base_compiledir. The whole compiledir path appears to be hardcoded to
something.

**Comment by nouiz** [comment]
good finding, do you want to fix it?

**Comment by nouiz** [comment]
I just checked the code and this happen only when we pass the --buildbot
parameter. Did you do that? That parameter was done to be used only by the
daily buildot. If you used it, why did you do so? Should we document it
better?

**Comment by dwf** [comment]
I wanted to run exactly what the buildbot would, so I did that. The
documentation is pretty much non-existent, so I just assumed...

**Comment by nouiz** [comment]
I'll close this as I merged your PR gh-3019 that fix the problem you had between python2 and 3.
