### ISSUE TITLE
CUDA unavailable after update

### ISSUE THREAD

**Issue by Creative-Punch** [Theano/Theano#3016]
Hi all,

I just updated Theano to the latest version. Now I keep getting this output:

*ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: dynamic module does not define init function (initcuda_ndarray)
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavilable)*

It used to work however now I can't even use CUDA anymore even if I revert to an older version of theano.

**Comment by Creative-Punch** [comment]
Also note, theano-cache purge/clear does not fix the problem

**Comment by nouiz** [comment]
When did you update Theano?

can you purge the compiledir, Can you remove Theano completly and reinstall
from scratch?

if that don't fix it, maybe a reboot could help. From what you wrote, it
could be a problem with the computer. It happen that GPU end up in bad
state and need a reboot.

Fred

**Comment by Creative-Punch** [comment]
I have done all those things and also rebooted just now.

The issue still persists.

I updated Theano today.

**Comment by lamblin** [comment]
Could you try with the following commit? https://github.com/Theano/Theano/commit/f0d1e63ec12f50207c09bc5a480bb72bd2bb6a4b
I'm suspecting #2765 to be the problem, as it seems like the Python module init function is not properly exported in cuda_ndarray.cu/h anymore.

**Comment by nouiz** [comment]
What is your OS?

**Comment by Creative-Punch** [comment]
Windows 7

If I remove theano and install the pip version it will use my GPU again after removing everything in the cache, sadly It lacks some features which I need that the latest version does have.

To compare I also ran theano-test on the pip version of theano and the latest version from github after a clean theano install. Result is the same, it will run the pip version, but throws the very same error using the latest version of theano

**Comment by Creative-Punch** [comment]
@lamblin The commit you mentioned gives me the same error

**Comment by nouiz** [comment]
Can you try the commit @lamblin gave? It should be the most recent before
the PR that we suspect. It would give you very 5 days old Theano version
that should work. Can you confirm it work? Don't forget to purge the cache.

**Comment by lamblin** [comment]
Well, if it does not work, I have no idea what could have triggered the problem.
The only way I see to identify it is if you can clone the github repository and use `git bisect` between 0.7 and the latest version, to identify wich is the first failing commit.

**Comment by Creative-Punch** [comment]
@lamblin @nouiz Nevermind, the commit you give me does indeed work so I guess you are right about what triggered this.

**Comment by lamblin** [comment]
This should be fixed in #3047.
@Creative-Punch can you confirm?
