### ISSUE TITLE
Warn Theano unknow Theano flags

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3021]
Currently, we just ignore them. But we can't easily just warn about them as other lib like pylearn2 define there own flags that get know about later. Doing it at the end of the process would help, but if the user not always use the other lib, we still have the warning and having it at the end isn't great.

block solved this by (https://github.com/mila-udem/blocks/pull/712) by using a diff and if the key is missing, but close to known ones, print the warning at start up. I think this would also be good for Theano.

**Comment by nouiz** [comment]
IRL discussion with @lamblin We think that it is better to move most if not all config declaration in the file configdefault.py. This will make sure that when the user define a config that we don't know about, we don't raise false warning (as it could be defined later).

**Comment by abergeron** [comment]
Fixed by #4042
