### ISSUE TITLE
Error  taking gradient of sparse element-wise multiplication (theano.sparse.basic.mul)

### ISSUE THREAD

**Issue by OttoFabius** [Theano/Theano#3022]
I am using the element wise multiplication of a sparse matrix and a regular matrix. The following function is expected to return the gradient, but instead it returns the following error:

```
"Variable type field must be a TensorType.", x, x.type)
theano.tensor.var.AsTensorError: ('Variable type field must be a TensorType.', SparseVariable{csc,float64}, Sparse[float64, csc])
```
For this, the following code was used:

```
import theano
import theano.tensor as T
import theano.sparse


x = theano.sparse.csc_matrix(name='x', dtype=theano.config.floatX)
y = T.matrix('y')

output = T.sum(theano.sparse.basic.mul(x,y))

grads = theano.grad(output, x)

f = theano.function([x,y], grads)
```

**Comment by lamblin** [comment]
Thanks for the report. You seem to be hitting the same problem as in #2782.
Support of sparse operations is not a high priority for the core developers at the moment, but we could provide some help if you would like to contribute.

**Comment by OttoFabius** [comment]
The problem turned out to be that the sparse multiplication creates a sparse matrix. To sum over this matrix, you have to use theano.sparse.sp_sum and not theano.sum.
