### ISSUE TITLE
Error in strides of max-pooling

### ISSUE THREAD

**Issue by duguyue100** [Theano/Theano#3023]
I'm using Theano's max-pooling for a while. But today is my first time I tried with it's `st` option because one of my friend told me that he can't compile my code with `st` option.

So I tried to add in one of my pooling layer. And then I can't build my model anymore, there is no error and no ending, here is how I use the max-pooling operation:

``` python
pool_0=MaxPooling(pool_size=(2,2), step=(3,3));
```
it's in this [file](https://github.com/duguyue100/telaugesa/blob/master/scripts/cifar10_convnet_test.py#L50). and my max-pooling layer is defined in [here](https://github.com/duguyue100/telaugesa/blob/master/telaugesa/convnet.py#L168).

Maybe you can help me on this.

**Comment by benanne** [comment]
I don't know if this is related to it not working at all, but a pooling layer with a stride larger than the pool size does not really make sense. You are basically ignoring part of the input then. Maybe that simply isn't supported and they forgot to throw an exception for it. Either way, it's rarely a good idea.

**Comment by nouiz** [comment]
I checked Theano code and it don't have tests for that and I didn't find
rapidly indication that we support it.

can you test with step(2,2) and confirm that this case work? If so, it
would confirm Sander hypothesis.

Do you think we should support it or raising an error would be enough?

Hu, why did you tried that special case?

**Comment by duguyue100** [comment]
Hi, thanks for your reply.

Actually at first I tried with step=(1,1), then I got stuck, i thought maybe the result feature map is too big, so I use (3,3). so I can deal with a smaller case.

Yeah, I will try with (2,2) later, now I don't have the machine with me. I will definitely get back to you all.

**Comment by lamblin** [comment]
The CPU implementation should support that, if there is a problem then this is an actual bug, and it means we are missing tests.
It is possible, however, that such cases are not supported by cudnn, for instance, and in that case we should make sure these cases are not optimized to use cudnn.

**Comment by lamblin** [comment]
@duguyue100 Could you clarify which device and library you are using?

**Comment by duguyue100** [comment]
I'm using a Nvidia K40 with CUDA 7 and cuDNN v2.
The Theano I have is the bleeding edge upgrade from Anaconda.

**Comment by lamblin** [comment]
Thanks! Can you check if it works if you use the CPU only, or if you exclude cdnn optimization ("optimizer_excluding=cudnn")?

**Comment by duguyue100** [comment]
sure, I will do it tomorrow (2am in my time zone) and will feedback to you guys

**Comment by lamblin** [comment]
Thanks!

**Comment by duguyue100** [comment]
Hi,

Here is my experiment results

+ if I set `step=(2,2)` as my `pool_size`, the code is working.

+ I run my test with `step=(3,3)` without cuDNN by 

   ```
   THEANO_FLAGS=optimizer_excluding=cudnn python cifar10_convnet_test.py
   ```

   And it's working correctly, so I guess this is caused by cuDNN.


@nouiz , if it is an error, I think raise an error or remove this option is enough (but still we need overlapping pooling sometimes right?)

**Comment by duguyue100** [comment]
And guys, I think the same issue happened to the `mode` option in the bleeding edge build.

All three additional "sum", "average_inc_pad" and "average_dec_pad" is not working with cuDNN's support in default.

**Comment by nouiz** [comment]
I tried to make tests in Theano to reproduce the problem with step =3 and pool_size=2 but I'm not able too do so.

Can you give us the error you have? cudnn seem to work well for the tests I added.

**Comment by duguyue100** [comment]
Hi, this is the weird part, when I had the error, it doesn't give any error on my machine unless I close it. like I described above, the machine is hanging.

But one of my friend got this error when he is using similar configuration:
```
TypeError: max_pool_2d() got an unexpected keyword argument 'st'
```

**Comment by nouiz** [comment]
That TypeError just mean is Theano is too old. He need to update to the
development version of Theano.

I don't think the software is the cause of the hang. I would more guess
that this is an hardware problem (bad PSU, PSU not strong enough, ...)

**Comment by duguyue100** [comment]
I'm running the code on a Nvidia K40. I wouldn't be so suspicious on hardware problem (and without cuDNN all functions are working fine).
Just in case I'm wrong, I will test it on AWS instance so I can confirm to you.

**Comment by duguyue100** [comment]
alright, turns out the function works with cuDNN again without any problem on my machine now. I swear that it didn't last week.. anyway, I guess it's just a false alarm. thanks for you guys help.

**Comment by nouiz** [comment]
That happen. If you end up finding the cause, keep us updated.
Understanding this could help in the futur.

**Comment by Rblivingstone** [comment]
I've been getting this error recently while trying to run some code on AWS. Anybody have a clue as to root cause yet?

**Comment by nouiz** [comment]
It seem nobody else that saw this message have your problem. Do you still
have it @Ryan

**Comment by tingtinglu** [comment]
I also come across this problem. How can this problem can be solved? Thank so much !

**Comment by duguyue100** [comment]
Like previous posts, have you tried to update your Theano to bleeding edge version? @tingtinglu
