### ISSUE TITLE
Implement CpuCorrMM

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3026]
We should have an implementation of CPU convolution (including gradient with subsampling) based on GEMM, like GpuCorrMM on GPU.
That way, when the abstract convolution op is finished, we will have a fast implementation of all cases on CPU.

**Comment by JesseLivezey** [comment]
Is anyone assigned to work on this? I've been wanting a faster CPU conv op and had thought about attempting this myself.

It would take me a while, since I'm pretty terrible at C, but I might be more useful than no one!

**Comment by JesseLivezey** [comment]
And would the best plan be to start from the Caffe code like the GPU op?

**Comment by nouiz** [comment]
The best start would be to start from GpuCorrMM and convert them to CPU op.
staring from caffe/torch would be more complicated as you need to learn
them and learn the corresponding to Theano.

For the GPU, you need to swap the call to cublas to normal blas (similar
interface) and convert 1 relatively simple GPU function to an equivalent
CPU version.

To my knowledge, nobody started that yet.

**Comment by JesseLivezey** [comment]
Great. I'll start that in the next few days.

**Comment by nouiz** [comment]
Thanks
