### ISSUE TITLE
theano.tensor.constant([1]).reshape(()) fails

### ISSUE THREAD

**Issue by jsalvatier** [Theano/Theano#3031]
theano.tensor.constant([1]).reshape(()) fails with:

```
/Library/Python/2.7/site-packages/theano/tensor/basic.pyc in make_node(self, x, shp)
   3831         shp = as_tensor_variable(shp, ndim=1)
   3832         if not shp.dtype.startswith('int'):
-> 3833             raise TypeError("Shape must be integers", shp, shp.dtype)
   3834         assert shp.ndim == 1
   3835         if isinstance(shp, TensorConstant):

TypeError: ('Shape must be integers', TensorConstant{[]}, 'float64')
```

But np.array([1]).reshape(()) succeeds, so tensor.reshape should too probably.

**Comment by lamblin** [comment]
Right, an empty shape should work.
I think we could either a special case for an empty vector here, or maybe add an option to `as_tensor_variable` to specify a default `dtype` if the original is empty and does not have one.
