### ISSUE TITLE
move NanGuardMode to Theano

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3034]
@hantek This one's yours. Followup to lisa-lab/pylearn2#1172

**Comment by hantek** [comment]
NanGuardMode is already in Theano while doing this ticket: https://github.com/Theano/Theano/pull/2849,  I will push a PR in pylearn2 removing related parts instead.

**Comment by dwf** [comment]
Fixed by lisa-lab/pylearn2#1543.
