### ISSUE TITLE
tensor.Split.perform needs C code

### ISSUE THREAD

**Issue by jsalvatier** [Theano/Theano#3039]
PyMC3 is using tensor.Split a lot and for many problems, its about 50% of the theano time. Would love to move this to C.

**Comment by twiecki** [comment]
@nouiz could you give a bit of guidance of what would need to be done here?

**Comment by nouiz** [comment]
Mostly, implement the c_code() method to the class Split in the file
theano/tensor/basic.py

Here is some documentation about this:
http://deeplearning.net/software/theano/extending/extending_theano_c.html

If you have questions, don't hesitate.

**Comment by twiecki** [comment]
Can you let me know if this is going into the right direction?
```python
    def c_code(self, node, name, inputs, outputs, sub):
        x, shp = inputs
        l = len(tensors)
        out, = outputs
        fail = sub['fail']
        len_splits = self.len_splits
        splits = self.splits
        code = """
        int lower_idx = 0;
        int upper_idx = 0;
        for(int i=0; i < %(len_splits)s; i++) {
            upper_idx = lower_idx + %(splits)s[i];
            %(out)[i][0] = %(x)s[lower_idx:upper_idx];
            lower_idx = upper_idx;
        }
        """ % locals()
        return code
```

Seems like I need to do more input checking and this probably does not support broadcasting yet. Especially broadcasting I'm not sure how to tackle.

**Comment by lamblin** [comment]
The main problem is that you cannot simply index into numpy arrays using `[i]` to get an element or `[i:j]` to get a new array in C.
You would really have to use NumPy's C API to create new arrays, access elements, cast pointers into the right type, manage refcounts, etc.
You can have a look at the C code of the `Subtensor` class to have an idea how extracting one subtensor can be done.

**Comment by twiecki** [comment]
I see. Can I use numpy's c iteration code (https://docs.scipy.org/doc/numpy/reference/c-api.iterator.html)?

**Comment by twiecki** [comment]
Also, is it not possible to write the c-code using cython? That would make things much simpler.

**Comment by lamblin** [comment]
It is possible to use the whole C API, yes. Although in that case, no iteration through the data should be required: the memory pointed to would be the same, only the shapes / strides would have to change.

It is also possible to write Cython code, but in that case I think the overhead of going back to the Python interface is what dominates, so I don't think it would buy us much.

Another option to solve the original problem would be to replace the `Split` node by a series of `Subtensor` nodes, which already have C code. @nouiz, @jsalvatier, what do you think about that?

**Comment by twiecki** [comment]
Good idea @lamblin.

@jsalvatier We don't explicitly call `Split` in pymc3, do you know which theano call triggers it?

**Comment by twiecki** [comment]
@lamblin Regardin `c_code`: I saw that it was also possible to create `slice`'s directly in C. Would those speed things up?

**Comment by jsalvatier** [comment]
@twiecki I think its probably here: https://github.com/pymc-devs/pymc3/blob/master/pymc3/theanof.py#L167 as a result of `inarray[slc]`

But not super sure. I would try to replicate the slowness to see exactly where. You can do that by passing `profile=True` to NUTS and then looking at `step.leapfrog1_dE.profile` (https://github.com/pymc-devs/pymc3/blob/master/pymc3/step_methods/nuts.py#L117).

**Comment by jsalvatier** [comment]
Oh, maybe I was doing IPython profiling actually: https://github.com/pymc-devs/pymc3/pull/757

using `%timeit` and `%%prun` and

```
%load_ext line_profiler
%lprun -f step2.astep for i in range(1000): step.step(start)
```

**Comment by lamblin** [comment]
My guess is that the `Split` you see is introduced as the gradient of `Join`.
Another option would be to rewrite `Join.grad` as a series of `Subtensor`, but then the second derivative would be less nice (a collection of `IncSubtensor` rather than a single `Join` again).

**Comment by lamblin** [comment]
And it is likely that the slowdown is worse on GPU, since going back to Python may force additional synchronizations.

**Comment by lamblin** [comment]
Just to keep you updated, @notoraptor will work on this.

**Comment by twiecki** [comment]
Very cool, look forward to testing it out.

**Comment by twiecki** [comment]
PR: https://github.com/Theano/Theano/pull/5499

**Comment by nouiz** [comment]
done
