### ISSUE TITLE
Clearer error messages for a common PyMC3 error

### ISSUE THREAD

**Issue by aflaxman** [Theano/Theano#3040]
There is a common error for people learning about theano through PyMC3, as exemplified in https://github.com/pymc-devs/pymc3/issues/754 ; in PyMC2, there was a common pattern where model parameters would be magically transformed into numpy arrays, and the user could manipulate them with familiar numpy functions, e.g. `np.exp(p)`.  Since PyMC3 is theano-based, translating is often as simple as switching from `np.exp` to `tt.exp`.  But it would be so helpful if there was an error message that said this. I think that the minimal example of this is the following:

```
import theano.tensor as tt

x = tt.dmatrix('x')
y = np.exp(x)
```

which raises the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-142-00dd09faf982> in <module>()
      3 x = tt.dmatrix('x')
----> 4 y = np.exp(x)

AttributeError: 'TensorVariable' object has no attribute 'exp'
```

Would it be possible to give a hint here, that perhaps `theano.tensor.exp` is what the user intended?

**Comment by nouiz** [comment]
This particular case can be fixed by adding the exp function in the right
class (TensorVariable).

But this is related to how numpy execute its function on unknow inputs.
This changed in recent version of numpy and will continue to change to make
this easier. So this isn't only related to Theano.

The simplest is that each time we see such error reported, we check if
adding a new method would solve this. Otherwise, someone (I don't have the
time) could search in the np namespace the one that don't work and we could
work on that.

Can you help on that? If you can make a list of the method that don't work
and the error, I could test and add the missing method if that fix it.

**Comment by aflaxman** [comment]
I think I know how to search the numpy namespace, so I'll try and report back here.  Can you point me to the numpy code that executes a function on unknown inputs?  I took a look in the code last night, but I didn't find it in the time I had.  Thanks!

**Comment by nouiz** [comment]
That functionality in numpy is very complicated. I fixed one case in that
past, when you where doing a_numpy_ndarray + a_theano_tensor to call
a_theano_tensor + a_numpy_ndarray as Theano know how to handle that.

But it was hard to find and do. It took me 2 days to get a first version
and probably 2 other days to finish and get the fix merged in Theano.

There is discussion on that in numpy mailing list. I don't have time to
follow this. If you want to get in that, I would suggest you to find those
discussion first.

But in all case, this could need some change in Theano. numpy need to find
the corresponding code to call on the theano variable. So it could mean
that we just need to add some method to tensor variable and this could work
in many cases like for the exp (I tested a quick hack and this work).

**Comment by aflaxman** [comment]
Here are the ufuncs in my `np` namespace that don't work with a theano variable: `arccos, arccosh, arcsin, arcsinh, arctan, arctanh, ceil, cos, cosh, deg2rad, degrees, exp, exp2, expm1, fabs, floor, log, log10, log1p, log2, rad2deg, radians, rint, sin, sinh, sqrt, tan, tanh, trunc`.

Here is a little notebook for generating them: http://nbviewer.ipython.org/gist/aflaxman/f056e2a3979867743078

**Comment by nouiz** [comment]
Thanks. We will be pretty busy for the next few weeks. I don't know when we
can do this.

But I made an example how to fix it for exp:

https://github.com/Theano/Theano/pull/3112

Do you want to do the same for the others? It is easy to do.

**Comment by aflaxman** [comment]
I think I can do this, PR to come.

**Comment by nouiz** [comment]
I open it again as the merged PR only fixed it for exp, not all the others ones listed here.

**Comment by springcoil** [comment]
Is this still open?

**Comment by nouiz** [comment]
To my knowledge, it is done. So I'll close this issue.

thanks.
