### ISSUE TITLE
Recent commit breaks cuda_convnet on Ubuntu 15.04, CUDA 7.0

### ISSUE THREAD

**Issue by hjweide** [Theano/Theano#3041]
I recently installed Theano, pylearn2, and Lasagne on a machine running Ubuntu 15.04 with CUDA 7.0 and an NVIDIA Quadro K4200.  When I tried to run the mnist_conv_cc.py example from Lasagne (which uses cuda-convnet), I ran into an undefined symbol error: undefined symbol: _Z16convLocalMaxUndoR8NVMatrixS0_S0_S0_iiiiff.  The full trace can be viewed on [pylearn2-users](https://groups.google.com/forum/#!topic/pylearn-users/-nx87q9EkTU), where I made a post about it.

Using the advice from the two people who replied to me, I was able to get it working by reverting to an old commit of Theano.  At the time, https://github.com/Theano/Theano/commit/f0d1e63ec12f50207c09bc5a480bb72bd2bb6a4b was suggested to me, but since then I have discovered that the most recent commit that works is https://github.com/Theano/Theano/commit/3556d9ec5e02b73fea76d240f00f31e64ddbbb4e.

I suspect that this must have something to do with either Ubuntu 15.04 or CUDA 7.0, because I have no issues with the most recent version of Theano on a computer running Ubuntu 14.04 and CUDA 6.5.

If I run  ```nm cuda_convnet.so | grep -i "_Z16convLocalMaxUndoR8NVMatrixS0_S0_S0_iiiiff" ```
then the output is ```0000000000062a70 T _Z16convLocalMaxUndoR8NVMatrixS0_S0_S0_iiiiff```, so I'm not sure why the symbol is shown as undefined.

**Comment by nouiz** [comment]
We use cuda 7 here, so that isn't the problem by itself.

Did you delete theano cache with the version that do not work? Having an
old compiledir could cause problem with newer Theano version. Normally, we
should handle that correctly, but it happen that there is problems.

@abergeron, I let you check that.

On Wed, Jun 17, 2015 at 11:34 AM, Hendrik Weideman <notifications@github.com

**Comment by hjweide** [comment]
Yes, I ran ./theano-cache purge every time before trying a different commit of Theano.

**Comment by nouiz** [comment]
until it get fixed, you can use this commit of Theano:

f0d1e63ec12f5020

it should work.

On Wed, Jun 17, 2015 at 11:46 AM, Hendrik Weideman <notifications@github.com

**Comment by nouiz** [comment]
Be sure to have a recent version of pylearn2. Older version won't work with newer Theano.

**Comment by lamblin** [comment]
I think this should fix the problem: https://github.com/lisa-lab/pylearn2/pull/1540

**Comment by hjweide** [comment]
Thanks @nouiz and @lamblin!  After checking out https://github.com/lisa-lab/pylearn2/pull/1540, I can use the latest version of Theano :)
