### ISSUE TITLE
3D convolution in Theano

### ISSUE THREAD

**Issue by jiangwenchao** [Theano/Theano#3059]
I want to implement 3D CNN with the Theano, but I am not sure whether the convolution is 3D convolution or multi-channel 2D convolution? More specially, If I have an image with MNK where M is the number of row, N is the number of column and K is number of channel. The filter is with M'N'K'. The first way to do convolution is just 3D convolution. The second way is process each channel seperately, which is filtering the first channel with the filter in the first channel, and so on. Which way does the Theano choose? Thank you very much.

Does you guys know any other deep learning tookbox supporting 3D convolution? Thank you very much.

**Comment by nouiz** [comment]
There is the lenet example in the Deep Learning Tutorial that talk about
this.

2d convolution will take 4d inputs. We add a dimensions for the mini-batch
on the images and a dimensions to allow for multiple kernel.

3d convolution is more for video. It take 5d inputs. So you can have
multiple channel in addition to the time dimensions.

A few web page that could help you understand this:

http://deeplearning.net/tutorial/lenet.html
http://deeplearning.net/software/theano/library/tensor/nnet/conv.html

Fred

**Comment by lamblin** [comment]
Also, in the future, please use the `theano-dev` mailing list instead of tickets for support requests. Thanks.
