### ISSUE TITLE
Parallel Optimization

### ISSUE THREAD

**Issue by t13m** [Theano/Theano#3067]
If a local optimizer can be applied to the fgraph's different parts in parallel, it will be more efficient. (for example the constant_folding_optimizer).

**Comment by nouiz** [comment]
This would be very hard to implement. First there is the python GIL.
second, we don't know how far each local optimization look in the graph. We
could have it tell it. This is needed to don't have multiple change
interact between them.

**Comment by nouiz** [comment]
I don't see that in the short or medium term, so I'll close this issue. But if someone have good ideas of how to do that, tell them.
