### ISSUE TITLE
Update NaN tutorial with a section on NanGuardMode

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3086]
Follow-up to #2770.
Replaces https://github.com/lisa-lab/pylearn2/issues/1171, now that NanGuardMode has been moved to Theano in #3034.

**Comment by hantek** [comment]
Hi, I created a PR to add the documentations.

**Comment by memimo** [comment]
LGTM, @lamblin could you skim through and have final look too please.

**Comment by lamblin** [comment]
Fixed by #3101.
