### ISSUE TITLE
Weird error when exiting python/ipython after using GPU

### ISSUE THREAD

**Issue by escopeta** [Theano/Theano#3088]
Hi I am getting the following error:

Exception AttributeError: AttributeError("'NoneType' object has no attribute 'remove'",) in <bound method Unlocker.__del__ of <theano.gof.compilelock.Unlocker object at 0x7f6a05de4f90>> ignored

This happens after I execute the following commands:

import theano.sandbox.cuda
theano.sandbox.cuda.use('gpu0')

and then exit ipython or python. I have to mention I am able to successfully secure GPU for usage (I get Using gpu device 0: Tesla K40c) and use the GPU fine during my computations, but I am puzzled about this Exception message and would like to fix it on my side. The python I am using comes in anaconda (Anaconda-2.2.0-Linux-x86_64) and I installed theano following the "Bleeding-edge install instructions" from deeplearning.net. I would really appreciate any help on this matter. Thanks.

**Comment by nouiz** [comment]
Your error message seem cut. What is between "in" and "ignored"? I have
this message here:

Exception TypeError: "'NoneType' object is not callable" in <bound method
Popen.__del__ of <subprocess.Popen object at 0x1baefd0>> ignored

Your isn't the same, so this could be comming from a different place.

**Comment by nouiz** [comment]
I did a PR that fix my error. I get it with the same code as your example, but it isn't the same error. https://github.com/Theano/Theano/pull/3110

Can you try it and tell me if it fix it for you?

**Comment by escopeta** [comment]
Hi @nouiz 

Sorry for the late response, I just upgraded to the latest commit and the error disappeared. Thank you very much!!!!
