### ISSUE TITLE
Quick python op with gradient is difficult

### ISSUE THREAD

**Issue by jsalvatier** [Theano/Theano#3094]
For pymc3 it is important to easily specify gradients for custom ops. Currently this is a little complex. 

`as_op` is very nice but can't specify gradient. Inheriting from Op is good but requires specifying `make_node` which novice users  won't understand.

Would be lovely to be able to specify `itypes` and `otypes` when inheriting from Op. 

More here:
https://groups.google.com/forum/#!searchin/theano-users/simplest$20op$20with$20gradient$20function/theano-users/ByysGhDmep8/NOFR0uE6UL4J

**Comment by nouiz** [comment]
Just to tell that I think this is relatively easy to do. It do not need any
deep knoledge of Theano, but knowing python.

No time to work shorlty on this, so if someone is interrested, don,t
hesitate to see the url of the description, it tell how to implement it.

**Comment by Sentient07** [comment]
@nouiz , is someone working on this issue ? if not, can I take this ?

**Comment by nouiz** [comment]
Nobody is working on this. You can take it. But be warned, it is more advanced then your previous issue you helped on.

Mostly, the as_op method use a class FromFunctionOp. In that case, there is a make_node implementation that use the self.itypes and self.otypes. You should move that make_node implementation in the Op class. If the class do not have itypes or otypes defined, the make_node should raise NotImplementedError().

This would need test inside theano/got/tests/test_op.py. You can base your tests on the tests for as_op().

If you didn't read that tutorial page, read it. It should give you the back-ground information on what is needed:

http://www.deeplearning.net/software/theano/tutorial/extending_theano.html

Mostly, we want to make it easier to make some type of op as as_op is doing, but with the full capacity of an Op.

thanks

**Comment by Sentient07** [comment]
@nouiz , Will go through them and get back if i have any question. Thanks! :+1:

**Comment by Sentient07** [comment]
@nouiz , sorry for the delayed reply. I just went through the tutorials and the file. From what i can understand, the make_node method is a mandatory method while using theano.Op, which checks if the input variables are compatible with the current op. But from what i can see, the make_node implementation here just raises an error if it's not overridden. Where should I look for make_node implementation that uses self.itypes and self.otypes ?

**Comment by Sentient07** [comment]
@nouiz Ignore my previous comment. I should be checking this method (https://github.com/Theano/Theano/blob/master/theano/compile/ops.py ) , and raising the error if itypes or otypes is not defined, right ?

**Comment by nouiz** [comment]
Yes. Move from the ops.py file the make node fct to the Op class. And raise
the the attributes aren't defined.
Le 4 déc. 2015 17:07, "Ramana Subramanyam" <notifications@github.com> a
écrit :

**Comment by Sentient07** [comment]
@nouiz I hope this is good ?
