### ISSUE TITLE
Add the doc generation in travis

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3103]
- [x] Add in the file .travis.yml a new test run that would generate Theano doc with the script doc/scripts/docgen.py. Configure it such that if there is an error in the doc, it make travis fail. (so mostly the process must return an error.)
- [x] If there is current error in the doc, fix them.
- [x] Make it also run doctest (docgen.py --test)
- [ ] Make travis fail when there is an error in doc generation
- [ ] Make travis fail when there is an error in doc test

**Comment by hantek** [comment]
doc/scripts/docgen.py --nopdf

**Comment by abergeron** [comment]
There is also `doc/scripts/docgen.py --test` that will run the code blocks embedded inside the docs.  This will make sure that the examples stay unbroken.

**Comment by nouiz** [comment]
The only think left is to make travis fail when the doc test or doc generation.

**Comment by nouiz** [comment]
done by gh-4030
