### ISSUE TITLE
[crash, bug?]GpuAdvancedIncSubtensor1_dev20 do not check the index and don't support negative index

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3111]
I'm not sure it should support negative index. But it probably need to support it.

But it do not check that the output is out of bound or not.

So bad user index can cause crash (try to read memory not allocated) or could return some unknow value instead of returning an error.

**Comment by nouiz** [comment]
The only thing left is the out of bound detection on the new back-end.

**Comment by abergeron** [comment]
new backend is done.
