### ISSUE TITLE
modprobe: ERROR: could not insert 'nvidia_346': No such device

### ISSUE THREAD

**Issue by floydwch** [Theano/Theano#3113]
Hi,

I'm trying to use theano with openmp, so I set `device = cpu`, but it doesn't work normally, prompt this message when I execute `OMP_NUM_THREADS=2 python theano/misc/elemwise_openmp_speedup.py`.

In gpu mode, it's all ok, but seems doesn't work with cpus when I change the device to cpu and migrate from aws ec2 gpu instance to cpu instance.

**Comment by floydsoft** [comment]
This issue is fixed after `sudo apt-get remove --purge nvidia-*`.
