### ISSUE TITLE
CUDA library directory isn't what Theano expects, at least when CUDA is installed using network installer.

### ISSUE THREAD

**Issue by SuperElectric** [Theano/Theano#3116]
I installed cuda 7.0 using NVidia's "network install" .deb file for Ubuntu 14.04 (LTS). This installs CUDA in /usr/local/cuda as usual. However, in that directory, there is only a 'lib64' softlink to the lib directory, whereas Theano expects it to be called 'lib'.

I've done the obvious workaround, where I create a 'lib' softlink that points to the same dir that 'lib64' does. All is good now.

Could Theano be changed to look for both 'lib' and 'lib64' in the CUDA dir?

**Comment by lamblin** [comment]
That would seem reasonable, yes (at least if the current Python is 64-bit, not 32-bit).

**Comment by lamblin** [comment]
With the new back-end, I think `cuda_root` is not really used any more, except when looking for `cudnn`, in which case it tries `lib64`.
