### ISSUE TITLE
Could not initialize pygpu

### ISSUE THREAD

**Issue by saienthan** [Theano/Theano#3126]
Hey, import theano does fails with the gpuarray back-end.  An assertion error is thrown on line 81 in theano/gof/optdb.py:
``
assert len(obj) == 1
``
len(obj) in this case turns out to be 6.

A work around is to remove the call to add_tags() from `theano/sandbox/gpuarray/__init__.py`(line 59):
``
optdb.add_tags('gpuarray', 'fast_run', 'fast_compile')
``
Since the purpose of these flags is not known, I don't know if this solution is advised.

This is my theanorc.
```
[global]
device = cuda0
```

**Comment by lamblin** [comment]
These tags will enable the optimizations that replace CPU Ops by GPU Ops using the new backend.
Without them, you would have to explicitly include those optimization by passing `optimizer_including=gpuarray` in the theano flags, for instance.
I don't know why 6 objects would be in there. @abergeron ?

**Comment by nouiz** [comment]
This is fixed by: https://github.com/Theano/Theano/pull/3199

thanks for the report.

**Comment by nouiz** [comment]
This should be fixed in Theano. Just update. If that don't fix it, tell us.
Fred
Le 16 juil. 2015 18:54, "Pascal Lamblin" <notifications@github.com> a
écrit :
