### ISSUE TITLE
How to do BFGS or other quasi-newton method in theano?

### ISSUE THREAD

**Issue by maplewizard** [Theano/Theano#3131]
I want to do some optimization of a function where several matrix as input should be optimized, there are also some other inputs. The function can be given as follow:

     F(x1, x2, x3, a1, a2, a3)

x1, x2, x3 is the matrix I want to optimize and a1, a2, a3 are some other parameters.
I didn't find any optimization function that theano provide. So I just use scipy.optimization.minimize. But the minimize function can only accept one vector as input.
I want to know whether there are some convenient ways to do some optimization in theano?

**Comment by lamblin** [comment]
Please use the mailing list (theano-users@googlegroups.com) for such requests (you can also try stackoverflow with the "theano" tag).
We try to keep GitHub tickets for bug reports and feature requests.

As for your question, I don't know much about BFGS, but I think that quasi-Newton methods can be implemented in Theano using the gradient and R-Op mechanism to compute the Gauss-Newton approximation of the Hessian.
The alternative is to use scipy's minimization routines, in that case you should keep all the parameters to optimize in one shared vector, and define the variables you will use in your model from that vector.
For instance:
```
x = ...
x1 = x[0:x1_size].reshape(...)
x2 = x[x1_size:(x1_size + x2_size)].reshape(...)
```
