### ISSUE TITLE
Fix problem with explicit cast to float16 in GpuElemwise (gpuarray)

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#3138]
Having a Cast(float16) in the elemwise graph can lead to having a ga_half datatype in the resulting which is almost never work correctly.

One trigger of this is if you set the pow upcast in the elemwise transfer to gpu to use 'float16' as the minimum type rather than float32 and have int8 inputs/outputs.

**Comment by nouiz** [comment]
@abergeron Should this be closed as gh-2930 is merged?

**Comment by lamblin** [comment]
Is it still an issue?

**Comment by abergeron** [comment]
Reading back the first sentence, I can't even believe that I wrote this.  I also can't understand what I was trying to say.

But in any case, I don't think this is a problem anymore since we handle float16 in elemwise correctly in all cases now.
