### ISSUE TITLE
Add a new op for sampling elements randomly without replacement

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#3143]

**Comment by nouiz** [comment]
This can be done by changing the MultinomialFromUniform Op I think. We already discussed a plan to implement it, but I forgot the detail. So if you want to work on this, tell me, I'll try to find again the plan. If you remember it, just write it now.

**Comment by nouiz** [comment]
I think this can be done by selection each sample one after the other. When one is selected, we set its weights to 0 in the probability. Then we need to keep a sum parameter (should start at 1) and decrease it by that probability. Then when we select the next, the uniform between 0 and 1, we rescale it between 0 and that probability sum.

This way, we keep the parallel generation of random numbers, but we loose the parallel sampling. I never saw this as a bottleneck (it was more the random number generation), but i didn't look closely to it. So we should benchmark first to be sure of this (especially on the GPU).

**Comment by lamblin** [comment]
What would the use case be for that? Generating only a couple of samples, or a full permutation?

Having the total sum of probabilities is not enough, you also need to keep track of the mapping between the uniform sample and the different classes, which changes every time.

Another option would be to implement the first algorithm of [Efraimidis and Spirakis (2006)](http://www.sciencedirect.com/science/article/pii/S002001900500298X#), see http://stackoverflow.com/a/20548895/1985353, but this requires sorting (or partial sorting).

**Comment by carriepl** [comment]
I've refactored the ticket into 2 tickets. The first ticket (this one) includes implementing the op (with a python implementation but no C implementation), the method to call the op and tests. The second ticket (#3930) is about adding a C implementation to the new op, for efficiency
