### ISSUE TITLE
Is there any tutorial that describes the arguments and return value of theano functions??

### ISSUE THREAD

**Issue by GiterLI** [Theano/Theano#3171]
Is there any tutorial that describes the arguments and return value of theano functions, such as scan. The "Theano 0.7 documentation" just give some examples of scan, but there is no complete description of the input arguments and output value. Thank you!

**Comment by nouiz** [comment]
This describe the signature of theano.function():

http://deeplearning.net/software/theano/library/compile/function.html#function.function

It return you what you give as the output parameter.

**Comment by lamblin** [comment]
If someone else has the same question later: that kind of documentation would be in the [library](http://deeplearning.net/software/theano/library/) section of the documentation, for instance [theano.scan](http://deeplearning.net/software/theano/library/scan.html#theano.scan).
