### ISSUE TITLE
importError: cannot import name gof

### ISSUE THREAD

**Issue by dongleecsu** [Theano/Theano#3172]
Hi, everyone
I'm a beginner of python, and today I try to install theano. When I install anaconda, mingw64, and use 'pip install theano' to install theano, I succeed. my environment:
Win7 64bit, python 2.7.9, theano 0.7.0, numpy 1.9.2, scipy 0.15.1
 But when I type 'import theano', some errors occur:
The first time I type 'import theano', the errors are like:
![11](https://cloud.githubusercontent.com/assets/13414927/8772939/d2ad3f96-2f02-11e5-94a5-1563c6387d3d.jpg)
if i don't close the cmd and continue to type 'import theano', the errors are :
ImportError: cannot import name gof

I get confused by this issue, can anyone help me? thanks a lot

**Comment by nouiz** [comment]
On windows with anaconda, you should use the dev version of Theano, as we have fix for that case:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

and follow those instruction to install missing dependency:

http://www.deeplearning.net/software/theano/install_windows.html#alternative-anaconda

I'll close this issue as I'm pretty sure of my answer, if you enconter problems, reply here and reopen it.

**Comment by dongleecsu** [comment]
Hi nouiz, thanks for your reply. I followed the install instruction of theano on windows. But I cannot install CUDA since my GPU is ATI. Does this means I cannot use theano? Does CUDA installation is necessary for installing theano? 
Thanks :)

**Comment by lamblin** [comment]
CUDA is not necessary at all to use Theano.
You seem not to be using mingw from Anaconda, this may be one of the reasons you have this error.
Also, you seem to be missing libpython.dll.

It looks like the missing step from your installation is `conda install mingw libpython`, but you may also need to uninstall your existing mingw, or remove it from the path.

**Comment by nouiz** [comment]
But you won't be to use your ATI/AMD GPU with Theano.

**Comment by dongleecsu** [comment]
Thank you all so much!
I tried 'conda install mingw libpython' and remove existing mingw from environment path and the problem was resolved.

**Comment by emmapapa** [comment]
hi dongleecsu, i have spend some days to install theano, and have many problem. i follow this link (http://stackoverflow.com/questions/25729969/installing-theano-on-windows-8-with-gpu-enabled), but do not succeed. Can you give me a help? thanks a lot
