### ISSUE TITLE
Ops creating variables without stack trace

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3190]
This ticket is here to centralize a list of functions or Ops creating symbolic variables without a stack trace.
- `DimShuffle`. None of the following assign a stack trace to the output's `tag.trace`:
  - `x.T`
  - `x.dimshuffle(1, 0)`
  - `theano.tensor.transpose(x)`

Related to #3018.

**Comment by nouiz** [comment]
DimShuffle.make_node call a_type.make_variable() instead of a_type.

Do work on this with too much duplication, who fix it?

**Comment by Sentient07** [comment]
@lamblin @nouiz  , I'm interested in fixing this issue. I've been a user of theano for a while, but a new contributor. Could you please help with the fix ? :)

**Comment by nouiz** [comment]
I think you simply need to go in the file tensor/elemwise.py in the method
DimShuffle.make_node() and replace


        output = TensorType(dtype=input.type.dtype,
                            broadcastable=ob).make_variable()

by


        output = TensorType(dtype=input.type.dtype,
                            broadcastable=ob)()


That should fix all the case in this tickets, as they all generate
DimShuffle.

Than make a PR [1] to Theano. Be sure to test this on your side.

If you have questions, don't hesitate.

[1]
http://www.deeplearning.net/software/theano/dev_start_guide.html#dev-start-guide

**Comment by Sentient07** [comment]
@nouiz , i'm able understand the change to be made with respect to the ticket. I ran the tests and one of the tests failed, test_flake8.py, which seems to exists from before.

**Comment by nouiz** [comment]
test_flake8.py will check that all files in Theano respect our coding
style. Check the error, it will tell you the problems in the modification
you did.

If you have difficulty, make a PR with what you have, it is easier to
discuss code over github.
