### ISSUE TITLE
Uninitialized memory returned from empty GpuGemv dot-product

### ISSUE THREAD

**Issue by mjwillson** [Theano/Theano#3217]
This case can show up when working with sparse vector representations, on the occasion you get a sparse vector without any non-zero entries.

Demo with Theano flags device=gpu,floatX=float32:

``` python
import theano
import theano.tensor as T
import numpy as np

# Compile a function that takes a dot product
W = T.matrix()
v = T.vector()
f = theano.function([W, v], W.dot(v))

# Apply to an empty matrix shape (5,0) and an empty vector shape (0,)
f([[], [], [], [], []], [])

# Get back some memory that's likely uninitialized

=>
array([  4.91618633e+00,  -6.61933719e+33,   8.00188596e+33,
        -2.90393344e+33,  -8.03866732e+32], dtype=float32)
```

It should return a vector of zeros for this empty dot-product, and it does when compiled on the CPU:

``` python
cpu = theano.compile.mode.get_default_mode().excluding('gpu')
f = theano.function([W, v], W.dot(v), mode=cpu)
f([[], [], [], [], []], [])

=>
array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)
```

**Comment by mjwillson** [comment]
Function graph is

```python
In [37]: theano.printing.debugprint(f.maker.fgraph.outputs[0])
HostFromGpu [@A] ''   
 |GpuGemv{inplace} [@B] ''   
   |GpuAllocEmpty [@C] ''   
   | |Shape_i{1} [@D] ''   
   |   |<CudaNdarrayType(float32, matrix)> [@E]
   |TensorConstant{1.0} [@F]
   |GpuDimShuffle{1,0} [@G] ''   
   | |GpuAdvancedSubtensor1 [@H] ''   
   |   |<CudaNdarrayType(float32, matrix)> [@E]
   |   |<TensorType(int64, vector)> [@I]
   |GpuFromHost [@J] ''   
   | |<TensorType(float32, vector)> [@K]
   |TensorConstant{0.0} [@L]
```

**Comment by nouiz** [comment]
Can you run with mode=DebugMode?

I think the problems is probably in GpuGemv or GpuAdvancedSubtensor1.
DebugMode should confirm this.

**Comment by mjwillson** [comment]
I just realised I can replicate this without the subtensor, just via a straight matrix-vector product -- looks like GpuGemv is the culprit.  I've updated the ticket with simpler steps to replicate. 

When running in DebugMode I get the correct answer -- a Heisenbug! that's one reason this took me so long to track down (NaNs were creeping into my code in a seemingly very non-deterministic way that went away when I turned on DebugMode...)

```
In [81]: f = theano.function([W, v], W.dot(v), mode="DebugMode")

In [82]: theano.printing.debugprint(f.maker.fgraph.outputs[0])
HostFromGpu [@A] ''   
 |GpuGemv{inplace} [@B] ''   
   |GpuAllocEmpty [@C] ''   
   | |Shape_i{0} [@D] ''   
   |   |<TensorType(float32, matrix)> [@E]
   |TensorConstant{1.0} [@F]
   |GpuFromHost [@G] ''   
   | |<TensorType(float32, matrix)> [@E]
   |GpuFromHost [@H] ''   
   | |<TensorType(float32, vector)> [@I]
   |TensorConstant{0.0} [@J]

In [83]: f([[], [], [], [], []], [])
Out[83]: array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)
```

**Comment by nouiz** [comment]
From memory, it is possible that cublas don't handle that case itself. So
we would need to do it ourself...

I'm pretty busy this week, are you able to help on that? Mostly go in the
file theano/sandbox/cuda/cuda_ndarray.cu in the function
CudaNdarray_sgemv(), we need to call cudamemset to set the output to 0
instead of calling cublasSgemv, for that case.

thanks

**Comment by mjwillson** [comment]
I just had a look at CudaNdarray_sgemv -- it seems like there's a lot of tricky special-case logic around striding for dimensions 0, 1 and >1 and I wondered if there might be a bug lurking there too, not that I could spot anything obvious?

The docs for cublassgemv don't mention any issue with m, n = 0, although it says m,n<0 is invalid: http://docs.nvidia.com/cuda/cublas/#cublas-lt-t-gt-gemv

If it is just a matter of cublas not handling it I might be able to fix, although I'm kinda nervous touching that striding logic. For now I've worked around it...

**Comment by nouiz** [comment]
I'm pretty sure this is a problem with cublas. As you didn't reply, could you make a report to NVIDIA about this? The more people report the problems they get, the more priority this get.

We already got this problem before.

**Comment by abergeron** [comment]
cublasXGemv doesn't work if n or m is 0 (it returns CUBLAS_MAPPING_ERROR).

I think what we do in that case is to just return the "output" buffer as-is since there is no computation to perform.

So to avoid nans the solution would be to memset the buffer to some values, but I would say that you have bigger problems in your model if you depend on that value since you effectively depend on the value of a mathematically undefined operation.

**Comment by nouiz** [comment]
@abergeron, we already discussed this live. I think this is defined
behavior. A reduction of type sum is defined for 0 element. It is the
identify of add: 0.

@mjwillson can you give more detail to why this happened and why this would
help you? I know some case, but I have dififculty to explain them clearly
as I didn't needed it myself and I was told about them a few years ago.

**Comment by mjwillson** [comment]
@nouiz the problem arose with a model that wants to compute a product of dense matrix and sparse vector. Conceptually speaking:

`dot(word_embedding_matrix, sparse_bag_of_words_vector)`

In the case where sometimes (rarely, but sometimes) the bag of words is empty.

The natural way to make this efficient is to represent the sparse vector as an index array and a values array, so you implement the matrix/sparse vector multiplication as

`dot(word_embedding_matrix[:, indexes], values)`

In the case of an empty sparse vector you get the problem described.

@abergeron this is well-defined, an empty sum is the additive identity, i.e. 0.

**Comment by nouiz** [comment]
I reported this to NVIDIA.
