### ISSUE TITLE
strange behavior with gradient of norm of a function involving relu units

### ISSUE THREAD

**Issue by jsusskin** [Theano/Theano#3223]
Here is an interesting case where a gradient of the built-in theano norm function does not behave properly when the norm is applied to a function of a relu activation.

The built-in and custom norm functions behave identically in the forward pass, but the gradient of the norm wrt. the weights does not produce proper values for inputs into the relu below 0. The gradient of the built-in norm produces a nan in that case. This is likely due to the piecewise nature of the relu where the values below the hinge are not handled properly in the gradient op.

Here's a test that shows the odd behavior for the built-in norm function:

```
x=T.matrix()
w=T.matrix()
relu=T.maximum(w*x,0)
gnorm1=0.5*relu.norm(2)**2
gnorm2=0.5*T.sqrt(T.sum(relu**2))**2
print T.grad(gnorm1,w).eval({x:[[1]],w:[[.5]]})
print T.grad(gnorm2,w).eval({x:[[1]],w:[[.5]]})
print T.grad(gnorm1,w).eval({x:[[-1]],w:[[.5]]})
print T.grad(gnorm2,w).eval({x:[[-1]],w:[[.5]]})
```

Output:
[[ 0.5]]
[[ 0.5]]
[[ nan]]
[[-0.]]

**Comment by lamblin** [comment]
Indeed, the gradient of `sqrt` is `inf` at 0, so when the output grad is 0 as well, it gives NaN.
I guess we could have an optimization replacing the gradient expression if that is important.
