### ISSUE TITLE
theano.function is changing random seed

### ISSUE THREAD

**Issue by keskarnitish** [Theano/Theano#3234]
I don't know if this issue was already reported (or if this is a design choice); a perfunctory search did not yield any hits. Here's what I noticed: calling theano.function seems to change the value of the seed for the `random` module. 

Here is a minimal working example:
```
import theano.tensor as T
import theano
import random

# Initialize random seed and print first number
random.seed(0)
firstVal = random.random()
print firstVal
# Reset seed
random.seed(0)

x = T.dscalar()
y = T.square(x)
f = theano.function([x],y)
print f(2)

secondVal = random.random()
print secondVal
```

Gives:
```
0.844421851525
4.0
0.403319204953
```

If you comment out `f = theano.function([x],y)`, then the test passes.

**Comment by nouiz** [comment]
It is used by theano lock for the compiledir.

Do this cause problems? I think it would be easy to use numpy random is
that help your case. Do you want to try to do it? It is in the file:
theano/gof/compilelock.py

One question, the fastest change would move the seed change in numpy
default randomstream. A just a little big longer modification would create
a new stream for the lock. Do you think it is a problem if we change numpy
seed?

I think for safety, it would be better to create a specific lock.

**Comment by keskarnitish** [comment]
The code I was writing needed both `random` and `numpy.random` streams. As you mentioned, the code doesn't seem to be changing `numpy.random` seed. I'm not sure if changing the `numpy.random` seed instead would really help since it might cause reproducibility issues. In my opinion, creating a new stream for the lock would indeed be a better solution to the issue. 
In any case, in order to get around the issue, one can easily seed the generators after all compilations have been made too. However, this could be a potential "gotcha" for someone and so I wanted to bring it up :)

**Comment by nouiz** [comment]
I have a PR in gh-3237, thanks for the report.

**Comment by lamblin** [comment]
@nouiz's fix makes sense, so I merged it. However, the C code compilation makes use of `mkdtemp`, which gets random tmp dir names from numpy.random. Since the number of new modules that need to be compiled depends on the current state of the compilation cache, this too could add an element of non-determinism in the state of `random`.

**Comment by nouiz** [comment]
@lamblin I checked the file from python 2.7 for the method mkdtemp.

It use an instance of random.Random(). It have it own state and don't change the global random state.

I tested the code above and I don't see the change in value as before my PR.

Where did you saw that mkdtemp changed the global python random state? With which python version? Could this be with one older then python 2.7?

**Comment by lamblin** [comment]
I vaguely remember that from an old ticket, that might very well be from an earlier Python version.
Actually, this is the issue I remember: #1533, and I don't remember if we determined that mkdtemp could actually change the random state, or if it was just a suspicion.
