### ISSUE TITLE
Creating a theano Tensor from a gpu pointer and size

### ISSUE THREAD

**Issue by Russell91** [Theano/Theano#3235]
Hey, I'm looking to bolt on Theano to some python code that wraps a c++ tensor library. To make this work, I need to be able to create a Theano tensor from my device pointer and never have the Theano tensor copied to the cpu. When I'm done, I'd want to copy the Theano memory back to a second gpu pointer. If I could do this, I'm assuming I can figure out how to hook up the gradients and make everything work on the way back. Is this possible with a little bit of creativity? Perhaps I could call into some functions from here: https://github.com/Theano/libgpuarray/blob/master/pygpu/gpuarray.pxd

**Comment by nouiz** [comment]
This is possible. Do you want to do that conversion in C or in Python?

We convert a pycuda array to a Theano one and the other way around in the
file theano/misc/pycuda_utils.py This would allow you do to so in python.

**Comment by Russell91** [comment]
Great, I hadn't seen that file. I'm very busy at the moment, but I'll try to look into this next week and let you know how it goes. Thanks!

**Comment by Russell91** [comment]
This is now working well for me. Thank you for the pointer.
