### ISSUE TITLE
Using theano with anaconda

### ISSUE THREAD

**Issue by spudzee** [Theano/Theano#3236]
I'm trying to use theano (0.7.0). And I'm using anaconda. I did "$ pip install theano", and it appeared to work. But when I do "$ python import theano" it produces this: http://pastebin.com/3i7WbC0y But I can clearly see the gof folder under theano.

So I ran python -v import theano, and it produced this: pastebin.com/uNW6RPdL

I'm running Windows 7, I downloaded anaconda from here: https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda3-2.3.0-Windows-x86_64.exe I also have mingw installed to handle the C compiling.

**Comment by nouiz** [comment]
On Windows, you need to use Theano development version to work with anaconda:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

I'll close this issue as I'm pretty sure it will fix, this, but if not, tell us.

Currently, there Theano use something that is in the C++ standard, but that windows don't implement! The work around isn't implemented yet. Use the git commit f4edcc5 it don't use the part that windows compiler don't implement.
