### ISSUE TITLE
A Real Example: Logistic Regression on page 42 of pdf

### ISSUE THREAD

**Issue by grfiv** [Theano/Theano#3240]
\# Declare Theano symbolic variables
x = T.matrix("x")
y = T.vector("y")

needs to be

\# Declare Theano symbolic variables
x = T.matrix("x",  dtype='float64')
y = T.vector("y",  dtype='float64')

**Comment by nouiz** [comment]
Why do you think we need that change?

By default, they are float64.

**Comment by grfiv** [comment]
Because it failed before I made the change.

Bleeding-edge installation on Ubuntu 14.04 on an AWS g2.2xlarge, Python
2.7.6

**Comment by nouiz** [comment]
What error did you got?

Did you changed Thean flags floatX to float32? If you aren't sure, execute:

print theano.config.floatX

thanks

**Comment by grfiv** [comment]
Removing the dtypes produces the following:

TypeError                                 Traceback (most recent call
last)<ipython-input-2-8331c0afec5a> in <module>()     30 # Train
31 for i in range(training_steps):---> 32     pred, err = train(D[0],
D[1])     33 print "Final model:"     34 print w.get_value(),
b.get_value()
/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc
in __call__(self, *args, **kwargs)    532
s.storage[0] = s.type.filter(    533                             arg,
strict=s.strict,--> 534
allow_downcast=s.allow_downcast)    535     536
except Exception as e:
/usr/local/lib/python2.7/dist-packages/theano/tensor/type.pyc in
filter(self, data, strict, allow_downcast)    129
       '"function".'    130                             % (self,
data.dtype, self.dtype))--> 131                         raise
TypeError(err_msg, data)    132                 elif (allow_downcast
is None and    133                         type(data) is float and
TypeError: ('Bad input argument to theano function with name
"<ipython-input-2-8331c0afec5a>:28"  at index 0(0-based)',
'TensorType(float32, matrix) cannot store a value of dtype float64
without risking loss of precision. If you do not mind this loss, you
can: 1) explicitly cast your data to float32, or 2) set
"allow_input_downcast=True" when calling "function".',
array([[-0.19988366,  0.57428403,  0.93216119, ..., -0.79247328,
        -0.91651899, -0.30001107],
       [ 0.60258529, -0.20330968, -1.50828514, ..., -1.06980813,
        -1.42848108, -1.13014792],
       [ 0.95016122,  0.86793314,  1.01328624, ...,  0.2618861 ,
        -1.37242731,  0.96285377],
       ...,
       [-0.9618907 ,  0.42620269,  1.1164728 , ...,  0.22901447,
        -0.11163282,  0.53509618],
       [-0.77687947, -0.20697709,  0.9403582 , ..., -0.69805483,
        -0.58376374,  0.47361758],
       [-2.04251093, -0.24669384,  0.3567223 , ..., -0.31852944,
         0.68991056, -0.43403961]]))

**Comment by grfiv** [comment]
In [1]: import theano
Couldn't import dot_parser, loading of dot files will not be possible.
Using gpu device 0: GRID K520 (CNMeM is disabled)

In [2]: print theano.config.floatX
float32

Removing the dtypes produces the following:

TypeError                                 Traceback (most recent call
last)<ipython-input-2-8331c0afec5a> in <module>()     30 # Train
31 for i in range(training_steps):---> 32     pred, err = train(D[0],
D[1])
     33 print "Final model:"
     34 print w.get_value(), b.get_value()

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc
in __call__(self, *args, **kwargs)    532
s.storage[0] = s.type.filter(    533                             arg,
strict=s.strict,--> 534
allow_downcast=s.allow_downcast)    535
    536                     except Exception as e:

/usr/local/lib/python2.7/dist-packages/theano/tensor/type.pyc in
filter(self, data, strict, allow_downcast)    129
       '"function".'    130                             % (self,
data.dtype, self.dtype))--> 131                         raise
TypeError(err_msg, data)    132                 elif (allow_downcast
is None and    133                         type(data) is float and
TypeError: ('Bad input argument to theano function with name
"<ipython-input-2-8331c0afec5a>:28"  at index 0(0-based)',
'TensorType(float32, matrix) cannot store a value of dtype float64
without risking loss of precision. If you do not mind this loss, you
can: 1) explicitly cast your data to float32, or 2) set
"allow_input_downcast=True" when calling "function".',
array([[-0.19988366,  0.57428403,  0.93216119, ..., -0.79247328,
        -0.91651899, -0.30001107],
       [ 0.60258529, -0.20330968, -1.50828514, ..., -1.06980813,
        -1.42848108, -1.13014792],
       [ 0.95016122,  0.86793314,  1.01328624, ...,  0.2618861 ,
        -1.37242731,  0.96285377],
       ...,
       [-0.9618907 ,  0.42620269,  1.1164728 , ...,  0.22901447,
        -0.11163282,  0.53509618],
       [-0.77687947, -0.20697709,  0.9403582 , ..., -0.69805483,
        -0.58376374,  0.47361758],
       [-2.04251093, -0.24669384,  0.3567223 , ..., -0.31852944,
         0.68991056, -0.43403961]]))

**Comment by f0k** [comment]
> TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32

That's what you should do. Ensure that the input to your compiled function is of dtype `theano.config.floatX`, i.e., by doing `np.asarray(your_data, dtype=theano.config.floatX)`. If you change the dtype of the symbolic variables to `float64` instead, execution cannot be moved to GPU any more.

**Comment by nouiz** [comment]
Jan, the problem is that our documentation here use T.matrix(), but this is
doc before we talk about floatX. He probably used a VM existing that have
been hardcoded to have floatX=float32 by someone else.

I think that for this doc example, we will force float64, as we talk later
about floatX:

http://www.deeplearning.net/software/theano/tutorial/examples.html#a-real-example-logistic-regression

**Comment by grfiv** [comment]
If it helps, I'm using Ubuntu 15.04 on an AWS g2.2xlarge instance with a
GPU.

**Comment by nouiz** [comment]
I have a fix in this PR: https://github.com/Theano/Theano/pull/3263

thanks
