### ISSUE TITLE
how to use an int parameter in theano.function

### ISSUE THREAD

**Issue by dinglei0719** [Theano/Theano#3271]
I'm new and I try to use multi-channel convolutional neural network to do some sentiment classification on short sentence.
here is a short explanation:
at first, each word in the sentence was transformed into a 100 d vector with gensim word2vec.
then each sentence become a 100*50 matrix, each row is a word (50 is a pre-defined sentence length, if a sentence has less than 50 words, the left part of the matrix will be zero)
then I use kernel with different size, such as 3*100, 5*100 then I concatenate the pooling result and use LR to do classification.

my problem is , for example, the input sentence is ['I','do','not','like','it'], the convolution output on ['like','it',0] effect the result a lot.
so i want to cut the conv output to numOfWords - kernelWidth + 1, and I need to transmit an int parameter into the theano.function. 
If numOfWords is less than kernelWidth, I will use set_subtensor function to set the conv output to zeros instead.

I write my code refer to the DeepLearningTutorials example convolutional_mlp.py: https://github.com/lisa-lab/DeepLearningTutorials/blob/master/code/convolutional_mlp.py

validate_model = theano.function(
        [index],
        layer3.errors(y),
        givens={
            x: valid_set_x[index * batch_size: (index + 1) * batch_size],
            y: valid_set_y[index * batch_size: (index + 1) * batch_size]
        }
    )
I need to transmit numOfWords into this function and numOfWords will change everytime I call the function.
I have tried to add self.numOfWords to the class and perform "self.numOfWord = 3" before call the valid function, but it do not change, always the number I init the object.

How can I make it change?

Thank you & sorry for my poor english

**Comment by nouiz** [comment]
very old user question, so closing. If you still need the answer, ask on theano-user mailing list or stackoverflow.
