### ISSUE TITLE
Add a 'name' argument to '.copy' method of Theano variables.

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#3273]
See the discussion in https://github.com/mila-udem/blocks/issues/784.

**Comment by dwf** [comment]
@yingzha This is your ticket for this week. Basically the `copy` method on Theano variables should have a `name` argument that sets the `.name` of the newly created variable. It will involve modifying [this method](https://github.com/Theano/Theano/blob/master/theano/tensor/var.py#L523-L524) and probably writing a small function to replace `tensor_copy` [here](https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py#L2809-L2810), plus tests.

**Comment by yingzha** [comment]
@dwf , I added .name to `copy` like this 
`def copy(self, name):
         """Copy a variable and set a name to the copy."""
         copied_variable = theano.tensor.basic.tensor_copy(self)
         copied_variable.name = name
         return copied_variable
`
Do we still need to modify `tensor_copy`?

**Comment by dwf** [comment]
The name argument should definitely be optional but otherwise that sounds fine.
