### ISSUE TITLE
NotImplementedError: We didn't implemented yet the case where scan do 0 iteration

### ISSUE THREAD

**Issue by danielrenshaw** [Theano/Theano#3276]
There appears to be a problem associated with computing gradients through scan when the first element in the sequence is used as an initialization value (via `outputs_info`) and the rest of the sequence is iterated over (via `sequences`).

This has been brought up on at least two occasions, e.g. on [StackOverflow](http://stackoverflow.com/questions/31804340/a-weird-error-with-updates-in-theano) and the [theano-users mailing list](https://groups.google.com/forum/#!topic/theano-users/aeZqBntdkNw).

A reasonably minimal reproduction example:

    import numpy
    import theano
    import theano.tensor as tt
    import theano.ifelse

    def inner_scan_step(x_t_t, h_tm1, w):
        # Fails when using this recursive expression
        h_t = tt.dot(h_tm1, w) + x_t_t

        # No failure when using this recursive expression
        # h_t = h_tm1 + tt.dot(x_t_t, w)

        return h_t

    def outer_scan_step(x_t, w):
        h, _ = theano.scan(inner_scan_step,
                           sequences=[x_t[1:]],
                           outputs_info=[x_t[0]],
                           non_sequences=[w],
                           strict=True)
        return h[-1]

    def get_outputs(x, w):
        features, _ = theano.scan(outer_scan_step,
                                  sequences=[x],
                                  non_sequences=[w],
                                  strict=True)
        return tt.grad(features.sum(), w)

    def main():
        theano.config.compute_test_value = 'raise'

        x_value = numpy.arange(12, dtype=theano.config.floatX).reshape((2, 2, 3))

        x = tt.tensor3()
        x.tag.test_value = x_value

        w = theano.shared(value=numpy.ones((3, 3), dtype=theano.config.floatX), borrow=True)

        f = theano.function(inputs=[x], outputs=get_outputs(x, w))

        print f(x_value)

    if __name__ == "__main__":
        main()

**Comment by nouiz** [comment]
I just tested that and it now work. I think it is https://github.com/Theano/Theano/pull/3292 that fixed that.
