### ISSUE TITLE
cuDNN on Windows not compiling + solution

### ISSUE THREAD

**Issue by GeertLitjens** [Theano/Theano#3298]
Line 10 in cudnn_base.c cause Theano code to fail compilation using Visual Studio 2013 on Windows. This has been changed in commit b9e29 on July 15th. Variable length arrays are not allowed by the C++ standard (although gcc supports it as an extension). This can be solved by changing this part to:

```
  int dim = CudaNdarray_NDIM(var);
  int* strides = new int[dim];
  int default_str = 1;

  for (int i = dim-1; i >= 0; i--)
  {
    if (CudaNdarray_HOST_STRIDES(var)[i])
      strides[i] = CudaNdarray_HOST_STRIDES(var)[i];
    else
      strides[i] = default_str;
    default_str *= CudaNdarray_HOST_DIMS(var)[i];
  }

  cudnnStatus_t err = cudnnSetTensorNdDescriptor(desc, CUDNN_DATA_FLOAT, dim,
                                                 CudaNdarray_HOST_DIMS(var),
                                                 strides);
  delete[] strides;
```

But probably there is a nicer solution.

**Comment by dhammack** [comment]
@GeertLitjens can you be more specific as to which file needs this change? I can't find a cudnn_base.c in the repo (or in CUDA). 

I also can't get cuDNN to compile on Windows + VS2013 after updating today, so I'm curious about your solution. My message is:

    ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: dynamic module does not define init function (initcuda_ndarray)
    WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: cuda unavilable)

**Comment by GeertLitjens** [comment]
Hmm, this was not the error I got, it managed to compile cuda_ndarray just fine. I did disable the check for cudnn in dnn.py (does not seem to work on Windows still, although cudnn itself works fine), so maybe your error is related to that.

**Comment by lamblin** [comment]
@GeertLitjens This solution would work, thanks. I think another option would be to use `calloc` to allocate dynamically `strides` on the stack, which removes the need to clean it up at the end. It may be a bit faster, not sure if that would be "nicer" though. Could you submit a pull request?
Hopefully we will be able to test cudnn on Windows ourselves soon.

**Comment by lamblin** [comment]
@dhammack This error message is similar to that of an issue that was solved a couple of weeks ago. Did you update from the latest development version on GitHub?

**Comment by dhammack** [comment]
@lambin thanks for the help. I thought I had updated theano but apparently I did it wrong. After updating and applying the changes of @GeertLitjens to dnn_base.c I am able to use cuDNN 3 on Win8.

**Comment by nouiz** [comment]
Can one of you try to change the malloc to calloc and remove the free? Making allocation can be very time consumming. If calloc work on windows, it would be better.

thanks.

**Comment by lamblin** [comment]
Closing as so many things have changed in the handling of cuDNN...
