### ISSUE TITLE
import Theano problem

### ISSUE THREAD

**Issue by guptarah** [Theano/Theano#3316]
Hi,
I am trying to install theano using pip. It installs numpy scipy and theano. 
However when I import Theano, I get the following error. It outputs a lot of code followed by error description.

Any help would be appreciated.
Thanks in advance.

Error:
.
.
A lot of code ....
.....
.....
01061	    PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01062	
01063	    return RETVAL;
01064	}
01065	
===============================
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -march=core2 -mcx16 -msahf --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=4096 -mtune=core2 -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include -I/auto/rcf-proj/pg/guptarah/Python-3.3.5/include/python3.3m -I/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/gof -fvisibility=hidden -o /auto/rcf-40/guptarah/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-3.3.5-64/lazylinker_ext/lazylinker_ext.so /auto/rcf-40/guptarah/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-3.3.5-64/lazylinker_ext/mod.cpp -L/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib -lpython3.3m
In file included from /auto/rcf-40/guptarah/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-3.3.5-64/lazylinker_ext/mod.cpp:7:
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘FILE* npy_PyFile_Dup2(PyObject*, char*, off_t*)’:
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:156: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:156: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:174: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:174: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:202: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:202: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘int npy_PyFile_DupClose2(PyObject*, FILE*, off_t)’:
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:255: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:255: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘int npy_PyFile_DupClose(PyObject*, FILE*)’:
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:289: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:289: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘PyObject* npy_PyFile_OpenFile(PyObject*, const char*)’:
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:348: warning: deprecated conversion from string constant to ‘char*’
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘int npy_PyFile_CloseFile(PyObject*)’:
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:356: warning: deprecated conversion from string constant to ‘char*’
/usr/bin/ld: /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/libpython3.3m.a(abstract.o): relocation R_X86_64_32S against `_PyObject_NextNotImplemented' can not be used when making a shared object; recompile with -fPIC
/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/libpython3.3m.a: could not read symbols: Bad value
collect2: ld returned 1 exit status

Traceback (most recent call last):
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/gof/lazylinker_c.py", line 74, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/gof/lazylinker_c.py", line 91, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/__init__.py", line 63, in <module>
    from theano.compile import (
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/compile/mode.py", line 12, in <module>
    import theano.gof.vm
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/gof/vm.py", line 672, in <module>
    from . import lazylinker_c
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/gof/lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "/auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/theano/gof/cmodule.py", line 2174, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): In file included from /auto/rcf-40/guptarah/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-3.3.5-64/lazylinker_ext/mod.cpp:7:. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘FILE* npy_PyFile_Dup2(PyObject*, char*, off_t*)’:. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:156: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:156: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:174: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:174: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:202: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:202: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘int npy_PyFile_DupClose2(PyObject*, FILE*, off_t)’:. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:255: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:255: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘int npy_PyFile_DupClose(PyObject*, FILE*)’:. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:289: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:289: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘PyObject* npy_PyFile_OpenFile(PyObject*, const char*)’:. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:348: warning: deprecated conversion from string constant to ‘char*’. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h: In function ‘int npy_PyFile_CloseFile(PyObject*)’:. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/python3.3/site-packages/numpy/core/include/numpy/npy_3kcompat.h:356: warning: deprecated conversion from string constant to ‘char*’. /usr/bin/ld: /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/libpython3.3m.a(abstract.o): relocation R_X86_64_32S against `_PyObject_NextNotImplemented' can not be used when making a shared object; recompile with -fPIC. /auto/rcf-proj/pg/guptarah/Python-3.3.5/lib/libpython3.3m.a: could not read symbols: Bad value. collect2: ld returned 1 exit status.

**Comment by lamblin** [comment]
Your installation seems to be missing the dynamic version of the python library (something like libpython3.3m.dll).
