### ISSUE TITLE
Theano function returning CudaNdarray

### ISSUE THREAD

**Issue by EderSantana** [Theano/Theano#3324]
Hi,

I compiled a Theano function and it returned a Cuda array instead of a numpy array. The function was
```python
W  = shared(np.random.randn(100, 100))
F = function([], W)
F()
```
Wasn't the compiled function supposed to return a numpy array? Am I missing something?

**Comment by nouiz** [comment]
Theano isn't 100% invisible about the GPU. You just hit a case where it isn't.

To fix that, you can execute any operation on W or call

W=shared(...)
out = theano.tensor.as_tensor_variable(W)
F=function([], out)
F()

this will force the output to be on the CPU. You can alway call it. If it is on the CPU, it will do nothing.

**Comment by nouiz** [comment]
If you have questions/comments, don't hesitate. I started some time ago to fix this, but it isn't trivial and I got moved to other priority.

**Comment by EderSantana** [comment]
Cool! Thanks, @nouiz!!! That solves my problem.
