### ISSUE TITLE
spatial softmax

### ISSUE THREAD

**Issue by abayowbo** [Theano/Theano#3326]
Is there a spatial softmax in theano that will sum over spatial locations in each channel, treating each channel separately? I have looked at the documentation and can't seem to find anything like this. Thanks.

**Comment by nouiz** [comment]
Cudnn allow it and we wrap it:
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html#softmax-ops

Otherwise, I'm pretty sure you can reshape/dimshuffle the inputs and call
the normal softmax. This would work on the CPU too (but maybe slower on the
GPU, I'm not sure of that).

If you end up doing the reshape/dimshuffle, a PR with this on Theano would
be useful.

**Comment by Pandoro** [comment]
I've been trying this for a while now, but I keep running into trouble,

Assuming my `input` is in the 'bc01' format and my `target` in the 'b01' format, if my width and height are both 1, the whole thing degrades to the following, e.g. a normal softmax:

```python
#softmax
self.p_y_given_x = T.nnet.softmax(input.flatten(2))

#negative log likelihood
-T.mean(T.log(self.p_y_given)[T.arange(target.shape[0]), target.flatten(1)])
```

This works like a charm and I can train a network with it without any problems, no Nans, good scores.

Now as a first test case for a spatial softmax, I keep the same test case, but I properly treat it as a spatial input. E.g.:

```python
#transform input
input_trans = input.swapaxes(0,1) #-> 'cb01'
input_trans = input_trans.flatten(2) #-> 'c "all" '
input_trans = input_trans..swapaxes(0,1) #-> '"all" c', this works for the softmax

#softmax
self.p_y_given_x = T.nnet.softmax(input_trans)

#negative log likelihood
-T.mean(T.log(self.p_y_given)[T.arange(target.shape[0]), target.flatten(1)])
```

As far as I understand it, this should have exactly the same effect and it should generalize to an actual spatial softmax that handles arbitrary input width and heights. In some dummy tests, it also works fine for forward computations, but when I actually use it while training a network, the negative log likelihood soon becomes very large and ends up in `nan`. If I now explicitely clip the softmax outputs to `(1e-4, 1-1e-4)` before putting it into the `T.log`, it will actually stop the negative log likelihood from becoming `nan`, but my network never converges to anything usefull. 

To make it worse, if I actually use the spatial softmax from cudnn, I run into exactly the same problem. So while a spatial softmax should be easy, I can't get it to work. So any input on this would be great.

**Comment by lamblin** [comment]
See #5712.
