### ISSUE TITLE
How to reformat theano Tensor variables? "TensorType does not support iteration" error comes:"(

### ISSUE THREAD

**Issue by ghost** [Theano/Theano#3328]
There are three 4D tensors X1, X2 and X3.
X1 and X2 has the same dimensions and the same number of elements in each dimension.
I want to get:

```
X3[:,:,0,:]=X1
X3[:,:,1,:]=X2
```

I tried the followed code:

```
        X= self.get_input(train)
 #       X3 = np.zeros((int(X.shape[0]), int(X.shape[1]), 2, int(X.shape[3]-self.nb_col-self.index)))
        X3 = T.tensor4()

        X1= X[:,:,:,0:X.shape[3]-self.nb_col-self.index]
        X2= X[:,:,:,self.nb_col+self.index:]
#        X3 = T.concatenate([X1,X2])
        for inum in X.shape[0]:
            for jnum in X.shape[1]:
                for knum in X.shape[3]-self.nb_col-self.index:
                    X3[inum,jnum,0,knum]=X1[inum,jnum,0,knum]
                    X3[inum,jnum,1,knum]=X2[inum,jnum,0,knum]
        return X3
```

The error is:TypeError(('TensorType does not support iteration. '
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)

How to solve this problem?
Thank you all!!

**Comment by nouiz** [comment]
Hi,

You can't loop over a Theano Variable, as this is symbolic variable.  This
is not good:

The for loop is executed by python and we don't know yet the number of
iteration that will be done.

You want to use set_subtensor to solve your problem:

http://deeplearning.net/software/theano/library/tensor/basic.html?highlight=set_subtensor#theano.tensor.set_subtensor
