### ISSUE TITLE
theano.tensor.nnet.conv.conv2d don't support uint

### ISSUE THREAD

**Issue by ghost** [Theano/Theano#3329]
Why is it the case that in the conv2d function, line 127 the following assert is there:

assert str(image_shape[i].dtype).startswith('int')

this does not allow uint shape and also allows negative shapes (if not checked before), right? Is there a reason you guys did startswith() and not something like 'int' in str(image_shape[i].dtype)?

**Comment by nouiz** [comment]
There isn't a good reason to not accept uint. We need to accept int as this is the default dtype and just using python int would create this.

We don't check the value, but this could be added. Do you want to make a PR with those suggestion?

thanks

**Comment by mronian** [comment]
I'd like to try fixing this. As far as I understand, you need the dtype to be restricted to int or uint. Am I right?

**Comment by nouiz** [comment]
Right. It you have questions dont hesitate.
Le 11 oct. 2015 09:10, "Anchit Navelkar" <notifications@github.com> a
écrit :

**Comment by mronian** [comment]
I changed that line to 
```
assert "int" in str(image_shape[i].dtype)
```
Is that all that was required?

**Comment by nouiz** [comment]
It also need tests. Tests for file:

ddd.py

are in:

tests/test_ddd.py

One one test for that and that could be enough.

**Comment by mronian** [comment]
The test ran without errors. 

There is a similar issue to this one a few lines below where the filter shape datatype is checked for 'startswith('int')'. Should I update that too in this pull request or will that be a separate one?

**Comment by nouiz** [comment]
Copy ing in the same pull request is good. This is 2 small related changes.
Thanks
Le 13 oct. 2015 7:00 AM, "Anchit Navelkar" <notifications@github.com> a
écrit :
