### ISSUE TITLE
Matrix Inverse using cuBLAS

### ISSUE THREAD

**Issue by aviveise** [Theano/Theano#3332]
Hi,
Are there any plans on implementing matrix inverse op on GPU using cuBLAS?, I wanted to implement this op using solver or batched matrix inverse op but if there are plans to develop this op i won't continue.

Thanks

**Comment by benanne** [comment]
I have a rudimentary implementation of a batched matrix inversion op with scikits.cuda here: https://github.com/benanne/theano_wmf/blob/master/ops.py#L180

**Comment by nouiz** [comment]
I don't think any of Theano core dev will work on that shortly.

As more then 1 person seem to use this, it would be good to move this in
Theano. @aviveise, do you want to do that? We don't have time for this in
the short term.

**Comment by aviveise** [comment]
I'll do it, Thanks!

**Comment by juancamilog** [comment]
Has this functionality been moved into Theano?

**Comment by nouiz** [comment]
No. If you want, you can help us on that.

Fred

**Comment by botev** [comment]
Could someone clear up how one can attempt to replicate the `skcuda` fft op for something like a linear solver? Is the code going to be almost parallel / analogous or is there something special we should have in mind?

**Comment by nouiz** [comment]
I'm not sure I understand what you mean. You can always make a new Op that
will do a combination of many calls to skcuda and others python function
that dispatch GPU code. The code inside those call will be parallelized on
the GPU. Does this answer your question?

This doc tell about how to make a GPU op:

http://deeplearning.net/software/theano_versions/0.9.X/extending/extending_theano_gpu.html

**Comment by botev** [comment]
@nouiz could we take it to the other thread I made specifically for the `skcuda` wrapper I'm trying to do. Could you check and give just a bit help of making that work? The questions I have are listed there and they include more details of how to actually manage some of the stuff in the operator.

**Comment by MahmoudIsmail88** [comment]
hello all, any updates on performing matrix inverse on GPU ?

**Comment by nouiz** [comment]
This was merged 2h ago with magma instead of cublas:

https://github.com/Theano/Theano/pull/5778

You will need to install magma and set Theano flag magma.enabled=True

**Comment by botev** [comment]
@nouiz Could we someone add a link for where/how to install Magma and which versions are compatible? Should we build it from source etc... Which flags when building MAGMA are required by Theano etc...

**Comment by aam-at** [comment]
@botev you need to build shared library (tested with magma-2.2). If you need to use linear solver, you can use `GpuCusolverSolve`.

**Comment by botev** [comment]
@aam-at I'm aware of the `GpuCusolverSolve`, however, if MAGMA is faster for matrix inverse I would have assumed this is also true for linear system solver, or is that not the case?

**Comment by aam-at** [comment]
@botev I haven't profiled magma linear solver, so I don't know.

**Comment by botev** [comment]
@aam-at Could I ask for some assistance or more heavy commenting in your `magma_inverse.c`, since if I want to port the linear solver I guess I need something close to that, as well as additionally take in to account any transposition or if the matrix is symmetric use `sposv` as I guess in many cases when we need inverses in ML we actually are working with symmetric PSD matrices. That would be really appreciated and then it would be easy to directly benchmark theano cusolver and magma ops. I guess also porting the eigenvalue decomposition in addition to the SVD makes sense for the same reasons as above.

**Comment by aam-at** [comment]
@botev you should check documentation or [examples](https://developer.nvidia.com/sites/default/files/akamai/cuda/files/Misc/mygpu.pdf) of usage. I don't plan to work on magma linear solver. I plan to add magma qr and cholesky. If you'll start working on psd inverse, let me know. Take a note, that numpy does not have specialized psd inverse. Ideally, we should have both cpu and gpu versions.

**Comment by botev** [comment]
@aam-at scipy has a more BLAS-like linear solver on the cpu. Note that however, if I do this it will be on linear solvers, rather than matrix inverses, since they are faster and more numerically stable.

**Comment by nouiz** [comment]
Having docs to tell user about that/and to install magma (link to magma doc good) and version would be great.
