### ISSUE TITLE
Don't have scan raise warning when strict=True and all is good

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3333]
See: https://groups.google.com/forum/#!topic/theano-users/VeOLnC9imHo

and

https://groups.google.com/d/topic/lasagne-users/jtXB62wd7mQ/discussion

**Comment by kyunghyuncho** [comment]
Somehow I now feel that there's no need for this warning at all. What do you think, @nouiz, @lamblin and @carriepl?

**Comment by nouiz** [comment]
I have no idea. On the URL pasted, it was told that without this, the error
message would be not very clear that without the strict=True parameter, it
would be working.
