### ISSUE TITLE
make downsample ignore_border=False, pad and use cudnn

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3336]
This is faster then the old code and remove some CPU case.

But we also need to transition to a new default of ignore_border=True after some transition.

**Comment by nouiz** [comment]
Instead of doing explicit padding, we can make 3 call to cuDNN pooling. The main that ignore the border and 2 others with changed pooling windows that will do the partial part. This would remove the need for a copy.

**Comment by aam-at** [comment]
@nouiz Do you still need help with this issue for new gpuarray backend?

**Comment by nouiz** [comment]
Nobody started it. If you start it, tell us.

thanks.

On Tue, Nov 1, 2016 at 2:50 PM, Alexander Matyasko <notifications@github.com

**Comment by nouiz** [comment]
Done in the new back-end, so closing.
