### ISSUE TITLE
speed up weight update for sub tensor

### ISSUE THREAD

**Issue by hycis** [Theano/Theano#3342]
Here I am experimenting with a very import feature that is needed for word embedding, that is selecting a subtensor from word embedding matrix. And I realise current theano back propagation is very inefficient to such scenario

```python
# this takes 43 seconds
# word embedding
w = theano.shared(np.random.rand(10000,1000))
x = T.matrix()
y = T.dot(w, x).sum()  
dydw = T.grad(y, w)
f = theano.function([x], y, updates=[(w, dydw * w)])
for i in range(1000):
    f(np.random.rand(1000,10))

# This takes 30 seconds
# word embedding
w = theano.shared(np.random.rand(10000,1000))
x = T.matrix()
y = T.dot(w[:10], x).sum() #using only subtensor  
dydw = T.grad(y, w)
f = theano.function([x], y, updates=[(w, dydw * w)])
for i in range(1000):
    f(np.random.rand(1000,10))
```
It takes a total of ```43 seconds```
Then instead of using the full word embedding, I select 10 rows to compute y, that is ```y=T.dot(w[:10],x).sum()``` and this takes ```30 seconds```.

Conclusion is when I use 1/1000 of the rows in `w`, the speed up is merely from `43s` to `30s`. My guess is that theano actually computes the gradient of the full weight matrix instead of the subtensor. I wonder is there a smarter way to compute the gradient of w, and only compute the gradients for the subtensor w[:10] instead of the whole w. I believe this is quite an important feature for training embeddings. Because usually there is very sparse selection in embeddings.

**Comment by benanne** [comment]
I think you should account for the transfer of the input data to the GPU. Because the computation is so simple, you might find that this dominates the running time.

(Sidenote: I appreciate this is just a short code snippet to demonstrate something, but the updates don't really seem to make much sense to me. It looks like you are updating w by the previous value of w multiplied by dy/dw.)

**Comment by hycis** [comment]
the w update has no meaning, it's just for demonstration purpose. I wonder if theano updates the whole `w` while in actual fact only the subtensor `w[:10]` is used for computation. Does theano has intelligent way of figuring out if only a subtensor is used for the computation graph, and only compute gradient for that subtensor?

**Comment by dwf** [comment]
There are (I think, memory is foggy) optimizations that push subtensor operations inward so that they are done earlier and thus resulting computations can take place on a smaller tensor, but it probably depends on the graph whether or not these can be applied.

**Comment by nouiz** [comment]
To make a good profiling, use the Theano flag profile=True. This will print
output that will give you the right thing to time.

But the problem I think is that you use a pattern that is very hard for
Theano to optimize. I tried to to do, but this isn't easy and we probably
won't cover. To have it fast, you need to write the code a little bit
differently like this:

```
import theano.tensor as T
import theano
import numpy as np
w = theano.shared(np.random.rand(10000,1000))
x = T.matrix()
w_ = w[:10]
y = T.dot(w_,x).sum()
dydw = T.grad(y, w_)
f = theano.function([x], y,
                    updates=[(w, theano.tensor.set_subtensor(w_, dydw *
w_))])
for i in range(1000):
    f(np.random.rand(1000,10))
```

This pattern like David told will be made inplace.

You can print the optimized function like this to see what we end up
doing[1]

```
theano.printing.debugprint(f)
```

```

Sum{acc_dtype=float64} [@A] ''   7
 |Dot22 [@B] ''   5
   |Subtensor{:int64:} [@C] ''   1
   | |<TensorType(float64, matrix)> [@D]
   | |Constant{10} [@E]
   |<TensorType(float64, matrix)> [@F]
IncSubtensor{InplaceSet;:int64:} [@G] ''   10
 |<TensorType(float64, matrix)> [@D]
 |Elemwise{Mul}[(0, 0)] [@H] ''   9
 | |Dot22 [@I] ''   8
 | | |Alloc [@J] ''   6
 | | | |TensorConstant{(1, 1) of 1.0} [@K]
 | | | |Elemwise{Composite{Switch(LT(i0, i1), i0, i1)}}[(0, 1)] [@L] ''   4
 | | | | |TensorConstant{10} [@M]
 | | | | |Shape_i{0} [@N] ''   0
 | | | |   |<TensorType(float64, matrix)> [@D]
 | | | |Shape_i{1} [@O] ''   3
 | | |   |<TensorType(float64, matrix)> [@F]
 | | |InplaceDimShuffle{1,0} [@P] ''   2
 | |   |<TensorType(float64, matrix)> [@F]
 | |Subtensor{:int64:} [@C] ''   1
 |Constant{10} [@E]
```

Can you test in your real use case if that do it for you? I'm pretty sure
it would work.

See also:
http://deeplearning.net/software/theano/tutorial/faq_tutorial.html?highlight=embedding#how-to-update-a-subset-of-weights

[1] http://deeplearning.net/software/theano/tutorial/printing_drawing.html

**Comment by hycis** [comment]
Hi Fred you are right, using your code below only takes 0.217s compare to 30s when updating the full matrix. Here when using 1/1000 of the rows in w, the speed up is from 43s to 0.217s, about 200x speedup, which is much faster than 30s.
```python
import theano.tensor as T
import theano
import numpy as np
w = theano.shared(np.random.rand(10000,1000))
x = T.matrix()
w_ = w[:10]
y = T.dot(w_,x).sum()
dydw = T.grad(y, w_)
f = theano.function([x], y,
                    updates=[(w, theano.tensor.set_subtensor(w_, dydw *
w_))])
for i in range(1000):
    f(np.random.rand(1000,10))
```

**Comment by nouiz** [comment]
I'm closing this issue as it seem solved from your answer.
