### ISSUE TITLE
Speed up 2 scan opt

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3346]
PushOutSeqScan and PushOutNonSeqScan.

Don't go over the toposort.

Create a dequeue object and init it with local_fgraph.inputs.

When you move one node outside, append its client to that dequeue. This will make that optimization just check the start of the inner fgraph and not all of it. It should make this faster.

**Comment by carriepl** [comment]
Closing the issue for now since it was tried but didn't really give any speed improvement and other things have been done to reduce the time spent in these two optimizations.
