### ISSUE TITLE
downsample.max_pool_2d only accepts int argument

### ISSUE THREAD

**Issue by hycis** [Theano/Theano#3349]
Currently downsample.max_pool_2d only accepts int argument for ds and st parameters. However it will be better if it can also accept tensor variable, for example in spatial pyramid pooling, the st and ds changes when the input image size changes.

```python
        b, c, h, w = X.shape  # tensor variable
        layer_out = []
        for i in [1,2,4]:
            out = downsample.max_pool_2d(state_below, ds=(h/i, w/i),
                                         st=(h/i, w/i),
                                         ignore_border=self.ignore_border,
                                         mode=self.mode)

            out = out.reshape((b, T.prod(out.shape)/b))
            layer_out.append(out)
```
here we get the error that max_pool_2d only takes integer value for ds and st. I think it will be better for ds and st to accept both integer and tensor variable so the max_pool_2d can change on the fly in the computation graph, if theano thinks this is useful, i can work on a pull request

**Comment by nouiz** [comment]
I opened another ticket gh-3386 about this. I forgot about this one. I worked on the GPU implementation, but I won't work on the CPU. If you can work on this and make a PR, that would be great.

https://github.com/Theano/Theano/pull/3387

**Comment by hycis** [comment]
Sure, I will be happy to work on the the cpu version.

**Comment by nouiz** [comment]
thanks.

I started this on the GPU:

https://github.com/Theano/Theano/pull/3387

Just in case this help you.

**Comment by hycis** [comment]
@nouiz I see that the gpu is not merged yet? was trying to use the gpu downsample version but still has the error it's only accepting int as input?

**Comment by nouiz** [comment]
Just an update. The support on GPU is merged already.

**Comment by nouiz** [comment]
Here some instruction for someone wanting to implement this:

and rename the method c_code() of the op theano.tensor.signal.pool.Pool to disable the c code and first make it work with only python code.
- Read the tutorial about making Theano op: http://deeplearning.net/software/theano/extending/
- I would focus first on the python version, so disable the C code by renaming the method c_code() to something like c_code_()
- You must make the properties that are passed when instantiating the op be passed during execution. So the \__init__ method will have less parameter and make_node will have more parameter.
- Make sure to update the grad method and the grad op to also support that.
- Implement a test in the file tensor/signal/tests/test_pool.py that use the dinamic version of it.
- When all that work, enable the c code again and you can update it to take the parameter as extra input.

Make the new parameter to make_node() in that order: ws(windows size), stride, pad to follow the same interface as done by the gpu back-end.

**Comment by nouiz** [comment]
Just to let know that this is done.

**Comment by hycis** [comment]
Awesome, thanks fred!
