### ISSUE TITLE
Takes 25 seconds to run first theano.shared when using GPU if opencv 3 is imported

### ISSUE THREAD

**Issue by Newmu** [Theano/Theano#3351]
``` python
import theano
import numpy as np
s = theano.shared(np.ones((1, 1)).astype('float32'))
```

Runs in about a thousandth of a second.

``` python
import cv2
import theano
import numpy as np
s = theano.shared(np.ones((1, 1)).astype('float32'))
```

Takes about 25 seconds. Every shared variable made after the first is then approximately normal speed. Ran cProfile and the time ends up being in `cuda_ndarray.cuda_ndarray.filter`

**Comment by nouiz** [comment]
If you import theano before cv2, do this change something?

This could be related to the GPU context/init.

Can you confirm that you have the flag device=gpu?

**Comment by Newmu** [comment]
> If you import theano before cv2, do this change something?
Import order does not change the time it takes

> Can you confirm that you have the flag device=gpu?
Yep! Standard print out of `Using gpu device 0: GeForce GTX 980 (CNMeM is disabled)` occurs when the program is run.

**Comment by nouiz** [comment]
I'm puzled by this. @abergeron do you have an idea what could cause this?

We won't spend much time on this as we are pretty busy, but I'm curious.

@Newmu do you know how opencv handle GPU context?

**Comment by Newmu** [comment]
Sorry, not aware enough. No worries, I'd wait to see if someone else encounters this since opencv 3 usage is still pretty low still!

**Comment by lamblin** [comment]
Closing because I'm not sure what to do about it, and I don't know if it would affect the new back-end.
