### ISSUE TITLE
Create less Scan nodes in ScanInplaceOptimizer

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#3353]
The current implementation of the optimization goes over every recurrent state of the Scan and, for each, attempts to replace the original with a new Scan that operates inplace over the input associated with that recurrent state.

To lessen this issue, some validation should be included before attempting to create any new Scan in that optimization to attempt to avoid many cases where the replacement will be rejected and a new Scan will have been created for nothing.

Also, since in a large number of cases it should be possible for a Scan to be inplace over all the inputs associated with its recurrent states, the optimization could start by attempting to create a replacement Scan that would be inplace on all of them and only go over the recurrent states one by one if that inplace Scan is rejected.

**Comment by nouiz** [comment]
@carriepl is there stuff left for that issue or we can close it?

**Comment by carriepl** [comment]
@nouiz Both of the improvements mentionned in this ticket have been implemented and merged. We can close the issue.
