### ISSUE TITLE
Support more than one experiment in multinomial sampling on CPU

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#3359]
This involves :
* Adapting the Python code
* Adapting the C code
* Adding tests for this new feature
* Update the opt that move it to the GPU to not move it if n != 1.

**Comment by bouthilx** [comment]
@carriepl Are you referring to something else than ```theano.raw_random.multinomial```? Because we can do multiple draws using ```theano.shared_randomstreams.RandomStreams().multinomial(size=(n_draws,))``` and multiple experiments using ```theano.shared_randomstreams.RandomStreams().multinomial(n=n_experiments)```.

**Comment by bouthilx** [comment]
Oh, I guess you meant theano.random.multinomial. 

from ```theano.sandbox.rng_mrg.MRG_RandomStreams.multinomial``` docstring:
> Sample `n` (currently `n` needs to be 1) times from a multinomial distribution defined by probabilities pvals.

**Comment by bouthilx** [comment]
### The plan

To add multiple experiments functionality to ```theano.sandbox.multinomial.MultinomialFromUniform```, we will add an argument ```n``` to ```perform``` method. The uniformly distributed random input (```unis```) is currently a vector of shape ```pvals.shape[0]``` where each ```unis[i]``` is sampled from ```uniform(pvals[i])```. It will be turned into a matrix of size ```(pvals.shape[0], n)``` where each ```unis[i,:]``` is sampled from ```uniform(pvals[i], size=n)```. 

We can directly infer ```n``` from ```unis```'s shape, but having ```n``` as an argument of ```make_node``` makes it possible to double check that ```unis```'s shape is conform to user's intention. @carriepl Do you believe this double-check is useless?

### Progression checklist
* [ ] 1. Adapt MultinomialFromUniform.make_node to add new argument ```n```. Test that ```unis.ndim``` == 2. The new functionality should be tested with ```n>0``` and bad values (```n<=0```).  The equality ```unis.shape[1] == n``` will be tested in ```perform``` and ```c_code``` at step 2 and 3 respectively. 

* [ ] 2. Adapt and test MultinomialFromUniform.perform to accumulate every experiments in ```unis[i, :]``` . Raise an error if ```unis.shape[1] != n```.

* [ ] 3.  Adapt and test MultinomialFromUniform.c_code similarly to perform. Raise an error if ```unis.shape[1] != n```. (practical hint: change ```c_code_cache_version()``` to return ```None``` to be sure theano compiles the c code every time you run your tests. Increment that previous value when you are ready to push)

* [ ] 4. Adapt and test the interface and the documentation of ```theano.sandbox.rng_mrg.MRG_RandomStream```

* [ ] 5. Modify the optimization function that transfers MultinomialFromUniform to GPU et test that transfers only occur in the right situations and vice versa.

### Note

The implementation does not support multiple experiments nor multiple draws. This ticket only addresses multiple experiments.
