### ISSUE TITLE
More elemwise optimization

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3370]
gh-3173 follow up

We should remove the elemwise in those cases:
-        f = theano.function([x], T.le(x, x), mode=mode)
-        assert_eqs_const(f.maker.fgraph.toposort(), 1)

idem for ge.

**Comment by lamblin** [comment]
This case seems to be handled. In any case, there is no elemwise in the graph in that case:
```python
>>> theano.printing.debugprint(theano.function([x], T.le(x, x)))
DeepCopyOp [id A] ''   0
 |TensorConstant{True} [id B]
```
