### ISSUE TITLE
Can the optimization to use DnnSoftmaxGrad be enabled again because cuDNN v.3 was released?

### ISSUE THREAD

**Issue by avostryakov** [Theano/Theano#3371]
This commit disabled the optimization to use DnnSoftmaxGrad:
https://github.com/Theano/Theano/commit/9783d9a94ab70bdae8bce1a739420d72c0f2bc05

Because cuDNN v.3 was released recently may be you can enable the optimization.

**Comment by avostryakov** [comment]
I checked cuDNN v.3 production and it looks like DnnSoftmaxGrad is working correctly now.

**Comment by nouiz** [comment]
This is in a pr to Theano. See github comment to this issue to find out.
