### ISSUE TITLE
Serious bug causes wrong computations in Keras, etc.

### ISSUE THREAD

**Issue by the-moliver** [Theano/Theano#3377]
Starting with this commit https://github.com/Theano/Theano/commit/41a8e89b63f5b4d4f9a0b942554ed5483e1ceab5 the training of various kinds of neural nets, and I presume other computations, is broken. I don't know the Theano codebase well enough to diagnose the exact cause, but I tracked it down to this commit. This issue has been confirmed by others here:
https://github.com/fchollet/keras/issues/664

**Comment by nouiz** [comment]
Quick reply, I'm working on it.

**Comment by the-moliver** [comment]
Thanks for the quick work!
