### ISSUE TITLE
Dynamic k-pooling

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3386]
[[lasagne-users] Dynamic K-max pooling](https://groups.google.com/d/topic/lasagne-users/f1z-mYiu2lI/discussion)

There is a paper that need that. To quickly support it in Theano, someone could do it just for cudnn. For this:
- [x] Modify the class theano.sandbox.cuda.dnn.GpuDnnPoolDesc to take the parameter as inputs and not as attribute (this will also cause less compilation).
- [x] Modify dnn_pool to make sure it support that.
- [x] Test it.

To complete this, we need to:
- [x] Make the CPU code also support this. gh-3349
- [x] Update the optimization to support this.
- [x] Port this to the new gpu back-end. gh-4053

**Comment by nouiz** [comment]
This is completly done to my knowledge.

**Comment by boyangli** [comment]
Can anyone provide some example code showing how to use Dynamic K-max pooling?

Thanks a lot!

**Comment by nouiz** [comment]
Just pass a symbolic scalar variable as the pooling windows size. Something
like

pool_size = theano.tensor.scalar()

pool_2d(..., ws=(pool_size, pool_size))

**Comment by boyangli** [comment]
Sorry. I think I still don't understand. I need to select the top-k max values instead of the top max value out of the pooling window. How do I do that with GPU support?

I would appreciate if you could provide a more complete code snippet.

**Comment by nouiz** [comment]
Just to be sure, this issue is about having a pooling size that is change at each Theano function call. A more complete example:
```
import theano
from theano.tensor.signal.pool import pool_2d
x=theano.tensor.dmatrix()
pool_sizes=theano.tensor.ivector()
o=pool_2d(x, ws=pool_sizes)
f=theano.function([x,pool_sizes], o)
import numpy
f(numpy.random.rand(4,4), [2, 2])
f(numpy.random.rand(6,6), [3, 3])
```

**Comment by boyangli** [comment]
It appears to me that there is a misunderstanding. I was reading the original post in Google Groups, which says:

> With K-max pooling, you select the k-max values of 1 row of values.
> With dynamic k-max pooling, the value of k depends on the input shape.
> The idea is that longer sentences can have more max values (higher k).

So I thought this was meant to address that problem. Now I see that's not the case.
