### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by Kaixhin** [Theano/Theano#3388]
I've created [CPU-backend](https://hub.docker.com/r/kaixhin/theano/) and [CUDA-backend](https://hub.docker.com/r/kaixhin/cuda-theano/) (v6.5, v7.0 and v7.5) Docker images for Theano. They may be worth adding to the [installation docs](http://www.deeplearning.net/software/theano/install.html#install) as an alternative for Ubuntu (like [Torch7](https://github.com/torch/torch7/wiki/Cheatsheet#docker-images) or [neon](http://neon.nervanasys.com/docs/0.9.0/installation.html#docker-images)).

**Comment by nouiz** [comment]
Do you want to make a PR to Theano that add that information?
