### ISSUE TITLE
Website documentation out of date?

### ISSUE THREAD

**Issue by danielrenshaw** [Theano/Theano#3391]
The documentation at http://deeplearning.net/software/theano/library/floatX.html includes a References section that says

floatX.xscalar(name=None)
Alias for either dscalar() or fscalar()
floatX.xvector(name=None)
Alias for either dvector() or fvector()
floatX.xmatrix(name=None)
Alias for either dmatrix() or fmatrix()
floatX.xrow(name=None)
Alias for either drow() or frow()
floatX.xcol(name=None)
Alias for either dcol() or fcol()
floatX.xtensor3(name=None)
Alias for either dtensor3() or ftensor3()
floatX.xtensor4(name=None)
Alias for either dtensor4() or ftensor4()
floatX.set_floatX(dtype=config.floatX)
Reset the xscalar(), ... xtensor4() aliases to return Variables with given dtype. This is called at import-time when setting floatX in THEANO_FLAGS.

But none of these aliases appear to exist. Is this outdated documentation?

Discussed on theano-users: https://groups.google.com/forum/#!topic/theano-users/h-lfKTfpYrw

**Comment by danielrenshaw** [comment]
Could this be caused by the documentation deployment procedure? Maybe files are copied, overwriting old pages with newer versions but leaving deleted pages untouched?

**Comment by nouiz** [comment]
I think you found the problem. This commit removed that file:

2b9bcf22136efa3ade4b947db59512d15108580e

I removed it and a few others at the same time.

Thanks
