### ISSUE TITLE
Rewrite Reshape.infer_shape and fix TestInferShape for flatten()

### ISSUE THREAD

**Issue by bouthilx** [Theano/Theano#3420]
[Reshape.infer_shape](https://github.com/bouthilx/Theano/blob/sparse_block_dot/theano/tensor/basic.py#L4018-L4066) is using Shape_i() which is adding a Reshape operation and makes [TestInferShape](https://github.com/bouthilx/Theano/blob/sparse_block_dot/theano/tensor/tests/test_basic.py#L6942-L6961) fail. It is not necessary to use Shape_i(), and the method should be rewritten to support -1 values in the new shape dimensions of Reshape.

There is two main cases

1. new shape dimensions are all constant
    1. new shape dimensions contain at most one -1
    2. new shape dimensions are all positive
2. new shape dimensions contain symbolic variables (switch is necessary)

For -1 dimensions, the value is inferred from the length of the array and remaining dimensions.

```newshape[i] == -1 ? prod(all inputs dim)/prod(all newshape dim but i) : newshape[i]```

**Comment by SinaHonari** [comment]
Reading the code and the description above, the only part that is I see is not following the description is in case 2, where
a switch should be used. Is there any other part in infer_shape that is problematic?

The above description tells how Shape_i should be working, but I'm not sure if it also tells which part of it is problematic? The support for case 1 to support -1 is already there.

**Comment by bouthilx** [comment]
Yes, Shape_i is used in case 2. It seems case 1 is already implemented properly except for l.4050 as it fails for scalars. 

There should be no Shape_i in ```infer_shape``` methods at all otherwise it reinserts the op in the shape graph. Case 2 should be implemented using a switch on ```node.inputs``` and ```ishapes``` only (not ```node.outputs```).

**Comment by SinaHonari** [comment]
OK, in l.4050 when there is an scalar, [-1] should be returned or an empty list []?

**Comment by bouthilx** [comment]
I  it would be ```[]``` but it seems to raised errors in #3480 so I'm not sure. We would need to investigate to understand what caused the errors. You can either start with this or by implementing cases 2 properly.

**Comment by SinaHonari** [comment]
I'm using the following for case 2, but I get tuple index out of range error:

return [tuple([switch(eq(node.inputs[1][i], -1),
	                                  ishapes[0][i], node.inputs[1][i])
 	                           for i in xrange(self.ndim)])]

**Comment by SinaHonari** [comment]
ishapes[0][i] apparently does not hold the right content.
It failing for test_basic.T_reshape
where ishape has this content
[(Shape_i{0}.0, Shape_i{1}.0), (TensorConstant{3},)]
and self.ndim=3

**Comment by bouthilx** [comment]
ndim of ishapes[0] is not equal to self.ndim (where self is Reshape). 

The code doesn't seems to be correct. The shape at a given axis ```i``` should be something like 

```new_shape[i] == -1 ? prod(all input_shape)/prod(all new_shape but i) : new_shape[i]```

What you do is more like

```new_shape[i] == -1 ? input_shape[i] : new_shape[i]```

**Comment by SinaHonari** [comment]
I updated the code. I make a PR.

**Comment by SinaHonari** [comment]
I discussed with Pascal Lamblin. 
There is an issue in test_basic.py:T_reshape.test_bad_shape
where it wants to test some bad input shapes. In current formulation, the test assumes that infer_shape should check for bad_shapes, while it is no longer happening and therefore infer_shape returns the new (bad) shape. Either the test should be removed, or a check should be added in infer_shape, which makes the optimization more complicated/slower/etc. Pascal wasn't sure which approach is the best, and probably you should discuss it together to get to a conclusion.

**Comment by bouthilx** [comment]
OK, thanks for the update. I'll let you know when there is anything new.

**Comment by SinaHonari** [comment]
No problem.

**Comment by lamblin** [comment]
Fixed by #3643.
