### ISSUE TITLE
More local_fill_to_alloc just after the canonicolize EQ

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3423]
Add in the EQ local_useless_fill.

This should help make the opt more consistent between similar graph. It should help speed up.

Need to check that it don't slow down computation and all tests pass.

**Comment by Shashi456** [comment]
Can Someone suggest how i can go about doing this ?

**Comment by nouiz** [comment]
This is done. Now we do a full pass after the canonicalize phase as this issue asked. So closing.

Why did you wanted to work on this?

**Comment by Shashi456** [comment]
I was looking at issues to work on and I found this through code triage , if you can direct me to tell other issues it would be helpful

**Comment by nouiz** [comment]
Look for issue marked as "easy fix". Also make sure to see this annoucement
before starting. Just that you know what to expect:
https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ
