### ISSUE TITLE
Try to use pypy for optimization

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3424]
We could use a separate process running with pypy to run Theano optimizer to speed it up.

pypy don't play nice with c code module, so running this in a separate process could solve that problem.

Doing a quick test would be great to see if we get enough speed up.. Pypy have its own reimplementation of numpy.

**Comment by EderSantana** [comment]
@nouiz have you thought about JIT with numba? wouldn't Pypy require a separate Python install?

**Comment by nouiz** [comment]
numba is for numerical computation. There is an example to reuse to have
faster Op with only python c.

http://deeplearning.net/software/theano/extending/other_ops.html?highlight=numba#numba-ops

But it can't help during the optimization, as this is generic python code
(function call, conditions, ...)

Do you have other information? I didn't use much Numba, so I could be wrong.

**Comment by EderSantana** [comment]
On that same subject, PyPy updated their C-API http://morepypy.blogspot.ch/2016/02/c-api-support-update.html

Yeah, Numba for sure helps the most if you are running for loops and iterating through arrays. But I thought the optimization required here would be pretty much it. 

A third idea would be to implement a few slow functions in cython. Which is the approach people are taking in spaCy, the nlp library.

As a final word. Could you please, give more information about Theano's optimization module, where it is and how to profile it? I believe this may help outsiders to take a closer look and see where we can help.

**Comment by elanmart** [comment]
> As a final word. Could you please, give more information about Theano's optimization module, where it is and how to profile it? I believe this may help outsiders to take a closer look and see where we can help.

+1

**Comment by nouiz** [comment]
Doc for optimization is in a few files. Go in this page:

http://deeplearning.net/software/theano/extending/index.html#extending

and grep for "opt", you will find those pages/sections.

If you want to help and also help yourself at the same time, I think the
best approch is to profile the optimizer in your code and we can see which
optimization is needed in your case. To profile that, see
http://deeplearning.net/software/theano/extending/optimization.html#profiling-theano-function-compilation

Most of the time, we need to adjust the algorythm to make it faster.
Sometimes, this is implementation detail like how we do the comparison that
will help.

**Comment by EderSantana** [comment]
Thanks! @nouiz I'll check it out!

**Comment by GSam** [comment]
In trying to find an ML library to work on pypy, I figured out some hacks to get it working (at least superficially with runtime compiled cpyext modules). 

There seems to be a few problems that need to be resolved before it would work out of the box:

1. A single usage of the ctypes.pythonapi.PyCapsule_Type

2. A single usage of sys.getrefcount (to check that there isn't leaks)

3. Missing build information to runtime load the compiled .so python module
- The correct binary .so filename looks to be able to be constructed using distutils.sysconfig.get_config_var("SO") (or EXT_SUFFIX in python3)
- Expects libpython.so (or equivalent) in the distutils.sysconfig.get_config_var("LIBDIR") location
- distutils.sysconfig.get_config_var("LDLIBRARY") does not resolve in pypy currently -- but should in theory point to libpypy-c

The hacks I've done (for a specific version of pypy2) are in a branch here:
https://github.com/GSam/Theano/tree/pypy-hack

**Comment by nouiz** [comment]
Hi, I just wanted to make sure you saw this:

https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ

1. Disabling it cause the GPU back-end to not work I think. But for a first version, this is good. I just wanted to make clear the consequence of this.
2. We have only 2 such call. But they are there just to assert we do not change the refcount. So a quick hack is to just comment them. Could we wrap that function call in a python function and call it indirectly? If that work, it would be a quick work around that could get merged in Theano.
3. Theano was started a very long time ago. This part of the code did not got a big overhaul since the original version. I do not remember why we didn't used disutils for everything, but I think we tried and at the time, it was not able to do exactly what we wanted.

I looked at your branch. I think small change would allow us to merge it in the master of Theano. As it is simple, I can take the time to review it. Are you interested to finish this? If so, can you make a PR of you branch? I is much easier to talk about there in a PR then in an issue.

**Comment by GSam** [comment]
I have seen the notice, it doesn't bother me, I'm just really looking for a good ML library to experiment with a bit. I haven't the foggiest how to fix CNTK to work with pypy which I looked briefly at, nor does Tensorflow have any chance without modifying SWIG (and their auto-generated bindings) it seems.

I do have some interest in getting this done properly. I'll see what I can do.
https://github.com/Theano/Theano/pull/6574

**Comment by GSam** [comment]
https://github.com/Theano/Theano/pull/6574 is merged now. This issue can probably be closed. It would be interesting to do some benchmarks of whether or not PyPy causes any noticeable performance improvement, but that kind of depends on how much actual Python code Theano is running (and whether or not the overheads from PyPy's cpyext offset that in any meaningful way). In the latter case, it's not really Theano's problem anyways. PyPy numpy performance is still a bit off, but as long as Theano is only using it as an intermediary, it shouldn't be that bad.

**Comment by nouiz** [comment]
Theano use python code to compile a model, but mostly C code for the execution phase. So the execution phase should not get significant speed different. But compile time could see good speed up.

I'll keep this issue open, in case someone take the time to benchmark the compilation time of Theano for a function that is slow to compile normally (more then 1m for example).

**Comment by juancamilog** [comment]
Do you have any guide on how to benchmark it? I have some code that creates big graphs, which take between 1 and 3 minutes to compile.

**Comment by nouiz** [comment]
Those should be good benchmark. Take the longest one (3m). I'm closing this as we won't work on it. But if you bench it, I would be interrested to see the results.
