### ISSUE TITLE
Can the output of a layer be treated as the index of another layer's output?

### ISSUE THREAD

**Issue by NancyZxll** [Theano/Theano#3427]
Dear all,
     I would like to use the output of a layer as the index of another layer's output.
    Such as:
```
inputs = [self.layers[i].get_output(train) for i in range(len(self.layers))] 
aa=inputs[1]
index=T.cast(inputs[0],'int64')
return aa[index]
```
Actually, the inputs[0] is the return value of the layer, which:
```
return T.nonzero(inputs0,axis=0)
```

I get the error:
TypeError: AdvancedSubtensor1.grad illegally  returned an integer-valued variable. (Input index 0, dtype int64)

I have upgraded my theano to the developing version.
If I don't cast the inputs[0] to int manually, the error would be: "index must be integers".

How can I solve this problem?

Thanks a LOT!!

**Comment by cooijmanstim** [comment]
You can use theano.gradient.disconnected_grad() to prevent theano from trying to backpropagate through the indexing, e.g. "return theano.gradient.disconnected_grad(aa[index])".

I presume you would like the layer to learn which element to select.  Note that the output of the subtensor is piecewise constant with respect to the index.  There is no gradient to follow, so you couldn't train this with e.g. gradient descent.

**Comment by nouiz** [comment]
I'll close this issue as the last answer seem to answer your questions.

**Comment by NancyZxll** [comment]
@cooijmanstim Yes, this is exactly what I want to do. As you said, I should find another way to do this. Thanks a lot!

**Comment by NancyZxll** [comment]
@nouiz Ok, thanks.
