### ISSUE TITLE
Python with statement, use it

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3429]
We should modify Theano to use it isntead of the old python 2.4 syntax now.

Which grep statement would help for that?

**Comment by piotrfrankowski** [comment]
Hi,
If you have installed pcregrep (pcre package), you can use command:
```find -name "*.py" | xargs pcregrep --color="auto" --buffer-size=1000k -M "try:[A-Za-z0-9\t ,./~\!\@\#\$%\^&\*\(\)\-=_+\[\]{};:\'\"\\|\n]*?finally:"``` 
I'm working on option "doesn't contain 'except' betweet 'try' and 'finally'".

**Comment by nouiz** [comment]
Thanks for working on this.
Le 29 sept. 2015 15:11, "Piotr Frankowski" <notifications@github.com> a
écrit :

**Comment by piotrfrankowski** [comment]
Hi,
Have you started working on this refactoring? Maybe I can start contributing to Theano?

**Comment by nouiz** [comment]
You are the only one working on this. It would be a good first contribution!

Just to help on getting the pr merged, don't make it to big and try to
split it in reasonable sized commit. The otherwise the review is more
complicated and this could need rebase and other related changes.

Thanks
Le 30 sept. 2015 14:50, "Piotr Frankowski" <notifications@github.com> a
écrit :

**Comment by piotrfrankowski** [comment]
Commit per file would be ok?

**Comment by piotrfrankowski** [comment]
Ok, I've started refactoring. First of all, I'm searching for
```
<variable> = open(<args>)
<do something with variable>
<variable>.close()
```
But I found some examples:
```
try:
     open(<some file>, 'w').close()
except Exception as e:
```
Should I refactor it?

**Comment by nouiz** [comment]
Refactor it if this make the code more clear. If not, it isn't useful.

**Comment by lamblin** [comment]
Done in #3478.
