### ISSUE TITLE
Move ProfileMode Hint to the new profiler

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3431]
Useful for user and would clean up code by removing old "if 0" ed code.
- [x] Add hint feature to new profiler (#3870)
- [ ] Clean-up the part in "if 0:"

**Comment by lamblin** [comment]
So, the deprecated [`ProfileMode`](https://github.com/Theano/Theano/blob/master/theano/compile/profilemode.py#L112) had a feature printing some hints or tips for the user when some cases were detected, for instance:
- using amdlibm for faster elemwise operations
- setting floatX=float32
- when dot product between one float32 and one float64 matrix are computed (not optimized to use gemm)

That code starts at https://github.com/Theano/Theano/blob/master/theano/compile/profilemode.py#L607, there is another commented-out version at https://github.com/Theano/Theano/blob/master/theano/compile/profiling.py#L1307

Now, we use the regular `Mode`, but print a profile when `theano.config.profile == True`. However, we are missing the hints. This is the last thing preventing the complete removal of `ProfileMode`.

So, this ticket is about moving that code from `ProfileMode` to `theano.compile.profiling`, maybe in a new method `ProfileStats.print_tips()`, that would be called at the end of `ProfileStats.summary()`.
When this is done, the commented-out code in `profiling.py` can be removed.

**Comment by Saizheng** [comment]
https://github.com/Theano/Theano/pull/3870

**Comment by nouiz** [comment]
done by https://github.com/Theano/Theano/pull/3870
