### ISSUE TITLE
Deprecation warning for tensor.stack

### ISSUE THREAD

**Issue by eulerreich** [Theano/Theano#3446]
In [the doc](http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor.stack), the deprecation for `stack(*tensors)` is placed under the entry for `stack(tensors, axis=0)`, which is unclear whether there is a typo and `stack(tensors, axis=0)` is deprecated, or `stack(*tensors)` is deprecated but the warning is misplaced. I'm guessing it's the second one.

**Comment by bouthilx** [comment]
Thank you for pointing that out! You are right that it's the second one. The example of stack(tensors, axis=0) is also incomplete. I will fix this.
