### ISSUE TITLE
Inconsistent shape between max_pool_2d and DownsampleFactorMax

### ISSUE THREAD

**Issue by diogo149** [Theano/Theano#3452]
Not sure how serious this specific issue is, since it's unlikely that this would actually happen (it just failed a test case). (:

```
import theano
import theano.tensor as T
from theano.tensor.signal.downsample import max_pool_2d, DownsampleFactorMax

input_shape = (3, 4, 1, 1)
kwargs = dict(
    ds=(2, 3),
    st=(2, 2),
    ignore_border=True,
    padding=(0, 0),
)
print(DownsampleFactorMax.out_shape(
    imgshape=input_shape,
    **kwargs
))
print(max_pool_2d(T.zeros(input_shape), **kwargs).shape.eval())
```

**Comment by diogo149** [comment]
Specifically, `DownsampleFactorMax.out_shape` returns `[3, 4, 0, 0]`, while `max_pool_2d().shape` return `[3, 4, 1, 1]`.

**Comment by nouiz** [comment]
Thanks for the report. This happen only when the input of the DownsampleFactorMax is broadcastable in one or both of the inner dimensions.

It is fixed in this PR:

https://github.com/Theano/Theano/pull/3477
