### ISSUE TITLE
Fibby example code (or exposition) out of date?

### ISSUE THREAD

**Issue by eulerreich** [Theano/Theano#3458]
In the second paragraph of [fibby](http://deeplearning.net/software/theano/extending/fibby.html) under the code example, it says

"The first two methods in the Op are relatively boilerplate: `__eq__` and `__hash__`."

But these two functions don't appear in the code.

**Comment by nouiz** [comment]
@abergeron @carriepl I let one of you fix this. It need some doc rewriting and you are better then me on this.

**Comment by lamblin** [comment]
This appears to have been fixed.
