### ISSUE TITLE
TypeError: transfer_type{0} with keras MLP sample code 

### ISSUE THREAD

**Issue by mmmikael** [Theano/Theano#3463]
A simple [MLP example (keras)](https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py) gives the following exception twice with bleeding-edge Theano:
```
ERROR (theano.gof.opt): SeqOptimizer apply inplace_elemwise_optimizer
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/mikael/Dev/Theano/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/mikael/Dev/Theano/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/mikael/Dev/Theano/theano/tensor/opt.py", line 404, in inplace_elemwise_optimizer
    for i in xrange(len(node.outputs))]))
  File "/home/mikael/Dev/Theano/theano/scalar/basic.py", line 1998, in __init__
    raise TypeError(o_type)
TypeError: transfer_type{0}
```
Even with these exceptions, the example still seems to run fine but it does not give any error message with Theano 0.7.

(My GPU: GeForce GTX TITAN X)

**Comment by nouiz** [comment]
Can you give me the git commit that have the problem? I'm not able to reproduce it here with:

 python examples/mnist_mlp.py 

I also tryed on the GPU.

**Comment by nouiz** [comment]
I used a new clone of keras for this.

**Comment by nouiz** [comment]
@lamblin make a PR that we merged that should fix this: https://github.com/Theano/Theano/pull/3470

Can you update Theano and confirm that it fix it for you?

**Comment by mmmikael** [comment]
(sorry for the late answer, I just for access to that computer.)

That fixes the problem. Thanks!
