### ISSUE TITLE
Theano exception on exit

### ISSUE THREAD

**Issue by sordonia** [Theano/Theano#3469]
Hi,

for any Theano script, i.e.:

a = theano.shared(value=numpy.array([1]))
b = a + 1

when the program exits, I get:

Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in <bound method DefaultOrderedDict.__del__ of DefaultOrderedDict()> ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored
Exception AttributeError: "'NoneType' object has no attribute 'clear'" in  ignored

I am using the last Theano commit, numpy-1.9.3 on Linux (fedora)

Thanks

**Comment by nouiz** [comment]
Do you use the default mode? Do you change the default flags? if so, which
one do you use? Is this with python 2 or 3? Do you enable the gpu?

In the file: theano/gof/utils.py there is a method clear. Can you test by
adding an "if self.__dict__:" before calling the other clear method?

**Comment by sordonia** [comment]
i just use the default mode, no change in default flags. python 2.7, no gpu.
Your proposed add doesn't seem to resolve the issue.

thanks,

**Comment by sordonia** [comment]
I found the broken import:

Just do an empty file, test.py:

import theno.sandbox.cuda

then python test.py

Thanks!

**Comment by nouiz** [comment]
There was such an error in the past. It is fixed in the dev version of
Theano. Update to it:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Fred

**Comment by sordonia** [comment]
Thanks!

**Comment by sordonia** [comment]
Thanks !
