### ISSUE TITLE
Document (and possibly optimize) compilation flags

### ISSUE THREAD

**Issue by delallea** [Theano/Theano#347]
Çağlar Gülçehre reported on the mailing list compilation flags that can boost performance on the CPU:
http://groups.google.com/group/theano-users/browse_thread/thread/0f7045ae8233ae37/17c6828139298050
It would be good to have such information in the documentation.

Even better: add a way to automatically optimize compilation flags to minimize execution time of a given Theano function.

**Comment by nouiz** [comment]
native is done by default in a good way. The other one are documented.
