### ISSUE TITLE
tensor.pow fails with negative numbers on GPU

### ISSUE THREAD

**Issue by adbrebs** [Theano/Theano#3496]
``` python
import theano
import theano.tensor as T

x = T.fscalar('x')
f = theano.function([x], x**4)
print f(-1.)
```
This returns nan on GPU (but works well on cpu).

**Comment by nouiz** [comment]
It return 1 for me on my config. Which OS do you use? Which cuda version do
you use?

**Comment by adbrebs** [comment]
Cuda V7.0.27
on bart2 with a Titan
stack v3

**Comment by nouiz** [comment]
I'm not able to reproduce it on that computer with that setup. So this isn't a problem in Theano or a bug in nvcc 7.0. So I'll close this ticket. Can you try again today? If yous still have a problem with this, come see me as it seem to be a problem just for your account.

**Comment by adbrebs** [comment]
Ok thanks Fred, I will come and see you tomorrow.

**Comment by adbrebs** [comment]
In my .theanorc, fastmath was set to True. Setting it back to False (default) solved the problem.
