### ISSUE TITLE
Extend nervana gemm to floa32 and enable it by default

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3497]
This would speed up computation as it is faster then cublas gemm.

It currently only support float16

**Comment by Sandy4321** [comment]
is it possible to see code example pls

**Comment by nouiz** [comment]
This isn't trivial. Are you good at C code and ready to read much code to
understand it? There isn't a good guideline for this issue. Here is a high
level one:

- Use the new GPU back-end and implement it there.
- Extend the op Gemm16 in the file theano/sandbox/gpuarray/nerv.py to
support float32 gemm from nervana. This will ask you to understand how
nervana code can be called.

**Comment by nouiz** [comment]
We don't use it anymore as now float16 storage and computation are in cublas, so closing.
