### ISSUE TITLE
numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by sdustwdd** [Theano/Theano#3501]
When I run my program ,the issue as follow:

c:\Anaconda\lib\site-packages\theano-0.7.0-py2.7.egg\theano\gof\cmodule.py:327: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  rval = __import__(module_name, {}, {}, [module_name])

**Comment by nouiz** [comment]
This is a know "problem". The detail are a little bit complicated, but in conclusion you can ignore it.

To fix this, it is cython that need changes, not Theano.

I added filter for those warning in that PR:

https://github.com/Theano/Theano/pull/3477

**Comment by nouiz** [comment]
We merged the fix that hide the warning.
