### ISSUE TITLE
dnn_pool padding documentation is wrong

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3503]
> **pad** – (padX, padY) padding information. padX is the size of the left and right borders, padY is the size of the top and bottom borders.

But this is clearly not the case:

```
In [42]: from theano.sandbox.cuda.dnn import dnn_pool

In [43]: from theano.tensor import tensor4

In [44]: a = tensor4()

In [45]: q = dnn_pool(a, (2, 2), stride=(2, 2), pad=(4, 1))

In [46]: image = numpy.random.normal(size=(128, 3, 32, 32)).astype('float32')

In [47]: numpy.array(f(image)).shape
Out[47]: (128, 3, 20, 17)
```

**Comment by nouiz** [comment]
Your input have shape 128,3,32,32. With padding 4,1, this give
128,3,32+2*4,32+2*1 = 128,3,40,34.

With a non overlaping pooling of 2,2, the should is really 128,3,20,17.

What did you expected? We take the value and pad by that number of each
side. How can you write the more clearly?

On Wed, Oct 7, 2015 at 3:51 PM, David Warde-Farley <notifications@github.com

**Comment by abergeron** [comment]
The problem isn't the result (which is correct), but the documentation which seems to imply the inverse (or maybe not it's confusing to me).

We should fix it to be clearer.

**Comment by dwf** [comment]
Yes, in addition, it wasn't clearer whether this was total padding or per-side padding. I've submitted #3504 which tries to address both of these things.
