### ISSUE TITLE
How to convert TensorVariable Object into numpy ???

### ISSUE THREAD

**Issue by nitish11** [Theano/Theano#3505]
I want to  do something reverse of  <a href="https://theano.readthedocs.org/en/rel-0.6rc3/library/tensor/basic.html#tensor.as_tensor_variable"> this link </a>.

What is difference between a tensor object and TensorVariable?

**Comment by abergeron** [comment]
This is not always possible since a TensorVariable is symbolic, not numeric so it may not have a numeric value associated.

Also, this is a question for the theano-users mailing list, not as issue.

**Comment by nouiz** [comment]
In short, you need to compile a Theano function and execute it. This will
generate an ndarray. There is a shortcut that you can use if you use it
only once:

var.eval()

if you need to use it more then once, compile a real Theano function. That
will be faster in the long run.

**Comment by nitish11** [comment]
@abergeron  : thanks for the reply. 
@nouiz  : For my give use case :
```
('type(y_pred) :', <class 'theano.tensor.var.TensorVariable'>)
('y_pred :', AdvancedSubtensor1.0)
('y_pred[0] :', Subtensor{int64}.0)
('y_pred_shape :', Shape.0)
('y_pred_ndim :', 2)
('y_pred_dtype :', 'float64')
```

When I used <i>("y_pred_eval:",y_pred.eval())</i>, I am getting the below error.
```
theano.gof.fg.MissingInputError: ("An input of the graph, used to compute ConvOp{('imshp', (None, None, None)),('kshp', (None, None)),('nkern', None),('bsize', None),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (None, None, None)),('kshp_logical', (None, None)),('kshp_logical_top_aligned', True)}(cards_input, conv1_p0), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", cards_input)
```

**Comment by nouiz** [comment]
Here is an example of how to use eval correctly:

http://deeplearning.net/software/theano/tutorial/adding.html?highlight=eval

**Comment by lombardata** [comment]
khkb
