### ISSUE TITLE
Merge cuda batched gemm and faster version for big size

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3512]
In https://github.com/Theano/Theano/pull/1698/files#diff-43102a08f907f49ba6fbb467e08e04d8

we have another implementation of batched gemm that is faster for big matrices.

This ticket is about:

1) merging that in the batched gemm from cublas. Have a parameter that default to 128, if that size of smaller, use the cublas version, if bigger, use the other implementation. Do some speed tests to make sure 128 is the right number. This could change depending of cuda version. Test at least with 7.90 and 7.5.

**Comment by cooijmanstim** [comment]
Should I create a procedure `CudaNdarray_block_gemm` in `cuda_ndarray.cu` like Razvan did or should I put the logic inside `GpuBatchedDot`?

@abergeron

**Comment by nouiz** [comment]
It don't need to be in cuda_ndarray.cu. Just do the simplest.

**Comment by lamblin** [comment]
Is adding that to the new back-end part of this ticket, or should we create a different one?

**Comment by abergeron** [comment]
There is no GpuBatchedDot in the new backend, and the way blas binding is handled is different, so I would consider that a new ticket.
