### ISSUE TITLE
Usage of printf %zd on Visual Studio 2013 and earlier

### ISSUE THREAD

**Issue by wuaalb** [Theano/Theano#3514]
The file `cuda_ndarray.cu` uses `fprintf(stderr, ...)` with the `%zd` format specifier in several places to display error messages related to memory allocations.

Unfortunately `%z` isn't supported on Visual Studio 2013 and earlier, and causes those and subsequent values not to be printed properly. E.g. messages look something like this on my machine 
```
Error allocating zd bytes of device memory (gßf=-ÇB>ñ+F+L!_+Pt+=x?n;+ p+çM&?¦+ZÇ
'+ëëZ+¦q~=Vë?+¦s++ß?=+HU-+áë(;?=
=?¦<+n+?+å1++Y`1+»-P+t÷?=Üb-++¦à+æ
*E+·Öí+(M?+F=X=?}¶>?¦ÿ+,e). Driver report zd bytes free and zd bytes total
```

The corresponding format specifier would be `%I` (i.e. `%Id` or `%Iu`). Visual Studio 2015 is supposed to support `%z`, but last time I checked it was not yet supported by Cuda Toolkit.

Maybe one solution could be to add a helper function which converts the numerical value in bytes to a more human readable string in bytes, kilobytes, megabytes, gigabytes, .., depending on the value's magnitude and just use `%s` in the final message.

**Comment by nouiz** [comment]
@abergeron, do we have the same problem in the new gpu back-end?

I like the idea to add the size in a more readable format, but I think we
should keep the exact size. It is useful sometimes.

I think a simpler fix that is used at some place would be to use:

%lld

and cast the value to (long long)

%llu is also used.

Do you want to make that change? It would be a good contribution.

thanks

**Comment by abergeron** [comment]
Yes, I had the same problem.  I fixed it by making a macro called SIZE_PREFIX that would be either "z" or "I" depending on the platform.

The other approach of using %ll[du] is also fine, but requires casts to make sure it works correctly on 32-bit platforms.
