### ISSUE TITLE
dyld warning when using the GPU

### ISSUE THREAD

**Issue by changkun** [Theano/Theano#3518]
I try to following this [page](http://deeplearning.net/software/theano/tutorial/using_gpu.html) to using GPU computation.
but I got this warning in my computer:
``` bash
➜  ~/Desktop  THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python test-cuda.py
dyld: warning, LC_RPATH @executable_path/ in /usr/local/cuda/lib/libcublas.7.5.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/ in /usr/local/cuda/lib/libcublas.7.5.dylib being ignored in restricted program because of @executable_path
Using gpu device 0: GeForce GT 750M
[GpuElemwise{exp,no_inplace}(<CudaNdarrayType(float32, vector)>), HostFromGpu(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.820002 seconds
Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
  1.62323296]
Used the gpu
```
Theano works well basically, but what is the warning about dyld warning? And how to fix it? 

Here is my environment:
``` bash
➜  ~/Desktop  python
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
>>> print theano.__version__
0.7.0
>>> exit()
➜  ~/Desktop  clang -v
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
➜  ~/Desktop  nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Thu_Sep_24_00:26:39_CDT_2015
Cuda compilation tools, release 7.5, V7.5.19
```

**Comment by abergeron** [comment]
How were you able to use cuda 7.5 and Xcode 7?  This isn't supported by nvidia, nor by us.

**Comment by changkun** [comment]
@abergeron No,no,no, I downloaded CUDA 7.5 from [NVIDIA](https://developer.nvidia.com/cuda-downloads) yesterday and there's an option that I can choose OSX 10.11. I tested all the samples and it combines with Xcode 7 without any build error but this warning only come from Theano when I try to using the GPU.

**Comment by abergeron** [comment]
Oh ok, they released a quick update to make it work with clang 7.  I'll have to look into this at some point then, but I don't have the time right now.

If the test suite passes, I would say that it's not a problem for now, though.
