### ISSUE TITLE
downsample.max_pool_2d - average() only among nonzero values

### ISSUE THREAD

**Issue by tjurczyk** [Theano/Theano#3525]
Hi all,

I'm trying to make one change required for my project, but I can't figure out how Theano handles max_pool_2d function. My NNet package (Keras) calls max_pool_2d as a Pooling function and I'm trying to modify it in such a way that the average will be taken only among nonzero values (e.g.: [[1,2,3], [0,0,0], [0,0,0]] will give 2.0, not 2/3). In numpy this change is easy, I created a simple method in downsample.py:

```
def mean_nonzero(a):
    return numpy.mean(a[numpy.nonzero(a)])
```

which works fine. Now, in the class ```DownsampleFactorMax``` I tried to modify the ```def perform(self, node, inp, out)``` fragment which sets an appropriate numpy function:

```
        if self.mode == 'sum':
            func = numpy.sum
        elif self.mode != 'max':
            #func = numpy.average
            func = mean_nonzero
```

this is not working unfortunately. I tried to debug it, but it seems that method ```perform``` is never called. Am I trying to do this from the right way? Thanks for any help.

**Comment by nouiz** [comment]
This have been answered on the theano-user mailing list:

[max_pool_2d in downsample - average on non-zero values only](https://groups.google.com/forum/embed/#!topic/theano-users/H4F-zGSTPrk)
