### ISSUE TITLE
T.mean doesn't work on a list, T.sum does

### ISSUE THREAD

**Issue by capybaralet** [Theano/Theano#3527]
See this example:

In [16]: ll = [theano.shared(0.), theano.shared(2.)]

In [17]: T.sum(ll).eval()
Out[17]: array(2.0)

In [18]: T.mean(ll).eval()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-749479f94476> in <module>()
----> 1 T.mean(ll).eval()

/u/kruegerd/repo/Theano/theano/tensor/basic.pyc in mean(input, axis, dtype, op, keepdims, acc_dtype)
   3000 
   3001     # float16 overflows way too fast for sum
-> 3002     if ((sum_dtype == 'float16' or input.dtype == 'float16') and
   3003             acc_dtype != 'float16'):
   3004         sum_dtype == 'float32'

AttributeError: 'list' object has no attribute 'dtype'

**Comment by nouiz** [comment]
It is quick to fix:

https://github.com/Theano/Theano/pull/3528
