### ISSUE TITLE
theano.test() fails and also outputs some weird warnings

### ISSUE THREAD

**Issue by ssampang** [Theano/Theano#3529]
Hi guys,

My overall goal has been to get a version of Nathan Sprague's deep_q_rl code working. This didn't work, and I've posted about that issue [here](https://github.com/Lasagne/Lasagne/issues/469). In my attempts at troubleshooting, I've discovered that theano.test() fails. Since the log is really long, I just copied it over to this [gist](https://gist.github.com/ssampang/20fcc0261e9ef389412e). Apart from the errors themselves, I noticed repeated warnings of the following type:
```/home/sid/.local/lib/python2.7/site-packages/theano/tensor/nnet/tests/test_conv.py:98: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  ref_output = numpy.zeros(out_shape)```
After some googling, I couldnt find anyone else with similar warnings, so I thought I'd post here. Are these ok? Does this mean that some tests are returning NaN when they shouldnt be?

Finally, almost all the failed tests (all located near the end of the log) seem to have something to do with d3 visualization and a file not existing. Could this be a permissions issue? The one outlier is a GradientError. 

Any help - both with this and the overall goal of running deep_q_rl - would be greatly appreciated!

Thanks,
Sid

**Comment by nouiz** [comment]
The DeprecationWarning are du to numpy 1.10 being more strict. I fixed some
of them.

For now, forget the d3vis error. I also think I fixed some of the. So an
update of Theano should help you.

Have you been able to run the code? Otherwise, what is your problem?

On Sun, Oct 18, 2015 at 8:59 PM, Siddarth Sampangi <notifications@github.com

**Comment by zer0n** [comment]
I run into the same issue and I'm using the latest version of Theano (via `git clone`).

Here're the warnings (many of them)

```
C:\src\Theano\theano\tensor\nnet\tests\test_corr.py:99: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
```

**Comment by ssampang** [comment]
I think it was a combination of multiple problems involving CUDA suddenly not working for some reason (even though it was working before), and both theano and lasagne not being installed with the correct permissions. . The code works now.
