### ISSUE TITLE
Custom loss layer in theano

### ISSUE THREAD

**Issue by bluechill52** [Theano/Theano#3541]
Hi, where do you write a custom loss layer in theano ? Also, where are the other loss layers defined ? I guess you need to define the forward and backward functions somewhere. Thanks in advance.

**Comment by JesseLivezey** [comment]
You'll probably get more responses if you ask in the theano-users google group.

**Comment by nouiz** [comment]
User questions are better asked on theano-user mailing list as Jesse wrote.

Most of the time, you don't need to define new layers in Theano. All our component are small enough and reusable. Theano will automatically optimize this for many cases and compute the grad for them.

if you need to extend Theano, there is a tutorial here: http://deeplearning.net/software/theano/tutorial/extending_theano.html

But I would suggest you to check the Deep Learning Tutorial, it show how to use Theano with machine learning example: http://deeplearning.net/tutorial/

You will see there that there is no need for new layers.
