### ISSUE TITLE
downsample.max_pool_2d is slow when ds!= st

### ISSUE THREAD

**Issue by nidleo** [Theano/Theano#3542]
I'm running a computation composed of many layers. One of them is downsample.max_pool_2d.
If I set ds=(3,3), st=(2,2), it runs x2 slower compared to ds=(2,2), st(2,2). The pooling op should not be the bottleneck.

What could be causing this? I'm running on a GPU, is there no GPU implementation for the case ds!=st?

**Comment by nouiz** [comment]
It seem we missed this questions. User questions are better on the theano-user mailing list. More people see it.

On the GPU, with cudnn, we all all the CPU poolling operation including ds != st. But without cudnn, we only support ds==st.

I'm closing this as it is an old question. We tried to make this more clear in the doc.

I made an issue to have our profiler add tip when cudnn isn't there and this cause some computation on the CPU: https://github.com/Theano/Theano/issues/4102

If you still have questions/comments, don't hesitate to reply here.
