### ISSUE TITLE
unrecognized command line option -m64 on ARM 64-bit processors

### ISSUE THREAD

**Issue by moslemk** [Theano/Theano#3543]
On ARMv8 (i.e., ARM64) processors platform.machine() returns 'aarch64'. Hence, the check in theano/gof/cmodule.py line 2016:

https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L2016

will not fail and and the '-m64' will be added to the compile list of options which in turn results in a "g++: unrecognized command line option -m64" during the compile time.

**Comment by moslemk** [comment]
Here the PR fix: https://github.com/Theano/Theano/pull/3544

**Comment by lamblin** [comment]
Fixed by #3544.
