### ISSUE TITLE
IndexError: One of the index value is out of bound. Error code: 2147483647

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#3561]
Running the exact same code that used to work with 557fe6fab49262706241f0e774f3269a2ec0275b with latest version of theano 4736c9b3d459a7b0c88bb14c4dd789fe4d09d9b3 I have the following error:
>Traceback (most recent call last):
  File "/u/visin/.miniconda/envs/arctic/lib/python2.7/site-packages/ipdb/__main__.py", line 157, in main
    pdb._runscript(mainpyfile)
  File "/u/visin/.miniconda/envs/arctic/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/u/visin/.miniconda/envs/arctic/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "evaluate_horses39.py", line 1, in <module>
    from recseg import train
  File "evaluate_horses39.py", line 40, in main
    do_random_invert_color=False)
  File "recseg.py", line 857, in train
    cost = f_grad_shared(x, y)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/data/lisa/exp/visin/theano/arctic/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/data/lisa/exp/visin/theano/arctic/theano/gof/op.py", line 865, in rval
    r = p(n, [x[0] for x in i], o)
  File "/data/lisa/exp/visin/theano/arctic/theano/sandbox/cuda/basic_ops.py", line 2759, in perform
    self.max_threads)
IndexError: One of the index value is out of bound. Error code: 2147483647.\n
Apply node that caused the error: GpuAdvancedSubtensor1(GpuFlatten{1}.0, Elemwise{Composite{((i0 * i1) + i2)}}[(0, 1)].0)
Toposort index: 1452
Inputs types: [CudaNdarrayType(float32, vector), TensorType(int64, vector)]
Inputs shapes: [(111936,), (55968,)]
Inputs strides: [(1,), (8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuReshape{2}(GpuAdvancedSubtensor1.0, MakeVector{dtype='int64'}.0), GpuElemwise{Composite{((-i0) / i1)},no_inplace}(GpuReshape{1}.0, GpuAdvancedSubtensor1.0)]]

I am sorry I cannot be more detailed at the moment. I am trying to git-bisect it but it will take some time.

**Comment by fvisin** [comment]
ed1fca7a3f188a71edf375272a3596c3292fc2c2 is the first bad commit.
Let me know if I can provide more information or help somehow.

**Comment by nouiz** [comment]
Can you run with the env variable CUDA_LAUNCH_BLOCKING=1

Otherwise, the error can be not the right one as computation on the GPU are
async.

I'm very surprised that this is the first bad commit. It don,t do anything
related to that error message. Do you use cnmem? If you stop using it, do
it still fail?

**Comment by fvisin** [comment]
Hey Fred, sorry I edited my message but I should have written a new one. It is actually not the right commit. As I didn't make sense I checked my git bisect and it was actually failing in some cases but for different errors. I am now trying to git-bisect again making sure to track the right error. Sorry about that, I'll keep you posted and when I am done I'll try to run the bad commit with CUDA_LAUNCH_BLOCKING=1.

**Comment by fvisin** [comment]
Between 221fb064de2c9a0 and 8e88a29288fc3b7 I always get this other error, so I have to bisect-skip:
>Traceback (most recent call last):
  File "evaluate_horses39.py", line 64, in <module>
    'use_fullsize_images': False})
  File "evaluate_horses39.py", line 40, in main
    do_random_invert_color=False)
  File "/data/lisa/exp/visin/arctic/recseg/recseg.py", line 857, in train
    cost = f_grad_shared(x, y)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 618, in __call__
    storage_map=self.fn.storage_map)
  File "/data/lisa/exp/visin/theano/arctic/theano/gof/link.py", line 297, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 607, in __call__
    outputs = self.fn()
RuntimeError: Cuda error: k_elemwise_unary_rowmajor_copy: an illegal memory access was encountered. (n_blocks=4096, n_threads_per_block=256)
>
>Apply node that caused the error: GpuReshape{3}(GpuDimShuffle{1,0,2}.0, MakeVector{dtype='int64'}.0)
Toposort index: 1973
Inputs types: [CudaNdarrayType(float32, 3D), TensorType(int64, vector)]
Inputs shapes: [(53, 66, 10400), (3,)]
Inputs strides: [(10400, 551200, 1), (8,)]
Inputs values: ['not shown', array([    1,  3498, 10400])]
Outputs clients: [[GpuElemwise{Add}[(0, 0)](GpuReshape{3}.0, GpuReshape{3}.0)]]


This is the output of the git-bisect:
>There are only 'skip'ped commits left to test.                                                        
>
>The first bad commit could be any of:
75241083945e8078208d444083a102e3caf4fa9c
8da3449a7329ae7a1998f03afbf33348914a4622
df61d3b01eed210f9626319656a44fc26dca92cc
45adc6e0a3f20de21b15f88cdb6e9f62142c37e9
8cb9d50ee1205728eb2feb5419c099de9afb3814
4d4be31647bfea2ecc370e2dc1354116de82cc90
fd1e668bd0f7c3074ed8b6b7e8397796b0ef27ef
434ac0251dd9ead62a6aa9c38e0b1dd290704490
91f713511784c4a69fa2e452785a6257e916ff73
e94e34bc9a9b325aed08cefa28aecf92bbed3fa9
d36faf2311ec3c6089c3e4996dfa42db6c1fecdf
fc1d6686642dbebbca4f637d4a371e827d2ec186
adbcbfc23f240517ebf06a64bcd73396e9e964e1
d4d3ae5b531870f6fe0721c229c27ef73ae4dc2f
397394d6f352a0a50dd557c9d638f202cd041859
6e221a6e6aace3fb534363744918ced5c4077216
9839a0025bd77cef25aed391cf78303a59be8af1
f2e2a7bece69df234aa20a1e6e11004c87bc3b9b
fc1ed89732245700f92bcd57d3270d1fa380c450
c4df0b99b4b082a93349ca49ceffadfe12e7f6a8
51a26add3ee8a185e863fb33cf7645e4c40d296c
a5fe8e38b9a28d621f4446781ec61d6cba59b6ad
349378f1d2e476b8b9bd4b89654655a1d2bb45bd
8b640d34aebd3e545e937a0317f045b2a1c1f5c9
de787b0c63964e6f2c8ed178f866f54c3ce2ad38
e6a86a015d66c6e280edcd830ca0f3d254344721
32ad87b4f4fddd022e67dd558b205537f39afe16
ecf4a8ab53e4cd86f791d6f1cb5460c5eadf5e41
4850f926b611cf589e08fcfe05ba09f958c94c4d
814ae6a1924678ee4a584d9858c4eed95bc7c46e
8aa3dc1dcfa436f1f14d9a07f16bd64712c98e11
689ce21a3d6b0c65de93fd75665962749886ac79
191de4eba98458017c4f5fb7696f33d27d304cf7
2445d58c45a6ea518c892dd866a9abd44aa4d7ef
557c3fd3a00e4a503b1d4e5208bd3fcd8295948c
8bcd3264f55fbbc0e4a8f3a02a22a293a5f6631a
0efc781fe943b51446df6f6bd94cc89841962d38
178ad156f6905e1508af161c4b8473aec77008ba
2b6ef54e8a294779b2f6a205b366e273fe5cbdc9
72b8b163086cca050b406d7a2701251439c44423
01a4a9e69ec6cf76ab786c26481105e48a2141da
6f80c3bec3ba55899aff0280c4bd0c746d68da18
222899031e72a0910e9165b0ddd07656c2ec6217
5e6820a60e24ac0bc83d6ad0c6a11fd2d227f59d
10f2615fc94e6cfea58dae0532239deb8a634758
c586d80b886db0014657a4cbaca13fe9cf9300d0
14b81781acccf90198a18ec647f464959aa57e3c
15c90dd36c95ea2989a2c0085399147d15a6a477
319cf6213138023b1dbadb365d991104e2edee9d
3f0f841e7a9be8c025aab91c5e36bfba4beaa321
44518ac8cd2252eb10d8f33d8e10ca5219119ac1
e0eaa3974174d0449f58f5fddc199b3d0f297e8a
02c218fa875104618282b41481e0302f9bb37352
28f72bb5aa0aaa97ebb41805b059cdde43c2ae92
d27f23981fa3091d32d4d6fe87b35d375116f277
d740f88e79d517ef90f7d4bab07247993e3a5287
2389c49091a6d2d8a57d7c2d23e444cbcd5bb4cf
5f2c912690ab7e943bff64d8932ae6fb181ba33f
8c7ab0922f3c374b85fe1fbbd0e1b57e27d5ab13
9de861618979d9e4e0b6fe5bc1eb65d08dc60074
682385f7d68ebf1d4411dfcd0d93c87a520a849e
891998079fe97d0c3039f25704c6fd56256a356f
680d2034e8134d9a7fcfb071dd808e9ee4c760ac
b2f62a1e18a68817a6f54e39e922d2d3511c2a72
05dc20de0c2fb985fb49b64e9abce4b9d32138e2
5381bbdaf48d05823489464953f50bee84b6503d
079181cf9e503d61cb9cd830ddc87c81b01fbc6b
564cd12b3fb1817f314f4821e964d3ce13dbdce2
929628de883bcfd80878d897421c0ea95e061900
56bb06ebd2f0c2f801dd965e22ff40aeb29e600e
We cannot bisect more!

Finally, this is the traceback with CUDA_LAUNCH_BLOCKING=1:
>Traceback (most recent call last):
  File "evaluate_horses39.py", line 64, in <module>
    'use_fullsize_images': False})
  File "evaluate_horses39.py", line 40, in main
    do_random_invert_color=False)
  File "/data/lisa/exp/visin/arctic/recseg/recseg.py", line 857, in train
    cost = f_grad_shared(x, y)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/data/lisa/exp/visin/theano/arctic/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/data/lisa/exp/visin/theano/arctic/theano/gof/op.py", line 865, in rval
    r = p(n, [x[0] for x in i], o)
  File "/data/lisa/exp/visin/theano/arctic/theano/sandbox/cuda/basic_ops.py", line 2759, in perform
    self.max_threads)
IndexError: One of the index value is out of bound. Error code: 2147483647.\n
Apply node that caused the error: GpuAdvancedSubtensor1(GpuFlatten{1}.0, Elemwise{Composite{((i0 * i1) + i2)}}[(0, 1)].0)
Toposort index: 1452
Inputs types: [CudaNdarrayType(float32, vector), TensorType(int64, vector)]
Inputs shapes: [(111936,), (55968,)]
Inputs strides: [(1,), (8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuReshape{2}(GpuAdvancedSubtensor1.0, MakeVector{dtype='int64'}.0), GpuElemwise{Composite{((-i0) / i1)},no_inplace}(GpuReshape{1}.0, GpuAdvancedSubtensor1.0)]]

**Comment by fvisin** [comment]
@lamblin The mistery gets deeper!! 
I got into the breakpoint we set and called take manually several times at each iteration. I don't get any error on the first image, but I still get an *after init_err_var* error message when I call `take` for the first time on the second image. 

I looked into the index again and made sure that the min is zero and the max is not greater than the size of x. Everything is fine. Then I ran `take` a second time. And it succeeded. No error. Several times.

**Comment by fvisin** [comment]
Of course no error at all with cuda-memcheck, even at the second run on the second image..
```python
In [7]: f(x[0:1], y[0:1])
init_err_var was fine
TAKE SUCCEDED
init_err_var was fine
TAKE SUCCEDED
Out[7]: array(nan)

In [8]: f(x[1:2], y[1:2])
init_err_var was fine
TAKE SUCCEDED
```
The `nan` might be an optimization problem. That still doesn't explain why when we ran my code (directly the code, with no pickling-unpickling) it was not `nan`. Let's ignore it for now though.

The only finding so far are (always with `CUDA_LAUNCH_BLOCKING=1`):
- running the pickled function on leto06 (where X is using the TitanX) with memcheck we get a `cudaErrorLaunchTimeout`
- running on eos3 (exclusive use of the TitanX) we don't. 
- running without memcheck on leto06 we got `Cuda error: k_elemwise_unary_rowmajor_copy: an illegal memory access was encountered.`
- running without memcheck we got the `IndexError: One of the index value is out of bound. Error code: 2147483647` that seems to be an error flag set somewhere else when computing the gradient and somehow detected only at the next forward pass.

BTW, to disable the kernel watchdog see here:
http://http.download.nvidia.com/XFree86/Linux-x86/270.41.06/README/xconfigoptions.html#Interactive

**Comment by nouiz** [comment]
This error: cudaErrorLaunchTimeout

this happen on which node? Maybe we can speed up that node.

**Comment by lamblin** [comment]
It happens on GpuReshape, but only when using cuda-memcheck.

**Comment by lamblin** [comment]
@fvisin Could you try without memcheck, on eos3, _without cnmem_? Then maybe with memcheck, without cnmem? I'm wondering if something strange could be happening because of cnmem...

**Comment by fvisin** [comment]
I tried: 
- without memcheck, without cnmem: no error
- with memcheck, without cnmem: no error
just to be sure I checked again with memcheck, with cnmem.....and obviously no error!

The theano version is the same as before, the function and the data are pickled so they didn't change...all the tests are run with `CUDA_LAUNCH_BLOCKING=1`

**Comment by nouiz** [comment]
Can you give me a way to reproduce this?

**Comment by fvisin** [comment]
Sure. If you access `/u/visin/pascal` you can find `f_grad_shared.pkl`, `y.pkl` `x.pkl`.
Usage: 
```python
import cPickle as pkl
f = pkl.load(open("f_grad_shared.pkl", "r"))
x = pkl.load(open("x.pkl", "r"))
y = pkl.load(open("y.pkl", "r"))
f(x[0:1], y[0:1])
```

**Comment by fvisin** [comment]
I got the `Cuda error: k_elemwise_unary_rowmajor_copy: an illegal memory access was encountered.` error again on `GpuReshape{4}(GpuElemwise{Add}[(0, 0)].0, MakeVector{dtype='int64'}.0)`.
This is on a new model (the function has been renamed but is the same), that is much smaller than the previous one:
```python
Traceback (most recent call last):
  File "/u/visin/.miniconda/envs/arctic/lib/python2.7/site-packages/ipdb/__main__.py", line 157, in main
    pdb._runscript(mainpyfile)
  File "/u/visin/.miniconda/envs/arctic/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/u/visin/.miniconda/envs/arctic/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "evaluate_horses44.py", line 1, in <module>
    from recseg import train
  File "evaluate_horses44.py", line 35, in main
    do_random_invert_color=False,
  File "recseg.py", line 580, in train
    cost = f_grads_optimized(x, y)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/data/lisa/exp/visin/theano/arctic/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/data/lisa/exp/visin/theano/arctic/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
RuntimeError: Cuda error: k_elemwise_unary_rowmajor_copy: an illegal memory access was encountered. (n_blocks=4096, n_threads_per_block=256)

Apply node that caused the error: GpuReshape{4}(GpuElemwise{Add}[(0, 0)].0, MakeVector{dtype='int64'}.0)
Toposort index: 1978
Inputs types: [CudaNdarrayType(float32, 3D), TensorType(int64, vector)]
Inputs shapes: [(140, 127, 600), (4,)]
Inputs strides: [(600, 84000, 1), (8,)]
Inputs values: ['not shown', array([  1, 140, 127, 600])]
Outputs clients: [[GpuDimShuffle{0,2,1,3}(GpuReshape{4}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations ca
n be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
```

I tried to pickle it, as it would be much faster to use it for test, but I can't: 
```*** RuntimeError: error (an illegal memory access was encountered)copying data to host```

**Comment by fvisin** [comment]
The previous experiment failed at the very beginning.
I am running the same experiment as before without cnmem and I didn't get any error so far.
To be sure, I ran the same exact experiment with cnmem on a different machine, and I didn't get errors again. It might have to do with the fact that on leto06 X is running on the same GPU I am using, or it might be just depend on a mix of conditions.

Let me know if I can do anything to help. If I can run experiments for the ICML deadline it is not a big problem, but it seems to be triggered at random and that leads to random failures of the experiments.

**Comment by fvisin** [comment]
[List of trials](https://docs.google.com/spreadsheets/d/1wzqymQ2WlfwmuFkcYesDd_YhsvSnx-vUaIn8EGAUE_8/edit?usp=sharing)

**Comment by fvisin** [comment]
I couldn't reproduce this issue after some time and I have moved to another version of the code now, so I will close this issue. Should I face the same problem again I will reopen it.
