### ISSUE TITLE
Scan infer_shape()

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#3566]
For Scan nodes that are not used as 'while' loops, the infer_shape() method of the Scan class should be able to infer the shapes of the outer outputs based only on the shapes of the outer inputs in most cases, which is not the case right now.

**Comment by carriepl** [comment]
Addendum : many of the recent issues with unoptimized scan nodes being introduced in the graph are related to this issue. The cause is a combination of the scan_op.infer_shape() method not correctly infering the shapes of the outputs, and the ShapeFeature class sometimes keeping outdated information about the shapes of various variables.

**Comment by nouiz** [comment]
Small correction. Scan infer shape do not give wrong result. It just
frequently don't infer that shape and this combined with the other point
cause this problem.

**Comment by carriepl** [comment]
Closed by #3580
