### ISSUE TITLE
Assert to never reintroduce Apply node in fgraph.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3573]
Some optimization call replace_validate_remove.

I think we should tag the node to remove with a tag like node.tag.never_reuse=True. Then in FunctionGraph, when we add an apply node in the graph, we check that it don't have that tag.

That way we can be sure to not reintroduce by mistake some node.

Should we also do that for local optimizer on the original node if after substitution, it isn't in the fgraph anymore?

**Comment by carriepl** [comment]
How costly would it be to do it every time a local optimizer requests a substitution?
Even if it ends up being too costly to do it for local optimizers, it would probably still have benefits to do it only in the cases or replace_validate_remove()

**Comment by nouiz** [comment]
What about when we remove a node from fgraph, we alsays tag it as not to
reintroduce, until we start to do inplace optimization? Before inplace opt,
we shouldn't revert change in the graph I think. After that, some revert
could reintroduce it. Could we allow to reintroduce only for revert?

**Comment by Sentient07** [comment]
@nouiz , is this ticket open, shall i take it ?

**Comment by nouiz** [comment]
It is open. It need to investigate in the core of Theano. It isn't very well documented, so not the most trivial. But if you are able to investiage unknow code, you can take it.

Mostly, go in the file theano/gof/fg.py, then find __remove_clients__

**Comment by Sentient07** [comment]
@nouiz So, i'd need to create a new variable in the class ```FunctionGraph```(probably a list) that contains the information of all the removed nodes (from ```__remove_clients__``` method) and prevent them from getting added to the graph from inside the ```__import__``` method, right ?

**Comment by Sentient07** [comment]
@nouiz Also, according to your initial comment, I should use a variable ```never_reuse``` to check if apply nodes could be added back to graph, right ?

**Comment by Sentient07** [comment]
@nouiz Ping

**Comment by nouiz** [comment]
I think this is good. It is possible that this is too strict and cause
problems. I don't think so, but I just want to let you know about this. If
this end up being too strict this can be done in a less strict way.

thanks

**Comment by Sentient07** [comment]
@nouiz , I've a question. While adding back ```apply_nodes``` that has once been removed, do i need to add the output and input of that node to the variable ? (This is a slight confusion I'm having as to how nodes and variables go in hand..)
P.S: This issue seems challenging and interesting! :)

**Comment by nouiz** [comment]
This is in the core of Theano, so it is normal that this isn't as clear as
the user interface. I suggest that you revisit this page that help
understand the link between apply node and variable:

http://deeplearning.net/software/theano/tutorial/symbolic_graphs.html

So mostly, it is the apply node that must not be reintroduced in the graph.
Not the variable.

On Tue, Feb 2, 2016 at 2:03 PM, Ramana Subramanyam <notifications@github.com

**Comment by Sentient07** [comment]
@nouiz Yeah, had read that, will read through again. Also, node.tag.never_reuse must be Apply's attribute and should be set as true by default, right ?

**Comment by nouiz** [comment]
By default, I would set this attribute to not exist. And set it to False
when needed. So if it don't exist, it is equivalent to True.

On Wed, Feb 3, 2016 at 2:07 PM, Ramana Subramanyam <notifications@github.com

**Comment by Sentient07** [comment]
Yeah, so first i'll test it without that variable and with that variable. As of now, i'm getting some errors when I had applied the filter of not allowing a used apply_node into graph.

**Comment by nouiz** [comment]
Can you give an example of those error? Just in case we can't go it
generally for some reason I don't foresee. Maybe we can do it only for call
to replace_all_validate_remove() and not all replacement.

On Thu, Feb 4, 2016 at 5:18 PM, Ramana Subramanyam <notifications@github.com

**Comment by AnishShah** [comment]
This can be closed now?

**Comment by nouiz** [comment]
yes. thanks.
