### ISSUE TITLE
inc_subtensor of column vector

### ISSUE THREAD

**Issue by traversc** [Theano/Theano#3575]
Trying to set a column vector using inc_subtensor gives an error.  E.g.:

The following code attempts to set the first two columns in a matrix and works fine:

```
import numpy, theano 
import theano.tensor as T
mat = theano.shared(numpy.zeros((10,10)))
temp = numpy.asarray(range(20))
temp.shape = (10,2)
mat_inc = theano.shared(temp)
mat = T.inc_subtensor(mat[:,[0,1]], mat_inc)
print mat.eval()
```

The following code attempts to set the first one columns in a matrix, but returns an error:

```
import numpy, theano
import theano.tensor as T
mat = theano.shared(numpy.zeros((10,10)))
temp = numpy.asarray(range(20))
temp.shape = (10,1)
mat_inc = theano.shared(temp)
mat = T.inc_subtensor(mat[:,[0]], mat_inc)
print mat.eval()
```

The following code works as expected, but isn't as general.  I'd like to use the above approach, but if I don't know which columns I want to set beforehand, it causes a problem.  

```
import numpy, theano
import theano.tensor as T
mat = theano.shared(numpy.zeros((10,10)))
temp = numpy.asarray(range(10))
mat_inc = theano.shared(temp)
mat = T.inc_subtensor(mat[:,0], mat_inc)
print mat.eval()
```

**Comment by nouiz** [comment]
There is a mistake in your second code snippet. I think you wanted to give this code:

```import numpy, theano
import theano.tensor as T
mat = theano.shared(numpy.zeros((10,10)))
#temp = numpy.asarray(range(20))
temp = numpy.asarray(range(10))
temp.shape = (10,1)
mat_inc = theano.shared(temp)
mat = T.inc_subtensor(mat[:,[0]], mat_inc)
print mat.eval()
```

This will fail with the error you probably had. I tried quickly to fix it, but today I need to work on other stuff.

**Comment by traversc** [comment]
Thanks, that is what I meant. 

On a side note, I had previously been trying to update a subset of the weight matrix, but it seems that subtensor calls are expensive computationally.  I'm still trying to wrap my head around theano and make sure I do things properly, but what are some common applications for the subtensor function?

**Comment by nouiz** [comment]
This will probably help you make the partial update efficient:

http://deeplearning.net/software/theano/tutorial/faq_tutorial.html?highlight=inc_subtensor#how-to-update-a-subset-of-weights

**Comment by nouiz** [comment]
The fix would be to not do reshape/dimshuffle when we build the graph to use AdvancedSubtensor1 instead of AdvancedSubtensor. Now, on the CPU we support the full AdvancedSubtensor. We need to profile it we need to make a graph optimization to do the conversion.

If we do this change before  we implement AdvancedSubtensor on the GPU, we will need an optimization, otherwise, we need to time which version is faster.

**Comment by nouiz** [comment]
I don't think we have time for the 0.9 release, so I bump that to 0.10 release.

This advanced, in the new back-end, we have GpuAdvancedSubtensor, we started working on GpuAdvancedIncSubtensor.

**Comment by lamblin** [comment]
I just tried that code, and the issue now seems different now, it has to do with unexpected broadcasting patterns in DimShuffle.
