### ISSUE TITLE
Unify shape inference for convolutions

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3582]
We should have one implementation of shape inference for each type of convolution Op, I think it belongs in `theano/tensor/nnet/abstract_conv2d`.
Then, each implementation of the Conv operators, including the abstract one, should implement `infer_shape`.
Currently, we have such computation for CorrMM, DNN conv ops, the legacy CPU Conv Op, and GpuCorrMM.

**Comment by lamblin** [comment]
Closed by #3644.

**Comment by lamblin** [comment]
Still missing for DNN conv ops in the old back-end.

**Comment by lamblin** [comment]
Should we also deprecate the static `get_out_shape` in `GpuDnnConv` Ops, and call `get_conv_output_shape` directly [here](https://github.com/laurent-dinh/Theano/blob/conv_infer_shape/theano/sandbox/cuda/dnn.py#L1151-L1153), [here](https://github.com/laurent-dinh/Theano/blob/conv_infer_shape/theano/sandbox/cuda/dnn.py#L1234-L1236), and [here](https://github.com/laurent-dinh/Theano/blob/conv_infer_shape/theano/sandbox/gpuarray/dnn.py#L815-L817)?

**Comment by nouiz** [comment]
I think so.

**Comment by nouiz** [comment]
@lamblin should we close this issue?

**Comment by lamblin** [comment]
Yes, I think we're done.
