### ISSUE TITLE
dimshuffle a variable and assign back to itself

### ISSUE THREAD

**Issue by xunhuang1995** [Theano/Theano#3584]
Here is a simple code:

import numpy as np
import theano.tensor as T
X = T.tensor3()
X = X.dimshuffle((2,1,0))
Y = X
f = theano.function([X],Y)
x = np.random.rand(2,3,4)
y=f(x)
print(x.shape)
print(y.shape)

In my computer, y has the same shape as x. So the dimshuffle function has no effect. If I use P = X.dimshuffle((2,1,0)), and Y = P, the y will have shape (4,3,2), which is what dimshuffle should do. Any idea about why "X = X.dimshuffle((2,1,0))" has no effect?

**Comment by benanne** [comment]
You are passing `X` to `theano.function` to represent the input after you have already changed it. It is not referencing the original `X` because you overwrote it with something else.

**Comment by xunhuang1995** [comment]
Yeah, I see. Thank you!
