### ISSUE TITLE
pooling implementation in max_pool_2d should warn for cases where there's no GPU implementation

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3591]
I might not have wasted my time with it if I had realized it would quadruple my training time.

**Comment by nouiz** [comment]
It work with cudnn. So maybe it should be better documented.

**Comment by dwf** [comment]
Ideally it would just use CuDNN in the first place.

**Comment by dwf** [comment]
The issue seems to be that 
1. if you use `ignore_border=False` and you have overlapping pools, you will always run on CPU, period. 
2. if you use `ignore_border=False` and pool shape == stride, you will get Theano's own GPU max pooling op.
3. if you use `ignore_border=True`, a `GpuDnnPool` replacement will/should take place.

`assert_no_cpu_op` will not help you to catch this either, apparently.

**Comment by dwf** [comment]
There's already a warning printed when using the default value for `ignore_border`, it would be nice if that warning explained the reason that the default will change (at least what I presume is the reason), i.e. that CuDNN can only do the `ignore_border=False` case (and that you might be stuck on CPU if you use the wrong combination of `ignore_border=False` and overlapping pools). It'd be even nicer if #3591.

A large part of why people complain about Theano convnets being slow are probably attributable to mysterious slowdowns like this.

To make this concrete:

* 340 seconds per epoch with max pooling, `ignore_border=False`, (3, 3) pools (2, 2) stride
* 1140 seconds per epoch with two of those replaced with average pooling, `ignore_border=False`, (3, 3) pools (2, 2) stride
* 8 seconds per epoch for the identical epoch with `ignore_border=False`, (3, 3) pools (2, 2) stride and (1, 1) padding on each

**Comment by nouiz** [comment]
What you tell is the expected behavior. Can you add this to the doc?

**Comment by dwf** [comment]
Why is it expected behaviour that `assert_no_cpu_op` fails to catch number 1?

**Comment by lamblin** [comment]
@dwf The part about `assert_no_cpu_op` not catching case 1 is not expected. Could you share code or a graph to help us investigate?
For the moment, `assert_no_cpu_op` will only catch things like `gpu_from_host(some_op(host_from_gpu))`, so we will have to update it, but I don't know why case 1 does not fit that case.

**Comment by dwf** [comment]
Here's a debugprint of a graph where it was happening: https://gist.github.com/dwf/054b1ff9ec915a43dd10

As you can see, it's often a GpuFromHost(TrueDiv(DownsampleFactorMax(HostFromGpu(...)) that's not triggering it, which it sounds like is expected (though it's unclear why the TrueDiv is not being moved to the GPU). But there are clearly some GpuFromHost(DownsampleFactorMax(HostFromGpu(...))) expressions in there too.

**Comment by nouiz** [comment]
Just a link to the issue that would implement more case on the GPU with cudnn:
https://github.com/Theano/Theano/issues/3336

**Comment by nouiz** [comment]
This will be available in the new back-end in this PR: https://github.com/Theano/Theano/pull/5198/files that should be merged today. So closing.
