### ISSUE TITLE
Add slow implementation for Abstract Conv2D Ops

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3598]
We would like the computation of test values to work when building a graph with abstract ops, but make sure that the execution fails if there are still abstract ops in the graph at the execution time.
Currently, the abstract conv2d Ops raise `NotImplementedError` in their `perform` method, which address the second point, but not the first.

An option could be to have a flag (prop?) in the Op, enabling a slow `perform` method at graph construction time, and that would be turned off at some point during the optimization.

Another option may be to highjack the test_value mechanism itself, so it uses a different method of the Op in that case.

**Comment by nouiz** [comment]
I like the idea of a flag with try an optimization at the end that would
check all the ops.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/3973 disable the test in DebugMode for now to have all tests pass.

**Comment by Saizheng** [comment]
https://github.com/Theano/Theano/pull/4049

**Comment by lamblin** [comment]
Done in #4116.
