### ISSUE TITLE
Error when import version theano from github

### ISSUE THREAD

**Issue by astrung** [Theano/Theano#3606]
I use python 2.7.6-theano 0.7(install with pip from github)-block 0.1.1-OS:Centos 64bit
when i run examples, i get this error:
Problem occurred during compilation with the command line below:
/opt/rh/devtoolset-2/root/usr/bin/g++ -shared -g -march=corei7-avx -mcx16 -msahf -mno-movbe -maes -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-bmi2 -mno-tbm -mavx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=20480 -mtune=corei7-avx -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/admin/trungtv/python/lib/python2.7/site-packages/numpy/core/include -I/home/admin/trungtv/python/include/python2.7 -I/home/admin/trungtv/python/lib/python2.7/site-packages/theano/gof -fvisibility=hidden -o /root/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.6-64/lazylinker_ext/lazylinker_ext.so /root/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.6-64/lazylinker_ext/mod.cpp -L/home/admin/trungtv/python/lib -lpython2.7
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: /home/admin/trungtv/python/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/home/admin/trungtv/python/lib/libpython2.7.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status.
And when i try to import theano,i still get this error.
It seem the problem is try to clone a bad version theano from github???

**Comment by nouiz** [comment]
The problem is your Python installation. If you compiled it yourself, see:

http://stackoverflow.com/questions/21342931/error-importing-theano

If you installed it from your OS, then install the python-dev or python-devel package. This is needed by Theano.

**Comment by astrung** [comment]
Yes.Try to reinstall with --enable-shared when build python and add LD_LIBRARY_PATH>fixed.Thank
