### ISSUE TITLE
Grad of diff for n dimensional matrices

### ISSUE THREAD

**Issue by crmne** [Theano/Theano#3611]
Hi,

I implemented the [fused lasso](http://deepblue.lib.umich.edu/bitstream/handle/2027.42/73606/j.1467-9868.2005.00490.x.pdf?sequence=1) in pylearn2, and to finish it off I need to implement the gradient of the DiffOp for inputs with number of dimension other than 1, such as a 4D tensor. I'm new to contributing to Theano. I've been looking at the [Theano doc](http://deeplearning.net/software/theano/extending/op.html#grad) but it's not clear to me what I should return from the grad function of the DiffOp.

Could anyone give me a hand? That would be very much appreciated.

**Comment by nouiz** [comment]
This is our tutorial on how to make an Op for Theano:

http://www.deeplearning.net/software/theano/tutorial/extending_theano.html

It explain how to make a gradient. This work with the symbolic graph too.
Start by reading that page, it should help you.
