### ISSUE TITLE
NanGuardMode triggering for AllocEmpty

### ISSUE THREAD

**Issue by shawntan** [Theano/Theano#3612]
Hi,

I'm trying out NanGuardMode over a scan, and it keeps triggering at this node:
```
AssertionError: NaN detected
NanGuardMode found an error in the output of a node in this variable:
AllocEmpty{dtype='float32'} [@A] ''   
 |Elemwise{add,no_inplace} [@B] ''   
 | |Subtensor{int64} [@C] ''   
 | | |Shape [@D] ''   
 | | | |Subtensor{int64::} [@E] ''   
 | | |   |DimShuffle{1,0,2} [@F] ''   
 | | |   | |Elemwise{Cast{float32}} [@G] ''   
 | | |   |   |input_sequences [@H]
 | | |   |Constant{0} [@I]
 | | |Constant{0} [@J]
 | |Subtensor{int64} [@K] ''   
 |   |Shape [@L] ''   
 |   | |Rebroadcast{0} [@M] ''   
 |   |   |DimShuffle{x,0,1,2} [@N] ''   
 |   |     |Elemwise{mul,no_inplace} [@O] 'batch_memory_init'   
 |   |       |DimShuffle{x,0,1} [@P] ''   
 |   |       | |memory_init [@Q]
 |   |       |DimShuffle{0,x,x} [@R] ''   
 |   |         |Elemwise{second,no_inplace} [@S] ''   
 |   |           |Subtensor{::, int64, int64} [@T] ''   
 |   |           | |Elemwise{Cast{float32}} [@G] ''   
 |   |           | |Constant{0} [@U]
 |   |           | |Constant{0} [@V]
 |   |           |DimShuffle{x} [@W] ''   
 |   |             |TensorConstant{1.0} [@X]
 |   |Constant{0} [@Y]
 |Subtensor{int64} [@Z] ''   
 | |Shape [@BA] ''   
 | | |Rebroadcast{0} [@M] ''   
 | |Constant{1} [@BB]
 |Subtensor{int64} [@BC] ''   
 | |Shape [@BD] ''   
 | | |Rebroadcast{0} [@M] ''   
 | |Constant{2} [@BE]
 |Subtensor{int64} [@BF] ''   
   |Shape [@BG] ''   
   | |Rebroadcast{0} [@M] ''   
   |Constant{3} [@BH]

Apply node that caused the error: AllocEmpty{dtype='float32'}(Elemwise{add,no_inplace}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0)
Toposort index: 266
Inputs types: [TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(), (), (), ()]
Inputs strides: [(), (), (), ()]
Inputs values: [array(5), array(8), array(128), array(20)]
Outputs clients: [[IncSubtensor{Set;:int64:}(AllocEmpty{dtype='float32'}.0, Rebroadcast{0}.0, ScalarFromTensor.0)]]
```

As far as I understand it, this is `scan` attempting to allocate a bunch of memory to which it will fill out the outputs of each scan step. It's causing `NanGuardMode` to trigger, and using `MonitorMode` with a hook shows me arrays that are mostly zeros in contiguous areas, and then very high negative or low values in others.

My guess right now is that since the allocation doesn't zero out the array, it's triggering both these modes with it's initial rubbish values from the memory.

**Comment by nouiz** [comment]
You seem to have identified the problem clearly.

I think the quick solution is to make an exception in the file:

theano/compile/nanguardmode.py

You could change the contains_inf and contains_nan method. You can make
them ignore

I did a quick hack here, maybe it work, but if it don't try to modify it.
It should be close to what you need:

https://github.com/Theano/Theano/pull/3613

**Comment by shawntan** [comment]
Cool thanks!

So, using `MonitorMode` I kinda did the same skips for `GpuAllocEmpty` and `AllocEmpty`.
And then I started getting errors for `IncSubtensor` as well. I'm assuming if `AllocEmpty` gives you an array with nan values, updating one row should give you back the same arrays with nans.

In this case, I'm not so sure how to skip them. Skipping them completely lands me in the situation where the error is only triggered at the gradient step, and I have no idea how to interpret that. Any thoughts?

**Comment by bh** [comment]
"@BH", I will unsubscribe ;)

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/issues/2826 is related. Both AllocEmpty and the MRG can have nan and that is fine.

What about making scan use zeroed alloc? This way, you will bypass all the problem related to that.

/theano/scan_module/scan_utils.py

For this change the function expand_empty to have:

empty = tensor.zeros(new_shape, var.dtype)

instead of

empty = tensor.AllocEmpty(tensor_var.dtype)(*new_shape)

**Comment by nouiz** [comment]
This is related to https://github.com/Theano/Theano/issues/2826

The same fix would help here.

**Comment by lamblin** [comment]
Scan used to have zero-filled buffers, but we changed it to AllocEmpty to avoid a useless memset. Are you suggesting we revert that change?

**Comment by nouiz** [comment]
No, but we should bump the priority to work around that in NanGuardMode.

**Comment by shawntan** [comment]
Thanks @nouiz  that helped!

Should I close the issue? Like you said, this isn't a fix yet, right?

**Comment by nouiz** [comment]
Keep it open, it isn't fixed.

**Comment by nouiz** [comment]
fixed by https://github.com/Theano/Theano/pull/3768
