### ISSUE TITLE
switch shape failure due to optimization

### ISSUE THREAD

**Issue by danielrenshaw** [Theano/Theano#3614]
An optimization appears to be changing the output of `switch` expressions incorrectly. Possibly occurs only when the true condition and false condition values are the same.

Reproduced in latest Github version of Theano as of 7:30am GMT, Sunday 8th November 2015.

Reproduction code:

import theano
import theano.tensor as tt

    theano.config.compute_test_value = 'raise'
    x = tt.lvector()
    x.tag.test_value = [1, 2]
    y = tt.switch(x > 0, 1, 1)
    f = theano.function([x], y)
    print y.tag.test_value
    print f(x.tag.test_value)
    theano.printing.debugprint(y)
    theano.printing.debugprint(f)

Prints

    [1 1]
    [1]
    Elemwise{switch,no_inplace} [@A] ''   
     |Elemwise{gt,no_inplace} [@B] ''   
     | |<TensorType(int64, vector)> [@C]
     | |DimShuffle{x} [@D] ''   
     |   |TensorConstant{0} [@E]
     |DimShuffle{x} [@F] ''   
     | |TensorConstant{1} [@G]
     |DimShuffle{x} [@H] ''   
       |TensorConstant{1} [@G]
    DeepCopyOp [@A] ''   0
     |TensorConstant{(1L,) of 1} [@B]

Changing `y = tt.switch(x > 0, 1, 1)` to something like `y = tt.switch(x > 0, 1, 2)` yields expected results.

Originally reported by Dong-Hyun Lee on theano-dev mailing list: https://groups.google.com/forum/#!topic/theano-dev/gHeI49PqjfY

Original report:

    I might have found a bug in function theano.tensor.switch. 
	 

	<code>

	import theano, cPickle, time, os
	import theano.tensor as T
	import numpy as np

	input = np.array([[1.,0.,1.],[0.,1.,0.]], dtype='float32')
	X = T.fmatrix()
	ss = theano.function( [X], T.switch( X > 0 , 0.5 + 0.*X, 0.5 - 0.*X ) )
	ss(input)

	<output>
	array([[ 0.5]], dtype=float32)

	but it should be 2x3 matrix. If i modify the code, it's output is correct.

	<code>
	input = np.array([[1.,0.,1.],[0.,1.,0.]], dtype='float32')
	X = T.fmatrix()
	ss = theano.function( [X], T.switch( X > 0 , 0.499999 + 0.*X, 0.5 - 0.*X ) )
	ss(input)

	<output> 

	array([[ 0.49999899,  0.5       ,  0.49999899],
	       [ 0.5       ,  0.49999899,  0.5       ]], dtype=float32)

**Comment by lamblin** [comment]
Probably coming from `local_useless_switch`
```
BadOptimization: BadOptimization Error 
  Variable: id 140245558346136 Rebroadcast{0,0}.0
  Op Rebroadcast{0,0}(TensorConstant{(1, 1) of 0.5})
  Value Type: <class 'numpy.ndarray'>
  Old Value shape, dtype, strides: (2, 3) float32 (12, 4)

  Old Value:  [[ 0.5  0.5  0.5]
 [ 0.5  0.5  0.5]]
  New Value shape, dtype, strides: (1, 1) float32 (4, 4)

  New Value:  [[ 0.5]]
  Reason:  local_useless_switch
  Old Graph:
  Elemwise{switch,no_inplace} [@A] ''   
   |Elemwise{gt,no_inplace} [@B] ''   
   | |<TensorType(float32, matrix)> [@C]
   | |TensorConstant{(1, 1) of 0} [@D]
   |TensorConstant{(1, 1) of 0.5} [@E]
   |TensorConstant{(1, 1) of 0.5} [@E]

  New Graph:
  Rebroadcast{0,0} [@F] ''   
   |TensorConstant{(1, 1) of 0.5} [@E]
```

**Comment by nouiz** [comment]
I have a PR:

https://github.com/Theano/Theano/pull/3619

thanks
