### ISSUE TITLE
true_dot gradient bug

### ISSUE THREAD

**Issue by fedorajzf** [Theano/Theano#3615]
I found bug in true_dot gradient , here is the test code
  3 import sys
  4 import theano
  5 import numpy as np
  6 import lookup_table
  7 import theano.sparse as SS
  8 import theano.tensor as TT
  9 import scipy.sparse as ss
 10 
 11 x = SS.csr_matrix('input')
 12 
 13 embedding = theano.shared(np.zeros((10, 1), dtype='float32'))
 14 
 15 w = theano.shared(np.asarray([[0.2],[0.3]]))
 16 b = theano.shared(np.asarray([0.1]))
 17 
 18 y = (SS.true_dot(x, embedding, grad_preserves_dense=False).toarray().reshape((-1, 2)).dot(w) + b).sum()
 19 #y = (SS.structured_dot(x, embedding).reshape((-1, 2)).dot(w) + b).sum()
 20 
 21 ge = TT.grad(y, embedding)
 22 gb = TT.grad(y, b)
 23 
 24 theano.printing.debugprint(ge)
 25 
 26 a = ss.csr_matrix(([1, 1], [3, 2], [0, 1, 2]), (2, 10), dtype='float32')
 27 print ge.eval({x:a})

It got zero when use true_dot, but got non-zero values use structured_dot

**Comment by fedorajzf** [comment]
Need help

**Comment by nouiz** [comment]
I suppose you closed it as there wasn't a bug in Theano. If I'm wrong, tell me.

**Comment by fedorajzf** [comment]
I closed it because I modify theano's code and fixed this problem
Maybe we should discuss this problem

**Comment by nouiz** [comment]
Which change did you do to Theano?

**Comment by fedorajzf** [comment]
add a function like toarray,  which will calculate gradient for zero elements in sparse array
def dense_grad_toarray(self):
     return DenseFromSparse(structured=False)(self)

**Comment by fedorajzf** [comment]
add a function like toarray,  which will calculate gradient for zero elements in sparse array
def dense_grad_toarray(self):
     return DenseFromSparse(structured=False)(self)

**Comment by fedorajzf** [comment]
replace toarray with dense_grad_toarray in the code on the top will fix the bug

**Comment by fedorajzf** [comment]
ok, I'll submit a pull request later this week
