### ISSUE TITLE
Can't find theano.compile.module

### ISSUE THREAD

**Issue by sbos** [Theano/Theano#3616]
I can't import `theano.compile.module` which is referenced in many places including the documentation http://deeplearning.net/software/theano/sandbox/module2.html.
I use theano 7.0 installed by pip.

Is this functionality deprecated or was it moved somewhere? I'm a new user to theano and may be missing something.

**Comment by nouiz** [comment]
Module are very old stuff that is removed from Theano.

But it seem that this old web page wasn't deleted from the web site. I just did it now. I also searched for other such file and got rid of them.

thanks.

**Comment by sbos** [comment]
Thanks Frederic. Do you know if there is any replacement for modules? I find the idea very convenient as it allows to re-use parts of the computational graph in the form of functions.

**Comment by nouiz** [comment]
It have been replaced by SharedVariable. You can use class to share part of
the computational graph as done in the deep learning tutorial:

http://deeplearning.net/tutorial/
