### ISSUE TITLE
How to efficiently calculate pairwise distances (possibly on GPU)

### ISSUE THREAD

**Issue by gabrielelanaro** [Theano/Theano#3622]
Hi, I was trying to speed up some pairwise distance calculation with the following code:

```
from theano.tensor import matrix, shared
from theano import config
import numpy as np

x = np.random.rand(100, 3).astype(config.floatX)
X_i = shared(x[None, :, :], broadcastable=(True, False, False))
X_j = shared(x[:, None, :], broadcastable=(False, True, False))
print X_i
print X_j

dX = (X_i - X_j)**2
Dsq = dX.sum(axis=2)
D = Dsq**0.5
import time
start = time.time()
D.eval()
print time.time() - start
```

When I run on gpu, the runtime is slightly higher than the CPU version, I was wondering which technique I could use to improve the code and reduce memory usage

**Comment by nouiz** [comment]
This timming isn't well done.

.eval() will include time for the compilation. Compilation on the GPU is
little higher then on the CPU. Do it in two step:

```
f=theano.function([], D)
start=time.time()
f()
print time.time() - start
```

this way, you only compute the time for the computation.

This computation graph do very little computation. So the bottleneck on the
GPU could be the CPU/GPU transfer for the result. You can use Theano
profiler to see if this is the case:

http://deeplearning.net/software/theano/tutorial/profiling.html

As there isn't much computation and that the reduction isn't the
computation that get much speed up from the GPU, I won't not exept a good
speed up for that small graph. Other graph with more computation would
probably give more speed up.

**Comment by oak-tree** [comment]
Old but might be still relevant 

check out http://stackoverflow.com/a/26065509/1211174
