### ISSUE TITLE
theano.printing.pydotprint() TypeError:

### ISSUE THREAD

**Issue by DemoRunner** [Theano/Theano#3624]
pyhton3.4.4
my code is :
 import theano
>>> a = theano.tensor.vector("a")
>>> b = a + a ** 10
>>> f = theano.function([a], b)
>>> print(f([0, 1, 2]))
[    0.     2.  1026.]
>>>theano.printing.pydotprint(b, outfile="/home/prafly/desktop/symbolic_graph_unopt.png", var_with_name_simple=True)

error is
TypeError: sequence item 0: expected str instance, bytes found

**Comment by nouiz** [comment]
This was fixed by gh-3633
