### ISSUE TITLE
Confusion matrix

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3637]
This question happen frequently on the mailing list, maybe we should add it in Theano directly:

[[theano-users] Show the confusion matrix](https://groups.google.com/d/topic/theano-users/MMuXRzYPePA/discussion)

**Comment by meetshah1995** [comment]
@nouiz - I went through the google thread , is anyone working on it ? If not I'd like to add a PR with the implementation, example and tests.

**Comment by nouiz** [comment]
Nobody work on this to my knowledge.

thanks

**Comment by meetshah1995** [comment]
@nouiz in which file do I add the method to show the confusion matrix ? Sorry for being silly, I am new with this.

**Comment by lamblin** [comment]
Closed by #4810.
