### ISSUE TITLE
Switch our convolution operations to b01c layout

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#3638]
This is 8x as fast with cudnn v3.

However it seems that cudnn pooling is much more limited with this layout.

**Comment by nouiz** [comment]
For which case/shapes you saw this?

Can you detail the limit in the pooling?

**Comment by abergeron** [comment]
It's a dumb 5-layers convnet like this:

input (32, 224, 224, 3)

conv(channels=3, filters=64, filter_size=11, stride=4, padding='valid')
conv(channels=64, filters=128, filter_size=5, stride=1, padding=2)
conv(channels=128, filters=256, filter_size=3, stride=1, padding=1)
conv(channels=256, filters=192, filter_size=3, stride=1, padding=1)
conv(channels=192, filters=192, filter_size=3, stride=1, padding=1)

I had to remove the pooling layers since they don't support b01c for the required configuration of maxpool(ws=3, stride=2) and we get a CUDNN_STATUS_NOT_SUPPORTED error.

**Comment by abergeron** [comment]
I did some timings just to be really sure of all the variables and I can't seem to be able to reproduce the slow timings.

Here is what I get:

The timings I've got for these now are:

Layout  | cross | conv
---------- | ------- | -------
bc01 | 0.567 | 0.567
b01c | 0.591 | 0.594

I did try to revert as much of the code I could to the initial state but all timings seem consistent with the above, so I really don't know why I got such horrible timings before and I can't seem to reproduce those.
