### ISSUE TITLE
where to find theano tutorial's example

### ISSUE THREAD

**Issue by liyi193328** [Theano/Theano#3645]
As the title, I'm the beginer of thean, and want to go further, because It's so cool to do some tests.
I learn theano by its officeal tutorial, but if I want to do some modification on its tutorial code(picture), I must input all the tutorial code manually, which is time-consuming and disgusting.
But I can't find the tutorial code for a long time. Please help me, Thanks very much!
![image](https://cloud.githubusercontent.com/assets/6782974/11169128/cbdcb9b4-8be9-11e5-92da-18e8e072ac37.png)

**Comment by nouiz** [comment]
The tutorial code in under the doc directory of Theano repository. You could clone it, then copy/paste the code:

https://github.com/Theano/Theano/tree/master/doc

But better, use ipython and its %cpaste magic. It will allow you to copy/paste the code from the web site and it will work.

I'm closing as I think it answer well your need, but if you still have questions, you can ask here.

**Comment by liyi193328** [comment]
Thanks very much @nouiz
