### ISSUE TITLE
Ubuntu 14.04 installation instructions look outdated

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [Theano/Theano#3648]
http://deeplearning.net/software/theano/install_ubuntu.html seems a bit outdated. I've had to use some quite different instructions to make Theano works on GPU on Kubuntu 14.04 (I'd assume the same instructions are valid in Ubuntu but unsure): http://stackoverflow.com/q/33743346/395857

**Comment by Seleucia** [comment]
Hi, I prepare a Theano GPU instillation for ubuntu 14.04, if you want you can have a look at it. 
https://goo.gl/1jH8eJ

**Comment by lamblin** [comment]
Instructions have been updated since.
