### ISSUE TITLE
Error allocating 24 bytes of device memory (out of memory). Driver report 0 bytes free and 0 bytes total  ERROR (theano.sandbox.cuda): 

### ISSUE THREAD

**Issue by xxxzhi** [Theano/Theano#3655]
When I run bin/theano-test, I get this errors: 

Error when trying to find the memory information on the GPU: out of memory
Error allocating 24 bytes of device memory (out of memory). Driver report 0 bytes free and 0 bytes total 
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
CudaNdarray_ZEROS: allocation failed.

I use tesla C2075 and Linux version 3.19.0-25-generic（Ubuntu server 14.04 LTS ). 
The driver is NVIDIA-Linux-x86_64-346.96.run.
cuda is cuda_7.0.28_linux.run

It is some bugs? thanks.
the full logs is : 

Theano version 0.7.0.dev-80197cf574b62fa7d869f4de800700d2f75b7f4e
theano is installed in /home/b3432/Theano/theano
NumPy version 1.9.2
NumPy is installed in /usr/local/lib/python2.7/dist-packages/numpy
Python version 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
nose version 1.3.7
/home/b3432/Theano/theano/misc/pycuda_init.py:34: UserWarning: PyCUDA import failed in theano.misc.pycuda_init
  warnings.warn("PyCUDA import failed in theano.misc.pycuda_init")
Error when trying to find the memory information on the GPU: out of memory
Error allocating 24 bytes of device memory (out of memory). Driver report 0 bytes free and 0 bytes total 
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
CudaNdarray_ZEROS: allocation failed.
..................Error when trying to find the memory information on the GPU: out of memory
Error allocating 24 bytes of device memory (out of memory). Driver report 0 bytes free and 0 bytes total 
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
CudaNdarray_ZEROS: allocation failed.
E............................K................../home/b3432/Theano/theano/compile/profilemode.py:103: UserWarning: DEPRECATION WARNING: The ProfileMode is deprecated. Use the Theano flags/parameter to theano.function 'profile=True' instead of 'mode=ProfileMode'
  "DEPRECATION WARNING: The ProfileMode is deprecated. Use the Theano"
................................................../home/b3432/Theano/theano/gof/vm.py:729: UserWarning: CVM does not support memory profile, using Stack VM.
  'CVM does not support memory profile, using Stack VM.')
......................0.0581646137166
0.0581646137166
0.0581646137166
0.0581646137166

**Comment by xxxzhi** [comment]
I get this (it is ok ) when I run deviceQuery, 

./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Tesla C2075"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    2.0
  Total amount of global memory:                 5374 MBytes (5635194880 bytes)
  (14) Multiprocessors, ( 32) CUDA Cores/MP:     448 CUDA Cores
  GPU Max Clock rate:                            1147 MHz (1.15 GHz)
  Memory Clock rate:                             1566 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 786432 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65535), 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (65535, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Enabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 5 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = Tesla C2075
Result = PASS

**Comment by nouiz** [comment]
Do you have something else running on that GPU? After one such error, the
driver is probably in a bad state and will cause the following error.

**Comment by xxxzhi** [comment]
I run nvidia-smi and can find the GPU message. I also can run deviceQuery
in cuda examples. But I can't use theano and caffe.

On Sat, Nov 21, 2015 at 12:03 AM, Frédéric Bastien <notifications@github.com
> wrote:

> Do you have something else running on that GPU? After one such error, the
> driver is probably in a bad state and will cause the following error.
>
>

**Comment by nouiz** [comment]
Maybe you aren't authorized to use that GPU.

deviceQuery just query about the GPU, so it can work even when you can't
use the GPU.

Try to use another cuda example that will do computation on the GPU.

**Comment by xxxzhi** [comment]
oh, Thanks. I has been informed the c2075 is not authorized and I change
the nvidia-card to k8, and it is ok.

On Mon, Nov 23, 2015 at 11:11 PM, Frédéric Bastien <notifications@github.com
> wrote:

> Maybe you aren't authorized to use that GPU.
>
> deviceQuery just query about the GPU, so it can work even when you can't
> use the GPU.
>
> Try to use another cuda example that will do computation on the GPU.
>
>
> On Sat, Nov 21, 2015 at 12:16 AM, 侯志 <notifications@github.com> wrote:
>
> > I run nvidia-smi and can find the GPU message. I also can run deviceQuery
> > in cuda examples. But I can't use theano and caffe.
> >
> >
> > On Sat, Nov 21, 2015 at 12:03 AM, Frédéric Bastien <
> > notifications@github.com
> > > wrote:
> >
> > > Do you have something else running on that GPU? After one such error,
> the
> > > driver is probably in a bad state and will cause the following error.
> > >
> > >
> > > On Thu, Nov 19, 2015 at 11:09 PM, 侯志 <notifications@github.com> wrote:
> > >
> > > > I get this (it is ok ) when I run deviceQuery,
> > > >
> > > > ./deviceQuery Starting...
> > > >
> > > > CUDA Device Query (Runtime API) version (CUDART static linking)
> > > >
> > > > Detected 1 CUDA Capable device(s)
> > > >
> > > > Device 0: "Tesla C2075"
> > > > CUDA Driver Version / Runtime Version 7.5 / 7.5
> > > > CUDA Capability Major/Minor version number: 2.0
> > > > Total amount of global memory: 5374 MBytes (5635194880 bytes)
> > > > (14) Multiprocessors, ( 32) CUDA Cores/MP: 448 CUDA Cores
> > > > GPU Max Clock rate: 1147 MHz (1.15 GHz)
> > > > Memory Clock rate: 1566 Mhz
> > > > Memory Bus Width: 384-bit
> > > > L2 Cache Size: 786432 bytes
> > > > Maximum Texture Dimension Size (x,y,z) 1D=(65536), 2D=(65536, 65535),
> > > > 3D=(2048, 2048, 2048)
> > > > Maximum Layered 1D Texture Size, (num) layers 1D=(16384), 2048 layers
> > > > Maximum Layered 2D Texture Size, (num) layers 2D=(16384, 16384), 2048
> > > > layers
> > > > Total amount of constant memory: 65536 bytes
> > > > Total amount of shared memory per block: 49152 bytes
> > > > Total number of registers available per block: 32768
> > > > Warp size: 32
> > > > Maximum number of threads per multiprocessor: 1536
> > > > Maximum number of threads per block: 1024
> > > > Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
> > > > Max dimension size of a grid size (x,y,z): (65535, 65535, 65535)
> > > > Maximum memory pitch: 2147483647 bytes
> > > > Texture alignment: 512 bytes
> > > > Concurrent copy and kernel execution: Yes with 2 copy engine(s)
> > > > Run time limit on kernels: No
> > > > Integrated GPU sharing Host Memory: No
> > > > Support host page-locked memory mapping: Yes
> > > > Alignment requirement for Surfaces: Yes
> > > > Device has ECC support: Enabled
> > > > Device supports Unified Addressing (UVA): Yes
> > > > Device PCI Domain ID / Bus ID / location ID: 0 / 5 / 0
> > > > Compute Mode:
> > > > < Default (multiple host threads can use ::cudaSetDevice() with
> device
> > > > simultaneously) >
> > > >
> > > > deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA
> > > Runtime
> > > > Version = 7.5, NumDevs = 1, Device0 = Tesla C2075
> > > > Result = PASS
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/Theano/Theano/issues/3655#issuecomment-158274032
> >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Theano/Theano/issues/3655#issuecomment-158443333>.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Theano/Theano/issues/3655#issuecomment-158591203>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Theano/Theano/issues/3655#issuecomment-158963712>.
>



-- 
houzhi
