### ISSUE TITLE
Cuda drivers and toolkit points to 404 in docs

### ISSUE THREAD

**Issue by anuragranj** [Theano/Theano#3657]
The following link on the page (http://deeplearning.net/software/theano/install.html#gpu-linux) is no longer valid:
'''
Using the GPU
The first thing you’ll need for Theano to use your GPU is Nvidia’s GPU-programming toolchain. You should install at least the CUDA driver and the CUDA Toolkit, as described here(http://www.nvidia.com/object/cuda_get.html). The CUDA Toolkit installs a folder on your computer with subfolders bin, lib, include, and some more too.

**Comment by nouiz** [comment]
thans, I have a PR with a fix.
