### ISSUE TITLE
setup.py should copy the content of d3viz/html

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3658]
See https://groups.google.com/d/topic/theano-users/Cc-22kytHF0/discussion

**Comment by saatvikshah1994** [comment]
@nouiz - I would like to take up this bug if theres no one working on it. It would be sufficient to add the following line in setup.py under 'package_data' right? Or is there anything more?:
`'theano.d3viz' : ['html/*']`

**Comment by nouiz** [comment]
This is part of what is needed. But you also need to test it to make sure
it work. I tried rapidly, and I didn't success in 15m. Maybe there is also
the MANIFEST* file to modify.

To my knowledge, nobody work on this.

thanks

**Comment by saatvikshah1994** [comment]
@nouiz I've submitted PR #3862 to correct this issue.
There was also the problem of other subdirectories not being copied such as `js` and `css` which is also fixed. I dont think there is any change required in the MANIFEST* files required, but please correct me if Im wrong. 
Any other changes required here?

**Comment by nouiz** [comment]
done by gh-3862
