### ISSUE TITLE
BUG IN FGRAPH.REPLACE OR A LISTENER <type 'exceptions.Exception'> Constant{0} is already owned by another fgraph local_shape_to_shape_i

### ISSUE THREAD

**Issue by bourbakimember** [Theano/Theano#3663]
Hi,

Incurring this error when attempting to compile theano function. Function compiles with optimizer=fast_compile.

The function implements a for loop where i assume this error originates.

python version : Python 2.7.9 
theano version : 0.7.0.dev-6ca7b2b65000e371f009b617d41bc5a90f022d38

similar to ticket : https://github.com/Theano/Theano/issues/2976, although work around didn't seem to circumvent the issue.

Error begins:

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.Exception'> Constant\{0\} is already owned by another fgraph local_shape_to_shape_i\
ERROR (theano.gof.opt): Optimization failure due to: local_shape_to_shape_i\
ERROR (theano.gof.opt): node: Shape(for\{cpu,grad_of_scan_fn\}.61)\
ERROR (theano.gof.opt): TRACEBACK:\
ERROR (theano.gof.opt): Traceback (most recent call last):\
  File "/Users/Theano/theano/gof/opt.py", line 1822, in process_node\
    fgraph.replace_all_validate(repl_pairs, reason=lopt)\
  File "/Users/Theano/theano/gof/toolbox.py", line 306, in replace_all_validate\
    fgraph.replace(r, new_r, reason=reason, verbose=False)\
  File "/Users/Theano/theano/gof/fg.py", line 592, in replace\
    self.change_input(node, i, new_r, reason=reason)\
  File "/Users/Theano/theano/gof/fg.py", line 530, in change_input\
    self.__import_r__(new_r, reason=reason)\
  File "/Users/Theano/theano/gof/fg.py", line 363, in __import_r__\
    self.__import__(variable.owner, reason=reason)\
  File "/Users/Theano/theano/gof/fg.py", line 394, in __import__\
    raise Exception("%s is already owned by another fgraph" % r)\
Exception: Constant\{0\} is already owned by another fgraph\

Please find entire exception: [error.txt](https://github.com/Theano/Theano/files/40653/error.txt)

Thanks in advance.

**Comment by nouiz** [comment]
Thanks for the report. Can you give us a way to reproduce this? This would help you generate such case:

http://www.deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

**Comment by bourbakimember** [comment]
Hi nouiz,

Please find pickle file attached: http://www.mediafire.com/download/t3811ft0u0ae46d/error

If this doesnt suffice let me know. (Also I wasnt sure if mediafire is an acceptable platform to distribute such files)

Thanks!

**Comment by nouiz** [comment]
You can use this older commit. It don't have this problem:

```
git checkout 146fbae8c4e235cd80e959cf4d510588d811692b
```

I'm able to reproduce this.

**Comment by nouiz** [comment]
Just to have all the information in the same ticket, I'm able to reproduce this.

**Comment by shawnjhenry** [comment]
I'm also getting this error.

**Comment by nouiz** [comment]
I'm adding the work around with an easier way to install it in the mean time:

```
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git@07e9332a0932e90c47ed2a70fc3c7f8a55d2aa23
```

**Comment by nouiz** [comment]
Just to tell, we merge the fix. thanks for the report.

**Comment by bourbakimember** [comment]
thanks so much!
theano community is incredible!
