### ISSUE TITLE
Error message in conv.py

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3665]
https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/conv.py#L871-L872

Two suggestions and a question:

* [ ] This is only raised when border_mode is not 'valid'; the error message should make mention of that so it's easier to debug
* [ ] "different from 1 or 2" would be better phrased as "greater than 2", assuming that dx and dy are elsewhere checked for > 0 (because <= 0 makes no sense whatsoever).

Finally, does this mean that one still cannot use stride > 2 convolution if you need to backprop?

**Comment by JesseLivezey** [comment]
> Finally, does this mean that one still cannot use stride > 2 convolution if you need to backprop?

I think the cuDNN and gemm implementations should allow stride > 2. On cpu, there is a gemm implementation available through the abstract_conv interface/optimizations.

**Comment by nouiz** [comment]
I have a PR: https://github.com/Theano/Theano/pull/3682

It mostly need link to the not yet done doc on the web site about
abstract_conv.
