### ISSUE TITLE
max_pool_2d unexpected output for st < ds and ignore_border=False

### ISSUE THREAD

**Issue by chrisdonahue** [Theano/Theano#3666]
I'm seeing some unexpected output from `max_pool_2d` when using a stride strictly less than my downsample factor with `ignore_border=False`. I expect `ignore_border` to take my stride into account. There are workarounds involving padding but it's an awkward fix. I cooked up a 1D example for simplicity. Here is the output with stride=2, downsample=4:

```
--------
input:	[ 0.  1.  2.  3.  4.  5.]
expect:	[ 3.  5.  5.]
theano:	[ 3.  5.]
--------
input:	[ 0.  1.  2.  3.  4.  5.  6.]
expect:	[ 3.  5.  6.  6.]
theano:	[ 3.  5.  6.]
--------
input:	[ 0.  1.  2.  3.  4.  5.  6.  7.]
expect:	[ 3.  5.  7.  7.]
theano:	[ 3.  5.  7.]
--------
input:	[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]
expect:	[ 3.  5.  7.  8.  8.]
theano:	[ 3.  5.  7.  8.]
```

And the script used to generate it:

```python
import theano
import theano.tensor as T
from theano.tensor.signal.downsample import max_pool_2d

import numpy as np

downscale = 4
stride = 2
x_var = theano.tensor.matrix(dtype=theano.config.floatX)
x_var_downsampled = max_pool_2d(input=x_var, ds=(1, downscale), ignore_border=False, st=(1, stride), padding=(0, 0), mode='max')
downsample = theano.function([x_var], x_var_downsampled)

for n in xrange(6, 10):
	x = np.arange(n).astype(theano.config.floatX)[np.newaxis, :]
	correct = []
	for l in xrange(0, n, stride):
		r = l + downscale
		correct.append(max(x[0][l:r]))
	print '--------'
	print 'input:\t{}'.format(x[0])
	print 'expect:\t{}'.format(np.array(correct))
	print 'theano:\t{}'.format(downsample(x)[0])
```

**Comment by nouiz** [comment]
I think you are right, Theano could handle that in the way you tell. But
currently ignore_border is only add a max of 1 colums.

But ignore_border=False is deprecated. We are the only one supporting that.
CuDNN do not support that, so this end up with slower code. You can pad
explicitly to have the equivalent behavior.

But why do you want that? I don't know any case where this is benefical vs
ignore_border=True.

We plan to change the default to have ignore_border=True.

**Comment by chrisdonahue** [comment]
Thank you for your response! I wasn't aware that ignore_border was deprecated.

I wanted this behavior as I am working with convolutional autoencoders. My handling of edge cases in pooling layers has to be precise in order for me to be able to reverse the network and get the exact same dimensions in the decoder layers as in the encoder layers. Padding is an acceptable workaround and it's very useful to know that this would not have been supported by CuDNN anyway.

**Comment by lamblin** [comment]
Your "expected" value would also have been reasonable, but we decided that if the last column was included in at least one pooling region, then it was not "ignored", so that is the semantic.
