### ISSUE TITLE
A small mistake in Unittest documentation

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#3671]
The directory from which running all the tests(using theano-nose) in the given link seems to be wrong. I guess it should be from one level above what's given in the link
http://deeplearning.net/software/theano/extending/unittest.html#theano-nose

**Comment by nouiz** [comment]
thanks for reporting this. Do you want to make a PR with this? Otherwise, I
can do it.

**Comment by Sentient07** [comment]
@nouiz I'll make a PR :)
