### ISSUE TITLE
default_blas_ldflags assumes try_compile_tmp always returns tuple

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3677]
I have no idea what's actually triggering this failure, maybe the C compiler vanished, but this reveals an error in the logic in `default_blas_ldflags`.

https://travis-ci.org/mila-udem/blocks/jobs/92842112#L1238-L1257

**Comment by bartvm** [comment]
I ran into this today myself, thought it was my setup, but after looking again I traced it to this commit from 5 days ago which introduced the erroneous code (`if res[0] and res[1]`): https://github.com/Theano/Theano/commit/bba7fda1f4af9bf2d00fddb324108f7a3bf6eb47

**Comment by nouiz** [comment]
I have a PR with a fix:

https://github.com/Theano/Theano/pull/3678

Can you test it? I think this can only happen when there is no g++
compiler. Is that your case? Otherwise, can you investigate and tell me why
res is False? In all other case I found in the code, it should be a tuple
of lenght 2.

**Comment by dwf** [comment]
I can't seem to replicate this locally but @bartvm can so it would be better if he tried it out.
