### ISSUE TITLE
Add `infer_shape` for `GpuCorrMM*` Ops

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3680]
This should be quite simple, just a call to `theano.tensor.nnet.abstract_conv.get_conv_output_shape` for the forward operation, and reading from the `shape` argument for the gradient operations.

**Comment by f0k** [comment]
For the gradient operations for non-strided convolutions, the `shape` argument is optional, though. In that case, the shape needs to be inferred from the Op's input shapes.

**Comment by nouiz** [comment]
@lamblin is this one done?

**Comment by nouiz** [comment]
it is done.
