### ISSUE TITLE
strided-conv-{transpose,adjoint} in abstract-conv

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3681]
Having more direct access to the conv-transpose op (specifically, conv-transpose with stride in the output) would be a useful addition. This is useful for generative networks.

The current way of doing it (with CuDNN only) requires some acrobatics:

https://github.com/Newmu/dcgan_code/blob/master/lib/ops.py#L85-L96

**Comment by lamblin** [comment]
Right.
This interface would instantiate `AbstractConv2d_gradInputs`, then the rest will be taken care of by existing optimizations.
Note that, unlike `conv2d`, you will have to provide the shape for the output of the operation, since it cannot be automatically determined when the strides are not 1.

**Comment by nouiz** [comment]
@Sentient07 this one is also interresting. Mostly move the code from that repo to Theano, but make it use the new theano.tensor.nnet.abstract_conv.AbstractConv2d_gradInputs op instead to make it work on the CPU and add tests.

I would put it in the file theano.tensor.nnet.__init__.py

**Comment by Sentient07** [comment]
@nouiz Yeah, seems doable. Should the test be at ``` theano.tensor.nnet.tests.test_conv.TestConv2D ``` ?

**Comment by nouiz** [comment]
no, it should be in tensor/tests/test_abstract_conv.py. It currently don't
exist for some complex reason, but normally, it should be there.

**Comment by Sentient07** [comment]
@nouiz Sorry for the delayed reply, i had gone on a vaccation. Should i be using only the AbstractConv2d_gradInputs op ? I'm having this confusion as i can see the GPU version using 3 different Ops..

**Comment by Sentient07** [comment]
Hi, its almost a year and I just am realizing more about this issue. Can we have a GPUOp for this? caffe has an implementation. https://github.com/BVLC/caffe/blob/master/src/caffe/layers/deconv_layer.cu

**Comment by lamblin** [comment]
The Ops have been in Theano for a while, there is one based on caffe-like convolutions and their gradients (GpuCorrMM), and one based on cuDNN.
There are also helper functions named `conv{2,3}d_grad_wrt_{inputs,weights}`.
The only part missing would be an interface named differently, to convey the fact that it is a transposed convolution (as well as gradient wrt inputs), which is what #3989 is about, so I'll close this ticket.
