### ISSUE TITLE
Complex number cast warning, on compiling conv2d on CPU with FAST_COMPILE

### ISSUE THREAD

**Issue by mjwillson** [Theano/Theano#3685]
This is despite my not using complex numbers anywhere. Still seems (?) to work despite the warning, but makes me wonder if something wrong is happening internally.

``` python
In [1]: import theano.tensor as T; import theano
In [2]: input, filters = T.tensor4('input'), T.tensor4('filters')
In [3]: fn = theano.function([input, filters], T.nnet.conv2d(input, filters), mode='FAST_COMPILE')
In [4]: fn(np.ones((1,1,1,1), dtype=np.float32), np.ones((1,1,1,1), dtype=np.float32))
/home/matt/venv/theano/lib/python3.4/site-packages/theano/tensor/nnet/conv.py:789: ComplexWarning: Casting complex values to real discards the imaginary part
  1, val, bval, 0)
Out[4]: array([[[[ 1.]]]], dtype=float32)
```

The warning doesn't show up when using FAST_RUN.

**Comment by nouiz** [comment]
This come from scipy, not Theano. I checked and we pass only float* values.

Be warned, that the execution will be slow in that mode. If you want
something that is faster to compile but still not too slow try:

mode=theano.Mode(optimizer='fast_compile')

**Comment by nouiz** [comment]
We removed the warning due to newer numpy version.
