### ISSUE TITLE
Add unit tests for get_conv_output_shape

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3686]
`theano.tensor.nnet.abstract_conv.get_conv_output_shape` is only tested indirectly, via the functions that call it. We should also have direct tests.

**Comment by nouiz** [comment]
I think https://github.com/Theano/Theano/pull/3786 did this. @lamblin can you confirm? If so, we can close this PR.

**Comment by nouiz** [comment]
Forget my previous comment. I'll delete it. I have read this issue too rapidly.

**Comment by nouiz** [comment]
@Sentient07 I think this woud be a good ticket that can be done while there is nobody around.

**Comment by Sentient07** [comment]
@nouiz , So i should be creating a new file ```theano.tensor.nnet.tests.test_abstract_conv``` and test the ```get_conv_output_shape``` method ?

**Comment by nouiz** [comment]
Yes.

**Comment by Sentient07** [comment]
@nouiz I'm starting with this first :+1:
