### ISSUE TITLE
Test DownSampleFactorMax.out_shape as other framework use it

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3687]
see: [theano-dev] third regression in 24 hours

**Comment by Sentient07** [comment]
@nouiz , can I give it a try ? A little more details about this ticket please ?

**Comment by nouiz** [comment]
You can take it. thanks!

In the file theano/tensor/signal/downsample.py there is a class
DownSampleFactorMax. It have a method out_shape. This ticket is about
adding test in the file .../signal/tests/test_downsample.py to test that
function. Is is used to compute the output of shape max pooling operation.
So mostly test that it compute the current result.

We are pretty sure it compute the value correctly, the goal is to also make
sure we don't break that interface as there is code outside Theano that use
it.

**Comment by Sentient07** [comment]
@nouiz , i went through those two files. A quick confirmation, should the test be similar to how "DownsampleFactorMaxGradGrad" class is tested  ?

**Comment by nouiz** [comment]
We don't want to test the op itself. This is already done. We want to test
just that method. If that don't answer the question, can you ask it
differently? I'm not sure what you want to know.

**Comment by Sentient07** [comment]
Yeah, i think i get what you say. I need to make a call to the "out_shape" method and do an assert_allclose on what it returns ?

**Comment by nouiz** [comment]
Yes. If you can test a few different schedule at the same time, it would be
great.

Le jeu. 26 nov. 2015 17:19, Ramana Subramanyam <notifications@github.com> a
écrit :

**Comment by Sentient07** [comment]
@nouiz, i'm comparing the shape of numpy_output_val(https://github.com/Theano/Theano/blob/master/theano/tensor/signal/tests/test_downsample.py#L185 ) and the output of out_shape method. But the test seems to fail.. Shall I make a PR of the failed test so that it'd be easier for you to have a look at ?

**Comment by nouiz** [comment]
If you want me to look, make a PR.
