### ISSUE TITLE
Type Error when invoking shared variable's set_value method

### ISSUE THREAD

**Issue by zeka0** [Theano/Theano#3702]
I have read the theano documentation and found it only explains using scalar value in shared variable.
And I just tried to using a shared 'ndarray' variable(created using 'theano.shared(numpy.ones(100))' ) in theano and it reports"
 z = z + make_array(dt=dt)
TypeError: ("unsupported operand type(s) for +: 'numpy.ndarray' and 'numpy.ndarray'", 'Container name "None"')"
Can shared variable be an array?

**Comment by nouiz** [comment]
Just a quick reply, yes, theano shared variable can be array.
