### ISSUE TITLE
Very slow performance on CPU on dev branch

### ISSUE THREAD

**Issue by sheckylin** [Theano/Theano#3704]
I am running Theano 0.7/numpy 1.9.3 with direct linkage to the OpenBLAS master branch. After upgrading Theano to the ToT dev branch, I have noticed a significant performance drop from ~0.7s to ~10s when running the check_blas.py script. It has also become noticeably slower when training RNNs although the difference is not that huge.

I have tried to shuffle in/out different versions for each library and I've found that Theano is the one to blame. Somewhere between 0.7 and ToT there is a commit that causes this performance regression. Unfortunately, I ran out of time bisecting commits but I figured it might still be useful to report the issue.

As more information, my desktop is an HP Z620 workstation with 32 cores / 64GB RAM running Ubuntu 14.04.

**Comment by nouiz** [comment]
With a speed difference that big, I think the problem is that Theano is
probably not able to link directly anymore to OpenBLAS or that your current
OpenBLAS isn't multi-thread, where as it was multi-threads before.

Can you give the output of check_blas? It tell information related to that.

To know if it run in parallel, run check_blas in a shell and in another one
run top et see if the python process usage go over 100%

**Comment by sheckylin** [comment]
Thanks for the quick response. I got some training session running right now so I couldn't swap in ToT to run the test. However, as far as I could remember, the output is the same for both the dev branch and 0.7 - they both shows linkage to OpenBLAS and the environmental variables are set correctly. They also both appears to run in parallel. It is just that everything becomes very slow for ToT for no reason.

Here is the script output for my current (working) setup. I'll come back with the output on ToT in a few days.

Some Theano flags:
    blas.ldflags= -lopenblas
    compiledir= /usr/local/google/home/sheckylin/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64
    floatX= float64
    device= cpu
Some OS information:
    sys.platform= linux2
    sys.version= 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
    sys.prefix= /usr
Some environment variables:
    MKL_NUM_THREADS= None
    OMP_NUM_THREADS= 32
    GOTO_NUM_THREADS= None

Numpy config: (used when the Theano flag "blas.ldflags" is empty)
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/OpenBLAS/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
Numpy dot module: numpy.core._dotblas
Numpy location: /usr/local/lib/python2.7/dist-packages/numpy/__init__.pyc
Numpy version: 1.9.3

We executed 10 calls to gemm with a and b matrices of shapes (2000, 2000) and (2000, 2000).

Total execution time: 0.73s on CPU (with direct Theano binding to blas).

**Comment by sheckylin** [comment]
BTW, could it just be that we changed the gemm test matrix size from 2K to 5K in recent commits? If so, then it would probably explain the 10x speed drop. Looks like I am just being stupid ...

**Comment by nouiz** [comment]
This change isn't clear. What about just dropping the 2k timing and keep
only the 5k one? We could do the timing on a few CPU only to start with
more recent CPU.

Do you think it would be more clear like this?

**Comment by sheckylin** [comment]
Yeah, definitely! 2K is probably too small for recent hardware.

**Comment by cBournhonesque** [comment]
Hello.

I have spent the whole day trying to install Theano/CUDA/OpenBlas. (on Windows64bit/Anaconda64bit)

I managed to install the PiPy Theano version, and ran check_blas.py with OpenBlas (on Theano, not on Numpy) and no GPU. It took 5s.

Now I installed the bleeding edge version of Theano (what you're calling ToT, I assume?), and the check_blas.py takes me 85s.

So apparently you're telling me that nothing is wrong and it's just the test size that got bigger?

BTW, I was wondering. Can I safely uninstall Visual Studio 2013 (I installed it as a requirement for CUDA) ? In the official guide, they say that you can uninstall it. However in the file .theanorc, I have the line " compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin " which points to the file cl.exe.

Is this used only by CUDA (and nvcc, which is linked to CUDA?) or is it mandatory for theano?

Thanks for your help.

**Comment by sheckylin** [comment]
Increasing the test size from 2K to 5K is expected to increase the runtime by a factor of 2.5^3=15.625, which corresponds well to your timing result.

**Comment by nouiz** [comment]
The problem seem to have been answered.
