### ISSUE TITLE
 libcuda_ndarray.so: cannot open shared object file 

### ISSUE THREAD

**Issue by sutr90** [Theano/Theano#3711]
I was trying to get the theano up and running on computation grid and I always got following error after import

    >>> import theano
        ....
        libcuda_ndarray.so: cannot open shared object file 

After some googling I found following thread on google groups:
https://groups.google.com/forum/#!msg/theano-users/F0AuGH3g1CY/Sm0Rphqbp_8J

The issue is on Linux if ```config.compiledir``` flag contains colon (:) character. The compiler then cannot find the correct location of the compiled library. In my case it was really obscure bug, as the ```%(platform)s-%(processor)s``` substitution keys from ```config.compiledir_format``` contained colon as part of the grid's platform description.

The workaround is easy - set the compiledir to some safe value.
The fix should be easy as well, just sanitize the compiledir path.

**Comment by nouiz** [comment]
Thanks for the report. We are pretty busy, do you want to contribute this
to Theano?

**Comment by sutr90** [comment]
Okay, I will try to do the necessary changes in upcoming week. I will let you know here on the progress.

**Comment by nouiz** [comment]
Thanks!

**Comment by mronian** [comment]
Hi @sutr90,

Are you still working on it? Can I take this up?

**Comment by sutr90** [comment]
Hello @mronian,
sadly I haven't started yet. Feel free to fix it. ;)

**Comment by mronian** [comment]
@sutr90 Could you tell me how to reproduce the error on my local machine?

**Comment by sutr90** [comment]
There probably isn't an easy way to test it without mocking the environment. The problem in my case was on the grid computer. The call to `platfom.platform()` returned string with colon in it.

The relevant code is in https://github.com/Theano/Theano/blob/master/theano/gof/compiledir.py the relevant function is the `short_platform`@71 and the dictionary `compiledir_format_dict`. I think that the contents of this dictionry should be stripped of platform specific prohibied characters (eg. ?/*\:).

So the fix could be as easy as changing the return value of `short_platform` function.

For example:
```
return p.replace(':','-')
```

**Comment by mronian** [comment]
@sutr90  is PR #3822 the correct fix?

**Comment by sutr90** [comment]
Yes, that seems fine.
