### ISSUE TITLE
lib.cnmem ignored in .theanorc on Windows

### ISSUE THREAD

**Issue by bosmart** [Theano/Theano#3714]
No matter how I enter cnmem in the .theanorc file (Winpython), it's ignored (Theano says "CNMeM is disabled"). However, changing the default value of lib.cnmm in the cuda/__init__.py file to say 0.9 actually enables cnmem with a ~15% speedup.

**Comment by abergeron** [comment]
It should look like this in the file:

```
[lib]
cnmem=0.9
```

To confirm that it works you can print the value of `theano.config.lib.cnmem`.

Also it is possible that the theanorc file must be named `.theanorc.txt` on windows.

**Comment by bosmart** [comment]
Renaming the file to .theanorc.txt actually helped, thank you! It's interesting though because other settings from the file worked even if it didn't have .txt at the end (e.g. the device to use).
