### ISSUE TITLE
Add view_map/destroy_map support to as_op decorator.

### ISSUE THREAD

**Issue by mgermain** [Theano/Theano#3720]
At the moment the python function wrapped by the `as_op` decorator needs to return a new data allocation. It would ne interesting to support views or maybe even in place modification of the input.

**Comment by nouiz** [comment]
I edited the ticket name. Mostly, add to as_op() 2 parameter that default to None, view_map and destroy_map that will be the value used for that Op.

**Comment by nouiz** [comment]
I'm not sure this is good to do anymore This PR https://github.com/Theano/Theano/pull/3747 allow to make a Op subclass that don't implement make_node. With this way, it is easy to add view_map and destroy_map.

Personally, I prefer to not have too many ways of doing the same thing when this isn't useful. This new way of doing things is as easy from my point of view as as_op(). But if people disagree with me, we can still do this issue. Maybe I know to much about Theano to judge well how easy it is now, but doing a subclass and putting the same information in attribute or method seem as easy to me then passing that as parameter to function.

**Comment by nouiz** [comment]
I'll close this PR as I think this should not be done due to the change in PR gh-3747. If someone disagree, tell it.

**Comment by nouiz** [comment]
As nobody asked for that again and now we can do an op without a make_node(), I'll close this issue.
