### ISSUE TITLE
Wrong result when iterating over symbolic shapes

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3722]
Some slices are not correctly handled when we try to extract all scalar elements of a symbolic shape after a subtensor:
```python
>>> x = theano.shared(np.zeros((2,3,4,5), dtype='float32'))
>>> list(x.shape)  # OK
[Subtensor{int64}.0,
 Subtensor{int64}.0,
 Subtensor{int64}.0,
 Subtensor{int64}.0]
>>> list(x.shape[2:4])  # OK
[Subtensor{int64}.0, Subtensor{int64}.0]
>>> list(x.shape[2:])  # BUG
[]
```
I think the previous behaviour was to raise an Exception in the last 2 cases.

**Comment by lamblin** [comment]
Actually, Python 3 still raises an exception in the last 2 cases, because it does not consider `np.int64` as `numpy.Integrals`.

**Comment by nouiz** [comment]
I have a PR: https://github.com/Theano/Theano/pull/3727
