### ISSUE TITLE
theano gives “…Waiting for existing lock by unknown process…”

### ISSUE THREAD

**Issue by great-thoughts** [Theano/Theano#3723]
My code was working fine. However, now I am getting an error that says:

Using gpu device 0: GeForce GT 750M
WARNING (theano.gof.cmodule): ModuleCache.refresh() Found key without dll in cache, deleting it. /Users/mas/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpcm9_P6/key.pkl
INFO (theano.gof.compilelock): Waiting for existing lock by unknown process (I am process '2799')
INFO (theano.gof.compilelock): To manually release the lock, delete /Users/mas/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/lock_dir
I delete the folder lock_dir, but I still get the same message.

**Comment by nouiz** [comment]
This happen just when the cache is empty and multiple process try to
compile some code. You can ignore them. When the cache will contain enough
stuff, out won't happen frequently.

To get this less frequently, you can starts the process with some delay to
let Theano compile the code in only one process.

Fred

**Comment by great-thoughts** [comment]
Thanks for reply. I solved the problem by deleting .theano folder. After that the code was running as usual.

**Comment by Spandyie** [comment]
@great-thoughts I have same problem. What does deleting .theano folder do ? I notice that it houses `compiledir_macOS-10.16-x86_64-i386-64bit-i386-3.8.10-64`
`compiledir_macOS-10.16-x86_64-i386-64bit-i386-3.8.8-64` files.

**Comment by nouiz** [comment]
Note, Theano isn't maintained anymore. But it got forked here https://github.com/aesara-devs/aesara and that version is maintained.

Theano compiledir have a lock in that directory. When you delete this directory, you delete all the compiled cache and delete the lock at the same time.

This could be a harmless warning if you have multiple process running Theano in parallel. Just wait and all will come back to normal.
But it the problem isn't solved, then make sure to stop all Theano process, then deleting this directory delete the lock. So it should fix it.
