### ISSUE TITLE
ImportError: No module named cPickle

### ISSUE THREAD

**Issue by imoonkey** [Theano/Theano#3739]
I successfully installed theano, but when I try to import it, it shows the following message. I updated the package six to the latest version 1.1.0.

````
    import theano
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/__init__.py", line 52, in <module>
    from theano.gof import (
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/__init__.py", line 38, in <module>
    from theano.gof.cc import \
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 30, in <module>
    from theano.gof import link
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/link.py", line 18, in <module>
    from theano.gof.type import Type
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/type.py", line 17, in <module>
    from theano.gof.op import CLinkerObject
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/op.py", line 25, in <module>
    from theano.gof.cmodule import GCC_compiler
  File "/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 8, in <module>
    import six.moves.cPickle as pickle
ImportError: No module named cPickle
````

**Comment by nouiz** [comment]
I tried "import six.moves.cPickle as pickle" with the same six version and
I don't have this problem.

I suppose you have multiple six version installed. Uninstall all of them
and reinstall it.

On Thu, Dec 3, 2015 at 11:31 PM, imoonkey <notifications@github.com> wrote:
>
> I successfully installed theano, but when I try to import it, it shows
the following message. I updated the package six to the latest version
1.1.0.
>
>     import theano
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/__init__.py", line
52, in <module>
>     from theano.gof import (
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/__init__.py",
line 38, in <module>
>     from theano.gof.cc import \
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/cc.py", line
30, in <module>
>     from theano.gof import link
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/link.py", line
18, in <module>
>     from theano.gof.type import Type
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/type.py", line
17, in <module>
>     from theano.gof.op import CLinkerObject
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/op.py", line
25, in <module>
>     from theano.gof.cmodule import GCC_compiler
>   File
"/home/ubuntu/.local/lib/python2.7/site-packages/theano/gof/cmodule.py",
line 8, in <module>

**Comment by imoonkey** [comment]
Thanks! There was some version mismatch. It is fixed now!

**Comment by apuljain** [comment]
Hi, How did you resolve this? I'm getting the same error
import cPickle works fine but not import six.moves.cPickle

I guess it's conflicting with another six installed by default in /Library

I'm on Mac OS X early 2015

**Comment by nouiz** [comment]
Try to uninstall all six package, then reinstall it.

Try to not mix different python installation.

**Comment by NickRuiz** [comment]
I installed the latest version of six (version 1.10.0), which replaces the syntax of `import six.moves.cPickle as pickle` with `from six.moves import cPickle as pickle` (Python 2.7.10; Mac OS X 10.10.5).

**Comment by chenmengyang** [comment]
this solution "sudo easy_install --upgrade six" works for me, this

**Comment by nouiz** [comment]
If you have "pip" installed, it is better to use it instead of easy_install. So this get:

"sudo pip install -U six"

But your command also work frequently.

**Comment by nishkgp** [comment]
sudo easy_install --upgrade six . works

**Comment by michellehanan** [comment]
I both installed pip and easy_install. Failed to use pip to upgrade, however easy_install fixed the problem . No idea of this...

**Comment by nouiz** [comment]
Strange. I don't recommand using easy_install, but to use pip anymore. If you find the explanation, I would like to know it.

**Comment by richashree11** [comment]
while importing keras  i am getting below errors . i m not able to fix it. i am using Mac Machine   please guide me..


>>> import keras
Using Theano backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/Library/Python/2.7/site-packages/keras/backend/__init__.py", line 61, in <module>
    from .theano_backend import *
  File "/Library/Python/2.7/site-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/Library/Python/2.7/site-packages/theano/__init__.py", line 52, in <module>
    from theano.gof import (
  File "/Library/Python/2.7/site-packages/theano/gof/__init__.py", line 38, in <module>
    from theano.gof.cc import \
  File "/Library/Python/2.7/site-packages/theano/gof/cc.py", line 24, in <module>
    from theano.gof import graph
ImportError: cannot import name graph

**Comment by Sentient07** [comment]
Can you give us your present working directory ? It s possible that there is a clash in the name of two modules.

**Comment by richashree11** [comment]
its /users/nottiee

**Comment by richashree11** [comment]
problem fixed.. thanks github

**Comment by Sentient07** [comment]
Sorry, I meant to ask the content of pwd. Could you please show us all the files there ?

**Comment by richashree11** [comment]
could you tell me how to install openCV in mac Machine through terminal ,,,because by using pip installer  i am getting  error

**Comment by richashree11** [comment]
i m  getting  error   while installing opencv  through terminal

ravirajs-MacBook-Air:~ nottiee$ pip install OpenCV
Collecting OpenCV
  Could not find a version that satisfies the requirement OpenCV (from versions: )
No matching distribution found for OpenCV
ravirajs-MacBook-Air:~ nottiee$

**Comment by songjs1993** [comment]
this solution "sudo easy_install --upgrade six" works for me, too.

**Comment by arpita8** [comment]
<img width="688" alt="screen shot 2016-12-19 at 4 49 16 pm" src="https://cloud.githubusercontent.com/assets/22601715/21330380/281640a4-c60b-11e6-9817-61627230443c.png">
How can i correct it

**Comment by Sentient07** [comment]
@arpita8 use pip with sudo or use Anaconda environment.

**Comment by arpita8** [comment]
thanks

**Comment by arpita8** [comment]
I have tried sudo pip install -U six but it still gives me the error
<img width="336" alt="screen shot 2016-12-19 at 4 56 11 pm" src="https://cloud.githubusercontent.com/assets/22601715/21330592/2bf8f30a-c60c-11e6-9b51-671725d4a0d4.png">

**Comment by Sentient07** [comment]
Its `cPickle` and not `cPickel`. Please ask user related questions on StackOverflow or `theano-users` google group.
