### ISSUE TITLE
How to define a cost function with different weight.

### ISSUE THREAD

**Issue by muyinanhai** [Theano/Theano#3740]
Hi,all
I'm studying the tutorial of theano about logistic_sgd.py.

here is the code: http://deeplearning.net/tutorial/code/logistic_sgd.py

I'm curious about function:

def negative_log_likelihood(self, y):
    return -T.mean(T.log(self.p_y_given_x)[T.arange(y.shape[0]), y])

 If I want to set different weights for different class, how should I do?

Thank you.

**Comment by JesseLivezey** [comment]
Generally, you'll get more responses through the theano-users google group
https://groups.google.com/forum/#!forum/theano-users

Given ```self.p_y_given_x``` (n_batch, n_classes), ```y``` (n_batch), you could also have a variable
```w_y``` (n_classes) which contains a float for each class. Then you could compute
```
log_likelihood_per_example = T.log(self.p_y_given_x)[T.arange(y.shape[0]), y]
weighted_log_likelihood_per_example = log_likelihood * w_y[y]
weighted_average_negative_log_likelihood = -weighted_log_likelihood_per_example.mean()
```

**Comment by muyinanhai** [comment]
Thank you.
I tried, but failed.
here is my code:

 w_y=T.ivector('w_y')

cost = classifier.negative_log_likelihood(y,w_y)
def negative_log_likelihood(self, y,w_y):
    return -T.mean((T.log(self.p_y_given_x)[T.arange(y.shape[0]), y])*w_y[y])

the Error log:
function_module.UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 1 is not part of the computational graph needed to compute the outputs: w_y.

Can you help me ?
