### ISSUE TITLE
Compiles during import

### ISSUE THREAD

**Issue by simonzack** [Theano/Theano#3751]
I've installed the master branch of theano to get some cudnn compatibility fixes, now theano always compiles something on import which can take around 5 seconds, even when debug mode is enabled. This slows things down a bit when doing unit tests. Is this compilation necessary each time?

**Comment by nouiz** [comment]
We shouldn't compile at every import. But we do it the first time we import
the GPU back-end.

We do some test for old driver bug, there is a new Theano flag to stop this:

https://github.com/Theano/Theano/pull/3718

Would this help you?

**Comment by simonzack** [comment]
Thanks that works.
