### ISSUE TITLE
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by lqchn** [Theano/Theano#3755]
when I use:
              model.add(MaxPooling2D(pool_size=(2, 2)))
it throws this error:
              TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

how can i solve this problem?

**Comment by nouiz** [comment]
This isn't in the last release of Theano. You can use the development version of Theano to get it:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
