### ISSUE TITLE
GpuDnnConv3d slower than fallback

### ISSUE THREAD

**Issue by xeray** [Theano/Theano#3759]
Hi,

I've been playing around with different implementations of a fixed 3d-CNN architecture and suspect that the full potential of cuDNN is not really used - or something else must be strange with cuDNN itself.

Implementation 1: using conv3d2d
- The underlying 2d conv is automativally replaced by GpuDnnConvGradW (0.65s spent there)
- A lot of time is spent on conv3d2d.IncDiagonalSubtensor (1.1s) and GPU-transfers required for that (0.9s)
- The whole summed up to 4.0s

Implementation 2: using dnn_conv3d
- GpuDnnConv3dGradW takes 3s for computing less than all the 2d-convs in implementation 1
- The precise op in use was GpuDnnConv3dGradW{algo='none', inplace=False}. For implementation 1 the inplace option was set to True.
- Less GPU-transfer time (0.7s)
- Summed up to 4.2s 

Comments on my setup:
- 8 layer maxpooling CNN, x,y-input 199 pix, z-input 15 pix, my test case was to compute the gradient (wrt W,b) of the sum of the outputs.
- a lot of filters had size 1 along the z-axis, so were in fact 2d convs.
- Putting the z axis in the first spatial dimension was faster than in the last (as expected; z last summed up to 6.4s)
- I had corresponding runtime contributions from GradI and the forward conv, they scaled in the same way as GradW so I didn't mention them above.

So the big questions is, why is the direct 3d conv of dnn slower than the conv3d2d workaround?
Does "inplace=False" slow down the the computation? I suspect the the "inplace=True" of implementation 1 are placed there by the theano optimizer, because when I tried to set this flag manually for alternative 2, an exeption was raised and told that graphs must not contain inplace operations.

Is the assumption about inplace correct and what other causes could be around?

Cheers Marius

**Comment by nouiz** [comment]
Theano introduce manually the inplace. This can lower the memory usage and
speed up computation.

cudnn 3d conv isn't as much optimized as cudnn 2d convolution. So this is
normal. We have a GpuCorrMM op described in this page that could be faster
those 2 versions:

http://deeplearning.net/software/theano/library/tensor/nnet/conv.html
