### ISSUE TITLE
I think there is a problem with scan

### ISSUE THREAD

**Issue by ad26kt** [Theano/Theano#3760]
I wrote a code of GRU-RNN and faced a problem with scan.
the class variable will get input size, embedding size and hidden size and etc as input. the hidden size can be list or just a number(list means hidden stacks with different layer size, for example:
```javascript
class GRU-RNN( input_size = ~, ..., hidden_size = [100,200,200], ...) 
```
)

just because there can be variable stacks of hidden layer, I tried to store each weights and hidden states to lists.

here is the code of forward_propagation_one_step and scan:
```javascript
def feedforward_one_step(x_t, *ht_m1):
            
            # input to embedding layer
            e = self.E[:, x_t] + self.b_E
            ht_m1 = [state for state in ht_m1]
            print ht_m1[0]
            # embedding to hidden, hidden to hidden
            z, r, h_candidate, ht = list(), list(), list(), list()
            
            for idx, _ in enumerate(U):
                
                # embedding to hidden case :
                if(idx == 0):
                    z.append(T.nnet.sigmoid(T.dot(self.U[idx][0], e) + T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
                    r.append(T.nnet.sigmoid(T.dot(self.U[idx][1], e) + T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
                    h_candidate.append(T.tanh(T.dot(self.U[idx][2], e) + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) + self.b[idx][2]))
                    ht.append((T.ones_like(z[idx]) - z[idx]) * h_candidate + z[idx] * ht_m1[idx])
                    print ht[0]
                    
                # hidden to hidden case :
                else:
                    z.append(T.nnet.sigmoid(T.dot(self.U[idx][0], ht[idx-1]) + T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
                    r.append(T.nnet.sigmoid(T.dot(self.U[idx][1], ht[idx-1]) + T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
                    h_candidate.append(T.tanh(T.dot(self.U[idx][2], ht[idx-1]) + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) + self.b[idx][2]))
                    ht.append((T.ones_like(z[idx]) - z[idx]) * h_candidate + z[idx] * ht_m1[idx])
                    
            
            # final output
            #print '------'
            ot = T.nnet.softmax(T.dot(V, ht[-1]) + b_o)[0]
            return [ht, ot]
        
        #outputss = [dict(initial = T.zeros(size)) for size in self.hiddenSize] + [None]
        #h_and = [0]*(len(self.hiddenSize)+1)
        #h_and_o = [h_and[idx] for idx in range(len(h_and))]  
        [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
                             outputs_info = [dict(initial = T.zeros(size)) for size in self.hiddenSize]+[None],  
                             truncate_gradient = self.bptt_truncate)

```

If I wouldn't use variable length and just use fixed size hidden layer, it works well( in this case: i will fix the code like:
```javascript 
  [h1, h2, o], updates = theano.scan(feedforward_one_step, sequences = x,
                             outputs_info = [dict(initial = T.zeros(self.hiddenSize)), 
                                             dict(initial = T.zeros(self.hiddenSize)), None], 
                             non_sequences = [E_, b_E_, U1_, U2_, V_, W_, b_, b_o_], 
                             truncate_gradient = self.bptt_truncate, strict = True)
```

I think there is a problem with the original code of 'scan'
or not, are there any problem with my code?
Please help

**Comment by nouiz** [comment]
What make you think there is a problem? Do you have an error?

I wrote a code of GRU-RNN and faced a problem with scan.
the class variable will get input size, embedding size and hidden size and
etc as input. the hidden size can be list or just a number(list means
hidden stacks with different layer size, for example:

class GRU-RNN( input_size = ~, ..., hidden_size = [100,200,200], ...)

)

just because there can be variable stacks of hidden layer, I tried to store
each weights and hidden states to lists.

here is the code of forward_propagation_one_step and scan:

def feedforward_one_step(x_t, *ht_m1):

            # input to embedding layer
            e = self.E[:, x_t] + self.b_E
            ht_m1 = [state for state in ht_m1]
            print ht_m1[0]
            # embedding to hidden, hidden to hidden
            z, r, h_candidate, ht = list(), list(), list(), list()

            for idx, _ in enumerate(U):

                # embedding to hidden case :
                if(idx == 0):
                    z.append(T.nnet.sigmoid(T.dot(self.U[idx][0], e) +
T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
                    r.append(T.nnet.sigmoid(T.dot(self.U[idx][1], e) +
T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
                    h_candidate.append(T.tanh(T.dot(self.U[idx][2], e)
+ T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) + self.b[idx][2]))
                    ht.append((T.ones_like(z[idx]) - z[idx]) *
h_candidate + z[idx] * ht_m1[idx])
                    print ht[0]

                # hidden to hidden case :
                else:
                    z.append(T.nnet.sigmoid(T.dot(self.U[idx][0],
ht[idx-1]) + T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
                    r.append(T.nnet.sigmoid(T.dot(self.U[idx][1],
ht[idx-1]) + T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
                    h_candidate.append(T.tanh(T.dot(self.U[idx][2],
ht[idx-1]) + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) +
self.b[idx][2]))
                    ht.append((T.ones_like(z[idx]) - z[idx]) *
h_candidate + z[idx] * ht_m1[idx])


            # final output
            #print '------'
            ot = T.nnet.softmax(T.dot(V, ht[-1]) + b_o)[0]
            return [ht, ot]

        #outputss = [dict(initial = T.zeros(size)) for size in
self.hiddenSize] + [None]
        #h_and = [0]*(len(self.hiddenSize)+1)
        #h_and_o = [h_and[idx] for idx in range(len(h_and))]
        [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
                             outputs_info = [dict(initial =
T.zeros(size)) for size in self.hiddenSize]+[None],
                             truncate_gradient = self.bptt_truncate)

If I wouldn't use variable length and just use fixed size hidden layer, it
works well( in this case: i will fix the code like:

  [h1, h2, o], updates = theano.scan(feedforward_one_step, sequences = x,
                             outputs_info = [dict(initial =
T.zeros(self.hiddenSize)),
                                             dict(initial =
T.zeros(self.hiddenSize)), None],
                             non_sequences = [E_, b_E_, U1_, U2_, V_,
W_, b_, b_o_],
                             truncate_gradient = self.bptt_truncate,
strict = True)

I think there is a problem with the original code of 'scan'
or not, are there any problem with my code?
Please help

—
Reply to this email directly or view it on GitHub
<https://github.com/Theano/Theano/issues/3760>.

**Comment by ad26kt** [comment]
I forgot to post the error:

```javascript

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-da8e4dbc5da9> in <module>()
----> 1 model = GRU(len(vocab.index2word),1000, 200)

<ipython-input-46-4fddc070eb7d> in __init__(self, inputSize, embeddingSize, hiddenSize, bptt_truncate)
    104         [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
    105                              outputs_info = [dict(initial = T.zeros(size)) for size in self.hiddenSize]+[None],
--> 106                              truncate_gradient = self.bptt_truncate)
    107 
    108         # feedforward_one_step function

/Library/Python/2.7/site-packages/theano/scan_module/scan.pyc in scan(fn, sequences, outputs_info, non_sequences, n_steps, truncate_gradient, go_backwards, mode, name, profile, allow_gc, strict)
    743     # and outputs that needs to be separated
    744 
--> 745     condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
    746     if condition is not None:
    747         as_while = True

/Library/Python/2.7/site-packages/theano/scan_module/scan_utils.pyc in get_updates_and_outputs(ls)
    313                 return (ls[1].condition, _list(ls[0]), OrderedDict())
    314             else:
--> 315                 raise ValueError(error_msg)
    316         elif is_updates(ls[0]):
    317             if is_outputs(ls[1]):

ValueError: Scan cannot parse the return value of your lambda expression, which is: [[Elemwise{add,no_inplace}.0], Subtensor{int64}.0]
```

**Comment by ad26kt** [comment]
I forgot to post the error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call
last)<ipython-input-47-da8e4dbc5da9> in <module>()----> 1 model =
GRU(len(vocab.index2word),1000, 200)
<ipython-input-46-4fddc070eb7d> in __init__(self, inputSize,
embeddingSize, hiddenSize, bptt_truncate)
    104         [h,o], updates = theano.scan(feedforward_one_step,
sequences = x,
    105                              outputs_info = [dict(initial =
T.zeros(size)) for size in self.hiddenSize]+[None],--> 106
                 truncate_gradient = self.bptt_truncate)
    107
    108         # feedforward_one_step function
/Library/Python/2.7/site-packages/theano/scan_module/scan.pyc in
scan(fn, sequences, outputs_info, non_sequences, n_steps,
truncate_gradient, go_backwards, mode, name, profile, allow_gc,
strict)
    743     # and outputs that needs to be separated
    744 --> 745     condition, outputs, updates =
scan_utils.get_updates_and_outputs(fn(*args))
    746     if condition is not None:
    747         as_while = True
/Library/Python/2.7/site-packages/theano/scan_module/scan_utils.pyc in
get_updates_and_outputs(ls)
    313                 return (ls[1].condition, _list(ls[0]), OrderedDict())
    314             else:--> 315                 raise ValueError(error_msg)
    316         elif is_updates(ls[0]):
    317             if is_outputs(ls[1]):

ValueError: Scan cannot parse the return value of your lambda
expression, which is: [[Elemwise{add,no_inplace}.0],
Subtensor{int64}.0]


On Thu, Dec 10, 2015 at 7:09 AM, Frédéric Bastien <notifications@github.com>
wrote:

> What make you think there is a problem? Do you have an error?
>
> I wrote a code of GRU-RNN and faced a problem with scan.
> the class variable will get input size, embedding size and hidden size and
> etc as input. the hidden size can be list or just a number(list means
> hidden stacks with different layer size, for example:
>
> class GRU-RNN( input_size = ~, ..., hidden_size = [100,200,200], ...)
>
> )
>
> just because there can be variable stacks of hidden layer, I tried to store
> each weights and hidden states to lists.
>
> here is the code of forward_propagation_one_step and scan:
>
> def feedforward_one_step(x_t, *ht_m1):
>
> # input to embedding layer
> e = self.E[:, x_t] + self.b_E
> ht_m1 = [state for state in ht_m1]
> print ht_m1[0]
> # embedding to hidden, hidden to hidden
> z, r, h_candidate, ht = list(), list(), list(), list()
>
> for idx, _ in enumerate(U):
>
> # embedding to hidden case :
> if(idx == 0):
> z.append(T.nnet.sigmoid(T.dot(self.U[idx][0], e) +
> T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
> r.append(T.nnet.sigmoid(T.dot(self.U[idx][1], e) +
> T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
> h_candidate.append(T.tanh(T.dot(self.U[idx][2], e)
> + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) + self.b[idx][2]))
> ht.append((T.ones_like(z[idx]) - z[idx]) *
> h_candidate + z[idx] * ht_m1[idx])
> print ht[0]
>
> # hidden to hidden case :
> else:
> z.append(T.nnet.sigmoid(T.dot(self.U[idx][0],
> ht[idx-1]) + T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
> r.append(T.nnet.sigmoid(T.dot(self.U[idx][1],
> ht[idx-1]) + T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
> h_candidate.append(T.tanh(T.dot(self.U[idx][2],
> ht[idx-1]) + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) +
> self.b[idx][2]))
> ht.append((T.ones_like(z[idx]) - z[idx]) *
> h_candidate + z[idx] * ht_m1[idx])
>
>
> # final output
> #print '------'
> ot = T.nnet.softmax(T.dot(V, ht[-1]) + b_o)[0]
> return [ht, ot]
>
> #outputss = [dict(initial = T.zeros(size)) for size in
> self.hiddenSize] + [None]
> #h_and = [0]*(len(self.hiddenSize)+1)
> #h_and_o = [h_and[idx] for idx in range(len(h_and))]
> [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
> outputs_info = [dict(initial =
> T.zeros(size)) for size in self.hiddenSize]+[None],
> truncate_gradient = self.bptt_truncate)
>
> If I wouldn't use variable length and just use fixed size hidden layer, it
> works well( in this case: i will fix the code like:
>
> [h1, h2, o], updates = theano.scan(feedforward_one_step, sequences = x,
> outputs_info = [dict(initial =
> T.zeros(self.hiddenSize)),
> dict(initial =
> T.zeros(self.hiddenSize)), None],
> non_sequences = [E_, b_E_, U1_, U2_, V_,
> W_, b_, b_o_],
> truncate_gradient = self.bptt_truncate,
> strict = True)
>
> I think there is a problem with the original code of 'scan'
> or not, are there any problem with my code?
> Please help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Theano/Theano/issues/3760>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Theano/Theano/issues/3760#issuecomment-163412654>.
>



-- 
*___________________*
*Yanghoon Kim*

Seoul National University.
Department of Electrical and Computer Engineering.
Machine Intelligence Lab.
*Tel : +82 10-2297-5301
*Email : ad26kr@snu.ac.kr
*___________________*

**Comment by ad26kt** [comment]
I fotgot to post the error:

```javascript

---------------------------------------------------------------------------ValueError
                               Traceback (most recent call
last)<ipython-input-47-da8e4dbc5da9> in <module>()----> 1 model =
GRU(len(vocab.index2word),1000, 200)
<ipython-input-46-4fddc070eb7d> in __init__(self, inputSize,
embeddingSize, hiddenSize, bptt_truncate)    104         [h,o],
updates = theano.scan(feedforward_one_step, sequences = x,    105
                        outputs_info = [dict(initial = T.zeros(size))
for size in self.hiddenSize]+[None],--> 106
  truncate_gradient = self.bptt_truncate)    107     108         #
feedforward_one_step function
/Library/Python/2.7/site-packages/theano/scan_module/scan.pyc in
scan(fn, sequences, outputs_info, non_sequences, n_steps,
truncate_gradient, go_backwards, mode, name, profile, allow_gc,
strict)    743     # and outputs that needs to be separated    744 -->
745     condition, outputs, updates =
scan_utils.get_updates_and_outputs(fn(*args))    746     if condition
is not None:    747         as_while = True
/Library/Python/2.7/site-packages/theano/scan_module/scan_utils.pyc in
get_updates_and_outputs(ls)    313                 return
(ls[1].condition, _list(ls[0]), OrderedDict())    314
else:--> 315                 raise ValueError(error_msg)    316
 elif is_updates(ls[0]):    317             if is_outputs(ls[1]):
ValueError: Scan cannot parse the return value of your lambda
expression, which is: [[Elemwise{add,no_inplace}.0],
Subtensor{int64}.0]

```


On Thu, Dec 10, 2015 at 4:28 PM, Yanghoon Kim <ad26kt@gmail.com> wrote:

> I forgot to post the error:
>
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)<ipython-input-47-da8e4dbc5da9> in <module>()----> 1 model = GRU(len(vocab.index2word),1000, 200)
> <ipython-input-46-4fddc070eb7d> in __init__(self, inputSize, embeddingSize, hiddenSize, bptt_truncate)
>     104         [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
>     105                              outputs_info = [dict(initial = T.zeros(size)) for size in self.hiddenSize]+[None],--> 106                              truncate_gradient = self.bptt_truncate)
>     107
>     108         # feedforward_one_step function
> /Library/Python/2.7/site-packages/theano/scan_module/scan.pyc in scan(fn, sequences, outputs_info, non_sequences, n_steps, truncate_gradient, go_backwards, mode, name, profile, allow_gc, strict)
>     743     # and outputs that needs to be separated
>     744 --> 745     condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
>     746     if condition is not None:
>     747         as_while = True
> /Library/Python/2.7/site-packages/theano/scan_module/scan_utils.pyc in get_updates_and_outputs(ls)
>     313                 return (ls[1].condition, _list(ls[0]), OrderedDict())
>     314             else:--> 315                 raise ValueError(error_msg)
>     316         elif is_updates(ls[0]):
>     317             if is_outputs(ls[1]):
>
> ValueError: Scan cannot parse the return value of your lambda expression, which is: [[Elemwise{add,no_inplace}.0], Subtensor{int64}.0]
>
>
> On Thu, Dec 10, 2015 at 7:09 AM, Frédéric Bastien <
> notifications@github.com> wrote:
>
>> What make you think there is a problem? Do you have an error?
>>
>> I wrote a code of GRU-RNN and faced a problem with scan.
>> the class variable will get input size, embedding size and hidden size and
>> etc as input. the hidden size can be list or just a number(list means
>> hidden stacks with different layer size, for example:
>>
>> class GRU-RNN( input_size = ~, ..., hidden_size = [100,200,200], ...)
>>
>> )
>>
>> just because there can be variable stacks of hidden layer, I tried to
>> store
>> each weights and hidden states to lists.
>>
>> here is the code of forward_propagation_one_step and scan:
>>
>> def feedforward_one_step(x_t, *ht_m1):
>>
>> # input to embedding layer
>> e = self.E[:, x_t] + self.b_E
>> ht_m1 = [state for state in ht_m1]
>> print ht_m1[0]
>> # embedding to hidden, hidden to hidden
>> z, r, h_candidate, ht = list(), list(), list(), list()
>>
>> for idx, _ in enumerate(U):
>>
>> # embedding to hidden case :
>> if(idx == 0):
>> z.append(T.nnet.sigmoid(T.dot(self.U[idx][0], e) +
>> T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
>> r.append(T.nnet.sigmoid(T.dot(self.U[idx][1], e) +
>> T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
>> h_candidate.append(T.tanh(T.dot(self.U[idx][2], e)
>> + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) + self.b[idx][2]))
>> ht.append((T.ones_like(z[idx]) - z[idx]) *
>> h_candidate + z[idx] * ht_m1[idx])
>> print ht[0]
>>
>> # hidden to hidden case :
>> else:
>> z.append(T.nnet.sigmoid(T.dot(self.U[idx][0],
>> ht[idx-1]) + T.dot(self.W[idx][0], ht_m1[idx]) + self.b[idx][0]))
>> r.append(T.nnet.sigmoid(T.dot(self.U[idx][1],
>> ht[idx-1]) + T.dot(self.W[idx][1], ht_m1[idx]) + self.b[idx][1]))
>> h_candidate.append(T.tanh(T.dot(self.U[idx][2],
>> ht[idx-1]) + T.dot(self.W[idx][2], (ht_m1[idx] * r[idx])) +
>> self.b[idx][2]))
>> ht.append((T.ones_like(z[idx]) - z[idx]) *
>> h_candidate + z[idx] * ht_m1[idx])
>>
>>
>> # final output
>> #print '------'
>> ot = T.nnet.softmax(T.dot(V, ht[-1]) + b_o)[0]
>> return [ht, ot]
>>
>> #outputss = [dict(initial = T.zeros(size)) for size in
>> self.hiddenSize] + [None]
>> #h_and = [0]*(len(self.hiddenSize)+1)
>> #h_and_o = [h_and[idx] for idx in range(len(h_and))]
>> [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
>> outputs_info = [dict(initial =
>> T.zeros(size)) for size in self.hiddenSize]+[None],
>> truncate_gradient = self.bptt_truncate)
>>
>> If I wouldn't use variable length and just use fixed size hidden layer, it
>> works well( in this case: i will fix the code like:
>>
>> [h1, h2, o], updates = theano.scan(feedforward_one_step, sequences = x,
>> outputs_info = [dict(initial =
>> T.zeros(self.hiddenSize)),
>> dict(initial =
>> T.zeros(self.hiddenSize)), None],
>> non_sequences = [E_, b_E_, U1_, U2_, V_,
>> W_, b_, b_o_],
>> truncate_gradient = self.bptt_truncate,
>> strict = True)
>>
>> I think there is a problem with the original code of 'scan'
>> or not, are there any problem with my code?
>> Please help
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Theano/Theano/issues/3760>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Theano/Theano/issues/3760#issuecomment-163412654>.
>>
>
>
>
> --
> *___________________*
> *Yanghoon Kim*
>
> Seoul National University.
> Department of Electrical and Computer Engineering.
> Machine Intelligence Lab.
> *Tel : +82 10-2297-5301
> *Email : ad26kr@snu.ac.kr
> *___________________*
>



-- 
*___________________*
*Yanghoon Kim*

Seoul National University.
Department of Electrical and Computer Engineering.
Machine Intelligence Lab.
*Tel : +82 10-2297-5301
*Email : ad26kr@snu.ac.kr
*___________________*

**Comment by ad26kt** [comment]
I found the last comment quite difficult to recognize:


```javascript
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-da8e4dbc5da9> in <module>()
----> 1 model = GRU(len(vocab.index2word),1000, 200)

<ipython-input-46-4fddc070eb7d> in __init__(self, inputSize, embeddingSize, hiddenSize, bptt_truncate)
    104         [h,o], updates = theano.scan(feedforward_one_step, sequences = x,
    105                              outputs_info = [dict(initial = T.zeros(size)) for size in self.hiddenSize]+[None],
--> 106                              truncate_gradient = self.bptt_truncate)
    107 
    108         # feedforward_one_step function

/Library/Python/2.7/site-packages/theano/scan_module/scan.pyc in scan(fn, sequences, outputs_info, non_sequences, n_steps, truncate_gradient, go_backwards, mode, name, profile, allow_gc, strict)
    743     # and outputs that needs to be separated
    744 
--> 745     condition, outputs, updates = scan_utils.get_updates_and_outputs(fn(*args))
    746     if condition is not None:
    747         as_while = True

/Library/Python/2.7/site-packages/theano/scan_module/scan_utils.pyc in get_updates_and_outputs(ls)
    313                 return (ls[1].condition, _list(ls[0]), OrderedDict())
    314             else:
--> 315                 raise ValueError(error_msg)
    316         elif is_updates(ls[0]):
    317             if is_outputs(ls[1]):

ValueError: Scan cannot parse the return value of your lambda expression, which is: [[Elemwise{add,no_inplace}.0], Subtensor{int64}.0]```

**Comment by lamblin** [comment]
The return value of the step function cannot contain nested lists, which is what you have, just a flat list of variables.

**Comment by ad26kt** [comment]
I didn't know there is that kind of restriction on scan. Thanks
