### ISSUE TITLE
cmodule: asserts fail because of inconsistent slashes on mingw64

### ISSUE THREAD

**Issue by patrikhuber** [Theano/Theano#3775]
I got a failed assert in `theano/gof/cmodule.py` because of mismatching slashes:

```
File "C:/msys64/mingw64/lib/python3.5/site-packages\theano\gof\cmodule.py", line 303, in dlimport
    assert fullpath.startswith(rval.__file__)
```

When I print `fullpath` and `rval.__file__`, they look like this:

```
fullpath     : C:/Users/Patrik/AppData/Local/Theano/compiledir_Windows-10.0.10240-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.0-64/lazylinker_ext/lazylinker_ext.pyd

rval.__file__: C:/Users/Patrik/AppData/Local/Theano/compiledir_Windows-10.0.10240-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.0-64\lazylinker_ext\lazylinker_ext.pyd
```

The two slashes at the end are different (`/` vs `\`) and the `assert` fails.

The respective line in `master` is this one: [cmodule.py#L339](https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L339).

The same happens also later in the same file at:

```
File "C:/msys64/mingw64/lib/python3.5/site-packages\theano\gof\cmodule.py", line 1080, in module_from_key
    assert name.startswith(location)
```

```
name    : C:/Users/Patrik/AppData/Local/Theano/compiledir_Windows-10.0.10240-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.0-64\tmpru8ps4wz\ma1be92cb806d912fc1cd60d877958722.pyd
location: C:/Users/Patrik/AppData/Local/Theano/compiledir_Windows-10.0.10240-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.0-64/tmpru8ps4wz
```

[Here](https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L1176) the respective line in `master`.

I'm using [msys2-mingw64](msys2.github.io) with python3.5 and Theano from `pip`.

**Comment by lamblin** [comment]
An easy fix would be to call [`os.path.normpath`](https://docs.python.org/2/library/os.path.html#os.path.normpath) before doing the comparison.
Would you be able to submit a pull request with those changes if they fix your case?
Thanks.

**Comment by patrikhuber** [comment]
Cool, thanks for having a look. I'm not very familiar with python, the hint is thus very welcome.
Yep, I'll try it and do a pull request if it fixes the problem. I'll update this issue.

**Comment by patrikhuber** [comment]
It's kind of weird, but I've re-added the asserts in my code to add and test the fix, but the paths now have the same slashes in both cases. I've deleted the temporary files in AppData/Theano, but at the moment I can't make the issue appear again. I'll checkout Theano from git and try with that. It may take a bit.

**Comment by nouiz** [comment]
Could it be that you where using an old Theano? To my knowledge, there is
no such problem in the dev version. I know the last release have problem on
windows, bit I forget which one.

Fred
