### ISSUE TITLE
Installation problem PyCUDA import failed in theano.misc.pycuda_init

### ISSUE THREAD

**Issue by shubham1310** [Theano/Theano#3777]
Hi,
I am using Ubuntu 14.04 on my laptop
I tried to install theano using pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
and it installed successfully but when I run 
import theano
theano.test()
on terminal it shows:
Theano version 0.7.0.dev-d7e653ab8ce499d63dd8d5dee102f9ea0bf65bd1
theano is installed in /usr/local/lib/python2.7/dist-packages/theano
NumPy version 1.8.2
NumPy is installed in /usr/lib/python2.7/dist-packages/numpy
Python version 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
nose version 1.3.1
/usr/local/lib/python2.7/dist-packages/theano/misc/pycuda_init.py:34: UserWarning: PyCUDA import failed in theano.misc.pycuda_init
  warnings.warn("PyCUDA import failed in theano.misc.pycuda_init")
....................S........................................S...................../usr/local/lib/python2.7/dist-packages/theano/compile/profilemode.py:106: UserWarning: DEPRECATION WARNING: The ProfileMode is deprecated. Use the Theano flags/parameter to theano.function 'profile=True' instead of 'mode=ProfileMode'
  "DEPRECATION WARNING: The ProfileMode is deprecated. "
...../usr/lib/python2.7/dist-packages/numpy/lib/nanfunctions.py:319: RuntimeWarning: All-NaN slice encountered
  warnings.warn("All-NaN slice encountered", RuntimeWarning)
/usr/lib/python2.7/dist-packages/numpy/lib/nanfunctions.py:220: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
............................................../usr/local/lib/python2.7/dist-packages/theano/gof/vm.py:852: UserWarning: CVM does not support memory profile, using Stack VM.
  'CVM does not support memory profile, using Stack VM.')
...........SS.............0.0581646137166
0.0581646137166
0.0581646137166
0.0581646137166
..........................................................................................................................................................SS..S...SSSSSSSSSSSSSSSSSSSSSSS../usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/type.py:586: UserWarning: config.experimental.unpickle_gpu_on_cpu is set to True. Unpickling CudaNdarray as numpy.ndarray
  warnings.warn("config.experimental.unpickle_gpu_on_cpu is set to True. Unpickling CudaNdarray as numpy.ndarray")
.SSSSSSSSSSSSSS...........S.....SSSSS.................................................................S.S.......................................
.
.
...........
....S...................S........................../usr/local/lib/python2.7/dist-packages/theano/scan_module/scan.py:1019: Warning: In the strict mode, all neccessary shared variables must be passed as a part of non_sequences
  'must be passed as a part of non_sequences', Warning)
.........................SSSSSSSSSSSSSS......................................./usr/lib/python2.7/dist-packages/scipy/sparse/data.py:60: ComplexWarning: Casting complex values to real discards the imaginary part
  return self._with_data(self.data.astype(t))
/usr/local/lib/python2.7/dist-packages/theano/sparse/tests/test_basic.py:2342: ComplexWarning: Casting complex values to real discards the imaginary part
  expected = data.toarray().astype(o_dtype)
...../usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:728: SparseEfficiencyWarning: Changing the sparsity structure of a csc_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:728: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)
.............S.........................................S........S................................................................../usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:350: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, try using <, >, or !=, instead.
  "try using <, >, or !=, instead.", SparseEfficiencyWarning)
/usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py:316: SparseEfficiencyWarning: Comparing sparse matrices using >= and <= is inefficient, using <, >, or !=, instead.
  "using <, >, or !=, instead.", SparseEfficiencyWarning)
...................................S................................................../usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/__init__.py:111: UserWarning: The `image_shape` keyword argument to `tensor.nnet.conv2d` is deprecated, it has been renamed to `input_shape`.
  warnings.warn("The `image_shape` keyword argument to "
.......................................................................S..SS............................................./usr/local/lib/python2.7/dist-packages/theano/tensor/signal/tests/test_conv.py:38: UserWarning: theano.tensor.signal.conv2d() now outputs a 2d tensor when both inputs are 2d. To disable this warning, set the Theano flag warn.signal_conv2d_interface to False
  output = sym_conv2d(input, filters)
./usr/lib/python2.7/unittest/case.py:331: UserWarning: theano.tensor.signal.conv2d() now outputs a 2d tensor when both inputs are 2d. To disable this warning, set the Theano flag warn.signal_conv2d_interface to False
  testMethod()
...................ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_upcast_elemwise_constant_inputs'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_upcast_elemwise_constant_inputs'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_upcast_elemwise_constant_inputs'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_upcast_elemwise_constant_inputs'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_upcast_elemwise_constant_inputs'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../usr/lib/python2.7/unittest/case.py:331: DeprecationWarning: stack(*tensors) interface is deprecated, use stack(tensors, axis=0) instead.
  testMethod()
................................................................................................................................/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_basic.py:7541: UserWarning: Tile op is deprecated, use tile function instead.
  [Tile(ndim)(advec, aivec_val)],
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_basic.py:7549: UserWarning: Tile op is deprecated, use tile function instead.
  [Tile(ndim)(admat, aivec_val)],
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_basic.py:7557: UserWarning: Tile op is deprecated, use tile function instead.
  [Tile(ndim)(adtens4, aivec_val)],
......................................./usr/local/lib/python2.7/dist-packages/theano/scalar/basic.py:1670: DeprecationWarning: Division of two integer types with x / y is deprecated, please use x // y for an integer division.
  if (x / y).type in discrete_types:
/usr/local/lib/python2.7/dist-packages/theano/scalar/basic.py:1670: DeprecationWarning: Division of two integer types with x / y is deprecated, please use x // y for an integer division.
  if (x / y).type in discrete_types:
/usr/local/lib/python2.7/dist-packages/theano/scalar/basic.py:1670: DeprecationWarning: Division of two integer types with x / y is deprecated, please use x // y for an integer division.
  if (x / y).type in discrete_types:
..........................................................S............................................................................................................................................................../usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_basic.py:6768: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  a = numpy.empty(1e4, dtype=dtype)['f1']
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_basic.py:6769: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  b = numpy.empty(1e4, dtype=dtype)['f1']
..............................................................................................................................................................................S..SSSS.S............................................................../usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:193: UserWarning: Tile op is deprecated, use tile function instead.
  f1 = theano.function([x], BinCountOp()(x, weights=None))
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:194: UserWarning: Tile op is deprecated, use tile function instead.
  f2 = theano.function([x, w], BinCountOp()(x, weights=w))
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:201: UserWarning: Tile op is deprecated, use tile function instead.
  f3 = theano.function([x], BinCountOp(minlength=23)(x, weights=None))
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:202: UserWarning: Tile op is deprecated, use tile function instead.
  f4 = theano.function([x], BinCountOp(minlength=5)(x, weights=None))
./usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:225: UserWarning: Tile op is deprecated, use tile function instead.
  [BinCountOp()(x,None)],
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:233: UserWarning: Tile op is deprecated, use tile function instead.
  [BinCountOp()(x, weights=weights)],
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:242: UserWarning: Tile op is deprecated, use tile function instead.
  [BinCountOp(minlength=60)(x, weights=weights)],
/usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_extra_ops.py:249: UserWarning: Tile op is deprecated, use tile function instead.
  [BinCountOp(minlength=5)(x, weights=weights)],
..........................S............../usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:534: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return transpose(axes)
........................................../usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:729: DeprecationWarning: The 'full' option is deprecated in favor of 'reduced'.
For backward compatibility let mode default.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:729: DeprecationWarning: The 'full' option is deprecated in favor of 'reduced'.
For backward compatibility let mode default.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:729: DeprecationWarning: The 'full' option is deprecated in favor of 'reduced'.
For backward compatibility let mode default.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:729: DeprecationWarning: The 'full' option is deprecated in favor of 'reduced'.
For backward compatibility let mode default.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:729: DeprecationWarning: The 'full' option is deprecated in favor of 'reduced'.
For backward compatibility let mode default.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:733: DeprecationWarning: The 'economic' option is deprecated.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:733: DeprecationWarning: The 'economic' option is deprecated.
  warnings.warn(msg, DeprecationWarning)
/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py:733: DeprecationWarning: The 'economic' option is deprecated.
  warnings.warn(msg, DeprecationWarning)
........../usr/local/lib/python2.7/dist-packages/theano/tensor/tests/test_opt.py:4024: UserWarning: Tile op is deprecated, use tile function instead.
  f = theano.function([var], Tile(ndim)(var, (1,)*ndim), mode=mode)
...............................S.......................................................S.S..S.........SS...........................ERROR (theano.gof.opt): EquilibriumOptimizer max'ed out by 'local_add_canonizer'. You can safely raise the current threshold of 5.000000 with the theano flag 'optdb.max_use_ratio'.
...................S.......S............S................................................................................................................................................/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:875: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return argsort(axis, kind, order)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:875: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return argsort(axis, kind, order)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:875: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return argsort(axis, kind, order)
/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:875: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return argsort(axis, kind, order)
............................................................................................................................................................S/usr/lib/python2.7/unittest/case.py:331: UserWarning: consider_constant() is deprecated, use zero_grad() or disconnected_grad() instead.
  testMethod()
...........................................SS......SSSSS...SSSSS.......S.........SS.....................
----------------------------------------------------------------------
Ran 2892 tests in 3838.646s

OK (SKIP=108)

Any pointer would be a great help

**Comment by nouiz** [comment]
It is normal to have some tests skipped. All the one that run passed, so it
is good.

Most of the warning are from newer numpy.
