### ISSUE TITLE
why theano with gpu is slower than cpu?

### ISSUE THREAD

**Issue by HadXu** [Theano/Theano#3778]
I run cnn on Geforce gt 635m,with this gpu costs 104s,and with cpu,only costs 72s!

**Comment by nouiz** [comment]
The 635m is a low end gpu. Your CPU is probably just faster then your CPU.

The other option is that some operation aren't moved to the GPU. Even if
you fix this, I would not expect good speed up from this GPU

**Comment by lamblin** [comment]
Also, for such questions or requests for support, please use the "theano-users" mailing list, or stackoverflow with the "theano" tag.
We are trying to keep the tickets for bug reports and feature requests.
