### ISSUE TITLE
TypeError when using mode=ProfileMode

### ISSUE THREAD

**Issue by rubenvereecken** [Theano/Theano#3782]
I don't have the exact error anymore, I'm sorry, but here goes.

TypeError on [this line](https://github.com/Theano/Theano/blob/master/theano/compile/mode.py#L331), saying `clone` does not have the keyword `optimizer`. I'm still not entirely sure about calling Python methods with arguments as keywords without extracting them from kwargs, so I can't be too about what went wrong here. Just though I'd give you a heads up, maybe someone else can spot something out of order on sight.

Installing theano through conda fixed it for now.

**Comment by nouiz** [comment]
ProfileMode is deprecated. Use the Theano flag profile=True instead.

I would recommand that you continue to use the development version. There is too much upgrade in it.

**Comment by rubenvereecken** [comment]
Didn't know about ProfileMode, I found it on some forum and it was still in the source so I figured it worked. Thanks, @nouiz ! I'll upgrade to dev version again.

**Comment by nouiz** [comment]
I fixed it anyway in this PR: https://github.com/Theano/Theano/pull/3783

thanks for the report.
