### ISSUE TITLE
cula RuntimeError (libcula.so not found)

### ISSUE THREAD

**Issue by oeway** [Theano/Theano#3785]
Hi, 

I just upgraded theano, and it keep complaining that "RuntimeError, libcula.so not found". (I am running Ubuntu 14.04, and I don't have cula installed.)

I think the possible solution could be change cula.py by adding "RuntimeError" in the except line:
```
try:
    from scikits.cuda import cula
    cula_available = True
except (ImportError, OSError, RuntimeError, pkg_resources.DistributionNotFound):
    pass
```

**Comment by nouiz** [comment]
That seem resonable. Do you want to make a PR? I can make one if you prefer.

Fred

**Comment by oeway** [comment]
OK, I will do it.
