### ISSUE TITLE
str() needed around self.out_mode in conv.py

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#3789]
```
  File "/home/dl/anaconda2/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 149, in conv2d
    imshp=imshp, kshp=kshp, nkern=nkern, bsize=bsize, **kargs)
  File "/home/dl/anaconda2/lib/python2.7/site-packages/theano/tensor/nnet/conv.py", line 531, in __init__
    raise Exception("Mode %s not implemented" % self.out_mode)
TypeError: not all arguments converted during string formatting
```

**Comment by nouiz** [comment]
Normally, self.out_mode should be a string. So that ConvOp instance got bad
parameter when it was created.

Yes, the error should get thrown correctly. But I think we should also fix
this upstream. Can you give us a way to reproduce this? The full stack
trace could also help.

**Comment by dwf** [comment]
It's from someone attempting to use a tuple as the out_mode.

**Comment by nouiz** [comment]
This is only supported in the new interface, not the old interface.

Do you call theano.tensor.nnet.conv2d() or theano.tensor.nnet.conv.conv2d()?

Do you still have the full stack trace? Was this when building the graph or
during optimization?
