### ISSUE TITLE
Add to documentation that max_pool_2d's downscaling factor should be known at graph build time.

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [Theano/Theano#3800]
The tutorial http://deeplearning.net/tutorial/lenet.html says:

> Note that compared to most Theano code, the `max_pool_2d` operation is a little special. It requires the downscaling factor `ds` (tuple of length 2 containing downscaling factors for image width and height) to be known at graph build time. This may change in the near future.

If that's still true with Theano's current version, one should probably add this information in [theano.tensor.signal.downsample.max_pool_2d's documentation](http://deeplearning.net/software/theano/library/tensor/signal/downsample.html).

If not, one should update the tutorial.

**Comment by nouiz** [comment]
For now, it still must be ints. I updated the doc in this PR:

https://github.com/Theano/Theano/pull/3801

thanks
