### ISSUE TITLE
Can't import register_opt on CPU

### ISSUE THREAD

**Issue by TiRune** [Theano/Theano#3837]
Working on bleeding edge Theano, get this issue:

======================================================================
ERROR: Failure: ImportError (cannot import name as_cuda_ndarray_variable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/data/Projects/scyfernn/tests/layers/test_activation_layer.py", line 5, in <module>
    from tests.utils import func_fact, elicit_error, \
  File "/mnt/data/Projects/scyfernn/tests/utils.py", line 7, in <module>
    from NN.layers.identity_layer import IdentityLayer
  File "/mnt/data/Projects/scyfernn/NN/layers/__init__.py", line 20, in <module>
    from pooling_layer import PoolingLayer
  File "/mnt/data/Projects/scyfernn/NN/layers/pooling_layer.py", line 1, in <module>
    import pooling_ops
  File "/mnt/data/Projects/scyfernn/NN/layers/pooling_ops.py", line 698, in <module>
    from theano.sandbox.cuda.opt import register_opt
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/sandbox/cuda/opt.py", line 22, in <module>
    from theano.sandbox.cuda import as_cuda_ndarray_variable
ImportError: cannot import name as_cuda_ndarray_variable
-------------------- >> begin captured logging << --------------------
theano.sandbox.cuda: WARNING: CUDA is installed, but device gpu0 is not available  (error: Unable to get the number of gpus available: no CUDA-capable device is detected)
--------------------- >> end captured logging << ---------------------

I realize that this is fixed when I turn on my gpu, but I want to have my code work for CPU as well. Fixed this in Theano, and making a pull request soon for this.

Quick question, would it be better form to only include optimization in the DB by using register_opt if cuda is installed by checking cuda_available, or is it better form to just register the optimizations and check inside the optimization if cuda is available? I believe something can be said for both.

**Comment by nouiz** [comment]
The traceback seem from an old version of Theano. Can you uninstall Theano
a few time to make sure to remove all version and reinstall the development
version like this:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by nouiz** [comment]
To prevent problems with import your code currently do:

from theano.sandbox.cuda.opt import register_opt

With the dev version of Theano, you can do:

from theano.sandbox.cuda import register_opt

register_opt is defined inside `cuda/__init__.py` now.

But your PR seem fine too.

**Comment by TiRune** [comment]
I think I fetched and rebased Theano this morning (it's 18:00) now, might be that I was already behind?

I did from theano.sandbox.cuda.opt import register_opt

Now I do theano.sandbox.cuda import register_opt

Seems to have fixed things on HEAD is now at cb79538

On the same commit, I'm getting the following error when running the same cpu experiment:
```python
ERROR (theano.gof.opt): SeqOptimizer apply <theano.scan_module.scan_opt.ScanInplaceOptimizer object at 0x7f4c4abb9350>
ERROR:theano.gof.opt:SeqOptimizer apply <theano.scan_module.scan_opt.ScanInplaceOptimizer object at 0x7f4c4abb9350>
ERROR (theano.gof.opt): Traceback:
ERROR:theano.gof.opt:Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/scan_module/scan_opt.py", line 1087, in apply
    alloc_ops += (theano.sandbox.cuda.GpuAlloc,
AttributeError: 'module' object has no attribute 'GpuAlloc'
```

Should perhaps make a seperate issue for this, but it seems sorta related.

**Comment by TiRune** [comment]
That last part is fixed here now:
https://github.com/Scyfer/Theano/commit/bf5df73656f499b927c72d2680c55b1bf21335d3

Should I add that to the PR?

**Comment by TiRune** [comment]
Seems that with the most recent version of Theano, and the fix in our code:
```python
+from theano.sandbox.cuda import register_opt
-from theano.sandbox.cuda.opt import register_opt
```
This is fixed! Can close this issue now
