### ISSUE TITLE
Cannot use theano.misc.pkl_utils.dump

### ISSUE THREAD

**Issue by JacobIsrael123** [Theano/Theano#3839]
In the webpage : http://deeplearning.net/software/theano/library/misc/pkl_utils.html#theano.misc.pkl_utils.load

There is example like
```python
>>> import theano
>>> foo_1 = theano.shared(0, name='foo')
>>> foo_2 = theano.shared(1, name='foo')
>>> with open('model.zip', 'w') as f:
...     dump((foo_1, foo_2, numpy.array(2)), f)
>>> numpy.load('model.zip').keys()
['foo', 'foo_2', 'array_0', 'pkl']
>>> numpy.load('model.zip')['foo']
array(0)
>>> with open('model.zip') as f:
...     foo_1, foo_2, array = load(f)
>>> array
array(2)
```
I tried but it reports that the ```dump``` is not defined. 
I tried many ways to import the ```theano.misc.pkl_utils.dump```, but is doesn't work.
Then I use Pycharm to check the source code. I did not find ```dump``` defined in ```theano.misc.pkl_utils```
I checked, my theano version is indeed 0.7.0. 

Could anyone help with this?

**Comment by nouiz** [comment]
This need the develpment version of Theano:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

It is pretty stable, you can use it. If you still have problems, you can reopen this issue.
