### ISSUE TITLE
typo in sparse.opt.py - ) missing

### ISSUE THREAD

**Issue by jojolalpin** [Theano/Theano#3840]
Hi,

In file theano.sparse.opt.py, class StructuredDotCSC : 
lines 351 and 352, 2 ")" are missing before last ";"
const npy_int32 * __restrict__ Dind = (npy_int32*)PyArray_DATA(%(a_ind)s;
const npy_int32 * __restrict__ Dptr = (npy_int32*)PyArray_DATA(%(a_ptr)s;
should be
const npy_int32 * __restrict__ Dind = (npy_int32*)PyArray_DATA(%(a_ind)s);
const npy_int32 * __restrict__ Dptr = (npy_int32*)PyArray_DATA(%(a_ptr)s);

StructuredDotCSR is ok.

Thanks to all devs for this amazing library.

**Comment by nouiz** [comment]
Good catch. Do you want to make a PR? This would also need update to the
test to detect this to be sure it don,t get broken again.

thanks

**Comment by jojolalpin** [comment]
Hi Frédéric,

I never made a PR.
I wanted to do it, seems easy, but as I use the master directly with pip I
am not sure it will be the right version (not bleeding edge).
I made changes directly in my system files and it works.
I thought for a small typo (at compile it says the ")" is missing before
";") someone would do it quicker than me.

If you want me to make one, tell me, I will learn something.

++


2016-01-06 22:20 GMT+01:00 Frédéric Bastien <notifications@github.com>:

**Comment by nouiz** [comment]
the PR was merged, so closing. thanks
