### ISSUE TITLE
Multiplication between a NaN and a constant of 0 give 0 instead of NaN.

### ISSUE THREAD

**Issue by MarcCote** [Theano/Theano#3848]
This is issue is probably related to some optimizations done by Theano when multiplying with a constant with a value of zero. Here is an example: 
```python
import numpy as np
import theano
import theano.tensor as T
(np.array([0, 0, np.nan]) * T.zeros(3)).eval()
```
outputs `([ 0.,  0.,  0.])`.

Whereas
```python
(np.array([0, 0, np.nan]) * theano.shared(np.array([0., 0, 0]))).eval()
```
correctly ouputs `array([  0.,   0.,  nan])`.

My `theano.version.full_version` is `'0.7.0.dev-RELEASE'`, but @mgermain tested it with `0.7.0.dev-9367e589ef2f876e56d6221800043bd61b2c29f2`.

Interestingly, with my current version this
```python
(np.array([np.nan]) * T.zeros(3)).eval()
```
ouputs `array([ nan,  nan,  nan])` but @mgermain gets `array([ 0.,  0.,  0.])`.

**Comment by Sentient07** [comment]
Yes, it seems to be a bug to me. The same mathematical operation when done by compiling functions gives a different output and when done using ```shared``` variable gives a different output. Multiplication (even the ```tensor.dot()```) does not return ```numpy.nan``` (as expected) when using shared variables.
cc : @nouiz

**Comment by nouiz** [comment]
If this is a bug or a feature is for debate :)

Theano will optimize multiplication by 0. We do some other optimization
related to 0.

There was some work started for this:
https://github.com/Theano/Theano/pull/1294/files

But mostly, it got dropped and I don't remember why. Maybe we didn't agreed
on the solution or we didn't got enough time to finish this on our side.

**Comment by Sentient07** [comment]
@nouiz I'm really glad to work on this. If the idea is still up, could you please help me with catching up on what's been done and what is to be done ?

**Comment by abergeron** [comment]
I'm not convinced there is anything to be done.  Optimizing away things such as multiplication by zero is important for performance and I don't think that the cost of trying to detect when the other input is NaN is worth it.

The detection code is guaranteed to be very complex and full of corner cases and almost impossible to maintain.  I think we should accept some tradeoffs like this one.

**Comment by lamblin** [comment]
Agreed with @abergeron, this is just a consequence of the design of Theano as an optimizing compiler.
