### ISSUE TITLE
segfault from sending None to a compiled function

### ISSUE THREAD

**Issue by jonathanstrong** [Theano/Theano#3849]
hey, 

I traced a segfault to accidentally sending the Python `None` object to a compiled theano function. Although the original case was a super complicated graph, I just reproduced this with a very simple example:

```
>>> import theano
Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled)
>>> import theano.tensor as T
>>> x = T.matrix('x')
>>> y = T.matrix('y')
>>> z = x.dot(y)
>>> f = theano.function([x, y], z)
>>> f(np.ones((10,10)).astype('float32'), None)
Segmentation fault (core dumped)
```

Is this expected behavior? I can't imagine it would be, since if you accidentally send float64 to the same function it will raise a `TypeError`. 

In the unlikely case that it is expected, I think theano functions should not segfault on `None`. It took a lot of time to trace this. 

If it is not expected, what could I do to be helpful in tracking it down? 

I'm using version 0.7.0.dev-3431cc8d102fc075cf50bf1216a45b0da13f1f26

**Comment by nouiz** [comment]
If I run this on CPU, I get as expected an exception, but I get as you a
segfault on the GPU. It is not normal. Thanks for the report.

**Comment by lamblin** [comment]
I just tried it on the current master, with the new GPU back-end, and it raises an exception as expected.
