### ISSUE TITLE
Compute gradient through conditional ending of scan

### ISSUE THREAD

**Issue by dhammack** [Theano/Theano#3852]
Hi!

I have a recurrent model where I'd like to do a conditional scan and allow the model to decide to stop early. Setting up the until object is easy enough but I'm getting a theano.gradient.DisconnectedInput graph error when I try to take the gradient with respect to the parameters that control the exiting of the scan loop. The following simplified example illustrates the issue:

```

#replicate a problem encountered in theano scan where gradient is not computed 
#through the termination criteria
import theano.tensor as T
import theano
def fn(x, learnable_float):
	xi = x + 1
	stop_now = theano.scan_module.until(xi + learnable_float > 5)
	return xi, stop_now

x_0 = T.constant(0)
learnable_float = T.scalar()

outputs, _ = theano.scan(fn=fn, 
						n_steps=1024, 
						sequences=None,
						non_sequences=[learnable_float],
						outputs_info = [dict(initial=x_0, taps=[-1])])
x_n = outputs[-1]
#note x_n = 5 - learnable_float + 1?

#this works fine!
g_test = theano.gradient.grad(cost = x_n, wrt=x_0)

#this fails!
g = theano.gradient.grad(cost=x_n, wrt=learnable_float)

```
And running this example gives me the result:

```
Traceback (most recent call last):
  File "theano_scan_issue.py", line 25, in <module>
    g = theano.gradient.grad(cost=x_n, wrt=learnable_float)
  File "C:\Anaconda\lib\site-packages\theano\gradient.py", line 545, in grad
    handle_disconnected(elem)
  File "C:\Anaconda\lib\site-packages\theano\gradient.py", line 532, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of
the cost, or is used only by a non-differentiable operator: <TensorType(float32, scalar)>
Backtrace when the node is created:
  File "theano_scan_issue.py", line 11, in <module>
    learnable_float = T.scalar()
```

But in this example x_n is a linear function of learnable_float! The ability to *learn to* control the ending of scan is a very powerful mechanism for recurrent architectures, it would be great to see this in Theano.  

So I guess I'm wondering: 

1) Is this behavior expected and should I be able to compute gradients though the conditional ending of scan?
2) If not, can this get added or is there a workaround?

Thanks,
Daniel

**Comment by lamblin** [comment]
The condition for the ending of `scan` is a discrete number, for which there is not mathematical gradient that could be defined. It would be akin to taking the gradient of a cost wrt the size of a vector.
You could try to compute an alternative expression of `learnable_float` to minimize, and use the gradient of that to update `learnable_float`. Alternatively, you could explicitly specify a pseud-gradient expression for `learnable_float` (or other variables) and pass them in the `known_grads` dictionary of `theano.grad()`.
