### ISSUE TITLE
Is there any way to cache the theano compiling result?

### ISSUE THREAD

**Issue by daweileng** [Theano/Theano#3863]
I ask this question because the compiling process of theano is quite time consuming, and what making it worse is that each time I run the code, the function will be recompiled. So, is there any way to make theano cache the previous compiling result if there is no code change?

**Comment by nouiz** [comment]
I understand that you probably don't need an answer, but for the record,
here is what I started to write before you close this issue:

First use Theano development version. There is much speed up for that.

If that isn't enough, you can pickle and unpickled Theano function. So you
can do your own manual caching.

**Comment by daweileng** [comment]
Yes I'm using the old 0.7.0 version. And pickling the function, I never thought of that, I'll give it a try. Thanks~

**Comment by nouiz** [comment]
For the last release, to don,t have during unpickling the re-optimization
(we changed the default), set the Theano flag:
reoptimize_unpickled_function=False.
