### ISSUE TITLE
Update Theano PyPi package

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#3864]
Any way to get more regular releases of Theano to pypi? It has been ~10 months since the last release even though there has been a lot of work on the repos.

**Comment by kmike** [comment]
+1. If making releases is too cumbersome it may be automated - see https://docs.travis-ci.com/user/deployment/pypi. An example: scrapy uses this setup to make pypi releases from git tags - see https://github.com/scrapy/scrapy/blob/57f99fc34ebc7cb8a2a84371b89552e6623c9e9d/.travis.yml#L27 - it makes a release each time git tag is added X.Y.Z (e.g. 1.0.0)

**Comment by nouiz** [comment]
The time consumming part is making sure Theano is stable on all platform
(linux, mac and windows). The linux part is easy, the mac and windows isn't.

If we had travis testing with GPU and testing on windows and mac, it would
be much easier...

If someone want to set up appveyor or another buildbot for Theano on
windows (even without GPU) it would help a lot.

**Comment by rbharath** [comment]
+1 on this (not sure if I can commit the time to set up appveyor right now though).

**Comment by nouiz** [comment]
Just to update that we did a release. If someone is ready to set up a buildbot like travis for windows, it would help futur release. There is free travis like for windows.
