### ISSUE TITLE
Clarify Manual OpenBlas Install Instructions

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#3865]
[The install instructions for Ubuntu call out manually building OpenBlas](https://github.com/Theano/Theano/blob/a60bf55d7f5259d1c78c93d4d7b129c1d237860b/doc/install_ubuntu.txt#L176-L196) however they suggest this _might_ not be needed on Ubuntu 14.04+.

That being said, the [install script from `deeplearningparis/dl-machine`](https://github.com/deeplearningparis/dl-machine/blob/bf87365c462e28f0f9936d4bdd6a0c2bcfb92c23/scripts/install-deeplearning-libraries.sh#L21-L37) still seems to build OpenBlas even though it is based on 14.04. is that recommended? Will performance be better?

**Comment by nouiz** [comment]
It depend how OpenBLAS in Ubuntu 14.04 was build. The only way to be sure
is to try it. Also, if you have a very recent CPU and it got optimized for
in newer OpenBLAS, then it could make a big difference.

But if you mainly use the GPU, it shouldn't matter.

**Comment by lamblin** [comment]
The latest instructions mention `conda` as the preferred way of installing Theano's requirements, and it includes MKL.
