### ISSUE TITLE
Error: no such instruction: `shrx %rcx,8(%rax),%rcx'

### ISSUE THREAD

**Issue by masayoshi-louis** [Theano/Theano#3873]
I am getting the following error when compiling for the CPU on HPC cluster (Rocks 5.4) using the newest version of Theano:

Problem occurred during compilation with the command line below:

/share/apps/gcc/5.1.0/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mno-avx -mno-avx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mno-f16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=30720 -mtune=haswell -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/mb15505/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/mb15505/anaconda2/include/python2.7 -I/home/mb15505/anaconda2/lib/python2.7/site-packages/theano/gof -fvisibility=hidden -o /home/mb15505/.theano/compiledir_Linux-2.6-el5-x86_64-with-redhat-5.5-Final-x86_64-2.7.11-64/tmpxVDFzB/5422a3dec735a78746c65b95ef4de399.so /home/mb15505/.theano/compiledir_Linux-2.6-el5-x86_64-with-redhat-5.5-Final-x86_64-2.7.11-64/tmpxVDFzB/mod.cpp -L/home/mb15505/anaconda2/lib -lpython2.7

===============================

===============================

/tmp/142169.1.gpu.q/ccwAQqSF.s: Assembler messages:

/tmp/142169.1.gpu.q/ccwAQqSF.s:2963: Error: no such instruction: `shrx %rcx,8(%rax),%rcx'

The CPU is Intel(R) Xeon(R) CPU E5-2690 v3. The same program runs well on another computing node which CPU is E5-2667.

**Comment by zcyang** [comment]
I got a similar error here:
```
Problem occurred during compilation with the command line below:
/share/apps/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=core-avx2 -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/share/apps/lib/python2.7/site-packages/numpy/core/include -I/share/apps/include/python2.7 -I/share/apps/src/Theano/theano/gof -fvisibility=hidden -o /tmp/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.9-64/tmpdlOQDj/cdb0b986639740d2acf156f042fe37d2.so /tmp/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.9-64/tmpdlOQDj/mod.cpp -L/share/apps/lib -lpython2.7
```
```
Exception: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', "Compilation failed (return status=1): /tmp/ccDoPJZT.s: Assembler messages:. /tmp/ccDoPJZT.s:2982: Error: no such instruction: `vinserti128 $0x1,%xmm1,%ymm0,%ymm0'. /tmp/ccDoPJZT.s:2999: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'. ", '[DotModulo(A, s, m, A2, s2, m2)]')
```

and I tried out the solution here https://github.com/Theano/Theano/issues/1650
it does not work..

**Comment by nouiz** [comment]
-mbmi2

This is probably caused by a bug in g++. If you can update it, do it.
Otherwise, which solution did you try? There is many suggestion in that
page. Try this theano flag:

gcc.cxxflags=-march=avx


If it don't work try one of this:


gcc.cxxflags="-march=native -mno-bmi2"
gcc.cxxflags=-march=core

Which version of g++ do you have?

**Comment by masayoshi-louis** [comment]
This flag works:
gcc.cxxflags="-march=native -mno-bmi2"

Thank you very much!

**Comment by zcyang** [comment]
none of the above options seem to work for me... I am using gcc 4.8.4.
masayoshi-louis was using ```gcc/5.1.0/```, upgrading the gcc won't solve the problem?

**Comment by masayoshi-louis** [comment]
actually, I use gcc 4.8.4 now, because our CUDA version does not support gcc 5.1.0.

**Comment by nouiz** [comment]
try:


gcc.cxxflags="-march=core-avx"

**Comment by zcyang** [comment]
```error: bad value (core-avx) for -march= switch```
it generates an error

**Comment by nouiz** [comment]
Here is the list of possible value with your version of gcc:

https://gcc.gnu.org/onlinedocs/gcc-4.8.5/gcc/i386-and-x86-64-Options.html#i386-and-x86-64-Options
try corei7 or corei7-avx

**Comment by zcyang** [comment]
I tried ```core2``` and it worked. Many thanks!

**Comment by adityajumde** [comment]
@nouiz 
I'm getting the following error while running keras with theano backend:

Exception: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', 'Compilation failed (return status=1): C:\\Users\\xyz\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-2.7.11-64\\tmppfmji0\\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in\r.  #include <Python.h>\r.  ^\r. ', '[DotModulo(A, s, m, A2, s2, m2)]')

Thank you!

**Comment by nouiz** [comment]
This is a different error. The compiler Theano try to use do not support 64
bit, while the python version if 64 bit. Install a compiler that is 64 bit.
I found this link that explain this:

http://stackoverflow.com/questions/8861105/gcc-sorry-unimplemented-64-bit-mode-not-compiled-in#

**Comment by adityajumde** [comment]
Mine is a windows platform.. Windows 7 64bit i7. How can I get past this error?
