### ISSUE TITLE
Able to get cuda only after running a cuda example

### ISSUE THREAD

**Issue by AdrianoW** [Theano/Theano#3874]
I have setup cuda environment and all the setups needed for Theano. 

Strangely, when I boot the computer and try to use it, I receive an error:

    WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)

Then, If I run one of the CUDA examples (e.g: volumeRender), it works normally.

My Setup:
Ubuntu 14.04 LTS
CUDA 7.5
Theano .7

**Comment by nouiz** [comment]
It can be that the driver isn't initialized.

Can you try to instaed of running the example to run nvidia-smi to try to
fix the problem? If this work, make this command executed at boot.

If you don't have a GUI installed, the driver don't always start at boot. I
don't know why the example would fix this.

Fred

**Comment by AdrianoW** [comment]
Yes, that worked. Loading nvidia-smi on startup makes the card ready.

Thanks
