### ISSUE TITLE
Print cuDNN Version On Device "using"

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#3876]
Right now when theano loads a device is prints out wether or not `CNMeM` is enabled. I suggest also adding whether or not cuDNN is in use (and which version as well). BOth of these libraries are important for good performance.
Currently:
```
Using gpu device 0: GRID K520 (CNMeM is enabled)
```
I suggest:
```
Using gpu device 0: GRID K520 (CNMeM is enabled; cuDNN v4)
```

**Comment by nouiz** [comment]
I like this suggestion, do you want to make a PR? To get cudnn information,
you can call the function theano.sandbox.cuda.dnn.version() to get cudnn
version.
