### ISSUE TITLE
cnmem clipping at 98% is too high

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#3879]
[This line](https://github.com/Theano/Theano/blob/a7ddc3e4c2f3444946d2ce92aa1a1480bebde45f/theano/sandbox/cuda/cuda_ndarray.cu#L3225-L3230) which clips the cnmem value at 98% is still likely too high. I get the following unless I lower to `~ 0.97`:
```
RuntimeError: ('The following error happened while compiling the node', GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode=(0, 0), subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n',
'could not create cuDNN handle: CUDNN_STATUS_INTERNAL_ERROR', "[GpuDnnConv{algo='small', inplace=True}(<CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, 4D)>, <CudaNdarrayType(float32, 4D)>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]")
```

**Comment by nouiz** [comment]
Which GPU do you have? Is the monitor connected to it?

**Comment by cancan101** [comment]
There is no monitor connected. I am using a `GRID K520` on the AWS / EC2 `g2.2xlarge` instance.

**Comment by nouiz** [comment]
@abergeron told somewhere else that we could use 1 mean 0.95, but do not
clip to this number, so people could raise it if they wish.

What do you think of this? I think it would make sure it work everywhere,
but still allow the best case. I needed 0.95 at one place.

**Comment by cancan101** [comment]
@nouiz Are you suggesting just to remove the clipping entirely and let the user set the value as he wants? If so, I agree with that point. I would just add a note to the docs indicating that the value may need to be lowered if there are memory issues.

**Comment by nouiz** [comment]
Done. Now we clip at 0.95 by default. The user can set a fixed size if he want to go higher.
