### ISSUE TITLE
How to extract the features of 3d objects?

### ISSUE THREAD

**Issue by yobichi** [Theano/Theano#3880]
I have Minecraft building models for data mining. I wonder whether Theano provides functions to extract the features like colour, shape and texture. And can I do the clustering directly? Thanks.

**Comment by lamblin** [comment]
Theano does not provide any functions like that that are ready do use.
Theano provides a way of building models that could learn how to do that, however.
Please ask such questions on the `theano-users` mailing list, or on stackoverflow with the "theano" tag. Tickets are for bug reports.
