### ISSUE TITLE
DeprecationWarning from numpy in sparse/

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#3889]
This line gets it: https://github.com/Theano/Theano/blob/master/theano/sparse/basic.py#L898

Simple pdb tracing reveals that in one case, grad is of shape (64,) and gout_data is also of shape (64,), but self.kmap is a list of length 36.  So there is something fishy there.

However the tests currently pass so I'm not sure what exactly is wrong.

**Comment by Sentient07** [comment]
@abergeron From the tests, i can see only ```ComplexWarning``` and ```SparseEfficiencyWarning```s . How do i reproduce this error ?

**Comment by nouiz** [comment]
kmap is old stuff not used, not well tested and not well documented. I
tried to understand what it was doing years ago and I'm still not sure why
this is needed.

So I would vote to get rid of the kmap stuff (make a warning if someone try
to use it) and remove associated tests.

Objection?
