### ISSUE TITLE
Import bug in tensor\signal\downsample.py

### ISSUE THREAD

**Issue by daweileng** [Theano/Theano#3894]
current Line 2 in downsample.py

    import pool
should be

    from . import pool

**Comment by dwf** [comment]
Introduced in 372939b.

**Comment by jfsantos** [comment]
I submitted a PR (#3897) fixing this.

**Comment by tebzito** [comment]
Hey there. I still can't figure out the problem. First off, I can't find the import pool in downsample.py. And when I just add the 'from . import pool', the problem persists. Even after changing the 'DownsampleFactorMax' class name to Pool, still nothing. HELP!!!

**Comment by lamblin** [comment]
The most likely explanation is that you have an old version of Theano, maybe you have several versions of Theano at the same time.
Can you uninstall _all_ the versions of Theano and try with 0.8.2?
