### ISSUE TITLE
If config.cxx="", and border_mode is half, the compilation will crash

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#3906]
blocks disable the c compilation to speed up Theano tests.

PR https://github.com/Theano/Theano/pull/3905 fix a problem, we where still adding CorrMM in the graph and as it don't have perform, it would crash. With this PR, now we will use the old conv that have a perform.

but we don't have any conv on the CPU with a perform that support half. So we need to implement half for the old conv (in c code and perform)

**Comment by gokul-uf** [comment]
@nouiz, I'd like to take up this issue

**Comment by lamblin** [comment]
What do you mean by the "old conv"? `theano.tensor.nnet.conv.ConvOp`?
If so, I don't think we should touch that C code.
Also, when #3598 is addressed, we could add a flag to allow the use of `AbstractConv2d.perform` in the graph, which would support "half".

**Comment by nouiz** [comment]
So I'll close this issue, as we need to work on gh-3598 instead.
