### ISSUE TITLE
Bilinear interpolation for upsampling images by an int factor

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3928]
Upsampling images by an int factor (doubling, tripling, ...) can be done by computing `conv2d_grad_wrt_inputs` with a specially-crafted kernel (and taking care of the borders).
With `conv2d_grad_wrt_...` is part of `theano.nnet`, we could add the wrapper to make it available easily.

For large upsampling factors, it is also faster to decouple horizontal and vertical upsampling, and apply the operation twice, with a row kernel and a column kernel.

**Comment by Sentient07** [comment]
@lamblin can i take this ?

**Comment by lamblin** [comment]
Sorry, @SinaHonari is already assigned to this, since he's been working on that already.

**Comment by fvisin** [comment]
#3951 closes this ticket

**Comment by Sentient07** [comment]
I am trying to use this as an alternative to Transpose Convolution and I want to ideally decrease the number of filters/kernels used by this compared to the previous layer. The current implementation seems to retain the input channel dimension as the output channel dimension. Is this the desired behavior ?

**Comment by nouiz** [comment]
What you want is not interpolation of the image, but a convolution I think.

Le mar. 2 mai 2017 13:54, Ramana Subramanyam <notifications@github.com> a
écrit :

**Comment by Sentient07** [comment]
This is using transpose convolutional operation to scale up the images. So, if I rather take multiple kernels(which is the desired number of output filters), perform a normal transpose convolution operation and then apply weighted average of nearest cells, isn't that also the bilinear interpolated convolution operation? I'm not sure if it is correct, but this is the intuitive idea that I have from the distil.pub article

**Comment by Sentient07** [comment]
@vdumoulin as you're an author of that post, I'd also like to have your input :)
