### ISSUE TITLE
Officially deprecate `ProfileMode` in the docs

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3929]
Also finish the clean-up `theano.compile.profiling.py` (#3431)

**Comment by carriepl** [comment]
@lamblin, you mean remove references to it from the doc or make sure it marked as deprecated everywhere (it currently is, but only in some places)?

**Comment by lamblin** [comment]
- Make sure it is marked as deprecated
- Make sure we do not call it, but use `profile=True` instead, in examples in the documentation
- Make sure that the documentation for `profile=True` now includes the "hints" that `ProfileMode`'s documentation has.
