### ISSUE TITLE
Uninstalling Theano built from Github

### ISSUE THREAD

**Issue by prateekpg2455** [Theano/Theano#3949]
Hi,

Can you tell me how should I uninstall Theano which I developed by cloning the Theano Git Repository?

I have:
```
$pip freeze | grep Theano
-e git://github.com/Theano/Theano.git@18319b8f426e99fa209c4910af7208c0d51c41a6#egg=Theano
```

`sudo pip uninstall Theano` returns `Can't uninstall 'Theano'. No files were found to uninstall.`

`sudo pip install Theano` gives:
```
Requirement already satisfied (use --upgrade to upgrade): theano in ./Theano
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/local/lib/python2.7/dist-packages/numpy-1.12.0.dev0+1436ec3-py2.7-linux-x86_64.egg (from theano)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.11 in /usr/local/lib/python2.7/dist-packages (from theano)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from theano)
```

**Comment by lamblin** [comment]
Maybe try without "sudo"?

On Fri, Jan 29, 2016, Prateek wrote:
> Hi,
> 
> Can you tell me how should I uninstall Theano which I developed by cloning the Theano Git Repository?
> 
> I have:
> ```
> $pip freeze | grep Theano
> -e git://github.com/Theano/Theano.git@18319b8f426e99fa209c4910af7208c0d51c41a6#egg=Theano
> ```
> 
> `sudo pip uninstall Theano` returns `Can't uninstall 'Theano'. No files were found to uninstall.`
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Theano/Theano/issues/3949

-- 
Pascal

**Comment by lamblin** [comment]
Also, please use the `theano-users` mailing list, or StackOverflow with the "theano" tag, for requests for support.
We use tickets to keep track of bugs and missing features only.
