### ISSUE TITLE
square of negative number is NA

### ISSUE THREAD

**Issue by rosstang** [Theano/Theano#3953]
```
x0 = theano.shared(np.array([[-1, 1], [3,4]], dtype=np.float32))
f1 = theano.function([], x0**2)
f1()


Out[6]: array([[ nan,   1.],
       [  9.,  16.]], dtype=float32)
```

I am using the latest theano.

**Comment by AnishShah** [comment]
I'm using the latest theano, as in, the development version and I'm getting the correct answer.
Which version are you using?

![image](https://cloud.githubusercontent.com/assets/3175743/12695064/ce8ac49e-c767-11e5-9b76-abda78206fce.png)

**Comment by rosstang** [comment]
```
In [34]: print theano.__version__
0.8.0.dev0.dev-18319b8f426e99fa209c4910af7208c0d51c41a6
```

I am using windows though.

**Comment by nouiz** [comment]
I also have the good answer. Can you execute this and give me the output:

theano.printing.debugprint(f1, print_type=True)

**Comment by rosstang** [comment]
```
In [755]: theano.printing.debugprint(f1, print_type=True)
Out[755]: HostFromGpu [id A] <TensorType(float32, matrix)> ''   1
 |GpuElemwise{pow,no_inplace} [id B] <CudaNdarrayType(float32, matrix)> ''   0
   |<CudaNdarrayType(float32, matrix)> [id C] <CudaNdarrayType(float32, matrix)>
   |CudaNdarrayConstant{[[ 2.]]} [id D] <CudaNdarrayType(float32, (True, True))>
```

**Comment by nouiz** [comment]
Can you try while changing the place of the -1? Otherwise, it is probably a
problem with your setup, a bug in one of the software we reuse like
nvcc(CUDA compiler).

**Comment by rosstang** [comment]
```
In [778]: x0 = theano.shared(np.array([[1, -1], [3,4]], dtype=np.float32))
f1 = theano.function([], x0**2)
f1()

Out[778]: 
array([[  1.,  nan],
       [  9.,  16.]], dtype=float32)

In [779]: x0 = theano.shared(np.array([[1, 3], [-1,4]], dtype=np.float32))
f1 = theano.function([], x0**2)
f1()

Out[779]: 
array([[  1.,   9.],
       [ nan,  16.]], dtype=float32)
```

Still the same. It looks like the 2 is converted into CudaNdarrayConstant{[[ 2.]]}  (which is a float?)

**Comment by nouiz** [comment]
Yes, this is normal. exp is only defined for 2 float inputs on the GPU.
Which version of CUDA do you use?

**Comment by lamblin** [comment]
On Linux, I have the following:
```python
In [5]: theano.printing.debugprint(f1)
HostFromGpu [id A] ''   1
 |GpuElemwise{sqr,no_inplace} [id B] ''   0
   |<CudaNdarrayType(float32, matrix)> [id C]

In [6]: theano.printing.debugprint(x0 ** 2)
Elemwise{pow,no_inplace} [id A] ''   
 |HostFromGpu [id B] ''   
 | |<CudaNdarrayType(float32, matrix)> [id C]
 |DimShuffle{x,x} [id D] ''   
   |TensorConstant{2} [id E]
```

So the graph is different, and I end up with `sqr` instead of `pow`.

**Comment by rosstang** [comment]
I am using cuda 7.5

**Comment by nouiz** [comment]
Can you give us all Theano flag that you used? If you changed the mode of
passed some fast math flag, try without.

**Comment by rosstang** [comment]
```
[global]
floatX = float32
device = gpu
optimizer=fast_compile
exception_verbosity = high

[nvcc]
fastmath = True
```

Here was my .theanorc.txt.

After removing fastmath=True, the issue is gone.

**Comment by nouiz** [comment]
The combination of fastmath and fast_compile probably caused this. fast_compile keep the pow in the graph, then fastmath make nvcc use a hardware implementation of exp that don't cover your number.

Can you test that is you use fastmath=True, but don't specify fast_compile, you have the right answer?

**Comment by rosstang** [comment]
With only fastmath=True (without fast_compile), the result is correct.

So, should I take it as fastmath shouldn't be used? I don't want to use without fast_compile, as the compile time will be too long.

**Comment by nouiz** [comment]
So remove fastmath. Maybe we should make this more clear in the doc that it
have problems with negative number. Do you want to fill a PR with that?

**Comment by nouiz** [comment]
doc updated in https://github.com/Theano/Theano/pull/3988.

We also don't use it in example and add it in the nan investigation tutorial.

thanks.

**Comment by nouiz** [comment]
Also, the problem isn't only the combination of fast_compile and fastmath. Some other case could generate this in FAST_RUN with fastmath.

thanks for the report.
