### ISSUE TITLE
NaN gradient in scan

### ISSUE THREAD

**Issue by zcyang** [Theano/Theano#3956]
Hi,

I am trying to train a model using lstm, the training goes on well and suddenly the cost becomes NaN. The NaN is NOT caused by the diverging of the objective function, otherwise, the cost will have a stage diverging or increasing. For my case, it does not have such a stage. The cost suddenly becomes NaN.

I debugged into it and found that the gradient in the previous step is NaN, this is the cause of NaN cost in the current step. But in the previous step, the cost and the output from lstm are fine, the gradients of the parameters in lstm becomes NaN.

I used ```NanGuardMode``` to find the error and got the following message:

```
Apply node that caused the error: AllocEmpty{dtype='float32'}(Elemwise{add,no_inplace}.0, Subtensor{int64}.0, Subtensor{int64}.0)
```

Any suggestion what may cause the problem?
I switch from lstm to gru and the problem disappeared...

Is there anyway I can debug this?

Many thanks!

**Comment by nouiz** [comment]
I suppose you closed this issue as you solved your problem. Just to let
know that NanGuardMode currently cause false positive and you hit one.
There is a PR that should make this better:

https://github.com/Theano/Theano/pull/3768
