### ISSUE TITLE
Error on cuDNN despite excluding dnn optimizer

### ISSUE THREAD

**Issue by erfannoury** [Theano/Theano#3962]
Hello,
I want to disable cuDNN but Theano still complains about cuDNN's incorrect installation.

I have this line in my `.theanorc` file:
```
optimizer_excluding=dnn
```
However, when I try to run code, I get this error:
```
ImportError: ('The following error happened while compiling the node', <theano.sandbox.cuda.dnn.DnnVersion object at 0x0000000027CB3B00>(), '\n', 'DLL load failed: The specified module could not be found.', '[<theano.sandbox.cuda.dnn.DnnVersion object at 0x0000000027CB3B00>()]')
```
Although I think I have set up everything correctly, this error still shows up when I don't include that line in the config file. It should be noted that path to cuDNN DLL file is in system path and I have also included the path to cuDNN include and library files in the Theano config file.
How can I solve this problem? Isn't it possible to disable cuDNN completely? I don't have a decent GPU and cuDNN actually slows down things a litte bit.

**Comment by nouiz** [comment]
Are you using the last release 0.7 or Theano development version? You
should use Theano dev version on Windows. If you want to disable the GPU
completly, you can use this flag:
force_device=True
when device=cpu (the default), this disable the GPU.

Can you confirm this fix your problem?

**Comment by erfannoury** [comment]
@nouiz I'm using the bleeding-edge version that I pulled ~2 hours ago.
I don't want to disable GPU, I just want to disable cuDNN.

**Comment by nouiz** [comment]
The simplest would be to go in the file theano/sandbox/cuda/dnn.py In the
method dnn_available() add this at the start
dnn_available.avail = False
dnn_available.msg = "disabled"

I'll try to make a config variable for this.

**Comment by nouiz** [comment]
I made a PR to help disable/enable/raise error when not available more easily: gh-3966

**Comment by erfannoury** [comment]
@nouiz Thank you very much. I just tested it and I can confirm that it now works.

However an extra thing to mention. 
When I reported the problem, I used Lasagne's `Conv2DMMLayer`. Before your fix it complained about cudnn, but after your fix it works without any problem.
However, when I changed that layer to `Conv2DLayer` (not `Conv2DDNNLayer`), even with your fix, Theano complains about cudnn. Doesn't this layer use `abstract_conv` which delegates the selection of convolution implementation to Theano? Is there another issue that I should report to Lasagne? Or maybe quite the contrary, this indeed is the expected behavior?

**Comment by nouiz** [comment]
Can you give the new full error? What Theano flag did you set?

I didn't wanted to change too much stuff in that PR, but I think that some
of the path you gave for cudnn are only used at one place, but should be at
another place.

**Comment by erfannoury** [comment]
I'm sorry, I made a mistake there.
cuDNN wasn't the problem in fact (when using `Conv2DLayer`), it was the issue with `pad='same'` that produced the errors.

**Comment by nouiz** [comment]
Ok. So I think all about this issue will be fixed when we perge the PR.
thanks

**Comment by erfannoury** [comment]
Thank you very much @nouiz :smile:
