### ISSUE TITLE
Did the Param disappear/change in the bleeding edge , Theano-0.8.0.dev0

### ISSUE THREAD

**Issue by gammaguy** [Theano/Theano#3979]
I installed the Theano-0.8.0.dev0 to get Keras Relu working.

Now I can't import Param

1 import theano.tensor as T
2 from theano import Param
3 from theano import function
4 x, y = T.dscalars('x', 'y')
5 z = x + y
6 f = function([x, Param(y, default=1)], z)

I get:
/home/paul/anaconda2/bin/python /home/paul/.PyCharm50/config/scratches/scratch_6
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled)
Traceback (most recent call last):
  File "/home/paul/.PyCharm50/config/scratches/scratch_6", line 2, in <module>
    from theano import Param
ImportError: cannot import name Param

Process finished with exit code 1

**Comment by lamblin** [comment]
Yes, `Param` has been removed. We thought it was only used internally, and now `In` supports all the features of `Param`. We should put it back with a deprecation warning, I guess.
The solution is to replace `Param(y, default=1)` with `In(y, value=1)`, like was done at https://github.com/lisa-lab/DeepLearningTutorials/pull/133

**Comment by gammaguy** [comment]
TY for answering so quickly.

I got it from the Theano tutorial section.

Setting a Default Value for an Argument section  from http://deeplearning.net/software/theano/tutorial/examples.html#computing-more-than-one-thing-at-the-same-time

**Comment by lamblin** [comment]
OK, I did not remember about that. That's another good reason to add back `Param` with a deprecation warning.
On top of it, this section of the doc has been changed in the repository (it now tells to use `In()`), but the online doc does not seem to have been updated. I'll try to investigate that.

**Comment by nouiz** [comment]
The problem with the only doc is that now warning are consided as error.
I'm working on a PR to add back Param.

**Comment by nouiz** [comment]
Here is the PR: https://github.com/Theano/Theano/pull/3984

**Comment by gammaguy** [comment]
There is still a problem as you changed the Param --> In but forgot to change the default --> value as per 
"The solution is to replace Param(y, default=1) with In(y, value=1), like was done at lisa-lab/DeepLearningTutorials#133"

In the Setting a Default Value for an Argument section of: http://deeplearning.net/software/theano/tutorial/examples.html 

>>> f = function([x, In(y, **default**=1)], z)
and
>>> f = function([x, In(y, default=1), In(w, **default**=2, name='w_by_name')], z)

**Comment by nouiz** [comment]
Thanks, I did a PR to fix this:

https://github.com/Theano/Theano/pull/4061
