### ISSUE TITLE
Disable warn_float64 temporarily in ARange.infer_shape

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#3985]
See [this post](https://groups.google.com/d/msg/theano-users/RILW5vH07K8/7UwOy_2xGQAJ) for the context.
Sometimes, we want some small computation to be done in float64 regardless of floatX, for instance in shape inference. It would be good to be able to disable the warning for one line.

A nice interface would be using the `with` statement, for instance
```python
with disable_warn_float64:
    arange_len = cast((stop - start), 'float64')

...(ceil(arange_len) / step) ...
```

Otherwise, it could be done with `try / finally`:
```python
orig_warn_float64 = warn_float64
try:
    config.warn_float64 = False
    arange_len = ...
finally:
    config.warn_float64 = orig_warn_float64
...
```

**Comment by nouiz** [comment]
This can be done with this decorator:

@theano.configparser.change_flags(warn_float64='ignore')
def f(...).

I didn't test it with an "with" statement, but we could do something
similar, it would be more generic.

**Comment by Saxenauts** [comment]
Hi, @lamblin , @nouiz   I'm a newbie in open source contribution, I'd like to contribute to Theano. 
I have added the decorator to the specified function, and sent a pull request. 
Please review, and thanks for filtering out the easyfixes for us mortals, and guiding us :) 
Looking forward to contribute to this project.

**Comment by nouiz** [comment]
done by gh-4010
