### ISSUE TITLE
prod have no optimization: Reuse sum opt on prod when applicable.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#399]

**Comment by kelvinxu** [comment]
The optimizations covered by the ticket seem to be the following:

local_sum_alloc
local_sum_mul_by_scalar
local_sum_div_dimshuffle
local_sum_all_to_none
local_sum_sum

**Comment by kelvinxu** [comment]
The optimizations covered by the ticket seem to be the following:

local_sum_alloc
local_sum_mul_by_scalar
local_sum_div_dimshuffle
local_sum_all_to_none
local_sum_sum

**Comment by nouiz** [comment]
I re-open as the opt  local_sum_div_dimshuffle wasn't converted.

**Comment by carriepl** [comment]
Finished by #3290
