### ISSUE TITLE
Warn if cuDNN is too new?

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#3996]
Some Lasagne users get trapped by trying to use cuDNN v4 with Theano 0.7. Maybe Theano should issue a warning if cuDNN is of a later version than expected, just something like: "Your cuDNN version is newer than what your version of Theano was written for. If something does not work as expected, try upgrading Theano to the bleeding-edge version or downgrading cuDNN to version XYZ."

**Comment by nouiz** [comment]
Can you point to a discussion where this caused problem? Just to see the type of error the user currently have.

**Comment by nouiz** [comment]
Done: https://github.com/Theano/Theano/pull/4000

**Comment by f0k** [comment]
> Can you point to a discussion where this caused problem?

Sorry, was away over the weekend. One example is this: https://groups.google.com/forum/#!topic/lasagne-users/CV2Gx8NZPQY
The user got something cryptic:
```
mod.cu(147): error: argument of type "void *" is incompatible with
parameter of type "cudnnConvolutionBwdDataAlgo_t"
mod.cu(148): error: argument of type "float *" is incompatible with
parameter of type "size_t"
mod.cu(148): error: too few arguments in function call
3 errors detected in the compilation of
"/tmp/tmpxft_000040a5_00000000-9_mod.cpp1.ii".
```
