### ISSUE TITLE
binary_crossentropy gradient blows up when using uint8 labels

### ISSUE THREAD

**Issue by bfredl** [Theano/Theano#4014]
`binary_crossentropy` is defined as
`-(target * tensor.log(output) + (1.0 - target) * tensor.log(1.0 - output))`
 it looks perfectly fine to use an unsigned int `target`, as it immediately gets converted to a float in both places, and it is, until you differentiate w.r.t the `output`:

```
import theano.tensor as T
z = T.scalar("z")
u = T.scalar("u",dtype='uint8')
# u = T.cast(u,'int8')
v = T.nnet.binary_crossentropy(z,u)
v.eval({z:0.5, u:1}) # ok
g = T.grad(v,z)
g.eval({z:0.5, u:1}) # blows up
```

adding the cast fixes it. But this behavior is very confusing as `target` is just a constant only used in float contexts, its integer signedness shouldn't matter, right?

**Comment by nouiz** [comment]
If I execute this code with floatX=float64 or floatX=float32, then it don't blow up with the current Theano development version: 

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Can you try it to confirm it also work in your setup? If not, what other Theano flags do you use.

Do you use mode=fast_compile? If so, this is normal as this disable stability optimization. Try mode=stabilize instead. This would be not much slower and would have the stability optimization.

**Comment by bfredl** [comment]
I updated to latest theano master and I still see it. I get it when running on cpu with no `THEANO_FLAGS` on both python2/3. 
However, when running with `THEANO_FLAGS="mode=FAST_COMPILE"` I actually do get the correct value. mode=stabilize doesn't seem to exist? at least not here: https://github.com/Theano/Theano/blob/master/doc/library/compile/mode.txt

**Comment by lamblin** [comment]
I just tried it with the latest master, and it seems to work without the cast:
`array(510.0)`
