### ISSUE TITLE
pydotprint does not work 

### ISSUE THREAD

**Issue by yiulau** [Theano/Theano#4019]
I am trying to run the following notebook : https://github.com/mila-udem/summerschool2015/blob/master/intro_theano/intro_theano.ipynb 

When ran cell 8 I got this is as output:

`---------------------------------------------------------------------------
InvocationException                       Traceback (most recent call last)
<ipython-input-9-1481499deb15> in <module>()
      1 from theano.printing import pydotprint
----> 2 pydotprint(f, outfile='pydotprint_f.png')

/Users/patricklau/anaconda3/lib/python3.5/site-packages/theano/printing.py in pydotprint(fct, outfile, compact, format, with_ids, high_contrast, cond_highlight, colorCodes, max_label_size, scan_graphs, var_with_name_simple, print_output_file, return_image)
   1025     else:
   1026         try:
-> 1027             g.write(outfile, prog='dot', format=format)
   1028         except pd.InvocationException:
   1029             # based on https://github.com/Theano/Theano/issues/2988

/Users/patricklau/anaconda3/lib/python3.5/site-packages/pydot_ng/__init__.py in write(self, path, prog, format)
   1846 
   1847             else:
-> 1848                 fobj.write(self.create(prog, format))
   1849         finally:
   1850             if close:

/Users/patricklau/anaconda3/lib/python3.5/site-packages/pydot_ng/__init__.py in create(self, prog, format)
   1956             raise InvocationException(
   1957                 'Program terminated with status: %d. stderr follows: %s' % (
-> 1958                     status, stderr_output))
   1959         elif stderr_output:
   1960             print(stderr_output)

InvocationException: Program terminated with status: -5. stderr follows: dyld: Library not loaded: /usr/lib/libltdl.7.dylib
  Referenced from: /Users/patricklau/anaconda3/bin/dot
  Reason: image not found
`

I suspect it may have something to do with pydot. I installed it via "pip install pydot-ng" but when I typed in dot in the command line I got something similar back:

dyld: Library not loaded: /usr/lib/libltdl.7.dylib
  Referenced from: /Users/patricklau/anaconda3/bin/dot
  Reason: image not found
Trace/BPT trap: 5

**Comment by nouiz** [comment]
This is a problem with your installation, not Theano. As I'm not using mac,
I can't help much, hopefully, someone else can help more.

Maybe reinstalling dot on your os would help you.
