### ISSUE TITLE
Support record dtypes

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#4021]
Record types are more efficient than multiple arrays being accessed in parallel because they incur many times fewer cache misses.  They're also convenient programmatically when you're actually working with records and don't want to pass around tuples of arrays of different dimensions.

I would like to extend TensorType to support record dtypes.

**Comment by NeilGirdhar** [comment]
I've started with something like this:

```
import itertools as it
import networkx as nx
import numpy as np


class TypeManager:

    INDENT = " " * 4

    BASIC_TYPES = {
        np.float16: (float, 'npy_float16', 'NPY_FLOAT16'),
        np.float32: (float, 'npy_float32', 'NPY_FLOAT32'),
        np.float64: (float, 'npy_float64', 'NPY_FLOAT64'),
        np.uint8: (int, 'npy_uint8', 'NPY_UINT8'),
        np.int8: (int, 'npy_int8', 'NPY_INT8'),
        np.uint16: (int, 'npy_uint16', 'NPY_UINT16'),
        np.int16: (int, 'npy_int16', 'NPY_INT16'),
        np.uint32: (int, 'npy_uint32', 'NPY_UINT32'),
        np.int32: (int, 'npy_int32', 'NPY_INT32'),
        np.uint64: (int, 'npy_uint64', 'NPY_UINT64'),
        np.int64: (int, 'npy_int64', 'NPY_INT64'),
        np.complex128: (complex, 'theano_complex128', 'NPY_COMPLEX128'),
        np.complex64: (complex, 'theano_complex64', 'NPY_COMPLEX64')
    }
    BASIC_TYPES = {np.dtype(x): y
                   for x, y in BASIC_TYPES.items()}

    def __init__(self):
        self.code_graph = nx.DiGraph()
        self.dtype_to_code = {}
        self.dtype_to_typename = {}
        self.dtype_to_typenum = {}
        self.pad_name_generator = self.var_name_generator("pad")
        self.struct_name_generator = self.var_name_generator("struct")
        self.typenum_generator = it.count()

    @staticmethod
    def var_name_generator(base_name):
        for i in it.count():
            yield "{}_{}".format(base_name, i)

    def register(self, dtype):
        """
        Register a structure corresponding to a dtype.
        """
        dtype = np.dtype(dtype)
        if dtype in self.dtype_to_typename:
            return  # Already registered.
        if dtype in self.BASIC_TYPES:
            # Copy over the basic mappings.
            _, typename, typenum = self.BASIC_TYPES[dtype]
            self.dtype_to_typename[dtype] = typename
            self.dtype_to_typenum[dtype] = typenum
            return
        if dtype.fields is not None:
            # Register the components of the record type and then register
            # the record type itself.
            indent = self.INDENT
            subdtypes = [subdtype
                         for (subdtype, offset) in dtype.fields.values()]
            self.code_graph.add_node(dtype)
            for subdtype in subdtypes:
                self.register(subdtype.base)
                if subdtype.base in self.dtype_to_code:
                    self.code_graph.add_edge(subdtype.base, dtype)

            typename = next(self.struct_name_generator)
            typenum = "THEANO_" + typename.upper()
            typenum_as_number = next(self.typenum_generator)

            self.dtype_to_typename[dtype] = typename
            self.dtype_to_typenum[dtype] = typenum


            code = "// Definitions for {}\n".format(dtype)
            code += ("#define {typenum} "
                    "(NPY_USERDEF + {typenum_as_number})\n").format(
                        typenum=typenum,
                        typenum_as_number=typenum_as_number)

            total_offset = 0
            code += "struct {typename} {{\n".format(
                typename=typename)

            # Add data members.
            sorted_fields = sorted(dtype.fields.items(),
                                   key=lambda x: x[1][1])
            for name, (subdtype, offset) in sorted_fields:
                if total_offset != offset:
                    code += "{indent}char {name}[{size}];\n".format(
                        indent=indent,
                        name=next(self.pad_name_generator),
                        size=(offset - total_offset))
                sub_typename = self.c_typename(subdtype.base)
                if subdtype.shape == ():
                    code += "{indent}{typename} {name};\n".format(
                        indent=indent,
                        typename=sub_typename,
                        name=name)
                else:
                    code += "{indent}{typename} {name}[{shape}];\n".format(
                        indent=indent,
                        typename=sub_typename,
                        name=name,
                        shape="][".join(str(dimension)
                                        for dimension in subdtype.shape))
                total_offset += subdtype.itemsize
            code += "\n"

            # Add methods.
            copy_operator = indent*2 + ("\n" + indent * 2).join(
                "this->{name} = other.{name};".format(name=name)
                for name, _ in sorted_fields)
            comparison_operator = (
                2*indent +
                "return " +
                ("\n" + indent * 3 + "&& ").join(
                    "(this->{name} == other.{name})".format(name=name)
                    for name, _ in sorted_fields) +
                ";")
            code += ("{indent}{typename}() {{}}\n"
                     "{indent}{typename}(const {typename} &other) {{ "
                     "*this = other; }}\n"
                     "{indent}{typename}& operator =(const {typename} &other) {{\n"
                     "{copy_operator}\n"
                     "{indent}{indent}return *this;\n"
                     "{indent}}}\n"
                     "{indent}bool operator ==(const {typename} &other) {{\n"
                     "{comparison_operator}\n"
                     "{indent}}}\n"
                     ).format(
                         indent=indent,
                         typename=typename,
                         copy_operator=copy_operator,
                         comparison_operator=comparison_operator)
            code += "};\n\n"
            self.dtype_to_code[dtype] = code

    def c_support_code(self):
        """
        Return a generator of all C++ support code for all of the registered
        structures in an appropriate declaration order.
        """
        return "\n".join(self.dtype_to_code[dtype]
                         for dtype in nx.topological_sort(self.code_graph))

    def c_typename(self, dtype):
        """
        Return a C typename corresponding to a dtype.
        """
        return self.dtype_to_typename[dtype]

    def c_typenum(self, dtype):
        """
        Return a C integer constant "type number" corresponding to a dtype.
        """
        return self.dtype_to_typenum[dtype]

```

Then the code:
```

import numpy as np

from theano.tensor.type_manager import TypeManager


array = np.zeros(100, np.dtype([('time', '<f8'),
                                ('data', np.float32, 20)]))
array2 = np.zeros(100, np.dtype([('red', '<f8'),
                                 ('blue', array.dtype, 30)]))


tm = TypeManager()
tm.register(array.dtype)
tm.register(array2.dtype)

print(tm.c_support_code())
```

produces
```

// Definitions for [('time', '<f8'), ('data', '<f4', (20,))]
#define THEANO_STRUCT_0 (NPY_USERDEF + 0)
struct struct_0 {
    npy_float64 time;
    npy_float32 data[20];

    struct_0() {}
    struct_0(const struct_0 &other) { *this = other; }
    struct_0& operator =(const struct_0 &other) {
        this->time = other.time;
        this->data = other.data;
        return *this;
    }
    bool operator ==(const struct_0 &other) {
        return (this->time == other.time)
            && (this->data == other.data);
    }
};


// Definitions for [('red', '<f8'), ('blue', [('time', '<f8'), ('data', '<f4', (20,))], (30,))]
#define THEANO_STRUCT_1 (NPY_USERDEF + 1)
struct struct_1 {
    npy_float64 red;
    struct_0 blue[30];

    struct_1() {}
    struct_1(const struct_1 &other) { *this = other; }
    struct_1& operator =(const struct_1 &other) {
        this->red = other.red;
        this->blue = other.blue;
        return *this;
    }
    bool operator ==(const struct_1 &other) {
        return (this->red == other.red)
            && (this->blue == other.blue);
    }
};
```

**Comment by abergeron** [comment]
The only problem I see is that C++ has no guarantee of data alignment for non-POD structs. So there may be some compilers (or future GCC) where the structs won't fit the data.

Otherwise it's nice and all to have a TypeManager, but how will this relate to TensorType?  Or whatever Type you plan to implement?

**Comment by NeilGirdhar** [comment]
Aren't they all composed of POD types?  Everything is `np.float32`, `np.int16`, etc. and C `char` for padding.

I'm not sure how to put it together, which is why I posted here.  I only started looking at the code last night and thought a first step would be generating the C support code?  I'm looking at slicing now.

**Comment by nouiz** [comment]
You will need to make a new Theano Type, that take as a parameter a record dtype.

Then you will need to implement all operation you want to work on that new Type. Some like slicing could be done for all possible instead of record dtype. Here I suppose slicing mean taking a subset of the records, not spliting a record. This can also be done, but it would to take case of those 2 cases. One is if the output is a new record type and one if the output type is a tensor.

Which operation will you need on the record type?

**Comment by NeilGirdhar** [comment]
@nouiz Thank you, yes, I just need slicing.  After slicing, I have a regular TensorType and the regular Theano code would be fine.

So, I need to have `RecordTensorType` inherit from `TensorType`?  I also need a `RecordSubtensor` to do the slicing?

Finally, how does my `TypeManager` code look to you? I assume that after processing a function tree, you accumulate all of the C support code somewhere?  I was thinking the TypeManager could accumulate all of the C support code for types.

**Comment by nouiz** [comment]
On Wed, Feb 10, 2016 at 4:42 PM, Neil <notifications@github.com> wrote:

> @nouiz <https://github.com/nouiz> Thank you, yes, I just need slicing.
> After slicing, I have a regular TensorType and the regular Theano code
> would be fine.
>
> So, I need to have RecordTensorType inherit from TensorType? I also need
> a RecordSubtensor to do the slicing?
>

I would not make type inherit from each other. We don't do that now, so
just to prevent problems, I wouldn't start doing it now. I don't think you
can share much code anyway.

RecordSubtensor sound good.


> Finally, how does my TypeManager code look to you? I assume that after
> processing a function tree, you accumulate all of the C support code
> somewhere? I was thinking the TypeManager could accumulate all of the C
> support code for types.
>
I'm not sure how to get that code compiled. The simplest would be to have
the RecordType add this code in c_support_code() Then each node would
recompile that part of the code, but I think it would work and would be
much simpler than using that TypeManager to make a special shared lib with
all the types. Then later new types could be created and then it would need
to generate a new one, ...

**Comment by NeilGirdhar** [comment]
> I'm not sure how to get that code compiled. The simplest would be to have
> the RecordType add this code in c_support_code() Then each node would
> recompile that part of the code, but I think it would work and would be
> much simpler than using that TypeManager to make a special shared lib with
> all the types. Then later new types could be created and then it would need
> to generate a new one, ...

The problem with this solution is that dependencies in the C support code make it so that it might have to be included in a particular order.  Also I don't find Theano's solution of generating many copies of identical C support code and then filtering them at the end very appealing.

**Comment by abergeron** [comment]
If you want tom embark on a redesign of this points, that would be a major endeavour.  Even if it doesn't seem appealing, following the established practice will avoid much sweat and tears.

Also, the support code for types appears before the support code for the ops, so you shouldn't have a dependency problem there.

**Comment by NeilGirdhar** [comment]
@abergeron I'm happy to stick with the current system if it can be made to work.  The problem is that there can be dependencies between the types.  I illustrated that in the example above.

**Comment by NeilGirdhar** [comment]
Why not just pass in a Manager object into the calls to `c_support_code`?  The Manager would have a directed graph.  The nodes in your function tree produce nodes in the graph unless their key already exist.  Besides a key, the nodes in the graph have a value that is the C support code and the edges in the graph represent dependencies.  The caller topologically sorts the graph and emits the code.  The advantage of this is that you can have arbitrary dependencies between C support code generated from different nodes.

**Comment by nouiz** [comment]
If you want to emit all the existing RecType c code in the c_support_code,
you can just reference a single Manager in the c_support_code. No need to
pass it

I don't see the problem with dependence between types. If one compiled op
take 1 input type and a different output type, then the c_suppose_code will
be called for each type. Both of them will be there.

**Comment by NeilGirdhar** [comment]
In the above example, if one OP uses `array2`, that op will generate both `struct0` and `struct1`.  If another op uses `array`, it will regenerate `struct0`.  First of all, both ops need to make sure that they call every occurrence of `struct0` by the same name (the other op should not allocate a different name), and second of all, if the dtypes are all different, they need to make sure they don't reuse the same names.  That's why you need a manager to allocate names for each new dtype in the tree — never reallocating them, and always returning consistent names for the same dtypes.
