### ISSUE TITLE
Use `numbers.Integral` instead of `(numpy.integer, int)`

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#4022]
Instead of this:

`isinstance(entry, (numpy.integer, int)):`

or this:

`isinstance(entry, (numpy.integer, six.integer_types)):`

write:

`isinstance(entry, numbers.Integral)`.

As of December 2015, numpy registers itself with `numbers`.

**Comment by lamblin** [comment]
Good idea, but we still need compatibility with earlier versions of NumPy.
[Last time I checked](https://github.com/Theano/Theano/pull/3727#discussion-diff-46564115), that did not work with the version we were testing with.

**Comment by NeilGirdhar** [comment]
@lamblin Oh, I see.  Which version of numpy is the minimum supported?

**Comment by NeilGirdhar** [comment]
@lamblin Ah, I see.   That's too bad. :)

**Comment by nouiz** [comment]
The minimal Theano version we support is 1.7.1.

**Comment by NeilGirdhar** [comment]
@nouiz Found it, thanks :)  Any comment on my record dtypes?  I'm going to be at U de M on Friday if you have any time to discuss that.  Also I'm looking into passing my "shared variables" to OpenGL.  Have you looked into that at all?
