### ISSUE TITLE
Yet another Failed to compile cuda_ndarray.cu:

### ISSUE THREAD

**Issue by sygi** [Theano/Theano#4024]
1. I checked cuda by running nvidia-smi and deviceQuery and it works
2. Running (on the current github master of theano):
```
THEANO_FLAGS=device=gpu python -c "import theano; print(theano.sandbox.cuda.device_properties(0))"
```
gives me long error code and after it:
```
/usr/bin/ld: cannot find -lpython2.7.a
collect2: ld returned 1 exit status

['nvcc', '-shared', '-O3', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/icm/home/sygnowsk/.theano/compiledir_Linux-2.6-v1-x86_64-with-redhat-6.6-Carbon-x86_64-2.7.5-64/cuda_ndarray', '-I/icm/home/sygnowsk/dqn/deep_q_rl/venv/lib/python2.7/site-packages/theano/sandbox/cuda', '-I/icm/home/sygnowsk/dqn/deep_q_rl/venv/lib/python2.7/site-packages/numpy/core/include', '-I/mnt/software/common/python/2.7.5/include/python2.7', '-I/icm/home/sygnowsk/dqn/deep_q_rl/venv/lib/python2.7/site-packages/theano/gof', '-o', '/icm/home/sygnowsk/.theano/compiledir_Linux-2.6-v1-x86_64-with-redhat-6.6-Carbon-x86_64-2.7.5-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/mnt/software/common/python/2.7.5/lib', '-lpython2.7.a', '-lcublas', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -m64 -Xcompiler -DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/icm/home/sygnowsk/.theano/compiledir_Linux-2.6-v1-x86_64-with-redhat-6.6-Carbon-x86_64-2.7.5-64/cuda_ndarray -I/icm/home/sygnowsk/dqn/deep_q_rl/venv/lib/python2.7/site-packages/theano/sandbox/cuda -I/icm/home/sygnowsk/dqn/deep_q_rl/venv/lib/python2.7/site-packages/numpy/core/include -I/mnt/software/common/python/2.7.5/include/python2.7 -I/icm/home/sygnowsk/dqn/deep_q_rl/venv/lib/python2.7/site-packages/theano/gof -o /icm/home/sygnowsk/.theano/compiledir_Linux-2.6-v1-x86_64-with-redhat-6.6-Carbon-x86_64-2.7.5-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/mnt/software/common/python/2.7.5/lib -lpython2.7.a -lcublas -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'device_properties'
```
I am not surprised that nvcc couldn't find python2.7.a - in /mnt/software/common... I have only:
```
ls /mnt/software/common/python/2.7.5/lib/
libpython2.7.a	libpython2.7.so  libpython2.7.so.1.0  pkgconfig  python2.7
```
So it is looking for python2.7.a, and I have libpython2.7.a. Do you have an idea where it'd gone wrong and how can I convince theano to give nvcc correct name of the library?

**Comment by lamblin** [comment]
I think the command line should say `-lpython2.7`, which the linker should interpret as "find libpython2.7.so".
The command line itself gets generated around [here](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/nvcc_compiler.py#L146), so you could set up a breakpoint in there, check what is getting passed as `libs` and if it includes `python2.7.a`, and try to check where thta comes from...

Just make sure that you are using the latest version from GitHub for that, as it may have already been fixed.

**Comment by sygi** [comment]
You're right. From what I saw the problem is around (here)[https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L1658]
I get `libname = libpython2.7.a`, which is later cut to `python2.7.a`, but it's extension is not cut, as it's only checked if it's `*.so`. I don't know why this config var is set to python2.7.a for me.

I'll try to change the source to remove the extension and tell you if it helped. But thanks, anyway!

**Comment by lamblin** [comment]
It is kind of strange that "LDLIBRARY" would point to a `.a` file, but if it works for you to remove the ".a" at the end, I think it could be useful for other people, and a PR would be welcome.
Thanks for investigating.

**Comment by nouiz** [comment]
fixed by gh-4024, so I close. thanks.
