### ISSUE TITLE
Add OpenGL-CUDA interop functionality

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#4027]
The goal is to be able to visualize the results of GPU-accelerated operations synchronously.

I don't know Theano that well, but I imagine it would be a context manager around a theano function evaluation that makes calls to `cudaGraphicsMapResources` (before) and `cudaGraphicsUnmapResources` (after) computations.

**Comment by nouiz** [comment]
Can you tolerate to copy the data? It would make that easier to implement I think. Theano like to manage the GPU memory :)

Otherwise, could it be done in the reverse directly? Theano compute some stuff and put it in some CUDA memory, then you access it from OpenGL?

**Comment by NeilGirdhar** [comment]
@nouiz Copy from GPU space to GPU space, or copy on every frame from CPU to GPU and back?

I've been reading about how this is supposed to work:

```
cudaGraphicsMapResources(1, &cudaResourceBuf, cudaStream);
cudaGraphicsResourceGetMappedPointer((void **)&memPtr, &size, cudaResourceBuf); doWorkInCUDA(cudaArray, memPtr, cudaStream);//asynchronous
cudaGraphicsUnmapResources(1, & cudaResourceBuf, cudaStream);
doWorkInGL(imagePBO, imageTex); //asynchronous
```

In which file does Theano manage the GPU memory?  Perhaps I can take a look to get a better idea what's going on?

**Comment by nouiz** [comment]
Theano don't manage memory in only one file. We have this document that
explain it:

http://deeplearning.net/software/theano/tutorial/aliasing.html

I was talking about GPU to GPU copy.

What do you want to do with that memory? Give data to Theano from OpenGL?
That should be not too complicated.

The more complicated case to implement would be to ask Theano to read
OpenGL memory and write back the output of a Theano function to it. There i
not mechanism to garantie where Theano will write its update.

**Comment by NeilGirdhar** [comment]
I want to do all of my processing in shared variables in Theano, and then push those variables to OpenGL.

More specifically, the processing would have all of the historic values of all the parameters and configuration of my model.  OpenGL would be used to render various graphs in real time.

**Comment by nouiz** [comment]
Who generate the data? If this is in Theano, you could have it returned by
a Theano function, then map it to OpenGL to show it. Then all the control
will be outside Theano, which could make thing easier.

**Comment by NeilGirdhar** [comment]
@nouiz  Yes, that's exactly what I want to do!

My initial research seems to suggest that you have to have OpenGL allocate the buffer, and then lend it to cuda using the code in my earlier comment.  Please correct me if I'm wrong.

**Comment by nouiz** [comment]
If this need to be done that way, the simplest would be to copy the result
of Theano to that buffer.

Otherwise, it is possible in some cases to provide the output buffer and
hope that Theano will reuse it. But you must check after that he used it
and if not copy. Scan do this.

So I would recommand, do first by copy and if this isn't fast enough, then
we can discuss how to remove the copy.
