### ISSUE TITLE
cudnn v4 is now officially released

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#4029]
do we need to patch something to support?

**Comment by nouiz** [comment]
I don't think so. I didn't test it, but it should be compatible with the v4
rc1.

To use it, you must use Theano development version

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by nouiz** [comment]
I ran Theano tests with it and they pass. So I confirm that it work. So I'm closing this issue.
