### ISSUE TITLE
[GPU] AssertionError in theano.sandbox.cuda.tests.test_opt.Test_local_elemwise_alloc

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4034]
The tests for ```theano.sandbox.cuda``` failed thrice, the ```AssertionError``` Originating from ```_verify_alloc_count``` method. 
The full traceback : 
```
FAIL: test_multi_input_single_alloc (theano.sandbox.cuda.tests.test_opt.Test_local_elemwise_alloc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/tensor/tests/test_opt.py", line 3144, in test_multi_input_single_alloc
    self._verify_alloc_count(func, 2)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/tests/test_opt.py", line 210, in _verify_alloc_count
    if elem.op is not None]) == count
AssertionError

======================================================================
FAIL: test_remove_alloc_w_dimshuffle (theano.sandbox.cuda.tests.test_opt.Test_local_elemwise_alloc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/tensor/tests/test_opt.py", line 3107, in test_remove_alloc_w_dimshuffle
    self._verify_alloc_count(func, 1)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/tests/test_opt.py", line 210, in _verify_alloc_count
    if elem.op is not None]) == count
AssertionError

======================================================================
FAIL: test_remove_alloc_wo_dimshuffle (theano.sandbox.cuda.tests.test_opt.Test_local_elemwise_alloc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/tensor/tests/test_opt.py", line 3042, in test_remove_alloc_wo_dimshuffle
    self._verify_alloc_count(func, 1)
  File "/Users/Ramana/projects/theano/Theano/theano/sandbox/cuda/tests/test_opt.py", line 210, in _verify_alloc_count
    if elem.op is not None]) == count
AssertionError
```

I'm using Nvidia GT 750M on OSX 10.11.3. Also, doesn't travis support GPU test or is it only my machine that's failing ?

**Comment by lamblin** [comment]
Travis does not have any instance with GPUs, which is why GPU tests break periodically.

**Comment by Sentient07** [comment]
@lamblin Oh! I'd investigate this soon. I'll also edit the title of the issue by adding GPU to it's description.

**Comment by nouiz** [comment]
I checked and when there is no CUDA available, this test is skiped.
Could it be that you have a partially working cuda installation?
Can you print the output of theano.sandbox.cuda.cuda_enabled and theano.sandbox.cuda.cuda_available?

Theano tests should be run with Theano flag device=cpu. GPU test will still run.

**Comment by Sentient07** [comment]
@nouiz Both gives me True. But CNMeM was disabled and a few tests were skipped. Could it be because of that ?

**Comment by nouiz** [comment]
cnmem should not affect the result of tests.

What is your value of device flag? It should be cpu

**Comment by Sentient07** [comment]
@nouiz the device is GPU. At the start, it says Using gpu device 0: GeForce GT 750M and i could see in my system process that GPU is being used. Also, the device flag is GPU.

**Comment by Sentient07** [comment]
Also, I had got a failure while running the following test, ```theano/gof/tests/```. Paste of that failure message, 

`.................................................................................F
======================================================================
FAIL: theano.gof.tests.test_vm.test_reallocation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/macvnev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/tests/test_vm.py", line 396, in test_reallocation
    assert check_storage(storage_map)[0]
AssertionError
`

Could it be because i have configured the GPU wrongly ? The tests results seem to be perfectly fine when on CPU. But this time, there wasn't any tests that were skipped because of the absence of CuDNN.  My configuration is in sync with http://deeplearning.net/software/theano/library/config.html#envvar-THEANORC except that I don't have cnmem. Should I need to open a new issue for this ? or continue discussion in this thread itself ?

**Comment by nouiz** [comment]
Theano tests are done while supposing device=cpu. So it is normal that some of them fail when device=gpu.

As all tests pass when device=cpu, then I'll close this issue.

We test the gpu even when device=cpu when possible.

**Comment by xgh45** [comment]
@nouiz 
hello.I am test like:import theano;theano.test(); Could you please tell me where to set device=cpu?

**Comment by nouiz** [comment]
Don't ask unrelated question in old thread. To set THeano flag, see this doc page:

http://deeplearning.net/software/theano/library/config.html
