### ISSUE TITLE
Add tip in regarding mixed dtypes to profiling output.

### ISSUE THREAD

**Issue by carriepl** [Theano/Theano#4035]
See @lamblin's comment in #3964.

Context : the logistic regression example from the deep learning tutorials was used to provide an example of the output of Theano's profiling mode. However, in the profile output, it seems like one of the dot products has been kept in the graph because of float32/float64 dtypes (otherwise it could have been removed).

**Comment by lamblin** [comment]
The code for that seems to already be [here](https://github.com/Theano/Theano/blob/master/theano/compile/profiling.py#L1367-L1378), we should investigate why it was not triggered, or displayed.

**Comment by lamblin** [comment]
Oh, OK, actually in that case, that is a `Dot` between a vector and a matrix, which should have been optimized into a `Gemv`. The existing tip only looks for matrix-matrix dot products.
So indeed, a new tip should be added.

**Comment by AnishShah** [comment]
Hi, I will work on this. I will try to send a PR in a day.
