### ISSUE TITLE
Problem with conv2d `border_mode='half'`

### ISSUE THREAD

**Issue by ebenolson** [Theano/Theano#4036]
As reported [here](https://groups.google.com/forum/#!topic/lasagne-users/Amj6YE8gX7w). Example:

    import theano
    import theano.tensor as T

    image = T.tensor4()
    W = T.tensor4()
    conv = T.nnet.conv2d(image,
                         W,
                         input_shape=(1, 32, 32, 32),
                         filter_shape=(32, 32, 3, 3),
                         border_mode='half')
    theano.function([image, W], [conv])   

Raises

    ValueError: shape must be given if subsample != (1, 1) or border_mode == "half"

Works with `device=cpu`, cuDNN, or with `optimizer_excluding=local_abstractconv_gradweight_gemm`

**Comment by nouiz** [comment]
I'm able to reproduce it and I'm close to a fix. thanks for the good report.

**Comment by nouiz** [comment]
Fixed in https://github.com/Theano/Theano/pull/4033
