### ISSUE TITLE
update installation for Lasagne  use -->>fails on Windows PC, Python 2.7 , Anaconda 

### ISSUE THREAD

**Issue by Sandy4321** [Theano/Theano#4037]
how to get  Theano which new enough to  work with Lasagne  ?
I have 
theano.__version__
'0.7.0'
and seems to be it is the newest one, since for now 

C:\Users\Sander>pip install --upgrade --no-deps theano
Requirement already up-to-date: theano in c:\anaconda\lib\site-packages
C:\Users\Sander>

But, lasagne needs newer version than may be get by pip install --upgrade --no-deps theano
as written in 
http://lasagne.readthedocs.org/en/latest/user/installation.html#theano
they need
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
but this line gives error
when I run
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip

installation fails with error:

******************************************************************************************************

c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    _configtest.c: In function 'main':
    _configtest.c:8:12: error: 'HAVE_DECL_SIGNBIT' undeclared (first use in this
 function)
    _configtest.c:8:12: note: each undeclared identifier is reported only once f
or each function it appears in
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    _configtest.c: In function 'main':
    _configtest.c:8:12: error: 'HAVE_DECL_ISFINITE' undeclared (first use in thi
s function)
    _configtest.c:8:12: note: each undeclared identifier is reported only once f
or each function it appears in
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    gcc -g _configtest.o -lmsvcr90 -o _configtest.exe
    success!
    removing: _configtest.exe.manifest _configtest.c _configtest.o _configtest.e
xe
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    gcc -g _configtest.o -lmsvcr90 -o _configtest.exe
    success!
    removing: _configtest.exe.manifest _configtest.c _configtest.o _configtest.e
xe
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    gcc -g _configtest.o -lmsvcr90 -o _configtest.exe
    success!
    removing: _configtest.exe.manifest _configtest.c _configtest.o _configtest.e
xe
    BUILD_ARCHITECTURE: 'AMD64', os.name='nt', sys.platform='win32'
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    _configtest.c:2:41: error: expected ';', ',' or ')' before 'a'
    failure.
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    success!
    removing: _configtest.c _configtest.o
    C compiler: gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes

    compile options: '-DNPY_MINGW_USE_CUSTOM_MSVCR -D__MSVCRT_VERSION__=0x0900 -
Inumpy\core\src\private -Inumpy\core\src -Inumpy\core -Inumpy\core\src\npymath -
Inumpy\core\src\multiarray -Inumpy\core\src\umath -Inumpy\core\src\npysort -IC:\
Anaconda\include -IC:\Anaconda\PC -c'
    gcc -g -DDEBUG -DMS_WIN64 -O0 -Wall -Wstrict-prototypes -DNPY_MINGW_USE_CUST
OM_MSVCR -D__MSVCRT_VERSION__=0x0900 -Inumpy\core\src\private -Inumpy\core\src -
Inumpy\core -Inumpy\core\src\npymath -Inumpy\core\src\multiarray -Inumpy\core\sr
c\umath -Inumpy\core\src\npysort -IC:\Anaconda\include -IC:\Anaconda\PC -c _conf
igtest.c -o _configtest.o
    _configtest.c: In function 'main':
    _configtest.c:7:12: error: 'Py_UNICODE_WIDE' undeclared (first use in this f
unction)
    _configtest.c:7:12: note: each undeclared identifier is reported only once f
or each function it appears in
    failure.
    removing: _configtest.c _configtest.o
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\setup.py",
 line 263, in <module>
        setup_package()
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\setup.py",
 line 255, in setup_package
        setup(**metadata)
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\core.py", line 169, in setup
        return old_setup(**new_attr)
      File "C:\Anaconda\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Anaconda\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\install.py", line 62, in run
        r = self.setuptools_run()
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "C:\Anaconda\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Anaconda\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build.py", line 47, in run
        old_build.run(self)
      File "C:\Anaconda\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Anaconda\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 153, in run
        self.build_sources()
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 170, in build_sources
        self.build_extension_sources(ext)
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 329, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File "c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy\numpy\dist
utils\command\build_src.py", line 386, in generate_sources
        source = func(extension, build_dir)
      File "numpy\core\setup.py", line 455, in generate_config_h
        rep = check_long_double_representation(config_cmd)
      File "numpy\core\setup_common.py", line 191, in check_long_double_represen
tation
        cmd.compiler.compile_options.remove("/GL")
    AttributeError: Mingw32CCompiler instance has no attribute 'compile_options'

    ----------------------------------------
  Rolling back uninstall of numpy
Command "C:\Anaconda\python.exe -u -c "import setuptools, tokenize;__file__='c:\
\users\\sander\\appdata\\local\\temp\\pip-build-ygtavk\\numpy\\setup.py';exec(co
mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __
file__, 'exec'))" install --record c:\users\sander\appdata\local\temp\pip-ez3b8n
-record\install-record.txt --single-version-externally-managed --compile" failed
 with error code 1 in c:\users\sander\appdata\local\temp\pip-build-ygtavk\numpy

C:\Users\Sander>

*****************************************************************************************

**Comment by lamblin** [comment]
Please use the theano-users mailing list or stackoverflow (with the "theano" tag) for such support requests.
For you problem, can you try the following:
`pip install --upgrade --no-deps https://github.com/Theano/Theano/archive/master.zip`

**Comment by Sandy4321** [comment]
this did not work
but this works
 pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
 from

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
*****************************************************************

**Comment by nouiz** [comment]
Thanks for the follow up.

**Comment by Sandy4321** [comment]
thank you for taking care
by the way why  is not working
pip install --upgrade --no-deps
https://github.com/Theano/Theano/archive/master.zip

when works
 pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
 from

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
