### ISSUE TITLE
CpuCorrMM uses BLAS without checking availability

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#4044]
CpuCorrMM uses _sgemm() or _dgemm(), but doesn't check if a BLAS library is actually available. This leads to cryptic error messages for Windows users (https://groups.google.com/forum/#!searchin/lasagne-users/undefined$20reference/lasagne-users/IQjKYgoBWr4/77813wVNFQAJ, https://github.com/Lasagne/Lasagne/issues/607).

Is there any way to prevent CpuCorrMM from being used in that case, or to use Theano's gemm fallback, or to give a clear error message telling the user to install a BLAS library (preferrably linking to corresponding documentation on the web)?

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/4045

thanks
