### ISSUE TITLE
Make docstring of AssertOp appear in the generated doc

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4047]
Follow-up to #2720.
Use `autodoc` or something similar so that `AssertOp`'s documentation appears somewhere on http://deeplearning.net/software/theano/library/tensor/

**Comment by nouiz** [comment]
The assert op is in the file tensor/opt.py. Add a reference in its docstring to the pdbbreakpoint op that people probably want to use instead.

**Comment by hantek** [comment]
Hi Fred, I have created a PR at #4069

**Comment by nouiz** [comment]
done.
