### ISSUE TITLE
Theano import Error: I dont know how to solve this issue

### ISSUE THREAD

**Issue by isragamer** [Theano/Theano#4051]
Can anyone help??

CPU: i74210hq
GPU: Gtx 850m
OS: Windows 10
MVST: 2013
CUDA Toolkit 7.5

THEANO_FLAGS = floatX=32, device = gpu
.theanorc.txt file 
global]
floatX = float32
device = gpu0

[nvcc]
fastmath = True
flags=-LC:\Anaconda2\libs
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64

[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5

Theano shows in every imports: His works fine on cpu, but my objective is run with my gpu :((( 

DEBUG: nvcc STDOUT mod.cu

   Creating library C:/Users/user/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/cuda_ndarray/cuda_ndarray.lib and object C:/Users/user/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/cuda_ndarray/cuda_ndarray.exp

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: DLL load failed: %1 is not a valid Win32 application.
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavilable)

**Comment by lamblin** [comment]
Also asked at https://groups.google.com/forum/#!topic/theano-users/_ZaKK8l9R6s, which is the right place, so I'm closing.
