### ISSUE TITLE
flake8, directory d3viz/tests

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4054]

**Comment by fvisin** [comment]
This ticket is to fix all the PEP8 errors. This includes making sure that all the functions and classes have comprehensible and exhaustive docstrings.

**Comment by taesupkim** [comment]
There is no PEP8 error for this issue, and no need to check docstring as all of them as for test.

**Comment by fvisin** [comment]
@nouiz  @lamblin he is right. `theano-nose` passes but running `flake8` directly gives some errors, among which some I personally find quite annoying:
```
E226 missing whitespace around arithmetic operator
W191 indentation contains tabs
E702 multiple statements on one line (semicolon)
E402 module level import not at top of file
```

Did we disable them on purpose in `theano-nose`? If so, should we discuss this choice?

**Comment by abergeron** [comment]
With flake8 2.5.1 the only error I see is E402: module level import not at top of file.

Also the ignore list (besides the whitelist) is "E501,E123,E133" which is long lines and bracket indentation.

**Comment by abergeron** [comment]
Also, theano-nose passes because the files that have errors are on the whitelist.  The point of this ticket is to remove them from the whitelist and fix the errors.

**Comment by fvisin** [comment]
My bad, I was running `flake8 *`.
So @taesupkim please fix these errors:
```
flake8 *.py
test_d3viz.py:7:1: E402 module level import not at top of file
test_d3viz.py:8:1: E402 module level import not at top of file
test_d3viz.py:9:1: E402 module level import not at top of file
test_d3viz.py:10:1: E402 module level import not at top of file
test_d3viz.py:11:1: E402 module level import not at top of file
test_d3viz.py:13:1: E402 module level import not at top of file
test_d3viz.py:14:1: E402 module level import not at top of file
test_d3viz.py:15:1: E402 module level import not at top of file
test_formatting.py:7:1: E402 module level import not at top of file
test_formatting.py:8:1: E402 module level import not at top of file
test_formatting.py:10:1: E402 module level import not at top of file
test_formatting.py:11:1: E402 module level import not at top of file
test_formatting.py:12:1: E402 module level import not at top of file
```
