### ISSUE TITLE
Remove useless dimshuffle

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4071]
Sub-ticket of #2943.
`DimShuffle{0, 1, ..., var.ndim-1}(var)` is useless and should be removed.

[`local_dimshuffle_lift`]( https://github.com/Theano/Theano/blob/c8aa0615ac6884793d969c2361de84f12a6442bf/theano/tensor/opt.py#L573) removes them if they are the result of the fusion of two successive `DimShuffle`s, but not in general.
Updating that optimization should be a good starting point.

**Comment by mohammadpz** [comment]
fixed in #4062

**Comment by lamblin** [comment]
Another kind of useless dimshuffle are those only shifting around broadcastable dimensions. For instance:
- `DimShuffle{0, x}(col)` when `col.broadcastable = (False, True)`
- `DimShuffle{2, 1, 0}(var)` when `var.broadcastable = (True, False, True)`

The solution would be to not only consider the index of the dimension itself, but also accept 'x' and the index of all broadcastable dimensions as "useless".

**Comment by lamblin** [comment]
Done by #4062.
