### ISSUE TITLE
Replace some Alloc by DimShuffle

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4072]
Sub-ticket of #2943.
When `Alloc` adds broadcastable dimensions (of length 1, to the left), then it can be replaced by a `DimShuffle` instead.

For instance:
- `alloc(3, 1, 1)` could be replaced by `dimshuffle{x, x}(3)` (edit: ~~`dimshuffle{x, x, 0}(3)`~~)
- `alloc([3 4], 1, 3, 2)` could be replaced by `dimshuffle{x, 0, 1}(alloc([3 4], 3, 2)`

**Comment by nouiz** [comment]
I think the first example should be:

 alloc(3, 1, 1) could be replaced by dimshuffle{x, 0}(3) 

I think we can make this work not just when the added dimensions is at the left. But doing it at the left would be a good first step.

**Comment by lamblin** [comment]
I meant `dimshuffle{x,x}(3)`, actually, I'll edit.
Also, alloc only adds dimensions to the left, it cannot add dimensions to the right by itself (the allocated value would have to be dimshuffled already). However, if there are other broadcastable dimensions that were already there before the alloc, then we could "lift" them, but I'm not sure if it is a good idea.

**Comment by lamblin** [comment]
Closed by #4388.
