### ISSUE TITLE
Replace some Reshape by DimShuffle

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4073]
Sub-ticket of #2943.
When Reshape only adds broadcastable dimensions, then it could be replaced by a DimShuffle instead.
However, we would still want to be able to catch shape errors, so we could decide to only make the substitution if the shapes can be inferred to be equal.

One of the ways of doing that would be to only take care of the dimensions of length 1, and have another optimization (maybe already existing) take care of removing things like `reshape(x, x.shape)`.

For instance:
- replace `reshape(x, (1, n))` with `dimshuffle{x,0}(reshape(x, (n,))`
- replace `reshape(x, (1, m, 1, n, 1, 1))` by `dimshuffle{x,0,x,1,x,x}(reshape(x, (m, n)))`

**Comment by nouiz** [comment]
I like the idea to spit this this in 2 optimization. Baybe the second one
is already done.

**Comment by lamblin** [comment]
Closed by #4843
