### ISSUE TITLE
Metadocumentation should request to use Numpy's docstring format

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#4085]
[This](http://deeplearning.net/software/theano/extending/extending_theano.html#documentation) should be fixed.

**Comment by lamblin** [comment]
Also, go through the examples of docstrings in the documentation (in `theano/doc/`, the RST files), and update them if they do not use NumPy format.

**Comment by fvisin** [comment]
@taesupkim you can probably use the email I sent you for the previous ticket as starting point for rewriting the documentation.
