### ISSUE TITLE
-arch passed twice to nvcc

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#4091]
My colleague just updated to the latest Theano master and got the following error when trying to import Theano:
```
nvcc : fatal error : redefinition of argument 'gpu-architecture'
```
Turns out he had the following in his `.theanorc`:
```
[nvcc]
flags = -arch=sm_30
```
And the nvcc call contained `-arch=sm_30 -arch=sm_30`, causing nvcc to abort. Removing the line from `.theanorc` makes it work again, but it used to work correctly with older versions of Theano. No time to do a bisect right now, but can do if nobody recalls committing a change that possibly triggered this.

(Not a high-priority issue, probably, as everything works fine without manually specifying the `-arch` flag -- I think he added this before I knew Theano auto-detects the architecture anyway.)

**Comment by nouiz** [comment]
There was a recent change related to nvcc flags. I didn't taught it can
cause problem with the arch.

thanks for the report. I'm not sure when I can check.

**Comment by f0k** [comment]
Turns out it's not restricted to `-arch`. I've just spend quite some time trying to get Theano working with CUDA under Windows (to document it for Lasagne), and in the end had to add `--cl-version=2010 --use-local-env` to `nvcc.flags`. Those flags *also* end up being duplicated.

Investigating a bit, `NVCC_compiler.compile_args()` gets everything right, i.e., it returns the correct list of flags [in the end](https://github.com/Theano/Theano/blob/d94cdf4f23998cbff5f1f2fc0868d4f4d2de0d75/theano/sandbox/cuda/nvcc_compiler.py#L143). However, `preargs` passed to [`compile_str()`](https://github.com/Theano/Theano/blob/d94cdf4f23998cbff5f1f2fc0868d4f4d2de0d75/theano/sandbox/cuda/nvcc_compiler.py#L148) consists of what `compile_args()` returned plus an extra copy of `config.nvcc.flags.split(' ')`.

Does this ring a bell? Who's calling `NVCC_compiler.compile_args()` and `NVCC_compiler.compile_str()`? Seems that it's not clear who's supposed to add the `nvcc.flags` (it should be `compile_str()` only, as it handles the case of `-arch` being included in `nvcc.flags`).

**Comment by nouiz** [comment]
Thanks for the report. Fixed in https://github.com/Theano/Theano/pull/4161. We where using nvcc.flags elsewhere then in compile_args and at the place it was also adding parameter from compile_args.

**Comment by f0k** [comment]
Ah, you beat me to it. I just finally got around bisecting this to see that 4507dd1 is the culprit.
