### ISSUE TITLE
Recent MRG_RandomStreams slowdown

### ISSUE THREAD

**Issue by diogo149** [Theano/Theano#4098]
I've isolated a weird slowdown in a neural network to commit: adb02ace571898b7faef8b61d9792547af8e0dda and strangely enough the minimal reproducing case doesn't involve cuDNN at all:
```
import theano
import theano.tensor as T
from theano.sandbox.rng_mrg import MRG_RandomStreams

fX = theano.config.floatX
srng = MRG_RandomStreams()
mask = srng.binomial((32, 64, 64, 64), p=0.5, dtype=fX)
fn = theano.function([], mask)
%timeit fn()
```

I've seen the slowdown on both maxwell (titan X: from 12.8ms to 237ms) and kepler (k80 from 14.1ms to 315ms) GPUs.

Let me know if there's anything I can do to help!

**Comment by JohnZed** [comment]
This seems to be an issue with the use of:

`from theano.sandbox.cuda import cuda_available, cuda_enabled, GpuOp`

in rng_mrg.py. This causes the local `rng_mrg.cuda_enabled` variable to be set early on in initialization, so it gets stale and doesn't notice that cuda_enabled is subsequently set to True.

A small patch to fix it is:

```
diff --git a/theano/sandbox/rng_mrg.py b/theano/sandbox/rng_mrg.py
index 6e444dc..e5b0539 100644
--- a/theano/sandbox/rng_mrg.py
+++ b/theano/sandbox/rng_mrg.py
@@ -21,8 +21,9 @@ from theano.compile import optdb
 from theano.gof import local_optimizer
 from . import multinomial
 
-from theano.sandbox.cuda import cuda_available, cuda_enabled, GpuOp
-if cuda_available:
+import theano.sandbox.cuda
+from theano.sandbox.cuda import GpuOp
+if theano.sandbox.cuda.cuda_available:
     from theano.sandbox.cuda import (CudaNdarrayType,
                                      float32_shared_constructor)
 
@@ -1091,7 +1092,7 @@ class MRG_RandomStreams(object):
         self.set_rstate(seed)
 
         if use_cuda is None:
-            self.use_cuda = cuda_enabled
+            self.use_cuda = theano.sandbox.cuda.cuda_enabled
         else:
             self.use_cuda = use_cuda

```

I can submit a PR this weekend if that helps.

**Comment by nouiz** [comment]
Good catch. A PR is welcome.
