### ISSUE TITLE
lib_dirs catch22

### ISSUE THREAD

**Issue by jonathanstrong** [Theano/Theano#4103]
Just pulled the latest version ('0.8.0.dev0.dev-7cc0d87a6197c3905595a0cbf5bc925a64749346') and ran into something that may be related to #4082. 

I have cuda 7.5.18 and cudnn v4 installed and was working mostly fine. 

My .bashrc has these lines

```
export PATH="$PATH:/usr/local/cuda/bin"
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
```

relevant .theanorc lines: 

```
[cuda]
root = /usr/local/cuda
```

The new Theano says "UserWarning: You have the cuda library directory in your lib_dirs. This has been known to cause problems and should not be done."

So, I try 

```
$ LD_LIBRARY_PATH='' ipython

>>> import theano
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: libcublas.so.7.5: cannot open shared object file: No such file or directory
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
```

The warning above stems from sandbox.cuda.nvcc_compiler:222, which was touched 5 days ago w/ a pull request (https://github.com/Theano/Theano/pull/4084/files). 

Since I installed cudnn v4 last week, had a couple times where I had to restart my machine because GPU was suddenly invisible to theano. But it was working mostly. 

What do I need in my .bashrc? What do I need in my .theanorc? 

Seems like a catch22 that 1) theano warns you against something, 2) breaks when you follow the warning. Perhaps could be clarified?

**Comment by fayeshine** [comment]
same problem, please help

**Comment by nouiz** [comment]
I reverted a PR that is causing other problems. It could also cause the problem you see here. Can you update Theano again and tell me how it goes? Also delete your Theano cache. "theano-cache purge"

**Comment by jonathanstrong** [comment]
hmm, I don't see anything new when I pull from master, and don't see any new commits here either https://github.com/Theano/Theano/commits/master. Am I missing something? Perhaps the commit was on another branch?

**Comment by shirtzet** [comment]
same same but.... same
where do i execute "theano-cache purge"?

**Comment by jonathanstrong** [comment]
theano-cache is installed as a cli utility when you install thenao. try

```
which theano-cache
```

should bring up `/usr/local/bin/theano-cache`

**Comment by nouiz** [comment]
You can execute this python function instead:

theano.gof.compiledir.compiledir_purge()

**Comment by nouiz** [comment]
I have a new PR that try to introduce the old PR with fixes. Can you try it?

https://github.com/Theano/Theano/pull/4107

thanks.

**Comment by nouiz** [comment]
gh-4107 fixed this.
