### ISSUE TITLE
Inplace-Operation on Input-Array by simple identity op

### ISSUE THREAD

**Issue by wielandbrendel** [Theano/Theano#4108]
I am getting a slightly funny behaviour for a self-written Op, which I here reduced to the mere identity function:

```
from theano import gof

class Identity(gof.Op):
    __props__ = ()

    def make_node(self, W):
        _W = theano.tensor.as_tensor_variable(W)
        if _W.type.ndim != 2:
            raise TypeError('matrix required for argument: W')

        return theano.Apply(self, [_W], [_W.type()])

    def perform(self, node, inputs, output_storage):
        W, = inputs
        WT, = output_storage
        WT[0] = W

    def infer_shape(self, node, i0_shapes):
        return i0_shapes
```

When I apply this Op on a matrix,

```
V = np.random.randn(1, 1)
W = T.matrix('W')
print(V)
print(Identity()(W).eval({W : V}))
print(V)
print((2*Identity()(W)).eval({W : V}))
print(V)
```

I get the output

```
[[ 0.68445571]]
[[ 0.68445571]]
[[ 0.68445571]]
[[ 1.36891142]]
[[ 1.36891142]]
```

In other words: the numpy array was changed in place by the compiled theano function. Any idea on why this happened?

Also, since we are on it, instead of perform (which, as far as I understand, works on the level of numpy arrays) I'd like to use theano expressions in the Op (instead of writing my own C-code). How can I do this? Thanks a lot in advance!

**Comment by nouiz** [comment]
When an op return memory that is a view of inputs or if it override the
inputs, this add restriction in the order of node execution. Theano need to
know this. The op must add the view_map or destroy_map attribute to tell
this information.

Here is the documentation section:
http://deeplearning.net/software/theano/extending/inplace.html

**Comment by lamblin** [comment]
Regarding your second question, if the operations you want to compose already exist in Theano, then you do not need to write a new Op.
Finally, the `theano-users` and `theano-dev` mailing lists are better suited for such questions and support requests.

**Comment by wielandbrendel** [comment]
@noiuz: thanks for the explanation!
@lamblin: What I try is to change the gradient for a theano expression. But you are right, this should go to the mailing list.
