### ISSUE TITLE
Test Theano with numpy 1.11rc1

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4110]
Check if all tests pass and if there isn't new warning that we need to remove/work around.

Maybe we also need to retest it with numpy 0.11

**Comment by abergeron** [comment]
We already test with 0.11.  Maybe you mean 0.17?

**Comment by nouiz** [comment]
I mean 1.11rc1: https://github.com/numpy/numpy/tree/v1.11.0rc1
release note: https://github.com/numpy/numpy/blob/master/doc/release/1.11.0-notes.rst

**Comment by nouiz** [comment]
Just an update. All tests passes, so we don't need change for the release. There is deprecation warning, but this will be fixed after the release. So I'm removing the milestone.

**Comment by lamblin** [comment]
Some warnings have been removed in #4941.
The following warnings still seem to be there, from the buildbot's output:
```
/usr/local/miniconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py:740: DeprecationWarning: The 'full' option is deprecated in favor of 'reduced'.
For backward compatibility let mode default.
  warnings.warn(msg, DeprecationWarning)
/usr/local/miniconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py:745: DeprecationWarning: The 'economic' option is deprecated.
  warnings.warn(msg, DeprecationWarning)
```
We should investigate where they are coming from and how to fix the corresponding code.

**Comment by nouiz** [comment]
finished in https://github.com/Theano/Theano/pull/4986
