### ISSUE TITLE
print_test_value should be mentioned in debugging tutorial

### ISSUE THREAD

**Issue by rizar** [Theano/Theano#4111]
[This feature](http://deeplearning.net/software/theano/library/config.html#config.print_test_value) should be used [here](http://deeplearning.net/software/theano/tutorial/debug_faq.html).

**Comment by yash14123** [comment]
Working on it.

**Comment by lamblin** [comment]
@IshmaelBelghazi You can take inspiration from #4202 if you want, taking into account the comments that have been made there. Or, if you prefer, you can start from scratch.
