### ISSUE TITLE
Theano with OpenCL tries to use nvcc and hence fails

### ISSUE THREAD

**Issue by Gandhi-Sagar** [Theano/Theano#4112]
After a series of pains, I have installed Theano on a machine with AMD graphics card - `Radeon HD 5450 (Cedar)`. It works perfect with [Hello World](http://deeplearning.net/software/theano/tutorial/using_gpu.html#testing-theano-with-gpu)

Now, consider the following code:
```

import numpy
import theano
import theano.tensor as T
rng = numpy.random

N = 400         #number of samples
feats = 784     #dimensionality of features
D = (rng.randn(N, feats), rng.randint(size=N, low=0, high=2))
training_steps = 10000

# theano symbolic variables
x = T.matrix("x")
y = T.vector("y")
w = theano.shared(rng.randn(784), name="w")
b = theano.shared(0., name="b")

print("Initial Model:")
print(str(w.get_value()) + " " + str(b.get_value()) )

p_1 = 1/(1 + T.exp(-T.dot(x, w) - b))       # probability of target being 1
prediction = p_1 > 0.5                      # prediction threshold
xent = -y * T.log(p_1) - (1-y)*T.log(1-p_1) # cross-entropy loss function
cost = xent.mean() + 0.01 * (w**2).sum()    # cost - to be minimized
gw, gb = T.grad(cost, [w, b])

#compile it
train = theano.function(
                        inputs = [x, y],
                        outputs = [prediction, xent],
                        updates = {w: w - 0.1*gw, b: b - 0.1*gb}    )

predict = theano.function(inputs = [x], outputs = prediction)

#train it
for i in range (training_steps):
    pred, err = train(D[0], D[1])

print("Final Model: ")
print(str(w.get_value()) + " " + str(b.get_value()) )
print("Target values for D: " + str(D[1]))
print("Predictions on D: " + str(D[0]))
```
I get a series of errors: 

```
ERROR (theano.gof.opt): Optimization failure due to: local_gpua_hgemm
ERROR (theano.gof.opt): node: dot(x.T, Elemwise{sub,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.5/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/home/user/anaconda3/lib/python3.5/site-packages/theano/sandbox/gpuarray/opt.py", line 140, in local_opt
    new_op = maker(node, context_name)
  File "/home/user/anaconda3/lib/python3.5/site-packages/theano/sandbox/gpuarray/opt.py", line 732, in local_gpua_hgemm
    if nvcc_compiler.nvcc_version < '7.5':
TypeError: unorderable types: NoneType() < str()
```
and there is series of same messages. So it seems that because `nvcc` is not found, it fails. But I do not have `CUDA`. 

I confirmed that opencl is the active device using:
```
>>> from theano import config
>>> config.device
'opencl0:0'
```
At the end of all error messages, I get the error message:
```
File "pygpu/gpuarray.pyx", line 1950, in pygpu.gpuarray.GpuKernel.__cinit__ (pygpu/gpuarray.c:24214)
  File "pygpu/gpuarray.pyx", line 467, in pygpu.gpuarray.kernel_init (pygpu/gpuarray.c:7174)
pygpu.gpuarray.UnsupportedException: ('The following error happened while compiling the node', GpuElemwise{Composite{((-i0) - i1)}}[(0, 0)]<gpuarray>(GpuFromHost<None>.0, InplaceGpuDimShuffle{x}.0), '\n', b'Device does not support operation')
```
I also tried `optimizer_excluding=conv_dnn` and various other combinations of it, but to no avail.
So is this bug, lack of implementation in `gpuarray` or I am missing on to something?

Regards,
Sagar

**Comment by nouiz** [comment]
Theano OpenCL is close to working, but we don't work on it. So I can guide you on how to fix this, one, but there will be others one following fix. We need someone from the community that help us make it work. Are you interrested? Here is the issue that describe the current status:

https://github.com/Theano/Theano/issues/2936

To fix this error, go in the file theano/sandbox/gpuarray/opt.py. You will need to modify the optimization local_gpua_hgemm to don't. For this in the op_lifter decorator, you can add a parameter cuda_only=True. This will make this optimization skipped on OpenCL. This is the right thing to do, as it don't supper hgemm.

**Comment by Gandhi-Sagar** [comment]
Yes, I would like to contribute. I can devote around 1 hour (almost) every day and may be 2 hours on weekend. Just to make a note, I consider myself more skilled at C++ than Python, I have already taken up to learn Python and I am doing good. Overall, I think I understand Computer in general, so I will be able to pick up the things.
I will join the mailing list later today. In a meanwhile, is there any way to understand the architecture or the library? 
About the above errors:

Apologies, but you meant to change cuda_only=True in the definition of a decorator - overall, i.e. 
`def op_lifter(OP, cuda_only=False):`, right? 
Or did you mean to do this?
```
@register_opt('fast_compile')
@op_lifter([tensor.basic.Dot], cuda_only=True)
def local_gpua_hgemm(node, context_name):
```
i.e. restricting only `local_gpua_hgemm`? 
Pl confirm. I will execute the code with the changes tomorrow.

**Comment by nouiz** [comment]
On Thu, Feb 25, 2016 at 7:53 AM, Gandhi-Sagar <notifications@github.com>
wrote:

> Yes, I would like to contribute. I can devote around 1 hour (almost) every
> day and may be 2 hours on weekend. Just to make a note, I consider myself
> more skilled at C++ than Python, I have already taken up to learn Python
> and I am doing good. Overall, I think I understand Computer in general, so
> I will be able to pick up the things.
> I will join the mailing list later today. In a meanwhile, is there any way
> to understand the architecture or the library?
>

For Theano itself, there is some, but not much is writen for the new GPU
array back-end. Maybe the best for now is that you continue to tell us the
error and I guide you. I will be easier to point to doc related to the
specific error.

For Theano doc, there is the tutorial:

http://deeplearning.net/software/theano/tutorial/

About the above errors:
>
> Apologies, but you meant to change cuda_only=True in the definition of a
> decorator - overall, i.e.
> def op_lifter(OP, cuda_only=False):, right?
> Or did you mean to do this?
>
> @register_opt('fast_compile')
> @op_lifter([tensor.basic.Dot], cuda_only=True)
> def local_gpua_hgemm(node, context_name):
>
> i.e. restricting only local_gpua_hgemm?
> Pl confirm. I will execute the code with the changes tomorrow.
>
The second. Only to local_gpua_hgemm.

I just want to tell you that their is a few weeks full time of work needed
to have everything working. But depending of the operation you need, it can
vary. Can you run Theano with its profiler on the CPU to have an idea of
the operation that you will need?
http://deeplearning.net/software/theano/tutorial/profiling.html

You can just give me this output.

**Comment by nouiz** [comment]
Closing. See https://github.com/Theano/Theano/issues/2936 for opencl status.
