### ISSUE TITLE
Keep stack trace in opt: theano/gpuarray

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4115]
##Sub-ticket of #3018.
Use copy_stack_trace for optimizations defined in `theano/gpuarray/`, and add checks that the stack trace is still there during tests.

**Comment by nouiz** [comment]
We should not spend time in the old back-end for this. Instead, do this in theano/gpuarrray. There is at least the file opt.py and dnn.py.

**Comment by lamblin** [comment]
We should start with `theano/gpuarray/opt.py`, most optimizations can be updated by simply updating `op_lifter`. Then, the optimizations that are not decorated with `@op_lifter(...)` should be updated.
