### ISSUE TITLE
is there any example of h_softmax

### ISSUE THREAD

**Issue by tttwwy** [Theano/Theano#4120]
I am interest in the theano.tensor.nnet.h_softmax, but I don't know how to use it. 
for the softmax,the code is 
y = T.nnet.softmax(T.dot(W, x) + b)
If I want to switch the softmax to h_softmax, what should I do?
Thank you very much.

**Comment by nouiz** [comment]
We have this doc:

http://deeplearning.net/software/theano/library/tensor/nnet/nnet.html#theano.tensor.nnet.h_softmax

Otherwise there is the tests that can help understand how to use it:

https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/tests/test_nnet.py#L1560

**Comment by nouiz** [comment]
issue gh-4122 is about making a tutorial for this. So I'm closing this issue.
