### ISSUE TITLE
Scan memory/speed trade-off

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4124]
When you take the gradient of scan, this scan grad need the full output of the forward scan. So this take much memory. It is possible to only save part of the forward output and to recompute it during the grad to have a much lower memory peak. As the grad of scan take about 6x more time the then forward, we execpt a ~20% slowdown of this, but with a much lower memory peak.

We will make example of how to do that. It should be possible to do this with 2 scan, one inside each other.

@carriepl do you want to add something about this?

**Comment by sindhra** [comment]
Before taking grad scan it passes through error scanner right? and error scanner needs full forward output. I'm not sure if I understood it completely. It would be great if you can elaborate with an example.

PS: newbee alert :)

**Comment by nouiz** [comment]
It was started in https://github.com/Theano/Theano/pull/4271 some times ago.
