### ISSUE TITLE
how to make use of all the history outputs in scan?

### ISSUE THREAD

**Issue by tttwwy** [Theano/Theano#4136]
Each step I want to have access to all the previous return var h
For example,  I want to compute hi = (hi-1 + hi-2 + hi-3 + hi-4...h0)/(i-1),  is there any way to do it

**Comment by sindhra** [comment]
what would be your input parameter in this case?

**Comment by tttwwy** [comment]
The input parameter can be a vector k.In each step,It can be ki, we can assume that i want to compute 
hi = (hi-1 + hi-2 + hi-3 + hi-4...h0)/(i-1) + ki

**Comment by sindhra** [comment]
You will have to accumulate the previous updates and then divide it by current value of (i-1), where i is the step number and ki is the ith element from non_sequences field? 

There is one slight problem, `i-1' will be `0` at `i=1`, then we'll be dividing some quantity by zero
second, what would be the initialised value of h0 in outputs_info?
Please correct me if i'm wrong here.

**Comment by lamblin** [comment]
Please use `theano-users` or StackOverflow for discussing such topics, we try to use the tickets for bugs or missing features only.
For your question, you can pass the whole `h` as a recurrent state, and `i` as a sequence, and from inside the step function, you can access `h[:i]` and return `set_subtensor(h[i], ...)`. It may be memory-inefficient.
