### ISSUE TITLE
Fix dev_start_guide

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#4147]
The instructions to enable the spell check in vim are not working (the curl command doesn't work), refers to `vimrc` instead of `.vimrc`, and more generally the whole section could use a refactoring. I also suggest to use [Vundle](https://github.com/VundleVim/Vundle.vim) instead of Bundle to install vim packages as it's much more flexible, allows to easily install new plugins and update the installed ones hiding much of the complexity from the users. A nice extra would be to provide a list of suggested vim packages and/or a `.vimrc` (I have one in my repo we can link).
Let me know your opinions on this please.

**Comment by nouiz** [comment]
I don't use vim, but if the doc is not working anymore am update would be
good. On which OS do you have the problem?

**Comment by fvisin** [comment]
The current instructions are linux only (`curl` is not installed by default on windows) and fail to install Syntastic at the lab. If vim users don't have anything to say on the Vundle vs Bundle proposal, I will assign this as CCW ticket to someone in the next weeks and rewrite the whole section.

**Comment by fvisin** [comment]
This will be fixed in #4189.

**Comment by nouiz** [comment]
gh-4189 was continued in gh-4335 that is merged. Can we close this issue? If not, what is left?

**Comment by fvisin** [comment]
I confirm that #4335 fixed this. I'm closing the issue.
