### ISSUE TITLE
Questions about conv2d

### ISSUE THREAD

**Issue by dsy412610** [Theano/Theano#4158]
I used conv2d with subsample value (4,4). And now I find a problem is that the training time is even longer than only using CPU. But when I change this value into (1,1), the GPU works. Why? And is there any solutions to this problem?

**Comment by lamblin** [comment]
Can you try again with the latest version from GitHub (or 0.8.0rc1), making sure you are using `theano.tensor.nnet.conv2d`, not `theano.tensor.nnet.conv2d.conv2d`?

**Comment by dsy412610** [comment]
Thank you. But I used Keras which depends on Theano. It uses conv2d as following: theano.tensor.nnet.conv.conv2d. Is anything wrong with that？

**Comment by JesseLivezey** [comment]
If you swap that to ```theano.tensor.nnet.conv2d``` it should work. ```theano.tensor.nnet.conv.conv2d``` is [deprecated](https://github.com/Theano/Theano/blob/99de36c86441e7db7cffe3defaba4749dc2bc1a7/theano/tensor/nnet/conv.py#L43).

**Comment by dsy412610** [comment]
Thank you so much！ I have solved the problem.
