### ISSUE TITLE
setting broadcastable flags on output of MRG_RandomStreams methods

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#4159]
Should these methods not take a 'broadcastable' argument?

**Comment by nouiz** [comment]
We should allow this. I'm not sure of the interface. In the mean mean, you
can use add theano.tensor.addbroadcast()

On Tue, Mar 1, 2016 at 9:51 PM, David Warde-Farley <notifications@github.com

**Comment by nouiz** [comment]
I discussed with @lamblin and here is what we come up.
- We don't like the idea to add a new broadcastable parameter to those functions as currently done by pr gh-4779. We don't support that elsewhere and it help only save 1 line of code (a call to patternbroadcast) that do nothing if nothing is needed. Also in the futur, when we implement the shape inference during the graph construction time, this will become stale.

Current things to do:
- [ ] Document in those mrg function a reference to patternbroadcast. So people will find it easily.
- [ ] Modify mrg_uniform_base.make_node to try to guess the broadcastable flag as we do everywhere else in Theano. This can be do by calling "br = T.extract_constant(size[i]) == 1" for each dimensions. Test that it work when size is a constant vector and when it is a mix of constant value and symbolic value (like the batchsize is non-constant, but the other are constant). Test it when getting value via an uniform().
- [ ] Check the other random distribution. Check if after the uniform value, the graph infer correctly the broadcast pattern. If not, use patternbroadcast after the transformation to insert the right pattern broadcast.

**Comment by Saizheng** [comment]
Pull request here:https://github.com/Theano/Theano/pull/5269

**Comment by nouiz** [comment]
done.

thanks
