### ISSUE TITLE
Conditional breakpoint tutorial example is not working

### ISSUE THREAD

**Issue by Sandy4321** [Theano/Theano#4164]
# Conditional breakpoint
http://deeplearning.net/software/theano/tutorial/debug_faq.html#faq-monitormode
import theano
import theano.tensor as T
from theano.tests.breakpoint import PdbBreakpoint

input = T.fvector()
target = T.fvector()

# Mean squared error between input and target
mse = (input - target) ** 2

# Conditional breakpoint to be activated if the total MSE is higher
# than 100. The breakpoint will monitor the inputs, targets as well
# as the individual error values
breakpointOp = PdbBreakpoint("MSE too high")
condition = T.gt(mse.sum(), 100)
mse, monitored_input, monitored_target = breakpointOp(condition, mse,
                                                      input, target)

# Compile the theano function
fct = theano.function([input, target], mse)

# Use the function
print fct([10, 0], [10, 5]) # Will NOT activate the breakpoint
print fct([0, 0], [10, 5]) # Will activate the breakpoint

error
File "C:\Sander\my_code\Feb12_Theano_Tutorial\S_Theano_Debugging_from_Theano_Spec_March2.py", line 266, in ?
  print fct([10, 0], [10, 5]) # Will NOT activate the breakpoint

invalid syntax: S_Theano_Debugging_from_Theano_Spec_March2.py, line 266, pos 13 in file C:\Sander\my_code\Feb12_Theano_Tutorial\S_Theano_Debugging_from_Theano_Spec_March2.py, line 266
print fct([10, 0], [10, 5]) # Will NOT activate the breakpoint

**Comment by lamblin** [comment]
Are you by chance using python 3? This would explain a syntax error when using `print` as a keyword instead of a function. The examples were written with python 2.

**Comment by nouiz** [comment]
As no reply, I'll close as the answer see good.
