### ISSUE TITLE
Qs about tensor shape

### ISSUE THREAD

**Issue by zeka0** [Theano/Theano#4165]
I wrote this:
x = theano.shared( numpy.zeros( (28, 28) ) )
then I tried to obtain the shape information of x:
print theano.tensor.shape(x)
But instead giving me the result "(28, 28)"
It gives me a tensor: " Shape.0 "
I don't quite understand...
I.e if you set a shared tensor to be shape of (28, 28), then I hope the operation "x.set_value(np.zeros(  ( 54, 54 ) ) )" will be illegal.
Is there any way to enforce the shape of a tensor?
And how can I obtain the right information of a tensor's shape(or a shared tensor's shape)?

**Comment by JesseLivezey** [comment]
You'll should ask questions like this on the theano google group as this isn't an "issue" with theano
https://groups.google.com/forum/#!forum/theano-users

x.shape will return the symbolic shape for the shared variable x, not the shape of the array in memory. If you want that, you can do x.get_value().shape

Theano is generally flexible with the exact shape of a variable, but not the number of dimensions. Computations will crash if there is a shape mismatch. Depending on when you want shapes to be checked, you could precompute shapes, check the shapes of the shared variables like above, or have a compiled theano function return the shape info.
