### ISSUE TITLE
ImportError: cannot import name pool

### ISSUE THREAD

**Issue by talentlei** [Theano/Theano#4167]
when I update Theano , I got this error as follow.  Who Can help me?  thanks a lot.

Using Theano backend.

Traceback (most recent call last):
  File "lstm_loc.py", line 4, in <module>
    from keras.models import Sequential
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 15, in <module>
    from . import backend as K
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/__init__.py", line 46, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 4, in <module>
    from theano.tensor.signal import pool
ImportError: cannot import name pool

**Comment by lamblin** [comment]
The file exists in 0.8.0rc1 (https://github.com/Theano/Theano/blob/rel-0.8.0rc1/theano/tensor/signal/pool.py), so this does not look like a bug in Theano, and I will close the ticket.

What do you mean by "upgrade" Theano? Which version of Theano are you using? You should use 0.8.0rc1 or the latest development version from GitHub.
Is it possible that you have more than one version of Theano installed at the same time?

If you need more assistance, please use [theano-dev](https://groups.google.com/forum/#!forum/theano-dev) or [StackOverflow](http://stackoverflow.com/questions/tagged/theano).

**Comment by ImmanuelSamuel** [comment]
I have the same issue as well. I did git clone and python setup.py develop. I see the pool.py file in theano->tensor->signal->pool.py. But i cannot run 
```from theano.tensor.signal import pool```

**Comment by nouiz** [comment]
You probably have multiple Theano version installed and aren't using the
right one.

you can print theano.__file__ to see the currently imported version.

I would suggest to remove Theano "pip uninstall theano" a few times to make
sure all version are removed and reinstall.
