### ISSUE TITLE
deeplearning.net LeNet uses old conv2d

### ISSUE THREAD

**Issue by JesseLivezey** [Theano/Theano#4174]
The [deeplearning.net LeNet tutorial](http://deeplearning.net/tutorial/lenet.html#the-convolution-operator) uses the ```theano.tensor.nnet.conv.conv2d``` op and also references ```theano.tensor.signal.conv2d``` in the description which is a bit confusing.

**Comment by nouiz** [comment]
We need them to work with the last release. We just did an rc1. So the 0.8 release should be too far. Just after it, we can change this. I tagged this issue for the 0.8 milestone so that we don't forget it.

**Comment by theaverageguy** [comment]
Does it need a fix @nouiz ?

**Comment by nouiz** [comment]
Only after we make the Theano 0.8 release.

**Comment by abergeron** [comment]
The code is already switched to the code to use the new interface (since it is backward compatible).

So we don't need to wait until after the release.

**Comment by nouiz** [comment]
@abergeron told me that we need to change a parameter name as it changed in
the new version after the release. We should also check the doc, it
probably tell about the old parameter name and the old conv2d path.

**Comment by nouiz** [comment]
https://github.com/lisa-lab/DeepLearningTutorials/pull/150
