### ISSUE TITLE
Typo in docs - dnn.enabled flag

### ISSUE THREAD

**Issue by acganesh** [Theano/Theano#4182]
It looks like there's a minor typo in the documentation entry for the [`dnn.enabled`](http://deeplearning.net/software/theano/library/config.html#config.dnn.enabled) flag -- `dnn.enabled` should be `config.dnn.enabled`, mirroring the rest of the config entries.

I'm happy to submit a quick PR if helpful.

**Comment by nouiz** [comment]
A PR would be good.

**Comment by acganesh** [comment]
Submitted PR here: #4191.  Thanks!
