### ISSUE TITLE
Typo in docs - lib.cnmem flag

### ISSUE THREAD

**Issue by acganesh** [Theano/Theano#4183]
There's a small error in the documentation for the [`lib.cnmem`](http://deeplearning.net/software/theano/library/config.html#config.config.lib.cnmem) flag.  It seems like it should say:

> \>1: use that number of MB of memory

instead of ">0" as it currently does.  Let me know if I can submit a PR.

**Comment by nouiz** [comment]
A PR would be great.

**Comment by nouiz** [comment]
a second, > 0 but <=1 is a % of the GPU memory. > 1 is a fixed number of memory. So what do you think happen between 0 and 1? Maybe we can make it more clear in the doc.

**Comment by lamblin** [comment]
Thanks for the report.
Indeed, a PR would be welcome :)

**Comment by lamblin** [comment]
Also, you could add that users should *not* pass `True`.

**Comment by acganesh** [comment]
Great!  I fixed the typo and clarified a few things in my PR here: #4192.  Let me know what you think.

Before this is merged into the 0.8 release, it could make sense to separate the behaviors into two options.  This might improve clarity a little bit.  For example:

1. `config.lib.cnmem.start_frac` - A value between 0 and 1, representing the fraction of GPU memory to be used in the starting memory pool.
2. `config.lib.cnmem.start_mb` - A value representing the number of megabytes (MB) of GPU memory to be used the in the starting memory pool.

**Comment by lamblin** [comment]
Having two different flags exclusive of each other would not be easy, so I would keep the current behaviour.
Ideally, I think it would be better if we had the option of parsing things like "2GB", "150MB", "97%", "0.70", and still fall back to something sensible (no one will ask for less than 1MB or more than 100%).

**Comment by lamblin** [comment]
Closed by #4192.

**Comment by acganesh** [comment]
Makes sense -- I think the smart parsing behavior is a good approach.  If it's helpful, I'm happy to work on implementing that.
