### ISSUE TITLE
Doc in the tutorial a_function.copy()

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4193]
http://deeplearning.net/software/theano/library/compile/function.html?highlight=copy#theano.compile.function_module.Function.copy

* This allow lowering the peak memory when using allow_gc=False as the storage_map can be shared between copies.
* This allow changing the copied function by swapping shared variable (test fn vs valid fn).
* This allow deleting the updates. So can take the train and generated the test fn if they have the same output. (maybe loose some speed computation ...)

Write proper documentation of this feature and add some examples.

**Comment by lamblin** [comment]
Closed by #4419.
