### ISSUE TITLE
Bump tolerance of `test_gc_never_pickles_temporaries`

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4196]
I've seen it fail 3 times in 2 days, and each time a restart of the test "fixed" it.
We should bump the tolerance a little.

**Comment by theaverageguy** [comment]
What does bump tolerance mean?

**Comment by nouiz** [comment]
Check the test. It compare string length with a tolerance. In the ideal case the length would be exact, but they aren't due to technical details. You can probably run 100x the test and see the failure. Do you know how to run only one tests in Theano?

nosetests a_test_file.py:test_name.

**Comment by sygi** [comment]
Hello,
I took a look at the test, but despite 500+ reruns (both cpu and gpu) couldn't reproduce the issue.
(Can I just change https://github.com/Theano/Theano/blob/master/theano/tensor/tests/test_gc.py#L95 128 -> 256, or will that be too big?)

**Comment by nouiz** [comment]
ok.
