### ISSUE TITLE
Impossible to compile a COp with more outputs than inputs

### ISSUE THREAD

**Issue by mjwillson** [Theano/Theano#4199]
This looks like it's due to a typo here:

https://github.com/Theano/Theano/blob/master/theano/gof/op.py#L1426

(should be `range(len(node.outputs))` not `range(len(node.inputs))`)

I ran into it when trying to implement a Gpu-based MaxAndArgmax op:

`('The following error happened while compiling the node', GpuMaxAndArgmaxPerRow(GpuContiguous.0), '\n', 'list index out of range')`

**Comment by mjwillson** [comment]
Furthermore I didn't find any tests at all for COp (although it's indirectly covered via GpuDnnConv) -- I can make a PR for the one-line fix if you want, but not sure I want to take on the task of testing it from scratch, maybe the author has a preference on how it should be tested.

**Comment by nouiz** [comment]
Good catch. A PR with the fix is welcome. I don't think testing COp
directly is possible. At least, I don't know how and the indirect test are
pretty good I think. So I wouldn't spend time on that.

**Comment by nouiz** [comment]
I just saw that this is already done. Thanks.

**Comment by theaverageguy** [comment]
@nouiz I would like to express my interest in Theano for GSoC 2016 with this PR. I am hunting for more bugs to fix before I introduce myself. :)

**Comment by nouiz** [comment]
I would recommand that you introduce yourself now on theano-dev and that
you read https://github.com/Theano/Theano/wiki/GSoC2016

**Comment by mjwillson** [comment]
Nice one, thanks!
