### ISSUE TITLE
Optimization: 0/x -> 0

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#4213]
Discussed in https://github.com/Theano/Theano/issues/4086#issuecomment-186286921, and required for #3758. I'm adding this as an issue so it's not forgotten.

**Arguments against this optimization:**
It will hide NaNs (e.g., 0/0 or 0/nan would become 0).

**Arguments for this optimization:**
There are other optimizations that hide NaNs as well (e.g., for 0 * nan or x / x), and the equivalent 0 * inv(x) is also optimized to 0 already.

**Implementation:**
The optimization of 0*x is part of `theano.tensor.opt.Canonizer`, in its only incarnation `theano.tensor.opt.local_mul_canonizer`. Or maybe it's done by `theano.tensor.opt.local_mul_specialize`, after canonicalization? The latter clearly does it, the former has a lot of code that I don't have the time to read through.

So I guess we'd add a `local_div_of_zero` that looks similar to one of the cases of `local_mul_specialize` (https://github.com/Theano/Theano/blob/5f4eab9/theano/tensor/opt.py#L5382)? If there's consensus, I can do that.

**Comment by nouiz** [comment]
"0 * inv(x)" is optimized by the opt "0 * x". It don't have a specific optimization.

I don't think local_mul_canonizer do that optimization. But we should make sure. If it do or don't add this in its docstring. If it don't why local_mul_specialize is only registered in specialize? I would register it in canonizer and stabilize.

This is always tricky to add such an optimization. We should test it well before merging. Make sure it don't break DLT, and other repo on top of Theano. But we should start by seing if Theano tests pass:)

**Comment by Sandy4321** [comment]
is rprop this kind of optimization

On Fri, Mar 11, 2016 at 12:17 PM, Frédéric Bastien <notifications@github.com

**Comment by nouiz** [comment]
This is optimization done on Theano graph. This isn't machine learning optimization technique. In Theano repo, we don't talk much about machine learning optimization, so most of time, we refert to graph optimization/speed optimization.
