### ISSUE TITLE
RuntimeError: Cuda error 'misaligned address' while copying %lli data element to device memory

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#4219]
I am seeing this sometimes. It usually goes away after restarting the IPython Notebook Kernel:

```
RuntimeError: Cuda error 'misaligned address' while copying %lli data element to device memory
Apply node that caused the error: GpuFromHost(input.input)
Toposort index: 6
Inputs types: [TensorType(float32, 4D)]
Inputs shapes: [(1, 1, 96, 128)]
Inputs strides: [(49152, 49152, 512, 4)]
Inputs values: ['not shown']
Outputs clients: [[GpuContiguous(GpuFromHost.0)]]
```

**Comment by nouiz** [comment]
Those this happen always on the same function? At the same place? Or this
is random?

I don't understand why this happen. Can you try with this PR:

https://github.com/Theano/Theano/pull/4245

it should give a better error message.

**Comment by lamblin** [comment]
Closing as the old back-end has been removed.
