### ISSUE TITLE
Unhandled exception for CuDNN not available error

### ISSUE THREAD

**Issue by cb4** [Theano/Theano#4221]
This is my first programming contribution so if I've submitted this incorrectly please let me know.

I got errors installing theano 0.8.0rc1 into a new python 3.4 environment. Theano found my GTX 970 but always reported CuDNN as "not available" even though v4.0 was installed. Double-checked all environment variables, paths, etc. - they were fine. Troubleshooting turned up a couple of problems in theano/sandbox/cuda/**init**.py. I created a new version with modifications to dnn_available(), dnn_version(), and use(). All mods are documented in the attached new init file. 

Specifically, the issue in the current init file this line was throwing an exception:
        f = theano.function([], DnnVersion()(), theano.Mode(optimizer=None), profile=False)

It wasn't being caught until the handler on line 589. But there it was just being ignored:
                try:
*\*                    (hdr_v, runtime_v) = dnn_version()  #generated the error**
                    cudnn_version = runtime_v
                    #4100 should not print warning with cudnn 4 final.
                    if cudnn_version > 4100:
                        warn = ("Your CuDNN version is more recent then Theano."
                                " If you see problems, try updating Theano or"
                                " downgrading CuDNN to version 4.")
*\*                except Exception:
                    pass  #error ignored
**

Consequently, CuDNN was always reported as not available. I put line 412 in its own try-except block and got the following error instead:
        DLL load failed: The specified module could not be found.

That's as far as I could take it. But with my new init file, I did successfully get theano installed. Let me know if you have any questions.

[**init**.py.txt](https://github.com/Theano/Theano/files/170226/__init__.py.txt)

**Comment by nouiz** [comment]
We get contribution via gihub pull request. Do you want to try that?

We updated Theano with windows fix recently. Can you update Theano to the
dev version (save your modification first) and see if that fix your problem?

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by cb4** [comment]
Yes, I will do a pull request. I checked the latest theano update and it does not fix the problem. I have forked master and will create a pull request probably in the next couple of days. I’m running a long simulation right now that can’t be interrupted.

 

Conrad

**Comment by lamblin** [comment]
Closing as the old back-end has been removed.
