### ISSUE TITLE
Mention alloc_empty_to_zeros in the documentation for tracking NaN.

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4224]
AllocEmpty can introduce NaN when an Op does not properly clear the memory it is working on (for instance, when multiplying by 0 instead of ignoring it, since `0 * NaN => NaN`).
Using `optimizer_including=alloc_empty_to_zeros` replaces `AllocEmpty` by `Alloc{0}`, which is helpful to diagnose where NaNs come from.

**Comment by theaverageguy** [comment]
Where do we add this ?

**Comment by nouiz** [comment]
I would add it to the NanGuardMode documentation:

http://deeplearning.net/software/theano/library/compile/nanguardmode.html#nanguardmode

it is in the file doc/library/compile/nanguardmode.txt.

**Comment by lamblin** [comment]
I think we should actually put it in http://deeplearning.net/software/theano/tutorial/nan_tutorial.html, which lists different possible causes of nan and ways to detect them (including, but not exclusively, NanGuardMode).

**Comment by nouiz** [comment]
done by gh-4576
