### ISSUE TITLE
Could not find .egg-info directory in install record for Theano

### ISSUE THREAD

**Issue by isalirezag** [Theano/Theano#4227]
Im using Ubuntu 14.04 and when I install Teano although it says "succesfully installed Theano, it saied "  Could not find .egg-info directory in install record for Theano".
Please somebody help me why it happened and what do I need to do to fix it.
Thanks

**Comment by lamblin** [comment]
Please use stackoverflow or the `theano-users` mailing list for such support requests.
You will have to provide the exact command you used, the complete error message you received, and try to see if importing theano from Python is actually failing. That could be a simple warning that does not prevent Theano from working.
