### ISSUE TITLE
Import Theano Error

### ISSUE THREAD

**Issue by CongB** [Theano/Theano#4229]
I just installed all the required packages of theano and then installed theano. The installation is smooth but issue pops out when I try to import theano. I tried to uninstall and re-install it several times and use wheel to do the installation. Issue still not solved..

> Python 3.5.1 |Continuum Analytics, Inc.| (default, Jan 29 2016, 15:01:46) on Windows (64 bits).
> This is the IEP interpreter.
> Prepending the project path 'c:\\users\\cong\\dropbox' to sys.path
> Using IPython 4.1.2 -- An enhanced Interactive Python.
> In [1]: (executing cell "show the list of ..." (line 2 of "0314.py"))
> show the list of installed packages
> ['anaconda-client==1.3.1', 'clyent==1.2.1', 'conda-env==2.4.5', 'conda==4.0.4', 'cycler==0.10.0', 'decorator==4.0.9', 'ipython-genutils==0.1.0', 'ipython==4.1.2', 'matplotlib==1.5.1', 'menuinst==1.3.2', 'networkx==1.11', 'numpy==1.10.4', 'pandas==0.18.0', 'path.py==0.0.0', 'patsy==0.4.0', 'pickleshare==0.5', 'pillow==3.1.1', 'pip==8.1.0', 'pycosat==0.6.1', 'pycrypto==2.6.1', 'pymc==2.3.6', 'pyparsing==2.0.3', 'pyreadline==2.1', 'python-dateutil==2.4.2', 'pytz==2015.7', 'pyyaml==3.11', 'requests==2.9.1', 'scikit-image==0.12.3', 'scikit-learn==0.17.1', 'scikit-rf==0.14.1', 'scipy==0.17.0', 'setuptools==20.2.2', 'simplegeneric==0.8.1', 'six==1.10.0', 'sphinx==1.3.1', 'statsmodels==0.6.1', 'traitlets==4.1.0', 'wheel==0.29.0']
>  In [2]: pip install theano
> Collecting theano
> Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.2 in c:\miniconda3\lib\site-packages (from theano)
> Requirement already satisfied (use --upgrade to upgrade): scipy>=0.11 in c:\miniconda3\lib\site-packages (from theano)
> Installing collected packages: theano
> Successfully installed theano-0.7.0
>  In [3]: import theano
> ===============================
> ```
> 00001	#include <Python.h>
> 00002	#include "structmember.h"
> 00003	#include <sys/time.h>
> 00004	
> 00005	// Old Python compatibility from here:
> 00006	// http://www.python.org/dev/peps/pep-0353/
> 00007	#if PY_VERSION_HEX < 0x02050000 && !defined(PY_SSIZE_T_MIN)
> 00008	typedef int Py_ssize_t;
> 00009	#define PY_SSIZE_T_MAX INT_MAX
> 00010	#define PY_SSIZE_T_MIN INT_MIN
> 00011	// This one was taken from:
> 00012	// http://svn.python.org/projects/python/trunk/Modules/_ctypes/ctypes.h
> 00013	#define PyNumber_AsSsize_t(ob, exc) PyInt_AsLong(ob)
> 00014	#endif
> 00015	
> 00016	#if PY_VERSION_HEX >= 0x03000000
> 00017	#include "numpy/npy_3kcompat.h"
> 00018	#define PyCObject_AsVoidPtr  NpyCapsule_AsVoidPtr
> 00019	#define PyCObject_GetDesc  NpyCapsule_GetDesc
> 00020	#define PyCObject_Check NpyCapsule_Check
> 00021	#endif
> 00022	
> 00023	#ifndef Py_TYPE
> 00024	#define Py_TYPE(obj) obj->ob_type
> 00025	#endif
> ...
> 01077	    return RETVAL;
> 01078	}
> 01079	
> 01080	
> ```
> ===============================
> Problem occurred during compilation with the command line below:
> C:\Miniconda3\Scripts\g++.bat -shared -g -march=corei7 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=generic -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -Ic:\miniconda3\lib\site-packages\numpy\core\include -Ic:\miniconda3\include -o C:\Users\Cong\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Cong\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64\lazylinker_ext\mod.cpp -Lc:\miniconda3\libs -Lc:\miniconda3 -lpython35
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `_import_array':
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1641: undefined reference to `__imp_PyExc_ImportError'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1647: undefined reference to `__imp_PyExc_AttributeError'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1652: undefined reference to `__imp_PyCapsule_Type'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1653: undefined reference to `__imp_PyExc_RuntimeError'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1668: undefined reference to `__imp_PyExc_RuntimeError'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1676: undefined reference to `__imp_PyExc_RuntimeError'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1682: undefined reference to `__imp_PyExc_RuntimeError'
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1692: undefined reference to `__imp_PyExc_RuntimeError'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1704: more undefined references to `__imp_PyExc_RuntimeError' follow
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `NpyCapsule_Check':
> c:/miniconda3/lib/site-packages/numpy/core/include/numpy/npy_3kcompat.h:406: undefined reference to `__imp_PyCapsule_Type'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `unpack_list_of_ssize_t':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:58: undefined reference to `__imp_PyExc_TypeError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:68: undefined reference to `__imp_PyExc_IndexError'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_init':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:362: undefined reference to `__imp_PyExc_IndexError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:380: undefined reference to `__imp_PyExc_IndexError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:395: undefined reference to `__imp_PyExc_IndexError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:399: undefined reference to `__imp_PyExc_IndexError'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:403: more undefined references to `__imp_PyExc_IndexError' follow
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_init':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:415: undefined reference to `__imp_PyExc_TypeError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:450: undefined reference to `__imp_PyExc_TypeError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:454: undefined reference to `__imp__Py_NoneStruct'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `c_call':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:555: undefined reference to `__imp__Py_NoneStruct'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:556: undefined reference to `__imp__Py_NoneStruct'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:556: more undefined references to `__imp__Py_NoneStruct' follow
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `lazy_rec_eval':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:628: undefined reference to `__imp_PyExc_IndexError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:667: undefined reference to `__imp_PyExc_IndexError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:718: undefined reference to `__imp__Py_NoneStruct'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:725: undefined reference to `__imp_PyExc_TypeError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:731: undefined reference to `__imp_PyExc_TypeError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:782: undefined reference to `__imp__Py_NoneStruct'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_call':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:817: undefined reference to `__imp__Py_NoneStruct'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:817: undefined reference to `__imp__Py_NoneStruct'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:818: more undefined references to `__imp__Py_NoneStruct' follow
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_call':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:867: undefined reference to `__imp_PyExc_AssertionError'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:911: undefined reference to `__imp__Py_NoneStruct'
> C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_set_allow_gc':
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:943: undefined reference to `__imp_PyBool_Type'
> C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:946: undefined reference to `__imp__Py_TrueStruct'
> collect2.exe: error: ld returned 1 exit status
> 
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> c:\miniconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>()
>      64         if version != getattr(lazylinker_ext, '_version', None):
> ---> 65             raise ImportError()
>      66 except ImportError:
> 
> ImportError: 
> 
> During handling of the above exception, another exception occurred:
> 
> ImportError                               Traceback (most recent call last)
> c:\miniconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>()
>      81             if version != getattr(lazylinker_ext, '_version', None):
> ---> 82                 raise ImportError()
>      83         except ImportError:
> 
> ImportError: 
> 
> During handling of the above exception, another exception occurred:
> 
> Exception                                 Traceback (most recent call last)
> <ipython-input-2-3397704bd624> in <module>()
> ----> 1 import theano
> 
> c:\miniconda3\lib\site-packages\theano\__init__.py in <module>()
>      53     object2, utils
>      54 
> ---> 55 from theano.compile import \
>      56     SymbolicInput, In, \
>      57     SymbolicOutput, Out, \
> 
> c:\miniconda3\lib\site-packages\theano\compile\__init__.py in <module>()
>       7         SpecifyShape, specify_shape, register_specify_shape_c_code)
>       8 
> ----> 9 from theano.compile.function_module import *
>      10 
>      11 from theano.compile.mode import *
> 
> c:\miniconda3\lib\site-packages\theano\compile\function_module.py in <module>()
>      16 from theano import gof
>      17 from theano.compat.python2x import partial
> ---> 18 import theano.compile.mode
>      19 from theano.compile.io import (
>      20     In, SymbolicInput, SymbolicInputKit, SymbolicOutput)
> 
> c:\miniconda3\lib\site-packages\theano\compile\mode.py in <module>()
>       9 import  theano
>      10 from theano import gof
> ---> 11 import theano.gof.vm
>      12 from theano.configparser import config, AddConfigVar, StrParam
>      13 from theano.compile.ops import register_view_op_c_code, _output_guard
> 
> c:\miniconda3\lib\site-packages\theano\gof\vm.py in <module>()
>     566 
>     567 try:
> --> 568     from . import lazylinker_c
>     569 
>     570     class CVM(lazylinker_c.CLazyLinker, VM):
> 
> c:\miniconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>()
>     115             args = cmodule.GCC_compiler.compile_args()
>     116             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
> --> 117                                              preargs=args)
>     118             # Save version into the __init__.py file.
>     119             init_py = os.path.join(loc, '__init__.py')
> 
> c:\miniconda3\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module)
>    2008             # difficult to read.
>    2009             raise Exception('Compilation failed (return status=%s): %s' %
> -> 2010                             (status, compile_stderr.replace('\n', '. ')))
>    2011         elif config.cmodule.compilation_warning and compile_stderr:
>    2012             # Print errors just below the command line.
> 
> Exception: Compilation failed (return status=1): C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `_import_array':
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1641: undefined reference to `__imp_PyExc_ImportError'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1647: undefined reference to `__imp_PyExc_AttributeError'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1652: undefined reference to `__imp_PyCapsule_Type'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1653: undefined reference to `__imp_PyExc_RuntimeError'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1668: undefined reference to `__imp_PyExc_RuntimeError'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1676: undefined reference to `__imp_PyExc_RuntimeError'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1682: undefined reference to `__imp_PyExc_RuntimeError'
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1692: undefined reference to `__imp_PyExc_RuntimeError'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:c:/miniconda3/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1704: more undefined references to `__imp_PyExc_RuntimeError' follow
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `NpyCapsule_Check':
> . c:/miniconda3/lib/site-packages/numpy/core/include/numpy/npy_3kcompat.h:406: undefined reference to `__imp_PyCapsule_Type'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `unpack_list_of_ssize_t':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:58: undefined reference to `__imp_PyExc_TypeError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:68: undefined reference to `__imp_PyExc_IndexError'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_init':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:362: undefined reference to `__imp_PyExc_IndexError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:380: undefined reference to `__imp_PyExc_IndexError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:395: undefined reference to `__imp_PyExc_IndexError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:399: undefined reference to `__imp_PyExc_IndexError'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:403: more undefined references to `__imp_PyExc_IndexError' follow
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_init':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:415: undefined reference to `__imp_PyExc_TypeError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:430: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:436: undefined reference to `__imp_PyExc_IndexError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:450: undefined reference to `__imp_PyExc_TypeError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:454: undefined reference to `__imp__Py_NoneStruct'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `c_call':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:555: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:555: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:555: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:556: undefined reference to `__imp__Py_NoneStruct'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:556: more undefined references to `__imp__Py_NoneStruct' follow
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `lazy_rec_eval':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:628: undefined reference to `__imp_PyExc_IndexError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:651: undefined reference to `__imp_PyExc_TypeError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:659: undefined reference to `__imp_PyExc_ValueError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:667: undefined reference to `__imp_PyExc_IndexError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:718: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:725: undefined reference to `__imp_PyExc_TypeError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:731: undefined reference to `__imp_PyExc_TypeError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:781: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:781: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:782: undefined reference to `__imp__Py_NoneStruct'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_call':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:817: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:817: undefined reference to `__imp__Py_NoneStruct'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o:C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:818: more undefined references to `__imp__Py_NoneStruct' follow
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_call':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:867: undefined reference to `__imp_PyExc_AssertionError'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:910: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:910: undefined reference to `__imp__Py_NoneStruct'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:911: undefined reference to `__imp__Py_NoneStruct'
> . C:\Users\Cong\AppData\Local\Temp\ccMHnQSz.o: In function `CLazyLinker_set_allow_gc':
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:943: undefined reference to `__imp_PyBool_Type'
> . C:/Users/Cong/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.1-64/lazylinker_ext/mod.cpp:946: undefined reference to `__imp__Py_TrueStruct'
> . collect2.exe: error: ld returned 1 exit status

**Comment by nouiz** [comment]
Don't use python 3.5 with Theano on windows. They changed many things and
we didn't had anyone try to fix them.

Python 2.7 or 3.4 should work.

**Comment by CongB** [comment]
@nouiz  Thanks a lot. I saw on the introduction page that any python version >= 3.3 would work. But after many frustrations I'm now settled with 3.4.

**Comment by nouiz** [comment]
@fvisin can you make sure it get in the doc that on python 3.5 don't work
on windows?

thanks

**Comment by fvisin** [comment]
Sure!

Ciao,
Francesco
