### ISSUE TITLE
Documentation markdown for tensor transpose is messed up

### ISSUE THREAD

**Issue by hlin117** [Theano/Theano#4254]
Seen on [this page](http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor._tensor_py_operators.transpose).

![screenshot 2016-03-18 01 22 35](https://cloud.githubusercontent.com/assets/1865885/13869968/15d20b2c-eca8-11e5-8262-7d44d359b295.png)

Related: #4141. (Transpose is not mentioned in that issue.)

**Comment by fvisin** [comment]
Thank you @hlin117. I took note of it in #4141, it will take us some time to go through everything, but we will try our best to fix the documentation in a reasonable amount of time.

**Comment by lamblin** [comment]
There's a bit more discussion on #4875, so I'll close this one.
