### ISSUE TITLE
Optimization of FGraph reports bug

### ISSUE THREAD

**Issue by Sylvus** [Theano/Theano#4255]
Hi, I'm using Lasagne and everything works fine. However, when starting my program I get the following message:

> <<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer') MergeOptimizer
> ERROR (theano.gof.opt): SeqOptimizer apply MergeOptimizer
> ERROR (theano.gof.opt): Traceback:
> ERROR (theano.gof.opt): Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 230, in apply
>     sub_prof = optimizer.optimize(fgraph)
>   File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 89, in optimize
>     ret = self.apply(fgraph, _args, *_kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 817, in apply
>     fgraph.replace_all_validate(pairs, 'MergeOptimizer')
>   File "/usr/local/lib/python3.4/dist-packages/theano/gof/toolbox.py", line 309, in replace_all_validate
>     fgraph.replace(r, new_r, reason=reason, verbose=False)
>   File "/usr/local/lib/python3.4/dist-packages/theano/gof/fg.py", line 566, in replace
>     str(reason))
> TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')

It doesn't bother me because the program still runes but in case this was an unknown bug, I wanted to share it. If you want I can post my lasagne code but it is really just a collection of standard convolutional layers.

Currently using theano
0.8.0rc1.dev-35254935ca6cf165481154d7bbc77e0bf732f929
with python3

**Comment by nouiz** [comment]
Can you update Theano to the dev version:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

And tell us if it still happen? If it still happen, I would like a way to
reproduce this.

thanks

**Comment by Sylvus** [comment]
I updated to the dev version (there were only one or two commits missing). The error message stayed but the line numbers changed slightly so I'm posting it again:

>   [output_lin_ctc, output_softmax, cost_train], updates=updates, on_unused_input='warn')
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply MergeOptimizer
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/opt.py", line 817, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/usr/local/lib/python3.4/dist-packages/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (False, True, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')


Is there an easy way how I can help you to reproduce this? I can't share my whole codebase which means I would need to extract the critical part and see if it still happens, right?

**Comment by nouiz** [comment]
You can use function_dump() for this case:

http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

Do that only on the function that fail.

**Comment by Sylvus** [comment]
Thanks, I did that. Attached is the dump.
[function_dump.zip](https://github.com/Theano/Theano/files/179804/function_dump.zip)

**Comment by pchavanne** [comment]
Hi, I get the s

**Comment by pchavanne** [comment]
Hi, I get the same kind of message:

```

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', AllocEmpty{dtype='float32'}.0, AllocEmpty{dtype='float32'}.0, TensorType(float32, row), TensorType(float32, matrix), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7fe7bffc8e90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 817, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', AllocEmpty{dtype='float32'}.0, AllocEmpty{dtype='float32'}.0, TensorType(float32, row), TensorType(float32, matrix), 'MergeOptimizer')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', AllocEmpty{dtype='float32'}.0, AllocEmpty{dtype='float32'}.0, TensorType(float32, row), TensorType(float32, matrix), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7fe7be56a790>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 2223, in apply
    sub_prof = gopt.apply(fgraph)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 817, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/philippe/anaconda/lib/python2.7/site-packages/theano/gof/fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', AllocEmpty{dtype='float32'}.0, AllocEmpty{dtype='float32'}.0, TensorType(float32, row), TensorType(float32, matrix), 'MergeOptimizer')


```

**Comment by drasmuss** [comment]
I get the same error.  Here is a minimal example that will reproduce the bug:

```python
import lasagne as lgn
import theano
import theano.tensor as T

input_layer = lgn.layers.InputLayer(shape=(32, 3, 5, 5))

# note: if you change n_filters to anything >1, the bug goes away
n_filters = 1
output_layer = lgn.layers.Conv2DLayer(input_layer, num_filters=n_filters,
                                      filter_size=3)

target_var = T.tensor4("target_var", "floatX")

loss = lgn.objectives.squared_error(lgn.layers.get_output(output_layer),
                                    target_var).mean()

# note: if you change l_rate to 1, the bug goes away
l_rate = 0.9
update = lgn.updates.rmsprop(loss, lgn.layers.get_all_params(output_layer),
                             learning_rate=l_rate)
func = theano.function([input_layer.input_var, target_var], loss,
                              updates=update)
```

**Comment by nouiz** [comment]
If I'm running Theano with the last release 0.8.2, this code snippet reproduce the problem. But if I use the dev version of Theano it work well. So update Theano to :

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by drasmuss** [comment]
I believe I am on the latest dev version, but I still get the error.  

`theano.__version__ = 0.9.0dev1.dev-9ea0f3f26474c7716268a3404ca3d828b7e67e76`

**Comment by nouiz** [comment]
What Theano flag do you use?

**Comment by drasmuss** [comment]
Here is my `.theanorc` (I'm not setting any other options within the script)

```
[global]
device = gpu
floatX = float32
warn_float64 = raise

[lib]
cnmem = 0.8

[blas]
ldflags = -LD:/Anaconda3/pkgs/mkl-11.3.1-0/Library/bin -lmkl_rt
```

**Comment by nouiz** [comment]
I tried to reproduce it and wasn't able.

Could you have 2 Theano version and that they get mixed?

**Comment by drasmuss** [comment]
I created a totally fresh virtual environment, but the same thing occurred. Here's the full output:
```
[tmp] >pip freeze
-e git+https://github.com/Lasagne/Lasagne@1565826486fd2081d3fb0da31949f1338f203f05#egg=Lasagne
numpy==1.11.0
scipy==0.17.1
six==1.10.0
-e git+https://github.com/Theano/Theano@9ea0f3f26474c7716268a3404ca3d828b7e67e76#egg=Theano

[tmp] >python tmp.py
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5005)
theano.__version__: 0.9.0dev1.dev-9ea0f3f26474c7716268a3404ca3d828b7e67e76
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (True, False, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply MergeOptimizer
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "...\theano\theano\gof\opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "...\theano\theano\gof\opt.py", line 90, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "...\theano\theano\gof\opt.py", line 855, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "...\theano\theano\gof\toolbox.py", line 312, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "...\theano\theano\gof\fg.py", line 506, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', GpuAllocEmpty.0, GpuAllocEmpty.0, CudaNdarrayType(float32, (True, False, False, False)), CudaNdarrayType(float32, 4D), 'MergeOptimizer')
```

This is on Windows 10, if that helps.  Is there any other debugging info I could provide that would help narrow it down?

**Comment by nouiz** [comment]
a general fix is already merged. So if someone find this issue again, make sure to update Theano.
