### ISSUE TITLE
gpuarray.GpuJoin with negative axes

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4262]
This ticket is about cleaning up the fix in #4258.
- [ ] First, we should sort out if `axis` should be changed to a signed type in `gpuarray`, in `pygpu`, or if only Theano Ops should accept negative axes.
- [ ] Then, we should make `GpuJoin.perform` raise `IndexError` instead of `OverflowError` when axis < -ndim, be it by modifying `perform` or something in `pygpu` or in `gpuarray` to add explicit checks, instead of relying on Cython's overflow checks.
- [ ] Finally, in [`test_basic.py`](https://github.com/Theano/Theano/pull/4258/files#diff-bd238af9c7f5e76b67885294b7da00aa), we should change the `assertRaises` to only accept `IndexError`, not `OverflowError`

**Comment by gokul-uf** [comment]
@lamblin I'd like to work on this
I suggest that we do it in Theano Op so that it is caught early/higher up in the compilation process.

**Comment by abergeron** [comment]
I think that all the points are addressed now.
