### ISSUE TITLE
Blocks tests non-deterministically segfault with latest Theano and default optimizer

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#4266]
TestRecurrentWrapper in tests/bricks/test_recurrent.py is causing a segfault but only sometimes. In fact, I haven't gotten to work except in the context of running the entire test suite.

Running with device=cpu and float64.

**Comment by nouiz** [comment]
Can you start it with gdb to know where that happen?

**Comment by nouiz** [comment]
Closing as no news and not enough information to do something.
