### ISSUE TITLE
Deprecation warning while upgrading to 0.8.0

### ISSUE THREAD

**Issue by gokul-uf** [Theano/Theano#4274]
While upgrading to Theano 0.8 from Theano 0.7 via `pip` ( `sudo pip install --upgrade theano` ) , I get the following warning
`DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.`

This message came up while the install uninstalled and installed numpy. Is this normal behavior or should it be something that needs to be fixed?

The full message is 

> Collecting theano
  Downloading Theano-0.8.0.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 604kB/s 
Collecting numpy>=1.7.1 (from theano)
  Downloading numpy-1.10.4.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 456kB/s 
Requirement already up-to-date: scipy>=0.11 in /usr/local/lib/python2.7/dist-packages (from theano)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from theano)
Installing collected packages: numpy, theano
  Found existing installation: numpy 1.8.2
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.2:
      Successfully uninstalled numpy-1.8.2
  Running setup.py install for numpy ... done
  Found existing installation: Theano 0.7.0
    Uninstalling Theano-0.7.0:
      Successfully uninstalled Theano-0.7.0
  Running setup.py install for theano ... done
Successfully installed numpy-1.10.4 theano-0.8.0

**Comment by abergeron** [comment]
This is normal and has nothing to do with Theano.

It is there because the previous version of numpy was installed with distutils instead of pip.

Also, you don't have to update numpy to install the newer theano, 1.8 is still supported.

**Comment by nouiz** [comment]
You can pass the parameter --no-deps to pip to not upgrade Theano
dependency.
