### ISSUE TITLE
Help with following error message

### ISSUE THREAD

**Issue by sebastianrisi** [Theano/Theano#4280]
I get the following error message when I try to run any Theano code on my Mac. More specifically, when the code includes "theano.function(...)", , Reinstalling/updating Theano and anaconda didn't help. A couple of days ago it worked fine. I think the only difference is the "Command Line Tools (OS X 10.11) for Xcode" update that was installed. I tried downloading Xcode and changing the used command line tools from to "/Library/Developer/CommandLineTools to  "Applications/Xcode.app", which also didn't help. Any help would be greatly appreciate. 

$ python test.py 
===============================
00001	#include <Python.h>
00002	#include <iostream>
00003	#include "theano_mod_helper.h"
00004	#include <math.h>
00005	#include <numpy/arrayobject.h>
00006	#include <numpy/arrayscalars.h>
00007	//////////////////////
00008	////  Support Code
00009	//////////////////////
00010	
00011	
00012	    namespace {
00013	    struct __struct_compiled_op_5558d5d588540c868bea4e3d250b251f {
00014	        PyObject* __ERROR;
00015	
00016	        PyObject* storage_V3;
00017	PyObject* storage_V1;
00018	        
00019	
00020	        __struct_compiled_op_5558d5d588540c868bea4e3d250b251f() {
00021	            // This is only somewhat safe because we:
00022	            //  1) Are not a virtual class
00023	            //  2) Do not use any virtual classes in the members
00024	            //  3) Deal with mostly POD and pointers
00025	
00026	            // If this changes, we would have to revise this, but for
00027	            // now I am tired of chasing segfaults because
00028	            // initialization code had an error and some pointer has
00029	            // a junk value.
00030	            memset(this, 0, sizeof(*this));
00031	        }
00032	        ~__struct_compiled_op_5558d5d588540c868bea4e3d250b251f(void) {
00033	            cleanup();
00034	        }
00035	
00036	        int init(PyObject* __ERROR, PyObject* storage_V3, PyObject* storage_V1) {
00037	            Py_XINCREF(storage_V3);
00038	Py_XINCREF(storage_V1);
00039	            this->storage_V3 = storage_V3;
00040	this->storage_V1 = storage_V1;
00041	            
00042	
00043	
00044	
00045	            this->__ERROR = __ERROR;
00046	            return 0;
00047	        }
00048	        void cleanup(void) {
00049	            __label_1:
00050	
00051	double __DUMMY_1;
00052	__label_3:
00053	
00054	double __DUMMY_3;
00055	__label_6:
00056	
00057	double __DUMMY_6;
00058	
00059	            Py_XDECREF(this->storage_V3);
00060	Py_XDECREF(this->storage_V1);
00061	        }
00062	        int run(void) {
00063	            int __failure = 0;
00064	            
00065	    PyObject* py_V1;
00066	    
00067	        PyArrayObject* V1;
00068	        
00069	    PyObject* py_V3;
00070	    
00071	        PyArrayObject* V3;
00072	        
00073	{
00074	
00075	    py_V1 = PyList_GET_ITEM(storage_V1, 0);
00076	    {Py_XINCREF(py_V1);}
00077	    
00078	        if (py_V1 == Py_None)
00079	        {
00080	            
00081	        V1 = NULL;
00082	        
00083	        }
00084	        else
00085	        {
00086	            
00087	        V1 = (PyArrayObject*)(py_V1);
00088	        Py_XINCREF(V1);
00089	        
00090	        }
00091	        
00092	{
00093	
00094	    py_V3 = PyList_GET_ITEM(storage_V3, 0);
00095	    {Py_XINCREF(py_V3);}
00096	    
00097	        V3 = (PyArrayObject*)(py_V3);
00098	        Py_XINCREF(V3);
00099	        
00100	{
00101	// Op class DimShuffle
00102	if (PyArray_NDIM(V3) != 0){PyErr_SetString(PyExc_NotImplementedError, "input nd"); {
00103	        __failure = 5;
00104	        if (!PyErr_Occurred()) {
00105	            PyErr_SetString(PyExc_RuntimeError,
00106	                "Unexpected error in an Op's C code. "
00107	                "No Python exception was set.");
00108	            }
00109	        goto __label_5;};};
00110	if (V1) {Py_XDECREF(V1);};
00111	{ PyArrayObject * V3__view_or_copy = (PyArrayObject*)PyArray_FromAny((PyObject*)V3, NULL, 0, 0, NPY_ARRAY_ALIGNED|NPY_ARRAY_ENSURECOPY, NULL);
00112	npy_intp dimensions[1];
00113	dimensions[0] = 1;
00114	npy_intp strides[1];
00115	strides[0] = 0;
00116	if (strides[1-1] == 0) strides[1-1] = PyArray_DESCR(V3__view_or_copy)->elsize;
00117	V1 = (PyArrayObject*)PyArray_New(&PyArray_Type, 1, dimensions, PyArray_TYPE(V3__view_or_copy), strides, PyArray_DATA(V3__view_or_copy), PyArray_ITEMSIZE(V3__view_or_copy), (NPY_ARRAY_WRITEABLE*PyArray_ISWRITEABLE(V3__view_or_copy)), NULL);
00118	if (V1 == NULL) {
00119	        __failure = 5;
00120	        if (!PyErr_Occurred()) {
00121	            PyErr_SetString(PyExc_RuntimeError,
00122	                "Unexpected error in an Op's C code. "
00123	                "No Python exception was set.");
00124	            }
00125	        goto __label_5;};;
00126	PyArray_UpdateFlags(V1, NPY_ARRAY_UPDATE_ALL);
00127	
00128	#if NPY_API_VERSION < 0x00000007
00129	PyArray_BASE(V1) = (PyObject*)V3__view_or_copy;
00130	#else
00131	PyArray_SetBaseObject(V1, (PyObject*)V3__view_or_copy);
00132	#endif
00133	};__label_5:
00134	
00135	double __DUMMY_5;
00136	
00137	}
00138	__label_4:
00139	
00140	        if (V3) {
00141	            Py_XDECREF(V3);
00142	        }
00143	        
00144	    {Py_XDECREF(py_V3);}
00145	    
00146	double __DUMMY_4;
00147	
00148	}
00149	__label_2:
00150	
00151	    if (!__failure) {
00152	      
00153	        {Py_XDECREF(py_V1);}
00154	        if (!V1) {
00155	            Py_INCREF(Py_None);
00156	            py_V1 = Py_None;
00157	        }
00158	        else if ((void*)py_V1 != (void*)V1) {
00159	            py_V1 = (PyObject*)V1;
00160	        }
00161	
00162	        {Py_XINCREF(py_V1);}
00163	
00164	        if (V1 && !PyArray_ISALIGNED((PyArrayObject*) py_V1)) {
00165	            PyErr_Format(PyExc_NotImplementedError,
00166	                         "c_sync: expected an aligned array, got non-aligned array of type %ld"
00167	                         " with %ld dimensions, with 3 last dims "
00168	                         "%ld, %ld, %ld"
00169	                         " and 3 last strides %ld %ld, %ld.",
00170	                         (long int) PyArray_TYPE((PyArrayObject*) py_V1),
00171	                         (long int) PyArray_NDIM(V1),
00172	                         (long int) PyArray_NDIM(V1) >= 3 ?
00173	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-3] : -1,
00174	                         (long int) PyArray_NDIM(V1) >= 2 ?
00175	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-2] : -1,
00176	                         (long int) PyArray_NDIM(V1) >= 1 ?
00177	        PyArray_DIMS(V1)[PyArray_NDIM(V1)-1] : -1,
00178	                         (long int) PyArray_NDIM(V1) >= 3 ?
00179	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-3] : -1,
00180	                         (long int) PyArray_NDIM(V1) >= 2 ?
00181	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-2] : -1,
00182	                         (long int) PyArray_NDIM(V1) >= 1 ?
00183	        PyArray_STRIDES(V1)[PyArray_NDIM(V1)-1] : -1
00184	        );
00185	            {
00186	        __failure = 2;
00187	        if (!PyErr_Occurred()) {
00188	            PyErr_SetString(PyExc_RuntimeError,
00189	                "Unexpected error in an Op's C code. "
00190	                "No Python exception was set.");
00191	            }
00192	        goto __label_2;}
00193	        }
00194	        
00195	      PyObject* old = PyList_GET_ITEM(storage_V1, 0);
00196	      {Py_XINCREF(py_V1);}
00197	      PyList_SET_ITEM(storage_V1, 0, py_V1);
00198	      {Py_XDECREF(old);}
00199	    }
00200	    
00201	        if (V1) {
00202	            Py_XDECREF(V1);
00203	        }
00204	        
00205	    {Py_XDECREF(py_V1);}
00206	    
00207	double __DUMMY_2;
00208	
00209	}
00210	
00211	            
00212	        if (__failure) {
00213	            // When there is a failure, this code puts the exception
00214	            // in __ERROR.
00215	            PyObject* err_type = NULL;
00216	            PyObject* err_msg = NULL;
00217	            PyObject* err_traceback = NULL;
00218	            PyErr_Fetch(&err_type, &err_msg, &err_traceback);
00219	            if (!err_type) {err_type = Py_None;Py_INCREF(Py_None);}
00220	            if (!err_msg) {err_msg = Py_None; Py_INCREF(Py_None);}
00221	            if (!err_traceback) {err_traceback = Py_None; Py_INCREF(Py_None);}
00222	            PyObject* old_err_type = PyList_GET_ITEM(__ERROR, 0);
00223	            PyObject* old_err_msg = PyList_GET_ITEM(__ERROR, 1);
00224	            PyObject* old_err_traceback = PyList_GET_ITEM(__ERROR, 2);
00225	            PyList_SET_ITEM(__ERROR, 0, err_type);
00226	            PyList_SET_ITEM(__ERROR, 1, err_msg);
00227	            PyList_SET_ITEM(__ERROR, 2, err_traceback);
00228	            {Py_XDECREF(old_err_type);}
00229	            {Py_XDECREF(old_err_msg);}
00230	            {Py_XDECREF(old_err_traceback);}
00231	        }
00232	        // The failure code is returned to index what code block failed.
00233	        return __failure;
00234	        
00235	        }
00236	    };
00237	    }
00238	    
00239	
00240	        static int __struct_compiled_op_5558d5d588540c868bea4e3d250b251f_executor(__struct_compiled_op_5558d5d588540c868bea4e3d250b251f* self) {
00241	            return self->run();
00242	        }
00243	
00244	        static void __struct_compiled_op_5558d5d588540c868bea4e3d250b251f_destructor(void* executor, void* self) {
00245	            delete ((__struct_compiled_op_5558d5d588540c868bea4e3d250b251f*)self);
00246	        }
00247	        
00248	//////////////////////
00249	////  Functions
00250	//////////////////////
00251	static PyObject * instantiate(PyObject * self, PyObject *argtuple) {
00252	  assert(PyTuple_Check(argtuple));
00253	  if (3 != PyTuple_Size(argtuple)){ 
00254	     PyErr_Format(PyExc_TypeError, "Wrong number of arguments, expected 3, got %i", (int)PyTuple_Size(argtuple));
00255	     return NULL;
00256	  }
00257	  __struct_compiled_op_5558d5d588540c868bea4e3d250b251f* struct_ptr = new __struct_compiled_op_5558d5d588540c868bea4e3d250b251f();
00258	  if (struct_ptr->init( PyTuple_GET_ITEM(argtuple, 0),PyTuple_GET_ITEM(argtuple, 1),PyTuple_GET_ITEM(argtuple, 2) ) != 0) {
00259	    delete struct_ptr;
00260	    return NULL;
00261	  }
00262	  PyObject* thunk = PyCObject_FromVoidPtrAndDesc((void*)(&__struct_compiled_op_5558d5d588540c868bea4e3d250b251f_executor), struct_ptr, __struct_compiled_op_5558d5d588540c868bea4e3d250b251f_destructor);
00263	  return thunk; }
00264	
00265	//////////////////////
00266	////  Module init
00267	//////////////////////
00268	static PyMethodDef MyMethods[] = {
00269		{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
00270		{NULL, NULL, 0, NULL}
00271	};
00272	PyMODINIT_FUNC init5558d5d588540c868bea4e3d250b251f(void){
00273	   import_array();
00274	   (void) Py_InitModule("5558d5d588540c868bea4e3d250b251f", MyMethods);
00275	}
00276	
===============================
Problem occurred during compilation with the command line below:
/usr/bin/clang++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=haswell -target-feature -sse4a -target-feature -avx512bw -target-feature +cx16 -target-feature -tbm -target-feature +xsave -target-feature -fma4 -target-feature -avx512vl -target-feature -prfchw -target-feature +bmi2 -target-feature -adx -target-feature -xsavec -target-feature +fsgsbase -target-feature +avx -target-feature -avx512cd -target-feature -avx512pf -target-feature +rtm -target-feature +popcnt -target-feature +fma -target-feature +bmi -target-feature +aes -target-feature +rdrnd -target-feature -xsaves -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +avx2 -target-feature -avx512er -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -avx512f -target-feature +f16c -target-feature +ssse3 -target-feature +mmx -target-feature +cmov -target-feature -xop -target-feature -rdseed -target-feature +movbe -target-feature +hle -target-feature +xsaveopt -target-feature -sha -target-feature +sse2 -target-feature +sse3 -target-feature -avx512dq -D NPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/Users/sebr/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/sebr/anaconda/include/python2.7 -I/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof -fvisibility=hidden -o /Users/sebr/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.11-64/tmpK1YDfv/5558d5d588540c868bea4e3d250b251f.so /Users/sebr/.theano/compiledir_Darwin-15.0.0-x86_64-i386-64bit-i386-2.7.11-64/tmpK1YDfv/mod.cpp -L/Users/sebr/anaconda/lib
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sse4a'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-tbm'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-fma4'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-prfchw'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-rdseed'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sha'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: no such file or directory: '+cx16'
clang: error: no such file or directory: '+xsave'
clang: error: no such file or directory: '+bmi2'
clang: error: language not recognized: 'savec'
clang: error: no such file or directory: '+fsgsbase'
clang: error: no such file or directory: '+avx'
clang: error: no such file or directory: '+rtm'
clang: error: no such file or directory: '+popcnt'
clang: error: no such file or directory: '+fma'
clang: error: no such file or directory: '+bmi'
clang: error: no such file or directory: '+aes'
clang: error: no such file or directory: '+rdrnd'
clang: error: language not recognized: 'saves'
clang: error: no such file or directory: '+sse4.1'
clang: error: no such file or directory: '+sse4.2'
clang: error: no such file or directory: '+avx2'
clang: error: no such file or directory: '+sse'
clang: error: no such file or directory: '+lzcnt'
clang: error: no such file or directory: '+pclmul'
clang: error: no such file or directory: '+f16c'
clang: error: no such file or directory: '+ssse3'
clang: error: no such file or directory: '+mmx'
clang: error: no such file or directory: '+cmov'
clang: error: language not recognized: 'op'
clang: error: no such file or directory: '+movbe'
clang: error: no such file or directory: '+hle'
clang: error: no such file or directory: '+xsaveopt'
clang: error: no such file or directory: '+sse2'
clang: error: no such file or directory: '+sse3'

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: DimShuffle{x}(TensorConstant{-1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/tensor/opt.py", line 5825, in constant_folding
    no_recycling=[])
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/Users/sebr/anaconda/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2196, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ("Compilation failed (return status=1): clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sse4a'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-tbm'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-fma4'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-prfchw'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-rdseed'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-sha'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: unknown argument: '-target-feature'. clang: error: no such file or directory: '+cx16'. clang: error: no such file or directory: '+xsave'. clang: error: no such file or directory: '+bmi2'. clang: error: language not recognized: 'savec'. clang: error: no such file or directory: '+fsgsbase'. clang: error: no such file or directory: '+avx'. clang: error: no such file or directory: '+rtm'. clang: error: no such file or directory: '+popcnt'. clang: error: no such file or directory: '+fma'. clang: error: no such file or directory: '+bmi'. clang: error: no such file or directory: '+aes'. clang: error: no such file or directory: '+rdrnd'. clang: error: language not recognized: 'saves'. clang: error: no such file or directory: '+sse4.1'. clang: error: no such file or directory: '+sse4.2'. clang: error: no such file or directory: '+avx2'. clang: error: no such file or directory: '+sse'. clang: error: no such file or directory: '+lzcnt'. clang: error: no such file or directory: '+pclmul'. clang: error: no such file or directory: '+f16c'. clang: error: no such file or directory: '+ssse3'. clang: error: no such file or directory: '+mmx'. clang: error: no such file or directory: '+cmov'. clang: error: language not recognized: 'op'. clang: error: no such file or directory: '+movbe'. clang: error: no such file or directory: '+hle'. clang: error: no such file or directory: '+xsaveopt'. clang: error: no such file or directory: '+sse2'. clang: error: no such file or directory: '+sse3'. ", '[DimShuffle{x}(TensorConstant{-1.0})]')
....

**Comment by nouiz** [comment]
Just a follow up, this is fixed by this PR:
https://github.com/Theano/Theano/pull/4281

It is caused by new version of apple software that don't support old stuff.
