### ISSUE TITLE
Cannot import Theano 8.0 with Xcode 7.3 (7D175)

### ISSUE THREAD

**Issue by jli05** [Theano/Theano#4282]
`import theano` will trigger loads of errors as:

> clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-rdseed'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-hle'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-sha'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: unknown argument: '-target-feature'
clang: error: no such file or directory: '+cx16'
clang: error: no such file or directory: '+xsave'
clang: error: no such file or directory: '+bmi2'
clang: error: language not recognized: 'savec'
clang: error: no such file or directory: '+fsgsbase'
clang: error: no such file or directory: '+avx'
clang: error: no such file or directory: '+popcnt'

I'm on MacBook Air with Python 3.5.1, Xcode 7.3 (7D175). The suggested fix on the following page doesn't work.

http://cloudspace.com/blog/2014/03/23/2014-03-23-cant-install-gems-after-upgrading-to-xcode-5.1-heres-the-solution/#.VvHHY2M3eUs

**Comment by abergeron** [comment]
Yes Xcode 7.3 was release the day after 0.8 but it is fixed in the development version.

You can use the current master: http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions to get it working.

We will probably do release 0.8.1 in a bit to have an official fixed release.

**Comment by nouiz** [comment]
Closing as the update will fix it.

**Comment by jli05** [comment]
It'd be great if we do a bugfix/patchset release. Ordinary users would welcome a latest and stable working copy.
