### ISSUE TITLE
conv.conv2d to Segmentation fault

### ISSUE THREAD

**Issue by zhaolei** [Theano/Theano#4284]
img size 24,25  conv.conv2d is OK!

` stone@gpu test $ python cnn02.py `
- Using gpu device 0: GeForce GTX 970
- filter: (5, 3, 9, 9)
- img.shape: (24, 25, 3)
- img_.shape: (1, 3, 24, 25)
- filtered_img.shape: (1, 5, 16, 17)

img size > 24,25 conv.conv2d is  **Segmentation fault**

`stone@gpu test $ python cnn02.py `

- Using gpu device 0: GeForce GTX 970
- filter: (5, 3, 9, 9)
- img.shape: (75, 75, 3)
- img_.shape: (1, 3, 75, 75)
- Segmentation fault

Theano Version 0.7.0, install By pip

**Comment by zhaolei** [comment]
`theano-cache purge `
Than it's OK  

ths

**Comment by nouiz** [comment]
We released Monday Theano 0.8. It contain speed too many updates to list here. I strongly recommand that you update. Probabaly a theano-cache purge before using the new version will help.
