### ISSUE TITLE
ImportError "from theano.sandbox.cuda import filter as type_support_filter"

### ISSUE THREAD

**Issue by wcy0319** [Theano/Theano#4291]
I get the ImportError by the line, "from theano.sandbox.cuda import filter as type_support_filter".Can anyone help me?Thanks!

**Comment by nouiz** [comment]
Can you give the full error mesage? The problem is probably that the GPU
isn'T enabled. Did you set the Theano flag device=gpu?

Also, user question are better asked on theano-user mailing list.

**Comment by wcy0319** [comment]
@nouiz thanks! you ara right,issue solved.
