### ISSUE TITLE
inc_subtensor doesn't handle Reshape nodes correctly

### ISSUE THREAD

**Issue by around1991** [Theano/Theano#4293]
Hi all

The following code errors:

```python
import theano
import numpy as np

lookup = theano.shared(np.random.uniform(size=(5, 5)))
indices = theano.tensor.lmatrix()

subtensor = lookup[indices]
output = subtensor.sum()

grad = theano.grad(output, subtensor)
update = theano.tensor.inc_subtensor(subtensor, 0.1*grad)

f = theano.function([indices], output, updates=[(lookup, update)])

f(np.array([[1, 2, 3]]))  # gives an error
```

I think the issue is in how inc_subtensor handles Reshape nodes. At line 1157, it says that the higher-dimensional subtensor ``x`` is flattened, but no flattening actually takes place. This causes dimension mismatches (because ``y`` is flattened).

Does anyone have a solution for this?

Thanks
Kris

**Comment by nouiz** [comment]
We know about this. The solution isn't fast, but we are going there.

If manually, you converte the indices matrix to a vector and reshape
yourself the output of the call to inc_subtensor, it should work. We do
that internally, but we loose the information of how to reshape back in
some cases.

If you can confirm that this fix your problem, it would be great.

**Comment by around1991** [comment]
Hi Fred, that works. I had to reshape the updates I passed in as well (to account for the flattened indices matrix).

Thanks for the suggestion! I hope the fix goes well :)

**Comment by nouiz** [comment]
This is the same problem as https://github.com/Theano/Theano/issues/3575, so I'll close this issue. You can subscribe to the other to be kept updated on this.
