### ISSUE TITLE
Theano can not compile with cuDNN

### ISSUE THREAD

**Issue by rachidasen** [Theano/Theano#4294]
After copy and pasting cudnn.h to /usr/local/cuda/include/
the following error message came

`Theano can not compile with cuDNN. We got this error:
/tmp/try_flags_Zk7PdX.c:5:19: fatal error: /usr/local/cuda/include/cudnn.h: Permission denied
 #include <cudnn.h>`

Then I change the permission of `/usr/local/cuda/include/cudnn.h` to 666, the following error came

`AssertionError: cuDNN optimization was enabled, but Theano was not able to use it. We got this error: 
Theano can not compile with cuDNN. We got this error:
/usr/bin/ld: cannot find -lcudnn
collect2: error: ld returned 1 exit status
`

**Comment by nouiz** [comment]
You didn't install cudnn correctly.

You need to install the header (*.h file) and also the shared library. *.so* file:

http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html

User questions/help request should be asked on stackoverflow or theano-user mailing list.
