### ISSUE TITLE
Scan ValueError on Theano 0.8, while runned well on 0.7

### ISSUE THREAD

**Issue by PierrotLC** [Theano/Theano#4295]
My scan functions used to run well on previous Theano version 0.7.

After upgrading to 0.8 git version, I have a ValueError : `When compiling the inner function of scan (the function called by scan in each of its iterations) the following error has been encountered: The initial state (`outputs_info`in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 1) has 4 dimension(s), while the corresponding variable in the result of the inner function of scan (`fn`) has 2 dimension(s) (it should be one less than the initial state).`

As I did not find the answer in "Issues", could you explain me the matter please ?
Thanks in advance !

**Comment by nouiz** [comment]
Normally, this error mean there is a problem in the user code. But if it
work with an older version of Theano, then I'm not so sure. I think we
always tested to raise that error correctly.

Do you use many taps for some recurrent value? If so, the initial state for
that state need to have an ndim of one more then the ndim of each iteration.

On Fri, Mar 25, 2016 at 8:27 AM, Pierre Luppi Chen <notifications@github.com

**Comment by PierrotLC** [comment]
Thank you for answering Nouiz !
I use no taps, but outputs_info have 3 elements which are 3-D tensors.
I also have a 1D array as sequence.
The lambda function then has 4 inputs, 3 outputs and one update.

**Comment by PierrotLC** [comment]
I must also say that I upgraded to Python 3.5 w/ Anaconda 2.5. I don't know if this matters.
I gonna try to make the scripts run w/ the Python 3.4 I used to have, and still Theano 0.8.

**Comment by PierrotLC** [comment]
I downgraded CLT to previous version for XCode 7.2, to use Theano 0.7.
The scripts run well then.
After that, I upgraded Theano to 0.8 (not the git version), that works w/ CLT XCode 7.2. Then I found the former ValueError.
I conclude that something not obvious has changed between Theano 0.7 and 0.8.

**Comment by nouiz** [comment]
Can you give the full stack trace and code to reproduce this?
Le 26 mars 2016 05:47, "Pierre Luppi Chen" <notifications@github.com> a
écrit :

**Comment by PierrotLC** [comment]
I won't bother you with that, as there may be 2000 coding lines.
I will test next week each computation inside the scan lambda function stack.
I think this must just be a stack/concatenate Theano operation that has changed between 0.7 and 0.8 and does not have the desired output anymore.

**Comment by lamblin** [comment]
The interface for [`tensor.stack`](http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor.stack) has changed indeed, but the previous behaviour should have been retained with a warning.
It may also be that scan is now stricter than it used to be, and not ignoring any more something that should have been an error.
In any case, please keep us updated.

**Comment by PierrotLC** [comment]
Thank you Pascal for your answer !
Indeed I use 7 times the old tensor.stack version w/out axis precised.
What are the new errors recognized by 0.8 scan version that were not by previous one ?

**Comment by nouiz** [comment]
Can this issue be closed?
