### ISSUE TITLE
update does not have same type as original shared variable

### ISSUE THREAD

**Issue by asimkievich** [Theano/Theano#4297]
I am getting the error below, executing theano 0.8.0 from keras 0.3.2 - any hints?

TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by nouiz** [comment]
If you make issue on different repo, link them to help keep the information
linked. I give an answer on the other ticket:

https://github.com/fchollet/keras/issues/2083
