### ISSUE TITLE
Older Theano version

### ISSUE THREAD

**Issue by PierrotLC** [Theano/Theano#4299]
A dumb question :
Is it possible to download a previous version of Theano, like the 0.7 ?

Thanks in advance !

**Comment by gokul-uf** [comment]
yes, 
use `pip install theano==0.7`, 
more details at http://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

In fact, even a specific commit from source by using 
`pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git@<MD5sum of commit>`
http://www.deeplearning.net/software/theano/install.html#specific-git-commit

**Comment by PierrotLC** [comment]
Thank you very much !
