### ISSUE TITLE
Bilinear_Upsampling requires to specify batch_size and num_input_channels

### ISSUE THREAD

**Issue by MarcoCiccone** [Theano/Theano#4303]
Referring to this line:
https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/abstract_conv.py#L570

this piece of code doesn't work with `batch_size` and/or `num_input_channels` set to `None`
it requires to specify the dimensions as scalar values

**Comment by lamblin** [comment]
Indeed. We should `input.shape[0]` and `input.shape[1]` instead if they are not None.

**Comment by nouiz** [comment]
Just a follow up, a PR have the fix: https://github.com/Theano/Theano/pull/4343/files, it just miss a test.
