### ISSUE TITLE
fail to use Theano and Keras 

### ISSUE THREAD

**Issue by bqf2008** [Theano/Theano#4304]
I installed Theano and Keras to apply neural network in python. However the compilation failed with errors in the attached file.
I'm a mac user with OSX10.11.4. I'm wondering what could the problem be?

[Error.docx](https://github.com/Theano/Theano/files/191023/Error.docx)

**Comment by gokul-uf** [comment]
Upgrade to the bleeding edge version of Theano. This is a known issue and will be fixed in 0.8.1 to be released on Tuesday.
See: https://github.com/Theano/Theano/issues/4296

**Comment by nouiz** [comment]
closing as duplicate of gh-4296. To have the work around Xcode interface change, use Theano dev version: 

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
