### ISSUE TITLE
clang: error: unknown argument: '-target-feature'

### ISSUE THREAD

**Issue by anayebi** [Theano/Theano#4306]
I recently updated my Mac to use El Capitan v. 10.11.4, and I found that I am getting a "clang: error: unknown argument: '-target-feature'." error when running Theano 0.8.0.

Is there a workaround for this?

Thanks in advance!

**Comment by nirum** [comment]
The answer here:
http://stackoverflow.com/questions/36213642/mac-osx10-11-4-python3-import-theano-error

suggests that it is a problem with the latest version of Xcode, but that there will be an update tomorrow (3/29/2016) that will fix it.

**Comment by nouiz** [comment]
You can update Theano to the dev version until the new release. It is
stable, you can use it without problems.

Fred
