### ISSUE TITLE
OpenMP support on Mac OS X

### ISSUE THREAD

**Issue by kevin-keraudren** [Theano/Theano#4307]
OpenMP can be installed on a Mac with `brew install clang-omp`. The C++ compiler that needs to be used for the '-fopenmp' flag to work is then:

```python
import theano
theano.config.cxx = '/usr/local/bin/clang-omp++'
```

However, theano expects either g++ or clang++ as a custom compiler, so here:

https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L1828

we should add:

```python
    and 'clang-omp++' not in theano.config.cxx
```

**Comment by nouiz** [comment]
thanks. Do you want to make a PR? We can do it if you prefer.

**Comment by gokul-uf** [comment]
@kevin-keraudren  could you close this? Thanks

**Comment by nouiz** [comment]
done, so closing.
