### ISSUE TITLE
theano_backend: Bug when device is changed from cpu to gpu

### ISSUE THREAD

**Issue by fnmps** [Theano/Theano#4311]
There is a problem when you change from CPU to GPU using:
`theano.sandbox.cuda.use('gpu')`

On theano_backend.py the following code:
```
def _on_gpu():
    '''Return whether the session is set to
    run on GPU or not (i.e. on CPU).
    '''
    return theano.config.device[:3] == 'gpu' or theano.sandbox.cuda.cuda_enabled


if _on_gpu():
    '''Import cuDNN only if running on GPU:
    not having Cuda installed should not
    prevent from running the present code.
    '''
    from theano.sandbox.cuda import dnn
```

is not expecting that change, making it cause an error, for example, in this condition statement on the same file:
`if _on_gpu() and dnn.dnn_available():`

since it will return true from `_on_gpu() ` but the dnn isn't defined because it failed to run the code that would import the dnn, when it first started.

This can easily be fixed with seperate conditions, something like:

```
if _on_gpu(): 
    if 'dnn' not in globals(): 
        from theano.sandbox.cuda import dnn
    if dnn.dnn_available():
    (...)
```

**Comment by nouiz** [comment]
Where those _on_gpu() is used? It whould be:

def _on_gpu():
      import theano.sandbox.cuda
      return theano.sandbox.cuda.cuda_enabled

This is the right way to know if the GPU was enabled.

**Comment by fnmps** [comment]
It is at least used in the conv2d function.

That is not the problem. The problem is if you start with cpu the _on_gpu will return false (as it should) and it won't import the dnn (again as it is expected).

However if you change at a later time to gpu, the condition to import the dnn is not executed, but the _on_gpu is returning true, therefore causing the following error:

`NameError: global name 'dnn' is not defined`

**Comment by nouiz** [comment]
This method isn't from Theano. Where it come from?

**Comment by fnmps** [comment]
Oh, you're right! 

Just noticed this is in keras and not theano package.
