### ISSUE TITLE
Removing pygments dependency

### ISSUE THREAD

**Issue by mgermain** [Theano/Theano#4315]
I don't think that `pygments` is still a dependency for the documentation.

http://deeplearning.net/software/theano/install.html#requirements

**Comment by nouiz** [comment]
I also think that. The last time that line in the doc that tell is a
dependency was changed is in 2010.

Also grep about it to make sure to remove all reference. There was one in a
conf file.

**Comment by gokul-uf** [comment]
This is `git grep "pygments"` output

```
doc/conf.py:pygments_style = 'sphinx'
doc/install.txt:    `Sphinx <http://sphinx.pocoo.org/>`_ >= 0.5.1, `pygments <ht
doc/library/d3viz/index.ipynb:   "pygments_lexer": "ipython2",
```

@nouiz  I think we can go ahead and remove the pygments dependency.

**Comment by gokul-uf** [comment]
@nouiz @mgermain disregard my previous message. I checked `sphinx` docs. They say that you need `pygments` for code highlighting. Guess we still have pygments as a dependency, then. http://www.sphinx-doc.org/en/stable/intro.html#prerequisites

**Comment by mgermain** [comment]
Thanks for looking that up.

**Comment by nouiz** [comment]
Can you add that information in the doc/conf.py file just before adding it
with the link to where this add the dependency?

@mgermain, I think we should add it in the soft dependency for doc in the
setup.py file. What do you think?

**Comment by mgermain** [comment]
Yup, I'll add it to the optional deps in the setup.py now.
