### ISSUE TITLE
Disable test values in BNComposite.__init__

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4321]
In `tensor/nnet/bn.py`, we build a scalar graph for the Composite Op.
This is troublesome when using `compute_test_values != 'off'` because the inputs of that graph are created without test values.
Since it is not possible to get test values from the inputs (we will have access to the tensor inputs in `make_node` only), we should temporarily set `compute_test_values = 'off'` for that part.

**Comment by dwf** [comment]
Can you just assign arbitrary scalar test values as a workaround?

**Comment by lamblin** [comment]
Yes, but I don't think that it would be a shorter fix.

**Comment by nouiz** [comment]
We can use the decorator to change it for just a function. We should add a test for that too.

@theano.configparser.change_flags(compute_test_value='off')

issue: https://github.com/Theano/Theano/issues/4319 is also the same problem, but at a different place.

**Comment by nouiz** [comment]
done by gh-4378
