### ISSUE TITLE
GPU implementation of Diag

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4322]
This was needed on the mailing list: [theano-users] What is the fastest way to create a diagonal matrix from a vector?

There is a work around:
non_zero_indices = theano.shared((np.arange(0,d)*(d)+np.arange(0,d2)).astype('int32'),name='non_zero_indices')
update_gamma_delta_large = theano.function(inputs=[],updates=[(gamma_delta_large,T.set_subtensor(gamma_delta_large[non_zero_indices],gamma_delta))])
updateGamma = theano.function(inputs = [], updates=[(Gamma,T.reshape(gamma_delta_large,(d,d),ndim=2))])

Ideally, we should implement it directly on GPU, make a new GPU op that init memory to zero with a small kernel that set the data at the right place.
An alternative is to make an optimization that will implement the work around.

**Comment by bouthilx** [comment]
@nouiz AllocDiag will be deprecated in favor of theano.tensor.basic.Diag, see #4169.

**Comment by nouiz** [comment]
If that don't remove feature, I'm good with that.

**Comment by bouthilx** [comment]
Should not. I would add tickets for a full GPU implementation for both Diagonal (successor of ExtractDiag) and Diag (successor of AllocDiag). This ticket could simply be renamed with AllocDiag->Diag.

**Comment by nouiz** [comment]
I think we support some of the case in Theano right now. We should not
merge a PR that would temporarily remove that. So just double check that. I
think we currently support ExtractDiag on the GPU, so I'm not sure why you
make it a separate task.

On Wed, Apr 6, 2016 at 2:27 PM, Xavier Bouthillier <notifications@github.com

**Comment by bouthilx** [comment]
ExtractDiag and Diagonal does the same thing, except ExtractDiag also runs on the GPU and Diagonal support extra parameters (so it's more flexible). The new version of Diagonal would work on the GPU with default parameters, as for ExtractDiag, but only on CPU for non-default values.

I was planning to make a ticket to add GPU support for any values, not only the default ones. I'm breaking it down to make it easier to manage relatively small CCW tasks.

**Comment by nouiz** [comment]
look good. thanks.

On Wed, Apr 6, 2016 at 3:45 PM, Xavier Bouthillier <notifications@github.com

**Comment by abergeron** [comment]
Closed by #5247

**Comment by abergeron** [comment]
Sorry It was Diagonal that was done, not Diag.

**Comment by abergeron** [comment]
Done in https://github.com/Theano/Theano/pull/5524
