### ISSUE TITLE
theano.tensor.squeeze() is not as expected ?

### ISSUE THREAD

**Issue by wangg12** [Theano/Theano#4325]
```
a=np.ones((1,5))
aa=theano.shared(value=a.astype('float32'))
aa.eval().shape
# (1, 5)
aa.squeeze().eval().shape
# (1, 5)

theano.__version__ 
'0.8.0'
```
It seems `squeeze()` does nothing. Is this a bug?

**Comment by nouiz** [comment]
squeeze will only remove broadcastable dimensions. Theano broadcastable
dimensions aren't dependent of the shape, but on the type.

theano.shared() by default suppose the shape can change. So by default, all
dimensions are not broadcastable. So by default squeeze don't remove them.
You can specify shared variable broadcastable dimensions like this:

>>> aa=theano.shared(value=a.astype('float32'), broadcastable=(True,False))
>>> aa.squeeze().eval().shape
(5,)

**Comment by wangg12** [comment]
@nouiz Got it. Thanks!
