### ISSUE TITLE
Softmax computation error

### ISSUE THREAD

**Issue by zeka0** [Theano/Theano#4331]
I have tried a following sentence in python2.7:
```python
import theano
from theano import tensor as T
xT = T.matrix()
yT = T.nnet.softmax(xT)
fun = theano.function(inputs=[xT], outputs=yT)
print fun(np.array([[ 7037.5136159, 7611.69078938, 7197.10745514, 7373.56197423, 7395.85992396, 7241.17424998, 7202.14100706, 7449.58107226, 7190.49475249, 7514.04714423]]))
```
And surprisingly the answer is:
*[[  4.34532158e-250   1.00000000e+000   8.88680500e-181   3.81917535e-104
    1.84436182e-094   1.22098825e-161   1.36392181e-178   3.95043019e-071
    1.19367302e-183   3.92557897e-043]]*

I have tried the same thing on matlib and it reports that because the operation exp(xT) causes some values to be Inf, the computation can't be completed.
However theano seems to have find a way out.
Here is my question: why there is a **1.00000000e+000** here? It shouldn't have this value obviously!

**Comment by JesseLivezey** [comment]
The value could be 1.-4e-43 (next largest value), but this truncates to 1. even in float64. You're putting numbers that are around 7k with differences of 100 into exponentials and running into the limits of floating point values.

**Comment by zeka0** [comment]
Thanks! Now I understand why this happens now.
