### ISSUE TITLE
I am not seeing versions above 0.7.0 with `pip search theano`

### ISSUE THREAD

**Issue by xguse** [Theano/Theano#4349]
BUT when I go to pypi (https://pypi.python.org/pypi/Theano) the list the version hosted as 0.8.1.

Is there a problem with how the version is being listed inside the package maybe?  Or is the problem just in `pip` having issues getting the latest versions of the pkg db?

Anyone else seen this?

**Comment by lamblin** [comment]
It looks like an issue with how `pip` displays things, or tries to determine what the "latest" version is.
Calling `yolk -V theano` gives `Theano 0.8.1`, and calling `pip install Theano` on a system where Theano is not installed fetches 0.8.1.

**Comment by gokul-uf** [comment]
@xguse It seems that `pip` installs an older version if you have it locally.
Take a look at the answers [here](http://stackoverflow.com/questions/14617136/why-is-pip-installing-an-old-version-of-my-package)
