### ISSUE TITLE
Implementation of "R-ReLU" based on theano

### ISSUE THREAD

**Issue by lixin77** [Theano/Theano#4350]
I want to implement the Randomized Leaky Rectified Linear Unit and the script does work on **theano vector**. My script is below:
*****************************************************
def ReLU(x):
    y = T.maximum(0.0, x)
    return(y)

def RReLU(x, rng):
    srng = RandomStreams(seed=rng.randint(99999))
    y, updates = theano.scan(lambda v: ifelse(T.gt(v, 0.0), v, v * srng.uniform(low=3.0, high=8.0, dtype='float32')), sequences=x)
    return(y) 
*****************************************************
However, it cannot apply on the  matrix or high dimensional tensor since "Condition" given to the op of "ifelse" has to be a scalar

Are there any methods in **theano** to get the result like **RELU** does which sets all negative elements in the tensor to zero and keeps the same values for positive ones using **T.maximum(0.0, x)**

**Comment by lamblin** [comment]
- Those kinds of questions should be asked on `theano-users` or StackOverflow, we try to keep the tickets for bug reports or feature requests
- As the [documentation](http://deeplearning.net/software/theano/tutorial/conditions.html) mentions, you can use `theano.tensor.switch` to have conditions in a tensor.

**Comment by lixin77** [comment]
Thanks a lot and I have found another approach to solve this problem
