### ISSUE TITLE
An error with bilinear_upsampling

### ISSUE THREAD

**Issue by shampool** [Theano/Theano#4351]
`AsTensorError: ('Cannot convert (None, None, Elemwise{mul,no_inplace}.0, Elemwise{mul,no_inplace}.0) to TensorType', <type 'tuple'>)`

```
bilinear_upsampling(X,ratio = 2, batch_size=None,   num_input_channels=None, use_1D_kernel=True)
```

**Comment by fvisin** [comment]
This is most probably related to #4303, that is being addressed and should be fixed soon.
The next time please provide the complete error message.

**Comment by lamblin** [comment]
Closing as a duplicate of #4303.

**Comment by nouiz** [comment]
Can you give the full error message? We can't help with just that part.

**Comment by shampool** [comment]
@nouiz  Thanks for the reply！ It turns out to be  a similar problem with  #4303.
