### ISSUE TITLE
relu optimization causing NaN in certain cases

### ISSUE THREAD

**Issue by dementrock** [Theano/Theano#4353]
```python
import theano.tensor as TT
import theano
import numpy as np


def test1():
    input = TT.vector('input')
    W1 = theano.shared(np.zeros((1, 1)), 'W1')

    h1 = W1.dot(input)
    a1 = TT.nnet.relu(h1)
    W2 = theano.shared(np.zeros((1, 1)), 'W2')

    output = W2.dot(a1)

    W1x = TT.matrix("W1x")
    grad = theano.grad(TT.sum(TT.square(output)), W1)
    xout = TT.grad(TT.sum(grad * W1x), W1)

    fx = theano.function([input, W1x], xout, allow_input_downcast=True)
    print fx([0.], [[0.]])

def test2():
    input = TT.vector('input')
    W1 = theano.shared(np.zeros((1, 1)), 'W1')

    h1 = W1.dot(input)
    a1 = TT.maximum(h1, 0.)
    W2 = theano.shared(np.zeros((1, 1)), 'W2')

    output = W2.dot(a1)

    W1x = TT.matrix("W1x")
    grad = theano.grad(TT.sum(TT.square(output)), W1)
    xout = TT.grad(TT.sum(grad * W1x), W1)

    fx = theano.function([input, W1x], xout, allow_input_downcast=True)
    print fx([0.], [[0.]])

test1() # => [[nan]]
test2() # => [[0.]]
```

**Comment by lamblin** [comment]
That particular case can be solved by an optimization that would do CGer(0, x) -> 0, or maybe even dot(0, x) -> 0.
But that would not solve the issue of simplifying the gradients through `abs` that show up here.
Maybe the best solution would be to have a ReLU Op that has a better implementation of `grad`, and that then gets optimized away.

**Comment by dementrock** [comment]
@lamblin I vote for a better implementation of grad for the RELU op. It seems like a cleaner approach.

**Comment by manuels** [comment]
I am able to reproduce this bug. This code also returns NaN when using `optimizer=fast_compile` but not when using `optimizer=fast_run`:

    a =theano.tensor.fscalar("a")
    b=theano.tensor.nnet.relu(a)
    c=theano.grad(b,a)
    f=theano.function([a],[c])
    print f(0.0)

(this bug was also reported in [another project](https://github.com/fchollet/keras/issues/828#issuecomment-213889948) that uses theano)

**Comment by nouiz** [comment]
@manuels this is working correctly. fast_compile disable stability optimization. They are needed in this case to make it work. To have fast_compile + just the stability optimization, use optimizer=stabilize.

I made an issue about this, as it get reported frequently enough to rethink that: https://github.com/Theano/Theano/issues/4442

**Comment by nouiz** [comment]
I did a change to Abs grad() to remove the need of the stability optimization:

https://github.com/Theano/Theano/pull/4443

@lamblin what do you think of that?

**Comment by nouiz** [comment]
I checked this fix both case here in FAST_COMPILE.

**Comment by manuels** [comment]
Thanks @nouiz! It's really not obvious (maybe it should also be mentioned in the docs of RELU?) Great work!

**Comment by nouiz** [comment]
I think that we should make sure that relu() don't return nan by default
in fast_compile. So I wouldn't put that in the doc, except to warn people
that old version of Theano had that problem.

I'll wait for other Theano dev to comment on my PR before changing the doc.
