### ISSUE TITLE
how can I get CudaNdarraySharedVariable's shape?

### ISSUE THREAD

**Issue by baymin1217** [Theano/Theano#4357]
train, valid, test = load('mnist.pkl.gz')
trans_test, shift_test, ori_test = translation(test[0], 28)
trans_test, shift_test, ori_test = shared((trans_test, shift_test, ori_test))

the first output of function translation is the input

type(trans_test)
<class 'theano.sandbox.cuda.var.CudaNdarraySharedVariable'>

trans_test should be images, so how could I transfer the data of trans_test to images that I can look

**Comment by lamblin** [comment]
Please use `theano-users` or StackOverflow for such questions.
We try to keep the tickets about bug reports and feature requests.

For your question, you would have to compile a theano function that outputs the value you care about.
If you are not familiar with the difference between symbolic variables and numerical values, please refer to the [documentation](http://deeplearning.net/software/theano/tutorial/).
