### ISSUE TITLE
PersistentNdarrayLoad in pkl_utils.py doesn't process same object properly

### ISSUE THREAD

**Issue by tete1030** [Theano/Theano#4358]
As mentioned in #4238 and mila-udem/blocks#1031  , I encountered the same problem when I use function __theano.misc.pkl_utils.load__ with default __persistent\_id__ parameter, __PersistentNdarrayLoad__.

If __PersistentNdarrayLoad.\_\_call\_\___ receives two same __persid__, it will return two different objects with same value instead of one single object, which causes __AssertionError__ in __\_constructor\_Function__ of __theano.compile.function\_module__.

The issues of _blocks_ mentioned above have been fixed by caching created object as https://github.com/mila-udem/blocks/pull/1032/commits/5c04f77b71a7c95182645e1cfa20299fb883f802

Besides, there is a little problem at https://github.com/Theano/Theano/blob/master/theano/compile/sharedvalue.py#L79
**container** should be **value**, **container** has already been checked.

And I found in https://github.com/Theano/Theano/blob/master/theano/misc/pkl_utils.py#L263
Why is it storing object name with key __id(obj.container.storage[0])__ but retrieving object name with key __id(obj)__ in __\_resolve\_name__ ? I'm not sure if it is correct.

Thank you

**Comment by tete1030** [comment]
I was wrong about the code at Line 79 in _sharedvalue.py_. It seems like a duplicate check of **container**.

**Comment by lamblin** [comment]
@tete1030 Can you confirm if #4362 fixed the issue for you?

**Comment by tete1030** [comment]
I can confirm that #4362 has fixed the issue about PersistentNdarrayLoad. But I don't know if the remaining two problems is okay.

**Comment by nouiz** [comment]
Which other 2 problems do you talk about?

**Comment by nouiz** [comment]
I'm closing as this issue is fixed.
