### ISSUE TITLE
GPU implementation of Diagonal

### ISSUE THREAD

**Issue by bouthilx** [Theano/Theano#4360]
When #4169 is merged, theano.tensor.basic.Diagonal will now run on the GPU for default properties: offset, axis1 and axis2. We should modify perform to support non-default values on the GPU, or write a GpuOp if it is not possible to handle non-default values with python code.

**Comment by hantek** [comment]
So question number one for the non-default properties:

We need numpy.transpose() to manipulate high-dim tensors, is there such a counterpart in CudaNdarray? I find "reshape" from dir(CudaNdarray) but that is not what we need.

**Comment by bouthilx** [comment]
I doubt we can do it with pure python. We will probably need to use pyCUDA or pure CUDA.

**Comment by hantek** [comment]
Could you point me some example codes of pyCUDA? Haven't written that before, but I know CUDA.

**Comment by abergeron** [comment]
Since it's been a while, the CudaNdarray implementation is less relevant.

We want one for the new gpuarray backend.  This has support for numpy-like transpose(), but you can't assign to the strides, so you might have to use c_code there.

**Comment by abergeron** [comment]
See #5247
