### ISSUE TITLE
Speed up theano: GPU 10x slower than CPU

### ISSUE THREAD

**Issue by jpiabrantes** [Theano/Theano#4365]
I have a couple of "Model" Gaussians these gaussians have a fixed attribute named color, a fixed variance and a variable centre (mu) that depends on the value of 4 theano scalars. I have an energy function which I want to maximize that computes the color similarity of these "Model" Gaussians with other 400 gaussians weighted by the distance of their centres and their sigmas. I want to maximize this energy function so I am using `theano` to compute the gradient of the energy function in respect to the 4 `theano` scalars with the goal to do gradient ascent. The problem is to compute the gradients my computer is taking 0.055 seconds, this way too much time because I need to find the maximum of the energy function in 0.067 seconds (15 fps) and I need to compute the gradient multiple times (to give multiple steps in the gradient ascent) to find the maximum.

The energy function is a big sum of different independent components so the gradient must also be a big sum. How can I paralelize the computation in `theano` to make it faster? I'm new to `theano`.. Is there another way to make it faster?

I have tried using the GPU and it's super slow (0.57 seconds - 10x slower!!). When I use the GPU the compile time is much longer and it prints some weird DEBUG messages:

    Using gpu device 0: GeForce GTX 950M (CNMeM is disabled, CuDNN not available)
    WARNING (theano.gof.compilelock): Overriding existing lock by dead process '15728' (I am process '5852')
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpgjqqsc/a8222d140e820f451f997ce8d242438d.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpgjqqsc/a8222d140e820f451f997ce8d242438d.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpsiqa4y/7c7b01c1dec0ea114288fc88c907f5d4.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpsiqa4y/7c7b01c1dec0ea114288fc88c907f5d4.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpvohusa/1f08b8e24ebc71512128db6673c780b9.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpvohusa/1f08b8e24ebc71512128db6673c780b9.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpzg9hw0/ae530d54c914e1359c6b545882fbfaa7.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpzg9hw0/ae530d54c914e1359c6b545882fbfaa7.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpbltwxe/0f2b6410343ac680a423e5048cb30682.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpbltwxe/0f2b6410343ac680a423e5048cb30682.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp5ucemf/c0864be7c3f43e61a81861eaec1abb80.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp5ucemf/c0864be7c3f43e61a81861eaec1abb80.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp2vfidh/0bf72dc7718f2be737de5d70cb85e8b9.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp2vfidh/0bf72dc7718f2be737de5d70cb85e8b9.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmptagjlf/33bc93ccb1dc6a7bc44d31fdb2d92dfb.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmptagjlf/33bc93ccb1dc6a7bc44d31fdb2d92dfb.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpiw0n_k/b699737d09497760d1293c9e70c11cea.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpiw0n_k/b699737d09497760d1293c9e70c11cea.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpcoadyn/c0ddaf62ace3f4dd0df01eca06d9788f.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpcoadyn/c0ddaf62ace3f4dd0df01eca06d9788f.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpmiwzix/dc9911d7df522c5986f4be6045448701.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpmiwzix/dc9911d7df522c5986f4be6045448701.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp0wsn2s/0350f8ac8835b27a465f19600368e841.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp0wsn2s/0350f8ac8835b27a465f19600368e841.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpynmczg/4bfcc366f81ee79fc38a0dd6e9373cdd.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpynmczg/4bfcc366f81ee79fc38a0dd6e9373cdd.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmprcbv0t/e61a62edd624acad9832af8cbfc493fa.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmprcbv0t/e61a62edd624acad9832af8cbfc493fa.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpilpkks/983b8c365d220ffec8fedb5c07acfb46.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpilpkks/983b8c365d220ffec8fedb5c07acfb46.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp2wdt1l/ddf4c4c7cd4f518cf3ea8c851e66c849.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp2wdt1l/ddf4c4c7cd4f518cf3ea8c851e66c849.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpjk1v9y/d693ea2fb5d9f3cdd6f8dc4a3c4239ab.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpjk1v9y/d693ea2fb5d9f3cdd6f8dc4a3c4239ab.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmppdutly/d87678e5554f825701a868ff2efa13a2.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmppdutly/d87678e5554f825701a868ff2efa13a2.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpubdgfa/e861653ea51659ad69c1fa5490cba2d0.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpubdgfa/e861653ea51659ad69c1fa5490cba2d0.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmprobsmm/69e4deb0dff7eff152f4128f68510cf7.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmprobsmm/69e4deb0dff7eff152f4128f68510cf7.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp3dibos/8025a31cc721d8853fc0b17c736c5183.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp3dibos/8025a31cc721d8853fc0b17c736c5183.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp388roo/dfa41d1f763476627306ce437b9ab77d.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp388roo/dfa41d1f763476627306ce437b9ab77d.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpviroje/a828036e1ed5edabfedc18bc8647ecad.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpviroje/a828036e1ed5edabfedc18bc8647ecad.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpo2trwg/4f7c883428ce31b4afab2ce5aae3f51b.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpo2trwg/4f7c883428ce31b4afab2ce5aae3f51b.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmptf9_td/58c144bbf3113a7cbef0416a1f497473.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmptf9_td/58c144bbf3113a7cbef0416a1f497473.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpoe0rw2/05d99ec41ea874a610071aa6b09d38af.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpoe0rw2/05d99ec41ea874a610071aa6b09d38af.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpzu2ifn/8d1ac2dce98dc38e79a32aa2ac13a89e.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpzu2ifn/8d1ac2dce98dc38e79a32aa2ac13a89e.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpvnfxgf/d109879da2aaa1471f200ea154916786.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpvnfxgf/d109879da2aaa1471f200ea154916786.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpe5ew5r/001caa6d612c4cd4092a11ebc1949538.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpe5ew5r/001caa6d612c4cd4092a11ebc1949538.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpourrey/9f544f5e1aab5944ce90e0761c4c7410.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpourrey/9f544f5e1aab5944ce90e0761c4c7410.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpyg7c3f/f255b19afdc94bb36d37d33c9a042c8f.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpyg7c3f/f255b19afdc94bb36d37d33c9a042c8f.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmphircmu/8294b2165ca5a066dea43ef22a8cc627.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmphircmu/8294b2165ca5a066dea43ef22a8cc627.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp04x5ie/c189fdbab40b1916f73ca65b078e15da.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmp04x5ie/c189fdbab40b1916f73ca65b078e15da.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpwb9jgt/08ae111fa702337ccadec7e9e20915eb.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpwb9jgt/08ae111fa702337ccadec7e9e20915eb.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpqm07tj/ead4deb182232f6b525120388e7ee086.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpqm07tj/ead4deb182232f6b525120388e7ee086.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpmvbs2e/15af393f70403d831145c9f37bf68feb.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpmvbs2e/15af393f70403d831145c9f37bf68feb.exp
    
    
    DEBUG: nvcc STDOUT mod.cu
    
       Creating library C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpg9vm1n/04510a233d168ef4ac0af4bd7e51be4c.lib and object C:/Users/jpiabrantes/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpg9vm1n/04510a233d168ef4ac0af4bd7e51be4c.exp
    
    
    I took 0.570000 seconds to compute the grads
    I took 0.565000 seconds to compute the grads
    I took 0.558000 seconds to compute the grads
    I took 0.561000 seconds to compute the grads
    I took 0.558000 seconds to compute the grads
    I took 0.569000 seconds to compute the grads
    I took 0.556000 seconds to compute the grads
    I took 0.561000 seconds to compute the grads
    I took 0.578000 seconds to compute the grads
    I took 0.564000 seconds to compute the grads

Thank you so much, here's my code:

    import theano
    import theano.tensor as T
    import numpy as np
    from time import time
    dtype = theano.config.floatX
    
    #Define the Model Gaussian MUs that depend on Theano variables
    class ModelGaussian(object):
        def __init__(self,mu,sigma,color):
            self.mu    = mu
            self.sigma = sigma
            self.color = color
    
    model_gaussians = []
    
    x  = T.fscalar('x')
    y  = T.fscalar('y')
    q1 = T.fscalar('q1')
    
    C = T.cos
    S = T.sin
    Tr1 = T.stacklists([[C(q1),-S(q1),x],
                       [S(q1), C(q1),y],
                       [0   ,0    ,1]])
    
    
    mu1    = Tr1[:2,-1]
    color1 = np.array((0.2,0.3,0.4),dtype)
    sigma1 = 5
    model_gaussians.append(ModelGaussian(mu1,sigma1,color1))
    
    q2 = T.fscalar('q2')
    Temp = T.stacklists([[C(q2),-S(q2),x],
                       [S(q2), C(q2),y],
                       [0   ,0    ,1]])
    
    Tr2 = Tr1.dot(Temp)
    
    mu2 = Tr2[:2,-1]
    color2 = np.array((0.1,0.23,0.1),dtype)
    sigma2 = 6
    
    syms = [x,y,q1,q2]
    model_gaussians.append(ModelGaussian(mu2,sigma2,color2))
    
    #Create energy function
    class Solver(object):
        def __init__(self, modelGaussians,syms):
            self.W = np.diag([1,1,.2]).astype(dtype)
            self.Km = [(g.mu,g.sigma,g.color) for g in modelGaussians]
            
            I_mus    = T.matrix('I_mus',dtype)    #N x 2
            I_sigmas = T.vector('I_sigmas',dtype) #N x 0
            I_colors = T.matrix('I_colors',dtype) #N x 3
            
            result, updates = theano.scan(fn=self.energy,
                          outputs_info=None,
                          sequences=[I_mus, I_sigmas,I_colors],
            )
            E = result[0].sum()/result[1].sum()  
            grads = T.grad(E,syms)
            
            self.get_grads = theano.function(
                inputs=syms+[I_mus,I_sigmas,I_colors],
                outputs=grads,
            )
            
        def energy(self,imu,isigma,icolor):
            S = T.sum([self.similarity((imu,isigma,icolor),gm) for gm in self.Km])
            return T.min((S,np.pi*isigma**2)),np.pi*isigma**2
            
        def similarity(self,gi,gm):
            imu,isigma,icolor = gi
            mmu,msigma,mcolor = gm
            exp = T.exp(-((imu-mmu).T.dot((imu-mmu)))/(isigma**2+msigma**2))
            return exp*self.d(icolor,mcolor)*2.*np.pi*(isigma**2*msigma**2)/(isigma**2\
            +msigma**2)
        
        def d(self,c1,c2):
            r = ((c1-c2).T.dot(self.W).dot(c1-c2))/2.2 #0=<r<=1
            return (1-r)**4*(4*r+1)
    
    solver = Solver(model_gaussians,syms)
    
    #Test speed
    for _ in xrange(10):
        #other gaussians
        N = 400 #number of other gaussians
        i_mus = np.random.rand(N,2).astype(dtype)
        i_sigmas = np.random.rand(N,).astype(dtype)
        i_colors = np.random.rand(N,3).astype(dtype)
        
        x = np.random.rand()
        y = np.random.rand()
        q1= np.random.rand()
        q2= np.random.rand()    
        
        start = time()   
        grads = solver.get_grads(x,y,q1,q2,i_mus,i_sigmas,i_colors)
        total = time()-start
        print 'I took %f seconds to compute the grads' % total

**Comment by nouiz** [comment]
The GPU won't speed up computation for scalar or small matrix of size 3x3.
It need "big" input size to speed up computation.

To help you speed that up, you can use Theano profile to see where the
bottleneck is:

http://deeplearning.net/software/theano/tutorial/profiling.html

There is also this doc section that tell how to lower the Theano function
call overhead that can be significant:

http://deeplearning.net/software/theano/faq.html#faster-small-theano-function

If you need help interpreting the output of the profiler, just past it
here, it is quick for me to understand it.

**Comment by lamblin** [comment]
Also, please use `theano-users` or StackOverflow for such requests for support.
We try to keep the ticket about bug reports and feature requests.
