### ISSUE TITLE
Remove neighbourhoods

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4372]
This is an old version of neighbours. We kept it as it was a little bit more flexible, but it have too much restriction. So I would get rid of it. Objection?

todo so:

git rm theano/sandbox/neighbourhoods.py theano/sandbox/tests/test_neighbourhoods.py 

then update the files Theano.pyproj and theano/tests/test_flake8.py that point to it.

**Comment by lamblin** [comment]
No problem.
I'm not even sure this is actually more flexible than neighbours, since "ignore_borders" have been added to neighbours at some point.
