### ISSUE TITLE
Downsample module import warning

### ISSUE THREAD

**Issue by fchollet** [Theano/Theano#4380]
The warning message below always appears when someone uses Keras with the Theano backend:

```
theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
```

Nowhere in the Keras codebase is there any import related to this module. Keras only makes the following imports from Theano:

```python
import theano
from theano import tensor as T
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
from theano.tensor.signal import pool
from theano.tensor.nnet import conv3d2d
```

Can somebody give me a few pointers as to what could be triggering the warning message?

**Comment by nouiz** [comment]
Could this be that you have old stuff in your Theano cache that cause that
old module to be imported?

Can you just delete your Theano cache and see if this fix it?

**Comment by fchollet** [comment]
Running `theano-cache clear` appears to have solved the issue for me. Quite a few people appear to experience the same issue, by the way.

Thanks!

**Comment by nouiz** [comment]
This is a duplicate of https://github.com/Theano/Theano/issues/3892
