### ISSUE TITLE
CUDA is installed, but device gpu0 is not available

### ISSUE THREAD

**Issue by sjhddh** [Theano/Theano#4384]
Hey friends, I'd like to ask for some help,

I recently bought a Nvidia G 970 card, and would like to try theano on this new GPU.

I think I've followed everything stated on theano page (CUDA, enviroment, config, etc.) and also some other blogs.

But, it is still not working.

I am running on: 
`
os = ubuntu 16.04;
theano = 0.8.1;
language = python3.5;
gpu = Nvidia GTX 970;
`

And I have tested CUDA using its own samples, no problem, the tests all PASS.

But when use theano:
I always get the error msg (no matter on theano.test(), or my own pgm):
```bash
['/usr/local/cuda-7.5/bin/nvcc', '-shared', '-O3', '-use_fast_math', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/aaron/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.1+-64/cuda_ndarray', '-Xlinker', '-rpath,/usr/local/cuda-7.5/lib', '-Xlinker', '-rpath,/usr/local/cuda-7.5/lib64', '-I/home/aaron/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/sandbox/cuda', '-I/home/aaron/Git/.virtualenvs/ts/lib/python3.5/site-packages/numpy/core/include', '-I/usr/include/python3.5m', '-I/home/aaron/Git/.virtualenvs/ts/include/python3.5m', '-I/home/aaron/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/gof', '-o', '/home/aaron/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.1+-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/usr/lib', '-lcublas', '-lpython3.5m', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', '/usr/local/cuda-7.5/bin/nvcc -shared -O3 -use_fast_math -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/aaron/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.1+-64/cuda_ndarray -Xlinker -rpath,/usr/local/cuda-7.5/lib -Xlinker -rpath,/usr/local/cuda-7.5/lib64 -I/home/aaron/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/sandbox/cuda -I/home/aaron/Git/.virtualenvs/ts/lib/python3.5/site-packages/numpy/core/include -I/usr/include/python3.5m -I/home/aaron/Git/.virtualenvs/ts/include/python3.5m -I/home/aaron/Git/.virtualenvs/ts/lib/python3.5/site-packages/theano/gof -o /home/aaron/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-3.5.1+-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/usr/lib -lcublas -lpython3.5m -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: cuda unavailable)
```

What should I do?

Thx

**Comment by gokul-uf** [comment]
Hi,
It seems that CUDAToolkit was not installed properly.
run `nvidia-smi` and check the output for `gpu0`
Additionally, run `theano-cache clear` and `theano-cache purge`.
Also, check for the version of `g++` and `nvcc` and check from the CUDA docs if `nvcc` supports the version of `g++` available.

More info at:
1. https://groups.google.com/forum/#!topic/theano-users/-N-W6GKL4eU
2. https://groups.google.com/forum/#!topic/theano-users/xW9jmHzOwp0
3. https://github.com/Theano/libgpuarray/issues/19

Hope that helps!

**Comment by sjhddh** [comment]
@gokul-uf Thank you very much
 
I checked nvidia-smi, I think there is no problem"
```
+------------------------------------------------------+                       
| NVIDIA-SMI 361.42     Driver Version: 361.42         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 0000:01:00.0      On |                  N/A |
| 22%   30C    P8    18W / 151W |    257MiB /  4092MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       878    G   /usr/lib/xorg/Xorg                             135MiB |
|    0      1275    G   compiz                                          44MiB |
|    0      1774    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    57MiB |
+-----------------------------------------------------------------------------+
```

And, I also ran `theano-cache` and `theano-cache purge` before.

The versions for other things:
`g++ (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413`
`nvcc: Cuda compilation tools, release 7.5, V7.5.17`

According to one of the google discussion, it might be a unsupported g++ version?
But that post is about a year ago, does it still fit?

Looking for wards to heard more,
Cheers!

**Comment by abergeron** [comment]
Yes, it's probably because of the compiler.  nvcc 7.5 requires g++ 4.8 or 4.9

**Comment by sjhddh** [comment]
Ahh, I've re-linked g++ and gcc to 4.9 version. But still....

**Comment by nouiz** [comment]
You can change your gcc version to something that nvcc support. Google for that, there is frequently doc about this. Something it is simple as asking your package manager to install an older gcc.

**Comment by sjhddh** [comment]
well, as I said  in the previous reply, I tried that. i.e. 4.8 / 4.9. But the situation is still not changed..

**Comment by nouiz** [comment]
Try NVIDIA sample to make sure that nvidia is working well in your setup.
Ubuntu 16.04 is very new and probably they don't support it. If that is the
case, we can't help. If those sample work, then they support it.

**Comment by lamblin** [comment]
Please ask for support on `theano-dev` or StackOverflow. There, please provide the *whole* error message.
We try to keep the tickets only for bug reports and feature requests.

**Comment by evan912** [comment]
try this 
`sudo ldconfig /usr/local/cuda-7.5/lib64`

**Comment by DanlanChen** [comment]
Hello, I am having the same problem,
my output is like this, any suggestion on what is going on?
Thu Sep 15 16:55:24 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 4.304...   Driver Version: 304.131        |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name                     | Bus-Id        Disp.  | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap| Memory-Usage         | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  NVS 300                  | 0000:05:00.0     N/A |                  N/A |
| N/A   68C  N/A     N/A /  N/A |  53%  269MB /  511MB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Compute processes:                                               GPU Memory |
|  GPU       PID  Process name                                     Usage      |
|=============================================================================|
|    0            Not Supported                                               |
+-----------------------------------------------------------------------------+

**Comment by nouiz** [comment]
This is a very old GPUs. It isn't supported by newer driver and CUDA
version. I'm not sure the current gpu back-end in Theano support it in all
cases. Also, it is a low end GPUs, so it won't give you any  speed up.

if you still want to make it work, make sure CUDA examples work. Without
this, Theano can't work.

But personnaly, I htink it is wasted time to try to make Theano run on that
GPU.

**Comment by richard-vogl** [comment]
I had the same issue I could solve my issue by fixing two things:

- Install gcc 4.9 and linking /usr/bin/gcc to /usr/bin/gcc-4.9 as well as /usr/bin/g++ to /usr/bin/g++4.9

- Adding this flag to THEANO_FLAGS: '-D_FORCE_INLINES' since apparently a bug in  glibc 2.23 causes this issue

also see: 
https://github.com/Theano/Theano/issues/4430
and
https://github.com/Theano/Theano/pull/4369

**Comment by MinaRe** [comment]
Dear All,

I have same problem and I solved it with the following task:

Add environment variable:

    sudo nano /etc/profile

 Add following to the file:

    PATH=/usr/local/cuda/bin:$PATH
    export PATH

  Then execute :

    source /etc/profile
 
Then you can import keras or theano library in python without any problem.
Enjoy!

**Comment by ShuaiW** [comment]
@MinaRe doens't work

**Comment by ShuaiW** [comment]
@MinaRe  doesn't work for me

**Comment by nouiz** [comment]
Email the information on theano-user to get user help.

**Comment by ankitshah009** [comment]
Same problem. Any solution to this issue?

 nvidia-smi
Tue Mar  7 10:39:47 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 378.13                 Driver Version: 378.13                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 820M     Off  | 0000:03:00.0     N/A |                  N/A |
| N/A   49C    P0    N/A /  N/A |      0MiB /  1985MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

**Comment by kcheng999** [comment]
> I am facing the same question.

**Comment by 1165048017** [comment]
One of the reasons maybe the com configures in '.theanorc.txt'. I have write the 'flags=-arch=sm_61' which the GPU is GTX1060. Then the same questions occurred, and then I changed 'flags=-arch=sm_53', it works. Here is my final '.theanorc.txt'. 
`[global] 
openmp=False 

device=gpu

floatX=float32

allow_input_downcast=True
[blas] 
ldflags= 
[gcc] 
cxxflags=-IC:\ProgramData\Anaconda2\MinGW


[nvcc] 
flags = -LC:\ProgramData\Anaconda2\libs
compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
fastmath = True 
flags=-arch=sm_53`

**Comment by Nick7hill** [comment]
i am having the same issues, can anyone tell me exactly how does one change path, i am kind of a noob at this

**Comment by abergeron** [comment]
email theano-users@googlegroups.com to get support.  Commenting on an old closed issue will get you nowhere.
