### ISSUE TITLE
Lack of several updates for the same shared variable

### ISSUE THREAD

**Issue by avostryakov** [Theano/Theano#4386]
When I tried to implement Recurrent Batch Normalization from (http://arxiv.org/pdf/1603.09025v1.pdf) I ran into an inability to implement several updates of several slices of running_mean and running_inv_std shared variables in one theano function. These variables save statistics.
  I have to update only one slice of each variable at every time step. For one time step, a simplified code will be looked the following way:
updates = OrderedDict()
......
updates[running_mean] = T.set_subtensor(running_mean[time_step], np.float32(0.9) * running_mean[time_step] + np.float32(0.1) * input_mean)
.....
f = theano.function([inputs], [outputs], updates=updates)

The problem is that I have to do it for every time step in the loop:
for time_step in range(time_steps):
  updates[running_mean] = T.set_subtensor(running_mean[time_step], np.float32(0.9) * running_mean[time_step] + np.float32(0.1) * input_mean)

Of course, It will not work in theano correctly.

Is it possible to do something with it?

**Comment by nouiz** [comment]
This paper is from people from our group. So I'm pretty sure it can be done correctly.

set_subtensor(), if you use it to update multiple time the same index, only one of them will be choosen. Which one isn't clear. Probably the last one of the CPU and a random one on the GPU.

inc_subtensor(), if you have the same index multiple time, then each increment will be added together.

So just reformulate your code to use inc_subtensor.

semantically, using set_subtensor() with multiple time the same index don't make sence(which one to keep isn't clear, you event suggest that we should add all of them. So there is many possible way to interpret it). But incrementing the same index multiple make sence and have only 1 interpretation (add all the increment).

**Comment by avostryakov** [comment]
1. Hmm, I see only one way to implement it correctly: split on two inc_subtensor operations:
# for np.float32(0.9) * running_mean[time_step]:
T.inc_subtensor(running_mean[time_step], np.float32(-0.1) * running_mean[time_step])
# for np.float32(0.1) * input_mean:
T.inc_subtensor(running_mean[time_step], np.float32(0.1) * input_mean)

2. "inc_subtensor(), if you have the same index multiple time, then each increment will be added together."
   By the index do you mean the key in updates dictionary above?

3. Is it possible to use a default_update attribute of a shared variable instead of 'updates' dict? For example: 

for time_step in range(time_steps):
  running_mean.default_update = T.inc_subtensor(running_mean[time_step], np.float32(-0.1) * running_mean[time_step])
  running_mean.default_update = T.inc_subtensor(running_mean[time_step], np.float32(0.1) * input_mean)

P.S. Of course, instead of 'for' loop can be used theano.scan. I used it only for demonstration.

**Comment by avostryakov** [comment]
Of course, a source code of LSTM layer with batch normalization from this article will be highly appreciated :)

**Comment by f0k** [comment]
> By the index do you mean the key in updates dictionary above?

No, the index `time_step`. If you use the same key multiple times, you should use inc_subtensor instead of set_subtensor. This doesn't apply in your case, though.

> The problem is that I have to do it for every time step in the loop:

```python
for time_step in range(time_steps):
    updates[running_mean] = T.set_subtensor(running_mean[time_step], np.float32(0.9) * running_mean[time_step] + np.float32(0.1) * input_mean)
```
Well, you'd need to accumulate rather than replace the updates:
```python
updates[running_mean] = running_mean
for time_step in range(time_steps):
    updates[running_mean] = T.set_subtensor(updates[running_mean][time_step], np.float32(0.9) * updates[running_mean][time_step] + np.float32(0.1) * input_mean)
```
If you do the same in scan, you can return updates from your step function and catch the updates returned by the theano.scan() call. See the [scan documentation](http://deeplearning.net/software/theano/library/scan.html): "fn can return either (outputs_list, update_dictionary) or (update_dictionary, outputs_list) or just one of the two (in case the other is empty)."

**Comment by lamblin** [comment]
@f0k's solution is probably what you are looking for.
In the future, please use the `theano-users` mailing list, or StackOverflow, for such requests for help.
We try to keep the tickets for bug reports and feature requests.

**Comment by avostryakov** [comment]
Thank you! I'll use theano-users the next time.

Anatoly Vostryakov,
Energy,
mailto: a.vostrjakov@gmail.com

//////

2016-04-19 4:45 GMT+03:00 Pascal Lamblin <notifications@github.com>:
