### ISSUE TITLE
Rop for Pool

### ISSUE THREAD

**Issue by AndreasMadsen** [Theano/Theano#4387]
I'm trying to implement a transformation invariance regularizer as described in http://yann.lecun.com/exdb/publis/pdf/simard-00.pdf section 3. Basically for a classification model with a scale transformation `s(x, alpha) = x * alpha`, it is just:

<img src="https://cloud.githubusercontent.com/assets/505333/14587583/9559395e-04b5-11e6-91b4-9c33a39ae2af.png" width="350">

I have implemented this using a scan operator:

``` python
def loop(i, x, p, t):
  p_class_t = p[i, t[i]]
  return T.dot(
    T.flatten(T.grad(p_class_t, x)[i, :, :, :]),
    T.flatten(x[i, :, :, :])
  )

jacobi_dot_x, _ = theano.scan(
  loop,
  non_sequences=[input_var, prediction, target_var],
  sequences=T.arange(self.input_var.shape[0])
)

regularizer = jacobi_dot_x.sum()
```

however it is horrifyingly slow.

As I understand it I should be able to implement this using an `Rop`:

``` python
regularizer = T.Rop(p[:, t], x, x).sum()
```

I have tested this on a simple model and the performance gain was huge. However in the full CNN model I have a max pooling layer using `theano.tensor.signal.pool.Pool` and I get the following error:

```
NotImplementedError: Pool{ds=(1, 4), ignore_border=True, st=(1, 4), padding=(0, 0), mode='max'} of class Pool does not implement R_op. If this is a theano op, write to the theano-dev mailing list for assistance. If it is your own op, implement the R_op method.
```

Is it difficult to implement the `Rop` operation for `Pool` operation? I took a look at the code, but had a very hard time understanding the general architecture (e.q. `make_nodes`) as well as the C API.

**Comment by nouiz** [comment]
We have this in a PR to an older version of Theano. You can use it directly
if you want:

https://github.com/Theano/Theano/pull/3587

**Comment by AndreasMadsen** [comment]
Wow that is amazing. But I think the `DownsampleFactorMaxRop` op is missing an gradient implementation. I'm getting the following error:

```
AttributeError: 'DownsampleFactorMaxRop' object has no attribute 'grad'
```

My _port_ of Theano/Theano#3587:  https://github.com/AndreasMadsen/Theano/commit/d5dfbe1d124cc155151b10f0076bd8d53a4308ff

**Comment by nouiz** [comment]
What do you try to do? You build your graph with the max pool op, then you
call Rop and then you call grad on that?
If that is the case, then you will need to implement the
"DownsampleFactorMaxRop.grad" method.

Thanks for porting the branch. Do you want to finish it? Mostly, you need
to update the test to use the Rop test infrastucture. This is less error
prone:

http://deeplearning.net/software/theano/extending/extending_theano.html#testing-the-rop

It would be great to have this in Theano as it get requested from time to
time.

**Comment by AndreasMadsen** [comment]
> What do you try to do? You build your graph with the max pool op, then you
call Rop and then you call grad on that?

Exactly.
```python
# given input x and weights w
# Prediction
p = P(x, w)  # uses Pool(type='max')
# Loss 
regularizer = T.Rop(p[:, t], x, x)
loss = T.nnet.categorical_crossentropy(p, t).mean() + regularizer.mean()
# Optimize
w -= T.grad(loss, w)
```

> Thanks for porting the branch. Do you want to finish it?

I can give it a try.

**Comment by AndreasMadsen** [comment]
I looked at the test. Apparently `RopLop_checker` only support vectors (`self.x`) and matrices (`self.mx`) however the `Pool` tests requires a 4d tensor. `test_conv` suffers from the same problem and also appears to use the `theano.scan` for testing.

**Comment by nouiz** [comment]
I wanted to not need to review that testing code as it is tricky. So it seem we can't remove the code duplicate.

Can you make a PR with your new code? I'll try to have it reviewed merged this week or next week.

**Comment by AndreasMadsen** [comment]
@nouiz I've made a pull request: #4412
