### ISSUE TITLE
test_value on shared variable throws AttributeError

### ISSUE THREAD

**Issue by wielandbrendel** [Theano/Theano#4390]
The attribute tag.test_value is not set for shared variables. E.g.

    import theano, numpy
    x = theano.shared(numpy.random.rand(10))
    print(x.tag.test_value)

throws the error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-98b2252a1204> in <module>()
      1 import theano, numpy
      2 x = theano.shared(numpy.random.rand(10))
----> 3 print(x.tag.test_value)

AttributeError: 'scratchpad' object has no attribute 'test_value'
```

in Python 3.4 and Theano version '0.8.0.dev-7943ab37580fc4f1436d93bb455ff7731be3c28d'. As far as I understand this is not the supposed behaviour (e.g. [here](https://udibr.github.io/tips-on-working-with-theano.html)).

**Comment by nouiz** [comment]
We don't set that attribute for shared variable. This could only cause extra memory usage and isn't useful.

Internally, we call a function that return the tag.test_value or the value of shared variable. If you want to use it yourself, you can do:

theano.gof.op.get_test_value(a_theano_variable)

This will give you the same test_value that will be used by Theano.
