### ISSUE TITLE
Theano not freeing GPU memory

### ISSUE THREAD

**Issue by stefdoerr** [Theano/Theano#4391]
Hi, I have a function that trains an autoenconder and I call it roughly 20 times. Inside the function I do:
```python
def myfunc(traindata):
    ...
    traindata_th = np.array(traindata, dtype=theano.config.floatX)
    traindata_th = theano.shared(traindata_th, borrow=True)
    weights = train(traindata_th)
```

The traindata is always same size but a different batch of data (batchratio is also constant).
After three calls to the function I get:

```python
Error allocating 891072000 bytes of device memory (out of memory). Driver report 388902912 bytes free and 3221028864 bytes total 

MemoryError                               Traceback (most recent call last)
/xxx/projections.py in projectAEtheano(n_hidden, data, traindata, testdata, conf)
     64     batchsize = int(traindata.shape[0] * conf['batchratio'])
     65     traindata_th = np.array(traindata, dtype=theano.config.floatX)
---> 66     traindata_th = theano.shared(traindata_th, borrow=True)
     67     weights = trainer(traindata_th, '', n_epochs=conf['nepochs'], batch_size=batchsize, sparsity=0, n_hidden=n_hidden, tied=False, sparsityweight=0)
     68 

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/theano/compile/sharedvalue.py in shared(value, name, strict, allow_downcast, **kwargs)
    245             try:
    246                 var = ctor(value, name=name, strict=strict,
--> 247                            allow_downcast=allow_downcast, **kwargs)
    248                 utils.add_tag_trace(var)
    249                 return var

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/theano/sandbox/cuda/var.py in float32_shared_constructor(value, name, strict, allow_downcast, borrow, broadcastable, target)
    238         # type.broadcastable is guaranteed to be a tuple, which this next
    239         # function requires
--> 240         deviceval = type_support_filter(value, type.broadcastable, False, None)
    241 
    242     try:

MemoryError: ('Error allocating 891072000 bytes of device memory (out of memory).', "you might consider using 'theano.shared(..., borrow=True)'")
```

I cannot understand what would cause this to happen, other than theano failing to free GPU memory after the function has finished, since as I said the data size is the same each time I call the function.

I added to `.theanorc` the 
```
allow_gc = True
allow_pre_alloc = False
```
options which I saw suggested in another thread but it doesn't help.

Any ideas on this?

**Comment by nouiz** [comment]
Python GC (Garbare collector) isn't perfect and sometimes takes times to
clean up everything (complicated technical detail).

But in all cases, I think you have a bad usage patter for Theano. Why do
you create new shared variable everything? One laywer weights must be
created by only once in a shared variable.

If you already do that, you could call a few times python gc before
building the new shared variable:

import gc
for i in range(3): gc.collect()

Did you change Theano default flag? Some non-default flag cause Theano to
keep allocated memory.

**Comment by stefdoerr** [comment]
Sorry, I don't understand what you mean. This shared variable are not the weights. They are the training examples. Or are you saying I don't need to put the training data in a shared variable?

**Comment by nouiz** [comment]
If you pass one mini-batch at a time, you don't need to pass it via shared
variable. You can pass them as input of your Theano funciton and Theano
will transfer it to the GPU each time.

The reason to use shared variable it to have all your dataset or
multiple-minibatch transfered at once to the GPU. So this could
remove/speed up the transfer of your dataset.

Also, even in that case, you should not create a new shared variable, as
this force you to compile a new Theano function (or copy it while changing
the Theano function). You can call a_shared_varialbe.set_value() to change
the value of a shared variable you want to do that:

http://deeplearning.net/software/theano/tutorial/aliasing.html#assigning

**Comment by stefdoerr** [comment]
The function is called 20 times to train 20 different Autoencoders with different data (but same amount). 
They are not mini-batches.
So I want every time the function is called to transfer the data to GPU.

I cannot use the .set_value() because after the 20 calls to the function I am going to increase the amount of data and call it another 20 times. 

I can look if calling the garbage-collector helps.

**Comment by stefdoerr** [comment]
I tried the gc trick but I still get the error. I cannot believe anyways that python does not free function local variables on return.

Any other ideas?

**Comment by nouiz** [comment]
You can do set_value() while changing the shapes of the shared variable.
Theano do not suppose shared variable shapes are constant.

Be sure to del your own reference to Theano function compiled with that
shared variable and your reference to that shared variables.

**Comment by stefdoerr** [comment]
Due to the way the code is written I am not able to initialize the theano shared variable outside of that loop.

In the end I found the solution. I just set value to an empty array. Seems to free the GPU memory.

```python
traindata_th = np.array(traindata, dtype=theano.config.floatX)
traindata_th = theano.shared(traindata_th, borrow=True)
weights = trainer(traindata_th, '', n_epochs=conf['nepochs'], batch_size=batchsize, sparsity=0, n_hidden=n_hidden, tied=False, sparsityweight=0)
traindata_th.set_value([[]])
```
