### ISSUE TITLE
keepdims=True not binary equivalent to keepdims=False + reshape

### ISSUE THREAD

**Issue by nidleo** [Theano/Theano#4398]
This happens on GPU, but not CPU. I'm using Theano 0.7

Here's the shortest code I came up with to reproduce it:

```
r = np.random.rand(10, 200).astype(theano.config.floatX)
wInit = np.random.rand(200).astype(theano.config.floatX)
for b in [True, False]:
    if b:
        val = np.zeros((1,200))
        val[0,:] = wInit
    else:
        val = wInit

    w = theano.shared(value = val)
    additive = T.matrix()
    a = T.matrix()
    w_reshape = T.reshape(w, (1, 200))
    if b:
        out = w_reshape * T.mean(a, axis=[0], keepdims=True)
    else:
        out = w_reshape * T.reshape(T.mean(a, axis=[0], keepdims=False), (1, 200))

    func = theano.function(
            inputs=[a],
            outputs=[out]        
        )

    o = func(r)
    if b:
        res1 = o[0]
    else:
        res2 = o[0]

print np.max(np.abs(res1 - res2))
```

prints:
2.58439030176e-08

**Comment by lamblin** [comment]
That's normal, especially on GPU. The same numbers are not necessarily summed in the same order, which means rounding happens in a different way. Something in the order of 1e-7 or 1e-8 is actually quite a small difference in float32.

**Comment by nouiz** [comment]
The difference is very small. You can ignore it as this is close to the eps of float values.

I tried to find the cause to explain it, but I didn't found it in the time I had. But I'm pretty sure you can just ignore it. Don't forget when working with float/double number, just changing (a + b) + c to a + (b + c) can change the final result by small values. If you didn't know that see this:

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

On the GPU, we change much more frequently the order of operation like this to get more parallism. Without this, the GPU won't give speed up.

**Comment by nidleo** [comment]
The difference is small indeed, but becomes significant when the operation is repeated (e.g. when training for several epochs). Although they are both correct if it's just due to order of summation.

Since both computation graphs are logically the same, doesn't the difference suggest that one of them is executed in sub-optimal summation order?

**Comment by nouiz** [comment]
We select the order of summation for speed not for accuracy. Doing it for
accuracy would request a sort and would slow down computation a lot.

Did you really see a difference in training speed du to that our similar
small difference? If so can you give the information you have? All the
information I have tell that such small difference don't change
significantly the training.

**Comment by nidleo** [comment]
I didn't see speed differences (although this summation is a negligible part of the training so I cannot know for sure).
The trained weights are different enough so that the train\test error is affected. But the difference is arbitrary.

I think the only concern here is a possible optimization bug.
if these two are exactly the same operation:
    w_reshape * T.mean(a, axis=[0], keepdims=True)
    w_reshape * T.reshape(T.mean(a, axis=[0], keepdims=False), (1, 200))
Why do they have different summation orders?
