### ISSUE TITLE
deeplearning.net is DOWN. 4/25/16

### ISSUE THREAD

**Issue by freytheviking** [Theano/Theano#4432]
The deeplearning.net website is down. Cannot access tutorials.

**Comment by nouiz** [comment]
Thanks, looking into it.

**Comment by nouiz** [comment]
It is fixed.

**Comment by derestle-htwg** [comment]
it's down again

**Comment by mariomeissner** [comment]
And again

**Comment by nouiz** [comment]
Thanks, it was fixed a few days ago.

**Comment by unixtomato** [comment]
it's down again.

**Comment by LeonovYurii** [comment]
It's down, this is weird...

**Comment by brandonwillard** [comment]
https://theano-pymc.readthedocs.io/en/latest/ is still mostly a clone of deeplearning.net, so you can probably use that in the meantime.  
**Note: there will be some differences, because it's based on a fork (i.e. [Theano-PyMC](https://github.com/pymc-devs/Theano-PyMC)).**

**Comment by moynama** [comment]
down again...

**Comment by arda-ai** [comment]
what is the problem with deeplearning.net?

Why is it not operating?

**Comment by sachinmotwani20** [comment]
Down again.
Was it ever working!

**Comment by ThatScar** [comment]
Seems to be down since 2020?
For tutorials, some of them are there at https://web.archive.org/
For software, use brandonwillard's link above.

**Comment by infinite0522** [comment]
Down again.

**Comment by KINGSTERKRISHNA** [comment]
down again

**Comment by YakoScarlet** [comment]
Down again

**Comment by ing-Hugo** [comment]
Down again

**Comment by YAMWD** [comment]
down again

**Comment by Damfilius** [comment]
down again
