### ISSUE TITLE
CuDNN version detection issue

### ISSUE THREAD

**Issue by magic282** [Theano/Theano#4437]
I just installed the latest Theano release and it noticed me that my cudnn version too old:

``
Using gpu device 1: Tesla K20Xm (CNMeM is disabled, cuDNN Version is too old. Update to v5, was 3007.)
``

But I am quite sure I am using this cudnn (``Download cuDNN v4 (Feb 10, 2016), for CUDA 7.0 and later.``) (``cudnn-7.0-win-x64-v4.0-prod``).

The previous release 0.8.1 recognized my cudnn as 4007, but this release (0.8.2) recognize it as 3007.

Is this a bug or cudnn 4007 is not supported? The pypi page says ``cuDNN v3 isn’t supported anymore``.

**Comment by magic282** [comment]
It turns out that someone on the server messed up the cuda installation. Sorry for this issue. Closing.

**Comment by magic282** [comment]
Found something new:
On a M40 GPU, it reports ``Using gpu device 0: Tesla M40 (CNMeM is enabled with initial size: 30.0% of memory, CuDNN 3007)``
But on a K40 GPU, it reports ``Using gpu device 0: Tesla K40m (CNMeM is enabled with initial size: 30.0% of memory, CuDNN 4007)``.

**Comment by magic282** [comment]
update:
when using CuDNN v5 rc:
``Using gpu device 0: Tesla K40m (CNMeM is enabled with initial size: 30.0% of memory, CuDNN 5004)
\Anaconda2\lib\site-packages\theano\sandbox\cuda\__init__.py:600: UserWarning: Your CuDNN version is more recent then Theano. If you see problems, try updating Theano or downgrading CuDNN to version 4.``

``Using gpu device 0: Tesla M40 (CNMeM is enabled with initial size: 30.0% of memory, CuDNN 3007)``

**Comment by magic282** [comment]
update (using theano 0.8.2, cudnn v4):
``Using gpu device 0: Tesla M40 (CNMeM is enabled with initial size: 30.0% of memory, cuDNN Version is too old. Update to v5, was 3007.)``

``Using gpu device 0: Tesla K40m (CNMeM is enabled with initial size: 30.0% of memory, cuDNN 4007)``

**Comment by magic282** [comment]
update (using theano 0.8.2, cudnn v5 rc):
``Using gpu device 0: Tesla M40 (CNMeM is enabled with initial size: 30.0% of memory, cuDNN Version is too old. Update to v5, was 3007.)``
``Using gpu device 0: Tesla K40m (CNMeM is enabled with initial size: 30.0% of memory, cuDNN 5004)``

So from my experiments, it seems that the cudnn version depends on the cards?

**Comment by hive-bee** [comment]
In both versions you have selected GPU device 0. To the best of my knowledge, if you have several GPUs in a single computer, they should be listed as, e.g., gpu0 for the Tesla K40m and gpu1 for the Tesla M40. Are you sure both cards are on the same computer?

If not, there are probably different CUDNN versions on these computers.

**Comment by magic282** [comment]
@hive-bee I am using a GPU cluster and they have different cards. And there are no CuDNN installed on the cluster nodes, I was using a batch script to setup the CuDNN during testing, and the testing script is the same one. The only different is the GPU on different nodes. I am also very confused about this.

**Comment by hive-bee** [comment]
@magic282 I'm sorry but I'm unfamiliar with Windows' implementation of cuDNN and GPU clusters. I'm afraid you'll need someone else's help.

Good luck!

**Comment by lamblin** [comment]
Could it be that there _is_ an installation of cudnn v3 in addition to the v4 or v5 that you are trying, at least on some nodes?

**Comment by magic282** [comment]
@lamblin You are right I just found that cudnn is installed on some m40 nodes. Thanks for your help.

**Comment by DanlanChen** [comment]
I am using m40, getting this result:Using gpu device 0: Tesla M40 (CNMeM is enabled with initial size: 20.0% of memory, cuDNN not available), I am not sure if this is wrong? I am installing cuda 8.0

**Comment by DanlanChen** [comment]
I know now , I did not install cuDNN

**Comment by DanlanChen** [comment]
But what does CNMeM do, can we change the percenetage by ourself?

**Comment by Sentient07** [comment]
CnMEM is a memory manager of cuda. You can specify how much of memory you need to allocate for the code in decimal. You can change the percentage till 1.0 if you don't use your GPU for display. If it is being used for some display or other purpose, you need to use a lesser fraction

**Comment by Sentient07** [comment]
To use that, you can set it using theano flag, lib.cnmem=0.XX

**Comment by loretoparisi** [comment]
I get this error with `nvidia-docker` on `FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04`

and 

```
root@d842fc00a358:~# nvidia-smi
Tue Jul 25 09:58:02 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   39C    P8    17W / 125W |      0MiB /  4036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

My theano config is

```
[global]
floatX = float32
device = cuda0

[lib]
cnmem = 1

[nvcc]
fastmath = True
```
