### ISSUE TITLE
a single gpu, can only use one cpu?

### ISSUE THREAD

**Issue by liyi193328** [Theano/Theano#4446]
Hi:
   My ubuntu 14.04 has 6 cpu processors, and one titan x GPU， when I run some theano examples, theano always make use one processors(usage 100%), my ~/.theanorc like this:

[global]
floatX=float32
device=gpu
optimizer_including=cudnn
openmp=True
OMP_NUM_THREADS=4

[nvcc]
fastmath=True

How I use these multi cpu processors at the same time of GPU?

**Comment by lamblin** [comment]
Please use the theano-users mailing list for such requests.
We try to keep GitHub tickets only about bug reports and feature requests.
As for your question, it is likely that all the heavy computation is done on the GPU, and only one CPU core is actively waiting on the GPU during that time.
