### ISSUE TITLE
Slowdown in the new back-end for some Ops

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4448]
While doing some profiling, I realized some of the Ops were faster in the new back-end, but some were still slower, at least in some cases.
Here are the most impactful I encountered.

- [ ] `GpuAdvancedIncSubtensor1`, x2 (not sure why the `_dev20` version is not always used)
  - Addressed partially
- [ ] `GpuAdvancedSubtensor1`, x2
  - Addressed partially
- [x] `GpuDnnConv`, almost x2 with `time_once`
- [x] `GpuDnnConvGradW`, 20% with `time_once`
- [ ] `GpuCAReduce` / `GpuCAReduceCuda`, up to 25% (sometimes equivalent)
- [x] `GpuDot22`, 25%, seems to be x5 in one case
  - probably due to the fact that the BLAS kernels are compiled during the first call to a BLAS Op, and it takes 8s. It seems to disappear when ignoring the first call during profiling.
- [ ] `GpuIncSubtensor`, 25%
- [ ] `GPUA_mrg_uniform`, 10%
- [ ] `GpuElemwise`: from 20% speed-up to 40% slow-down
- [ ] `GpuDimShuffle`: x2.5, but small overall
- [ ] `GpuReshape`: 50%, small overall
- [x] `GpuJoin`, x50
- [x] `GpuSplit`, x50

These were observed with `CUDA_LAUNCH_BLOCKING=1`, and `profile=True`.
Overall, it made a slowdown of around 15% without blocking.

**Comment by nouiz** [comment]
Can you give code that reproduce this?

also, when there is only 1 number, is this speed up or slowdown?

**Comment by lamblin** [comment]
Basically, the benchmarking code in https://github.com/caglar/rnn_benchmarks and https://github.com/soumith/convnet-benchmarks/
I have a couple of prints with profiling I can show you as well.
What I report is the increase in computation time (x2 if it takes twice as long, for instance).

**Comment by nouiz** [comment]
For the slowdown with time_once*, you most ignore the first call from the timing. With time_once* we ask cudnn to execute all its version and to report to us the fastest. Then we record that and always reuse it. So the first call is always much slower. If you use THeano profiler, you can ignore the first call with this flag:

profiling.ignore_first_call=True

**Comment by nouiz** [comment]
A few nodes that don't do any GPU computation like GpuDimshuffle have a
more overhead in the new back-end. But in practice it shouldn't matter as
they are overlaper with the GPU computation. So check the others.

Note, the _dev20 don't support all ndims cases. That is why it isn't always
used.

**Comment by abergeron** [comment]
#4478 fixes the GpuDnnConv issues

**Comment by lamblin** [comment]
To reproduce the issue, clone `https://github.com/soumith/convnet-benchmarks`, go in `theano`, and compare:
- `CUDA_LAUNCH_BLOCKING=1 THEANO_FLAGS=profile=True,floatX=float32,device=gpu2,lib.cnmem=2,gpuarray.preallocate=2,dnn.conv.algo_fwd=time_once,dnn.conv.algo_bwd_filter=time_once,dnn.conv.algo_bwd_data=time_once python benchmark_imagenet.py -a googlenet -B 32`
- CUDA_LAUNCH_BLOCKING=1 THEANO_FLAGS=profile=True,floatX=float32,device=cuda2,lib.cnmem=2,gpuarray.preallocate=2,dnn.conv.algo_fwd=time_once,dnn.conv.algo_bwd_filter=time_once,dnn.conv.algo_bwd_data=time_once python benchmark_imagenet.py -a googlenet -B 32

It should take around 1.7 GB on GPU, which should fit on a 750.

**Comment by abergeron** [comment]
GpuAdvancedSubtensor1 is possibly addressed by https://github.com/Theano/libgpuarray/pull/166

**Comment by abergeron** [comment]
GpuJoin is fixed (and 3x faster than the old backend) with https://github.com/Theano/libgpuarray/pull/178

**Comment by abergeron** [comment]
GpuSplit is apparently also fixed (and about ~2.5x faster) with the same PR.

**Comment by abergeron** [comment]
It is possible that GpuAdvancedSubtensor1 and GpuAdvancedIncSubtensor1 are fixed, but we should make timings to be sure.

**Comment by lamblin** [comment]
The remaining issues should be fixed when using only one stream.
