### ISSUE TITLE
CuDNN issues with the new back-end

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4453]
Tested with cudnn v4 and Soumith's benchmarks (using Lasagne).
- [ ] The slowdowns experienced with `time_*` and `guess_*` reported at #4448
- [x] Compilation error of `GpuDnnConvGradW` with `time_*` and `guess_*`
- [x] This sometimes happen on some calls, even when the function had been called tens of times before with the same shapes:
```python: /home/erisuser/p4sw/sw/gpgpu/MachineLearning/cudnn_v4/src/conv2d_fft.cu:520: cudnnStatus_t getBufferPointers(void*, float*&, cuComplex*&, T_INPUT*&, float*&, cuComplex*&, cuComplex*&, cuComplex*&, cuComplex*&, cuComplex*&, cuComplex**&, float*&, size_t, size_t, size_t) [with T_INPUT = float]: Assertion `(size_t)workSpace % 64 == 0' failed. ``` It seems to appear in the [nightly buildbot](https://groups.google.com/d/msg/theano-buildbot/6AyvX5OjRAA/1OtunnFVLAAJ) as well.

**Comment by nouiz** [comment]
The compilation error where with which archtecture?

**Comment by nouiz** [comment]
I don't have compilation error. Theano cache don't always put the cudnn
version in the key. So if you are mixing Theano cache between cudnn
version, this could explain that.

**Comment by lamblin** [comment]
Here is the log I have of the error, after `theano-cache purge`.
Version of Theano: `1bd371ce6edbe27260a7c38d8b75c2dcb9f6b53d`
Version of libgpuarray: `fc36a40526c0a8303ace6c574ffdefba7feafe17`
[dnn_compile_error.txt](https://github.com/Theano/Theano/files/245409/dnn_compile_error.txt)

**Comment by nouiz** [comment]
I have an branch with the compilation crash fix:

https://github.com/nouiz/Theano/tree/dnn

Before making a PR, I'll investigate the other problems.

**Comment by nouiz** [comment]
The crash fix by https://github.com/Theano/Theano/pull/4467

**Comment by abergeron** [comment]
#4478 fixes the time_/guess_ issues

**Comment by abergeron** [comment]
https://github.com/Theano/libgpuarray/pull/165 should fix the assert.

**Comment by lamblin** [comment]
time/guess seem to have been fixed in at least 3/4 cases, I'm checking the 4th one.

**Comment by lamblin** [comment]
The issue in the 4th one is not related to cuDNN, so I'm closing this one as fixed.
