### ISSUE TITLE
Implement DownsampleFactorMaxGradGrad.grad

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4456]
The gradient is simply MaxPoolGrad.
Tests should be added as well.

**Comment by yobibyte** [comment]
Could you elaborate a little bit more on that?

**Comment by lamblin** [comment]
Someone already has working code for that, they just need to add a test and submit a PR, which should be done in a couple of weeks. We just created the issue to keep track of it.

**Comment by yobibyte** [comment]
Ok.

Sincerely yours,
Vitaly Kurin

**Comment by lamblin** [comment]
Fixed by #4842.
