### ISSUE TITLE
T.grad raises TypeError with ifelse statement

### ISSUE THREAD

**Issue by hlin117** [Theano/Theano#4471]
I have this simple code that implements the 0-1 loss using an `ifelse` op. It runs into a compiler error

```
import theano
import theano.tensor as T
import numpy as np
from theano.ifelse import ifelse

w = theano.shared(np.random.rand(10))
b = theano.shared(np.random.rand())
params = [w, b]

x = T.vector()
y = T.scalar()

score = w.dot(x) + b
correct = (score * y > 0)

loss = ifelse(correct, 0, 1)
updates = [(param, param - 0.5 * T.grad(cost=loss, wrt=param))
           for param in params]
#TypeError: ('IfElse requires same types for true and false return values', Elemwise{Cast{float64}}.0, #Elemwise{second,no_inplace}.0, TensorType(float64, scalar), TensorType(int8, scalar))
```

This doesn't make sense to me, since `0` and `1` are the same types. Even when I force cast, I run into the same error:
```
>>> no_loss = T.cast(0, "int64")
>>> one_loss = T.cast(1, "int64")
>>> loss = ifelse(correct, no_loss, one_loss)
>>> updates = [(param, param - 0.5 * T.grad(cost=loss, wrt=param)) for param in params]
TypeError: ('IfElse requires same types for true and false return values', Elemwise{Cast{float64}}.0, Elemwise{second,no_inplace}.0, TensorType(float64, scalar), TensorType(int8, scalar))
```

I am using theano commit 1bd371ce6edbe27260a7c38d8b75c2dcb9f6b53d on a Mac OS X, El Capitan.

**Comment by hlin117** [comment]
Here's a workaround. `T.switch` does not suffer from this problem. The following code compiles just fine.
```
>>> loss = T.switch(correct, 0, 1)
>>> updates = [(param, param - 0.5 * T.grad(cost=loss, wrt=param))
>>>            for param in params]
```

**Comment by nouiz** [comment]
If you do:


loss = ifelse(correct, 0., 1.)

It work. Check the 0 and 1 are not float number and not int numbers. The grad don't work well with int. This cause some upcast at the wrong place. I'll see if we can fix this in Theano, but I'm not sure this is safe. But you have a work around in the mean time.

**Comment by nouiz** [comment]
By the way, why not just do a negation of the condition? This would result in a simpler graph:

loss = T.neg(correct)

**Comment by nouiz** [comment]
I have a proposal fix here:
https://github.com/nouiz/Theano

I'm not sure at 100% this is right. But in all cases, for you I think you should use T.neg(correct)

**Comment by hlin117** [comment]
@nouiz the `loss = T.neg(correct)` is a good idea. Thanks. I was actually using this issue report as an example of a reproducible bug related to my own bug. My own bug involves a lot hairier theano code.

**Comment by nouiz** [comment]
This PR have a porposed fix:

https://github.com/Theano/Theano/pull/4472

**Comment by hlin117** [comment]
@nouiz Thank you for looking into the problem.
