### ISSUE TITLE
ifelse does not perform lazy evaluation with test_values

### ISSUE THREAD

**Issue by hlin117** [Theano/Theano#4474]
As title. This is reproducible code.

The code should not evaluate `ints[0]` because `is_size_zero = 1` (True).

```
>>> import theano
>>> import theano.tensor as T
>>> from theano.ifelse import ifelse
>>> import numpy as np
>>> from theano.printing import Print
>>> theano.config.compute_test_value = "raise"
>>>
>>> ints = T.ivector()
>>> ints.tag.test_value = np.array([]).astype(np.int32)
>>>
>>> is_size_zero = T.eq(ints.size, 0)
>>> is_size_zero = Print("ints size is zero?")(is_size_zero)
>>> ifelse(is_size_zero, -1, ints[0])
ints size is zero? __str__ = 1
IndexError: index out of bounds
```

This is using commit 1bd371ce6edbe27260a7c38d8b75c2dcb9f6b53d on OS X, El Capitan.

Related: #3004, however this issue is concerned with runtime evaluation instead of pre-compile time evaluation.

**Comment by nouiz** [comment]
The error is related to your test value. You try to access the element 0 of a vector of 0 element. This isn't good:) Use this line instead:

>>> ints.tag.test_value = np.array([1]).astype(np.int32)

Then this cause another error so use this other line:

>>> ifelse(is_size_zero, np.asarray(-1, dtype='int32'), ints[0])

**Comment by hlin117** [comment]
> The error is related to your test value. You try to access the element 0 of a vector of 0 element. This isn't good :)

The purpose of the example is to demonstrate that using the vector of size zero, `is_size_zero = 1`, so we should return `-1` from that `ifelse` instead of evaluating `ints[0]` (which would otherwise cause an `IndexError`).

The lazy evaluation should skip `ints[0]` because `is_size_zero = 1`, right?

**Comment by nouiz** [comment]
It don't work like that with test_value. test_value will compute all branch as soon as they are executed. There isn't any lazy evaluation for test value. The purpose of test value is to execute the computation while building the graph.

In fact, you don't call ifelse, but jut ins[0] in your example, it will fail.

**Comment by lamblin** [comment]
Like @nouiz said, test values will force the computation of variables as soon as you create them, even if they are not needed in the end, or could be skipped. In other words, the point of computing test values is to force eager (not lazy) computation.

**Comment by hlin117** [comment]
Thanks @lamblin , @nouiz . Do you think more documentation regarding `ifelse` and test_values are appropriate?

**Comment by nouiz** [comment]
Added this in the doc:

https://github.com/Theano/Theano/pull/4464

thanks

**Comment by nouiz** [comment]
I added a note about this in the doc.
