### ISSUE TITLE
BatchDot on CPU sometimes should copy the inputs

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4476]
When one of the input don't have one dimensions of size 1.

https://groups.google.com/d/topic/theano-users/fsJhhd6Cwr4/discussion

work around, use cpu_contiguous on the inputs that cause problems.

**Comment by hantek** [comment]
I assume it can be fixed by adding T.extra_ops.cpu_contiguous() in [this](https://github.com/Theano/Theano/blob/master/theano/tensor/blas.py#L2329-L2363) part, right?

The dimshuffle() in computing the grad is the culprit that fails joelthchao's code.

**Comment by hantek** [comment]
Seems it requires editing the c code. Could someone give me some guidelines in how to fix it?
