### ISSUE TITLE
Super high system cpu usage

### ISSUE THREAD

**Issue by yiyang-gt** [Theano/Theano#4480]
Hi,

I am running theano program on Ubuntu 14.04. However, I found the system cpu usage is incredibly high... Here are results given by sar:

11:19:01 AM     CPU     %user     %nice   %system   %iowait    %steal     %idle
2:49:01 PM     all      6.97      0.00     92.22      0.03      0.00      0.79
12:51:01 PM     all      6.97      0.00     92.21      0.03      0.00      0.79
12:53:01 PM     all      7.13      0.00     90.98      0.04      0.00      1.85

htop also gives a lot of red bars (system cpu usage bars). 

It seems that theano forces each program to run on multiple cores, which may cause the high system overhead. 

Does someone know the cause and solution to this problem?

Thanks!

**Comment by nouiz** [comment]
I don't understand the table.

But each Theano job can use multiple process by default. So if you start
many jobs in parallel, you must tell Theano to not use too much process. See

http://deeplearning.net/software/theano/tutorial/multi_cores.html

You can use the env variable: OMP_NUM_THREADS=1 to force to use only 1 core
for the full software stack.

Fred

**Comment by yiyang-gt** [comment]
Thanks for your reply. 

The code works pretty good on RHEL. 

However, on ubuntu, different values of OMP_NUM_THREADS make no difference. Each program is forced to splitted to several subprograms. Each subprogram can only take less than 10% CPU, and 90% CPU are used by system/kernel threads...

**Comment by nouiz** [comment]
Which version of Ubuntu? WHich version of blas did you installed? BLAS
could be the cause of this problem. I suppose you have matrix dot product
in your code.

**Comment by yiyang-gt** [comment]
Ubuntu 14.04. I follow http://deeplearning.net/software/theano/install_ubuntu.html#manual-openblas-instruction and install the openblas.

Yes, my code has matrix dot product operations.

**Comment by nouiz** [comment]
It work well for me in that setup.

Can you pass the Theano flag to disable openblas, or at least, part of it:

blas.ldflags=

**Comment by yiyang-gt** [comment]
Here is my .theanorc file:

--------------------------------------------------------
[global]
floatX = float32
device = cpu
openmp = True
#base_compiledir = /path/to/base/dir
profile = False

[nvcc]
fastmath = True

[blas]
ldflags = -lopenblas

[cuda]
#root = /path/to/cuda/
--------------------------------------------------------

I tried to set openmp = False/True and fastmath = False/True, but no differences at all. 

Maybe my ubuntu version is just very weird...

Thanks,
Yi

**Comment by lamblin** [comment]
I don't think we are able to help with that, sorry.
For more support, you can try StackOverflow or theano-users.
