### ISSUE TITLE
Repeat 'None' times

### ISSUE THREAD

**Issue by ghost** [Theano/Theano#4482]
Hi,

i have a network that gets an arbitrary input length (None, None) := (Samples, length)
i would like to repeat the input as its length : 
`input.dimshuffle((0, 'x', 1))`
`repeat(input, input.shape[0], axis=1)`

But because input.shape[0] = None at compilation, i get:
`theano.tensor.var.AsTensorError: ('Cannot convert None to TensorType', <class 'NoneType'>)`

any solution?
10x

**Comment by nouiz** [comment]
I will need the full error message.

**Comment by lamblin** [comment]
Since Theano is strongly-typed, it is not possible to change a value from None to a number at run-time.
