### ISSUE TITLE
Leky relu upcast to float64

### ISSUE THREAD

**Issue by hmendozap** [Theano/Theano#4483]
Hi,

I noticed that the leaky rectifier activation upcasts the gradient of the weights in the layer. (I mentioned on Lasagne repo)
```
theano.tensor.nnet.relu(X, np.float32(0.123))
/home/mendozah/workspace/envHDMp/bin/ipython:1: UserWarning: You are creating a TensorVariable with float64 dtype. You requested an action via the Theano flag warn_float64={ignore,warn,raise,pdb}
```
What I find weird is that if alpha is python float, there is no upcast, but if it is np.float32 there is.
So I just added this to the call:
```python
alpha =  theano.tensor.as_tensor_variable(alpha))
```

Should that be enough?

Thanks,
HM

**Comment by nouiz** [comment]
What is X.type?

**Comment by hmendozap** [comment]
float32

**Comment by f0k** [comment]
This was reported at Lasagne/Lasagne/issues/677, and `theano.tensor.as_tensor_variable(alpha)` is a good solution (we had similar issues in other places in Lasagne). We want to allow `alpha` to be either a Python float, Theano float or numpy float without any upcasting to float64 occurring at `alpha + 1` and `alpha - 1` here: https://github.com/Theano/Theano/blob/8c7511b/theano/tensor/nnet/nnet.py#L2223-2224
This can be achieved either by wrapping `alpha` in `theano.tensor.as_tensor_variable`, or by wrapping `1` in `theano.tensor.constant`.

**Comment by nouiz** [comment]
thanks:

https://github.com/Theano/Theano/pull/4484
