### ISSUE TITLE
crash during test_nvidia_driver---"argument  not a CudaNdarray"

### ISSUE THREAD

**Issue by braingineer** [Theano/Theano#4485]
Hi all,

I updated to cuDNN 5 and theano 0.9 and then things started to crash.  

I've pasted the crash here:

https://gist.github.com/braingineer/cabb0706dcdf334fac7bc9d59ef96a31

Thanks

**Comment by braingineer** [comment]
re-installed 0.8.2 and it seems to be working.

**Comment by nouiz** [comment]
Fixed in https://github.com/Theano/Theano/pull/4489

thanks

**Comment by braingineer** [comment]
awesome, thanks!
