### ISSUE TITLE
Reuse compile Cuda expression

### ISSUE THREAD

**Issue by arita37** [Theano/Theano#4487]
Hi,

Is there a way to reuse the compile code (when we compile the expression) in C and Cuda,
for after ?

(especially, when we only change very little in the graph calculation).

Thanks

**Comment by nouiz** [comment]
Theano already do this. What do you want to do?

**Comment by arita37** [comment]
I have compiled expression and want to use them 1 month later / any time 
later without re-compiling.
(during this time, I will use theano for other projects).

Can theano handle a folder of compiled expression ? (like we specify the 
directory)



> Frédéric Bastien <mailto:notifications@github.com>
> Tuesday, May 10, 2016 2:30 AM
> Theano already do this. What do you want to do?
>

**Comment by lamblin** [comment]
You can specify which folder to use with configuration flags, in particular `compile_dir` (see also `base_compiledir` and `compiledir_format`).
There is an expiration time of 24 days [here](https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L659), but it could be made as an option.

**Comment by arita37** [comment]
Hi,

Thanks, it does not solve of how theano can pick up the right folder/files 3 weeks later (during this time I have run other simulations/compils).

If I specify a specific folder where 3 weeks old files, can theano recongnize the folder
and prevent re-compiling ?


Thanks
Kevin








On 10 May 2016, at 06:22, Pascal Lamblin <notifications@github.com> wrote:

You can specify which folder to use with configuration flags, in particular compile_dir (see also base_compiledir and compiledir_format).
There is an expiration time of 24 days here, but it could be made as an option.

―

**Comment by nouiz** [comment]
I think you are misunderstanding something in Theano. So I'll try to
describe more how our compilation work.

The compilation step is in 2 step:

1) do some graph optimization
2) reuse c code or generate c code and compile it if not in the cache.

The c code compilation is per node in the graph, not per function. This
mean you will share the c code between Theano function. Normally, this step
2, is only time consuming the first time you compile many new c code. For
example, if you change computer where the cache is empty.

If you use Theano 0.8 or later and pickle a compiled Theano function, it
should work. We try to keep it working with newer version of Theano, but
you aren't sure to get all the updates from Theano with that way of working.

This will skip by default the step 1). step 2 will reuse the c code cache
if still available. So this allow to save some pre-made Theano function and
reuse it later. Theano will be smart and reuse the C code if he can, it
not, then it will recompile automatically.

Do this clear up your understanding?

Normally, people don't save the c code. They just recompile the Theano
function when they need it.

**Comment by nouiz** [comment]
no news, so I'll close this issue.
