### ISSUE TITLE
latest install of theano in mac OSX 10.11.4 with both canopy and bleeding edge version not working

### ISSUE THREAD

**Issue by rkunnawa** [Theano/Theano#4497]
Dear Theano experts, 

I was following the instructions here http://deeplearning.net/software/theano/install.html#installing-theano 
and I tried installing the latest version of theano with canopy and the bleeding version from this repo multiple times and the theano.test() fails with a lot of errors.  i initially got the UserWarning: PyCUDA import failed in theano.misc.pycuda_init and then a lot a lot of ERRORs 

I think this might be due to come conflicts with the python that i already have but i dont know what is causing that exactly. 
this is my PYTHONPATH incase that helps 
/Users/raghav/WORK/RIVET/local/lib/python2.7/site-packages::/Users/raghav/root-6.04.10/lib:/Users/raghav/Theano:/Users/raghav/pylearn2:/usr/local/lib/python2.7/site-packages:/user/local/bin/python:/usr/local/lib/python2.7/site-packages:/user/local/bin/python:

pb-d-128-141-166-103:~ raghav$ python
Python 2.7.10 (default, Jul 13 2015, 12:05:58) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
>>> theano.test()
Theano version 0.9.0dev1.dev-8c58dfb88ba58e22c3c6d75037c72dfab3475d4e
theano is installed in /Users/raghav/Theano/theano
NumPy version 1.11.0
NumPy relaxed strides checking option: False
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
Python version 2.7.10 (default, Jul 13 2015, 12:05:58) [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
nose version 1.3.7
/Users/raghav/Theano/theano/misc/pycuda_init.py:35: UserWarning: PyCUDA import failed in theano.misc.pycuda_init
  warnings.warn("PyCUDA import failed in theano.misc.pycuda_init")
/Users/raghav/Theano/theano/sandbox/gpuarray/__init__.py:9: UserWarning: theano.sandbox.gpuarray has been moved to theano.gpuarray. Please update your code and pickles.
  warnings.warn(message)
EE...........E..../Users/raghav/Theano/theano/compile/profilemode.py:84: UserWarning: DEPRECATION WARNING: The ProfileMode is deprecated. Use the Theano flags/parameter to theano.function 'profile=True' instead of 'mode=ProfileMode'
  "DEPRECATION WARNING: The ProfileMode is deprecated. "
...../usr/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:326: RuntimeWarning: All-NaN slice encountered
  warnings.warn("All-NaN slice encountered", RuntimeWarning)
/usr/local/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:227: RuntimeWarning: All-NaN axis encountered
  warnings.warn("All-NaN axis encountered", RuntimeWarning)
.E........E.............................../Users/raghav/Theano/theano/gof/vm.py:832: UserWarning: CVM does not support memory profile, using Stack VM.
  'CVM does not support memory profile, using Stack VM.')
...........SS.............0.27815248301
0.27815248301
0.27815248301
0.27815248301
.............................................
.....
======================================================================
ERROR: Failure: ImportError (No module named nose_parameterized)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/raghav/Theano/theano/tests/test_ifelse.py", line 15, in <module>
    from theano.tests import unittest_tools as utt
  File "/Users/raghav/Theano/theano/tests/unittest_tools.py", line 7, in <module>
    from nose_parameterized import parameterized
ImportError: No module named nose_parameterized

======================================================================
ERROR: Failure: ImportError (No module named nose_parameterized)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/raghav/Theano/theano/tests/test_rop.py", line 16, in <module>
    from theano.tests import unittest_tools as utt
  File "/Users/raghav/Theano/theano/tests/unittest_tools.py", line 7, in <module>
    from nose_parameterized import parameterized
ImportError: No module named nose_parameterized

----------------------------------------------------------------------
Ran 411 tests in 39.217s

FAILED (SKIP=24, errors=87)
<nose.result.TextTestResult run=411 errors=87 failures=0>
>>> 
>>> 

Cheers
Raghav

**Comment by nouiz** [comment]
You are missing one new Theano dependency:

nose_parameterized

It is documented on that page, but maybe it could be better documented. Do
you know where we could put it to have you install it the first time?
To install it:

pip install --user nose-parameterized

**Comment by rkunnawa** [comment]
Ahh i see that its under the optional section. My bad, i didnt see that part. I think its detailed very nicely. I installed the nose and now its running... If it fails again, i will let you know. thanks for the quick reply!
