### ISSUE TITLE
drop Python 2.6 and 3.3 support

### ISSUE THREAD

**Issue by kmike** [Theano/Theano#4507]
What do you think about dropping Python 2.6 support in Theano, and starting to run tests in Python 2.7 by default? Numpy will drop Python 2.6 support soon (https://github.com/numpy/numpy/blob/master/doc/release/1.12.0-notes.rst), and Python 2.6 is not supported by Python core team for years - no even security support.

**Comment by nouiz** [comment]
Personally, I think we should do it.

But we should ask on theano-user and theano-dev about this. Do you want to
do this?

**Comment by abergeron** [comment]
Just to note that numpy 1.12 also drops support for python 3.3 which we
support.

2016-05-13 8:30 GMT-04:00 Frédéric Bastien <notifications@github.com>:

**Comment by nouiz** [comment]
It seem nobody objected. I would wait to make Theano 0.9 still support them, but remove the support just after 0.9 release. We will try to make it this summer. It will officially deprecate the old back-end. So we don't want to wait to long for it.

**Comment by nouiz** [comment]
See another reason to drop python 2.6 support:

https://github.com/Theano/Theano/issues/4685 one package got updated and that broke travis. I'm fixing this for pydot by fixing the version in https://github.com/Theano/Theano/pull/4701, so if pydot drop support for it, travis won't break again.

**Comment by johnyf** [comment]
Upstream `pydot` fixed https://github.com/erocarrera/pydot/issues/123 and is again compatible with python 2.6. However, support for python 2.6 will not be actively maintained.

**Comment by nouiz** [comment]
Python 2.6 was dropped.

**Comment by nouiz** [comment]
NumPy 1.12 that was just released dropped Python 3.3. We should do it not for this release 0.9, but the next one 0.10
