### ISSUE TITLE
How to detect if libgpuarray backend is used?

### ISSUE THREAD

**Issue by mrakgr** [Theano/Theano#4509]
I am asking because the information in the documentation can be stale, so I thought that `libgpuarray` might come with the main Theano build, so I might be wasting time trying to get it to run manually. More problematically, when I try to run the tests for it on Windows, I get a [heap corruption error](https://github.com/Theano/libgpuarray/issues/173).

Is there a command to check if it is being used?

Also in a similar vein, I am worried if the OpenBLAS is being loaded correctly into Theano. How could I check for that as well?

**Comment by abergeron** [comment]
For the libgpuarray backend, it should print something along this line for initialization:

```
Mapped name None to device cuda0: GeForce GTX TITAN X
```

The card will change depending on you hardware.

For OpenBLAS, I don't know how to check.

Finally this is more of a support question that an issue, so it should be addressed to either the theano-users mailing list or stackoverflow.

**Comment by nouiz** [comment]
For the openblas, you can print:

import theano
print theano.config.blas.ldflags

this will tell you which flag Theano use for blas. If it contain openblas,
then you are good.

**Comment by mrakgr** [comment]
@nouiz 
The worrying thing about this is that by default the `blas.ldflags` is empty unlike what it says in the documentation, and if I pass it some random strings instead of -lopenblas it does not give me an error message.
```
>>> theano.config.blas.ldflags
'-LC:\\OpenBlas -lopenblas'
```
I am guessing something like the above is fine.
@abergeron 
```
>>> import theano
Using gpu device 0: GeForce GTX 970 (CNMeM is enabled with initial size: 75.0% of memory, cuDNN 5004)
```
The above is what I get when I load Theano. It is not at all like your message. Though...
```
>>> import theano.gpuarray
>>>
```
...the above import works fine. So can I assume that Theano will try to use the new backend?

**Comment by nouiz** [comment]
This use the old back-end. It isn't the output of the new back-end. See

http://deeplearning.net/software/theano/tutorial/using_gpu.html#gpuarray

You use must device=cuda and not device=gpu to enable the new back-end.

**Comment by mrakgr** [comment]
Your link is broken for me, but your message is very helpful nonetheless! Thank you!

In the [configuration documentation](http://deeplearning.net/software/theano/library/config.html#envvar-THEANO_FLAGS), the `cuda` option is not documented.

I knew my hunch had something to it. Maybe it was something I read a few months ago when I tried to set it up on Linux. At any rate, I'll try it.

**Comment by mrakgr** [comment]
```
>>> import theano
Mapped name None to device cuda: GeForce GTX 970
```
Yeah, I now get the correct message. I should note that I have to use the debugger to force my way past the heap corruption error otherwise it crashes.

Also, where is `device=cuda` option documented? This might be an issue with the documentation. It should definitely be in the configuration options.

**Comment by nouiz** [comment]
I made the comment in the PR that doc this:

https://github.com/Theano/Theano/pull/4500

**Comment by slefrancois** [comment]
Done
