### ISSUE TITLE
nvcc with gcc 6.1.1 crash (+solution)

### ISSUE THREAD

**Issue by xeray** [Theano/Theano#4514]
Dear Theano-Team,

some distros such as arch linux have now gcc 6.1.1 to which nvcc (7.5.17) is not compatible (gives 100+ errors during compilation) unless it is called with the following options:

```-std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO```

(see [here](https://bugs.archlinux.org/task/49272) and [here](https://www.reddit.com/r/archlinux/comments/4iczja/a_work_around_if_you_are_using_cuda_and_have/d30duqi))

The second option can be injected into the compiler command using ``theano.config.nvcc.flags`` which is then put amongst other ``Xcompiler flags``. But the first flag cannot be placed there because it needs to be directly given to nvcc  ( in ``preargs1`` in [this line](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/nvcc_compiler.py#L284) ). As it is now, this cannot be achieved through ``theano.config`` because ``preargs1`` must have a specifically listed pattern. I propose to add ``'-std='`` into the list of patterns for ``preargs1``. Then, putting
``
[nvcc]
flags = -std=c++11 -D__CORRECT_ISO_CPP11_MATH_H_PROTO
``
in .theanorc fixes this whole issue.

But I cannot say whether this additional pattern might cause any other problems. If so, another way to add this flag must be created.

Cheers
Marius

**Comment by abergeron** [comment]
I just want to be very clear that we don't support incompatible combinations of gcc and nvcc.  So if you get any other problem with that the response will be "install a supported gcc".

That said I don't oppose the addition of -std to the recognized patterns in preargs1 and your PR was merged.
