### ISSUE TITLE
Scan throws error when indexing through vector longer than 128 (very weird)

### ISSUE THREAD

**Issue by lobachevzky** [Theano/Theano#4517]
```python

import theano
import theano.tensor as T
import numpy
vector = T.ivector() 
offset = 1

result, _ = theano.scan(fn=lambda i: [vector[i : i + offset], i + 1],
                        outputs_info=[None, T.constant(0)],
                        n_steps=vector.size - offset)

test = theano.function([vector], outputs=result)
test(numpy.ones(128, dtype='int32'))  # passes
test(numpy.ones(129, dtype='int32'))  # throws error
```

results in the following error:

> ValueError: could not broadcast input array from shape (0) into shape (1)
> Apply node that caused the error: forall_inplace,cpu,scan_fn}(Elemwise{add,no_inplace}.0, IncSubtensor{InplaceSet;:int64:}.0, Elemwise{add,no_inplace}.0, <TensorType(int32, vector)>)
> Toposort index: 11
> Inputs types: [TensorType(int64, scalar), TensorType(int8, vector), TensorType(int64, scalar), TensorType(int32, vector)]
> Inputs shapes: [(), (128,), (), (129,)]
> Inputs strides: [(), (1,), (), (4,)]
> Inputs values: [array(128), 'not shown', array(128), 'not shown']
> Outputs clients: [[Subtensor{int64:int64:int8}(forall_inplace,cpu,scan_fn}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1})], ['output']]
> 
> HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
> HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Note that the first execution of the `test` function -- `test(numpy.ones(128, dtype='int32'))` -- does not throw an error, whereas the second --`test(numpy.ones(129, dtype='int32'))` -- does (as do all vectors longer than 129, that I've tried).

Print statements reveal that the error is thrown when `i` equals 127.
I was unable to reproduce the error without `scan`, i.e. with `test = theano.function([vector], outputs=vector[127:128])`. I also had to index a range to reproduce the error, i.e. 
```python
result, _ = theano.scan(fn=lambda i: [vector[i], i + 1],
                        outputs_info=[None, T.constant(0)],
                        n_steps=vector.size - offset) 
```
does not throw an error.

**Comment by nouiz** [comment]
The problem is that the 0 get casted to int8 in Theano. You can force the dtype to be int32 like this:

outputs_info=[None, T.constant(0, dtype='int32')],

Theano use the smallest dtype that fix exactly the data for python int and float. If you use numpy object, as they are typed, we use the type gived.

**Comment by lobachevzky** [comment]
Great! That fixed it. Thanks!

**Comment by nouiz** [comment]
I made an issue related: https://github.com/Theano/libgpuarray/issues/177

This would fix some issue like this one.

**Comment by lobachevzky** [comment]
Just to make sure I understand: since 0 was int8, once `i` got to 128, it just went back to 0?

**Comment by nouiz** [comment]
128 can't be represented in int8:

>>> numpy.int8(128)
-128
>>> numpy.int8(129)
-127
>>> numpy.int8(130)
-126

**Comment by lobachevzky** [comment]
Got it. Thanks.
