### ISSUE TITLE
Good broadcasting tutorial

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4519]
This page is not visualized correctly: http://deeplearning.net/software/theano/sandbox/broadcasting.html

We should not just fix the display, but make a good tutorial with picture and exercices.

TODO:
- [ ] delete the doc/sandbox/broadcasting.txt file. 
- [ ] move http://deeplearning.net/software/theano_versions/dev/library/tensor/basic.html#broadcasting-in-theano-vs-numpy to the Theano tutorial in its own page. 
- [ ] Add in this new page, as text, an example of (F, F) + (F, T).

**Comment by lamblin** [comment]
There is some information and a nice figure at http://deeplearning.net/software/theano_versions/dev/library/tensor/basic.html#broadcasting-in-theano-vs-numpy
We should probably move it outside of the "library" section and into the tutorial part, with an example like @nouiz suggested. There is not much more in the sandbox/broadcasting page.
