### ISSUE TITLE
MissingGxx , g++ not available Error

### ISSUE THREAD

**Issue by ahmed-18** [Theano/Theano#4521]
I've been trying to deploy my Python Flask App that uses Conv nets using Theano on local IIS. When I try to load a pickled Lasagne Neural Network , I get following Errors
1. Unable to Create compiledir. I solved this by changing compiledir path in configdefaults.py and giving read/write rights to IIS on that directory. Now compiledir gets created and I get a different type of error given below.
2. Now I'm getting MissingGXX error "g++ not available! We can't compile c code.". G++ is there in my PythonFolder\Scripts and I've added this path to my environmental variable PATH.

> I just Want to know that what causes this error while g++ is already there and added to PATH? Is it because Theano can't find g++ and it's all about path issues or it has something to do with compiledir lock

PS: I can run the code from my Winpython console and everything works fine. I've seen the contents of %PATH% , %PYTHONPATH% and %HOME% from my Win python console and replicated the same on my deployed IIS web App.

Here's the header of the stack trace :

(MissingGXX('The following error happened while compiling the node', Shape_i{0}(input.input), '\n', "g++ not available! We can't compile c code.", '[Shape_i{0}(input.input)]'), <function _constructor_Function at 0x0000000006708588>, (<theano.compile.function_module.FunctionMaker object at 0x0000000019A7A320>

**Comment by nouiz** [comment]
Did you log out/reboot after changing your env variable? Sometimes this is
needed to take effect on Windows. I don't know the details.
