### ISSUE TITLE
Theano on Windows 8.1

### ISSUE THREAD

**Issue by AakashKumarNain** [Theano/Theano#4527]
I am writing this because literally I have become frustrated by the fact that why such a low support for Windows is provided by every package for deep learning. I tried to install theano on ubuntu 14.04 as per the instructions provided in the documentation but if you upgrade to python3 in that ,thing don't work out smoothly. I have found that installing packages is much easier in Win8.1 , then why is there no direct and smooth way to install theano. The steps given in documentation are for win 7 only and evey method uses Microsoft Visual Studio. If I don't like Visual Studio , why should I use it and why such a dependency to install packages?

**Comment by erfannoury** [comment]
Installing Theano on Windows is easy and fully supported. And you don't even need to install Visual Studio to use Theano.
If you want to use Theano only on CPU, you only need to install GCC (I recommend installing [TDM-GCC](http://tdm-gcc.tdragon.net/)).
Now if you want to use GPU, you also need to install CUDA SDK and Visual C++ Compiler. To install Visual C++ Compiler you can download and install Visual Studio shell (without needing to install the full Visual Studio) and then install the CUDA SDK. Remember to install compatible version of Visual C++ Compiler and CUDA SDK.

**Comment by AakashKumarNain** [comment]
I installed it but it still requires BLAS . Can you also please explain how to install BLAS ? I have seen the documentation for OpenBLAS and it didn't work out as the instruction given there .

**Comment by erfannoury** [comment]
You can install the latest release of OpenBLAS from the [OpenBLAS Releases page](https://github.com/xianyi/OpenBLAS/releases). Then remember to add corresponding flags to your config file, e.g. add this line to your `.theanorc` config file:
```
[blas]
ldflags = -LC:\\Path\\to\\OpenBLAS\\bin -lopenblas
```
Although I'm not sure about the OpenBLAS instructions, since I haven't used Theano on CPU to need OpenBLAS. You should check with the Theano team.

Also it's worth noting that Anaconda's installation of Python (which is highly recommended) comes with Intel's MKL library (you can obtain an academic license to use for free, if you're an academic).

**Comment by nouiz** [comment]
If youplan to use the GPU, you can ignore openblas and use this theano flag:

[blas]
ldflags =

This will cause slower operation on the CPU, that isn't your use case.

The Microsoft compiler is a dependency of NVIDIA SDK not Theano.

Fred

**Comment by AakashKumarNain** [comment]
@Fred I don't want to use it on GPU. I want to make it run on CPU only.

**Comment by AakashKumarNain** [comment]
okay I got everything installed and running but still I am facing this error 

C:/SciSoft/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -libopenblas
collect2.exe: error: ld returned 1 exit status

Please help!!

**Comment by erfannoury** [comment]
I think you need to give `libopenblas.a` to GCC to work. There is one in the OpenBLAS's `lib` folder after you extract the Release zip file.

**Comment by AakashKumarNain** [comment]
Can you please tell me the exact path where to put this in GCC folder because I have copied this to the above path(shown in error) and it still didn't work

**Comment by erfannoury** [comment]
Looks like the last release of OpenBLAS with Windows build (not just the source code) is [OpenBLAS v-0.2.15](https://sourceforge.net/projects/openblas/files/v0.2.15/). In the corresponding compressed file for your architecture you can find the file that you need. Then provide the address to that file in your config file (`.theanorc`). 
So I suspect that you should change the config file to this:
```
[blas]
ldflags = -LC:\\Path\\to\\OpenBLAS\\lib -lopenblas
```
where the `lib` subdirectory contains the `libopenblas.a` file.

**Comment by lamblin** [comment]
You may need to compile openblas as a dynamic library (.dll), the .a file may not be enough.
