### ISSUE TITLE
Shape inconsistency for strided pooling with ignore_border=False

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#4534]
As reported in Lasagne/Lasagne/issues/685, there's something wrong with Theano's pooling implementation for `ignore_border=False`. Reduced test case:
```
>>> import numpy as np
>>> import theano
>>> import theano.tensor as T
>>> x = np.ones((1,1,4,4), dtype=theano.config.floatX)
>>> y = T.signal.pool.pool_2d(T.constant(x), (4,4), ignore_border=False, st=(2,2))
>>> y.shape.eval()
(1, 1, 1, 1)
>>> y.eval().shape
(1, 1, 2, 2)
```
So we pool a 4x4 image with a 4x4 window with stride 2. The result should be 1x1, regardless of whether we ignore the border or not.
The evaluated shape (`y.shape.eval()`) is correct, but the shape of the evaluated value (`y.eval().shape`) is too large.

**Comment by nouiz** [comment]
I have a fix, I still need to finish it and add tests.

**Comment by nouiz** [comment]
thanks the problem seem to be only when the window is bigger then the image. I have a PR:

https://github.com/Theano/Theano/pull/4544
