### ISSUE TITLE
Unuseful error message when using Boolean tensor

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#4538]
```
In [12]: x = shared(np.ones((), dtype=np.bool))

In [13]: y = tensor.fscalar()

In [14]: tensor.where(tensor.eq(y, y), x, x)
```

Gives the following unuseful error:

> AsTensorError                             Traceback (most recent call last)
> <ipython-input-14-68823a644960> in <module>()
> ----> 1 tensor.where(tensor.eq(y, y), x, x)
> 
> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/gof/op.py in **call**(self, _inputs, *_kwargs)
>     609         """
>     610         return_list = kwargs.pop('return_list', False)
> --> 611         node = self.make_node(_inputs, *_kwargs)
>     612
>     613         if config.compute_test_value != 'off':
> 
> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/tensor/elemwise.py in make_node(self, *inputs)
>     541         using DimShuffle.
>     542         """
> --> 543         inputs = list(map(as_tensor_variable, inputs))
>     544         shadow = self.scalar_op.make_node(
>     545             *[get_scalar_type(dtype=i.type.dtype).make_variable()
> 
> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/tensor/basic.py in as_tensor_variable(x, name, ndim)
>     165         if not isinstance(x.type, TensorType):
>     166             raise AsTensorError(
> --> 167                 "Variable type field must be a TensorType.", x, x.type)
>     168
>     169         if ndim is None:
> 
> AsTensorError: ('Variable type field must be a TensorType.', <Generic>, <theano.gof.type.Generic object at 0x10299b4a8>)

**Comment by nouiz** [comment]
Theano don't support boolean type. theano.shared() create a Generic object,
not a Tensor object.

I agree we should raise a better error message. I'll do it.

**Comment by nouiz** [comment]
In fact, I'm not sure what we should do here. I don't want to make
theano.shared() raise an error, as there is corner case where people could
want that. But at the same time, it is very unfrequent that people want to
make a generic variable.

What about if the user pass an ndarray with bool to theano.shared() we
raise an error and tell that if they really want to do that, guide them on
how to do an genearic shared variable manually? @lamblin, what do you think
of that?

**Comment by lamblin** [comment]
Maybe falling back to Generic is a bad idea in the end, and we could add a mechanism for explicitly allowing Generic, but not do it in general.
This would force users to explicitly cast bool arrays to int8 or lists to ndarrays. It is reasonable in my opinion if there is a helpful error message.

**Comment by nouiz** [comment]
I like your proposition to not just change the interface for numpy.bool,
but all generic.

If someone want to work on that, it would be great. It isn't too hard, but
would make a good introduction to Theano internal without probably getting
lost.

**Comment by lamblin** [comment]
There are boolean arrays in Theano now, and your code snippet is now working.
