### ISSUE TITLE
Allow indexing using Ellipsis

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#4539]
Sometimes, I need to update a shared variable having dynamic shape.  I do this by calling:

```
function([], [], updates=[(x, inc(x, tensor.inc_subtensor(x[index], 1.0)))])
```

When the shape of `x` is a vector like `(4,)`, then `index == slice(None)` updates the whole vector.  Using `index == ()` gives a crazy exception (that should probably be fixed).

When the shape of `x` is a scalar like `()`, then `index == ()` works fine whereas using `slice(None)` gives the reasonable error:

> ValueError: The index list is longer (size 1) than the number of dimensions of the tensor(namely 0). You are asking for a dimension of the tensor that does not exist! You might need to use dimshuffle to add extra dimension to your tensor.

In numpy, I can deal with both cases by letting `index = Ellipsis` (or `...`).  Unfortunately, theano doesn't accept it, telling me:

> /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/theano/tensor/basic.py in as_tensor_variable(x, name, ndim)
>     206         except Exception:
>     207             str_x = repr(x)
> --> 208         raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
>     209
>     210 # this has a different name, because _as_tensor_variable is the
> 
> AsTensorError: ('Cannot convert Ellipsis to TensorType', <class 'ellipsis'>)

**Comment by NeilGirdhar** [comment]
A related problem is given a matrix `m` with some shape, how do I prepend a newaxis?  In numpy, I would do:

    m[np.newaxis]

or, more explicitly,

    m[np.newaxis, ...]

However, Theano complains about the first that:

    ValueError: ('You cannot drop a non-broadcastable dimension.', ((False,), ('x',)))

And about the second that


    AsTensorError: ('Cannot convert Ellipsis to TensorType', <class 'ellipsis'>)

I do not know the shape of `m` a priori, so I cannot do `m[np.newaxis, :]` or similar.

**Comment by NeilGirdhar** [comment]
Squashed pull request: https://github.com/Theano/Theano/pull/4840

**Comment by nouiz** [comment]
merged in https://github.com/Theano/Theano/pull/4853
