### ISSUE TITLE
d3viz module broken on Python 3

### ISSUE THREAD

**Issue by gibiansky** [Theano/Theano#4552]
When running `d3viz` on a node in Python 3, the output is broken, with the following JS error:

```
Uncaught SyntaxError: Expected "digraph", "graph", "strict", comment or whitespace but "b" found.
```

The reason is that the output JS looks like this:

``` javascript
var dotGraph = graphlibDot.read("b\'digraph G...
```

Note that `b\'` (which has a corresponding `\'` at the end). That looks like an issue with Python 3 support to me, and when I manually remove those bits the browser can render it just fine.

Don't know if Python 3 support is a priority or if Theano is meant to work on Python 3, but I figured I would report this since it seems straightforward to fix.

**Comment by nouiz** [comment]
U update to the dev version of Theano. I think it is already fixed there.

Thanks for the report.
Le 24 mai 2016 18:55, "Andrew Gibiansky" <notifications@github.com> a
écrit :

**Comment by nouiz** [comment]
As no news and it should be fixed, I close this issue.

**Comment by githubnemo** [comment]
I can still reproduce this from master. Not fixed sadly.

**Comment by nouiz** [comment]
Can you give the full error message?
