### ISSUE TITLE
theano fails cuda module compilation with gcc 5.x

### ISSUE THREAD

**Issue by ntoussaint** [Theano/Theano#4553]
specs: 
ubuntu 16.04
gcc 5.3
cuda toolkit 7.5
cudNN v5
theano git @ master (updated 25/05/2016)

There seems to be a problem when using gcc 5.x when at run time and module import it reports an error when trying to compile mod.cu. when reproducing the error manually it outputs the following:

```
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
```  
This is apparently reported elsewhere (in [tensorflow](https://github.com/tensorflow/tensorflow/issues/1346) for instance). and the workaround is to add a compiler flag in nvcc_compiler.py:

```
# add the compiler option to avoid string.h error 
preargs2.append('-D_FORCE_INLINES')
```

**Comment by nouiz** [comment]
This is already documented here:

http://deeplearning.net/software/theano/install_ubuntu.html

You can just pass a Theano flag and not modify Theano to pass that extra parameter to nvcc. As nvcc don't support that g++ version, there is also documentation on how to install a g++ version that is supported.

thanks for the report.
