### ISSUE TITLE
gpuarray tests should pass when floatX=float32 and add this to the daily buildbot

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4555]

**Comment by mgermain** [comment]
@nouiz 
Just to make sure, this issue is twofold right?
1. Make sure that all the gpuarray tests pass when floatX=float32
2. Add all the gpuarray tests to the daily builbot

**Comment by nouiz** [comment]
1. yes.
2. just to clarify, this is in the gpuarray daily buildbot. We have 2 daily
buildbot, 3 when the new one by @lefransi is done.

Fred

**Comment by Sentient07** [comment]
@nouiz  If you're having a list of opts that does not pass the test I would like to know them so that I could add few if they are missing there

**Comment by nouiz** [comment]
@abergeron will finish this.

**Comment by nouiz** [comment]
It is added in the gpuarray daily buildbot in float32. So I'll close this issue. It have a few errors, but I'll let this to be fixed as current buildbot errors.
