### ISSUE TITLE
Having problem with an objective function that gives unused input warning

### ISSUE THREAD

**Issue by wailoktam** [Theano/Theano#4557]
Hi, the following function I add to Keras yields a warning from Theano:

   def custom_objective(y_true, y_pred):
      if (y_true == 1):
        result = theano.tensor.maximum(0.09 - y_pred, 0.)
    else:
        result = theano.tensor.maximum(0.09 + y_pred, 0.)
    return result

 which is an implementation of the following:

L = max {0,m − cos(VQ, VA+) + cos(VQ, VA−)}

where m is 0.09, VQ is the vector representing a question sentence, VA+ is the vector representing a sentence including the correct answer to the question and VA- is the vector representing a sentence not including the correct answer.

Can anyone tell me what is wrong with my objective function? Many thanks in advance.

**Comment by lamblin** [comment]
Please use `theano-users` or StackOverflow for such requests.
GitHub tickets are for bug reports and feature requests.
In your case, you should not use Python `if / else` statements to check for values of symbolic variables, see http://deeplearning.net/software/theano/tutorial/conditions.html.
