### ISSUE TITLE
feature request: support for cuda 8.0 rc

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#4558]
https://developer.nvidia.com/cuda-release-candidate-download

**Comment by orionr** [comment]
+1

I'm just getting a GTX 1080 setup and CUDA 8.0 is preferred. @fayeshine have you seen errors on compilation yet or is this just preemptive?

**Comment by nouiz** [comment]
I had access to an early access. All in Theano was working correctly. Did
you tried it? If so, did you have problems?

In the new gpu back-end, a small difference was needed, I'll try to get the
fix merged this week. But the current GPU back-end was working well.

**Comment by nouiz** [comment]
Someone made a PR with the fix for the new GPU back-end:

https://github.com/Theano/libgpuarray/pull/181

So all problems I know are fixed.

**Comment by orionr** [comment]
@nouiz , just FYI, I've confirmed that CUDA 8.0 with Theano off master works great. Thanks! I would consider this closed myself.

**Comment by nouiz** [comment]
I would keep it open, as they have a new interface for batched dot that
should lower the overhead of using it.

thanks for the confirmation.

**Comment by nouiz** [comment]
Finally, I think we have nothing to do.
