### ISSUE TITLE
Error in theano.printing.pprint() while theano.printing.debugprint() seems to be working

### ISSUE THREAD

**Issue by indraforyou** [Theano/Theano#4559]
Function: (prediction function of DBN from https://github.com/lisa-lab/DeepLearningTutorials but with the last layer as linear regression instead of logistic regression)
`    predict_model = theano.function(
        inputs=[classifier.x],
        outputs=classifier.linLayer.y_pred)`

Output of:
`theano.printing.debugprint(predict_model)`
```
HostFromGpu [id A] ''   16
 |GpuElemwise{Add}[(0, 0)] [id B] ''   15
   |GpuDot22 [id C] ''   14
   | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id D] ''   13
   | | |GpuDot22 [id E] ''   12
   | | | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id F] ''   11
   | | | | |GpuDot22 [id G] ''   10
   | | | | | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id H] ''   9
   | | | | | | |GpuDot22 [id I] ''   8
   | | | | | | | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id J] ''   7
   | | | | | | | | |GpuDot22 [id K] ''   6
   | | | | | | | | | |GpuFromHost [id L] ''   5
   | | | | | | | | | | |x [id M]
   | | | | | | | | | |W [id N]
   | | | | | | | | |GpuDimShuffle{x,0} [id O] ''   4
   | | | | | | | |   |b [id P]
   | | | | | | | |W [id Q]
   | | | | | | |GpuDimShuffle{x,0} [id R] ''   3
   | | | | | |   |b [id S]
   | | | | | |W [id T]
   | | | | |GpuDimShuffle{x,0} [id U] ''   2
   | | | |   |b [id V]
   | | | |W [id W]
   | | |GpuDimShuffle{x,0} [id X] ''   1
   | |   |b [id Y]
   | |W [id Z]
   |GpuDimShuffle{x,0} [id BA] ''   0
     |b [id BB]
```

whereas ..
`theano.printing.pprint(predict_model)` gives error:
```
Traceback (most recent call last):
  File "./predict.py", line 60, in <module>
    predict()
  File "./predict.py", line 42, in predict
    theano.printing.pprint(predict_model)
  File "$PATH$/Theano/theano/printing.py", line 577, in __call__
    return self.process(*args)
  File "$PATH$/Theano/theano/printing.py", line 512, in process
    if condition(pstate, r):
  File "$PATH$/Theano/theano/printing.py", line 502, in <lambda>
    condition = (lambda pstate, r: r.owner is not None and
AttributeError: 'Function' object has no attribute 'owner'
```

Version: 0.9.0dev1.dev-5e50147375ad507990655cc1a3e990aa4c190549

**Comment by nouiz** [comment]
pprint is to be used inside a Theano graph to print something each time the Theano function is used.

What do you want to do with it? What was you expecting?

We keep issue for bug report/feature request. For user questions, use theano mailing list or stackoverflow.

**Comment by lamblin** [comment]
pprint has to be called on one variable, whereas debugprint can be
called on compiled functions or lists of variables.

If your function has only one output, you can use
theano.printing.pprint(predict_model.maker.fgraph.outputs[0])

On Sat, May 28, 2016, Indranil Sur wrote:
> Function: (prediction function of DBN from https://github.com/lisa-lab/DeepLearningTutorials but with the last layer as linear regression instead of logistic regression)
> `    predict_model = theano.function(
>         inputs=[classifier.x],
>         outputs=classifier.linLayer.y_pred)`
> 
> Output of:
> `theano.printing.debugprint(predict_model)`
> ```
> HostFromGpu [id A] ''   16
>  |GpuElemwise{Add}[(0, 0)] [id B] ''   15
>    |GpuDot22 [id C] ''   14
>    | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id D] ''   13
>    | | |GpuDot22 [id E] ''   12
>    | | | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id F] ''   11
>    | | | | |GpuDot22 [id G] ''   10
>    | | | | | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id H] ''   9
>    | | | | | | |GpuDot22 [id I] ''   8
>    | | | | | | | |GpuElemwise{Composite{scalar_sigmoid((i0 + i1))}}[(0, 0)] [id J] ''   7
>    | | | | | | | | |GpuDot22 [id K] ''   6
>    | | | | | | | | | |GpuFromHost [id L] ''   5
>    | | | | | | | | | | |x [id M]
>    | | | | | | | | | |W [id N]
>    | | | | | | | | |GpuDimShuffle{x,0} [id O] ''   4
>    | | | | | | | |   |b [id P]
>    | | | | | | | |W [id Q]
>    | | | | | | |GpuDimShuffle{x,0} [id R] ''   3
>    | | | | | |   |b [id S]
>    | | | | | |W [id T]
>    | | | | |GpuDimShuffle{x,0} [id U] ''   2
>    | | | |   |b [id V]
>    | | | |W [id W]
>    | | |GpuDimShuffle{x,0} [id X] ''   1
>    | |   |b [id Y]
>    | |W [id Z]
>    |GpuDimShuffle{x,0} [id BA] ''   0
>      |b [id BB]
> ```
> 
> whereas ..
> `theano.printing.pprint(predict_model)` gives error:
> ```
> Traceback (most recent call last):
>   File "./predict.py", line 60, in <module>
>     predict()
>   File "./predict.py", line 42, in predict
>     theano.printing.pprint(predict_model)
>   File "$PATH$/Theano/theano/printing.py", line 577, in __call__
>     return self.process(*args)
>   File "$PATH$/Theano/theano/printing.py", line 512, in process
>     if condition(pstate, r):
>   File "$PATH$/Theano/theano/printing.py", line 502, in <lambda>
>     condition = (lambda pstate, r: r.owner is not None and
> AttributeError: 'Function' object has no attribute 'owner'
> ```
> 
> 
> Version: 0.9.0dev1.dev-5e50147375ad507990655cc1a3e990aa4c190549
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Theano/Theano/issues/4559

-- 
Pascal

**Comment by indraforyou** [comment]
Thanks @nouiz @lamblin for taking time to explain it. Sorry for unnecessarily opening a issue. Keep up the good work.
