### ISSUE TITLE
Windows - Error when import theano

### ISSUE THREAD

**Issue by coroner4817** [Theano/Theano#4561]
When I try to import theano, it gives me this error:

```
===============================
c1xx : fatal error C1083: Cannot open: “mod.cu”: No such file or directory
mod.cu

['nvcc', '-shared', '-O3', '--compiler-bindir', 'C:\\Program Files (x86)\\Micros
oft Visual Studio 12.0\\VC\\bin', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m32',
 '-Xcompiler', '-DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEP
RECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-IC:\\Python27\\lib\\site-packages\\t
heano\\sandbox\\cuda', '-IC:\\Python27\\lib\\site-packages\\numpy\\core\\include
', '-IC:\\Python27\\include', '-IC:\\Python27\\lib\\site-packages\\theano\\gof',
 '-o', 'C:\\Users\\wangyingnan\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1
.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.8-32\\cuda_ndarr
ay\\cuda_ndarray.pyd', 'mod.cu', '-LC:\\Python27\\libs', '-LC:\\Python27', '-lcu
blas', '-lpython27', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return st
atus', 2, 'for cmd', 'nvcc -shared -O3 --compiler-bindir C:\\Program Files (x86)
\\Microsoft Visual Studio 12.0\\VC\\bin -Xlinker /DEBUG -D HAVE_ROUND -m32 -Xcom
piler -DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_AP
I=NPY_1_7_API_VERSION,/Zi,/MD -IC:\\Python27\\lib\\site-packages\\theano\\sandbo
x\\cuda -IC:\\Python27\\lib\\site-packages\\numpy\\core\\include -IC:\\Python27\
\include -IC:\\Python27\\lib\\site-packages\\theano\\gof -o C:\\Users\\wangyingn
an\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_M
odel_42_Stepping_7_GenuineIntel-2.7.8-32\\cuda_ndarray\\cuda_ndarray.pyd mod.cu
-LC:\\Python27\\libs -LC:\\Python27 -lcublas -lpython27 -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not availabl
e  (error: cuda unavailable)
```

However, the mod.cu file is located at the C:\Users\XXX\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.8-32\cuda_ndarray\

My theanorc file has:

```
[global]
floatX=float32
device=gpu
mode=FAST_RUN

[blas]
ldflags=-LC:\\openBLAS -lopenblas

[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0

[nvcc]
compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
```

I installed CUDA 7.0 and the GPU is GT540M. It's an old gpu but it should works. Can anyone help me with my case? THX!

**Comment by lamblin** [comment]
Since you have spaces in some of your paths, maybe it will help to put quotation marks around them.

**Comment by masakinakada** [comment]
I have the same error
Having quotation did not solve the problem on win 10.
Could anyone help?

**Comment by coroner4817** [comment]
@masakinakada have you ever changed anything in your registry? In my case, I figured out that I have previously used registry to set the starting directory of the cmd to D drive using autorun. VS will run this autorun before build. Remove that the error is fixed.

**Comment by masakinakada** [comment]
Thank you very much Yingnan,

I do not recall I changed anything in the registry.
Could you tell me which one might cause the error?
I did not change it manually, but some of softwares might change it
automatically...

Again, thank you so much!

**Comment by coroner4817** [comment]
@masakinakada Something like this: http://stackoverflow.com/a/4896002/4812471

**Comment by lamblin** [comment]
Closing as we removed the old GPU back-end.
Now we suggest to use pre-compiled conda packages for Theano and libgpuarray rather than trying to compile it with Visual Studio.

**Comment by masakinakada** [comment]
Thank you very much Yingnan and Pascal!
