### ISSUE TITLE
Can't understand theano grad applied scan outputs behaviour

### ISSUE THREAD

**Issue by seuqaj114** [Theano/Theano#4563]
So I have to code below, and when I apply the grad wrt A everything runs fine and it computes the gradients correctly. However, if I do wrt=i then it gives me a DisconnectedInputError. Why is that, and how can I compute the derivatives with respect to i (or to any output of step, for that matter)?
Thanks!

    def step(i, A):
        return A*i, i
    
    A = T.scalar("A")
    outputs, _ = theano.scan(step, sequences=T.arange(2,6), non_sequences=A)
    res, i = outputs
    grad = T.grad(cost=res[3], wrt=i)
    func = theano.function([A],[grad, res, i])
    
    print func(3.0)

    Traceback (most recent call last):
      File "test.py", line 17, in <module>
        grad = T.grad(cost=res[3], wrt=i)
      File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 545, in grad
        handle_disconnected(elem)
      File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 532, in handle_disconnected
        raise DisconnectedInputError(message)
    theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: for{cpu,scan_fn}.1
    Backtrace when the node is created:
      File "test.py", line 15, in <module>
        outputs, _ = theano.scan(step, sequences=T.arange(2,6), non_sequences=A)

**Comment by lamblin** [comment]
See the discussion at https://groups.google.com/d/topic/theano-users/fh9uYZnFj40/discussion
