### ISSUE TITLE
work is not clear

### ISSUE THREAD

**Issue by aakash1492** [Theano/Theano#4569]
hello 
i  am new to speech recognition.I am working on kaldi. I was searching for machine learning that is building a dictionary by auto correction through machine learning. I am confused whether this Theano is used for this purpose or some thing else, only deep learning is written. what does this mean. ?

**Comment by lamblin** [comment]
This is really not the place for such questions.
If you have generic questions on Theano, please refer to the doc. If you have questions about speech recognition, or Kaldi, I suggest you find a forum on those topics.
