### ISSUE TITLE
Cannot import theano in certain subdirectories with Python3.4

### ISSUE THREAD

**Issue by evanbiederstedt** [Theano/Theano#4572]
Let's say I go to the `public` subdirectory, `~/public`. I open python3.4 in the terminal with `python3'. 

If I try to import theano,

    >>> import theano

I get the following error:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/name/Public/theano.py", line 4, in <module>
    import theano.tensor as T
ImportError: No module named 'theano.tensor'; 'theano' is not a package

```

However, if I am in the home directory, there is no problem. I can execute the following statements without a hitch:

```
>>> import theano
>>> import theano.tensor as T
```

How can I resolve this issue?

**Comment by jfsantos** [comment]
You probably did not install Theano, just cloned the repository to your home directory. If you run `import something` from a directory where you have either  a file called `something.py` or a folder called `something`, Python will import it. Try calling `python setup.py install` from inside the Theano directory first.

**Comment by evanbiederstedt** [comment]
Yes, I resolved this by downloading theano off of github, and specifically running the `setup.py` with python 3.x. I'm still not entirely sure why `import theano.tensor as T` and then ` x = T.vector()` would work without an error from a Jupyter notebook opened within the home directory, but would throw the above error in `public`. 

Thank you for the help. Sorry for bothering---feel free to close. T

**Comment by nouiz** [comment]
It was probably installed before in a place only visible to the current user and not public. Or the PYTHONPATH wasn't set correctly.

**Comment by Erica-Tan** [comment]
I had a similar issue but my problem was because I named my python file theano.py
