### ISSUE TITLE
nvcc STDOUT debug messages on by default.

### ISSUE THREAD

**Issue by dalupus** [Theano/Theano#4579]
Using theano version 0.8.2 on Windows 7 64 it is printing out a debug message for every single class that nvcc compiles.

For instance:
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/dalupus/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/tmpkasnpv/265abc51f7c376c224983485238ff1a5.lib and object C:/Users/dalupus/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.11-64/tmpkasnpv/265abc51f7c376c224983485238ff1a5.exp

Is this logger supposed to be set to DEBUG by default and if so is there a way to suppress them so I don't have to run everything twice (they don't show up the second time)

**Comment by lamblin** [comment]
This should be fixed already in the master.
Can you check?

**Comment by damaha** [comment]
Great! This worked for me. I had the exact same problem.

**Comment by lamblin** [comment]
Thanks for checking!
