### ISSUE TITLE
Theano fails to utilize CUDA with gcc 6.1

### ISSUE THREAD

**Issue by harshhemani** [Theano/Theano#4588]
I was getting large wall of warnings/errors when trying to run theano GPU example (http://deeplearning.net/software/theano/tutorial/using_gpu.html) on archlinux with gcc 6.1 and cuda 7.5 sdk.

Part of wall of warnings/errors:   

        In file included from /home/harsh/anaconda2/include/python2.7/Python.h:8:0,`
                         `from mod.cu:3:
        /home/harsh/anaconda2/include/python2.7/pyconfig.h:1194:0: warning: "_POSIX_C_SOURCE" redefined
         #define _POSIX_C_SOURCE 200112L
         
        In file included from /opt/cuda/bin/..//include/host_config.h:160:0,
                         from /opt/cuda/bin/..//include/cuda_runtime.h:76,
                         from <command-line>:0:
        /usr/include/features.h:225:0: note: this is the location of the previous definition
         # define _POSIX_C_SOURCE 200809L
         
        In file included from /home/harsh/anaconda2/include/python2.7/Python.h:8:0,
                         from mod.cu:3:
        /home/harsh/anaconda2/include/python2.7/pyconfig.h:1216:0: warning: "_XOPEN_SOURCE" redefined
         #define _XOPEN_SOURCE 600
         
        In file included from /opt/cuda/bin/..//include/host_config.h:160:0,
                         from /opt/cuda/bin/..//include/cuda_runtime.h:76,
                         from <command-line>:0:
        /usr/include/features.h:166:0: note: this is the location of the previous definition
         # define _XOPEN_SOURCE 700
         
        /usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include/stddef.h(436): error: identifier "nullptr" is undefined
        /usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include/stddef.h(436): error: expected a ";"
        /usr/include/c++/6.1.1/x86_64-pc-linux-gnu/bits/c++config.h(202): error: expected a ";"
        /usr/include/c++/6.1.1/exception(63): error: expected a ";"
        /usr/include/c++/6.1.1/exception(69): error: expected a ";"
        /usr/include/c++/6.1.1/exception(77): error: expected a ";"
        /usr/include/c++/6.1.1/exception(85): error: expected a ";"
        /usr/include/c++/6.1.1/exception(95): error: expected a "{"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(64): error: expected a "{"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(71): error: namespace "std" has no member "rethrow_exception"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(81): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(83): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(84): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(86): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(88): error: declaration is incompatible with previous "std::current_exception"
        (64): here
        /usr/include/c++/6.1.1/bits/exception_ptr.h(88): error: use of a local type to declare a function
        /usr/include/c++/6.1.1/bits/exception_ptr.h(88): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(89): error: use of a local type to declare a function
        /usr/include/c++/6.1.1/bits/exception_ptr.h(92): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(94): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(97): error: incomplete type is not allowed
        /usr/include/c++/6.1.1/bits/exception_ptr.h(97): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(118): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(128): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(145): error: use of a local type to declare a function
        /usr/include/c++/6.1.1/bits/exception_ptr.h(146): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(149): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(154): error: use of a local type to declare a function
        /usr/include/c++/6.1.1/bits/exception_ptr.h(155): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(158): error: use of a local type to declare a function
        /usr/include/c++/6.1.1/bits/exception_ptr.h(159): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(162): error: use of a local type to declare a function
        /usr/include/c++/6.1.1/bits/exception_ptr.h(163): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(171): error: expected a ";"
        /usr/include/c++/6.1.1/bits/exception_ptr.h(197): error: expected a ";"
        /usr/include/c++/6.1.1/bits/move.h(47): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(71): error: identifier "constexpr" is undefined
        /usr/include/c++/6.1.1/type_traits(71): error: template parameter "_Tp" may not be redeclared in this scope
        /usr/include/c++/6.1.1/type_traits(71): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(72): error: member "std::integral_constant<_Tp, __v>::_Tp" is not a type name
        /usr/include/c++/6.1.1/type_traits(73): error: member "std::integral_constant<_Tp, __v>::_Tp" is not a type name
        /usr/include/c++/6.1.1/type_traits(74): error: identifier "constexpr" is undefined
        /usr/include/c++/6.1.1/type_traits(79): error: identifier "constexpr" is undefined
        /usr/include/c++/6.1.1/type_traits(79): error: "value_type" has already been declared in the current scope
        /usr/include/c++/6.1.1/type_traits(79): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(84): error: identifier "constexpr" is undefined
        /usr/include/c++/6.1.1/type_traits(84): error: "_Tp" is not a function or static data member
        /usr/include/c++/6.1.1/type_traits(93): error: expected a declaration
        /usr/include/c++/6.1.1/type_traits(93): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(126): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(235): error: identifier "char16_t" is undefined
        /usr/include/c++/6.1.1/type_traits(239): error: identifier "char32_t" is undefined
        /usr/include/c++/6.1.1/type_traits(239): error: class "std::__is_integral_helper<<error-type>>" has already been defined
        /usr/include/c++/6.1.1/type_traits(337): error: identifier "__float128" is undefined
        /usr/include/c++/6.1.1/type_traits(453): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(457): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(465): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(469): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(477): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(481): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(489): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(493): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(501): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(505): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(513): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(517): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(525): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(529): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(537): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(541): error: expected a ">"
        /usr/include/c++/6.1.1/type_traits(551): error: namespace "std" has no member "nullptr_t"
        /usr/include/c++/6.1.1/type_traits(572): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(578): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(585): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(592): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(602): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(628): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(738): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(752): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(767): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(777): error: expected a ")"
        /usr/include/c++/6.1.1/type_traits(788): error: an explicit template argument list is not allowed on this declaration
        /usr/include/c++/6.1.1/type_traits(788): error: expected a type specifier
        /usr/include/c++/6.1.1/type_traits(788): error: function returning function is not allowed
        /usr/include/c++/6.1.1/type_traits(788): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(794): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(795): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(825): error: identifier "noexcept" is undefined
        /usr/include/c++/6.1.1/type_traits(825): error: function call is not allowed in a constant expression
        /usr/include/c++/6.1.1/type_traits(825): error: function call is not allowed in a constant expression
        /usr/include/c++/6.1.1/type_traits(825): error: this operator is not allowed in a template argument expression
        /usr/include/c++/6.1.1/type_traits(836): error: an explicit template argument list is not allowed on this declaration
        /usr/include/c++/6.1.1/type_traits(836): error: expected a type specifier
        /usr/include/c++/6.1.1/type_traits(836): error: function returning function is not allowed
        /usr/include/c++/6.1.1/type_traits(836): error: expected a ";"
        /usr/include/c++/6.1.1/type_traits(842): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(843): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)
        /usr/include/c++/6.1.1/type_traits(868): error: function returning function is not allowed
        /usr/include/c++/6.1.1/type_traits(879): error: an explicit template argument list is not allowed on this declaration
        Error limit reached.
        100 errors detected in the compilation of "/tmp/tmpxft_0000312f_00000000-9_mod.cpp1.ii".
        Compilation terminated.

        ['nvcc', '-shared', '-O3', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/harsh/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray', '-I/home/harsh/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda', '-I/home/harsh/anaconda2/lib/python2.7/site-packages/numpy/core/include', '-I/home/harsh/anaconda2/include/python2.7', '-I/home/harsh/anaconda2/lib/python2.7/site-packages/theano/gof', '-o', '/home/harsh/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/home/harsh/anaconda2/lib', '-lcublas', '-lpython2.7', '-lcudart']
        ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 4, 'for cmd', 'nvcc -shared -O3 -m64 -Xcompiler -DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/harsh/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray -I/home/harsh/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda -I/home/harsh/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/harsh/anaconda2/include/python2.7 -I/home/harsh/anaconda2/lib/python2.7/site-packages/theano/gof -o /home/harsh/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/home/harsh/anaconda2/lib -lcublas -lpython2.7 -lcudart')
Complete error: [http://pastebin.com/Kyb2zfAp](http://pastebin.com/Kyb2zfAp)

I found out that its an issue with CUDA that it doesn't support gcc > 4.8. 
I also found a workaround to this here: https://bugs.archlinux.org/task/49272.
It involves passing compiler option `-std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO` to `nvcc`

In order to do this, i needed to add the following line to `theano/sandbox/cuda/nvcc_compiler.py` after line [306](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/nvcc_compiler.py#L306):
`cmd.extend(['-std=c++11', '-Xcompiler', '-D__CORRECT_ISO_CPP11_MATH_H_PROTO'])`

Although everything seems to be working fine till now, I was concerned that this change might introduce some other issue. Is this change correct? Should I be submitting a PR?

**Comment by nouiz** [comment]
Instead of modifing Theano, can you try to pass this Theano flag:
"nvcc.flags=-std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO"

If this work, it would be great to add this somewhere in the doc, but we
are in the mid of big doc changes.

Can you confirm that without changing theano (to test it well, you should
delete your Theano cache) and using this flag, it fix it?

**Comment by harshhemani** [comment]
Tried running with
`THEANO_FLAGS="nvcc.flags=-std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO"`
failed with error: `gcc: error: unrecognized command line option ‘-Xcompiler’; did you mean ‘--compile’?`

Then I tried running with
`THEANO_FLAGS="nvcc.flags=-std=c++11 -D__CORRECT_ISO_CPP11_MATH_H_PROTO"` 

and it runs successfully. 

Thanks.

**Comment by bigeagle** [comment]
Hi there,

I was suffering from the same issue. However, setting neither `THEANO_FLAGS="nvcc.flags=-std=c++11 -D__CORRECT_ISO_CPP11_MATH_H_PROTO"` nor `THEANO_FLAGS="nvcc.flags=-std=c++11 -Xcompiler -D__CORRECT_ISO_CPP11_MATH_H_PROTO"` does not solve the problem.
The error message is 
```
Compilation terminated.

['nvcc', '-shared', '-O3', '-m64', '-Xcompiler', '-std=c++11,-D__CORRECT_ISO_CPP11_MATH_H_PROTO,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden', '-Xlinker', '-rpath,/home/athena/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray', '-I/home/athena/.local/lib/python2.7/site-packages/theano/sandbox/cuda', '-I/usr/lib/python2.7/site-packages/numpy/core/include', '-I/usr/include/python2.7', '-I/home/athena/.local/lib/python2.7/site-packages/theano/gof', '-o', '/home/athena/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray/cuda_ndarray.so', 'mod.cu', '-L/usr/lib', '-lcublas', '-lpython2.7', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 4, 'for cmd', 'nvcc -shared -O3 -m64 -Xcompiler -std=c++11,-D__CORRECT_ISO_CPP11_MATH_H_PROTO,-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,-fPIC,-fvisibility=hidden -Xlinker -rpath,/home/athena/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray -I/home/athena/.local/lib/python2.7/site-packages/theano/sandbox/cuda -I/usr/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -I/home/athena/.local/lib/python2.7/site-packages/theano/gof -o /home/athena/.theano/compiledir_Linux-4.5--ARCH-x86_64-with-glibc2.2.5--2.7.11-64/cuda_ndarray/cuda_ndarray.so mod.cu -L/usr/lib -lcublas -lpython2.7 -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
```

Cheers,

**Comment by abergeron** [comment]
I would like to point out that nvcc 7.5 does *not* support gcc 6.1 and while there may be some workarounds to make it work, we aren't in the business to make it work.

You are on your own here.
