### ISSUE TITLE
Indexing subtensor with a Boolean mask

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#4595]
In Numpy it is possible to index arrays with a Boolean mask. 
This allows, e.g., this kind of operation:
```python
import numpy as np
my_array = np.array([1, 42, 6])
my_array[my_array == 42] = 0  # my_array --> [1, 0, 6]
```

At the moment Theano not only does not allow this kind of indexing, but also fails silently, considering the boolean mask as 0/1 indexing.

As discussed with @lamblin, part of the problem originates from the fact that Theano has no Boolean type. I think we should either support Boolean mask indexing implicitly when the indices are `int8` (and have the same length as the tensor?) or at least raise an error with the option to suppress it setting a flag.

**Comment by nouiz** [comment]
I would make Theano raise an error everywhere it get a numpy bool and ask
the user to convert it explicitly. This way, when/if we add support for it,
it won't break code. This could be done in TensorType.filter I think.

**Comment by lamblin** [comment]
@nouiz I'm not sure what exactly you mean by that. I don't think that things like `x > 0`, where `x` is a tensor, should raise errors. We should continue using `int8` for that.
However, we could make *indexing* with int8 arrays raise an exception by default, so that `y[x > 0]` does not do the wrong thing.

**Comment by nouiz** [comment]
I agree with what you tell. I mean that this should raise an error too:

>>> import theano
>>> import numpy as np
>>> m=theano.tensor.matrix()
>>> m[np.random.rand(5)>0.5]
AdvancedSubtensor1.0
>>> theano.printing.debugprint(m[np.random.rand(5)>0.5], print_type=True)
AdvancedSubtensor1 [id A] <TensorType(float64, matrix)> ''
 |<TensorType(float64, matrix)> [id B] <TensorType(float64, matrix)>
 |TensorConstant{[1 0 0 1 1]} [id C] <TensorType(uint8, vector)>

Here we create a TensorConstant()

**Comment by fvisin** [comment]
@SinaHonari in response to your email, we don't need an optimization here. As Fred suggested you can do the check directly inside [TensorType.filter](https://github.com/Theano/Theano/blob/9bf778f89da28ab418cfc6395827c827053dd95a/theano/tensor/type.py#L74).

**Comment by fvisin** [comment]
After looking into it more carefully, I am not sure `TensorType.filter` is the right place to put this check.
It looks like that's the code to check the *numerical value* that is being assigned to a tensor. What we care about is the *index* of the subtensor, which doesn't seem to be available in `filter`. 

I would check if `entry` is an `uint8` inside [SubTensor.convert](https://github.com/Theano/Theano/blob/9bf778f89da28ab418cfc6395827c827053dd95a/theano/tensor/subtensor.py#L334) and raise an error in that case.

@nouiz or @lamblin can you please comment on this? Thanks!

**Comment by fvisin** [comment]
@abergeron suggested to put the check [here](https://github.com/Theano/Theano/blob/b5018dbad0146b59b08af2da2692ba190abaf592/theano/tensor/var.py#L468).

**Comment by fvisin** [comment]
@SinaHonari please don't forget to do the pull request with the code we came up with yesterday. I'd like to discuss the test errors with the other guys here while you are away. When you do, please reference this issue so we get the notification. Thank you!

**Comment by SinaHonari** [comment]
@fvisin sorry for the late response. I got busy since I left you on Thursday and could not get back to it. I cannot also do anything during these two weeks. Sorry for that. I made a pull request with the latest changes and let Travis check what might go wrong. We can then fix the issues that will be raised. Thank you!

**Comment by fvisin** [comment]
@SinaHonari no problem, thank you for committing the code so we can begin to look into the errors. Enjoy your vacation!

**Comment by lamblin** [comment]
Closed by #4750

**Comment by prithagupta** [comment]
Masked array: 
[[ True False  True False  True  True]
 [False  True  True False False  True]
 [ True False False  True  True  True]
 [False False False  True  True  True]
 [ True  True False  True False False]]
TO apply on 2d tensor of values:
[[3 3 1 1 2 2]
 [1 3 2 3 4 1]
 [2 4 1 2 4 1]
 [1 3 1 2 3 3]
 [1 2 4 2 4 3]]

Resulting masked tensor:
[[-- 3 -- 1 -- --]
 [1 -- -- 3 4 --]
 [-- 4 1 -- -- --]
 [1 3 1 -- -- --]
 [-- -- 4 -- 4 3]]

Is this possible in theano

**Comment by lamblin** [comment]
Closed tickets are not the right place to ask if features are implemented.
Please use stackoverflow or theano-users.

Btw, the following is possible, but since you seem to select on `False` values rather than `True`, you need to invert the mask first:
```
>>> values[~mask].eval({values: <your values>, mask: <your mask>})
array([3, 1, 1, 3, 4, 4, 1, 1, 3, 1, 4, 4, 3])
```
This may be slow on GPU though.
