### ISSUE TITLE
Remove the name parameter to reshape op

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4601]
I don't know any other op that have that. I think it should be on the variable and not the op. So this is clean up of old stuff. Check the GPU op and gpu opt, as they handle it.

**Comment by EugenePY** [comment]
Hi! I would like to work on this. Do you mean just remove the name parameter of reshape? I can also check other op.

**Comment by nouiz** [comment]
I think it is only this op that have this. So no need to check the other
ops. Yes, remove the name, but it will probably request some small
adjustment where it is used to remove it.

thanks
