### ISSUE TITLE
Maximum Recursion Depth error while using Keras.model.fit

### ISSUE THREAD

**Issue by nitish11** [Theano/Theano#4602]
I am running a deep net model on Keras code. The training model was running perfectly fne on image size 76*76, but it not working on image dimension 128*128.

I got the below error :

  <i>File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 4262, in get_num_denum
    pairs = [self.get_num_denum(input2) for input2 in parent.inputs]
RuntimeError: maximum recursion depth exceeded

if isinstance(c, graph.Constant) and (len(c.clients) <= 1):
RuntimeError: ('maximum recursion depth exceeded while calling a Python object', 'Please, report this to theano-dev mailing list. As a temporary work around, you can raise Python stack limit with: import sys; sys.setrecursionlimit(10000)')</i>

I am using a GPU machine (NVIDIA GF110GL [Tesla M2075]) with fairly good configuration. I don't want to proceed with temporary work-around because in that case, the code is getting stuck before training. Kindly suggest some better way to handle this issue.

**Comment by nitish11** [comment]
The Keras build used is from the below URL : https://github.com/fchollet/keras/tree/d6e33ce5558169de2c85bad5360609323cdc44c5

The Model architecture can be found in the below gist.

https://gist.github.com/nitish11/d1e90390a5cc203e9e7a493a9e1d85e9

**Comment by nouiz** [comment]
This was already answered at: https://github.com/fchollet/keras/issues/2931#issuecomment-224504851

Don't open multiple issue. If you do, link them.

**Comment by nitish11** [comment]
Hi @nouiz,

thanks for the reply. 

Kindly reply the updated comment at [issue](https://github.com/fchollet/keras/issues/2931).

**Comment by simonhughes22** [comment]
For me the problem was using a RNN with unroll=True when constructing the RNN layer, and then getting this error on model.fit. Posting here incase someone else encounters this specific issue. None of the other suggestions helped, so I tinkered with the code.
