### ISSUE TITLE
Different (forward convolution) results obtained by Theano and CuDNN

### ISSUE THREAD

**Issue by daothanhtuan** [Theano/Theano#4603]
Using the same input, I compare the output values of feature maps between Theano wrapper "dnn_conv" and direct use of cudnn "cudnnConvolutionForward".
The two functions looks like these:

conv_out = dnn.dnn_conv(img=input_shuffled,
                                        kerns=W_shuffled,
                                        subsample=(convstride, convstride),
                                        border_mode=padsize,
                                        conv_mode='cross',
                                        algo='none'
                                        )

checkCUDNN(cudnnConvolutionForward(cudnnHandle, &alpha, dataTensor,
                                           data, conv1filterDesc, pconv1, conv1Desc,
                                           conv1algo, workspace, m_workspaceSize, &beta,
                                           conv1Tensor, conv1));

I matched all possible parameters (convolution type, filter size, depth, alpha=1, beta=0, float32). However there is a slight difference for each output, which looks something like this:

```
cuDNN:
26.6941 26.7009 27.175 27.1285
``` 

```
Theano:
26.66 26.6666 27.1405 27.0936
```

Please note that I made sure the input of the two functions are exactly the same. I wonder what could be the reason and how would I modify Theano parameters to get the same results as cuDnn?

Thanks

**Comment by nouiz** [comment]
The algo 'none' for the forward isn't the default one. So this could explain it. There can be small numerical difference between the different cudnn algo.

**Comment by daothanhtuan** [comment]
I checked all possible types of algo. They won't make such a big difference.

**Comment by daothanhtuan** [comment]
I have checked it again and it turned out that it was my mistake to get the wrong output. It seems the difference caused by the algo are always within very small range. Thanks for the help though.
