### ISSUE TITLE
Error while implementing keras with theano backend

### ISSUE THREAD

**Issue by adityajumde** [Theano/Theano#4609]
Anaconda for python -2.7
Windows 7 - 64 bit Intel core i7

Exception: ('The following error happened while compiling the node', DotModulo(A, s, m, A2, s2, m2), '\n', 'Compilation failed (return status=1): C:\\Users\\ajumde\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_78_Stepping_3_GenuineIntel-2.7.11-64\\tmppfmji0\\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in\r.  #include <Python.h>\r.  ^\r. ', '[DotModulo(A, s, m, A2, s2, m2)]')

**Comment by nouiz** [comment]
I have replied on the user mainling list about this. Don't duplicate questions. We keep issue for feature request and bug. This is a problem in your environment, so I let the discussion continue on the mailing list.
