### ISSUE TITLE
Theano doesn't work after unpdating

### ISSUE THREAD

**Issue by heipangpang** [Theano/Theano#4623]
I updated my theano to the version 0.8.2 in Ubuntu 14.04, after that it always get the warning:
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '22446' (I am process '22484').
Then it killed python by itself. Do you have any idea about that?

**Comment by nouiz** [comment]
Can you delete your Theano cache? If that don't fix it, try the development
version of Theano:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

**Comment by heipangpang** [comment]
I have already deleted my Theano cache, I will try the develpment version.

**Comment by heipangpang** [comment]
@nouiz I can import theano now, but it got another error when I try theano.test().
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu. And how to deal with that ?

**Comment by nouiz** [comment]
Give the full error message.

**Comment by heipangpang** [comment]
Hi, I reboot the machine and it works now. But there's another problem is that when I use THEANO_FLAGS='floatX=float32,device=gpu0,lib.cnmem=1' python, it cannot import lasagne, and give  me the error:
Traceback (most recent call last):
  File "ttt.py", line 17, in <module>
    import lasagne
  File "/usr/local/lib/python2.7/dist-packages/lasagne/__init__.py", line 24, in <module>
    from . import nonlinearities

However, it works when I try the code 
'import theano.sandbox.cuda
theano.sandbox.cuda.use('gpu0')'.

Do you have any ideas about that?

Thank you very much.
