### ISSUE TITLE
Use issue and PR template

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4625]
https://github.com/blog/2111-issue-and-pull-request-templates

This will help lower the question in issue instead of mailing list.

**Comment by lamblin** [comment]
Fixed by #4952.

**Comment by Sentient07** [comment]
In the template, if someone is wanting to report a bug/issue with their cuda version or problem with using CUDNN with theano, I think it would be nice if we ask people for outputs like nvidia-smi, nvcc -V, GCC version, if cuddn.h is present, it's location, `$DYLIB_LIBRARY_PATH` ( and its counter part), which we end up doing it manually most of the time. Would that be fine ?

**Comment by nouiz** [comment]
nvcc version and gcc/(clang on mac) version are good idea.

Otherwise, it it too specific. We don't want that page to be too long,
otherwise people won't read it.
