### ISSUE TITLE
Theano fails to compile Logistic regression example using CUDA 7.0 on GPU

### ISSUE THREAD

**Issue by jhimlimitra** [Theano/Theano#4626]
Hi,
   I have been trying to make theano (tried both 0.8.2 and 0.9) work on hpc and on a gpu. Theano seems to work for all examples on the cpu but not for gpu. I do not have root access but the cuda version 7.0 is  installed in /usr/local/cuda-7.0. The CUDA root path is set and LD_LIBRARY_PATH points to /usr/local/cuda-7.0/lib64. 

The basic example that checks whether Theano uses gpu or cpu is working without errors, but the one with logistic regression is not working and is throwing compilation error. It shows a g++ compilation issue even after trying out different suggestions from various blogs.

Any help on this will be highly appreciated. The error is as follows:

Problem occurred during compilation with the command line below:
/usr/local/gcc/4.9.3/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -W                 no-unused-variable -Wno-write-strings -lpython2.7 -lpthread -ldl -lutil -lm -Xli                 nker -export-dynamic -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3                  -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lw                 p -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1                  -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno                 -adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx                 512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --                 param l2-cache-size=25600 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VER                 SION -m64 -fPIC -I/home/jxm877/anaconda2/lib/python2.7/site-packages/numpy/core/                 include -I/home/jxm877/anaconda2/include/python2.7 -I/home/jxm877/anaconda2/lib/                 python2.7/site-packages/theano/gof -fvisibility=hidden -o /home/jxm877/.theano/c                 ompiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/                 tmpBl2pNe/54baef0193e0acaee27bdf77b9d25da0.so /home/jxm877/.theano/compiledir_Li                 nux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/tmpBl2pNe/mo                 d.cpp -L/home/jxm877/anaconda2/lib -lpython2.7
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s: Assembler messages:
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1553: Error: suffix or operands invalid for                  `vpand'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1554: Error: suffix or operands invalid for                  `vpshufb'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1555: Error: suffix or operands invalid for                  `vpand'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1556: Error: suffix or operands invalid for                  `vpshufb'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1557: Error: suffix or operands invalid for                  `vpor'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1559: Error: no such instruction: `vpermq $2                 16,%ymm1,%ymm1'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1560: Error: suffix or operands invalid for                  `vpand'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1561: Error: suffix or operands invalid for                  `vpshufb'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1562: Error: suffix or operands invalid for                  `vpshufb'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1563: Error: suffix or operands invalid for                  `vpand'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1564: Error: suffix or operands invalid for                  `vpshufb'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1565: Error: suffix or operands invalid for                  `vpor'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1566: Error: no such instruction: `vpermq $2                 16,%ymm0,%ymm0'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1567: Error: suffix or operands invalid for                  `vpshufb'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1568: Error: suffix or operands invalid for                  `vpor'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1569: Error: no such instruction: `vpermq $2                 16,%ymm0,%ymm0'
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1847: Error: no such instruction: `vinserti1                 28 $0x1,%xmm0,%ymm1,%ymm0'

Traceback (most recent call last):
  File "expy.py", line 32, in <module>
    name = "train")
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/functi                 on.py", line 322, in function
    output_keys=output_keys)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.                 py", line 480, in pfunc
    output_keys=output_keys)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/functi                 on_module.py", line 1828, in orig_function
    defaults)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/functi                 on_module.py", line 1692, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/link.py",                  line 693, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py", li                 ne 1034, in make_all
    no_recycling))
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", li                 ne 969, in make_thunk
    no_recycling)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", li                 ne 872, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1591, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py                 ", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1502, in compile_cmodule
    preargs=preargs)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py                 ", line 2204, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Elemwise{gt                 ,no_inplace}(HostFromGpu.0, TensorConstant{(1,) of 0.5}), '\n', "Compilation fai                 led (return status=1): /tmp/pbsjobs.1029932.hpc/cclYW4f6.s: Assembler messages:.                  /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1553: Error: suffix or operands invalid for                  `vpand'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1554: Error: suffix or operands in                 valid for `vpshufb'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1555: Error: suffix or                  operands invalid for `vpand'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1556: Error: s                 uffix or operands invalid for `vpshufb'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:155                 7: Error: suffix or operands invalid for `vpor'. /tmp/pbsjobs.1029932.hpc/cclYW4                 f6.s:1559: Error: no such instruction: `vpermq $216,%ymm1,%ymm1'. /tmp/pbsjobs.1                 029932.hpc/cclYW4f6.s:1560: Error: suffix or operands invalid for `vpand'. /tmp/                 pbsjobs.1029932.hpc/cclYW4f6.s:1561: Error: suffix or operands invalid for `vpsh                 ufb'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1562: Error: suffix or operands invali                 d for `vpshufb'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1563: Error: suffix or oper                 ands invalid for `vpand'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1564: Error: suffi                 x or operands invalid for `vpshufb'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1565: E                 rror: suffix or operands invalid for `vpor'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s                 :1566: Error: no such instruction: `vpermq $216,%ymm0,%ymm0'. /tmp/pbsjobs.10299                 32.hpc/cclYW4f6.s:1567: Error: suffix or operands invalid for `vpshufb'. /tmp/pb                 sjobs.1029932.hpc/cclYW4f6.s:1568: Error: suffix or operands invalid for `vpor'.                  /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1569: Error: no such instruction: `vpermq $                 216,%ymm0,%ymm0'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1847: Error: no such instr                 uction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'. ", '[Elemwise{gt,no_inplace}(<Tens                 orType(float32, vector)>, TensorConstant{(1,) of 0.5})]')
[jxm877@gpu025t ~]$ Problem occurred during compilation with the command line below:
           include -I/home/jxm877/anaconda2/include/python2.7 -I/home/jxm877/anaconda2/lib/                 python2.7/site-packages/theano/gof -fvisibility=hidden -o /home/jxm877/.theano/c                 ompiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/                 tmpBl2pNe/54baef0193e0acaee27bdf77b9d25da0.so /home/jxm877/.theano/compiledir_Li                 nux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/tmpBl2pNe/mo                 d.cpp -L/home/jxm877/anaconda2/lib -lpython2.7
/tmp/pbsjobs.1029932.hpc/cclYW4f6.s: Assembler messages:
bash: Problem: command not found
[jxm877@gpu025t ~]$ /usr/local/gcc/4.9.3/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -W                 no-unused-variable -Wno-write-strings -lpython2.7 -lpthread -ldl -lutil -lm -Xli                 nker -export-dynamic -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3                  -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lw                 p -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1                  -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno                 -adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx                 512pf -mno-prefetchwt1 --param l1-cache-size=32 --param l1-cache-line-size=64 --                 param l2-cache-size=25600 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VER                 SION -m64 -fPIC -I/home/jxm877/anaconda2/lib/python2.7/site-packages/numpy/core/                 include -I/home/jxm877/anaconda2/include/python2.7 -I/home/jxm877/anaconda2/lib/                 python2.7/site-packages/theano/gof -fvisibility=hidden -o /home/jxm877/.theano/c                 ompiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/                 tmpBl2pNe/54baef0193e0acaee27bdf77b9d25da0.so /home/jxm877/.theano/compiledir_Li                 nux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/tmpBl2pNe/mo                 d.cpp -L/home/jxm877/anaconda2/lib -lpython2.7
g++: error: no-unused-variable: No such file or directory
g++: error: nker: No such file or directory
g++: error: p: No such file or directory
g++: error: 512pf: No such file or directory
g++: error: param: No such file or directory
g++: error: l2-cache-size=25600: No such file or directory
g++: error: SION: No such file or directory
g++: error: include: No such file or directory
g++: error: python2.7/site-packages/theano/gof: No such file or directory
g++: error: ompiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/: No such file or directory
g++: error: tmpBl2pNe/54baef0193e0acaee27bdf77b9d25da0.so: No such file or directory
g++: error: /home/jxm877/.theano/compiledir_Li: No such file or directory
g++: error: nux-2.6-el6.x86_64-x86_64-with-redhat-6.6-Santiago-x86_64-2.7.11-64/tmpBl2pNe/mo: No such file or directory
g++: error: d.cpp: No such file or directory
g++: error: unrecognized command line option ‘-Xli’
g++: error: unrecognized command line option ‘-mno-lw’
g++: error: unrecognized command line option ‘-mno’
g++: error: unrecognized command line option ‘-adx’
g++: error: unrecognized command line option ‘--’
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s: Assembler messages:
bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:: No such file or directory
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1553: Error: suffix or operands invalid for                  `vpand'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1554: Error: suffix or operands invalid for                  `vpshufb'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1555: Error: suffix or operands invalid for                  `vpand'
    keep_lock=keep_lock)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1591, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cmobash: command substitution: line 1: unexpected EOF while looking for matching `''
dule.py       bash: command substitution: line 3: syntax error: unexpected end of file
          ", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1502, in compile_cmodule
    preargs=preargs)
  File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py                 ", line 2204, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Elemwise{gt                 ,no_inplace}(HostFromGpu.0, TensorConstant{(1,) of 0.5}), '\n', "Compilation fai                 led (return status=1): /tmp/pbsjobs.1029932.hpc/cclYW4f6.s: Assembler messages:.      bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1553:: No such file or directory
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1556: Error: suffix or operands invalid for                  `vpshufb'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1557: Error: suffix or operands invalid for                  `vpor'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1559: Error: no such instruction: `vpermq $2                 16,%ymm1,%ymm1'
`
bash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 3: syntax error: unexpected end of file
bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1556:: No such file or directory
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1560: Error: suffix or operands invalid for                  `vpand'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1561: Error: suffix or operands invalid for                  `vpshufb'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1562: Error: suffix or operands invalid for                  `vpshufb'
bash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 3: syntax error: unexpected end of file
bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1560:: No such file or directory
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1563: Error: suffix or operands invalid for                  `vpand'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1564: Error: suffix or operands invalid for                  `vpshufb'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1565: Error: suffix or operands invalid for                  `vpor'
bash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 3: syntax error: unexpected end of file
bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1563:: No such file or directory
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1566: Error: no such instruction: `vpermq $2                 16,%ymm0,%ymm0'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1567: Error: suffix or operands invalid for                  `vpshufb'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1568: Error: suffix or operands invalid for                  `vpor'
bash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 3: syntax error: unexpected end of file
bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1566:: No such file or directory
[jxm877@gpu025t ~]$ /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1569: Error: no such instruction: `vpermq $2                 16,%ymm0,%ymm0'
> /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1847: Error: no such instruction: `vinserti1                 28 $0x1,%xmm0,%ymm1,%ymm0'
>
> Traceback (most recent call last):
>   File "expy.py", line 32, in <module>
>     name = "train")
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/functi                 on.py", line 322, in function
>     output_keys=output_keys)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.                 py", line 480, in pfunc
>     output_keys=output_keys)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/functi                 on_module.py", line 1828, in orig_function
>     defaults)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/compile/functi                 on_module.py", line 1692, in create
>     input_storage=input_storage_lists, storage_map=storage_map)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/link.py",                  line 693, in make_thunk
>     storage_map=storage_map)[:3]
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py", li                 ne 1034, in make_all
>     no_recycling))
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", li                 ne 969, in make_thunk
>     no_recycling)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", li                 ne 872, in make_c_thunk
>     output_storage=node_output_storage)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1200, in make_thunk
>     keep_lock=keep_lock)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1143, in __compile__
>     keep_lock=keep_lock)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1591, in cthunk_factory
>     key=key, lnk=self, keep_lock=keep_lock)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py                 ", line 1142, in module_from_key
>     module = lnk.compile_cmodule(location)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", li                 ne 1502, in compile_cmodule
>     preargs=preargs)
>   File "/home/jxm877/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py                 ", line 2204, in compile_str
>     (status, compile_stderr.replace('\n', '. ')))
> Exception: ('The following error happened while compiling the node', Elemwise{gt                 ,no_inplace}(HostFromGpu.0, TensorConstant{(1,) of 0.5}), '\n', "Compilation fai                 led (return status=1): /tmp/pbsjobs.1029932.hpc/cclYW4f6.s: Assembler messages:.                  /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1553: Error: suffix or operands invalid for                  `vpand'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1554: Error: suffix or operands in                 valid for `vpshufb'. /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1555: Error: suffix or                  operands invalid for `
bash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 3: syntax error: unexpected end of file
bash: command substitution: line 1: unexpected EOF while looking for matching `''
bash: command substitution: line 2: syntax error: unexpected end of file
bash: /tmp/pbsjobs.1029932.hpc/cclYW4f6.s:1569:: No such file or directory

**Comment by nouiz** [comment]
We merged yesterday some code in the development branch that could help.
Can you try Theano github version?

Fred

**Comment by jhimlimitra** [comment]
Hi Fred,
    Thanks for your time on reading through the extensive error messages. I managed to solve the issue. 
Apparently, Cuda 7.0 in RHEL 6.x version only works with gcc/g++ 4.4.7, which comes by default with RHEL. My system however had different other gcc versions and the Anaconda version was gcc/g++ 4.8.5. The work around was deleting the the /home/jxm877/anaconda2/bin/gcc and creating the symlink:
ln -s /usr/bin/gcc /home/jxm877/anaconda2/bin/gcc

Same goes for g++.
ln -s /usr/bin/g++ /home/jxm877/anaconda2/bin/g++
This worked like magic. I am able to compile and run Theano successfully as well as DeepMedic that uses Theano.

Thanks,
Jhimli

**Comment by nouiz** [comment]
great, so I'm closing this issue.
