### ISSUE TITLE
Bitwise "and" and "or" broken

### ISSUE THREAD

**Issue by MaigoAkisame** [Theano/Theano#4633]
I've found that the bitwise "and" and "or" operators do not function correctly on Theano 0.8.0 and 0.8.2:

```
>>> import theano, theano.tensor as T
>>> theano.function([], T.and_(5,6))()
array(6, dtype=int8)    # Should be 4
>>> theano.function([], T.or_(5,6))()
array(1, dtype=int8)    # Should be 7
```

I've tried several other pairs of values. It appears that "T.or_" is performing a logical instead of bitwise operation, outputting 0 if both operands are zero and 1 otherwise. "T.and_" outputs 0 if either operand is zero, and the second operand otherwise.

By the way, "and_" and "or_" are indeed intended as bitwise (not logical) operators, because they have the aliases "bitwise_and" and "bitwise_or".

However, the following is correct:

```
>>> theano.function([], theano.scalar.and_(5,6))()
4
>>> theano.function([], theano.scalar.or_(5,6))()
7
```

The bug did not exist in Theano 0.7.0.

**Comment by lamblin** [comment]
To make things even more confusing:
```
>>> theano.tensor.CAReduce(theano.scalar.and_)([5, 6]).eval()
array(4)
>>> theano.tensor.CAReduce(theano.scalar.or_)([5, 6]).eval()
array(7)
```

**Comment by lamblin** [comment]
The issue is `local_useless_elemwise`, which should only perform some simplifications on `AND` and `OR` if they are the Boolean version.
