### ISSUE TITLE
A suggestion for the implementation of matrix update

### ISSUE THREAD

**Issue by OlafLee** [Theano/Theano#4636]
I find it take much time to update a big matrix even if I just update a few rows, for instance, word embedding matrix. If there is a way to update only the changed rows or columns, it will be much more efficient.

**Comment by nouiz** [comment]
This should answer your question:

http://deeplearning.net/software/theano/tutorial/faq_tutorial.html?highlight=inc_subtensor#how-to-update-a-subset-of-weights

It tell how to implement that efficiently in Theano.

**Comment by OlafLee** [comment]
Thank you, Fred.

**Comment by OlafLee** [comment]
@nouiz I found a problem with his method. If I use a index matrix to get the vectors from a word embedding matrix and calculate the grad. I can't use it with inc_subtensor. The error information is Trying to increment a 2-dimensional subtensor with a 3-dimensional value. Is there any way for this?

**Comment by OlafLee** [comment]
There is a problem when I use an imatrix to update the corresponding embedding rows. For example, 
`import theano
import theano.tensor as T

import numpy as np

x = np.random.random((10,10))

emb = theano.shared(x)

y = T.imatrix()

z = emb[y]

sum = z.sum()

grads = T.grad(sum,z)


updates = T.set_subtensor(z, z+grads)

updates = [(emb,updates)]

fun = theano.function([y],sum,updates=updates, allow_input_downcast=True)

c = np.array([[1,2],[3,2]])

print fun(c)`

There would be an error ValueError: array is not broadcastable to correct shape

**Comment by OlafLee** [comment]
@nouiz 
There is a problem when I use an imatrix to update the corresponding embedding rows. For example, 
`import theano
import theano.tensor as T

import numpy as np

x = np.random.random((10,10))

emb = theano.shared(x)

y = T.imatrix()

z = emb[y]

sum = z.sum()

grads = T.grad(sum,z)

updates = T.set_subtensor(z, z+grads)

updates = [(emb,updates)]

fun = theano.function([y],sum,updates=updates, allow_input_downcast=True)

c = np.array([[1,2],[3,2]])

print fun(c)`

There would be an error ValueError: array is not broadcastable to correct shape

**Comment by nouiz** [comment]
We merged a fix in gh-4678. thanks for the report.

**Comment by OlafLee** [comment]
@nouiz  Thank you Fred.
