### ISSUE TITLE
Redo Windows Installation instruction

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4643]
We need to update Windows Installation instruction. Especially with GPU.

This link could help:

https://www.reddit.com/r/MachineLearning/comments/3hkv2b/most_recent_way_to_install_theano_for_windows_10/

We probably need to wait for the PR https://github.com/Theano/Theano/pull/4211 to be done before.

**Comment by f0k** [comment]
This could also help: https://github.com/Lasagne/Lasagne/wiki/From-Zero-to-Lasagne-on-Windows-7-(64-bit)

**Comment by slefrancois** [comment]
Also with regard to Canopy and Enthough Python, they have been merged, but the instructions still treat them as separate.
