### ISSUE TITLE
Uncanonicalize DimShuffle inside Alloc, Reshape and Subtensor

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4647]
We need to explicitly make put in the graph DimShuffle for canonicalization.

But we should merge them in the Alloc, Reshape and Subtensor that do it itself. This make the graph smaller and lower the overhead.
- [x] Alloc(DimShuffle(x), ...) - > Alloc(x, ...) when the dimshuffle just add dimensions at the left.
- [x] Reshape(Dimshuffle(x), shp) -> Reshape(x, shp) when the dimshuffle just add dimsions (anywhere) and don't change the order of dimensions.
- [x]  Subtensor
  
  some_col[i].dimshuffle() => some_col[i, 0], or
  x[i:j, :, k:l].dimshuffle(0, 2) => x[i:j, 0, k:l] if x.broadcastable == (False, True, False).
  
  In general, when a dimshuffle only removes broadcastable dimensions that were kept intact by the subtensor, we can index by 0 on those dimensions instead.
  Register this in canonicalize.

**Comment by olimastro** [comment]
should be in the file theano/tensor/opt_uncanonicalize.py.

If you can only partially remove the DimShuffle, don't remove it. It is useless.

**Comment by lamblin** [comment]
For the subtensor case, the following could be done:
- `some_col[i].dimshuffle() => some_col[i, 0]`, or
- `x[i:j, :, k:l].dimshuffle(0, 2) => x[i:j, 0, k:l]` if `x.broadcastable == (False, True, False)`.
In general, when a dimshuffle only removes broadcastable dimensions that were kept intact by the subtensor, we can index by 0 on those dimensions instead.

**Comment by nouiz** [comment]
Do we have a canonicalization opt that will add those dimshuffles? I don't
think so(and didn't find in a quick search in tensor/opt.py). I don't think
we should make one as this will probably break many other optimization that
are related to subtensors like subtensor_make_vector,
local_subtensor_merge, local_subtensor_of_alloc (maybe others, I stopped
the search).

I think the canonical form to help other optimizations to be easier to
implement would be for now what you suggest. Not an uncanolicalize form.
Doing the reverse would help merge some dimshuffles, but would make at
least a few optimizations more complicated. I'm not sure it is a good gain
to merge DimShuffle. In particular as we didn't see real gain in real life.

I would suggest your dimshuffle(subtensor()) -> subtensor opt at the
canonical phase for now. If later we see a need for the reverse, we could
move the opt to the uncanonical phase and upgrades the other opt. So no
work will be lost and we will have a more canonical phase compared to the
current state.

In all cases, do this one after the 2 others are completly done.

**Comment by lamblin** [comment]
> Do we have a canonicalization opt that will add those dimshuffles?

- We have a canonicalization opt that replaces subtensor with dimshuffles (see #4162, #4356)
- We intended to have one (#4562), but there were too many issues (see #4612) so we decided not to add it yet.

**Comment by nouiz** [comment]
So do you agree why what I said: for now, make an canonikalize opt that
will merge the dimshuffle inside the Subtensor?

**Comment by lamblin** [comment]
Given that it is only a special case of dimshuffle that it would handle, yes, I agree with that.

**Comment by lamblin** [comment]
I think the first one should actually be `dimshuffle(alloc) => alloc`, if what we want is to reverse the optimization from #4072. In this example, we would want:
*   `dimshuffle{x, 0, 1}(alloc([3 4], 3, 2)` => `alloc([3 4], 1, 3, 2)`

There may already be an optimization doing:
*  `alloc([3 4].dimshuffle('x', 'x', 0), 6, 5, 2)` => `alloc([3 4], 6, 5, 2)`
otherwise this would be a good idea to add it, but not only in the "uncanonicalize" phase. We may also want something like:
*  `alloc([3 4].dimshuffle('x', 'x', 0), 5, 2)` => `alloc([3 4], 5, 2).dimshuffle('x', 0, 1)` or
*  `alloc([3 4].dimshuffle('x', 'x', 0), 5, 2)` => `alloc([3 4], 1, 5, 2)`
but it should be a different item in the list.

**Comment by nouiz** [comment]
For the first point, I make another issue: https://github.com/Theano/Theano/issues/5024

For point 2, there wasn't such opt.
I don't see the point of doing point 3.  Throught point 4 is useful as an extension of the opt in this issue. I add it at the end of this issue, as it is a generalization of the first point of this issue.

**Comment by lamblin** [comment]
Actually, in my points 3 and 4 above, `alloc([3 4].dimshuffle('x', 'x', 0), 5, 2)` is not actually correct (it raises a TypeError if we try to build it), so it does not matter.

**Comment by olimastro** [comment]
I found this :
`def local_subtensor_remove_broadcastable_index(node):`
`    """`
`    Remove broadcastable dimension with index 0 or -1`
`    a[:,:,:,0] -> a.dimshuffle(0,1,2), when`
`        a.broadcastable = (False, False, False, True)`
`    a[0,:,-1,:] -> a.dimshuffle(1,3), when`
`        a.broadcastable = (True, False, True, False)`
`    """`

Wouldn't the subtensor opt you are asking here compete with this opt?

**Comment by nouiz** [comment]
This is related but not the same. This convert a subtensor to dimshuffle, but only if it completly remove the subtensor.

The new optimization is to merge the dimshuffle into the subtensor. This will make the graph smaller. It should be normally when the subtensor is mandatory as it will be done after the optimization local_subtensor_remove_broadcastable_index is applied.

Thew new optimization missing must be registered in the uncanonicalise phase, that happen after local_subtensor_remove_broadcastable_index.
