### ISSUE TITLE
Improvements to theano.var

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#4651]
There are two things that I think would improve `theano.var`:

* [ ] Add an option to use a more stable variant, namely the "corrected two-pass" algorithm described [here](http://www.cs.yale.edu/publications/techreports/tr222.pdf). PR gh-4681
* [x] Add the `ddof` argument from `numpy.var` and `numpy.std` to `tensor.var` and `tensor.std`.

**Comment by dwf** [comment]
Yes, that's pretty much it. For backwards compatibility it's probably not good to add it by default (also not sure how much of a speed hit it is).

**Comment by dwf** [comment]
Also, bad @nouiz, you're on vacation 😛

**Comment by nouiz** [comment]
Actually, I'm staring my vacation only tomorrow!

**Comment by kumarkrishna** [comment]
Hi @nouiz 
Could you mention what you meant by embedding in the Theano graph? I could update my PR to cover the ```ddof``` parameter as well.

**Comment by nouiz** [comment]
there is already someone that started doing the ddof, so to prevent duplicate work, let him do it:) By embedding in the Theano graph, I mean this can be added in the Theano graph (as you did for the corrected two-pass).

I let @ballasn review your PR and the one for ddof.

thanks

**Comment by nouiz** [comment]
all is done.
