### ISSUE TITLE
Runtime error with Cuda

### ISSUE THREAD

**Issue by KayMKM** [Theano/Theano#4657]
Hi,
I tried to run a theano training process with the gpu but runtime error:
CudaNdarray_TakeFrom: invalid device function.

It works well with the cpu. The Cuda is v7.5, graphics card is Quadro 600, theano is 0.8, OS is Win10, VS is 2013.

Is my graphics card too old? How can I fix it?

Thanks, 
Kay

**Comment by Morgan243** [comment]
If it's the K600, it's listed on this page as supporting the 3.0 (Kepler) compute capability: https://developer.nvidia.com/cuda-gpus

My understanding is that only the Tesla line (compute capability 1.*) has had support dropped in the CUDA v7 software. So you should be able to run some CUDA programs as long it isn't using any CUDA features that aren't supported by your card - perhaps this is where the error is coming from?
