### ISSUE TITLE
Theano 0.8.1 ImportError in Winpython 3.5.1 64bit, no GPU

### ISSUE THREAD

**Issue by fnorlund** [Theano/Theano#4664]
Hello,
I've just installed WinPython 3.5.1.3 64bit including Theano 0.8.1 on a Windows 10 machine. The compiler is TDM-GCC-64 and I'm not using a GPU. 

After running a theano demo example I get the following error:
>>> import theano
>>> from theano import tensor
>>> a = tensor.dscalar()
>>> b = tensor.dscalar()
>>> c = a + b
>>> f = theano.function([a,b], c)

Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    f = theano.function([a,b], c)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\compile\function_module.py", line 1777, in orig_function
    defaults)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\vm.py", line 1003, in make_all
    no_recycling))
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\op.py", line 970, in make_thunk
    no_recycling)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cmodule.py", line 2212, in compile_str
    return dlimport(lib_filename)
  File "F:\Program_Files\WinPython-64bit-3.5.1.3\python-3.5.1.amd64\lib\site-packages\theano\gof\cmodule.py", line 299, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

What can be wrong?
Please help a newbie

Thanks!

**Comment by fnorlund** [comment]
I decided to downgrade to WinPython 3.4.4.2 64bit and now everything works out of the box.

**Comment by ddofer** [comment]
Same issue with Anaconda installation

**Comment by ddofer** [comment]
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-28-b4245457998b> in <module>()
      2 
      3 model = Sequential()
----> 4 model.add(Embedding(input_dim=vocabulary_size, output_dim=14, input_length=X_train.shape[1], dropout=0.1,
      5                    ) )
      6 

C:\Program Files\Anaconda3\lib\site-packages\keras\models.py in add(self, layer)
    278                 else:
    279                     input_dtype = None
--> 280                 layer.create_input_layer(batch_input_shape, input_dtype)
    281 
    282             if len(layer.inbound_nodes) != 1:

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py in create_input_layer(self, batch_input_shape, input_dtype, name)
    368         # and create the node connecting the current layer
    369         # to the input layer we just created.
--> 370         self(x)
    371 
    372     def assert_input_compatibility(self, input):

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py in __call__(self, x, mask)
    512         if inbound_layers:
    513             # this will call layer.build() if necessary
--> 514             self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
    515             input_added = True
    516 

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
    570         # creating the node automatically updates self.inbound_nodes
    571         # as well as outbound_nodes on inbound layers.
--> 572         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
    573 
    574     def get_output_shape_for(self, input_shape):

C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
    147 
    148         if len(input_tensors) == 1:
--> 149             output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
    150             output_masks = to_list(outbound_layer.compute_mask(input_tensors[0], input_masks[0]))
    151             # TODO: try to auto-infer shape if exception is raised by get_output_shape_for

C:\Program Files\Anaconda3\lib\site-packages\keras\layers\embeddings.py in call(self, x, mask)
    130         if 0. < self.dropout < 1.:
    131             retain_p = 1. - self.dropout
--> 132             B = K.random_binomial((self.input_dim,), p=retain_p) * (1. / retain_p)
    133             B = K.expand_dims(B)
    134             W = K.in_train_phase(self.W * B, self.W)

C:\Program Files\Anaconda3\lib\site-packages\keras\backend\theano_backend.py in random_binomial(shape, p, dtype, seed)
   1653         seed = np.random.randint(1, 10e6)
   1654     rng = RandomStreams(seed=seed)
-> 1655     return rng.binomial(shape, p=p, dtype=dtype)
   1656 
   1657 # Theano implementation of CTC

C:\Program Files\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py in binomial(self, size, n, p, ndim, dtype, nstreams)
   1359                 x = self.uniform(size=size, dtype=dtype, nstreams=nstreams)
   1360             else:
-> 1361                 x = self.uniform(size=size, nstreams=nstreams)
   1362             return cast(x < p, dtype)
   1363         else:

C:\Program Files\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py in uniform(self, size, low, high, ndim, dtype, nstreams)
   1319         if nstreams is None:
   1320             nstreams = self.n_streams(size)
-> 1321         rstates = self.get_substream_rstates(nstreams, dtype)
   1322 
   1323         if self.use_cuda and dtype == 'float32':

C:\Program Files\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py in get_substream_rstates(self, n_streams, dtype, inc_rstate)
   1221         # If multMatVect.dot_modulo isn't compiled, compile it.
   1222         if multMatVect.dot_modulo is None:
-> 1223             multMatVect(rval[0], A1p72, M1, A2p72, M2)
   1224 
   1225         # This way of calling the Theano fct is done to bypass Theano overhead.

C:\Program Files\Anaconda3\lib\site-packages\theano\sandbox\rng_mrg.py in multMatVect(v, A, m1, B, m2)
     62         o = DotModulo()(A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym)
     63         multMatVect.dot_modulo = function(
---> 64             [A_sym, s_sym, m_sym, A2_sym, s2_sym, m2_sym], o, profile=False)
     65 
     66     # This way of calling the Theano fct is done to bypass Theano overhead.

C:\Program Files\Anaconda3\lib\site-packages\theano\compile\function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    318                    on_unused_input=on_unused_input,
    319                    profile=profile,
--> 320                    output_keys=output_keys)
    321     # We need to add the flag check_aliased inputs if we have any mutable or
    322     # borrowed used defined inputs

C:\Program Files\Anaconda3\lib\site-packages\theano\compile\pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    477                          accept_inplace=accept_inplace, name=name,
    478                          profile=profile, on_unused_input=on_unused_input,
--> 479                          output_keys=output_keys)
    480 
    481 

C:\Program Files\Anaconda3\lib\site-packages\theano\compile\function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1775                    on_unused_input=on_unused_input,
   1776                    output_keys=output_keys).create(
-> 1777             defaults)
   1778 
   1779     t2 = time.time()

C:\Program Files\Anaconda3\lib\site-packages\theano\compile\function_module.py in create(self, input_storage, trustme, storage_map)
   1639             theano.config.traceback.limit = 0
   1640             _fn, _i, _o = self.linker.make_thunk(
-> 1641                 input_storage=input_storage_lists, storage_map=storage_map)
   1642         finally:
   1643             theano.config.traceback.limit = limit_orig

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\link.py in make_thunk(self, input_storage, output_storage, storage_map)
    688         return self.make_all(input_storage=input_storage,
    689                              output_storage=output_storage,
--> 690                              storage_map=storage_map)[:3]
    691 
    692     def make_all(self, input_storage, output_storage):

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\vm.py in make_all(self, profiler, input_storage, output_storage, storage_map)
   1001                                                  storage_map,
   1002                                                  compute_map,
-> 1003                                                  no_recycling))
   1004                 if not hasattr(thunks[-1], 'lazy'):
   1005                     # We don't want all ops maker to think about lazy Ops.

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
    968             try:
    969                 return self.make_c_thunk(node, storage_map, compute_map,
--> 970                                          no_recycling)
    971             except (NotImplementedError, utils.MethodNotDefined):
    972                 logger.debug('Falling back on perform')

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    877         logger.debug('Trying CLinker.make_thunk')
    878         outputs = cl.make_thunk(input_storage=node_input_storage,
--> 879                                 output_storage=node_output_storage)
    880         fill_storage, node_input_filters, node_output_filters = outputs
    881 

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock)
   1198         cthunk, in_storage, out_storage, error_storage = self.__compile__(
   1199             input_storage, output_storage, storage_map,
-> 1200             keep_lock=keep_lock)
   1201 
   1202         res = _CThunk(cthunk, init_tasks, tasks, error_storage)

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cc.py in __compile__(self, input_storage, output_storage, storage_map, keep_lock)
   1141                                     output_storage,
   1142                                     storage_map,
-> 1143                                     keep_lock=keep_lock)
   1144         return (thunk,
   1145                 [link.Container(input, storage) for input, storage in

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock)
   1593         else:
   1594             module = get_module_cache().module_from_key(
-> 1595                 key=key, lnk=self, keep_lock=keep_lock)
   1596 
   1597         vars = self.inputs + self.outputs + self.orphans

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1140             try:
   1141                 location = dlimport_workdir(self.dirname)
-> 1142                 module = lnk.compile_cmodule(location)
   1143                 name = module.__file__
   1144                 assert name.startswith(location)

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cc.py in compile_cmodule(self, location)
   1504                 lib_dirs=self.lib_dirs(),
   1505                 libs=libs,
-> 1506                 preargs=preargs)
   1507         except Exception as e:
   1508             e.args += (str(self.fgraph),)

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2211             open(os.path.join(location, "__init__.py"), 'w').close()
   2212             assert os.path.isfile(lib_filename)
-> 2213             return dlimport(lib_filename)
   2214 
   2215 

C:\Program Files\Anaconda3\lib\site-packages\theano\gof\cmodule.py in dlimport(fullpath, suffix)
    297             warnings.filterwarnings("ignore",
    298                                     message="numpy.ndarray size changed")
--> 299             rval = __import__(module_name, {}, {}, [module_name])
    300         t1 = time.time()
    301         import_time += t1 - t0

ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.`

**Comment by nouiz** [comment]
We have a PR that easy Theano installation on windows:

https://github.com/Theano/Theano/pull/5290

Try it with anaconda.

**Comment by ddofer** [comment]
Note that currently it doesn't work for 3.5 64 bit, but does for 3.5 32bit

**Comment by mingwandroid** [comment]
@ddofer, did you try this from the `Anaconda Prompt`?

.. or do you add `Anaconda` to the System Path? Because we are missing a mingw-w64 folder in the System Path case (and I am hoping to get that option removed from the installers since IMHO it's broken by design).
