### ISSUE TITLE
modprobe: ERROR: could not insert 'nvidia_361_uvm': Invalid argument

### ISSUE THREAD

**Issue by ShuaiW** [Theano/Theano#4667]
- GPU: GTX1080
- GPU driver: 367.27
- OS: Ubuntu 16.04
- CUDA: 8.0 rc

I am using keras with theano backend. When I run 
`THEANO_FLAGS=device=gpu,floatX=float32 python *.py`

I got

Using Theano backend.
modprobe: ERROR: could not insert 'nvidia_361_uvm': Invalid argument
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available (error: Unable to get the number of gpus available: unknown error)

Does theano support the hardware/software listed above already?

**Comment by aymericdamien** [comment]
I answered it here: https://github.com/fchollet/keras/issues/3043, you can have a try.

**Comment by jonathanstrong** [comment]
just posted some detailed notes from my experience [here](https://github.com/fchollet/keras/issues/3043#issuecomment-233480326)
