### ISSUE TITLE
Updating Shared Variable using Symbolic variable

### ISSUE THREAD

**Issue by kimdon20** [Theano/Theano#4668]
Hi, I was wondering if there is a way to update a shared variable using a theano symbolic variable, during a single compilation.

Or is there a way that we can store a symbolic variable's contents to a list , perhaps able to store the values we can print using theano.printing.Print() ? 

Thanks :)

**Comment by lamblin** [comment]
Please ask your question on `theano-users` or StackOverflow, with an example of your code, and the full error message.
