### ISSUE TITLE
Import error for  DLL 

### ISSUE THREAD

**Issue by AakashKumarNain** [Theano/Theano#4673]
I tried to install theano using Anaconda package for Windows. After that I created an environment where I wanted to use theano. I have installed gcc as well as put openblas required for computation. But I am getting this error. 

> ```
> ImportError Traceback (most recent call last) in () 11 np_end = time.time() 12 X, Y =    theano.tensor.matrices('XY') ---> 13 mf = theano.function([X, Y], X.dot(Y)) 14 t_start = time.time() 15 tAB = mf(A, B)
> 
> C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\compile\function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input) 318 on_unused_input=on_unused_input, 319 profile=profile, --> 320 output_keys=output_keys) 321 # We need to add the flag check_aliased inputs if we have any mutable or 322 # borrowed used defined inputs
> 
> 
>  C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\compile\pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys) 477 accept_inplace=accept_inplace, name=name, 478 profile=profile, on_unused_input=on_unused_input, --> 479 output_keys=output_keys) 480 481
> 
>   C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\compile\function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys) 1775
>  on_unused_input=on_unused_input, 1776
>  output_keys=output_keys).create( -> 1777 defaults) 1778 1779 t2 = time.time()
> 
>  C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\compile\function_module.py in  create(self, input_storage, trustme, storage_map) 1639
>       theano.config.traceback.limit = 0 1640 _fn, _i, _o = self.linker.make_thunk( -> 1641 input_storage=input_storage_lists, storage_map=storage_map) 1642 finally: 1643
>       theano.config.traceback.limit = limit_orig
> 
>   C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\link.py in make_thunk(self, input_storage, output_storage, storage_map) 688 return self.make_all(input_storage=input_storage, 689 output_storage=output_storage, --> 690 storage_map=storage_map)[:3] 691 692 def make_all(self, input_storage, output_storage):
> 
>    C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\vm.py in make_all(self, profiler, input_storage, output_storage, storage_map)
>    1001 storage_map,
>    1002 compute_map, -> 1003 no_recycling)) 1004 if not hasattr(thunks[-1], 'lazy'): 1005 # We don't want all ops maker to think about lazy Ops.
> 
>    C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\op.py in make_thunk(self, node, storage_map, compute_map, no_recycling) 968 try: 969 return self.make_c_thunk(node, storage_map, compute_map, --> 970 no_recycling) 971 except (NotImplementedError, utils.MethodNotDefined): 972 logger.debug('Falling back on perform')
> 
>    C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling) 877 logger.debug('Trying CLinker.make_thunk') 878 outputs = cl.make_thunk(input_storage=node_input_storage, --> 879 output_storage=node_output_storage) 880 fill_storage, node_input_filters, node_output_filters = outputs 881
> 
>    C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock) 1198 cthunk, in_storage, out_storage, error_storage = self.compile( 1199 input_storage, output_storage, storage_map, -> 1200 keep_lock=keep_lock) 1201 1202 res = _CThunk(cthunk, init_tasks, tasks, error_storage)
> 
>     C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cc.py in compile(self, input_storage, output_storage, storage_map, keep_lock) 1141 output_storage, 1142 storage_map, -> 1143 keep_lock=keep_lock) 1144 return (thunk, 1145
>      [link.Container(input, storage) for input, storage in
> 
>     C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock) 1593 else: 1594
>       module = get_module_cache().module_from_key( -> 1595 key=key, lnk=self, keep_lock=keep_lock) 1596 1597 vars = self.inputs + self.outputs + self.orphans
> 
>     C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cmodule.py in module_from_key(self, key, lnk, keep_lock) 1140 try: 1141 location = dlimport_workdir(self.dirname) ->        1142 module = lnk.compile_cmodule(location) 1143 name = module.file 1144 assert name.startswith(location)
> 
>    C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cc.py in compile_cmodule(self, location) 1504
>     lib_dirs=self.lib_dirs(), 1505 libs=libs, -> 1506 preargs=preargs) 1507 except Exception as e: 1508 e.args += (str(self.fgraph),)
> 
>    C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols) 2211
>    open(os.path.join(location, "init.py"), 'w').close() 2212
>    assert os.path.isfile(lib_filename) -> 2213 return dlimport(lib_filename) 2214 2215
> 
>     C:\Anaconda3\envs\DeepLearning\lib\site-packages\theano\gof\cmodule.py in dlimport(fullpath, suffix) 297 warnings.filterwarnings("ignore", 298 message="numpy.ndarray size changed") --> 299 rval = import(module_name, {}, {}, [module_name]) 300 t1 = time.time() 301 import_time += t1 - t0
> 
>   **ImportError: DLL load failed: The specified module could not be found.**
> ```

**Comment by lamblin** [comment]
Please use StackOverflow or theano-users for such requests.
To know which module is missing, you can try the dependency walker for instance. You may need to add some places to the `PATH` manually.
The upcoming 0.9 version should have better support for Windows in the conda package, including the new GPU back-end.
