### ISSUE TITLE
DLL load failed: The specified module could not be found for pygpu

### ISSUE THREAD

**Issue by dog56ui78** [Theano/Theano#4684]
I'm using libgpuarray (openCL) but can't seem to get the GPU working with Theano in anaconda 2. When I try to run the test I get: 

ERROR (theano.gpuarray): pygpu was configured but could not be imported
Traceback (most recent call last):
  File "C:\Users\username\Anaconda2\lib\site-packages\theano-0.9.0.dev1-py2.7.egg\theano\gpuarray\__init__.py", line 21, in <module>
    import pygpu
  File "C:\Users\username\Anaconda2\lib\site-packages\pygpu-0.2.1-py2.7-win-amd64.egg\pygpu\__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
ImportError: DLL load failed: The specified module could not be found.

Theano works fine with the cpu. I ran the command code "python setup.py build" and "python setup.py install" on setup.py in the libgpuarray folder (after I used cmake to install libgpuarray) to get pygpu and it ran successfully. Did it not install correctly or is there something else happening?

**Comment by nouiz** [comment]
Can you tell what was the fix? It will help other people having the same
problem find the solution faster.

thanks
