### ISSUE TITLE
CorrMM: upcast inputs?

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#4687]
When `CorrMM` receives inputs of mixed types (single and double precision), it fails at runtime:
```python
import theano
import theano.tensor as T
x = T.ftensor4()
y = T.dtensor4()
z = T.nnet.corr.CorrMM()(x, y)
fn = theano.function([x, y], z)
fn(np.random.randn(2,3,4,5).astype(np.float32), np.random.randn(1,2,3,4))
```
This fails with `ValueError: CorrMM received weight with wrong type.`, from here: https://github.com/Theano/Theano/blob/a668c6c/theano/tensor/nnet/corr_gemm.c#L130
`CorrMM`, `CorrMM_gradWeights` and `CorrMM_gradInputs` should probably upcast their input tensors to a common datatype in `make_node`, or at least check for matching types early instead of failing at runtime.

Problem reported at https://groups.google.com/d/topic/lasagne-users/I5u9RHXTHmI/discussion.

**Comment by JesseLivezey** [comment]
I ran into this a while ago and wrote a fix but never made a PR. Upcasting version is here #4691
