### ISSUE TITLE
Theano Compilation failed (may related to gcc)

### ISSUE THREAD

**Issue by gxstudy** [Theano/Theano#4692]
Hi, I am using theano on my school's server(CentOs 6), which has gcc version of 4.8.3. But I got such error while running it. 

I didn't do the first step of installation,  "sudo yum install python-devel python-nose python-setuptools gcc gcc-gfortran gcc-c++ blas-devel lapack-devel atlas-devel". But the system does has them installed already, the gcc version is 4.8.3. Anybody can tell me what's wrong with it. Thanks a lot. 

Cindy

```
Problem occurred during compilation with the command line below:
/opt/shared/gcc/4.8.3/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=core-avx2 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=25600 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/opt/shared/anaconda/2.5.0-python2/lib/python2.7/site-packages/numpy/core/include -I/opt/shared/anaconda/2.5.0-python2/include/python2.7 -I/home/1001/.local/lib/python2.7/site-packages/theano/gof -fvisibility=hidden -o /home/1001/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.11-64/tmpaJyUFi/e272626fce8242df38e99a5ea7f34d67.so /home/1001/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.6-Final-x86_64-2.7.11-64/tmpaJyUFi/mod.cpp -L/opt/shared/anaconda/2.5.0-python2/lib -lpython2.7
/tmp/ccCRhmRe.s: Assembler messages:
/tmp/ccCRhmRe.s:1698: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'
/tmp/ccCRhmRe.s:1703: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'

Traceback (most recent call last):
  File "logistic_sgd.py", line 475, in <module>
    sgd_optimization_mnist()
  File "logistic_sgd.py", line 316, in sgd_optimization_mnist
    y: test_set_y[index * batch_size: (index + 1) * batch_size]
  File "/home/1001/.local/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/vm.py", line 1003, in make_all
    no_recycling))
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/op.py", line 970, in make_thunk
    no_recycling)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1143, in __compile__
    keep_lock=keep_lock)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "/home/1001/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2204, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Elemwise{mul,no_inplace}(TensorConstant{600}, <TensorType(int64, scalar)>), '\n', "Compilation failed (return status=1): /tmp/ccCRhmRe.s: Assembler messages:. /tmp/ccCRhmRe.s:1698: Error: no such instruction: `vinserti128 $0x1,%xmm0,%ymm1,%ymm0'. /tmp/ccCRhmRe.s:1703: Error: no such instruction: `vextracti128 $0x1,%ymm0,16(%rax)'. ", '[Elemwise{mul,no_inplace}(TensorConstant{600}, <TensorType(int64, scalar)>)]')
```

**Comment by nouiz** [comment]
Update to Theano dev version. This is a bug in GCC. Theano dev version try
to detect that and try a work around:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Keep us updated if it work or not.

**Comment by gxstudy** [comment]
Thank you for replying, I tried to install the dev version using 
```
git clone git://github.com/Theano/Theano.git
cd Theano
python setup.py develop --prefix=~/.local
```

Here is the log of installation:
`/opt/shared/anaconda/2.5.0-python2/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.9.0dev1' to '0.9.0.dev1'
running develop
running egg_info
creating Theano.egg-info
writing requirements to Theano.egg-info/requires.txt
writing Theano.egg-info/PKG-INFO
writing top-level names to Theano.egg-info/top_level.txt
writing dependency_links to Theano.egg-info/dependency_links.txt
writing manifest file 'Theano.egg-info/SOURCES.txt'
reading manifest file 'Theano.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 9: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'Theano.egg-info/SOURCES.txt'
running build_ext
Creating /home/1001/.local/lib/python2.7/site-packages/Theano.egg-link (link to .)
Adding Theano 0.9.0.dev1 to easy-install.pth file
Installing theano-cache script to /home/1001/.local/bin
Installing theano-nose script to /home/1001/.local/bin
Installing theano-test script to /home/1001/.local/bin

Installed /home/1001/Theano
Processing dependencies for Theano==0.9.0.dev1
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /home/software/anaconda/2.5.0-python2/lib/python2.7/site-packages
Searching for scipy==0.17.0
Best match: scipy 0.17.0
Adding scipy 0.17.0 to easy-install.pth file

Using /home/software/anaconda/2.5.0-python2/lib/python2.7/site-packages
Searching for numpy==1.10.4
Best match: numpy 1.10.4
Adding numpy 1.10.4 to easy-install.pth file

Using /home/software/anaconda/2.5.0-python2/lib/python2.7/site-packages
Finished processing dependencies for Theano==0.9.0.dev1`

Then I tried `python -c "import theano; theano.test()"`
But the errors are the same as before. 

Could it be the version of any of these dependencies, i.e.,  gcc gcc-gfortran gcc-c++ blas-devel lapack-devel atlas-devel, since I am just using the system version, partly because I don't have privilege to install them.  What can I do next? Thanks a lot for help.

**Comment by nouiz** [comment]
Try wit hthis Theano flag:

gcc.cxxflags=-march=corei7

if is don't work, try this one:

gcc.cxxflags=-march=core2

Delete your theano cache before changing this flag.

**Comment by nouiz** [comment]
You seem to still use the old Theano. Uninstall all version. DO:

pip uninstall theano

multilple time. Then reinstall the bleading edge. It could fix it without the flag.

**Comment by nouiz** [comment]
I think we fixed that in the master of Theano, so I'll close.

If you still have problems with the master of Theano, open a new issue.
