### ISSUE TITLE
Mimic Rop in Theano

### ISSUE THREAD

**Issue by zeka0** [Theano/Theano#4693]
Since some of the operators(like downsample) doesn't support T.Rop, I decided to use theano to mimic the behavior of it. Here is the code:

``` python
import theano
from theano import tensor as T
import numpy as np

W = T.dmatrix()
V = T.dmatrix()
x = T.dvector()
y = T.dot(x, W)
Jv1 = T.Rop(y, W, V)
Jv2 = T.dot(theano.gradient.jacobian(y, W), V)

fun1 = theano.function([W, V, x], Jv1)
fun2 = theano.function([W, V, x], Jv2)

print fun1([[1, 1], [1, 1]], [[2, 2], [2, 2]], [0,1])
print fun2([[1, 1], [1, 1]], [[2, 2], [2, 2]], [0,1])
```

First thing I noticed is that in T.Rop(y, W, V), W and V must be of the same shape which doesn't make sense to me. Also, the result of fun1 and fun2 doesn't match.
I have googled that Rop operates in flattened mode. But why should it do so?
Thanks in advance.

**Comment by lamblin** [comment]
Yes, the input (W) and evaluation point (V) should have the same shape, because they live in the same space.
Jacobian needs flat vectors because it will explicitly return a matrix, and dimensions are less ambiguous that way.
