### ISSUE TITLE
Type Error: 'Non-unit value on shape on a broadcastable dimension.', (0, 0)

### ISSUE THREAD

**Issue by smar111** [Theano/Theano#4710]
Hi I am writing a code in theano for machine translation. I am getting the following error:

TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Shape_i{0}.0, Alloc.0, Elemwise{Composite{(i0 - sqr(i1))}}.0, InplaceDimShuffle{0,x,1}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Subtensor{::int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, vh, vx, bx, wo, wy, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0, 0), (True, False), 'Container name "None"')

Some related part of the code is as follows:
        # end-snippet-2
        self.params = [self.embs, self.embt, self.vh, self.vx, self.wc, self.wh, self.wo,
                               self.wy, self.bx, self.bh, self.bo, self.h0]

```
    # start-snippet-3
    idxs = T.ivector('idxs')
    x = self.embs[idxs].reshape((idxs.shape[0], dembs))
    idxt = T.ivector('idxt')
    y = self.embt[idxt].reshape((idxt.shape[0], dembt))
    y0 = self.embt[-1].dimshuffle('x',0)

    # end-snippet-3 start-snippet-4

    def calculate_beta(x, h_tm1):
        B_i=T.tanh(T.dot(h_tm1, self.vh) + T.dot(x, self.vx) + self.bx)
        return B_i

    def recurrence(x, h_tm1, y_tm1):
        beta, _ = theano.scan(fn=calculate_beta,
                              sequences=x, 
                              outputs_info=None, 
                              non_sequences=h_tm1,
                              n_steps=x.shape[0])                                 
        alpha_t = T.nnet.softmax(beta)       

        Z_t=T.dot(alpha_t.T,x)

        h_t = T.tanh(T.dot(h_tm1, self.wh) + T.dot(Z_t, self.wc) + self.bh)
        y_t = T.nnet.softmax(T.dot(h_t, self.wo) + T.dot(y_tm1, self.wy) + self.bo)

        return [h_t, y_t]

    [h, s], _ = theano.scan(fn=recurrence,
                            sequences=x,
                            outputs_info=[self.h0, y0],
                            n_steps=idxt.shape[0])

    p_y_given_x_sentence = s[:, 0, :]
    y_pred = T.argmax(p_y_given_x_sentence, axis=1)
    # end-snippet-4

    # cost and gradients and learning rate
    # start-snippet-5
    lr = T.dscalar('lr')

    sentence_nll = -T.mean(T.log(p_y_given_x_sentence)
                          [T.arange(idxt.shape[0]), idxt])
    sentence_gradients = T.grad(sentence_nll, self.params)
    sentence_updates = OrderedDict((p, p - lr*g)
                                   for p, g in
                                   zip(self.params, sentence_gradients))
    # end-snippet-5

    # theano functions to compile
    # start-snippet-6
    self.sentence_train = theano.function(inputs=[idxs, idxt, lr], 
                                          outputs=sentence_nll, 
                                          updates=sentence_updates)
```

The error occurs in the last line i.e. updates=sentence_updates). I have checked the dimensions of the parameter vectors/matrices but they seem to be in accordance.

**Comment by nouiz** [comment]
Can you give the full error message?

**Comment by smar111** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-9-7a0315bb1520> in <module>()
     37 
     38 if __name__ == '__main__':
---> 39     main()

<ipython-input-9-7a0315bb1520> in main(lr, dembs, dembt, n_epochs, nh)
     18     print("instantiate the model......")
     19     numpy.random.seed(345)
---> 20     rnn=RNNMT(nh, ntarget, nsource, dembs, dembt)
     21 
     22     print("training the model......")

<ipython-input-8-58918a6f9bed> in __init__(self, nh, nt, ns, dembs, dembt)
    119         self.sentence_train = theano.function(inputs=[idxs, idxt, lr],
    120                                               outputs=[sentence_nll],
--> 121                                               updates=sentence_updates)
    122         # end-snippet-6 start-snippet-7
    123         self.norms = theano.function(inputs=[],

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    318                    on_unused_input=on_unused_input,
    319                    profile=profile,
--> 320                    output_keys=output_keys)
    321     # We need to add the flag check_aliased inputs if we have any mutable or
    322     # borrowed used defined inputs

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    477                          accept_inplace=accept_inplace, name=name,
    478                          profile=profile, on_unused_input=on_unused_input,
--> 479                          output_keys=output_keys)
    480 
    481 

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1775                    on_unused_input=on_unused_input,
   1776                    output_keys=output_keys).create(
-> 1777             defaults)
   1778 
   1779     t2 = time.time()

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function_module.py in create(self, input_storage, trustme, storage_map)
   1639             theano.config.traceback.limit = 0
   1640             _fn, _i, _o = self.linker.make_thunk(
-> 1641                 input_storage=input_storage_lists, storage_map=storage_map)
   1642         finally:
   1643             theano.config.traceback.limit = limit_orig

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\gof\link.py in make_thunk(self, input_storage, output_storage, storage_map)
    688         return self.make_all(input_storage=input_storage,
    689                              output_storage=output_storage,
--> 690                              storage_map=storage_map)[:3]
    691 
    692     def make_all(self, input_storage, output_storage):

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\gof\vm.py in make_all(self, profiler, input_storage, output_storage, storage_map)
   1001                                                  storage_map,
   1002                                                  compute_map,
-> 1003                                                  no_recycling))
   1004                 if not hasattr(thunks[-1], 'lazy'):
   1005                     # We don't want all ops maker to think about lazy Ops.

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\scan_module\scan_op.py in make_thunk(self, node, storage_map, compute_map, no_recycling)
    854                                name=self.name,
    855                                profile=profile,
--> 856                                on_unused_input='ignore')
    857 
    858         # Analyse the compile inner function to determine which inputs and

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    318                    on_unused_input=on_unused_input,
    319                    profile=profile,
--> 320                    output_keys=output_keys)
    321     # We need to add the flag check_aliased inputs if we have any mutable or
    322     # borrowed used defined inputs

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    477                          accept_inplace=accept_inplace, name=name,
    478                          profile=profile, on_unused_input=on_unused_input,
--> 479                          output_keys=output_keys)
    480 
    481 

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1775                    on_unused_input=on_unused_input,
   1776                    output_keys=output_keys).create(
-> 1777             defaults)
   1778 
   1779     t2 = time.time()

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function_module.py in create(self, input_storage, trustme, storage_map)
   1655         fn = self.function_builder(_fn, _i, _o, self.indices, self.outputs,
   1656                                    defaults, self.unpack_single,
-> 1657                                    self.return_none, self.output_keys, self)
   1658         fn.profile = self.profile
   1659         return fn

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\compile\function_module.py in __init__(self, fn, input_storage, output_storage, indices, outputs, defaults, unpack_single, return_none, output_keys, maker)
    415                         assert not refeed
    416                     else:
--> 417                         c.value = value
    418                 c.required = required
    419                 c.implicit = input.implicit

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\gof\link.py in __set__(self, value)
    466                                                            **kwargs)
    467             else:
--> 468                 self.storage[0] = self.type.filter(value, **kwargs)
    469 
    470         except Exception as e:

C:\Users\Sameen\Anaconda3\lib\site-packages\theano\tensor\type.py in filter(self, data, strict, allow_downcast)
    192             if b and data.shape[i] != 1:
    193                 raise TypeError("Non-unit value on shape on a broadcastable"
--> 194                                 " dimension.", data.shape, self.broadcastable)
    195             i += 1
    196         if (self.filter_checks_isfinite and

TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,grad_of_scan_fn}(Shape_i{0}.0, Alloc.0, Elemwise{Composite{(i0 - sqr(i1))}}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, Alloc.0, Subtensor{::int64}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, vh, vx, bx, wo, wy, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{1,0}.0, InplaceDimShuffle{1,0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0), '\n', 'Non-unit value on shape on a broadcastable dimension.', (0, 0), (True, False), 'Container name "None"')

**Comment by smar111** [comment]
I tried changing my code since I found some mistake in the dimensions of the symbolic variable (idxs and idxy which I was reshaping later) but I am now getting a new error in the gradient calculation:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-31-7a0315bb1520> in <module>()
     37 
     38 if __name__ == '__main__':
---> 39     main()

<ipython-input-31-7a0315bb1520> in main(lr, dembs, dembt, n_epochs, nh)
     18     print("instantiate the model......")
     19     numpy.random.seed(345)
---> 20     rnn=RNNMT(nh, ntarget, nsource, dembs, dembt)
     21 
     22     print("training the model......")

<ipython-input-32-5dcc19bd6901> in __init__(self, nh, nt, ns, dembs, dembt)
    101                               [T.arange(idxt.shape[0]), idxt])
    102 
--> 103         sentence_gradients = T.grad(sentence_nll, self.params)
    104         sentence_updates = OrderedDict((p, p - lr*g) for p, g in zip(self.params, sentence_gradients))
    105 

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in grad(cost, wrt, consider_constant, disconnected_inputs, add_names, known_grads, return_disconnected, null_gradients)
    559 
    560     rval = _populate_grad_dict(var_to_app_to_idx,
--> 561                                grad_dict, wrt, cost_name)
    562 
    563     for i in xrange(len(rval)):

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in _populate_grad_dict(var_to_app_to_idx, grad_dict, wrt, cost_name)
   1322         return grad_dict[var]
   1323 
-> 1324     rval = [access_grad_cache(elem) for elem in wrt]
   1325 
   1326     return rval

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in <listcomp>(.0)
   1322         return grad_dict[var]
   1323 
-> 1324     rval = [access_grad_cache(elem) for elem in wrt]
   1325 
   1326     return rval

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_grad_cache(var)
   1277                     for idx in node_to_idx[node]:
   1278 
-> 1279                         term = access_term_cache(node)[idx]
   1280 
   1281                         if not isinstance(term, gof.Variable):

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_term_cache(node)
    971             inputs = node.inputs
    972 
--> 973             output_grads = [access_grad_cache(var) for var in node.outputs]
    974 
    975             # list of bools indicating if each output is connected to the cost

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in <listcomp>(.0)
    971             inputs = node.inputs
    972 
--> 973             output_grads = [access_grad_cache(var) for var in node.outputs]
    974 
    975             # list of bools indicating if each output is connected to the cost

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_grad_cache(var)
   1277                     for idx in node_to_idx[node]:
   1278 
-> 1279                         term = access_term_cache(node)[idx]
   1280 
   1281                         if not isinstance(term, gof.Variable):

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_term_cache(node)
    971             inputs = node.inputs
    972 
--> 973             output_grads = [access_grad_cache(var) for var in node.outputs]
    974 
    975             # list of bools indicating if each output is connected to the cost

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in <listcomp>(.0)
    971             inputs = node.inputs
    972 
--> 973             output_grads = [access_grad_cache(var) for var in node.outputs]
    974 
    975             # list of bools indicating if each output is connected to the cost

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_grad_cache(var)
   1277                     for idx in node_to_idx[node]:
   1278 
-> 1279                         term = access_term_cache(node)[idx]
   1280 
   1281                         if not isinstance(term, gof.Variable):

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_term_cache(node)
    971             inputs = node.inputs
    972 
--> 973             output_grads = [access_grad_cache(var) for var in node.outputs]
    974 
    975             # list of bools indicating if each output is connected to the cost

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in <listcomp>(.0)
    971             inputs = node.inputs
    972 
--> 973             output_grads = [access_grad_cache(var) for var in node.outputs]
    974 
    975             # list of bools indicating if each output is connected to the cost

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_grad_cache(var)
   1277                     for idx in node_to_idx[node]:
   1278 
-> 1279                         term = access_term_cache(node)[idx]
   1280 
   1281                         if not isinstance(term, gof.Variable):

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gradient.py in access_term_cache(node)
   1111                                 str(g_shape))
   1112 
-> 1113                 input_grads = node.op.grad(inputs, new_output_grads)
   1114 
   1115                 if input_grads is None:

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\scan_module\scan_op.py in grad(self, inputs, dC_douts)
   2521 
   2522         local_op = Scan(inner_gfn_ins, inner_gfn_outs, info)
-> 2523         outputs = local_op(*outer_inputs)
   2524         if type(outputs) not in (list, tuple):
   2525             outputs = [outputs]

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\gof\op.py in __call__(self, *inputs, **kwargs)
    609         """
    610         return_list = kwargs.pop('return_list', False)
--> 611         node = self.make_node(*inputs, **kwargs)
    612 
    613         if config.compute_test_value != 'off':

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\scan_module\scan_op.py in make_node(self, *inputs)
    428         for inner_seq, outer_seq in zip(self.inner_seqs(self.inputs),
    429                                         self.outer_seqs(inputs)):
--> 430             new_inputs.append(format(outer_seq, as_var=inner_seq))
    431 
    432         argoffset += len(self.outer_seqs(inputs))

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\scan_module\scan_op.py in format(var, as_var)
    420                     broadcastable=(tuple(var.broadcastable[:1]) +
    421                                    tuple(as_var.broadcastable)))
--> 422                 rval = tmp.filter_variable(rval)
    423             return rval
    424 

C:\Users\msameen\AppData\Local\Continuum\Anaconda3\lib\site-packages\theano\tensor\type.py in filter_variable(self, other, allow_convert)
    231             dict(othertype=other.type,
    232                  other=other,
--> 233                  self=self))
    234 
    235     def value_validity_msg(self, a):

TypeError: Cannot convert Type TensorType(float64, 3D) (of Variable Subtensor{:int64:}.0) into Type TensorType(float64, (False, False, True)). You can try to manually convert Subtensor{:int64:}.0 into a TensorType(float64, (False, False, True)).

The updated code is as follows:

        self.embs = theano.shared(name='embeddings_source',
                                 value=0.2 * numpy.random.uniform(-1.0, 1.0,
                                 (ns, dembs))
                                 .astype(theano.config.floatX))
        self.embt = theano.shared(name='embeddings_target',
                                 value=0.2 * numpy.random.uniform(-1.0, 1.0,
                                 (nt+1, dembt))
                                 .astype(theano.config.floatX))
        self.vh = theano.shared(name='vh',
                                value=numpy.random.uniform(-1.0, 1.0,
                                 (nh,))
                                 .astype(theano.config.floatX))
        self.vx = theano.shared(name='vx',
                                value=numpy.random.uniform(-1.0, 1.0,
                                 (dembs,))
                                 .astype(theano.config.floatX))
        self.wc = theano.shared(name='wc',
                                value=0.2 * numpy.random.uniform(-1.0, 1.0,
                                (dembs, nh))
                                .astype(theano.config.floatX))
        self.wh = theano.shared(name='wh',
                                value=0.2 * numpy.random.uniform(-1.0, 1.0,
                                (nh, nh))
                                .astype(theano.config.floatX))
        self.wo = theano.shared(name='wo',
                               value=0.2 * numpy.random.uniform(-1.0, 1.0,
                               (nh, nt))
                               .astype(theano.config.floatX))
        self.wy = theano.shared(name='wy',
                                value=0.2 * numpy.random.uniform(-1.0, 1.0,
                                (dembt, nt))
                                .astype(theano.config.floatX))
        self.bx = theano.shared(name='bx',
                               value=numpy.zeros(1,
                               dtype=theano.config.floatX))
        self.bh = theano.shared(name='bh',
                                value=numpy.zeros(nh,
                                dtype=theano.config.floatX))
        self.bo = theano.shared(name='bo',
                               value=numpy.zeros(nt,
                               dtype=theano.config.floatX))
        self.h0 = theano.shared(name='h0',
                                value=numpy.zeros(nh,
                                dtype=theano.config.floatX))
        # end-snippet-2
        self.params = [self.embs, self.embt, self.vh, self.vx, self.wc, self.wh, self.wo,
                       self.wy, self.bx, self.bh, self.bo, self.h0]

        # start-snippet-3
        idxs = T.ivector()
        x = self.embs[idxs.dimshuffle('x',0)].reshape((idxs.shape[0], dembs))
        idxt = T.ivector()
        y = self.embt[idxt.dimshuffle('x',0)].reshape((idxt.shape[0], dembt))
        y0 = self.embt[-1]
        
        # end-snippet-3 start-snippet-4

        def calculate_beta(x, h_tm1):
            B_i=T.tanh(T.dot(h_tm1, self.vh) + T.dot(x, self.vx) + self.bx)
            return B_i
           
        def recurrence(h_tm1, y_tm1, x):
            beta, _ = theano.scan(fn=calculate_beta,
                                  sequences=x, 
                                  outputs_info=None, 
                                  non_sequences=h_tm1,
                                  n_steps=x.shape[0])                                 
            alpha_t = T.nnet.softmax(beta)       
            
            Z_t=T.dot(alpha_t,x)
            
            h_t = T.tanh(T.dot(h_tm1, self.wh) + T.dot(Z_t, self.wc) + self.bh)
            y_t = T.nnet.softmax(T.dot(h_t, self.wo) + T.dot(y_tm1, self.wy) + self.bo)
            
            return [h_t, y_t]
        
        [h, s], _ = theano.scan(fn=recurrence,
                                outputs_info=[self.h0.dimshuffle(0,'x'), y0.dimshuffle(0,'x')],
                                non_sequences=x,
                                n_steps=idxt.shape[0])
        
        p_y_given_x_sentence = s[:, 0, :]
        y_pred = T.argmax(p_y_given_x_sentence, axis=1)
        # end-snippet-4

        # cost and gradients and learning rate
        # start-snippet-5
        lr = T.dscalar('lr')

        sentence_nll = -T.mean(T.log(p_y_given_x_sentence)
                              [T.arange(idxt.shape[0]), idxt])
        
        sentence_gradients = T.grad(sentence_nll, self.params)
        sentence_updates = OrderedDict((p, p - lr*g) for p, g in zip(self.params, sentence_gradients))
        
        # end-snippet-5

        # theano functions to compile
        # start-snippet-6
        self.sentence_train = theano.function(inputs=[idxs, idxt, lr], 
                                              outputs=sentence_nll, 
                                              updates=sentence_updates)

**Comment by nouiz** [comment]
closing. We added better error message for case like this.

If you end up with such an error and don't understand the problem, open a new issue. Small difference in the code could request different error message.
