### ISSUE TITLE
theano equivalent of list comprehension + flatten

### ISSUE THREAD

**Issue by LindleyLentati** [Theano/Theano#4718]
Hi, I'm trying to implement the following:

	NVec = np.array([np.ones(1024)*sig for sig in noise]).flatten()
	Offs = np.array([np.ones(1024)*off for off in offset]).flatten()
	Amps = np.array([np.ones(1024)*amp for amp in amplitude]).flatten()

where noise, offset, and amplitude are theano vectors that contain free parameters from a PyMC3 likelihood.  When i try and do this I get the following:

    ValueError: length not known: offset [id A]

which I assume is because these vectors have no notion of length right?  I'm just wondering what the equivalent expression would be for use in theano.  Apologies if this is documented all over the place, I couldn't find an example that I could translate into what I wanted to do.

Many Thanks

**Comment by LindleyLentati** [comment]
So far the closest i've gotten is creating a list of tensors:

    [theano.tensor.ones(1024)*noise[i] for i in range(useToAs)]

but I cant seem to get them to concatenate into a single tensor.

**Comment by nouiz** [comment]
What this is supped to do? It seem pretty not efficient.

NVec = np.array([np.ones(1024)*sig for sig in noise]).flatten()

if noise is a numpy vector, you could do this:

>>> import numpy
>>> a=numpy.arange(4)
>>> numpy.repeat(a, 2)
array([0, 0, 1, 1, 2, 2, 3, 3])
>>> numpy.repeat(a, 2)

This in Theano would be:

>>> import theano
>>> v=theano.tensor.vector()
>>> v.repeat(4).eval({v:[2,3]})
array([ 2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.])

**Comment by LindleyLentati** [comment]
So the 'full' function is (currently):


    basic_model = Model()

    with basic_model:

	    Y_obs = 0
	

	    # Priors for unknown model parameters
	    amplitude = Normal('amplitude', mu=0, sd=10000, shape = useToAs)
	    offset = Normal('offset', mu=0, sd=10000, shape = useToAs)
	    noise = HalfNormal('noise', sd=10000, shape = useToAs)
	    phase = Normal('phase', mu=0, sd=1000)

           #Parameters for the two component gaussian
	    gsep    = Savex[1]*ReferencePeriod/1024
	    g1width = Savex[2]*ReferencePeriod/1024
	    g2width = Savex[3]*ReferencePeriod/1024
	    g2amp   = Savex[4]

	    for i in range(useToAs):
 
                   #Determine X axis for first gaussian
		    x = TBinTimes[i]-phase
		    x = ( x + ReferencePeriod/2) % (ReferencePeriod ) - ReferencePeriod/2

                    #Evaluate model for first gaussian with offset
		    s =  offset[i] + amplitude[i]*(np.exp(-0.5*(x)**2/Tg1width**2)) 

                   #Determine X axis for second gaussian
		    x = TBinTimes[i]-phase-Tgsep
		    x = ( x + ReferencePeriod/2) % (ReferencePeriod ) - ReferencePeriod/2

                   #Add model for second gaussian
		    s += amplitude[i]*Tg2amp*np.exp(-0.5*(x)**2/Tg2width**2)

		    # Likelihood (sampling distribution) of observations
		    Y_obs += Normal('Y_obs', mu=s, sd=noise[i], observed=ProfileData[i])


So, this is looping over a number of light curves (useToAs is the number), and fitting a joint model to those curves.  Each light curve has an amplitude, a noise level, and an offset.  Currently the code loops through these light curves, and sums up the likelihood.

I had hoped to remove the sum by doing something like:

    basic_model = Model()

    with basic_model:

	
            # Priors for unknown model parameters
	    amplitude = Normal('amplitude', mu=0, sd=10000, shape = useToAs)
	    offset = Normal('offset', mu=0, sd=10000, shape = useToAs)
	    noise = HalfNormal('noise', sd=10000, shape = useToAs)
	    phase = Normal('phase', mu=0, sd=1000)

            #Parameters for the two component gaussian
	    gsep    = Savex[1]*ReferencePeriod/1024
	    g1width = Savex[2]*ReferencePeriod/1024
	    g2width = Savex[3]*ReferencePeriod/1024
	    g2amp   = Savex[4]


            #Determine X axis for all light curves, evaluate model
	    x = TFlatTimes - phase
	    x = ( x + ReferencePeriod/2) % (ReferencePeriod ) - ReferencePeriod/2
	    FlatS = np.exp(-0.5*(x)**2/Tg1width**2)

           #Determine X axis for all light curves for second gaussian, add model
	    x = TFlatTimes-phase-Tgsep
	    x = ( x + ReferencePeriod/2) % (ReferencePeriod ) - ReferencePeriod/2
	    FlatS  += Tg2amp*np.exp(-0.5*(x)**2/Tg1width**2)

           #Get vector for total offsets, amplitudes and noise levels
           NVec = np.array([np.ones(1024)*sig for sig in noise]).flatten()
           Offs = np.array([np.ones(1024)*off for off in offset]).flatten()
           Amps = np.array([np.ones(1024)*amp for amp in amplitude]).flatten()

           #Construct total model
           Signal = Offs + Amps*FlatS
           Y_obs = Normal('Y_obs', mu=FlatS, sd=NVec,  observed=FlatData)

Is that clear at all?  I will look into the tile thing now.

Many Thanks

**Comment by LindleyLentati** [comment]
Ok, so I have this working with the repeat function:

```
basic_model = Model()

with basic_model:

	# Priors for unknown model parameters
	amplitude = Normal('amplitude', mu=0, sd=10000, shape = useToAs)
	offset = Normal('offset', mu=0, sd=10000, shape = useToAs)
	noise = HalfNormal('noise', sd=10000, shape = useToAs)
	#phase = Normal('phase', mu=0, sd=1000)
	phase = Uniform('phase', lower = 0, upper = ReferencePeriod)


	gsep    = Savex[1]*ReferencePeriod/1024
	g1width = Savex[2]*ReferencePeriod/1024
	g2width = Savex[3]*ReferencePeriod/1024
	g2amp   = Savex[4]


	Tg1width=theano.shared(g1width)
	Tg2width =theano.shared(g2width)
	Tg2amp=theano.shared(g2amp)
	Tgsep=theano.shared(gsep)

	x = TFlatTimes - phase
	x = ( x + ReferencePeriod/2) % (ReferencePeriod ) - ReferencePeriod/2
	FlatS = np.exp(-0.5*(x)**2/Tg1width**2)

	x = TFlatTimes-phase-Tgsep
	x = ( x + ReferencePeriod/2) % (ReferencePeriod ) - ReferencePeriod/2
	FlatS  += Tg2amp*np.exp(-0.5*(x)**2/Tg1width**2)


	NVec = theano.tensor.extra_ops.repeat(noise, 1024)
	Offs = theano.tensor.extra_ops.repeat(offset, 1024)
	Amps = theano.tensor.extra_ops.repeat(amplitude, 1024)

	Signal = Offs + Amps*FlatS

	# Likelihood (sampling distribution) of observations
	Y_obs = Normal('Y_obs', mu=Signal, sd=NVec, observed=FlatData)
```

Is there a much cleverer/faster way of writing this down though? Its still an order of magnitude slower than the C code I have that does similar things.

Cheers

**Comment by nouiz** [comment]
Can you use broadcasting instead of repeat? This could speed up computation
quite a lot.

**Comment by LindleyLentati** [comment]
Thanks, yes broadcasting it turns out makes it a lot faster, i've sped it up by alot in the last couple of days, but now have some issues with calculating gradients, for which i'll make a new post.
