### ISSUE TITLE
nvcc_compiler bug(theano 0.8.1 used in python3.x )

### ISSUE THREAD

**Issue by nightinwhite** [Theano/Theano#4721]
when I use theano 0.8.1 in python3.x, it will be wrong as "0xd5 " can't be encode by "utf-8" so I change that(in nvcc_compiler) :
# nvcc_stdout, nvcc_stderr = decode_iter(p.communicate()[:2])

```
        #2016.7.12
        bnvcc_stdout, bnvcc_stderr = p.communicate()[:2]
        nvcc_stdout = bnvcc_stdout.decode("windows-1252")
        nvcc_stderr = bnvcc_stderr.decode("windows-1252")
```

and it can finally run ,maybe it should be fixed or it just be a wrong in my code? 
ps(it runs in win7 and language is chinese)

**Comment by nouiz** [comment]
Can you try with the development version of Theano?

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Maybe it is fixed there.

**Comment by nightinwhite** [comment]
@nouiz thank you ! I have found it.

**Comment by nouiz** [comment]
does this fix your problem?
