### ISSUE TITLE
3d pooling on CPU

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4731]
cuDNN support 3d pooling, but we don't have a CPU implementation. Some people are using a graph of Op to generate that on CPU, but it causing that we don't use the cudnn 3d pooling and so end up being not efficient.

see gh-4377

A first quick version could be python only with only python code, so I tag it with Python code Only". But ideally we should have a C version.

**Comment by EugenePY** [comment]
Hi, @nouiz I'm currently work on this issue. I had read [gh-4377](https://github.com/Theano/Theano/issues/4377). We need to add 3d pooling support for theano.tesnsor.sinal.Pool and restricted to 5d tensor (which same with [cuDNN](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L558). Is that right?

**Comment by gvtulder** [comment]
Hi @EugenePY, have you had a look at the pull request #4884 linked above? There's code for 3D CPU pooling there.

**Comment by EugenePY** [comment]
@gvtulder yeah I just saw that. Thx !

**Comment by nouiz** [comment]
done by gh-4884
