### ISSUE TITLE
EquilibriumOptimizer maxed out in some tests

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#4734]
This test causes the problem for 'local_dimshuffle_lift':
`theano.tensor.signal.tests.test_pool.py:TestDownsampleFactorMax.test_infer_shape`

This test causes the problem for 'local_upcast_elemwise_constant_inputs':
`theano.tensor.nnet.tests.test_corr.py:TestCorr2D.test_infer_shape_forward`

**Comment by Sentient07** [comment]
Even `local_add_canonizer` has this problem. This is originating from this test, `theano.tensor.tests.test_opt.test_local_subtensor_merge`.

**Comment by ReyhaneAskari** [comment]
`theano.tensor.signal.tests.test_pool.py:TestDownsampleFactorMax.test_infer_shape` is no longer giving the error but both `theano.tensor.nnet.tests.test_corr.py:TestCorr2D.test_infer_shape_forward` and `theano.tensor.tests.test_opt.test_local_subtensor_merge` work when:

**THEANO_FLAGS**="optdb.max_use_ratio=**6**"

**Comment by nouiz** [comment]
Can you make a PR that change the default to 6 and make sure no other tests
raise error in that setup?

**Comment by lamblin** [comment]
Closed by #5435.
