### ISSUE TITLE
Run the buildbots with `on_opt_error=raise`

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#4735]
This would help catch optimization problems that don't necessarily make the tests fail.  We would have to make sure to fix the current problems first though.

**Comment by nouiz** [comment]
We should also make a way that EQ maxed out also make errors in buildbots/travis. I was told that on_opt_error=raise don't cause this.

Related: https://github.com/Theano/Theano/issues/4734

**Comment by nouiz** [comment]
This is done in jenkins and travis for a long time, so closing.
