### ISSUE TITLE
Theano does not use CUDA flags for cuDNN

### ISSUE THREAD

**Issue by ruslanagit** [Theano/Theano#4739]
This is an issue, similar to the 2nd issue mentioned in #2928 (fixed in #3664), when compiler-bindir was not used. 
In my setup I use flags to compile with CUDA:
[nvcc]
flags = --use-local-env  --cl-version=2010

Though cuDNN was properly installed, it was not seen by theano. After digging in, I have seen that params in dnn_available() method (in file theano\sandbox\cuda\__init__.py) does not include nvcc flags. 
Fixed manually, by appending appropriate flags to params just after the lines 
if config.nvcc.compiler_bindir:
                params.extend(['--compiler-bindir',
                               config.nvcc.compiler_bindir])
cuDNN works fine with this fix.

Please fix on main branch.

**Comment by nouiz** [comment]
Can you make a PR with the fix? This way you will get the credit for this
fix.

thanks.

**Comment by ruslanagit** [comment]
This is me first PR. Not sure if done correctly...
