### ISSUE TITLE
Import Error from fresh install

### ISSUE THREAD

**Issue by willgdjones** [Theano/Theano#4745]
I'm getting an import error when I run the mnist example script [https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py] with a fresh install on a GPU.

ImportError: ('The following error happened while compiling the node', Dot22(dense_input_1, dense_1_W), '\n', '/nfs/users/nfs_w/wj2/.theano/compiledir_Linux-3.2--generic-x86_64-with-Ubuntu-12.04-precise-x86_64-2.7.3-64/tmpoukhqK/e3c8de9d51e298a853a3dc6d24b85ffd.so: undefined symbol: _gfortran_transfer_integer_write', '[Dot22(dense_input_1, dense_1_W)]')

Any clues as to where to start? I have everything installed from the Theano installation page.

Seems like gfortran is not included in the version of Ubuntu I have installed (Ubuntu 12), however this should have been install with gcc.

Thanks

**Comment by willgdjones** [comment]
Seems to be a Theano issue and not Keras https://github.com/fchollet/keras/issues/3224

**Comment by nouiz** [comment]
Be sure to follow the instruction on that page for your verison of ubuntu.

http://deeplearning.net/software/theano/install_ubuntu.html

If that don't work, there is a section with a possible fix.
