### ISSUE TITLE
Is it possible that get all previous output at current timestep in scan?

### ISSUE THREAD

**Issue by junfenglx** [Theano/Theano#4753]
Suppose I have a function: F = f( g(h_{1:t-1}), x_t), g is another function,
I want to implement the function using scan.
How could I use taps to get all previous output?

I already know padding all sequence to same length, and using unroll scan
can solve the problem, but I don't want to padding and unroll scan.

Ideas are welcome.
 Thanks

I want to implement LSTMN described in the paper: http://arxiv.org/abs/1601.06733

Related issue: #4752

**Comment by nouiz** [comment]
No. Please use the theano-user mailing list for questions. I'll close this, in the other issue a work around is explained.
