### ISSUE TITLE
Documentation: Best way to install python packages

### ISSUE THREAD

**Issue by gokul-uf** [Theano/Theano#4754]
According to http://www.deeplearning.net/software/theano/install_ubuntu.html#install-ubuntu
Scipy, Numpy and other python libraries are installed via `apt-get`. This is not best practice as `pip` will not recognize the packages installed via `apt-get`. Additionally, `pip` usually has the latest stable versions of the packages while the LTS repos are almost always lagging behind.

Better instructions would be to install the dependencies like `gfortran` via `apt-get` and replace the `python-*` packages with `pip`.  This saves a lot of headaches (and weekends).

Source:
1. http://askubuntu.com/questions/21027/easy-install-pip-or-apt-get
2. http://askubuntu.com/questions/431780/apt-get-install-vs-pip-install

**Comment by nouiz** [comment]
I'm not opposed to this change, but do you know what happen if the user
already have python-numpy installed and we call pip install numpy?

I don't want the instruction to break current user setup.

Also, now that there is a conda package for Theano, I would have a tendency
to suggest conda first. What do you think?

https://github.com/conda-forge/staged-recipes/pull/574#issuecomment-234592160

**Comment by nouiz** [comment]
@fvisin what do you think of that? You are the last one to have touch the installation instruction and I forgot where it is now.

**Comment by fvisin** [comment]
We are in the process of modifying the installation instructions heavily in #4211. IIRC we suggest conda as default and only provide system-package information for experienced users, but it's a good point that I'll keep in mind.

**Comment by fvisin** [comment]
I recently opened a PR with an updated documentation in #4775. It should be a semi-final, almost ready to merge version. There are still some unaddressed points, but they will take time so I want to merge what we got and take care of those points in another PR. 

If you want, feel free to check it out and tell me if you feel something can be improved.

**Comment by lamblin** [comment]
The PR mentioned by @fvisin has been merged a while ago, so I'll consider this closed.
