### ISSUE TITLE
Pool_2D Grad Error - Tensor.zeros() vs numpy.zeros() difference

### ISSUE THREAD

**Issue by davidmascharka** [Theano/Theano#4761]
The gradient of `pool_2d` differs depending on whether the input is initialized with `tensor.zeros()` or with `theano.shared` using `np.zeros()`.

This is not specific to `zeros`. The same occurs when using `ones` and likely any value you like.

![bug](https://cloud.githubusercontent.com/assets/5611862/16957396/2a091e9c-4daa-11e6-9418-dd3185e2ccf6.png)

I think we should do one of the following:
- Make all the GPU and CPU implementation use the same behavor (which mean always use cudnn behavior)
- Document the strange difference and let it like this
- Allow the user to specify the behavior it have, which mean he could loose GPU pooling implementation until someone implement the other case.

**Comment by meowklaski** [comment]
I cannot reproduce this on theano 0.8.2, cpu-only. It may be a CUDA issue.

**Comment by davidmascharka** [comment]
On my machine, dev0.9 CPU-only does not have this problem.

**Comment by meowklaski** [comment]
I reproduced this error on theano 0.8.2 using Nvidia K2100M

**Comment by nouiz** [comment]
The case where there is multiple index with the same max value is a corner
case. We do not identify clearly what is done there.

From memory, old cudnn version was doing the same as on the CPU now, but
this have bad properties for training conv model, so it was changed. But I
could be wrong and it could be another implementation that did that.

You can try to disable cudnn pooling with this Theano flag:

optimizer_excluding=local_pool_dnn:local_pool_dnn_alternative:local_pool_dnn_grad:local_pool_dnn_grad_stride:local_avgpool_dnn_grad_stride

but if you do that, maybe your pooling will stay on the CPU as we don't
implement all pooling ourself that cudnn support.

**Comment by meowklaski** [comment]
I understand that this can create a difference between the CPU and CUDNN output.

Why, though, does he get different answers, all using CUDNN, simply based on the way he initializes his zeroed tensor?

**Comment by nouiz** [comment]
It depend of how the implementation is done.

In Theano, we take the output of the forward and compare it to all the
input value. If they are equal, we set 1.
Some implementation will save the index where the max value was. This only
allow to one value to be set to 1.

I think cudnn do like Theano, but stop when 1 value is set.

For the question, why there is a difference depending how it is built? I
needed to investigate to answer this question. The reason is that the last
case can and is constant folded. This mean, Theano detect that everything
is constant and compute the final answer during the compilation. This is
done before we move the computation on the GPU. So it give the same result
as if you ran on CPU.

**Comment by nouiz** [comment]
I updated the description with a few options of what could be done in Theano.

Why do you want/expected the last behavior? Why we should not switch all implementation to cuDNN behavior?

**Comment by davidmascharka** [comment]
The last behavior where we get a `1` in all the places would be technically correct, since all values in this case contribute to the maximum value (because they all _are_ the maximum). Picking one at random (or just the first) doesn't seem to be the correct way to do it.

Option 1 definitely seems reasonable. If cuDNN gives the first behavior, matching it in Theano would make some sense, even if that behavior may not be technically correct. Someone writing a new Op or extending functionality in some way could very easily run into issues where they expect output like cuDNN and don't get it, which leads to a terrible time trying to figure out why [[1]](https://github.com/davidmascharka).

Option 2 is not the way to go.

Option 3 would also be alright but is less preferable compared to 1 because it's a bit convoluted.

**Comment by nouiz** [comment]
Option 3 is just an extention of option 1. Mostly, we change the default on CPU to be like cudnn and keep the option via an option and comment that it don't work on GPU. This would be to allow more user choice.

There is another possible output, that you have .25,.25, .25., .25 on each input. I don't know if it would be useful.

**Comment by davidmascharka** [comment]
I think Option 3 is fair as long as it's clearly documented.

I'd be very confused by splitting the gradient into `0.25` for each input, given the gradient for a max operation only makes sense as either `0` or `1`.

**Comment by meowklaski** [comment]
^ seconded

**Comment by nouiz** [comment]
I don't think we have time to fix this for 0.9 release, but i schedule it for 0.10. No timeline, but I would like to have that fixed for 0.10.

**Comment by aam-at** [comment]
Is anyone working on it?

**Comment by nouiz** [comment]
No. We are doing a release candiate now. We won't change that before the
release.

Do we have an agreement that by default we should go with setting one to
only 1 values and document that?  @lamblin? If so, you could start to work
on that.

**Comment by aam-at** [comment]
@nouiz I changed the behavior of pooling to match `cudnn` in #5506. Is that pull request still relevant?

**Comment by nouiz** [comment]
This is still needed. As for overloaded with the release and now nips
deadline and GTC. We will get to it and sorry about the delay!

Le mar. 9 mai 2017 22:09, Alexander Matyasko <notifications@github.com> a
écrit :
