### ISSUE TITLE
Runtime completely dominated by GPUJoin in Roll.  Suggestions welcome.

### ISSUE THREAD

**Issue by LindleyLentati** [Theano/Theano#4762]
Hi, I'm trying to write a function that uses the roll method.  In particular I have an NxM matrix, and I want to loop through the N-dimension, applying a roll along the M-axis, where the amount rolled depends on which entry along the N direction you are on.  The relevant subset of the code is below.

IVec is the NxM matrix, and the function RVec iterates over that performing a roll.  This is then used to calculate a likelihood beneath.

```
IVec = tt.dot(TInterpBasis[IBin],ShapeCoeff)

def RVec(iv):
        for i in range(N):
                iv=tt.set_subtensor(iv[i], tt.roll(iv[i], -WBT[i]))
        return iv

lfunc = -0.5*tt.sum(((AmpParams*RVec(IVec)+OffParams-TData)/SigParams)**2-1)

ReturnLFunc = theano.function(inputs=[tp],outputs= lfunc, name='ReturnLFunc')

```

The problem is that the run time is totally dominated by the GPUJoin method.  The output of the profile for the function ReturnLFunc after  calling it 1000 times, with N=100 is below.  Do you have any suggestions for how to rewrite this to make it less dependent on GPUJoin?

Many Thanks
# Function profiling

  Message: ReturnLFunc
  Time in 1000 calls to Function.**call**: 2.952008e+01s
  Time in Function.fn.**call**: 2.945256e+01s (99.771%)
  Time in thunks: 2.029642e+01s (68.755%)
  Total compile time: 1.323349e+01s
    Number of Apply nodes: 638
    Theano Optimizer time: 1.066999e+01s
       Theano validate time: 1.154151e+00s
    Theano Linker time (includes C, CUDA code generation/compiling): 7.844720e-01s
       Import time 8.336782e-02s

Time in all call to theano.grad() 0.000000e+00s
Time since theano import 111.982s
## Class

<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  82.6%    82.6%      16.764s       1.68e-04s     C   100000     100   theano.sandbox.cuda.basic_ops.GpuJoin
   8.5%    91.1%       1.720s       1.72e-05s     C   100000     100   theano.sandbox.cuda.basic_ops.GpuIncSubtensor
   1.8%    92.8%       0.358s       3.58e-04s     C     1000       1   theano.sandbox.cuda.basic_ops.GpuAdvancedSubtensor1
   1.7%    94.6%       0.351s       1.75e-06s     C   201000     201   theano.sandbox.cuda.basic_ops.GpuSubtensor
   0.9%    95.5%       0.191s       1.91e-04s     C     1000       1   theano.sandbox.cuda.blas.GpuGemv
   0.9%    96.4%       0.173s       1.73e-06s     C   100000     100   theano.tensor.subtensor.Subtensor
   0.8%    97.2%       0.166s       1.66e-04s     C     1000       1   theano.sandbox.cuda.basic_ops.GpuCAReduce
   0.8%    98.0%       0.159s       3.97e-05s     C     4000       4   theano.sandbox.cuda.basic_ops.GpuElemwise
   0.7%    98.6%       0.137s       1.37e-04s     C     1000       1   theano.sandbox.cuda.basic_ops.GpuAllocEmpty
   0.6%    99.3%       0.131s       2.62e-05s     C     5000       5   theano.sandbox.cuda.basic_ops.HostFromGpu
   0.3%    99.6%       0.061s       2.03e-05s     C     3000       3   theano.sandbox.cuda.basic_ops.GpuFromHost
   0.3%    99.9%       0.058s       5.82e-07s     C   100000     100   theano.tensor.basic.ScalarFromTensor
   0.0%    99.9%       0.009s       1.53e-06s     C     6000       6   theano.tensor.elemwise.Elemwise
   0.0%    99.9%       0.006s       1.28e-06s     C     5000       5   theano.sandbox.cuda.basic_ops.GpuDimShuffle
   0.0%   100.0%       0.006s       1.90e-06s     C     3000       3   theano.sandbox.cuda.basic_ops.GpuReshape
   0.0%   100.0%       0.003s       1.03e-06s     C     3000       3   theano.tensor.opt.MakeVector
   0.0%   100.0%       0.003s       7.51e-07s     C     4000       4   theano.compile.ops.Shape_i
   ... (remaining 0 Classes account for   0.00%(0.00s) of the runtime)
## Ops

<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Op name>
  82.6%    82.6%      16.764s       1.68e-04s     C     100000      100   GpuJoin
   8.5%    91.1%       1.720s       1.72e-05s     C     100000      100   GpuIncSubtensor{InplaceSet;int64}
   1.8%    92.8%       0.358s       3.58e-04s     C     1000        1   GpuAdvancedSubtensor1
   1.3%    94.1%       0.257s       2.57e-06s     C     100000      100   GpuSubtensor{int64, int64:int32:}
   0.9%    95.0%       0.191s       1.91e-04s     C     1000        1   GpuGemv{inplace}
   0.9%    95.9%       0.173s       1.73e-06s     C     100000      100   Subtensor{int64}
   0.8%    96.7%       0.166s       1.66e-04s     C     1000        1   GpuCAReduce{add}{1,1}
   0.7%    97.4%       0.137s       1.37e-04s     C     1000        1   GpuAllocEmpty
   0.6%    98.0%       0.131s       2.62e-05s     C     5000        5   HostFromGpu
   0.5%    98.5%       0.092s       9.18e-07s     C     100000      100   GpuSubtensor{int64, int32::}
   0.3%    98.8%       0.069s       3.47e-05s     C     2000        2   GpuElemwise{mul,no_inplace}
   0.3%    99.1%       0.061s       2.03e-05s     C     3000        3   GpuFromHost
   0.3%    99.4%       0.058s       5.82e-07s     C     100000      100   ScalarFromTensor
   0.3%    99.7%       0.056s       5.59e-05s     C     1000        1   GpuElemwise{Composite{(i0 + sqr(((((i1 \* i2) + i3) - i4) / i5)))},no_inplace}
   0.2%    99.9%       0.034s       3.37e-05s     C     1000        1   GpuElemwise{Composite{((((i0 - i1) + i2) % i3) - i2)},no_inplace}
   0.0%    99.9%       0.006s       1.90e-06s     C     3000        3   GpuReshape{2}
   0.0%    99.9%       0.003s       1.06e-06s     C     3000        3   GpuDimShuffle{x}
   0.0%    99.9%       0.003s       1.03e-06s     C     3000        3   MakeVector{dtype='int64'}
   0.0%    99.9%       0.003s       2.88e-06s     C     1000        1   Elemwise{Composite{Cast{int32}(((i0 % i1) / i2))}}
   0.0%    99.9%       0.003s       2.54e-06s     C     1000        1   GpuSubtensor{::, int64}
   ... (remaining 10 Ops account for   0.06%(0.01s) of the runtime)
## Apply

<% time> <sum %> <apply time> <time per call> <#call> <id> <Apply name>
   1.8%     1.8%       0.358s       3.58e-04s   1000    29   GpuAdvancedSubtensor1(<CudaNdarrayType(float32, 3D)>, Elemwise{Cast{int64}}.0)
   0.9%     2.7%       0.191s       1.91e-04s   1000   231   GpuGemv{inplace}(GpuAllocEmpty.0, TensorConstant{1.0}, GpuReshape{2}.0, GpuDimShuffle{0}.0, TensorConstant{0.0})
   0.9%     3.6%       0.181s       1.81e-04s   1000   236   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     4.4%       0.170s       1.70e-04s   1000   240   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     5.3%       0.170s       1.70e-04s   1000   428   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     6.1%       0.170s       1.70e-04s   1000   244   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     6.9%       0.168s       1.68e-04s   1000   260   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     7.8%       0.168s       1.68e-04s   1000   248   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     8.6%       0.168s       1.68e-04s   1000   420   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%     9.4%       0.168s       1.68e-04s   1000   264   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    10.3%       0.168s       1.68e-04s   1000   312   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    11.1%       0.168s       1.68e-04s   1000   292   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    11.9%       0.168s       1.68e-04s   1000   440   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    12.7%       0.168s       1.68e-04s   1000   388   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    13.6%       0.168s       1.68e-04s   1000   484   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    14.4%       0.168s       1.68e-04s   1000   436   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    15.2%       0.168s       1.68e-04s   1000   308   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    16.0%       0.168s       1.68e-04s   1000   372   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    16.9%       0.168s       1.68e-04s   1000   392   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   0.8%    17.7%       0.168s       1.68e-04s   1000   408   GpuJoin(TensorConstant{0}, GpuSubtensor{int64, int32::}.0, GpuSubtensor{int64, int64:int32:}.0)
   ... (remaining 618 Apply instances account for 82.30%(16.70s) of the runtime)

**Comment by nouiz** [comment]
the GPUJoin come from the roll.

Can you chagne the code so to not do a loop for N iteration? What are the
possible values of WBT? How htey are organized? Are they constant? If this
take only a few possible values, then you could make a version that call
roll less often.

Fred

**Comment by nouiz** [comment]
Closing as no news. This related issue is about making a new OP that would help this case:

https://github.com/Theano/Theano/issues/4762
