### ISSUE TITLE
Problem occurred when import theano 

### ISSUE THREAD

**Issue by Danni3l** [Theano/Theano#4778]
I'm on windows 10, and when ever i try to "import theano" i get this error :
I tested g++, it can be executed on my cmd.. I don't know what to do

`
===============================
Problem occurred during compilation with the command line below:
C:\MinGW\bin\g++.exe -shared -g -shared -I[MinGW directory]\include -L[Python directory]\libs -lpython34 -DMS_WIN64 -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx -mno-clzero -mno-pku --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Users\danie\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\danie\Anaconda2\include -IC:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof -o C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-2.7.12-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-2.7.12-64\lazylinker_ext\mod.cpp -LC:\Users\danie\Anaconda2\libs -LC:\Users\danie\Anaconda2 -lpython27
g++.exe: error: directory]\include: No such file or directory
g++.exe: error: directory]\libs: No such file or directory

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-3397704bd624> in <module>()
----> 1 import theano

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\__init__.pyc in <module>()
     68     object2, utils)
     69
---> 70 from theano.compile import (
     71     SymbolicInput, In,
     72     SymbolicOutput, Out,

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\__init__.py in <module>()
      8         SpecifyShape, specify_shape, register_specify_shape_c_code)
      9
---> 10 from theano.compile.function_module import *
     11
     12 from theano.compile.mode import *

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\function_module.py in <module>()
     19 from theano.compat import izip
     20 from theano.gof import graph
---> 21 import theano.compile.mode
     22 from theano.compile.io import (
     23     In, SymbolicInput, SymbolicOutput)

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\mode.py in <module>()
     10 import theano
     11 from theano import gof
---> 12 import theano.gof.vm
     13 from theano.configparser import config
     14 from theano.compile.ops import _output_guard

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\vm.py in <module>()
    652
    653 try:
--> 654     from . import lazylinker_c
    655
    656     class CVM(lazylinker_c.CLazyLinker, VM):

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\lazylinker_c.py in <module>()
    125             args = cmodule.GCC_compiler.compile_args()
    126             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 127                                              preargs=args)
    128             # Save version into the __init__.py file.
    129             init_py = os.path.join(loc, '__init__.py')

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cmodule.pyc in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2297             # difficult to read.
   2298             raise Exception('Compilation failed (return status=%s): %s' %
-> 2299                             (status, compile_stderr.replace('\n', '. ')))
   2300         elif config.cmodule.compilation_warning and compile_stderr:
   2301             # Print errors just below the command line.

. g++.exe: error: directory]\libs: No such file or directoryror: directory]\include: No such file or directory
`

**Comment by ruslanagit** [comment]
I think it's a configuration problem.
Do you have cxxflags  in your .theanorc file?
Do you mistakenly have them set to " -I**[MinGW directory]**\include -L**[Python directory]**\libs " ?
Try to put real paths instead.

**Comment by Danni3l** [comment]
when you say .teanorc file do you mean here ? 
`C:\Users\danie\Anaconda2\Lib\site-packages\theano` ?

I have to put it in that way ?
 -IC:\MinGW\bin\include -LC:\Users\danie\Anaconda2\libs

**Comment by ruslanagit** [comment]
.theanorc file is found in %userprofile% directory. In my case it's "C:\Users\[user name]"

For the include directory - if your g++ has path C:\MinGW\bin\g++.exe 
Then, you should have -IC:\MinGW\include

Also, from the error message it looks like python libs are already detected and included automatically, so I would remove the -L option from cxxflags

**Comment by Danni3l** [comment]
I found it ! it look like this: 
`[blas]
ldflags = 
[gcc]
cxxflags = -shared -I[MinGW directory]\include -L[Python directory]\libs -lpython34 -DMS_WIN64`

so I've change it: 
`[blas]
ldflags = 
[gcc]
cxxflags = -shared -I-IC:\MinGW\include -lpython34 -DMS_WIN64` 

is that correct ? 
when i try to import theano with this configuration i get this error : 

`Problem occurred during compilation with the command line below:
C:\MinGW\bin\g++.exe -shared -g -shared -IC:\MinGW\include -lpython34 -DMS_WIN64 -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx -mno-clzero -mno-pku --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=3072 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Users\danie\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\danie\Anaconda2\include -IC:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof -o C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-2.7.12-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-2.7.12-64\lazylinker_ext\mod.cpp -LC:\Users\danie\Anaconda2\libs -LC:\Users\danie\Anaconda2 -lpython27
In file included from C:/MinGW/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/math.h:36:0,
                 from C:\Users\danie\Anaconda2\include/pyport.h:325,
                 from C:\Users\danie\Anaconda2\include/Python.h:58,
                 from C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-2.7.12-64\lazylinker_ext\mod.cpp:1:
C:/MinGW/lib/gcc/x86_64-w64-mingw32/6.1.0/include/c++/cmath:1133:11: error: '::hypot' has not been declared
   using ::hypot;
           ^~~~~

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-3397704bd624> in <module>()
----> 1 import theano

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\__init__.pyc in <module>()
     68     object2, utils)
     69
---> 70 from theano.compile import (
     71     SymbolicInput, In,
     72     SymbolicOutput, Out,

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\__init__.py in <module>()
      8         SpecifyShape, specify_shape, register_specify_shape_c_code)
      9
---> 10 from theano.compile.function_module import *
     11
     12 from theano.compile.mode import *

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\function_module.py in <module>()
     19 from theano.compat import izip
     20 from theano.gof import graph
---> 21 import theano.compile.mode
     22 from theano.compile.io import (
     23     In, SymbolicInput, SymbolicOutput)

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\mode.py in <module>()
     10 import theano
     11 from theano import gof
---> 12 import theano.gof.vm
     13 from theano.configparser import config
     14 from theano.compile.ops import _output_guard

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\vm.py in <module>()
    652
    653 try:
--> 654     from . import lazylinker_c
    655
    656     class CVM(lazylinker_c.CLazyLinker, VM):

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\lazylinker_c.py in <module>()
    125             args = cmodule.GCC_compiler.compile_args()
    126             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 127                                              preargs=args)
    128             # Save version into the __init__.py file.
    129             init_py = os.path.join(loc, '__init__.py')

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cmodule.pyc in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2297             # difficult to read.
   2298             raise Exception('Compilation failed (return status=%s): %s' %
-> 2299                             (status, compile_stderr.replace('\n', '. ')))
   2300         elif config.cmodule.compilation_warning and compile_stderr:
   2301             # Print errors just below the command line.

Exception: Compilation failed (return status=1): In file included from C:/MinGW/lib/gcc/x86_64-w64-mingw32/6.1.0/include.                  from C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_S.            ^~~~~;x86_64-w64-mingw32/6.1.0/include/c++/cmath:1133:11: error: '::hypot' has not been declared`

**Comment by ruslanagit** [comment]
You get this error, because you include mingw include folder.
This happened to me as well. You need to use TDM GCC include folders (there are 2).
So, try to:
1. Install TDM-GCC (**uncheck add to path option**), if not already installed
2. Update cssflags to include
-I"[TDM-GCC path]\include" -I"[TDM-GCC path]\x86_64-w64-mingw32\include" 
instead of mingw include
3. Verify that TDM is not in path

**Comment by ruslanagit** [comment]
Also, in your cssflags there is "-lpython34" options, whereas from error message it looks like theano tries to link with python 2.7 libraries. So you might have a conflict here as well.
I think it's better to remove "-lpython34" from cxxflags.

**Comment by Danni3l** [comment]
I want to run my code into python 2.7 at first, is that possible ? 
I already have TDM-GCC, and when you talk about PATH, you mean the environment variable ?
I'm not sure how to add TDM in my cxxflags, i juste add this line ?
-I"[TDM-GCC path]\include" -I"[TDM-GCC path]\x86_64-w64-mingw32\include"

**Comment by ruslanagit** [comment]
> I want to run my code into python 2.7 at first, is that possible ? 

It should be.
> I already have TDM-GCC, and when you talk about PATH, you mean the environment variable ?

Yes
> I'm not sure how to add TDM in my cxxflags, i juste add this line ?
 -I"[TDM-GCC path]\include" -I"[TDM-GCC path]\x86_64-w64-mingw32\include" 

You should have this in your .theanorc file
**[gcc]
cxxflags = -shared  -I"[TDM-GCC path]\include" -I"[TDM-GCC path]\x86_64-w64-mingw32\include" -DMS_WIN64**
where [TDM-GCC path] is the path on your system to TDM-GCC (where there are bin, include, etc.)
Note, you have to include 2 directories for TDM

**Comment by Danni3l** [comment]
this is my .theanorc file now is it correct ? 
```
[gcc]
cxxflags = -shared -I"C:\TDM-GCC-64\bin\include" -I"C:\TDM-GCC-64\bin\x86_64-w64-mingw32\include" -DMS_WIN64
```

**Comment by Danni3l** [comment]
with this configuration, i got an error when i try to import : 
```
Exception                                 Traceback (most recent call last)
<ipython-input-1-3397704bd624> in <module>()
----> 1 import theano

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\__init__.pyc in <module>()
     68     object2, utils)
     69
---> 70 from theano.compile import (
     71     SymbolicInput, In,
     72     SymbolicOutput, Out,

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\__init__.py in <module>()
      8         SpecifyShape, specify_shape, register_specify_shape_c_code)
      9
---> 10 from theano.compile.function_module import *
     11
     12 from theano.compile.mode import *

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\function_module.py in <module>()
     19 from theano.compat import izip
     20 from theano.gof import graph
---> 21 import theano.compile.mode
     22 from theano.compile.io import (
     23     In, SymbolicInput, SymbolicOutput)

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\compile\mode.py in <module>()
     10 import theano
     11 from theano import gof
---> 12 import theano.gof.vm
     13 from theano.configparser import config
     14 from theano.compile.ops import _output_guard

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\vm.py in <module>()
    652
    653 try:
--> 654     from . import lazylinker_c
    655
    656     class CVM(lazylinker_c.CLazyLinker, VM):

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\lazylinker_c.py in <module>()
    125             args = cmodule.GCC_compiler.compile_args()
    126             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 127                                              preargs=args)
    128             # Save version into the __init__.py file.
    129             init_py = os.path.join(loc, '__init__.py')

C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cmodule.pyc in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2297             # difficult to read.
   2298             raise Exception('Compilation failed (return status=%s): %s' %
-> 2299                             (status, compile_stderr.replace('\n', '. ')))
   2300         elif config.cmodule.compilation_warning and compile_stderr:
   2301             # Print errors just below the command line.

Exception: Compilation failed (return status=1): In file included from C:/MinGW/lib/gcc/x86_64-w64-mingw32/6.1.0/include.                  from C:\Users\danie\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_69_S.            ^~~~~;x86_64-w64-mingw32/6.1.0/include/c++/cmath:1133:11: error: '::hypot' has not been declared
```

also, i don't understand why do we have to add the "\include" ?
what does it mean ? because i'm my  "C:\TDM-GCC-64\bin" in the bin folder i don't have any include ?

**Comment by ruslanagit** [comment]
I think you should remove 'bin' from both paths.

**Comment by ruslanagit** [comment]
include directory is where the h files with all the definitions and declarations are found. 
Compiler needs to know where to look for those.

**Comment by Danni3l** [comment]
It works, I can now import Theano without getting an error ! 
But when i run in the shell `theano.tests()` it get stuck in a loop:
```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: DimShuffle{x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\opt.py", line 1820, in process_node
    replacements = lopt.transform(node)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\tensor\opt.py", line 6099, in constant_folding
    no_recycling=[])
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\op.py", line 975, in make_thunk
    no_recycling)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\op.py", line 875, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cc.py", line 1189, in make_thunk
    keep_lock=keep_lock)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cc.py", line 1130, in __compile__
    keep_lock=keep_lock)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cc.py", line 1585, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cmodule.py", line 1145, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cc.py", line 1491, in compile_cmodule
    preargs=preargs)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cmodule.py", line 2308, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\danie\Anaconda2\lib\site-packages\theano-0.9.0.dev2-py2.7.egg\theano\gof\cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('DLL load failed: La proc\xe9dure sp\xe9cifi\xe9e est introuvable.', '[DimShuffle{x}(TensorConstant{1.0})]')
...
...
```

**Comment by Danni3l** [comment]
I got the same loop of error when i try to run my code (using keras)
I'm on a Surface Pro 3 i5-4300U, 8 G of RAM, runing on Windows 10

**Comment by ruslanagit** [comment]
Try to check your PATH variable.
Verify that only mingw directory is there, and remove TDM from your path if its there.
Tip: you can run 
_echo %PATH%_
and see what you get. This way you know exactly what your PATH is in your **theano environment**.

**Comment by Danni3l** [comment]
I've run `echo %PATH%` this is what i've got: 

```
C:\Users\danie\Anaconda2;
C:\Users\danie\Anaconda2\Library\mingw-w64\bin;
C:\Users\danie\Anaconda2\Library\usr\bin;
C:\Users\danie\Anaconda2\Library\bin;
C:\Users\danie\Anaconda2\Scripts;
C:\Program Files\Git\cmd;C:\MinGW\bin;
C:\ProgramData\Oracle\Java\javapath;
C:\WINDOWS\system32;C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files\MATLAB\R2015b\runtime\win64;
C:\Program Files\MATLAB\R2015b\bin;
C:\Program Files\MATLAB\R2015b\polyspace\bin;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\MinGW\bin\g++.exe;
C:\Users\danie\Anaconda2;
C:\Users\danie\Anaconda2\Scripts;
C:\Users\danie\Anaconda2\Library\bin;
C:\Users\danie\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\vcvarsall.bat;
C:\Users\danie\AppData\Local\Enthought\Canopy\User\Scripts;
c:\users\danie\appdata\local\enthought\canopy\user\scripts;
C:\Users\danie\AppData\Local\Enthought\Canopy\User;
C:\Users\danie\pyenv\MinGW\bin
```

i'm confuse because when i go to >control panel> system> advanced system> settings environment variables 
I don't have all those PATH, should i erase some of them ?

**Comment by ruslanagit** [comment]
It looks like a mess - your have 3 different mingw locations in your path. 
Try to leave only one.

**Comment by Danni3l** [comment]
My environement is on `C:\Users\danie\Anaconda2`
So i can erase all MinGW who isn't there ? like 
```
C:\Users\danie\pyenv\MinGW\bin
C:\MinGW\bin
C:\MinGW\bin\g++.exe
```

**Comment by ruslanagit** [comment]
> So i can erase all MinGW who isn't there ?

I would definitely start from this.

**Comment by Danni3l** [comment]
Thank you ! 
It's working well, i can now import theano and run my code

**Comment by Statham-stone** [comment]
this may help:

http://stackoverflow.com/questions/38536788/g-error-on-import-of-theano-on-windows-7

**Comment by surajpadhy** [comment]
@ruslanagit Thanks. Your suggestion of installing TDM-GCC solved my issue. was getting same error as others (Compilation failed). 
-Was using MinGW 64
-Removed MinGW from environment variables
-Installed TDM-GCC 32bit. Installing 64bit was getting download error.
Able to import theano after the above steps. 

![image](https://user-images.githubusercontent.com/3975878/43268517-7ff40ade-910e-11e8-9b78-bdf8b6259136.png)
