### ISSUE TITLE
Bug: "The type of the replacement must be compatible with the type of the original Variable"

### ISSUE THREAD

**Issue by yangwenz** [Theano/Theano#4782]
The following program reports:

"<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Alloc.0, Alloc.0, TensorType(float64, (False, True, False, False)), TensorType(float64, 4D), 'MergeOptimizer') MergeOptimizer"

Is this a bug in merge optimizer?

-------------------------------------------------------------------------------------------

import theano.tensor as T
import lasagne, numpy, theano

DATA_TYPE = theano.config.floatX

class TestLayer(lasagne.layers.Layer):
    
    def __init__(self, input_layer, batch_size, x_size, y_size, n_hidden,
                 W_init=lasagne.init.GlorotUniform(), 
                 b_init=lasagne.init.Constant(0.0),
                 nonlinearity=lasagne.nonlinearities.rectify,
                 hid_init=lasagne.init.Constant(0.0), **argv):
        
        super(TestLayer, self).__init__(input_layer, **argv)
        self.batch_size = batch_size
        self.x_size = x_size
        self.y_size = y_size
        self.n_hidden = n_hidden
        self.nonlinearity = nonlinearity
        
        self.W_1 = self.add_param(W_init, (x_size, self.n_hidden), name='W_1')
        self.b_1 = self.add_param(b_init, (self.n_hidden,), name='b_1', regularizable=False)
        self.W_2 = self.add_param(W_init, (self.n_hidden+y_size, self.n_hidden), name='W_2')
        self.b_2 = self.add_param(b_init, (self.n_hidden,), name='b_2', regularizable=False)
        
        self.M_init = self.add_param(lasagne.init.Constant(1e-6), shape=(10, 10), name='M_init', trainable=False, regularizable=False)
        self.h_init = self.add_param(hid_init, (1, self.n_hidden), name='hid_init', trainable=False, regularizable=False)
        
    def get_params(self, **tags):
        params = super(TestLayer, self).get_params(**tags)
        return params

    def get_output_shape_for(self, input_shape):
        return (input_shape[0], input_shape[1], self.n_hidden)
    
    def get_output_for(self, input_var, **kwargs):
        
        input_var = input_var.dimshuffle(1, 0, 2)
        xs = input_var[:, :, T.arange(self.x_size)]
        ys = input_var[:, :, T.arange(self.x_size, self.x_size+self.y_size)]

        # (1) After removing M or setting M=None, the bug hides.
        # (2) After changing "step" into a single-layer neural network like h = T.dot(x, self.W_1) + self.b_1, the bug disappears.
        def step(x, y, h, M, *params):
            o = T.dot(x, self.W_1) + self.b_1
            z = T.concatenate([o, y], axis=1)
            h = T.dot(z, self.W_2) + self.b_2
            return [h, M]
        
        h_init = T.tile(self.h_init, (batch_size, 1))
        h_init = T.unbroadcast(h_init, 0)
        M_init = T.tile(self.M_init, (self.batch_size, 1, 1))
        M_init = T.unbroadcast(M_init, 0)
        
        non_seqs = self.get_params()
        hids, _ = theano.scan(fn=step, sequences=[xs, ys], 
                              outputs_info=[h_init, M_init],
                              non_sequences=non_seqs, strict=True)
        return hids[0].dimshuffle(1, 0, 2)

if __name__ == "__main__":

    batch_size = 1
    x_size = 8
    y_size = 2
    n_hidden = 100
    n_output = 5

    x = T.tensor3('x', dtype=DATA_TYPE)
    y = T.tensor3('y', dtype=DATA_TYPE)
    
    input_layer = lasagne.layers.InputLayer(shape=(batch_size, None, x_size+y_size), input_var=x)
    test_layer = TestLayer(input_layer=input_layer, batch_size=batch_size, x_size=x_size, y_size=y_size, n_hidden=n_hidden)

    output_layer = lasagne.layers.ReshapeLayer(test_layer, (-1, n_hidden))
    output_layer = lasagne.layers.DenseLayer(output_layer, n_output, nonlinearity=lasagne.nonlinearities.tanh)
    output_layer = lasagne.layers.ReshapeLayer(output_layer, (batch_size, x.shape[1], n_output))
    
    prediction = lasagne.layers.get_output(output_layer, deterministic=True)
    loss = T.mean(lasagne.objectives.squared_error(prediction, y))
    params = lasagne.layers.get_all_params(output_layer, trainable=True)
    updates = lasagne.updates.rmsprop(loss, params, learning_rate=1e-3)
    
    train_fn = theano.function([x, y], outputs=loss, updates=updates)
    loss_fn = theano.function([x, y], outputs=loss)
    
    a = numpy.asarray(numpy.random.rand(batch_size, 5, x_size+y_size), dtype=DATA_TYPE)
    b = numpy.asarray(numpy.random.rand(batch_size, 5, n_output), dtype=DATA_TYPE)
    print(train_fn(a, b))
    print(loss_fn(a, b))

**Comment by nouiz** [comment]
Can you give the full error message?

**Comment by yangwenz** [comment]
Hi, here is the error message:

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Alloc.0, Alloc.0, TensorType(float64, (False, True, False, False)), TensorType(float64, 4D), 'MergeOptimizer') MergeOptimizer
ERROR (theano.gof.opt): SeqOptimizer apply MergeOptimizer
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\theano\gof\opt.py", line 230, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\Python34\lib\site-packages\theano\gof\opt.py", line 89, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "C:\Python34\lib\site-packages\theano\gof\opt.py", line 817, in apply
    fgraph.replace_all_validate(pairs, 'MergeOptimizer')
  File "C:\Python34\lib\site-packages\theano\gof\toolbox.py", line 309, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\Python34\lib\site-packages\theano\gof\fg.py", line 561, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Alloc.0, Alloc.0, TensorType(float64, (False, True, False, False)), TensorType(float64, 4D), 'MergeOptimizer')

**Comment by nouiz** [comment]
I can't reproduce it. Can you update Theano to the dev version:

http://www.deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions


It is probably already fixed. If you still have it, then give me the Theano
flags that you are using.

**Comment by yangwenz** [comment]
Thanks very much. The problem is solved. 
Theano 0.8.2 has this bug. The latest version Theano 0.9.0 fixed this problem.
