### ISSUE TITLE
Follow up to the work done in the new Multiple Optimizer

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4786]
This issue is about the To-do list of the tasks that needs to be done on the PR. This PR (mentioned above) is about trying multiple optimizers to a node even after the node is optimized, till the point no  optimizers could optimize the node. 
This refers to the Optimizer being built in https://github.com/nouiz/Theano/pull/45
- [ ] All optimization to be applied to a node by default irrespective of whether it is deorated with the new optimizer or not. Mostly, change LocalOptGroup to always do all optimization and do it multiple time.

**Comment by Sentient07** [comment]
@nouiz do we also have this behaviour for `EquilibriumOptimizer` ?

**Comment by nouiz** [comment]
No.

**Comment by Sentient07** [comment]
Then do we also aim to change the behaviour of `canonicalize`/ `EquilibriumOptimizer` to do multiple optimization to a node ?

**Comment by nouiz** [comment]
It already does it. It add the new nodes in the list of nodes it will optimize. But we could change the logic to do it now instead of adding it at the end. This would also allow to apply a few optimization at the same time. I'm not sure I would like this, so I would start by tring to do it right now. This could cut the number of iteration we do.

**Comment by Sentient07** [comment]
> It already does it. It add the new nodes in the list of nodes it will optimize. But we could change the logic to do it now instead of adding it at the end.

The current way of working is, it optimizes the node, then reiterates the graph to see if any further iptimization could be applied and keeps doing this till all the nodes are optimized, right ? This logic is what you'd like to change to optimizing a node to the maximum possible level before proceeding to the next, right ?

**Comment by nouiz** [comment]
The logic is complicated and not well documented. Ask me again next week to document that.
