### ISSUE TITLE
Stuck at theano.sandbox.cuda.use(gpu_id)

### ISSUE THREAD

**Issue by daweileng** [Theano/Theano#4790]
I'm using Theano revision f27c11e, on Ubuntu linux with cuda7.0 installed. Previously (old Theano version updated at 1-26-2016) all things were fine. Strange problem arises after I update Theano, is that my script will be stuck at  `theano.sandbox.cuda.use(gpu_id)`  for quite long time (about 30 minutes). I checked the GPU specified by 'gpu_id' is not being used. Any hints?

**Comment by nouiz** [comment]
It is probably a problem not in Theano. Try to reboot the computer. This
sometimes fix GPU related problems.

**Comment by lamblin** [comment]
Please use stackoverflow or theano-users for such requests.

**Comment by daweileng** [comment]
@nouiz : Just let you know, this problem remains after reboot. Also on another Ubuntu with cuda7.5 installed.
