### ISSUE TITLE
CUDA8: RuntimeError: Cuda error: k_copy_4d: invalid device function.

### ISSUE THREAD

**Issue by jeanpijon** [Theano/Theano#4805]
Hi, 
I am getting `RuntimeError: Cuda error: k_copy_4d: invalid device function.` errors while using CUDA8 either on GTX980 or a new 1080. I was trying to fiddle with -arch=sm_XX, but no luck. I am using bleeding edge Theano `0.9.0dev2.dev-81e527839752b2fadbdcc0ae0c048d321fe1e5f7`. Also disabling optimizer did not help. When I use older CUDA 7.5 everything runs OK on 980, but obviously can't use 1080. 
Can someone help me out? I already tried to remove `case 4:` bracnch in switch in  /theano/sandbox/cuda/cuda_ndarray.cu. In that case, it failed on the similar error, just with `k_elemwise_unary_rowmajor_copy`. 

Regards
J

**Comment by lamblin** [comment]
The best guess we have for that issue now is that there are GPUs with different architectures on the same machine, and it compiles on a different one that the one being used.
The workaround would be to delete the cache manually (`theano-cache purge` may not work) and then recompile with `arch=sm_XX`.

On the other hand, the new GPU back-end should be unaffected by this issue, so users are encouraged to use it (along with the latest dev version or upcoming 0.9 release).

**Comment by nouiz** [comment]
no news and the cache is probably the problems. So closing.

**Comment by avijoyChakma** [comment]
Hello,
I'm facing the same problem in my environment. I'm trying to execute the program mentioned in this [link](https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py). 
Environment specification-
- Ubuntu 14.04
- CUDA 6.5 and Nvidia Driver 340.101
- GT200GL [Tesla C1060]

Theano configuration file specification - 
- [global]
floatX=float32
device=gpu0
openmp = True 
mode = FAST_RUN
force_device=False
openmp=True
exception_verbosity=high
[lib]
cnmem=1

[blas]
ldflags = -lopenblas


I executed the same program in my another environment where the only difference is the GPU which is K600.
