### ISSUE TITLE
Cuda yield CPU while waiting on GPU

### ISSUE THREAD

**Issue by lachlants** [Theano/Theano#4812]
Hello, 

I would like the option to yield the CPU when waiting on long cuda kernels, I've found this very useful for freeing CPU resources for multi threaded multi gpu code. It can be enabled by calling: cudaSetDeviceFlags() with cudaDeviceScheduleBlockingSync or cudaDeviceScheduleYield after cudaSetDevice() and before any context creation. 

I've been testing a hacked in version of the above with my own branch and it hasn't caused any issues so far. 

Cheers

**Comment by nouiz** [comment]
Hi,

we are moving to a new GPU back-end called libgpuarray:

https://github.com/Theano/libgpuarray/

It is there that we should add that. There is already a mechanism for
flags, but I don't think it cover that one. @abergeron, did I miss it?

Can you give a more concrete data on the difference it does for you? Can
you give some speed up number? Can you confirm that the use case was 1
python process per GPU and inside it multiple python thread? If not, can
you describe it more? I would like to understand better the cases when that
flag help.

thanks

**Comment by lachlants** [comment]
I don't have alot of concrete data but I observed the processes running kernels went from 100% to ~20% CPU utilization with cudaDeviceScheduleBlockingSync enabled. This approx. halved the time required for a set of background processes to run. You can find a bit of info online about these different flags but it basically boils down to a trade off between kernel latency and CPU utilization i.e. busy wait loop vs polling / interrupt 

My use case is: 4x GPU processes and 4-16x data loading processes (not threads). I'm using Cuda 8.0 + Ubuntu 16.04 with 4x 1080 + i7-6700K. When Cuda kernels were running they consumed all CPU cores (excluding hyperthreading) which significantly slowed down the data loading processes (which require a bit of CPU for augmentation).... making the data loading the bottleneck. This is a fairly typical use case with modern very large datasets (e.g. Imagenet, etc) which can't be completely loaded into memory.

**Comment by nouiz** [comment]
thanks. I made a PR that add a Theano flags to allow this in the new
back-end:

https://github.com/Theano/Theano/pull/4821
