### ISSUE TITLE
Unable to use theano

### ISSUE THREAD

**Issue by daemonSlayer** [Theano/Theano#4813]
I installed Theano on Ubuntu 14.04 python 2.7 using these commands : 
```
sudo apt-get install python3-numpy python3-scipy python3-dev python3-pip python3-nose g++ libopenblas-dev git
sudo pip install Theano

```
Everything is successful, but when I do `import theano` or `from theano import *`, it says : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named theano

```
I dont understand the problem here.

**Comment by nouiz** [comment]
Use stackoverflow or theano mailig list for user question. This is for feature request/bugs.

Install Theano as a user:

pip install Theano

This is probably your problem.
