### ISSUE TITLE
Problem when Running theano benchmark

### ISSUE THREAD

**Issue by you-n-g** [Theano/Theano#4816]
Hi, 
I'm recently  running theano benchmark with https://github.com/soumith/convnet-benchmarks/tree/master/theano

It ran out of memory when I run the vgg network.
I found  this paper [Theano: A Python framework for fast computation of mathematical expressions ](http://arxiv.org/abs/1605.02688) had run the same experiment.

I'm using the same GPU  Titan X with 12204MiB memory.
I'm using the same configuration from the paper.

```
[global]
# device = cpu
device = gpu1
floatX = float32
optimizer_including = unsafe

[cuda]
root = /usr/local/cuda-7.5/

[lib]
cnmem = 0.45

[dnn.conv]
algo_fwd = time_once
algo_bwd_filter = time_once
algo_bwd_data = time_once
```

Then I tired to reduce the image size.
When I the image size is reduced to 186, I can run it successfully.

I get similar result like the  paper when running googlenet and alexnet. 
But it is  2 times slower (For a minibatch full forward and backward, my result  is 2007ms and paper result is about 600ms) when running vgg with image size = 186. 

How did the paper achieve this result?  Are there any other configuration I missed ? 

Any comments will be appreciated :) ! 
Thanks :)

**Comment by nouiz** [comment]
Did you install cudnn? It is important to do so.

Also, you should make sure the first call isn't included in the timing, as
it compute the result many times to find which one is the fastest.

**Comment by you-n-g** [comment]
I installed cuDNN. Otherwise I can't  get similar results on  googlenet and alexnet. 
The benchmark run the function many times after compile, I think the first call overhead won't affect much.

Thanks for your reply :)

**Comment by lamblin** [comment]
When timing the VGG network, we used a batch size of 64 (not 128 like the other networks), otherwise we would have a memory error.
Halving the batch size could also account for the speed difference.
Please let us know if it fixes the issue.
