### ISSUE TITLE
Slow compilation with device=cuda0

### ISSUE THREAD

**Issue by juancamilog** [Theano/Theano#4817]
I have a script that builds a small multilayer perceptron using lasagne 0.2.  The script is available here [https://drive.google.com/open?id=0B-j0Gj1S1Cb9UU5LNXFEeUJtQ3M](https://drive.google.com/open?id=0B-j0Gj1S1Cb9UU5LNXFEeUJtQ3M)

If you run the script as follows:

THEANO_FLAGS='device=gpu,floatX=float32' python testNN.py

compilation takes about 2 seconds on my laptop (i7 6700HQ, GTX 960M). When running as,

THEANO_FLAGS='device=cuda0,floatX=float32' python testNN.py

compilation times increase considerably ( to about 30 seconds ). For more complex models (like feeding the output to the network to its input inside a scan loop), the slowdown is even bigger.

Note that there is no slow down at run time. In my case, using cuda0 is actually a bit faster at run time.

Inside the zip file you'll find the python script to reproduce the error, along with the outputs of pydotprint and debugprint for all of the compiled functions. These correspond to a two layer network with 4 inputs, 256 hidden units in each layer, and 2 outputs.
It looks like the graphs in the cuda0 case are actually smaller (which looks like a good thing)

**Comment by nouiz** [comment]
I started to look. I have found dtype problem:

NN.py(235)predict_symbolic()
-> C = theano.tensor.slinalg.solve_lower_triangular(Lx,C)
(Pdb) l
230              # empirical covariance
231              S = theano.tensor.diag(theano.tensor.exp(self.logsn2)) +
y.T.dot(y)/n - theano.tensor.outer(M,M)
232              # Sx^-1 times empirical input output covariance
233              if Sx is not None:
234                  C = x.T.dot(y)/n - theano.tensor.outer(mx,M)
235  ->                C =
theano.tensor.slinalg.solve_lower_triangular(Lx,C)

Here Lx is float64 and not float32. So the solve isn't moved to the GPU and
print warnings.

**Comment by nouiz** [comment]
also, that op isn't ported to the new back-end. So if you fix the dtype,
then it could be faster to execute in the old back-end until it get ported.

**Comment by nouiz** [comment]
I got some result. The compilation is done in 2 phases. The extra time
consuming is in the second phases called Linker.

We currently cache a less think in the new back-end. It is on our todo to
fix that. Not sure when.

**Comment by juancamilog** [comment]
I am setting the dtype to be float64 because I want that op to be done with the higher precision, for numerical stability.

**Comment by nouiz** [comment]
I don't think we have time for the 0.9 release, so I bump that to 0.10 release.

**Comment by nouiz** [comment]
A follow up, in libgpuarray, there will be a disk cache:

https://github.com/Theano/libgpuarray/pull/335

But we will finish it after the Theano 0.9 version.

We also moved part of the init about cublas to the init of the contect to help to have better timming. We also have a theano flag to remove the first call from theano profiling.
