### ISSUE TITLE
Change Theano to be determinitic by default

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4819]
This issue is related to: https://github.com/Theano/Theano/issues/3029

This issue is not about implementing the different option of deterministic level as in that issue. It is about selecting the default of Theano after the different option is implemented.

I think that Theano should be by default deterministic (so mostly don't use atomicAdd on the GPU).

My reasoning is that we are doing science and science should be reproducible. Our tools should guide us in that direction. I see 4 level of deterministic:

1) fully deterministic
2) very close to fully deterministic but include a few practical use case, like using an op on GPU with atomicAdd by default when we don't have any of those op on the GPU. Mostly if we try to be deterministic, this cause great slow down.
3) (what I consider Theano current default behavior): Try to get the fastest speed by default, but not including some operation that only bring marginal speed up.
4) don't care of being deterministic. This would include making blas call faster by enabling there non-deterministic version.

I think we should change Theano default to level 1 or 2. I'm not sure which between between the 2. I see that having significant slow down by default as bad. But I also see having rare corner case non-deterministic as bad as user will suppose Theano is deterministic at first.

What do you think?

**Comment by ozancaglayan** [comment]
Once the behaviour change is properly documented in the release notes with some warnings, I think people will adapt to it easily. And yes 1 or 2 should be default but maybe we can evaluate on some real tasks beforehand to assess whether 1 is really slower than 2 or not.

**Comment by nouiz** [comment]
We got some previous cases where using AdvancedIncSubtensor1_dev20 vs AdvancedIncSubtensor1 was significatively faster. I also got case where using AdvancedIncSubtensor1 vs AdvancedIncSubtensor1_dev20 was giving significant final better training error...

So it mostly depend of the models, which make it an hard decision to make globally.

In that particular cases, if/when we get the time, I would go to re-implement AdvancedIncSubtensor1 to stay deterministic but be faster (not as fast as AdvancedIncSubtensor1_dev20, but probably close enough to be the default I think).

**Comment by ozancaglayan** [comment]
For me I didn't observe any speed difference in a deep RNN based MT model.

**Comment by nouiz** [comment]
I don't think we have time for the 0.9 release, so I bump that to 0.10 release.

**Comment by lamblin** [comment]
Actually, I think that being deterministic by default would have a performance impact that would be too big to be acceptable, especially with the current direction of cuDNN and the latest architecture (Volta).
As long as we have a deterministic option usable for debugging, I think it would be enough.

**Comment by nouiz** [comment]
I agree with @lamblin. We probably won't be able to make Theano deterministic by default. So I'll close this issue.

Note, we merge a PR that add the flag deterministic={default,more}. If you set it to more, it won't use the AdvancedIncSubtensor1_dev20 op. So it will be more deterministic. There isn't a global flag that will cover more cases. cudnn still need flags to make it deterministic.

**Comment by ozancaglayan** [comment]
Why is the value called `more`? :)

**Comment by nouiz** [comment]
Because maybe later there will be "most" or "all". a bool True/False would
not make it clear that it don't make it completly deterministic. I think
more does convein that.

If you have other idea, don't hesitate.
