### ISSUE TITLE
Generalise local_merge_alloc to go throught DimShuffle

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4825]
Current, it support Alloc(Alloc(...), ..) -> Alloc(...)
It should suport Alloc(DimShuffle(Alloc(...)) -> Alloc(...) or DimShuffle(Alloc).

The DimShuffle can be introduced by the user or the optimization local_useless_alloc or local_canonicalize_alloc optimizaiton.

**Comment by Sentient07** [comment]
I'll try this in a separate PR, after cgt-opt.

**Comment by nouiz** [comment]
This isn't super urgent. I would prefer that you continue to work on thing
that will speed up compilation.

**Comment by nouiz** [comment]
This happened in this PR: https://github.com/nouiz/Theano/pull/45

The current tests pass in this PR as we changed the opt local_useless_alloc to only remove useless alloc and moved the canonicalization that introduce the DimShuffle in the opt local_canonicalize_alloc that is run later.

**Comment by lamblin** [comment]
What we could start with is actually change the optimization transforming "Alloc(...) => DimShuffle(Alloc(...))" so that it does not apply when there is another Alloc in the clients of the first one.

**Comment by nouiz** [comment]
I think https://github.com/Theano/Theano/pull/4906 fix it enough. Yes, the user could manually create an Alloc(DimSHuffle(Alloc(...)), ...), but this isn't a problem/regression we introduce. Anyway, this Alloc merge opt is more for graph clean up then a real speed up. So I'll close this issue. If we see that user build that graph and we want to optimize it, we can reopen or make a new issue.

**Comment by lamblin** [comment]
Moreover, as we discussed IRL the other day, that case should be taken care of by #4647.
