### ISSUE TITLE
Make GraphToGPU try more than one optimizer for a node

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4829]
Similar to how we have `register_useless` for optimization multiple times before moving to the GPU, likewise, we could've this for moving nodes to GPU. If not this would be worth to try for all the nodes, I think trying multiple optimizers would work for few cases where there are multiple optimizers present for same op. ( like a node optimized by`local_gpua_lift_abstractconv2d_graph` could be optimized by `local_abstractconv_cudnn_graph` again) 
cc : @nouiz @lamblin

**Comment by Sentient07** [comment]
@nouiz Could this be considered as a change that could give bigger speedup ?

**Comment by nouiz** [comment]
I don't think it will speed up the optimization phase. Currently, even if there is a few optimization for one node, only 1 of them should apply. So it won't make a big difference.

In the case you talk about, only 1 of them are in GraphToGPU local_gpua_lift_abstractconv2d_graph. The other is still in the old optimization phase.

**Comment by nouiz** [comment]
I don't think we should change the code, so closing.
