### ISSUE TITLE
Non-unit value on shape on a broadcastable dimension.

### ISSUE THREAD

**Issue by xuanchien** [Theano/Theano#4834]
I am developing a very simple program which uses `theano.scan` function to loop through an array of vectors (in the end, I intend to develop a LSTM layer for my program). The problem is that I always get the error **Non-unit on shape of a broadcastable dimension** when compiling the function. I believe the `updates` param is the cause because as long as I put it there to compile a function, the error will occur. Here is the code:

```
import theano
import theano.tensor as T
from utils import *
import numpy as np

class LSTM:
    def __init__(self, X, in_size, out_size):
        self.X = X
        self.in_size = in_size
        self.out_size = out_size
        self.W_x = init_weights((in_size, out_size), "W_x")

        def _active(x, pre_h):
            x = T.reshape(x, (1, in_size))
            pre_h = T.dot(x, self.W_x)
            return pre_h

        h, updates = theano.scan(_active, sequences=X,
            outputs_info = [T.alloc(floatX(0.), 1, out_size)])

        self.activation = h

if __name__ == "__main__":
    X = T.matrix('X')
    in_size = 2
    out_size = 4
    lstm = LSTM(X, in_size, out_size)
    value = lstm.activation
    cost = T.mean(value)
    params = [lstm.W_x]

    updates = []
    for p in params:
        gp = T.grad(cost, p)
        updates.append((p, p - 0.1*gp))

    f = theano.function([X], outputs = cost, updates=updates)

    test = f(np.random.rand(10, in_size))
    print test
```

In the code, I use some functions loaded from utils.py, which is like this:

```
#pylint: skip-file
import numpy as np
import theano
import theano.tensor as T

def floatX(X):
    return np.asarray(X, dtype=theano.config.floatX)

def init_weights(shape, name):
    return theano.shared(floatX(np.random.randn(*shape) * 0.1), name)

def init_gradws(shape, name):
    return theano.shared(floatX(np.zeros(shape)), name)

def init_bias(size, name):
    return theano.shared(floatX(np.zeros((size,))), name)
```

I have been searching for a while but could not find any solution for this problem. In addition, I can not see any problem with my code. If I do not use theano.scan, the code will be running just fine.

Can you see any problem in my code? Do you have any advice to solve this problem?

Thank you in advance

**Comment by lamblin** [comment]
The mismatch seems to come from the default initial storage used to try and make scan work inplace.
That storage is initialized to a zero-shaped array, here an array of shape (0, 0) for a 2D variable. Then, as soon as a value is provided, then the right shape will be used.
Here, since the variable is a row (broadcastable pattern (True, False)), a shape of (0, 0) is not valid.
The solution would be to make it (1, 0) instead, I believe.

**Comment by lamblin** [comment]
As a temporary workaround, you can try to make x and pre_h vectors instead of rows, or full matrices (replacing the 1 in reshapes with a shared variable with a value of 1).
