### ISSUE TITLE
Cuda 8 : Unified Memory fast

### ISSUE THREAD

**Issue by arita37** [Theano/Theano#4837]
Pascal with cuda 8 has unified memory, allowing bigger than GPU Ram to be used
through CPU Ram. Latency is very low because of nvlink.

Is there any plane to upgrade Theano so big models can be used.

Thanks

**Comment by nouiz** [comment]
Currently there is no plan. It is not sure it won't give a big slow down.
Nvlink won't help in the current box as currently there is no NV link to go
to the CPU. When there is open power box with nvlink, then maybe it will
change that.
