### ISSUE TITLE
Failed to compile cuda_ndarray.cu

### ISSUE THREAD

**Issue by Autogazer** [Theano/Theano#4839]
I am having a similar issue to the closed issue: https://github.com/Theano/Theano/issues/1367

I am trying to get Theano to run on my NVIDIA GeForce GT 650M on my Macbook Pro.

Here is the error that prints when I try to import Theano with my .theanorc file having [global] floatX=float32 and device=gpu

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: dlopen(/Users/me/.theano/compiledir_Darwin-15.6.0-x86_64-i386-32bit-i386-2.7.12-32/cuda_ndarray/cuda_ndarray.so, 2): Symbol not found: ___cudaRegisterFatBinary
  Referenced from: /Users/me/.theano/compiledir_Darwin-15.6.0-x86_64-i386-32bit-i386-2.7.12-32/cuda_ndarray/cuda_ndarray.so
  Expected in: flat namespace
 in /Users/me/.theano/compiledir_Darwin-15.6.0-x86_64-i386-32bit-i386-2.7.12-32/cuda_ndarray/cuda_ndarray.so
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)

Theano runs just fine when I use the cpu, and the CUDA samples are running alright.  I also installed gfxCardStatus and switched to discrete to make sure my computer was using the gpu.

As suggested in the closed issue linked above, I did clear the theano-cache and I also purged the theano-cache.  Initially when I would clear and purge the cache, it would print the same error as above.  If I change the .theanorc file to be device=cpu and import theano, theano would run fine and I can clear the cache with no error printing.

Any ideas?  I have been trying to get this working for a week now, searching forums for any ideas I can find but no luck.  I am considering formatting my computer to install everything fresh and see if that helps.

**Comment by lamblin** [comment]
You seem to have a 32-bit installation of Python, on a 64-bit OS. This works as long as you do not compile GPU code, but CUDA only provides 64-bit versions of its runtime and libraries.
You should install a 64-bit distribution of Python instead.
