### ISSUE TITLE
How can I keep the image size untouched after convolution operation?

### ISSUE THREAD

**Issue by dengdan** [Theano/Theano#4844]
I wanna keep the  shape of feature maps the same as the inputs during convolution, but only two kinds of border_mode are available for  theano.tensor.nnet.conv.conv2d, i.e., valid/full. I am new to Theano. What should I should?

**Comment by nouiz** [comment]
I think we support the mode half. Which version of Theano do you use?
Otherwise you can pass a parameter to pad.

Also, use the new interface Theano.tensor.nnet.conv2d, not the one you are
currently using.

**Comment by lamblin** [comment]
Please ask such questions on StackOverflow or theano-users. `theano.tensor.nnet.conv2d` supports padding by "half", or by an explicit number of pixels.
