### ISSUE TITLE
nvidia driver version

### ISSUE THREAD

**Issue by rajats** [Theano/Theano#4851]
I have installed cuda and passed bandwidthTest but I am getting error:
The nvidia driver version installed with this OS  does not give good results for reduction.
Installing the nvidia driver available on the same download page as the cuda package will fix the 
problem: http://developer.nvidia.com/cuda-download

My driver version is 331.62 and using cuda toolkit 6.0
Does this mean theano is not using gpu?
How to fix this?

**Comment by rajats** [comment]
sorry not a issue of theano

**Comment by nouiz** [comment]
In case someone else find this questions. The problem is that you are using
an old and bugged driver and nvcc version. Update them and Theano will stop
complaining about them.

On Sat, Aug 13, 2016 at 3:50 PM, Rajat kumar Singh <notifications@github.com

**Comment by zhouhoo** [comment]
I upgrade to cuda8.0, the newlest, but still get such error.

**Comment by nouiz** [comment]
Open a new issue with your driver version, the code that you tested and the result you got, your OS and which Theano flag you used.

**Comment by nouiz** [comment]
Also see this issue if you use the new gpu back-end: https://github.com/Theano/Theano/issues/5530
