### ISSUE TITLE
Problems with the convolution affected by the nnet.conv2d function

### ISSUE THREAD

**Issue by krishnakinnal** [Theano/Theano#4854]
I have a video wherein I scan each frame as a Numpy image (3 channel RGB) using OpenCV's _read()_ call, which I blur using the _nnet.conv2d_ function and a custom kernel of my own. I need to draw a string onto the frame for displaying. When I display the image, the image is blurred, which means the Theano-defined function works, but the string isn't displayed. This doesn't seem to be supported, and needs fixing.

Also, when the border mode for convolution is specified as 'half', since in this case the size of my kernel is a 5x5 matrix, the first and last two rows and columns of my image are white, i.e, have the value 1. This is because convolution takes place by placing the center of the kernel over the pixel to be convoluted. Is there any method that supports ignoring these 'edge pixels', so that the first and last two rows and columns remain unaffected?
`

    def unsharp_theano(frame):

        frame = np.float32(frame) / 255.0
        kernelx = np.asarray([[[[1,4,6,4,1]]]], dtype = 'float32') / 16
        kernely = np.asarray([[[[1],[4],[6],[4],[1]]]], dtype = 'float32') / 16
        frame = np.rollaxis(frame,2)

        #Converting into a 4D Numpy array for conv2d input
        R = np.asarray([[frame[0]]], dtype='float32')
        G = np.asarray([[frame[1]]], dtype='float32')
        B = np.asarray([[frame[2]]], dtype='float32')

        #Blur function definition in Theano
        t_img = T.ftensor4("t_img")
        t_kernel = T.ftensor4("t_kernel")
        blurred = conv2d(input = t_img, filters = t_kernel, border_mode = 'half')
        blur = theano.function([t_img,t_kernel],blurred)

        #Calling the Theano function
        Rblur = blur(blur(R,kernelx),kernely)[0][0]
        Gblur = blur(blur(G,kernelx),kernely)[0][0]
        Bblur = blur(blur(B,kernelx),kernely)[0][0]

        res = np.asarray([Rblur,Gblur,Bblur])
        res = np.rollaxis(np.rollaxis(res,2),2) #Final image

        #Drawing string onto image
        putText(res, "Theano Blur", (40, 40), FONT_HERSHEY_PLAIN, 2, (0, 0, 0), thickness = 13)
        putText(res, "Theano Blur", (40, 40), FONT_HERSHEY_PLAIN, 2, (255, 255, 255), thickness = 2)
        return res

**Comment by nouiz** [comment]
Half of equivalent of using padding with 0s. Of you don't use it, then your
output will get smaller and won't get padded. The value you have of 1 is
the result of thy be computation of your filter with the padding. If you
want a different value you will need to change your filter or pass manually
with a different value.

Fred

**Comment by lamblin** [comment]
Please use theano-users or StackOverflow for such questions.
Convolutions in Theano, unlike some in other frameworks, only support 0-padding, not "mirror" or "nearest" padding that would duplicate some pixels around the borders. This is something you could do manually, though, using indexing or tensor.join for instance, in conjunction with the "valid" mode of convolution (no 0-padding).
