### ISSUE TITLE
Theano on Gpuarray gives 'module' object has no attribute 'gpuarray' error

### ISSUE THREAD

**Issue by johndoe2012** [Theano/Theano#4863]
I am going through the tutorial on [Returning a Handle to Device-Allocated Data](http://deeplearning.net/software/theano/tutorial/using_gpu.html#id2). After running the script it gives following error: 
```
Mapped name None to device cuda0: Tesla K80
Using cuDNN version 5005 on context None
Traceback (most recent call last):
  File "check2.py", line 11, in <module>
    f = function([], sandbox.gpuarray.basic_ops.gpu_from_host(tensor.exp(x)))
AttributeError: 'module' object has no attribute 'gpuarray'
```

The same error shows up in a previous [post](https://github.com/Theano/Theano/issues/2531) without a solution, although mine is linux environment. All required libraries, including cuda, cudnn, and libgpuarray should have been installed and configure correctly since it passes all tests listed in the tutorial. Cuda backend works fine. 

Any ideas on how to troubleshoot? Thanks,

**Comment by nouiz** [comment]
I suppose you are using Theano dev version. If not, update to it.

You are reading the doc about the last release. The doc for the dev version
is at:

http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html#returning-a-handle-to-device-allocated-data

**Comment by johndoe2012** [comment]
Thank you nouiz, following the dev tutorial indeed solved the problem.
