### ISSUE TITLE
how to reverse a theano tensor along a specific axis

### ISSUE THREAD

**Issue by kracwarlock** [Theano/Theano#4869]
I want to write a function that looks like
```
def reverse(x, axis):
```
where `x` would be a Tensor of unknown dimensions while `axis` will be an integer. How can implement the reversal of the tensor along this arbitrary axis in Theano?

**Comment by Sentient07** [comment]
Hi, 
You can use `theano.tensor.roll` to shift your tensor that you require along the axis. It works similar to numpy's `rollaxis`
Docs : http://deeplearning.net/software/theano/library/tensor/basic.html#theano.tensor.roll

**Comment by nouiz** [comment]
As no news and the questions got answered, closing
