### ISSUE TITLE
Mixed activation function

### ISSUE THREAD

**Issue by gillesdegottex** [Theano/Theano#4879]
Hi,

For the output layer, is it possible to have a linear activation for the first N values and a sigmoid for the remaining M values ?

I tried to do this with ranges:
```
        lin_output = T.dot(input, self.W) + self.b
        output[:N] = lin_output[:N]
        output[N:] = T.nnet.sigmoid(lin_output[N:])
```
but got a: "TypeError: 'TensorVariable' object does not support item assignment"

Do I have to build two separate parallel layers ?

Cheers,

**Comment by Sentient07** [comment]
You can do the operation that you intend to but in a slightly different way. 
``` T.set_subtensor(output[:N], lin_output[:N])```

**Comment by gillesdegottex** [comment]
Great! Thanks a lot!

**Comment by gillesdegottex** [comment]
Sorry, the doc reads:
```
new_r = set_subtensor(r[10:], 5)
```

So should I do ?
output = T.set_subtensor(output[:N], lin_output[:N])

**Comment by Sentient07** [comment]
That's absolutely dependent on your imports. I generally prefer importing the whole of tensor module as `T` and then using the methods that I want. In the docs, probably the import has been done as 
`from theano.tensor import set_subtensor`

**Comment by gillesdegottex** [comment]
Oh, sorry, I meant the assignement before the function call, not about the presence of the 'T.' i.e.

```
output = T.set_subtensor(output[:N], lin_output[:N])
```
or
```
T.set_subtensor(output[:N], lin_output[:N])
```

**Comment by nouiz** [comment]
first.

**Comment by gillesdegottex** [comment]
Thanks!
