### ISSUE TITLE
Why does GpuDnnSoftmax needs 'bc01'?

### ISSUE THREAD

**Issue by shiretzet** [Theano/Theano#4887]
Softmax dim is usually 2.

How should i implement my softmax with GpuDnnSoftmax?

thanks

**Comment by lamblin** [comment]
Please use theano-users or theano-dev for such questions, we try to keep the tickets for bug reports and feature requests.
GpuDnnSoftmax does not actually need 'bc01', it is a remnant from an earlier version.
