### ISSUE TITLE
Is it possible to reshape to a new shape with more than one ungiven dimension?

### ISSUE THREAD

**Issue by daweileng** [Theano/Theano#4895]
The reason I ask is because I want to reshape a 4D tensor with shape `(None, m, n, None)` to new shape `(None, m*n, None)`, by which it means dimension 1 and 2 are merged together. Currently reshape op only allows one ungiven dimension. So is there any way to fulfill this task?

**Comment by nouiz** [comment]
Use theano-user or stackoverflow for user questions. You can do

X.reshape(x.shape[0], -1, x.shape[3])

Theano accept symbolic shape.

**Comment by Sentient07** [comment]
We can have something like `Contributions.md` file where we add a disclaimer before opening a new issue so that we can redirect people better. 
For example, something like what Scikit-learn does, https://github.com/scikit-learn/scikit-learn/blob/master/CONTRIBUTING.md
