### ISSUE TITLE
cuda initialization and multiprocessing memory problems

### ISSUE THREAD

**Issue by arthurneural** [Theano/Theano#4896]
Using theano on a machine with GPU creates problems with multiprocessing if I try to limit the memory usage.
If I try to limit the memory usage by using resource.setrlmit() anywhere after theano.sandbox.cuda import I get memory errors even if the memory limit is large (up to 150 GB on my machine, which has 128GB).
One way that it fails is when using Queue() and another way is when calling start() or join() on a Process.
Attached is a file that reproduces the issues (you may want to play with the memory limit).

```
import resource, multiprocessing, traceback

# without this line everything happens normally
import theano.sandbox.cuda

# imposing a reasonable memory limit (up to 150GB on my machine)
lim = 1024 * 1024 * 10000
resource.setrlimit(resource.RLIMIT_AS, (lim, lim))

# example 1: fails in run and debug
try:
    q = multiprocessing.Queue()
except Exception as e:
    print('fail number 1: ' + str(e))
    traceback.print_exc()

# example 2: fails in debug
p = multiprocessing.Process()
try:
    p.start()
    p.join()
except Exception as e:
    print('fail number 2: ' + str(e))
    traceback.print_exc()
```

**Comment by lamblin** [comment]
There are two issues combining in there:
- the cuda runtime deems to take a lot of virtual memory
- when starting new processes from inside Python, the Python process is forked, and is allocated as much virtual memory as the original process, even if it does not need it, see #2184.

Does that happen with the new GPU back-end as well (`import theano.gpuarray`)?

**Comment by arthurneural** [comment]
1. Does the cuda runtime need all that memory, or can it somehow be freed after the initialization stage? (gc.collect() didn't have any effect) 

2. Switching the import line to `import theano.sandbox.gpuarray` doesn't cause the errors, but the reason I'm using the sandbox.cuda is to allow usage of two GPUs. I do this by calling use(device) inside processes. Those processes are also being limited in their memory consumption. Is there a way to accomplish this with gpuarray (decide at runtime which GPU to use?)

3. Besides forking (the second error) which doubles the memory as you explained, the first error happens when just creating a Queue object. Do you know why this happens?

**Comment by lamblin** [comment]
1. This is virtual memory, probably coming from memmapped files, Theano compiled modules or CUDA libraries. It is not taking any actual RAM (just addressing space) I think, and cannot be garbage-collected.
2. I think there is, but @nouiz or @abergeron should confirm.
3. I don't know about that, sorry.

**Comment by nouiz** [comment]
On Thu, Aug 25, 2016 at 9:45 AM, Pascal Lamblin <notifications@github.com>
wrote:

>
>    1. This is virtual memory, probably coming from memmapped files,
>    Theano compiled modules or CUDA libraries. It is not taking any actual RAM
>    (just addressing space) I think, and cannot be garbage-collected.
>    2. I think there is, but @nouiz <https://github.com/nouiz> or
>    @abergeron <https://github.com/abergeron> should confirm.
>
> You can call theano.gpuarray.init_dev('cuda') # or cuda0, cuda1,. ...

Don't import/init the GPU before forking.

**Comment by nouiz** [comment]
I think we answered the problem and there is no feedback, so closing.
