### ISSUE TITLE
Sentences containing one word : Issue Faced Again NotImplementedError: We didn't implemented yet the case where scan do 0 iteration

### ISSUE THREAD

**Issue by raghavchalapathy** [Theano/Theano#4902]
Hi All, 

I have data which have sentences with one word, While referring to 
Issues below 
1) [Theano/Theano#3276](https://github.com/Theano/Theano/issues/3276)

2) [solved in #102](https://github.com/zseder/hunvec/pull/102)

3) [Issue 3292 ](https://github.com/Theano/Theano/pull/3292)

It seemed like fix was provided in[ Issue 3292](https://github.com/Theano/Theano/pull/3292/commits/56bb06ebd2f0c2f801dd965e22ff40aeb29e600e)

But , I have the tested in the below theano versions 
1)  theano version 0.9.0dev2.dev- 
2) theano version 0.8.2

While using theano version 0.9.2dev2.dev

I am facing the below error 

```
Traceback (most recent call last):
  File "./train_loop.py", line 305, in <module>
    runModelInLoop(dropout,char_dim,char_lstm_dim,word_dim,word_lstm_dim)
  File "./train_loop.py", line 279, in runModelInLoop
    test_data, id_to_tag, dico_tags)
  File "/Users/raghav/Documents/Uni/COLING-2016/COLING-2016-Code/i2b2-2010/tagger/utils.py", line 231, in evaluate
    y_preds = np.array(f_eval(*input))[1:-1]
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 879, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function_module.py", line 866, in __call__
    self.fn() if output_subset is None else\
  File "/usr/local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 951, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 940, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 215, in theano.scan_module.scan_perform.perform (/Users/raghav/.theano/compiledir_Darwin-15.5.0-x86_64-i386-64bit-i386-2.7.)
NotImplementedError: We didn't implemented yet the case where scan do 0 iteration
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Shape_i{1}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:)
Toposort index: 112
Inputs types: [TensorType(int64, scalar), TensorType(float64, 3D), TensorType(float64, (True, False, False)), TensorType(float64, 3D), TensorType(float64, matrix), TensorType]
Inputs shapes: [(), (0, 1, 25), (1, 1, 25), (2, 1, 25), (25, 25), (25, 25), (25, 25), (25, 25), (25, 25), (25, 25), (25, 25), (25, 25), (1, 25), (1, 25), (1, 25)]
Inputs strides: [(), (200, 200, 8), (200, 200, 8), (200, 200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8), (200, 8)]
Inputs values: [array(0), array([], shape=(0, 1, 25), dtype=float64), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', ]
Outputs clients: [[], [Subtensor{int64:int64:int8}(forall_inplace,cpu,scan_fn}.1, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1})]]
```

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
# 
# While using the theano version 0.8.2 

I am just getting a message like floating point exception 8

Could you please suggest how to go about fixing this issue 

Please let me know if you require further information 

with regards
Raghav

**Comment by nouiz** [comment]
With the older version of Theano, we didn't got a good error message. So we made one that is more clear. It is mostly a case where the scan will do 0 iteration. We didn't implement that case. Can you modify your code/dataset so that this case don't happen?

**Comment by lamblin** [comment]
The way Scan is implemented, it needs to produce output tensors that have a shape of `(nsteps, *shape_of_each_step)`. Since it is impossible to know what the shape of each step is when there are 0 steps, it is not possible to implement this case, except for a massive rewrite.
You will have to work around that case in your code.
