### ISSUE TITLE
Memory Leak unnoticed in master 

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#4904]
In my recent PR, cgt-opt, the travis kept stopping for several builds and some tests got interrupted and didn't complete execution even after few attempted restarts of travis. I then tried using the nose-test on travis (https://github.com/nouiz/Theano/pull/46 ) with the parameter ` --process-restartworker`, which is "an option to restart workers once they are done, this helps control memory usage. Sometimes memory leaks can accumulate making long runs very difficult." The travis build passed then. As suggested by @lamblin it might be a bug in the master which is being exposed in this PR #4876 .
To ascertain that it is not caused by the new useless optimization as suggested by @nouiz , I had disabled that optimization and tried travis. Still the tests on travis stops. The result here : https://travis-ci.org/Sentient07/Theano/builds/155281685

**Comment by lamblin** [comment]
Could it be possible that the new profiling informations that are
collected prevent garbage collection of some objects, and this is where
the leak could come from?

On Fri, Aug 26, 2016, Ramana Subramanyam wrote:
> In my recent PR, cgt-opt, the travis kept stopping for several builds and some tests got interrupted and didn't restart when attempted a restart of travis. I then tried using the nose-test on travis (https://github.com/nouiz/Theano/pull/46 ) with the parameter ` --process-restartworker`, which is "an option to restart workers once they are done, this helps control memory usage. Sometimes memory leaks can accumulate making long runs very difficult." The travis build passed then. As suggested by @lamblin it might be a bug in the master which is being exposed in this PR #4876 .
> To ascertain that it is not caused by the new useless optimization as suggested by @nouiz , I had disabled that optimization and tried travis. Still the tests on travis stops. The result here : https://travis-ci.org/Sentient07/Theano/builds/155281685 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Theano/Theano/issues/4904

-- 
Pascal

**Comment by Sentient07** [comment]
@lamblin anyway how i could get that information? I'm using this https://github.com/minichate/nose-memory-grinder to check the memory consumed for different test on the cgt-opt branch and master

**Comment by nouiz** [comment]
To test that, chance the opt to return none instead of a tuple and rename
the method print_profile.

Le 26 août 2016 19:29, "Ramana Subramanyam" <notifications@github.com> a
écrit :

**Comment by Sentient07** [comment]
Which opt you mean?

**Comment by Sentient07** [comment]
Also, I have figured out the error. With reverting the rebases and just adding the commit to my branch, I observe there is no stoppage of travis. From my rebase history, I can confirm that a commit made between 
start : d5944c965c453558ef834b439b671e0c01530b3c
and 
end : e4e08782d3a10d010d3a99bc87fd0fc3b0465405

is causing the memory leak. Could you please help me with which commits could possibly cause this?

**Comment by Sentient07** [comment]
Just to make sure i'm proceeding in the right direction, this is my `$git reflog` output , 
http://pastebin.com/PdrJtJNK

**Comment by lamblin** [comment]
If I have a look at the difference between those commits on Github (https://github.com/theano/theano/compare/d5944c965c453558ef834b439b671e0c01530b3c...e4e08782d3a10d010d3a99bc87fd0fc3b0465405), there are 25 commits between those. Can you refine a little more? This should be only 4 or 5 bisection steps.

**Comment by Sentient07** [comment]
This issue is caused by introducing a new `staticmethod` in a LocalOptimizer. These two commits fix the error, 4aef3e2289a9fa394e3a32df31a3f69cfb4ec4c4 and e616eb785ec12df2e5126601c3b93262875f89c0
