### ISSUE TITLE
cuDNN installed, but "not available"

### ISSUE THREAD

**Issue by wojciech-galan** [Theano/Theano#4905]
Ubuntu 16.04, cuda 7.5 installed from repositories and works, cuDNN 5.1. I use keras with theano backend. I followed instructions from this link:
http://deeplearning.net/software/theano/library/sandbox/cuda/dnn.html
(is it still up to date?), so I have copied include and lib64 directories to CUDA_ROOT (/usr/lib/nvidia-cuda-toolkit on my machine). When I use keras, I get this message:

> Using Theano backend.
Using gpu device 0: GeForce GT 720 (CNMeM is enabled with initial size: 60.0% of memory, cuDNN not available)

I've tried also:
`theano.sandbox.cuda.dnn.version()`
and got 
`Exception: ("We can't determine the cudnn version as it is not available", 'Can not compile with cuDNN. We got this error:\n/tmp/try_flags_CkTbMY.c:5:19: fatal error: cudnn.h: Nie ma takiego pliku ani katalogu\ncompilation terminated.\n')`

So what is wrong? Am I missing something?

**Comment by Sentient07** [comment]
Which system are you working on ? did you try to set path to CUDNN ? 
This is what to be done on OSX for setting path, 
```
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$DYLD_LIBRARY_PATH
```
For linux, you should replace `DYLD_LIBRARY_PATH` with LD_LIBRARY_PATH.

**Comment by wojciech-galan** [comment]
`echo $LD_LIBRARY_PATH`
`/usr/lib/nvidia-cuda-toolkit/lib64`
As I mentioned before, I work under Ubuntu 16.04

**Comment by lamblin** [comment]
If the compiler did not find cudnn.h, you should make sure its path is in the CPATH environment variable. The compiler needs the header as well as the compiled .so.

In the future, please use StackOverflow or theano-users for support requests.

**Comment by skrish13** [comment]
In case anyone comes looking here again, the solution in this [thread](http://askubuntu.com/questions/767269/how-can-i-install-cudnn-on-ubuntu-16-04) seems to work perfectly for 16.04. Both copy pasting inside /usr/local/cuda/ and the 5.1's .deb doesn't seems to work for me (tried only for CUDA 8).
