### ISSUE TITLE
Does theano have a function to resize a tensor type (just like the function 'resize' function in cv2)

### ISSUE THREAD

**Issue by owphoo** [Theano/Theano#4908]
I have a tensor (2,3,640,480),it is probablely 2 images,and i want to resize it to a tensor of dimsion(2,3,200,200).
Keras has a function resize_image that can only resize an integer factor
Is there any function can help me?

**Comment by nouiz** [comment]
Theano resize don't change the number of element. How do you want your
transformation to happen? You could use slicing over the last 2 dimensions
to select a sub part of the tensor.

Fred

**Comment by owphoo** [comment]
@nouiz 
Because I want to resize images(tensor4(batch,channel,h,w)) in the 'scan' function,how can I do  ?

**Comment by nouiz** [comment]
We have the same semantic as numpy. Can you give an example of what you
have as input and what you want as output with small shapes?

x=T.tensor4() # (2,3,640,480)

would give you the good shape. But is probably not what you want.
x[:,:,200:,200:]

x[:,:,:STOP1:3,:STOP2:2]

If you fill correctly STOP1 and STOP2, this would give you something more
sensible.

**Comment by nouiz** [comment]
closing. This is a user questions. They should on the mailing list theano-user or stackoverflow. The post on theano-user is: 

https://groups.google.com/d/topic/theano-users/pdppGDSNEhM/discussion

Continue the discussion there.

**Comment by owphoo** [comment]
@nouiz Okay,I am moving to google discussion.thanks!
