### ISSUE TITLE
bilinear interpolation bug

### ISSUE THREAD

**Issue by AdrianLsk** [Theano/Theano#4914]
Theano doesnt like the `None` values for `batch_size` and `num_input_channels` in the return value of `theano.tensor.nnet.abstract_conv.bilinear_upsampling` function. It results in ```AsTensorError: ('Cannot convert (None, None, Elemwise{mul,no_inplace}.0, Elemwise{mul,no_inplace}.0) to TensorType', <type 'tuple'>)```. Since the function should upsample the input only across the spatial dimensions, it should be good enough to use `batch_size=input.shape[0]` and `num_input_channels=input.shape[1]`, right?

**Comment by lamblin** [comment]
Can you please provide the full stack trace of the error?
Are you using the master branch from GitHub?

**Comment by lamblin** [comment]
I'm asking because there is a [test](https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/tests/test_abstract_conv.py#L777-L792) that should check that case, and it seems to be passing.

**Comment by AdrianLsk** [comment]
Ah, sorry, my bad. The problem is that I am using a pip-installed `Theano 0.8.2.`, while the github version has the correct code. Should have checked it earlier.
