### ISSUE TITLE
Crash in MRG_RandomStreams with the new backend

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#4916]
I was a case where we end up in a situation where mrg_uniform gets asked for c_code with a GpuArrayType, meaning the optimization to replace it was skipped somehow.

I'll try to gather more information.

**Comment by abergeron** [comment]
This only happens with compute_test_values.

We would need to fix the op and the optimization for the new backend to introduce/remove transfers.

**Comment by nouiz** [comment]
A new duplicate issue about this contains test code that reproduce the problem:

https://github.com/Theano/Theano/issues/5279
