### ISSUE TITLE
Do theano support lmdb or hdf5 data?

### ISSUE THREAD

**Issue by JulyUp** [Theano/Theano#4919]
Now I have lmdb and hdf5 data for image classification. And I want to use theano to train some convnets. So do theano support lmdb or hdf5 data?

**Comment by Sentient07** [comment]
You have to process the HDF5 file using PyTables. There is a good example given here, http://deeplearning.net/software/pylearn/seriestables.html#introduction-to-pytables-and-hdf5

**Comment by lamblin** [comment]
Also, this is a question for theano-users or stackoverflow.

**Comment by Sentient07** [comment]
@lamblin I have made comment elsewhere how to alert people before they open an issue. I'll open a new issue on that so that everyone could see

**Comment by lamblin** [comment]
@Sentient07 Yes, that would be useful. I was sure we already had a ticket about it, but could not find it.

**Comment by JulyUp** [comment]
@Sentient07 @lamblin  Thank you very much. I will open this issue in the theano-users or stackoverflow.
