### ISSUE TITLE
Scan examples from docs not working (DOCUMENTATION NEEDS UPDATING) !

### ISSUE THREAD

**Issue by franciscovargas** [Theano/Theano#4927]
Running the following example from docs:

```python
import theano
import theano.tensor as T

k = T.iscalar("k")
A = T.vector("A")

# Symbolic description of the result
result, updates = theano.scan(fn=lambda prior_result, A: prior_result * A,
                              outputs_info=T.ones_like(A),
                              non_sequences=A,
                              n_steps=k)

# We only care about A**k, but scan has provided us with A**1 through A**k.
# Discard the values that we don't care about. Scan is smart enough to
# notice this and not waste memory saving them.
final_result = result[-1]

# compiled function that returns A**k
power = theano.function(inputs=[A,k], outputs=final_result, updates=updates)

print(power(range(10),2))
print(power(range(10),4))
```

and I'm getting the error:

ValueError: ('The following error happened while compiling the node', forall_inplace,gpu,scan_fn}(Elemwise{maximum,no_inplace}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuFromHost.0), '\n', 'numpy.dtype has the wrong size, try recompiling')

I'm running the latest version of Theano from github and it works for an example I wrote for a convnet on MNIST, but so far I haven't gotten any examples with scan to work yet. A similar error appears if I try to run anything with scan on the CPU as well. Any ideas what could be causing the error?

Thanks,

**Comment by kyunghyuncho** [comment]
I tried the code above with the latest dev version of Theano pulled from github. It works on CPU (Mac OS X 10.11.6 (15G31)), and also works on GPU (Titan X 2015, CNMeM is disabled, cuDNN 5004, THEANO_FLAGS=device=gpu0,floatX=float32).

**Comment by franciscovargas** [comment]
let me replicate your config mines are :

Using gpu device 0: GeForce GTX 980 Ti (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5005) 

I am pip installing the latest version thus:

Theano-0.8.2

This is odd I just reinstalled and it works. Maybe worth closing but I have seen it come up too in the users-group.

**Comment by nouiz** [comment]
"numpy.dtype has the wrong size, try recompiling" is in the error.

This is a problem related to numpy version and something Theano cache. Installing a different Theano version, deleting the cache. Changing numpy version can fix this.

**Comment by franciscovargas** [comment]
Yup it did I forgot to update after I fixed. Had an old University GPU
running on an un-updated version. Thanks.
