### ISSUE TITLE
"sum" pooling crashes when being replaced by cuDNN op

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#4929]
The lifter transforming `Pool(mode="sum")` to `GpuDnnPool`, or at least its gradient (`AveragePoolGrad(mode='sum')` to `GpuDnnPoolGrad` seems to be passing `mode='sum'` to the cuDNN Op, which does not support it.

We should probably use ~~`avg_exc_padding`~~ (EDIT: `average_inc_padding`) and explicitly multiply the by the window size for the forward op, and multiply the gradient for the backward op.

See the problem reported here: https://groups.google.com/d/topic/theano-users/tsYtmmTeBlg/discussion

**Comment by nouiz** [comment]
Do you have the full error?

**Comment by lamblin** [comment]
See the problem reported here: https://groups.google.com/d/topic/theano-users/tsYtmmTeBlg/discussion

**Comment by nouiz** [comment]
I think we should use avg_inc_padding otherwise, the windows size won't be
the same for each elements. with avg_inc_padding, it will be the same.

**Comment by lamblin** [comment]
You're right, I'll correct the text.

**Comment by nouiz** [comment]
Full error message: https://groups.google.com/d/topic/theano-users/tsYtmmTeBlg/discussion

**Comment by nouiz** [comment]
I fixed it in this PR: https://github.com/Theano/Theano/pull/4932
