### ISSUE TITLE
cuDNN batch norm does not support 5D input

### ISSUE THREAD

**Issue by mdering** [Theano/Theano#4931]
I believe this is an issue to be opened here. Briefly, the GpuDnnBatchNorm operation has a few assertions that the input must be 4 dimensions. However, it seems like the cudnn function it calls, cudnnBatchNormalizationForwardTraining, can accept both 4D and 5D tensors as input. I'm not an experienced cudnn programmer at all but this seems like it could possibly be a quick fix. Could someone take a look at this?

**Comment by nouiz** [comment]
Just to make sure that people who follow this, there is a PR here for that:

https://github.com/Theano/Theano/pull/4948

**Comment by nouiz** [comment]
the PR was merged 26 day ago
