### ISSUE TITLE
User interface change: pool_2d rename parameter ds to ws

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4933]
Both GPU back-end use ws. Some internal stuff in the gpu back-ends is fixed by this PR:

https://github.com/Theano/Theano/pull/4756/

But this don't change the CPU user interface, as it is using ds for historical reason (downsample size).

I think we should be consistent in the user interface in CPU and GPU and I prefer ws to ds.

We must keep the support for the old interface with a deprecation warning and we should support unpickling old files and automatically convert them to the new interface.

**Comment by lamblin** [comment]
We should change the following names in the Python interface:
- `ds` to `ws`
- `st` to `stride`
- `padding` to `pad`

There is no need to change it in the CPU Op for now, so there should be no problem regarding unpickling.

**Comment by lamblin** [comment]
Now that `pool_3d` has been merged, the same change should be done there as well.
If it is done quickly enough, I think we don't need to worry about deprecation warnings and compatibility.

**Comment by lamblin** [comment]
Closed by #5142
