### ISSUE TITLE
theano.gradient.NullTypeGradError: tensor.grad encountered a NaN Help! help!help!

### ISSUE THREAD

**Issue by HornHehhf** [Theano/Theano#4939]
...... I'm not sure if argsort should have its gradient implemented or is should be marked as undefined. So I mark it as not implemented for now.

I can run my program in linux and my laptop with windows. But when I run my program in other windows machines. The theano report the error.
I am not sure whether the problem is caused by version. I think there are may some versions which can compute grad for argsort but others can not.
Please help me!
Thank you!

**Comment by lamblin** [comment]
Please address your requests for help to StackOverflow or theano-users.
We try to keep GitHub tickets about bug reports and feature requests.
