### ISSUE TITLE
Update convolution tutorial about dilation

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#4962]
http://deeplearning.net/software/theano_versions/dev/tutorial/conv_arithmetic.html

It is documented only in the library doc. Not very user friendly: http://deeplearning.net/software/theano_versions/dev/library/tensor/nnet/conv.html

**Comment by ajboulay** [comment]
Hi,
I saw this note in the tutorial documentation:
"TODO: Give examples on how to use these things! They are pretty complicated."
I can provide some examples for the documentation; 
please advise if you have more directions for this issue.
AJB
