### ISSUE TITLE
Theano is running very slow on GPU

### ISSUE THREAD

**Issue by ibrahim-amer** [Theano/Theano#4974]
I'm using Theano backend on Keras running on jupyter ipython notebook. Everything was working fine couples of days ago, but today I notice that it is running very very slow !, I think running it on CPU is much faster than that. I'm running [ mnist example](https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py) without making any changes. The batch (128 size) takes too long to process, around 5 minutes or something to finish, the next batch takes the same time almost or longer, it used to run mnist example very very fast (170 seconds for the whole epoch). 

Please help me how could I figure out the problem
Note: I tried it using anaconda then I tried it using winpython and the same problem occur.

I'm using windows 10, 16GB ram, Nvidia GTX 660 2 GB, cuDNN either enabled or disabled the same problem occur

**Comment by nouiz** [comment]
Did you reboot? Sometimes the GPU get stuck and a reboot fix that.

**Comment by ibrahim-amer** [comment]
@nouiz Thanks sir for your reply !. I did what you suggested but nothing changed it is very slow :(

**Comment by Sentient07** [comment]
Can you try to run it outside the jupyter notebook and tell? Because, sometimes, jupyter notebook uses limited GPU memory and hence you might have this problem. ( This problem happens with me in my OSX, nvidia 750M and also the same happens with ipython)

**Comment by lamblin** [comment]
Please use StackOverflow or theano-users for such requests for support.
