### ISSUE TITLE
gpuarray: compiler-bindir passed to g++

### ISSUE THREAD

**Issue by gvtulder** [Theano/Theano#4978]
Perhaps this is something specific to my system, perhaps not. If I have the `nvcc.compiler_bindir` config option set, the `theano.gpuarray.dnn` functions do not compile. The tests produce errors like these:
```
test_softmax (theano.gpuarray.tests.test_dnn.TestDnnInferShapes) ... SKIP: cannot compile with cuDNN. We got this error:
g++: error: unrecognized command line option ‘--compiler-bindir’
```

My suspicion is that this is caused by the code in [theano/gpuarray/dnn.py#L70-L71](https://github.com/Theano/Theano/blob/master/theano/gpuarray/dnn.py#L70-L71) that adds `--compiler-bindir` to the list of arguments:
```python
    if config.nvcc.compiler_bindir:
        params.extend(['--compiler-bindir', config.nvcc.compiler_bindir])
# ...
    avail, out, err = GCC_compiler.try_flags(
        params, preambule=preambule, body=body,
        try_run=False, output=True)
```
If I remove the lines that add the parameter, everything works.

This code seems to be similar to that in `theano/sandbox/cuda/__init__.py`, with the difference that the gpuarray code runs g++, which doesn't accept the argument, and the sandbox code calls nvcc, which does:
```python

            if config.nvcc.compiler_bindir:
                params.extend(['--compiler-bindir',
                               '%s%s%s' % (path_wrapper, config.nvcc.compiler_bindir, path_wrapper)])
# ...
            comp, out, err = nvcc_compiler.NVCC_compiler.try_flags(
                flag_list=params, preambule=preambule, body=body,
                try_run=False, output=True)
```

Is this a bug in the code or is this something specific to my setup?

**Comment by lamblin** [comment]
It is an issue in Theano.
Passing `nvcc` options to `g++` looks like a bad idea in general...
@abergeron what do you think the fix should be?

**Comment by gvtulder** [comment]
I'm not sure if this is the right solution, but this (#5010) fix works for me.
