### ISSUE TITLE
Theano Seems to Ignore device=cpu Flag

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#4994]
I set `device=cpu`, `reoptimize_unpickled_function=true` and tried to load a pickled model but am seeing:

```
Using gpu device 0: GeForce GT 750M (CNMeM is disabled, cuDNN 5103)
```

I also but a breakpoint and see:

``` pytb
> /Users/alex/.virtualenvs/demo/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py(485)use()
-> if force and not cuda_available and device.startswith('gpu'):
(Pdb) device
'gpu'
```

**Comment by nouiz** [comment]
Your own code could enable the GPU without that flag.

Also, this don't mean to disable the GPU. Can you give us the full stack
trace to see what cause this call that init the GPU?

To force the disabling of the gpu, use this flag: force_device=True

**Comment by cancan101** [comment]
I set `force_device=True` but now I get:
```
  File "/Users/alex/.virtualenvs/demo/lib/python2.7/site-packages/theano/sandbox/cuda/type.py", line 601, in CudaNdarray_unpickler
    raise ImportError("Cuda not found. Cannot unpickle CudaNdarray")
```

**Comment by nouiz** [comment]
What did you pickle? If you pickled a Theano graph, variables or function,
they are bind to a specific device. Theano don't allow to swap them during
unpickling. We tried and it is complicated with many corner cases.

So we recommand to pickle only the data from the SharedVariables.

With manual recover it, but it isn't trivial. You can manually recover the
value from SharedVariables on GPU by unpickling the graph on a computer
with a GPU. Then pickle only the value. Then in a new process you can
reload the new pickle.

You could do in on a computer without a GPU and without a second pickle and
process, but it is more complicated.

In all cases, you need to rebuild the graph.

There is those Theano flag that can help you:
experimental.unpickle_gpu_on_cpu=True:

AddConfigVar('experimental.unpickle_gpu_on_cpu',
             "Allow unpickling of pickled CudaNdarrays as numpy.ndarrays."
             "This is useful, if you want to open a CudaNdarray without "
             "having cuda installed."
             "If you have cuda installed, this will force unpickling to"
             "be done on the cpu to numpy.ndarray."
             "Please be aware that this may get you access to the data,"
             "however, trying to unpicke gpu functions will not succeed."
             "This flag is experimental and may be removed any time, when"
             "gpu<>cpu transparency is solved.",

and this one: unpickle_function=False

AddConfigVar('unpickle_function',
             ("Replace unpickled Theano functions with None. "
              "This is useful to unpickle old graphs that pickled"
              " them when it shouldn't"),
             BoolParam(True),
             in_c_key=False)

What exactly is in the pickled file and what you want to do?

**Comment by lamblin** [comment]
Yes, you need a GPU to unpickle a CudaNdarray.
The experimental flags provided above could help, but in general, unpickling in a different setting is hard, so we do not support it here.

**Comment by wangqipeng** [comment]
so, it seems tensorflow doesn't have this problem. how does tensorflow solve this issue?
