### ISSUE TITLE
Import theano fails, AttributeError

### ISSUE THREAD

**Issue by luango3110** [Theano/Theano#5005]
Hi,

I'm using Anaconda 4.1.11, python 3.5 on Window10. I successfully installed theano, however when I import theano, the error occurs as below (I updated all the packages but there is still this error):

Problem occurred during compilation with the command line below:
C:\TDM-GCC-64\bin\g++.exe -shared -g -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=8192 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -IC:\Anaconda3\lib\site-packages\numpy\core\include -IC:\Anaconda3\include -IC:\Anaconda3\lib\site-packages\theano\gof -o C:\Users\Lua\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\Lua\AppData\Local\Theano\compiledir_Windows-10-10.0.14393-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\lazylinker_ext\mod.cpp -LC:\Anaconda3\libs -LC:\Anaconda3 -lpython35
Traceback (most recent call last):

  File "<ipython-input-16-3397704bd624>", line 1, in <module>
    import theano

  File "C:\Anaconda3\lib\site-packages\theano__init__.py", line 63, in <module>
    from theano.compile import (

  File "C:\Anaconda3\lib\site-packages\theano\compile__init__.py", line 9, in <module>
    from theano.compile.function_module import *

  File "C:\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 22, in <module>
    import theano.compile.mode

  File "C:\Anaconda3\lib\site-packages\theano\compile\mode.py", line 12, in <module>
    import theano.gof.vm

  File "C:\Anaconda3\lib\site-packages\theano\gof\vm.py", line 647, in <module>
    except (OSError, theano.gof.cmodule.MissingGXX) as e:

AttributeError: module 'theano' has no attribute 'gof'

Please anyone help me!! Thank you so much.

**Comment by nouiz** [comment]
Python 3.5 is not supported on Windows. Use Python 3.4 or 2.7

**Comment by luango3110** [comment]
Thank you so much nouiz, I installed anaconda with python 2.7, this issue disappeared.
