### ISSUE TITLE
Make [sd]gemm call numpy matrix call when we don't have blas

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5008]
Modify the header in tensor/blas_headers.py to have an implementation of [sd]gemm that call numpy matrix product in C when we don't have a blas.

The goal is to have all ops including CorrMM work in C code when we don't have direct link to BLAS. For this case, we can remove the old convolution after that.

if the flag theano.config.blas.ldflags is empty use the new code. Otherwise, use the old code.

Then in the file theano/tensor/nnet/opt.py, in the functions local_abstractconv__gemm_, update it to execute even if that flag is empty. So we should use the CorrMM\* class now.

To test that it work well, set the Theano flag blas.ldflags to empty and the following tests should pass (and not be skipped, so also modify that test):

```
nosetests theano/tensor/nnet/tests/test_abstract_conv.py:TestCorrConv2d
```

you could need to delete Theano cache while developing this: "theano-cache purge"

http://deeplearning.net/software/theano/extending/extending_theano_c.html

in blas_header_text() in file tensor/blas_headers.py return the new code if config.blas.ldflag is empty otherwise return old code. 

The new code should implement the c method `sgemm_` that should create a new numpy ndarray object from the parameter and call  http://docs.scipy.org/doc/numpy/reference/c-api.array.html#c.PyArray_MatrixProduct2

**Comment by lamblin** [comment]
Closed by #5076.
