### ISSUE TITLE
Merge the Solve op in sandbox/solve.py and in tensor/nlinalg.py

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5017]
See the title. Investigate what is the difference and delete sandbox/solve.py if the one in nlinalg.py does everything. Otherwise document or merge both version.

**Comment by slefrancois** [comment]
sandbox.solve uses scipy.solve, while tensor.nlinalg.tensorsolve uses numpy.tensorsolve. However, there is tensor.slinalg.solve which also uses scipy.solve.

We will merge sandbox.solve with slinalg.solve and assess if optimizations should transfer  nlinalg.tensorsolve to slinalg.solve for certains matrices.
