### ISSUE TITLE
How can I speed up theano compilation to C using multicores?

### ISSUE THREAD

**Issue by yxchng** [Theano/Theano#5019]
I understand that I can speed up theano computation using the OMP_NUM_THREADS setting but I cannot figure out how I can speed up the compilation of model using multicores. Right now, it seems that the compilation process only uses one core of my CPU and it is taking extremely long. My model is very large and it takes about 2 hours to compile before it starts training. Can I know how I can parallelize this process or is there any other way to speed up the compilation process? Thanks

**Comment by nouiz** [comment]
It would request changes to Theano. Do you want to dive in Theano code
generator to parallelize it?

Maybe using a new python 3 features "async" would help make this change
easier.

**Comment by lamblin** [comment]
We are aware that the graph optimization process can be a bottleneck for larger graphs, and are trying to address that.
Parallelizing on multiple cores is not really something that could help in that regard in the near future, though, as it consists in global passes over the whole expression graph.

If you have further questions on the implementation, theano-dev is a better-suited forum.
