### ISSUE TITLE
Unnecessary GpuFromHost/HostFromGpu when using "lt"

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#5020]
```
import os

import numpy as np

os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

from theano import function, shared, tensor



x = shared(np.zeros(4, dtype=np.float32))
y = shared(np.zeros(4, dtype=np.float32))
z = shared(np.zeros(4, dtype=np.int8))

f = function(inputs=[],
             updates=[(z, tensor.lt(x, y))],
             profile=True)

f()
f.profile.summary()
```

I don't understand why computations involving only shared variables invoke transmission to and from the GPU.

**Comment by Sentient07** [comment]
Hi Neil, 
The nature of SharedVariable is that they're created on the GPU and are GPU Variables even before the compilation of the graph. This PR moves all the containing shared variables to a particular device, if pickling is what you're concerned about. https://github.com/Theano/Theano/pull/4717

**Comment by NeilGirdhar** [comment]
@Sentient07 I'm not concerned about pickling.  I am concerned about the HostFromGpu ops that are produced.  Did you run the above code and inspect the output?

**Comment by nouiz** [comment]
In this particular case, the "lt" operation return an int8 output dtype. In the old gpu back-end, we only support float32. If you cast the output of "lt" to float32, then in default mode, we will merge them and this will move them to the GPU.

In the new gpu back-end, we support multiple dtype, (not just float32). So the cast isn't necessary.

**Comment by NeilGirdhar** [comment]
@nouiz Awesome! When will this be checked in?  When I fetch master, it still seems to have the same problem.

**Comment by nouiz** [comment]
See this issue on how to use it: https://github.com/Theano/Theano/issues/2908

**Comment by nouiz** [comment]
Also this link: http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html#gpuarray

**Comment by NeilGirdhar** [comment]
@nouiz Thanks a lot!

**Comment by NeilGirdhar** [comment]
@nouiz It works!!!  How do I resolve this though?  "WARNING (theano.configdefaults): Only clang++ is supported. With g++, we end up with strange g++/OSX bugs."

**Comment by nouiz** [comment]
If it work, you can ignore it. Do you set the theano flag cxx to something?
Let it take the default of clang++. If it don't find clang++, maybe it fall
back to g++. You could install clang to remove the warning, but if it work,
you can ignore it.

**Comment by NeilGirdhar** [comment]
I set cxx=clang++ and the other error went away.
