### ISSUE TITLE
Modifying padding values for convolution 2D layer

### ISSUE THREAD

**Issue by TianweiXing** [Theano/Theano#5030]
I want to modify the Theano code for specific use: change padded values from 0 to 1

Originally, in "nnet.conv2d", the feature map can be padded with zeros to extend the output size.
However, I want to change the padded value----pad the feature map with "1" instead of "0".

I looked at the source code, and found that there are actually 2 "conv2d" function: 
"conv2d" in conv.py:
https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/conv.py#L40
and "conv2d" in abstract_conv.py:
https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/abstract_conv.py#L140

So I'm not sure which file should I modify to get a different padding value....
(I tried modifying "https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/abstract_conv.py#L841"
from "zeros" to "ones", but nothing changed in the result).

**Comment by lamblin** [comment]
There are several implementations of conv2d, including some that rely on external libraries (cuDNN) that do _not_ support other values for padding.
The easiest way for you to have padding of ones and still have reasonable performance would be to explicitly pad the input with ones, for instance using `set_subtensor`.
