### ISSUE TITLE
new feature in cuda8.0 release

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#5035]
```
New in CUDA 8
Pascal Architecture Support
Enhance performance out-of-the-box on Pascal GPUs
Simplify programming using Unified Memory including support for large datasets, concurrent data access and atomics
Optimize Unified Memory performance using new data migration APIs
Increase throughput at ultra-fast speeds using NVLINK, new high-speed interconnect
Developer Tools
Identify latent system-level bottlenecks using critical path analysis
Improve productivity up to 2x with NVCC
Tune OpenACC applications and overall host code using new profiling extensions
Libraries
Accelerate graph analytics algorithms with nvGRAPH
Speed-up Deep Learning applications using native support for FP16 and INT8, support for batch operation in cuBLAS
```

Do we have anything to improve in these places
1.Simplify programming using Unified Memory including support for large datasets, concurrent data access and atomics
2.Optimize Unified Memory performance using new data migration APIs
3.Increase throughput at ultra-fast speeds using NVLINK, new high-speed interconnect
4.Speed-up Deep Learning applications using native support for FP16 and INT8, support for batch operation in cuBLAS

**Comment by nouiz** [comment]
1) Nothing to do. The unifed memory isn't useful as we already automatically does the transfer. I don't expect any gain by letting them do it.
1)atomic. We already removed our float64 atomic to use the one from cuda8 in the release candidate.
2) See 1). I don't think we will benefit from this.
3) This is automatic if you use platoon with NCCL: https://github.com/mila-udem/platoon/
4) float16 is underway: https://github.com/Theano/Theano/issues/2908 . Mostly we already support many float16 storage (a few fixes missing for some ops, but MLP and conv model work). Small work needed to support float16 computation. We will do after the small fixes
4) which batch operation do you want? I checked and didn't see a new one that would help us. We already use batchedGemm.
INT8 isn't high in the priority list for now.

I'll close as this is mostly all done. float16 have its own issue. If you personnaly need int8, open an issue about it.

If you see think that I missed and that you would like, open an issue specific for each item.

**Comment by fayeshine** [comment]
@nouiz 
I found a strange thing, my MLP, become slower when I updated to CUDA 8.0 from 8.0RC.
1min15s -> 1min 30s

**Comment by nouiz** [comment]
Delete your Theano cache and reboot your computer. Just to be sure. then
time again.
