### ISSUE TITLE
theano.function crashes when forgetting to put multiple output variables in a container

### ISSUE THREAD

**Issue by krikru** [Theano/Theano#5040]
When you create a Theano function, you need to put the output variables in a list or in a tuple if you have more than one output variable. However, if you forget to put the output variables in a container, you just get an error message on the form

```
Traceback (most recent call last):
  File "C:/test/test.py", line 7, in <module>
    f = theano.function([x], a, b)
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\function_module.py", line 1439, in __init__
    optimizer, linker = mode.optimizer, copy.copy(mode.linker)
AttributeError: 'TensorVariable' object has no attribute 'optimizer'
```

which is quite confusing.

If you on the other hand forget to put the input variables in a container, you get a much more helpful error message:

```
Traceback (most recent call last):
  File "C:/test/test.py", line 7, in <module>
    f = theano.function(x, [a, b])
  File "C:\Program Files\Python35\lib\site-packages\theano\compile\function.py", line 278, in function
    raise Exception("Input variables of a Theano function should be "
Exception: Input variables of a Theano function should be contained in a list, even when there is a single input.
```

(Although this is not completely true; putting the input variables in a tuple seems to be okay too.) A similar message should be given also when you have multiple output variables and forget to put them in a container.

This is the file that was used to produce the crash:

```
import theano.tensor

x = theano.tensor.scalar()
a = x + 1
b = x ** 2

f = theano.function([x], a, b)
```

**Comment by lamblin** [comment]
The problem is not that outputs are not in containers. In fact, `theano.function` is perfectly happy to have only one Variable as output, even if it is not in a list or tuple (which is not the case for inputs).
The issue is that you are passing `b` as a _third_ argument to `theano.function`, and that argument is `mode`. Since `b` does not act like a `mode`, you get an error message stating that.

**Comment by krikru** [comment]
How can you read that from the error message? Anyway, the message is quite cryptic (too cryptic for me to understand what's causing it) and my point is that it should be clarified so that it can be more easily understood.
