### ISSUE TITLE
GPU is always initialized

### ISSUE THREAD

**Issue by danielS91** [Theano/Theano#5041]
Running theano code like: 
```python
import theano

a = theano.tensor.matrix()
b = a * 2.
print(theano.config.device)
f = theano.function([a], b)
theano.printing.debugprint(f)
```
with `THEANO_FLAGS='device=cpu'` is always initializing the GPU. In the end no optimization is done, but it's confusing for the user. 

The output for the code above at least for me:
```
cpu
Mapped name None to device cuda: GeForce GTX 970
Using cuDNN version 5105 on context None
Elemwise{Composite{(i0 + (i0 * i1))}} [id A] ''   0
 |TensorConstant{(1, 1) of 2.0} [id B]
 |<TensorType(float64, matrix)> [id C]
```
I also tried to delete my .theanorc file, but it's still the same.

**Comment by nouiz** [comment]
This should not happen. I don't have this problem here.

Can you print

Import theano
print theano.config.device?

Le 29 sept. 2016 13:10, "Daniel Seichter" <notifications@github.com> a
écrit :

**Comment by danielS91** [comment]
Looks like that the problem was related to the cache. 
After deleting the theano cache folder (for me: ~/.theano) I was not able to reproduce the problem.

**Comment by Sentient07** [comment]
But are such information supposed to be cached ? @nouiz

**Comment by nouiz** [comment]
@Sentient07, what do you think was cached? I don't understand how we can cache the initialization of GPUs...

As it is solved, I'll close the issue. If you have it again, reopen. I don't understand why the cache content can trigger the init of the GPU. If it happen again, keep your cache (you can move it). We need to don't let it init the gpu.

**Comment by Sentient07** [comment]
> I don't understand why the cache content can trigger the init of the GPU

That was my question actually.
