### ISSUE TITLE
inconsistent arange

### ISSUE THREAD

**Issue by majidaldo** [Theano/Theano#5046]
I don't think this should happen.

```
dt=.01;cl=1;nd=1
tdm= T.tile( T.arange(0,cl,dt),nd).reshape((nd,-1))
ndm=np.tile(np.arange(0,cl,dt),nd).reshape((nd,-1))
print(tdm.shape.eval(),ndm.shape)
#tdm.eval(),ndm
```
result
```
[  1 101] (1, 100)
```

**Comment by lamblin** [comment]
It it just a matter of floating-poing precision. If you set `floatX=float32`, then `dt` will be converted by Theano into a float32 constant, equal to `0.0099999998`. If `floatX` is `float64`, then the output is `[1, 100]` as expected.
Note that it happens in NumPy as well:
```python
>>> print(np.tile(np.arange(0, cl, np.float32(dt)), nd).reshape((nd, -1)).shape)
(1, 101)
```

**Comment by lamblin** [comment]
To force double-precision for `dt`, you can always use `dt = np.float64(0.1)`.
