### ISSUE TITLE
warning then error after updating nvida drivers + kernel

### ISSUE THREAD

**Issue by apulver** [Theano/Theano#5051]
```
WARNING (theano.sandbox.cuda.opt): Optimization Warning: Got the following error, but you can ignore it. This could cause less GpuElemwise fused together.
CudaNdarray_ptr_int_size: error when calling the gpu code. (invalid device function)
```

and then it fails with the following error

```
RuntimeError: Cuda error: k_elemwise_unary_rowmajor_copy: invalid device function. (n_blocks=128, n_threads_per_block=256)

Apply node that caused the error: GpuAlloc(<CudaNdarrayType(float32, vector)>, TensorConstant{1}, Shape_i{1}.0, Shape_i{0}.0)
```

code previously worked fine. switching to the older kernel does not resolve the issue, so it might be a driver problem. 

OS is debian testing, cuda 7.5.18-4, nvidia 367.44-2. gpu: titan X (old version), tried multiple versions of CUDNN without success. the error occurs with both the latest git version of theano and the version on pypi.

**Comment by nouiz** [comment]
Delete theano cache

theano-cache purge

It could fix this.

**Comment by apulver** [comment]
I purged the cache before and after every configuration change I tried

**Comment by apulver** [comment]
this looks like a similar issue: https://github.com/Theano/Theano/issues/4805

**Comment by apulver** [comment]
I don't get any errors when I set 
```
optimizer=None 
```

**Comment by nouiz** [comment]
What about optimizer=fast_compile?

Using make it don't run on the GPU.

**Comment by apulver** [comment]
Tried it and got the same error. See my edited comment above

**Comment by apulver** [comment]
I think I got it:
adding -arch=sm_52 solves the issue
this might be relevant: https://github.com/Theano/Theano/pull/3258

**Comment by elPistolero** [comment]
I also have this problem with a similar setting (debian testing, titan x, cuda 7.5, cudnn 5005, driver: 367.44).

I get the same warning message and then occasionally it will just crash
`terminated by signal SIGSEGV (Address boundary error)`
or I will get the same error message as @apulver.

However, adding -arch=sm_52 or switching to float64 doesn't help. Only if I set
`optimizer = None`
does the error not occur.

**Comment by apulver** [comment]
run theano-cache purge and then try using the following nvcc section in your theanorc
```
[nvcc]
fastmath = False
flags=-D_FORCE_INLINES -arch=sm_52
```

**Comment by apulver** [comment]
As a minor side issue:

It wasn't really clear to me how .theanorc is parsed, e.g. if # comments are ignored, how to add multiple flags, etc. I had to read the source to see how it worked.

**Comment by elPistolero** [comment]
Thanks for the suggestion.
Sadly, your recommended nvcc settings did not change the situation for me.

Is there any information that I could add to make this easier to debug?

**Comment by elPistolero** [comment]
Scratch that! It's actually working now. I had to delete the .theano folder (theano-cache purge wasn't enough) before using your nvcc settings.

**Comment by apulver** [comment]
I don't really understand exactly how the cache works, but it might be a good idea to save the config along with cached content and then compare it to the current config whenever the cache is accessed. If it's different, then ignore the cached data.

**Comment by nouiz** [comment]
This is what we do (don't reuse the cache if the config flag changes).

I still don't understand this error, but it seem to be an nvcc error. The
flag you have added are just passed to nvidia, we don't do something with
it.

**Comment by lamblin** [comment]
We will stop supporting the old GPU back-end soon.
Does it work with the new one, based on libgpuarray?

**Comment by apulver** [comment]
Is the new backend used by default? I compiled and used the new backend a few months ago to work around an unrelated issue, but stopped using it because I was getting inconsistent results with some of my models. 

The bug is likely related to the issue/pull request I cited above. Did you look that over?

**Comment by lamblin** [comment]
The CPU is used by default.
If you use `device=gpu*`, it will use the old back-end.
If you use `device=cuda*`, it will use the new one.

It may be related to the issue you mentioned, especially if you have a second GPU with different compute capabilities on the same machine.
The new back-end should not be affected by that issue, which is why I asked.

**Comment by lamblin** [comment]
Also, lots of issues have been recently fixed in the new back-end, we believe it is safe to use now.

**Comment by apulver** [comment]
Good to know. Yes, I was using a configuration with two GPUs having different cuda architecture versions. I'm no longer using Debian on my machine, so it would be hard to say whether or not the bug is still there. I'll open another issue if it pops up again.

**Comment by lamblin** [comment]
OK, thanks.
