### ISSUE TITLE
Theano cannot detect clang++ in Mac OS X

### ISSUE THREAD

**Issue by pcyin** [Theano/Theano#5053]
I am using the dev version of theano under Mac OS X 10.11.3 with command line tools for Xcode 7. Running theano gives me the following warning:

`WARNING (theano.configdefaults): Only clang++ is supported. With g++, we end up with strange g++/OSX bugs.`

I've also got g++ installed. It seems theano cannot detect the ``clang++``.

Besides, I had strang NaN problems resulting from a simple calculation ``T.dot(W, X)`` where ``W`` and ``X`` do not have nan value (checked with `np.any(np.isnan)`). I doubt this is because of I am not using `clang++`

**Comment by lamblin** [comment]
Are you setting `theano.config.cxx`, either in your `.theanorc` or in `THEANO_FLAGS`? What is its value?
Regarding the NaN issue, if you think it is a bug, please provide a reproducible example.

**Comment by Sentient07** [comment]
Xcode 7 has a bug in it. Even though you have X-code 7.x , there are chances that your mac might be using CLT 8.0 with X-code displaying the version wrong. The correct version details of command line tool could by checked with this command, `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables`.

**Comment by pcyin** [comment]
I didn't set `cxx`, but I checked its value, which was `cxx=/Library/Developer/CommandLineTools/usr/bin/clang++`. I believe it's a small bug in [configdefaults.py](https://github.com/Theano/Theano/blob/master/theano/configdefaults.py#L449), which gives me a warning even if `cxx` is correctly set by default.

Update: I do not have a minimal reproducible example. But I tried running on OS X 10.12 with Xcode 8.0 and the NaN issue disappears.

**Comment by pcyin** [comment]
Update: NaN issue solved by updating OS X from 10.11.3 to 10.11.6 and command line tools from 7.0 t0 7.3

**Comment by Sentient07** [comment]
> Update: I do not have a minimal reproducible example. But I tried running on OS X 10.12 with Xcode 8.0 and the NaN issue disappears.

Were you able to use CUDA with XCode 8.0 ? That seems strange to me. From what I saw in Nvidia's developer blogs, CUDA 8.0 works with only CLT/X Code 7.3.1. Could you please verify this ?

**Comment by nouiz** [comment]
For clang++, there is a fix here:

https://github.com/Theano/Theano/pull/5049/commits/66a32849b7801ef925d6a9c3554146bc34007962

On Thu, Oct 6, 2016 at 7:35 AM, Ramana Subramanyam <notifications@github.com
