### ISSUE TITLE
Port ProfileMode GPU and scan extra information

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5055]
PR https://github.com/Theano/Theano/pull/5054 removed ProfileMode.

There is still 2 things to port to the new profiler:
- (not needed, the old back-end is deprecated) ~~Port gpu stats to the new profiler (https://github.com/Theano/Theano/pull/5054/files#diff-8f504707a80fc0f2baf16a8847aae2c8). The commanted change in the file theano/sandbox/cuda/basic_ops.py in case the good section don't show up.~~
- [ ] Make a new registry like theano.compile.profilemode.register_profiler_printer in the new profiler in theano/compile/profiling.py. Add a variable "_profiler_printer=[]" and a decorator like https://github.com/Theano/Theano/pull/5054/files#diff-0b102f2db511e60cadfb19a10f8c3356L768.
- [ ] Port [gpu stats](https://github.com/Theano/Theano/pull/5054/files#diff-8f504707a80fc0f2baf16a8847aae2c8) to the new back-end. Mostly port the function profile_printer from the file theano/sandbox/cuda/basic_ops.py to theano/gpuarray/basic_ops.py that use the new register_profile_printer() method created above.
- [ ] Port scan stats (verify first it is now in the current scan stats) (https://github.com/Theano/Theano/pull/5054/files#diff-5bef5ca45d04a952bc292575d565258aR2835) Mostly, update the function profile_printer in theano/scan_module/scan_op.py to use the new profiler/register above)

**Comment by Sentient07** [comment]
What GPU stats are to be ported to the new backend ?

**Comment by nouiz** [comment]
Check the PR, there is 2 todo comment.

**Comment by Saizheng** [comment]
https://github.com/Theano/Theano/pull/5455
