### ISSUE TITLE
Importing theano consumes a lot of memory when the device flag is set to cuda/gpu

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#5059]
When I try to just import theano, the memory the import takes is around 125Mb when I use the old backend and 37.5Mb when I use the new backend. When I don't use use any flags for the device (the cpu mode), it takes ~9Mb. I don't understand why there is spike in the memory with just an import statement. 
I used this [package](https://pypi.python.org/pypi/memory_profiler) for memory profiling.
My relevant code where I found this ambiguity :  http://pastebin.com/EAbqnCLx

**Comment by nouiz** [comment]
It is normal that an import raise the memory usage. The new code and
libraries used must go in the RAM. Using GPU request more libraries, so it
is normal that this use more CPU memory.

It is great to see the new backend use less memory. This surprise me.

Le 6 oct. 2016 15:57, "Ramana Subramanyam" <notifications@github.com> a
écrit :
