### ISSUE TITLE
check_equal_numpy returns True for unequal ndarrays

### ISSUE THREAD

**Issue by medakk** [Theano/Theano#5064]
The function `check_equal_numpy` defined in [tensor/basic.py](https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py#L66) returns True when given unequal ndarrays. To be precise, the function (wrongly) returns True if all of the following are true:

1. Both the arguments `x` and `y` are instances of `ndarray`
2. Both the arguments `x` and `y` have equal `shape` and `dtype`
3. If **any** element in `abs(x-y)` is less than 1e-10

I believe it should be **all** elements, not **any**.

Here is a REPL session demonstrating this issue:
```
>>> import theano
>>> import numpy as np
>>> A = np.array([1,2,3,4,5])
>>> B = np.array([9,8,7,6,5])
>>> theano.tensor.check_equal_numpy(A, B)
True
```

The fix would be to change `numpy.any` to `numpy.all` in that function.

**Comment by nouiz** [comment]
thanks. Do you want to make a PR to fix that? That way you will have your
nae in the history of Theano.

Otherwise, I can do it.

**Comment by medakk** [comment]
I'll make a PR.
