### ISSUE TITLE
When will the next release be?

### ISSUE THREAD

**Issue by ericmjl** [Theano/Theano#5074]
I'm a conda-forge recipe maintainer for pymc3. 

Theano 0.8.2 crashes 12" MacBooks when used with PyMC3. I get an error akin to what's shown [here](https://github.com/pymc-devs/pymc3/issues/1361). I had to install theano from source (version 0.9-dev) to get pymc3 to work. I was just wondering, when will a new release be updated? No worries if the devs here decide to close this thread without answering, just asking out of curiosity.

**Comment by nouiz** [comment]
When we can. No timeline... Ideally this year.

If people want to help us, tell it. There is a few things to do first.
