### ISSUE TITLE
Theano issue while running LSTM

### ISSUE THREAD

**Issue by sa-j** [Theano/Theano#5080]
Hi, 
I am trying to run the neural network from https://github.com/junfenglx/reasoning_attention

I created a python3.5 environment with anaconda, where I installed the Bleeding-edge version of Theano/Lasagne with

pip install --upgrade https://github.com/Theano/Theano/archive/master.zip
pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip

The following error message is depicted:

(py35)user1@machine:~/matchLSTM$ python ./snli_match_lstm.py 
Loading data ...
Loading train ...
550152
550149
549364
Loading dev ...
10000
10000
9842
Loading test ...
10000
10000
9824
num_epochs: 20
k: 300
batch_size: 30
display_frequency: 100
save_frequency: 1000
load previous: False
Building network ...
unchanged_W.shape: (34283, 300)
oov_in_train_W.shape: (9166, 300)
apply dropout mask id 140482817419472 to embedding matrix ...
dropout rate is 0.3
input var is hypo_var
apply dropout mask id 140482817419472 to embedding matrix ...
dropout rate is 0.3
input var is premise_var
Computing updates ...
Compiling functions ...
Traceback (most recent call last):
File "/home/user1/anaconda2/envs/py35/lib/python3.5/site-packages/theano/compile/pfunc.py", line 193, in rebuild_collect_shared
allow_convert=False)
File "/home/user1/anaconda2/envs/py35/lib/python3.5/site-packages/theano/tensor/type.py", line 234, in filter_variable
self=self))
TypeError: Cannot convert Type TensorType(float64, matrix) (of Variable Elemwise{add,no_inplace}.0) into Type TensorType(float32, matrix). You can try to manually convert Elemwise{add,no_inplace}.0 into a TensorType(float32, matrix).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "./snli_match_lstm.py", line 325, in 
main(num_epochs=20, batch_size=30, load_previous=False)
File "./snli_match_lstm.py", line 213, in main
cost, updates=updates)
File "/home/user1/anaconda2/envs/py35/lib/python3.5/site-packages/theano/compile/function.py", line 326, in function
output_keys=output_keys)
File "/home/user1/anaconda2/envs/py35/lib/python3.5/site-packages/theano/compile/pfunc.py", line 447, in pfunc
no_default_updates=no_default_updates)
File "/home/user1/anaconda2/envs/py35/lib/python3.5/site-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

###### END OR ERROR MESSAGE ######

Could you please support me with this issue? Thank you!

**Comment by lamblin** [comment]
Please use theano-users or StackOverflow for support requests.
In that case, the error message tells you that your update expression for a variable is float64, but the original variable is float32. This is an error so that Theano does not silently reduce precision or waste computation.
If you want the computation to be all in float32, then you can set floatX=float32 and use `config.warn_float64` to check where the float64.
If you want the computation to be in float64, but the variable casted into float32, then cast the update explicitly into float32.
If you want the computation and variable to be float64, then define your shared variables as float64.
