### ISSUE TITLE
MaxAndArgmax ValueError

### ISSUE THREAD

**Issue by julianser** [Theano/Theano#5081]
I am using my own softmax function, which sometimes fails:

    def SoftMax(x):
        x = T.exp(x - T.max(x, axis=x.ndim-1, keepdims=True))
        return x / T.sum(x, axis=x.ndim-1, keepdims=True)

My graph compiles fine, but when I execute it it sometimes fails with this error (mode=FAST_COMPILE):

    Traceback (most recent call last):
      File "train.py", line 505, in <module>
        main(args)
      File "train.py", line 307, in main
        samples, costs = random_sampler.sample([sample_context], n_samples=1, n_turns=1)
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/search.py", line 55, in sample_apply
        samples, costs = sample_logic(sampler, joined_context, **kwargs) 
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/search.py", line 385, in sample
        next_probs, new_hd = self.next_probs_predictor(combined_hidden_states, prev_hd, prev_words, context)
      File "/u/serbaniv/THEANO_BLEEDING_EDGE/Theano/theano/compile/function_module.py", line 866, in __call__
        self.fn() if output_subset is None else\
      File "/u/serbaniv/THEANO_BLEEDING_EDGE/Theano/theano/gof/vm.py", line 304, in __call__
        link.raise_with_op(node, thunk)
      File "/u/serbaniv/THEANO_BLEEDING_EDGE/Theano/theano/gof/link.py", line 325, in raise_with_op
        reraise(exc_type, exc_value, exc_trace)
      File "/u/serbaniv/THEANO_BLEEDING_EDGE/Theano/theano/gof/vm.py", line 300, in __call__
        thunk()
      File "/u/serbaniv/THEANO_BLEEDING_EDGE/Theano/theano/gof/op.py", line 866, in rval
        r = p(n, [x[0] for x in i], o)
      File "/u/serbaniv/THEANO_BLEEDING_EDGE/Theano/theano/tensor/basic.py", line 1425, in perform
        (-1,))
    ValueError: total size of new array must be unchanged
    Apply node that caused the error: MaxAndArgmax(Elemwise{add,no_inplace}.0, TensorConstant{(1,) of 1})
    Toposort index: 69
    Inputs types: [TensorType(float32, matrix), TensorType(int64, (True,))]
    Inputs shapes: [(0, 23), (1,)]
    Inputs strides: [(92, 4), (8,)]
    Inputs values: [array([], shape=(0, 23), dtype=float32), array([1])]
    Outputs clients: [[InplaceDimShuffle{0,x}(max)], []]

    Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/search.py", line 119, in sample
        self.compile()
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/search.py", line 84, in compile
        self.next_probs_predictor = self.model.build_next_probs_function()
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/dialog_encdec.py", line 2143, in build_next_probs_function
        outputs, hd = self.utterance_decoder.build_next_probs_predictor(self.beam_hd_input, self.beam_source, self.beam_hd)
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/dialog_encdec.py", line 1369, in build_next_probs_predictor
        return self.build_decoder(inp, x, mode=UtteranceDecoder.BEAM_SEARCH, prev_state=prev_state)
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/dialog_encdec.py", line 1438, in build_decoder
        _res = f_dec(x, xmask, decoder_inp, hd_init)
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/dialog_encdec.py", line 1695, in LSTM_step
        softmax_outputs = self.output_softmax(pre_activ)
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/dialog_encdec.py", line 1377, in output_softmax
        return SoftMax(T.dot(pre_activ, self.Wd_emb.T) + self.bd_out)
      File "/data/lisatmp4/serbaniv/Dialog/MrRNN-latent-norm/utils.py", line 221, in SoftMax
        x = T.exp(x - T.max(x, axis=x.ndim-1, keepdims=True))

BUT, if I instead use the nnet version, i.e.:

    def SoftMax(x):
        return T.nnet.softmax(x)

then everything works fine. My graph is complicated, but could this be a bug in the T.max function?

Note, on my experiments, x is a TensorType(float32, matrix) with shape (1, 23) and I am using the bleeding edge Theano version: 146ef971fae05dc14ea10282b79f83e6796e94a0.

**Comment by nouiz** [comment]
It seem the MaxAndArgmax python code don't like it when the inputs shapes
is (0, 23). Is it normal that you have a tensor with 0 elements?

I don't know why using the nnet version don't cause this problem. Why you
don't use it? It is a stable version like your implementation and work on
the GPU. So I don't see a reason not to use it.

You could use the flag optimizer=fast_compile instead of the mode flags.
This will make the graph optimization phase as fast, but still use C code
(the first time it compile could be slower to compile the c code we cache).

**Comment by lamblin** [comment]
Yes, the issue is that `T.max(x, axis=x.ndim-1, keepdims=True)` does not work when `x.shape == (0, 23)`, because there is no maximum over axis 0.
I think `T.nnet.softmax` gets around that because it just returns an empty array without trying to do any computation on it.

**Comment by lamblin** [comment]
Wait, `x.ndim-1` is 1, not 0. So it should work, and indeed it works in numpy:
```python
>>> z = np.zeros((0, 23))
>>> z - z.max(axis=1, keepdims=True)
array([], shape=(0, 23), dtype=float64)
```

I'll have a look.

**Comment by lamblin** [comment]
OK, so it actually only happens in the Python code of `MaxAndArgmax`, which is forced by `mode='FAST_COMPILE'`. I'll have a PR soon.
Are you sure you do not mean `optimizer='fast_compile'` instead?

**Comment by julianser** [comment]
> It seem the MaxAndArgmax python code don't like it when the inputs shapes is (0, 23). Is it normal that you have a tensor with 0 elements?

Yes, the (0, 23) shape was a bit of an outlier. I have modified my own code so that it doesn't happen anymore. Even though it should work with a zero dimension, we may want to give the user a warning when this happens.

>  Are you sure you do not mean optimizer='fast_compile' instead?

I really mean mode='FAST_COMPILE'. This is how I launched the training script:

     THEANO_FLAGS=mode=FAST_COMPILE,device=cpu,floatX=float32 python train.py

**Comment by lamblin** [comment]
@julianser This should be fixed now.

I was just wondering why you were using `mode=FAST_COMPILE` rather than `optimizer=fast_compile`, since it completely disables C and CUDA code. The issue you exposed was only in the Python code for MaxAndArgmax, the C code was working fine.

**Comment by Sentient07** [comment]
There is a confusion between the two for a while and if you remember, I've
raised this problem earlier. I also have a branch added details to the doc
that mode=FAST_COMPILE doesn't work.

**Comment by nouiz** [comment]
mode=FAST_COMPILE work. But people sometimes would prefer
optimizer=fast_compile.

Making better doc about that is great. If you see problem with
mode=FAST_COMPILE, then make an issue about that.


mode=FAST_COMPILE don't work with gpu, but should work well on CPU.

**Comment by Sentient07** [comment]
How are they different ? IIRC, the tensor tests were failing. Mostly the tests involving nodes with Elemwise operations. Do I need to force use CPU or could it be `device=cpu,init_gpu_device=cuda*` ?

**Comment by nouiz** [comment]
Open an issue about that.
