### ISSUE TITLE
TX1 fp16 broken

### ISSUE THREAD

**Issue by guoxuesong** [Theano/Theano#5085]
I have a TX1. Theano require CUDA7.5 for float16 dot, but TX1 only has CUDA7.0
As mentioned in "https://devtalk.nvidia.com/default/topic/931678/jetson-tx1/64-bit-cuda-7-5-on-the-tx1/"
"Instead of releasing a separate CUDA toolkit 7.5 for Jetson TX1, features and maintenance fixes relevant to TX1 were backported and released as v7.0"
The following code in theano/gpuarray/opt.py disabled float16 dot support for TX1:

```
if nvcc_compiler.nvcc_version < '7.5':
    _logger.warning("Not performing dot of float16 on the GPU since "
                    "cuda 7.5 is not available. Updating could speed up "
                    "your code.")
    return
```

I tried commenting this and get theano works in my TX1. Using the lasagne mnist.py example, the best result is, for mlp it works and faster than float32, for cnn it works but a bit slower than float32, I changed dnn.conv.precision=as_input_f32 to float16, it's much slower. But memory was saved, this is good.

But now it's broken, GPU is idle, only CPU is used by theano. 20161013.

**Comment by nouiz** [comment]
On Thu, Oct 13, 2016 at 6:08 AM, guoxuesong <notifications@github.com>
wrote:

> I have a TX1. Theano require CUDA7.5 for float16 dot, but TX1 only has
> CUDA7.0
> As mentioned in "https://devtalk.nvidia.com/default/topic/931678/jetson-
> tx1/64-bit-cuda-7-5-on-the-tx1/"
> Instead of releasing a separate CUDA toolkit 7.5 for Jetson TX1, features
> and maintenance fixes relevant to TX1 were backported and released as v7.0
> The following code in theano/gpuarray/opt.py disabled float16 dot support
> for TX1:
>
> if nvcc_compiler.nvcc_version < '7.5':
> _logger.warning("Not performing dot of float16 on the GPU since "
> "cuda 7.5 is not available. Updating could speed up "
> "your code.")
> return
>
We could change the condition to be 7.5+ or tx1. Do you know how we can
detect we are on the tx1?



> I tried commenting this and get theano works in my TX1. Using the lasagne
> mnist.py example, the best result is, for mlp it works and faster than
> float32, for cnn it works but a bit slower than float32, I changed
> dnn.conv.precision=as_input_f32 to float16, it's much slower. But memory
> was saved, this is good.
>

Do you still have the timings? I would like to know how faster/slower those
conditions are. For the convolution, which version of cudnn did you use?
Can you update it?


> But now it's broken, GPU is idle, only CPU is used by theano. 20161006.
>
What is the date? Did you update Theano? Did you change Theano flags?
Somethings must have changed.

**Comment by guoxuesong** [comment]
> We could change the condition to be 7.5+ or tx1. Do you know how we can detect we are on the tx1?
The device name is GM20B.
> Do you still have the timings? I would like to know how faster/slower those conditions are. For the convolution, which version of cudnn did you use? Can you update it?
The log is gone,  faster/slower was not much, 10% or 20% maybe. cuDNN version 4007, THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float16,dnn.conv.algo_fwd=small,lib.cnmem=0.3,allow_gc=True,optimizer_verbose=False,enable_initial_driver_test=False
"Can you update it" do you mean "upgrade the cudnn" ? I donnot like to, I'm using the board now, It works fine.
> What is the date? Did you update Theano? Did you change Theano flags? Somethings must have changed.
I test it 20161006, the newest git version of Theano, THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float16,dnn.conv.algo_fwd=small,lib.cnmem=0.3,allow_gc=True,optimizer_verbose=False,enable_initial_driver_test=False,dnn.conv.precision=as_input_f32,assert_no_cpu_op=warn
I will test it again later.

**Comment by guoxuesong** [comment]
I test it again, Theano is updated 20161014 16:16

THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float16,dnn.conv.algo_fwd=small,lib.cnmem=0.3,allow_gc=True,optimizer_verbose=False,enable_initial_driver_test=False,dnn.conv.precision=as_input_f32,assert_no_cpu_op=warn

$ uname -a
Linux tegra-ubuntu 3.10.67 #1 SMP PREEMPT Thu Jun 23 17:19:29 CST 2016 aarch64 aarch64 aarch64 GNU/Linux

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Fri_Oct_16_15:23:46_CDT_2015
Cuda compilation tools, release 7.0, V7.0.70

$ python -u mnist.py mlp
Mapped name None to device cuda: GM20B
Using cuDNN version 4007 on context None
Loading data...
Building model and compiling functions...
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for MaxAndArgmax due to unsupported float16
Starting training...
Epoch 1 of 500 took 178.485s
  training loss:                2.198509
  validation loss:              1.843896
  validation accuracy:          65.37 %
Epoch 2 of 500 took 144.530s
  training loss:                1.809640
  validation loss:              1.395117
  validation accuracy:          75.08 %
Epoch 3 of 500 took 146.013s
  training loss:                1.468566
  validation loss:              1.037061
  validation accuracy:          80.00 %
Epoch 4 of 500 took 145.343s
  training loss:                1.220353
  validation loss:              0.820361
  validation accuracy:          82.26 %

top shows:
 6389 ubuntu    20   0  620024 496536  78624 R  90.4 12.6  10:17.16 python

tegrastats output:
RAM 1051/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [0%,95%,2%,5%]@1912 EMC 2%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1052/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [5%,22%,5%,69%]@1836 EMC 2%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1052/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [5%,33%,2%,62%]@1912 EMC 2%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1046/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [2%,95%,0%,0%]@1912 EMC 10%@408 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1052/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [10%,71%,8%,4%]@1912 EMC 3%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1052/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [3%,87%,1%,1%]@1224 EMC 11%@408 AVP 2%@12 VDE 0 GR3D 22%@76 EDP limit 1912
RAM 1052/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [4%,84%,10%,5%]@1326 EMC 3%@1600 AVP 2%@12 VDE 0 GR3D 0%@153 EDP limit 1912
RAM 1052/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [4%,4%,95%,12%]@1912 EMC 3%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1051/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [4%,6%,31%,55%]@1428 EMC 2%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912
RAM 1046/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [9%,21%,4%,75%]@1632 EMC 3%@1600 AVP 2%@12 VDE 0 GR3D 40%@76 EDP limit 1912
RAM 1051/3854MB (lfb 10x4MB) SWAP 26/4096MB (cached 3MB) cpu [1%,95%,0%,0%]@1912 EMC 3%@1600 AVP 2%@12 VDE 0 GR3D 0%@76 EDP limit 1912

GR3D 0%@76 shows GPU is totally idle, rarely GR3D 22%@76

**Comment by guoxuesong** [comment]
I interrupted mnist.py after the first epoch, got thie:

$ python mnist.py mlp
Mapped name None to device cuda: GM20B
*** Error in `/usr/bin/g++': double free or corruption (top): 0x0009d170 ***
Using cuDNN version 4007 on context None
Loading data...
Building model and compiling functions...
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for dot due to unsupported float16
Disabling C code for MaxAndArgmax due to unsupported float16
Starting training...
Epoch 1 of 500 took 179.753s
  training loss:                2.203725
  validation loss:              1.861719
  validation accuracy:          65.41 %
^CTraceback (most recent call last):
  File "mnist.py", line 360, in <module>
    main(**kwargs)
  File "mnist.py", line 297, in main
    train_err += train_fn(inputs, targets)
  File "/home/ubuntu/Theano/theano/compile/function_module.py", line 866, in __call__
    self.fn() if output_subset is None else\
  File "/home/ubuntu/Theano/theano/gof/op.py", line 861, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/ubuntu/Theano/theano/tensor/basic.py", line 5580, in perform
    z[0] = numpy.asarray(numpy.dot(x, y))
KeyboardInterrupt

It looks like theano was using CPU to compute Dot op, is this normal ?

**Comment by nouiz** [comment]
If the input are in float 64, then yes. The old backend only support
float32. Use the Theano flag warn_float64 to help you detect update to
float 64 if this is the problem.

**Comment by guoxuesong** [comment]
> If the input are in float 64, then yes. The old backend only support float32. Use the Theano flag warn_float64 to help you detect update to float 64 if this is the problem.

warn_float64 not helps, It's not a float64 problem, and the new backend is used.

**Comment by guoxuesong** [comment]
It turn out not a theano issue, It's Lasagne's dropout layer that returned a float32 tensor.
Thanks for your help.

Now, on my Tx1, float16 mnist mlp without dropout takes 1.65s per epoch.  float32 mnist mlp without dropout takse 3.71s

You did a great job! 
 I will test cnn later.

**Comment by guoxuesong** [comment]
TX1 fp16 Lasagne mnist cnn without dropout dnn.conv.precision=as_input 26.0s at epoch 8 ; dnn.conv.precision=as_input_f32 24.3s at epoch 8; 

fp32 15.1s

**Comment by lamblin** [comment]
It looks like the issue was resolved, so I'm closing.
