### ISSUE TITLE
Blocks test broken by recent commit

### ISSUE THREAD

**Issue by dwf** [Theano/Theano#5088]
```
a16e91f7933e20b1ae77c1d43f8278af9333f2ab is the first bad commit
commit a16e91f7933e20b1ae77c1d43f8278af9333f2ab
Author: Gijs van Tulder <gvtulder@gmail.com>
Date:   Thu Sep 15 17:24:08 2016 +0200

    theano.tensor.signal.Pool with 3D support.

:040000 040000 c969fd3fe408357f15e9403f6d6bc15b240ef1c9 8855314caee1ac5adf9d234961c37628409eeaf5 M      theano
bisect run success
```

**Comment by dwf** [comment]
A simplified failing test case.
```python
from theano.tensor.signal.pool import Pool


def test_wrong_shape():
    assert Pool.out_shape((9, 8, 6), (2, 2)) == [9, 4, 3]
```

This is an embarassment, and a16e91f7933e20b1ae77c1d43f8278af9333f2ab is a living argument for small, granular commits, ladies and gentlemen.

**Comment by dwf** [comment]
Seems that it's specifically this assumption: https://github.com/Theano/Theano/commit/a16e91f7933e20b1ae77c1d43f8278af9333f2ab#diff-7e13e905a5451cdcfd78519fcca02c2fR210

which is a breaking change.

**Comment by nouiz** [comment]
In the code before, we where doing the inverse. Mostly, suppose that we
pooling over the last 2 dimensions.

Did you try to just do that? For 3d pool, we would need to pass the ndim=3
parameter.

**Comment by dwf** [comment]
See my referenced pull request. We are using (channels, height, width)
input for shape computation and the new code assuming a default of ndim-2
means only width gets computed correctly.

**Comment by nouiz** [comment]
I have a PR, the CPU tests pass.
