### ISSUE TITLE
Opt: IncSubtensor(zeros, x, ...) -> SetSubtensor(zeros, x,  ...)

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5094]
See https://github.com/Theano/Theano/pull/5086/commits/1649d3eac9742347254d6de512954f3767233e56

I suppose this can stay in the final graph if there is no add.

**Comment by lamblin** [comment]
I'm not convinced there is anything to gain from doing that.
Apart maybe in the case where we have both inc_subtensor and set_subtensor with the same indices, then they could be merged.

**Comment by nouiz** [comment]
I think you didn't understand what I want by this optimization.
The goal is to transforme  IncSubtensor(zeros, x , slices/ints) to
SetSubtensor(zeros, x slices/ints)

There is no merge needed. This is a local opt on only 1 node with the
condition that the source is zeros.

This will save execution time as we won't need to read the zeros, we will
only overwrite them. I didn't saw this as a bottleneck, but I saw this in
some graph. I don't remember which graph, it was maybe tests, not real
model. This is low priority.

**Comment by lamblin** [comment]
OK, let me clarify.
I don't think that reading the zeros will make a measurable difference in practice. In the inplace case, we will have to write to that memory anyway, in the no-inplace case the rest of the array will need to be copied.
However, if for some reason there is both `set_subtensor(zeros[idx], x)` and `inc_subtensor(zeros[idx], x)` in the same graph, then having a standard form may help merge them (and potentially further computation as well). I have no idea if it happens in real life, though.
