### ISSUE TITLE
Wrong optimization on reshape

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5099]
So I have the latest Theano and I have a program with sampling and quite a few dimshuffles. When I run it with `optimizer=None` or `optimizer=fast_compile` everything is fine, however with full optimization I get:

```
ValueError: Input dimension mis-match. (input[0].shape[0] = 100, input[1].shape[0] = 1300)
Apply node that caused the error: Elemwise{Composite{(sqr((i0 - i1)) / i2)}}(Elemwise{switch,no_inplace}.0, InplaceDimShuffle{0,x,1}.0, InplaceDimShuffle{0,x,1}.0)
Toposort index: 744
Inputs types: [TensorType(float32, 3D), TensorType(float32, (False, True, False)), TensorType(float32, (False, True, False))]
Inputs shapes: [(100, 13, 32), (1300, 1, 32), (1300, 1, 32)]
Inputs strides: [(1664, 128, 4), (128, 128, 4), (128, 128, 4)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [[if{inplace}(Elemwise{eq,no_inplace}.0, Elemwise{Composite{(sqr((i0 - i1)) / i2)}}.0, Elemwise{Composite{(sqr((i0 - i1)) / i2)}}[(0, 0)].0)]]
```

This is both in python 2.7 and 3.4. The second operand (I think, but hard to confirm cause I can't debug on full optimization) should have been reshaped to (100, 13, 32). It seems that the optimization is screwing it up. At the moment I'm trying to digest where exactly this happens so I can create a minimal example of this.

**Comment by nouiz** [comment]
Can you run it with all those Theano flags? It will be super slow, but it
should help find where this happen.

mode=DebugMode
DebugMode.patience=1
DebugMode.check_py=False

**Comment by botev** [comment]
Ok so it seems to be coming from the following segment of code (the theano_print_shape essentially just wraps a Print operator that shows the shape but returns the whole variable for debugging):
```
        x = x.reshape((N, K, D))
        x = theano_print_shape(x, self.name + "_x+")
        mu = theano_print_shape(mu, self.name + "_mu+")
        var = theano_print_shape(var, self.name + "_var+")
        N = Print(self.name + "_n+")(N)
        K = Print(self.name + "_k+")(K)
        D = Print(self.name + "_d+")(D)
        l_t = (x - mu.dimshuffle(0, 'x', 1)) ** 2 / var.dimshuffle(0, 'x', 1)
        l_f = (x - mu.reshape((N, K, D))) ** 2 / var.reshape((N, K, D))
        cond = T.eq(mu.shape[0], N)
        cond = Print(self.name + "_cond")(cond)
        l = ifelse(cond, l_t, l_f)
        l = theano_print_shape(l, self.name + "_l")
```
The output of this is:
```
importance_log_ll_p_2_n+ __str__ = 100
importance_log_ll_p_2_cond __str__ = 0
importance_log_ll_p_2_x+ __str__ = [100  13  64]
importance_log_ll_p_2_mu __str__ = [1300   64]
importance_log_ll_p_2_mu+ __str__ = [1300   64]
importance_log_ll_p_2_var __str__ = [1300   64]
importance_log_ll_p_2_var+ __str__ = [1300   64]
```
So I guess it is related to the `ifelse` since the condition is 0, it should have reshaped the variables to `(100, 13, 64)` but it didn't. The error otherwise is the same

**Comment by botev** [comment]
Ok so I changed such that this conditioning is outside Theano, since it is static for my problem. Now again for `optimizer` None and fast_compile it works, however for full optimizer now I get:
```
/usr/local/bin/run_experiment: line 3:  5174 Floating point exception(core dumped) python3 -u /media/hdd/work/python/Toppings/bin/run_experiment.py $*
```
Note that this is even in the CPU. Its starting to become a chase down the rabbit hole...

**Comment by lamblin** [comment]
The segfault is worrying, do you think you could run python from `gdb` and see where it is coming from? I think you can add debugging symbols to the C code generated by Theano by adding flags to `gcc.cxx_flags` or something like that.
What happens if you completely disable shape inference with `optimizer_excluding=ShapeOpt`?

**Comment by botev** [comment]
Well I found out that later in the code I had a similar `ifelse` to the one here. After removing and that everything was ok. It seems that for some reason the `ifelse` was getting the wrong branch, which made it create a tensor of size `(N, 0, D)` and possibly somewhere later I divide by the middle shape (or do a mean on `axis=1`). Nevertheless, all seems to point to the `ifelse` not being evaluated correctly.

**Comment by nouiz** [comment]
ifelse (sadly) do not always garantie that the not taken branch won't be executed. It tries, but in combination with other Theano optimization there is cases where we execute both branch and select the good one.

This problem is already in this issue: https://github.com/Theano/Theano/issues/1318

**Comment by nouiz** [comment]
as there is another issue about the ifelse, I'm closing this one.
