### ISSUE TITLE
Tests fail on optimizer=fast_compile

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#5100]
Earlier, @nouiz and I had discussion of whether `optimizer=fast_compile` or `mode=FAST_COMPILE` that creates problem. With `optimizer=fast_compile` and device=cpu few tests fail in `theano/tensor/tests/test_opt.py`. One among them is `theano.tensor.tests.test_opt.T_Tile`. Also, earlier I reported that it was mode=FAST_COMPILE that fails with the current test suites, but even optimizer=fast_compile also fails.

**Comment by Sentient07** [comment]
I know travis tests with mode=FAST_COMPILE flag, but i don't know how these errors went undetected. The failure of a test (one out of many) on the current master:
```
======================================================================
FAIL: test_remove_alloc_w_dimshuffle (theano.tensor.tests.test_opt.Test_local_elemwise_alloc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/tensor/tests/test_opt.py", line 3251, in test_remove_alloc_w_dimshuffle
    mode=self.fast_run_mode
  File "/Users/Ramana/projects/theano/Theano/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/Users/Ramana/projects/theano/Theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/Users/Ramana/projects/theano/Theano/theano/compile/function_module.py", line 1777, in orig_function
    defaults)
  File "/Users/Ramana/projects/theano/Theano/theano/compile/function_module.py", line 1644, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/Users/Ramana/projects/theano/Theano/theano/gof/vm.py", line 1053, in make_all
    impl=impl))
  File "/Users/Ramana/projects/theano/Theano/theano/gof/op.py", line 921, in make_thunk
    no_recycling)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/op.py", line 825, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/cmodule.py", line 1111, in module_from_key
    module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/cmodule.py", line 1021, in _get_from_hash
    self.check_key(key, key_data.key_pkl)
  File "/Users/Ramana/projects/theano/Theano/theano/gof/cmodule.py", line 1219, in check_key
    "Ops. The file is: %s. The key is: %s" % (msg, key_pkl, key))
AssertionError: ('The following error happened while compiling the node', Elemwise{eq,no_inplace}(TensorConstant{2}, Shape_i{1}.0), '\n', "Multiple equal keys found in unpickled KeyData file. Verify the __eq__ and __hash__ functions of your Ops. The file is: /Users/Ramana/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.10-64/tmp7LGxtS/key.pkl. The key is: (((12, (4,), (13, '1.11.0'), (13, '1.11.0'), (13, '1.11.0'), ('openmp', False)), (11, 13, '1.11.0'), (11, 13, '1.11.0'), (11, 13, '1.11.0')), ('CLinker.cmodule_key', ('-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION', '-O3', '-Wno-unused-label', '-Wno-unused-variable', '-Wno-write-strings', '-fPIC', '-fno-math-errno', '-m64', '-march=haswell', '-undefined', 'dynamic_lookup'), (), (), 'NPY_ABI_VERSION=0x1000009', u'c_compiler_str=/usr/bin/clang++ 4.2.1', 'md5:582ca1ab0a1bf8b3bb2de51389f37071', (<theano.tensor.elemwise.Elemwise object at 0x10df9b4d0>, ((TensorType(int64, scalar), (('b622c91fe5d0ce176124ac4dfc2619a4', 0, 0), False)), (TensorType(int64, scalar), ((-1, 1), False))), (1, (False,)))))")
```

**Comment by Sentient07** [comment]
I wonder why this happens! This is very much related to my work on the `frozendict` PR and I confirm that there weren't any changes when I checked out the branch. 
One of the test failures with optimizer=fast_compile , 
```
======================================================================
FAIL: test_local_useless_tile (theano.tensor.tests.test_opt.T_Tile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Ramana/projects/theano/Theano/theano/tensor/tests/test_opt.py", line 4254, in test_local_useless_tile
    assert len(topo) == 1
AssertionError
```
I will update this PR once the tests are complete. I'm starting it on my travis.

**Comment by lamblin** [comment]
One of the errors say "`Multiple equal keys found in unpickled KeyData file. Verify the __eq__ and __hash__ functions of your Ops. The file is: /Users/Ramana/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.10-64/tmp7LGxtS/key.pkl`".
Can you try clearing your cache, and running the test again on a clean master?

Regarding launching the tests with `optimizer=fast_compile`, unfortunately many tests are only trying to detect if they are running with `mode='FAST_COMPILE'` and adapt their behaviour in that case (or be skipped). For instance, `test_local_useless_tile` has the following code:
```python
if theano.config.mode == "FAST_COMPILE":
    mode = "FAST_RUN"
```
Ideally, they should be more precise.

**Comment by Sentient07** [comment]
I tried clearing cache before, the first time that I saw the error. But that didn't fix it. Later, I did `theano-cache purge` and deleted `~/.theano` . That helped with the error. 
What is the difference between `optimizer=fast_compile` and `mode=FAST_COMPILE` ? Both mean the same?

**Comment by nouiz** [comment]
They don't mean the same thing.

A mode is a combination of 2 things: a linker and an optimizer.
optimizer=fast_compile only change the default uptimizer to the same
mode=FAST_COMPILE. mode=FAST_COMPILE will also change the linker to don't
compile c code.

**Comment by nouiz** [comment]
Ideally they should be more precise, but this isn't a priority. I would not
recommend that you speed much time on this. If it is quick why not, but not
much time(or none)

**Comment by Sentient07** [comment]
I had tried resolving this in the PR where i have removed ShapeOptimizer from FAST_COMPILE. It's just few conditions at the beginning of tests, similar to what Pascal mentioned. Checking for where to apply them would be time consuming. I'll try this for weekend if I don't have anything

**Comment by nouiz** [comment]
You don't need that for removing ShapeOptimizer from FAST_COMPILE. This is
something not related.

But if you work on it, change the way we do it to make it easier and remove
code duplication. Make a function like get_fast_run_mode() that will do the
condition and return the good mode.

**Comment by nouiz** [comment]
As said, we don't support that and I don't think we should make tests support that. So I'm closing this issue.
