### ISSUE TITLE
Calling a compiled function for first time takes much longer on new backend

### ISSUE THREAD

**Issue by Sentient07** [Theano/Theano#5102]
Timing a simple matrix multiplication on the new backend, comparing with the old backend and on CPU mode gave me the following results. 
Time on new backend : 1.545019sec 
Time on old backend : 0.005173sec
Time on CPU : 0.001573sec
I also tested for second time, the same matrices. Then I observed the following result:
Time on new backend :  0.005586sec
Time on old backend : 0.005436sec
Time on CPU :  0.0014sec

Why does the new backend take so long for the first time computation ? 
The code I used : https://gist.github.com/Sentient07/a4b69b9a3ca9b2568ba7d70f872c1af3

**Comment by nouiz** [comment]
The first compilation is always slower. This is not dependent of the back-end. It happen also on CPU. If we need to compile c code, it is always taking more time. But after that, we cache and reuse the c code, so it is faster.

**Comment by Sentient07** [comment]
Yes, I can understand if the compilation is slower. But the call to the compiled function that seems slower. Also, why is it 1.5sec on new backend while it's 0.05sec on the old backend?

**Comment by lamblin** [comment]
If I understand correctly, there is on-the-fly compilation of GPU code in the new back-end, and it is not cached in a persistent way. This could be added in the future.

**Comment by Sentient07** [comment]
Okay, that explains. I will investigate more on this and propose a change if feasible

**Comment by nouiz** [comment]
The fix is a compilation cache in C in GPU array. This request advanced C
skill.

Le 18 oct. 2016 08:45, "Ramana Subramanyam" <notifications@github.com> a
écrit :
