### ISSUE TITLE
Generalize Scan memory/speed trade-off

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5106]
https://github.com/Theano/Theano/issues/4124 issue was about adding that.

Current implementation have this restriction that we want to lift:
- [ ] The value of `save_every_N` divides the number of steps the scan will run without remainder.

I'm not sure we should lift this limit. What do you think?
- Only singly-recurrent and non-recurrent outputs are used. No multiple recurrences.

**Comment by nouiz** [comment]
The first thing to try to implement is to pass just the slice to the inner scan with the right shape. If all goes well, it will work. But maybe something will request that the inner scan have the same number of step. In that case, we could pad in the outer scan the slice to always have the same size.

**Comment by Thrandis** [comment]
@nouiz Just a quick note that we discussed with @lamblin and we have no choice but padding the input because of the reshape of the sequences:
```python
o_sequences = [s.reshape([s.shape[0] / save_every_N, save_every_N] +
                           [s.shape[i] for i in range(1, s.ndim)],
                          s.ndim + 1) for s in sequences]
```
Here we definitively need to have sequences with length that are a multiple of `save_every_N`. So we will pad the input sequence.

**Comment by nouiz** [comment]
ok. I think we should pad by default, but add a parameter to not pad, so
that people that can garanty the shapes are good, won't pay this price.

Should we do such a pad op? This appear at a few different places and
having an op in the graph that would garanty we have it optimized (return a
view if no pad needed) would be very useful. I don't think we can rely on
ifelse to do that well in all cases without side effect that aren't fun.

**Comment by nouiz** [comment]
I'm thinking about that again. SetSubtensor and variant, if they see that we override the full tensor, could return a view on the original data (if there is no broadcast too).

This would request that we do special code to force those nodes to be inplace on the value instead of the original data or change Theano to allow one output to be a view of many inputs.

Between those 3 options, the new op or added a new parameter to setsubtensor to be inplace on the value would be faster to implement then the last one.

What about @Thrandis implementing the not optimized code for now and make a new issue about adding that is needed for the optimized version in Theano?

**Comment by Thrandis** [comment]
@nouiz I'm ok with doing anything. It is true that since we do need padding, we should have an op for it!

**Comment by lamblin** [comment]
I think we should start with the un-optimized code so that it works and the interface is stable.
Then we can see how to optimize that memory-wise.

When we decide to optimize, I like the idea of SetSubtensor being inplace on the value. Another option may be to optimize the runtime of Join (instead of SetSubtensor) so that it can work inplace on an input if it is the only one with a nonzero size. All of these require to be able to work inplace on different inputs, though, which is its own can of worms.

**Comment by nouiz** [comment]
The SetSubtensor* won't work. It will only save the copy, it won't save the creation of a big tensor of zeros.

@Thrandis tried to use join. If we allow join to concatenate empty tensor (it crash now in that cases) then that would work. We could do the quick fix to make it inplace on the first inputs. So it don't ask the need to be inplace on many inputs.

This would reuse existing ops instead of creating a new ops. But this won't be a different interface then to numpy as we think numpy don't allow to do that, as we call numpy.concatenate.

**Comment by nouiz** [comment]
We decided to use Join with a Alloc of the needed size. https://github.com/Theano/Theano/issues/5253

is about making Join work inplace on the first inputs, so if we join empty tensor, then we can just return a view on the inputs. So it will be optimized when no padding are needed.
