### ISSUE TITLE
Document cuDNN RNN binding

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5109]
Follow-up to #4915.
We should document that we are supporting cuDNN v5's RNN bindings (without dropout) and their gradient, and make that easily searchable from the web and the built-in search box.

This could simply mean updating the docstrings of `RNNBlock` class, maybe adding an example and a few keywords, and then using `autodoc` to integrate it with Sphinx.

**Comment by souravsingh** [comment]
@lamblin The issue can be closed.

**Comment by nouiz** [comment]
I'm reopening as I think we need better doc. We don't have example usage. Also I think all the shapes stuff isn't well documented.
