### ISSUE TITLE
theano.tensor.take does not allow axis=-1 on GPU with optimization

### ISSUE THREAD

**Issue by BarclayII** [Theano/Theano#5112]
Here's the example:

``` python
import theano as T
import theano.tensor as TT
import numpy.random as RNG

a = TT.matrix()
f = T.function([a], a.take(0, axis=-1), allow_input_downcast=True)

print f(RNG.normal(0, 1, (30, 4)))
```

The code above works when running on CPU (optimization does not matter), and on GPU with the flag `"optimizer=None"`.  However, when running on GPU with optimization turned on (that is, without specifying the `"optimizer"` flag in `THEANO_FLAGS`), Theano fails and gives very confusing message:

```
ValueError: GpuReshape: given shape is of incorrect length (3 should be 1).
Apply node that caused the error: GpuReshape{1}(GpuDimShuffle{1,0}.0, MakeVector{dtype='int64'}.0)
Toposort index: 7
Inputs types: [CudaNdarrayType(float32, col), TensorType(int64, vector)]
Inputs shapes: [(30, 1), (3,)]
Inputs strides: [(1, 0), (8,)]
Inputs values: ['not shown', array([30, 30,  4])]
Outputs clients: [[HostFromGpu(GpuReshape{1}.0)]]
```

The version is 0.8.2

**Comment by nouiz** [comment]
Thanks for the report. I'm not sure when we can fix it, but you have an
easy work around by using the corresponding positive value for axis.

**Comment by lamblin** [comment]
The issue exists in the unoptimized graph as well, but gets hidden on CPU in that case, because apparently `Reshape{1}` does not check the length of the shape.
I think we may find a case where an incorrect shape would be returned on CPU.

**Comment by lamblin** [comment]
The issue is in the definition of `take` when axis is provided and the indices are not a vector (here, a scalar, but it could happen for a higher-dimension tensor as well), the shape build for the final reshape is not correct if axis < 0.
We would need to "normalize" the axes by adding a.ndim.
