### ISSUE TITLE
The SoftmaxGrad opt doesn't check the Elemwise type.

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#5113]
https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/nnet.py#L776

**Comment by lamblin** [comment]
It should match `true_div`.

**Comment by Knight-X** [comment]
Does anyone fix this bug ?

**Comment by nouiz** [comment]
Nobody started to work on it. Do you want to look at it?

thanks

**Comment by Knight-X** [comment]
Sure, I will start to fix it

**Comment by lamblin** [comment]
Actually, we assigned @adbrebs to work on it already.

**Comment by lamblin** [comment]
Fixed by #5214
