### ISSUE TITLE
Can any guys help me: nvcc.exe popup when theano compiles?

### ISSUE THREAD

**Issue by jf003320018** [Theano/Theano#5114]
I have installed theano. And I use keras to use it.  
But I found the "nvcc.exe“ always popup when theano compiles a file.
Does any guys meet this problem and finally solve it?

![qq 20161019125717](https://cloud.githubusercontent.com/assets/6231180/19506241/70d214c4-95fc-11e6-9d63-f604b9bd1534.png)

**Comment by carlthome** [comment]
Doesn't really seem like a problem? Theano uses nvcc to compile CUDA code.

**Comment by nouiz** [comment]
Update to Theano dev version. There was a change that could fix that.

But this is the first time I heard this specific problem.

**Comment by jf003320018** [comment]
@nouiz @carlthome I have tried this, but it does not work, thank you all the same.  I have ask many guys, they haven't met this problem. So I will try to reinstall CUDA. 
  This problem does not affect me to use theano, but it really affect my mood. Nvcc.exe pops up many times when a file is compiling. So during the compile time,  I cannot do any other things. 
  I will close this issue, but I hope any guys who solve this problem can tell me how to fix it. Thank you very much.

**Comment by nouiz** [comment]
Did you googled for nvcc create new windows?

**Comment by jf003320018** [comment]
@nouiz Yes, I has googled it. But I cannot find an answer.  I think something is wrong when I config the system, but I have tried many ways and have not found a solution.

**Comment by carlthome** [comment]
This might be relevant: http://stackoverflow.com/questions/1689015/run-python-script-without-windows-console-appearing

**Comment by jf003320018** [comment]
@carlthome Wow, this may be the reason. I find that anaconda4.2 has a bug when using the pythonw.exe. So I will reinstall all the stuff. And thank you.

**Comment by carlthome** [comment]
Cool. Glad to be of help.

**Comment by sroodhorst** [comment]
Currently I'm experiencing this nvcc.exe popup problem too.
I use Anaconda3-4.2.0 and Anaconda2-4.3.0, running a Unet in Keras with Theano backend. Tried to change my python files to .pyw, but the popup keeps appearing. 

OS: W7

Any new ideas on this problem?

**Comment by nouiz** [comment]
Did you try the suggested fix?

Make sure to use Theano 0.9rc1

**Comment by sroodhorst** [comment]
Yep, but currently fixed it partially by running it from a batch file / cmd.  
I use Theano version: 0.9.0rc1.dev, with cuda 8.0

**Comment by nouiz** [comment]
How do you execute Theano when you have pop up?

**Comment by sroodhorst** [comment]
I execute normally via Spyder (Anaconda), in the IPython console of Spyder.

**Comment by jf003320018** [comment]
@sroodhorst  Now I use Anaconda 4.1.1, the problem does not appear any more.

**Comment by wqp89324** [comment]
@jf003320018 so you are using an older version of Anaconda?

**Comment by jf003320018** [comment]
@wqp89324 Yes, I think Anaconda 4.1.1 is more stable than the newer version.  If you have this problem, Anaconda 4.1.1 should be a good version.

**Comment by wqp89324** [comment]
@jf003320018 but then you are stuck with older version of all related packages, numpy, etc?

**Comment by jf003320018** [comment]
@wqp89324 Of cousrse you can update them. Anaconda 4.1.1 just an IDE.

**Comment by skjerns** [comment]
I have the same problem with Anaconda 4.3.13. Quite annoying. Already tried quite a couple of things like replacing the nvcc with a .bat or a link or a symbolic link, nothing helps.

The solution above only helps against python files themself opening in a new window, but not the nvcc

**Comment by kaare-mikkelsen** [comment]
I have the same problem, and same setup. Spyder, ipython, conda 4.3.14, keras, theano. nvcc.exe pops up multiple times during compile.

**Comment by nouiz** [comment]
Use the new gpu back-end of Theano 0.9. It don't use nvcc anymore:)

see
https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

You can now install it with "conda install theano pygpu"

We are in the process to update our doc with that.

**Comment by skjerns** [comment]
Else my workaround:
Run the following python code, it automatically minimized the nvcc window

```
import win32gui
import win32com.client
import time
import sys
prev_hwnd = win32gui.GetForegroundWindow()
while True:
    firefox = []
    toplist = []
    winlist = []
    hwnd = win32gui.GetForegroundWindow()
    title =  win32gui.GetWindowText(hwnd)
    if 'nvcc.exe' in title.lower():
        try:
            shell = win32com.client.Dispatch("WScript.Shell")
            shell.SendKeys('%')
            win32gui.SetForegroundWindow(prev_hwnd)
            print('Minimized nvcc.exe')
            time.sleep(1)
        except:
            print("Error: ", sys.e
```xc_info()[0])
            time.sleep(1)
            pass
    else:
        prev_hwnd = hwnd

    time.sleep(0.001)

**Comment by FabianaMorais** [comment]
Hello @jf003320018,

I have a similar problem with nvcc.exe popup. I created an executable from Python script using Pyinstaller and on spec file options I hide the console.
However the nvcc.exe popup appear every time my code calls cuda driver compile…
I reinstalled CUDA, upgraded pyinstaller however I don´t fix the problem. Do you have any idea how to fix it? 
Regards
Fabiana
