### ISSUE TITLE
Optimization failure when adding result of set_subtensor on GPU

### ISSUE THREAD

**Issue by DoctorEyebrows** [Theano/Theano#5116]
I think I've found a problem with theano.tensor.set_subtensor on the GPU. There is some optimization failure when trying to add the result of set_subtensor to another tensor. Here is code that should reproduce the bug for version 0.9.0dev3.dev-418a5f1bdc5534cb1d421228dc243088ccf3afb6:

```
import theano
import theano.tensor as T

a = T.vector()
idx = T.ivector()
b = T.set_subtensor(a[idx], 1)
c = a + b

f = theano.function([a, idx], c)

print f([1,2,3,4,5], [2,4])
```

It compiles and runs correctly, but spits out the following optimization error (3 times):

```
ERROR (theano.gof.opt): Optimization failure due to: local_gpu_advanced_incsubtensor1
ERROR (theano.gof.opt): node: GpuFromHost(AdvancedIncSubtensor1{no_inplace,set}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/theano/gof/opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/opt.py", line 1142, in local_gpu_advanced_incsubtensor1
    as_cuda_ndarray_variable(y), *coords)]
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 46, in as_cuda_ndarray_variable
    return gpu_from_host(tensor_x)
  File "/usr/lib/python2.7/site-packages/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 132, in make_node
    dtype=x.dtype)()])
  File "/usr/lib/python2.7/site-packages/theano/sandbox/cuda/type.py", line 95, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype int16 for variable None
```

I don't know where the int16 came from, since `ivector` should be int32 by default according to the docs. If I compile to compute `b` instead (`f = theano.function([a, idx], b)`) then everything is fine, and `b` is output with `dtype=float32` so I don't know why theano can't add it to another float32 vector. Am I missing something obvious?

Here's my .theanorc:

```
[global]
floatX = float32
device = gpu
mode = FAST_RUN
profile=False

[nvcc]
fastmath = True
flags = -arch=sm_52 -ccbin=/usr/local/gcc-5.4/bin/g++
```

**Comment by nouiz** [comment]
if you do:


b = T.set_subtensor(a[idx], 1.)

instead of

b = T.set_subtensor(a[idx], 1)

This problem is related to the fact that we only support float32 in the old
back-end. I tested it and it work well in the new back-end. As we are
deprecating the old back-end and we are in rush, I don't plan to fix it in
the old back-end, but if someone does it, we will accept the fix.

You have a simple workaround for now.

**Comment by DoctorEyebrows** [comment]
Works well. Many thanks!

**Comment by lamblin** [comment]
Closing as this has been resolved.
