### ISSUE TITLE
SeqOptimizer Reports "Could not infer context from inputs" ValueError

### ISSUE THREAD

**Issue by kaniblu** [Theano/Theano#5118]
I was happily used `rel-0.8.2` version without a problem, but for the latest project I had to use multi-gpus, which require libgpuarray to be installed, so I upgraded theano to the latest version (67f31fb), then the perfectly running code starting to cause troubles:

```
Using gpu device 1: GeForce GTX 780 Ti (CNMeM is disabled, cuDNN 5005)
Mapped name dev0 to device cuda0: GeForce GTX 780 Ti
Using cuDNN version 5005 on context dev0
Mapped name dev1 to device cuda1: GeForce GTX 780 Ti
Using cuDNN version 5005 on context dev1
ERROR (theano.gof.opt): SeqOptimizer apply <theano.gpuarray.opt.GraphToGPU object at 0x7fee68e36bd0>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/kani/.local/lib/python2.7/site-packages/Theano-0.9.0.dev3-py2.7.egg/theano/gof/opt.py", line 235, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/kani/.local/lib/python2.7/site-packages/Theano-0.9.0.dev3-py2.7.egg/theano/gof/opt.py", line 87, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/kani/.local/lib/python2.7/site-packages/Theano-0.9.0.dev3-py2.7.egg/theano/gpuarray/opt.py", line 307, in apply
    target = infer_context_name(*fgraph.inputs)
  File "/home/kani/.local/lib/python2.7/site-packages/Theano-0.9.0.dev3-py2.7.egg/theano/gpuarray/basic_ops.py", line 122, in infer_context_name
    raise ValueError("Could not infer context from inputs")
ValueError: Could not infer context from inputs
```

I was using the following `THEANO_FLAGS`: 

```
mode=FAST_RUN,device=gpu1,floatX=float32,contexts=dev0->cuda0;dev1->cuda1
```

And the code I was trying to run is as follows. Let me remind you that it worked perfectly before upgrading to development version (v0.9.0).

```
import numpy as np
import theano
import theano.tensor as T
from collections import OrderedDict

def init_params(size):
    return np.random.normal(0, 0.1, size=size).astype(np.float32)

def glorot_init(n_in, n_out):
    return np.random.normal(0, 2.0 / (n_in + n_out), size=(n_in, n_out)).astype(np.float32)

def empty(*size):
    return np.zeros(size).astype(np.float32)

def adagrad(grads, params, learning_rate=1.0, epsilon=1e-6):
    updates = OrderedDict()

    for param, grad in zip(params, grads):
        value = param.get_value(borrow=True)
        accu = theano.shared(np.zeros(value.shape, dtype=value.dtype),
                             broadcastable=param.broadcastable)
        accu_new = accu + grad ** 2
        updates[accu] = accu_new
        updates[param] = param - (learning_rate * grad /
                                  T.sqrt(accu_new + epsilon))

    return updates

def lstm_step(x, c_prev, h_prev, W_f, b_f, W_n, b_n, W_m, b_m, W_e, b_e):
    u = T.concatenate((h_prev, x), axis=1)
    f = T.nnet.sigmoid(T.dot(u, W_f) + b_f)
    i = T.nnet.sigmoid(T.dot(u, W_n) + b_n)
    m = T.nnet.sigmoid(T.dot(u, W_m) + b_m)
    o = T.nnet.sigmoid(T.dot(u, W_e) + b_e)

    c = f * c_prev + i * m
    h = o * T.tanh(c)

    return c, h

lstm_size = 512
vocab_size = 300

n_epoch = 10
data_size = 1000000

batch_size = 1000
bptt_size = 50

W_f = theano.shared(glorot_init(lstm_size * 2, lstm_size))
W_n = theano.shared(glorot_init(lstm_size * 2, lstm_size))
W_m = theano.shared(glorot_init(lstm_size * 2, lstm_size))
W_e = theano.shared(glorot_init(lstm_size * 2, lstm_size))
b_f = theano.shared(init_params((lstm_size, )))
b_n = theano.shared(init_params((lstm_size, )))
b_m = theano.shared(init_params((lstm_size, )))
b_e = theano.shared(init_params((lstm_size, )))

W_i = theano.shared(glorot_init(vocab_size, lstm_size))

W_o = theano.shared(glorot_init(lstm_size, vocab_size))
b_o = theano.shared(init_params((vocab_size, )))

lstm_params = (W_f, b_f, W_n, b_n, W_m, b_m, W_e, b_e)
params = (W_i, W_o, b_o)

x = T.imatrix()
t = T.imatrix()

c0 = T.matrix()
h0 = T.matrix()

x_e = W_i[x]

lr = T.scalar()

(c, h), _ = theano.scan(lstm_step, sequences=x_e, outputs_info=(c0, h0), non_sequences=lstm_params)
h = T.reshape(h, (-1, lstm_size))
o = T.nnet.softmax(T.dot(h, W_o) + b_o)

loss = T.nnet.categorical_crossentropy(o, T.reshape(t, (-1, ))).mean()
y = T.reshape(T.argmax(o, axis=1), (-1, batch_size))

gradients = T.grad(loss, lstm_params + params)
train = theano.function((x, t, c0, h0, lr), loss, updates=adagrad(gradients, lstm_params + params), on_unused_input='ignore')
test = theano.function((x, c0, h0), y)

data = np.random.randint(vocab_size, size=data_size, dtype=np.int32)

for i in range(n_epoch):
    data_x = data.reshape((-1, batch_size, bptt_size))
    data_x = data_x.transpose((0, 2, 1))
    data_y = data.copy()
    np.roll(data_y, -1)
    data_y = data.reshape((-1, batch_size, bptt_size))
    data_y = data_y.transpose((0, 2, 1))

    for j, (dx, dy) in enumerate(zip(data_x, data_y)):
        l = train(dx, dy, empty(batch_size, lstm_size), empty(batch_size, lstm_size), 1)
        print("[{}/{}/{}] {}".format(j, i, n_epoch, l))
```

**Comment by nouiz** [comment]
First, try without multi GPU in the same process. This part isn't finished.
Multi GPU via platoon allow data parallelism and work well.

**Comment by kaniblu** [comment]
Thank you for your reply. Single GPU still doesn't work. I will have a look
on platoon as it looks quite promising.

**Comment by nouiz** [comment]
What error do you have with single GPU?

**Comment by kaniblu** [comment]
Single GPU works only when 'contexts' option is turned off in THEANO_FLAGS. Otherwise, the same error message is displayed.

**Comment by lamblin** [comment]
Please do not mix the old back-end (`gpu0`) with the new one (`cuda0`, `cuda1`) in the same process.
The issue seems to be that some variable is created with the old back-end, and the new back-end cannot figure out in which context it was.

**Comment by cshanbo** [comment]
Hi all,

I ran into the same error, too. 
My THEANO_FLAGS is like:
`THEANO_FLAGS="mode=FAST_RUN,floatX=float32,contexts=dev0->cuda0;dev1->cuda1"`
Then I change the THEANO_FLAGS to like:
`THEANO_FLAGS="mode=FAST_RUN,floatX=float32,contexts=dev0->cuda0;dev1->cuda1,device=cuda2"`. 
The error went away. 

In this setting, there will be 3 processes spawned on `cuda0`, `cuda1`, and `cuda2`, respectively. I'm not sure which gpu card will do the actual computing.

But I still got a question:
According to the [tutorial](http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html), I believe that we need to explicitly map the nodes in a graph to specific target, to make it work, like 
```
v12 = theano.shared(numpy.random.random((1024, 1024)).astype('float32'),
                    target='dev1')
```
Or will Theano herself make the computing on different GPUs automatically without settings like `target='dev1'`?

Thank you

**Comment by nouiz** [comment]
This part of Theano isn't well finished. I don't know if it is in a useable
state. What is sure in a usable state is the multi-GPU for data
parallelism. We foccused on that.

If you use the Theano flag context instead of device, you need to specify
the target of shared variable to distribute it to all the GPUs. I forgot if
by default we put on the first context of keep on CPU.

For computation, Theano try to infer where to do the computation. But this
is very gready. If all the inputs ends up on one GPU, then it is this GPU.
If they are on multiple GPU, it end up on one of those GPUs (most of the
time the first inputs of the node, but optimization make it hard to know
from a user point of view.

You can add transfer between GPUs or to a specific GPU before an operation
to make sure it get executed on that device.

But this isn't well tested.
