### ISSUE TITLE
ImportError, undefined symbol

### ISSUE THREAD

**Issue by xeray** [Theano/Theano#5141]
Hi,
after a new setup of anaconda and theano I get the following error on a host which was capable of running theano before the reinstall:

`ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x,x}(TensorConstant{-1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/opt.py", line 1922, in process_node
    replacements = lopt.transform(node)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/tensor/opt.py", line 6354, in constant_folding
    no_recycling=[], impl=impl)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1492, in compile_cmodule
    preargs=preargs)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2332, in compile_str
    return dlimport(lib_filename)
  File "/home/mfk/.local/lib/python2.7/site-packages/theano/gof/cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('/home/mfk/.theano/compiledir_Linux-4.8--ARCH-x86_64-with-glibc2.2.5--2.7.12-64/tmpHTbSbT/ad6edb4f9c10fef4cc23fcf2aafa22c3.so: undefined symbol: _ZdlPvm', '[InplaceDimShuffle{x,x}(TensorConstant{-1.0})]')`
- It basically happens for any function I try to compile and for various Ops.
- Although the name `_ZdlPvm` looks like a hash value it is constantly the same (even for release and git version of theano)
- I did not find any results googling that name
- The error even occurs with `py`-linker. Because of that I am not even sure whether this is related to the gcc version (which is 6.2.1)
- numpy version: 1.10.4
- scipy version: 0.17.1
- Will provide more details depending on whats needed

I would be grateful for any hint.

Cheers
Marius

**Comment by xeray** [comment]
Update:
`_ZdlPvm` seems to be related to too new gcc. I know you don't support incompatible versions, so I will keep looking for a solution myself and post it here if I find anything.

**Comment by nouiz** [comment]
The py linker can still compile c code during compilation.

Sorry, for now the only idea I have is due to some googling. If could be
related to change in Theano that isn't compatible with the compiler you
use. Can you try the Theano version you used when it was working?

**Comment by xeray** [comment]
Hi,

yes, you were right it was presumably a change in theano that rendered the gcc6.2.1 incompatible whereas it was compatible before (however only if using the compiler flags `-std=c++11 -D__CORRECT_ISO_CPP++_MATH_H_PROTO` which was quite a hack itself...).

The Fix for now:
`cxx =  .../g++-5` in `.theanorc`

**Comment by pananiko** [comment]
may i ask how this problem can be fixed?or which version of theano works on gcc 6.2.1

**Comment by nouiz** [comment]
I don't have the time to get more. But in many is you can install an older
gcc and use it. It was the previous user fix.

**Comment by jbruck** [comment]
Could you be a little more specific with what the cxx line should look like, I am using ubuntu 16.10. installed via pip or anaconda seems to make little difference. 

cxx = /usr/bin/g++-5

does not seem to help

**Comment by jbruck** [comment]
I believe this still affects the current development version 0.9.0rc4.dev-127ae529

**Comment by nouiz** [comment]
For the flags in theanorc file, it should be

[global]
cxx=/usr/bin/g++-5

But you didn't give your exact error message. Open a new issue with the full error message. Small change in the error message could make your case a different one then this one.

**Comment by jbruck** [comment]
I'm not sure whats changed, but somehow it seems to be working ... I know thats totally unhelpful, maybe I simply couldn't type that cxx line right, or something, but yeah ... I will come back if I have any more problems.  thanks for your help!

**Comment by dyang37** [comment]
Hi jbruck. I'm encountering the exact same problem here. So how exactly did you get it work. Did you pass the flag directly into the python compile command?
Appreciate you help!

**Comment by pananiko** [comment]
No i am not the jbruck. 

    Στις 3:53 μ.μ. Δευτέρα, 19 Ιουνίου 2017, ο/η dyang37 <notifications@github.com> έγραψε:
 

 Hi jbruck. I'm encountering the exact same problem here. So how exactly did you get it work. Did you pass the flag directly into the python compile command?
Appreciate you help!—
