### ISSUE TITLE
Implement PoolGradGrad for gpuarray

### ISSUE THREAD

**Issue by aam-at** [Theano/Theano#5145]
Currently, gpuarray backend does not have PoolGradGrad operation. Transferring to cpu to perform DownsampleGradGrad results in slow execution.

It is feature request but I also can try to implement it myself.

For gpuarray backend we use cudnn library. Can we implement PoolingGradGrad using existing cudnn functions?

**Comment by nouiz** [comment]
We have it in the old back-end in the file sandbox/cuda/blas.py in the
class GpuDownsampleFactorMaxGradGrad. We didn't ported it yet to the new
back-end. Do you want to help? Here is some doc about that:

http://deeplearning.net/software/theano_versions/dev/extending/extending_theano_gpu.html

You can base yourself on the old op. I don't think this can be done with
cudnn function.

**Comment by aam-at** [comment]
I ported MaxGradGrad for gpuarray backend in #5159. Further improvements include adding padding which will allow to use tensor variables and average pooling.
