### ISSUE TITLE
How to update a subset of weights from a tensorVariable

### ISSUE THREAD

**Issue by slegall56** [Theano/Theano#5148]
Hi, 

I want to do exactly as the code below ie get a subset of my ndarray shared variable : 

```
lookup_table = theano.shared(matrix_ndarray)
subset = lookup_table[vector_of_indices]
```

But in my case, vector_of_indices is a TensorVariable. 

How can I do ?

**Comment by nouiz** [comment]
Check this doc sections: http://deeplearning.net/software/theano/tutorial/faq_tutorial.html?highlight=inc_subtensor#how-to-update-a-subset-of-weights

Next time, ask user question on the theano-user mailing list. issues are for bug/features requets. Not user questions. thanks.
