### ISSUE TITLE
ERROR (theano.gof.opt): Optimization failure due to: constant_folding

### ISSUE THREAD

**Issue by 317070** [Theano/Theano#5158]
```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: Elemwise{add,no_inplace}(TensorConstant{60}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2}, TensorConstant{2})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/opt.py", line 1820, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/opt.py", line 6101, in constant_folding
    required = thunk()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 908, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 859, in perform
    super(Elemwise, self).perform(node, inputs, output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 762, in perform
    "Did you used Theano flags mode=FAST_COMPILE?"
MethodNotDefined: ('perform', <class 'theano.tensor.elemwise.Elemwise'>, 'Elemwise', 'Did you used Theano flags mode=FAST_COMPILE? You can use optimizer=fast_compile instead.')

```

I get this error during compilation, after which it runs fine. The only flag used is "device=cpu".
It seems that some optimizer is trying to do constant_folding, when that is only possible when there are less than 32 inputs: https://github.com/Theano/Theano/blob/master/theano/tensor/elemwise.py#L837
Was introduced in version 0.7 probably: https://github.com/Theano/Theano/commit/84825fc1409389dff889b23d412aa15046b4d90c

There is a wrong assumption here: https://github.com/Theano/Theano/blob/master/theano/tensor/opt.py#L6357

Therefore, the explanation of MakeVector is sometimes wrong. It is not always optimized away, when there are more than 32 (constant) inputs: https://github.com/Theano/Theano/blob/master/theano/tensor/opt.py#L731

In my case, I have the suspision that the calculation is done to compute the shape of some tensor somewhere (the numbers 60 and 2 are batch sizes). I have no idea how to further analyze this problem.

**Comment by nouiz** [comment]
Thanks for the report. You can safely ignore it. Your analysis is good.

To speed up constant_folding, we sometimes force the python code instead of
using the C code. But the python code don't support 32 or more inputs.

I have a PR that should fix this: https://github.com/Theano/Theano/pull/5163

Can you try it to confirm the fix?
