### ISSUE TITLE
Transposed Convolution figures confusion.

### ISSUE THREAD

**Issue by warmspringwinds** [Theano/Theano#5170]
Hello,

Recently, I have been following the Convolution Arithmetic tutorial
and was confused by the part where the equivalence between
transposed convolution and convolution with zero padding is shown.

The part that I am talking about is here:
http://deeplearning.net/software/theano_versions/dev/tutorial/conv_arithmetic.html#no-zero-padding-unit-strides-transposed

More specifically, if you look at the transposed convolution example (first image in the section that I have linked) -- the top left element of bigger matrix is equal to w_{0,0} * y(0,0) where y(0,0) is the top left element of the smaller matrix.

But if you look at the figure that follows after where the equivalence supposed to be shown.
The top left element of the matrix is equal to w_{2,2} * y(0,0).

Is it due to the fact that the matrix was rotated by 180 degrees (convolution is a cross correlation if you rotate the kernel matrix)?
Or is it a mistake?

**Comment by lamblin** [comment]
Exactly, the kernel needs to be flipped to get a transposed convolution, in addition to having padding.

**Comment by warmspringwinds** [comment]
@lamblin Thank you.

I have also found a written example of that [here](http://arxiv.org/pdf/1609.07009v1.pdf).

In the phrase:

```
We can see that the only
difference between these two operations is that the indices of the weights used when contributing to y
from x are different. If we reverse the element indices of filter f in the sub­pixel convolution then this
layer will be identical to a transposed convolution layer. 
```

And reversing the filter weights is equal to rotating matrix by 180 degrees.
