### ISSUE TITLE
Better document config.gpuarray.preallocate

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5186]
In particular, it should be made clearer that `config.lib.cnmem` affects only the old back-end, and that `config.gpuarray.preallocate` is its new-backend equivalent.

**Comment by gaebor** [comment]
The mere existence of these two options gives me a hunch that there is something wrong with the old-backend. Or, there is something which I don't understand.
The hunch is based on the fact that the same functionality is used via two different libraries.

What is the old-backend if not a precompiled gpuarray?

**Comment by nouiz** [comment]
It is 2 completly differents implementation with significant difference in
the goal.

But I understand that for users, they don't see much that differences and
we try to make the difference as much invisible as we can. But as the
default is different for both back-end, it was hard to reuse the same flag.
Especially as the implementation of that feature is very different in both
cases too.
