### ISSUE TITLE
Problem related to Seaborn Error Message 

### ISSUE THREAD

**Issue by furkat11** [Theano/Theano#5188]
when i import data into Python and tried to analyze it through Seaborn i got stuck in this problem that i have never seen before. Can any of you help me out with my problem please.thank you.
1.i imported the csv file via this code and it was successful;
import pandas as pd 
import os 
movies= pd.read_csv("Movie-Ratings.csv") 
2.then i used this code first in jupyter notebook: 
from matplotlib import pyplot as plt
import seaborn as sns 
%matplotlib inline 
import warnings 
warnings.filterwarnings('ignore')
3.And it went through successfully, Then i was stuck when i click next code ;
A = sns.barplot(x='Genre', y='CriticRating', data=movies) 
ValueError: Could not interpret input 'CriticRating'

Can any of you tell me what is the issue here....

Thank you

**Comment by lamblin** [comment]
This does not seem to have anything to do with Theano.
