### ISSUE TITLE
spot checks for testing conv more quickly

### ISSUE THREAD

**Issue by jaberg** [Theano/Theano#519]
To speed up the validation of auto-generated convolution kernels , run spot-checks on the output rather than validating the entire output.  This makes it tractable to validate large convolutions in unit tests.  For example

* test the corners of the output array

* test a few points along edges, faces of the array

* test a few points from the interior of the array

conclude that if all those points are right, the whole array is probably right, and move on to the next test.

**Comment by nouiz** [comment]
There is another ticket to tag slow and we did some speed up of convolution tests.
