### ISSUE TITLE
Add support of bool indexing in Theano

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5192]
Now that we support bool dtype in Theano, we should add the support for indexing with bool.

**Comment by khaotik** [comment]
Should this be implemented as an elemwise Op? (internally an if switch)

**Comment by nouiz** [comment]
If we just call numpy implementation, then it won't be hard to implement on
CPU.

There is 2 difficulties:
1) we need to determine the output size for this we need to do a first pass
on the bool mask
2) Then doing serially the copy isn't hard, but doing it in parallel is
more complicated. So the GPU version will be hard to do. Do to so and 1),
we should probably do a prefix scan first, this could give us the
destination index.

**Comment by lamblin** [comment]
The easiest immediate way of making that work would be to return `x[mask.nonzeros()]`, rather than implementing a new op.

**Comment by nouiz** [comment]
The corresponding keras issue: https://github.com/fchollet/keras/issues/4976

**Comment by nouiz** [comment]
Note, @lamblin suggestion would make this work on CPU and GPU.

But on CPU, we can just use the class AdvancedSubtensor. Its perform should work for that cases. Maybe small adjustment would be needed. It would be faster. This would need adjustment to the GPU opt of AdvancedSubtensor to introduce the nonzero() as I think the GPU version don't support it.

**Comment by nouiz** [comment]
Done in gh-6207, so I'll close this issue.
