### ISSUE TITLE
Anaconda/Windows documentation is out of date.

### ISSUE THREAD

**Issue by mingwandroid** [Theano/Theano#5202]
At http://deeplearning.net/software/theano/install_windows.html it states:

> Alternative: Anaconda
> ContinuumIO is providing a free Python distribution for Windows (32-bit and 64-bit), including all dependencies of Theano. If you are not eligible for a download of EPD or Canopy (via a commercial, or free academic licence), this is the easiest way to install Theano’s dependencies. Simply download and execute the installer from Anaconda download page, and execute the following in Windows command line:
>
> $ conda install mingw libpython

Conda's Theano package has a dependency on mingw-w64 GCC (m2w64-toolchain) now and so installing it is very simple. Could I request the following re-write:

> Alternative: Anaconda
> ContinuumIO provides a free Python distribution for all 3 main desktop operating systems, including Windows 32-bit and 64-bit, and includes Theano and all of its dependencies. This is the easiest way to install Theano on Windows. Simply download and execute the installer from Anaconda download page, and execute the following from the `Anaconda Prompt`:
>
> $ conda install theano

**Comment by nouiz** [comment]
The change is good, except for the last line. Kast time I checked, conda
had only a very old Theano 0.7. we should make sure they get Theano 0.8.2
or the dev version.

Do you want to make a pr with this? Can you confirm the version you have on
Theano in anaconda?

**Comment by mingwandroid** [comment]
I work at Continuum Analytics and I updated theano on all platforms to 0..8.2 recently.

**Comment by nouiz** [comment]
That is good news! Did you check if Theano link to mkl on Windows? We where
able to do so in the past, but recently it wasn't working anymore. I think
at some point you changed how mkl is installed or updated it and it broke
that.

You can check if Theano find blas and know how we link to it by running:

python -c "import theano; print theano.config.blas.ldflags"

It would be great if that work again, especially as now, our CPU
convolution is optimized to use blas. When we can't link directly to blas,
the convolution on CPU get a big hit of performance and features.

Thanks.

**Comment by mingwandroid** [comment]
PR incoming. I combined all my changes into the one PR.

**Comment by mingwandroid** [comment]
https://github.com/Theano/Theano/pull/5207

From Python 3.5 on Windows 64-bit:

```
> python -c "import theano; print(theano.config.blas.ldflags)"
-LC:\Users\ray\mc-x64-3.5\Library\bin -lmkl_core -lmkl_intel_thread -lmkl_rt
```

I'd actually like to move the Anaconda documentation higher up in that text file, but I thought it was a bit cheeky to do that without asking first, so I'm formally asking now :-)

MKL is enabled now, yes. Please feel free to try my Theano builds out on any desktop OS and let me know if there are any problems.

**Comment by nouiz** [comment]
I agree! Conda make installation much easier on Windows, so it make sence
to put it at the top.

You can move it at the top around line 34 without problems as the first
options people will see.

I don't have time to test now, but I'll try to so tomorrow or ask for some
help. I have a few comments on the PR.

Did you try with GPUs? I suppose not, but I'm asking just in case:)

thanks

**Comment by mingwandroid** [comment]
Thanks! I've not yet tested with GPUs as I only have a very old ATI graphics card.

**Comment by unkufunku** [comment]
Hello, Thanks for keeping theano on the boil for anaconda x64 win 10, python 3.5
I've installed the toolchain and theano 0.8.2 latest.
First I removed previous attempts and setup well.
Now sees g++ & vcm.
However, testing for mkl -> theano.config.blas.ldflags = ' '

I'm not sure, but output seems to indicate mkt-rt package should be installed.
My anaconda3 public install doesn't include these. Now installed.

How do I link the mkl enabled blas to theano?

many thanks
frank

**Comment by unkufunku** [comment]
re: previous msh. I think I made a bad move as the packages mentioned aren't as I assumed.
My question stands.
all help appreciated
frank

**Comment by unkufunku** [comment]
Hello,
I undid the mess and established system as before. whew!
still
theano.config.blas.ldflgs = ' '
Reading theano manual indicates uses default numpy operations rather than BLAS or MKL.
numpy uses mkl, so this could be correct way to go.

I found the numpy confgured mkl.
so I could add flag to .theanorc

[global]
device = cpu
[blas]
ldflags = 'mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll'

Is this a proper way to go about configuring theano to use mkl or should I leave as default?
thank
frank

**Comment by nouiz** [comment]
Now in conda, there is a theano 0.8.2 version. Make sure it is this one you
are using, not the one on pypi. It have a few fixes to c=use mkl correctly
with the more recent version of conda.

Also, there is a PR that give better support:
https://github.com/Theano/Theano/pull/5207, but it isn't ready to use.

**Comment by lamblin** [comment]
I'll close this one since #5290 has been merged.
See also #4643.
