### ISSUE TITLE
Retry theano import or check for free GPU

### ISSUE THREAD

**Issue by CCXD** [Theano/Theano#5203]
I'm trying to create a queuing system for a Python script that uses Theano.
If all GPUs are unavailable, it will give the import error upon importing Theano, and I'd like to retry this until it succeeds.
However, Theano does not do the device initialization when I reimport Theano, or delete the Theano modules manually and reimport Theano.
Is there some way to check for free GPU devices, or to reload Theano completely?

**Comment by nouiz** [comment]
Don't set device=gpu, let it at the default device=cpu.

Then
import theano.sandbox.cuda

Then maybe manually initilizing the GPU would work:

theano.sandbox.cuda.use("gpu0") # same param as flag device.

I didn't try what you want, but this could work.
