### ISSUE TITLE
Scan: broadcast pattern bug

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#5224]
This isn't very thoroughly examined, so I'm not sure about the title, but the symptoms are reproducible for quite a while (several months). They manifest when using an LSTM or GRU layer with a single unit (but not for a vanilla recurrent layer, or for multiple units).
Using bleeding-edge Lasagne:
```python
import theano
import theano.tensor as T
import lasagne
x = T.tensor3('x')
network = lasagne.layers.InputLayer((10,20,30), input_var=x)
network = lasagne.layers.GRULayer(network, num_units=1)
network = lasagne.layers.DenseLayer(network, num_units=2)
theano.grad(None, wrt=x, known_grads={lasagne.layers.get_output(network): T.matrix('y')})
```
This gives `TypeError: Cannot convert Type TensorType(float32, 3D) (of Variable Subtensor{:int64:}.0) into Type TensorType(float32, (False, False, True)). You can try to manually convert Subtensor{:int64:}.0 into a TensorType(float32, (False, False, True)).`
For a stack trace, see https://github.com/Lasagne/Lasagne/issues/730#issuecomment-249885421.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/issues/5384#issuecomment-273493711 is related (same error message) I think the cause is the same, but it should be verified. In the comment I linked above, I said what I think should be the way forward. That issue have an example that don't depend on lasagne, so would be a better starting point for a test then the example in this issue.

**Comment by nouiz** [comment]
After a long discussion with @lamblin it is not good in the case the user did an error it its inner function to post pone the error. This case happen frequently enough that we don't want to make this case more complicated, so we won't be more tolerant about such broadcast pattern difference.

But we should add a much better error message. Mostly, in scan, around that call to filter_variable, make a try...except. If the ndim and dtype are the same, but not the broadcastable, extend/add to the current error message.

Make 2 new error message. One if the inner function add an extra broadcast pattern, one if it remove it. Both case can happen in the case error as different dimensions could hit different case.

**Comment by f0k** [comment]
> #5384 (comment) is related (same error message) I think the cause is the same, but it should be verified.

I see, thank you for the hint! So you're saying the error may be that the output_info given to scan has a different broadcast pattern than what's returned by the inner loop function. I'll investigate.

> After a long discussion with @lamblin it is not good in the case the user did an error it its inner function to post pone the error. This case happen frequently enough that we don't want to make this case more complicated, so we won't be more tolerant about such broadcast pattern difference.

Yes, I agree. The solution is not to make Theano more tolerant about broadcasting patterns, but figure out why the broadcast patterns do not match up (which I initially assumed was due to Theano, but I'll recheck Lasagne and let you know).

**Comment by f0k** [comment]
> The solution is not to make Theano more tolerant about broadcasting patterns, but figure out why the broadcast patterns do not match up (which I initially assumed was due to Theano, but I'll recheck Lasagne and let you know).

Okay, thanks to your hint I found the culprit: `T.subtensor.Subtensor` does not infer broadcasts. [In Lasagne](https://github.com/Lasagne/Lasagne/blob/18292b2/lasagne/layers/recurrent.py#L1393-L1394), we have:
```python
def slice_w(x, n):
    return x[:, n*self.num_units:(n+1)*self.num_units]
```
When `self.num_units==1`, this returns a matrix of pattern `(False, False)`. As a workaround, I'll file a PR to Lasagne that makes the second axis broadcastable in this case, but the better solution would be to have Theano infer this automatically whenever possible.

Hmm, thinking again, Theano cannot know whether `x` is large enough so that `x[:, 3:4]` returns a nonempty matrix at all -- so it cannot infer the broadcast pattern. Theano needs shape inference, or another subtensor Op that asserts the input is large enough. I guess we should close this issue then, there's no easy fix for Theano.
