### ISSUE TITLE
Add an easy way of redefining gradients

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5225]
The following feature has been requested a couple of times: being able to define a new `Op`, where the forward operation (like `perform`) would be defined as a symbolic expression, and the gradient (`grad`) would be defined explicitly (not as the result of `theano.grad` on the forward expression).
This is useful in at least two cases:
- when we have an optimized formulation of a gradient, but Theano does not optimize it that way automatically
- when we want to redefine the backpropagation of an operation to something that is not mathematically equivalent to the true gradient.

The goal would be to have an subclass of `Op` where we could define `forward` and `grad`, and with an optimization replacing it by the symbolic expression defined in `forward`.

`OpFromGraph` has some useful bits, but also things that would not apply, and that would make the optimization difficult.
The plan would be to refactor `OpFromGraph` in 3 classes:
- a base class with everything that should be shared (maybe including the definition of `perform` given the internal graph)
- the current `OpFromGraph`
- the new class

and then have an optimization in the beginning (maybe the `useless` phase) replacing the new class with its internal graph.

**Comment by nouiz** [comment]
The optimization should be registered in both fast_run and fast_compile.

**Comment by khaotik** [comment]
I'm planning for a implementation. Not sure if suitable for merge with master. My plans so far:

1. make a base class `CompoundOp`, subclass `CompiledCompoundOp` and `InlineCompoundOp`.

2. make a API function `compound_op(inputs, outputs, inline=False, **kwargs)`

3. `OpFromGraph=CompiledCompoundOp` for compatibility

4. add optimization

Is this OK?

**Comment by nouiz** [comment]
The principe is good. I don't like Compound as this is too general. We have
many other ops that are compound op already, but done manualy for other
reason. So I would use BaseOpFromGraph, OpFromGraphOp and InlineOpFromGraph
name instead. If you have other name to suggest don't hesitate.

thanks

**Comment by lamblin** [comment]
@khaotik We assigned @adbrebs to work on that ticket already.

**Comment by lamblin** [comment]
As a general note, tickets tagged "CCW" are the ones we plan on having students work on.

**Comment by nouiz** [comment]
This don't give any timeline. Some times are tagged CCW for a very long
time and we still didn't give them. Mostly, this mean it is better to ask
an update before starting them. If you are interrested, don't skip them if
they are tagged CCW, just ask.

**Comment by khaotik** [comment]
Thanks for the response. I have local project at hand that really could use this feature. If this feature is not going to be added in anytime soon, I do wanna add my PR.

**Comment by lamblin** [comment]
I would say this is fixed by #5255.
