### ISSUE TITLE
cuDNN 5.1 support with old GPU backend?

### ISSUE THREAD

**Issue by carlthome** [Theano/Theano#5230]
Using the old GPU backend (due to https://github.com/fchollet/keras/issues/4305, https://github.com/Theano/Theano/issues/5123) still but it doesn't seem to work with cuDNN 5.1. Is this on purpose? Has cuDNN support been dropped?

**Comment by nouiz** [comment]
It work here. This is what we use. What if your error?

**Comment by carlthome** [comment]
My bad. Had nvcc calling an old gcc on my system. Solved!
