### ISSUE TITLE
Is cuBLAS-XT for a multi-GPU machine supported?

### ISSUE THREAD

**Issue by yukoba** [Theano/Theano#5238]
CUDA has cuBLAS-XT for a multi-GPU machine.
Is is supported in Theano?

**Comment by nouiz** [comment]
We didn't wrap cuBLAS-XT in Theano.

Depending how it work, maybe it would be easy to wrap the multi-GPU inside
one computer. I have no idea on how much work it would be for the
multi-node version as I didn't look at the interface.

**Comment by yukoba** [comment]
I tried the test. This is the code https://github.com/yukoba/Theano/commit/d5b3d379a3a434a3db071b84edf8fa9c6f585896
It was just replacing ```cublasSgemm``` to ```cublasXtSgemm```.

I ran on Amazon EC2. What I found is,

1. ```cublasXtSgemm``` is slower on the small matrices.
2. I used g2.8xlarge machine, which has 4 GPUs, but it does not get very fast.
3. I heard that g2.8xlarge GPU communication is slow, and the new p2.8xlarge and p2.16xlarge will be faster. But my account need the permission from Amazon to use p2.8xlarge, I requested, but there is no response yet.

**Comment by yukoba** [comment]
I get the permission to use Amazon EC2 p2.8xlarge.

The result for a (16384, 16384) matrix.
- matrix plus: 0.6958642006 sec
- 1 GPU dot: 5.945456982 sec
- 8 GPUs dot: 5.345315456 sec

The difference is so small, and I give up using cuBLAS-XT.

**Comment by nouiz** [comment]
I don't have time to investigate, but I would be very surprised that just
changing the function call would give speed up. We need to tell cuBLAS-XT
information about which GPU to use. This is probably the problem you have,
it use only 1 GPU right now.

**Comment by yukoba** [comment]
> We need to tell cuBLAS-XT information about which GPU to use.

Yes that's right.
So I called `cudaGetDeviceCount()` and passed the number to `cublasXtDeviceSelect()`.
https://github.com/yukoba/Theano/commit/d5b3d379a3a434a3db071b84edf8fa9c6f585896#diff-0ba12adece268f304a1bc28b64410c1bR3782

I checked that 8 GPUs are working by nvidia-smi, and used CUDA_VISIBLE_DEVICES to see the effect.

According to this paper https://arxiv.org/abs/1510.05041
there are some machines which cuBLAS-XT scales matrix multiplications.
I expected that on Amazon EC2 p2.8xlarge, but I could not do that.
I searched about this on Google, but I could not find any information.

![1](https://cloud.githubusercontent.com/assets/194666/20534759/bc81c4ac-b125-11e6-9ab3-7b75cb127ff0.png)

**Comment by nouiz** [comment]
ok. thanks for confirming that you tried that.

In case someone else want to continue, maybe enabling peer2peer gpu
communication would help or event bigger matrices.

**Comment by yukoba** [comment]
> enabling peer2peer gpu

According to this page, Amazon EC2 P2 instance supports GPUDirect.
https://aws.amazon.com/ec2/instance-types/p2/?nc1=h_ls

And according to this page, CUDA Toolkit v4.0 and R270 driver supports GPUDirect.
https://developer.nvidia.com/gpudirect

I used CUDA 8.0 and Ubuntu 16.04 NVIDIA 367.57 device driver.

I believe cuBLAS-xt uses GPUDirect automatically, but do I have to do some configuration?

**Comment by nouiz** [comment]
I don't know. I think we need to enable manually peer2peer, otherwise it
fall back to slower communication by the host. At least, this is what
happen for gpu to gpu transfer in the new back-end.

I don't know if cublas-xt does it automatically or if it would benefit from
this or now.
