### ISSUE TITLE
Theano, windows 10, using GPU

### ISSUE THREAD

**Issue by nebojsa992** [Theano/Theano#5258]
Cant make Theano work on GPU. Warning:
ERROR (theano.sandbox.gpuarray): pygpu was configured but could not be imported
NoneType

Trying to solve this problem for two days now. libgpuarray instructions arent helpful either. Any way for me to just download necessary files and add them to PATH?

PS: I tried both 0.8 and 0.9 Theano versions.

**Comment by nouiz** [comment]
You need to install libgpuarray:

http://deeplearning.net/software/libgpuarray/

**Comment by nouiz** [comment]
Also, for user questions, ask on theano-user mailing list. We keep issue for enhancements, feature requests and bug.
