### ISSUE TITLE
Theano config don't see BLAS

### ISSUE THREAD

**Issue by vshebunyaev** [Theano/Theano#5259]
I have Windows7,install theano through Anaconda
My config
[global]
floatX = float32
device = cpu
exception_verbosity=high
blas.ldflags=-LC:\\openblas -lopenblas

Put libopenblas.dll to c:\openblas\libopenblas.dll

Python see my config file ,because previously make warning for incorrect parameter for exception_verbosity

but didn't see BLAS
and for model.fit(X_train,Y_train
get error

> AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

**Comment by nouiz** [comment]
You have an error the blas.ldflags should be writen as
```
[blas]
ldflags=-LC:\openblas -lopenblas
```
