### ISSUE TITLE
Grad illegally in 0.9.0-dev4

### ISSUE THREAD

**Issue by TommeyChang** [Theano/Theano#5274]
Dear Sir,
I implemented a CNN+LSTM network with keras. When I run this program, an error occurred as below. 
The version of keras and theano are 1.1.1 and 0.9.0-dev4 respectively. However, this program can run in another computer with the theano-0.8.2. Then, I replaced the 0.9.0-dev4 with 0.8.2, this program can run properly.

File "image_caption.py", line 327, in
model.fit([images, partial_captions], next_words,validation_data=([images_val, partial_captions_val],next_words_val), batch_size=12, nb_epoch=100)
File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 642, in fit
sample_weight=sample_weight)
File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1107, in fit
self._make_train_function()
File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 720, in _make_train_function
self.total_loss)
File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 200, in get_updates
grads = self.get_gradients(loss, params)
File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 62, in get_gradients
grads = K.gradients(loss, params)
File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 825, in gradients
return T.grad(loss, variables)
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 553, in grad
grad_dict, wrt, cost_name)
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1317, in _populate_grad_dict
rval = [access_grad_cache(elem) for elem in wrt]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 965, in access_term_cache
output_grads = [access_grad_cache(var) for var in node.outputs]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1272, in access_grad_cache
term = access_term_cache(node)[idx]
File "/usr/local/lib/python2.7/dist-packages/theano/gradient.py", line 1189, in access_term_cache
i, term.type.dtype))
TypeError: Subtensor{:int64:}.grad illegally returned an integer-valued variable. (Input index 0, dtype bool)

**Comment by Sentient07** [comment]
Could you please share the code that caused this crash?

**Comment by TommeyChang** [comment]
[image_caption.zip](https://github.com/Theano/Theano/files/608851/image_caption.zip)

**Comment by TommeyChang** [comment]
#encoding=utf-8
from __future__ import absolute_import
import sys
reload(sys)
sys.setdefaultencoding('utf-8')


from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten,Masking
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.layers import Embedding,GRU,RepeatVector,Merge,TimeDistributed,LSTM
from keras.preprocessing import sequence,text
import matplotlib.image as mpimg
import numpy as np
from keras.models import model_from_json
from keras.utils.visualize_util import plot
from keras import backend as K

def binary_crossentropy1(y_true, y_pred):
    return K.mean(K.binary_crossentropy(y_pred, y_true), axis=-1)*1000

max_caption_len = 20
vocab_size = 5550+1
def VGG_16(weights_path=None):
    model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(3,224,224)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(512, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

    model.add(Flatten())
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(1000, activation='softmax'))

    if weights_path:
        model.load_weights(weights_path)

    #Remove the last two layers to get the 4096D activations
    # model.layers.pop()
    # model.layers.pop()

    return model

print "VGG loading"
image_model = VGG_16('vgg16_weights.h5')
image_model.trainable = False
print "VGG loaded"

print "Text model loading"
language_model = Sequential()
language_model.add(Embedding(vocab_size, 512, input_length=max_caption_len,mask_zero=True))
print "Text model loaded"
# let's repeat the image vector to turn it into a sequence.
print "Repeat model loading"
image_model.add(RepeatVector(max_caption_len))
print "Repeat model loaded"
# the output of both models will be tensors of shape (samples, max_caption_len, 128).
# let's concatenate these 2 vector sequences.
print "Merging"
model = Sequential()
model.add(Merge([image_model, language_model], mode='concat', concat_axis=-1))
# let's encode this vector sequence into a single vector

#masking
model.add(Masking(mask_value=0.))

model.add(LSTM(512, return_sequences=True))
# which will be used to compute a probability
# distribution over what the next word in the caption should be!
model.add(TimeDistributed(Dense(vocab_size)))
model.add(Activation('softmax'))

model.compile(loss=binary_crossentropy1, optimizer='rmsprop')
print "Merged"
plot(model, to_file='model.png',show_shapes=True)
print "Data preprocessig"

#give number to every word
# f_text_all = open("caption_chinese1.txt", "r")
f_text_all = open("flickr8kzhc.caption_wordcount.txt", "r")
Texts_all=[]
while True:
    line = f_text_all.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        string=line.split(":")
        Texts_all.append(string[0])
    else:
        break
f_text_all.close()

# tokenize = text.Tokenizer(nb_words=1574,lower=True, split=" ")
# tokenize.fit_on_texts(Texts_all)
# word_index=tokenize.word_index

# print Texts_all

words = [ txt.split() for txt in Texts_all]
unique = []
#padding=post =>&&
unique.extend("&")
# print len(Texts_all)
for word in words:
    # print word
    unique.extend(word)
# print len(unique)
unique = list(set(unique))
z=unique.index("&")
unique[z]=unique[0]
unique[0]="&"
word_index = {}
index_word = {}

# print len(unique)
f1=open("word_index.txt","w")

for i,word in enumerate(unique):
    word_index[word] = i
    index_word[i] = word
    f1.write(index_word[i]+":"+str(i)+"\n")

# image
f_image = open("flickr8ktrain_id.txt", "r")
Images=[]
i=0
while i<20000:
    i=i+1
    line = f_image.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        line="../Flicker8k_Dataset/"+line
        Images.append(line)
    else:
        break
f_image.close()

images = []
for image in Images:
    img = mpimg.imread(image)
    img.resize((3,224,224))
    images.append(img)
images = np.asarray(images)

# text
f_text = open("flickr8ktrain_caption_fenci_input.txt", "r")
Texts=[]
i=0
while i<20000:
    i=i+1
    line = f_text.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        Texts.append(line)
    else:
        break
f_text.close()

partial_captions = []
for text in Texts:
    one=[]
    text_split = text.split()
    for txt in text_split:
        if txt in Texts_all:
            one.append(word_index[txt])
    # one = [word_index[txt] for txt in text.split()]
    partial_captions.append(one)

partial_captions = sequence.pad_sequences(partial_captions, maxlen=max_caption_len,padding='post')
f_text_out = open("flickr8ktrain_caption_fenci_output.txt", "r")
Texts_out=[]
i=0
while i<20000:
    i=i+1
    line = f_text_out.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        Texts_out.append(line)
    else:
        break
f_text_out.close()

# next_words = []
# for text in Texts_out:
#     one=np.zeros(vocab_size)
#     for txt in text.split():
#         one[0,word_index[txt]]
#     next_words.append(one)
#
# next_words = sequence.pad_sequences(next_words, maxlen=max_caption_len,padding='post')
# print len(images)

# for i in range(0,len(images),100):
#     print i
#     next_words_val = np.zeros((i, max_caption_len, vocab_size))

next_words = np.zeros((len(images),max_caption_len,vocab_size))


for k,text in enumerate(Texts_out):
    text = text.split()
    i=0
    for txt in text:
        if txt in Texts_all:
            j=word_index[txt]
            next_words[k,i,j]=1
            i=i+1

# val
f_image1 = open("flickr8kval_id.txt", "r")
Images1=[]
i=0
while True:
    line = f_image1.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        line="../Flicker8k_Dataset/"+line
        Images1.append(line)
    else:
        break
f_image1.close()

print len(Images1)

images_val = []
for image in Images1:
    img = mpimg.imread(image)
    img.resize((3,224,224))
    images_val.append(img)
images_val = np.asarray(images_val)

f_text1 = open("flickr8kval_caption_fenci_input.txt", "r")
Texts_val=[]
while True:
    line = f_text1.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        Texts_val.append(line)
    else:
        break
f_text1.close()

partial_captions_val = []
for text in Texts_val:
    one=[]
    text_split = text.split()
    for txt in text_split:
        if txt in Texts_all:
            one.append(word_index[txt])
    # one = [word_index[txt] for txt in text.split()]
    partial_captions_val.append(one)

partial_captions_val = sequence.pad_sequences(partial_captions_val, maxlen=max_caption_len,padding='post')
f_text_out1 = open("flickr8kval_caption_fenci_output.txt", "r")
Texts_out1=[]
while True:
    line = f_text_out1.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        Texts_out1.append(line)
    else:
        break
f_text_out1.close()

print len(images_val)

next_words_val = np.zeros((len(images_val),max_caption_len,vocab_size))
for k,text in enumerate(Texts_out1):
    text = text.split()
    i=0
    for txt in text:
        if txt in Texts_all:
            j=word_index[txt]
            next_words_val[k,i,j]=1
            i=i+1

print len(images)
print len(partial_captions)
print len(images_val)
print len(partial_captions_val)

print "Data preprocessing done"
# plot(model, to_file='model.png',show_shapes=True)
model.fit([images, partial_captions], next_words,validation_data=([images_val, partial_captions_val],next_words_val), batch_size=12, nb_epoch=100)

#save the model
json_string=model.to_json()
open('model_architecture.json_100epoch','w').write(json_string)
model.save_weights('model_weights_100epoch.h5')

# model = model_from_json(open('my_model_architecture.json').read())
# model.load_weights('model2_weights.h5')

f_image = open("flickr8ktest_id.txt", "r")
Images_test=[]
while True:
    line = f_image.readline()
    if line:
        pass    # do something here
        line=line.replace("\n",'')
        Images_test.append("../Flicker8k_Dataset"+line)
    else:
        break
f_image.close()

images_test = []
for image in Images_test:
    img = mpimg.imread(image)
    img.resize((3,224,224))
    images_test.append(img)
images_test = np.asarray(images_test)

# #caption=<S>
Texts_test=[]
for i in range(0,len(images_test)):
    Texts_test.append("<S>")

partial_captions_train_test1 = []
for text in Texts_test:
    one = [word_index[txt] for txt in text.split()]
    # print one
    partial_captions_train_test1.append(one)


f_predict = open("caption_predict.txt", "w")
# # f_predict.write(str(result))
# print result
# print len(result)
# for text in result:
#     i=text.argmax()
#     print i
#     print index_word[i]
#     f_predict.write(index_word[i])
# f_predict.close()
prediction = np.zeros((len(images_test),max_caption_len))

for i in range(0,max_caption_len):
   # print i
    partial_captions_train_test = sequence.pad_sequences(partial_captions_train_test1, maxlen=max_caption_len,
                                                         padding='post')
    print partial_captions_train_test
    result = model.predict([images_test, partial_captions_train_test], batch_size=12, verbose=0)
    partial_captions_train_test2 = []
    t=0
    for j in range(0,len(images_test)):
        print j
        result1=result[j,i,:]
        print result1
        max=result1.argmax()
        # print max
        # print result1[934]
        prediction[j,i]=max
        partial_captions_train_test2.append([max])
    # for text in result:
    #     # print "t="+str(t)
    #     j=text.argmax()
    #     prediction[t,i]=j
    #     t=t+1
    #     partial_captions_train_test2.append([j])
    for k in range(0,len(images_test)):
        partial_captions_train_test1[k]=partial_captions_train_test1[k]+partial_captions_train_test2[k]


# for i in range(0,len(images_test)):
#     for j in range(0,max_caption_len):
#         print prediction[i,j]
#         print " "
#     print "\n"

for i in range(0,len(images_test)):
    sentence=""
    for j in range(0,max_caption_len):
        print prediction[i,j]
        # word = index_word[934]
        word=index_word[int(prediction[i,j])]
        sentence=sentence+word+" "
        print word
    f_predict.write(sentence+"\n")

**Comment by TommeyChang** [comment]
[image_caption.zip](https://github.com/Theano/Theano/files/608856/image_caption.zip)

**Comment by TommeyChang** [comment]
Dear @Sentient07 ,
I think the problem may be caused by the binary_crossentropy objective function, because there is a mean operation in this function. In keras, the input of the mean function is inserted a cast,  while the output is not. 

I noticed that there is a note in the document of theano 0.8.2, which is " Insert manual cast around the mean operator (this involves division by length, which is an int64)". However, the theano 0.8.2 can work properly, which also makes me confused.

**Comment by Sentient07** [comment]
@TommeyChang Sorry, I haven't gotten time to check the issue. I will check it in the evening and let you know

**Comment by TommeyChang** [comment]
Thanks, you can solve it in your pace. I am not very anxious.

**Comment by nouiz** [comment]
I get this error when I try to run the script:

    IOError: Unable to open file (Unable to open file: name = 'vgg16_weights.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

How can I get this file or generate a dummy such file?

**Comment by TommeyChang** [comment]
Sir @nouiz,
I think the file from 'https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_th_dim_ordering_th_kernels.h5' is proper. Although, my fellow downloaded it form another website which she has forgotten. 
But, I think you can annotate the code to load the weights. And the program will go to the line which triggers the error.

**Comment by nouiz** [comment]
A new PR gh-5355 should fix this.

**Comment by notoraptor** [comment]
Hello @TommeyChang , I have made a PR to Theano that fixes the "Grad illegally" error: https://github.com/Theano/Theano/pull/5355

Could you test it to check if all is right ?
