### ISSUE TITLE
d3v.d3viz throws an assert on a valid graph

### ISSUE THREAD

**Issue by Ignotus** [Theano/Theano#5291]
Hello,

Below there is a code to reproduce an issue:

```python
import theano as th
import theano.tensor as T
import theano.d3viz as d3v

v = T.fmatrix()
op = th.OpFromGraph([v], [v])
func = th.function([v], [op(v)])
from theano.printing import pydotprint
pydotprint(func, 'out.png') # produces a correct 'out.png'
from IPython.display import Image
Image('out.png')

d3v.d3viz(func, 'out.html') # An assert appears theano/d3viz/formatting.py:263
```

If I try to comment an assert then a wrong visualization will be generated after zooming out the OpFromGraph block (there will be two fmatrix blocks which are not connected to each other http://imgur.com/Tl8gKbY ).

**Comment by nouiz** [comment]
thanks for the report. Here is the fix:

https://github.com/Theano/Theano/pull/5297
