### ISSUE TITLE
Import Theano Error

### ISSUE THREAD

**Issue by anandcu3work** [Theano/Theano#5310]
I have Anaconda Python 2.7.12 installed with numpy 1.11.2 and scipy 0.18.1 versions. I have installed Theano 0.8.2 through conda install.  I have added these lines in the .theanorc.txt file:

`[global]
floatX = float32
device = gpu0

[nvcc]
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin`

I have the CUDA Path set in the environment variables. I have also added CUDNN v4.0 to the cuda installation.

However when I do a simple

`import theano`

in the python interpreter it gives me the following error and falls back to cpu.

`DEBUG: nvcc STDOUT nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mod.cu
   Creating library C:/Users/<USER_NAME>/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.12-64/cuda_ndarray/cuda_ndarray.lib and object C:/Users/<USER_NAME>/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.12-64/cuda_ndarray/cuda_ndarray.exp

ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: DLL load failed: The specified module could not be found.
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu0 is not available  (error: cuda unavailable)`

The error does not specify which DLL is missing either. I am not sure if this is a bug or a theano installation/config issue or a CUDA installation/config issue.

Thanks

**Comment by lamblin** [comment]
For support, please use `theano-users` or StackOverflow rather than GitHub tickets.
Please provide there the following additional information:
- the version of CUDA you are using.
- are you able to compile with nvcc the examples provided in the CUDA toolkit?
- does it work if you install the latest development version of Theano from GitHub, via `pip install git+...`?

**Comment by anandcu3work** [comment]
Hi lamblin,

I reinstalled CUDA and it worked fine. 

It's weird because the test sample were running correctly. I tried deviceQuery and BandwidthTest. To answer your other queries, I am using CUDA v8.0 and updating Theano to the latest version did not help and gave the same error. All OK now. Cheers. Thank you for your time.

**Comment by lamblin** [comment]
Glad to hear that it is working now.
Cheers.
