### ISSUE TITLE
Python 2 incompatible string type check

### ISSUE THREAD

**Issue by meowklaski** [Theano/Theano#5312]
Trivial Python 2 incompatibility issue in theano version: 

`0.9.0dev4.dev-cea45e8bd95971d2a4d9a790d80b3824ca573d041`

The following line of code located in [theano/gof/utils.py
](https://github.com/Theano/Theano/blob/9cb9ff4db5bf4720c47613348c8a143c3aeaa772/theano/gof/utils.py#L164) is the problem:

```python
if not all(isinstance(p, str) for p in props)
```
should be:

```python
if not all(isinstance(p, string_types) for p in props)
```

**Comment by nouiz** [comment]
thanks for the report, here is the PR with this fix:

https://github.com/Theano/Theano/pull/5313
