### ISSUE TITLE
Optimization failure due to: local_reshape_dimshuffle

### ISSUE THREAD

**Issue by ysjakking** [Theano/Theano#5316]
**I encountered this error with the develop version of theano on Ubuntu 14：**

**Theano version** 0.9.0dev4.dev-9cb9ff4db5bf4720c47613348c8a143c3aeaa772
NumPy version 1.11.2
NumPy relaxed strides checking option: False
NumPy is installed in /usr/local/lib/python2.7/dist-packages/numpy
Python version 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
nose version 1.3.7
/home/Theano-master/Theano/theano/misc/pycuda_init.py:35: UserWarning: PyCUDA import failed in theano.misc.pycuda_init
  warnings.warn("PyCUDA import failed in theano.misc.pycuda_init")

**ERROR information:**
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{1}(InplaceDimShuffle{0,x}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/Theano-master/Theano/theano/gof/opt.py", line 1964, in process_node
    replacements = lopt.transform(node)
  File "/home/Theano-master/Theano/theano/tensor/opt_uncanonicalize.py", line 136, in local_reshape_dimshuffle
    return [T.reshape(input_.owner.inputs[0], node.inputs[1])]
  File "/home/Theano-master/Theano/theano/tensor/basic.py", line 4714, in reshape
    "argument to 'reshape' to avoid this problem." % newshape)
ValueError: The length of the provided shape (<TensorType(int64, vector)>) cannot be automatically determined, so Theano is not able to know what the number of dimensions of the reshaped variable will be. You can provide the 'ndim' keyword argument to 'reshape' to avoid this problem.

**My script for .theanorc:**
[global]
floatX = float32
device = gpu1
exception_verbosity=high
compute_test_value=warn
optimizer= fast_run
allow_gc=False
[nvcc]
fastmath = False
[scan]
allow_gc=False
[lib]
cnmem=0.3
[blas]
ldflags= -lblas -lgfortan

**Information on blas:**
>>> import numpy
>>> numpy.distutils.__config__.show()
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_mkl_info:
  NOT AVAILABLE

**Comment by ysjakking** [comment]
I have find the code that causes this error:
e = T.dot(A,B)    #A is a 3D  tensor with size=(a,b,c),  and B is a vector with size=c

After I replace the code  with:
 e = A* B.dimshuffle(['x','x',0])
 e = e.sum(axis=2)
The error can be avoided. 
 I just wonder why I can not make a dot between a 3D tensor and a vector directly?

**Comment by ysjakking** [comment]
Ok！Thanks for reply

**Comment by nouiz** [comment]
We merged the PR. If you contiue to have problems, tell us.

**Comment by ysjakking** [comment]
Thanks very much！I will try later and let you know.
