### ISSUE TITLE
stdint.h link to header for install is broken

### ISSUE THREAD

**Issue by ThirstyGeo** [Theano/Theano#5324]
This link no longer works (from the Windows install how-to): http://msinttypes.googlecode.com/svn/trunk/stdint.h

[From http://deeplearning.net/software/theano/install_windows.html#install-windows]

**Comment by nouiz** [comment]
It should not be needed anymore with the new version of libgpuarray. We
should update the doc about this.

**Comment by nouiz** [comment]
Sorry, I mixed stuff. If you use the new gpu back-end, this should not be needed anymore. Do you want to try it? We are close to dropping the old back-end and I'm pretty sure the new back-end should fit your need and maybe easier to install:

http://deeplearning.net/software/theano/tutorial/using_gpu.html#gpuarray

@abergeron did you had the time to make the distributable package on windows for libgpuarray or not?

**Comment by lamblin** [comment]
The instructions have been updated in the dev branch (the link on http://deeplearning.net/software/theano_versions/dev/install_windows.html points to https://sourceforge.net/p/mspgcc/msp430-libc/ci/master/tree/include/stdint.h), but not back-ported to the doc for 0.8 yet.

**Comment by nouiz** [comment]
I back-ported the doc fix. The doc web page should be updated in the next hour.
