### ISSUE TITLE
Performance issue with GPUAMultinomialWOReplacementFromUniform

### ISSUE THREAD

**Issue by senarvi** [Theano/Theano#5338]
I requested size argument for `multinomial()` in issue #5292 in order to efficiently get a large number of samples. I also said that `multinomial_wo_replacement()` is faster, so I'm using it currently, but there seems to be another performance issue in the new GpuArray backend.

When I'm using the new backend, processing one mini-batch takes more than 900 ms. I did some profiling and noticed that `theano.gpuarray.multinomial.GPUAMultinomialWOReplacementFromUniform` is consuming 97 % of the processing time.

Using the old backend, one mini-batch takes 90 ms. This is the top four time consumers:
```
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  49.5%    49.5%       0.218s       2.91e-03s     C       75      75   theano.sandbox.cuda.basic_ops.GpuElemwise
  27.9%    77.4%       0.123s       6.14e-02s     Py       2       2   theano.scan_module.scan_op.Scan
  10.2%    87.5%       0.045s       2.36e-03s     C       19      19   theano.sandbox.cuda.blas.GpuDot22
   4.3%    91.8%       0.019s       1.88e-02s     C        1       1   theano.sandbox.multinomial.MultinomialWOReplacementFromUniform
```
In this case the sampling is apparently not done on GPU, but the operation `MultinomialWOReplacementFromUniform{int64}(HostFromGpu.0, HostFromGpu.0, ScalarFromTensor.0)` is using variables that are transferred to host memory from GPU. Still it's a lot faster. Or is there a reason why this operation cannot be implemented efficiently on GPU?

**Comment by lamblin** [comment]
There is no reason I know that would make it slow on GPU.
Do you have an example script we could use to try and reproduce the issue?
Also, are you excluding the first call from the timing?

**Comment by senarvi** [comment]
During profiling I have `profiling.ignore_first_call=True`.

That's a huge network but I'll try to make a smaller example.

**Comment by senarvi** [comment]
I can reproduce this performance issue by just looping over `multinomial_wo_replacement()` calls. This is the program:

```python
from time import time
import numpy
import theano
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
numpy.random.seed(23)
probs = numpy.random.randn(1, 100000)
probs /= probs.sum()
probs = theano.shared(probs.astype(theano.config.floatX), 'probs')
rng = RandomStreams(23)
sample = rng.multinomial_wo_replacement(n=100, pvals=probs)
f = theano.function([], [sample.min(), sample.max()])
start_time = time()
for _ in range(10):
    sample_min, sample_max = f()
    print('min:', sample_min, 'max:', sample_max)
duration = time() - start_time
print('duration:', duration)
```

This is the result from running this on CPU (`device=cpu,floatX=float32`):

```
min: 307 max: 83698
min: 8 max: 83265
min: 303 max: 82661
min: 303 max: 83696
min: 304 max: 83695
min: 8 max: 83665
min: 307 max: 83697
min: 7 max: 83698
min: 303 max: 83672
min: 8 max: 83265
duration: 0.17172002792358398
```

Running it on GPU using the old backend (`device=gpu,floatX=float32`) gives exactly the same numbers, except duration is 0.19 seconds. This is the result of running it on GPU using the new backend (`device=cuda0,floatX=float32`):


```
Mapped name None to device cuda0: Tesla K80
PCI Bus ID: 0000:88:00.0
min: 307 max: 83698
min: 8 max: 83265
min: 303 max: 82661
min: 303 max: 83696
min: 304 max: 83695
min: 8 max: 83665
min: 307 max: 83697
min: 7 max: 83698
min: 303 max: 83672
min: 8 max: 83265
duration: 81.14884948730469
```

**Comment by nouiz** [comment]
In the old back-end, we don't have a GPU implementation for
multinomial_wo_replacement, so it is normal that it run on the CPU.

In the new back-end, it use pvals.shape[0] threads. So in your current
examples, it end up using only 1 threads on the GPU.

I did a PR that help a little, it make it 2x faster in your case and fix a
memory leak. But more speed up are needed:

https://github.com/Theano/Theano/pull/5346


We would need to use multiple threads to find the threashold. It isn't done
now.

**Comment by senarvi** [comment]
This seems to be still a problem. When I'm using the latest Theano and GpuArray, random sampling is so slow that NCE training is 10x slower. It's reasonably fast when I use older Theano and the old backend, which runs this op on CPU.

As far as I can see, there's no way to implement noise-contrastive estimation or other sampling-based costs in such a way that they would run reasonably fast with large-dimensional outputs. I think that would be quite important e.g. in language modeling.

Is it possible to work around this by forcing this particular operation to CPU?

**Comment by nouiz** [comment]
You can disable the sampling on the GPU with this Theano flag:

optimizer_excluding=local_gpua_multinomial_wor

To have the the conversion of the distribution from uniform to multinomial without replacement. To have the uniform also generated on the CPU, you would need this PR: https://github.com/nouiz/Theano/tree/mrg_target

and call multinomial(..., target='cpu') to force it on the CPU when you use device=cuda.
Keep us updated if you try it. We try to make a release shortly, so having it tester in the master would be great.

**Comment by nouiz** [comment]
I added the branch in a PR: https://github.com/Theano/Theano/pull/6274

**Comment by nouiz** [comment]
@senarvi We merged a PR that allow you to force the random on CPU or GPU: https://github.com/Theano/Theano/pull/6355

Mostly, just add target='cpu' when drawing random number to force the state to be on the CPU.

**Comment by senarvi** [comment]
Thanks, I'll test this soon. I hadn't noticed your reply.

**Comment by nouiz** [comment]
I think you will need the follow up in this PR:

https://github.com/Theano/Theano/pull/6405

Mostly, the current master will keep the state on the CPU, but that PR will keep the generation + the state on the CPU while using target='cpu'

**Comment by senarvi** [comment]
I'm having difficulties testing this. I updated Theano and pygpu to latest commits and I'm not able to use pygpu anymore. The problem seems to be that pygpu is unable to parse version information and version will be `0+unknown`:
https://github.com/Theano/libgpuarray/blob/8f21ba2a7a9f510f41081331631b6c2c010cee42/pygpu/_version.py#L477

Then Theano won't use the GPU because it fails to parse the pygpu version number here:
https://github.com/Theano/Theano/blob/9b3f6351d41d9f5e01b198e3de7538d7f032c409/theano/gpuarray/__init__.py#L48

I tried a bit older commits but so far no luck. I'll try to come up with a workaround later.

**Comment by senarvi** [comment]
I set the version variables manually for testing this. (It also fails to parse `0.7.0.dev0`.)

I can see a small improvement from setting `optimizer_excluding=local_gpua_multinomial_wor`. I don't see any effect from adding `target='cpu'` argument. I'm using `choice()`, not `multinomial()`, and I haven't applied the pull request. I'll need to figure out how to do that!

**Comment by nouiz** [comment]
We merged changes to the master about that. It should not be needed anymore to set the Theano flag optimizer_excluding. So just using target='cpu' when calling choice should give the new back-end the same speed as the old back-end.

Can you update Theano to the master of Theano. For the version, we release 0.7.2 and this should be fixed. Can you update it at the same time?

**Comment by senarvi** [comment]
I had some time to test this again with the latest versions. I'm not sure anymore what is causing this improvement, but my training speed is almost doubled, so I'm closing this issue.
