### ISSUE TITLE
theano.tensor.argsort() give incorrect result of sorting

### ISSUE THREAD

**Issue by Jonbean** [Theano/Theano#5339]
Here's my test script.

```
import theano
import theano.tensor as T
import numpy as np

a = T.matrix()

b = T.argsort(a, axis = 1, kind='mergesort')

test = theano.function([a], [a,b])

a_t = np.random.randint(20, size=(5,5))
arg_list = test(a_t)

print a_t
print arg_list

```

And here's the result:

```
[[ 7  2 15 13  9]
 [ 8 10 10 10 14]
 [17  5  1  4  8]
 [ 5  7  5 12 15]
 [ 6  0 10  7  9]]
[array([[  7.,   2.,  15.,  13.,   9.],
        [  8.,  10.,  10.,  10.,  14.],
        [ 17.,   5.,   1.,   4.,   8.],
        [  5.,   7.,   5.,  12.,  15.],
        [  6.,   0.,  10.,   7.,   9.]]), 
array([[1, 0, 4, 3, 2],
       [0, 1, 2, 3, 4],
       [2, 3, 1, 4, 0],
       [0, 2, 1, 3, 4],
       [1, 0, 3, 4, 2]])]
```
The third row is not correctly sorted. the right order is [4,2,0,1,3]

I'm expecting the theano.tensor.argsort() function returns correct sorted index of each row of a matrix.

**Comment by jiangnanHugo** [comment]
import theano
import theano.tensor as T
import numpy as np

a = T.imatrix()

b = T.argsort(a,axis=1)

test = theano.function([a], b)

a_t = np.random.randint(20, size=(5,5))
arg_list = test(a_t)

print a_t
print arg_list
print np.argsort(a_t,axis=1)
the result of `T.argsort` is euqal to `np.argsort`. and the results is correct.
