### ISSUE TITLE
Keras Using Theano Backend MaxPooling2d Dimension Limitation Using GPU Speed Up

### ISSUE THREAD

**Issue by YuqiCui** [Theano/Theano#5340]
Hi guys, I'm new to Theano and may ask a few stupid questions, sorry about that.
I'm using keras with Theano backend, when using the layer MaxPooling2d, I got a dimension limitation. It says the last dimension can't be larger then 512 dimensions if I want to use GPU to speed up my program. When using cpu, I got no problem in my program.
So do you have any idea about how to solve this problem if I want to use GPU?
I use CNMeM=0.8 and didn't install cuDNN yet.

**Comment by gvtulder** [comment]
Installing cuDNN would probably help and is a good idea anyway. You could also switch to the [GpuArray backend](http://www.deeplearning.net/software/theano/tutorial/using_gpu.html#gpuarray) (`device=cuda`) , which has a pooling implementation that should support larger dimensions as well.

**Comment by nouiz** [comment]
Good work around provided, so closing.
