### ISSUE TITLE
RuntimeError: could not set tensor4d descriptor: CUDNN_STATUS_BAD_PARAMshapes=0

### ISSUE THREAD

**Issue by rahulroxx** [Theano/Theano#5341]
Theano Version: Theano-0.9.0.dev4
I'm new to theano I was following the reporsitory pydeeplearn and I got an error 

```
RuntimeError: could not set tensor4d descriptor: CUDNN_STATUS_BAD_PARAMshapes=0
1 1 1 strides=1 1 1 1
Apply node that caused the error: GpuDnnSoftmax{tensor_format='bc01', mode='chan
nel', algo='log'}(GpuContiguous.0)
Toposort index: 66
Inputs types: [CudaNdarrayType(float32, (False, False, True, True))]
Inputs shapes: [(0, 1, 1, 1)]
Inputs strides: [(1, 0, 0, 0)]
Inputs values: [CudaNdarray([])]
Outputs clients: [[GpuDimShuffle{0,1}(GpuDnnSoftmax{tensor_format='bc01', mode='
channel', algo='log'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-tr
ace of when this node was created. This can be done with by setting the Theano f
lag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be
 disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storag
e map footprint of this apply node.
```

Please Help thanks :)

**Comment by lamblin** [comment]
You have a batch of 0 elements, and cuDNN does not support empty tensors.
This is a corner case that we should fix a some point (if it is not already done in the new back-end), but it probably indicates an issue on your side.

**Comment by rahulroxx** [comment]
Thanks a lot for a prompt reply, Ok I will check on my end. 
Can you please suggest what possible solution, should I tweak 2d tensor for types? 
Thanks in advance. 

```
TypeError: Cannot convert Type TensorType(float32, matrix) (of Variable HostFrom
Gpu.0) into Type TensorType(float64, matrix). You can try to manually convert Ho
stFromGpu.0 into a TensorType(float64, matrix).
```

**Comment by nouiz** [comment]
There is an upcast to float64 in your code. Use theano flag:

warn_float64=pdb to see when it is created.

**Comment by nouiz** [comment]
@gvtulder make a PR that I just merged that will fix the first error of softmax with 0 size. Now it should work and return an output with 0 element.
