### ISSUE TITLE
how to normalize input for each patch during convolution

### ISSUE THREAD

**Issue by HC-2016** [Theano/Theano#5344]
I wanna to normalize (substract mean, divide standard deviation) input in each patch during convolution.
This means a affine transformation before convolution for each patch .
How can I achieve it ? Any idea?

**Comment by nouiz** [comment]
For user support, use Theano mailing list.

In Theano, you can just do elemwise operation on the input matrix:

input = ...
input_normalized = (input - input.mean())/input.std()
