### ISSUE TITLE
Apply node that caused the error: HostFromGpu(GpuElemwise{add,no_inplace}.0)

### ISSUE THREAD

**Issue by manhon** [Theano/Theano#5366]
i dont know if this is a bug related to Theano:

I thought it may be a bug on CUDA, but I can use this server to finetune model with py-FasterRCNN with latest caffe (built from source)

The config is Ubuntu 16.04, Cuda 8.0, Theano-dev, Keras-dev.

Successfully installed Theano-0.9.0.dev4
```
raymond@ubuntu1:~/keras/examples$ THEANO_FLAGS='optimizer=fast_compile'  python cifar10_cnn.py
Using Theano backend.
--------------------------------------------------------------------------
[[5570,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: ubuntu1

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
Using gpu device 0: Tesla K80 (CNMeM is enabled with initial size: 75.0% of memory, cuDNN 5105)
X_train shape: (50000, 3, 32, 32)
50000 train samples
10000 test samples
Using real-time data augmentation.
Epoch 1/200
50000/50000 [==============================] - 29s - loss: 1.6020 - acc: 0.4166 - val_loss: 1.4979 - val_acc: 0.4908
Epoch 2/200
50000/50000 [==============================] - 29s - loss: 1.2496 - acc: 0.5561 - val_loss: 1.1277 - val_acc: 0.6129
Epoch 3/200
50000/50000 [==============================] - 46s - loss: 1.1565 - acc: 0.5971 - val_loss: 0.9284 - val_acc: 0.6760
Epoch 4/200
 6528/50000 [==>...........................] - ETA: 97s - loss: 1.1131 - acc: 0.6141Traceback (most recent call last):
  File "cifar10_cnn.py", line 103, in <module>
    validation_data=(X_test, Y_test))
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/models.py", line 924, in fit_generator
    pickle_safe=pickle_safe)
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1508, in fit_generator
    class_weight=class_weight)
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1267, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 919, in __call__
    return self.function(*inputs)
  File "/home/raymond/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/raymond/.local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/raymond/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
RuntimeError: error (unknown error)copying data to host
Apply node that caused the error: HostFromGpu(GpuElemwise{add,no_inplace}.0)
Toposort index: 349
Inputs types: [CudaNdarrayType(float32, 4D)]
Inputs shapes: [(32, 64, 6, 6)]
Inputs strides: [(2304, 36, 6, 1)]
Inputs values: ['not shown']
Outputs clients: [[Elemwise{lt,no_inplace}(HostFromGpu.0, TensorConstant{(1, 1, 1, 1) of 0.75})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by manhon** [comment]
another run with another code:

...
...
Train on 2518 samples, validate on 1259 samples
Epoch 1/5000
46s - loss: 8.7327 - val_loss: 8.9232
Epoch 2/5000
Traceback (most recent call last):
  File "example3.py", line 424, in <module>
    info_string, models = run_cross_validation_create_models(num_folds)
  File "example3.py", line 196, in run_cross_validation_create_models
    callbacks=callbacks)
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/engine/training.py", line 1143, in fit
    initial_epoch=initial_epoch)
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/engine/training.py", line 843, in _fit_loop
    outs = f(ins_batch)
  File "/home/raymond/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 919, in __call__
    return self.function(*inputs)
  File "/home/raymond/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 886, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/raymond/.local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/raymond/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 873, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Cuda error 'unknown error' while copying %lli data element to device memory. str ptr=%p. dst ptr=%p
Apply node that caused the error: GpuFromHost(dense_1_sample_weights)
Toposort index: 197
Inputs types: [TensorType(float32, vector)]
Inputs shapes: [(16,)]
Inputs strides: [(4,)]
Inputs values: ['not shown']
Outputs clients: [[GpuDimShuffle{0,x}(GpuFromHost.0), GpuElemwise{Composite{Cast{float32}(NEQ(i0, i1))},no_inplace}(GpuFromHost.0, CudaNdarrayConstant{error while transferring the value: error (unknown error)copying data to host}), GpuElemwise{mul,no_inplace}(GpuCAReduce{add}{0,1}.0, GpuFromHost.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by manhon** [comment]
another run with another code:

Epoch 2/200
34048/50000 [===================>..........] - ETA: 21s - loss: 1.2745 - acc: 0.5471[ubuntu1:03387] *** Process received signal ***
[ubuntu1:03387] Signal: Segmentation fault (11)
[ubuntu1:03387] Signal code: Address not mapped (1)
[ubuntu1:03387] Failing at address: (nil)
[ubuntu1:03387] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x113d0)[0x7fb512bdf3d0]
[ubuntu1:03387] [ 1] /home/raymond/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/cuda_ndarray/cuda_ndarray.so(+0x118e3)[0x7fb4d2b488e3]
[ubuntu1:03387] [ 2] python(PyObject_Repr+0x2d)[0x51051d]
[ubuntu1:03387] [ 3] python[0x5434ce]
[ubuntu1:03387] [ 4] python(_PyObject_Str+0x69)[0x513769]
[ubuntu1:03387] [ 5] python(PyString_Format+0x819)[0x50e749]
[ubuntu1:03387] [ 6] python(PyEval_EvalFrameEx+0x211b)[0x4c611b]
[ubuntu1:03387] [ 7] python(PyEval_EvalCodeEx+0x255)[0x4c2765]
[ubuntu1:03387] [ 8] python(PyEval_EvalFrameEx+0x6099)[0x4ca099]
[ubuntu1:03387] [ 9] python(PyEval_EvalCodeEx+0x255)[0x4c2765]
[ubuntu1:03387] [10] python[0x4de6fe]
[ubuntu1:03387] [11] python(PyObject_Call+0x43)[0x4b0cb3]
[ubuntu1:03387] [12] python[0x4f492e]
[ubuntu1:03387] [13] python(PyObject_Call+0x43)[0x4b0cb3]
[ubuntu1:03387] [14] python[0x553187]
[ubuntu1:03387] [15] python(PyObject_Call+0x43)[0x4b0cb3]
[ubuntu1:03387] [16] python(PyEval_EvalFrameEx+0x2ad1)[0x4c6ad1]
[ubuntu1:03387] [17] python(PyEval_EvalCodeEx+0x255)[0x4c2765]
[ubuntu1:03387] [18] python[0x4de6fe]
[ubuntu1:03387] [19] python(PyObject_Call+0x43)[0x4b0cb3]
[ubuntu1:03387] [20] python[0x4f492e]
[ubuntu1:03387] [21] python(PyObject_Call+0x43)[0x4b0cb3]
[ubuntu1:03387] [22] python[0x553187]
[ubuntu1:03387] [23] python(PyObject_Call+0x43)[0x4b0cb3]
[ubuntu1:03387] [24] python(PyEval_EvalFrameEx+0x5faf)[0x4c9faf]
[ubuntu1:03387] [25] python(PyEval_EvalCodeEx+0x255)[0x4c2765]
[ubuntu1:03387] [26] python(PyEval_EvalFrameEx+0x6099)[0x4ca099]
[ubuntu1:03387] [27] python(PyEval_EvalCodeEx+0x255)[0x4c2765]
[ubuntu1:03387] [28] python(PyEval_EvalFrameEx+0x6099)[0x4ca099]
[ubuntu1:03387] [29] python(PyEval_EvalCodeEx+0x255)[0x4c2765]
[ubuntu1:03387] *** End of error message ***

**Comment by lamblin** [comment]
Are you using threads in Python?
If so, be careful as Theano is not thread-safe.

**Comment by abergeron** [comment]
Try to run with cuda-memcheck.  This will be much slower but should catch any memory access problem on the GPU.

**Comment by nouiz** [comment]
closing as no news and we are switching to the new gpu back-end.

**Comment by Quxyz** [comment]
I meet the same error, what should I do?
