### ISSUE TITLE
Cannot find cudnn lib

### ISSUE THREAD

**Issue by aviveise** [Theano/Theano#5370]
Hi
For some reason, I'm getting an error 'Could not find cudnn library (looked for v5[.1])'.
The code raising the error is in dnn.py (line 67) for some reason ctypes.util.find_library('cudnn') returns None. the path to the cudnn lib files is located in LD_LIBRARY_PATH

appreciate your help

**Comment by aviveise** [comment]
I've figured out the problem, I had to add "LIBRARY_PATH=/usr/local/cuda/lib64" to the environment variables

**Comment by rmlopes** [comment]
After almost a day lost this was the issue for me as well. 

In my case I could only use the gpu if run as roo, even if it said it could not find cudnn. For the regular users there was a problem with gpuarray, and it always fell back to the cpu backend.

This fixed the message when root, and fixed the gpu for the regular users.

Maybe it should be added to the installation instructions after the LD_LIBRARY_PATH part.

**Comment by nouiz** [comment]
Can you give me a link to the page you would include that? Mostly, this is a problem with your installation of cuda, and I'm not sure on which page I would put such note to help user.

**Comment by lamblin** [comment]
I think `LIBRARY_PATH` is mentioned as well in http://deeplearning.net/software/theano/library/gpuarray/dnn.html.
Are you referring to another page?

**Comment by rmlopes** [comment]
Hi, I was following the Theano docs [here](http://deeplearning.net/software/theano/install_ubuntu.html#bleeding-edge-installation-recommended). It redirects to [gpuarray](http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install-system-library-as-admin) at some point.

I just noticed in the "install as user" section it actually mentions the `LIBRARY_PATH` var. I just thought maybe it could be mentioned as well in the "System library" section.

**Comment by joedercoder** [comment]
for me to solution was to use cudnn 5.1 instead of 6.0
