### ISSUE TITLE
GPU mode error on Windows 10 with visual studio 2013

### ISSUE THREAD

**Issue by masakinakada** [Theano/Theano#5372]
I am getting the following error and cannot run on gpu mode on win 10.
Could anyone please help me to solve this?

Program
Files
c1xx : fatal error C1083: Cannot open source file: 'ô-IC:/Program': No such file or directory
Microsoft
c1xx : fatal error C1083: Cannot open source file: 'Files': No such file or directory
Visual
c1xx : fatal error C1083: Cannot open source file: '(x86)/Microsoft': No such file or directory
Studio
c1xx : fatal error C1083: Cannot open source file: 'Visual': No such file or directory
include"
c1xx : fatal error C1083: Cannot open source file: 'Studio': No such file or directory
Program
c1xx : fatal error C1083: Cannot open source file: '12.0/VC/includeö': No such file or directory
Files
c1xx : fatal error C1083: Cannot open source file: 'ô-IC:\Program': No such file or directory
Microsoft
c1xx : fatal error C1083: Cannot open source file: 'Files': No such file or directory
Include"
c1xx : fatal error C1083: Cannot open source file: '(x86)\Microsoft': No such file or directory
mod.cu
c1xx : fatal error C1083: Cannot open source file: 'SDKs\Windows\v7.1A\Includeö': No such file or directory
c:\users\masak\anaconda2\include\pyconfig.h(238) : fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
mod.cu

['nvcc', '-shared', '-O3', '-LC:\\Users\\masak\\Anaconda2\\libs', '-use_fast_math', '--compiler-bindir', 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-I"C:\\Users\\masak\\Anaconda2\\lib\\site-packages\\theano\\sandbox\\cuda"', '-I"C:\\Users\\masak\\Anaconda2\\lib\\site-packages\\numpy\\core\\include"', '-I"C:\\Users\\masak\\Anaconda2\\include"', '-I"C:\\Users\\masak\\Anaconda2\\lib\\site-packages\\theano\\gof"', '-L"C:\\Users\\masak\\Anaconda2\\libs"', '-L"C:\\Users\\masak\\Anaconda2"', '-o', 'C:\\Users\\masak\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-lcublas', '-lpython27', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -LC:\\Users\\masak\\Anaconda2\\libs -use_fast_math --compiler-bindir C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=c72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -I"C:\\Users\\masak\\Anaconda2\\lib\\site-packages\\theano\\sandbox\\cuda" -I"C:\\Users\\masak\\Anaconda2\\lib\\site-packages\\numpy\\core\\include" -I"C:\\Users\\masak\\Anaconda2\\include" -I"C:\\Users\\masak\\Anaconda2\\lib\\site-packages\\theano\\gof" -L"C:\\Users\\masak\\Anaconda2\\libs" -L"C:\\Users\\masak\\Anaconda2" -o C:\\Users\\masak\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.14393-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.13-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -lcublas -lpython27 -lcudart')
WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)

**Comment by mustgoplay** [comment]
It looks like you are trying to use a path with spaces in .theanorc 

Try using my installation instructions:

https://github.com/Theano/Theano/issues/5348

**Comment by masakinakada** [comment]
@mustgoplay Thank you so much! I would like to try your solution. 
Just one question. Does it also work with python 2.7? 

Thank you so much for your kind help!

**Comment by mustgoplay** [comment]
Haven't tried it but can't see why it wouldn't.

**Comment by masakinakada** [comment]
I still got this error,

 pygpu was configured but could not be imported or is too old (version 0.6
or higher required)
Traceback (most recent call last):

Do you know if I need to install pygpu?
I tried to install but I failed with it on my system.

Thank you very much for your help!

Masaki

**Comment by mustgoplay** [comment]
Not sure about that.  Only have 3.4 and 3.5 working.  Did the gpu work at least?

**Comment by masakinakada** [comment]
@mustgoplay
Unfortunately, it switches back to CPU mode with the error...
Maybe pygpu only comes with 3.~ python... I tried many solutions online,
but so far none of them solved.....

**Comment by mustgoplay** [comment]
Sorry I'm not sure what else to recommend.

**Comment by masakinakada** [comment]
I understand. Thank you.
I am going to give up for now...

**Comment by Vertislav** [comment]
Instead of opening a new issue, maybe I will ask here because my problem seems to be quite similar to these, and I am clueless for now what to do... I am trying to run Theano with GPU (GTX 970M) on Windows 10. I have installed anaconda, with Python 3.5 and Theano in version 0.9.0. My .theanorc looks as follows:

> [global]
> theano_compiledir = cuda
> floatX = float32

And below you can see what I see after typing "import theano" in the IPython console. The last line suggests that GPU is seen but first and before last lines suggest an error. Does anybody know what can I do with this problem? I spent on it one day already and really I have no idea what could be wrong. Thanks in advance for any help!

Greetings,
Bartosz

> c:\programdata\anaconda3\envs\py35\include\pyconfig.h(243) : fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
> ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -I"C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\theano\\sandbox\\cuda" -I"C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\numpy\\core\\include" -I"C:\\ProgramData\\Anaconda3\\envs\\py35\\include" -I"C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\theano\\gof" -L"C:\\ProgramData\\Anaconda3\\envs\\py35\\libs" -L"C:\\ProgramData\\Anaconda3\\envs\\py35" -o C:\\Users\\VerTislav\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.3-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -lcublas -lpython35 -lcudart')
> nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
> mod.cu
> 
> ['nvcc', '-shared', '-O3', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-I"C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\theano\\sandbox\\cuda"', '-I"C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\numpy\\core\\include"', '-I"C:\\ProgramData\\Anaconda3\\envs\\py35\\include"', '-I"C:\\ProgramData\\Anaconda3\\envs\\py35\\lib\\site-packages\\theano\\gof"', '-L"C:\\ProgramData\\Anaconda3\\envs\\py35\\libs"', '-L"C:\\ProgramData\\Anaconda3\\envs\\py35"', '-o', 'C:\\Users\\VerTislav\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.3-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-lcublas', '-lpython35', '-lcudart']
> Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
> b'C:\\Users\\VERTIS~1\\AppData\\Local\\Temp\\try_flags_2dnaosdt.c:4:19: fatal error: cudnn.h: No such file or directory\r\ncompilation terminated.\r\n'
> Mapped name None to device cuda: GeForce GTX 970M (0000:01:00.0)
