### ISSUE TITLE
Indexing with empty list

### ISSUE THREAD

**Issue by 317070** [Theano/Theano#5374]
Unlike numpy, theano cannot index with an empty list. It seems to me that this should be something AdvancedSubtensor should be able to deal with?
```
>>> np.zeros((5,5))[:,[]]
array([], shape=(5, 0), dtype=float64)
```
versus
```
>>> T.fmatrix()[:,[]]
TypeError: index must be integers
```

Note that the following do work fine. It is only empty python lists which pose difficulty.
```
>>> T.fmatrix()[:,np.array([],dtype='int64')]
DimShuffle{1,0}.0
>>> T.fmatrix()[:,[1]]
DimShuffle{1,0}.0
```

**Comment by abergeron** [comment]
This is probably because `numpy.asarray([]) == numpy.array([], dtype='float64')`.

**Comment by nouiz** [comment]
If so, should we make a special case, when the idx list is an empty
constant and cast it to int?

Or detect that case and give a better user error?

I would prefer option 1, as it make us behave more like numpy.

**Comment by affanv14** [comment]
@nouiz I'd like to try implementing option 1.

**Comment by nouiz** [comment]
thanks. We didn't agree on the final implementation, but you can start. The
difference is small between the options. A starting point:

tensor/var.py the method __getitem__ is what is called by [] symbol in
python. This is the entry point.

**Comment by lamblin** [comment]
I think the way to go is, in `__getitem__`, to check if one of the indexing arguments is an empty list before trying to convert it using `as_tensor_variable`, and instead call `as_tensor_variable(np.array([], dtype='int64'))`.
I vaguely recall something similar having been done somewhere already (or at least a ticket being open).

**Comment by affanv14** [comment]
@lamblin 
Okay.If i understood you correctly. I just need to check in __getitem__ if i got an empty list in an arg and replace it with None?

**Comment by 317070** [comment]
Not with None, but with
as_tensor_variable(np.array([], dtype='int64'))

**Comment by affanv14** [comment]
I think i did just that in the PR but in an inner call.
