### ISSUE TITLE
deep learning with binary features

### ISSUE THREAD

**Issue by dinasaif** [Theano/Theano#5381]
I want to make classifier but not in images , I have (Arff)file or excell sheet with binary features can you help me to make classification with deep learning by Theano.
thanks

**Comment by Sentient07** [comment]
Hi, if you have such data formats, I would recommend you to use Pandas to load the data and convert it into a numpy array. The theano tensors are of different dimensions(3D, 4D are the predefined ones in the library and others can be constructed using TensorType ). Define Tensors of your necessity, compile a function that suits your task with the necessary Op. Train your network/model. 
P.S : These questions do not contribute to development and we request you to ask such questions on StackOverflow or theano-users mailing list henceforth.
Thanks
