### ISSUE TITLE
Unexpected DEBUG: nvcc STDOUT messages

### ISSUE THREAD

**Issue by wgpubs** [Theano/Theano#5383]
```
if sys.platform != 'win32' and nvcc_stdout:
            # this doesn't happen to my knowledge
            print("DEBUG: nvcc STDOUT", nvcc_stdout, file=sys.stderr)

```

sys.platform is equal to 'win32' so I have no idea why I'm getting all these messages when running on my 64bit Windows 10 machine.

**Comment by nouiz** [comment]
Which version of Theano do you have? I think it was fixed in the master of
Theano.

**Comment by wgpubs** [comment]
0.8.2

**Comment by nouiz** [comment]
That explain it. Use Theano dev version and you won't see that problem. It
is stable, I recommand you to use it instead  of 0.8.2

**Comment by wgpubs** [comment]
Ok. Thanks!
