### ISSUE TITLE
Optimization failure due to: local_reshape_dimshuffle

### ISSUE THREAD

**Issue by wjb123** [Theano/Theano#5392]
Hi, I run my code by THEANO_FLAGS='mode=FAST_RUN,floatX=float32,device=gpu0'  python train.py, and I use the Bleeding-edge theano version: 0.9.0dev4.dev-63006f464e712a5821cd832cae030a298eac1313, but it always reports the following errors:
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (False, True, True)), TensorType(float32, 3D), 'local_reshape_dimshuffle') local_reshape_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{3}(InplaceDimShuffle{0,x}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/junbo/software/Theano/theano/gof/opt.py", line 2004, in process_node
    remove=remove)
  File "/home/junbo/software/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/junbo/software/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/junbo/software/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (False, True, True)), TensorType(float32, 3D), 'local_reshape_dimshuffle')

**Comment by nouiz** [comment]
I think this was fixed. Are you sure you don't have multiple Theano version
and you use an older one then the one you told (this one should have the
fix)?

If that is the case, it would be very useful to get a way to reproduce it.
I suppose it will be hard to reproduce this error with a small code snipet
that still reproduce this. Can you do a function_dump?
http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

**Comment by wjb123** [comment]
I am sure that there is only one theano version in the centos system, and the theano version is latest. I try to dump the function, but it reports the error: RuntimeError: maximum recursion depth exceeded.

**Comment by nouiz** [comment]
Can you reproduce the error with a smaller graph? Keep all type of layers
and all combinations of layers, but lowering the repetition in the network
should not remove the error.

Thanks.

**Comment by nouiz** [comment]
no news and no way to reproduce, so closing. If you have that problem, make sure to update Theano.
