### ISSUE TITLE
comment typo

### ISSUE THREAD

**Issue by cosmozhang** [Theano/Theano#5414]
A typo in the comment "Sequence is shorter then the required". It should be "Sequence is shorter than the required"

**Comment by rishikksh20** [comment]
Need to change here : 
https://github.com/Theano/Theano/blob/master/theano/scan_module/scan_perform.pyx#L220

**Comment by wazeerzulfikar** [comment]
Hi, I am new to Theano and really interested in making a first contribution. I would like to work on this issue.

**Comment by rishikksh20** [comment]
@cosmozhang close this issue.
