### ISSUE TITLE
Bit length of the elements inside theano variable

### ISSUE THREAD

**Issue by kkarnatak** [Theano/Theano#5429]
Hi, I have a keras layer output in Theano variable. And, I need to calculate the bit length of each element inside this variable. This bit length is required for some further calculations. 
I am trying to do something like below:
```
Y1 = layer A output
Lambda( lambda x: conversion_method(x))(Y1)

def conversion_method( input_tensor ):
     # do the conversion and also calc bit length
     calc_integer_bits( input_tensor ) # input_tensor.eval() give an error

def calc_integer_bits(X): 
      noib_list = list() 
      for pos, each in enumerate(X): 
            in_range = int(round(abs(each .max() - each .min()))) 
            bit_length = in_range.bit_length() 
            noib_list.append(bit_length) 
       return noib_list

```
I can't call eval() method to get numpy array as it gives following error:

```
  File "C:\ENV\p34\lib\site-packages\theano-0.9.0.dev4-py3.4.egg\theano\gof\fg.py", line 396, in __import__
    variable=r)
theano.gof.fg.MissingInputError: An input of the graph, used to compute InplaceDimShuffle{x,x,x,x}(keras_learning_phase), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.
Backtrace when the variable is created:
  return original_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_remove
```

Is there any way I can get this bit length of elements inside Theano variable?

**Comment by nouiz** [comment]
What do you mean by bit length? Do you mean the number of bit in the
tensor? If so, use keras fonctionality to know the shape of the variable.
From this compute the number of element in the variable. Then multiple by
the number of bit in each element. You can find that with the "dtype"
attribute of the variable.

**Comment by kkarnatak** [comment]
Thanks for the reply. Do you think the following func would work, although its different from what you have suggested. Here I am trying to calcualte how many bits are necessary for a variable. This is imp as i am converting 32bits to 16bits and trying to evaluate results for each bitsize.
```
def func ( x ):
    range = x.max() - x.min()
    no_of_bits = theano.tensor.floor(theano.tensor.log2(range)) + 1
    return no_of_bits
```

**Comment by lamblin** [comment]
Yes, this should work.
Closing, as `theano-users` and StackOverflow would be the places to go for such questions.
