### ISSUE TITLE
Is there a bug when computing gradient of scan with until?

### ISSUE THREAD

**Issue by MultiPath** [Theano/Theano#5439]
Hi, 

I want to compute the gradient from the scan's output w.r.t the "sequences" input.
I used a "scan_module.until" to early-stop the iteration.
However, when I ran the following lines, the results seem weird:

```
import theano
import theano.tensor as tensor
import theano.scan_module as ts
import numpy

print theano.__version__

x1 = tensor.vector(dtype='float32')
r,_= theano.scan(lambda i, x: (x[i]*x[i], ts.until(tensor.eq(x[i], 5))),
                sequences=tensor.arange(x1.shape[0]),
                non_sequences=[x1])

g = theano.grad(r.sum(), x1)
f = theano.function([x1], [r, g])

x0 = numpy.arange(20).astype('float32')

print x0
print f(x0)
```

The results are:
```
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
[array([  0.,   1.,   4.,   9.,  16.,  25.], dtype=float32),
 array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 0.,   0.,   0.,  28.,  30.,  32.,  34.,  36.,  38.], dtype=float32)]
```

In my view, since the iterations only ran 5 steps before it stops, the gradient should only be computed for the first 5 elements. However,  it did the last 5 elements of the sequence.

Thank you very much!

**Comment by lamblin** [comment]
Yes, that looks like a bug in scan.
I'm not sure when we are going to be able to investigate and fix it, though.

**Comment by nouiz** [comment]
Note, the first step would be to run with mode=DEBUG_MODE. this would allow us to know if the problem is an optimization or the original graph.

**Comment by nouiz** [comment]
Just an update, we found that the grad of scan just don't check if there is an until or not. So mostly, it isn't implemented and don't return an error about that! It show that this is code never used:)

Anyway, we think it should be easy to implement it and someone is working on implementing it and testing it.
