### ISSUE TITLE
Windows toolchain update

### ISSUE THREAD

**Issue by c-w-m** [Theano/Theano#5466]
New Feature: update code to work with a more current Windows toolchain.
Proposal: Target System (but should also work on Win10):
1. Windows 7 x64
2. VS2015 Community (vs_community_ENU__553382801.1485301018.exe)
3. CUDA 8.1 (cuda_8.0.44_windows.exe base installer for Win7 x86_64) is cuDNN needed?
4. Anaconda x64 Python (2.7.12 and 3.5.2)
5. additional packages?

**Comment by nouiz** [comment]
We have better then that!

We got rid of the VS and CUDA dependencies!

There is test anaconda packages. You can test them with this command line:

conda install -c rdonnelly pygpu

We don't support ourself other method to install it on windows.

To help us get this new packages tested in more environment, do you have
time to try them?

**Comment by c-w-m** [comment]
I like the direction you are taking.

I would also be happy to help test the new implementation.

Aside from the conda installation, do you have any benchmark or regression
testing project you would like used as the basis for my evaluation?

On Mon, Jan 30, 2017 at 10:43 AM, Frédéric Bastien <notifications@github.com

**Comment by nouiz** [comment]
In python, you can run:

import theano
theano.test()

to run Theano tests suite.

Otherwise, I don't see other tests.

**Comment by c-w-m** [comment]
There are many deprecation warnings thrown when running theano.test().  That aside, there is one ERROR that needs attention:

  ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu

~~~~~~~~~~~~~~~~~~~~
my virtual environment:
~~~~~~~~~~~~~~~~~~~~
conda create --name theano-gpu python=3.5     (Python 3.5.2)
activate theano-gpu
conda install -c anaconda nose=1.3.7
conda install -c conda-forge nose_parameterized=0.5.0
conda install –c rdonnelly pygpu	     # ?this take the place of VS and CUDA
conda install theano
~~~~~~~~~~~~~~~~~~~~
> python
import theano
theano.test()

~~~~~~~~~~~~~~~~~~~~
...


~~~~~~~~~~~~~~~~~~~~
...
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\\bin\\Anaconda\\2.7.12\\envs\\theano-gpu\\lib\\site-packages\\theano\\sandbox\\cuda -IC:\\bin\\Anaconda\\2.7.12\\envs\\theano-gpu\\lib\\site-packages\\numpy\\core\\include -IC:\\bin\\Anaconda\\2.7.12\\envs\\theano-gpu\\include -IC:\\bin\\Anaconda\\2.7.12\\envs\\theano-gpu\\lib\\site-packages\\theano\\gof -o C:\\Users\\cwm\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-3.5.2-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -LC:\\bin\\Anaconda\\2.7.12\\envs\\theano-gpu\\libs -LC:\\bin\\Anaconda\\2.7.12\\envs\\theano-gpu -lcublas -lpython35 -lcudart')
C:\bin\Anaconda\2.7.12\envs\theano-gpu\lib\site-packages\theano\misc\pycuda_init.py:34: UserWarning: PyCUDA import failed in theano.misc.pycuda_init
  warnings.warn("PyCUDA import failed in theano.misc.pycuda_init")
~~~~~~~~~~~~~~~~~~~~
...

**Comment by lamblin** [comment]
Yes, the tests are trying to compile the old GPU back-end, which prints an error but should not actually make tests fail.
If you want to get rid of it, you could add `cuda.enabled=False` in the config flags.
Some deprecation warnings are normal, since we are still testing some of the deprecated features of Theano. Hopefully we will remove that after the next release.
