### ISSUE TITLE
GpuAdvancedSubtensor1 error with libgpuarray

### ISSUE THREAD

**Issue by ozancaglayan** [Theano/Theano#5467]
With the latest Theano + libgpuarray, my code is hitting the below error and does not work with the new backend:

https://github.com/Theano/libgpuarray/issues/277

**Comment by nouiz** [comment]
I was able to reproduce it here.

@abergeron, can you look at that?

**Comment by abergeron** [comment]
This should fix the problem: https://github.com/Theano/Theano/pull/5469

**Comment by ozancaglayan** [comment]
OK it works with the first commit. Thanks.
