### ISSUE TITLE
Finish Gpu Cholesky decomposition op

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5472]
Based on #4006.
- It should be based on cuSolver
- In the new back-end only
- with lifter optimizations

**Comment by nouiz** [comment]
The good commit from that PR are at the end. The other one are from a bad
rebase/merge. Ignore them.

**Comment by tfjgeorge** [comment]
I am working on this, but just a remark: there is a Cholesky version for the GpuSolve op in the new backend that deals with symmetric matrices. Do we really need a standalone Cholesky decomposition ? What would be a use case for just using a Cholesky decomposed matrix in Theano, without solving an equation of the form Ax = b ?

For reference, I put the direct link to the correct commits in the PR by matt graham: https://github.com/matt-graham/Theano/commits/cholesky_grad

**Comment by matt-graham** [comment]
@tfjgeorge 

> I am working on this, but just a remark: there is a Cholesky version for the GpuSolve op in the new backend that deals with symmetric matrices. Do we really need a standalone Cholesky decomposition ? What would be a use case for just using a Cholesky decomposed matrix in Theano, without solving an equation of the form Ax = b ?

The advantage of having a standalone Cholesky decomposition op is that often you may want to cache the Cholesky decomposition of a matrix to do multiple solve operations. It also allows easy calculation of the determinant of the matrix the decomposition was calculated of by taking the product of the diagonal entries. 

Both of these come up when for example working with the probability density function of a Gaussian where we will usually want to pre-compute the Cholesky of the D×D covariance matrix as a one-off O(D³) cost to allow for evaluations of the (log) density at a O(D²) cost.

Did you manage to make any progress with this? I have some time over the next couple of weeks to help on this if it's any use.

**Comment by nouiz** [comment]
done
