### ISSUE TITLE
cannot import theano in python3.6 (anaconda version 4.3, theano master branch)

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#5491]
```
/home/wenjian/anaconda3/lib/python3.6/site-packages/Theano-0.9.0b1-py3.6.egg/theano/gof/cmodule.py in std_include_dirs()
   1579 
   1580 def std_include_dirs():
-> 1581     numpy_inc_dirs = np.distutils.misc_util.get_numpy_include_dirs()
   1582     py_inc = distutils.sysconfig.get_python_inc()
   1583     py_plat_spec_inc = distutils.sysconfig.get_python_inc(plat_specific=True)

AttributeError: module 'numpy' has no attribute 'distutils'
```

**Comment by mmusket** [comment]
I'm experiencing a similar import error.

**Comment by ivmreg** [comment]
same

**Comment by mmusket** [comment]
I dirty fixed it by adding 
 import numpy.distutils I'm the offending file. 
I noticed there was a to-do item regarding it so I guess it's a wip

I'm on a win 10 machine and a gtx1060 I was hitting a wall. The current release was not working for me and this error was another blocker, so this quick fix will have to do for now.

**Comment by n1ghtmare** [comment]
To be specific @mmusket refers to [this line](https://github.com/Theano/Theano/blob/master/theano/gof/cmodule.py#L23), just add:
`import numpy.distutils` below, should fix your build.

**Comment by t-vi** [comment]
Hello,

This might be related to this change

https://github.com/Theano/Theano/commit/316f10443fbad9cd2185f6be64e5cb3dad275910

from PR #5454 
As far as I can tell, numpy.distutils needs to be explicitly imported.

(This also seems to break keras CI tests...)

Thank you

Thomas
