### ISSUE TITLE
AND([]) is +1 in theano and numpy 1.8 but -1 in numpy 1.12

### ISSUE THREAD

**Issue by rebecca-palmer** [Theano/Theano#5494]
Theano's AND operation has [identity=1](https://github.com/Theano/Theano/blob/84aa7becb8202ffce38d9fdca3cff2e47d39ae40/theano/scalar/basic.py#L1348), and hence CAReduce(and_) of a zero-size array is +1.

numpy.bitwise_and.reduce did the same in 1.8, but returns all-bits-set (i.e. -1 for signed types, largest value for unsigned types) in 1.12.

This causes [test_CAReduce to fail](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848764) in numpy 1.12, as [it compares AND to numpy.bitwise_and](https://github.com/Theano/Theano/blob/84aa7becb8202ffce38d9fdca3cff2e47d39ae40/theano/tensor/tests/test_elemwise.py#L415) and [includes zero-size cases.](https://github.com/Theano/Theano/blob/84aa7becb8202ffce38d9fdca3cff2e47d39ae40/theano/tensor/tests/test_elemwise.py#L327)

(I've only tested this in 0.8, but the problematic code is still there in master)

**Comment by slefrancois** [comment]
Thanks, we identified the same issue last week, we plan on having Theano start using -1 for the bitwise identity for the next release.

**Comment by rebecca-palmer** [comment]
Is this a "was always meant to be -1" bug, or a "+1 was intended in 0.8, but we've since changed our minds" design decision?

Debian is currently frozen with Theano 0.8, which is marked for possible removal because of [these test failures](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848764), so we need to decide whether to keep it as +1 and silence the test (with something like the following; means it will stay +1 in Debian stable for the ~2 years until the next Debian release), switch to -1 (easy but riskier, so might not be allowed in Debian at this stage), or do nothing and let Theano be removed (it could return in the next Debian release, but again ~2 year interval).

`--- a/theano/tensor/tests/test_elemwise.py`
`+++ b/theano/tensor/tests/test_elemwise.py`
`@@ -430,7 +430,11 @@ class test_CAReduce(unittest_tools.InferShapeTester):`
`                     zv = numpy.bitwise_or.reduce(zv, axis)`
`             elif scalar_op == scalar.and_:`
`                 for axis in reversed(sorted(tosum)):`
`-                    zv = numpy.bitwise_and.reduce(zv, axis)`
`+                    if zv.shape[axis] == 0:`
`+                        # Theano and old numpy use +1 as 'AND of no elements', new numpy uses -1`
`+                        zv = numpy.abs(numpy.bitwise_and.reduce(zv, axis).astype('int8'))`
`+                    else:`
`+                        zv = numpy.bitwise_and.reduce(zv, axis)`
`             elif scalar_op == scalar.xor:`
`                 # There is no identity value for the xor function`
`                 # So we can't support shape of dimensions 0.`

**Comment by slefrancois** [comment]
We followed numpy's convention without giving it too much tough in the past. In this case we think the change makes sense (-1 is the true bitwise identity), so we're adopting it.

For the Debian package, their release cycle is slow compared to Theano development, so it tends to get stuck on outdated versions. Maybe it's better to let the package be removed and have users install with pip or conda instead, but we haven't made a final decision yet.

**Comment by nouiz** [comment]
If people want or don't want Theano on Debian, tell it!

**Comment by rebecca-palmer** [comment]
Specifically, tell [debian-science@lists.debian.org](https://lists.debian.org/debian-science/2017/02/maillist.html); you don't need to be subscribed, but be aware that Debian does NOT mask email addresses in its public archives, so you are likely to get spam.

**Comment by lamblin** [comment]
Should be fixed in #5527.
