### ISSUE TITLE
test_fit_int64 fails in 32-bit Python 3

### ISSUE THREAD

**Issue by rebecca-palmer** [Theano/Theano#5498]
[test_fit_int64](https://github.com/Theano/Theano/blob/master/theano/tensor/tests/test_basic.py#L6891) creates a Theano array constant from a list of longs (Python 2) or ints (Python 3), and expects it to have dtype int64.

However, [this uses numpy's asarray](https://github.com/Theano/Theano/blob/master/theano/scalar/basic.py#L278), which uses list of longs -> int64 array but list of ints -> int_nativesize array, so fails with Python 3 on 32 bit systems.

(Tested in 0.8, where it was [previously noted in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831540), but the problem still appears to be there in master, though the affected code has been moved from tensor/basic.py to scalar/basic.py.  It might not have been noticed here because [Jenkins does Python2/64bit, Python2/32bit and Python3/64bit, but not Python3/32bit](https://github.com/Theano/Theano/tree/master/.jenkins).)

**Comment by nouiz** [comment]
Do you use python 3 32bit or you hit that by chance?

The easy fix would be to modify the test to have different expected output
in python2 or python3.

The other change would be in python 3, for int to always use int64 and
don't do as numpy.

What is the max value of int in python 3 32 bit? the equivalent of int32 or
int64?

**Comment by nouiz** [comment]
Which version of numpy did this happen?

**Comment by rebecca-palmer** [comment]
I found this problem while trying to fix Debian's theano package (it's [bug 831540](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831540) there; I normally use 64-bit, but Debian's policy is to provide both options if possible).  Hence, it was tested in Debian unstable (Python 3.5.3, numpy 1.12), but the underlying numpy behaviour is not new.

The Python 3 int is what used to be called a long (i.e. no size limit other than available memory); 32-bit numpy uses int32 if all the values fit, but will use int64 or even object if the list/tuple includes large values.

Also, explicit .astype(int) means int32 in 32-bit numpy (with silent truncation - only too-big-for-int64 throws OverflowError); I'm not aware of Theano using that, but haven't looked.

**Comment by rebecca-palmer** [comment]
...and theano.configdefaults.python_int_bitwidth() is 32 on 32-bit systems.

One way to fix the test:

`--- a/theano/tensor/tests/test_basic.py
+++ b/theano/tensor/tests/test_basic.py
@@ -6897,11 +6897,11 @@ class T_long_tensor(unittest.TestCase):
             assert scalar_ct.value == val
 
             vector_ct = constant([val, val])
-            assert vector_ct.dtype == 'int64'
+            assert vector_ct.dtype in ('int32','int64')
             assert numpy.all(vector_ct.value == val)
 
             matrix_ct = constant([[val, val]])
-            assert matrix_ct.dtype == 'int64'
+            assert matrix_ct.dtype in ('int32','int64')
             assert numpy.all(matrix_ct.value == val)
 
     def test_too_big(self):
`

**Comment by lamblin** [comment]
Right, with Python 2, numpy.asarray called on a Python long always gives int64 at least (or uint64).
With Python 3 however, all ints are long, and numpy.asarray uses the size of the C long on that platform (here, 32-bit for Linux 32-bit) if it can.
This is somewhat inconsistent in numpy, but I understand why they did not want to change it in Python 2.

For this test, I think your fix makes sense.
We could be stricter, and only allow `'int32'` if we are using 32-bit Python 3, but I don't think it is worth it.

@nouiz, do you agree?
If so, @rebecca-palmer , could you please submit a PR with your diff?

Thanks for the report!

**Comment by jrtc27** [comment]
I took that approach when I ran into this issue myself:
````
--- a/theano/tensor/tests/test_basic.py
+++ b/theano/tensor/tests/test_basic.py
@@ -6664,7 +6664,8 @@ class test_arithmetic_cast(unittest.Test
 
 class T_long_tensor(unittest.TestCase):
     def test_fit_int64(self):
-        for exp in xrange(theano.configdefaults.python_int_bitwidth()):
+        bitwidth = theano.configdefaults.python_int_bitwidth()
+        for exp in xrange(bitwidth):
             val = L(2 ** exp - 1)
             scalar_ct = constant(val)
 
@@ -6672,11 +6673,21 @@ class T_long_tensor(unittest.TestCase):
             assert scalar_ct.value == val
 
             vector_ct = constant([val, val])
-            assert vector_ct.dtype == 'int64'
+            # Python 3 only has int, which is more like Python 2's long. On
+            # 32-bit systems this means that int32 is used instead of int64,
+            # since numpy is not told to use a long.
+            if bitwidth == 32 and PY3:
+                assert vector_ct.dtype == 'int32'
+            else:
+                assert vector_ct.dtype == 'int64'
             assert numpy.all(vector_ct.value == val)
 
             matrix_ct = constant([[val, val]])
-            assert matrix_ct.dtype == 'int64'
+            # See note above for vector_ct.
+            if bitwidth == 32 and PY3:
+                assert matrix_ct.dtype == 'int32'
+            else:
+                assert matrix_ct.dtype == 'int64'
             assert numpy.all(matrix_ct.value == val)
 
     def test_too_big(self):
````
