### ISSUE TITLE
Warn if taking softmax over broadcastable dimension

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#5501]
At least one user inadvertently had a softmax applied to a network layer with a single output unit. The softmax Op could issue a warning if the axis to be softmaxed is broadcastable (i.e., guaranteed to only have a single element), because usually you wouldn't want this. (Otherwise, Theano could also use an optimizer replacing softmax over a broadcastable dimension with `T.ones_like()` ;) ).

**Comment by kahnchana** [comment]
Can I work on this? I'm new so will take some time. 

So this is basically about changing theano.tensor.nnet.nnet.softmax to issue a warning when softmax is fixed to a single output unit layer, isn't it? 

Also I was thinking if adding the optimizer to replace softmax for broadcastable dimensions can be done alongside the warning without using only one.

**Comment by nouiz** [comment]
Nobody work on it to my knowledge. When we build the graph, we could put a
one like as Jan said, but I think it would be better done as an
optimisation. I would recommend that you do a PR with the warning first.
The optimisation isn't really useful add this is a useless use case.

**Comment by f0k** [comment]
> So this is basically about changing theano.tensor.nnet.nnet.softmax to issue a warning when softmax is fixed to a single output unit layer, isn't it?

Exactly. As the softmax currently only supports 2D input, you'd just need to check if `input.broadcastable[1]` is True and issue a warning if it is.

> The optimisation isn't really useful add this is a useless use case.

Yep, this was meant as a joke, sorry if it wasn't explicit enough!
