### ISSUE TITLE
Wrong result with sum() on new back-end

### ISSUE THREAD

**Issue by mtomassoli** [Theano/Theano#5512]
Here's a minimal example:

    import theano
    import theano.tensor as T
    import numpy as np

    d = T.vector('d', dtype=floatX)
    d_np = np.array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=floatX)
    f = theano.function([d], d.sum())
    print(f(d_np))          # 9.0 with gpu, but 5.0 with cuda

**Comment by Sentient07** [comment]
I get consistent result on both the places. Try updating the version of theano, libgpuarray, reinstalling pygpu and try if the results are consistent.

**Comment by mtomassoli** [comment]
I updated everything, rebuilt libgpuarray from src (cmake + msbuild) and reinstalled everything, but I keep getting 5.0.
If I try summing [1, 2, 10, 11] I get 13.0. The 11 is ignored (I checked). The particular numbers are not important. I get errors with everything.

pygpu.test() tells everything is OK.

My config is Windows 10 64bit, Python 3.5.2 (Anaconda), Cuda 8.0.44 and I fetched Theano and libgpuarray directly from this and Theano/libgpuarray repositories.

If I run

    x = T.vector('x', dtype=floatX)
    x_np = np.random.uniform(size=100000).astype(floatX)
    f = theano.function([x], x.sum())
    print(x_np.sum(), f(x_np))

I get 49891.8 14015.38671875

**Comment by mtomassoli** [comment]
I even removed libgpuarray and reinstalled the conda package with comes with prebuilt binaries. Same result.

**Comment by Sentient07** [comment]
I also did the same but couldn't reproduce. What GPU do you use? Is it Maxwell architecture? Some users are facing inconsistent results on those GPUs. I really doubt this could be an issue as Arnaud (@abergeron) wasn't able to reproduce.

**Comment by mtomassoli** [comment]
It's a GTX 970. I've never had such issues with the old backend. And why doesn't pygpu.test() find anything wrong?

**Comment by abergeron** [comment]
Because it doesn't test the sum() code for Theano.

**Comment by abergeron** [comment]
I just tried it locally and I get 9.0 for both float32 and float64 with a GTX 750 (which is a Maxwell GPU and our main test card).  Admittedly I tried on linux since I don't have ready access to a windows machine with a GPU.

What I can think is that your card is somehow busted or the driver is in a weird state.  Try rebooting to see if the errors go away.

**Comment by mtomassoli** [comment]
I have two GTX 970 and they give the same (wrong) result. I'll try removing the driver completely and reinstalling CUDA.

**Comment by mtomassoli** [comment]
I reinstalled everything and I get the same result. I suspect you have some race conditions.

Here's what I get with cuda-memcheck:

```
> cuda-memcheck --tool racecheck python test.py
========= CUDA-MEMCHECK
Can not use cuDNN on context None: Disabled by dnn.enabled flag
Preallocating 2867/4096 Mb (0.700000) on cuda
Mapped name None to device cuda: GeForce GTX 970 (0000:02:00.0)
100000.0 28125.0
========= Race reported between Read access at 0x000004b8 in kernel_reduce_ccontig
=========     and Write access at 0x000004d0 in kernel_reduce_ccontig [120 hazards]
=========     and Write access at 0x00000498 in kernel_reduce_ccontig [120 hazards]
=========
========= Race reported between Write access at 0x00000450 in kernel_reduce_ccontig
=========     and Read access at 0x00000438 in kernel_reduce_ccontig [96 hazards]
=========     and Read access at 0x00000488 in kernel_reduce_ccontig [112 hazards]
=========
========= Race reported between Read access at 0x00000438 in kernel_reduce_ccontig
=========     and Write access at 0x000003b0 in kernel_reduce_ccontig [32 hazards]
=========     and Write access at 0x00000450 in kernel_reduce_ccontig [96 hazards]
=========
========= Race reported between Write access at 0x00000498 in kernel_reduce_ccontig
=========     and Read access at 0x000004b8 in kernel_reduce_ccontig [120 hazards]
=========     and Read access at 0x00000488 in kernel_reduce_ccontig [112 hazards]
=========
========= Race reported between Write access at 0x000003b0 in kernel_reduce_ccontig
=========     and Read access at 0x00000410 in kernel_reduce_ccontig [64 hazards]
=========     and Read access at 0x00000438 in kernel_reduce_ccontig [32 hazards]
=========     and Read access at 0x000003f0 in kernel_reduce_ccontig [128 hazards]
=========
========= RACECHECK SUMMARY: 5 hazards displayed (5 errors, 0 warnings)
```

With the old backend I get even more race conditions, but the result is correct. Maybe these are false positive, but are you sure?

**Comment by abergeron** [comment]
What is the version of the driver that you have installed?

**Comment by mtomassoli** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

**Comment by abergeron** [comment]
That's the cuda install.  Run nvidia-smi for the driver version.

**Comment by abergeron** [comment]
I can reproduce your problem with driver 375.26.  You are not the first to have a weird problem with that driver version.  My advice is to go back to the 367 series for the moment.

**Comment by mtomassoli** [comment]
I can't find nvidia-smi but I have version 376.51. Previously I had 378.49. Same problem. I'll try 367.x.

**Comment by mtomassoli** [comment]
Driver 373.06 works!

**Comment by abergeron** [comment]
Good to know!

**Comment by mtomassoli** [comment]
Thank you very much for your help!
