### ISSUE TITLE
cxxflags doesn't work on Windows

### ISSUE THREAD

**Issue by mtomassoli** [Theano/Theano#5519]
```
[gcc]
cxxflags="-I<PATH>"
```
seems to work but when I add -L, both flags are ignored (or so it seems).

In particular, I'd like to include two paths for cudnn (I included it in cuda):

```
[gcc]
cxxflags="-Ic:\PROGRA~1\NVIDIA~2\CUDA\v8.0\include -Lc:\PROGRA~1\NVIDIA~2\CUDA\v8.0\lib\x64"
```

**Comment by lamblin** [comment]
What happens if you remove the double quotes?
Which version of Theano are you using?

**Comment by mtomassoli** [comment]
I'm using the latest dev version from this repository.
Right now I can't do any test.

**Comment by notoraptor** [comment]
On my computer (Windows 8.1 64 bits) it works when I remove the quotes, as @lamblin suggests:

```
[gcc]
cxxflags=-Ic:\PROGRA~1\NVIDIA~2\CUDA\v8.0\include -Lc:\PROGRA~1\NVIDIA~2\CUDA\v8.0\lib\x64
```

Could you try it and post error messages if it fails again ?

**Comment by mtomassoli** [comment]
I can't do tests right now, but this works:

    [blas]
    ldflags=-LD:\MyFiles\standalone_libraries\openblas -lopenblas

**Comment by nouiz** [comment]
As no news and it work for @notoraptor, I'll close this issue. If the proposed fix don't work when you test it, reopen the issue.
