### ISSUE TITLE
run imdb_lstm.py error: 'callkernel_node' is undefined

### ISSUE THREAD

**Issue by 1064950364** [Theano/Theano#5526]
error info:
mod.cu(299): error: identifier ''callkernel_node_3a084fd032db206a67ca8121a24aa32e_0'' is undefined
1 error detected in the compilation of ''C:Users/aa/AppData/Local/Temp/tmpxft_000041d4_00000000-10_mod.cpp1.ii''

when I run mnist_cnn.py, it worked well. But when I run the imdb_lstm.py, It didn't work.

numpy1.12.0
theano0.8.2
pip8.1.2
Anconda2.7
CUDA7.5
cudnn-7.5-windows7-x64-v5.0-ga
keras1.2.1
GCC4.7.0

.theanorc.txt:
[global]
openmp=False
device = gpu
optimizer_including=cudnn
floatX = float32
allow_input_downcast=True
[lib]
cnmem = 0.8
[blas]
ldflags=
[gcc]
cxxflags=-ID:\Anaconda2\MinGW
[nvcc]
fastmath = True
flags=-LD:\Anaconda2\libs
compiler_bindir=D:\VS2012\VC\bin

when I run mnist_cnn.py, it worked well. But when I run the imdb_lstm.py, It didn't work.
Please help me!

**Comment by 1064950364** [comment]
when I add 'optimizer=None' to .theanorc.txt, it worked.But it maybe run too slow.
Maybe  it  related to CUDNN?
My OS: win10

**Comment by 1064950364** [comment]
My keras version is 1.2.1. When I used keras1.2.0, it worked.

**Comment by nouiz** [comment]
We are in the middle of deprecating the old gpu back-end. So I'm not sure
we will have the time to investigate this. optimizer=None mostly disable
the GPU. Can you give the link to the code that cause problem so that we
could reproduice it if we find the time?

**Comment by lamblin** [comment]
We have removed the old GPU back-end. We strongly suggest you [convert to the new back-end](https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)).
