### ISSUE TITLE
Black screen while working with Theano 0.9 with new backend

### ISSUE THREAD

**Issue by mtomassoli** [Theano/Theano#5529]
I was working with Theano when my display went black (I wasn't stressing the GPU in any way. Just a few eval with very small vectors of 10 elements.). Only the mouse pointer was visible. I think the video driver crashed. I had to reboot but Windows 10 wouldn't boot anymore if not in safemode. It just kept loading and loading...

I had to go back to a restore point.

I was using driver 373.06 because of issue #5512.

Something like this (but without the booting problem) also happened with Theano 0.8 but I find out it was because I was allocating too much memory with cnmem. Now I'm allocating just 0.7 so this shouldn't be the problem.

**Comment by nouiz** [comment]
cnmem isn't used by the new back-end. Can you try with the flag
gpuarray.preallocate=0.7 instead?

The screen should not go black like this. I don't know what the problem is,
but I don't remember having heard this.

**Comment by mtomassoli** [comment]
I'm already using preallocate.
BTW, I have two GPUs and I noticed that preallocate=1.0 fails (out of memory) both with cuda0 and cuda1. Is this normal?

**Comment by nouiz** [comment]
You probably don,t want to allocate 100% The driver need some memory.
Normally, 1 should be converted to 0.95 to prevent that type of error. Does
it work if you use 0.7 or you still have black screen?

**Comment by mtomassoli** [comment]
I had the black screen with device=cuda & preallocate=0.7.
I'll try again with cuda1. For now I'm just looking for a workaround. If this fails I'll try installing an older driver.

**Comment by mtomassoli** [comment]
I tried driver 368.81 and Theano can't use the GPU anymore. I get many errors such as

    WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: Unable to get the number of gpus available: CUDA driver version is insufficient for CUDA runtime version)

I'm going back to the old backend until these problems are not resolved. I'll have to rewrite part of my code which relies on bools since the old backend doesn't seem to support them on the GPU.

**Comment by mtomassoli** [comment]
FYI, driver 368.81 crashed as well but only after I suspended and resumed my PC.

**Comment by abergeron** [comment]
We can't really do anything about this until NVIDIA releases a fixed driver.

**Comment by nouiz** [comment]
The warning is that you use a too recent cuda version for the driver maybe
using an older CUDA would work for that driver. Take care that the old
driver must support the GPU you have in the computer. It is not always the
case.

**Comment by nouiz** [comment]
I saw today that nvidia released a new driver that seem to fix problems with suspend/resume. It is the driver 375.39. Can you test it?

Mostly, this is not a Theano problem, but a driver problem.

What is your GPU?

**Comment by mtomassoli** [comment]
I had never had any problems with suspend/resume until now. It only happened because I had just used theano.

I have two GTX 970.

**Comment by nouiz** [comment]
Theano could trigger bugs from the driver, but it don't mean it is the cause!

Theano is well optimized and some "broken" gpus that only cause problems when push too much get problems only with Theano as we push it very high.

We already got 4 computers that where "certified" with k6000 GPUs not working and only be fixed when the seller accepted that its power supply wasn't good even if the spec was all right. When the PSU was changed for another model from a different company, everything started to work correctly.

Anyway, that new driver have other bug with the new gpu back-end. It return wrong result, so even if it fix your suspend/resume problem, you should not use it with the new gpu back-end. To my knowledge, the old gpu back-end don't hit the bug of that serie of driver.

**Comment by mtomassoli** [comment]
I'm not suggesting that Theano is at fault. I'm just saying that my one-time-only suspend/resume problem was just a symptom that the driver was in an "unstable" state. It could've crashed in any other moment. I don't think that it's important that it happened after I resumed my PC.

BTW, if I remember correctly, importing theano is enough to cause the crash. One doesn't even have to do any computation. Are you able to reproduce the crash?

**Comment by nouiz** [comment]
We aren't able to reproduce it. One of the dev here have a windows laptop with an nvidia gpu and he didn't have this type of problems. He use the driver 373.06. His GPU is an 840m.

Anyway, I don't know what we can do.

**Comment by mtomassoli** [comment]
I'm not surprised. You should try with a 970. I don't even know if the 840m and the 970 rely on the same driver code. Maybe the drivers, even if unified, contain customized parts for different cards. I'm really not a GPU programmer so I'm just speculating.

**Comment by lamblin** [comment]
Are you able at all to get a driver of the 367 or 373 series working (without Theano), without Windows restoring a different version?

**Comment by mtomassoli** [comment]
Yes, there are ways to prevent the update.

**Comment by lamblin** [comment]
Have you done that?

**Comment by mtomassoli** [comment]
I don't know exactly what you're getting at, but I updates drivers regularly and I installed my GTX 970s at least 2 years ago, so I would have noticed problems with the 373 series.

**Comment by lamblin** [comment]
Can you please do the following:
- install a driver of the 367 series,
- reboot, and make sure Windows does not upgrade or uninstall it,
- make sure the machine is stable with that driver without using Theano,
- upgrade Theano to the latest development version from GitHub,
- upgrade and reinstall libgpuarray and pygpu
- try again to import theano and report.

Thanks,

**Comment by mtomassoli** [comment]
I tried so many drivers and used so many restore points that Windows got somewhat corrupted and I was able to update my drivers only through Windows update. Right now I don't dare to mess anymore with the video drivers.
One alternative is to build a live image of Windows. See [this](http://theoven.org/index.php?topic=1336.0).
I can't look into it right now, but if you manage to build a working image I'll gladly try it out and report.

**Comment by lamblin** [comment]
OK.
Unfortunately, we do not have a 970 to test, nor the time or expertise to build an image for you.
Unless you have a way of reproducing the issue on a clean installation of Windows, with the latest drivers supported by Theano, and the latest version of theano/libgpuarray/pygpu, I'm going to assume that the "somewhat corrupted" installation of Windows is to blame.
Hopefully Nvidia will release a fixed driver that you can install through Windows update.

**Comment by mtomassoli** [comment]
Now it works on 376.53! As for the crash with older drivers, who knows...

**Comment by nouiz** [comment]
Thanks for the update.
