### ISSUE TITLE
Detect bad nvidia driver in the new back-end

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5530]
There was a few reports of wrong result in the new back-end. They seem to be related to a bad driver.

Add in Theano code that will test the case that give bad result to know if the driver is good or not.

The issue that report the wrong values.
https://github.com/Theano/Theano/issues/5475
https://github.com/Theano/Theano/issues/5512
probably also https://github.com/Theano/Theano/issues/5379

Summary of bad drivers:
- 375.* and up (more detail: 375.26, others?)

Summary of good drivers:
- 367.57, 373.06

**Comment by abergeron** [comment]
More specifically the problem appears to be with drivers 375.* and up.  

I can personally confirm that 367.57 is ok, and I've had reports that 373.06 is also ok.

**Comment by abergeron** [comment]
See https://github.com/Theano/libgpuarray/pull/352

**Comment by mtomassoli** [comment]
Driver 373.06 and previous versions give the right result but they crash and Windows won't boot anymore without direct intervention. I don't know what's wrong, but I'm staying away from the new backend until you solve this issue. On my system there are no good drivers for the new backend. New ones give wrong result and older ones crash. Never had any issue with the old backend.

**Comment by nouiz** [comment]
done in libgpuarray

**Comment by Dapid** [comment]
As I understand, this should be fixed in https://github.com/Theano/Theano/issues/5632 (see also https://github.com/Theano/Theano/issues/5623) and the drivers 375.* and up should be usable, right?

(I cannot test it myself right now, computer down).

**Comment by nouiz** [comment]
I confirm, Theano master branch should now work with recent nvidia driver.

**Comment by mtomassoli** [comment]
Yeah, now it works!
