### ISSUE TITLE
shape mismatch: error message is too vague in new backend

### ISSUE THREAD

**Issue by khaotik** [Theano/Theano#5534]
For the same model with a shape mismatch:

using CPU:

```
Traceback (most recent call last):
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: Shape mismatch: x has 128 cols (and 16 rows) but y has 512 rows (and 32 cols)
```

the old backend:

```
Traceback (most recent call last):
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: dimension mismatch in args to gemm (16,128)x(512,32)->(16,32)
```

the new backend:

```
Traceback (most recent call last):
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/blas.pyx", line 44, in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:2011)
pygpu.gpuarray.GpuArrayException: (b'Value invalid or out of range', 2)
```

With the new backend, the error message is just misleading.

**Comment by hkhatri241** [comment]
Seems like pygpu.blas.pygpu_blas_rgemm is returning a GA_VALUE_ERROR as defined here: https://github.com/Theano/libgpuarray/blob/fde02d272470fa6a3db4051d953291bc73c2bbd9/src/gpuarray_error.c . Any suggestion on the approach to take?

**Comment by abergeron** [comment]
We can check the shapes before calling into it to get a pretty error message.

Or we can wait for the new error reporting that is on the todo list for libgpuarray and should give better error messages.

**Comment by nouiz** [comment]
A new PR on libgpuarray should give now much better error in many cases including this one:

Fow we give something like:

ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[1] == 1, but the output's size on that axis is 2.
