### ISSUE TITLE
which version of theano support cuda8.0+cudnnv6

### ISSUE THREAD

**Issue by gmyofustc** [Theano/Theano#5549]
I am using tesla p40 card, but this device only support cuda8.0 with cudnn v6
I am using Theano 0.9, but this version does not support cudnn v6 right now, 
looking for  theano version support cudnn v6

**Comment by nouiz** [comment]
Where did you found cudnn v6?

The old gpu back-end support cudnn v4. This probably cause it to use older
interface that is removed from cudnn v6.
The new gpu back-end only support cudnn v5, so it probably don't have that
problem.

Can you tell which gpu back-end did you used? What was the value of Theano
flag device?

cuda 8 is supported for a long time. The old back-end always supported it
and the new back-end supported it before its final release.

**Comment by fayeshine** [comment]
@gmyofustc where is the link to cudnn v6?

**Comment by gmyofustc** [comment]
@nouiz  @fayeshine I am using nvidia pascal p100 gpu, and cuda8.0-cudnn-v6 comes from the official CD driver

**Comment by nouiz** [comment]
Did you try with the new GPU back-end? I think it should work.

Note, we have problems with recent cuda driver. So maybe you will get an
error due to that. We are working on work around the changes in the
behavior of cuda drivers.

**Comment by gmyofustc** [comment]
@nouiz i tried the new gpu back-end, it still does not work. I will use theano on Tesla series gpus, thanks for your advice.

**Comment by nouiz** [comment]
Can you give the error message?
