### ISSUE TITLE
Same graph but different time-consuming and different apply nodes after compile

### ISSUE THREAD

**Issue by aeloyq** [Theano/Theano#5575]
i've got two cumputing graph
first one printed by pydotprint like this:
![5665](https://cloud.githubusercontent.com/assets/20637250/23095898/e6439fc4-f64c-11e6-8067-6ecaa87768b9.png)
another one like this:
![123444665](https://cloud.githubusercontent.com/assets/20637250/23095908/0530bf5c-f64d-11e6-80a8-1280da3668d5.png)
i didn't find anything different
but after i test these function , first graph cost 6 seconds while another one cost only 4 seconds.
i'm really confused.
here is the profile

first graph:
Time in 2500 calls to Function.__call__: 6.304999e+00s
  Time in Function.fn.__call__: 6.196999e+00s (98.287%)
  Time in thunks: 6.103061e+00s (96.797%)
  Total compile time: 6.389999e-01s
    Number of Apply nodes: 39
    Theano Optimizer time: 5.290000e-01s
       Theano validate time: 1.000047e-02s
    Theano Linker time (includes C, CUDA code generation/compiling): 4.500008e-02s
       Import time 1.799989e-02s
       Node make_thunk time 4.299998e-02s

second graph:
Time in 2500 calls to Function.__call__: 4.366000e+00s
  Time in Function.fn.__call__: 4.256000e+00s (97.481%)
  Time in thunks: 4.194483e+00s (96.072%)
  Total compile time: 4.640000e-01s
    Number of Apply nodes: 35
    Theano Optimizer time: 3.720000e-01s
       Theano validate time: 6.299949e-02s
    Theano Linker time (includes C, CUDA code generation/compiling): 3.099990e-02s
       Import time 1.199961e-02s
       Node make_thunk time 2.900004e-02s

actually they if i drop the updating in function i still got a big difference so there may not issues for updates.

**Comment by aeloyq** [comment]
i found sth abnormal in detail profile
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Class name>
  23.3%    48.4%       1.422s       1.90e-04s     C     7500       3   theano.sandbox.cuda.basic_ops.HostFromGpu
<% time> <sum %> <apply time> <time per call> <type> <#call> <#apply> <Op name>
  23.3%    23.3%       1.422s       1.90e-04s     C     7500        3   HostFromGpu

**Comment by aeloyq** [comment]
ok i print the graph after compiling(no update)
there's distinct difference
why that happens
am i forgot sth
![56665](https://cloud.githubusercontent.com/assets/20637250/23096287/d61088cc-f653-11e6-8c72-fa26ca703da6.png)
![Uploading 6123444665.png…]()

**Comment by aeloyq** [comment]
ok i may have found the problem
i transformed the mnist train data into theano sharedvariable ........ twice?

**Comment by lamblin** [comment]
I don't think there is a bug in Theano given these informations.
If you have more, that could indicate an issue in Theano, please feel free to re-open.
