### ISSUE TITLE
Port merged PR with milestone 0.9.1

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5584]
We will/have merged them after Theano 0.9 release. If we do an 0.9.1, back-port those PR.

**Comment by notoraptor** [comment]
New tag (`0.9.0rc1`) and new branch (`0.9.X`) created on central repository.

**Comment by notoraptor** [comment]
PyPI package online: https://pypi.python.org/pypi/Theano/0.9.0rc1

**Comment by nouiz** [comment]
@notoraptor, this issue is about 0.9.1, not 0.9rc1.
