### ISSUE TITLE
TypeError with dimshuffle and set_subtensor

### ISSUE THREAD

**Issue by laudney** [Theano/Theano#5589]
Hi

I have the following code:

`y_true = target.dimshuffle(1, 0, 2, 3).flatten(ndim=1)`
`weights = T.ones_like(y_true)`
`weights = T.set_subtensor(weights[T.eq(y_true, 1.0).nonzero()], 100)`
`weights = T.set_subtensor(weights[T.eq(y_true, -1.0).nonzero()], .0)`

Then I get the following errors when I try to train the model:

> ERROR (theano.gof.opt): Optimization failure due to: local_gpua_advanced_incsubtensor
ERROR (theano.gof.opt): node: AdvancedIncSubtensor1{no_inplace,set}(HostFromGpu(gpuarray).0, TensorConstant{0.0}, Subtensor{int64}.0)
...
...
TypeError: InplaceDimShuffle{0}.0

Any help would be much appreciated. Thanks.

**Comment by lamblin** [comment]
Please provide an full runnable example, as well as information regarding your set up (which version of Theano, contents of .theanorc, are you using the GPU, etc.).

**Comment by lamblin** [comment]
I executed the following with the latest Theano master, without any issue:
```python
>>> y_true = T.tensor3()
>>> weights = T.ones_like(y_true)
>>> weights2 = T.set_subtensor(weights[T.eq(y_true, 1.0).nonzero()], 100)
>>> weights3 = T.set_subtensor(weights2[T.eq(y_true, -1.0).nonzero()], .0)
>>> print(weights3.eval({y_true: [[[-1, 0, 1]]]}))
[[[   0.    1.  100.]]]
```

**Comment by laudney** [comment]
It's the dimshuffle that creates the problem. I'm running the latest Theano git on Titan X. Below code can reproduce the error on my side.

>   File ".../python3.5/site-packages/Theano-0.9.0b1-py3.5.egg/theano/gpuarray/basic_ops.py", line 560, in make_node
    raise TypeError(x)
TypeError: InplaceDimShuffle{0}.0


```python
target = tt.ftensor4()
y = target.dimshuffle(1, 0, 2, 3).flatten(ndim=1)
w = tt.ones_like(y)
w = tt.set_subtensor(w[tt.eq(y, 1.0).nonzero()], 100)
w = tt.set_subtensor(w[tt.eq(y, -1.0).nonzero()], 0)
f = theano.function([target], w)
```

**Comment by nouiz** [comment]
I'm able to reproduce it.

**Comment by nouiz** [comment]
thanks, this PR fix that:

https://github.com/Theano/Theano/pull/5593

**Comment by laudney** [comment]
@nouiz Thank you, sir!
