### ISSUE TITLE
Sub-profile for scan ops are not printed any more

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5590]
Neither in the old or new back-end, but they are still there for CPU.

**Comment by lamblin** [comment]
Actually, it prints "skipping empty profile", so the code for printing the profile seems to be there, but the right profile does not seem to be associated with the execution of scan.

**Comment by nouiz** [comment]
Is this related to https://github.com/Theano/Theano/pull/5455?

**Comment by lamblin** [comment]
I don't think so, the profile for the main function is still there, but the profile for the step function of scan is not, even in the old back-end.
