### ISSUE TITLE
 GpuArrayException not raised

### ISSUE THREAD

**Issue by deepali-c** [Theano/Theano#5592]
While executing tests using `theano-test`, I observed the following:
```
===================================================
FAIL: Test that scan_checkpoint reduces memory usage.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/test_scan_checkpoints.py", line 65, in test_memory
    self.assertRaises(GpuArrayException, f, data, 1000)
AssertionError: GpuArrayException not raised
----------------------------------------------------------------------
```

**Comment by nouiz** [comment]
This test make sure something crash as it use too much memory. But from
other issue you have, you are maybe on a computer that have enough memory
to don't crash in that case. How much CPU RAM do you have? GPU RAM? Maybe
we should adjust that test sizes to check what the user have.

Fred

**Comment by deepali-c** [comment]
Yes we do have a lot of memory.

**Comment by nouiz** [comment]
@lamblin did a fix for that error in the master. Can you update Theano and try again to confirm the fix is also good for your use case?

**Comment by deepali-c** [comment]
Yes, the test passes now. 
`Test that scan_checkpoint reduces memory usage. ... ok`

**Comment by nouiz** [comment]
thanks
