### ISSUE TITLE
test_conv3d_bwd fails on power

### ISSUE THREAD

**Issue by deepali-c** [Theano/Theano#5601]
While executing `theano-test` I observe that the `test_conv3d_bwd` fails on power for both old and new backend.

Example error - [Error.txt](https://github.com/Theano/Theano/files/793023/Error.txt)

**Comment by lamblin** [comment]
The median error seems to be really low, so it might just be that we need to bump slightly the tolerance of the test.
By default, conv3d_bwd is not deterministic with cuDNN (due to the use of atomic float add), so we may have missed some outliers.
Could you try to bump the rtol a bit, and see if it helps? The maximum errors reported can look scary, but when the relative error is high, the abolute one is usually low, and vice versa.

**Comment by deepali-c** [comment]
For the old backend I did the following changes:
```
-        utt.assert_allclose(res_ref[0], res[0], rtol=2e-5)
-        utt.assert_allclose(res_ref[1], res[1], rtol=2e-5)
+        utt.assert_allclose(res_ref[0], res[0], rtol=2e-4)
+        utt.assert_allclose(res_ref[1], res[1], rtol=2e-4)
```
and for the new backend I tried following:
```
-        rtol = None
+       rtol = 1e-04
```

With these changes the test_conv3d_bwd did pass. And now I am executing complete set of test cases.

**Comment by deepali-c** [comment]
After making these changes I observed that when I execute `test_conv3d_bwd` using `nosetests -sdv theano.sandbox.cuda.tests.test_dnn:test_conv3d_bwd` it passes but when the complete set of test cases is run through `theano-test`, the tests fail.

**Comment by nouiz** [comment]
That could be caused by the test using different initial random value. So
it also point to making the test more tolerant to small variation.

**Comment by nouiz** [comment]
This is in the old GPU back-end that we will remove. Did you installed libgpuarray? If so, do you have errors in the new back-end tests?

Also, which Theano flags do you use? Some cudnn flags can change the precision of the computation and make the test request more tolerance than what is there. But it would explain that we don't get other report of this.

**Comment by nouiz** [comment]
As no news, I'll close as it is probably working now correctly. But if you still have problem, reopen.
