### ISSUE TITLE
Possible improvement on scan function 

### ISSUE THREAD

**Issue by aeloyq** [Theano/Theano#5602]
this is a simple scan example
which contains 1 input A  and 2 outputs to caculate A^2,A*2

code like
`import theano
import theano.tensor as T
A = T.vector("A")
def fun(prc,prj,A):
    return prc*A,prj+A
result, updates = theano.scan(fn=fun,
                              outputs_info=[T.ones_like(A),T.zeros_like(A)],
                              non_sequences=A,
                              n_steps=2)
f = theano.function(inputs=[A,k], outputs=result)
print(f([3,4]))`
and i got the result i want:
`[array([[  3.,   4.],
       [  9.,  16.]], dtype=float32), array([[ 3.,  4.],
       [ 6.,  8.]], dtype=float32)]
`
but if i change the order of inputs in  function fun
`def fun(A,prc,prj):
    return prc*A,prj+A`
A is still the none_sequence
but i got the result like this
`[array([[  0.,   0.],
       [  0.,  0.]], dtype=float32), array([[ 4.,  5.],
       [ 3.,  4.]], dtype=float32)]`

i think the reason is that:

at first function fun's inputs order is:
A,outputs_info[1],outputs_info[0] 
and get the first output which i named: 
pro_fun_output[0],pro_fun_output[1]

following iteration's inputs order is:
A,pro_fun_output[1],pro_fun_output[0]

so i got the wrong result finally

what machanism leads outputs_info assign value to function's input like this
why can't it keep the order and just jump over sequence and none_sequence inputs

**Comment by nouiz** [comment]
This ipython notebook have a good explanation of scan:

https://github.com/lamblin/ccw_tutorial/blob/master/Scan_W2016/scan_tutorial.ipynb

Mostly, scan force the order of inputs and outputs of fun. We can't use the order of the kwargs passed to the scan function as we don't have that.

If that URL don't clarify thing enough, ask again on the theano-user mailing list. issue are for feature request/bug report. Not user questions like what this is.

**Comment by aeloyq** [comment]
i see
thank you!
