### ISSUE TITLE
Problem with neibs2images

### ISSUE THREAD

**Issue by bernardohenz** [Theano/Theano#5613]
Hi,
I am trying to use the images2neibs and neibs2images functions, but the neibs2images seems not to be working. My theano is updated. Here is the simplest example I've tryied

```python
import numpy as np
import theano
from theano import tensor as T

imagesP = T.tensor4('imagesP')
patches = T.nnet.neighbours.images2neibs(imagesP, [16,16])
extractPatches = theano.function([imagesP], patches,on_unused_input='ignore')

patsRecovery = T.matrix('patsRecovery')
original_size  = T.vector('original_size')
reconstructed_imgs = T.nnet.neighbours.neibs2images(patsRecovery, (16,16),original_size)
recoverImg = theano.function([patsRecovery,original_size],reconstructed_imgs,on_unused_input='ignore')

im_val = np.ones((1,3, 320, 320),dtype=np.float32)
neibs = extractPatches(im_val)    #shape = (1200,256)
recovered_img = recoverImg(neibs ,im_val.shape)

```

While the "images2neibs" works fine, the other one keep getting the following error "ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False), ('x', 'x', 0, 1)))"
Can someone help me?

**Comment by lamblin** [comment]
The error message seems to indicate that `patsRecovery` is a 4D tensor, which does not seem to be the case from your code.
Another issue is that `original_size` should be a vector of integers, not floats.
If I correct that last issue, I find another error because Theano is not able to infer the length of `original_size`, even though it is supposed to be 4 for everything to make sense. I'll try to come up with a fix for that.

Cheating a little bit to make the shape 4 scalars instead of one vector, the following code works:
```python
import numpy as np
import theano
from theano import tensor as T
import theano.tensor.nnet.neighbours

imagesP = T.tensor4('imagesP')
patches = T.nnet.neighbours.images2neibs(imagesP, [16,16])
extractPatches = theano.function([imagesP], patches,on_unused_input='ignore')

patsRecovery = T.matrix('patsRecovery')
original_size  = [T.iscalar('original_size%i' % i) for i in range(4)]
reconstructed_imgs = T.nnet.neighbours.neibs2images(patsRecovery, (16,16),original_size)
recoverImg = theano.function([patsRecovery] + original_size, reconstructed_imgs, on_unused_input='ignore')

im_val = np.ones((1,3, 320, 320), dtype=np.float32)
neibs = extractPatches(im_val)
recovered_img = recoverImg(neibs, *im_val.shape)
```

**Comment by nouiz** [comment]
@lamblin did a PR yesterday that fix your problem and I updated it with more fixes related to this case. see gh-5616. You can use it now until it get merged.

thanks for the report. Don't forget @lamblin comment that the shapes must be int, not float.
