### ISSUE TITLE
ContextNotDefined: context is not registered

### ISSUE THREAD

**Issue by deepali-c** [Theano/Theano#5617]
Hi,

I am using the below code to execute the `pygpu tests` after `theaono tests`:
    
```
        import theano        
        theano.test()
        import os
        import pygpu
        os.environ["DEVICE"] = "cuda0"
        print("Running pygpu tests")
        pygpu.test()
```

At the end of the `pygpu.test(),` I am getting following error:

```
ERROR: test_GpuArray (pygpu.tests.test_gpu_ndarray.TestPickle)
Traceback (most recent call last):
  File "/pathto/pygpu/tests/test_gpu_ndarray.py", line 744, in test_GpuArray
    pickle.dumps(pygpu.zeros((32,), context=ctx))
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 292, in save
    rv = reduce(obj)
  File "/pathto/theano/gpuarray/type.py", line 811, in GpuArray_pickler
    ctx_name = _name_for_ctx(cnda.context)
  File "/pathto/theano/gpuarray/type.py", line 105, in _name_for_ctx
    raise ContextNotDefined('context is not registered')
ContextNotDefined: context is not registered
```
 I had also initiated a discussion on [theano-users group](https://groups.google.com/forum/#!topic/theano-users/XQoUTvGFTD0) for this.

**Comment by nouiz** [comment]
Modify the environ before importing pygpu. pygpu read the env when it get
imported. It don't see later change to the enc.

**Comment by deepali-c** [comment]
I modified the script to set the `DEVICE` before importing `pygpu`:
```
        import theano        
        theano.test()
        import os
        #import pygpu
        os.environ["DEVICE"] = "cuda0"
        print("Running pygpu tests")
	import pygpu
        pygpu.test()
```
But I still see the same issue. The complete output is - 
[pygpu_context_error_x86.txt](https://github.com/Theano/Theano/files/806327/pygpu_context_error_x86.txt)

So although it executed pygpu tests but it gives the `Context not registered` error for `"test_GpuArray (pygpu.tests.test_gpu_ndarray.TestPickle)"`. 

Similar issue is not seen if only pygpu tests are executed using:
```
        import os
        #import pygpu
        os.environ["DEVICE"] = "cuda0"
        print("Running pygpu tests")
	import pygpu
        pygpu.test()

```
However, when I execute `pygpu.test()` after `theano.test()` in the same script then I observe this error.

**Comment by nouiz** [comment]
It is possible/probable that Theano will import pygpu depending of your
Theano flags. Do os.environ before importing anything else then os.
Something like:

import os
os.environ...
# then import theano and/or pygpu and/or any other lib. If there is
anything that import pygpu before os.environ, then it will be ignored.
