### ISSUE TITLE
Add unshared (Locally-connected) convolution

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5620]
There was such op in Pylearn2:

https://github.com/lisa-lab/pylearn2/tree/master/pylearn2/packaged_dependencies/theano_linear/unshared_conv

But before working on this, check if there is a better implementation somewhere else.

It will need to be ported to the new back-end.

**Comment by f0k** [comment]
> But before working on this, check if there is a better implementation somewhere else.

A possible alternative would be a im2col-based implementation. We have a pure Theano implementation in Lasagne to compare performance against.

**Comment by affanv14** [comment]
Wont there be a huge memory overhead with im2col and unshared convolutions combined?

**Comment by f0k** [comment]
> Wont there be a huge amount of memory used with im2col

Memory use for the `im2col` operation would be the same. But the way `im2col` works, we can't use gemm for the reduction. We'd have to check what's the best option. Not sure if batched gemm would be a good idea.

**Comment by nouiz** [comment]
Batched gemm in cublas was optimized for "small" matrix, up to 128 or 256
on each dimensions. I don't know how efficient it is for bigger matrix.
This could be tested with a small Theano graph that just do a batched gemm
with the right shape to see how efficient it is at those sizes.

Do you know the sizes on which it would be called?

**Comment by f0k** [comment]
> Do you know the sizes on which it would be called?

In the forward pass, `im2col` is called for each item in a batch. Each item has a shape of `(channels, h, w)` and will be transformed to `(regions, channels*kh*kw)` (where `regions` is the number of positions the filter kernel will be applied).
In normal convolution, the weight tensor would be reshaped to `(filters, channels*kh*kw)`, so you can apply `gemm` with the second argument transposed, and obtain a `(filters, regions)` output.
In unshared convolution, the weight tensor would be reshaped to `(filters, regions, channels*kh*kw)`. With these shapes, what we'd want to compute would be `(im2col(input) * weights).sum(axis=-1)`, so we get an output of `(filters, regions)` as in normal convolution. With a different layout of shapes, this could be done as `regions` many matrix products of a `(1, channels*kh*kw)` and a `(channels*kh*kw, filters)` matrix. So typically, the matrices would be up to maybe 256*9 x 256, and the number of matrices depends on the image size and stride. And actually a batched gemv would suffice, but that doesn't exist.

Before we benchmark a batched gemm, we'd need to think through if we can actually provide the weight tensor in the correct memory layout for this to work for the forward and two backward passes.

**Comment by f0k** [comment]
CUDA 8's strided batched gemm is relevant: https://devblogs.nvidia.com/parallelforall/cublas-strided-batched-matrix-multiply/

**Comment by affanv14** [comment]
@f0k i have a few questions
1.Would this also need a cpu and gpu implementation as well?

2.Inputs would need to be computed in batches,so do i add a loop to the  method mentioned above?

> we'd need to think through if we can actually provide the weight tensor in the correct memory layout for this to work for the forward and two backward passes.

3.Can you elaborate on why we need two backward passes.

**Comment by f0k** [comment]
> Would this also need a cpu and gpu implementation as well?

Yes (although batched gemm concerns the gpu Op only).

> Inputs would need to be computed in batches,so do i add a loop to the method mentioned above and join them later?

Yes, that's the way it's done for standard convolution: https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/corr_gemm.c
You wouldn't join the tensors, but reserve an output tensor large enough and then write to the correct offsets within that tensor.

> Can you elaborate on why we need two backward passes.

Hmm, that formulation was misleading. We need to multiply the gradient wrt. the output (that we get from the layer above) with (1) the Jacobian of the output wrt. the input, and (2) the Jacobian of the output wrt. the weights (so we get the gradient wrt. the input and wrt. the weights). In a standard convolution, both these operations are convolutions as well, and can be implemented with gemm.

**Comment by vikramnitin9** [comment]
> Before we benchmark a batched gemm, we'd need to think through if we can actually provide the weight tensor in the correct memory layout for this to work for the forward and two backward passes.

Can you tell me more about how we might decide whether this is possible?

**Comment by f0k** [comment]
> Can you tell me more about how we might decide whether this is possible?

Well, think through what the backward passes for unshared convolution must look like, how you could implement them efficiently, and how this aligns with the memory layout options for the forward pass. Have a look at the [regular gemm-based convolution implementation](https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/corr_gemm.c) for comparison.

**Comment by nouiz** [comment]
Now that gh-6286 is merged, should we close this issue?

Is it useful to do the same on the cudnn conv as done on the GpuCorrMM op to have the unshared use the cudnn implementation?

**Comment by vikramnitin9** [comment]
I don't think cuDNN directly supports unshared convolution yet. And I don't know how we could compute it efficiently in terms of the existing cuDNN functions.

**Comment by nouiz** [comment]
so it seem this wasn't a good idea. So I close this issue.

thanks.
