### ISSUE TITLE
Do not use unsafe warp synchronous programming

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5623]
It seems that [warp synchronous programming is a lie](https://github.com/AccelerateHS/accelerate/issues/167), and that it was the issue behind #5475, #5512, etc., with newer drivers.

We should:
- find an appropriate, safe solution
- find all the places in Theano to apply it.

**Comment by lamblin** [comment]
For now (excluding the old back-end), I found:
- [ ] https://github.com/Theano/Theano/blob/140d0a064523349b630a284247c7cddd767fc46e/theano/gpuarray/kernel_codegen.py#L90
- [ ] https://github.com/Theano/Theano/blob/140d0a064523349b630a284247c7cddd767fc46e/theano/gpuarray/kernel_codegen.py#L271
- [ ] https://github.com/Theano/Theano/blob/140d0a064523349b630a284247c7cddd767fc46e/theano/gpuarray/elemwise.py#L1169

**Comment by cliffwoolley** [comment]
FWIW, it *is* actually (sort of) documented that warp-synchronous programming should not be used.  See http://docs.nvidia.com/cuda/kepler-tuning-guide/index.html#warp-synchronous

**Comment by abergeron** [comment]
I've made the changes, tested with the examples in the two tickets and everything seems fine.  I am running the test suite with 375.26 on a 750 to make sure everything is fine and I'll make a PR once this is finished.
