### ISSUE TITLE
Remove `.value` from shared variables

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5627]
It has been deprecated and raising an exception for a looong time.

**Comment by nouiz** [comment]
I'm not convinced about that. I recently found old codes that use it. Having a good error is very useful. This specific code clean up don't make a big difference, just a few lines of codes, so I'm -0.5 on this as the gain isn't significant. Both otherwise, clean up is good:)

**Comment by nouiz** [comment]
@lamblin told IRL he is ok to close.
