### ISSUE TITLE
Will Theano new back-end (cuda#) cost more memory than the old one (gpu#)?

### ISSUE THREAD

**Issue by cshanbo** [Theano/Theano#5628]
Hi,
I was using Theano new back-end to run an experiment.
I found that the new back-end will raise an out-of-memory exception with exactly the same settings with the old back-end (gpu#)  so that I have to reduce the batch size to keep the experiment running. 

I made a rough comparison, and found that the memory usage of new back-end is 3~ times of the old one. 

So I wonder if there's any method to fix it.

**Comment by nouiz** [comment]
It should not use the same amount, but how it is managed is different by
default. We think the current default is better, but can cause problems
like what you got.

the flag lib.cnmem isn't used anymore. It is gpuarray.preallocate. It
default to enabled, but to don't take all memory, which can cause memory
fragmentation. You can try the value -1, that will deactivate it, so it
will be the most memory efficient, but will slow down computation. Or you
can set it to 1 or 0.9 to take most of the GPU memory (it is a %, by
default 1 goes to 0.95 as the driver and other stuff use memory). This will
be the fastest and won't have fragmentation.

Keep us updated on what you try and get as a result.

**Comment by cshanbo** [comment]
Oh, great! The gpuarray.preallocate FLAG really works! It indeed cost a lot
more memory than the old back-end. 

I will compare the training speed on my project. 

Thank you so very much for your help.

**Comment by aeloyq** [comment]
i faced with the same situation

is there any other way to reduce the memory cost besides preallocate ?

otherwise， can i say these extra cost is necessary for speedup?

**Comment by cshanbo** [comment]
Hi @aeloyq 
I'm currently using `gpu.preallocate` to control the memory usage, and it works well.

Experimental results show that it **DOES** speedup the training (roughly 20% according to my experience). You can test it by yourself. 
> i conbined the predict and updates within one theano function , may it cause the problem? 

I don't think that's a problem.

> is there any other way to reduce the memory cost besides preallocate ?

I'm sorry that I cannot answer the question. Maybe @nouiz can give us some advices.

**Comment by nouiz** [comment]
With the new back-end, if you don,t define preallocate, Theano will still
cache the gpu memory usage (so won't free it), but could use less memory.
But this can also use more memory due to fragmentation. It depend of the
use case. If your inputs size changes, using the biggest size in the first
call could limit/remove the fragmentation, but I didn't test it.

So mostly, try without, it could slow down only the first call in the new
back-end if the sizes don't change too much.

**Comment by aeloyq** [comment]
Thank you very much !!

Preallocate works!

> If your inputs size changes, using the biggest size in the first
call could limit/remove the fragmentation, but I didn't test it.

For this:I tried to use the biggest size in the first call (training seq2seq model from max-length 50 to 10)
and the memory usage without prealloocate and allowgc(MiB):
1381(first call)
4220(began from third call)
6588(began from nearly 1000th call)
8726(began from nearly 10000th call)
