### ISSUE TITLE
--Weird T.sum error ?!

### ISSUE THREAD

**Issue by jc-Rosichini** [Theano/Theano#5637]
Just went through a weird error using T.sum()

Quick summary (dump follows)
`
yt_hot
 [[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]]

logp
 [[ -2.30258512  -1.60943794  -1.20397282  -0.9162907 ]
 [ -0.9162907   -2.30258512  -1.60943794  -1.20397282]
 [ -1.20397282  -0.9162907   -2.30258512  -1.60943794]
 [ -1.60943794  -1.20397282  -0.9162907   -2.30258512]
 [-20.7232666   -0.69314718 -20.7232666   -0.69314718]
 [ -2.30258512  -0.9162907   -1.60943794  -1.20397282]]

A = - yt_hot * logp
 [[ 0.          1.60943794  0.          0.        ]
 [ 0.          0.          1.60943794  0.        ]
 [ 0.          0.          0.          1.60943794]
 [ 1.60943794  0.          0.          0.        ]
 [ 0.          0.69314718  0.          0.        ]
 [ 0.          0.9162907   0.          0.        ]]

sig should be equal to sum(A) ... BUT this is not the case !!!
 2.3025851249694824
`

[marbug.txt](https://github.com/Theano/Theano/files/809271/marbug.txt)

Test code follows:
[marbug_py.txt](https://github.com/Theano/Theano/files/809270/marbug_py.txt)

**Comment by jc-Rosichini** [comment]
`
import theano
import theano.tensor as T
import numpy as np
import lasagne

def c_sym(yp, yt):
    n_classes = yp.shape[1]
    
    yt_flat = T.flatten(yt)   # b,0,1 -> b01    
    
    epsilon = 1e-9
    P = yp + epsilon
    yt_hot = lasagne.utils.one_hot(yt_flat,n_classes)
  
    # Compute cross-entropy
    logp = T.log(P)
    A = - yt_hot * logp 
    sig = A.sum()

    return sig, A, yt_hot, logp


def test_c_sym():
    y_pred = T.fmatrix()
    y_true = T.imatrix()
    
    sig ,A, yt_hot, logp = c_sym(y_pred, y_true)
    fn = theano.function([y_pred, y_true], [sig ,A, yt_hot, logp])
    
    yt = np.array([ [1,2,3],
                    [0,1,1] ])
					
    yp = np.array([ [.1, .2, .3, .4],
                    [.4, .1, .2, .3],
                    [.3, .4, .1, .2],
                    [.2, .3, .4, .1],
                    [.0, .5, .0, .5],
                    [.1, .4, .2, .3] ]).astype('float32')
    
    sigv ,Av, yt_hotv, logpv = fn(yp,yt)
    print('\nyp\n',yp)
    print('\nyt\n',yt)
    
    print('\nyt_hot\n', yt_hotv)
    print('\nlogp\n', logpv)

    print('\nA = - yt_hot * logp \n', Av)
    
    print('\nsig should be equal to sum(A) ... BUT this is not the case !!!\n', sigv)


########################## TESTS ##############################################
print('theano:\t',theano.__version__)
print('numpy:\t',np.__version__)
print('lasagne:\t',lasagne.__version__)

test_c_sym()

`

**Comment by jc-Rosichini** [comment]
Just try with CPU and old GPU backend this works ok in both cases !! 

So this issue seems to be tied to the new cuda backend

**Comment by jc-Rosichini** [comment]
just moved from 0.9.0rc1 to 0.9.0rc2 the bug seems to be corrected 
________________________________________________________________________

Using cuDNN version 5105 on context None
Mapped name None to device cuda0: GeForce GTX 980M (0000:01:00.0)
theano:  0.9.0rc2.dev-19540d4e3064fe0dc0e1281f517bad0f355e46a2
numpy:   1.11.0
lasagne:         0.2.dev1

yp
 [[ 0.1         0.2         0.30000001  0.40000001]
 [ 0.40000001  0.1         0.2         0.30000001]
 [ 0.30000001  0.40000001  0.1         0.2       ]
 [ 0.2         0.30000001  0.40000001  0.1       ]
 [ 0.          0.5         0.          0.5       ]
 [ 0.1         0.40000001  0.2         0.30000001]]

yt
 [[1 2 3]
 [0 1 1]]

yt_hot
 [[ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]]

logp
 [[ -2.30258512  -1.60943794  -1.20397282  -0.9162907 ]
 [ -0.9162907   -2.30258512  -1.60943794  -1.20397282]
 [ -1.20397282  -0.9162907   -2.30258512  -1.60943794]
 [ -1.60943794  -1.20397282  -0.9162907   -2.30258512]
 [-20.7232666   -0.69314718 -20.7232666   -0.69314718]
 [ -2.30258512  -0.9162907   -1.60943794  -1.20397282]]

A = - yt_hot * logp
 [[ 0.          1.60943794  0.          0.        ]
 [ 0.          0.          1.60943794  0.        ]
 [ 0.          0.          0.          1.60943794]
 [ 1.60943794  0.          0.          0.        ]
 [ 0.          0.69314718  0.          0.        ]
 [ 0.          0.9162907   0.          0.        ]]

sig should be equal to sum(A) ... BUT this is not the case !!!
 **8.047189712524414** THIS IS CORRECT NOW

**Comment by lamblin** [comment]
#5623 was likely the issue, if you were using libgpuarray 6.0 (rather than 6.1) and a recent cuda driver.
I'm glad to see that it is corrected now.
