### ISSUE TITLE
*** RuntimeError: error getting worksize: CUDNN_STATUS_NOT_SUPPORTED ** 0.9.0rc2

### ISSUE THREAD

**Issue by jc-Rosichini** [Theano/Theano#5649]
**the problem:**
changing floatX = float32 to floatX = float64 triggers a runtime error 'CUDNN_STATUS_NOT_SUPPORTED'

**my config:**
theano:  0.9.0rc2.dev-674f8d5148cb8dcea446e7243e629d8f83647da5
numpy:   1.11.0
pygpu:   0.6.1
lasagne:  0.2.dev1
Using cuDNN version 5105 
GeForce GTX 980M
Windows 10 x64

**theanorc:**

[global]
#floatX = float32         # works ok
floatX = float64
base_compiledir=E:\theano_compiledirxx

#device=gpu
device=cuda0
optimizer=fast_run
#optimizer_including=cudnn
allow_gc=True

[lib]
cnmem=0.815

[cuda]
root=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

[nvcc]
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
optimizer_including=cudnn
flags=-LC:\Users\PCGP1\Anaconda3\libs 

[dnn]
library_path = C:\CUDA\v8.0\lib\x64
enabled = True

**Dump with floatX = float64 **

Compilation starts at 2017-03-03 12:26:22
optimizer: rmsprop, initial learning rate:  0.001
train compilation took 391.546 seconds
Compilation starts at 2017-03-03 12:32:58
valid compilation took 132.803 seconds
Training starts at 2017-03-03 12:35:17

Traeback (most recent call last):
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: error getting worksize: CUDNN_STATUS_NOT_SUPPORTED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 601, in <module>
    initiate_training(cf)
  File "train.py", line 567, in initiate_training
    train(cf)
  File "train.py", line 442, in train
    history, nan_occured = batch_loop(train_iter, train_fn, epoch, 'train', history, limit_randomize)
  File "train.py", line 97, in batch_loop
    loss, logT, logonmT, ypred, I, U, acc = f(X, y) # avec f  train_function or val_function
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\PCGP1\Anaconda3\lib\site-packages\theano\compile\function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: error getting worksize: CUDNN_STATUS_NOT_SUPPORTED
Apply node that caused the error: GpuDnnConvGradI{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float64', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='cross', precision='float32'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 6798
Inputs types: [GpuArrayType<None>(float64, (False, False, True, True)), GpuArrayType<None>(float64, (False, False, False, False)), GpuArrayType<None>(float64, (False, False, False, False)), <theano.gof.type.CDataType object at 0x00000190E6C70B38>, Scalar(float64), Scalar(float64)]
Inputs shapes: [(12, 160, 1, 1), (1, 12, 256, 256), (1, 160, 256, 256), 'No shapes', (), ()]
Inputs strides: [(1280, 8, 8, 8), (6291456, 524288, 2048, 8), (83886080, 524288, 2048, 8), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x0000019091CF5E70>, 1.0, 0.0]
Outputs clients: [[GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>(GpuArrayConstant{[[[[ 0.5]]]]}, GpuDnnConvGradI{algo='none', inplace=True}.0, GpuArrayConstant{[[[[ 0.5]]]]}, GpuJoin.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by jc-Rosichini** [comment]
btw. using the old gpu backend works, but maybe this is merely due to the fact that floatX is treated as float32 in this case!

**Comment by nouiz** [comment]
I think this PR try to addresse this:

https://github.com/Theano/Theano/pull/5569

The current PR isn't a good fix for it, but it provide a work around if you want to use floatX=float64 with the new back-end and cudnn for now.

**Comment by jc-Rosichini** [comment]
Thanks. I don't really need to use float64, actually the error popped up while I was trying to hunt for a nasty Nan bug (still not solved).
I just wanted to report the issue.
Rgds - Jean-Claude

**Comment by nouiz** [comment]
I'll close this as duplicate. This PR fix this problem:

https://github.com/Theano/Theano/pull/5650

thanks for the report.

**Comment by rnunziata** [comment]
Getting same error: running latest pygpu and theano:  Anyone have a fix. 

```
Using cuDNN version 5110 on context None
Mapped name None to device cuda0: GeForce GTX 1060 (0000:01:00.0)
2017-09-18 20:18:56,349 INFO Only predict function
Images 1
Traceback (most recent call last):
  File "predict.py", line 167, in <module>
    main()
  File "predict.py", line 142, in main
    predictions = pred_fn(image)
  File "/home/rjn/miniconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/rjn/miniconda2/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/rjn/miniconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: error getting worksize: CUDNN_STATUS_BAD_PARAM
Apply node that caused the error: GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), conv_mode='conv', precision='float64'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 757
Inputs types: [GpuArrayType<None>(float32, (False, False, False, False)), GpuArrayType<None>(float64, (False, False, False, False)), GpuArrayType<None>(float32, (False, False, False, False)), <theano.gof.type.CDataType object at 0x7ff9a5325d90>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(1, 3, 256, 512), (48, 3, 5, 5), (1, 48, 256, 512), 'No shapes', (), ()]
Inputs strides: [(1572864, 524288, 2048, 4), (600, 200, 40, 8), (25165824, 524288, 2048, 4), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x7ff99a6d0cc0>, 1.0, 0.0]
Outputs clients: [[GpuElemwise{Composite{(i0 * (Composite{(((i0 - i1) * i2 * i3) + i4)}(i1, i2, i3, i4, i5) + Abs(Composite{(((i0 - i1) * i2 * i3) + i4)}(i1, i2, i3, i4, i5))))}}[]<gpuarray>(GpuArrayConstant{[[[[ 0.5]]]]}, GpuDnnConv{algo='small', inplace=True}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0, InplaceGpuDimShuffle{x,0,x,x}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by nouiz** [comment]
Update cudnn to version 7. UPdate Theano to the dev version. Update libgpuarray/pygpu to the dev version.

There was many fixes/work around in those packages for that error code. If that don't fix it, open a new issue.

**Comment by ArashHosseini** [comment]
this helped me
`floatX = float64`

**Comment by nouiz** [comment]
floatX=float64 will cause very bad speed on the GPU. This isn't a good work around. Be sure to use Theano 1.0.1 (uninstall Theano many times to be sure to don't have many version installed). Also be sure to use CUDNN 7, prior version of CUDNN gave such error in some cases.

**Comment by ArashHosseini** [comment]
right, thank for response........ cudnn6.21, theano0.9.0 get........
`/usr/local/lib/python2.7/dist-packages/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.`
