### ISSUE TITLE
cuda version driver problem

### ISSUE THREAD

**Issue by apulver** [Theano/Theano#5662]
Tried to convert to the new backend. Using newest git versions of theano and libgpuarray, nvidia driver 378.13-2 

ERROR: refusing to load cuda driver library because the version is blacklisted.  Versions 373.06 and below are known to be ok.

**Comment by nouiz** [comment]
If you use the dev version of Theano, use the env variable to force the loading and bypass the check. The master of Theano support the newer driver.

We have a PR on libgpuarray that should remove this blacklist, should be merged today. So I'll close this issue now to don't forget to close it.

https://github.com/Theano/libgpuarray/pull/371

**Comment by nouiz** [comment]
The master of libgpuarray don't do the check anymore.
