### ISSUE TITLE
conv2d_transpose documentation is missing

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#5663]
The new `conv2d_transpose` is not present on the Theano website, although properly documented [in the code](https://github.com/Theano/Theano/blob/37679226209a09f9202db523bbe1e0b5fee28c6d/theano/tensor/nnet/__init__.py#L157). Might be related to #5645

**Comment by Sentient07** [comment]
Maybe this could be of use,  http://deeplearning.net/software/theano_versions/dev/tutorial/conv_arithmetic.html#transposed-convolution-arithmetic ?

**Comment by fvisin** [comment]
@Sentient07 I know it very well, but thanks! :)

Fact is, there is a new interface that is not documented in the API. I think the reason why it doesn't come up in the documentation is that `__init__` is skipped by default by Sphinx. I'd suggest to move the definition of these functions in `conv2d.py` (which IMO makes more sense, not only for documentation purposes).

**Comment by Sentient07** [comment]
It was in the developer section of the documentation page, so I pointed out the link :)
