### ISSUE TITLE
cuda launch blocking back in hints & documentation

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5669]
It seems like profiling GPU use still requires setting `CUDA_LAUNCH_BLOCKING=1` to get meaningful results?  But this suggestion no longer appears when profiling a function, and it seems to have disappeared from readthedocs (it was in the CUDA backend section)....tripped me up for a bit before I remembered!

**Comment by lamblin** [comment]
I just tried with `device=cuda,profiling=True`, on the latest development version, and got the following error:
```
Exception: You are running the Theano profiler with CUDA enabled. Theano GPU ops execution is asynchronous by default. So by default, the profile is useless. You must set the environment variable CUDA_LAUNCH_BLOCKING to 1 to tell the CUDA driver to synchronize the execution to get a meaningful profile.
```

Can you elaborate on what you did to profile a GPU function without this message getting printed? Which Theano version are you using, Theano flags, etc.?

**Comment by astooke** [comment]
Yes, sorry I didn't already.  I passed `profile=True` to a function and used `f.profile.summary()`, as described on [this page](http://deeplearning.net/software/theano_versions/0.9.X/tutorial/profiling.html) of the docs.  Neither that page of the docs nor the function produced the hint.

**Comment by lamblin** [comment]
Indeed, we only raise the exception if `config.profile` is `True`, not if `profile=True` was passed manually. This does not look like a recent change.
We could raise the exception in this case as well, or just make it a warning (like for `ignore_first_call`).

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/5686

does a warning in that case.
