### ISSUE TITLE
triu/tril in gpuarray

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5671]
We have the CPU op, but not the gpu one. Do it ourself with c code as the gpu code seem trivial.

**Comment by tfjgeorge** [comment]
With @abergeron we were talking about putting it in pygpu instead ?

In any case there is a base version [here](https://github.com/tfjgeorge/Theano/blob/a8964a7713ea910d09591a97297a878baa9f6014/theano/gpuarray/linalg.py#L66) which I was planing to put in pygpu (with more checks for when the argument matrix is c_contiguous). But I can put it in Theano directly.

**Comment by notoraptor** [comment]
Yes, put it in pygpu, not in Theano.

**Comment by lamblin** [comment]
Done in https://github.com/Theano/libgpuarray/pull/386
