### ISSUE TITLE
Same Enviroment different results

### ISSUE THREAD

**Issue by jmaronas** [Theano/Theano#5677]
Hello.

I have experimented an issue and try to find the solution in some forums but get no results. Basically I have three GPU 1080 in three different machines (two of them EXACTLY the same). The point is that after I install the same theano version, numpy version... And the same g++ compiler if I compile a simple expression like matrix multiplication in one GPU (from the same computers) the result is different from the other. However on the GPUs of the same computer I get exactly the same result.

My matrix are initialized randomly (previous seed fixing). For example things like generating random number using the GPU yield to same results on three GPUs. Problems seems to be in dot products, convolutions... cuDNN library is disabled. I have checked a little how theano works. Maybe has to do with differences in the cuBlas library depending on the machine? I understand cuBlas could change (similar as BLAS library changes depending on CPU arquitecture) if GPU model change or cuda version change, but that is fix. 

Maybe a theano incorporate a theano flag that chooses between using cuBlas matrix product or home made matrix product?

Thanks

**Comment by nouiz** [comment]
We always use cublas for dot product on GPU. Which Theano version do you
use? What tho flags do you use? If you use the new backend, but an old
version,. An old thing we changed could affect that.

What is the code? Do you do something like a_tendor[avector] and take the
gradient of that?

**Comment by jmaronas** [comment]
I am using the stable version of blocks which I install in a virtual enviroment on both ubuntu 16. I think the theano version it uses is the last stable one
pip install git+git://github.com/mila-udem/blocks.git@stable \
  -r https://raw.githubusercontent.com/mila-udem/blocks/stable/requirements.txt

This is my .theanorc:

[global]
device =gpu0
floatX = float32
exception_verbosity=high
force_device=True
[dnn]
enabled=False
[lib]
cnmem=0.9

With this simple code I experience this difference:

   import numpy

    import theano

    a = numpy.random.RandomState(seed=1)

    A = a.rand(10,100).astype(theano.config.floatX)

    B = a.rand(100,10).astype(theano.config.floatX)

    X,Y = theano.tensor.matrices('XY')

    mf = theano.function([X,Y],X.dot(Y))

    print m(A,B)

For example on one machine I get (first row):

[[ 2466.199**46289**  2495.580**32227**  2482.59667969 ...,  2480.11181641
   2462.97924805  2480.32177734]

In other machine I get:

[[ 2466.199**21875**  2495.580**56641**  2482.59667969 ...,  2480.11157227
   2462.97973633  2480.32226562]


I have marked some difference in bold. I know the difference is very little but the problem is that I am using the GPUS for hyperparameter searching on a heavy task and I need the three to perform exactly the same. If a train a model I can have (with the exact model) difference on the validation error....

**Comment by nouiz** [comment]
There is this issue that talk about having more deterministic result on GPU:

https://github.com/Theano/Theano/issues/4819

Mostly, this is a thread off between speed and deterministic.

If that don't allow you to be deterministic, tell us.

**Comment by lamblin** [comment]
Different versions of CUDA could do that for sure. Maybe different versions of the driver as well.

**Comment by jmaronas** [comment]
I think drivers are not the problem because the three machines have different drivers. Cuda version is the same. 

I have checked #4189 and end up making the changes in #3029 and nothing changes. I am getting different results. What I basically do is adding theano.config.deterministic to take value True and False, and when True get into GpuAdvancedIncSubtensor1. Actually the code I posted does not seem to get into that functions because I put some printings on both if-else conditions an nothing goes to stdout. 

I will make some code directly on cuda using cuBlas matrix product and check if it is related to cuda and gpu or to theano. I read in those thread you intended to make some modifications to make theano deterministic. Is that getting further?

**Comment by jmaronas** [comment]
I am checking how cuBlas works and found this this http://docs.nvidia.com/cuda/cublas/#axzz4avB2KLxe , take a look at **2.1.4. Results reproducibility** . It is said that with same GPU architecture (my case) and with same toolkit version (also my case), results should be reproducible unless theano sets cublasSetAtomicsMode(). Maybe this is the reason.

**Comment by lamblin** [comment]
Theano does not set `cublasSetAtomicsMode()` in the old back-end. In fact, the cublas functions we use would not even use atomics if we did, and it made the execution slower in the new back-end when we tried, so it should be disabled in the new back-end as well now.
Having an option for deterministic (but slower) execution is still in our plans, but we do not have a timeline yet.

**Comment by jmaronas** [comment]
Hello.

I think I have good notices. I have written some code directly on cuda using the cuBlas library, disabling the atomic mode. I have perform the same matrix operation (without the same numbers), and surprisingly I got in one machine:

821351.187500(float CPU sum)
821353.260980(double CPU sum)

and in the other:

821353.250000 (float CPU sum)
821353.253652 (double CPU sum)

So this means as I expected that the cuBlas library changes depending also on computer architecture, not only on GPU architecture. I have read that the normal blas and lapack library has some hardware specific code that executes depending on the HW arquitecture. I thought that, because cuBlas follows the same structure as Blas, it will have some code depending on the GPU architecture but I did not think the CPU arquitecture could also change the result... Well the good point is that knowing this you could fix it whenever you decide to make theano deterministic. 
 
I let you here the my code. Just run:

nvcc matrixProductCublas.cu -o exe -lcudart -lcublas

And for execution it has 6 parameters:

./exe 1000 10000 1000 r 1 0

Assuming we perform C=A*B, first two arguments are rows and columns from matrix A, third argument is columns from matrix B, the fourth element is an "i" for making and integer matrix product or other letter for making float random matrix product. The last two numbers are the random seed(first one) and the last one takes value 1 or 0. 1 prints the three matrix and the sum of all the elements of the C matrix and 0 prints only the sum of the elements in C.  Run only ./exe will print a little help.
![matrixproductcublas](https://cloud.githubusercontent.com/assets/15247250/23907702/42608ffa-08d2-11e7-898a-e5cc92014d8c.png)

I have to check this code running in the machine that is similar to one of these but I have some code running and have to wait. However, if i run:

./exe 10 100 10 r 1 0

I get same result on both: 

-29.708994

The accumulation of all the values of C matrix is done in the CPU casting all the values to double  (in the first results I also show the sum in float). I do not think the difference is related to this sum. I have checked the matrix C via stdout and see that the last element in both machines is different.

 Change the file extension from .png to .cu because github do not let me upload files with .cu extension.

**Comment by lamblin** [comment]
In this particular case, could it be that the rng, even seeded the same way, behaves differently on different systems? Did you check the original inputs?

**Comment by jmaronas** [comment]
Yes, the inputs are the same

**Comment by nouiz** [comment]
The problem was with the old GPU back-end, so closing.
