### ISSUE TITLE
Initial support for cudnn v6?

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#5679]
we can download cudnn v6 rc from here
http://blog.yannisassael.com/2017/02/cudnn-v6-0-rc/

**Comment by lamblin** [comment]
For now, all tests seem to pass in the new back-end with 0.9rc3 and cudnn v6 rc0.
We are not going to support it in the old back-end.

**Comment by nouiz** [comment]
Can you confirm it work for you and if so close the issue?

thanks

**Comment by nouiz** [comment]
no news and it compiled and passed all Theano tests here, so I'll close this issue. If you try it later and have problems, open a new issue.

thanks
