### ISSUE TITLE
ImportError: ('The following error happened while compiling the node', Corr3dMM{valid, (1, 1, 1), (1, 1, 1)}

### ISSUE THREAD

**Issue by markofan** [Theano/Theano#5681]
I am using keras to write a cnn. when the code goes to model.fit, the error comes out:
ImportError: ('The following error happened while compiling the node', Corr3dMM{valid, (1, 1, 1), (1, 1, 1)}(convolution3d_input_6, Subtensor{::, ::, ::int64, ::int64, ::int64}.0), '\n', '/home/marko/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/tmpGR6M3e/28dc91d1f00bb564d0b33a57db1b2b75.so: undefined symbol: openblas_get_num_threads', '[Corr3dMM{valid, (1, 1, 1), (1, 1, 1)}(convolution3d_input_6, <TensorType(float32, 5D)>)]')

**Comment by nouiz** [comment]
You have a problem with your blas installation. How did you install
openblas? On which OS are you? Try to reinstall it and make sure it is
available completly in your OS.

**Comment by markofan** [comment]
Thank you! There is something wrong with my theano, I have restalled it, and everything is OK!

**Comment by GloriaZyx** [comment]
I encountered this problem ,too, please tell me what's wrong with your theano, and how did you solve it,thank you very much!
