### ISSUE TITLE
Perform tensor.fft using GPU

### ISSUE THREAD

**Issue by zzd1992** [Theano/Theano#5689]
When I perform tensor.fft, it looks slow.
I guess tensor.fft is performed based on CPU.
So how can I perform tensor.fft using GPU?
Or is there any similar functions to perform fft in theano( I need the gradients backthrough it) ?

**Comment by nouiz** [comment]
In the new back-end there is fft op under theano.gpuarray.fft.*

http://deeplearning.net/software/theano/library/gpuarray/fft.html

So it should be working, but you need to manually use it for now and you need to use the new gpu back-end.

**Comment by zzd1992** [comment]
Thanks. It is exactly what I want.
