### ISSUE TITLE
Regarding theano implementation

### ISSUE THREAD

**Issue by aartikas** [Theano/Theano#5691]
Hi,
I am working with Anacoda,Python 2.7 and windows 8
While running a CNN,following error pops up:
C:\Users\Abhishek\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.12-64\tmpkxtmoz\mod.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include <Python.h>

I have tried tolook up:
http://stackoverflow.com/questions/29995397/compilation-failure-when-running-theano-windows-8-1-64-bit-with-anaconda-pytho

but could reach a solution.Even though this issue is reported before but I failed to reach to a solution

Kindly help!

**Comment by lamblin** [comment]
You seem to have a 32-bit version of gcc with a 64-bit version of Python, or some kind of platform mismatch.
