### ISSUE TITLE
Theano import error

### ISSUE THREAD

**Issue by Zola15** [Theano/Theano#5699]
Hi,

I am new to Theano. I installed it using: sudo pip install scikit-neuralnetwork.
The installation process went ok, but when I try to import theano I got an error:

Problem occurred during compilation with the command line below:
/opt/moose/clang_3.5.1/bin/clang++ -dynamiclib -g -march=penryn -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/Users/zola/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/zola/anaconda/include/python2.7 -I/Users/zola/anaconda/lib/python2.7/site-packages/theano/gof -fvisibility=hidden -o /Users/zola/.theano/compiledir_Darwin-15.6.0-x86_64-i386-64bit-i386-2.7.13-64/lazylinker_ext/lazylinker_ext.so /Users/zola/.theano/compiledir_Darwin-15.6.0-x86_64-i386-64bit-i386-2.7.13-64/lazylinker_ext/mod.cpp -L/Users/zola/anaconda/lib

Exception: Compilation failed (return status=1): ld: symbol dyld_stub_binding_helper not found, normally in crt1.o/dylib1.o/bundle1.o for architecture x86_64. clang: error: linker command failed with exit code 1 (use -v to see invocation). 

I use Xcode 8.2.1. and anaconda2(Python 2.7). It is on MacBook Pro (El Capitan - OS).

It looks that lazylinker_ext.so is missing. 

Please help mee to start my project.

Many thanks,
Zola

**Comment by nouiz** [comment]
I'm not a mac expect, maybe other people can give a better answer, but check the issue, installation instruction on mac and use the specified environment. That environment work well for many people or google the specific error: "ld: symbol dyld_stub_binding_helper not found, " It could point you to a fix.

**Comment by Sentient07** [comment]
Hi, Xccode 8.2 isn't supported as it uses a higher version of GCC. You have to download and install Xcode 7.3 and Clang 7.3. You can refer to posts made by me on `theano-dev` and `theano-users` on installation instructions that addresses few requirements for using theano on a mac.

**Comment by Sentient07** [comment]
@nouiz is there a way by which we can tag/sort posts on google group? If possible, I suggest we could ask the people to try those steps and then report the errors if they still exist.

**Comment by Zola15** [comment]
@Sentient07 Thank you very much! I am going to try with Xcode 7.3.

**Comment by nouiz** [comment]
There is no way to my knowledge on how to tag posts on google group. This
is a mailing list, not an issue tracker and I never saw a mailing list that
can tag posts.

Fred

**Comment by Sentient07** [comment]
Okay, in that case, can I add the specifications to `Wiki` section of the github, like how there is Windows installation?

**Comment by nouiz** [comment]
We have in the doc a section on mac:
http://deeplearning.net/software/theano_versions/dev/install_macos.html

Instead of doing partial duplication, I think it would be better to update
that doc version.

Fred

**Comment by Sentient07** [comment]
Okay, I will update there. Also, this forum supports tagging of posts. http://www.discourse.org

**Comment by leocnj** [comment]
@Sentient07 Thanks for letting us know that ONLY clang 7.3 is supported by theano so far. After upgrading my clang from 7.3 to new 8.x with Mac OS 10.12, I never can use GPU in theano (on both 0.8.2 and 0.9).

**Comment by Sentient07** [comment]
@leocnj thanks for informing me. It seems like it was 2 months from the date that i wrote the post on theano-dev, Nvidia has added support to LLVM 8.0. [Link](https://devtalk.nvidia.com/default/topic/970835/cuda-programming-and-performance/cuda-8-on-sierra/post/5032995/#5032995) Time to update the post. For quick reference for someone who visits this thread in the future, here is a table that specifies the [requirement](http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html#axzz4MhqEjPgP)
