### ISSUE TITLE
Python3.6 theano error in gpu device

### ISSUE THREAD

**Issue by vladimircape** [Theano/Theano#5700]
I have Python3.6 and install theano from github
this is my 
.theanorc
`[global]
floatX = float32
device = gpu
base_compiledir = C:\TheanoOperational
#cxx = C:\msys64\mingw64\bin\g++.exe

[gcc]
cxxflags = -D_hypot=hypot

[nvcc]
flags = -LD:\Programms\Anaconda36\libs
fastmath = True
compiler_bindir = D:\Programms\VisualStudio\Vc\bin\cl.exe

[cuda]
root = D:\Programms\cuda\development\bin

#[blas]
#ldflags=-LC:\\openblas -lopenblas`

when try to import theano got erorrs
`===============================
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 1, 'for cmd', 'nvcc -shared -O3 -LD:\\Programms\\Anaconda36\\libs -use_fast_math --compiler-bindir D:\\Programms\\VisualStudio\\Vc\\bin\\cl.exe -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=m18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -I"D:\\Programms\\Anaconda36\\lib\\site-packages\\theano\\sandbox\\cuda" -I"D:\\Programms\\Anaconda36\\lib\\site-packages\\numpy\\core\\include" -I"D:\\Programms\\Anaconda36\\include" -I"D:\\Programms\\Anaconda36\\lib\\site-packages\\theano\\gof" -L"D:\\Programms\\Anaconda36\\libs" -L"D:\\Programms\\Anaconda36" -o C:\\TheanoOperational\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-3.6.0-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -lcublas -lpython36 -lcudart')
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

['nvcc', '-shared', '-O3', '-LD:\\Programms\\Anaconda36\\libs', '-use_fast_math', '--compiler-bindir', 'D:\\Programms\\VisualStudio\\Vc\\bin\\cl.exe', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=m18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-I"D:\\Programms\\Anaconda36\\lib\\site-packages\\theano\\sandbox\\cuda"', '-I"D:\\Programms\\Anaconda36\\lib\\site-packages\\numpy\\core\\include"', '-I"D:\\Programms\\Anaconda36\\include"', '-I"D:\\Programms\\Anaconda36\\lib\\site-packages\\theano\\gof"', '-L"D:\\Programms\\Anaconda36\\libs"', '-L"D:\\Programms\\Anaconda36"', '-o', 'C:\\TheanoOperational\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_69_Stepping_1_GenuineIntel-3.6.0-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-lcublas', '-lpython36', '-lcudart']`

I am very confused, because i also have tensorflow with GPU support and everythin works correct

**Comment by nouiz** [comment]
We are going to a new back-end that should be simpler to install. Follow the url in the error to see how to use it. To install it remove Theano and install it via conda:

conda install -c rdonnelly theano

**Comment by nouiz** [comment]
Also, there seem to have problems with Python 3.6. Use Python 2.7 or 3.5.

**Comment by vladimircape** [comment]
I also tried Python2.7 and 3.5. Very strange behaviour previously on python 2.7 with mingw BLAS version was working, right now, after i install Visual Studio i didn't see that i use BLAS(according tests)

**Comment by nouiz** [comment]
Try the new back-end. Installing the old back-end on windows is very complicated.

**Comment by stevenxxiu** [comment]
I've been using theano and python 3.6 on windows for a while, seems to work fine so far.

**Comment by nouiz** [comment]
Which version of numpy do you have with the build version? How did you
install it? I saw many report of memory leak of numpy on python 3.6. But I
don't know the details.

thanks.

**Comment by lamblin** [comment]
The memory leaks was likely the one reported in #5810, which has been fixed.
It was not directly linked to python 3.6, but rather to an installation where we could not link directly with a blas (for instance the one provided by Anaconda), and were attempting to use numpy's one through the C API.

**Comment by nouiz** [comment]
So I think we can close this issue as someone wrote it was going well for him.
