### ISSUE TITLE
Optimization failure due to: local_gpua_advanced_incsubtensor

### ISSUE THREAD

**Issue by fsalmasri** [Theano/Theano#5703]
> ERROR (theano.gof.opt): Optimization failure due to: local_gpua_advanced_incsubtensor
> ERROR (theano.gof.opt): node: AdvancedIncSubtensor1{no_inplace,set}(HostFromGpu(gpuarray).0, TensorConstant{0}, Subtensor{int64}.0)
> TypeError: InplaceDimShuffle{0}.0
> 

I'm having this message when I'm using indexing and set_subtensor 

idxs = (self.y_pred >= 0.5).nonzero()
        self.y_pred = T.set_subtensor(self.y_pred[idxs], 1)
        idxs = (self.y_pred < 0.5).nonzero()
        self.y_pred = T.set_subtensor(self.y_pred[idxs], 0)
```

**Comment by nouiz** [comment]
Can you give the full error message? Be sure to update to Theano dev version, there was related fix in the master recently I think.

To be able to reproduce this, what is self.y_pred and idxs?

**Comment by fsalmasri** [comment]
I'm using theano 0.9 getched from the rep.  
regarding self.y_pred is 1D vector output from sigmoid function.  idxs just defined here to find the indices for greater and smaller than the threshold and then substituting to 0 or 1 by using set_subtensor.

**Comment by lamblin** [comment]
It is hard to investigate without the full error message to investigate, and ideally a minimal reproducing case.
#5747 may be the solution.
