### ISSUE TITLE
More options for gpuarray.sched

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#5706]
The `gpuarray.sched` configuration option controls the device synchronization mode set with `cudaSetDeviceFlags`. There are three modes that are interesting, but only two of them are available in Theano:
* `cudaDeviceScheduleSpin`: This is the default. Whenever the host is waiting for the device, the CPU enters a busy loop, continuously polling the device whether it's ready, consuming 100% CPU. This is currently available as `"default"` and `"single"`.
* `cudaDeviceScheduleYield`: When waiting for the device, the CPU enters a loop that alternates between polling the device and issuing a [`sched_yield`](https://linux.die.net/man/2/sched_yield), so the OS scheduler can use the core for another thread or process if there is any. If there isn't, this effectively consumes 100% CPU as well. This is currently available as `"multi"`.
* `cudaDeviceScheduleBlockingSync`: When waiting for the device, the CPU thread blocks and waits for an event set by the driver (I assume), consuming 0% CPU. This is the greenest option, and it's what I'm using with the old backend currently (but I never got around submitting a PR for this). There is a slight performance hit (about 1% for an experiment I timed), but it's more elegant than a busy loop and it saves a lot of power. It's not available as a `gpuarray.sched` option for now.

I'd be up to implement this, but I'm unsure about the naming. If `single` and `multi` weren't there already, I'd use `spin`, `yield` and `block`. If we just want to add an extra option to fit within the current names and not create a ton of aliases (`default`=`single`=`spin`, `multi`=`yield`, ...), what about `gpuarray.sched=green` or `gpuarray.sched=eco`? Is that acceptable or too much of a marketing term? It sort of fits what you'd use it for -- reducing power usage accepting a slight performance hit.

**Comment by nouiz** [comment]
What about block? It isn't used and tell what it does.

I don't like too much green or eco, but block isn't much better. I don't think any of them is much clearer for people without much computer science knowledge. Another option: wait_event

**Comment by f0k** [comment]
> What about block? It isn't used and tell what it does.

I think it doesn't fit well with `single` and `multi`. It sounds very mysterious.

> I don't like too much green or eco, but block isn't much better. I don't think any of them is much clearer for people without much computer science knowledge.

I thought `eco` might entice people to look closer when scrolling through the theano configuration documentation and just try it out, with or without computer science knowledge. This would lower Theano's overall carbon footprint. (It literally drives CPU usage from 100% to 2-3% for every GPU process you're running. I understand why nvidia made the busy loop the default, but it's a bit insane.)

> Another option: wait_event

Okay, that could work. Or just `wait`. And then explain that the other options actively poll the GPU instead of passively waiting. (Although I'd still like the `eco` mode...) Feel free to assign me to this.

**Comment by abergeron** [comment]
I would just change the definition of of multi to mean BLOCKING_SYNC.  YIELD is not that useful and has a huge performance impact.

**Comment by f0k** [comment]
> I would just change the definition of of multi to mean BLOCKING_SYNC.

That'd be much easier (just a single line change in pygpu, and updating the documentation). But it really doesn't fit the name `multi`, since it's just as useful for single-threaded processes... we could add aliases `poll` and `wait` then.

> YIELD is not that useful and has a huge performance impact

It does? In my experiments, when not all CPU cores are busy, YIELD was virtually the same as SPIN. I'd have thought YIELD is a tradeoff between SPIN and BLOCKING_SYNC -- it polls as frequently as other threads let it, which I assumed would still give less delay than waiting on an event (although I don't know at what queue position the scheduler puts a thread when it's unblocked?). Did you find YIELD to be slower than BLOCKING_SYNC?
