### ISSUE TITLE
Move MRG gpuarray methods and tests inside theano/gpuarray/

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5729]
Now that we do not have to do ugly hacks for the old back-end.

**Comment by morrme** [comment]
@lamblin this looks like it has already been done, unless I've missed something.

**Comment by nouiz** [comment]
I see them in theano/gpuarray/tests/test_rng_mrg.py and test_multinomial.py, so I'll close this issue. thanks for pointing that.
