### ISSUE TITLE
ability to change libgpuarray preallocate value after importing theano to CPU

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5731]
Hi,

  It would be very helpful to be able to change the `gpuarray.preallocate` setting in python, after `import theano` (to CPU only), and before using `theano.gpuarray.use()`.  

Not sure whether preferable to make that config value editable or to allow `gpuarray.use()` to take an optional argument, I think either would work equally.

Thanks,
Adam

**Comment by astooke** [comment]
OK that was really simple, just change to `allow_override=True` for `gpuarray.preallocate` in `theano.configdefaults`.   I suggest making this standard unless there is some reason not to?

**Comment by lamblin** [comment]
The main reason I have not to do that is that it would build the expectation that the allocated memory size can be changed _at any point_ during the execution.
Moreover, it is only useful when using `device=cpu` but manually calling `gpuarray.use()`, and we do not have a way of allowing changes in the configuration options only until `gpuarray.use()` is called.

I would actually support `preallocate` being an argument to `use` and `init_dev`, and defaulting to `config.gpuarray.preallocate` if it is not provided. It would make it easier to pre-allocate different amounts of memory on different devices as well.

Finally, most of what `gpuarray.preallocate` is doing is calling `pygpu.empty()` to literally pre-allocate a block of the right size, which is something you could do just after calling `gpuarray.use()` as well.

**Comment by lamblin** [comment]
#5735 makes it possible to specify a value for `preallocate` when calling `gpuarray.use()`.

**Comment by astooke** [comment]
Great! Thank you!
