### ISSUE TITLE
Add lifter optimizations for AllocDiag and ExtractDiag

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5748]
There does not seem to be optimizations these Ops to the new back-end (towards GpuAllocDiag and GpuExtractDiag).
In fact, the tests call `GpuAllocDiag(...)` and `GpuExtractDiag(...)` instead of letting the optimization transfer it, and then check, so the tests should be upgraded as well.

**Comment by nouiz** [comment]
is done. so closing.
