### ISSUE TITLE
AssertionError, BUG IN FGRAPH.REPLACE OR A LISTENER (theano.gof.fg.CachedConstantError)

### ISSUE THREAD

**Issue by fvisin** [Theano/Theano#5753]
When I run my code with `optimizer=fast_compile` I get this `AssertionError` and a bunch of `BUG IN FGRAPH.REPLACE OR A LISTENER` messages. This is really annoying as I am trying to locate a shape error in a huge and messy code :)

Here is a gist with the full log:
https://gist.github.com/fvisin/beff6c95918b18713f03a17f58c8353b

**Comment by lamblin** [comment]
I think we would need the code to reproduce that... I cannot think of a particular reason why this would happen.
Are you using `compute_test_values`? Do you have any scan or OpFromGraph?

**Comment by fvisin** [comment]
Thank you for your answer!

I am not using `compute_test_values`, I definitely have multiple `scan` and I am afraid I have no idea if I have `OpFromGraph`! The code is the one @nouiz was looking into last week. 

I will give you access to the repo as well and send you a parameter file that you can use with the latest code on master.

**Comment by nouiz** [comment]
You have blas.ldflags 2 times. This isn't useful. You can/should remove now
optimizer_excluding=local_softmax_dnn_grad

This is fixed.

**Comment by nouiz** [comment]
Quick reply, I'm able to reproduce it and I think I got a fix.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/5760
