### ISSUE TITLE
Porting cuSOLVER linear system solver - help needed. 

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5754]
I'm trying to put the cuSOLVER linear system solver routine under a theano op #3332 . However, although there are a few examples of how to do custom ops, the documentation is significantly sparse on what many things are and where my mistake is coming from. As such I'm posting below my first attempt and list all my questions to which I did not find answers online. The code is based on the `fft` wrappers around `skcuda` as the implementation uses `skcuda` as well.
The code for this is in this [gist](https://gist.github.com/botev/156eb765b497c1120f11b25dfe973846)

Now, at the moment, however, the solver provides wrong results. Note that the pure code in `skcuda_cuSOLVER.py` works so there is something wrong of managing things inside the `Theano` op. Possible reasons why this could be happening are:

1. The `skcuda` require transposing the numpy arrays and transposing back because numpy stores row major, and cuda uses column major. It is unclear what is the situation with Theano and how to make that work. 

2. The fact that the `solve` routine is inplace, means that I had to copy the values of `A` and `b` such that they are not modified. However, I'm not sure if the copying is done correctly, as I do not understand how that should be done in `Theano`.

Some extra questions:

1. Why is the syncing of the inputs done? When should it be done for other situations?

2. If we want to perform the op with `overwrite_a` or `overwrite_b` how can we tell `Theano` that the operations are going to be in_place? There was no documentation of what is the `storage_map` and how it works, what are its purposes. 

3. If we want the operator to be automatically promoted for matrix inversion for when the device selected is a GPU, what is the correct way of doing that? Any pointers?

In general, any help of making the op works are most welcome and I'm happy to experiment with various things, but at the stage where it executes, but produces wrong results I do need a few questions answered. 

Another issue I'm having is that there is 0 docs on `pygpu`. How do we create a `pygpu` context or anything else so that we can test things in isolation.?

**Comment by nouiz** [comment]
Some notes, your inputs won't be numpy ndarray, but a gpu version of it. It isn't 100% the same but very close.

You don't know in advance if the inputs will be c order, fortran order or have an arbitrary strides. Probably skcuda expect inputs in fortran order. This add complication to the code for sure, there is example of this in the file gpuarray/linalg.py from memory.

Before continuing, I checked your gist rapidly and found that in gpuarray/linalg.py, there is the class GpuCusolverSolve. Is it what you want? Otherwise, it could be a better starting point the one that wrap cufft, as it seem pretty close to what you want to do.

**Comment by nouiz** [comment]
There is also those commits that wrap more skcuda stuff that could help you:

https://github.com/Theano/Theano/compare/master...tfjgeorge:gpu_cholesky

**Comment by lamblin** [comment]
OK, let me try to provide some information.

> I'm trying to put the cuSOLVER linear system solver routine under a theano op #3332 .

First of all, there is already an Op wrapping some cuSOLVER routines in [`theano/gpuarray/linalg.py`](https://github.com/Theano/Theano/blob/824cb36921ccb7476dd1f8dea8dba8ac74d55afe/theano/gpuarray/linalg.py#L55).

> Now, at the moment, however, the solver provides wrong results. Note that the pure code in `skcuda_cuSOLVER.py` works so there is something wrong of managing things inside the `Theano` op. Possible reasons why this could be happening are:
> 
> 1. The `skcuda` require transposing the numpy arrays and transposing back because numpy stores row major, and cuda uses column major. It is unclear what is the situation with Theano and how to make that work.

Theano supports arbitrary strides. When the layout is not the one expected by cuSOLVER (and if there is no easy way of working around it by passing a `transpose` flag or something like that), the array has to be copied as contiguous in the expected way (say, F-contiguous for column major). A copy could be needed anyway if the operation is destructive (see https://github.com/Theano/Theano/blob/824cb36921ccb7476dd1f8dea8dba8ac74d55afe/theano/gpuarray/linalg.py#L148 for instance).

> 2. The fact that the `solve` routine is inplace, means that I had to copy the values of `A` and `b` such that they are not modified. However, I'm not sure if the copying is done correctly, as I do not understand how that should be done in `Theano`.

The last link above should help.

> 1. Why is the syncing of the inputs done? When should it be done for other situations?

On GPU, scheduling execution of kernels is asynchronous, which means that when the function call returns, all that has been done is the scheduling of the kernel to be executed, the computation may not be finished (or even started), and the output memory space may not hold the computed value yet. Synchronizing waits for all previous computations writing to that memory to finish.

> 2. If we want to perform the op with `overwrite_a` or `overwrite_b` how can we tell `Theano` that the operations are going to be in_place? There was no documentation of what is the `storage_map` and how it works, what are its purposes. 

`destroy_map` is the property you want, it maps output indices to the input index it could overwrite.
The way it is usually done is that the Op is not inplace by default, and then an optimization tries to replace it with a destructive version if it is possible (it is not always possible, for instance if another operation in the graph is destructive on it).

> 3. If we want the operator to be automatically promoted for matrix inversion for when the device selected is a GPU, what is the correct way of doing that? Any pointers?

Usually, there are two Ops: one on CPU, one on GPU. An optimization replaces the former by the latter.

> In general, any help of making the op works are most welcome and I'm happy to experiment with various things, but at the stage where it executes, but produces wrong results I do need a few questions answered.

No problem. If you find some of our explanations useful and would like for them to be in the documentation (at the place where you would expected), a PR updating the doc would be more than welcome.

Thanks!

**Comment by botev** [comment]
Ok, so I think that probably the Op already existing is what I want, although I managed to make mine work as well. However, I think its notable to put in the docs that the `slinalg.solve` now works both on the cpu and the gpu, as this was not the case before.

**Comment by botev** [comment]
Actually, could you point me out to where is the optimization that exchanges the `Solve` cpu op to a gpu? Because currently, if the CPU op has `A_structure` different than general, that does not get passed to the GPU op. Additionally, I would want to perform the Solve inplace. However, again if `overwrite_A` and `overwirte_b` in the cpu op are set, the GPU op is not inplace. Additionally, trying to call the gpu op explicitly with inplace raises:
```
TypeError: ('Graph must not contain inplace operations', GpuCusolverSolve{A_structure='symmetric', trans='N', inplace=True}(GpuContiguous.0, GpuContiguous.0), <theano.gpuarray.linalg.GpuCusolverSolve object at 0x7f42956b96d8>)
```
Or is the inplace going to be automatically inserted by Theano?

**Comment by lamblin** [comment]
The optimization inserting the GPU Op is [here](https://github.com/Theano/Theano/blob/824cb36921ccb7476dd1f8dea8dba8ac74d55afe/theano/gpuarray/opt.py#L1940-L1947).
Indeed, it does not seem to forward `A_structure`, which is unfortunate, or `trans`, which is more worrying (could lead to wrong results).

Regarding inplace, it is tricky to try to set those flags manually. Usually, they are inserted automatically by Theano, after the transfer to GPU. In that case, however, these optimizations do not seem to exist.
The better solution would be to add them in `theano/gpuarray/opt.py`. These one are going to be slightly trickier than the other ones in that files, since `tensor.slinalg.Solve` has arguments `overwrite_A` and `overwrite_b` instead of just `inplace`.
If you know that this is safe for your specific case to work inplace on A and set it directly in `GpuCusolverSolve(...)`, then you could try passing `accept_inplace=True` to `theano.function()`. This is experimental and could make the graph optimization process slower.

**Comment by botev** [comment]
> Indeed, it does not seem to forward A_structure, which is unfortunate, or trans, which is more worrying (could lead to wrong results).
What do you mean about `trans`? It exists only for the GPU op, so unless someone is hoping to get the optimization in the opposite direction(GPU->CPU) it should not be a problem.

As for the second, in fact I think that the GpuSolve should be modified to have as the CPU one both `overwrite_A` and `overwrite_b`, e.g in GpuSolve lines 147-152 one can have separate flags for both `A` and `b`:
```
       # We copy A and b as cusolver operates inplace
        b = pygpu.array(b, copy=True, order='F')
        if not self.inplace:
            A = pygpu.array(A, copy=True)
        A_ptr = A.gpudata
        b_ptr = b.gpudata
```
Potentially, these can be passed in by the CPU op, but the question is is `Theano` going to optimize automatically the CPU op to do inplace stuff in the first place.

**Comment by botev** [comment]
So, actually for this Op I do not understand the specification of the `destroy_map`. E.g. for the GPU Solve we have (for solving `Ax=b`)
```
if self.inplace:
    self.destroy_map = {0: [0, 1]}
```
Now, as I understand, this means that the output `x` can overwrite either `A` or `b`. However, in the implementation, first `b` is always copied, second if we assume that `in_place=True` than the only think we will get is that the `LU` decomposition on `A` is going to be in place, but the output `x` will in fact never overwrite either `A` or `b`? The second hard bit is that by `overwrite` here we actually have single output, but possibility for more than 1 overwrite (the `LU` of `A`), however one of them is not related to the output, but more like the internals of the op. How can this be achieved?

**Comment by pstjohn** [comment]
As a feature request it would be awesome if this could also get a `grad` method, the current gpu_solve method seems to be lacking one.

**Comment by nouiz** [comment]
Call theano.tensor.slinalg.solve() instead. It should be moved to the GPU automatically and have a grad method.

**Comment by MahmoudIsmail88** [comment]
Hello all is there any updates on performing matrix inverse operation using the GPU ?

**Comment by lamblin** [comment]
Fixed by #5895

**Comment by nouiz** [comment]
For matrix inverse, it was added by using magma that you must install and use the Theano flag magma.enabled=True

https://github.com/Theano/Theano/pull/5778

**Comment by nouiz** [comment]
matrix inverse is now implemented on GPU. But for this, you need to install magma and use the Theano flag:
magma.enabled=True

gpu solve is implemented via cusolve, so I'll close this issue.
