### ISSUE TITLE
Remove theano/compat/six.py

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5761]
Theano is not using it any more, and Pylearn2 (which was) is not maintained.

**Comment by morrme** [comment]
What about the files that reference it? 

Ex. https://github.com/Theano/Theano/blob/a406f243a9d576907fc25d3a6b349f7b16c1d139/theano/updates.py#L7

**Comment by morrme** [comment]
@nouiz @lamblin OK, it is done.
