### ISSUE TITLE
fatal error: cudnn.h: No such file or directory

### ISSUE THREAD

**Issue by nikhiljha** [Theano/Theano#5768]
Doing `import theano` from conda 2.7 (Windows) gives this:

```
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
c:\users\nikhil\appdata\local\temp\try_flags_ef1xq6.c:4:19: fatal error: cudnn.h: No such file or directory.
Compilation terminated.
```

I installed CUDA 8.0 with the installer from Nvidia's website and then copied cudnn into the respective folders at `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0`. Cudnn.h is in the includes folder at that location, but it can't find it.

**Comment by notoraptor** [comment]
Hello ! Could you show us the content of your `.theanorc` file ?

Or what theano flags do you use ?

**Comment by mike1808** [comment]
I installed `libgpuarray` and `Theano` from the source and got the same issue on Ubuntu 16.04.

My `.theanorc` file is

```rc
[global]
floatX = float32
device=cuda
optimizer=fast_run

[blas]
ldflags = -L/usr/local/lib -lopenblas

[nvcc]
fastmath = True
```

**Comment by notoraptor** [comment]
Could you add the following to your .theanorc and retry (on Windows) ?

```
[dnn]

include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
```

**Comment by nikhiljha** [comment]
My new .theanorc is...

```
[global]
device = cuda

[dnn]
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
```

and it said it couldn't find cl.exe, which looks like the VS compiler after a quick google search. After saying that it crashes.

Adding it to PATH fixes the "couldn't find" error, but the crash is still there (as in, windows shuts down python and asks if I want to debug or close program.).

**Comment by notoraptor** [comment]
Maybe you are experiencing same issues as here on Windows: https://github.com/Theano/libgpuarray/issues/264#issuecomment-289185531

Python crashes come sometimes from compatibilities issues with GCC compiler. What I can suggest now is to install conda packages `m2w64-toolchain` in the same conda environment in which theano is installed, then work with this environment.

```batch
REM Activate your conda env in which you installed theano.
REM If you use the default conda env (i.e. root), run `activate root`, 
REM so that conda configures all environment variables correctly.
activate YOUR_CONDA_ENV

REM install m2w64-toolchain
conda install m2w64-toolchain

REM Then test again
```

**Comment by nikhiljha** [comment]
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\dnn.py", line 174, in dnn_available
    if not dnn_present():
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\dnn.py", line 157, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\dnn.py", line 130, in _dnn_check_version
    v = version()
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gpuarray\dnn.py", line 326, in version
    profile=False)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\compile\function_module.py", line 1795, in orig_function
    defaults)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\compile\function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gof\vm.py", line 1114, in make_all
    self.updated_vars,
  File "C:\Users\nikhil\Anaconda2\lib\site-packages\theano\theano\gof\vm.py", line 968, in make_vm
    vm = CVM(
NameError: global name 'CVM' is not defined
```

Tried that but this happened.

**Comment by nikhiljha** [comment]
I also installed build tools 2015 and now it hangs slightly longer before crashing (trying normally).

**Comment by notoraptor** [comment]
A bit strange. Can you clear the theano cache and then try again ?

`theano-cache purge`

**Comment by nikhiljha** [comment]
Did that and now it works, thanks!

**Comment by lauranceair** [comment]
why comes a error that "Process finished with exit code -1073741819 (0xC0000005)" when i add [dnn]
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

**Comment by hash** [comment]
My 3 cents: got to the point were dnn.dnn_available(name) L66 in C:\Users\hash\Miniconda3\lib\site-packages\theano\gpuarray\__init__.py crashes python.

**Comment by nouiz** [comment]
compute capability 2.1 isn't supported by cudnn. I just tested on a GPU that cudnn don't support, and for me it print a good error:

$ THEANO_FLAGS=device=cuda python -c "import theano"
Can not use cuDNN on context None: Device not supported
Mapped name None to device cuda: GeForce GTX 480 (0000:02:00.0)


But I found that we don't always handle it correctly. I asked @notoraptor to look into that.

**Comment by tswc** [comment]
@lauranceair have U solved the problem? I have the same problem as U. I mean after the error "fatal error: cudnn.h: No such file or directory"

**Comment by jingweimo** [comment]
The same issue occurs to me:
https://github.com/Theano/Theano/issues/6063

**Comment by Fellfalla** [comment]
If you just installed Cuda and followed the NVIDIA installing instruction: **Restart your machine**

**Comment by vihanb** [comment]
For anyone on macOS having this issue, adding these to `~/.theanorc` fixed my issue:

```
[dnn]
include_path=/usr/local/cuda/include
library_path=/usr/local/cuda/lib
```
