### ISSUE TITLE
Feature Request: Dynamically Sized shared variable

### ISSUE THREAD

**Issue by petered** [Theano/Theano#5777]
Hi all.  I'd like to request a `theano.shared_like(x, value=0)` function.  This would create a shared variable of the same shape and dtype as some symbolic variable x, filled with "value".  

Currently, you need to use this awkward `ifelse` construction if you want dynamically-sized shared variables.  For example:
```
import numpy as np
import theano
from theano.ifelse import ifelse

def accumulate(x):
    """
    Keep a running sum of the input
    """
    accumulator = theano.shared(np.zeros((0, )*x.ndim, dtype=x.dtype))
    new_val = ifelse(accumulator.size>0, accumulator+x, x)
    return new_val, {accumulator: new_val}

x = theano.tensor.matrix(dtype=theano.config.floatX)
y, updates = accumulate(x)
f = theano.function(inputs=[x], outputs=y, updates=updates, allow_input_downcast=True)

vals = np.random.randn(3, 2, 4)
assert np.allclose(f(vals[0]), vals[0])
assert np.allclose(f(vals[1]), vals[:2].sum(axis=0))
assert np.allclose(f(vals[2]), vals[:3].sum(axis=0))
```
It would be better if this could be hidden away by a `shared_like` function, so that the function in the above example could be rewritten as:

```
def accumulate(x):
    accumulator = theano.shared_like(x, value = 0)
    new_val = accumulator+x
    return new_val, {accumulator: new_val}
```

**Comment by petered** [comment]
Here is my current solution to the problem, which is a horrible hack and probably fails in some cases:

```
class ReshapingSharedVariable(TensorSharedVariable):
    """A shared variable with a dynamic shape."""

    def __add__(self, other):
        return ifelse(self.size>0, tt.add(self, other), other+self.initial_value)

    def __mul__(self, other):
        return ifelse(self.size>0, tt.mul(self, other), other*self.initial_value)


def shared_like(x, value=0., **kwargs):
    """
    Return a Shared Variable with dynamic shape. e.g.
        accumulator = shared_like(x)
        new_accum_val = accumulator+x
    :param x: A symbolic variable
    :param value: The initial value for this variable
    :param kwargs: Other args to pass to theano.shared
    :return: A ReshapingSharedVariabe
    """
    out = theano.shared(np.zeros((0, )*x.ndim, dtype=x.dtype), **kwargs)
    out.__class__ = ReshapingSharedVariable
    out.initial_value = value
    return out
```

**Comment by lamblin** [comment]
What you request is not really possible, as shared variables are shared between function calls (and between functions), for which the shape of `x` could be different.

**Comment by nouiz** [comment]
@petered, If you know before hand the size of x, why not init the shared
variable to that size? This would fix your problem with a simpler solution.

**Comment by petered** [comment]
@lamblin I think it's possible - I would just expect a shape error to be thrown if the shape of x changes, just as you'd expect a shape error if you'd initialized accumulator with a pre-defined shape an then called it with an x whose shape didn't match.

@nouiz I agree it's possible to do it this way but it becomes very awkward when x is the output of some other function (eg suppose we're computing the running sum of activations of some layer in a convnet) - you end up having make another layer of code that pre-computes the shapes of variables.

Anyway, I'm not sure how difficult it would be to add this to theano, but if it's feasible it's certainly be helpful..

**Comment by lamblin** [comment]
So the semantics would be more "shared like the first value to ever be affected to `x`".
Unfortunately, we do not really have the right abstractions to express that in Theano for the moment.
There may be creative ways of doing that, maybe using / abusing default values or default updates. Something like that may actually be in use inside of Scan. But I'm not sure it can be self-contained in the shared variable itself.
