### ISSUE TITLE
Update documentation to mention gpuarray.preallocate instead of lib.cnmem

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5781]
For instance, the API documentation for config [mentions](https://github.com/Theano/Theano/blob/afd11ed2078523a55dec4267ed3f9e4e2c615c07/doc/library/config.txt#L52-L54) : `THEANO_FLAGS='floatX=float32,device=cuda0,lib.cnmem=1'`

It does not make any sense, because `device=cuda0` activates the new back-end, but `lib.cnmem=1` only affects the old one.

**Comment by lamblin** [comment]
It has been done in the dev branch, but it should be back-ported to 0.9.X.

**Comment by lamblin** [comment]
See https://github.com/Theano/Theano/commit/7865799170d329d83b5e3725609357369d44765a#diff-f11d53ef1f89a6d3007dd2b33ef7c5d5 (but do not backport everything)

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/search?utf8=%E2%9C%93&q=cnmem&type= for all places that need update.
