### ISSUE TITLE
Return correct gradient in ARange with float dtype (and floatX-typed gradient when dtype is discrete)

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5790]
Currently, the [implementation](https://github.com/Theano/Theano/blob/372ae95ef9aae402b7f426d159585d26556eb0a1/theano/tensor/basic.py#L5395-L5397) re-uses the dtype of the inptus, which is not correct.

I think there is a helper function to get the right dtype (floatX if dtype in discrete_dtypes, else dtype) somewhere.

**Comment by lamblin** [comment]
Wait, that formula is not even correct when the dtype is not discrete!
We should figure out the right formula (including the case where step < 0), or at least return `GradNotImplemented()` in the mean time.

**Comment by lamblin** [comment]
When the output is continuous:
- I think that the gradient for the "stop" should be 0, as it does not change the result most of the time when changed by epsilon.
- The gradient wrt "start" should be the sum of output gradients
- The gradient wrt "step" should be `sum(dout * arange(n_steps+1))`, where `n_steps` is the actual number of steps taken during the forward.

**Comment by nouiz** [comment]
What is the consequence of this bug?

**Comment by lamblin** [comment]
Wrong results (0 gradient) when taking gradients through an ARange with a float dtype.

**Comment by nouiz** [comment]
I think for stop, it should be DisconnectedType, not zeros. currently it use connection_pattern to break the connection for that input. So if we really want zeros, we should remove the connection pattern.

The `+ 1` for the step isn't needed. Otherwise you end up with a different shape (and it would be `+ step`)

**Comment by lamblin** [comment]
I agree with zeros instead of DisconnectedType (initially I thought the role of `start` and `stop` may have been reversed for negative `step`).
I realized there is an ambiguity in what "steps" mean, I took it to mean the number of gaps between the numbers, so `dout.shape[0] - 1`, so indeed we want something corresponding to `arange(dout.shape[0])`.
Re-opening because there are issues in #6447.

**Comment by as1986** [comment]
Does this mean that currently, gradients of tensors that use T.arange may be incorrect?
My main use of T.arange is to select (unnormalized) probabilities in log space. E.g.
`chosens = log_probs[T.arange(log_probs.shape[0]), y]`, where `y` is an integer vector of indices.
If so, could you advise a possible workaround? Thanks!

**Comment by lamblin** [comment]
In your case, `log_probs.shape[0]` has an integer dtype, so the gradient is zero, which is correct.

**Comment by lamblin** [comment]
Fixed in #6452.
