### ISSUE TITLE
Implement tensor.min() for bool and uint*

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#5791]
Currently, it raises NotImplementedError.
It could use tensor.max(), like for float and int, or maybe in that case actually use a "minimum" reduction.

See [here](https://github.com/Theano/Theano/blob/372ae95ef9aae402b7f426d159585d26556eb0a1/theano/tensor/basic.py#L1734)

**Comment by ibrahimsharaf** [comment]
Hi @lamblin, I would love to work on this, can you provide more details on how to start?

**Comment by abergeron** [comment]
An actual minimum would be the correct solution, and should not be too hard of you base yourself on the existing MaxAndArgmax/Argmax/Max code.

**Comment by QtRoS** [comment]
@abergeron does my commit look like correct solution for bool?
_(It's little bit hard to check correctness because of Python's dynamic nature)_

**Comment by nouiz** [comment]
Note, I understood the problem and we approved the PR after small
modification. We will merge when CI pass.

thanks.
