### ISSUE TITLE
batched_dot gives sometimes wrong results with new backend.

### ISSUE THREAD

**Issue by Thrandis** [Theano/Theano#5795]
The following code reproduces the problem (might be linked to #5730 as well):
Theano version: `0.9.0.dev-aca733c85117efcc50653773d13cbb9e2a0a8210`
Pygpu version: `0.6.2`
```python
# problem.py
import numpy as np
from theano import tensor, function, config

x = tensor.tensor3('x')
y = tensor.tensor3('y')
z = tensor.batched_dot(x.dimshuffle(1, 2, 0), y.dimshuffle(1, 2, 0)) 
f = function([x, y], z)

x_num = np.arange(24, dtype=config.floatX).reshape((4, 2, 3)) 
y_num = np.arange(40, dtype=config.floatX).reshape((5, 2, 4)) 

print f(x_num, y_num)[0]
```

Note that the code runs perfectly if I don't do the `dimshuffle` on `x` and `y` (and reshape `x_num` and `y_num` accordingly).

#### Running on the CPU
`THEANO_FLAGS=device=cpu,floatX=float32 python problem.py`:
```
[[   84.   372.   660.   948.  1236.]
 [   90.   410.   730.  1050.  1370.]
 [   96.   448.   800.  1152.  1504.]]
```

#### Running on the old GPU backend
`THEANO_FLAGS=device=gpu,floatX=float32 python problem.py`:
```
Using gpu device 0: GeForce GTX 750 (CNMeM is disabled, cuDNN 5005)
[[   84.   372.   660.   948.  1236.]
 [   90.   410.   730.  1050.  1370.]
 [   96.   448.   800.  1152.  1504.]]
```

#### Running on the new GPU backend
`THEANO_FLAGS=device=cuda,floatX=float32 python problem.py`                                     
```
Using cuDNN version 5005 on context None
Mapped name None to device cuda: GeForce GTX 750 (0000:05:00.0)
[[  72.  112.  232.  272.  392.]
 [  57.  101.  233.  277.  409.]
 [  82.  130.  274.  322.  466.]]
```
This is the wrong result!

#### Running on the new GPU backend without optimizations
`THEANO_FLAGS=device=cuda,floatX=float32,optimizer=None python problem.py  `                                                    
```
Using cuDNN version 5005 on context None                      
Mapped name None to device cuda: GeForce GTX 750 (0000:05:00.0)
[[   84.   372.   660.   948.  1236.]
 [   90.   410.   730.  1050.  1370.]
 [   96.   448.   800.  1152.  1504.]]
```
@abergeron what can I do to fix it?

**Comment by lamblin** [comment]
The last one is not actually using the GPU for that computation, so it is normal it behaves like the CPU.

I'm suspecting an issue in the way strides or offsets are passed to libgpuarray kernels. I'll have a look.

**Comment by Thrandis** [comment]
Oh yeah, that's a good point.

**Comment by lamblin** [comment]
Not using dimshuffle in the graph (and instead transposing the numpy array) gives the right result, but transposing _either_ of the arguments give nonsensical responses.
It looks like some memory order is assumed, that is not the case.

**Comment by nouiz** [comment]
I have a fix that isn't optimized, but it fix the bug:

https://github.com/Theano/libgpuarray/pull/395

**Comment by nouiz** [comment]
I'm not sure what the problem is. If I ran my test without my fix twice,
the first time it fail, but the second time it pass. If I recompile and
reinstall libgpuarray and test again, it fail then pass!

I have this pattern on 2 computers!

**Comment by abergeron** [comment]
Can you test with the fix in https://github.com/Theano/libgpuarray/issues/398
