### ISSUE TITLE
transfer TensorVariable to another GPU

### ISSUE THREAD

**Issue by ehsanmajidi** [Theano/Theano#5812]
I want the output of a layer to be an input for another network in other GPU. I'm using pycuda but it doesn't support transferring TensorVariable. Also I don't want grad to be broken because of disconnected network. 
Any suggestion?

**Comment by nouiz** [comment]
I want to warn you that the multi-GPU in one process is beta and we don't have time to work on it right now. So you could hit problem and we won't have time to help.

You should not mix Theano variable and python. Theano Variable are symbolic. So I don't know understand what you want.

if you just want to transfer one node from one GPU to another GPU, you can do:

    a_theano_variable.transfer('cudaN')

to have it transfered to the right device. Normally it should work and the following Theano variable should be moved to that GPU. But see the warning at the begginging of this comment.

**Comment by ehsanmajidi** [comment]
Yes, it is Theano Tensor variable. I'm not mixing with python variables. 
I have tried .transfer but it didn't work in this case since my variable is not an array but symbolic variable.

**Comment by nouiz** [comment]
This is user support and should be directed to theano-user. We keep the issues for bug report and feature request.

I don't understand what your problem is. So when you write to theano-user, give runable code that produce your problem and the error it give.
