### ISSUE TITLE
TypeError on Windows 10, Python 3, CudaNdarray Backend

### ISSUE THREAD

**Issue by hma02** [Theano/Theano#5822]
There is a Windows related issue found when running the theano_alexnet code. Thought it might be a common problem to be reported here. See this issue:

https://github.com/uoguelph-mlrg/theano_alexnet/issues/32

The user is in a WinPython-64bit-3.4.4.4Qt5\python-3.4.4.amd64  environment running with theano's old backend CudaNdarray.

I understand the old backend is not supported any more. Just wondering if switching to older version of theano like 0.8 will solve the problem.

**Comment by abergeron** [comment]
cuda IPC memeory handles only work on linux (not our limitation, it's NVIDIA's).
