### ISSUE TITLE
 GpuCorrMM images and kernel must have the same stack size

### ISSUE THREAD

**Issue by JWarlock** [Theano/Theano#5828]
I am running ResNet50 on Keras 2.0.2 and Theano 0.9.0 as backend:
```
from keras.models import *
from keras.layers import *
from keras.applications import *
from keras.preprocessing.image import *

import h5py

def write_gap(MODEL, image_size, lambda_func=None):
    width = image_size[0]
    height = image_size[1]
    input_tensor = Input((3,height, width))
    x = input_tensor
    if lambda_func:
        x = Lambda(lambda_func)(x)

    base_model = MODEL(input_tensor=x, weights='imagenet', include_top=False)
    model = Model(base_model.input, GlobalAveragePooling2D()(base_model.output))

    gen = ImageDataGenerator()
    train_generator = gen.flow_from_directory(train_data_path, image_size, shuffle=False, 
                                              batch_size=32)
    test_generator = gen.flow_from_directory(test_data_path_stg1, image_size, shuffle=False, 
                                             batch_size=32, class_mode=None)
    print train_generator.samples
    print test_generator.samples
    print model.summary()
    train = model.predict_generator(train_generator, train_generator.samples)
    test = model.predict_generator(test_generator, test_generator.samples)
    with h5py.File("gap_%s.h5"%MODEL.func_name) as h:
        h.create_dataset("train", data=train)
        h.create_dataset("test", data=test)
        h.create_dataset("label", data=train_generator.classes)

write_gap(ResNet50, (224, 224))`
```

But I got the following error:

> ValueError: GpuCorrMM images and kernel must have the same stack size

Apply node that caused the error: GpuCorrMM{valid, (2, 2), (1, 1)}(GpuContiguous.0, GpuContiguous.0)
Toposort index: 1326
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D)]
Inputs shapes: [(32, 3, 230, 230), (7, 7, 3, 64)]
Inputs strides: [(158700, 52900, 230, 1), (1344, 192, 64, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuElemwise{add,no_inplace}(GpuCorrMM{valid, (2, 2), (1, 1)}.0, GpuReshape{4}.0)]]

I am so lost. I don't understand where is wrong

**Comment by nouiz** [comment]
This is a user questions and should be asked on theano-user mailing list or keras mailing list.

The problem is that the input shapes to the convolution aren't valid shapes. In particular in this case the image have shapes (32, 3, 230, 230) while the weights have shape (7, 7, 3, 64). If you make the weights with shapes of (7, 3, 3, 64), it should work. That dimensions must match in shape with the image shapes.
