### ISSUE TITLE
Function cudnnSetFilterNdDescriptor_v4 is removed from cuDNN v6 - please use the function without version suffix

### ISSUE THREAD

**Issue by imsedgar** [Theano/Theano#5830]
File https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn_base.c contains a call to cudnnSetFilterNdDescriptor_v4 in line 57. Function calls with a version number postfix is depredicated by cuda cuDNN and remove in cuDNN version 6.0.

Please could you rename the function call to cudnnSetFilterNdDescriptor ?

**Comment by nouiz** [comment]
No. We are removing the old back-end from Theano this week. We already have a PR that is close to get merged that does that: 

https://github.com/Theano/Theano/pull/5814

The new back-end compile with cudnn v6. Here is some doc on how to convert to it:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

If you have problems, tell us, but it should work.

**Comment by capybaralet** [comment]
I had this error as well, using the old backend with new cuda.
I had to change theano/sandbox/cuda/dnn.py to remove 3 `_v4`s, and now my code is running.

**Comment by nouiz** [comment]
That is a bad fix. Update Theano to 0.9 or the dev version. Theano have
frequent significant update. Updating Theano when it have the support for
newer cudnn version is better.
