### ISSUE TITLE
Runtime error with New Back-end on Windows10

### ISSUE THREAD

**Issue by aeloyq** [Theano/Theano#5831]
I installed anaconda 2-4.3.0.1(python27) on Win10 with cuda8.0 and cudnn5.1
then:
conda install numpy scipy mkl-service libpython m2w64-toolchain
conda install theano pygpu

with theanorc.txt:
[global]
device=cuda
floatX = float32
optimizer_including=cudnn
openmp=False
allow_input_downcast=True

[dnn]
enabled=True
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

but got runtime error following:
`>>> import theano
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\I\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 164, in <module>
    use(config.device)
  File "C:\Users\I\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 151, in use
    init_dev(device)
  File "C:\Users\I\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 66, in init_dev
    avail = dnn.dnn_available(name)
  File "C:\Users\I\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 174, in dnn_available
    if not dnn_present():
  File "C:\Users\I\Anaconda2\lib\site-packages\theano\gpuarray\dnn.py", line 165, in dnn_present
    dnn_present.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
In file included from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/driver_types.h:53:0,
                 from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/cudnn.h:63,
                 from c:\users\iotlab\appdata\local\temp\try_flags_5jgpcp.c:4:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/host_defines.h:84:0: warning: "__cdecl" redefined
 #define __cdecl
 ^
<built-in>: note: this is the location of the previous definition
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64/cudnn.lib: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status`

**Comment by nouiz** [comment]
Can you uninstall cudnn and reinstall it? Make sure to install the right
version, the one currently used is not the right one or is corrupt.

**Comment by aeloyq** [comment]
i have re-installed CUDA 8.0 and downloaded cudnn 5.1 from nvidia website(for now cudnn 6.0 is aviliable should i choose this version) 
still report same error “"__cdecl" redefined”
But i found another computer with same environment can using new-backend successfully.
so i may close the issue 
if i found something usefull i will report the solution here
Thank you Fred~

**Comment by aeloyq** [comment]
i have tried everthing but it just doesn't work
uninstalled anaconda cuda cudnn then reinstalled

conda install mingw libpython
conda install theano pygpu

cudnn compile failed after import theano

main error info:

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/host_defines.h:84:0: warning: "__cdecl" redefined
 #define __cdecl
 ^
<built-in>: note: this is the location of the previous definition
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64/cudnn.lib: error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status

**Comment by peterjc123** [comment]
You can specify your c++ compiler using the cxx flag in theanorc file like this in the [global] section
`cxx=full path to your g++ file`
Also add the dir of the g++ file to the environment variable PATH.

**Comment by aeloyq** [comment]
Thank you very much @peterjc123 !
This is vital for windows users for the reason that console won't know which compiler to choose if theano config isn't given a specific setting.

**Comment by brightblueray** [comment]
I'm feeling a little dim here... any chance you can post a working .theanorc?

**Comment by peterjc123** [comment]
Here is my .theanorc file.
```
[global]
device=cuda
floatX = float32
optimizer_including=cudnn
openmp=False
allow_input_downcast=True
cxx=C:\Anaconda2\Library\mingw-w64\bin\g++.exe

[dnn]
enabled=True
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
```
