### ISSUE TITLE
fresh conda install is not working

### ISSUE THREAD

**Issue by grg2rsr** [Theano/Theano#5833]
ubuntu 16.10.

installed theano via `conda install theano pygpu` as recommended [here](http://deeplearning.net/software/theano/install_ubuntu.html)

``` python
import theano
```
gave me a msg that I first had to remove a compiler lock file. After that, running
```
theano.test()
```
gives me an endless stream of errors, here is one:
```
In [5]: theano.test()
Theano version 0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291
theano is installed in /home/georg/anaconda2/lib/python2.7/site-packages/theano
NumPy version 1.11.1
NumPy relaxed strides checking option: False
NumPy is installed in /home/georg/anaconda2/lib/python2.7/site-packages/numpy
Python version 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
/home/georg/anaconda2/lib/python2.7/site-packages/theano/misc/pycuda_init.py:35: UserWarning: PyCUDA import failed in theano.misc.pycuda_init
  warnings.warn("PyCUDA import failed in theano.misc.pycuda_init")
/home/georg/anaconda2/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py:10: UserWarning: theano.sandbox.gpuarray has been moved to theano.gpuarray. Please update your code and pickles. If the warning persists, clear theano's cache ('$theano/bin/theano-cache clear').
  warnings.warn(message)
EE.EEEERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x}(TensorConstant{2.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/opt.py", line 1982, in process_node
    replacements = lopt.transform(node)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/tensor/opt.py", line 6450, in constant_folding
    no_recycling=[], impl=impl)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 935, in make_thunk
    no_recycling)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 839, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1159, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2325, in compile_str
    return dlimport(lib_filename)
  File "/home/georg/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 302, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: ('/home/georg/.theano/compiledir_Linux-4.8--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.12-64/tmpylnVOH/0abe19206004f55475830d020f9a6684.so: undefined symbol: _ZdlPvm', '[InplaceDimShuffle{x}(TensorConstant{2.0})]')
```
there is a closed issue (issue [#5141)](https://github.com/Theano/Theano/issues/5141) about the `undefined symbol: _ZdlPvm` problem, but I can't find a .theanorc file. and would be surprised if my fix requires manual compiling.

**Comment by grg2rsr** [comment]
Ok sorry I didn't do enough google research I guess. [this](http://stackoverflow.com/questions/42729958/python-theano-undefined-symbol-zdlpvm-error) fixed it.
I had no .theanorc but created one in the home folder, worked.

**Comment by nouiz** [comment]
thanks for the follow up.

On Tue, Apr 11, 2017 at 9:00 AM Georg Raiser <notifications@github.com>
wrote:

Closed #5833 <https://github.com/Theano/Theano/issues/5833>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Theano/Theano/issues/5833#event-1038238781>, or mute
the thread

**Comment by grg2rsr** [comment]
problem persists on Ubuntu 17.4, conda installed. If it is a problem that the gcc currently shipped with ubuntu by default is from now on too new, then all ubuntu users installing theano will run into this problem, and it should be noted in the [installation docs](http://deeplearning.net/software/theano/install_ubuntu.html).

**Comment by kubaroth** [comment]
Seeking the solution for the same problem. It is not clear to me if setting a non-default gcc (4.9) in .theanorc requires to be followed by removal theano from conda (and subsequent re-installation)? If that's the case does actually .theanorc is taken into account?

**Comment by nouiz** [comment]
You should not need to reinstall Theano when you change of gcc version. In
some cases, deleting the Theano cache could be useful, but if the gcc
version change,it should not be needed.
