### ISSUE TITLE
Make tensor.flatten(x, ...) and x.flatten() have the same keyword

### ISSUE THREAD

**Issue by olimastro** [Theano/Theano#5836]
This is a very small request but I have been annoyed by the fact that the calls to flatten do not accept the same keyword whereas it is:

theano.tensor.flatten(x, outdim=3)
and
x.flatten(ndim=3)

It would be nice to have this be consistent!

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/5873

thanks
