### ISSUE TITLE
Cannot import theano with cuda in ipython.

### ISSUE THREAD

**Issue by AC130USpectre** [Theano/Theano#5838]
Hi. I'm trying to make use theano with cuda on Win10. My theanorc:

> [global]
> floatX = float32
> device = cuda
> 
> [lib]
> cnmem = 1
> 
> [dnn]
> include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
> library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

When I type `import theano` in **jupyter notebook**, it gaves me the following error:

> Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
> In file included from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/driver_types.h:53:0,
>                  from C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/cudnn.h:63,
>                  from c:\users\ruslan\appdata\local\temp\try_flags_es22qk.c:4:
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include/host_defines.h:84:0: warning: "__cdecl" redefined
>  #define __cdecl
>  ^
> <built-in>: note: this is the location of the previous definition
> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64/cudnn.lib: error adding symbols: File in wrong format
> collect2.exe: error: ld returned 1 exit status
> 
> Mapped name None to device cuda: GeForce GTX 970M (0000:01:00.0)

Here it uses linker from VS 14 (VC++ 15 Upd 1). Obviously, I cannot use theano in that case (as library is not linked). But when I type  `import theano` into the **console**, it works well and returns me the following:

> >>> import theano
> Using cuDNN version 5110 on context None
> Mapped name None to device cuda: GeForce GTX 970M (0000:01:00.0)

Nice, but I want to use jupyter. **_What is the difference_** with importing from jupyter and from console? What exactly does it tries to link? Maybe If I will have more info, I will be able to backtrace this problem and find a solution.

Thanks!

**Comment by nouiz** [comment]
You probably have a different envirionment in the console and in the
notebook. They could use different python version. They could have
different environment variable that link to different compiler to be used.

On windows, I strongly recommand to use conda to install Theano. Remove all
other python version. Remove all old Theano version. Remove all g++
compiler. We don't need VS for the new gpu back-end. We don't call nvcc
anymore (we compile via the driver).

**Comment by AC130USpectre** [comment]
Are you sure that it should use driver? I've done like you said (reinstalled totally all) and now after `import theano` kernel just dies with error message like "this program has been shut down"

**Comment by AC130USpectre** [comment]
> We don't call nvcc
> anymore (we compile via the driver).

Is it true only for python 2.7 (when version from conda is used)

**Comment by nouiz** [comment]
I don't get what you mean. Theano 0.9 with the new gpu back-end
(device=cuda*) won't call nvcc. This is not dependent of python version. In
the master of Theano, we removed this week the old back-end, so there is no
code to compile with nvcc anymore.

**Comment by peterjc123** [comment]
You can specify your c++ compiler using the cxx flag in theanorc file like this in the [global] section
`cxx=full path to your g++ file`
Also add the dir of the g++ file to the environment variable PATH.

**Comment by nouiz** [comment]
As no news and the last comment should fix that, I'm closing. If you still have problems, comment them.
