### ISSUE TITLE
dimshuffle with batched_dot

### ISSUE THREAD

**Issue by krm58** [Theano/Theano#5839]
Picking up on #5795:

My configuration:
Ubuntu 16.04
Theano and libgpuarray are on latest master
```python
os.environ['THEANO_FLAGS'] = 'contexts=dev0->cuda0,device=cuda0,mode=FAST_RUN,floatX=float32'
```
```python
theano.__version__
'0.9.0.dev-e79c4e4c83c5a4907ea7fddf073fd2d659df7486'
```
```python
pygpu.__version__
'0.6.4'
```

Let's try the test data added in #5795:
```python
import numpy as np
A = (np.array(([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))).reshape(2, 3, 3)
print A
for idx in range(2):
    print A[idx].dot(A[idx].T) 
```
which outputs
```
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
```

Now, shuffle dimensions to (hopefully) get the same thing with `batched_dot`:
```python
import os
os.environ['THEANO_FLAGS'] = 'contexts=dev0->cuda0,device=cuda0,mode=FAST_RUN,floatX=float32'

import theano
import theano.tensor as T
import numpy as np

A = (np.array(([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))).reshape(2, 3, 3)
sym_a = T.tensor3()
T.batched_dot(sym_a, sym_a.dimshuffle(0, 2, 1)).eval({sym_a: A.astype('float32')})
```
which returns
```
array([[[   9.,   17.,   27.],
        [  21.,   41.,   66.],
        [  33.,   65.,  105.]],

       [[  11.,   21.,   29.],
        [  26.,   51.,   71.],
        [  41.,   81.,  113.]]], dtype=float32)
```

Note, though, that 
```python
T.batched_dot(sym_a, sym_a.dimshuffle(0, 1, 2)).eval({sym_a: A.astype('float32')})
```
correctly produces
```
array([[[  30.,   36.,   42.],
        [  66.,   81.,   96.],
        [ 102.,  126.,  150.]],

       [[  30.,   36.,   42.],
        [  66.,   81.,   96.],
        [ 102.,  126.,  150.]]], dtype=float32)
```

So is this a problem with `batched_dot` not passing on the correct memory layout from the view returned by `dimshuffle`?

@jmxpearson

**Comment by nouiz** [comment]
I'm not able to reproduce the problem. Which version of cuda do you use? Driver version? WHich GPU?

I updated the description with what I think reproduce the error. Can you confirm you have this error with this code in a new python shell?

```
import os
os.environ['THEANO_FLAGS'] = 'contexts=dev0->cuda0,device=cuda0,mode=FAST_RUN,floatX=float32'

import theano
import theano.tensor as T
import numpy as np

A = (np.array(([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))).reshape(2, 3, 3)
sym_a = T.tensor3()
T.batched_dot(sym_a, sym_a.dimshuffle(0, 2, 1)).eval({sym_a: A.astype('float32')})
```

If you still have the problem, can you uninstall all libgpuarray* files? Maybe there is the older version still there as it have a different version number and for some reason, this one get loaded.

**Comment by krm58** [comment]
I use Pycuda version is (2016, 1, 2). My Driver Version is 375.39, and I use Nvidia Titan X for my GPU. 

In a new python shell, I ran the code you provided:

```
import os
os.environ['THEANO_FLAGS'] = 'contexts=dev0->cuda0,device=cuda0,mode=FAST_RUN,floatX=float32'

import theano
import theano.tensor as T
import numpy as np

A = (np.array(([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]))).reshape(2, 3, 3)
sym_a = T.tensor3()
T.batched_dot(sym_a, sym_a.dimshuffle(0, 2, 1)).eval({sym_a: A.astype('float32')})
```
and received the following output:
```
array([[[   9.,   17.,   27.],
        [  21.,   41.,   66.],
        [  33.,   65.,  105.]],

       [[  11.,   21.,   29.],
        [  26.,   51.,   71.],
        [  41.,   81.,  113.]]], dtype=float32)
```
and not the desired output:
```
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
```
The error also replicates in the ipython terminal as well as in a jupyter notebook.

We will try your suggestion to uninstall libgpuarray* files and will let you know what happens.

**Comment by krm58** [comment]
We uninstalled all of the libgpuarray* files, and that fixed the issue. It turned out there was an old version of libgpuarray in the conda environment that was being called and was causing the error.

Thank you so much for helping us solve this issue!
