### ISSUE TITLE
Unable to assign a gpu (cuda0,cuda1,cuda2) to different co-running jupyter notebooks, no documentation for theano.gpuarray.use()

### ISSUE THREAD

**Issue by gcilibraise** [Theano/Theano#5846]
I have a linux system with three gpus.  I am using keras with theano to run cnn's,  In the past when I was using Theano 8.+ , I was able to assign a particular gpu to jupyter notebook window using the following:

import theano.sandbox.cuda
theano.sandbox.cuda.use("gpu2")

This allowed me to run three versions of the same cnn model using different hyper-parameters.

I very recently updated both keras (to 2.0) and theano ( to 0.9).  This required me to setup the gpuarray backend.

Running just one jupyter notebook with a model works fine.  gpu1 is selected by theano.   However when I startup a second notebook with the same model, theano tries to use the gpu assigned to the first notebook, causing a memory usage problem and ultimately causing the cnn model to run on the cpu rather than using one of the available two remaining gpus.

Is there a way to select the gpu that I wish the run on each jupyter notebook in theano 0.9 as I was able in theano 8.+

**Comment by nouiz** [comment]
You can use in the new back-end:

import theano.gpuarray
theano.gpuarray.use("cuda2")

**Comment by gcilibraise** [comment]
At the moment I have device=cuda0 in my .theanorc file.  I then added 
import theano.gpuarray
theano.gpuarray.use("cuda2")

to the bottom of my import block
I ran the import section
The message response was: Mapped name None to device cuda0: GeForce GTX 1080
At this point I would be able to run my model  BUT another message followed indicating a problem when the theano.gpuarray.use("cuda") line was processed

ValueError: context name None is already defined

I assume that theano is being imported by keras, hence the device selection cuda0 as defined in the .theanorc file

I then moved the 
import theano.gpuarray
theano.gpuarray.use("cuda2")
to the top of my import block with the same result.

**Comment by nouiz** [comment]
don't use device=cuda* in your .theanorc. This will cause conflict with the
call to use(). Let device=cpu (the default) in your .theanorc and
THEANO_FLAGS env var.

Then before creating any theano shared variable, call theano.gpuarray.use()
with the device you want to use.

**Comment by gcilibraise** [comment]
Perfect!
Thank you
