### ISSUE TITLE
serious drop performances: theano.sandbox.rng_mrg.mrg_uniform  executes on cpu !!!

### ISSUE THREAD

**Issue by jc-Rosichini** [Theano/Theano#5858]
Tried the summarize the findings after the hunt to chase the cause of sudden performance drop.

[see](https://github.com/Theano/Theano/issues/5849) saga

In summary: due to recent changes mrg.mrg_uniform gets executed on cpu and becomes a bottleneck for a net using lasagne's dropout layer

**Comment by nouiz** [comment]
I responded in the original issue. I think we can continue to use the original issue to track this, so I'll close this issue.

thanks for the investigation!

**Comment by jc-Rosichini** [comment]
Thanks Frederic!
Jan will certainly have to make a slight change in Lasagne github too.
Salut
Jean-Claude

**Comment by nouiz** [comment]
I don't get this comment. The fix should be in Theano I think.
