### ISSUE TITLE
Input dimension mismatch with (M, 1, N, N) * (M, 1, 1, 1) scalar multiplication in Theano 0.9.0dev3.dev-RELEASE

### ISSUE THREAD

**Issue by rafaelvalle** [Theano/Theano#5874]
Happens with Theano 0.9.0dev3.dev-RELEASE but not with 0.9

**Theano version**
'0.9.0dev3.dev-RELEASE'

**theanorc**
```bash
[global]
floatX = float32
device = cpu

[nvcc]
fastmath = True
```

**Code**
```python
import theano
import theano.tensor as T
import numpy as np

from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
srng = RandomStreams(seed=np.random.randint(2147462579, size=6))

alpha = srng.uniform((64, 1, 1, 1), low=0., high=1.)
img = srng.uniform((64, 1, 28, 28), low=0., high=1.)
z = alpha * img
f = theano.function([], z)
```

**Comment by nouiz** [comment]
Theano do broadcasting in a different way then NumPy. We do not do this based on the shapes, but on the broadcast flags of the variales. In Theano 0.9, we detect more case where we can put those flags to True, so this is why it work now.

I'll close this issue, as it work with the last release and the dev version. Having something not working in old version, but work in newer version isn't a reason to keep an issue open. Just update Theano.

If you still have questions, don't hesitate. 

For more information on broadcasting see this tutorial:

http://deeplearning.net/software/theano/tutorial/broadcasting.html

**Comment by rafaelvalle** [comment]
@nouiz It does not work with the dev version 0.9.0dev3.dev-RELEASE

**Comment by nouiz** [comment]
Theano 0.9 version is more recent then 0.9.0dev* versions.

**Comment by rafaelvalle** [comment]
That makes it very easy to solve the problem! Thanks!
