### ISSUE TITLE
integer division regression

### ISSUE THREAD

**Issue by bbudescu** [Theano/Theano#5875]
After commit https://github.com/Theano/Theano/commit/318dd6af2187e5afe8a4d3fe3d84385cb29cac42 which adds debug info for division by zero errors, the compilation of modules using integer division fails when using openmp backend.

Reason: 
c++ [code](https://github.com/Theano/Theano/blob/80a1e8e04f31631ae29936811f3e42d47025542b/theano/gof/cc.py#L112) chunk in theano.gof.cc.failure_code uses `goto` statement, which breaks compilation when passing `-fopenmp` flag to g++ (`theano.elemwise.Elemwise` enables this flag by default), being derived from OpenMPOp.

Code to reproduces issue:
```python
import theano
arr_shape = theano.shared(numpy.zeros((3, 3))).shape
t = arr_shape // numpy.array([2, 2], dtype=numpy.int64)
t.eval()
```

Note that the openmp code is called on array's shape, even if gpuarray backend is available, i.e., if
```python
arr_shape = K.variable(numpy.array([3, 3], dtype=numpy.int64), dtype=numpy.int64)
```
is used, instead, the crash is not reproduced.

gcc error message:
error: jump to label '__label_7' from here exits OpenMP structured block; invalid branch to/from OpenMP structured block

If more info required, please let me know.

**Comment by nouiz** [comment]
thanks for the report, here is the fix:

https://github.com/Theano/Theano/pull/5876

**Comment by bbudescu** [comment]
Thanks for the fix. It seems to work on my side.
Btw, is it expected for openmp to be used on shape tensors when gpuarray is available (and selected)?

**Comment by nouiz** [comment]
I don't understand your last sentence. Do you mean we enable openmp on scalar? or vector?

It is normal that some computation stay on the CPU when when the GPU is activated. Or you mean that we activated openmp for GPU elemwise? I would be very surprised of that.

**Comment by bbudescu** [comment]
No no, I am using the GPU, and was just a bit surprised to see that there are OpenMP Ops in the graph. I was, actually, wondering whether I managed to do something wrong with my model and instead of doing everything on GPU, some stuff remains on the CPU, and, as such, incurs a performance penalty.

**Comment by nouiz** [comment]
We try to keep on the CPU what is faster on the CPU. Elemwise on scalar
shapes is faster on the CPU so we keep them there.

Normally we should move vector elemwise to the GPU, as we only activate
openmp for tensor where ndim >= 1, it mean some such case stay on the CPU.
I support they aren't bottleneck, but you can use Theano profiler to make
sure of that.

**Comment by bbudescu** [comment]
It makes perfect sense. I didn't realize theano is so flexible as to decide what to run where. I thought it uses a single backend all over the place.
