### ISSUE TITLE
Gradient using nlinalg functions

### ISSUE THREAD

**Issue by ruanxt** [Theano/Theano#5879]
I'm trying to custom a layer using a nonlinear function in theano (SVD), however it shows an error:

AttributeError: 'SVD' object has no attribute 'grad'

It seems the gradient of svd hasn't been implemented. Is it possible to implement it, or it is just impossible to do so?

**Comment by nouiz** [comment]
This isn't implemented. There is already an issue that talk about how to implement it:

https://github.com/Theano/Theano/issues/5440

I'll close this issue as duplicate. If you have questions on how to implement it, don't hesitate to ask questions in the other issue.
