### ISSUE TITLE
Indexing by float triggers advanced indexing

### ISSUE THREAD

**Issue by jaberg** [Theano/Theano#588]
Currently, `a = tensor.vector()[: 1.0]` triggers advanced indexing. Is this desirable? I think not, but it's not obvious.  Thoughts?

**Comment by lamblin** [comment]
Fixed.

**Comment by nouiz** [comment]
Now we raise this error: "TypeError: index must be integers"

**Comment by Darthholi** [comment]
Excuse me, if I need to round a variable in a computation, which way is the right way?

I tried these ways:
T.round(y) (gives the error)
T.cast(T.round(y),'int32') (gives another unused-variable-error, it thinks, that variable y is unused and when made to warning, it just computes NaNs...)


What am I trying to accomplish:
-I want to store the variable (in tutorial logistic_sgd) as floats and round/cast them in the computation graph - as opposed to casting when loading the data.

How to create a node in computational graph, that will allow me to round the variable and use that as index?

**Comment by nouiz** [comment]
If you use only T.round, it is normal that you get the error. T.round round the number, but do not cast it. So it stay a float after that (like numpy).

So you should cast it you did in your second example. That snippet of code seem good. If you have an error that tell y isn't used, it mean there is an error in the way you use that snippet of code. A guess, if you do:

y = T.cast(T.round(y), 'int32')

this is bad. If you need more help, this isn't related to this issue, you are better to write to the mailing list.

An example that work:

tensor.vector()[: T.cast(T.round(1.0), 'int32')]

another

y=tensor.vector()
tensor.vector()[T.cast(T.round(y), 'int32')]

**Comment by Darthholi** [comment]
Thanks for reply! I will use the mailinglist!
