### ISSUE TITLE
Non-differential custom layer 

### ISSUE THREAD

**Issue by ruanxt** [Theano/Theano#5880]
I'm implementing a non-differenttiable layer, how to deal with the gradient? Because gradient is need for the backward computing. And a non-differentiable layer will block the passing of gradients.

**Comment by lamblin** [comment]
Which formula you want to implement for backpropagation when the gradient is not defined is out of the scope of Theano.
Theano provides you with different options to implement that formula when you have it figured out:
- use zero, disconnected, not implemented, or undefined gradients when gradients do not make sense
- call `theano.grad` with `known_grads` as a mapping from variables to manually-defined gradients
- define your own Op and its `grad` method
- use OpFromGraph and its `override_grad` parameter
