### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by tiagmoraismorgado** [Theano/Theano#5882]
it would be cool if thean would feature:
- a deep convolutional recursive swarm of hybrid bdi and artificial neural networks;
- it would be cool if it would be possible to feed such a thing with elastic fusion for gesture recognition using advanced computer vision algorithms

**Comment by nouiz** [comment]
I don't understant that the request is. Theano contain man advanced computer vision algo. I consider all our convolution to be that.

If you have something more specific, don't hesitate to add it to this issue.
