### ISSUE TITLE
Spelling error in docs. 

### ISSUE THREAD

**Issue by anmolsahoo25** [Theano/Theano#5884]
Hey,
I'm new here, so not really sure on the right way to approach this issue. I just found a tiny spelling error in the docs page. So should I create a pull request for that? 

Thanks!

**Comment by anmolsahoo25** [comment]
The spelling issue is in the Developer Start Guide by the way, where in the contributing section it spells 'recommanded'.

**Comment by nouiz** [comment]
I PR is the best for us.

Thanks
