### ISSUE TITLE
Theano ImportError: cannot import name function

### ISSUE THREAD

**Issue by puneet336** [Theano/Theano#5889]
Hi all,
I have installed theano on centos6.5 using gcc 4.4.7  and python 2.7.13 using command
python setup.py install

now when i try to import the module , i get following error:-
 server1]$ python
Python 2.7.13 (default, Apr 24 2017, 13:28:09) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import scipy
>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "theano.py", line 1, in <module>
    from theano import function, config, shared, tensor
ImportError: cannot import name function

I am getting this error with theano 0.9 as well as 0.8.

Please let me know if further information is required from my side.

**Comment by puneet336** [comment]
In my $HOME, there were too many files and theano.py / theano.pyc were also present. As i was trying  to import module from my $HOME, i was facing this issue. Deleting those files fixed this issue for me!

**Comment by nouiz** [comment]
thanks for the update. It can help others having he same issue.
