### ISSUE TITLE
Invalid value ("cpu") for configuration variable "gpu". Valid options start with one of "device", "opencl", "cuda"

### ISSUE THREAD

**Issue by Hazarapet** [Theano/Theano#5893]
Guys today I've upgraded my theano version to 0.9.0 and got the error "Invalid value ("cpu") for configuration variable "gpu". Valid options start with one of "device", "opencl", "cuda"". 
".theanorc" is 
[global]
floatX = float32
device = gpu0

[nvcc]
flags = -D_FORCE_INLINES

[lib]
cnmem = 0.9

[cuda]
root = /usr/local/cuda

Could you tell me please how I can solve it?

**Comment by nouiz** [comment]
Can you give the full error stack trace? This error is strange.

**Comment by Hazarapet** [comment]
it give me when I try to import theano. simple import theano gives that error.I've changed the device to cude (in .theanorc file) now it gives me another error: ('This name is already taken', 'floatX')

**Comment by nouiz** [comment]
There is a problem with your installation. Can you uninstall Theano
multiple time to make sure all version are removed? You could have multiple
Theano version in your environment and get such strange error.

Give the full error, it really help us to help you.

**Comment by Hazarapet** [comment]
Guys Why did you close this issue.It's not solved yet. I've installed theano correctly, like did always.Removed and installed again like @nouiz said.
Here is my whole error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 67, in <module>
    from theano.configdefaults import config
  File "/usr/local/lib/python2.7/dist-packages/theano/configdefaults.py", line 113, in <module>
    in_c_key=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 285, in AddConfigVar
    configparam.__get__(root, type(root), delete_key=True)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 333, in __get__
    self.__set__(cls, val_str)
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 344, in __set__
    self.val = self.filter(val)
  File "/usr/local/lib/python2.7/dist-packages/theano/configdefaults.py", line 100, in filter
    % (self.default, val, self.fullname)))
ValueError: Invalid value ("cpu") for configuration variable "gpu0". Valid options start with one of "device", "opencl", "cuda"

**Comment by nouiz** [comment]
I think I got what is going on.

Do you use Theano dev version and not the last release?

if so, we remove the old back-end (device=gpu*). You should use the new gpu
back-end: device=cuda*. See:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

**Comment by Hazarapet** [comment]
Thank you.I've already found out that I should write cuda* in stead of gpu*.

**Comment by Hazarapet** [comment]
Why don't you use pip package manager? It would be great to install with pip and I wouldn't have python's changed path

**Comment by nouiz** [comment]
You can install Theano with pip, but not the new packages managers.

pip don't suport well enough c packages, but conda does.

You can manually install libgpuarray if you want. On windows, this will be
probably very hard.

**Comment by goodfeli** [comment]
This isn't a request for support. This is a report of both a bug and violation of the best practices guide for API changes. The bug should be fixed and the API change should be brought into compliance with the best practices guide.

Users should get an error message saying that the old back-end has removed, not this cryptic and invalid error message.

Note that the error message says that a variable named "gpu0" has been set to "cpu", which isn't even true. The variable "device" has been set to "gpu0". It should be straightforward to detect if "device" is set to something beginning with "gpu" and raise an exception pointing to the doc for the new backend.

**Comment by nouiz** [comment]
Thanks for the reminder. Done here:

https://github.com/Theano/Theano/pull/5946
