### ISSUE TITLE
OpFromGraph bug

### ISSUE THREAD

**Issue by ruanxt** [Theano/Theano#5894]
I'm trying this example in stackoverflow: 

http://stackoverflow.com/questions/40613225/theano-how-to-override-gradient-for-part-of-op-graph

The example doesn't work for me and the error info is below:

---------------------------------------------------------------------------
UnusedInputError                          Traceback (most recent call last)
<ipython-input-4-693c94aa9815> in <module>()
     26 arg = atan2_safe(x, y)
     27 dx, dy = T.grad(arg, [x, y])
---> 28 fn = th.function([x, y], [dx, dy])
     29 fn(1., 0.) # gives [-0.0, 0.99099]
     30 fn(0., 0.) # gives [0.0, 0.0], no more annoying nan!

/usr/local/lib/python2.7/dist-packages/theano/compile/function.pyc in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    324                    on_unused_input=on_unused_input,
    325                    profile=profile,
--> 326                    output_keys=output_keys)
    327     # We need to add the flag check_aliased inputs if we have any mutable or
    328     # borrowed used defined inputs

/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.pyc in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    484                          accept_inplace=accept_inplace, name=name,
    485                          profile=profile, on_unused_input=on_unused_input,
--> 486                          output_keys=output_keys)
    487 
    488 

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1807                    on_unused_input=on_unused_input,
   1808                    output_keys=output_keys).create(
-> 1809             defaults)
   1810     finally:
   1811         t2 = time.time()

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in create(self, input_storage, trustme, storage_map)
   1672             theano.config.traceback.limit = theano.config.traceback.compile_limit
   1673             _fn, _i, _o = self.linker.make_thunk(
-> 1674                 input_storage=input_storage_lists, storage_map=storage_map)
   1675         finally:
   1676             theano.config.traceback.limit = limit_orig

/usr/local/lib/python2.7/dist-packages/theano/gof/link.pyc in make_thunk(self, input_storage, output_storage, storage_map)
    697         return self.make_all(input_storage=input_storage,
    698                              output_storage=output_storage,
--> 699                              storage_map=storage_map)[:3]
    700 
    701     def make_all(self, input_storage, output_storage):

/usr/local/lib/python2.7/dist-packages/theano/gof/vm.pyc in make_all(self, profiler, input_storage, output_storage, storage_map)
   1053                                                  compute_map,
   1054                                                  no_recycling,
-> 1055                                                  impl=impl))
   1056                 linker_make_thunk_time[node] = time.time() - thunk_start
   1057                 if not hasattr(thunks[-1], 'lazy'):

/usr/local/lib/python2.7/dist-packages/theano/gof/op.pyc in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    959         # python code was requested.
    960         self.prepare_node(node, storage_map=storage_map,
--> 961                           compute_map=compute_map, impl='py')
    962         return self.make_py_thunk(node, storage_map, compute_map, no_recycling)
    963 

/usr/local/lib/python2.7/dist-packages/theano/compile/builders.pyc in prepare_node(self, node, storage_map, compute_map, impl)
    607             self.fn = orig_function(self.local_inputs,
    608                                     self.local_outputs,
--> 609                                     **self.kwargs)
    610             self.fn.trust_input = True
    611 

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1806                    profile=profile,
   1807                    on_unused_input=on_unused_input,
-> 1808                    output_keys=output_keys).create(
   1809             defaults)
   1810     finally:

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in __init__(self, inputs, outputs, mode, accept_inplace, function_builder, profile, on_unused_input, fgraph, output_keys)
   1431 
   1432         # Check if some input variables are unused
-> 1433         self._check_unused_inputs(inputs, outputs, on_unused_input)
   1434 
   1435         # Make a list of (SymbolicInput|SymblicInputKits, indices,

/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.pyc in _check_unused_inputs(self, inputs, outputs, on_unused_input)
   1584                 elif on_unused_input == 'raise':
   1585                     raise UnusedInputError(msg % (inputs.index(i),
-> 1586                                                   i.variable, err_msg))
   1587                 else:
   1588                     raise ValueError("Invalid value for keyword "

UnusedInputError: ('The following error happened while compiling the node', OpFromGraph{inline=False}(<TensorType(float64, scalar)>, <TensorType(float64, scalar)>, TensorConstant{1.0}), '\n', "theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 2 is not part of the computational graph needed to compute the outputs: <TensorType(float64, scalar)>.\nTo make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.")

**Comment by nouiz** [comment]
Mostly, one OpFromGraph instance end up having one inputs that isn't used
for computation of its outputs.

You can pass the parameter on_unused_input='warn' or 'ignore' to that
OpFromGraph to ignore that fact. But this could cause extra computation.
For example, if nothing else use that inputs, it will end up still being
computed.

Did you override the gradient? If so, try to not use the inputs that isn't
needed for the grad.

**Comment by ruanxt** [comment]
That works! Thanks very much!
