### ISSUE TITLE
unexpected return of shared subtensor to CPU

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5899]
```
import theano
import numpy as np
s = theano.shared(np.ones([3, 3], dtype='float32'))
sub = s[1:3]
f = theano.function([], s)
g = theano.function([], sub)
h = theano.function([], sub.transfer(None))
print(type(f()))
print(type(g()))
print(type(h()))
```

Returns:
```
<class 'pygpu.gpuarray.GpuArray'>
<class 'numpy.ndarray'>
<class 'pygpu.gpuarray.GpuArray'>
```

Is this expected behavior? The numpy array surprised me!

**Comment by nouiz** [comment]
It is expected. The way it work is that the user build the graph on the
CPU, then we transfert it to the GPU. We do not change the types of the
inputs and outpus, so normally, they all stay on the CPU. The first case is
the one that should be surprising. This is where our GPU abstraction leak
and by default cause a return on the GPU contradiction the normal behavior.

To make sure that the output is on the GPU, use the third case.

This is related to https://github.com/Theano/Theano/issues/130.

**Comment by astooke** [comment]
Ok thanks!
