### ISSUE TITLE
Solve linear system XA=B

### ISSUE THREAD

**Issue by ruanxt** [Theano/Theano#5901]
Hi, I have found the operator for solving Ax=b, but is there a operator to solve $XA = B$, which is a simpler way to compute $X = BA^-1$ instead of using inverse explicitly?

**Comment by lamblin** [comment]
Can't you just transpose A and B, and use the regular Solve?

**Comment by ruanxt** [comment]
Yes, I can. But it will be a bit complicated like

X = theano.tensor.slinalg.solve(A.T, B.T).T

Which is a bit complicated, especially when there are complicated calculations. I wonder if there is a bit simple operator.

**Comment by lamblin** [comment]
No, there is not.
