### ISSUE TITLE
Windows 7: python stopped working 

### ISSUE THREAD

**Issue by ibrahim-amer** [Theano/Theano#5905]
I'm using theano's latest version installed using this command: 

> pip install git+git://github.com/Theano/Theano.git

-Then I installed libgpuarray using the instructions [here ](http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install).
 I used visual studio 2013 to build the solution then I copied the files to C:\Windows\System32 and added them to PATH like so: C:\Windows\gpuarray.dll;C:\Windows\gpuarray-static.lib;C:\Windows\gpuarray.exp;C:\Windows\gpuarray.lib. 

- CUDA 8.0 installed and tested using deviceQuery 
- THEANO_FLAGS:  floatX=float32,device=gpu,nvcc.fastmath=True,lib.cnmem=0.6,nvcc.flags=-D_FORCE_INLINES 

(Note: I'm getting a warning when I try to import theano using the above flags, that lib.cnmem is not recognised)

- When I try to run this code it keeps prompting me 

> Python stopped working 
No exception occurred or something 

```
import os
os.environ["THEANO_FLAGS"] = "floatX=float32,device=cuda0,lib.cnmem=0.6"
from theano import function, config, shared, tensor
import numpy

import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], **tensor.exp(x)**)  **#THE PROBLEM OCCURS AT THIS LINE "PYTHON STOPPED WORKING"**
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu'
```)

GPU: NVIDIA 1060 6GB
OS: Windows 7 64 bit
AMD FX8350 CPU 16GB RAM

Theano was working fine with me before libgpuarray backend integration. Is there any a solution for this? or is there any method to downgrade to a previous theano release before libgpuarray integration?

**Comment by ibrahim-amer** [comment]
Here is what I did to fix the problem:
1- Install pygpu library using this command: conda install Theano pygpu
2- Download mingw64 package from [here](conda install Theano pygpu), extract it to C:\ drive then add C:\mingw64\bin to PATH env variable
3- THEANO_FLAGS = "floatX=float32,device=cuda0"

Now everything is working fine using the GPU

**Comment by lamblin** [comment]
Thanks for providing the solution and update.
