### ISSUE TITLE
Theano crashes on import with dnn enabled

### ISSUE THREAD

**Issue by estrach** [Theano/Theano#5917]
Theano crashes on import with dnn.enabled=True, but imports correctly with dnn.enabled=False.

I'm using Windows 10 with Anaconda 4.1.1 (64-bit) (Python 3.5.2), CUDA 8.0 and a Geforce GTX 1060.  The steps I've followed are:

* Downloaded cuDNN v6.0 for CUDA 8.0 from Nvidia website and moved the contents of the bin, include, lib files to their corresponding folders in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
* Updated the enviroment path to include C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin (where there is nvcc.exe) and  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
* Installed Anaconda
* Installed required packages "conda install pip six nose numpy scipy mingw libpython scikit-image "
* Installed Pygpu "conda install -c rdonnelly pygpu" (this installs pygpu 0.6.2)
* Installed Theano from the instructions on the Lasagne install guide page "pip install -r https://raw.githubusercontent.com/Lasagne/Lasagne/v0.1/requirements.txt"
* Upgraded Theano to the bleeding-edge version "pip install --upgrade https://github.com/Theano/Theano/archive/master.zip" (Theano 0.9.0)
* And created a .theanrc file with the following contents:

[global]
device=cuda
floatX=float32

[lib]
cnmem=.75

[dnn]
enabled = True
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64

I've been able to test that Pygpu works with the GPU by setting an enviroment variable DEVICE=cuda and running "python -c "import pygpu;pygpu.test()"".  This all runs ok but when removing this environment variable, restarting the cmd window and importing Theano Python crashes

**Comment by nouiz** [comment]
Use Theano dev version. It contain fix for spaces in path and you have that
in the path you add for cudnn.

Also


[lib]
cnmem=.75

Isn't used in the new back-end. It is replaced by:

[gpuarray]
preallocate=0.75

**Comment by notoraptor** [comment]
Sorry, keyboard error.

**Comment by peterjc123** [comment]
You could try uninstalling Anaconda and then reinstall Theano through the following lines.
```
REM Install basic required packages for Theano
conda install numpy scipy mkl-service libpython m2w64-toolchain

REM Now install theano and pygpu
conda install theano pygpu

REM Clean theano cache if possible
theano-cache purge
```
If you still have problem, there're two more issues for your reference.
[pygpu.gpuarray.GpuArrayException: Error loading library: -1](https://github.com/Theano/libgpuarray/issues/407)
[error adding symbols: File in wrong format](https://github.com/Theano/Theano/issues/5831)

**Comment by estrach** [comment]
I previously had other versions of CUDA installed on the machine I'm running this on.  I've now removed all of the NVIDIA products, reinstalling only the graphics driver and CUDA v8.0 with cuDNN v6.0.  I then reinstalled Anaconda 3.4.1.1 (64-bit) and ran the following script:

pip install --upgrade pip
pip install cryptography --upgrade
conda install -c msys2 m2w64-toolchain=5.3.0 -y
conda install -c anaconda-extras mkl-service=1.1.0 -y
conda install numpy scipy libpython -y
conda install -c rdonnelly pygpu -y
cd c:\
git clone git://github.com/Theano/Theano.git
cd Theano
git pull --rebase
pip install -e . --no-deps
theano-cache purge

During this script I did get the following message when installing numpy scipi libpython and pygpu

`extern "Python": function Cryptography_locking_cb() called but @ffi.def_extern() was not callled in the current subinterpreter. Returning 0.`

Although, after this was complete I was able to test that pygpu was working fine "python -c "import pygpu;pygpu.test()"".  But when importing theano "python -c "import theano"" I get the following message:

`ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "d:\theano\theano\gpuarray\__init__.py", line 175, in <module>
    use(config.device)
  File "d:\theano\theano\gpuarray\__init__.py", line 162, in use
    init_dev(device, preallocate=preallocate)
  File "d:\theano\theano\gpuarray\__init__.py", line 71, in init_dev
    avail = dnn.dnn_available(name)
  File "d:\theano\theano\gpuarray\dnn.py", line 177, in dnn_available
    if not dnn_present():
  File "d:\theano\theano\gpuarray\dnn.py", line 168, in dnn_present
    dnn_present.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'g++.exe: error: Files\\NVIDIA: No such file or directory\r\ng++.exe: error: GPU: No such file or directory\r\ng++.exe: error: Computing: No such file or directory\r\ng++.exe: error: Toolkit\\CUDA\\v8.0\\include: No such file or directory\r\ng++.exe: error: Files\\NVIDIA: No such file or directory\r\ng++.exe: error: GPU: No such file or directory\r\ng++.exe: error: Computing: No such file or directory\r\ng++.exe: error: Toolkit\\CUDA\\v8.0\\lib\\x64: No such file or directory\r\n'
`

I'm not sure exactly what this error is.  It looks as though it is a problem parsing the path for CUDA, although I'm now using the development version of Theano.

The location of nvcc.exe is on the Path and I've tried installing MinGW "conda install -c anaconda mingw=4.7", and adding the location of g++.exe to the Path, but I still see the same error.

My updated .theanorc file is as follows:

[global]
device=cuda
floatX=float32

[gpuarray]
preallocate=0.75

[dnn]
enabled = True
include_path="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include"
library_path="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64"

**Comment by peterjc123** [comment]
Try to remove your	double quotation marks in the theanorc file like this:
```
[global]
device=cuda
floatX=float32

[gpuarray]
preallocate=0.75

[dnn]
enabled = True
include_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
```

**Comment by estrach** [comment]
Great, that works!  Thanks
