### ISSUE TITLE
Tricky setting of MKL_NUM_THREADS

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5920]
May not be anything to fix, but I was just tripped up in a case when I needed to set MKL_NUM_THREADS=1.  I did so in the subprocesses I forked before creating a Theano function in them...thought I was doing it the right way but still was getting multi-threaded execution.  The reason was because some time earlier, in the master process, I had built that same function.  So when the workers built it, they ignored their MKL_NUM_THREADS and just used previously built function from the other python process.

In my current problem it is perfectly fine to have the function be single-threaded in all processes, but anyway more local control of this would be desirable.  :)

edit: BTW the original function in the master had been dereferenced before forking.

**Comment by lamblin** [comment]
This is strange, since I would assume that the value of MKL_NUM_THREADS would be looked up each time an MKL function is called.
Can you check whether it is actually an MKL operation that is multithreaded, or another Theano operation (maybe an MPI Op)?

When you said you had built the same function, had you cached the result of the optimized graph (or compiled function) in any way? Or pickled it and transferred it to the child process?

**Comment by nouiz** [comment]
I think it was pickled to the chield process.

Currently, we hardcode in the graph if we enable or not our OpenMP code. If
OMP_NUM_THREADS is 1, we disable it. I don' t know then the value of
OMP_NUM_THREADS or MKL_NUM_THREADS are looked up. Maybe it is at the start
of a process? After the value was checked, it isn't looked again. To change
it during run time, call to C functions would be needed.

**Comment by astooke** [comment]
In this case it was a function that was built in the master process, and then instructions for building it were passed to the subprocess when forking.  Then the subprocess called `theano.function()` to make the function.

Interestingly, I must have MKL_NUM_THREADS=1 set during the first call to the function (in the master) in order to get single threaded operation.  If I unset MKL_NUM_THREADS after defining the function but before calling it, it does multithreaded.

**Comment by astooke** [comment]
> Can you check whether it is actually an MKL operation that is multithreaded, or another Theano operation (maybe an MPI Op)?

I assume that since setting MKL_NUM_THREADS=1 in the right place does lead to single-threaded operation, and since I haven't set any other environment variables, that it must be MKL?  It's a small convnet with a big enough fully connected layer on top to trigger multi-threaded MKL for at least that matrix multiply.

**Comment by nouiz** [comment]
I think this can be closed. If not, tell us.
