### ISSUE TITLE
Installed theano on my company computer, not working when imported

### ISSUE THREAD

**Issue by yyan162** [Theano/Theano#5924]
Hi,

I have installed the theano on my company computer but it has failed to work then I import theano on Anaconda. I am not a software engineer therefore I do not fully understand all the intricacies of the requirement for its successful installation though I have managed to do so on my own machine without any problems.

Below are the error message which is incomplete because it's too long. Many thanks for your time and effort.

Kind regards,
Y

> 00641                                 "lazy thunk should return a list");
00642                 err = 1;
00643                 goto pyfail;
00644               }
00645   
00646             if (!PyList_Size(rval))
00647               {
00648                 PyErr_SetString(PyExc_ValueError,
00649                                 "lazy thunk returned empty list without computing output");
00650                 err = 1;
00651                 goto pyfail;
00652               }
00653   
00654             for (int i = 0; i < PyList_Size(rval); ++i)
00655               {
00656                 PyObject * el_i = PyList_GetItem(rval, i);
00657                 Py_ssize_t N = PyNumber_AsSsize_t(el_i, PyExc_IndexError);
00658                 if (PyErr_Occurred())
00659                   {
00660                     err = 1;
00661                     goto pyfail;
00662                   }
00663                 assert (N <= self->node_n_inputs[owner_idx]);
00664                 Py_ssize_t input_idx = self->node_inputs[owner_idx][N];
00665                 err = lazy_rec_eval(self, input_idx, one, zero);
00666                 if (err) goto pyfail;
00667               }
00668   
00669             Py_DECREF(rval);
00670             /*
00671              * We intentionally skip all the end-of-function processing
00672              * (mark outputs, GC) as it will be performed by the call
00673              * that actually manages to compute the result.
00674              */
00675             return lazy_rec_eval(self, var_idx, one, zero);
00676           }
00677   
00678         Py_DECREF(rval);
00679       }
00680     else //owner is not a lazy op. Ensure all intputs are evaluated.
00681       {
00682         // loop over inputs to owner
00683         // call lazy_rec_eval on each one that is not computed.
00684         // if there's an error, pass it up the stack
00685         for (int i = 0; i < self->node_n_inputs[owner_idx]; ++i)
00686           {
00687             Py_ssize_t input_idx = self->node_inputs[owner_idx][i];
00688             if (!self->var_computed[input_idx])
00689               {
00690                 err = lazy_rec_eval(self, input_idx, one, zero);
00691                 if (err) return err;
00692               }
00693             assert (self->var_computed[input_idx]);
00694           }
00695   
00696         // call the thunk for this owner.
00697         if (self->thunk_cptr_fn[owner_idx])
00698           {
00699             err = c_call(self, owner_idx, verbose);
00700             if (err) goto fail;
00701           }
00702         else
00703           {
00704             rval = pycall(self, owner_idx, verbose);
00705             //rval is new ref
00706             if (rval) //pycall returned normally (no exception)
00707               {
00708                 if (rval == Py_None)
00709                   {
00710                     Py_DECREF(rval); //ignore a return of None
00711                   }
00712                 else if (PyList_Check(rval))
00713                   {
00714                     PyErr_SetString(PyExc_TypeError,
00715                                     "non-lazy thunk should return None, not list");
00716                     err = 1;
00717                     goto pyfail;
00718                   }
00719                 else // don't know what it returned, but it wasn't right.
00720                   {
00721                     PyErr_SetObject(PyExc_TypeError, rval);
00722                     err = 1;
00723                     // We don't release rval since we put it in the error above
00724                     goto fail;
00725                   }
00726               }
00727             else // pycall returned NULL (internal error)
00728               {
00729                 err = 1;
00730                 goto fail;
00731               }
00732           }
00733       }
00734   
00735     // loop over all outputs and mark them as computed
00736     for (int i = 0; i < self->node_n_outputs[owner_idx]; ++i)
00737       {
00738         self->var_computed[self->node_outputs[owner_idx][i]] = 1;
00739       }
00740   
00741     // Free vars that are not needed anymore
00742     if (self->allow_gc)
00743       {
00744         for (int i = 0; i < self->node_n_inputs[owner_idx]; ++i)
00745           {
00746             int cleanup = 1;
00747             Py_ssize_t i_idx = self->node_inputs[owner_idx][i];
00748             if (!self->var_has_owner[i_idx])
00749               continue;
00750   
00751             for (int j = 0; j < self->n_output_vars; ++j)
00752               {
00753                 if (i_idx == self->output_vars[j])
00754                   {
00755                     cleanup = 0;
00756                     break;
00757                   }
00758               }
00759             if (!cleanup) continue;
00760   
00761             for (int j = 0; j < self->n_dependencies[i_idx]; ++j)
00762               {
00763                 if (!self->var_computed[self->dependencies[i_idx][j]])
00764                   {
00765                     cleanup = 0;
00766                     break;
00767                   }
00768               }
00769             if (!cleanup) continue;
00770   
00771             Py_INCREF(Py_None);
00772             err = PyList_SetItem(self->var_value_cells[i_idx], 0, Py_None);
00773   //See the Stack gc implementation for why we change it to 2 and not 0.
00774             self->var_computed[i_idx] = 2;
00775             if (err) goto fail;
00776           }
00777       }
00778   
00779     return 0;
00780    pyfail:
00781     Py_DECREF(rval);
00782    fail:
00783     set_position_of_error(self, owner_idx);
00784     return err;
00785   }
00786   
00787   static PyObject *
00788   CLazyLinker_call(PyObject *_self, PyObject *args, PyObject *kwds)
00789   {
00790     CLazyLinker * self = (CLazyLinker*)_self;
00791     static char *kwlist[] = {
00792       (char *)"time_thunks",
00793       (char *)"n_calls",
00794       (char *)"output_subset",
00795       NULL};
00796     int n_calls=1;
00797     PyObject *output_subset_ptr = NULL;
00798     if (! PyArg_ParseTupleAndKeywords(args, kwds, "|iiO", kwlist,
00799                                       &self->do_timing,
00800                                       &n_calls,
00801                                       &output_subset_ptr))
00802       return NULL;
00803   
00804     int err = 0;
00805     // parse an output_subset list
00806     // it is stored as a bool list of length n_output_vars: calculate a var or not
00807     char *output_subset = NULL;
00808     int output_subset_size = -1;
00809     if (output_subset_ptr != NULL)
00810       {
00811         if (! PyList_Check(output_subset_ptr))
00812           {
00813             err = 1;
00814             PyErr_SetString(PyExc_RuntimeError, "Output_subset is not a list");
00815           }
00816         else
00817           {
00818             output_subset_size = PyList_Size(output_subset_ptr);
00819             output_subset = (char*)calloc(self->n_output_vars, sizeof(char));
00820             for (int it = 0; it < output_subset_size; ++it)
00821               {
00822                 PyObject *elem = PyList_GetItem(output_subset_ptr, it);
00823                 if (! PyInt_Check(elem))
00824                   {
00825                     err = 1;
00826                     PyErr_SetString(PyExc_RuntimeError, "Some elements of output_subset list are not int");
00827                   }
00828                 output_subset[PyInt_AsLong(elem)] = 1;
00829               }
00830           }
00831       }
00832   
00833     self->position_of_error = -1;
00834     // create constants used to fill the var_compute_cells
00835     PyObject * one = PyInt_FromLong(1);
00836     PyObject * zero = PyInt_FromLong(0);
00837   
00838     // pre-allocate our return value
00839     Py_INCREF(Py_None);
00840     PyObject * rval = Py_None;
00841     //clear storage of pre_call_clear elements
00842     for (int call_i = 0; call_i < n_calls && (!err); ++call_i)
00843       {
00844         Py_ssize_t n_pre_call_clear = PyList_Size(self->pre_call_clear);
00845         assert(PyList_Check(self->pre_call_clear));
00846         for (int i = 0; i < n_pre_call_clear; ++i)
00847           {
00848             PyObject * el_i = PyList_GetItem(self->pre_call_clear, i);
00849             Py_INCREF(Py_None);
00850             PyList_SetItem(el_i, 0, Py_None);
00851           }
00852         //clear the computed flag out of all non-input vars
00853         for (int i = 0; i < self->n_vars; ++i)
00854           {
00855             self->var_computed[i] = !self->var_has_owner[i];
00856             if (self->var_computed[i])
00857               {
00858                 Py_INCREF(one);
00859                 PyList_SetItem(self->var_computed_cells[i], 0, one);
00860               }
00861             else
00862               {
===============================
C:\Users\brandenyang\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_79_Stepping_1_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp:1: sorry, unimplemented: 64-bit mode not compiled in

00863                 Py_INCREF(zero);
00864                 PyList_SetItem(self->var_computed_cells[i], 0, zero);
00865               }
00866           }
00867   
00868         int first_updated = self->n_output_vars - self->n_updates;
00869         for (int i = 0; i < self->n_output_vars && (!err); ++i)
00870           {
00871             if (i >= first_updated || output_subset == NULL || output_subset[i] == 1)
00872               {
00873                 err = lazy_rec_eval(self, self->output_vars[i], one, zero);
00874               }
00875           }
00876   
00877         if (!err)
00878           {
00879             // save references to outputs prior to updating storage containers
00880             assert (self->n_output_vars >= self->n_updates);
00881             Py_DECREF(rval);
00882             rval = PyList_New(self->n_output_vars);
00883             for (int i = 0; i < (self->n_output_vars); ++i)
00884               {
00885                 Py_ssize_t src = self->output_vars[i];
00886                 PyObject * item = PyList_GetItem(self->var_value_cells[src], 0);
00887                 if ((output_subset == NULL || output_subset[i]) &&
00888                     self->var_computed[src] != 1)
00889                   {
00890                     err = 1;
00891                     PyErr_Format(PyExc_AssertionError,
00892                                  "The compute map of output %d should contain "
00893                                  "1 at the end of execution, not %d.",
00894                                  i, self->var_computed[src]);
00895                     break;
00896                   }
00897                 Py_INCREF(item);
00898                 PyList_SetItem(rval, i, item);
00899               }
00900           }
00901   
00902         if (!err)
00903           {
00904             // Update the inputs that have an update rule
00905             for (int i = 0; i < self->n_updates; ++i)
00906               {
00907                 PyObject* tmp = PyList_GetItem(rval, self->n_output_vars - self->n_updates + i);
00908                 Py_INCREF(tmp);
00909                 Py_ssize_t dst = self->update_storage[i];
00910                 PyList_SetItem(self->var_value_cells[dst], 0, tmp);
00911               }
00912           }
00913       }
00914   
00915     /*
00916       Clear everything that is left and not an output. This is needed
00917       for lazy evaluation since the current GC algo is too conservative
00918       with lazy graphs.
00919     */
00920     if (self->allow_gc && !err)
00921       {
00922         for (Py_ssize_t i = 0; i < self->n_vars; ++i)
00923           {
00924             int do_cleanup = 1;
00925             if (!self->var_has_owner[i] || !self->var_computed[i])
00926               continue;
00927             for (int j = 0; j < self->n_output_vars; ++j)
00928               {
00929                 if (i == self->output_vars[j])
00930                   {
00931                     do_cleanup = 0;
00932                     break;
00933                   }
00934               }
00935             if (!do_cleanup)
00936               continue;
00937             Py_INCREF(Py_None);
00938             PyList_SetItem(self->var_value_cells[i], 0, Py_None);
00939           }
00940       }
00941     if (output_subset != NULL)
00942       free(output_subset);
00943   
00944     Py_DECREF(one);
00945     Py_DECREF(zero);
00946     if (err)
00947       {
00948         Py_DECREF(rval);
00949         return NULL;
00950       }
00951     return rval;
00952   }
00953   
00954   #if 0
00955   static PyMethodDef CLazyLinker_methods[] = {
00956       {
00957         //"name", (PyCFunction)CLazyLinker_accept, METH_VARARGS, "Return the name, combining the first and last name"
00958       },
00959       {NULL}  /* Sentinel */
00960   };
00961   #endif
00962   
00963   
00964   static PyObject *
00965   CLazyLinker_get_allow_gc(CLazyLinker *self, void *closure)
00966   {
00967       return PyBool_FromLong(self->allow_gc);
00968   }
00969   
00970   static int
00971   CLazyLinker_set_allow_gc(CLazyLinker *self, PyObject *value, void *closure)
00972   {
00973     if(!PyBool_Check(value))
00974       return -1;
00975   
00976     if (value == Py_True)
00977       self->allow_gc = true;
00978     else
00979       self->allow_gc = false;
00980     return 0;
00981   }
00982   
00983   static PyGetSetDef CLazyLinker_getset[] = {
00984     {(char*)"allow_gc",
00985      (getter)CLazyLinker_get_allow_gc,
00986      (setter)CLazyLinker_set_allow_gc,
00987      (char*)"do this function support allow_gc",
00988      NULL},
00989     {NULL, NULL, NULL, NULL}  /* Sentinel */
00990   };
00991   static PyMemberDef CLazyLinker_members[] = {
00992       {(char*)"nodes", T_OBJECT_EX, offsetof(CLazyLinker, nodes), 0,
00993        (char*)"list of nodes"},
00994       {(char*)"thunks", T_OBJECT_EX, offsetof(CLazyLinker, thunks), 0,
00995        (char*)"list of thunks in program"},
00996       {(char*)"call_counts", T_OBJECT_EX, offsetof(CLazyLinker, call_counts), 0,
00997        (char*)"number of calls of each thunk"},
00998       {(char*)"call_times", T_OBJECT_EX, offsetof(CLazyLinker, call_times), 0,
00999        (char*)"total runtime in each thunk"},
01000       {(char*)"position_of_error", T_INT, offsetof(CLazyLinker, position_of_error), 0,
01001        (char*)"position of failed thunk"},
01002       {(char*)"time_thunks", T_INT, offsetof(CLazyLinker, do_timing), 0,
01003        (char*)"bool: nonzero means call will time thunks"},
01004       {(char*)"need_update_inputs", T_INT, offsetof(CLazyLinker, need_update_inputs), 0,
01005        (char*)"bool: nonzero means Function.__call__ must implement update mechanism"},
01006       {NULL}  /* Sentinel */
01007   };
01008   
01009   static PyTypeObject lazylinker_ext_CLazyLinkerType = {
01010   #if defined(NPY_PY3K)
01011       PyVarObject_HEAD_INIT(NULL, 0)
01012   #else
01013       PyObject_HEAD_INIT(NULL)
01014       0,                         /*ob_size*/
01015   #endif
01016       "lazylinker_ext.CLazyLinker",             /*tp_name*/
01017       sizeof(CLazyLinker), /*tp_basicsize*/
01018       0,                         /*tp_itemsize*/
01019       CLazyLinker_dealloc,       /*tp_dealloc*/
01020       0,                         /*tp_print*/
01021       0,                         /*tp_getattr*/
01022       0,                         /*tp_setattr*/
01023       0,                         /*tp_compare*/
01024       0,                         /*tp_repr*/
01025       0,                         /*tp_as_number*/
01026       0,                         /*tp_as_sequence*/
01027       0,                         /*tp_as_mapping*/
01028       0,                         /*tp_hash */
01029       CLazyLinker_call,          /*tp_call*/
01030       0,                         /*tp_str*/
01031       0,                         /*tp_getattro*/
01032       0,                         /*tp_setattro*/
01033       0,                         /*tp_as_buffer*/
01034       Py_TPFLAGS_DEFAULT|Py_TPFLAGS_BASETYPE,        /*tp_flags*/
01035       "CLazyLinker object",      /* tp_doc */
01036       0,                         /* tp_traverse */
01037       0,                         /* tp_clear */
01038       0,                         /* tp_richcompare */
01039       0,                         /* tp_weaklistoffset */
01040       0,                         /* tp_iter */
01041       0,                         /* tp_iternext */
01042       0,//CLazyLinker_methods,       /* tp_methods */
01043       CLazyLinker_members,       /* tp_members */
01044       CLazyLinker_getset,        /* tp_getset */
01045       0,                         /* tp_base */
01046       0,                         /* tp_dict */
01047       0,                         /* tp_descr_get */
01048       0,                         /* tp_descr_set */
01049       0,                         /* tp_dictoffset */
01050       (initproc)CLazyLinker_init,/* tp_init */
01051       0,                         /* tp_alloc */
01052       CLazyLinker_new,           /* tp_new */
01053   };
01054   
01055   static PyObject * get_version(PyObject *dummy, PyObject *args)
01056   {
01057     PyObject *result = PyFloat_FromDouble(0.211);
01058     return result;
01059   }
01060   
01061   static PyMethodDef lazylinker_ext_methods[] = {
01062     {"get_version",  get_version, METH_VARARGS, "Get extension version."},
01063     {NULL, NULL, 0, NULL}        /* Sentinel */
01064   };
01065   
01066   #if defined(NPY_PY3K)
01067   static struct PyModuleDef moduledef = {
01068           PyModuleDef_HEAD_INIT,
01069           "lazylinker_ext",
01070           NULL,
01071           -1,
01072           lazylinker_ext_methods,
01073           NULL,
01074           NULL,
01075           NULL,
01076           NULL
01077   };
01078   #endif
01079   #if defined(NPY_PY3K)
01080   #define RETVAL m
01081   PyMODINIT_FUNC
01082   PyInit_lazylinker_ext(void) {
01083   #else
01084   #define RETVAL
01085   PyMODINIT_FUNC
01086   initlazylinker_ext(void) 
01087   {
01088   #endif
01089       PyObject* m;
01090   
01091       lazylinker_ext_CLazyLinkerType.tp_new = PyType_GenericNew;
01092       if (PyType_Ready(&lazylinker_ext_CLazyLinkerType) < 0)
01093           return RETVAL;
01094   #if defined(NPY_PY3K)
01095       m = PyModule_Create(&moduledef);
01096   #else
01097       m = Py_InitModule3("lazylinker_ext", lazylinker_ext_methods,
01098                          "Example module that creates an extension type.");
01099   #endif
01100       Py_INCREF(&lazylinker_ext_CLazyLinkerType);
01101       PyModule_AddObject(m, "CLazyLinker", (PyObject *)&lazylinker_ext_CLazyLinkerType);
01102   
01103       return RETVAL;
01104   }
01105   
Problem occurred during compilation with the command line below:
"C:\Strawberry\c\bin\g++.exe" -shared -g -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"C:\Anaconda2New\lib\site-packages\numpy\core\include" -I"C:\Anaconda2New\include" -I"C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\gof" -L"C:\Anaconda2New\libs" -L"C:\Anaconda2New" -o C:\Users\brandenyang\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_79_Stepping_1_GenuineIntel-2.7.13-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\brandenyang\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_79_Stepping_1_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp -lpython27
Traceback (most recent call last):

  File "<ipython-input-1-3397704bd624>", line 1, in <module>
    import theano

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\__init__.py", line 66, in <module>
    from theano.compile import (

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\compile\__init__.py", line 10, in <module>
    from theano.compile.function_module import *

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\compile\function_module.py", line 21, in <module>
    import theano.compile.mode

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\compile\mode.py", line 10, in <module>
    import theano.gof.vm

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\gof\vm.py", line 662, in <module>
    from . import lazylinker_c

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)

  File "C:\Users\brandenyang\AppData\Roaming\Python\Python27\site-packages\theano\gof\cmodule.py", line 2316, in compile_str
    (status, compile_stderr.replace('\n', '. ')))

. ception: Compilation failed (return status=1): C:\Users\brandenyang\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_79_Stepping_1_GenuineIntel-2.7.13-64\lazylinker_ext\mod.cpp:1: sorry, unimplemented: 64-bit mode not compiled in

**Comment by lamblin** [comment]
- you seem to be using an old version of Theano, currently the full source code is dumped into a temporary file
- The error message is `sorry, unimplemented: 64-bit mode not compiled in` and comes from `g++`. It means that `C:\Strawberry\c\bin\g++.exe` is a 32-bit compiler, but your installation of Python (through Anaconda) is 64-bit.
- You could try to install Conda package `m2w64-toolchain` instead, as mentioned [here](http://deeplearning.net/software/theano/install_windows.html#install-requirements-and-optional-packages), and make sure that version of `g++` is the one that gets called
- This is not the right place to request support, as we try to keep tickets about bug reports.
