### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by jiqiujia** [Theano/Theano#5928]
I use the latest theano 0.9. And I set .theanorc as follows as suggested by [http://deeplearning.net/software/theano/tutorial/using_gpu.html](url)
`[global]
floatX=float32
device=cuda
cast_policy=numpy+floatX
[nvcc]
fastmath=True
arch=sm_50
optimizer=fast_compile`

But I got the following error:

> ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
> Traceback (most recent call last):
>   File "/home/dl/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 175, in <module>
>     use(config.device)
>   File "/home/dl/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 162, in use
>     init_dev(device, preallocate=preallocate)
>   File "/home/dl/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 65, in init_dev
>     sched=config.gpuarray.sched)
>   File "pygpu/gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:9415)
>   File "pygpu/gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9106)
>   File "pygpu/gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:13468)
> GpuArrayException: Unknown device error: -1

If I set `device=cuda0`, the program goes well.
By the way, I install the libgpuarray backend using `conda install pygpu`  and I have three nvidia xp cards installed.

**Comment by jiqiujia** [comment]
I update the graphic card driver to 375 and everything goes well now. But I wonder if there is a feasible way to specify which card to use programmatically?

**Comment by lamblin** [comment]
You could use `device=cpu`, and then manually call `theano.gpuarray.use()` after you determine which GPU you want.

**Comment by alyato** [comment]
hi i meet this error.
Then i run the `python -c "import pygpu;pygpu.test()"`
it show me that 
![34](https://cloud.githubusercontent.com/assets/6815071/26773894/f7a68c98-49ff-11e7-960a-fe536a7d12d1.png)

like:https://stackoverflow.com/questions/43577788/error-loading-library-gpuarray-with-theano

my os is 14.04, the version of cuda is `7.0`
how to solve it ? THanks.

**Comment by jiqiujia** [comment]
@alyato It seems that you are using the system python environment and you install pygpu by pip. I would suggest you do as the answer said from the link you post. That is,
> completely uninstall python [ If you use the system python environment, don't do this, or your system will crash ]
> install cuda 8.0 (with cudnn 5.1)
> install anaconda
> install theano through anaconda: conda install theano pygpu

**Comment by nouiz** [comment]
The pygpu test error are due to the fact that you didn't told him which GPU
to use for the tes. You can do it with:

DEVICE=cuda0 python -c "import pygpu;pygpu.test()"

**Comment by alyato** [comment]
@nouiz @jiqiujia  Thanks. It works now.

**Comment by alyato** [comment]
hi @nouiz ,i meet another question by installing libgpyarray  in another os.
when i run  `python setup.py build` in libgpuarray
it show me that

> Exception: cython is too old or not installed (at least 0.25 required)

Then i  install the cython.

> cython --version
   Cython version 0.25.1

Then i rerun `python setup.py build` ,it also show me the same error.
> Exception: cython is too old or not installed (at least 0.25 required)

it's so crazy. Do you give me some advice? Thanks.

**Comment by lamblin** [comment]
You may have more than one version of cython installed. The one first picked up in the command line may not be the same as the one imported from python.

**Comment by Lan1991Xu** [comment]
Hi  @jiqiujia. I meet the same problem, but my  Driver Version already : 375.66. So any suggestions about this situation

**Comment by nouiz** [comment]
Install Theano dev version of the last beta. This should include the fix. Don'T use Theano 0.9

**Comment by wyichew2708** [comment]
I spent 1 day try to solve this problem. 
Finally, i decided to change device = cpu.
easy way, although it's compiled slower than gpu.
