### ISSUE TITLE
Theano cannot compile with cudnn

### ISSUE THREAD

**Issue by xiaotangfeidao** [Theano/Theano#5933]
**I am trying to run the Theano GPU test**

from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')

**and getting the following error**

Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'g++.exe: error: C:\\Program: No such file or directory\r\ng++.exe: error: Files\\Microsoft\\R: No such file or directory\r\ng++.exe: error: Server\\R_SERVER\\DeployR\\rserve\\workdir\\tmp\\try_flags_9v9qtupn.c: No such file or directory\r\ng++.exe: error: Files\\Microsoft\\R: No such file or directory\r\ng++.exe: error: Server\\R_SERVER\\DeployR\\rserve\\workdir\\tmp\\try_flags_9v9qtupn: No such file or directory\r\n'
Mapped name None to device cuda: Tesla K80 (77CB:00:00.0)

**output**
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float32, (False,))>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.297524 seconds
Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
  1.62323296]
Used the gpu

**Here is my .theanorc**

[global]
floatX = float32
device = cuda

[gcc]
cxxflags = -shared -I-IC:\Users\f401074\Anaconda3\envs\deeplearning\Library\mingw-w64\include -DMS_WIN64

[dnn]
library_path = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64
include_path = C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include

[lib]
cnmem = 1

**Comment by lamblin** [comment]
You can try to:
- upgrade to the latest development version of Theano from GitHub, or
- use path without spaces for your temporary directory (rather than `C:\Program Files\Microsoft\R Server\R_SERVER\DeployR\rserve\workdir`)

**Comment by nouiz** [comment]
The first (use Theano dev version) should fix this. There is fix to that
since the last release.
