### ISSUE TITLE
images2neibs with border_mode=half

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5938]
Is there any way to perform `theano.tensor.nnet.neighbours.images2neibs` with the equivalent to `boreder_mad=half` of the standard 2D Convolution, without explicitly construing the padded image tensor?

**Comment by nouiz** [comment]
We need someone to implement it. Currently it isn't.

**Comment by botev** [comment]
Do you know who worked on the `Images2Neibs` op both in the nnet and gpuarray, as the C does not look too pretty and there is some interaction with PyObjects in C, but on the other hand the change should not be particularly difficult?

**Comment by nouiz** [comment]
I forgot so worked on it. The GPU array version is just a port of the old
backend version. To know who worked on it, check git history on the files.

Le jeu. 11 mai 2017 19:20, Alexander Botev <notifications@github.com> a
écrit :

**Comment by botev** [comment]
@nouiz So I have a question, since I've managed to get on the CPU working implementation, but I'm not sure a bit about performance:

In the numpy version the output array is initialized to empty. This means that for padding I have to fill in the 0s. However, if it is initialized to 0s you can skip these iterations. Would it make sense to initialize it to 0 and would the overhead of filling it with zeros be more (or any intuition on this)?
Similarly, the same consensus on the CPU (C) version and for the GPU?

**Comment by botev** [comment]
@nouiz Could you tell me how I can run only the tests_neighoburhood.py and could someone review the code briefly.

**Comment by lamblin** [comment]
You can run the code manually with `theano-nose .../theano/tensor/nnet/tests/test_neighbours.py` (or `nosetests` instead of `theano-nose`).

**Comment by botev** [comment]
I've made a pull request.
