### ISSUE TITLE
Can Theano to work in Windows?

### ISSUE THREAD

**Issue by AgataShell** [Theano/Theano#5968]
For many days I've been trying to get to work the theano. Constantly there are problems. When I solve them, new problems arise.

Please tell me the theano can work in Windows at all?

I'm using Windows 7/10 and Anaconda 3.

**Comment by sjm1992st** [comment]
yeah,I could run Theano 0.8.2 on win7 use anaconda2

**Comment by nouiz** [comment]
Use the conda packages:

conda install theano

for the GPU:

conda install pygpu
