### ISSUE TITLE
ImportError: No module named cuda.var in theano version 0.9.0

### ISSUE THREAD

**Issue by AnushaManila** [Theano/Theano#5971]
I have installed Theano==0.9.0 version.
Since import as_cuda_ndarray_variable from theano.sandbox.cuda.basic_ops is not available in release version 0.9.0, I guess the equivalent module is from theano.sandbox.cuda.var import CudaNdarraySharedVariable. But it gives import error as the title says No module named cuda.var.

Similarly, I am searching the equivalent for below modules
1.host_from_gpu
2.gpu_alloc_empty

The exact line which throws the error is as shown below:
from theano.sandbox.cuda.basic_ops import (as_cuda_ndarray_variable,
host_from_gpu,
gpu_contiguous, HostFromGpu,
gpu_alloc_empty)

I'm unsure if this is a bug or am I doing something wrong.
Any help is appreciated. Thank you in advance.

**Comment by lamblin** [comment]
How did you install Theano?
`as_cuda_ndarray_variable` and `CudaNdarraySharedVariable` are completely different things.
If you are using the latest dev version, `theano.sandbox.cuda` has been completely removed. Please use `theano.gpuarray` and follow the instructions on https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)
