### ISSUE TITLE
A new problem when I try to "import theano"

### ISSUE THREAD

**Issue by rnunziata** [Theano/Theano#5972]
This problem does not occure in caffe or tensorflow but seems to be unique to theano. I have tried to follow  various solutions suggested but none seem to resolve this issue.
```

>>> import theano
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 1060 (CNMeM is enabled with initial size: 100 MB, cuDNN Mixed dnn version. The header is from one version, but we link with a different version (6021, 5005))
```

**Comment by ReyhaneAskari** [comment]
Your code should be running as usual. This is just a warning that happens when you use the old backend of theano and specifically you are setting the ```THEANO_FLAGS=device=gpu```. The old backend is going to be removed in the next release of theano. You should set the  device to ```cuda``` (```THEANO_FLAGS=device=cudaa```) if you do not want to see the warning and want a small speedup. For more instructions you can visit  [here](https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29. )

**Comment by rnunziata** [comment]
I was under the assumtion this message was related to the error that followed it:  Which I did not post the whole of the output as it was long and I thought the message I posted on this issue was descriptive.

`Exception: ('The following error happened while compiling the node', GpuDnnSoftmax{tensor_format='bc01', mode='channel', algo='log'}(GpuContiguous.0), '\n', "We can't determine the cudnn version as it is not available", 'Mixed dnn version. The header is from one version, but we link with a different version (6021, 5005)')
`

**Comment by ReyhaneAskari** [comment]
How do you set your device? Have you recently updated your cudnn? You might have multiple installations. You can try these:
- delete your ```.pyc``` files 
- delete your theano cache
- delete your cudnn and reinstall

**Comment by rnunziata** [comment]
sorry...same error. I should not have different version since this is the first time I am using this and also I know tensorflow and caffe both work on my system. Is there any way to analyze this further ... can I search for the headers in question ? Where is it getting the numbers  (6021, 5005) from. The 6021 is the cudnn version I downloaded for cuda 8.0 which is required for unbuntu 16 with gtx1060

**Comment by lamblin** [comment]
That version is defined in the header for cuDNN, and should correspond to the name of the compiled library as well. Do you have a libcudnn.so.5 on your system?

**Comment by rnunziata** [comment]
yes : see below
```
(cvp3) richard@rjn:~$ sudo find . / -name libcudnn.so.5

/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.5
```
I also have:

```
(cvp3) richard@rjn:~$ sudo find . / -name libcudnn.so.6
/usr/local/cuda-8.0/targets/x86_64-linux/libcudnn.so.6
/usr/lib/x86_64-linux-gnu/libcudnn.so.6
/usr/libx86_64-linux-gnu/libcudnn.so.6

```

**Comment by lamblin** [comment]
So, here is your problem: you have the header for cuDNN 6 only, but you are trying to link with cuDNN 5.

If you want to use cuDNN 5, make sure that there is a cudnn.h with version 5 in `/home/richard/cudnn-5.0/include`.
If you want to use cuDNN 6, then use `/usr/local/cuda-8.0/targets/x86_64-linux/` or `/usr/lib/x86_64-linux-gnu/` in `LD_LIBRARY_PATH` and `LIBRARY_PATH`, rather than `/home/richard/cudnn-5.0/lib64`.

**Comment by rnunziata** [comment]
Thank you for the insight....that seems to have resolved the issue.

**Comment by Hoototo** [comment]
Hello, I met the similar problem. Could you help me to solve it?
ImportError: cuDNN not available: Mixed dnn version. The header is from one version, but we link with a different version (5110,6021)

**Comment by nouiz** [comment]
You have many version of cudnn in your system. Delete all of them. Then reinstall the latest version.

**Comment by Hoototo** [comment]
Thanks for your reply@nouiz 
And I share the server with other colleague. I want to choose another specific GPU to run(gpu2), but it failed. 

The content of the file .theanorc is:
[global]
device = gpu2
floatX = float32

[nvcc]
fastmath = True

[lib]
cnmem = 0.0

**Comment by nouiz** [comment]
I don't recommand you continue to use that old Theano version. Update at least to the 0.9 version.

Your have a problem that isn't related to Theano, but to your computer configuration. The cuda driver can hide GPUs to the Theano process with the environment variable CUDA_VISIBLE_DEVICES. Make sure it isn't set. If it is set, check with your system admin. If they added that, they probably have a good reason for that.

Also, the name of the GPU GTX 1090 and GTX 1089 are strange. I don't know such product on the market? Make sure you don't have a bad driver. Maybe a reboot could also help.

**Comment by Light--** [comment]
How to solve this?
```
Traceback (most recent call last):
  File "/home/user/test.py", line 11, in <module>
    import theano
  File "/home/user/.local/lib/python2.7/site-packages/theano/__init__.py", line 156, in <module>
    import theano.gpuarray
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 33, in <module>
    from . import fft, dnn, opt, extra_ops, multinomial, reduction, sort, rng_mrg, ctc
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/fft.py", line 14, in <module>
    from .opt import register_opt, op_lifter, register_opt2
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/opt.py", line 2812, in <module>
    from .dnn import (local_abstractconv_cudnn,
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 339, in <module>
    handle_type = CUDNNDataType('cudnnHandle_t', 'cudnnDestroy')
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 259, in CUDNNDataType
    version=version(raises=False))
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 319, in version
    if not dnn_present():
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 209, in dnn_present
    dnn_present.avail, dnn_present.msg = _dnn_check_version()
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 180, in _dnn_check_version
    v = version()
  File "/home/user/.local/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 334, in version
    "while the library is version %s." % v)
RuntimeError: Mixed dnn version. The header is version 7005 while the library is version 7604.
```

**Comment by nouiz** [comment]
You have multiple cudnn version installed. Remove all of them, then reinstall one of them.

**Comment by Light--** [comment]
> You have multiple cudnn version installed. Remove all of them, then reinstall one of them.

No other way to seperate them to use one at a time??

**Comment by IveJ** [comment]
Hi Issuer,

Let try container if any help.

**Comment by nouiz** [comment]
Yes it can be done. But they are already fixed in your environment. This isn't easy to fix indirectly via github. That is why I recommend to remove all of them. But if someone with good OS knowledge can access the box, they could fix it while keeping many version in a way that isn't mixed in the environment.

________________________________

**Comment by IveJ** [comment]
Hi friend,

virtual enviroment for this issue.
