### ISSUE TITLE
Regression - Incorrect shapes when running on GPU

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5975]
So I have a model which runs fine on a CPU, tested on several platforms. For various reasons I needed the latest Theano branch. Running the code on the GPU I get:
```
  File "bin/run.py", line 58, in train
    results[i, 1] = train_f(*data_transform(x, y))
  File "/share/apps/barber/clones/Theano/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/share/apps/barber/clones/Theano/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/share/apps/barber/miniconda3/envs/py35/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/share/apps/barber/clones/Theano/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[0] == 1000, but the output's size on that axis is 513.
Apply node that caused the error: GpuElemwise{mul}[]<gpuarray>(GpuDot22.0, GpuElemwise{Composite{(i0 - sqr(i1))}}[]<gpuarray>.0)
Toposort index: 336
Inputs types: [GpuArrayType<None>(float32, matrix), GpuArrayType<None>(float32, matrix)]
Inputs shapes: [(513, 512), (1000, 512)]
Inputs strides: [(2048, 4), (2048, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuDot22(GpuElemwise{mul}[]<gpuarray>.0, InplaceGpuDimShuffle{1,0}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f348870fd08>
Traceback (most recent call last):
  File "/share/apps/barber/miniconda3/envs/py35/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```
This most obviously is an GPU optimization which have forgot to make the transpose of the right matrix in this GEMM. 
Actually, how is this even possible that somehow this works fine on the CPU on various platforms and variations, but the GPU gives such error? These are the bloody shapes it can not be that wrong and the shapes are fixed across iterations.

**Comment by nouiz** [comment]
Hi,

the error is generated by an GpuElemwise operation. This client is a GpuDot22. This mean the dot use the output of the GpuElemwise, but the problem is with GpuElemwise.

Did you try with the recent Theano version on CPU too? Can you confirm that it is working?

Do you use Keras and did you update it at the same time as Theano?

If you have the same problem on CPU, can you try it again on CPU with optimizer=fast_compile?

If you don't have the same problem on CPU, can you try it again on GPU with mode=DebugMode,DebugMode.patience=1,DebugMode.check_py=False? It will be super slow, but it should tell us which Theano optimization introduced the crash.

**Comment by botev** [comment]
@nouiz Ah sorry for this - we were traversing the graph for finding specific ops and did not expect that the graph was different for the CPU and GPU, thus rather than passing smth that had to be a Dot we were passing the HostToGPU and the sizes did not match. Totally my bad!

**Comment by nouiz** [comment]
Few people traverse the graph themself. I would like to know more of when
you need this. There is also some functions inside theano/gof/graph.py that
help the navigation, but don't have documentation on the web site. We could
add that if useful.

So, why do you need to traverse the graph and what manipulation you do?

**Comment by botev** [comment]
Well, I can't give out too many details as we are preparing to release some very nice things integrated into Lasagne as part of our publication and efforts on very scalable Second Order methods for NN. But, we basically needed to code up a "curvature" backprop trough the network on the `Layer` level. To be consistent with the API we have to do this after the user has fetched all the outputs and gradients. However, on this backprop for `DenseLayer` for instance, I can pass only the input and the output of the layer, but in fact, I need the pre-activation (e.g. the T.dot(x, W)) which is somewhere in the middle between the input, parameters and the output. Also since the nonlinearity can be arbitrary I can't rely on it being the "1 hop away" node from the output. As a result, I had to do a DFS backwards from the output to the weight matrix until and then look on the path until I hit a `Dot` operator.

**Comment by nouiz** [comment]
thanks for the explanation. When the paper is out, I will read it.

**Comment by chih-hong** [comment]
I have same problem with using GPU.
How to deal with it ?

**Comment by chih-hong** [comment]
Like this 
Traceback (most recent call last):
  File "sca_resnet_branch2b.py", line 1428, in <module>
    train()
  File "sca_resnet_branch2b.py", line 1266, in train
    cost = f_grad_shared(x, mask, ctx_res5b, ctx_res5c_branch2b)
  File "/home/sca_test/anaconda3/envs/Sca/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/sca_test/anaconda3/envs/Sca/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/sca_test/anaconda3/envs/Sca/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
ValueError: Input dimension mis-match. (input[0].shape[1] = 512, input[1].shape[1] = 2048)
Apply node that caused the error: Elemwise{Composite{(i0 + (((i1 - i2) / i3) * i4) + i5)}}(ctx_res5b, CorrMM{valid, (1, 1), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0, Elemwise{Composite{sqrt((i0 + i1))}}.0, InplaceDimShuffle{x,0,x,x}.0, InplaceDimShuffle{x,0,x,x}.0)
Toposort index: 268
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True)), TensorType(float32, (True, False, True, True))]
Inputs shapes: [(64, 512, 7, 7), (64, 2048, 7, 7), (1, 2048, 1, 1), (1, 2048, 1, 1), (1, 2048, 1, 1), (1, 2048, 1, 1)]
Inputs strides: [(100352, 196, 28, 4), (401408, 196, 28, 4), (8192, 4, 4, 4), (8192, 4, 4, 4), (8192, 4, 4, 4), (8192, 4, 4, 4)]
Inputs values: ['not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 * (i1 + Abs(i1)))}}(TensorConstant{(1, 1, 1, 1) of 0.5}, Elemwise{Composite{(i0 + (((i1 - i2) / i3) * i4) + i5)}}.0), Elemwise{Composite{((((i0 * i1) + (i0 * i1 * sgn(i2))) * i3) / i4)}}[(0, 1)](TensorConstant{(1, 1, 1, 1) of 0.5}, AveragePoolGrad{ignore_border=True, mode='average_exc_pad', ndim=2}.0, Elemwise{Composite{(i0 + (((i1 - i2) / i3) * i4) + i5)}}.0, InplaceDimShuffle{x,0,x,x}.0, Elemwise{Composite{sqrt((i0 + i1))}}.0)]]
