### ISSUE TITLE
Official Logo and T-shirts

### ISSUE THREAD

**Issue by botev** [Theano/Theano#5984]
So, recently I thought since a lot of the frameworks backed by industry get a lot more PR and Advertising I wanted to somehow promote Theano. As such I've decided that potentially I want to make a T-shirt for myself for ICML with the Theano Logo to promote it. Thus two questions come up:

1. Does Theano have an official logo or at least an image of it that I can use.
2. Am I legally allowed to put it on a T-shirt for myself, or on T-shirt for other people (e.g. giveaways) as long it is not for commercial purposes?

**Comment by nouiz** [comment]
The logo we have are here: https://github.com/Theano/Theano/tree/master/doc/images

I don't see problems with someone making T-shirt of Theano if this is not commercial. But I'll ask a few other people here in case they are a different opinion.

**Comment by nouiz** [comment]
You can go for it.

**Comment by botev** [comment]
Thanks!

**Comment by MurugeshMarvel** [comment]
thats nice botev, we need some promotions for surviving in the industries.

**Comment by Sentient07** [comment]
Is there a way I could get it if I am not going to be at ICML ?

**Comment by botev** [comment]
@Sentient07 I can share a T-shirt design. Otherwise I'm just a PhD student so I can't really afford to send them around :D

**Comment by Sentient07** [comment]
Sure, I would like to pay, but that would commercialise it. @nouiz could something be done from MILA for stickers and T-shirts ? It would be amazing in that case :-)

**Comment by nouiz** [comment]
I would be surprised we can pay for such thing, but I'll ask.

I don't know how exactly it is, but there is compagnies outside that could
make them on order if there is a design. So everybody could order there own
and pay for it. I don't know enough those compagnies, so I don't know how
the price would change based on quantities.

**Comment by Sentient07** [comment]
> So everybody could order there own and pay for it. 

I think this is perfect, but I thought it would be commercialising. For the ICML, it would be great if some industrial giants could support us to give takeaways. But I am not sure how that works

**Comment by botev** [comment]
@nouiz Is there any moto (or smth like that) of Theano which we can add together with the logo?

**Comment by nouiz** [comment]
There isn't one existing. Do you want to start a thread on theano-user
about that?

A first idea (but probably not very good): Theano the first ML/DL compiler!

**Comment by botev** [comment]
Let's hope people participated: https://groups.google.com/forum/#!topic/theano-users/Z7dv-9VrNmY

**Comment by affanv14** [comment]
This is a great idea! i'd like the t-shirt design as  well.
As for the moto, here is a suggestion:
'dive DEEP into machine learning'

**Comment by botev** [comment]
Actually, where did the initial inspiration for the name `Theano` came up from?

**Comment by nouiz** [comment]
It is the dauther of pythagoras.

**Comment by MurugeshMarvel** [comment]
We dont want to narrow theano usage by mentioning the word machine learning,.. its for general research purpose.
