### ISSUE TITLE
erroneous dnn_conv result with algo 'small' an large batches

### ISSUE THREAD

**Issue by astooke** [Theano/Theano#5985]
Hi,

I have a call to a forward pass through a convnet using `theano.gpuarray.dnn.dnn_conv()` as the convolution for a Lasagne `Conv2DLayer`.  It gives erroneous results from forward pass for `dnn.conv.algo_fwd=small` and for large batch sizes.  Has anyone had this problem?  Might be a cuDNN thing?

I found that if I compute some values using the entire batch in one function call, they are not the same as when calling the function multiple times using only a subset of the data each time.  The effect kicks in at batch size about 70,000 in my case, corresponding to about a couple of GBs.  Instead of the comparison result returning `0.0`, it will be at least `1e-5`.  Another strange thing is that as my algorithm progresses, checking the batch vs multi-call results in values at each iteration, the comparison gradually diverges to values much greater than one.  

Calling the GPU function on data subsets is stable and results in overall comparison `1e-9` or less against values computed on the CPU.  When computing everything on the CPU, it works fine.

I pulled latest Theano and built latest libgpuarray / pygpu today.

CuDNN 6020, CUDA 8.  GTX 1080 (8GB)

Any ideas?  

Thanks,
Adam

**Comment by nouiz** [comment]
It is possible the is a problem at 2g. From memory, some of cuddn size are
passed as int. Maybe we don't always check that we fit.

**Comment by lamblin** [comment]
Do earlier versions of cuDNN work?

**Comment by notoraptor** [comment]
Hello, @astooke ! Could you give the full shape of your inputs and filters, and also the subsample, dilation, border mode, dtype and precision that you use ?

**Comment by notoraptor** [comment]
NB: Ultimately, it seems I can reproduce the problem.
