### ISSUE TITLE
ValueError: You are tring to use the old GPU back-end. It was removed from Theano. 

### ISSUE THREAD

**Issue by alyato** [Theano/Theano#5997]
hi, i upgrade the theano but it show me 

> ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda* now. See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 for more information.

I don't know how to solve it easily. Can everyboby give me some advices? Thanks

**Comment by lamblin** [comment]
The link you quoted will have most of the information.
You can also check theano-users for information, or post there if you have more precise questions.

**Comment by alyato** [comment]
hi @lamblin I‘m using the keras based on theano. Does i change some code about keras?  Thanks.

**Comment by lamblin** [comment]
I think Keras should support the new back-end.

**Comment by caiexu** [comment]
Hi do you address this problem I meet the same issue to you, can you help me, thank you so much

**Comment by nouiz** [comment]
As the error say, look at this URL: https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Or use an older Theano version.
