### ISSUE TITLE
python will crash when adding dnn path on winows7

### ISSUE THREAD

**Issue by Imorton-zd** [Theano/Theano#6008]
Related infomation:
```
Anaconda2-4.3.1-Windows-x86_64
cuda_8.0.61_windows
the newest theano
cudnn-8.0-windows7-x64-v5.1
Geforce GTX 1080 Ti 382.33
```

.theanore.txt
```
[gpuarray]
preallocate=0.5
[gcc]
cxxflags = -IC:\Anaconda2\MinGW
[global]
openmp = False 
device=cuda 
floatX = float32
optimizer_including=cudnn 
allow_input_downcast=True
optimizer=fast_run
[nvcc]
fastmath = True
[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
[dnn]
enabled = True
include_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include
library_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64
```
If I test the file, I will get the crash as the picture below, which means that `python.exe` has stopped working
```
import theano
from theano import function, config, shared, sandbox
import theano.tensor as T
import numpy
import time

vlen = 10 * 6 * 24  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(
    value=numpy.asarray(
        rng.rand(vlen),
        dtype=config.floatX
        ),
    name='x',
    borrow=True
    )
f = function(inputs=[], outputs=T.exp(x))
print f.maker.fgraph.toposort()
t0 = time.time()
for i in xrange(iters):
    r = f()
t1 = time.time()
print 'Looping %d times took' % iters, t1 - t0, 'seconds'
print 'Result is', r
if numpy.any([isinstance(x.op, T.Elemwise) for x in f.maker.fgraph.toposort()]):
    print 'Used the cpu'
else:
    print 'Used the gpu'
```
![qq 20170605171323](https://cloud.githubusercontent.com/assets/13865086/26779921/eea8ab20-4a19-11e7-9f60-8c9e91e63dcd.png)

If I delete the `[dnn]` path, another error will happen.
![2](https://cloud.githubusercontent.com/assets/13865086/26780015/5b3a73ae-4a1a-11e7-8294-5a71a5c3177d.png)

**Comment by nouiz** [comment]
Make sure to use the latest development version of Theano, not the latest release. You seem to have spaces in your path and there was fixes related to that since the last release.

**Comment by Imorton-zd** [comment]
Hi, @nouiz, thanks for your reply. I have installed the latest development version of Theano, using the command: "pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps". But this error still exists. And Where does my path have spaces as you said? Please indicate the exact location.

**Comment by lamblin** [comment]
- The following paths contains spaces: `include_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/include`, `library_path=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64`
- Please remove the `[cuda]` and `[nvcc]` sections, they are not used by the new back-end.
- The main issue is that `cudnn.h` is not found, but you forced its use by setting `optimizer_including=cudnn`. Where is your `cudnn.h`?

**Comment by nouiz** [comment]
As no news and I think the last comment should resolve this, I'll close. If that don't fix your issue, don't hesitate to reopen/comment on this issue.

**Comment by Imorton-zd** [comment]
In fact, I turn back to the old type of theano and use the old cuda backend. I'm sorry that I can't solve the errors above about the new backend.
