### ISSUE TITLE
Tried to update backend, nothing has changed

### ISSUE THREAD

**Issue by kaare-mikkelsen** [Theano/Theano#6046]
As theano has been requesting for a while, I tried switching to the gpuarray backend. But it seems that the instructions are not sufficiently foolproof? 

I am using Windows. This is what I've done:

set up a new environment in anaconda, with python=3.5
Gone through http://deeplearning.net/software/theano_versions/dev/install_windows.html, making sure numpy, scipy, blas, mingw, nose, sphinx, pygments, pydot-ng, libgpuarray, pycuda and skcuda are installed in the new environment, with the right versions. Since I already had nvidia cuda drivers from my last install, I did not touch those.

I then typed conda install theano pygpu and let that run.

Finally "pip install keras", which should have me ready to go.

I fire up spyder, having activated the new environment - and I still get the 

"WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29"

My $USER/.theanorc looks like this:

[global]
floatX = float32
device = gpu

[nvcc]
flags=-LC:\Users\kaare\Anaconda3\libs
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

According to https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29, I should be able to remove the nvcc settings, but it seems that their existence should not be dictating anything?

 What is it that I don't understand?

**Comment by danielS91** [comment]
You have to set ``device``to ``cuda`` in your .theanorc in order to use the new backend.

**Comment by kaare-mikkelsen** [comment]
ok, changing that, I get this instead. can't tell if that's an improvement?

Using Theano backend.
C:\Users\kaare\Anaconda3\envs\py35_2\lib\site-packages\skcuda\cublas.py:282: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'C:\\Users\\kaare\\AppData\\Local\\Temp\\try_flags_qvb1ond_.c:4:19: fatal error: cudnn.h: No such file or directory\r\ncompilation terminated.\r\n'
Mapped name None to device cuda: GeForce GTX 960M (0000:01:00.0)

**Comment by danielS91** [comment]
Looks like that the compiler is not able to find the header file for cudnn. You can try to specify the path in your config as well using:
```
[dnn]
include_path=/path/to/header
library_path=/path/to/lib
```
(I assume that cudnn is insalled)

**Comment by danielS91** [comment]
btw, "Mapped name None to device cuda: GeForce GTX 960M (0000:01:00.0)" tells you that the new backend is used

**Comment by XuYunqiu** [comment]
hi, I have the same issue
I try to specify the path in my config,  but my python just quit for no reason
I use `windows10`, `cudnn5.1`, `cuda8.0,` `python3.5`, and `theano9.0`
