### ISSUE TITLE
Move C codes into a sub-folder `c_code` for each module

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6047]
As suggested by @nouiz , to help not have too many files in directories, C code files could be moved into separate sub-folder `c_code` in each module. For example, `theano/gpuarray/c_code` for all C code files in `theano/gpuarray` module (as done here: https://github.com/Theano/Theano/commit/5b6d3ac7bb74ef02e86d9091c80ca00e1f5c7e6d ).

What do you think, @abergeron @lamblin ?

**Comment by abergeron** [comment]
I am ok with moving to a sub-folder.  One thing to watch out for is to make sure that those sub-folders are included with installs.
