### ISSUE TITLE
Theano float64 warning and cpu fallback problem

### ISSUE THREAD

**Issue by jiqiujia** [Theano/Theano#6053]
I use theano 0.9. And through a analyzing function, I found some problem with my network.
`# Check for common problems in a compiled Theano function.

def analyze_function(func, verbose = False):

    assert isinstance(func, theano.compile.Function)

    topo = func.maker.fgraph.toposort()

    # Print stats.

    if verbose:

        op_names = [type(apply.op).__name__ for apply in topo]

        op_dict = {op: 0 for op in op_names}

        for op in op_names:

            op_dict[op] += 1

        op_list = op_dict.items()

        op_list.sort(key = lambda x: -x[1])

        print

        for op, num in op_list:

            print "  %-8d%s" % (num, op)

        print

    # Check for float64 use.

    for apply in topo:

        dtype = getattr(apply.outputs[0].type, 'dtype', '')

        acc_dtype = getattr(apply.op, 'acc_dtype', '')

        if dtype == 'float64' or acc_dtype == 'float64':

            print 'WARNING: Theano float64:', apply

            if verbose:

                print

                theano.printing.debugprint(apply)

                print

    # Check for excess GPU=>CPU transfers.

    for apply in topo:

        op = type(apply.op).__name__

        if op == 'HostFromGpu':

            for parent in topo:

                parent_inputs = [var.owner for var in parent.inputs]

                if apply in parent_inputs:

                    print 'WARNING: Theano CPU fallback:', parent

                    if verbose:

                        print

                        theano.printing.debugprint(parent)

                        print`
> WARNING: Theano float64: GpuCAReduceCuda{add}{2}(GpuReshape{3}.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{2}(GpuReshape{3}.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0}(InplaceGpuDimShuffle{0,2}.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0}(InplaceGpuDimShuffle{0,2}.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 1)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 1)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 1)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 1)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 1)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 3)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[(0, 1)]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{0, 2, 3}(GpuElemwise{Composite{((i0 * i1) + (i2 * i1 * sgn(i3)))}}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano float64: GpuCAReduceCuda{add}{1, 2, 3}(GpuElemwise{mul}[]<gpuarray>.0)
> WARNING: Theano CPU fallback: Shape_i{0}(HostFromGpu(gpuarray).0)
> WARNING: Theano CPU fallback: Shape_i{0}(HostFromGpu(gpuarray).0)
> WARNING: Theano CPU fallback: CrossentropyCategorical1HotGrad(HostFromGpu(gpuarray).0, HostFromGpu(gpuarray).0, labels)
> WARNING: Theano CPU fallback: CrossentropyCategorical1HotGrad(HostFromGpu(gpuarray).0, HostFromGpu(gpuarray).0, labels)
> WARNING: Theano float64: GpuCAReduceCuda{add}{2}(GpuReshape{3}.0)
> WARNING: Theano CPU fallback: Argmax(HostFromGpu(gpuarray).0, TensorConstant{(1,) of 1})

I wonder if these hurt computing performance a lot. And how could I correct these warnings?

**Comment by lamblin** [comment]
float64 for acc_dtype is not really an issue, it is only used internally when the operation is memory-bound.
Argmax does not have a GPU implementation for the moment, but we are working on one.
If you want to know if these hurt performance, try using [profiling](http://deeplearning.net/software/theano/tutorial/profiling.html).

**Comment by jiqiujia** [comment]
@lamblin , ok, thanks.
