### ISSUE TITLE
gpuarray implementation batched_dot grad error

### ISSUE THREAD

**Issue by tdihp** [Theano/Theano#6054]
Hi.

Here's my code: https://gist.github.com/tdihp/30e39ddbcb7d7e8428efc80c59c6b571

I've tried on both theano 0.9 and bleeding edge

My environment is AWS p2.xlarge (not sure if this reproduces on other GPUs though, that's my only cuda machine right now), ubuntu 14.04 with cuda 8.0 libcudnn 5.1. gpuarray is installed by anaconda.

with `THEANO_FLAGS='floatX=float32'` and `THEANO_FLAGS='floatX=float32,device=gpu'`, the results are the same.

However with `THEANO_FLAGS='floatX=float32,device=cuda'`, the result is different.

Would someone have a try, please?

**Comment by lamblin** [comment]
Which version of libgpuarray?

**Comment by lamblin** [comment]
I just tried with the dev version from libgpuarray and it appears to work for me.
If you are currently using 0.6.5, could you try the dev version?

**Comment by tdihp** [comment]
Ah...

My `pygpu.__version__` was 0.6.2

After updating pygpu in conda (now 0.6.4), the test code now works. However my actual model now doesn't compile on 0.6.4 (:P)

I'll try newer versions of libgpuarray. Thanks, @lamblin .

**Comment by tdihp** [comment]
I've updated both theano and libgpuarray (to dev), now I've got this error when I try to run the compiled function:

```
 ** On entry to SGEMM  parameter number 8 had an illegal value
Traceback (most recent call last):
  File "trainer.py", line 156, in <module>
    main()
  File "trainer.py", line 137, in main
    trainer.run_course()
  File "trainer.py", line 111, in run_course
    cost = updates_f(inputs, outputs, masks, learning_rate)
  File "/mnt/proj/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/mnt/proj/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/mnt/proj/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
RuntimeError: (cublas) Invalid value.
Apply node that caused the error: GpuGemmBatch{inplace=False}(GpuAllocEmpty{dtype='float32', context_name=None}.0, TensorConstant{1.0}, InplaceGpuDimShuffle{1,0,x}.0, InplaceGpuDimShuffle{0,2,1}.0, TensorConstant{0.0})
Toposort index: 479
Inputs types: [GpuArrayType<None>(float32, 3D), TensorType(float32, scalar), GpuArrayType<None>(float32, (False, False, True)), GpuArrayType<None>(float32, (False, True, False)), TensorType(float32, scalar)]
Inputs shapes: [(30, 32, 24), (), (30, 32, 1), (30, 1, 24), ()]
Inputs strides: [(3072, 96, 4), (), (4, 120, 3840), (96, 4, 4), ()]
Inputs values: ['not shown', array(1.0, dtype=float32), 'not shown', 'not shown', array(0.0, dtype=float32)]
Outputs clients: [[InplaceGpuDimShuffle{1,0,2}(GpuGemmBatch{inplace=False}.0)]]
```

**Comment by tdihp** [comment]
The odd bit in the exception might be the `InplaceGpuDimShuffle{1,0,x}.0`, which shouldn't be in that place.

I have a "mask" with the last dimension 'x', then element-wise multiply with the batched_dot output.  But it should be outside of the batched_dot op. I've checked both the CPU and CUDA version debugprint, the CPU version has a `InplaceDimShuffle{0,1,x}` outside of the BatchedDot op, I suppose some optimizer moved the dimshuffle into the BatchedDot?

**Comment by lamblin** [comment]
If I remember correctly, the CPU version of `BatchedDot` accepts both 2D and 3D inputs, but the GPU version needs 3D, so a `GpuDimShuffle` would be inserted by the lifter (optimization replacing the CPU op with the GPU one). Then, different DimShuffles can be combined by other optimizers.

I'll have another look.
Actually, maybe the merge of #6057 helped as well.

**Comment by tdihp** [comment]
Ah, now I see how my tensor got an 'x'. I use lasagne, and (Layer.add_param) would change 1 dimensions to 'x'. and my weight in BatchedDot had a last dimension of 1.

When I use weight param with different shape (no 1), the compiled graph is different, and the exception is no more.

I still wonder what's the behavior when broadcast dimensions exist though, as when using CPU graph, the output seems right.

**Comment by tdihp** [comment]
I've tried to use a batched_dot wrapper function so that broadcast won't affect the BatchedDot:

``` python
def batched_dot(a, b):
    return T.batched_dot(T.unbroadcast(a, 0, 1, 2), T.unbroadcast(b, 0, 1, 2))
```

However this surprisingly didn't work for me. I got a similar exception, without the broadcast shape, but still with incorrect shape as I would expect from the operation.

Is there any way I can step through every OP, and print all the input output shapes that has executed? (preferably alongside with the debugprint, but I know there's the case of scan)

While I found that `theano.printing.Print` [can be useful](https://aholzner.wordpress.com/2016/01/03/printing-a-tensors-shape-in-theano/), it failed with the following:

```
  File "/mnt/proj/anaconda2/lib/python2.7/site-packages/theano/compile/ops.py", line 697, in make_node
    if self.axis.keys() and (x.ndim <= max(self.axis.keys())):
AttributeError: 'Print' object has no attribute 'ndim'
```

**Comment by tdihp** [comment]
Ah, I've found [how-do-i-step-through-a-compiled-function](http://deeplearning.net/software/theano/tutorial/debug_faq.html#how-do-i-step-through-a-compiled-function)

**Comment by tdihp** [comment]
I managed to strip my model and reproduce the failure:

https://gist.github.com/tdihp/2edf7b3b1580a1abf9f47bcb160751a1

It seems ok without the gradient call, I added the sgd update to reproduce the error.

**Comment by tdihp** [comment]
@lamblin would you please try my script again? It should fail when using `device=cuda` and `outdim==1` (variable in main function).

I've shrunk down the test code more today, and I'm rather certain the error happens when:

- batched_dot stacks together
- final output shape with 3rd dim 1
- `T.grad` applied
- `device=cuda`

Thanks.

**Comment by tdihp** [comment]
The [script](https://gist.github.com/tdihp/2edf7b3b1580a1abf9f47bcb160751a1) worked with `gpuarray.preallocate=1`.

Since the error cublas error: ` ** On entry to SGEMM  parameter number 8 had an illegal value` is the pointer of A, maybe it's about allocation?

**Comment by tdihp** [comment]
After removing pygpu and libgpuarray from conda (then install bleeding edge), finally I found my script work correctly as expected. Thanks @lamblin.

**Comment by nouiz** [comment]
Note, libgpuarray was updated in conda. pygpu should be updated soon in
conda. So if in the futur someone found this issue, just update the conda
version of pygpu and libgpuarray.

**Comment by lamblin** [comment]
I just tried your updated script, with a recent (dev version) of libgpuarray and Theano, and it seems to work for me:
```
Using cuDNN version 5105 on context None
Mapped name None to device cuda0: GeForce GTX 750 Ti (0000:01:00.0)
[gpuarray.array([[[  6.73558607e-05,   1.12151625e-04,   4.82404248e-05, ...,
...
```

**Comment by lamblin** [comment]
(oops, too late).
