### ISSUE TITLE
Theano 0.10: ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by jingweimo** [Theano/Theano#6093]
I am using Theano 0.10. dev1 in win10. Other system settings include Python 2.7.13 |Anaconda 4.4.0 (64-bit), Nvidia Geforce940M and Cuda7.5. My .theanorc file is:

    [global]
    floatX = float32
    device = cuda0

    [cuda]
    root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5

    [nvcc]
    fastmath = True
    compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin

    [dnn] 
    #library_path = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\lib\x64
    #include_path = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include
    enabled = True

Then:
     `import theano `
gives the error message:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\Y L\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 179, in <module>
    use(config.device)
  File "C:\Users\Y L\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 166, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Users\Y L\Anaconda2\lib\site-packages\theano\gpuarray\__init__.py", line 77, in init_dev
    dnn.dnn_available.msg)
RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
c:\users\y~1\appdata\local\temp\try_flags_u5vegs.c:4:19: fatal error: cudnn.h: No such file or directory
compilation terminated.

```

Originally, I can work with theano by setting `[dnn] enable=False`, as reported in another issue :https://github.com/Theano/Theano/issues/6063.  In this case cudnn is deactivated. But there is indeed the need to enable cudnn in many cases.

**Comment by notoraptor** [comment]
Hello @jingweimo . GCC can't find `cudnn.h`. Try removing `#` before `include_path` and `library_path` into your `.theanorc.txt`. Also check that `cudnn.h` is indeed in folder `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include`.

**Comment by tswc** [comment]
Hallo @jingweimo ~ Sorry for 2 days late,
I am just following Tips of someone else and I am using Theano 0.10. But you can try it.
First, go to find this file.
`C:\Anaconda2\Scripts\g++.bat`

Then, change the file into
`@echo off
"%~f0\..\..\pkgs\m2w64-gcc-5.3.0.6\Library\mingw-w64\bin\g++.exe" %*`

This solved the problem of `c:4:19: fatal error: cudnn.h: No such file or directory
compilation terminated.`for me.

I hope this will be helpful

**Comment by jingweimo** [comment]
@tswc ： Thanks for your reply!  I will try your suggestion later
