### ISSUE TITLE
Import pygpu: ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by jingweimo** [Theano/Theano#6095]
I install theano following these steps:
`conda install numpy scipy mkl-service libpython m2w64-toolchain nose `
`pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git`
`conda install pygpu`

Then,
`import pygpu`
gives the error message:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-b22a183e5879> in <module>()
----> 1 import pygpu
D:\ProgramData\Anaconda2\lib\site-packages\pygpu\__init__.py in <module>()
      5     return p
      6
----> 7 from . import gpuarray, elemwise, reduction
      8 from .gpuarray import (init, set_default_context, get_default_context,
      9                        array, zeros, empty, asarray, ascontiguousarray,
pygpu\gpuarray.pyx in init pygpu.gpuarray (pygpu/gpuarray.c:38363)()
__init__.pxd in numpy.import_array (pygpu/gpuarray.c:34466)()
ImportError: numpy.core.multiarray failed to import


```

**Comment by lamblin** [comment]
Are you able to import numpy outside of pygpu?
Did you change things in your `%PATH%`?

**Comment by jingweimo** [comment]
@lamblin ： numpy can be imported successfully. What should I do with `%path%` ?

**Comment by lamblin** [comment]
There is nothing you _should_ do with `%path%`, I was just asking if you had changed it for some reason.
Is it possible you have more than one version of numpy installed on your system, maybe one installed by conda and another one with pip? If so, please uninstall them all, reinstall it from conda, and try again.
