### ISSUE TITLE
Theano works on old backend, "no attribute 'dtype_to_ctype' error" on new backend

### ISSUE THREAD

**Issue by datasci4** [Theano/Theano#6099]
I am using Windows 10/Python 3.5/Theano 0.9.0/pygpu 0.6.8 as downloaded using conda install and CUDA 8.0.

When I use the old backend, I get the following on `import theano` (it looks to be working);

> WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29
Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 70.0% of memory, cuDNN 5110)

When I change the .theanorc file to use device = cuda0 for the new backend and `import theano`, I get the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-3397704bd624> in <module>()
----> 1 import theano

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\theano\__init__.py in <module>()
    121         config.init_gpu_device.startswith('opencl') or
    122         config.contexts != ''):
--> 123     import theano.gpuarray
    124 
    125 # Use config.numpy to call numpy.seterr

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\theano\gpuarray\__init__.py in <module>()
     29                    GpuArraySharedVariable, gpuarray_shared_constructor,
     30                    reg_context, get_context, ContextNotDefined)
---> 31 from .basic_ops import as_gpuarray_variable
     32 from . import fft, dnn, opt, nerv, extra_ops, multinomial, reduction
     33 

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\theano\gpuarray\basic_ops.py in <module>()
     20 
     21 try:
---> 22     import pygpu
     23     from pygpu import gpuarray
     24 except ImportError:

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\pygpu\__init__.py in <module>()
      5     return p
      6 
----> 7 from . import gpuarray, elemwise, reduction
      8 from .gpuarray import (init, set_default_context, get_default_context,
      9                        array, zeros, empty, asarray, ascontiguousarray,

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\pygpu\reduction.py in <module>()
      7 
      8 from . import gpuarray
----> 9 from .tools import ScalarArg, ArrayArg, check_args, prod, lru_cache
     10 from .dtypes import parse_c_arg_backend
     11 

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\pygpu\tools.py in <module>()
     11 from .gpuarray import GpuArray
     12 
---> 13 _fill_dtype_registry()
     14 
     15 

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\pygpu\dtypes.py in _fill_dtype_registry()
     72 
     73 def _fill_dtype_registry():
---> 74     register_dtype(np.bool, ["ga_bool", "bool"])
     75     register_dtype(np.int8, ["ga_byte", "char", "signed char"])
     76     register_dtype(np.uint8, ["ga_ubyte", "unsigned char"])

C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\lib\site-packages\pygpu\dtypes.py in register_dtype(dtype, c_names)
     61     # register if not already there
     62     try:
---> 63         gpuarray.dtype_to_ctype(dtype)
     64     except ValueError:
     65         gpuarray.register_dtype(dtype, c_names[0])

AttributeError: module 'pygpu.gpuarray' has no attribute 'dtype_to_ctype'
```

I have tried unistalling/reinstalling the packages and creating a new conda environment but haven't had any luck. 

My .theanorc file looks like this:
```
[global]
floatX = float32
device = cuda0
cxx = C:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\Library\mingw-w64\bin\g++.exe

[gcc]
cxxflags = -LC:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\Library\mingw-w64\include -LC:\Users\B\AppData\Local\Continuum\Anaconda3\envs\env_full\Library\mingw-w64\lib -lm

[nvcc]
flags=--cl-version=2015 -D_FORCE_INLINES
compiler_bindir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin

[dnn]
enabled=True
```

Thank you

**Comment by lamblin** [comment]
Can you check that you have version 0.6.8 of both conda packages `libgpuarray` and `pygpu`?

**Comment by datasci4** [comment]
Yes, both libgpuarray and pygpu are version 0.6.8 installed with conda.

**Comment by nouiz** [comment]
Downgrade pygpu and libgpuarray array to 0.6.2 or update Theano to the dev
version.  This fixes problem for another user. It seem the last release of
Theano don't work well with the last release of pygpu and libgpuarray.

@abergeron

**Comment by zhouqun8508** [comment]
I have the same problem...but updating to dev version does not help...

**Comment by zhouqun8508** [comment]
Using device=cpu does not have the problem to import theano

**Comment by zhouqun8508** [comment]
cannot import pygpu...

**Comment by zhouqun8508** [comment]
interesting... when importing pygpu, just now the error was "module 'pygpu.gpuarray' has no attribute 'dtype_to_ctype'", but now it becomes "numpy.core.multiarray failed to import"

**Comment by abergeron** [comment]
Can you post the full output of the script?

**Comment by zhouqun8508** [comment]
I just uninstalled everything, and start installing miniconda instead of
full anaconda...I have been stuck on it for two days for getting the GPU
work. I will keep you posted...

**Comment by mhubii** [comment]
hey I am new but had a similar problem. 
I uninstalled pygpu via 'pip uninstall pygpu'
Now it works

**Comment by lubimov** [comment]
Hi,

I've had a similar problem and fixed it. There are steps which helped me.
1. First I'm run pygpu test.
```
python -c "import pygpu;pygpu.test()"
Traceback (most recent call last):
  File "__init__.pxd", line 987, in numpy.import_array (pygpu/gpuarray.c:34423)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Alexey\Miniconda3\envs\idp\lib\site-packages\pygpu\__init__.py", line 7, in <module>
    from . import gpuarray, elemwise, reduction
  File "pygpu\gpuarray.pyx", line 25, in init pygpu.gpuarray (pygpu/gpuarray.c:38363)
  File "__init__.pxd", line 989, in numpy.import_array (pygpu/gpuarray.c:34466)
ImportError: numpy.core.multiarray failed to import
```
2. Then I updated numpy `pip install numpy --upgrade`
That's all. 

```
(idp) D:\WORK\PyProject\TI-25>set DEVICE=cuda

(idp) D:\WORK\PyProject\TI-25>python -c "import pygpu;pygpu.test()"
pygpu is installed in C:\Users\Alexey\Miniconda3\envs\idp\lib\site-packages\pygpu
NumPy version 1.13.0
NumPy relaxed strides checking option: True
NumPy is installed in C:\Users\Alexey\Miniconda3\envs\idp\lib\site-packages\numpy
Python version 3.5.3 |Intel Corporation| (default, Apr 27 2017, 17:03:30) [MSC v.1900 64 bit (AMD64)]
nose version 1.3.7
*** Testing for GeForce GTX 850M
```

**Comment by datasci4** [comment]
Tried a few fixes and got it to work:
- downgrading to 0.6.2 for libgpuarray and pygpu wasn't recognizing the CUDA/cuDNN drivers I had installed
- the conda environment I was in wouldn't let me upgrade to numpy 1.13.0  and I had a similar error to @lubimov on `import pygpu;pygpu.test()` 

I created a new conda environment without the full anaconda package, and installed pgypu and libgpuarray 0.6.8, the development version of theano, and supporting packages. Made some changes to the .theanorc file (ie including cxx path, dnn path)

Everything is up and running now, and I get the following output on the gpu test
```
Using cuDNN version 5110 on context None
Preallocating 6553/8192 Mb (0.800000) on cuda0
[GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float32, vector)>), HostFromGpu(gpuarray)(GpuElemwise{exp,no_inplace}.0)]
Looping 1000 times took 0.269679 seconds
Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
  1.62323296]
Used the gpu

Mapped name None to device cuda0: GeForce GTX 1080 (0000:03:00.0)
``` 
Thanks everyone for the help!

**Comment by zhouqun8508** [comment]
I finally got it up and running by uninstall my anaconda, and install miniconda instead. Then followed each step on http://deeplearning.net/software/theano/install_windows.html.
After this, upgrade Theano to 0.10.0 dev version. Now everything is working. 
Thanks!

**Comment by sarvarip** [comment]
I had the same problem and the solution was to downgrade pygpu and libgpuarray to 0.6.2 as nouiz suggested.

**Comment by datasci4** [comment]
@sarvarip I tried that and it didn't work for me using CUDA 8.0 so I made a new conda environment (the prior environment didn't let me use numpy 1.13) and it worked.

**Comment by james77777778** [comment]
I tried with python 3.6.1, theano 0.9.0,  pygpu 0.6.8.
After upgrade numpy from 1.12 to 1.13 (made a new full conda environment and conda install numpy) it works!

**Comment by ddclone** [comment]
Upgrading numpy 1.12 from to numpy 1.13 helped me.
