### ISSUE TITLE
Forcing a theano function to block/synchronize

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6104]
I remember from various resources/conversations that Theano function is non-blocking, in the sense that they return to the caller as soon as the computation for the output is complete, while for instance, something like the "updates" can continue to work in the background.

I need to time exactly and compare two algorithms, thus I need to force the theano function whenever it executes to return only when it completes all of the computation and not earlier. Is there any direct way to do this?

**Comment by khaotik** [comment]
If your are using nvidia cards, does `env CUDA_LAUNCH_BLOCKING=1` work?

**Comment by nouiz** [comment]
This will slow down Theano enormously. It will sync each GPU kernel, not
each Theano function.

you can check the file check_blas.py, we do it. Mostly, call sync on each
output/updates of the Theano function.

**Comment by botev** [comment]
@nouiz In `check_blas.py`, however, you seem to be fetching the variable from the GPU, e.g. the code is:

c.get_value(borrow=True, return_internal_type=True).sync()

Is it possible to call sync on the variable without actually making the GPU -> CPU transfer?

**Comment by lamblin** [comment]
Done in #6160.
