### ISSUE TITLE
Should nervanagpu be still supported by Theano ?

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6114]
A Python module called `nervanagpu` is used in `theano/gpuarray/nerv.py`.

Got from this page: https://github.com/NervanaSystems/nervanagpu :

> ## Deprecated
> 
> NervanaGPU is now maintained as a backend inside of the [neon](https://github.com/NervanaSystems/neon) project. This repository remains for reference only and is no longer updated.

And it seems the PyPI package has not been updated since 2015: https://pypi.python.org/pypi/nervanagpu/0.3.1

Do we want to still keep the `nerv` module into Theano ? Or should it be removed / marked as `deprecated` too / rewritten to use the new module `neon` ?

@nouiz @lamblin @abergeron

**Comment by nouiz** [comment]
They changed the repo. I would be very surprised that it still work, so I would just remove it from Theano.

**Comment by abergeron** [comment]
I agree about removing the module.
