### ISSUE TITLE
segmentation fault with python3 

### ISSUE THREAD

**Issue by hma02** [Theano/Theano#6126]
Hi, I'm getting segmentation fault when compiling theano function in python3 on x86_64. See https://github.com/uoguelph-mlrg/Theano-MPI/issues/21. The same code works fine in python2.

I thought it might be worth reporting to here.

**Comment by lamblin** [comment]
Which version of libgpuarray are you using? 0.6.8 fixes some known segfaults. You may need to update theano to the development version on GitHub as well.

I'd also be interested in the source for the Theano module that it segfaults in. According to your stacktrace, it should be in `/export/mlrg/hma02/.theano/compiledir_Linux-3.13--generic-x86_64-with-debian-jessie-sid-x86_64-2.7.13-64/tmpGRA547/mod.cpp`.

**Comment by hma02** [comment]
Hi @lamblin,

Please find the `mod.cpp` in the attached zip file.
[mod.cpp.zip](https://github.com/Theano/Theano/files/1136716/mod.cpp.zip)

 I checked as below, the libgpuarray I installed is version 0.6.8. The theano version is 0.9.0. I will try the master branch on the github and get back to you.

```bash
$ conda list | grep libgpuarray
libgpuarray               0.6.8                         0 
$ python3
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>> import theano
>>> theano.__file__
'/export/mlrg/hma02/anaconda3/lib/python3.6/site-packages/theano/__init__.py'
>>> theano.__version__
'0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291'
>>> import pygpu
>>> pygpu.__file__
'/export/mlrg/hma02/anaconda3/lib/python3.6/site-packages/pygpu/__init__.py'
>>> pygpu.__version__
'0.6.8' 
```

**Comment by hma02** [comment]
@lamblin 

Thanks, it's working now after upgrading to the bleeding-edge

```bash
$ python3
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
>>> theano.__version__
'0.10.0dev1.dev-d5ba61346c2e243a86a31bcfdd7c4509a088a6f4'
```
