### ISSUE TITLE
ops don't seem work with scalars properly

### ISSUE THREAD

**Issue by NeilGirdhar** [Theano/Theano#6127]
```
from theano import shared, tensor, function, shared
a = shared(np.float32)
tensor.where(tensor.lt(a, a), a, a)
```
crashes with

> ('Variable type field must be a TensorType.', <Generic>, <theano.gof.type.Generic object at 0x1107dd9e8>)

Is there an easy workaround?  (Using vectors is not an easy workaround.)

**Comment by notoraptor** [comment]
When you type `a = shared(np.float32)`, `np.float32` is a numpy type, not a value, but `shared()` expects a value here.

This code will not fail:
`a = shared(12.0)`

Or even:
`a = shared(np.float32(15.37))`

**Comment by NeilGirdhar** [comment]
@notoraptor just wanted to write a quick thanks for looking into this. I haven't gotten around to updating my code and seeing if it works yet.
