### ISSUE TITLE
"conda intall theano" gets wrong version of pygpu (resulting in segmentation fault)

### ISSUE THREAD

**Issue by davidtellez** [Theano/Theano#6141]
I use `theano` in `Ubuntu` with `Anaconda3` and `python 3.5`. If I follow the [installation instructions](http://deeplearning.net/software/theano/install_ubuntu.html#with-conda) in the theano doc website, it says that I should execute the following to install theano:

`conda install theano pygpu`

This worked like a charm until last week or so, when I started to get `segmentation fault, core dumped` errors without any apparent reason. The problem is that `conda` installs `pygpu` version 0.6.8 which is incompatible with `theano`, according to the docs [here](http://deeplearning.net/software/theano/install_ubuntu.html#id1).

The solution I found to work is to install `theano` first, then downgrade `pygpu` to 0.6.2:

`conda install theano`
`conda install pygpu=0.6.2`

In the future, it would be nice if `conda` would fetch the right version of `pygpu`. In the meantime, specifying the version solves the issue.

**Comment by abergeron** [comment]
Where do you get those errors.  Theano *should* work with 0.6.8, but there may be some problem lurking.

Do you have a small example script which will reproduce the problem?

**Comment by myyan92** [comment]
I'm also facing segmentation fault with theano.function. 
I'm using Ubuntu 14.04, CUDA8.0,  with anaconda for python 2.7.10, pygpu version 0.6.8 and theano 0.9.0dev.

Here is the minimal code to reproduce the problem:

`import lasagne.layers as L`
`import theano.tensor as TT`
`input = L.InputLayer(shape=(None, 100))`
`h1=L.DenseLayer(input, num_units=10)`
`output=L.get_output(h1)`
`sum=TT.sum(output, axis=-1)`
`theano.function(inputs=[input.input_var],outputs=[output])`
`theano.function(inputs=[input.input_var],outputs=[sum])`


When theano.config.device is set to 'gpu' the above code goes fine, but when the device is set to 'cuda', the last line will give segmentation fault.

**Comment by danielS91** [comment]
I run into the same problem. The proposed solution (original post) worked for me as well.

**Comment by abergeron** [comment]
I've identified a bug that could cause this in 0.6.8 and fixed it with https://github.com/Theano/libgpuarray/pull/482.  We should release 0.6.9 shortly with that fix.

**Comment by myyan92** [comment]
I have tried downgrading to pygpu0.6.2  with conda install pygpu=0.6.2 It is not solving my problem. 
And I even cannot compile the dense layer, it gives this error:
ImportError: ('The following error happened while compiling the node', GpuDot22(GpuFromHost<None>.0, W), '\n', 'pygpu.blas does not export expected C function pygpu_blas_rgemmBatch_3d')

**Comment by deltaz0** [comment]
Rolling back from `pygpu 0.6.8` to `pygpu 0.6.2` fixed this problem for me today after a fresh install of everything on windows. I'd like to try updating 0.6.8 libgpuarray with the bugfixes mentioned but I'm having trouble manually building it on windows. I'll wait for the 0.6.9 release I suppose.

**Comment by loretoparisi** [comment]
My solution was the following (I'm using Docker):

```Dockerfile
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04
#...
# Install base packages: python3
RUN apt-get update && apt-get install -y \
  git \
  sudo \
  curl \
  build-essential \
  software-properties-common \
  cmake \
  python3-pip \
  p7zip-full

ENV HOME /root
WORKDIR $HOME

# upgrade pip
RUN pip3 install --upgrade pip
# install theano and dependencies
RUN pip3 install scipy numpy cython nose pandas

# anaconda
# RUN \
#     curl -O https://repo.continuum.io/archive/Anaconda3-4.2.0-Linux-x86_64.sh && \
#     yes "yes" | bash Anaconda3-4.2.0-Linux-x86_64.sh && \
#     sudo -s source $HOME/.bashrc

# # conda dependencies: Intel MKL
# # @see https://unix.stackexchange.com/questions/379816/install-anaconda-in-ubuntu-docker
# RUN \
#     /root/yes/bin/conda install -c anaconda mkl-service && \
#     /root/yes/bin/conda install pygpu && \
#     /root/yes/bin/conda install theano

# if using anaconda comment the following line
RUN pip3 install theano

# test nvidia docker
CMD nvidia-smi -q

# libgpuarray
# @see http://deeplearning.net/software/libgpuarray/installation.html
RUN \
    git clone https://github.com/Theano/libgpuarray.git && \
    cd libgpuarray && \
    mkdir Build && \
    cd Build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make && \
    sudo make install && \
    cd .. && \    
    python3 setup.py build && \
    python3 setup.py install && \
```

The full Dockerfile is [here](https://github.com/loretoparisi/docker/blob/master/theanogru/Dockerfile).

**Comment by pavgup** [comment]
I've been able to replicate exactly this problem here: https://gist.github.com/pavgup/e6e22eb6b6c3261837881b1cf8276e96

I wrote up a question about this problem here: http://forums.fast.ai/t/conv2d-segmentation-fault-cuda-8-0-cudnn-5-11-keras-2-0-2-in-dogs-cats-classifier/4376

And the solution downgrading pygpu to 0.6.2 solved my problem. 


```pavan@learn:~/lesson01$ conda install pygpu=0.6.2
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/pavan/anaconda2:

The following packages will be DOWNGRADED:

    libgpuarray: 0.6.8-0      --> 0.6.2-0
    pygpu:       0.6.8-py27_0 --> 0.6.2-py27_0

Proceed ([y]/n)? y

libgpuarray-0. 100% |#############################################################################################################################| Time: 0:00:00 888.38 kB/s
pygpu-0.6.2-py 100% |#############################################################################################################################| Time: 0:00:00   2.62 MB/s```

**Comment by nouiz** [comment]
continuing updated the libgpuarray version. So this should be fixed. I'm closing.
