### ISSUE TITLE
Slicing within tensordot

### ISSUE THREAD

**Issue by RomainPe** [Theano/Theano#6142]
Hi,

I noticed a weird result using slicing within tensordot. The following code shows how slicing in a call to theano.tensor.tensordot produces a different result from slicing in a call to a function mapping inputs to the result of theano.tensor.tensortdot.

The second value seems to be right since numpy.tensordot produces the same result.

I checked the `t[..., 0]` syntax (t being a theano tensor) which seems to work properly. 

```
import numpy as np
import theano
import theano.tensor as T

floatX = theano.config.floatX

a1 = T.matrix(dtype=floatX)
b1 = T.tensor3(dtype=floatX)
c1 = T.tensordot(a1, b1[..., 0])

testFunc1 = theano.function([a1, b1], c1)

a2 = T.matrix(dtype=floatX)
b2 = T.matrix(dtype=floatX)
c2 = T.tensordot(a2, b2)

testFunc2 = theano.function([a2, b2], c2)

mat = np.random.random((3, 3)).astype(floatX)
tensor = np.random.random((3, 3, 2)).astype(floatX)

print(testFunc1(mat, tensor)) # slicing in call to theano.tensor.tensordot
print(testFunc2(mat, tensor[..., 0])) # slicing in call to theano function
print(np.tensordot(mat, tensor[..., 0])) # slicing in call to numpy.tensordot
print(np.tensordot(mat, tensor)[0]) # no slicing with numpy.tensordot
```

(This result was obtained using theano 0.9)

**Comment by lamblin** [comment]
It seems to work for me with the latest master:
```
1.94397006514
1.94397006514
1.94397006514
1.94397006514
```
Could you try to update to the development version from GitHub?

**Comment by lamblin** [comment]
Actually, I have an issue with `device=cuda,floatX=float32`:
```
Using cuDNN version 6021 on context None
Mapped name None to device cuda: GeForce GTX 750 Ti (0000:01:00.0)
-1.25619448681e+38
3.36419057846
3.36419057846
3.36419
```
