### ISSUE TITLE
model won't run on GPU with new backend

### ISSUE THREAD

**Issue by david-leon** [Theano/Theano#6152]
The issue is related to Theano's optimization and new backend at GPU. The demo code will run on old backend (CPU and GPU), and new backend at CPU, but won't on new backend at GPU (except for `optimizer=None`), error raised as
```
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[0] == 4, but the output's size on that axis is 31.
```
Seemed there was tensor reshaped wrongly inside the GPU.

I've reduce the code as small as possible and put it in a repo [here](https://github.com/david-leon/theano_newbackend_debug) , to run the demo code, you'll need [Lasagne_CTC](https://github.com/david-leon/Lasagne_CTC) and [Lasagne_Ext](https://github.com/david-leon/Lasagne_Ext)

I'm using the latest dev. version of Theano, cuDNN version 5105, Ubuntu 14.04, and Tesla M40.

**Comment by abergeron** [comment]
This looks like a bug in GpuAdvancedSubtensor, where it is not returning the right shape.

This shorter script can repro the issue:
```                                    
import theano
import numpy

# 31, 6336, 4                                                                   
scorematrix = theano.shared(numpy.random.rand(31, 6336, 4).astype('float32'))

queryseq = theano.shared(numpy.random.randint(0, 6334, size=(15, 4)).astype('in\
t32'))

batch_size = scorematrix.shape[2]
f = theano.function([], scorematrix[:, queryseq, theano.tensor.arange(batch_siz\
e)])

res = f()

assert res.shape == (31, 15, 4), res.shape
```

I haven't dug into why it gives wrong results yet.

**Comment by lamblin** [comment]
Right, the final reordering of axes after the indexing is not correct.
What we are currently doing is putting all the array-indexed dimensions to the left when there is more than one such dimension.
However, the correct way would be to do that if all the dimensions indexed with arrays are not grouped together.
In this case, they are grouped together to the right, so the first dimension should be left alone.
We'll try to come up with a fix soon.

**Comment by david-leon** [comment]
@abergeron @lamblin Glad to know there's already some fix. However, the bug is not totally solved, with the newest commit of Theano, new error raised as
```
ValueError: Could not call GpuElemwise
Apply node that caused the error: GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}(GpuAlloc<None>{memset_0=True}.0, GpuElemwise{Composite{(AND(GE(i0, i1), LE(i0, i2)) * (i3 / i4))}}[(0, 0)]<gpuarray>.0, SliceConstant{None, None, None}, GpuElemwise{Cast{int32}}[]<gpuarray>.0, ARange{dtype='int64'}.0)
Toposort index: 334
Inputs types: [GpuArrayType<None>(float32, 3D), GpuArrayType<None>(float32, 3D), <theano.tensor.type_other.SliceType object at 0x7fa1ea053ef0>, GpuArrayType<None>(int32, matrix), TensorType(int64, vector)]
Inputs shapes: [(31, 6336, 4), (31, 15, 4), 'No shapes', (15, 4), (4,)]
Inputs strides: [(101376, 16, 4), (4, 496, 124), 'No strides', (16, 4), (8,)]
Inputs values: ['not shown', 'not shown', slice(None, None, None), 'not shown', array([0, 1, 2, 3])]
Outputs clients: [[InplaceGpuDimShuffle{2,0,1}(GpuAdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0)]]
```

**Comment by lamblin** [comment]
That new issue is in GpuAdvancedIncSubtensor, and has been reported as #6144.
Until we fix or disable it, I would suggest using `optimizer_excluding=local_gpua_advanced_incsubtensor`.
