### ISSUE TITLE
After updating Theano weird problems when using GPU

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6157]
Recently I've updated Theano to the master branch. However, this lead to the following error:
`
Exception: ('The following error happened while compiling the node', GpuDnnConvGradI{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), dilation=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0}), '\n', "Compilation failed (return status=1): /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:442: error: a brace-enclosed initializer is not allowed here before '{' token. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:442: error: ISO C++ forbids initialization of member 'prev_kern_dims'. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:442: error: making 'prev_kern_dims' static. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:442: error: invalid in-class initialization of static data member of non-integral type 'size_t [5]'. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:443: error: a brace-enclosed initializer is not allowed here before '{' token. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:443: error: ISO C++ forbids initialization of member 'prev_top_dims'. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:443: error: making 'prev_top_dims' static. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:443: error: invalid in-class initialization of static data member of non-integral type 'size_t [5]'. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp: In member function 'int<unnamed>::__struct_compiled_op_mc2bb2e24bb41d8af45c9d8be40d95ddd::conv_gi_node_mc2bb2e24bb41d8af45c9d8be40d95ddd_0(PyGpuArrayObject*, PyGpuArrayObject*, PyGpuArrayObject*, cudnnConvolutionStruct*, double, double, PyGpuArrayObject**, _Params_c626b80a28594f6fe623577946e29157_c29b5bb55c42161a5f82e1c2559749fa*)':. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:558: error: 'prev_kern_dims' was not declared in this scope. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:560: error: 'prev_top_dims' was not declared in this scope. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:625: error: 'prev_kern_dims' was not declared in this scope. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:626: error: 'prev_top_dims' was not declared in this scope. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp: In member function 'int<unnamed>::__struct_compiled_op_mc2bb2e24bb41d8af45c9d8be40d95ddd::init(PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*, PyObject*)':. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:883: error: 'prev_kern_dims' was not declared in this scope. /home/abotev/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.5-Final-x86_64-3.6.0-64/tmpa8wrg7og/mod.cpp:884: error: 'prev_top_dims' was not declared in this scope. ", "[GpuDnnConvGradI{algo='none', inplace=True}(<GpuArrayType<None>(float32, (True, False, False, False))>, <GpuArrayType<None>(float32, (False, True, False, False))>, <GpuArrayType<None>(float32, 4D)>, <CDataType{cudnnConvolutionDescriptor_t}>, Constant{1.0}, Constant{0.0})]")
`
I've also tried updating `libgpuarray` to the latest but that did not resolve it either. The code however runs fine on the CPU and worked fine before on the GPU. 

It seems that the error is coming from the C code of the kernel `prev_kern_dims` where there is a mistake of a brace initializer. However, I have no idea where exactly to look for that.

**Comment by botev** [comment]
Ok so it seems that this is stemming from my compiler since the default one is quite old, but I guess it would be good to notify users if before you could have got away without `-std=c++11` and now you don't. This quite relevant for people using clusters on older CentOS systems.

**Comment by lamblin** [comment]
Could you attach the `mod.cpp` in question?
If there's a way of making it work with older compilers, we should definitely do that.

**Comment by botev** [comment]
It seems Theano is doing some automatic clean up when the kernel fails, cause the folder and the file does not exist.

**Comment by botev** [comment]
After installing a new compiler and running Theano with it I dissected and found where this is coming from. The `mod.cpp` referenced there has the following part (I'm not pasteing the whole file as it is 1.4K lines):
```
#define APPLY_SPECIFIC(str) str##_node_mcb4d85a74cd4d544577dda732c18ece5_0
#define PARAMS_TYPE _Params_ad7c8aefacf298048a85f85fbc6cf377_36f935c3d2b58bd8767e661440baa348
#define DTYPE_PARAM_choose_algo npy_bool
#define DTYPE_PARAM_choose_once npy_bool
#define DTYPE_PARAM_choose_time npy_bool
#define DTYPE_PARAM_inplace npy_bool
#define DTYPE_PARAM_num_groups npy_int32

cudnnTensorDescriptor_t APPLY_SPECIFIC(input);
cudnnTensorDescriptor_t APPLY_SPECIFIC(output);
cudnnFilterDescriptor_t APPLY_SPECIFIC(kerns);



int reuse_algo;
cudnnConvolutionBwdDataAlgo_t prev_algo;
size_t prev_kern_dims[5] = {0};
size_t prev_top_dims[5] = {0};

int
APPLY_SPECIFIC(conv_gi)(PyGpuArrayObject *kerns, PyGpuArrayObject *output,
                        PyGpuArrayObject *im,
                        cudnnConvolutionDescriptor_t desc,
                        double alpha, double beta, PyGpuArrayObject **input,
                        PARAMS_TYPE* params) {
```
The error specifically is coming from the line `size_t prev_kern_dims[5] = {0};`
