### ISSUE TITLE
Memory leak in GPU backend?

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#6162]
Lasagne user @guoxuesong discovered what seems to be a memory leak in the new GPU backend: Lasagne/Lasagne#860
Updating Theano and libgpuarray to bleeding-edge does not help. I have been able to reproduce the leak as follows (requires Lasagne, any version will do):
1. download the mnist example: `wget https://raw.githubusercontent.com/Lasagne/Lasagne/master/examples/mnist.py`
2. patch it with the following command (run in the directory you put mnist.py):
```bash
patch << EOF
--- mnist.py
+++ mnist.py
@@ -18,4 +18,6 @@
 import os
 import time
+import gc
+import psutil
 
 import numpy as np
@@ -295,5 +297,5 @@
         train_batches = 0
         start_time = time.time()
-        for batch in iterate_minibatches(X_train, y_train, 500, shuffle=True):
+        for batch in iterate_minibatches(X_train, y_train, 32, shuffle=True):
             inputs, targets = batch
             train_err += train_fn(inputs, targets)
@@ -318,4 +320,9 @@
         print("  validation accuracy:\t\t{:.2f} %".format(
             val_acc / val_batches * 100))
+        while gc.collect() > 0:
+            pass
+        print('  memory use:\t\t\t{:.3f} MiB'.format(
+            psutil.Process().get_memory_info()[0] / float(1024**2)))
+
 
     # After training, we compute and print the test error:
EOF
```
3. Run it with `THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32,allow_gc=1,gpuarray.preallocate=0.25 python mnist_leak.py`

It will train an MLP on MNIST and print the CPU memory use after every epoch (after calling `gc.collect()` in a loop until it cannot free anything more). For a long time, it stays constant:
```
Epoch 60 of 500 took 1.519s
  training loss:		0.035076
  validation loss:		0.054378
  validation accuracy:		98.61 %
  memory use:			742.488 MiB

...

Epoch 257 of 500 took 1.518s
  training loss:		0.019314
  validation loss:		0.056173
  validation accuracy:		98.72 %
  memory use:			742.488 MiB
```
But then it raises every epoch:
```
Epoch 270 of 500 took 1.519s
  training loss:		0.017606
  validation loss:		0.062359
  validation accuracy:		98.53 %
  memory use:			743.090 MiB
Epoch 271 of 500 took 1.519s
  training loss:		0.017495
  validation loss:		0.062725
  validation accuracy:		98.66 %
  memory use:			743.137 MiB
Epoch 272 of 500 took 1.519s
  training loss:		0.016336
  validation loss:		0.058867
  validation accuracy:		98.69 %
  memory use:			743.188 MiB
Epoch 273 of 500 took 1.520s
  training loss:		0.016826
  validation loss:		0.063525
  validation accuracy:		98.64 %
  memory use:			743.234 MiB

...

Epoch 324 of 500 took 1.518s
  training loss:		0.014919
  validation loss:		0.061403
  validation accuracy:		98.71 %
  memory use:			745.699 MiB
```

With the original batchsize (500), the training function is not called often enough for the leak to appear. I ran it two times, the first time memory raised after 257 epochs, the second time after 265 epochs.

This is with Python 2.7.6, Theano and libgpuarray updated a few minutes ago.

**Comment by guoxuesong** [comment]
I would like to provide some context information.

I build a much larger network with my homebrew build_network() tool [deepstacks](https://github.com/guoxuesong/deepstacks) the network is about 330 layers, include two groups of layers each has 109 layers, the two groups share params with each other. 

It take me 2 hours to compile the model, but after run servery hours, it eat off my 16G memory and crashed.

It seems as if the memory leak is revelent to the number of layers, when the network be big, the memory leaked really fast.

It's not easy to determine which part is response to the memory leak, my code , Lasagne or Theano, by the way I also used nolearn. Thanks @f0k to take this seriously.

**Comment by lamblin** [comment]
Does it happen with `gpuarray.preallocate=-1`? It may be a memory fragmentation issue.

**Comment by guoxuesong** [comment]
@lamblin  I don't think so, because 0.25*6G (in my case) is enough for mnist , and It's CPU memory leaked. but if you want I can test  gpuarray.preallocate=-1

**Comment by lamblin** [comment]
Oh OK, if it is CPU memory leaked, then I don't think it would make a difference, but it may be worth a try.

**Comment by guoxuesong** [comment]
@lamblin I think what you said is gpuarray.preallocate=1 because gpuarray.preallocate=-1 not allocate gpu memory at all, but gpuarray.preallocate=1 does not help.

**Comment by f0k** [comment]
Sorry, could have been more clear about it: It's **CPU** memory leaked, but it only happens when running on the GPU backend.

**Comment by lamblin** [comment]
OK, I understand.
I was just wondering if maybe the memory allocation library in libgpuarray was the one leaking memory.
For that, it is really `gpuarray.preallocate=-1` that would be tried.

**Comment by guoxuesong** [comment]
@lamblin gpuarray.preallocate=-1 does not help.

**Comment by lamblin** [comment]
OK, thanks.

**Comment by botev** [comment]
I'm running now some experiments fully on the CPU. This issue leads to much more greater problems here as after 50 epochs the memory footprint has doubled. I pretty much need about 60GB of memory to run the full experiment...

**Comment by nouiz** [comment]
Can you confirm you use Theano dev version? Which commit?

There was a memory leak on the CPU when Theano can not link directly to
BLAS since the last release from memory.

**Comment by botev** [comment]
I'll try the latest bleeding edge, I think I have a slightly older version and will confirm or not later.

**Comment by lamblin** [comment]
And just to be absolutely certain, what if you always use the same value for `x` instead of calling `dataset.iter()` and iterating through the result?

**Comment by botev** [comment]
Yes, absolutely the same. Is there any way of viewing Theano's full memory print? This is really serious for CPU (and I'm using the latest master branch).

**Comment by f0k** [comment]
> I'm running now some experiments fully on the CPU. This issue leads to much more greater problems here

I'm not sure if that's the same issue then. The steps in my original post only reproduce the memory leak for `device=cuda`, not for `device=cpu` or `device=gpu`.

**Comment by nouiz** [comment]
@notoraptor should look into that this week.

**Comment by ylockerman** [comment]
I don't know if it is the same issue, but I am also seeing a memory leak in my own program when running device=cuda. 

In case it helps, here are my objgraph's most common types. From the graph, it looks like there is some sort of loop where the frames hold the objects that hold the tracebacks that hold the frames. However, this could be RedHerring, as I don't know if it is the same issue. Also, it can be some strange side effect of pdb. 

`objgraph.show_most_common_types(limit=30)
list                       9279683
dict                       5613284
scratchpad                 2418685
tuple                      1496582
TensorType                 1383711
Apply                      937928
TensorVariable             935744
TensorConstant             540547
DimShuffle                 384322
set                        87344
function                   42965
weakref                    13374
wrapper_descriptor         6273
getset_descriptor          5655
cell                       5220
Link                       4236
type                       4153
builtin_function_or_method 3605
method_descriptor          2360
module                     2157
instancemethod             2090
property                   1710
ScalarVariable             1676
GpuArrayVariable           1636
GpuArrayType               1272
OrderedSet                 1045
partial                    996
GpuArraySharedVariable     861
WeakSet                    850
frozendict                 798
`

I am running '0.9.0.dev-c697eeab84e5b8a74908da654b66ec9eca4f1291'.

**Comment by notoraptor** [comment]
Some memory leaks have been fixed in both libgpuarray and theano. With current master branch of both projects and with the modified script given above, memory does not seem to increase anymore (I ran it once):

```
THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32,allow_gc=1,gpuarray.preallocate=0.25 python mnist.py > out.txt 2>&1
```
Output head:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/utils/python$ head out.txt -n 20
Using cuDNN version 7002 on context None
Preallocating 1010/4041 Mb (0.250000) on cuda
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
Loading data...
Building model and compiling functions...
Starting training...
Epoch 1 of 500 took 1.535s
  training loss:		0.437303
  validation loss:		0.145722
  validation accuracy:		95.84 %
  memory use:			1232.207 MiB
Epoch 2 of 500 took 1.512s
  training loss:		0.231407
  validation loss:		0.110394
  validation accuracy:		96.73 %
  memory use:			1232.207 MiB
Epoch 3 of 500 took 1.503s
  training loss:		0.181437
  validation loss:		0.084375
  validation accuracy:		97.52 %
```
Output tail:
```
(python2) notoraptor@notoraptor-XPS-15-9560:~/mila/dev/git/utils/python$ tail out.txt 
  memory use:			1232.207 MiB
Epoch 500 of 500 took 1.472s
  training loss:		0.011710
  validation loss:		0.060796
  validation accuracy:		98.72 %
  memory use:			1232.207 MiB
Final results:
  test loss:			0.051924
  test accuracy:		98.89 %
  memory use:			1232.207 MiB
```

It stays at `1232.207 MiB` along the 500 epochs.

Can you check it on your computers ? @f0k @guoxuesong 

NB: As info, this is how I patched the mnist script:
```patch
--- mnist-backup.py	2017-09-12 09:25:48.490271200 -0400
+++ mnist.py	2017-09-13 13:25:37.277130600 -0400
@@ -17,6 +17,8 @@
 import sys
 import os
 import time
+import gc
+import psutil
 
 import numpy as np
 import theano
@@ -294,7 +296,7 @@
         train_err = 0
         train_batches = 0
         start_time = time.time()
-        for batch in iterate_minibatches(X_train, y_train, 500, shuffle=True):
+        for batch in iterate_minibatches(X_train, y_train, 32, shuffle=True):
             inputs, targets = batch
             train_err += train_fn(inputs, targets)
             train_batches += 1
@@ -317,6 +319,11 @@
         print("  validation loss:\t\t{:.6f}".format(val_err / val_batches))
         print("  validation accuracy:\t\t{:.2f} %".format(
             val_acc / val_batches * 100))
+        while gc.collect() > 0:
+            pass
+        print('  memory use:\t\t\t{:.3f} MiB'.format(
+            psutil.Process().memory_info()[0] / float(1024**2)))
+
 
     # After training, we compute and print the test error:
     test_err = 0
@@ -332,6 +339,10 @@
     print("  test loss:\t\t\t{:.6f}".format(test_err / test_batches))
     print("  test accuracy:\t\t{:.2f} %".format(
         test_acc / test_batches * 100))
+    while gc.collect() > 0:
+        pass
+    print('  memory use:\t\t\t{:.3f} MiB'.format(
+        psutil.Process().memory_info()[0] / float(1024**2)))
 
     # Optionally, you could now dump the network weights to a file like this:
     # np.savez('model.npz', *lasagne.layers.get_all_param_values(network))
```

**Comment by nouiz** [comment]
Note, we have released libgpuarray 0.7.2 that contain that part of the fix.
There is conda packages on our channel:

# remove your old libgpuarray.

conda install pygpu -c mila-udem

in case you don't manually build it.

**Comment by f0k** [comment]
I can confirm the leak has disappeared with the bleeding-edge libgpuarray and Theano; memory usage stays constant over the 500 epochs for me. Good job!

**Comment by botev** [comment]
@f0k Could you tell me which exactly commit/tag you use for libgpuarray?

**Comment by f0k** [comment]
@botev: I used 3d1c382 for libgpuarray and 8678787 for Theano. But as I said before, if you experience a memory leak with device=cpu, then your leak is different from the one I reported here. You should try to boil it down to a minimal working example and open a new issue for it.
