### ISSUE TITLE
Regression on loading cuDNN

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6175]
Recently updating to the master branch I got the following error for using cuDNN
```
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: cannot find -lcudnn\ncollect2: error: ld returned 1 exit status\n'
```

I nailed down the issue to [this commit c649d0447c847790bdb2883f94b49e61393225ff](https://github.com/botev/Theano/commit/c649d0447c847790bdb2883f94b49e61393225ff). Note that checking out earlier commit and cuDNN loads perfectly so there is some issue there.

**Comment by abergeron** [comment]
A couple of questions:
 - Can you post the content of `LIBRARY_PATH`, `LD_LIBRARY_PATH` and any theano config variables that you pass.
 - What is the actual location of cuDNN on this machine?

**Comment by botev** [comment]
`LD_LIBRARY_PATH`:
/share/apps/barber/cuda/lib64/:/share/apps/barber/cuda/nvvm/lib64/:/share/apps/barber/cuda/extras/CUPTI/lib64/:/share/apps/barber/system/lib64/:/share/apps/barber/system/lib/:/opt/gridengine/lib/linux-x64:/opt/openmpi/lib:/opt/python/lib:/share/apps/barber/arrayfire-3/lib/

I use only the `.theanorc` which looks like this:
```
[global]
floatX = float32
device = cuda
optimizer_including = conv_meta
warn_float64 = warn
assert_no_cpu_op = raise
cxx = /opt/rh/devtoolset-3/root/usr/bin/g++

[nvcc]
fastmath = True
```
Note that I need the `cxx` flag because of #6157 
cuDNN is in `/share/apps/barber/cuda/lib64/`

**Comment by abergeron** [comment]
This is probably because there is no longer a default value for dnn.library_path.  The default install leaves it in /usr/local, which does not require additional configuration, but if you have it elsewhere, then you need to inform Theano somehow.

Your options are to add `/share/apps/barber/cuda/lib64/` to `LIBRARY_PATH` (which is what the compiler uses to find libraries) or set `dnn.library_path` to that value and theano will pass the appropriate flags.

**Comment by botev** [comment]
Why is it not using `LD_LIBRARY_PATH` as well?

**Comment by lamblin** [comment]
My understanding is that `LIBRARY_PATH` is used at compile time to link with the dynamic library, and `LD_LIBRARY_PATH` is used at runtime when loading it, although `ctypes` seems to use `LIBRARY_PATH` as well sometimes.

**Comment by botev** [comment]
Ah yes, that is true, but then why was the default dnn path removed? I find that particularly counter intuitive as almost all setups have the libraries exactly in the cuda root directory?

**Comment by abergeron** [comment]
Are you sure about this?  If you install with the nvidia packages you get cudnn in /usr/local

**Comment by botev** [comment]
Hmm as far as I remember I always had to just unpack cudnn and it get's unpacked always into a `cuda` folder. Do they have some debian package now (I'm currently with cuDNN 6.0.21)

**Comment by abergeron** [comment]
The have some ubuntu packages on the cudnn download website.

However, if it makes life easier, we can try to look for cudnn in the cuda paths and set those by default if it's there.

**Comment by botev** [comment]
I did not know they had Ubuntu packages.
I definitely think for people which are used to what so far has been the standard way of installing cudnn would be nice if at least the cuda folder is searched, otherwise, basically anyone who updates would get the error on a Linux machine if he used the runtime cuDNN.

**Comment by nouiz** [comment]
There is a fix in gh-6146.

**Comment by botev** [comment]
Cool, feel free to close this when you merge it.
