### ISSUE TITLE
Replace usage of deprecated nose-parameterized

### ISSUE THREAD

**Issue by ghisvail** [Theano/Theano#6187]
`nose-parameterized` is deprecated and superseded by `parameterized`, which is not specific to `nose` anymore. Please consider updating your test dependencies.

**Comment by SebastinSanty** [comment]
I would like to take this up. Thanks!

**Comment by ghisvail** [comment]
It might be a good opportunity to also just drop `nose` (which is dormant) in favor of `pytest`. The new `parameterized` module is compatible with both.

**Comment by lamblin** [comment]
Done in #6209.
