### ISSUE TITLE
AttributeError: module 'theano.tensor' has no attribute 'slinalg'

### ISSUE THREAD

**Issue by ferrine** [Theano/Theano#6211]
I was using the following code previously without any error but now I have problems
```
import theano.tensor as tt
tt.slinalg
 > AttributeError: module 'theano.tensor' has no attribute 'slinalg'
```

**Comment by nouiz** [comment]
Update Theano. You have an old version that don't contain that.

Le dim. 30 juil. 2017 12:28, Maxim Kochurov <notifications@github.com> a
écrit :

**Comment by lamblin** [comment]
Or maybe you need to `import theano.tensor.slinalg` explicitly?

**Comment by ferrine** [comment]
`pip install -U git+https://github.com/Theano/Theano` does not help I get another error instead:

**Comment by ferrine** [comment]
cloning the whole project and `pip install -e .`seems to resolve `FileNotFoundError` problem (direct install still does not work). The main problem with `slinalg` still occurs

**Comment by nouiz** [comment]
Try @lamblin suggestion. I think he have the right fix. The file isn't
imported automatically as it depend on scipy and scipy is an optional
dependency.

**Comment by ferrine** [comment]
That works
