### ISSUE TITLE
Custom Theano op in c++

### ISSUE THREAD

**Issue by MehulAjax21** [Theano/Theano#6212]
Hello,

I have some existing C++ libraries of CRF are RNN. I dont want to write those code again.
I know that Theano supports the C ops. I wanted to know does it support the c++ op also?

Tensorflow has a method of writing files directly in C++ and compiling the *.so file which can be then loaded directly in python. This makes reuse of the libraries very easy. Does Theano has same kind of mechanism?

**Comment by botev** [comment]
I suggest looking at for instance magma bindings of how to link external libraries in to operators: #5914

**Comment by MehulAjax21** [comment]
@botev: Thanks for the hint. I went through the procedure. Need to analyse a bit more.
But the code is written in C. I want to check if I can write in C++ too. Intuitively, I can say it should be possible. I need to verify. And also know if there are some caveats.
I need to avoid rewriting anything and resuse the existing code as it is

**Comment by botev** [comment]
I think there is nothing more special (although I could be wrong), potentially you might need to somehow hint this to be compiled with g++ rather than gcc and that it can't run on the GPU. Someone from the devs should be the correct person to give hints on this.

**Comment by abergeron** [comment]
All the ops are compiled with g++ so you can use c++ code.

There is no special hint that you need to run on the CPU since GPU ops are just c++ code that happens to use the GPU to compute.

**Comment by MehulAjax21** [comment]
@abergon: Thanks for the info. That was helpful.
I got what I wanted to know.
I will close the isaue now
