### ISSUE TITLE
`.../c_code/dimshuffle.c` missing from setup.py?

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#6222]
A Lasagne user just reported that
```bash
pip install --upgrade --no-deps https://github.com/Theano/Theano/archive/master.zip
```
lead to the following error (I assume after installation, when trying to import it):
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/XXXX/anaconda/lib/python3.5/site-packages/theano/tensor/c_code/dimshuffle.c
```
The file was added in #6174 and is included in the `master.zip` snapshot, but maybe it's missing in `setup.py` and thus not copied over? You wouldn't notice when doing a development/editable install. The user solved it by downloading `tensor/c_code/dimshuffle.c` and `gpuarray/c_code/dimshuffle.c` manually from github.

Disclaimer: I haven't verified this behavior myself.

**Comment by notoraptor** [comment]
I confirm the problem.
