### ISSUE TITLE
Convert the docstrings to comments in compile/tests

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#6226]
- [ ] `theano/compile/tests/test_function_module.py`
 - [ ] `theano/compile/tests/test_monitormode.py`
 - [ ] `theano/compile/tests/test_pfunc.py`
 - [ ] `theano/compile/tests/test_profiling.py`

**Comment by yikangshen** [comment]
Hi, Arnaud. This is my first ccw work. Could you explain what should I do?

**Comment by yikangshen** [comment]
I have cloned a theano repo, and replaced all docstrings to comments in four *.py files mentioned. Eh, what the next step?

**Comment by lamblin** [comment]
You can have a look at the recommended setup and workflow here: http://deeplearning.net/software/theano/dev_start_guide.html#installation-and-configuration

**Comment by nouiz** [comment]
Make a GitHub PR. There is a dev start guide on Theano web site.

**Comment by yikangshen** [comment]
Thanks for helping!

**Comment by abergeron** [comment]
Done in #6262
