### ISSUE TITLE
Convert the docstrings to comments in gof/tests

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#6227]
- [ ] `theano/gof/tests/test_cmodule.py`
 - [ ] `theano/gof/tests/test_compute_test_value.py`
 - [ ] `theano/gof/tests/test_graph.py`
 - [ ] `theano/gof/tests/test_link.py`
 - [ ] `theano/gof/tests/test_op.py`
 - [ ] `theano/gof/tests/test_vm.py`

**Comment by nouiz** [comment]
done
