### ISSUE TITLE
Add doc for fast cycle detection

### ISSUE THREAD

**Issue by ReyhaneAskari** [Theano/Theano#6230]
Regarding the improvement with the cycle_detection flag we need to add documentation both where all the flags are introduced and also we need to add some more explanations as notes in the doc so the users would be aware of the new feature.

**Comment by ReyhaneAskari** [comment]
@lamblin , I checked and I have already included the explanation of `cycle_detection` in config.txt. Do you have any other suggestions on where I should add some side notes for it?

**Comment by nouiz** [comment]
We need to let more people know about this. Few peole read completly config.txt and even then, don't fully understand all the consequence of each options. (or forget about them). So we must highligh that option more I think.

What about adding a note in this section: http://deeplearning.net/software/theano_versions/dev/tutorial/modes.html#optimizers to tell about this option that give a good compilation speed up for big graph? Tell that for big graph, it goes something between fast_compile and fast_run and that it is better to use that flag then optimizer_excluding=inplace.

**Comment by ReyhaneAskari** [comment]
Sure. I will add it there.
