### ISSUE TITLE
Convert docstrings to comments in tests

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#6238]
- [x] `theano/tests/test_2nd_order_grads.py`
 - [x] `theano/tests/test_breakpoint.py`
 - [x] `theano/tests/test_dictionary_output.py`
 - [x] `theano/tests/test_flake8.py`
 - [x] `theano/tests/test_gradient.py`
 - [x] `theano/tests/test_ifelse.py`
 - [x] `theano/tests/test_printing.py`
 - [x] `theano/tests/test_record.py`

**Comment by nouiz** [comment]
What is left is to rebase gh-6266 and see what we need to keep from it.

**Comment by slefrancois** [comment]
All files currently listed only have docstring on top, or for non-test functions.
