### ISSUE TITLE
Convert docstrings to comments in misc tests

### ISSUE THREAD

**Issue by abergeron** [Theano/Theano#6239]
- [ ] `theano/sparse/tests/test_basic.py`
 - [ ] `theano/tensor/signal/tests/test_conv.py`
 - [ ] `theano/typed_list/tests/test_type.py`

**Comment by Alhaider** [comment]
I would like to work on this since it's an easy fix, to make sure I got it right I should comment out all the docstrings?

**Comment by abergeron** [comment]
The ticket is to replace the docstrings with comments for test methods (and classes).  You should comment them out and also remove the `"""`

**Comment by Alhaider** [comment]
Great I will start with the file 

theano/sparse/tests/test_basic.py

and make a pull request

**Comment by Alhaider** [comment]
Done

theano/tensor/signal/tests/test_conv.py
 theano/typed_list/tests/test_type.py
