### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/tensor/c_code/dimshuffle.c'

### ISSUE THREAD

**Issue by StatML** [Theano/Theano#6241]
Hi, I am using Theano 0.10.0.dev1 (which is built from source) with Python3.5 on Ubuntu 16.04.2.
When I try the following statements, I meet an error. Does anyone know how to fix it? Thanks!

CUDA Version: 8.0
cuDNN: 6.0

> x = T.fmatrix('x)
   y = 1 + T.exp(-x)

> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-51-894bae0dcc51> in <module>()
> ----> 1 1 + T.exp(-x)
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/tensor/var.py in __radd__(self, other)
>     225     # ARITHMETIC - RIGHT-OPERAND
>     226     def __radd__(self, other):
> --> 227         return theano.tensor.basic.add(other, self)
>     228 
>     229     def __rsub__(self, other):
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/gof/op.py in __call__(self, *inputs, **kwargs)
>     613         """
>     614         return_list = kwargs.pop('return_list', False)
> --> 615         node = self.make_node(*inputs, **kwargs)
>     616 
>     617         if config.compute_test_value != 'off':
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/tensor/elemwise.py in make_node(self, *inputs)
>     490         inputs = list(map(as_tensor_variable, inputs))
>     491         out_dtypes, out_broadcastables, inputs = self.get_output_info(
> --> 492             DimShuffle, *inputs)
>     493         outputs = [TensorType(dtype=dtype, broadcastable=broadcastable)()
>     494                    for dtype, broadcastable in izip(out_dtypes,
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/tensor/elemwise.py in get_output_info(self, dim_shuffle, *inputs)
>     446                 args.append(dim_shuffle(
>     447                     input.type.broadcastable,
> --> 448                     ['x'] * difference + list(range(length)))(input))
>     449         inputs = args
>     450 
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/tensor/elemwise.py in __init__(self, input_broadcastable, new_order, inplace)
>     155 
>     156     def __init__(self, input_broadcastable, new_order, inplace=True):
> --> 157         COp.__init__(self, [self.c_func_file], self.c_func_name)
>     158         self.input_broadcastable = tuple(input_broadcastable)
>     159         self.new_order = tuple(new_order)
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/gof/op.py in __init__(self, func_files, func_name)
>    1306         # find the new path and new version of the file in Theano.
>    1307         self.func_files = func_files
> -> 1308         self.load_c_code(func_files)
>    1309 
>    1310         if len(self.code_sections) == 0:
> 
> /usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/gof/op.py in load_c_code(self, func_files)
>    1329         for func_file in func_files:
>    1330             # U (universal) will convert all new lines format to \n.
> -> 1331             with _open_u(func_file) as f:
>    1332                 self.func_codes.append(f.read())
>    1333 
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/Theano-0.10.0.dev1-py3.5.egg/theano/tensor/c_code/dimshuffle.c'
>

**Comment by notoraptor** [comment]
It's a known bug related to Theano installation, that should be fixed by PR #6225 . We will merge it soon.

**Comment by StatML** [comment]
@notoraptor Great! Thanks a lot!

**Comment by f0k** [comment]
As a temporary workaround, if you don't want to wait, you can manually download the two missing files from github and copy them to the location mentioned in the error message (`theano/tensor/c_code/dimshuffle.c` and `theano/gpuarray/c_code/dimshuffle.c`).

**Comment by StatML** [comment]
Hi, @f0k Thanks a lot! :+1:
