### ISSUE TITLE
Should we make c++ mandatory?

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#6248]
This is a question. We won't change that for the 0.10 release. Currently we officialy suport it. But we don't run Theano tests in that setup frequently enough. So it frequently enough get broken and make the release time longer.

Current problem with the current state:
- It get broken frequently.
- It is mostly not usable as way too slow and many features are missing (mostly many ops).
- GPU mostly not usable.

Advantage of dropping that:
- Less maintenance
- A little bit smaller test code (no need to skip tests when g++ isn't there)
- A little bit less code to detect and disable cases like optimizations that introduce op that absolutly need g++.

Disadvantage:
- If we want to generate a module for deployment, maybe it would be harder to implement?

My personal idea is that we don't need to keep that. It don't bring enough benefit. I don't think it would make that implementation much more complicated.

**Comment by nouiz** [comment]
My personal take is that we make a c++ compiler mandatory and change the docker that test the case where we don't have one to a docker that test when we don't have scipy.

Do we want to write a deprecation warning in that case for the 0.10 release?

**Comment by lamblin** [comment]
I agree with that.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/6253 warn that c++ will be mandatory in the futur.

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/issues/6282 is a problem that we will need to fix if we make c++ mandatory.

**Comment by nouiz** [comment]
We won't do that change anymore, so closing.
