### ISSUE TITLE
How to manage `config.gpuarray.sync` ?

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6249]
In some Ops, it is used inside C code in string formatting:
```python
"""
if (%(sync)d) {...}
""" % {'sync': config.gpuarray.sync}
```

But in other Ops it is used as a condition to append C code:
```python
if config.gpuarray.sync:
    code += "..."
```

What is the best design to use ? Always use it in string formatting ? Find a way to always use it as an op param ? Always use it as a Python condition to append C code ? Or isn't it a problem if it is used in different ways across Theano code ?

@nouiz @lamblin @abergeron

**Comment by nouiz** [comment]
IRL discussion summary with @lamblin et @notoraptor. We will remove that for now. It isn't well supported and is not used and usefull in rare case we don't support.

If we want to add that back, we should do it well later. But that will probably won't happen.
