### ISSUE TITLE
Theano and g++, spaces in username

### ISSUE THREAD

**Issue by chrispikula** [Theano/Theano#6257]
I'm using the latest theano version, and I'm having trouble enabling the device = cuda* flag in .theanorc .

This is the error I get:
g++.exe: error: Pikula\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.11-64\lazylinker_ext\lazylinker_ext.pyd: No such file or directory
g++.exe: error: C:\Users\Chris: No such file or directory
g++.exe: error: Pikula\AppData\Local\Theano\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.11-64\lazylinker_ext\mod.cpp: No such file or directory

My username is "Chris Pikula".  It's kinda late to change it now, but on my next computer I'll know.  Any solutions for now?

I've tried adding the following to .theanorc
[gcc]
cxxflags = -D_hypot=hypot

**Comment by notoraptor** [comment]
@chrispikula You can set your base compiledir in `.theanorc`. E.g.:

```
[global]
base_compiledir=full\path\to\a\directory\without\spaces
```
