### ISSUE TITLE
More efficient batched_dot implementation

### ISSUE THREAD

**Issue by feiga** [Theano/Theano#6263]
Theano contains an interface ```theano.tensor.batched_dot(x, y)``` for batched matrix multiplication. For example, for 3d tensor x with shape (n, a, b) and y with shape (n, b, c). The operator returns a new tensor with shape (n, a, c). 

However, the current implementation of batched_dot is not efficient, which just iterates over the first dimension and call gemm(x[i], y[i]) n times. See https://github.com/Theano/Theano/blob/master/theano/tensor/blas.py#L2109

A desirable implementation would be calling only one operation like gemmBatched in cublas. http://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-gemmbatched

Several other frameworks, like tensorflow, also provide such implementations.

**Comment by khaotik** [comment]
That's the CPU implementation. When using `device=cuda*`, Theano graph optimization framework will replace CPU Op with corresponding GPU Op.
For GPU, I think the corresponding code is in `libgpuarray`. It calls batched gemm in cuBLAS.

**Comment by nouiz** [comment]
@khaotik is right. We already call batchedGemm from cublas on the GPU. You are right, we loop over gemm call on the CPU. MKL have a batchedGemm like interface, but we don't call it.

What made you think we don't call batchedGemm on the GPU?

**Comment by feiga** [comment]
Thanks, @khaotik @nouiz. My mistake : )
