### ISSUE TITLE
How to make `theano-cache purge` work on Windows if C++ compiler becomes mandatory ?

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6282]
Regarding https://github.com/Theano/Theano/pull/6253 . To make `theano-cache purge` work on Windows, we currently use a hack that forces the Theano flag `cxx` to have an empty value, so that Windows doesn't complain when we want to delete compiled modules: https://github.com/Theano/Theano/blob/master/bin/theano_cache.py#L7

If C++ compiler becomes mandatory, that hack will not work anymore, and we will get back to the bug (I temporarly deactivated the hack to reproduce the error):
```batch
(python2) C:\Users\notoraptor\mila\dev\git\theano>theano-cache
C:\Users\notoraptor\AppData\Local\Theano\compiledir_Windows-10-10.0.15063-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-2.7.13-64

(python2) C:\Users\notoraptor\mila\dev\git\theano>theano-cache purge
Traceback (most recent call last):
  File "C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\Scripts\theano-cache-script.py", line 11, in <module>
    load_entry_point('Theano', 'console_scripts', 'theano-cache')()
  File "c:\users\notoraptor\mila\dev\git\theano\bin\theano_cache.py", line 81, in main
    theano.gof.compiledir.compiledir_purge()
  File "c:\users\notoraptor\mila\dev\git\theano\theano\gof\compiledir.py", line 214, in compiledir_purge
    shutil.rmtree(config.compiledir)
  File "C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Accès refus: 'C:\\Users\\notoraptor\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.15063-Intel64_Family_6_Model_158_Stepping_9_GenuineIntel-2.7.13-64\\lazylinker_ext\\lazylinker_ext.pyd'
```

It seems Windows doesn't like that a same program loads a module and then tries to delete it. How to manage that ?

I will start working on it this week if I have time, but this might be difficult to solve.

@abergeron @nouiz 

NB: In fact, the best solution should be to find a way to avoid any compilation when it is not necessary.

**Comment by nouiz** [comment]
Don't work on that now. This is for after the release. There is other stuff for the release to do before.

We could make a special flag just for that. So it would be like "cxx=", but only allow to delete the cache. thanks for raising this problem we will hit when we do that.

**Comment by nouiz** [comment]
We won't do that change anymore, so closing.
