### ISSUE TITLE
support for cuda9 and cudnn7?

### ISSUE THREAD

**Issue by fayeshine** [Theano/Theano#6290]
support for cuda9 and cudnn7?

**Comment by borisfom** [comment]
I think that support is now in.

**Comment by nouiz** [comment]
Theano will compile for cudnn v7 in the dev version. We are still working
to wrap some new feature (like group convolution). This should be included
soon.

Theano compile with cuda9, except for float16 that we are also working on.

**Comment by nouiz** [comment]
This is done.
