### ISSUE TITLE
Bug with theano.tensor.sum in Theano 0.10.0b1

### ISSUE THREAD

**Issue by jacskiier** [Theano/Theano#6294]
Bug with theano.tensor.sum function. When summing across an axis using the theano config option mode=FAST_RUN. I am using Windows 10, python 2.7 Theano version 0.10.0b1. I have changed the config options so that optimizer=fast_compile and the problem goes away. Interestingly if you remove the constant 2.0 and replace it with iarg the bug disappears. I also believe I have seen this bug without doing a scan loop.
Code that creates problem is below:

```
import numpy as np
import theano.tensor as T
import theano

nLoops = 5
vec = np.arange(0, 10, dtype=np.float32)
slow_output = np.zeros((5, 10))
for i in range(nLoops):
    slow_output[i, :] = 2.0 * vec

slow_output = np.sum(slow_output.transpose(), axis=1)

def somefunction(iarg, vecArg):
    return 2.0 * vecArg

vecT = T.vector(dtype=theano.config.floatX)
outputT, updates = theano.scan(fn=somefunction,
                               outputs_info=None,
                               sequences=theano.tensor.arange(nLoops),
                               non_sequences=[vecT])
outputSummedT = T.sum(T.transpose(outputT), axis=1)
f3 = theano.function(inputs=[vecT], outputs=outputSummedT, updates=updates)

output = f3(vec)
print (slow_output)
print (output)
print (np.allclose(slow_output, output))
```

**Comment by nouiz** [comment]
I don't have this problem with your code on CPU, but only with the flag device=cuda.

What are your Theano flags? What is the output of your code snippet? Do you use the GPU?

thanks for the report.

**Comment by abergeron** [comment]
#6333 fixes the problem for me.

**Comment by nouiz** [comment]
fixed by gh-6333

thanks for the report.
