### ISSUE TITLE
Cannot load libwarpctc.so

### ISSUE THREAD

**Issue by reith** [Theano/Theano#6304]
Even so `warp-ctc` root path provided by `ctc.root`, compilation will fail until `LD_LIBRARY_PATH` is set explicitly.

`('The following error happened while compiling the node', GpuConnectionistTemporalClassification{compute_grad=True}(GpuContiguous.0, /placeholder, /placeholder), '\n', 'libwarpctc.so: cannot open shared object file: No such file or directory')`

**Comment by nouiz** [comment]
I just merged a PR that do some updates to the CTC code. Can you update to
the dev again and try without modifing LD_LIBRARY_PATH?

Also, can you give me your value of ctc.root and the output of "ls
YOUR_CTC_ROOT".

**Comment by reith** [comment]
Still happens.

```
$ python -c "import theano; print theano.config.ctc.root"
Using cuDNN version 5110 on context None
Mapped name None to device cuda: GeForce GTX 1080 Ti (0000:02:00.0)
/home/reith/deepspeech/warp-ctc/
```

```
/home/reith/deepspeech/warp-ctc/:
CMakeLists.txt  LICENSE  README.md  README.zh_cn.md  build  doc  include  src  tensorflow_binding  tests  torch_binding

/home/reith/deepspeech/warp-ctc/build:
CMakeCache.txt  CMakeFiles  Makefile  cmake_install.cmake  libwarpctc.so  test_cpu  test_gpu
```

**Comment by notoraptor** [comment]
Hello, @reith , could you run the following code in Python interpreter and post the result ?
```python
import theano.tensor.nnet.ctc as ctc
print(ctc.ctc_available())
print(ctc.ctc_available.path)
```

**Comment by reith** [comment]
Hi,

```
>>> print(ctc.ctc_available())
True
>>> print(ctc.ctc_available.path)
/home/reith/deepspeech/warp-ctc/build

```

**Comment by notoraptor** [comment]
Ok, it's really weird.

Can you post the entire error message ? Also, as it's a compilation error, Theano should have write an output file (check for a line that starts with `You can find the C code in this temporary file: ...` in console output to get the output file path). Could you post this file as attachment ?

**Comment by reith** [comment]
It's not a compilation error. It finely compiles against `libwarpctc` but It cannot be used later because It does not exist in library path. I cannot see where `ctc_available.path` is used, surely It must be added to LD_LIBRARY_PATH or provided by other means to theano.

**Comment by notoraptor** [comment]
Ok, I see.

`ctc_available.path` is used for compilation (`g++ -l<ctc_available.path> ...`), but indeed it's not automatically added to LD_LIBRARY_PATH later.

It may be an issue to resolve. @nouiz @abergeron ?

**Comment by notoraptor** [comment]
Hello @reith, could you test PR #6305 ? It should resolve this issue.

**Comment by reith** [comment]
Still raises error:
```
('The following error happened while compiling the node', GpuConnectionistTemporalClassification{compute_grad=True}(GpuContiguous.0, /placeholder, /placeholder), '\n', 'libwarpctc.so: cannot open shared object file: No such file or directory', '[*1 -> GpuConnectionistTemporalClassification{compute_grad=True}(<GpuArrayType<None>(float32, 3D)>, /placeholder, /placeholder), *1::1]')
```

But I see now output shared library is aware of libwarpctc directory. Can I get more verbose report?

**Comment by notoraptor** [comment]
Maybe with flag `exception_verbosity=high`.

I have pushed a new commit. Can you retry again with the updated PR ?

**Comment by reith** [comment]
Worked, Nice Job!

**Comment by notoraptor** [comment]
Ok @reith ! You are on Linux, right ?

@abergeron to resolve this issue, I had to avoid quotes around rpath for CTC library ( see new commits in PR #6305 ). Quite strange.

**Comment by reith** [comment]
> Ok @reith ! You are on Linux, right ?
Yes.
