### ISSUE TITLE
can run gpuarray backend without cuDNN ?

### ISSUE THREAD

**Issue by astrung** [Theano/Theano#6308]
For my card, its cuda compute capability is only 2.1. So it can not run with cuDNN (compute capability > 3.0 ). but with old gpu backend, it still can run with GPU with warning. So how can i config gpuarray without cuDNN ot ignore warning ?

**Comment by astrung** [comment]
this is my test results with `CPU`, `GPU-old backend` and `GPU-new backend`:

CPU:

    [Elemwise{exp,no_inplace}(<TensorType(float64, vector)>)]
    Looping 1000 times took 17.562541 seconds
    Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
      1.62323285]
    Used the cpu

GPU-old backend:

    WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next        release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to       switch at this URL:
      https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

     Using gpu device 0: GeForce GT 720M (CNMeM is disabled, cuDNN not available)
     [GpuElemwise{exp,no_inplace}(<CudaNdarrayType(float32, vector)>),     HostFromGpu(GpuElemwise{exp,no_inplace}.0)]
     Looping 1000 times took 1.871061 seconds
     Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
       1.62323296]
     Used the gpu

GPU-new backend:

     Can not use cuDNN on context None: cannot compile with cuDNN. We got this error: b'C:\\Users\\as\\AppData\\Local\\Temp\\try_flags_77o0uqwh.c:4:19: fatal error: cudnn.h: No such file or   directory\r\ncompilation terminated.\r\n'
     Mapped name None to device cuda0: GeForce GT 720M (0000:08:00.0)
     [GpuElemwise{exp,no_inplace}(<GpuArrayType<None>(float32, (False,))>), HostFromGpu(gpuarray)  (GpuElemwise{exp,no_inplace}.0)]
     Looping 1000 times took 1.140266 seconds
     Result is [ 1.23178029  1.61879349  1.52278066 ...,  2.20771813  2.29967761
       1.62323296]
     Used the cpu

Strange result with new back-end : test said that "Used the cpu", but its time is the fastest. So in third case, is it using CPU or GPU ?

**Comment by astrung** [comment]
Also, when i run with example from keras : https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py . With old backend i got this error : `Value 'sm_446217920' is not defined for option 'gpu-architecture`, but with new backend or cpu, it was fine.

**Comment by notoraptor** [comment]
@astrung, to use new backend without cuDNN, try theano flag `dnn.enabled=False`: http://deeplearning.net/software/theano_versions/dev/library/config.html#config.config.dnn.enabled

**Comment by nouiz** [comment]
Note, this flag will only remove us from trying to use cudnn. By default, we try to use it and fall back to not use it if not present. So this will only show what is being printed.

Be sure to use the dev version of Theano, otherwise 0.9 miss more functionality without cudnn.

But with such an old GPU, don't expect good speed up. If you can update it, that would really speed up your computation.

**Comment by astrung** [comment]
@nouiz By updating to dev version, this error is solved . But when i run test script from theano, it still shows : `Used the cpu`

**Comment by nouiz** [comment]
The script is probably not updated for the new back-end. Can you compare your scrit with this updated script in the dev doc?

http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html

**Comment by astrung** [comment]
thank. Its result is updated

**Comment by ashleshsortee** [comment]
@astrung, Is it still showing same result with cpu and gpu or does it changed?
In my case it's still showing same result with cpu as well as gpu.

Please help me out.
Thanks in advanced.
