### ISSUE TITLE
Error while executing test_ctc.py

### ISSUE THREAD

**Issue by deepali-c** [Theano/Theano#6314]
Hello,

I am using `theano rel-0.10.0beta1 ` and was trying to run the self test for CTC - `test_ctc.py`. 

I have the following set:
```
>>> print theano.config.ctc.root
/root/warp-ctc
>>> print theano.config.cuda.root
/usr/local/cuda
```

But while executing test_ctc.py, I see the following error:
`Exception: ('The following error happened while compiling the node', GpuConnectionistTemporalClassification{compute_grad=True}(GpuContiguous.0, labels, activation_times), '\n', 'Compilation failed (return status=1): In file included from /root/.theano/compiledir_Linux-4.4--generic-ppc64le-with-Ubuntu-16.04-xenial-ppc64le-2.7.12-64/tmpAkYWhF/mod.cpp:15:0:. /<myinstallpath>/include/gpuarray/ext_cuda.h:4:18: fatal error: cuda.h: No such file or directory. compilation terminated.. ', '[*1 -> GpuConnectionistTemporalClassification{compute_grad=True}(<GpuArrayType<None>(float32, 3D)>, labels, activation_times), *1::1]')`

**Comment by nouiz** [comment]
This week, we merged a PR that fix CTC wrapper in some environment. Can you update Theano to the dev version instead of the beta? This could fix your problem.

**Comment by deepali-c** [comment]
I tried with `master `branch, but it shows another error:. Commit id used -`d844e6c  `

`ImportError: ('The following error happened while compiling the node', GpuConnectionistTemporalClassification{compute_grad=False}(GpuContiguous.0, labels, activation_times), '\n', 'libwarpctc.so: cannot open shared object file: No such file or directory', '[GpuConnectionistTemporalClassification{compute_grad=False}(<GpuArrayType<None>(float32, 3D)>, labels, activation_times)]')`

The `libwarpctc.so` is located at:
```
 ls /root/warp-ctc/build
CMakeCache.txt  CMakeFiles  cmake_install.cmake  libwarpctc.so  Makefile  test_cpu  test_gpu
```

**Comment by notoraptor** [comment]
For the new error, we are working on it here: https://github.com/Theano/Theano/pull/6305 . Can you try this PR to check if it works ?

I had not yet time to finish the PR, but I will continue working on it today.

**Comment by deepali-c** [comment]
@notoraptor, I did run the tests with changes from [#6305](https://github.com/Theano/Theano/pull/6305)  and the tests passed. 

```
test_ctc (theano.gpuarray.tests.test_ctc.TestCTC) ... ok
test_torch_case (theano.gpuarray.tests.test_ctc.TestCTC) ... ok
test_verify_grad (theano.gpuarray.tests.test_ctc.TestCTC) ... ok
----------------------------------------------------------------------
Ran 3 tests in 19.885s
OK
```

**Comment by nouiz** [comment]
thanks I marked that PR as fixing this issue.
