### ISSUE TITLE
Issue in Visual studio 2017 with Cuda9 RC

### ISSUE THREAD

**Issue by finarb** [Theano/Theano#6320]
I am using the following theano flag
floatX=float32,device=gpu,nvcc.flags=-D_FORCE_INLINES,dnn.enabled=False,lib.cnmem=0.8,blas.ldflags=-LC:\deeplearning\OpenBLAS-v0.2.14-Win64-int32\bin -lopenblas

I am using visual studio 2017 with cuda 9 RC installation

in the visual studio command prompt when i type in "where cl" I get
(please note cuda smaple programs like devicequery works fine)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.11.25503\bin\Hostx86\x86\cl.exe

I have installed theano and open blas etc. . I run the following program

from theano import function, config, shared, sandbox
import theano.tensor as T
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], T.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, T.Elemwise) for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')

I get the error

Using gpu device 0: GeForce GTX 1070 (CNMeM is enabled with initial size: 80.0% of memory, cuDNN not available)
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from theano import function, config, shared, sandbox
  File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\__init__.py", line 116, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "C:\Users\finarb\AppData\Local\conda\conda\envs\py27\lib\site-packages\theano\sandbox\cuda\tests\test_driver.py", line 41, in test_nvidia_driver1
    raise Exception("The nvidia driver version installed with this OS "
Exception: The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads

However cuda 8 is not compatibe with VS 2017

**Comment by nouiz** [comment]
You are using the old GPU back-end. The new one is much easier to install on windows. It do not need MSVC anymore for the GPU.

I strongly suggest that you use the new GPU back-end: https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)

We also only have time to support the installation with conda on windows. You can install the 2 new dependency for GPU with conda: "conda install pygpu libgpuarray".
