### ISSUE TITLE
Tests for grouped convolution optimizations?

### ISSUE THREAD

**Issue by gvtulder** [Theano/Theano#6329]
@affanv14: I have a question about the GPU tests for the grouped convolution. Specifically, I'm not sure why these lines look the way they do: https://github.com/Theano/Theano/blob/5cc70bc0b826682c34ec465f367e77cc0c953e15/theano/gpuarray/tests/test_gemmcorr.py#L225-L232 Shouldn't the first `conv = GpuCorrMM` point to the AbstractConv2d function? (And similar for the gradients.)

Perhaps I'm missing something, but it seems that at the moment, the optimization that replaces `AbstractConv2d` with `GpuCorrMM` is not tested anywhere for grouped convolutions.

In the `Grouped_conv_noOptim` base class, you call this function to build an op: https://github.com/Theano/Theano/blob/5cc70bc0b826682c34ec465f367e77cc0c953e15/theano/tensor/nnet/tests/test_abstract_conv.py#L1475-L1478 and then, a few lines later, check if this abstract op has been replaced in the optimization:
https://github.com/Theano/Theano/blob/5cc70bc0b826682c34ec465f367e77cc0c953e15/theano/tensor/nnet/tests/test_abstract_conv.py#L1487-L1489

This line looks as if it should test if the CPU to GPU optimization works. In the GPU test, however, you're now directly constructing a GpuCorrMM op, which skips the optimization and makes this test a bit pointless.

I came across this while reading the unshared convolution tests. There's something similar in https://github.com/Theano/Theano/blob/5cc70bc0b826682c34ec465f367e77cc0c953e15/theano/gpuarray/tests/test_dnn.py#L2289-L2298

Did I misunderstand anything, or can these bits be improved?

**Comment by nouiz** [comment]
Or you could modify the current test to build with the abstract conv op and
make sure you assert the GPU op is introduced.

**Comment by gvtulder** [comment]
> Or you could modify the current test to build with the abstract conv op and
make sure you assert the GPU op is introduced.

That's also how the other AbstractConv tests do it: they build the abstract op and check that if has been replaced. I think that's a nice solution and it's only a small change to the tests.

**Comment by affanv14** [comment]
Alright, i'll put it up within an hour

**Comment by gvtulder** [comment]
Fixed in #6332. Thanks!
