### ISSUE TITLE
Could it be acceptable to extend PATH at runtime with required folders ?

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6330]
For example, on Windows, we always need to add cuDNN bin path to system `PATH` environment variable so that `cudnn*.dll` can be found to run cuDNN-related Theano ops.

What about directly add the required folder (here `theano.config.dnn.bin_path`, if defined) at runtime to `PATH` ? Doing that, PATH will be automatically correctly set by Theano and only inside Theano (changes are discarded as soon as Python closes). I made a branch about that: https://github.com/Theano/Theano/compare/master...notoraptor:allow-modify-path-at-runtime

Is it risky/unsafe, @nouiz @abergeron @lamblin ?

**Comment by abergeron** [comment]
The rpath workaround doesn't work?

Because the risk of doing that is that there are other DLLs in the same directory as cudnn and we could pick them up by accident.

**Comment by notoraptor** [comment]
Rpath doesn't seem to work on Windows, as I still have to extend `PATH` env variable to make cuDNN work (otherwise, it compiles, but there is a DLL error: `ImportError: ('The following error happened while compiling the node', DnnVersion(), '\n', 'DLL load failed: Le module sp\xe9cifi\xe9 est introuvable.', '[DnnVersion()]')`).

**Comment by abergeron** [comment]
Since -rpath doesn't work, then we would have to go with PATH manipulation like suggested here.

I'm ok with that given that we have no other alternative.

**Comment by nouiz** [comment]
What about printing a user error message that tell the user how to fix the
path instead of doing it ourselves if it is dangerous to do it
automatically?

**Comment by abergeron** [comment]
It's not terribly dangerous to do it ourselves, especially since it doesn't have any incidence on any other running process.

The only reason we don't do it on other platforms is that it doesn't work.

**Comment by nouiz** [comment]
k
