### ISSUE TITLE
raise Exception("Error, malformed dictionary!")

### ISSUE THREAD

**Issue by aj112** [Theano/Theano#6335]
THEANO_FLAGS=mode=FAST_RUN,device=cuda,floatX=float32 python train.py --prototype prototype_ubuntu_HRED > Model_Output.txt

raise Exception("Error, malformed dictionary!")
Exception: Error, malformed dictionary!
how solve this issue

**Comment by nouiz** [comment]
What is the full error message?

**Comment by lamblin** [comment]
This error does not seem to come from Theano.
