### ISSUE TITLE
Segmentation fault when compiling convolution codes

### ISSUE THREAD

**Issue by wangsix** [Theano/Theano#6344]
```
> python -c "import theano; print theano.__version__"
Using cuDNN version 5110 on context None
Mapped name None to device cuda0: Quadro P1000 (0000:05:00.0)
0.10.0beta1.dev-550703c41b5ce05dd0b85e0b159204a344f1da11

> python -c "import pygpu; print pygpu.__version__"
0.6.9
```

Segmentation faults started to happen yesterday after I upgraded libgpuarray to the latest version when I run codes that include convolution layers. My .theanorc looks like this,

```
[global]
floatX = float32
device = cuda0
exception_verbosity=high
```

I have tried revert libgpuarray back to 0.6.8 and/or Theano to 0.9.0, but none of them worked. An example of the segmentation fault looks like this, with the script from [deeplearning.net](http://deeplearning.net/tutorial/code/convolutional_mlp.py)

```
> python convolutional_mlp.py 
... loading data
... building the model
Segmentation fault
``` 

I use print to locate when did the segmentation fault happens, and it is always when calling the `theano.function`. And theano runs fine when I tested on other example codes where there is no convolution involved. And both gpu_tutorial1.py and gpu_tutorial2.py could run normally with GPU.

Please let me know what information should I provide or how should I gather more information as to why this is happening. 

p.s. The convolution codes were running fine before yesterday...

**Comment by nouiz** [comment]
I just merged the fix: https://github.com/Theano/Theano/pull/6341

So just update Theano to the dev version again.

**Comment by wangsix** [comment]
Works like a charm. Thank you.
