### ISSUE TITLE
hed-dlg-truncated/convert-wordemb-dict2emb-matrix.py

### ISSUE THREAD

**Issue by aj112** [Theano/Theano#6345]
python convert-wordemb-dict2emb-matrix.py tests/data/ttrain.dict.pkl WordEmb/D_german_50k_500k_168h.pkl --emb_dim 15 temb_pretrained
    python convert-wordemb-dict2emb-matrix.py Data/Training.dict.pkl WordEmb/D_german_50k_500k_168h.pkl --apply_spelling_corrections --emb_dim 300 OutMat

how to generate  "WordEmb/D_german_50k_500k_168h.pkl --emb_dim 15 temb_pretrained"
plese can u give example

**Comment by nouiz** [comment]
See answer in https://github.com/Theano/Theano/issues/6346

Please don't open many related issues. Continue on the opened issues or mailing list.
