### ISSUE TITLE
Exception: Model dictionary file not found

### ISSUE THREAD

**Issue by aj112** [Theano/Theano#6346]
python convert-wordemb-dict2emb-matrix.py Data/Training.dict.pkl WordEmb/GoogleNews-vectors-negative300.bin --apply_spelling_corrections --emb_dim 300 Word2Vec_WordEmb
The following non-word tokens will not be extracted from the pretrained embeddings:  ['<s>', '</s>', '<t>', '</t>', '<unk>', '.', ',', '``', "''", '[', ']', '`', '-', '--', "'", '<pause>', '<first_speaker>', '<second_speaker>', '<third_speaker>', '<minor_speaker>', '<voice_over>', '<off_screen>', '</d>']
INFO:covert-wordemb-dict2emb-matrix:Word2Vec embeddings given as input
INFO:covert-wordemb-dict2emb-matrix:Applying spelling corrections
INFO:covert-wordemb-dict2emb-matrix:Final word embedding dim: 300
INFO:covert-wordemb-dict2emb-matrix:Final standard deviation: 0.010000
Traceback (most recent call last):
  File "convert-wordemb-dict2emb-matrix.py", line 107, in <module>
    raise Exception("Model dictionary file not found!")
Exception: Model dictionary file not found!
useful.

**Comment by nouiz** [comment]
This is not a Theano question. From a similar email to theano-user, I think you are using another repository that use Theano. But this error is not related to Theano and I don't know the other repository. So we can't help here. You can ask your question on that repository. Maybe someone on theano-user can answer, too, but this isn't sure.
