### ISSUE TITLE
Model Sampling & Testing

### ISSUE THREAD

**Issue by aj112** [Theano/Theano#6352]
To generate model responses using beam search run:

THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=gpu python sample.py <model_name> <model_outputs> --beam_search --n-samples= --ignore-unk --verbose
i am confused abour context ,beam search and verbose.can u give example from where i can get these three parameters.
while model name is automticaly generated during training that i can get already.
thanks
https://github.com/julianser/hed-dlg-truncated

**Comment by bouthilx** [comment]
Question unrelated to Theano and you already made an issue at the right repo https://github.com/julianser/hed-dlg-truncated/issues/23.
