### ISSUE TITLE
Could not initialize pygpu, support disabled and with messy error information

### ISSUE THREAD

**Issue by whr94621** [Theano/Theano#6375]
Hello!

When I use theano 0.10 beta1 and pygpu 0.6.9 (install by conda). I get an error with messy information:

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/weihr/.local/share/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 179, in <module>
    use(config.device)
  File "/home/weihr/.local/share/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 166, in use
    init_dev(device, preallocate=preallocate)
  File "/home/weihr/.local/share/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 65, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init
  File "pygpu/gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__
GpuArrayException: cuInit: H󿿈	!:  Uޘ
Xshell[[-2.00841212 -0.05159963 -0.98285401  0.10107603  1.57511783]
 [-0.53133559 -1.09789515 -0.49902084 -0.86987436 -1.92696702]
 [ 0.72849804  1.24937284  0.92536372  2.23327947  0.2123798 ]]
[[ 0.11832253  0.48710296  0.27232584  0.52524751  0.82851195]
 [ 0.37020543  0.2501345   0.37777081  0.29528046  0.12708667]
 [ 0.67447561  0.77719128  0.71613371  0.90319848  0.55289626]]

what  "cuInit: H󿿈	!:"  Uޘ mean?

I use cuda 8.0 with cudnn 5.1
My system is ubuntu 14.04.

Here is my code:

```
"""
test_new_backend.py
"""
import theano
from theano import tensor
import numpy as np

x = tensor.matrix('x', dtype='float32')

y = tensor.nnet.sigmoid(x)

f_test = theano.function(inputs=[x], outputs=y, name='f_test')

x = np.random.randn(3,5).astype('float32')

print x
print f_test(x)
```
and this is script to run the python code

```
#!/usr/bin/env bash
export THEANO_FLAGS=device=cuda,floatX=float32,mode=FAST_RUN

python2 ./test_new_backend.py
```

**Comment by nouiz** [comment]
Did you solved it? Normally, I would expect an error from the OS that got mangled due to the local (different language). What is the language of your OS?

Do you have cuda nvidia driver installed? what is the output of this command line: "nvidia-smi"

**Comment by abergeron** [comment]
This is probably because you have the stubs directory on your LD_LIBRARY_PATH.

Those are non-functional libraries and they cause problems like this, remove them and it should work.

**Comment by nouiz** [comment]
no reply and answer should have fixed it, so closing.
