### ISSUE TITLE
import theano error; RuntimeError: 'path' must be None or a list

### ISSUE THREAD

**Issue by kite8** [Theano/Theano#6380]
theano : 0.9.0
python: 3.5

[blas]
ldflags = 
[gcc]
cxxflags = -IE:\Program Files\MinGW\include
[nvcc]
flags=-LE:\ProgramData\Anaconda3\envs\tensorflow\libs
compiler_bindir=E:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64
[global]
device=gpu
floatX=float32

I doubt it's something wrong with the compiler_bindir , but I don't know the vs2017 bin dir where . 

`import theano
Traceback (most recent call last):

  File "<ipython-input-1-3397704bd624>", line 1, in <module>
    import theano

  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\theano\__init__.py", line 108, in <module>
    import theano.sandbox.cuda

  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\theano\sandbox\cuda\__init__.py", line 153, in <module>
    compile_cuda_ndarray = not try_import()

  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\theano\sandbox\cuda\__init__.py", line 126, in try_import
    import cuda_ndarray.cuda_ndarray

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 892, in _find_spec

  File "<frozen importlib._bootstrap>", line 873, in _find_spec_legacy

  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\pyximport\pyximport.py", line 253, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)

  File "E:\ProgramData\Anaconda3\envs\tensorflow\lib\imp.py", line 270, in find_module
    "not {}".format(type(path)))

RuntimeError: 'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>`

**Comment by notoraptor** [comment]
Hello @kite8 :
- In your `.theanorc`, do not set compiler_bindir. I suggest you remove that line (`compiler_bindir=E:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64`) to let Theano choose the default compiler directory. Also, `compiler_bindir` is not related to Visual Studio at all, compiler bin dir is a directory where Theano compiles operations that are used later in computations.
- Consider using `device=cuda` instead of `device=gpu` so that Theano uses his new GPU backend. Old GPU backend (the one used with `device=gpu`) is not supported anymore in latest development releases.

Also, you should better update Theano to `0.10.0beta1`.

**Comment by kite8** [comment]
Thanks, @notoraptor , I change the  .theanorc file, like this, I update Theano to 0.10.0beta1, update cuDNN

> [global]
device=cuda
floatX=float32



> `nvcc

 fatal   : Cannot find compiler 'cl.exe' in PATH

['nvcc', '-shared', '-O3', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcom
piler', '-DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATE
D_API=NPY_1_7_API_VERSION,/Zi,/MD', '-I"E:\\ProgramData\\Anaconda3\\envs\\tensor
flow\\lib\\site-packages\\theano\\sandbox\\cuda"', '-I"E:\\ProgramData\\Anaconda
3\\envs\\tensorflow\\lib\\site-packages\\numpy\\core\\include"', '-I"E:\\Program
Data\\Anaconda3\\envs\\tensorflow\\include"', '-I"E:\\ProgramData\\Anaconda3\\en
vs\\tensorflow\\lib\\site-packages\\theano\\gof"', '-L"E:\\ProgramData\\Anaconda
3\\envs\\tensorflow\\libs"', '-L"E:\\ProgramData\\Anaconda3\\envs\\tensorflow"',
 '-o', 'C:\\Users\\kite\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-S
P1-Intel64_Family_6_Model_45_Stepping_7_GenuineIntel-3.5.3-64\\cuda_ndarray\\cud
a_ndarray.pyd', 'mod.cu', '-lcublas', '-lpython35', '-lcudart']
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return st
atus', 1, 'for cmd', 'nvcc -shared -O3 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcomp
iler -DCUDA_NDARRAY_CUH=mc72d035fdf91890f3b36710688069b2e,-DNPY_NO_DEPRECATED_AP
I=NPY_1_7_API_VERSION,/Zi,/MD -I"E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\l
ib\\site-packages\\theano\\sandbox\\cuda" -I"E:\\ProgramData\\Anaconda3\\envs\\t
ensorflow\\lib\\site-packages\\numpy\\core\\include" -I"E:\\ProgramData\\Anacond
a3\\envs\\tensorflow\\include" -I"E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\
lib\\site-packages\\theano\\gof" -L"E:\\ProgramData\\Anaconda3\\envs\\tensorflow
\\libs" -L"E:\\ProgramData\\Anaconda3\\envs\\tensorflow" -o C:\\Users\\kite\\App
Data\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_45
_Stepping_7_GenuineIntel-3.5.3-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -lcubla
s -lpython35 -lcudart')
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is to
o old (version 0.6 or higher required)
NoneType: None`

At last, I clean up the .theanorc file

**Comment by notoraptor** [comment]
Could you clear theano cache (type `theano-cache purge` in command line) and then retry ? This error should not happen.

Also, have you installed `pygpu` ? If you use conda, you can install it by typing `conda install pygpu`.

**Comment by kite8** [comment]
@notoraptor  
At last, I clean up the .theanorc file, then I import theano, It succeed.
```
(tensorflow) C:\Users\kite>conda list pygpu
# packages in environment at E:\ProgramData\Anaconda3\envs\tensorflow:
#
pygpu                     0.7.1               np112py35_0    https://mirrors.tun
a.tsinghua.edu.cn/anaconda/cloud/conda-forge
```

**Comment by notoraptor** [comment]
I am surprised that you have pygpu version `0.7.1`, and I think it may not work with theano 0.10.0beta1.

If you encounter some problems, consider install pygpu 0.6.9 (`conda install pygpu=0.6.9`) until theano 0.10.0bet2 be released.
