### ISSUE TITLE
Request for truncated normal distribution

### ISSUE THREAD

**Issue by mrTsjolder** [Theano/Theano#6381]
In neural networks, it has become common to initialise the weight by means of truncated normals. Tensorflow uses a simplified version of the truncated normal that simply cuts off the tails after two standard deviations ([tensorflow docs](https://www.tensorflow.org/api_docs/python/tf/truncated_normal)). An implementation of a truncated normal still seems to be missing in Theano, however. I only discovered this issue through the [poor man's implementation in keras](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L2238-L2246), which got me on the wrong leg in my analysis.

After taking a look at the code of `MRG_RandomStreams`, I found out that sampling from the [normal distribution](https://github.com/Theano/Theano/blob/master/theano/sandbox/rng_mrg.py#L1032-L1118) is done by means of the Box-Muller transform. While reading the referenced Wikipedia page, I found [this section on tails truncation](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform#Tails_truncation), which suggests that a truncated normal distribution with borders at `2 * std` should not be too hard to implement. 

Concretely, it would be nice to have something like

    def _normal_from_uniform(self, size, avg=0.0, std=1.0, low=0.0
                             ndim=None, dtype=None, nstreams=None):
        # the previous normal implementation with extra parameter
        # from: value in range [0, 1[ for cutting off tails
        avg = undefined_grad(as_tensor_variable(avg))
        std = undefined_grad(as_tensor_variable(std))

        if dtype is None:
            dtype = scal.upcast(config.floatX, avg.dtype, std.dtype)

        avg = cast(avg, dtype)
        std = cast(std, dtype)

        evened = False
        constant = False
        if (isinstance(size, tuple) and
                all(isinstance(i, (np.integer, integer_types)) for i in size)):
            constant = True
            n_samples = np.prod(size, dtype='int64')

            if n_samples % 2 == 1:
                n_samples += 1
                evened = True
        else:
            n_samples = prod(size) + (prod(size) % 2)

        # Use from to limit the number of samples (only necessary change)
        flattened = self.uniform(size=(n_samples,), low=from,
                                 dtype=dtype, nstreams=nstreams)

        if constant:
            U1 = flattened[:n_samples // 2]
            U2 = flattened[n_samples // 2:]
        else:
            U1 = flattened[:prod(flattened.shape) // 2]
            U2 = flattened[prod(flattened.shape) // 2:]

        sqrt_ln_U1 = sqrt(-2.0 * log(U1))
        trigo_domain = np.array(2.0 * np.pi, dtype=dtype) * U2

        first_half = sqrt_ln_U1 * cos(trigo_domain)
        second_half = sqrt_ln_U1 * sin(trigo_domain)
        normal_samples = join(0, first_half, second_half)

        final_samples = None
        if evened:
            final_samples = normal_samples[:-1]
        elif constant:
            final_samples = normal_samples
        else:
            final_samples = normal_samples[:prod(size)]

        if not size:
            size = tensor.constant(size, dtype='int64')
        final_samples = final_samples.reshape(size)

        final_samples = avg + std * final_samples

        assert final_samples.dtype == dtype
        return final_samples

    def normal(self, size, avg=0.0, std=1.0, ndim=None,
               dtype=None, nstreams=None):
        return self._normal_from_uniform(size, avg=avg, std=std, low=0.0,
                                         ndim=ndim, dtype=dtype, 
                                         nstreams=nstreams)
        
    def truncated_normal(self, size, avg=0.0, std=1.0, ndim=None,
                                         dtype=None, nstreams=None):
        return self._normal_from_uniform(size, avg=avg, std=std, 
                                         low=0.0773929018493629,
                                         ndim=ndim, dtype=dtype, 
                                         nstreams=nstreams)

in `MRG_RandomStreams`. I removed the comments in the original implementation of `normal` and added my own comments for the purpose of clarity. The from-value in the truncated normal has been retrieved through [wolfram alpha](http://www.wolframalpha.com/input/?i=sqrt(-2*ln(x))+*+cos(2*pi*x)+%3D+2) for clipping the tails at 2 times the standard deviation.

Would this be possible/useful?

**Comment by mrTsjolder** [comment]
Okay, I should have tested this before throwing this on here. It's obviously not that easy, however the request remains. It would be nice to see a truncated normal distribution implemented...

**Comment by nouiz** [comment]
Adding new distribution that user will use is useful. I don't have time to
check the implement today. Can you make a PR with this? You seem to have
most of the work done.

Thanks

**Comment by mrTsjolder** [comment]
First of all, the code I have written in my original feature request is useless. After some research, I managed to generate a truncated normal from the Box-Muller transform in numpy:

```
import numpy as np

def box_muller_transform(uniform, dtype=None):
    uniform = np.ravel(uniform)

    if dtype is None:
        dtype = uniform.dtype

    half = uniform.size // 2
    u1 = uniform[:half]
    u2 = uniform[-half:]

    big_r = np.sqrt(-2.0 * np.log(u1))
    theta = np.array(2.0 * np.pi, dtype=dtype) * u2
    sin_theta = np.sin(theta)
    cos_theta = np.cos(theta)

    z0 = big_r * cos_theta
    z1 = big_r * sin_theta

    return np.concatenate([z0, z1], 0)

def truncated_box_muller_transform(uniform, dtype=None):
    uniform = np.ravel(uniform)

    if dtype is None:
        dtype = uniform.dtype

    half = uniform.size // 2
    u1 = uniform[:half]
    u2 = uniform[-half:]

    big_r = np.sqrt(-2. * np.log(u1))
    theta = np.array(2. * np.pi, dtype=dtype) * u2
    sin_theta = np.sin(theta)
    cos_theta = np.cos(theta)

    z0 = big_r * cos_theta
    z1 = big_r * sin_theta

    fix0 = np.where(np.logical_or(z0 < -2., z0 > 2.))[0]
    fix1 = np.where(np.logical_or(z1 < -2., z1 > 2.))[0]

    fix_uniform = np.random.uniform(low=0.13585, size=fix0.size + fix1.size)
    fix_big_r = np.sqrt(-2. * np.log(fix_uniform))

    z0[fix0] = fix_big_r * cos_theta[fix0]
    z1[fix1] = fix_big_r * sin_theta[fix1]

    return np.concatenate([z0, z1], 0)
```

I will have to take a closer look at the Theano implementation again when I have some more time again, but I think the resulting code should be similar.

If there are any remarks, suggestions or improvements, I would be grateful for the feedback.

**Comment by mrTsjolder** [comment]
Implementation added thanks to nouiz!
