### ISSUE TITLE
Assertion error during training my model 

### ISSUE THREAD

**Issue by Rabia-Noureen** [Theano/Theano#6385]
Hi I am a newbie I am trying to train my model using my data set CustomerReviewData that is encoded in UTF-8 and i am using GoogleNews Pretrained Word embedding that is a .gz file....
http://www.cs.uic.edu/~liub/FBS/CustomerReviewData.zip
https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit
Kindly guide me as i am stuck with an Assertion error.
![image](https://user-images.githubusercontent.com/29410483/30082219-17e72bc8-929b-11e7-953c-e050f6f70d96.png)

I tried another dataset but then got:
![image](https://user-images.githubusercontent.com/29410483/30081913-01d437dc-929a-11e7-9a08-d4e96c613cf2.png)

Kindly help me debug the problem as i am stuck with this issue for the past 2 days.

**Comment by mrTsjolder** [comment]
This is not the place to ask for help with debugging your code. Even [stackoverflow](https://stackoverflow.com) does not generally welcome these types of questions. Maybe you should try asking on [codereview](https://codereview.stackexchange.com).

**Comment by nouiz** [comment]
The error is not related to Theano, but to your data loader that isn't in Theano. So I'll close this issue.

Probably the file itself isn't in the right format. I can't help more. Maybe you would get more help on the theano-user mailing list. Sometimes other user are able to help on such type of question.
