### ISSUE TITLE
Is it possible to set RandomStreams seed with a variable?

### ISSUE THREAD

**Issue by david-leon** [Theano/Theano#6394]
I need to define a function with random seed input, however `RandomStreams` does not accept a tensor variable as `seed` input.

Is there any way to fulfill this?

**Comment by nouiz** [comment]
For this, you will need to make a new op that take a seed as input and
generate a random state. Then you will need to use that state in the graph.

But why your seed cannot be set normally in the random state?

**Comment by david-leon** [comment]
@nouiz I'm building a generative model, and the model is expected to generate samples randomly at each run. Currently the model's `predict()` function is defined like:
```
def predict(self, x):
    srng = RandomStreams(seed=np.random.randint(1, 2147462579))
...
```
However, the compiled function generates same result at each run. I think the reason is that the random seed of `RandomStreams` is already fixed during compilation.

**Comment by david-leon** [comment]
OK, I've got a workaround: since there's `scan()` in the model's `predict()` function, I compile this function with `theano.function` 's `updates` set to `updates` returned by `scan()`. This will reuse the random state of last run.

**Comment by nouiz** [comment]
I don't get it. When scan return updates, you must pass it to calls to Theano function that use that scan.

Anyway, as you fixed your problem, I'll close this issue.
