### ISSUE TITLE
theano-0.10.0beta2 even simple funcs crash in multi-GPU setup after recompile

### ISSUE THREAD

**Issue by amurashov** [Theano/Theano#6422]
Hello all!

I am testing theano multi-GPU support and apparently there is some bug in internals which make the gpu backend crash after function recompile (different contexts cleanup issues?). Following code crashes always and exactly on _**third**_ iteration:

----
```
import theano
import numpy as np
for iter in range(10):
    t0 = theano.shared(1 * np.ones(shape=(20,)).astype(theano.config.floatX),  target = 'dev1')
    t1 = theano.shared(2 * np.ones(shape=(20,)).astype(theano.config.floatX),  target = None)

    fn = theano.function([], outputs=[t0 + t1 * t0])
    fn()
    print ("Iter %d went okay!" % (iter))
```

theano.__version__ = '0.10.0beta2.dev-867878721d14a6d530dbe798143bc5727b19454e'
pygpu.__version__ = u'0.7.2'
theano.config.device = 'cuda0'
theano.config.contexts = 'dev1->cuda1;dev2->cuda2;dev3->cuda3' #other combinations also tried!

Output looks like this (with a bit of my formatting):

> Using cuDNN version 6021 on context None
Preallocating 10867/11439 Mb (0.950000) on cuda0
Mapped name None to device cuda0: Tesla K80 (0000:0A:00.0)
Using cuDNN version 6021 on context dev1
Preallocating 10867/11439 Mb (0.950000) on cuda1
Mapped name dev1 to device cuda1: Tesla K80 (0000:0B:00.0)
Using cuDNN version 6021 on context dev2
Preallocating 10867/11439 Mb (0.950000) on cuda2
Mapped name dev2 to device cuda2: Tesla K80 (0000:0E:00.0)
Using cuDNN version 6021 on context dev3
Preallocating 10867/11439 Mb (0.950000) on cuda3
Mapped name dev3 to device cuda3: Tesla K80 (0000:0F:00.0)
Iter 0 went okay!
Iter 1 went okay!
GpuArrayException                         Traceback (most recent call last)
[LOTS OF TEXT]
GpuArrayException: 
Apply node that caused the error: GpuToGpu<None>(<GpuArrayType<dev1>(float32, vector)>)
Toposort index: 0
Inputs types: [GpuArrayType<dev1>(float32, vector)]
Inputs shapes: [(20,)]
Inputs strides: [(4,)]
Inputs values: ['not shown']
Outputs clients: [[GpuElemwise{Mul}[(0, 1)]<gpuarray>(<GpuArrayType<None>(float32, vector)>, GpuToGpu<None>.0)]]
Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/amur/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/amur/anaconda2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/amur/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/amur/anaconda2/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/amur/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/amur/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/amur/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-9e24e69d569b>", line 5, in <module>
    t0 = theano.shared(1 * np.ones(shape=(20,)).astype(theano.config.floatX),  target = 'dev1')
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by nouiz** [comment]
Multi-GPU in one process is still experimental. You can do multi-GPU for data paralelism with a few library on top of Theano: https://github.com/Theano/Theano/wiki/Related-projects#parallelism

We don't have much time for this specific issue of multi-GPU in one process as there is probably not just this issue. You will probably hit other problem after this one. But if you give me the missing part of the error in "[LOTS OF TEXT]", I can quickly look if I can fix this problem.
