### ISSUE TITLE
UndefinedGrad wrapping of pvals in mrg multinomial results in GPU->CPU->GPU transfer

### ISSUE THREAD

**Issue by amurashov** [Theano/Theano#6423]
Hello all.

With special regards to this post: https://github.com/Theano/Theano/issues/6408

Wrapping mentioned there (and in topic of this issue) results in following graph in the function - which is, probably, no what was intended:
![gpucpugpu](https://user-images.githubusercontent.com/32039151/30523274-fe8d13a2-9bde-11e7-848e-c6d712683868.JPG)

**Comment by nouiz** [comment]
This code generate the problem with device=cuda

```
import numpy as np
import theano
import theano.tensor as T
from theano.gradient import zero_grad
from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams
random = RandomStreams(np.random.randint(1, 2147462579))
pvals = theano.shared(np.random.rand(10, 20).astype(theano.config.floatX))
pvals = pvals / pvals.sum(axis=1)
pvals = zero_grad(pvals)
samples = random.multinomial(pvals=pvals, n=1)
samples = T.cast(samples, pvals.dtype)
samples = zero_grad(samples)
cost = T.sum(samples + pvals)
grad = T.grad(cost, samples)
f=theano.function([], grad)
theano.printing.debugprint(f)
```

**Comment by nouiz** [comment]
Fix here:

https://github.com/Theano/Theano/pull/6425

We will remove that node from the graph completely.
