### ISSUE TITLE
getting odd run time error related to installation

### ISSUE THREAD

**Issue by rnunziata** [Theano/Theano#6429]
getting odd run time error related to installation: can someone give insight.

I used pip to install 

```
  File "predict.py", line 13, in <module>
    import train
  File "/home/rjn/opencv3-p3-code/classification_and_boxing/newstuff/FRRN/FRRN/train.py", line 11, in <module>
    import lasagne
  File "/home/rjn/miniconda2/lib/python2.7/site-packages/lasagne/__init__.py", line 12, in <module>
    import theano
  File "/home/rjn/miniconda2/lib/python2.7/site-packages/theano/__init__.py", line 68, in <module>
    from theano.version import version as __version__
  File "/home/rjn/miniconda2/lib/python2.7/site-packages/theano/version.py", line 14, in <module>
    int(short_version.split('.')[2])
IndexError: list index out of range

```

If I install via conda I get the following error:

```
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.6 or higher required)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 23, in <module>
    import pygpu.version
ImportError: No module named version


```

**Comment by nouiz** [comment]
You have a bad version of Theano. Can you update to the dev version? It should have that fixed.

**Comment by rnunziata** [comment]
Still getting this error:

```
Traceback (most recent call last):
  File "predict.py", line 13, in <module>
    import train
  File "/home/rjn/opencv3-p3-code/classification_and_boxing/newstuff/FRRN/FRRN/train.py", line 11, in <module>
    import lasagne
  File "/usr/local/lib/python2.7/dist-packages/lasagne/__init__.py", line 12, in <module>
    import theano
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 68, in <module>
    from theano.version import version as __version__
  File "/usr/local/lib/python2.7/dist-packages/theano/version.py", line 14, in <module>
    int(short_version.split('.')[2])
IndexError: list index out of range
rjn@rjn-Oryx-Pro:~/opencv3-p3-code/c

```
I removed all references and libs for theano and pygpu on my system.
I down loaded theano from github to get the latest and compiled  and installed it,
then
conda install pygpu=0.7.0

```
/usr/local/lib/python2.7/dist-packages/pygpu-0.7.2+18.g2e73170-py2.7-linux-x86_64.egg/pygpu
/usr/local/lib/python2.7/dist-packages/theano
```
I made sure that the theano versions is the same as that which I complied for theano dev and put set up the env vars.

**Comment by nouiz** [comment]
pygpu 0.7.0 is old. Can you do:

conda update -c mila-udem/label/pre pygpu=0.7.2

How did you install Theano? I think you don't have the dev version, the dec
version have that fixed. Maybe we need the new fix that was merged
yesterday or today, so depending of when you updated Theano, updating it
again could fix this problem.

**Comment by rnunziata** [comment]
after installing with conda i get the following if I run it:

```
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
Traceback (most recent call last):
  File "/home/rjn/Theano/theano/gpuarray/__init__.py", line 21, in <module>
    import pygpu
ImportError: No module named pygpu

```
note: the results of find below

sudo find . / -name pygpu
[sudo] password for rjn: 
find: ‘/run/user/1000/gvfs’: Permission denied
/usr/local/lib/python2.7/dist-packages/pygpu-0.7.2+18.g2e73170-py2.7-linux-x86_64.egg/pygpu


I installed Theano by downloading it form github which according to website is the latest devel copy.

thank you for taking time to look at this.

**Comment by nouiz** [comment]
Can you execute:

python -c "import pygpu; print(pygpu.__version__)"

**Comment by rnunziata** [comment]
python -c "import pygpu; print(pygpu.__version__)"
0.7.2+18.g2e73170

**Comment by abergeron** [comment]
The packages in /usr/local/lib/python2.7 are not from conda.  They are from the system python.

The most likely reason for this is that the pip in your path is not the one from conda.  You can check that with `which pip`.  Also you should check if the python that you run is from the system or conda with a similar `which python`.

**Comment by rnunziata** [comment]
Are you saying that for Theano to work python needs to be installed with conda that Theano is dependent on?  I am going to close this issue. Conda is incompatible with other installs on my system  and break things if I put it in the path. Also I did try to do  as you said above  but it did not resolve the problem. Anyway thanks much for your help...sorry I could not implement. Moving on.

**Comment by abergeron** [comment]
For Theano to work, you need to install libgpuarray/pygpu and Theano in the same python.  We recommend conda, but it can work with the system python if that is what you need.

But you can't conda install pygpu and then use the system python for Theano that can't work.

**Comment by RaskaFR** [comment]
Hello,
I've the same error:
```
>>> import theano
0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 68, in <module>
    from theano.version import version as __version__
  File "/usr/local/lib/python2.7/dist-packages/theano/version.py", line 14, in <module>
    int(short_version.split('.')[2])
IndexError: list index out of range
```
Here is some information about Theano, pygpu,...:
- `python -c "import pygpu; print(pygpu.__version__)"`

`0.7.3+10.gc228dc9`

- `which python`

`/usr/bin/python`

- `which pip`

`/usr/local/bin/pip`

- `pip show theano`

`Name: Theano`
`Version: 0.10.0b3+unknown`
`Summary: Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.`
`Home-page: http://deeplearning.net/software/theano/`
`Author: LISA laboratory, University of Montreal`
`Author-email: theano-dev@googlegroups.com`
`License: BSD`
`Location: /usr/local/lib/python2.7/dist-packages`
`Requires: numpy, scipy, six`

Please, don't hesitate to share some information in order to solve this problem.

Thank you !

**Comment by nouiz** [comment]
How did you install Theano, pygpu and libgpuarray?

Can you use conda and install them like this:

conda install -c mila-udem/label/pre theano pygpu libgpuarray

This will install the last beta of Theano and the last release of pygpu/libgpuarray

**Comment by Arxa** [comment]
I also get the exact same error as @RaskaFR 

pygpu version: 0.7.2.dev1
Python version: Python 3.5.2 |Anaconda 4.2.0 (64-bit)| 

I executed your answer @nouiz and did the update but still getting this error.

**Comment by nouiz** [comment]
Do you have many Theano installed? I think this could be your problem. To fix that, remove Theano multiple time to be sure to remove all of them. Then reinstall it.

If that don't fix it, then put a breakpoint (import pdb;pdb.set_trace()) just before the line that generate the error and give me the value of the variable short_version.

**Comment by Arxa** [comment]
You were right. I had more than more than one Theano's installed. I did what you said and now the error is gone. Thank you very much.
