### ISSUE TITLE
version problem: Theano-0+unknown

### ISSUE THREAD

**Issue by ngkl** [Theano/Theano#6433]
I installed the bleeding edge version of Theano with command:
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip

The version is reported as Theano-0+unknown:
Successfully installed Theano-0+unknown

Then executing the command "import theano" I get:
(py35) C:\Users\ng>python -c "import theano"
Traceback (most recent call last):
File "", line 1, in 
File "D:\Users\ng\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\theano_init_.py", line 68, in 
from theano.version import version as version
File "D:\Users\ng\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\theano\version.py", line 14, in 
int(short_version.split('.')[2])
IndexError: list index out of range

--- I think the problem is caused from the +unknown in the version.

**Comment by ngkl** [comment]
I installed the bleeding edge version of Theano with command:
pip install --upgrade https://github.com/Theano/Theano/archive/master.zip

The version is reported as Theano-0+unknown:
Successfully installed Theano-0+unknown

Then executing the command "import theano" I get:
(py35) C:\Users\ng>python -c "import theano"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\ng\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\theano\__init__.py", line 68, in <module>
    from theano.version import version as __version__
  File "D:\Users\ng\AppData\Local\Continuum\Anaconda3\envs\py35\lib\site-packages\theano\version.py", line 14, in <module>
    int(short_version.split('.')[2])
IndexError: list index out of range

(py35) C:\Users\ng>git clone git://github.com/Theano/Theano.git
'git' is not recognized as an internal or external command,
operable program or batch file.

>>> I think the problem is caused from the +unknown in the version.

**Comment by ngkl** [comment]
I solved it by downloading and installing older version Theano-rel-0.10.0beta1.zip:
pip install --upgrade Theano-rel-0.10.0beta1.zip

**Comment by nouiz** [comment]
The beta3 that we are doing today (or Theano dev version) don't have that problem. So closing now as the fix will be made more easily available today.

**Comment by ngkl** [comment]
Thanks a lot!

**Comment by abergeron** [comment]
Just to note for future people googling this: `pip install --upgrade https://github.com/Theano/Theano/archive/master.zip` will have this problem if master is not on a tag.  To avoid this you can do `pip install --upgrade git+https://github.com/Theano/Theano.git#egg=Theano` as per the official installation instructions.
