### ISSUE TITLE
Explicit CPU transfer

### ISSUE THREAD

**Issue by botev** [Theano/Theano#6436]
Is there a way to force the explicit transfer of some variables to the CPU?
I'm specifically interested in this for scalar values for trying to implement something like a Quasi-Newton method. Generally, it requires for the "decision" logic only scalar values (directional derivatives), thus it might be better to have the logic executed on the CPU, while the heavy compute on the GPU and only transfer scalars between.

**Comment by nouiz** [comment]
We don't move scalar element on the GPU by default. Does the graph to compute that decision use other operation? If not, then you have nothing to do.

**Comment by botev** [comment]
So yes the graph to compute the "decision" scalar will use other.
For instance something like this:
```matlab
grad = T.grad(f, w)
gtd = T.sum(grad * d)
f_new, g_new, gtd_new = theano.clone([f, grad, gtd], replace={w: w_new})
 if f_new > f + c1*t*gtd || (LSiter > 1 && f_new >= f_prev)
        bracket = [t_prev t];
        bracketFval = [f_prev f_new];
        bracketGval = [g_prev g_new];
        break;
    elseif abs(gtd_new) <= -c2*gtd
        bracket = t;
        bracketFval = f_new;
        bracketGval = g_new;
        done = 1;
        break;
    elseif gtd_new >= 0
        bracket = [t_prev t];
        bracketFval = [f_prev f_new];
        bracketGval = [g_prev g_new];
        break;
    end
```
And this whole thing is in a loop where the checks happen every iteration until one of those gets hit. Note that for the decision-making we operate only with scalars, nothing else, but these scalars to appear in computations with some of the large arrays later.

**Comment by nouiz** [comment]
I don't get it. Is that decision inside a Theano graph or outside?

Do the loop you talk about is a scan or is it in a python for loop outside
a Theano function?

Is it unrolled inside a Theano function?

**Comment by botev** [comment]
It is in the graph. Basically, I've translated that Matlab code into Theano ifelse, so all the decisions are inside Theano. I explicitly do not want to go back to the python interpreter for this.

**Comment by nouiz** [comment]
WHere is the loop you talk about? In Python? Is it unrolled in the graph?
In Scan?

If you translate all that code to Theano, it would be mostly all elemwise +
ifelse and it should stay on CPU I think.

Can you just compile your Theano function and call:

theano.printing.debugprint(fct, print_type=True)

and you will see what is on the CPU vs GPU.

**Comment by nouiz** [comment]
no news, so closing.
