### ISSUE TITLE
[HELP]Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by wa1618i** [Theano/Theano#6449]
Did some research, and found some suggestion that need to do the following: 
conda update -c mila-udem/label/pre theano libgpuarray pygpu
But still the error persists:

Using Theano backend.
/home/lemma/miniconda2/lib/python2.7/site-packages/theano/configdefaults.py:17: TheanoConfigWarning: Config key 'cuda' has no value, ignoring it
  from theano.configparser import (AddConfigVar, BoolParam, ConfigParam, EnumStr,
Can not use cuDNN on context None: Disabled by dnn.enabled flag
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/lemma/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File "/home/lemma/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "/home/lemma/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 152, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm
GpuArrayException: ('nvrtcCompileProgram: NVRTC_ERROR_INVALID_OPTION', 3)

Inside my python script, i wrote: 
os.environ['KERAS_BACKEND']='theano'
os.environ['THEANO_FLAGS']='cuda'

Inside my theanorc, i wrote: 
[global]
device = cuda0
GPUARRAY_FORCE_CUDA_DRIVER_LOAD=1
floatX = float32
force_device=True
print_active_device = True
optimizer = fast_compile
[cuda]
root=/usr/local/cuda-8.0
[dnn]
include_path=/usr/local/cuda-8.0/include
library_path=/usr/local/cuda-8.0/lib64
enabled = False

**Comment by abergeron** [comment]
You also need `-c mila-udem` for pygpu and libgpuarray to install recent versions

**Comment by wa1618i** [comment]
Well i did that exactly in the first post. That's why i have no clue whatsoever

**Comment by gaebor** [comment]
The `os.environ['THEANO_FLAGS']='cuda'` is odd.
Have you tried `os.environ['THEANO_FLAGS']='device=cuda'`?
But it is unnecessary since you specified in the `.theanorc`.

**Comment by abergeron** [comment]
Which version of cuda and which model of GPU do you have.  The error looks like the cuda version you have doesn't support your GPU.  Note that cuda 9 dropped support for CC 2.x GPUS.

Also, GPUARRAY_FORCE_CUDA_DRIVER_LOAD in your .theanorc don't do anything.  It was supposed to be an environment variable, but got removed a while back.

**Comment by nouiz** [comment]
@abergeron,

Do you think it would save us and user time by making Theano detect if cuda
is >= 9 and if the CC 2.*, raise an error? It seem already the second time
in a few day users have this problem.

**Comment by wa1618i** [comment]
Thanks for replies. But it seems that the issue doesn't relate to Theano, and successfully resolved.
