### ISSUE TITLE
Self-contradictory documentation of required libgpuarray version

### ISSUE THREAD

**Issue by rebecca-palmer** [Theano/Theano#6454]
doc/install_generic.inc lists 0.6.5, 0.6.9 and 0.7.1 as the required libgpuarray version.

I don't know which is right (I can't use libgpuarray due to [an unrelated clBLAS issue](https://bugs.debian.org/877316)), but they can't all be.

doc/requirements.inc doesn't list a version requirement for libgpuarray at all.

**Comment by notoraptor** [comment]
Hello @rebecca-palmer .

For Theano `0.9.*`, the recommended libgpuarray version is `0.6.*` (currently `0.6.9`).

For Theano `0.10.*`, the recommended libgpuarray version is `0.7.*` (there are API changes from `0.6.*` to `0.7.*`).

Doc should be fixed in few days.

**Comment by nouiz** [comment]
The doc should be updated, so closing.
