### ISSUE TITLE
Intermittent error in TestCGemvNoFlags.test_cgemv

### ISSUE THREAD

**Issue by lamblin** [Theano/Theano#6464]
It looks like `theano.tensor.tests.test_blas_c.TestCGemvNoFlags.test_cgemv` fail in a non-deterministic way, see [here](https://travis-ci.org/Theano/Theano/jobs/283891616#L3503).

It looks like the output memory is not always zeroed out when `beta == 0`, so `nan` can result if there were non-finite elements in that memory, whereas the reference (and expected) result is `0`.

**Comment by notoraptor** [comment]
Ok. I will fix it today.
