### ISSUE TITLE
when import theano in python, get a error "list index out of range" 

### ISSUE THREAD

**Issue by ceo1207** [Theano/Theano#6465]
my python version is Python 2.7.12
when i setup the 10.0beta, get a error  "list index out of range" .
But when i choose 0.9.0 to setup, i can successfully import theano in Python

**Comment by nouiz** [comment]
This PR should fix that: https://github.com/Theano/Theano/pull/6472#pullrequestreview-68373276

Can you test that commit? It should be merged in master today.
