### ISSUE TITLE
(Could not initialize pygpu, support disabled)Theano GPU problems again.

### ISSUE THREAD

**Issue by Lan1991Xu** [Theano/Theano#6473]
Hi all
I have notice a few people meet the same problem. And some of them seems to solve it according the instruction
https://github.com/Theano/Theano/issues/6417. But I meet this again. 
My environment is Ubuntu 14.04 CUDA8.0. I have update the theano and  pygpu in the latest version.
I try this
**THEANO_FLAGS=device=cuda1 python gpu_tutorial1.py**
 get the problem: ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/root/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/root/anaconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 60, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu/gpuarray.pyx", line 634, in pygpu.gpuarray.init
  File "pygpu/gpuarray.pyx", line 584, in pygpu.gpuarray.pygpu_init
  File "pygpu/gpuarray.pyx", line 1057, in pygpu.gpuarray.GpuContext.__cinit__
GpuArrayException: cuDeviceGet: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal
I try this THEANO_FLAGS=device=gpu1
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 1 failed:
Bad device number 1. Only 1 devices available.

What reall confuse me is that if i set THEANO_FLAGS=device=cuda0, or gpu0 it works. I have 7 gpu,why only the first one is available? and when I even try my code for THEANO_FLAGS=device=cuda0    the Memory-Usage for nvidia-smi is almost 0. So could you give some suggestions about this.

**Comment by nouiz** [comment]
When you tell you updated to the latest, how did you do that? Update to the dev version(the version on github) or use the latest beta of Theano. 

You can get the latest beta on conda like this:

conda install -c mila-udem/label/pre theano

**Comment by Lan1991Xu** [comment]
0.10.0beta3-py27hbc93d2b_0 mila-udem/label/pre this is my theano version. The problem is when I use the gpu0, it seems work. But others like gpu 7, it will raise this problem

**Comment by lamblin** [comment]
It could be that the other GPUs are hidden from you. What's the value of `CUDA_VISIBLE_DEVICES`?

**Comment by Lan1991Xu** [comment]
Thanks. It seems when I use export CUDA_VISIBLE_DEVICES=5, and THEANO_FLAGS=device=cuda. It will sovle this problem. And use the gpu5. But when I use  THEANO_FLAGS=device=cuda5,it will lead this problem

**Comment by nouiz** [comment]
If CUDA_VISIBLE_DEVICES=5, there is only one device, so you need to do
device=cuda0.

If you have CUDA_VISIBLE_DEVICES=5,7

Then cuda0 mean gpu 5 and cuda1 mean gpu 1.

This is how nvidia driver work.
