### ISSUE TITLE
pygpu was configured but could not be imported or is too old

### ISSUE THREAD

**Issue by massimilianocomin** [Theano/Theano#6474]
Hi,

I installed theano, pygpu and libgpuarray on a cluster locally, through conda with the command `conda install -c mila-udem/label/pre theano pygpu libgpuarray`.
The versions I get from `conda list` are :

`libgpuarray               0.7.2.dev1           h3972f8e_0    mila-udem/label/pre`
`pygpu                     0.7.2.dev1       py35hcab9789_0    mila-udem/label/pre`
`theano                    0.10.0beta3      py35he84db1d_0    mila-udem/label/pre`

When I do `import theano` I get : 
`
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
`

And if I do `import pygpu` I have :
`
ImportError: /lib64/libc.so.6: version 'GLIBC_2.14' not found
`

I'm using python 3.5.3.

**Comment by nouiz** [comment]
@abergeron can you look?

What is the OS version?

**Comment by massimilianocomin** [comment]
@nouiz It's a GPU cluster on CentOS 6.9

**Comment by nouiz** [comment]
what is the output of:

    ls -l /lib64/libc.so

**Comment by massimilianocomin** [comment]
The output is :
`ls: cannot access /lib64/libc.so: No such file or directory`

**Comment by abergeron** [comment]
I'll see about changing the build container so that the next release is hopefully ok with old libc.

**Comment by nouiz** [comment]
Note, we should do this week a new release of the part that cause you
problem.

**Comment by massimilianocomin** [comment]
Ok I will wait the release then, thank you !

**Comment by abergeron** [comment]
You can try to install libgpuarray 0.7.4 with `conda install -c mila-udem pygpu` and that version should be ok with an older libc.

Can you confirm that it works?

**Comment by massimilianocomin** [comment]
After this installation I have no more errors when importing pygpu, but `import theano` gives :

`
File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init
File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
pygpu.gpuarray.GpuArrayException: b'Could not load "libnvrtc.so": libnvrtc.so: cannot open shared object file: No such file or directory'
`
when run from a compute node. In the login node it gives : 
`
pygpu.gpuarray.GpuArrayException: b'cuInit: CUDA_ERROR_UNKNOWN: unknown error'
`

instead

**Comment by abergeron** [comment]
The problem on the login node is most probably because it picks up the stubs from the dev kit which can't actually run things.

As for the other part, do you know which version of cuda is installed on the cluster?  Because cuda < 7.0 is not supported.

**Comment by massimilianocomin** [comment]
Sorry you were right : the default version of CUDA was 6.x. After loading CUDA 8.x theano works ! But when importing I still have an error message :
`Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:`
`b'/tmp/try_flags_yga3w010.c:4:19: fatal error: cudnn.h: No such file or directory\n #include <cudnn.h>\n                   ^\ncompilation terminated.\n'`
`Mapped name None to device cuda: Tesla K20m (0000:04:00.0)`

**Comment by abergeron** [comment]
You probably need to set dnn.root to the install location of the cudnn that you want to use.

**Comment by massimilianocomin** [comment]
How can I do this ?

**Comment by nouiz** [comment]
Check this doc on how to change Theano flag:

http://deeplearning.net/software/theano/library/config.html#libdoc-config

**Comment by massimilianocomin** [comment]
I checked the config.cuda.root flag and it points to the correct location i.e. the $CUDA_HOME environment variable. I still get the same error though !

**Comment by nouiz** [comment]
Look for the dnn.base_path (not cuda.root). They are separate config flag.

**Comment by massimilianocomin** [comment]
Ok the flag is indeed empty ! Where should it point to ? The same as cuda.root ?

**Comment by abergeron** [comment]
If you've install cudnn in your cuda.root there should be nothing to do.  However if it was installed elsewhere, then you will need to supply the path there.

**Comment by massimilianocomin** [comment]
Sorry but I don't understand.. 
I just installed theano/pygpu/libgpuarray through conda locally, and loaded the needed modules (cuda 8.x, and mkl libs) from the clusted libs. 

All I can say is that the cuda.root flag is OK and the dnn.base_path is empy !
Which path should I provide dnn.base_path ? 

(It doesn't work with the $CUDA_HOME path, still get the same error)

**Comment by lamblin** [comment]
cuDNN does not necessarily come with CUDA. You should check if the system install of cuda comes with cuDNN, if you need to load another module, or maybe you will have to download it somewhere.

**Comment by massimilianocomin** [comment]
Ok I found the path for cuDNN, it was indeed somewhere else. Now everything is finen ! Thank you all for the support !
