### ISSUE TITLE
Theano.scan only running on CPU on Theano 0.9.0

### ISSUE THREAD

**Issue by MehulAjax21** [Theano/Theano#6482]
Hello guys,

I noticed that scan function is running only on CPU even if rest of the theano ops are running on GPU.
Why is it so. Is there a new way to run scans on GPU?

**Comment by nouiz** [comment]
Scan run on GPU. What make you think otherwise? Depending of the output, it can be misleading. If you check the Theano profile and you see "py" and understand that it run on CPU, this isn't the case. It just mean some part of the code is in Python (in fact, it is cython). But this is just the control of the looping. The graph execution still continue to work on GPU.

**Comment by MehulAjax21** [comment]
![screenshot](https://user-images.githubusercontent.com/17104919/31618132-63189454-b291-11e7-96b7-ec04c1d22a5d.png)
I have attached the screenshot. The tensor type reads for{cpu,scan_fn}.0
Also the execution of the graph is taking a lot of time.
I am using the OpFromGraph function and scanning that function. I am not sure if that is slowing the things down.
How can I verify if the execution is actually on CPU or GPU?

**Comment by nouiz** [comment]
OpFromGraph don't work on the GPU yet. Or at least, it force the input and
output to be on the CPU. Can you use it with the flag inline=True? This way
it will work well with the GPU.

**Comment by MehulAjax21** [comment]
I Tried to restructure the code by creating a function and calling it in scan. The time was reduced to half of the time taken by base code which is good.

I also tried the inline=True in OpFromGraph which had exactly similar improvements.
I ran my base code again to confirm was the problem transient or not. The base code is still slower as expected.

The only unexpected thing is that in all the three codes, it lists the tensor as for{cpu,scan_fn}.0 (even with inline=true).
I am not sure if this is correct or not? Is the type of tensor ever reflected as gpu in any of your code?

**Comment by nouiz** [comment]
For scan, when on gpu, it should be "for{gpu..."

What Theano flags do you use? Which version of Theano do you use?

**Comment by MehulAjax21** [comment]
My theano version is 0.9.0.dev.
I am pasting the content of my theanorc file. This works great for other functions. I am sure all of them runs on the GPU. I am not sure whats wrong with scan.

===============================================================================
[global]
openmp = False
floatX=float32
device=gpu
mode = FAST_RUN

[dnn]
enabled=True
library_path = /usr/local/cudnn5_1/lib64
include_path = /usr/local/cudnn5_1/include

[cuda]
root=/usr/local/cuda

[nvcc]
fastmath = True

[lib]
cnmem = 0.8

**Comment by nouiz** [comment]
We don't have time to continue the support of the old GPU back-end. I would strongly suggest that you update to theano 0.10 beta4 (just merged, probably still not on pypi) or the github version. Also read this wiki page to know how to use the new gpu back-end:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)

**Comment by MehulAjax21** [comment]
I installed the 0.10 beta4 following the steps listed here (http://deeplearning.net/software/theano_versions/dev/install_ubuntu.html) and it is working well. I am using the libgpuarray backend now.

**The tensor from scan still says "for{cpu..."**

I am not sure what is incorrect. The output when importing theano:
"Using cuDNN version 5110 on context None
Preallocating 3235/4044 Mb (0.800000) on cuda0
Mapped name None to device cuda0: GeForce GTX 960M (0000:02:00.0)"

I think my environment settings are correct.

**Comment by nouiz** [comment]
Can give me the output of:
f=theano.function(...) # the function that should run on GPU, but seem to
not.

theano.printing.debugprint(f, print_type=True)

**Comment by MehulAjax21** [comment]
This is the output of theano.printing.debugprint(GAP, print_type=True)
===============================================================================
HostFromGpu(gpuarray) [id A] <TensorType(float32, 4D)> ''   14
 |for{cpu,scan_fn} [id B] <GpuArrayType<None>(float32, (False, False, False, False))> ''   13
   |Shape_i{0} [id C] <TensorType(int64, scalar)> ''   2
   | |<TensorType(float32, 4D)> [id D] <TensorType(float32, 4D)>
   |GpuSubtensor{int64:int64:int8} [id E] <GpuArrayType<None>(float32, (False, False, False, False))> ''   11
   | |GpuFromHost<None> [id F] <GpuArrayType<None>(float32, (False, False, False, False))> ''   3
   | | |<TensorType(float32, 4D)> [id D] <TensorType(float32, 4D)>
   | |ScalarFromTensor [id G] <int64> ''   9
   | | |Elemwise{Composite{Switch(LE(i0, i1), i1, i2)}} [id H] <TensorType(int64, scalar)> ''   7
   | |   |Shape_i{0} [id C] <TensorType(int64, scalar)> ''   2
   | |   |TensorConstant{0} [id I] <TensorType(int8, scalar)>
   | |   |TensorConstant{0} [id J] <TensorType(int64, scalar)>
   | |ScalarFromTensor [id K] <int64> ''   6
   | | |Shape_i{0} [id C] <TensorType(int64, scalar)> ''   2
   | |Constant{1} [id L] <int8>
   |Shape_i{0} [id C] <TensorType(int64, scalar)> ''   2
   |GpuFromHost<None> [id M] <GpuArrayType<None>(int64, ())> ''   5
   | |Shape_i{0} [id N] <TensorType(int64, scalar)> ''   0
   |   |<TensorType(float32, matrix)> [id O] <TensorType(float32, matrix)>
   |GpuSubtensor{int64:int64:int8} [id P] <GpuArrayType<None>(float32, (False, False))> ''   12
     |GpuFromHost<None> [id Q] <GpuArrayType<None>(float32, (False, False))> ''   1
     | |<TensorType(float32, matrix)> [id O] <TensorType(float32, matrix)>
     |ScalarFromTensor [id R] <int64> ''   10
     | |Elemwise{Composite{Switch(LE(i0, i1), i1, i2)}}[(0, 0)] [id S] <TensorType(int64, scalar)> ''   8
     |   |Shape_i{0} [id N] <TensorType(int64, scalar)> ''   0
     |   |TensorConstant{0} [id I] <TensorType(int8, scalar)>
     |   |TensorConstant{0} [id J] <TensorType(int64, scalar)>
     |ScalarFromTensor [id T] <int64> ''   4
     | |Shape_i{0} [id N] <TensorType(int64, scalar)> ''   0
     |Constant{1} [id L] <int8>

Inner graphs of the scan ops:

for{cpu,scan_fn} [id B] <GpuArrayType<None>(float32, (False, False, False, False))> ''   
 >for{cpu,scan_fn} [id U] <GpuArrayType<None>(float32, (False, False, False))> ''   
 > |HostFromGpu(gpuarray) [id V] <TensorType(int64, scalar)> ''   
 > | |<GpuArrayType<None>(int64, ())> [id W] <GpuArrayType<None>(int64, ())> -> [id M]
 > |GpuElemwise{mul,no_inplace} [id X] <GpuArrayType<None>(float32, (False, False, False))> ''   
 > | |InplaceGpuDimShuffle{0,1,x} [id Y] <GpuArrayType<None>(float32, (False, False, True))> ''   
 > | | |<GpuArrayType<None>(float32, (False, False))> [id Z] <GpuArrayType<None>(float32, (False, False))> -> [id P]
 > | |InplaceGpuDimShuffle{x,0,1} [id BA] <GpuArrayType<None>(float32, (True, False, False))> ''   
 > |   |GpuReshape{2} [id BB] <GpuArrayType<None>(float32, (False, False))> ''   
 > |     |<GpuArrayType<None>(float32, (False, False, False))> [id BC] <GpuArrayType<None>(float32, (False, False, False))> -> [id E]
 > |     |MakeVector{dtype='int64'} [id BD] <TensorType(int64, vector)> ''   
 > |       |Shape_i{0} [id BE] <TensorType(int64, scalar)> ''   
 > |       | |<GpuArrayType<None>(float32, (False, False, False))> [id BC] <GpuArrayType<None>(float32, (False, False, False))> -> [id E]
 > |       |TensorConstant{-1} [id BF] <TensorType(int64, scalar)>
 > |HostFromGpu(gpuarray) [id V] <TensorType(int64, scalar)> ''   
 > |GpuFromHost<None> [id BG] <GpuArrayType<None>(int64, (False,))> ''   
 >   |MakeVector{dtype='int64'} [id BH] <TensorType(int64, vector)> ''   
 >     |Shape_i{1} [id BI] <TensorType(int64, scalar)> ''   
 >     | |<GpuArrayType<None>(float32, (False, False, False))> [id BC] <GpuArrayType<None>(float32, (False, False, False))> -> [id E]
 >     |Shape_i{2} [id BJ] <TensorType(int64, scalar)> ''   
 >       |<GpuArrayType<None>(float32, (False, False, False))> [id BC] <GpuArrayType<None>(float32, (False, False, False))> -> [id E]

for{cpu,scan_fn} [id U] <GpuArrayType<None>(float32, (False, False, False))> ''   
 >GpuReshape{2} [id BK] <GpuArrayType<None>(float32, (False, False))> ''   
 > |GpuCAReduceCuda{add}{0} [id BL] <GpuArrayType<None>(float32, (False,))> ''   
 > | |<GpuArrayType<None>(float32, (False, False))> [id BM] <GpuArrayType<None>(float32, (False, False))> -> [id X]
 > |HostFromGpu(gpuarray) [id BN] <TensorType(int64, vector)> ''   
 >   |<GpuArrayType<None>(int64, (False,))> [id BO] <GpuArrayType<None>(int64, (False,))> -> [id BG]
===============================================================================

I made a debug scenario of my own to verify what is going on. I made a very trivial scalar addition to vector using a scan. 
The output tensor from scan reads for{cpu,...}, but when I run the script using nvprof to see whats going on on the GPU, **I see that the gpu is performing the actual add operation.**
So the only thing that confuses me is that scan tensor which is on CPU but the operations seem to place on GPU. Also you mentioned that type of the scan tensor should be for{gpu,...}. So that remains to be addressed. I can post my code and you can try to run it on your side to check, if you observe the same thing as i mentioned.
Here is my code:-
===============================================================================
import numpy as np

np.random.seed(1007)
from theano import function
import theano.tensor as T
from theano import scan

def fun_step(wtemp, feats):
    feat_temp = T.reshape(feats, (feats.shape[0], -1))
    g = wtemp * T.transpose(feat_temp)
    g = T.transpose(g)
    g = T.sum(g, axis=(0))
    return T.reshape(g, (feats.shape[1], feats.shape[2]))

def fun_loop(feats,w):
    op, _ = scan(fun_step, sequences=[w], non_sequences=[feats])
    return op

x = T.tensor4(dtype='float32')
w = T.matrix(dtype='float32')
x_mc = T.tensor4(dtype='float32')

op2, _ = scan(fun_loop, sequences=[x], non_sequences=[w])
GAP = function([x, w], op2)  # this is mc on full batch
op3 = T.sum(x_mc, axis=(2, 3))
GAP_out = function([x_mc], op3)

ft = np.arange(2 * 3 * 3 * 3).reshape(2, 3, 3, 3).astype('float32')
ft_1 = np.arange(1 * 3 * 3 * 3).reshape(3, 3, 3).astype('float32')
wt = np.array([[1, 1, 1], [2, 2, 2]]).astype('float32')
fin = GAP(ft, wt)
out = GAP_out(fin)
print(fin)
print(out)
===============================================================================

**Comment by nouiz** [comment]
I ran your code here with this command line:

    CUDA_LAUNCH_BLOCKING=1 THEANO_FLAGS=device=cuda,floatX=float32,profile=True,profiling.debugprint=True python gh-6482.py

while adding this at the end of your script:

    theano.printing.debugprint(GAP)
    theano.printing.debugprint(GAP_out)

and I have this output:

```
Using cuDNN version 7002 on context None
Mapped name None to device cuda: GeForce GTX 750 (0000:05:00.0)
[[[[  27.   30.   33.]
   [  36.   39.   42.]
   [  45.   48.   51.]]

  [[  54.   60.   66.]
   [  72.   78.   84.]
   [  90.   96.  102.]]]


 [[[ 108.  111.  114.]
   [ 117.  120.  123.]
   [ 126.  129.  132.]]

  [[ 216.  222.  228.]
   [ 234.  240.  246.]
   [ 252.  258.  264.]]]]
[[  351.   702.]
 [ 1080.  2160.]]
HostFromGpu(gpuarray) [id A] ''   14
 |for{gpu,scan_fn} [id B] ''   13
   |Shape_i{0} [id C] ''   2
   | |<TensorType(float32, 4D)> [id D]
   |GpuSubtensor{int64:int64:int8} [id E] ''   11
   | |GpuFromHost<None> [id F] ''   3
   | | |<TensorType(float32, 4D)> [id D]
   | |ScalarFromTensor [id G] ''   9
   | | |Elemwise{Composite{Switch(LE(i0, i1), i1, i2)}} [id H] ''   7
   | |   |Shape_i{0} [id C] ''   2
   | |   |TensorConstant{0} [id I]
   | |   |TensorConstant{0} [id J]
   | |ScalarFromTensor [id K] ''   6
   | | |Shape_i{0} [id C] ''   2
   | |Constant{1} [id L]
   |Shape_i{0} [id C] ''   2
   |GpuFromHost<None> [id M] ''   5
   | |Shape_i{0} [id N] ''   0
   |   |<TensorType(float32, matrix)> [id O]
   |GpuSubtensor{int64:int64:int8} [id P] ''   12
     |GpuFromHost<None> [id Q] ''   1
     | |<TensorType(float32, matrix)> [id O]
     |ScalarFromTensor [id R] ''   10
     | |Elemwise{Composite{Switch(LE(i0, i1), i1, i2)}}[(0, 0)] [id S] ''   8
     |   |Shape_i{0} [id N] ''   0
     |   |TensorConstant{0} [id I]
     |   |TensorConstant{0} [id J]
     |ScalarFromTensor [id T] ''   4
     | |Shape_i{0} [id N] ''   0
     |Constant{1} [id L]

Inner graphs of the scan ops:

for{gpu,scan_fn} [id B] ''   
 >for{gpu,scan_fn} [id U] ''   
 > |HostFromGpu(gpuarray) [id V] ''   
 > | |<GpuArrayType<None>(int64, scalar)> [id W] -> [id M]
 > |GpuElemwise{mul,no_inplace} [id X] ''   
 > | |InplaceGpuDimShuffle{0,1,x} [id Y] ''   
 > | | |<GpuArrayType<None>(float32, matrix)> [id Z] -> [id P]
 > | |InplaceGpuDimShuffle{x,0,1} [id BA] ''   
 > |   |GpuReshape{2} [id BB] ''   
 > |     |<GpuArrayType<None>(float32, 3D)> [id BC] -> [id E]
 > |     |MakeVector{dtype='int64'} [id BD] ''   
 > |       |Shape_i{0} [id BE] ''   
 > |       | |<GpuArrayType<None>(float32, 3D)> [id BC] -> [id E]
 > |       |TensorConstant{-1} [id BF]
 > |HostFromGpu(gpuarray) [id V] ''   
 > |GpuFromHost<None> [id BG] ''   
 >   |MakeVector{dtype='int64'} [id BH] ''   
 >     |Shape_i{1} [id BI] ''   
 >     | |<GpuArrayType<None>(float32, 3D)> [id BC] -> [id E]
 >     |Shape_i{2} [id BJ] ''   
 >       |<GpuArrayType<None>(float32, 3D)> [id BC] -> [id E]

for{gpu,scan_fn} [id U] ''   
 >GpuReshape{2} [id BK] ''   
 > |GpuDnnReduction{red_op='add', axis=(0,), acc_dtype='float32', dtype='float32', return_indices=False} [id BL] ''   
 > | |GpuContiguous [id BM] ''   
 > |   |<GpuArrayType<None>(float32, matrix)> [id BN] -> [id X]
 > |HostFromGpu(gpuarray) [id BO] ''   
 >   |<GpuArrayType<None>(int64, vector)> [id BP] -> [id BG]
HostFromGpu(gpuarray) [id A] ''   3
 |GpuDnnReduction{red_op='add', axis=(2, 3), acc_dtype='float32', dtype='float32', return_indices=False} [id B] ''   2
   |GpuContiguous [id C] ''   1
     |GpuFromHost<None> [id D] ''   0
       |<TensorType(float32, 4D)> [id E]

```

Can you give me your new Theano flag since the update? I don't think it is the problem, but as I'm not able to reproduce it, I'm not sure what I can do.

**Comment by MehulAjax21** [comment]
Thanks for checking my code. It very strange issue I think. Here are my flags from theanorc:-
[global]
openmp = False
floatX=float32
device=cuda0
mode = FAST_RUN

[dnn]
enabled=True
library_path = /usr/local/cudnn5_1/lib64
include_path = /usr/local/cudnn5_1/include

[gpuarray]
preallocate = 0.4


I also tried with CUDA_LAUNCH_BLOCKING=1 by setting it inside the code as Os environmental  variable. But as expected, this did nothing. There has to be something in my environement that is creating this issue. I will try to have a look on other systems as well and see what happens.

**Comment by MehulAjax21** [comment]
I have figured out the problem. Seems like running the code in a debugger or a python console make the scan compile on CPU. The last step that I did was during a debug session.
I ran the code like you did with he command line and got the correct result. This clears the confusion.
Thanks for your time in hunting this issue. I will now close this one
