### ISSUE TITLE
Slow convolutional neural network training on OpenCL

### ISSUE THREAD

**Issue by hy9be** [Theano/Theano#6484]
I am using a Keras script with Theano backend, to train a very simple CNN with my macbook pro 2016, which has an AMD GPU and has OpenCL support: [code](https://github.com/MorvanZhou/tutorials/blob/master/kerasTUT/6-CNN_example.py)

The entire training process took about 500 sec on CPU. When I switch to GPU via ``THEANO_FLAGS`` (Theano v0.10 beta1 + pygpu), it finishes with no errors. But it is about 20x slower (used 10500 sec).

I turned on the profiler and the top three function calls are 
```
AbstractConv2d_gradInputs
AbstractConv2d
AbstractConv2d_gradWeights
```
The sum of execution time of these three functions almost 99% of the total training time.

I do not think this performance is as expected, thus report it as a bug here. Thanks!

**Comment by nouiz** [comment]
For some reason, the GPU ops didn't moved to OpenCL.

We don't have time to finish making work the OpenCL back-end. Also, we
won't continue the development of Theano, so we won't finish that:
https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ

**Comment by hy9be** [comment]
Got it. Thanks for the work you guys did. Theano helped a lot of our work. Really appreciate it!

**Comment by EJShim** [comment]
How did you make it work using Mac Os + AMD GPU + OpenCL with theano?

I am trying and still getting errors when compiling with opencl.
I am using iMac Sierra, Radeon HD 6970M, theano 0.10.0beta4+42, with pygpu 0.7.4.

**Comment by hy9be** [comment]
What's the error?

**Comment by EJShim** [comment]
It was segmentation fault 11, It was a problem of somewhere in lasagne's global pooling layer. I resolved it now,, and figured out that OpenCL Backend is much slower than CPU.

**Comment by rltbennett** [comment]
How did you resolve it the segfault?
