### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by TurboFSIM** [Theano/Theano#6494]
> 
ValueError: The hardcoded shape for the number of columns in the image (3) isn't the run time shape (6).
Apply node that caused the error: ConvOp{('imshp', (1, 24, 3)),('kshp', (5, 1)),('nkern', 32),('bsize', 1),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (1, 24, 3)),('kshp_logical', (5, 1)),('kshp_logical_top_aligned', True)}(inputs, W)
Toposort index: 17
Inputs types: [TensorType(float64, 4D), TensorType(float64, 4D)]
Inputs shapes: [(1L, 1L, 24L, 6L), (32L, 1L, 5L, 1L)]
Inputs strides: [(1152L, 1152L, 48L, 8L), (40L, 40L, 8L, 8L)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 * (Abs((i1 + i2)) + i1 + i2))}}[(0, 1)](TensorConstant{(1L, 1L, 1..1L) of 0.5}, ConvOp{('imshp', (1, 24, 3)),('kshp', (5, 1)),('nkern', 32),('bsize', 1),('dx', 1),('dy', 1),('out_mode', 'valid'),('unroll_batch', None),('unroll_kern', None),('unroll_patch', True),('imshp_logical', (1, 24, 3)),('kshp_logical', (5, 1)),('kshp_logical_top_aligned', True)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

**Comment by nouiz** [comment]
When the graph was built, you told the convolution that the image input
will have 6 columns, but at run time, you it have only 3 columns. Remove
the shape or use the right shape when calling thee convolution.
