### ISSUE TITLE
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by meccaLeccaHi** [Theano/Theano#6499]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.2 
- **Theano installed from**: via conda
- **Theano version**: 0.9.0-py27_0
- **Python version**: 2.7
- **cuDNN version**: 6.0.21
- **CUDA compilation tools, release**: 8.0, V8.0.61
- **GPU model and memory**: GeForce GTX Titan X
- **Host compiler version**: GCC 4.9.3

### Problem
Fresh install of cuda/cudnn/theano as per [docs](http://deeplearning.net/software/theano/updating.html#updating). I get the following error message when I try importing theano. I know there are a multitude of posts for this error message, but none have been of any help. Any guidance would be *_greatly_* appreciated!

### Error message
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
In file included from /tmp/try_flags_IA_Yws.c:4:0:
/usr/local/cuda/include/cudnn.h:63:26: fatal error: driver_types.h: No such file or directory
 #include "driver_types.h"
                          ^
compilation terminated.

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 100, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm
GpuArrayException: ('cublasCreate: (cublas) Library not initialized.', 11)

### Exact steps to reproduce 
$ python -c "import theano"

### Relevant portion of .bashrc file
'export CUDA_ROOT=/usr/local/cuda

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64"

export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}

export CUDA_VISIBLE_DEVICES=0'

### Output of 'nvidia-smi'
'+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:01:00.0 Off |                  N/A |
| 22%   40C    P8    14W / 250W |      2MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GT 610      Off  | 00000000:07:00.0 N/A |                  N/A |
| 40%   35C    P8    N/A /  N/A |     48MiB /   963MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1                    Not Supported                                       |
+-----------------------------------------------------------------------------+'

**Comment by meccaLeccaHi** [comment]
#### In case anybody reads this- I've since upgraded my GPU, upgraded gcc to v5.4, reinstalled CUDA-8.0 (from with apt-get install), and modified my .bashrc file as per [this post](https://groups.google.com/forum/#!topic/theano-users/qD_HHtO3b-k). The relevant portion of the latest .bashrc file is shown here:

'export CUDA_ROOT=/usr/local/cuda
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64/"
export PATH="/usr/local/cuda/bin:$PATH"
export PATH="/usr/local/cuda-8.0/bin:$PATH"
export CUDA_VISIBLE_DEVICES=0
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/cuda/lib64
#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64"'

#### But I still get the following error. I would be eternally grateful for any insights.
'>>> import theano
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: libcublas.so.8.0: cannot open shared object file: No such file or directory
/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 68, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 85, in _make_handle
    raise RuntimeError("error creating cudnn handle")
RuntimeError: error creating cudnn handle
'

**Comment by nouiz** [comment]
Make sure to delete all the previously installed files and the previous
build directory. They can cause problem like this.

**Comment by meccaLeccaHi** [comment]
Thanks for the response, nouiz!
I made sure to run the following command after trying to install via run file:
`$ sudo /usr/local/cuda-X.Y/bin/uninstall_cuda_X.Y.pl`
and the following command after trying to install via deb:
`$ sudo apt-get --purge remove cuda`

I didn't remove cudnn, but I thought that would stay the same anyway.

Is there anything else I should have done? Happy to try any suggestions you might have.

**Comment by abergeron** [comment]
Run a `theano-cache purge` too.

Also you can try the 1.0rc release which has newer cudnn support and some fixes for header detection with this command:

`conda install -c mila-udem -c mila-udem/labels/pre theano pygpu`

**Comment by meccaLeccaHi** [comment]
Thanks, abergeron
Just to be clear- you mean to say that I should re-install theano again, but this time to include the command `theano-cache purge` to clear the theano cache before-hand and then install the 1.0rc release, correct? I'll give that a try.

**Comment by meccaLeccaHi** [comment]
**So, I get a similar error after running `theano-cache purge' with my current version of theano (see below).**  

`$ theano-cache purge
/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 164, in <module>
    use(config.device)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 151, in use
    init_dev(device)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 68, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 85, in _make_handle
    raise RuntimeError("error creating cudnn handle")
RuntimeError: error creating cudnn handle
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/adam/miniconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1492, in _on_atexit
    self.clear_old()
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1295, in clear_old
    cleanup=False)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 746, in refresh
    subdirs = sorted(os.listdir(self.dirname))
OSError: [Errno 2] No such file or directory: '/home/adam/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/adam/miniconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1492, in _on_atexit
    self.clear_old()
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1295, in clear_old
    cleanup=False)
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 746, in refresh
    subdirs = sorted(os.listdir(self.dirname))
OSError: [Errno 2] No such file or directory: '/home/adam/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64'
adam@adam-server:~$ ls .theano
.theano/   .theanorc `

**After upgrading to the newer theano using the command you provided, I get the following errors after trying to import theano.**
`>>> import theano
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/__init__.py", line 124, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/scan_module/scan_opt.py", line 60, in <module>
    from theano import tensor, scalar
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/tensor/__init__.py", line 17, in <module>
    from theano.tensor import blas
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/tensor/blas.py", line 155, in <module>
    from theano.tensor.blas_headers import blas_header_text
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/tensor/blas_headers.py", line 987, in <module>
    if not config.blas.ldflags:
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/configparser.py", line 332, in __get__
    val_str = self.default()
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/configdefaults.py", line 1407, in default_blas_ldflags
    check_mkl_openmp()
  File "/home/adam/miniconda2/lib/python2.7/site-packages/theano/configdefaults.py", line 1251, in check_mkl_openmp
    raise RuntimeError('To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.')
RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.`

**Comment by nouiz** [comment]
There is a conda bug in the way the stack is build and this can cause wrong
results. The work around is to do as in the end of the error message:

To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your
environement.

So this is a change to your shell, not Theano.

**Comment by meccaLeccaHi** [comment]
Thanks much for the feedback!
I added MKL_THREADING_LAYER to .bashrc and I now get the following error:
>>> import theano
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py",
line 220, in <module>
    use(config.device)
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py",
line 207, in use
    init_dev(device, preallocate=preallocate)
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py",
line 110, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/dnn.py",
line 124, in _make_handle
    "This can be a sign of a too old driver.", err)
RuntimeError: ('Error creating cudnn handle. This can be a sign of a too
old driver.', 4)

**Comment by abergeron** [comment]
If for some reason you are using the GT 610 card, I'm pretty sure it is not a supported card for cudnn (only sm 2.1).  So make sure to use the TITAN X card, which is supported.

If you want to avoid the cudnn error message you can temporarily set the theano flag `dnn.enabled=False` just to get the message about which GPU Theano is trying to initialize.

**Comment by meccaLeccaHi** [comment]
I've tried removing the GT 610, without any luck.
I've also got CUDA_VISIBLE_DEVICES set to "0" in the environment.

Where do I set dnn.enabled=False?
 Is that in .theanorc? If I set it there, I still get the same error from
my previous comment when trying to import theano.

**Comment by nouiz** [comment]
In theanorc add:
[dnn]
enabled=False

**Comment by meccaLeccaHi** [comment]
Thanks!

Add this:
`[dnn]
enabled=False`

got this:
`>>> import theano
Can not use cuDNN on context None: Disabled by dnn.enabled flag
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py",
line 220, in <module>
    use(config.device)
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py",
line 207, in use
    init_dev(device, preallocate=preallocate)
  File
"/home/adam/miniconda2/lib/python2.7/site-packages/theano/gpuarray/__init__.py",
line 152, in init_dev
    pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)
  File "pygpu/blas.pyx", line 149, in pygpu.blas.gemm
  File "pygpu/blas.pyx", line 47, in pygpu.blas.pygpu_blas_rgemm
GpuArrayException: ('cublasCreate: (cublas) Library not initialized.', 11)`

**Comment by abergeron** [comment]
It seems there is a problem with your driver install somewhere which prevents proper initialization.  I'm not sure what it is.

You can try to run the deviceQuery sample to isolate the problem to either the install or libgpuarray.

**Comment by pogilon** [comment]
I am having the same problem with "GpuArrayException: ('cublasCreate: (cublas) Library not initialized.', 11)`"

**Comment by meccaLeccaHi** [comment]
I've actually long since given up on this route and had much better luck
using docker containers. Doing so allows you to work with a perfectly
functional install (no warnings, just imagine it) which is robust to
ever-occurring updates in dependencies, etc. without having to understand
the nitty-gritty backend stuff which is apparently necessary to maintain a
local installation. I fully recommend it and wish I had done so from the
start.
e.g. https://github.com/windj007/docker-jupyter-keras-tools

**Comment by nouiz** [comment]
@pogilon did you fix your problem? Otherwise, this point to a problem with your environment. Can you try NVIDIA examples on cublas to make it work in your environment?

**Comment by imk1** [comment]
I am having this same problem.  Did anyone every figure out how to fix it?  Thanks!
