### ISSUE TITLE
Segmentation fault on theano.function in GPU mode with theno 0.9.0

### ISSUE THREAD

**Issue by RdlP** [Theano/Theano#6500]
I am trying this example with lasagne and theano: https://github.com/Lasagne/Lasagne/blob/master/examples/mnist.py

And it always get a `Segmentation fault (core dumped)`

the command that I use to run is `THEANO_FLAGS=device=cuda0 python mnist.py mlp 1`

I have tried with another example created by me and the result is the same `Segmentation fault (core dumped)`

In CPU mode it works fine.

**Comment by nouiz** [comment]
Be sure to use a more recent Theano. like the newly released 1.0.0 rc1. See
this doc to install it:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)

**Comment by sathickibrahims18** [comment]
I have used the latest theano version in my module still face 
**Fatal Python error: Segmentation fault**

In CPU mode its working fine.

Please help me to solve this issue

**Comment by sathickibrahims18** [comment]
Could you please any one reply for the above mentioned issue?

**Comment by nouiz** [comment]
Open a new issue with more details. It is probably something else and you do not provide enough information to help you.
