### ISSUE TITLE
GPUArrayException

### ISSUE THREAD

**Issue by ShivamSharma1997** [Theano/Theano#6504]
I am seeing this error on running a simple dense layer or CNN model using keras. 

```
GpuArrayException: ('The following error happened while compiling the node', GpuAdvancedIncSubtensor1_dev20{inplace=True, set_instead_of_inc=False}(GpuAlloc<None>{memset_0=True}.0, GpuReshape{2}.0, GpuReshape{1}.0), '\n', u'CUDA kernel compile failure ::\n0001\t#define local_barrier() __syncthreads()\n0002\t#define WITHIN_KERNEL extern "C" __device__\n0003\t#define KERNEL extern "C" __global__\n0004\t#define GLOBAL_MEM /* empty */\n0005\t#define LOCAL_MEM __shared__\n0006\t#define LOCAL_MEM_ARG /* empty */\n0007\t#ifdef NAN\n0008\t#undef NAN\n0009\t#endif\n0010\t#define NAN __int_as_float(0x7fffffff)\n0011\t#ifdef INFINITY\n0012\t#undef INFINITY\n0013\t#endif\n0014\t#define INFINITY __int_as_float(0x7f800000)\n0015\t#define LID_0 threadIdx.x\n0016\t#define LID_1 threadIdx.y\n0017\t#define LID_2 threadIdx.z\n0018\t#define LDIM_0 blockDim.x\n0019\t#define LDIM_1 blockDim.y\n0020\t#define LDIM_2 blockDim.z\n0021\t#define GID_0 blockIdx.x\n0022\t#define GID_1 blockIdx.y\n0023\t#define GID_2 blockIdx.z\n0024\t#define GDIM_0 gridDim.x\n0025\t#define GDIM_1 gridDim.y\n0026\t#define GDIM_2 gridDim.z\n0027\t#define ga_bool unsigned char\n0028\t#define ga_byte signed char\n0029\t#define ga_ubyte unsigned char\n0030\t#define ga_short short\n0031\t#define ga_ushort unsigned short\n0032\t#define ga_int int\n0033\t#define ga_uint unsigned int\n0034\t#define ga_long long long\n0035\t#define ga_ulong unsigned long long\n0036\t#define ga_float float\n0037\t#define ga_double double\n0038\t#define ga_half ga_ushort\n0039\t#define ga_size size_t\n0040\t#define ga_ssize ptrdiff_t\n0041\t#define load_half(p) __half2float(*(p))\n0042\t#define store_half(p, v) (*(p) = __float2half_rn(v))\n0043\t#define GA_DECL_SHARED_PARAM(type, name)\n0044\t#define GA_DECL_SHARED_BODY(type, name) extern __shared__ type name[];\n0045\t#define GA_WARP_SIZE warpSize\n0046\t#line 1\n0047\t\n0048\t/*\n0049\t * This is an atomicAdd that works for doubles since that is not provided\n0050\t * natively by cuda.\n0051\t */\n0052\t__device__ ga_double atomicAdd(ga_double* address, ga_double val) {\n0053\t    unsigned long long int* address_as_ull =\n0054\t                                          (unsigned long long int*)address;\n0055\t    unsigned long long int old = *address_as_ull, assumed;\n0056\t    do {\n0057\t        assumed = old;\n0058\t        old = atomicCAS(address_as_ull, assumed,\n0059\t                        __double_as_longlong(val +\n0060\t                        __longlong_as_double(assumed)));\n0061\t    } while (assumed != old);\n0062\t    return __longlong_as_double(old);\n0063\t}\n0064\t\n0065\t__device__ ga_double atomicExch(ga_double *address, ga_double val) {\n0066\t    return atomicExch((unsigned long long int *)address,\n0067\t                      __double_as_longlong(val));\n0068\t}\n0069\t\n0070\t/*\n0071\t * This is a version of atomicAdd that works for half-floats.  It may\n0072\t * read and write 2 bytes more than the size of the array if the array\n0073\t * has an uneven number of elements.  The actual value at that spot\n0074\t * will not be modified.\n0075\t */\n0076\t\n0077\t__device__ ga_half atomicAdd(ga_half *addr, ga_half val) {\n0078\t  ga_uint *base = (ga_uint *)((ga_size)addr & ~2);\n0079\t  ga_uint old, assumed, sum, new_;\n0080\t  old = *base;\n0081\t  do {\n0082\t    assumed = old;\n0083\t    sum = __float2half_rn(\n0084\t      __half2float(val) +\n0085\t      __half2float((ga_half)__byte_perm(old, 0,\n0086\t                     ((ga_size)addr & 2) ? 0x4432 : 0x4410)));\n0087\t    new_ = __byte_perm(old, sum, ((ga_size)addr & 2) ? 0x5410 : 0x3254);\n0088\t    old = atomicCAS(base, assumed, new_);\n0089\t  } while (assumed != old);\n0090\t  return (ga_half)__byte_perm(old, 0,\n0091\t                                  ((ga_size)addr & 2) ? 0x4432 : 0x4410);\n0092\t}\n0093\t\n0094\t__device__ ga_half atomicExch(ga_half *addr, ga_half val) {\n0095\t  ga_uint *base = (ga_uint *)((ga_size)addr & ~2);\n0096\t  ga_uint old, assumed, new_;\n0097\t  old = *base;\n0098\t  do {\n0099\t    assumed = old;\n0100\t    new_ = __byte_perm(old, val, ((ga_size)addr & 2) ? 0x5410 : 0x3254);\n0101\t    old = atomicCAS(base, assumed, new_);\n0102\t  } while (assumed != old);\n0103\t  return (ga_half)__byte_perm(old, 0,\n0104\t                                  ((ga_size)addr & 2) ? 0x4432 : 0x4410);\n0105\t}\n0106\t\n0107\t        KERNEL void k_vector_add_fast(const ga_size numRowsX,\n0108\t                                      const ga_size numColsX,\n0109\t                                      const ga_ssize stridesX0,\n0110\t                                      const ga_ssize stridesX1,\n0111\t                                      ga_float *X,\n0112\t                                      const ga_size offset_X,\n0113\t                                      const ga_size numRowsY,\n0114\t                                      const ga_size numColsY,\n0115\t                                      const ga_ssize stridesY0,\n0116\t                                      const ga_ssize stridesY1,\n0117\t                                      ga_float *Y,\n0118\t                                      const ga_size offset_Y,\n0119\t                                      const ga_size numIndices,\n0120\t                                      const ga_ssize stridesIndices,\n0121\t                                      ga_int *indices_arr,\n0122\t                                      const ga_size offset_indices_arr,\n0123\t                                      const int set_instead_of_inc,\n0124\t                                      ga_int *err)\n0125\t        {\n0126\t             X = (ga_float *)(((char *)X)+offset_X);\n0127\t             Y = (ga_float *)(((char *)Y)+offset_Y);\n0128\t             indices_arr = (ga_int *)(((char *)indices_arr)+offset_indices_arr);\n0129\t             for (int i = (blockIdx.x); i < numIndices; i += gridDim.x)\n0130\t             {\n0131\t                  for(int j = (threadIdx.x); j < numColsX;j += blockDim.x)\n0132\t                  {\n0133\t                      ga_ssize x_row = indices_arr[i * stridesIndices];\n0134\t                      if (x_row < 0)\n0135\t                          x_row += numRowsX;\n0136\t                      ga_ssize y_row = i;\n0137\t                      if (x_row < numRowsX && x_row >= 0) {\n0138\t                        if (set_instead_of_inc) {\n0139\t                          atomicExch(&X[(x_row * stridesX0) + (j * stridesX1)],\n0140\t                                   Y[(y_row * stridesY0) + (j * stridesY1)]);\n0141\t                        } else {\n0142\t                          atomicAdd(&X[(x_row * stridesX0) + (j * stridesX1)],\n0143\t                                    Y[(y_row * stridesY0) + (j * stridesY1)]);\n0144\t                        }\n0145\t                      } else {\n0146\t                        *err = 1;\n0147\t                      }\n0148\t                  }\n0149\t             }\n0150\t             return;\n0151\t        }\n0152\t        \n\nCompile log:\nNVRTC compile log::\ndefault_program(38): error: identifier "__half2float" is undefined\n\ndefault_program(37): error: identifier "__float2half_rn" is undefined\n\n2 errors detected in the compilation of "default_program".\n\n')
```

**Comment by nouiz** [comment]
How did you install Theano? Follow those instruction to install 1.0rc1. We don't support older version:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)

**Comment by ShivamSharma1997** [comment]
Can you please share the .theanorc . I have reinstalled theano and pygpu as recommended in the link. Should I uninstall the Visual C++ and mingw also?

**Comment by nouiz** [comment]
You should keep the mingw from conda, but remove other one. Visual C++ won't be used, but I think it don't hurt to keep it.

If that don't work, give the new error. Small change in the error can be hidden, so even if you think it didn't change, copy/paste it again.

**Comment by ShivamSharma1997** [comment]
Thanks. 
Can you please share the theanorc also?

**Comment by ShivamSharma1997** [comment]
Hey,
the new error was:

AssertionError: There is a negative shape in the graph! 
Backtrace when that variable is created:

  File "C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)
  File "C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\spyder\utils\site\sitecustomize.py", line 86, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "E:/Neural Network/CQA/WikiQACorpus/Python_Files/code.py", line 83, in <module>
    model = model1(X_train_l, X_train_r, label_train, embedding_matrix)
  File "models.py", line 37, in model1
    subsample_length=1)(y)
  File "C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\keras\engine\topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\keras\layers\convolutional.py", line 156, in call
    dilation_rate=self.dilation_rate[0])
  File "C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\keras\backend\theano_backend.py", line 1866, in conv1d
    data_format=data_format, dilation_rate=dilation_rate)
  File "C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\keras\backend\theano_backend.py", line 1912, in conv2d
    filter_dilation=dilation_rate)

**Comment by ShivamSharma1997** [comment]
I looked into it and found a coding error, sorry!!
Now my kernel keeps dying while as soon as I fit the model.
The code is correct, it is working on my other system but not on this one. 
Please help!

**Comment by notoraptor** [comment]
Hi. Which error do you have now ? Is it still the "GpuArrayException" error ?

Also, which `mingw` do you use ? The recommended compiler is the one provided by conda package `m2w64-toolchain`, see here: http://deeplearning.net/software/theano_versions/dev/install_windows.html#requirements-installation-through-conda-recommended

**Comment by ShivamSharma1997** [comment]
The error I have now is that the kernel keeps dying.
Other than that, its nothing.
mingw = 4.7

**Comment by notoraptor** [comment]
Could you clear theano cache (with command `theano-cache purge`) and then retry ?

On my computer, g++ version (provided by conda package `m2w64-toolchain`) is `5.3.0`. If you still have problems after clearing theano cache, consider replace your `mingw` distribution with the one recommended in installation page ( http://deeplearning.net/software/theano_versions/dev/install_windows.html#requirements-installation-through-conda-recommended ) and then retry again.

**Comment by ShivamSharma1997** [comment]
I cleared the cache as you said, and also have 5.3.0, but still the kernel keeps dying.

The following was shown on purging theano:

C:\Users\Shivam\Anaconda2\envs\tensor\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

**Comment by notoraptor** [comment]
These warnings are expected.

Ok, it's a quite strange error ...

You said the code works on another system, so what are the differences between your current system and the one where it works ? (OS, cuda version, cudnn version, python version, etc.)

Do you use a `.theanorc` file, `THEANO_FLAGS`, or any particular environment variable ?

**Comment by ShivamSharma1997** [comment]
OS, python version are same

The system on which the code is running just fine:
CUDA - 8.0

theanorc is:

[global]
floatX = float32
device = cude0
optimizer = fast_run

[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin

[nvcc]
flags=-LC:\Users\gaurav\Anaconda2\libs
fastmath=True
compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

As for the system on which the kernel keeps dying:

CUDA - 12.0

theanorc is:

[global]
floatX = float32
device = cuda0
mode=FAST_RUN

[cuda]
%root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA


[nvcc]
%flags = -LC:\Users\Shivam\Anaconda2\libs
%compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin
%fastmath = True

[blas]

**Comment by notoraptor** [comment]
As far as I known, there is no "CUDA 12", the latest available version should be "CUDA 9". What is the content of your environment variable `CUDA_PATH` ?

**Comment by ShivamSharma1997** [comment]
Yeah, my error CUDA version is 9.0
Sorry!

**Comment by notoraptor** [comment]
Ok. Unfortunately, I can't see why you have such problems.

As a last check, maybe could you try to install and use CUDA 8 on your erroneous system, to check if the problem comes from CUDA 9.

**Comment by MAbdullah47** [comment]
Please, When I import theano I got the following warning: 
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

**Comment by notoraptor** [comment]
Are you on Windows ? If so, make sure you have insalled conda packages `mkl` and `mkl-service`.

**Comment by MAbdullah47** [comment]
Yes Windows , Mk Installed as the following:

mkl                       2018.0.1             h2108138_4
mkl-service               1.1.2            py35h051acba_4


My Machine Properties are :
Python 3.5.4 :: Anaconda custom (64-bit)
conda 4.3.31
I check Theano pip list and I found: slight_smile:
tensorflow (1.2.0)
tensorflow-gpu (1.4.0)
tensorflow-tensorboard (0.4.0rc3)
Theano (1.0.1)
And when I do , conda list I found :slight_smile:
theano 0.9.0 py35h4ea80a6_3

So Based on your information I think it is not correct

**Comment by MAbdullah47** [comment]
I think this is not the problem , Mlk already installed

**Comment by notoraptor** [comment]
You have 2 installations of theano: 0.9.0 and 1.0.1, That's unexpected, maybe do you have 2 installations of Python on your computer ?

If so, make sure you use only one installation. Conda installation is the one recommended. I suggest you uninstall the second installation.

Can you post the output of following commands ?
```
where pip
where conda
```

**Comment by MAbdullah47** [comment]
Thank you for your support , I got the following: 
(C:\Users\Mohammad Mubarah\Anaconda3) C:\Users\Mohammad Mubarah>where pip
C:\Users\Mohammad Mubarah\Anaconda3\Scripts\pip.exe

(C:\Users\Mohammad Mubarah\Anaconda3) C:\Users\Mohammad Mubarah>where conda
C:\Users\Mohammad Mubarah\Anaconda3\Scripts\conda.exe

**Comment by notoraptor** [comment]
Ok. It is quite strange.

I think it's better to first clean the installation to have only 1 theano installation, then check if there are still problems.

Could you uninstall theano with both pip and conda, and then install theano from conda channel `mila-udem` ?
```batch
REM NB: Repeat `pip uninstall theano` many times until there is no more theano packages detected by pip.
pip uninstall theano

conda remove theano

conda install -c mila-udem theano
```

**Comment by MAbdullah47** [comment]
Thank You so much for your help , I'll do then get back to you with the results

**Comment by MAbdullah47** [comment]
Ok Now I checked the pip and conda list and I found them the same version:
Conda list
theano                    1.0.1                    py35_0    mila-udem

pip list
Theano (1.0.1)

But still when I import theano, I got the same message:
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

**Comment by MAbdullah47** [comment]
Please advise

**Comment by notoraptor** [comment]
Ok, so it's a hard problem, and you're not the first to have it. I can't currently figure out why theano can not use MKL. Maybe some further investigations will be required.

Anyway, it is a warning, not an error, so Theano should still work without any problem, it will be just not as fast as it can be on CPU, but it should work well on GPU.

**Comment by MAbdullah47** [comment]
So You think we can go smoothly without problem with Keras even with the present of Theano Warning?

**Comment by notoraptor** [comment]
Yes, everything should work.

**Comment by MAbdullah47** [comment]
Thank you so much, if there is some problems related to Kares I'll get back to this thread
