### ISSUE TITLE
configuring systems GPU for Theano crashes

### ISSUE THREAD

**Issue by pranitapradhan91** [Theano/Theano#6507]
Hello,

I am very new to theano and working on gpu. 
However, I have managed to follow the instructions given here [https://lepisma.github.io/2015/07/30/up-with-theano-and-cuda/](url). Attached is my theanorc file [.theanorc.txt](https://github.com/Theano/Theano/files/1449201/default.theanorc.txt). 
When I 'import theano' it crashes and I get something like this. (see the picture attached)
![capture](https://user-images.githubusercontent.com/25509717/32483951-67ede876-c39e-11e7-9982-f601fed4a512.PNG)

My versions:
Theano 1.0.0rc1
pygpu 0.6.9
Not able to install pycuda (raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.lfd.uci.edu', port=443): Max retries exceeded with url: /~gohlke/pythonlibs/ (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))

I am working on windows 10.

Your help is appreciated.

Regards
Pranita

**Comment by notoraptor** [comment]
Hi. First of all, there are more up-to-date installations instructions on Theano website : http://deeplearning.net/software/theano_versions/dev/install_windows.html

(you should not need to install neither pycuda nor Visual Studio with the latest theano version)

Also, 2 other remarks:
 - To get a compiler, the recommended conda package is `m2w64-toolchain` instead of `mingw`
 - pygpu `0.6.9` is too old and should not work with theano `1.0.0rc1`. The latest pygpu version is `0.7.4` and can be installed via conda channel `mila-udem` with following command:
```
conda install -c mila-udem pygpu
```

Could you retry to install with updated instructions and then check if you still have problems ?

**Comment by pranitapradhan91** [comment]
Thank you for your quick help. 

Below I have explained the ways I tried from the link you sent and also your suggestions.

1. First thing tried (without pygpu)
PACKAGES                      VERSION
python                            2.7.14
numpy                            1.12.0
scipy                               1.0.0
m2w64-toolchain           5.3.0
mkl-service                     1.1.2
Theano                           1.0.0rc1

import theano
error--- no module numpy
--------------------------------------------------------
2. Second thing (without pygpu and updated numpy)
PACKAGES                      VERSION
python                            2.7.14
numpy                            1.13.0
scipy                               1.0.0
m2w64-toolchain           5.3.0
mkl-service                    1.1.2
Theano                          1.0.0rc1

import theano
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
But does not work with gpu yet.
------------------------------------------------------------
3. Third thing (installed pygpu 0.7.4, this updated numpy to 1.13.3)
PACKAGES                      VERSION
python                            2.7.14
numpy                            1.13.3
scipy                               1.0.0
m2w64-toolchain           5.3.0
mkl-service                    1.1.2
Theano                          1.0.0rc1

import theano
RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.

How can I do this?
------------------------------------------------------------
Fourth thing (installed Theano==0.9.0 with conda)
PACKAGES                      VERSION
python                            2.7.14
numpy                            1.13.3
scipy                               1.0.0
m2w64-toolchain           5.3.0
mkl-service                     1.1.2
Theano                            0.9.0

import theano
works without error, however does not use gpu. And when I run theano.test() I get following errors (.txt file attached).
[errors.txt](https://github.com/Theano/Theano/files/1450492/errors.txt)

*Everything was done in a virtual environment and .theanorc.txt file was same as in my earlier comment and was kept in home directory.

Is there anything I am still failing to do? 
Waiting for suggestions. Thank you in advance.

Best,
Pranita

**Comment by notoraptor** [comment]
You should go with the third thing:

>     Third thing (installed pygpu 0.7.4, this updated numpy to 1.13.3)
>     PACKAGES VERSION
>     python 2.7.14
>     numpy 1.13.3
>     scipy 1.0.0
>     m2w64-toolchain 5.3.0
>     mkl-service 1.1.2
>     Theano 1.0.0rc1

About the error:

> import theano
> RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.

It is related to a bug recently found with latest versions of `mkl` package. You just need to set the environment variable as suggested by the error message. On a command line:
```
set MKL_THREADING_LAYER=GNU
```
Or via Windows Control Panel (set system environment variables), create a system variable named `MKL_THREADING_LAYER` with value `GNU`.

Also, to run `theano.tests()`, you may need to install package `parameterized` via pip:
```
pip install parameterized
```

**Comment by notoraptor** [comment]
NB: From your theanorc:
```
[global]
floatX = float32
device = cuda
mode=FAST_RUN

[cuda]
root = C:\Program Files\NVIDIA Corporation\Installer2\CUDAToolkit_9.0.{AE85B8EA-C063-4E5E-B333-151BFFB28009} 


[nvcc]
flags = -LC:\Users\si62qit\AppData\Local\Continuum\Anaconda2\libs
compiler_bindir = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
fastmath = True
```

If CUDA is correctly installed, you should not need `[cuda]` and `[nvcc]` sections. Consider having just this code into your theanorc:
```
[global]
floatX = float32
device = cuda
```

**Comment by pranitapradhan91** [comment]
Thank you.
This worked. But now I face another problem which is similar to the issue 
[https://github.com/Theano/Theano/issues/5768](url)

![image](https://user-images.githubusercontent.com/25509717/32507138-f696d608-c3e6-11e7-87b2-00f74e052992.png)


Therefore I changed my .theanorc file
[.theanorc.txt](https://github.com/Theano/Theano/files/1450912/default.theanorc.txt)

Any suggestions? Waiting for reply.

Regards
Pranita

**Comment by notoraptor** [comment]
Have you already downloaded and installed cuDNN in any directory ? If not, it seems you need it.

If so, you may need to tell Theano where to find cuDNN libraries and headers, with config variable `dnn.base_path`. In theanorc, add these lines:
```
[dnn]
base_path=C:\Users\notoraptor\data\libraries\cudnn-8.0-windows10-x64-v7.0.3\cuda
```
(replace value of `base_path` with path to folder when you have installed cuDNN).

**Comment by pranitapradhan91** [comment]
Thank you for the reply. 
I installed cuDNN. So basically here is what I did.
1. cudnn64_7.dll file is kept in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin
2. cudnn.h is kept in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include
3. cudnn.lib is kept in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\lib\x64

Is this correct? Also .theanorc file remained same. As I included cuDNN in the toolkit folder as shown above.
[.theanorc.txt](https://github.com/Theano/Theano/files/1453525/default.theanorc.txt)

And now it runs.
![image](https://user-images.githubusercontent.com/25509717/32545336-a87febae-c47b-11e7-9ea7-ec8f913e2df8.png)


Thank you very much for your help.

**Comment by notoraptor** [comment]
Yes, it should be correct, now. But your cuda root seems quite strange in your theanorc (`C:\Program Files\NVIDIA Corporation\Installer2\CUDAToolkit_9.0.{AE85B8EA-C063-4E5E-B333-151BFFB28009} `).

If you encounter some problems in the future, consider simplifying the theanorc file as I suggested above.

**Comment by wqp89324** [comment]
@notoraptor 
In a virtual environment created by conda, I have almost exact versions of these libraries as in the previous post:
```
python 2.7.14
numpy 1.13.3
scipy 1.0.0
m2w64-toolchain 5.3.0
mkl-service 1.1.2
Theano 1.0.1
pygpu 0.7.5
```
However I still have the warning message: Using NumPy C-API based implementation for BLAS functions. 
At this stage, I did not use a theanorc file yet. I'm on Windows. 

Any idea how to fix my issue?
Thanks!
