### ISSUE TITLE
Split the file tensor/basic.py

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#651]
Thi s is some discussion about this:

1) I don't know if move all ops in there own file is good. But we could use category file? But we can split it like the cuda code to help in that direction.

Move the TensorType stuff into the file tensor/type.py (500+ lines)
Move all the tensor variables and definition moved into tensor/var (~700 lines)

Also, what about moving all reduction op/function into tensor/reduction.py? Some of them are in basic.py and other in elemwise.py.

What do you think of those category? Others? Should sort be a category? Also, don't put pep8 in the same branch as the refactoring. It will make more conflict.

2)+1 on a file per category

I like the categories your proposed:

    type.py
    variables.py
    reduction.py
    elemwise.py
    etc.

3) careful about categories -> the TensorVariable methods depend on a lot of library functions

**Comment by lamblin** [comment]
Fixed.
