### ISSUE TITLE
GpuTopKOp accesses context.maxlsize, but pygpu provides maxlsize{0,1,2}

### ISSUE THREAD

**Issue by f0k** [Theano/Theano#6511]
First, congratulations on releasing 1.0!

When I try the following using the bleeding-edge Theano and libgpuarray versions, I run into an error:
```python
import theano
x = theano.tensor.matrix()
y = theano.tensor.topk(x, 10, sorted=False)
theano.function([x], y)
```

I get the following exception:
```
/raid/user/jan/install/Theano-git/theano/gpuarray/sort.pyc in c_code(self, node, nodename, inps, outs, sub)
    160         k_dtype = node.inputs[1].type.dtype_specs()[1]
    161         # max threads per block
--> 162         MAX_TPB = context.maxlsize
    163         # max blocks per grid
    164         MAX_BPG = context.maxgsize0

AttributeError: ('The following error happened while compiling the node', GpuTopKOp{axis=-1, sorted=True, return_values=True, return_indices=False, idx_dtype='int64'}(GpuFromHost<None>.0, TensorConstant{10}), '\n', "'pygpu.gpuarray.GpuContext' object has no attribute 'maxlsize'")
```

Looking at the code, Python seems to be right: `GpuTopKOp` tries to access `context.maxlsize`: https://github.com/Theano/Theano/blob/master/theano/gpuarray/sort.py#L162
But libgpuarray only defines `maxlsize0`, `maxlsize1`, `maxlsize2`: https://github.com/Theano/libgpuarray/blob/master/pygpu/gpuarray.pyx#L1133

Should GpuTopKOp access `context.maxlsize0` instead?

**Comment by f0k** [comment]
Okay, I see there are further problems, it doesn't seem to be an easy fix (there's a simple mistake in line https://github.com/Theano/Theano/blob/master/theano/gpuarray/sort.py#L189, but then it still doesn't compile). A suitable workaround for me is to set `THEANO_FLAGS=optimizer_excluding=local_gpua_topkop`, the overhead is not too critical in my case.

**Comment by nouiz** [comment]
I found more problem when making the tests. It seem some of the code just didn't work (missing variables and such). I'll continue slowly in the next few days.

**Comment by khaotik** [comment]
The tests I wrote a while ago are still inside `Theano/theano/tensor/test_sort.py`. I'm guessing jenkins didn't run it from the main GPU test. That explains why a lot bugs slipped through recent changes.

**Comment by nouiz** [comment]
I didn't found those tests. They use the mode "None". Normally the tests
are run with device=cpu, so we need to pass a special mode to have them run
on the GPU. This would explain the problem.

I pushed what I had as fix there: https://github.com/Theano/Theano/pull/6513

I don't have time to work on this today or tomorrow. Do you have time to
work on this? Next week we will make a release, so if we can't fix it by
then, we will just disable it on the GPU.

The problem I have now is that it use variable that just don't exist. Like
if the code never worked. There is also some problem that I update
variables that should not be updated as it don't exist (as it depend on the
number of output).

**Comment by nouiz** [comment]
Small update. I'm working on it. The original code probably work, it is me show missunderstood part of it. I think I'll be able to make it work if I have enough time left and no other problem pops up.

**Comment by nouiz** [comment]
@f0k can you try the updated PR gh-6513 ? Does it work for you at your size or you have a combination of size/gpu that generate errors?

**Comment by f0k** [comment]
> Does it work for you at your size

Seems to work, yes! At least it compiles and trains without my `THEANO_FLAGS=optimizer_excluding=local_gpua_topkop` workaround. (I haven't checked whether it uses the GPU Op nor whether the results are correct.)

**Comment by f0k** [comment]
> (I haven't checked whether it uses the GPU Op nor whether the results are correct.)

Update: Yes, it uses the GpuTopKOp, and in a simple test script, results look good as well. Good job!

**Comment by nouiz** [comment]
As all seem to be working, I'll close. Thanks
