### ISSUE TITLE
RuntimeError: ('Error creating cudnn handle. This can be a sign of a too old driver.', 4)

### ISSUE THREAD

**Issue by pogilon** [Theano/Theano#6515]
Theano version: 1.0.0
pygpu:  0.7.5
Nvidia GTX 1080
Cuda 8.0
Nvidia Driver version 384.98

Hello I have been trying to install theano the whole day! What could be the problem? Please see below the error after trying "import theano" I get :

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "XXXXX/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File ""XXXXX/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File ""XXXXX/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 110, in init_dev
    context.cudnn_handle = dnn._make_handle(context)
  File ""XXXXX/lib/python2.7/site-packages/theano/gpuarray/dnn.py", line 130, in _make_handle
    "This can be a sign of a too old driver.", err)
**RuntimeError: ('Error creating cudnn handle. This can be a sign of a too old driver.', 4)**

**Comment by notoraptor** [comment]
Hi. Have you configured a `.theanorc` file ? If so, can you post its content ? Or do you use the environment variable `THEANO_FLAGS` ? If so, can you post its content ?

Otherwise, consider either updating your driver or disable cudnn with theano flag `dnn.enabled=False`.

**Comment by Jay-Jia** [comment]
I have the same problem.
Theano version: 1.0.1
pygpu: 0.7.5
Nvidia TITAN X
Cuda 8.0
Cudnn 7.0.5
Nvidia Driver version 384.90

.theanorc file
[global]
floatX=float32
device=cuda0
optimizer_excluding=scanOp_pushout_output

[gpuarray]
preallocate=1
[cuda]
root=/usr/local/cuda-8.0

[nvcc]
fastmath = True
[dnn]
enabeld=True
inlude_path=/usr/local/cuda-8.0/include
library_path=/usr/local/cuda-8.0/lib64

**Comment by nouiz** [comment]
Can you update your driver and cuda to 9.0? I'll close now as you probably fixed this or stoped investigating, but if you still want to work on this, tell me and I'll re-open.
