### ISSUE TITLE
ImportError: cannot import name 'configparser'

### ISSUE THREAD

**Issue by Mr-Phoebe** [Theano/Theano#6521]
When I try to import theano in WINDOWS 10 with CUDA 8/VS 2015/Anaconda3/Python 3.6

I get 
```
ImportError: cannot import name 'configparser'
```
or 
```
AttributeError: module 'configparser' has no attribute 'ConfigParser'
```

And I can't use pip to uninstall it because the second error.

**Comment by nouiz** [comment]
This isn't normal. You probably have an old Theano and probably have many Theano installed. Try to uninstall it like this many times to be sure to remove all copy:

    conda uninstall theano
    pip uninstall theano

**Comment by 491506870** [comment]
@Mr-Phoebe hi~ have you solved this problem? i met the same problem with you , and i don't know how to do......

**Comment by young-qu** [comment]
Well,i met too,and i wonder why.
