### ISSUE TITLE
Docker images for theano

### ISSUE THREAD

**Issue by vaibhavsood** [Theano/Theano#6523]
Hi, 

Want to check if a multi-arch (non-x86) version of theano's docker image is available somewhere? I could not find any via a google search

If not, are there any plans to publish docker images for non-intel arches? Docker's official image program has support for building multi-arch containers  https://github.com/docker-library/official-images#multiple-architectures, however the requirement for this is for the x86 image to be a official image https://docs.docker.com/docker-hub/official_repos/ , can theano be considered to be made an official image and subsequently enable it to be mult-arch? thanks!

**Comment by nouiz** [comment]
There is this repo that have Theano docker image for x86.

https://github.com/nouiz/Theano-Docker/pull/4

As we are dropping development of Theano[1], I don't like the idea of spending time to make official docker repository. This would ask us more maintenance. If we can have a simple step by step instruction and it is quick to set up, why not. But we won't investigate it ourself.

[1] https://groups.google.com/d/msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ

Note I think IBM is providing Theano container on there hardware.
