### ISSUE TITLE
How does  #section cleanup_code_struct  gets called in Theano ? 

### ISSUE THREAD

**Issue by aditbhrgv** [Theano/Theano#6526]
Hello, 

I created a OP in Theano and inserted #section init_code_struct and wrote some input descriptor for Convolution  to be initialised once per layer. This init section code  is getting called once per layer as per expectation.  
But I also included  # section cleanup_code_struct and destroyed input descriptor using  below code: 
#section cleanup_code_struct
printf("I am cleaning up \n");
if (APPLY_SPECIFIC(input_descriptor) != NULL)
  cudnnDestroyTensorDescriptor(APPLY_SPECIFIC(input_descriptor));

But I am NOT  getting the print above. 

How does this section for cleanup gets called ? 
Do I have to tell explicitely to theano to clean this up ? 

Thanks

**Comment by nouiz** [comment]
This get called only when a Theano function get deleted. The way python work, when the process stop, it is not guaranted that all object are destroyed cleanly. Can you try to call "del f" on the function? Something like:
```
f=theano.function(...)
f()
del f
```

**Comment by aditbhrgv** [comment]
If I understand correctly, Theano can sometimes leak memory if it's not guranteed. This is also the case when I am running my GPU OP from python file, and when this python script stops, destructor is not called. 
But when I do 'del f ', it is called.

**Comment by aditbhrgv** [comment]
To add, when I run the above code in a python script,  destructor is still called. 
Then I don't understand why when I am calling GPU OP from Keras, destructor is not called.

**Comment by nouiz** [comment]
Theano do not leak memory. If f can be used in the futur, it cache object to speed up the next call. If you don't want to reuse it, make sure python will delete it. It is the same for all python object, we don't do more complicated stuff there. It is just that we probably cache more stuff then other python object, so it could be more visible.

More information.
In an op, you could want to create some object only once and reuse them between Theano function call. This is to speed up computation. This can be done by putting object in the "struct". Each apply node in the optimized graph will have its own struct.

The destructor of that struct is only called when the Theano function is delete.

If you want to create an object and destroy it at each call of a Theano function, don't put it in the struct section. Just put it in the normal c section and create it and delete it there.
