### ISSUE TITLE
How does theano reuse memory while stacking multiple layers ? No cudaMalloc, no cudaFree and no cudaStreamCreateWithFlags   in the forward pass 

### ISSUE THREAD

**Issue by aditbhrgv** [Theano/Theano#6528]
Hi,

I  have been lately studying Theano regarding creating a GPU OP which produces convolutions in 8-bit on GPU using NVIDIAs cudnn APIs. (Similar to the way the dnn.py is written in Theano). 

However, I am not very clear about some points: 
1. How does Theano allocates memory only once  at the beginning and reuse it again and again for each batch  and each layer thereafter ? How does GPU OP reuse memory ? Maybe somethiing related to context.  
2. I say point 1 because I can't see any cudaMalloc and cudaFree after running a forward pass. Also there is no cudaStreamCreateWithFlags cuda streams created. (which is increased when some cuda streams are created)
3. However, in dnn.py and dnn_fwd.c files, there are some code in #init_code_struct sections, which allocates input, kernel, output descriptors calling CreateTensordescriptor() which leads to increase in  cudaStreamCreateWithFlags .(this eats up my time )
4.In dnn_fwd.c, there are also gpu_allocate and  gpu_release() calls , for workspace parameter.
How does Theano doesn't do any  cudamalloc() and cudaFree() altogether ? 

Can you please guide me how to understand the whole call-flow for implementing a convolution GPU OP  the way theano implements. 

Thanks  

The below logs shows the cudaMalloc , cudaFree and cudaStreamCreateWithFlags in bold . These are initial allocations which Theano does iirrespective I change the number of layers. 
Which are 8 , 3 and 8 respectively and never increase when I call the forward pass with Conv2D layers and Dense layers.

Theano  version : 0.9.0

NVPROF Logs :

==19861== Profiling application: python normalCNN_src_ohne_train.py
==19861== Profiling result:
Time(%)      Time     Calls       Avg       Min       Max  Name
 43.45%  121.46ms       938  129.49us  25.025us  649.92us  maxwell_scudnn_128x64_interior_nn
 26.40%  73.794ms       312  236.52us  195.79us  311.31us  void magma_lds128_sgemm_kernel<bool=0, bool=0, int=6, int=5, int=3, int=3, int=3>(int, int, int, float const *, int, float const *, int, float*, int, int, int, float const *, float const *, float, float, int)
 13.63%  38.088ms      2201  17.304us  1.2800us  55.619us  elem
  5.41%  15.115ms       313  48.291us  4.7680us  1.9446ms  kSoftmaxWithBias
  5.31%  14.845ms       369  40.230us     672ns  109.45us  [CUDA memcpy HtoD]
  4.16%  11.627ms       626  18.572us  4.7040us  33.410us  void cudnn::detail::pooling_fw_4d_kernel<float, float, cudnn::detail::maxpooling_func<float, cudnnNanPropagation_t=1>, int=0>(cudnnTensorStruct, float const *, cudnn::detail::pooling_fw_4d_kernel<float, float, cudnn::detail::maxpooling_func<float, cudnnNanPropagation_t=1>, int=0>, cudnnTensorStruct*, cudnnPoolingStruct, float, cudnnPoolingStruct, int, cudnn::reduced_divisor, float)
  0.75%  2.0952ms       312  6.7150us  5.9520us  10.113us  void gemm_kernel1x1_core<float, bool=0, bool=0, bool=0, bool=0, bool=0>(float*, float const *, float const *, int, int, int, int, int, int, float*, float*, float, float, int)
  0.69%  1.9157ms       939  2.0400us  1.6960us  13.120us  cudnn::maxwell::gemm::computeOffsetsKernel(cudnn::maxwell::gemm::ComputeOffsetsParams)
  0.16%  449.81us       375  1.1990us     768ns  91.461us  [CUDA memcpy DtoH]
  0.02%  53.282us         1  53.282us  53.282us  53.282us  maxwell_scudnn_128x64_stridedB_splitK_interior_nn
  0.02%  43.105us        10  4.3100us  2.3680us  12.193us  mrg_uniform
  0.01%  31.393us         1  31.393us  31.393us  31.393us  void gemmSN_NN_kernel<float, float, float, int=256, int=4, int=2, int=8, int=4, int=4>(cublasGemmSmallNParams<float, float, float>, float const *, float const *, float, float, int)
  0.00%  5.9200us         1  5.9200us  5.9200us  5.9200us  void gemmSN_NN_kernel<float, float, float, int=128, int=2, int=4, int=8, int=4, int=4>(cublasGemmSmallNParams<float, float, float>, float const *, float const *, float, float, int)
  0.00%  3.4560us         1  3.4560us  3.4560us  3.4560us  void gemmSN_NN_kernel<float, float, float, int=128, int=2, int=4, int=8, int=2, int=4>(cublasGemmSmallNParams<float, float, float>, float const *, float const *, float, float, int)
  0.00%  2.5280us         1  2.5280us  2.5280us  2.5280us  void cudnn::maxwell::gemm::setOutputKernel<float>(int, float*, float)
  0.00%  1.7600us         1  1.7600us  1.7600us  1.7600us  cudnn::maxwell::gemm::computeBOffsetsKernel(cudnn::maxwell::gemm::ComputeBOffsetsParams)
  0.00%     576ns         1     576ns     576ns     576ns  [CUDA memset]

==19861== API calls:
Time(%)      Time     Calls       Avg       Min       Max  Name
 **27.64%  629.50ms         8  78.687ms  14.643us  629.31ms  cudaStreamCreateWithFlags**
 19.93%  453.95ms       361  1.2575ms  3.3850us  16.579ms  cuModuleUnload
 **19.69%  448.55ms         3  149.52ms     701ns  448.55ms  cudaFree**
 15.30%  348.46ms         1  348.46ms  348.46ms  348.46ms  cuDevicePrimaryCtxRetain
  8.39%  191.16ms       375  509.77us  12.643us  2.4834ms  cuMemcpyDtoHAsync
  2.51%  57.089ms        29  1.9686ms  1.4636ms  2.4209ms  cuLinkAddData
  1.68%  38.198ms      3133  12.192us  6.8750us  639.45us  cudaLaunch
  1.14%  25.888ms      2524  10.256us  5.9820us  753.99us  cuLaunchKernel
  0.91%  20.761ms       367  56.569us  7.1220us  701.01us  cuMemcpyHtoDAsync
  0.44%  10.020ms        29  345.53us  168.06us  1.1057ms  cuModuleLoadData
  0.41%  9.3563ms      7904  1.1830us     133ns  1.0138ms  cuDeviceGetAttribute
  0.26%  6.0141ms      9504     632ns     263ns  25.936us  cuEventCreate
  0.24%  5.3813ms     17520     307ns     144ns  621.12us  cudaSetupArgument
  0.23%  5.2991ms      9452     560ns     221ns  1.1632ms  cuEventDestroy
  0.21%  4.6703ms        29  161.04us  100.08us  264.74us  cuLinkComplete
  0.18%  4.0572ms        12  338.10us  234.56us  434.86us  cuDeviceTotalMem
  0.11%  2.4047ms        29  82.921us  40.908us  836.99us  cuLinkCreate
  0.10%  2.3527ms         1  2.3527ms  2.3527ms  2.3527ms  cuMemAlloc
  0.09%  2.0541ms       624  3.2910us  1.3010us  24.033us  cudaBindTexture
  0.08%  1.8526ms         4  463.16us  301.98us  900.37us  cuMemGetInfo
  0.06%  1.4743ms      3133     470ns     164ns  26.085us  cudaConfigureCall
  0.06%  1.4263ms      6740     211ns     123ns  18.845us  cuCtxGetDevice
  **0.06%  1.3993ms         6  233.22us  6.6790us  754.43us  cudaMalloc**
  0.06%  1.3264ms        13  102.03us  41.664us  662.07us  cuDeviceGetName
  0.05%  1.2493ms         1  1.2493ms  1.2493ms  1.2493ms  cuMemAllocHost
  0.05%  1.2114ms      4071     297ns     140ns  25.323us  cudaGetLastError
  0.04%  952.76us      2211     430ns     186ns  18.874us  cuFuncGetAttribute
  0.03%  634.34us         1  634.34us  634.34us  634.34us  cudaGetDeviceProperties
  0.03%  606.20us       624     971ns     476ns  22.283us  cudaUnbindTexture
  0.00%  61.405us         1  61.405us  61.405us  61.405us  cudaMemsetAsync
  0.00%  53.059us        58     914ns     153ns  6.8420us  cuCtxPushCurrent
  0.00%  42.320us        57     742ns     159ns  15.959us  cuCtxPopCurrent
  0.00%  32.813us         2  16.406us  13.207us  19.606us  cudaMemcpy
  0.00%  29.047us        40     726ns     491ns  3.2090us  cudaEventCreateWithFlags
  0.00%  25.406us        29     876ns     681ns  1.1660us  cuModuleGetFunction
  0.00%  24.121us         1  24.121us  24.121us  24.121us  cuStreamCreate
  0.00%  22.661us        77     294ns     220ns  1.3500us  cudaGetErrorString
  0.00%  21.834us        29     752ns     457ns  1.3200us  cuLinkDestroy
  0.00%  16.224us         1  16.224us  16.224us  16.224us  cuDeviceGetPCIBusId
  0.00%  14.051us        32     439ns     294ns  1.2440us  cudaDeviceGetAttribute
  0.00%  8.6230us        21     410ns     141ns  1.2900us  cuDeviceGet
  0.00%  7.8370us         3  2.6120us     897ns  3.9600us  cuInit
  0.00%  6.0880us         3  2.0290us  1.8230us  2.2140us  cudaGetDevice
  0.00%  3.7620us         2  1.8810us     781ns  2.9810us  cuDevicePrimaryCtxRelease
  0.00%  3.5000us         1  3.5000us  3.5000us  3.5000us  cudaGetDeviceCount
  0.00%  3.4530us         5     690ns     157ns  2.3220us  cuDeviceGetCount
  0.00%  2.1320us         3     710ns     482ns  1.1070us  cuDriverGetVersion
  0.00%  2.1290us         1  2.1290us  2.1290us  2.1290us  cudaDriverGetVersion
  0.00%  1.9830us         1  1.9830us  1.9830us  1.9830us  cuDevicePrimaryCtxGetState
  0.00%  1.1260us         1  1.1260us  1.1260us  1.1260us  cuDevicePrimaryCtxSetFlags

**Comment by nouiz** [comment]
1) libgpuarray have a wrapper on top of CudaMalloc. Theano use that wrapper. This allow us to reuse the malloc call done to cuda. This can give significant speed up. This behavior can be controled via a flag: http://deeplearning.net/software/theano/library/config.html#config.config.gpuarray.preallocate

2) We currently use only 1 stream per context by default. This can be changed via: http://deeplearning.net/software/theano/library/config.html#config.config.gpuarray.single_stream

3) cudnn could create stream. But we don't ask him ourself. This is its own internal stuff. But this is done only during the first call to a Theano function. Later call won't have those cost as we reuse them.

4) gpu_allocate and gpu_release are our wrapper to cudaMalloc. But we cache them for speed. Use the flag to disable our caching and see the cudamalloc call (and see slower execution speed)

**Comment by aditbhrgv** [comment]
Thank you very much for your valuable replies.
Just a follow up question : When I created my GPU Op, I created it in a Python file and then called this Op as:
doConv = MyConvOp(x, kernel)
fun = theano. function ([x], doConv)
fun(data)
This call gives me result of Convolution OP but when I do debug print using pydot in Theano, I can't see my post compilation graph. It's actually same as pre-compilation graph. 

I think this can be a problem as in normal Conv2D OP, theano uses an Abstract Conv2D layer. which takes TensorType inputs and returns TensorType outputs. But I am not doing that abstraction layer. I directly called this Op which has GpuarrayType inputs and GpuarrayType outputs.
Can this be the case that my Op is not able to print out  symbolic graph in post compilation using pydot?

**Comment by aditbhrgv** [comment]
This is the graph I am generating when I call my OP. It's same pre-and post compilation. I wonder if my OP is getting compiled with Theano function ?

![myconvop_pydotprint_postcompile](https://user-images.githubusercontent.com/19718391/33472909-7c751ad8-d674-11e7-9b4f-1bf6df2ff3a7.png)

**Comment by aditbhrgv** [comment]
These are the precompile and postcompile graphs for normal Theano conv2D op

![conv2d_pydotprint_precompile](https://user-images.githubusercontent.com/19718391/33473069-3e91c242-d675-11e7-941b-a7919215a34b.png)
![conv2d_pydotprint_postcompile](https://user-images.githubusercontent.com/19718391/33473070-3ecac1be-d675-11e7-9ae2-69d3dab20929.png)

**Comment by nouiz** [comment]
In your case, it is normal that the pre and post compilation is the same graph. Theano do not know your op, so don't apply any optimization on it. Did you expected something else?

**Comment by aditbhrgv** [comment]
So, how does I can register my OP with Theano  ?  Is there any documentation regarding this ?

**Comment by nouiz** [comment]
From the information I have, all your stuff work. If you know how to optimize your op, then you will need to create new optimization or modify current optimization to know about your op and to optimize it.

What did you expected?

**Comment by aditbhrgv** [comment]
Actually apart from returned callable object,  I expected to see the data flow when Theano compiled my OP in post-compile graph if not optimization because I have not writtten any  optimizations for my OP. 
But in function.py in comments section in  theano/compile folder, it mentions that there are no optimizations for new ops.
" 3. Optimization
               How well do optimizations apply to new ops?
                 **Usually there are no optimizations for new ops. In fact, new
        ops can disrupt patterns and break currently working optimizations.**
"

So I was confused with it how does it actually work . I was wondering whether  the post-compilation graph prints only the optimized graph or can it also print the non-optimized graph with the call flow for that particular op.

**Comment by nouiz** [comment]
I think you got an answer to all your questions. If so can you close this
issue?

**Comment by aditbhrgv** [comment]
I have one more question regarding this. Is there any logging mechanism to print intermediate messages  available in Theano which can be enabled from setting some environment variable ?

**Comment by notoraptor** [comment]
Hi,

To print intermediate values, you can use either Print op or monitor mode:
- About Print: http://deeplearning.net/software/theano/tutorial/debug_faq.html#how-do-i-print-an-intermediate-value-in-a-function
- About monitor mode: http://deeplearning.net/software/theano/tutorial/debug_faq.html#faq-monitormode

With monitor mode, you should be able to have an advanced control on the printed values.

**Comment by nouiz** [comment]
closing as no news. If you still have questions, don't hesitate.
