### ISSUE TITLE
I'm getting an ImportError in Theano in Anaconda

### ISSUE THREAD

**Issue by markgacoka** [Theano/Theano#6532]
When I import keras or theano after downloading it with Anaconda, I get this error.

F:\Anaconda>python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 07:29:16) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using Theano backend.

You can find the C code in this temporary file: C:\Users\JSI-NU~1\AppData\Local\Temp\theano_compilation_error_5fye1oej
Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Anaconda\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Anaconda\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "F:\Anaconda\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "F:\Anaconda\lib\site-packages\keras\utils\conv_utils.py", line 3, in <module>
    from .. import backend as K
  File "F:\Anaconda\lib\site-packages\keras\backend\__init__.py", line 80, in <module>
    from .theano_backend import *
  File "F:\Anaconda\lib\site-packages\keras\backend\theano_backend.py", line 3, in <module>
    import theano
  File "F:\Anaconda\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "F:\Anaconda\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "F:\Anaconda\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "F:\Anaconda\lib\site-packages\theano\gof\vm.py", line 673, in <module>
    from . import lazylinker_c
  File "F:\Anaconda\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "F:\Anaconda\lib\site-packages\theano\gof\cmodule.py", line 2356, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): C:\Users\JSI-NU~1\AppData\Local\Temp\ccAbnd1v.o: In function `import_ar. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1460: undefined reference to `_imp__PyExc_Im. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1466: undefined reference to `_imp__PyExc_At. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1471: undefined reference to `_imp__PyCapsul. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1472: undefined reference to `_imp__PyExc_Ru. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1487: undefined reference to `_imp__PyExc_Ru. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1495: undefined reference to `_imp__PyExc_Ru. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1501: undefined reference to `_imp__PyExc_Ru. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_api.h:1511: undefined reference to `_imp__PyExc_Ru. C:\Users\JSI-NU~1\AppData\Local\Temp\ccAbnd1v.o:F:/Anaconda/lib/site-packages/numpy/core/include/numpy/__multiarray_ap. F:/Anaconda/lib/site-packages/numpy/core/include/numpy/npy_3kcompat.h:456: undefined reference to `_imp__PyCapsule_Typ. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:\Users\JSI-NU~1\AppData\Local\Temp\ccAbnd1v.o:C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_GenuineIntel-3.6.3-32/lazylinker_ext/mod.cpp:393: more undefined references to. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:\Users\JSI-NU~1\AppData\Local\Temp\ccAbnd1v.o:C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_GenuineIntel-3.6.3-32/lazylinker_ext/mod.cpp:546: more undefined references to. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:\Users\JSI-NU~1\AppData\Local\Temp\ccAbnd1v.o:C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_GenuineIntel-3.6.3-32/lazylinker_ext/mod.cpp:850: more undefined references to. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. C:/Users/jsi-nupita/AppData/Local/Theano/compiledir_Windows-10-10.0.14393-SP0-x86_Family_6_Model_23_Stepping_10_Genuin. collect2.exe: error: ld returned 1 exit statusfined reference to `_imp___Py_TrueStruct'
>>>

What does it mean? I'm using a 32-bit Windows 10 Dell Computer

**Comment by notoraptor** [comment]
Hi:
- Have you installed the conda package `libpython` ?
- which version of GCC do you use (what is the output of `gcc -v`) ? The recommended version for Windows is the one provided in conda package `m2w64-toolchain`.
- Also, as you seems to use Aanaconda, make sure you always install the conda version of any module you use (`conda install <module>`/`conda remove <module>`) instead of the PyPI version (`pip install <module>` / `pip uninstall <module>`).

Could you make sure the following conda packages are installed, then clear the theano cache (`theano-cache purge`) and retry ?
```
conda install numpy scipy mkl-service libpython m2w64-toolchain
```

**Comment by markgacoka** [comment]
Thank you so much. I downloaded the packages and it's working fine...
But now I have one more problem. When I run keras library I get this error

Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:12:41) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
>>>

**Comment by notoraptor** [comment]
It's a warning, not an error, but indeed it would be better to not have this warning!

Have you installed mkl-service, and also mkl ?
```
conda install mkl mkl-service
```
If so, could you clear your theano cache (`theano-cache purge`) and then retry ?

Also, make sure to use the latest version of theano (at least 1.0.0).

**Comment by markgacoka** [comment]
I'm still getting the error... 
and the mkl-service is already installed.

When I run the theano-cache purge code I get an error displaying: Fatal error in launcher: Unable to create process using '"'

What else can I do? Thanks for the help thus far by the way.

**Comment by notoraptor** [comment]
Hi, could you check if you see any file matching the pattern `mkl*.dll` in your python library path ? (look into `Library\bin` in the folder returned by python code `import sys; print(sys.prefix)`).

**Comment by wsrosent** [comment]
I am encountering the same issue when I run any of the Theano tests. The first line of output is the warning:

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

Posts on this site claim that while this is a warning, performance may be slowed, so any help interpreting or clearing up the warning is appreciated. To follow-up on the previous comments:

1. mkl-services (including mkl) have been installed, per a separate warning about not having mkl-services installed, which disappeared after installing this package.

2. In attempting to purge the theano cache, a warning is returned indicating that no c++ compiler is installed:

C:\Users\rose396\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\theano\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."

3. I checked the python library path and numerous mkl*.dll files exist. In case it helps, here is the list:

mkl_avx.dll, mkl_avx2.dll, mkl_avx512.dll, mkl_avx512_mic.dll, mkl_blacs_ilp64.dll, mkl_blacs_intelmpi_ilp64.dll, mkl_blacs_intelmpi_lp64.dll, mkl_blacs_lp64.dll, mkl_blacs_mpich2_ilp64.dll, mkl_blacs_mpich2_lp64.dll, mkl_blacs_msmpi_ilp64.dll, mkl_blacs_msmpi_lp64.dll, mkl_cdft_core.dll, mkl_core.dll, mkl_def.dll, mkl_intel_thread.dll, mkl_mc.dll, mkl_mc3.dll, mkl_pgi_thread.dll, mkl_rt.dll, mkl_scalapack_ilp64.dll, mkl_scalapack_lp64.dll, mkl_sequential.dll, mkl_tbb_thread.dll, mkl_vml_avx.dll, mkl_vml_avx2.dll, mkl_vml_avx512.dll, mkl_vml_avx512_mic.dll, mkl_vml_cmpt.dll, mkl_vml_def.dll, mkl_vml_mc.dll, mkl_vml_mc2.dll, mkl_vml_mc3.dll

**Comment by dsblank** [comment]
Finally got rid of the warning with:

```
sudo apt install libblas-dev
```

**Comment by shahlaebrahimi** [comment]
@dsblank Hi
Could you please let me know where I should run your solution? I tried to install it via anaconda promt but the error is:
'sudo' is not recognized as an internal or external command,
operable program or batch file.

Best regards,

**Comment by dsblank** [comment]
@shahlaebrahimi My solution worked on my Linux computer from the console/terminal.

**Comment by shahlaebrahimi** [comment]
Thanks. Could you please let me know how to resolve my error on  windows 10 is: 
```
C:\Users\Markazi.co\Anaconda3\python.exe "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/Imbalanced - Copy - Copy.py"
Traceback (most recent call last):

  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
    raise ImportError()
You can find the C code in this temporary file: C:\Users\Markazi.co\AppData\Local\Temp\theano_compilation_error_sl8b3_3j
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/Imbalanced - Copy - Copy.py", line 19, in <module>
    import theano.tensor as T
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\vm.py", line 673, in <module>
    from . import lazylinker_c
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
    preargs=args)
  File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2359, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
. 
```

**Comment by wqp89324** [comment]
@notoraptor 
I'm trying to convert to the new gpu back end, and I also have the warning:
`(theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.`
After running gcc -v, here is what I get:

`
Using built-in specs.
COLLECT_GCC=C:\Program Files\Anaconda3\Scripts\gcc.bat\..\..\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/program files/anaconda3/mingw/bin/../libexec/gcc/x86_64-w
64-mingw32/4.7.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../build/gcc/src/configure --target=x86_64-w64-mingw32 --
prefix=/c/bb/vista64-mingw32/mingw-x86-x86_64/build/build/root --with-sysroot=/c
/bb/vista64-mingw32/mingw-x86-x86_64/build/build/root --enable-languages=all,obj
-c++ --enable-fully-dynamic-string --disable-multilib
Thread model: win32
gcc version 4.7.0 20111220 (experimental) (GCC)
`
How can I get rid to the current gcc and use the one that you recommended? I'm on Windows. 

Thanks!

**Comment by wqp89324** [comment]
@notoraptor What is the right output of gcc -v (that uses recommended gcc from conda package m2w64-toolchain)? I'm still struggling to troubleshoot my issue. 

Thanks!

**Comment by amruta24** [comment]
C:\Users\student\Anaconda2\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."

**Comment by migalo22** [comment]
@wsrosent have you find a solution ?

**Comment by alpynepyano** [comment]
Perhaps you might try [this](https://github.com/Theano/Theano/issues/6654)

**Comment by siliconMagic** [comment]
> Hi
> Thanks.
> Could you please let me know how to resolve my error on windows 10 is:
> 
> ```
> C:\Users\Markazi.co\Anaconda3\python.exe "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/Imbalanced - Copy - Copy.py"
> Traceback (most recent call last):
> 
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 75, in <module>
>     raise ImportError()
> You can find the C code in this temporary file: C:\Users\Markazi.co\AppData\Local\Temp\theano_compilation_error_sl8b3_3j
> ImportError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 92, in <module>
>     raise ImportError()
> ImportError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:/mifs-master_2/MU/learning-from-imbalanced-classes-master/learning-from-imbalanced-classes-master/continuous/Imbalanced - Copy - Copy.py", line 19, in <module>
>     import theano.tensor as T
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\__init__.py", line 110, in <module>
>     from theano.compile import (
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
>     from theano.compile.mode import *
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\compile\mode.py", line 11, in <module>
>     import theano.gof.vm
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\vm.py", line 673, in <module>
>     from . import lazylinker_c
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py", line 127, in <module>
>     preargs=args)
>   File "C:\Users\Markazi.co\Anaconda3\lib\site-packages\theano\gof\cmodule.py", line 2359, in compile_str
>     (status, compile_stderr.replace('\n', '. ')))
> . 
> ```
> 
> Best regards,

I come across this problem too, how to fix it?

**Comment by AllenDowney** [comment]
It seems like this issue might be back.  I just ran a `conda update -all` in the environment where I use PyMC3.  And now I am getting this warning:

```
/home/downey/anaconda3/envs/ThinkBayes2/lib/python3.8/site-packages/theano/configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

And now some sampling that used to be fast is ridiculously slow.

I've got libblas-dev installed at the system level.

```
$ sudo apt install libblas-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libblas-dev is already the newest version (3.6.0-2ubuntu2).
```

Here are the current versions of the other packages:

```
python                    3.8.8                hdb3f193_4  
pymc3                     3.8                        py_0  
arviz                     0.11.0             pyhd8ed1ab_0    conda-forge
```

Note that I had to hold back arviz to solve the geweke problem.

Is it time to blow away this environment and try again?
