### ISSUE TITLE
Can you tell me whether self.scale is constant in the training process after initialization?

### ISSUE THREAD

**Issue by zhangqianhui** [Theano/Theano#6535]
I have asked a question in stackoverflow.
[
https://stackoverflow.com/questions/47755200/is-it-constant-for-self-scale-variables-defined-in-constructor-function](url)

Thanks for your help.

**Comment by zhangqianhui** [comment]
https://stackoverflow.com/questions/47755200/is-it-constant-for-self-scale-variables-defined-in-constructor-function

**Comment by nouiz** [comment]
replied
