### ISSUE TITLE
Theano 1.0.1 - ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

### ISSUE THREAD

**Issue by shivank01** [Theano/Theano#6538]
Just installed theano and trying to check if it was using my amd gpu.
test.py 
` 
from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')

 `

the error is as follows:
` $ sudo THEANO_FLAGS=device=opencl0:0 python test.py

[sudo] password for shivank: 

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 227, in <module>
    use(config.device)

  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)

  File "/usr/local/lib/python2.7/dist-packages/theano/gpuarray/__init__.py", line 99, in init_dev
    **args)

  File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init (pygpu/gpuarray.c:9532)

  File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:9028)

GpuArrayException: clGetPlatformIDs(0, NULL, &nump): Unknown error

[Elemwise{exp,no_inplace}(<TensorType(float64, vector)>)]

Looping 1000 times took 12.010373 seconds

Result is [ 1.23178032  1.61879341  1.52278065 ...,  2.20771815  2.29967753
  1.62323285]

Used the cpu
`

running Ubuntu 16.04 /python2.7

**Comment by nouiz** [comment]
We do not support AMD GPU. We started OpenCL support, but it isn't finished. Due to 👍 
https://groups.google.com/d/topic/theano-users/7Poq8BZutbY/discussion

We won't finish this feature.
