### ISSUE TITLE
bug in test_bn.py

### ISSUE THREAD

**Issue by aswin-raghavan** [Theano/Theano#6542]
Lines 72,73
Function is compiled with an particular arguments
but the order is mistaken in the call (subsequent line)
f_ref = theano.function([x, b, g, m, v], [bn_ref_op])
res_ref = f_ref(X, G, B, M, V)
Should be X,B,G,M,V...

**Comment by nouiz** [comment]
Should be fixed in: https://github.com/Theano/Theano/pull/6546#pullrequestreview-87248300

thanks for the report.
