### ISSUE TITLE
feature request: pseudoinverse on GPU

### ISSUE THREAD

**Issue by pstjohn** [Theano/Theano#6559]
skcuda has a `pinv` function: http://scikit-cuda.readthedocs.io/en/latest/generated/skcuda.linalg.pinv.html

It would be awesome if there was a GPU-enabled pseudoinverse option. I'm building a model that requires a pseudoinverse solve, for larger matrices it really gets bogged down by the CPU.

Is there a PR for a similar feature that would easy enough to follow?

**Comment by nouiz** [comment]
due to :
https://groups.google.com/forum/#!msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ

we won't implement new features.
