### ISSUE TITLE
"ValueError: images and kernel must have the same stack size" Only on GPU

### ISSUE THREAD

**Issue by massimilianocomin** [Theano/Theano#6563]
Hi,

I am facing the error below only when I run my code on GPU, on CPU everything is fine.

I am using Helios cluster : 
GPU : Tesla k80
Theano version : 1.0.1
CUDA version : 8.0.44

The model is a GAN over 1D data (with 3 'color' channels), so I use Lasagne's 1D convolutions i.e. 2D convolutions with height or width set to one. I tried to change the kernel size, set the stride and dilation to one, and changing convolutions.

Here is the error message : 

> Inactive Modules:
 

>  1) mpi/openmpi/1.8.7
> 
> The following have been reloaded with a version change:
>   1) cuda/6.0.37 => cuda/8.0.44
> 
> WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
> Using cuDNN version 6021 on context None
> Preallocating 10295/11439 Mb (0.900000) on cuda
> Mapped name None to device cuda: Tesla K80 (0000:94:00.0)
> Traceback (most recent call last):
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/compile/function_module.py", line 903, in __call__
>     self.fn() if output_subset is None else\
> ValueError: images and kernel must have the same stack size
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "asi_wgan.py", line 417, in <module>
>     S.train(data, epochs=100, shuffle=True, dg=5)
>   File "asi_wgan.py", line 204, in train
>     self.d_cost += [self.dtrain(j, z, eta)]
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/compile/function_module.py", line 917, in __call__
>     storage_map=getattr(self.fn, 'storage_map', None))
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gof/link.py", line 325, in raise_with_op
>     reraise(exc_type, exc_value, exc_trace)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/six.py", line 692, in reraise
>     raise value.with_traceback(tb)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/compile/function_module.py", line 903, in __call__
>     self.fn() if output_subset is None else\
> ValueError: images and kernel must have the same stack size
> Apply node that caused the error: GpuDnnConv{algo='small', inplace=True, num_groups=1}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty{dtype='float32', context_name=None}.0, GpuDnnConvDesc{border_mode='half', subsample=(1, 1), dilation=(1, 1), conv_mode='conv', precision='float32', num_groups=1}.0, Constant{1.0}, Constant{0.0})
> Toposort index: 153
> Inputs types: [GpuArrayType<None>(float32, (False, False, True, False)), GpuArrayType<None>(float32, (False, False, True, False)), GpuArrayType<None>(float32, (False, False, True, False)), <theano.gof.type.CDataType object at 0x2ab55721a1d0>, Scalar(float32), Scalar(float32)]
> Inputs shapes: [(128, 216, 1, 3), (32, 3, 1, 3), (128, 32, 1, 3), 'No shapes', (), ()]
> Inputs strides: [(2592, 12, 12, 4), (36, 12, 12, 4), (384, 12, 12, 4), 'No strides', (), ()]
> Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x2ab55f42e5a0>, 1.0, 0.0]
> Inputs type_num: [11, 11, 11, '', 11, 11]
> Outputs clients: [[Rebroadcast{?,?,0}(GpuDnnConv{algo='small', inplace=True, num_groups=1}.0)]]
> 
> Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
>   File "asi_wgan.py", line 413, in <module>
>     S = WGAN(n, d, batchsize=128)
>   File "asi_wgan.py", line 87, in __init__
>     d_real = L.get_output(discriminator)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/lasagne/layers/helper.py", line 197, in get_output
>     all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/lasagne/layers/conv.py", line 333, in get_output_for
>     conved = self.convolve(input, **kwargs)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/lasagne/layers/conv.py", line 487, in convolve
>     filter_flip=self.flip_filters)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/lasagne/theano_extensions/conv.py", line 71, in conv1d_mc0
> filter_flip=filter_flip)

The error appears on the first convolution of the discriminator.

Any help would be appreciated,

Thanks !

**Comment by nouiz** [comment]
It is possible that the CPU just do not do this verification. Can you try
with the Theano flag more=DebugMode.

If it don't fail, it is probably what I wrote. Otherwise send the error.

**Comment by massimilianocomin** [comment]
Ok actually in FAST_RUN mode on CPU I have : 
- conv1d_mc1 (conv2d with height == 1) Works
- conv1d_mc0

>  (conv2d with width == 1) Crashes when compiling with the following error 
> 
> ERROR (theano.gof.opt): Optimization failure due to: constant_folding
> ERROR (theano.gof.opt): node: MakeVector{dtype='int64'}(TensorConstant{64}, TensorConstant{32}, TensorConstant{1}, TensorConstant{216})
> ERROR (theano.gof.opt): TRACEBACK:
> ERROR (theano.gof.opt): Traceback (most recent call last):
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/opt.py", line 2019, in process_node
>     replacements = lopt.transform(node)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/tensor/opt.py", line 6507, in constant_folding
>     no_recycling=[], impl=impl)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/op.py", line 955, in make_thunk
>     no_recycling)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/op.py", line 858, in make_c_thunk
>     output_storage=node_output_storage)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/cc.py", line 1217, in make_thunk
>     keep_lock=keep_lock)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/cc.py", line 1157, in __compile__
>     keep_lock=keep_lock)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/cc.py", line 1620, in cthunk_factory
>     key=key, lnk=self, keep_lock=keep_lock)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1140, in module_from_key
>     module = self._get_from_hash(module_hash, key, keep_lock=keep_lock)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1040, in _get_from_hash
>     key_data.add_key(key, save_pkl=bool(key[0]))
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/gof/cmodule.py", line 501, in add_key
>     assert key not in self.keys
> AssertionError


Now in DebugMode on CPU I have the same results (apart from the fact that conv1d_mc1 takes too long to run even one batch, so I can only say that it compiles correctly)

So it seems that the problem comes from the convolution used. I was using a modification of conv1d_mc0 that simply added support for filter_dilation that gives yet another error : 

> WARNING (theano.tensor.opt): Failed to infer_shape from Op AbstractConv2d{convdim=2, border_mode='half', subsample=(1, (1,)), filter_flip=True, imshp=(64, 16, 1, 216), kshp=(32, 16, 1, 5), filter_dilation=(1, 1), num_groups=1, unshared=False}.
> Input shapes: [(TensorConstant{64}, TensorConstant{16}, TensorConstant{1}, TensorConstant{216}), (Shape_i{0}.0, Shape_i{1}.0, TensorConstant{1}, Shape_i{2}.0)]
> Exception encountered during infer_shape: <class 'TypeError'>
> Exception message: unsupported operand type(s) for //: 'int' and 'tuple'
> Traceback: Traceback (most recent call last):
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/tensor/opt.py", line 946, in get_node_infer_shape
>     [self.shape_of[r] for r in node.inputs])
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/tensor/nnet/abstract_conv.py", line 2439, in infer_shape
>     self.subsample, self.filter_dilation)
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/tensor/nnet/abstract_conv.py", line 91, in get_conv_output_shape
>     subsample[i], filter_dilation[i]) for i in range(len(subsample)))
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/tensor/nnet/abstract_conv.py", line 91, in <genexpr>
>     subsample[i], filter_dilation[i]) for i in range(len(subsample)))
>   File "/Network/Servers/seguin.pmc.umontreal.ca/Users/mcomin/miniconda3/lib/python3.5/site-packages/theano/tensor/nnet/abstract_conv.py", line 151, in get_conv_shape_1axis
>     out_shp = out_shp // subsample
> TypeError: unsupported operand type(s) for //: 'int' and 'tuple'


 Strangely enough, it was working last week on CPU and GPU, and I haven't changed much in the code. (I don't understand why it's failing today even in FAST_RUN mode..)

**Comment by massimilianocomin** [comment]
Update : I have a similar problem with another model, still with 2D convolutions, though the error is different : 

> Traceback (most recent call last):
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/compile/function_module.py", line 903, in __call__
>     self.fn() if output_subset is None else\
> AssertionError: The convolution would produce an invalid shape (dim[2] <= 0).

After clearing the theano cache on my local machine, everything runs fine. I am still getting these errors on GPU.
Clearing the cache on the cluster gives the following error (while on my local machine there are no errors) : 

> WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
> ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
> Traceback (most recent call last):
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 227, in <module>
>     use(config.device)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 214, in use
>     init_dev(device, preallocate=preallocate)
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gpuarray/__init__.py", line 99, in init_dev
>     **args)
>   File "pygpu/gpuarray.pyx", line 651, in pygpu.gpuarray.init
>   File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.pygpu_init
> pygpu.gpuarray.GpuArrayException: b'cuInit: CUDA_ERROR_UNKNOWN: unknown error'
> WARNING (theano.gof.cmodule): A module that was loaded by this ModuleCache can no longer be read from file /home/cominm/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.9-Final-x86_64-3.5.4-64/tmppnxoy5vo/mb723a79e77767d1dbdefdd68a32a62b84558aa21c10528d0101d296d860cddc8.so... this could lead to problems.
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1507, in _on_atexit
>     self.clear_unversioned()
>   File "/home/cominm/miniconda/lib/python3.5/site-packages/theano/gof/cmodule.py", line 1448, in clear_unversioned
>     for filename in os.listdir(self.dirname):
> FileNotFoundError: [Errno 2] No such file or directory: '/home/cominm/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-centos-6.9-Final-x86_64-3.5.4-64'

I will try to reinstall everything from scratch, to see if that helps.

**Comment by nouiz** [comment]
Can you manually delete the cache?

rm -rf ~/.theano

**Comment by massimilianocomin** [comment]
I just did it and I still get the same error. 
I also tried to run the code on a CPU cluster, and it gives me the same error !
(I checked that theano.config.device was set to 'cpu')

So it's only working on my local machine.. I can't figure out why : the python/theano/lasagne/pygpu/libgpuarray versions are the same.

**Comment by massimilianocomin** [comment]
Ok so the only differences are the OS (CentOS 6.9 for GPU cluster, Carbon for CPU cluster, OS X El Capital for local machine) and the versions of GCC ('[GCC 7.2.0] on linux' for clusters, '[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin' on local machine).

To be totally sure that everything is OK on my machine (no older versions etc..) I created a new environment and installed only the required packages for the code to run and tested it, and it worked.
