### ISSUE TITLE
incorrect gif in doc

### ISSUE THREAD

**Issue by shesung** [Theano/Theano#6566]
the gif in https://github.com/Theano/Theano/blob/4d46e410bc765e9e288996c7da693146df69e3b9/doc/tutorial/conv_arithmetic.txt#L878

gif link : http://deeplearning.net/software/theano/_images/padding_strides_odd_transposed.gif

seems incorrect. 

For the input, there should be two zero row padding at bottom , but not at top.

**Comment by nouiz** [comment]
@vdumoulin what do you think of this issue?

**Comment by vdumoulin** [comment]
@shesung is correct, this is a mistake we made when first writing the guide. We have fixed it in the guide's repo (see [this commit](https://github.com/vdumoulin/conv_arithmetic/commit/5102586288b59400729d31502250111c6e089d5d)) but forgot to port the fix back here.

This should be a very simple fix: we just need to swap the GIF linked above with the [updated GIF](https://github.com/vdumoulin/conv_arithmetic/blob/master/gif/padding_strides_odd_transposed.gif).

**Comment by nouiz** [comment]
Thanks, here is the PR that fix this: https://github.com/Theano/Theano/pull/6581
