### ISSUE TITLE
Theano Runtime Error - must set MKL_THREADING_LAYER=GNU in environement

### ISSUE THREAD

**Issue by Oxi84** [Theano/Theano#6568]
I am getting this error when I try to run theano using anaconda and python 2.7.
RuntimeError: To use MKL 2018 with Theano you MUST set "MKL_THREADING_LAYER=GNU" in your environement.

What does this mean. I am running windows 7 and I do not know what term environment means.

Where should I change something?

**Comment by Oxi84** [comment]
I tried to unistal mkl as I do not want to run it, and I get another error. Because this broke numpy for some reason so I had to install numpy again and now I get the same error again.

**Comment by nouiz** [comment]
Google for "windows environment variable". Maybe this page can help you:

https://www.java.com/en/download/help/path.xml

This is  a problem with MKL that we cannot fix inside Theano.

**Comment by fundmntlTheorem** [comment]
I had this issue too.  It seems to be fixed by going to System Properties, Environment variables.  Add a New environment variable, and set name to MKL_THREADING_LAYER, and value to GNU.  This then allowed to execute import theano from the python shell.

![image](https://user-images.githubusercontent.com/12117028/37112856-868783f6-21f8-11e8-9d83-2759152f7835.png)

**Comment by jonesaj** [comment]
Linux user here, but if you are working inside of a conda virtual environment, it should be noted that you MAY need to perform the step outlined above by @fundmntlTheorem EACH time you enter that environment (this is the case for Linux). For instance, in Linux, I had to write a script to call "export MKL_THREADING_LAYER=GNU" (which sets that environment variable) each time I activate the virtual environment, and a counter script to undo that change upon exiting the environment. Sorry I can't be of more help for Windows.

**Comment by bhavanikallam** [comment]
I am getting this error when I write import theano
![111](https://user-images.githubusercontent.com/36656934/37390562-86d51bca-278e-11e8-9913-4b1fce60b02f.PNG)

**Comment by nouiz** [comment]
See the comments above. It answer the question how to set an environment variable to fix this problem. Theano sadly cannot do it for you.

**Comment by FrankZijlstra** [comment]
After running into this, the solution is quite easy to do from within Python like this:
```
import os
os.environ["MKL_THREADING_LAYER"] = "GNU"
```

Couldn't this be added somewhere in Theano?

**Comment by ikrambennasrbennasr** [comment]
@jonesaj , Can you explain to me more clearly this problem, I use a virtual machine ubuntu with amozon and i get the same problem! Thanks a lot

**Comment by nouiz** [comment]
@FrankZijlstra do not have a good work around. It can bypass the check, but it could result in wrong results. Theano master have an updated check that whitelist newer numpy version that contain a fix upstream.

**Comment by nouiz** [comment]
You can update Theano to the dev version to have the new check. Otherwise, in your shell environment, create a variable "MKL_THREADING_LAYER" and give it the value "GNU".

**Comment by ikrambennasrbennasr** [comment]
i solve the problem by typing : 
export MKL_THREADING_LAYER=GNU
$ env MKL_THREADING_LAYER=GNU

**Comment by sen-mao** [comment]
Running` conda install theano==0.9.0` fixed this error for me , of course runing `conda remove theano` befor

**Comment by abergeron** [comment]
The proper solution is to either update NumPy to the latest conda package and Theano to 1.0.2 or export MKL_THREADING_LAYER=GNU in your environment.

Downgrading to Theano 0.9.0 will just bypass the check and expose you to possible bad results.

**Comment by benmbrennan** [comment]
I've attempted to update NumPy and add the environment variable.  Neither work.  I wish I wasn't losing my Matlab license.  :(

**Comment by michaelklachko** [comment]
I'm using numpy 1.15.1, theano 1.0.2, mkl 2019.0 and mkl-service 1.1.2 and still getting this error:

```
To use MKL 2018 with Theano either update the numpy conda packages to
their latest build or set "MKL_THREADING_LAYER=GNU" in your
environment.
```

I wonder if it tries to find mkl 2018 while I have mkl 2019?

**Comment by abergeron** [comment]
Running this:
```
conda create -n mkl2019 python=3.6 numpy theano
source activate mkl2019
python -c 'import theano; print(theano.config.blas.ldflags)'
```
On a clean machine with no special config gives me no error and prints
```
-L<snip>/miniconda/envs/mkl2019/lib -lmkl_rt -lpthread -lm -lm
```
Which is what I would expect.

Can you post the exact steps that lead to you getting the error message.

**Comment by michaelklachko** [comment]
The exact steps:

1. Downloaded and installed miniconda2 to my Windows 10 machine
2. opened 'anaconda prompt' shell
3. conda update conda
4. conda install numpy scipy mkl-service libpython m2w64-toolchain
5. conda install theano

I don't have any .theanorc file. Note I'm using python2.

Adding 
```
import os
os.environ["MKL_THREADING_LAYER"] = "GNU"
```

fixes the problem.

**Comment by abergeron** [comment]
Ah ok.  It appears that the windows python 2.7 numpy packages don't include the _mklinit patch.

Either set the MKL_THREADING_LAYER in you env like indicated at the top of this issue or update to python 3 which does have patched packages.

**Comment by jingweimo** [comment]
conda uninstall mkl=2018
conda install mkl=2017
