### ISSUE TITLE
AttributeError: module 'theano' has no attribute 'gof', when i import theano

### ISSUE THREAD

**Issue by MrDarcy1** [Theano/Theano#6576]
I use python3.5 on anaconda with spider, theano 1.0.
I have tried to install all sort of things like mingw or m264-toolchain, etc using conda.
`Problem occurred during compilation with the command line below:
"G:\gcc\gcc\bin\g++.exe" -shared -g -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -DMS_WIN64 -I"G:\anaconda2\envs\python35\lib\site-packages\numpy\core\include" -I"G:\anaconda2\envs\python35\include" -I"G:\anaconda2\envs\python35\lib\site-packages\theano\gof" -L"G:\anaconda2\envs\python35\libs" -L"G:\anaconda2\envs\python35" -o C:\Users\admin\AppData\Local\Theano\compiledir_Windows-10-10.0.16299-SP0-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.5.4-64\lazylinker_ext\lazylinker_ext.pyd C:\Users\admin\AppData\Local\Theano\compiledir_Windows-10-10.0.16299-SP0-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.5.4-64\lazylinker_ext\mod.cpp -lpython35
Traceback (most recent call last):

  File "<ipython-input-4-3397704bd624>", line 1, in <module>
    import theano

  File "G:\anaconda2\envs\python35\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (

  File "G:\anaconda2\envs\python35\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *

  File "G:\anaconda2\envs\python35\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm

  File "G:\anaconda2\envs\python35\lib\site-packages\theano\gof\vm.py", line 671, in <module>
    except (OSError, theano.gof.cmodule.MissingGXX) as e:

AttributeError: module 'theano' has no attribute 'gof'`

The error is shown above

How to fix this

**Comment by abergeron** [comment]
You are using an external g++ (as evidenced by `"G:\gcc\gcc\bin\g++.exe"`).  You need to use the one provided by anaconda with the `m2w64-toolchain` package.  We don't support any other configuration.

**Comment by MrDarcy1** [comment]
so, how could i change to use m2w64-toolchain package?

**Comment by nouiz** [comment]
Start by removing the extra one. Maybe will find the correct one after that.

**Comment by Wisconsin786** [comment]
@MrDarcy1  did you find solution? I tried installing m2w64-toolchain package via pip but i did not get installed.

**Comment by abergeron** [comment]
m2w64-toolchain is a conda package.  We don't support pip install on Windows.

**Comment by CedricBeaulac** [comment]
I'm having a similar problem event though I installed m2w64-toolchain.

You can find the C code in this temporary file: C:\Users\THEBEA~1\AppData\Local\Temp\theano_compilation_error_s8_im1od
Traceback (most recent call last):

  File "<ipython-input-16-e2d3ee711e72>", line 1, in <module>
    import theano

  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\__init__.py", line 110, in <module>
    from theano.compile import (

  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\__init__.py", line 12, in <module>
    from theano.compile.mode import *

  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\mode.py", line 11, in <module>
    import theano.gof.vm

  File "C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\vm.py", line 683, in <module>
    except (OSError, theano.gof.cmodule.MissingGXX) as e:

AttributeError: module 'theano' has no attribute 'gof'

**Comment by nouiz** [comment]
Try to uninstall Theano many times. This can happen if many versions are installed in the computer and they get mixed for strange configuration problem.
When you are sure there is no Theano installation left, even if they should not be used, reinstall it.

**Comment by CedricBeaulac** [comment]
> Try to uninstall Theano many times. This can happen if many versions are installed in the computer and they get mixed for strange configuration problem.
> When you are sure there is no Theano installation left, even if they should not be used, reinstall it.

Thank you so much, this Is actually what I did and it did end up solving this particular issue. But it automatically lead to another issue : https://github.com/Theano/Theano/issues/6722

**Comment by Attilaali** [comment]
conda install m2w64-toolchain
