### ISSUE TITLE
A trivial bug in variable naming in scan.

### ISSUE THREAD

**Issue by Glexin** [Theano/Theano#6578]
https://github.com/Theano/Theano/blob/b2fdd67a2df938153560a881313642a0f19fc1bd/theano/scan_module/scan.py#L581-L583

In _'zip(scan_seqs, seqs)'_ _scan_seqs_ doesn't consists with _seqs_ by index. _scan_seqs_ is exploded _seqs_ by taps.

**Comment by nouiz** [comment]
thanks for the report. Here is a fix: https://github.com/Theano/Theano/pull/6582
