### ISSUE TITLE
theano 1.0 is slower than 0.9

### ISSUE THREAD

**Issue by eyaler** [Theano/Theano#6579]
I am training a VAE-LSTM: https://github.com/stas-semeniuta/textvae
this is on V100
with theano 1.0.1 i am seeing a x2 slowdown from 0.9

my setup:
ubuntu 16.04
python 3.6.4
coda 9 or 9.1
cudnn 7.1.1
slow: theano 1.0.1 pygpu 0.7.5
fast: theano 0.9 pygpu 0.6.9

**Comment by nouiz** [comment]
How do you do your timing? Can you enable Theano profiler in both case and send both output? See: http://deeplearning.net/software/theano/tutorial/profiling.html

**Comment by iteachmachines** [comment]
Just in a case try to update the Theano you're using currently

**Comment by iteachmachines** [comment]
The following command will update only Theano:

<sudo> pip install <--user> <--no-deps> theano
Use sudo for a root installation.
Use user for a user installation without admin rights. It will install Theano in your local site-packages.
Use no-deps when you don’t want the dependencies of Theano to not be installed through pip. This is important when they have already been installed as system packages.

**Comment by nouiz** [comment]
As no news for a long time, I'll close this issue.
