### ISSUE TITLE
Remove MKL_THREADING_LAYER=GNU not present error with newer NumPy version

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#6580]
Our report about the bug needing MKL_THREADING_LAYER=GNU this work around got followed up by a fix in https://github.com/AnacondaRecipes/numpy-feedstock/pull/5, we do not need that error anymore with mkl 2018. Those version of numpy include the fix:

numpy 1.13.3, build 3 or higher
numpy 1.14.1, build 2 or above
numpy 1.14.2, all versions

I was told that we could detect if the fix is present like this:

"Detecting it based on version won't really be possible, because numpy itself has no idea about build numbers.  You should instead be able to test for the existence of the _mklinit module in numpy.  Please see Sasha's PR at https://github.com/AnacondaRecipes/numpy-feedstock/pull/5 for more information."

Also:

"Also, import numpy with MKL_VERBOSE set to 1 should print some diagnostics, like so:

(idp_py3_dev) [09:03:34 linvm native]$ MKL_VERBOSE=1 python -c "import numpy"
Numpy + Intel(R) MKL: THREADING LAYER: (null)
Numpy + Intel(R) MKL: setting Intel(R) MKL to use INTEL OpenMP runtime
Numpy + Intel(R) MKL: preloading libiomp5.so runtime
"

Removing this error would ease the installation of Theano, especially for people on Windows that are less used to set variable environment.

**Comment by twiecki** [comment]
@nouiz Could you give a few more hints as to what needs to change where?

**Comment by nouiz** [comment]
What come to mind is to mostly grep for  MKL_THREADING_LAYER=GNU in Theano and find where the error is raised. Then at that place, change the condition such that newer version of numpy do not trigger the error. This should be tested with "You should instead be able to test for the existence of the _mklinit module in numpy."

Maybe also update the error message to tell they can update NumPy in conda to remove the need of the env variable.

**Comment by abergeron** [comment]
This is done
