### ISSUE TITLE
Getting the warning message while running theano. The error is mentioned below

### ISSUE THREAD

**Issue by rahashwini** [Theano/Theano#6585]
warnings.warn("DeprecationWarning: there is no c++ compiler."
UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.

**Comment by lamblin** [comment]
This is not the place to request support, please use StackOverflow or theano-users.
The issue is that Theano does not find a C++ compiler. Please follow the installation instructions to know how to install a compatible one.
