### ISSUE TITLE
import theano failure

### ISSUE THREAD

**Issue by alfredaita** [Theano/Theano#6592]
windows 10 ; anaconda / python 3.6 
installed through conda-forge
PYMC3 with Theano
when import pymc3 or theano:
I get the following runtime error message being thrown in  _init_.py  in theano directory:

"You have the theano directory in your Python path. 
    This do not work in Python 3."
 

If you have any questions on Theano, please ask your questions in either [theano-user mailing list](https://groups.google.com/forum/#!forum/theano-users) or [stackoverflow](http://stackoverflow.com/) with the "theano" tag.

Use issue only to report bugs or to ask for new features in Theano.

Before reporting a bug, update to Theano development version. Maybe it
is already fixed. If not, tell us the Theano flags and Theano version
that generate the problem. If it is a regression, can do a "git
bisect" to idenfy when the problem appeard. This really help fix it
rapidly.

If you add a feature request, describe in which case it will be useful.

**Comment by abergeron** [comment]
Can you post a verbatim copy of what appears in the terminal?

**Comment by abergeron** [comment]
Also, what is the content of `%PYTHONPATH%'?

**Comment by alfredaita** [comment]
when I:   import theano I get the following runtime error:
 You have the theano directory in your Python path. This do not work in Python 3.

sys.path  produces:


[" "
C:\users\alfre\anaconda3\Scripts
C:\users\alfre\anaconda3\python36.zip
C:\users\alfre\anaconda3\DLLs
C:\users\alfre\anaconda3\lib
C:\users\alfre\anaconda3
C:\users\alfre\anaconda3\lib\site-packages
C:\users\alfre\anaconda3\lib\site-packages\Sphinx-1.5.6-py3.6.egg
C:\users\alfre\anaconda3\lib\site-packages\theano
C:\users\alfre\anaconda3\lib\site-packages\pip-9.0.1-py3.6.egg
C:\users\alfre\anaconda3\lib\site-packages\win32
C:\users\alfre\anaconda3\lib\site-packages\win32\lib
C:\users\alfre\anaconda3\lib\site-packages\Pythonwin
C:\users\alfre\anaconda3\lib\site-packages\IPython\extensions
C:\Users\alfre\.ipython]

if I issue the following commands I can import theano
import sys
y = sys.path[8]
sys.path.remove(y)
import theano

**Comment by abergeron** [comment]
So the problem is exactly what it says.  You just need to figure out why python is putting the Theano directory in sys.path.  The most likely culprit is `%PYTHONPATH%`, but there are others.

Here is the documentation about how sys.path is filled on windows:
https://docs.python.org/3/using/windows.html#finding-modules
