### ISSUE TITLE
Wrong MKL lib name on Windows

### ISSUE THREAD

**Issue by david-leon** [Theano/Theano#6599]
Yesterday I installed pytorch 0.4.0 which broke Theano installation (numpy upgraded to 1.14.2), so I have to reinstall Theano. I noticed in the documentation Windows installation instructions have changed, so I followed exactly the steps described in http://deeplearning.net/software/theano/install_windows.html. However, when compiling functions, theano prompted:
```
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```
I traced back and found in `theano/configdefaults.py`, from line 1403 to 1407, wrong MKL lib name is set to `mkl_gnu_thread` which should be `mkl_intel_thread` instead.

The version of `mkl` package installed during the installation of theano is `1.1.2`. `mkl.get_version_string()` returns `Intel(R) Math Kernel Library Version 2018.0.2 Product Build 20180127 for Intel(R) 64 architecture applications`

By the  way, the g++.exe comes along with `m2w64-toolchain` packages doesn't work, I've to change to `Anaconda3\pkgs\mingw-4.7-1\MinGW\bin\g++.exe` which runs well.

Windows 10 64bit and python 3.5

**Comment by abergeron** [comment]
Can you try with: https://github.com/Theano/Theano/pull/6605

**Comment by nouiz** [comment]
We merged the fix. Can you try with the master of Theano? Having a confirmation would be great.

thanks
