### ISSUE TITLE
Issue running simultaneous scripts in Theano 1.0.1

### ISSUE THREAD

**Issue by ivan-marroquin** [Theano/Theano#6601]
Hi all,

I have a windows machine and installed conda 4.3 with Python 3.6.1 

Here is the content of the .theanorc file:
[global]
floatX = float32
device = cpu

[nvcc]
fastmath = True
flags = -LC:\Temp\Anaconda3\libs
compiler_bindir = "C:\Temp\Anaconda3\Library\mingw-w64\bin"

[blas]
ldflags = -LC:\Temp\Anaconda3\Library\bin -lmkl_rt

[cuda]
root = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

[dnn]
include_path = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
library_path = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
enabled = True

[lib]
cudnn = 1.0

When I was  using Theano 0.9.0 and be able to simultaneously run three scripts, I used the following header:
import itertools
import numpy as np
from sklearn import metrics, preprocessing
import matplotlib.pyplot as plt
import time
import os

os.environ["THEANO_FLAGS"]= "base_compiledir=\Model_1"  --> for the other two scripts, I used "Model_2" and "Model_3" folders

from functools import partial
from hyperopt import hp, Trials, fmin, tpe, STATUS_OK
from neupy import algorithms, layers, init#, environment, plots
from neupy.exceptions import StopTraining
import random
import pandas as pd
import theano

As expected, Theano created three subfolders to store the necessary files to properly run.

Now, I updated to Theano 1.0.1. When I tried to run a single script, I get the following error:
Exception: ('The following error happened while compiling the node', InplaceDimShuffle{x,0}(layer:tanh-1/bias), '\n', 'Compilation failed (return status=1): C:/Temp/Anaconda3/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot open output file C:\\Users\\IMarroquin\\Documents\\My_Python_Scripts\\MLP\\SEG_contest\\Independent_Scripts\\Model_1\\compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineI
ntel-3.6.1-64\\tmpyllht2ax\\m885ff006a95d626dac547a7bdfdb471bbf058622ece2b4435e4
2316c4012ea56.pyd: No such file or directory\r. collect2.exe: error: ld returned 1 exit status\r. ', '[InplaceDimShuffle{x,0}(layer:tanh-1/bias)]')

So, I went to check the content of the folder "Model_1" and noticed this:
a) the sub-folder "compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_63_Stepping_2_GenuineI
ntel-3.6.1-64" got created
b) the sub-folder only contains a file (__init__) and another folder (lazylinker_ext) 
c) the sub-folder "tmpyllht2ax" is missing, which is the cause of the error

Then, when I commented out these lines from the script header: 
import os
os.environ["THEANO_FLAGS"]= "base_compiledir=\Model_1"

The script used the default path in Windows. The compilation worked fine and the script properly run.

What changed in version 1.0.1? Is there a way to fix this problem?

Many thanks,
Ivan

**Comment by lamblin** [comment]
Discussion is ongoing here: https://groups.google.com/d/topic/theano-users/UoxCRxNdOwo/discussion

**Comment by abergeron** [comment]
Apparently this was fixed by using sub-directories of the default compiledir for each script.

**Comment by ivan-marroquin** [comment]
Thanks to Pascal, I used different sub-directories inside the default path.

with this information, i did this tests:
os.environ["THEANO_FLAGS"]= r"base_compiledir=C:\\Temp" --> worked

os.environ["THEANO_FLAGS"]= r"base_compiledir=C:\\Users\\IMarroquin\\Documents\\My_Python_Scripts\\MLP\\Well_8_to_five_wells\\"   --> worked

os.environ["THEANO_FLAGS"]= r"base_compiledir=C:\\Users\\IMarroquin\\Documents\\My_Python_Scripts\\MLP\\Well_8_to_five_wells\\Independent_Scripts"   --> keep in failing

I will have my IT colleague to check why the compilation fails in this  particular path. I can write and delete files/folders without issues. In case there is not a problem from windows perspective. Is it possible that I reached a maximum of characters for "base_compiledir" option?

many thanks for all,
Ivan

**Comment by nouiz** [comment]
Theano do not put any restriction on the length of base_compiledir. The OS
could, but I do not see a limit here that I understand.

I pasted this code in Python and I got an error. The failing string have
the first \ as an unicode charactere. Can you delete it and write it again?

Otherwise, can you test:
C:\Users\IMarroquin\Documents\My_Python_Scripts\MLP\Well_8_to_five_wells\IS

it would be shorter and maybe this bypass an OS limitation.

**Comment by ivan-marroquin** [comment]
thanks for the suggestion:

I tried: 
os.environ["THEANO_FLAGS"]= r"base_compiledir=C:\\Users\\IMarroquin\\Documents\\My_Python_Scripts\\MLP\\Well_8_to_five_wells\\Independent_Scripts"

and it didn't work

then, I tried the path as per your suggestion:
os.environ["THEANO_FLAGS"]= r"base_compiledir=C:\\Users\\IMarroquin\\Documents\\My_Python_Scripts\\MLP\\Well_8_to_five_wells\\IS"

and it work fine!

it makes me wonder, how windows created the sub-directory "Independent_Scripts"

I will check more at the end of next week. 

Thanks for all,

**Comment by abergeron** [comment]
This may be an issue of path length, since the limit on Windows with some APIs is really short (like 255 characters).

**Comment by nouiz** [comment]
As an explanation was provided and we won't modify Theano to work around Windows limitation, I'll close this issue. If someone make a PR for this, I'll merge it. I think the PR would be to give a better error message.
