### ISSUE TITLE
Theano.sum bug (theano 1.0.2)

### ISSUE THREAD

**Issue by jc-Rosichini** [Theano/Theano#6612]
**A quick one: T.sum doesn't appear to perform size reduction anylonger**

**Here is a basic test:**

import theano
import theano.tensor as T
import numpy as np

import lasagne
from lasagne.layers import ExpressionLayer

import pygpu
print('theano: \t',theano.__version__)
print('numpy:  \t',np.__version__)
print('pygpu:  \t',pygpu.__version__)
print('lasagne:\t',lasagne.__version__)
print('floatX: \t',theano.config.floatX)
print()

input_var  = T.tensor4('imaIn',  dtype='float32')
target_var = T.tensor4('imaOut', dtype='float32')

network = lasagne.layers.InputLayer((1, 3, 220, 240), input_var)
**test = ExpressionLayer(network, lambda X: T.sum(X, axis=2))** 
print('*** test.output_shape after T.sum ',test.output_shape)`

**Here is the outcome:**
python test_Tsum.py

Using cuDNN version 7004 on context None
Mapped name None to device cuda0: GeForce GTX 980M (0000:01:00.0)
theano:          1.0.2
numpy:           1.14.0
pygpu:           0.7.5
lasagne:         0.2.dev1
floatX:          float32

***** test.output_shape after T.sum  (1, 3, 220, 240)    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!**

**Comment by nouiz** [comment]
Theano is fine. The problem is in your usage of ExpressionLayer. By default, it expect the output to be of the same shape as the input. To show that Theano is fine:
```
import theano
x=theano.tensor.tensor4()
print(x.sum(axis=2).type)
# it print: TensorType(float64, 3D)
```

You can try to call ExpressionLayer like this:

    ExpressionLayer(network, lambda X: T.sum(X, axis=2), output_shape=lambda x: (x[0],x[1],x[3]))

If this do not answer your questions, you should ask in the Lasagne community your question.
