### ISSUE TITLE
Theano 1.0.2 cannot work for python 3.6 with cudnn enabled on windows

### ISSUE THREAD

**Issue by jingweimo** [Theano/Theano#6614]
I have anaconda 2 with python 2.7 and theano1.02 and cudnn enabled. Theano works fine! But when I create a python 3.6.5 environment for theano, it only works with the flag of cudnn set false. Otherwise it gives the error:
```
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\YL\Anaconda2\envs\py36\lib\site-packages\theano\gpuarray\__init__.py", line 227, in <module>
    use(config.device)
  File "C:\Users\YL\Anaconda2\envs\py36\lib\site-packages\theano\gpuarray\__init__.py", line 214, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Users\YL\Anaconda2\envs\py36\lib\site-packages\theano\gpuarray\__init__.py", line 121, in init_dev
    dnn.dnn_available.msg)

RuntimeError: You enabled cuDNN, but we aren't able to use it: cannot compile with cuDNN. We got this error:
b'In file included from C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/driver_types.h:53:0,\r\n                
 from C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/cudnn.h:63,\r\n                 
from C:\\Users\\Yuzhen\\AppData\\Local\\Temp\\try_flags_4e87ny_h.c:4:\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include/host_defines.h:84:0: 
warning: "__cdecl" redefined\r\n #define __cdecl\r\n ^\r\n<built-in>: 
note: this is the location of the previous definition\r\nC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64/cudnn.lib: error adding symbols: File in wrong format\r\ncollect2.exe: error: ld returned 1 exit status\r\n'
```

I also note a similar issue reported here (https://github.com/Theano/Theano/issues/5917)
I also remember I once successfully used theano in python3.5 environment with cudnn enabled. 
The official website also states the supported python<3.6 (http://deeplearning.net/software/theano/install_windows.html)

Summary of the software environment:
wind10 + vs2015
cuda8.0 + cudnn5.1 (works fine for theano in python2.7)
anaconda2 with python3.6 environment
theano 1.02
pygpu 0.76

**Comment by abergeron** [comment]
I've updated the title to better reflect the problem.  This is only a problem on windows.  I'm not sure how to fix it and I don't have any windows machine with an nVidia GPU, but maybe someone else does.

**Comment by jingweimo** [comment]
I just confirm that Theano works for Python3.6.5 with cudnn enabled. Only one optional package `m2w64-toolchain` is actually needed for resolving the issue I described above!!

**Comment by jingweimo** [comment]
Leave a comment
