### ISSUE TITLE
Please update or remove documentation on Python memory management

### ISSUE THREAD

**Issue by mjpieters** [Theano/Theano#6619]
The [Python Memory Management article](http://deeplearning.net/software/theano/tutorial/python-memory-management.html) is drawing a number of incorrect conclusions, it incorrectly claims the Python memory manager doesn't release memory, and the data produced by the memory profiler is being misinterpreted. The advice given is misleading.

Can it please be removed altogether, or at the very least be fixed to remove the misconceptions?

## Claims that Python doesn't release memory

The page claims that memory isn't released again:

> There are some internal details on how Python manages those lists into blocks, pools, and “arena”: a number of block forms a pool, pools are gathered into arena, etc., but they’re not very relevant to the point we want to make (if you really want to know, read Evan Jones’ ideas on how to improve Python’s memory allocation). The important point is that those lists never shrink.

This was perhaps true for Python versions before to Python 2.5. Evan Jones [tried to give that feedback on the original blog post](https://hbfs.wordpress.com/2013/01/08/python-memory-management-part-ii/#comment-3492) but the conversation there seemed to bog down on red herrings. If you run a modern Python version you'll readily see the process memory footprint shrink again when deleting large chunks of Python objects; or you can set `PYTHONMALLOCSTATS="1"` to be given exhaustive debug output on exactly how many arenas are allocated and reclaimed again.

## memory_profiler is inaccurate and the results are being misinterpreted

By default, memory usage is measured with `psutil`, which can't distinguish between bulk memory block allocations and per-object memory requirements. Python's process memory size is a function of not only the Python memory manager, but also of the *operating system's* strategies for allocating additional memory to processes. From this inaccurate feedback the article then draws incorrect conclusions. It is also rather outdated, being written with Python 2.7 as an example, a Python version that is going to [hit its EOL in 18 months time](https://pythonclock.org/).

Moveover, the article incorrectly infers that `copy.deepcopy()` would copy integers:

> [copy.deepcopy](url) copies both lists, which allocates again ~50 MB (I am not sure where the additional overhead of 50 MB - 31 MB = 19 MB comes from)

 In reality, `deepcopy()` only copies mutable objects, and the copied list shares the same integer objects. The actual difference in memory is about 8MiB; the rest is an overallocation of memory anticipating future needs; the overallocation size is a function of a lot of different factors and should not be taken as linear growth in direct response to objects being created.. *Most of the process memory added in the article is not actually in use yet*, it has been allocated to satisfy anticipated additional demand in the future.

Using [`tracemalloc`](https://docs.python.org/3/library/tracemalloc.html) backend you'd get far more accurate results on why and by how much memory use changes; this is part of the standard library since Python 3.4. The `memory-profile-me.py` script, using 3.6 and the tracemalloc backend for `memory_profiler` outputs:

```sh
$ python3.6 -m memory_profiler --backend tracemalloc memtest.py
Filename: memtest.py

Line #    Mem usage    Increment   Line Contents
================================================
     4    0.001 MiB    0.001 MiB   @profile
     5                             def function():
     6   35.280 MiB   35.279 MiB       x = list(range(1000000))  # allocate a big list
     7   35.281 MiB    0.001 MiB       y = copy.deepcopy(x)
     8   26.698 MiB   -8.583 MiB       del x
     9   26.698 MiB    0.000 MiB       return y
```

showing that `copy.deepcopy()` *doesn't copy immutable objects*, and the actual change in memory for the deepcopy line is close to zero as existing arena allocations can store the list object. Similar output is produced when using a Python 2.7 build [patched to support tracemalloc](http://pytracemalloc.readthedocs.io/install.html):

```sh
$ python2.7tracemalloc -m memory_profiler --backend tracemalloc memtest.py
Filename: memtest.py

Line #    Mem usage    Increment   Line Contents
================================================
     4    0.099 MiB    0.099 MiB   @profile
     5                             def function():
     6   31.734 MiB   31.635 MiB       x = list(range(1000000))  # allocate a big list
     7   31.726 MiB   -0.008 MiB       y = copy.deepcopy(x)
     8   23.143 MiB   -8.583 MiB       del x
     9   23.141 MiB   -0.002 MiB       return y
```

Almost paradoxically, memory use actually shrunk a little. That's because creating more objects can actually lead to more arena consolidation. Memory use is only indirectly connected to object creation.

However, even without using `tracemalloc` the memory increases the article demonstrates in Python 2.7 are completely absent in Python 3.6, where the standard `psutil`-based memory measurements show an expected minimal increase:

```sh
$ python3.6 -m memory_profiler memtest.py
Filename: memtest.py

Line #    Mem usage    Increment   Line Contents
================================================
     4   34.262 MiB   34.262 MiB   @profile
     5                             def function():
     6   72.844 MiB   38.582 MiB       x = list(range(1000000))  # allocate a big list
     7   81.043 MiB    8.199 MiB       y = copy.deepcopy(x)
     8   81.043 MiB    0.000 MiB       del x
     9   81.043 MiB    0.000 MiB       return y
```

At this point it is important to note that I am running these tests on a Macbook Pro, on MacOS 10.13. On a different OS the results may well be different because how much memory the `malloc` implementation gives to a process differs from OS to OS. You should always take this into account when using a memory profiler.

The size error is most visible in the pickle test. `pickle.dump` streams to a file, very efficiently, and doesn't need to make any copies of anything, so the interpretation there is extremely off-base. Pickle in 2.7 *does* use *some* memory proportional to the amount of data saved, but not the amount that `memory_profiler` shows. This is again the result of over-allocation of additional space for future growth.

 I've adapted the test there to use `tracemalloc` directly to make the test run a lot faster; `memory_profiler` is *extremely* slow due to its filter-snapshot-on-every-`sys.settrace()`-call approach running a lot of Python code for each interpreter step; the following avoids using `sys.settrace()` altogether by using explicit calls to measure memory:

```python
from __future__ import print_function
import tracemalloc
import pickle
import random
from string import ascii_uppercase

try:
    # Python 2 compatibility
    range = xrange
    try:
        # use the optimised version, in Py2 this requires an explicit import
        import cPickle as pickle
    except ImportError:
        pass
except NameError:
    pass


last = None
def display_memory_change(msg):
    global last
    snap = tracemalloc.take_snapshot()
    statdiff, last = snap.compare_to(last, 'filename', True), snap
    tot = sum(s.size for s in statdiff)
    change = sum(s.size_diff for s in statdiff)
    print('{:>20} (Tot: {:6.1f} MiB, Inc: {:6.1f} MiB)'.format(
        msg, tot / 2 ** 20, change / 2 ** 20))


def random_string(_c=random.choice, _l=ascii_uppercase):
    return "".join([_c(_l) for _ in range(20)])


def create_file():
    # use locals for faster looping
    rfloat, rstring, rrange = random.random, random_string, random.randrange
    x = [(rfloat(), rstring(), rrange(2 ** 64)) for _ in range(1000000)]
    display_memory_change('Data created')

    pickle.dump(x, open('machin.pkl', 'wb'))
    display_memory_change('Pickle dumped')


def load_file():
    y = pickle.load(open('machin.pkl', 'rb'))
    display_memory_change('Pickle loaded')
    return y


if __name__=="__main__":
    import sys
    print('Python version info:', sys.version)
    tracemalloc.start()
    last = tracemalloc.take_snapshot()
    display_memory_change('Baseline')
    if 'load' not in sys.argv:
        create_file()
    else:
        load_file()
```

Running this shows that `pickle` barely adds *any* additional memory pressure, and only on 2.7:

```sh
$ python3.6 test-pickle.py
Python version info: 3.6.5 (default, May  7 2018, 16:43:32)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
            Baseline (Tot:    0.0 MiB, Inc:    0.0 MiB)
        Data created (Tot:  200.0 MiB, Inc:  200.0 MiB)
       Pickle dumped (Tot:  246.0 MiB, Inc:   46.0 MiB)
$ python3.6 test-pickle.py load
Python version info: 3.6.5 (default, May  7 2018, 16:43:32)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
            Baseline (Tot:    0.0 MiB, Inc:    0.0 MiB)
       Pickle loaded (Tot:  199.6 MiB, Inc:  199.6 MiB)
```

and on the 2.7 tracemalloc build:

```sh
$ python2.7tracemalloc test-pickle.py
Python version info: 2.7.13 (default, Jun 25 2018, 22:08:02)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
            Baseline (Tot:    0.0 MiB, Inc:    0.0 MiB)
        Data created (Tot:  200.0 MiB, Inc:  200.0 MiB)
       Pickle dumped (Tot:  246.0 MiB, Inc:   46.0 MiB)
$ python2.7tracemalloc test-pickle.py load
Python version info: 2.7.13 (default, Jun 25 2018, 22:08:02)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
            Baseline (Tot:    0.0 MiB, Inc:    0.0 MiB)
       Pickle loaded (Tot:  199.0 MiB, Inc:  199.0 MiB)
```

Run `create_file()` multiple times and the memory changes disappear entirely, showing that the memory change as `pickle.dump()` runs is most likely due to arena overallocation.

So while Python's memory model is indeed different from that of C, the article is making some very wrong claims about what that model actually does. Because it is part of a major OSS project documentation, it carries more authority than it currently deserves. Please fix this.

**Comment by nouiz** [comment]
As Python memory management changed heavily, I agree we should not keep too old information. We won't update it ourself. I suppose you won't. I would like to keep a page that point to a good source of information about that. Do you know such a link? If not, we will just delete it (or remove the information and tell why we removed it)

**Comment by mjpieters** [comment]
Thanks for removing that post! Sorry, I don't have a recommendation for a better page. Memory profiling is, unfortunately, a misunderstood topic. Perhaps I'll have to put up a decent page on my own site.
