### ISSUE TITLE
Model won't train on GPU: "ValueError: images and kernel must have the same stack size"

### ISSUE THREAD

**Issue by david-leon** [Theano/Theano#6622]
I've built the [Shuffle-Seg model](https://github.com/david-leon/Dandelion/blob/master/dandelion/model/shufflenet.py) and tested it on CPU. But when run the model training on GPU, value error is raised: `images and kernel must have the same stack size`.

The problem can be reproduced with a test script: https://github.com/david-leon/Dandelion/blob/master/test/shuffleseg_train_debug.py. My environment is: Theano up-to-date, python 3.5 & 3.6, Ubuntu 14.04 & 16.04, CUDA 8.0 & CUDA9.1

To run the script, you'll need the [Dandelion](https://github.com/david-leon/Dandelion) package installed.

I've discovered that if [line 92](https://github.com/david-leon/Dandelion/blob/712510a423801913d5a66bc918df406cc7248077/dandelion/model/shufflenet.py#L92) changed to `self.conv1 = Conv2D(in_channels=in_channels, out_channels=self.inner_channels, kernel_size=1, pad=border_mode, num_groups=1)` problem disappeared, and whenever `num_groups` is set to value >1, the above value error will be raised again.

**Comment by abergeron** [comment]
I get this error when I try to run the example script with python 2.7: 
```
Traceback (most recent call last):
  File "shuffleseg_train_debug.py", line 16, in <module>
    from dandelion.module import *
  File "/u/bergearn/.local/lib/python2.7/site-packages/dandelion/__init__.py", line 1, in <module>
    from . import module
  File "/u/bergearn/.local/lib/python2.7/site-packages/dandelion/module.py", line 832
    return (seq_h, *final_state)
                   ^
SyntaxError: invalid syntax
```
You might want to mark the package as incompatible with python 2.

Apart from that, #6624 should fix your problem.

**Comment by david-leon** [comment]
Fix confirmed.
