### ISSUE TITLE
Error running PyMC3 Model

### ISSUE THREAD

**Issue by ben-mhamed** [Theano/Theano#6623]
I'm trying to run a Bayesian Model using PyMC3 and i get this error that i don't understand.
I have updated Theano, Scipy and PyMC3 but i still get the same Error. There is a long error output but i just selected this first part that seems to me meaningful.
PyMC3 version : 3.4.1
Theano version : 1.0.2

`WARNING (theano.gof.compilelock): Overriding existing lock by dead process '4077' (I am process '5557')
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.`

**Comment by abergeron** [comment]
All of those are warnings, not errors, so you might want to include a little more if you actually get an error.

The blas warning might make some computations much slower if you use the CPU, but I would have to know which platform/numpy/blas you have to propose a solution.

**Comment by ben-mhamed** [comment]
Here is the results of np.__config__.show()
I forget to mention that i'm using Ubuntu 18.04

`blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]`

**Comment by ben-mhamed** [comment]
The whole error i got is this:
`You can find the C code in this temporary file: /tmp/theano_compilation_error_2xhkeeph
library inux-gnu-ld: is not found.
library inux-gnu-ld: is not found.
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-10-dcb60f29497b> in <module>()
      9 
     10     # Perform Markov Chain Monte Carlo sampling
---> 11     normal_trace = pm.sample(draws=1000, chains = 1, tune = 500, njobs=-1)

~/.local/lib/python3.6/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    393             start_, step = init_nuts(init=init, chains=chains, n_init=n_init,
    394                                      model=model, random_seed=random_seed,
--> 395                                      progressbar=progressbar, **args)
    396             if start is None:
    397                 start = start_

~/.local/lib/python3.6/site-packages/pymc3/sampling.py in init_nuts(init, chains, n_init, model, random_seed, progressbar, **kwargs)
   1386             'Unknown initializer: {}.'.format(init))
   1387 
-> 1388     step = pm.NUTS(potential=potential, model=model, **kwargs)
   1389 
   1390     return start, step

~/.local/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py in __init__(self, vars, max_treedepth, early_max_treedepth, **kwargs)
    150         `pm.sample` to the desired number of tuning steps.
    151         """
--> 152         super(NUTS, self).__init__(vars, **kwargs)
    153 
    154         self.max_treedepth = max_treedepth

~/.local/lib/python3.6/site-packages/pymc3/step_methods/hmc/base_hmc.py in __init__(self, vars, scaling, step_scale, is_cov, model, blocked, potential, integrator, dtype, Emax, target_accept, gamma, k, t0, adapt_step_size, step_rand, **theano_kwargs)
     61 
     62         super(BaseHMC, self).__init__(vars, blocked=blocked, model=model,
---> 63                                       dtype=dtype, **theano_kwargs)
     64 
     65         self.adapt_step_size = adapt_step_size

~/.local/lib/python3.6/site-packages/pymc3/step_methods/arraystep.py in __init__(self, vars, model, blocked, dtype, **theano_kwargs)
    213 
    214         self._logp_dlogp_func = model.logp_dlogp_function(
--> 215             vars, dtype=dtype, **theano_kwargs)
    216 
    217     def step(self, point):

~/.local/lib/python3.6/site-packages/pymc3/model.py in logp_dlogp_function(self, grad_vars, **kwargs)
    706         varnames = [var.name for var in grad_vars]
    707         extra_vars = [var for var in self.free_RVs if var.name not in varnames]
--> 708         return ValueGradFunction(self.logpt, grad_vars, extra_vars, **kwargs)
    709 
    710     @property

~/.local/lib/python3.6/site-packages/pymc3/model.py in __init__(self, cost, grad_vars, extra_vars, dtype, casting, **kwargs)
    445 
    446         self._theano_function = theano.function(
--> 447             inputs, [self._cost_joined, grad], givens=givens, **kwargs)
    448 
    449     def set_extra_values(self, extra_vars):

~/.local/lib/python3.6/site-packages/theano/compile/function.py in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    315                    on_unused_input=on_unused_input,
    316                    profile=profile,
--> 317                    output_keys=output_keys)
    318     return fn

~/.local/lib/python3.6/site-packages/theano/compile/pfunc.py in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    484                          accept_inplace=accept_inplace, name=name,
    485                          profile=profile, on_unused_input=on_unused_input,
--> 486                          output_keys=output_keys)
    487 
    488 

~/.local/lib/python3.6/site-packages/theano/compile/function_module.py in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1839                   name=name)
   1840         with theano.change_flags(compute_test_value="off"):
-> 1841             fn = m.create(defaults)
   1842     finally:
   1843         t2 = time.time()

~/.local/lib/python3.6/site-packages/theano/compile/function_module.py in create(self, input_storage, trustme, storage_map)
   1713             theano.config.traceback.limit = theano.config.traceback.compile_limit
   1714             _fn, _i, _o = self.linker.make_thunk(
-> 1715                 input_storage=input_storage_lists, storage_map=storage_map)
   1716         finally:
   1717             theano.config.traceback.limit = limit_orig

~/.local/lib/python3.6/site-packages/theano/gof/link.py in make_thunk(self, input_storage, output_storage, storage_map)
    697         return self.make_all(input_storage=input_storage,
    698                              output_storage=output_storage,
--> 699                              storage_map=storage_map)[:3]
    700 
    701     def make_all(self, input_storage, output_storage):

~/.local/lib/python3.6/site-packages/theano/gof/vm.py in make_all(self, profiler, input_storage, output_storage, storage_map)
   1089                                                  compute_map,
   1090                                                  [],
-> 1091                                                  impl=impl))
   1092                 linker_make_thunk_time[node] = time.time() - thunk_start
   1093                 if not hasattr(thunks[-1], 'lazy'):

~/.local/lib/python3.6/site-packages/theano/gof/op.py in make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    953             try:
    954                 return self.make_c_thunk(node, storage_map, compute_map,
--> 955                                          no_recycling)
    956             except (NotImplementedError, utils.MethodNotDefined):
    957                 # We requested the c code, so don't catch the error.

~/.local/lib/python3.6/site-packages/theano/gof/op.py in make_c_thunk(self, node, storage_map, compute_map, no_recycling)
    856         _logger.debug('Trying CLinker.make_thunk')
    857         outputs = cl.make_thunk(input_storage=node_input_storage,
--> 858                                 output_storage=node_output_storage)
    859         thunk, node_input_filters, node_output_filters = outputs
    860 

~/.local/lib/python3.6/site-packages/theano/gof/cc.py in make_thunk(self, input_storage, output_storage, storage_map, keep_lock)
   1215         cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
   1216             input_storage, output_storage, storage_map,
-> 1217             keep_lock=keep_lock)
   1218 
   1219         res = _CThunk(cthunk, init_tasks, tasks, error_storage, module)

~/.local/lib/python3.6/site-packages/theano/gof/cc.py in __compile__(self, input_storage, output_storage, storage_map, keep_lock)
   1155                                             output_storage,
   1156                                             storage_map,
-> 1157                                             keep_lock=keep_lock)
   1158         return (thunk,
   1159                 module,

~/.local/lib/python3.6/site-packages/theano/gof/cc.py in cthunk_factory(self, error_storage, in_storage, out_storage, storage_map, keep_lock)
   1618                 node.op.prepare_node(node, storage_map, None, 'c')
   1619             module = get_module_cache().module_from_key(
-> 1620                 key=key, lnk=self, keep_lock=keep_lock)
   1621 
   1622         vars = self.inputs + self.outputs + self.orphans

~/.local/lib/python3.6/site-packages/theano/gof/cmodule.py in module_from_key(self, key, lnk, keep_lock)
   1179             try:
   1180                 location = dlimport_workdir(self.dirname)
-> 1181                 module = lnk.compile_cmodule(location)
   1182                 name = module.__file__
   1183                 assert name.startswith(location)

~/.local/lib/python3.6/site-packages/theano/gof/cc.py in compile_cmodule(self, location)
   1521                 lib_dirs=self.lib_dirs(),
   1522                 libs=libs,
-> 1523                 preargs=preargs)
   1524         except Exception as e:
   1525             e.args += (str(self.fgraph),)

~/.local/lib/python3.6/site-packages/theano/gof/cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2386             # difficult to read.
   2387             raise Exception('Compilation failed (return status=%s): %s' %
-> 2388                             (status, compile_stderr.replace('\n', '. ')))
   2389         elif config.cmodule.compilation_warning and compile_stderr:
   2390             # Print errors just below the command line.

Exception: ('The following error happened while compiling the node', CGemv{inplace}(AllocEmpty{dtype='float64'}.0, TensorConstant{1.0}, TensorConstant{[[1.000000..0000e+00]]}, MakeVector{dtype='float64'}.0, TensorConstant{0.0}), '\n', "Compilation failed (return status=1): /usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libpython3.6m.a(exceptions.o): relocation R_X86_64_PC32 against symbol `PyExc_BaseException' can not be used when making a shared object; recompile with -fPIC. /usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value. collect2: error: ld returned 1 exit status. ", '[CGemv{inplace}(<TensorType(float64, vector)>, TensorConstant{1.0}, TensorConstant{[[1.000000..0000e+00]]}, <TensorType(float64, vector)>, TensorConstant{0.0})]')`

**Comment by abergeron** [comment]
> /usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libpython3.6m.a

You are using a custom build of python and it probably wasn't built with the dynamic library for python.  That isn't supported.  I recommend to install python with either anaconda or the official ubuntu packages.

If you really must use this custom python, make sure to rebuild it with the dynamic library and also make sure to mention that you are using that in future support requests.

**Comment by ben-mhamed** [comment]
I have reinstalled everything with conda. It's working just fine. Thanks
