### ISSUE TITLE
grad of `images2neibs` not implemented

### ISSUE THREAD

**Issue by david-leon** [Theano/Theano#6630]
I'm trying to implement counterpart of Caffe's [`im2col()`](caffe.berkeleyvision.org/tutorial/layers/im2col.html), and I find `images2neibs()` in Theano. The following is my implementation:
```python
def im2col(x, nb_size=(3,3), border_mode='half'):
    """
    Function im2col allows to apply a sliding window operation to a 4D tensor, based on theano's images2neibs() and corresponding to Caffe's im2col()
    :todo: support any nb_step
    :param x: must be 4D tensor with shape (B, C, H, W)
    :param nb_size: neighbour size (h, w), i.e., the sliding window size, 2D vector. Only odd shapes are supported.
    :param border_mode: 'half' | 'wrap_centered' : on image border, whether pad by 0 or wrap image
    :return:
    """
    nb_step = (1, 1)
    B, C, H, W = x.shape
    x = images2neibs(x, neib_shape=nb_size, neib_step=nb_step, mode=border_mode) # (B*C*H*W, h*w)
    x = tensor.reshape(x, (B, C, H, W, -1))  # (B, C, H, W, h*w)
    return x
```
However when this `im2col()` integrated into a network, during back-propagation, exception is raised as `theano.gradient.NullTypeGradError: tensor.grad encountered a NaN. This variable is Null because the grad method for input 0 (Elemwise{add,no_inplace}.0) of the Images2Neibs{half} op is not implemented. 
`. It seems Theano's `images2neibs()` does not support gradient computation.

So, is this expected? Is there other way to implement Caffe's `im2col` equivalent with Theano?

**Comment by abergeron** [comment]
I can refer you to this: https://groups.google.com/forum/#!topic/theano-users/oirq0zyQ8Jo

But really this should be a question for the mailing list.

**Comment by david-leon** [comment]
@abergeron Sorry I don't get your point, the reference url is about forward computation, and still lead me to `theano.tensor.nnet.neighbours.images2neibs()`.  My question is Theano's implementation does not support gradient computation, which means I can't use it in a network for training.

**Comment by abergeron** [comment]
There is a portion about reimplementing this numpy version: https://stackoverflow.com/questions/10896841/find-a-3x3-sliding-window-over-an-image/10906015#10906015  in Theano with Scan.  This is probably the only way to get a version that you can get the gradient through.

**Comment by david-leon** [comment]
OK, I'll try implementing with scan(), and update this post with progress later.
