### ISSUE TITLE
debugprint() does not respect the "file" argument when passed numeric type

### ISSUE THREAD

**Issue by jlumpe** [Theano/Theano#6631]
The `theano.printing.debugprint` function accepts objects of numeric type as an argument, but does not take the `file` argument into account in this case:

```Python console
>>> from theano.printing import debugprint
>>> debugprint(1)
1
>>> result = debugprint(1, file='str')
1
>>> result
''
```

Here is the part of the function that is to blame, you can see it just calls `print` instead of writing to the file: https://github.com/Theano/Theano/blob/727477b5c3cfb4352f18b07ea4e4cb6df95cc254/theano/printing.py#L165-L166

**Comment by nouiz** [comment]
This was fixed in the master of Theano. Thanks for the report.
