### ISSUE TITLE
Problem with GpuContiguous on migrating into Theano 1

### ISSUE THREAD

**Issue by nobodykid** [Theano/Theano#6639]
Hello, I'm currently trying to migrate DCGAN code from [Alec Radford original code](https://github.com/Newmu/dcgan_code) to be compatible with Python 3 and Theano 1 (which my current env setting now)

When I tried to migrate `basic_ops` into `theano.gpuarray.basic_ops` I'm having problem with some of the members, such as `GpuContiguous` having error like
```
TypeError : object() takes no parameter
```
and others like
```
AttributeError : GpuContiguous doesn't have attribute shape
```

Can anyone help me with this migration?

**Comment by nouiz** [comment]
We don't have much time to support Theano anymore. But is you us the full
error message, maybe we will be able to help.

Le mer. 29 août 2018 03:24, Muhamad Iqbal <notifications@github.com> a
écrit :

**Comment by abergeron** [comment]
You probably replaced gpu_contiguous() with GpuContiguous().  You should use gpu_contiguous() with the new backend also, just from the new basic_ops module.

**Comment by nobodykid** [comment]
Tried to convert back from `GpuContiguous` to its original `gpu_contiguous`, now it raised a `ValueError`
```
Traceback (most recent call last):
  File "train_cond_dcgan.py", line 140, in <module>
    gX = gen(Z, Y, *gen_params)
  File "train_cond_dcgan.py", line 109, in gen
    h3 = relu(batchnorm(deconv(h2, w3, subsample=(2, 2), border_mode=(2, 2))))
  File "../lib/ops.py", line 95, in deconv
    img = gpu_contiguous(X)
  File "/home/riset/.conda/envs/iqbal_theano/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/riset/.conda/envs/iqbal_theano/lib/python2.7/site-packages/theano/gpuarray/basic_ops.py", line 1078, in make_node
    context_name=infer_context_name(input))
  File "/home/riset/.conda/envs/iqbal_theano/lib/python2.7/site-packages/theano/gpuarray/basic_ops.py", line 127, in infer_context_name
    raise ValueError("Could not infer context from inputs")
ValueError: Could not infer context from inputs
```

**Comment by abergeron** [comment]
Are you running with `device=cuda0` or something similar?

**Comment by abergeron** [comment]
Also, you can refer to this migration guide: https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

**Comment by nobodykid** [comment]
No, I didn't set any flags to run the code before. After you mentioned that, I tried to run it again with `device=cuda0` flag, and it returns different error

**Comment by abergeron** [comment]
I would encourage you to convert the convolution code to the CPU interface.  This will be moved automatically to GPU/cuDNN when required.

**Comment by abergeron** [comment]
In fact you can use http://deeplearning.net/software/theano/library/tensor/nnet/conv.html#theano.tensor.nnet.abstract_conv.conv2d_grad_wrt_inputs to implement the deconv function and get rid of all the gpu backend-specific code.

**Comment by nobodykid** [comment]
Do you have sample codes using this API?

**Comment by nobodykid** [comment]
I tried to change the whole body of `deconv` function using `conv2d_grad_wrt_inputs` as you suggested, such like this

```
def deconv(X, w, subsample=(1, 1), border_mode=(0, 0), conv_mode='conv'):

    d_img = abstract_conv.conv2d_grad_wrt_inputs(
        output_grad=X, filters=w, 
        input_shape=(X.shape[0], w.shape[1], X.shape[2]*subsample[0], X.shape[3]*subsample[1]),
        filter_shape=w.shape, 
        border_mode=border_mode,
        subsample=subsample)

    return d_img
```
But it raised `AssertionError` from the `input_shape` I gave as parameter. I took the `input_shape` from the original code, where they used it within `GpuAllocEmpty` to allocate for deconv result

```
desc = GpuDnnConvDesc(border_mode=border_mode, subsample=subsample, conv_mode=conv_mode)(GpuAllocEmpty(img.shape[0], kerns.shape[1], img.shape[2]*subsample[0], img.shape[3]*subsample[1]).shape, kerns.shape)
out = GpuAllocEmpty(img.shape[0], kerns.shape[1], img.shape[2]*subsample[0], img.shape[3]*subsample[1])
d_img = GpuDnnConvGradI()(kerns, img, out, desc)
```

**Comment by abergeron** [comment]
abstract_conv takes a constant shape, if you know it.  If all you have is the symbolic shape (as in this case) just don't pass those parameters and it should work.

**Comment by nobodykid** [comment]
Isn't `input_shape` mandatory? The [documentation](http://deeplearning.net/software/theano/library/tensor/nnet/conv.html#theano.tensor.nnet.abstract_conv.conv2d_grad_wrt_inputs) mentioned it's "not optional"

**Comment by abergeron** [comment]
Yes, you're right.  I was thinking of the regular convolution functions.  I don't see anything wrong with the code you posted.

Can you either post the full error or runnable code that uses this function so that I can see the context?

**Comment by nobodykid** [comment]
I'll try to fork the code into my repo and modified it. I'll give you the link when it's up

**Comment by nobodykid** [comment]
Sorry for the late, I've forked the code and modified it based on the Theano migration guide in [here](https://github.com/nobodykid/dcgan_code)

**Comment by nouiz** [comment]
What you pass as input shape isn,t good. The first 2 dims must be constant or None.

I created a PR to help test this case: https://github.com/Theano/Theano/pull/6652
