### ISSUE TITLE
Could not initialize pygpu, support disabled (CUDA v.10)

### ISSUE THREAD

**Issue by SauROnmiKE** [Theano/Theano#6646]
Greetings,

I get the well-known error that pygpu could not be initialized. I'm a complete newbie in Theano and Keras and I'm trying to run some tests from tutorials to use my GPU.

Just importing Theano produces the problem: "GpuArrayException: Could not load "nvrtc64_70.dll"
I've read a lot of other similar issues but no method worked, as they're all very old and use earlier versions of CUDA. 

I'm using a GTX 1070Ti and downloaded the latest CUDA Toolkit version 10. 
Of course, version 10 has the file nvrtc64_100.dll and not nvrtc64_70.dll. I set GPUARRAY_CUDA_VERSION  to 100 which of course didn't resolve anything.

**Versions**
Python: 2.7.15
Miniconda 3
Theano: 1.0.2
Keras: 2.2.2
pygpu: 0.7.5
libgpuarray: 0.7.5
CUDA: 10.0

Do I have to downgrade to an earlier version of CUDA? Or maybe use Python3? Please let me know if any more details are needed.

**Comment by nouiz** [comment]
We didn't try with cuda 10. Maybe @abergeron will be able to fix that, but
probably not this week or next week.
So the short term solution would be to downgrade cuda.

**Comment by SauROnmiKE** [comment]
I see, cuda 9 it is then! I'll let you know if I run into some other problem. Thanks for the super-fast answer.

**Comment by SauROnmiKE** [comment]
I guess I must also downgrade cuNNN to 7 or earlier?

**Comment by SauROnmiKE** [comment]
Works fine with Cuda 9 and cuDNN 7.3

**Comment by yitelee** [comment]
Cuda 9.0 worked, but Cuda 9.2 didn't, complained about no "nvrtc64_70.dll" was found. Maybe nvrtc64_90.dll is the highest working version.
