### ISSUE TITLE
Update `config.gpuarray.sched` docs with CU_CTX_SCHED_BLOCKING_SYNC

### ISSUE THREAD

**Issue by i3v** [Theano/Theano#6677]
AFAIU, libgpuarray is using `cudaDeviceScheduleBlockingSync` instead of `CudaDeviceScheduleYield` [for a few releases already](https://github.com/Theano/libgpuarray/pull/448#event-1113418241) (see also: #5706). But docs still [say](https://github.com/Theano/Theano/blob/b37f333bd15d404dbb5eb4617eb176d61f63dbd1/doc/library/config.txt#L484-L485) `using "multi" mean using the parameter cudaDeviceScheduleYield`.  Maybe, those last single word should be replaced?

**Comment by nouiz** [comment]
Do you want to send a PR?
Your name will stay in the code history of Theano.
