### ISSUE TITLE
How to install theano 0.11

### ISSUE THREAD

**Issue by amruta24** [Theano/Theano#6701]
If you have any questions on Theano, please ask your questions in either [theano-user mailing list](https://groups.google.com/forum/#!forum/theano-users) or [stackoverflow](http://stackoverflow.com/) with the "theano" tag.

Use issue only to report bugs or to ask for new features in Theano.

Before reporting a bug, update to Theano development version. Maybe it
is already fixed. If not, tell us the Theano flags and Theano version
that generate the problem. If it is a regression, can do a "git
bisect" to idenfy when the problem appeard. This really help fix it
rapidly.

If you add a feature request, describe in which case it will be useful.

**Comment by rpgoldman** [comment]
Is there any reason this should not be closed?

**Comment by nouiz** [comment]
No reason. Thanks.
For the original questions, we do not recommand installing old Theano version. normally you just need to follow the normal Theano installatation at: http://deeplearning.net/software/theano/install.html

and add "==0.11" or "=0.11" after "theano" on the installation line to specify the version.

**Comment by rpgoldman** [comment]
If I get a chance, I'll pass over these and suggest others as outdated.
