### ISSUE TITLE
several nosetest fail

### ISSUE THREAD

**Issue by mslacken** [Theano/Theano#6719]
When packaging theano for openSUSE Tumleweed, follwoing nosetets (functions or classes fail):
  * theano/gof/tests/test_compute_test_value.py:
   class TestComputeTestValue
  * theano/sandbox/tests/test_rng_mrg.py:
   def test_uniform() (endless loop)
  * theano/sparse/tests/test_basic.py:
    class SparseInferShapeTester
    def test_csm
    class test_csm
    class Remove0Tester
  * theano/tensor/signal/tests/test_pool.py:
    class TestDownsampleFactorMax
    ClipTester
  * theano/tensor/tests/test_raw_random.py
    def test_vector_arguments
  * theano/tensor/tests/test_shared_randomstreams.py
    class T_SharedRandomStreams
  * tests/test_var.py b/theano/tensor/tests/test_var.py
    def test_numpy_method

**Comment by nouiz** [comment]
Theano isn't actively maintained now. So do not expect fast answer. We need the full error message to be able to help. ALso make sure to use the master branch and not the last release. It contain a few fixes for more recent version of some dependencies. This could be the kind of error you see.

**Comment by nouiz** [comment]
Theano isn't actively maintained now. So do not expect fast answer. We need the full error message to be able to help. ALso make sure to use the master branch and not the last release. It contain a few fixes for more recent version of some dependencies. This could be the kind of error you see.

**Comment by rebecca-palmer** [comment]
Debian has [most of these](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955471) but not the test_uniform() hang.  Does the fix in #6749 help?

**Comment by nouiz** [comment]
#6749 is merged. So I'll suppose your issues is fixed and will close this issues. If not, do not hesitate to reopen.
