### ISSUE TITLE
Pass the theano-gpu-test, but still have problems with gpuarray  when running.

### ISSUE THREAD

**Issue by morantumi** [Theano/Theano#6730]
I use `theano=1.0.2` and `pygpu=0.7.6` and I can pass the theano-test-gpu
![image](https://user-images.githubusercontent.com/46220439/68739322-84cef880-0623-11ea-9b7d-95b7f05ac14b.png)
However, when I run rllab program (based on theano), I have the following bad result. 
![image](https://user-images.githubusercontent.com/46220439/68739441-c8296700-0623-11ea-8b47-4bf222edde68.png)
I am not sure which part is wrong. I read this website and I can not deal with this problem. Call for your help. Thank you.

**Comment by IveJ** [comment]
Hi Issuer,

check: http://deeplearning.net/software/theano/tutorial/using_gpu.html

**Comment by nouiz** [comment]
Are you sure the same version of Theano is used in the shell and in rllab?
You can execute that do see which folder is Theano:
import theano; print(theano.__file__)

**Comment by morantumi** [comment]
I can check with the guide of the  website. The result show that I am using the GPU but when I run the program in rllab, something is still  wrong.....
I run `import theano; print(theano.__file__)` , the result is as follow
/home/chenyang/anaconda2/envs/tf/lib/python3.5/site-packages/theano/__init__.py

**Comment by morantumi** [comment]
I find that the inner program  set the THEANO_FLAGS='gpu',  I change it to cuda and this problem is ok. However, I have a new problem is that 
`RuntimeError: You can't initialize the GPU in a subprocess if the parent process already did it` 
It seems that there is few answer about it on the website. could you give me some advice? Thank you very much.

**Comment by morantumi** [comment]
I solved the problem. Only use theano-gpu in subprocess can solve it. Thank you very much.
