### ISSUE TITLE
While Exceting some codes this shows as error, any help

### ISSUE THREAD

**Issue by munavircp** [Theano/Theano#6752]
While reading from '/home/firoz/.theanorc' [line  6]: section 'blas' already exists

i actually followed instructions from 
http://deeplearning.net/software/theano_versions/0.8.X/install_ubuntu.html

At last 

 remove openblas if you installed it
sudo apt-get remove libopenblas-base
# Download the development version of OpenBLAS
git clone git://github.com/xianyi/OpenBLAS
cd OpenBLAS
make FC=gfortran
sudo make PREFIX=/usr/local/ install
# Tell Theano to use OpenBLAS.
# This works only for the current user.
# Each Theano user on that computer should run that line.
echo -e "\n[blas]\nldflags = -lopenblas\n" >> ~/.theanorc

i think the last line done some thing

**Comment by nouiz** [comment]
Open the file /home/firoz/.theanorc 
And remove duplicate sections.
The echo command always append to that file. So if you ran it many times, it would be duplicated.
