### ISSUE TITLE
Theano releases are missing scan_perform.c

### ISSUE THREAD

**Issue by ericruleman** [Theano/Theano#6753]
I downloaded Theano 1.0.4 for MacOs 10.15 using Anaconda as described here: http://deeplearning.net/software/theano/install_macos.html

When attempting to run a Python program that requires Theano, the program would error out with the message:

> 76: UserWarning: The file scan_perform.c is not available. This donot happen normally. You are probably in a strangesetup. This mean Theano can not use the cython code for scan. If youwant to remove this warning, use the Theano flag'cxx=' (set to an empty string) to disable all ccode generation.

I had to do the fix recommended here: https://stackoverflow.com/questions/53423610/how-to-update-scan-cython-code-in-theano

Basically, Theano 1.0.4 is missing the scan_perform.c file.

**Comment by QCaudron** [comment]
I am seeing the same behaviour.

**Comment by twiecki** [comment]
Did you install using conda or pip? from the conda-forge channel or the default one?

**Comment by QCaudron** [comment]
I can't remember for sure, my apologies. I am fairly certain I installed
`pymc3` from conda's default channel.

The fix of manually downloading the file into site-packages worked for me,
but of course it's not ideal ;)

**Comment by twiecki** [comment]
I think this is an anaconda packaging problem.

**Comment by twiecki** [comment]
What would help is if someone with that problem could check whether it also occurs with the conda-forge package:
`conda install -C conda-forge theano`

**Comment by angeloruggieridj** [comment]
I've tried to copy scan_perform.c file in _C:\Users\<username>\Anaconda3\Lib\site-packages\theano\scan_module_ and now the error is gone.
But when I restart the kernel, JupyterLab gives this error:
```
Server Connection Error
A connection to the Jupyter server could not be established. JupyterLab will continue trying to reconnect. Check your network connection or Jupyter server configuration.
```

**Comment by twiecki** [comment]
That's unrelated.

**Comment by m-dodd** [comment]
> What would help is if someone with that problem could check whether it also occurs with the conda-forge package:
> `conda install -C conda-forge theano`

I did this and it fixed the error after restarting my kernel in Jupyter.
