### ISSUE TITLE
'DisconnectedType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by SouthAmericaB** [Theano/Theano#6774]
Hi!
I'm having this error in gradient.py file:

![image](https://user-images.githubusercontent.com/49905756/116068196-42b83c00-a68a-11eb-805a-1e49cdefb91d.png)
Could you help me to solve it please?

Thank you very much in advance :)

**Comment by twiecki** [comment]
This project is abandoned, try https://github.com/pymc-devs/aesara.
