### ISSUE TITLE
cutils fails when cutils_ext already present elsewhere in sys.path

### ISSUE THREAD

**Issue by usaar33** [Theano/Theano#728]
EDIT: Now it work with the c|py linker, but not with the cvm linker.

Theano's cutils moudle expects to find cutils_ext inside config.compiledir.

In cutils.py, cutils_ext.cutils_ext will be loaded.  On an import error, this extension will be built and eventually cmodule.dlimport will re-import cutils_ext.cutils_ext.  dlimport will inject config.compiledir into the front of sys,path, so the cutils_ext should always be loaded from config.compiledir.

Normally, this will then allow cutils_ext.cutils_ext to be loaded.  The problem is if the cutils_ext package was found elsewhere on sys.path, but not the cutils_ext module (extension) within that package.  cutils.py lacks the sys.path injection of dlimport.  The consequence is that the import of cutils_ext.cutils_ext in dlimport fails because the reference to the outer cutils_ext (the package) will be the incorrect path!

Needless to say, when a user encounters this bug, it is a pain to solve.

The solution is to ensure that the cutils.py try statement starts with:

sys.path.insert(0,theano.config.compiledir)
with the finally doing:
del sys.path[0]

**Comment by nouiz** [comment]
As this is from 2012 and we don't have news of user of PiCloud, I will close this issue. If someone still have problems with PiCloud, then open a new issue.
