### ISSUE TITLE
DebugMode verify that inplace op check the writable flags of ndarray before reusing them

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#734]
Also, verify that we check this flag for the preallocated output. Normally, it should not happen for output, but this could happen for inplace input if we start doing strange thing with strades.

See meaing list thread "[theano-dev] potential bug when using window view with Theano"

**Comment by abergeron** [comment]
We don't really want to check this since all the memory ops should see is internal to Theano. You may be able to cause problems with abuse of `borrow` in various places, but then it's the user's problem.
