### ISSUE TITLE
All Release: buildbot on a computer without g++

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#765]
Theano should continue to work in that case.

Intermediate, we can just test this before the release.

**Comment by nouiz** [comment]
@slefrancois we want to add a VM without a compilator to jenkins.

**Comment by slefrancois** [comment]
We now have a jenkins job running on a VM, see an example run [here](http://darjeeling.iro.umontreal.ca:8080/job/Theano_nogpp/7/testReport/). The errors it returns are almost all missing performs or compiler unavailable, except one [assertion error in test_scan](http://darjeeling.iro.umontreal.ca:8080/job/Theano_nogpp/7/testReport/theano.gof.tests.test_compute_test_value/TestComputeTestValue/test_scan_err2/).

**Comment by slefrancois** [comment]
Another things is that the python implementation of the random number generator in sandbox.rng_mrg is slow, so [these test](http://darjeeling.iro.umontreal.ca:8080/job/Theano_nogpp/7/testReport/theano.sandbox.tests/test_rng_mrg/) take 1h30 mins alone.

**Comment by nouiz** [comment]
ok, I'm working on fixing those tests.

On Tue, Nov 29, 2016 at 10:04 AM, Simon Lefrancois <notifications@github.com

**Comment by nouiz** [comment]
https://github.com/Theano/Theano/pull/5300
