### ISSUE TITLE
Cuda should raise MemoryError

### ISSUE THREAD

**Issue by jaberg** [Theano/Theano#809]
Cuda code should raise custom MemoryError, rather than RuntimeError.

See e.g. 
http://docs.python.org/c-api/exceptions.html#PyErr_NewException

- use it instead of RuntimeError where appropriate
- add it to the cuda_ndarray module symbol table

**Comment by abergeron** [comment]
This is not really required since MemoryError is handled specially because it is used in out of CPU memory error.

Also this would be in the old backend and we won't add new features.
