### ISSUE TITLE
Elemwise tester should test uint* dtype.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#850]
There was a bug recently found that those op output was not upcasted to float\* when needed!

**Comment by benathi** [comment]
Could you elaborate the issue further? From what I infer, some element-wise operations are supposed to cast the output to float* but they currently don't do that so it's an issue for some uint* input? If I understand correctly, what operations are these? For example,I looked at the test_elemwise.py and test_prod_without_zeros function; I modified the input with dtype=uint32. The output elements seem to be of type float64 . (which is the desirable behavior I presume)

I'm quite a beginner for theano so appreciate any additional clarifications are appreciated.

**Comment by nouiz** [comment]
The ticket is about adding tests for uint* dtype for elemwise. The tests are done in part with a test generator in the file: theano/tensor/tests/test_basic.py

For example, grep for "AddTester". If you have any questions, do not hesitate.

**Comment by benathi** [comment]
So the ticket is to create more tests like 'AddTester' or for other element wise operators but for input being array of type uint*? Is this correct?

**Comment by nouiz** [comment]
Yes. Just to be sure, do not create new AddTester, add other dtype test
case in the existing one.

**Comment by nouiz** [comment]
In dict of tensor/tests/test_basic.py in dict like _good_broadcast_binary_normal and a new key uint that would test for uint16
