### ISSUE TITLE
opt: deg2rad(rad2deg(x)) -> x and rad2deg(deg2rad(x)) -> x

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#864]

**Comment by clorenz7** [comment]
https://github.com/Theano/Theano/pull/2760

**Comment by nouiz** [comment]
done in gh-2760

Also cover those case:
+ (basic.Deg2Rad, basic.Rad2Deg),
+ (basic.Cosh, basic.ArcCosh),
+ (basic.Tanh, basic.ArcTanh),
+ (basic.Sinh, basic.ArcSinh),
+ (basic.Conj, basic.Conj),
+ (basic.Neg, basic.Neg),
+ (basic.Inv, basic.Inv),
