### ISSUE TITLE
Make an optimization to remove cast from graph

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#949]
import theano
v=theano.tensor.bvector()
f=theano.function([v], v.astype('int32').astype('int8'))
f.maker.fgraph.toposort()
[Elemwise{Composite{[Cast{int8}(Cast{int32}(i0))]}}(<TensorType(int8, vector)>)]

in the opt local_cast_cast in file tensor/opt.py

**Comment by kahnchana** [comment]
Can you explain what needs to be done a bit more? I'd like to work on this.

**Comment by nouiz** [comment]
Thanks for wanting to contribute. The code will be simple, but the difficult part is in the correct analysis. Mostly, for the code, it is to expect the function local_cast_cast() in the file tensor/opt.py to cover more cases. The difficult part is to determine which cases we can support. Currently, we only remove the first cast, when both cast are of the same dtype.

One extra cases I know that can be done is if the original dtype is int8, then the first cast is an upcast, then we have another cast (no constraint on what), then we can remove the first cast.

v=vector(dtype='int8').cast('int16').cast(any_dtype), we can remove the cast to int16 as it is an upcast.

But

v=vector(dtype='int16').cast('int8').cast(any_dtype) we can't remove the first cast, as it round the first values. Maybe the user wanted this.

**Comment by vikramnitin9** [comment]
Hi,
I'm new to the Theano codebase. I've submitted a pull request for the above issue at #5665. @nouiz.
