### ISSUE TITLE
Refactor Flatten, missing opt?

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#950]
We have the Flatten op. Why do we need it? We could reuse the reshape op. Having less op make the optimization easier.

We can reuse reshape(-1), this won't introduce bigger or uglier graph

TODO:
- [ ] Comment the Flatten op and use reshape(-1) where needed.
- [ ] Check optimization that would check for flatten, update them to check for the old Flatten and the new pattern. Maybe refactor this into a method?
- [ ] The user flatten interface should stay and should introduce reshape(-1)
- [ ] Then uncomment the Flatten op, change its description to tell it is deprecated (needed to unpickle old graph).

**Comment by nouiz** [comment]
Just to node, I updated the description to tell more detail on what is needed at the end of the description

**Comment by lamblin** [comment]
I believe this is closed by #3480, let's re-open it if something is missing.
